### ISSUE TITLE
can't open index.php

### ISSUE THREAD

**Issue by aporzio1** [causefx/Organizr#1]
I have it installed but when I try to open the index.php i get this error in my browser.

`Fatal error: Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [14] unable to open database file' in /Library/Server/Web/Data/Sites/Organizr/user.php:153 Stack trace: #0 /Library/Server/Web/Data/Sites/Organizr/user.php(153): PDO->__construct('sqlite:../users...') #1 /Library/Server/Web/Data/Sites/Organizr/index.php(17): User->__construct('registration_ca...') #2 {main} thrown in /Library/Server/Web/Data/Sites/Organizr/user.php on line 153`

**Comment by causefx** [comment]
You need SQLite, try to uncomment the php_sqlite extension in php.ini file and point it to the right directory

**Comment by aporzio1** [comment]
I have it uncommented, but what do you mean by point it to the directory? is that in the php.ini or in the  Organizr directory?

**Comment by causefx** [comment]
`<?php

function check($extension) {
    
    if (extension_loaded($extension)) :
    
        echo $extension . " is installed.  Good to go there!<br><br>";    
    
    else :
    
        echo $extension . " is NOT installed.  Please install it before proceeding!<br><br>";
    
    endif;  
    
}

function getFilePermission($file) {
        
    if (file_exists($file)) :
    
        $length = strlen(decoct(fileperms($file)))-3;
    
        if($file{strlen($file)-1}=='/') :

            $name = "Folder";

        else :

            $name = "File";

        endif;
    
        echo $name . ": " . $file . " - Permissions: " . substr(decoct(fileperms($file)),$length) . "<br>";

        if (is_writable($file)) :

            echo "The file is writable<br><br>";

        else :

            echo "The file is not writable<br><br>";

        endif;
        
    endif;
}
echo "CHECK PERMISSIONS:<br><br>";

$db = "../users.db";
$folder = "../users/";
$root = "../";

check("PDO_SQLITE");
check("PDO");

getFilePermission($root);
getFilePermission($db);
getFilePermission($folder);

?>`

can you put that inside a new php file and run it please?  let me know what the output is.

**Comment by aporzio1** [comment]
`CHECK PERMISSIONS: PDO_SQLITE is installed. Good to go there!

PDO is installed. Good to go there!

Folder: ../ - Permissions: 775
The file is not writable

**Comment by causefx** [comment]
Perfect, that's a good sign, can you tell me what the folder structure looks likes?  What OS are you on?

**Comment by aporzio1** [comment]
It is on MacOS 10.11.6.

/Library/Server/Web/Data/Sites/Organizr

**Comment by causefx** [comment]
make the permissions on Sites 777.

**Comment by aporzio1** [comment]
that did it. Thank you

**Comment by causefx** [comment]
:) awesome!
