### ISSUE TITLE
0.99991

### ISSUE THREAD

**Issue by Hakker** [causefx/Organizr#100]
Notice: Undefined index: loading in /var/www/dashboard/index.php on line 246

Notice: Undefined index: hovertext in /var/www/dashboard/index.php on line 247

happend after auto update

**Comment by causefx** [comment]
goto updatedb.php, next goto settings tab and save your colors.

**Comment by Hakker** [comment]
well that works. Maybe I missed the updatedb.php part.

**Comment by causefx** [comment]
no worries.
