### ISSUE TITLE
Plex share invite placeholder

### ISSUE THREAD

**Issue by lockntross** [causefx/Organizr#1000]
###### Branch: Develop
<hr>

##### Problem Description:
invites.js 
on line 363:
placeholder="Plex Username" is confusing. 
No one I sent this to knew what to do. They're used to logging in with their email addresses. 
It was a show stopper for a few folks. 
If you would change the label:
placeholder="Plex Account Email Address"

Then the invite emails to current Plex accounts will go so much smoother (at least for my invites).
Thanks!
<hr>

**Comment by si0972** [comment]
"Plex user" is the correct term. Plex allows logins with both username and email, in many cases the username is the email.

**Comment by lockntross** [comment]
You are correct. 
But consider you know Plex backwards and forwards. 
I'm speaking from the perspective of my Grandmother on Christmas when I had out invites.

**Constancy breeds usability.** 
Throughout the Organizr/Ombi/Plex setup the prompts read: 
"CONTINUE WITH EMAIL": [https://i.imgur.com/hhZuKq5.png](https://i.imgur.com/hhZuKq5.png)
and then 
"EMAIL OR USERNAME - EMAIL ADDRESS IS REQUIRED": [https://i.imgur.com/aGZaZQs.png](https://i.imgur.com/aGZaZQs.png)
It seems that Plex's, the initial registration, asks for email as often or more often than username.
Someone whose never used Plex before and just signed up, this process is very foreign. 

It would be best if the dialog read the same instructions the entire time. And as the Plex.tv prompt tells us: "EMAIL OR USERNAME"

Would a change to "Plex Username or Email" be acceptable, it would end the future phone calls I'm expecting and create a more uniform invite process using the same vernacular as the Plex invite.

**Comment by causefx** [comment]
Yeah I can change to to plex username or email.  Plex used to be username until they added SSO with FB and Google which they ended up changing username to email.  Which we all hated... then we let Plex know that they should change filed or notes about being able to use Username or EMail, which they did but only as notes.
