### ISSUE TITLE
Ping always showing as failed

### ISSUE THREAD

**Issue by unabatedshagie** [causefx/Organizr#1001]
###### Operating System: Windows
<hr>

##### Problem Description:
For the life of me I don't seem to be able to get the ping functionality to work, Organizr always shows a red dot next to Sonarr, Radarr, Lidarr etc.

I've tried 127.0.0.1:8989, 192.168.x.x:8989, {my no-ip hostname}:8989 and {myStaticIP}:8989

All four of these addresses return a negative on the ping. I'm not sure what other addresses I can try to get this to work.

It's not a massive issue, it's just bugging me that I can't get it to work.

**Comment by causefx** [comment]
you have to enable the ping time. 

the diff in v2 is there is no more green dot when online. only red when offline. 

try enabling ping time in settings.

**Comment by causefx** [comment]
![image](https://user-images.githubusercontent.com/16184466/49948211-3adc1080-feb0-11e8-8c46-5106faafc23c.png)

**Comment by unabatedshagie** [comment]
Okay, slightly confusing but I've got it working now, thanks.

**Comment by causefx** [comment]
yeah i wanted to give the user the choice of how it works and if they want response times. i may add an option to add online indicators.
