### ISSUE TITLE
LDAP groups?

### ISSUE THREAD

**Issue by Fug1** [causefx/Organizr#1003]
###### Operating System: Ubuntu 16.04
<hr>

##### Problem Description:
I'm able to connect Organizr to my LDAP server using the DN format cn=%s,ou=users,dc=mydomain,dc=com. This works well, but it means that anyone with an account in LDAP can log in to Organizr. It would be preferable if I could set up a group filter using the member-of-overlap function in LDAP, such as memberOf=cn=organizr,ou=groups,dc=mydomain,dc=com. 

I'm not very good with LDAP, so I'm not sure if this is the ideal way to go about it, but that seems to be the way it's handled in NextCloud (https://docs.nextcloud.com/server/stable/admin_manual/configuration_user/user_auth_ldap.html?highlight=ldap).

<hr>

**Comment by causefx** [comment]
try with todays commits

**Comment by seanbaker74** [comment]
I tried to update to the latest through the UI, but it looks like the update failed. I've restarted a couple of times but I'm just getting a blank page.

This is the error in nginx.log:

`2019/02/28` 15:03:02 [error] 316#316: *7 FastCGI sent in stderr: "PHP message: PHP Warning:  Class 'Tightenco\Collect\Support\Arr' not found in /var/www/organizr.local/html/api/vendor/tightenco/collect/src/Collect/Support/alias.php on line 16
PHP message: PHP Parse error:  syntax error, unexpected '=' in /var/www/organizr.local/html/api/vendor/tightenco/collect/src/Collect/Support/Arr.php on line 388" while reading response header from upstream, client: 192.168.15.13, server: organizr.localdomain, request: "GET /api/?v1/launch_organizr HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.0-fpm.sock:", host: "organizr.localdomain", referrer: "http://organizr.localdomain/"`

**Comment by causefx** [comment]
seems as if all files didnt unzip.

https://github.com/causefx/Organizr/archive/v2-develop.zip

download that zip and overwrite

**Comment by seanbaker74** [comment]
Okay, I did that but I'm getting the same error.

I double-checked that the files 
at /var/www/organizr.local/html/api/vendor/tightenco/collect/src/Collect/Support/alias.php and Arr.php match the ones in the zip file.

Same errors in the nginx error.log.

**Comment by causefx** [comment]
what version of php?

**Comment by seanbaker74** [comment]
7.0.32-0ubuntu0.16.04.1

**Comment by causefx** [comment]
can you please update to a minimum of 7.1.3?   I believe that will fix it.

Edit, sorry for the inconvenience

**Comment by seanbaker74** [comment]
Okay, I updated to 7.2.15-1+ubuntu16.04.1+deb.sury.org+1

Still seeing the same problem

The error log entry makes me think it's still using the 7.0 version of php. Is there a setting somewhere to get it to use 7.2?

`2019/02/28 16:42:26 [error] 342#342: *17 FastCGI sent in stderr: "PHP message: PHP Warning:  Class 'Tightenco\Collect\Support\Arr' not found in /var/www/organizr.local/html/api/vendor/tightenco/collect/src/Collect/Support/alias.php on line 16
PHP message: PHP Parse error:  syntax error, unexpected '=' in /var/www/organizr.local/html/api/vendor/tightenco/collect/src/Collect/Support/Arr.php on line 388" while reading response header from upstream, client: 192.168.15.13, server: organizr.localdomain, request: "GET /api/?v1/launch_organizr HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.0-fpm.sock:", host: "organizr.localdomain", referrer: "http://organizr.localdomain/"`

**Comment by causefx** [comment]
correct, you need to edit the sock location in your webserver

`fastcgi://unix:/run/php/php7.0-fpm.sock`

it will be maybe 7.1

**Comment by seanbaker74** [comment]
Okay, I didn't have a 7.2 socket in /run/php. I had to `apt-get install php7.2-fpm`, then set `fastcgi_pass unix:/run/php/php7.2-fpm.sock;` in nginx's phpblock.conf.

Organizr comes up now, but it's saying I'm missing dependencies for PDO_SQLITE and SQLITE3.

**Comment by causefx** [comment]
ok, now just install those.... 

i think `apt-get install php7.2-sqlite3`

**Comment by seanbaker74** [comment]
Okay, all good now! Thanks for your patience, I really appreciate it.

I'll do some testing on LDAP, but probably won't be able to get to it until tomorrow. I'll update you then.

**Comment by causefx** [comment]
no worries, Thank you :)

I did some testing on openLDAP and AD... both worked well... either way open this issue back up if it doesnt work.

**Comment by seanbaker74** [comment]
Okay, I'm trying to get this set up but I'm not doing something right.

Where do I specify the group filter? I currently have a group called 'organizr' that contains the users who should be able to access organizr.

Organizr settings:

Host Base DN: cn=%s,ou=users,dc=mydomain,dc=com
Account Prefix: cn=
Account Suffix: (&(memberOf=cn=organizr,ou=groups,dc=mydomain,dc=com))

**Comment by seanbaker74** [comment]
I'm not able to re-open this issue. Not sure if @causefx will see responses to this issue if it's closed.

**Comment by causefx** [comment]
Sorry I had been busy with the release.

are you using OpenLDAP or AD?

**Comment by seanbaker74** [comment]
Oh, no problem at all. I just wasn't sure if you would see the response since the issue is closed.

I'm using OpenLDAP.

**Comment by causefx** [comment]
try this:
Account Prefix: `uid=`
Account Suffix: `,cn=organizr,ou=groups,dc=mydomain,dc=com`
if that doesn't work try this:
Account Suffix: `,(&(memberOf=cn=organizr,ou=groups,dc=mydomain,dc=com))`

Either way the suffix needs to start with comma.... pay attn to the accoutn bind on the bottom

**Comment by seanbaker74** [comment]
With Account Suffix: `,cn=organizr,ou=groups,dc=mydomain,dc=com`
I'm getting LDAP error 49

with Account Suffix: `,(&(memberOf=cn=organizr,ou=groups,dc=mydomain,dc=com))`
I'm getting LDAP error 34 (invalid DN)

I've tried with Prefix cn= and uid=

**Comment by causefx** [comment]
is there data with that error 49?

**Comment by seanbaker74** [comment]
Nothing useful, no...

`[06-03-2019 15:33:24] slapd debug  conn=44201 fd=23 ACCEPT from IP=192.168.15.68:46756 (IP=0.0.0.0:389)`
`[06-03-2019 15:33:24] slapd debug  conn=44201 op=0 BIND dn="cn=ldap-bind,ou=users,dc=mydomain,dc=com" method=128`
`[06-03-2019 15:33:24] slapd debug  conn=44201 op=0 BIND dn="cn=ldap-bind,ou=users,dc=mydomain,dc=com" mech=SIMPLE ssf=0`
`[06-03-2019 15:33:24] slapd debug  conn=44201 op=0 RESULT tag=97 err=0 text=`
`[06-03-2019 15:33:24] slapd debug  conn=44201 op=1 BIND anonymous mech=implicit ssf=0`
`[06-03-2019 15:33:24] slapd debug  conn=44201 op=1 BIND dn="uid=testuser,cn=organizr,ou=groups,dc=mydomain,dc=com" method=128`
`[06-03-2019 15:33:24] slapd debug  conn=44201 op=1 RESULT tag=97 err=49 text=`
`[06-03-2019 15:33:24] slapd debug  conn=44201 op=2 BIND dn="cn=ldap-bind,ou=users,dc=mydomain,dc=com" method=128`
`[06-03-2019 15:33:24] slapd debug  conn=44201 op=2 BIND dn="cn=ldap-bind,ou=users,dc=mydomain,dc=com" mech=SIMPLE ssf=0`
`[06-03-2019 15:33:24] slapd debug  conn=44201 op=2 RESULT tag=97 err=0 text=`
`[06-03-2019 15:33:24] slapd debug  conn=44201 op=3 UNBIND`
`[06-03-2019 15:33:24] slapd debug  conn=44201 fd=23 closed`

**Comment by seanbaker74** [comment]
@causefx, do you have a configuration example that works with openldap on your end?

I was just looking at the ldap logs when I log into nextcloud, which employs a filter to specify the ldap group. Here's the relevant log entry:

`[20-03-2019 06:41:46] slapd debug  conn=1345 fd=23 ACCEPT from IP=192.168.15.76:51966 (IP=0.0.0.0:636)
[20-03-2019 06:41:46] slapd debug  conn=1345 fd=23 TLS established tls_ssf=128 ssf=128
[20-03-2019 06:41:46] slapd debug  conn=1345 op=0 BIND dn="cn=ldap-bind-with-password-change,ou=users,dc=mydomain,dc=com" method=128
[20-03-2019 06:41:46] slapd debug  conn=1345 op=0 BIND dn="cn=ldap-bind-with-password-change,ou=users,dc=mydomain,dc=com" mech=SIMPLE ssf=0
[20-03-2019 06:41:46] slapd debug  conn=1345 op=0 RESULT tag=97 err=0 text=
[20-03-2019 06:41:46] slapd debug  conn=1345 op=1 SRCH base="ou=users,dc=mydomain,dc=com" scope=2 deref=0 filter="(&(&(memberOf=cn=nextcloud,ou=groups,dc=mydomain,dc=com))(uid=testuser))"
[20-03-2019 06:41:46] slapd debug  conn=1345 op=1 SRCH attr=entryuuid nsuniqueid objectguid guid ipauniqueid dn uid samaccountname memberof mail displayname jpegphoto thumbnailphoto
[20-03-2019 06:41:46] slapd debug  <= mdb_equality_candidates: (memberOf) not indexed
[20-03-2019 06:41:46] slapd debug  conn=1345 op=1 SEARCH RESULT tag=101 err=0 nentries=1 text=
[20-03-2019 06:41:46] slapd debug  conn=1346 fd=24 ACCEPT from IP=192.168.15.76:51968 (IP=0.0.0.0:636)
[20-03-2019 06:41:46] slapd debug  conn=1346 fd=24 TLS established tls_ssf=128 ssf=128
[20-03-2019 06:41:46] slapd debug  conn=1346 op=0 BIND dn="cn=testuser,ou=users,dc=mydomain,dc=com" method=128
[20-03-2019 06:41:46] slapd debug  conn=1346 op=0 BIND dn="cn=testuser,ou=users,dc=mydomain,dc=com" mech=SIMPLE ssf=0
[20-03-2019 06:41:46] slapd debug  conn=1346 op=0 RESULT tag=97 err=0 text=
[20-03-2019 06:41:48] slapd debug  conn=1346 op=1 UNBIND
[20-03-2019 06:41:48] slapd debug  conn=1346 fd=24 closed
[20-03-2019 06:41:48] slapd debug  conn=1345 op=2 UNBIND
[20-03-2019 06:41:48] slapd debug  conn=1345 fd=23 closed`

**Comment by shokinn** [comment]
Hey There,
I'm also facing the issue that I can't login If I try to match a group membership.

This works:
Account Prefix: `cn=`
Account suffix: `,ou=users,dc=ldap,dc=example,dc=tld`

This not:
Account Prefix: `(&(cn=`
Account suffix: `,ou=users,dc=ldap,dc=example,dc=tld)(memberOf=cn=uws,ou=groups,dc=ldap,dc=example,dc=tld))`

In Emby the same DN works without any issues.

Any Ideas?

**Comment by nkoester** [comment]
@shokinn any chance you got it working? I am at the same crossroads: Known working DN do not work in organizr. I am also using openldap.

**Comment by shokinn** [comment]
Hey @nkoester,
nope I just gave up.
I use it now without group matching.
