### ISSUE TITLE
Custom HTML Tooltips Display Issue

### ISSUE THREAD

**Issue by christronyxyocum** [causefx/Organizr#1004]
###### Operating System: Ubuntu Server 18.04
<hr>

##### Problem Description:
Tooltips for the Custom HTML boxes seem to have an absolute position to the mouse cursor.

<hr>

##### Reproduction Steps:
Open Custom HTML box and cause an error or warning to be displayed and mouse over the corresponding error/warning box to view the tooltip.

<hr>

#### Errors on screen?  If so paste here:
N/A

Here's a GIF of the issue:

![2018-12-14_17-38-26 1](https://user-images.githubusercontent.com/22502007/50033619-3a826900-ffc7-11e8-8b4e-bdbc67461e10.gif)

**Comment by tronyx** [comment]
This is dumb, closing.
