### ISSUE TITLE
Ombi SSO stopped working

### ISSUE THREAD

**Issue by rix1337** [causefx/Organizr#1006]
###### Operating System: Docker
<hr>

##### Problem Description:

Ombi SSO has worked up until a few weeks ago with this version. I have not changed my nginx config since.
The api key is correct; Ombi homepage items are working.
<hr>

##### Reproduction Steps:

Have ombi SSO active for a month - it fails after a while. My db / debug log might help..
<hr>

`Results For cmd: activeInfo.settings.sso.ombi
{
	"enabled": true,
	"cookie": true,
	"url": true,
	"api": true
} `

#### Errors on screen?  If so paste here:

```
Login with Ombi / Plex shown on Ombi tab
```

**Comment by si0972** [comment]
Are you on the latest Ombi master?

**Comment by rix1337** [comment]
Hm, I thought my docker image would take care of that, but there seems to be an issue updating.. Ill resolve that first..

**Comment by regoras** [comment]
I can second this issue. After a cache/cookie clear, I lose the Ombi cookie in addition to the SSO not working, and it doesn't restore. Frustrating, since I just got it working a week ago.

**Comment by causefx** [comment]
i just tested on mine: 3.0.4049
```
{
	"enabled": true,
	"cookie": true,
	"url": true,
	"api": true
}
```

**Comment by christronyxyocum** [comment]
Working fine for me on 3.0.4061:

```
{
	"enabled": true,
	"cookie": true,
	"url": true,
	"api": true
}
```

**Comment by rix1337** [comment]
Seems like you are on a dev build.. ill try to update.

Latest master is not working (.4036)

**Comment by si0972** [comment]
https://hub.docker.com/r/lsiodev/ombi-preview for develop builds of ombi

**Comment by rix1337** [comment]
Same issue with the dev build. Any idea what else it could be? It worked before and I have neither changed my nginx conf, nor updated Organizr ...

**Comment by christronyxyocum** [comment]
All the more reason to believe it's an Ombi issue, but anything is possible. Have you tried logging all the way out of everything, restarting the services (at least both Nginx/Org and Ombi), and then try logging into Org and then seeing how Ombi behaves? If so, are there any errors in the browser console when you press `F12` and go to the console tab?

**Comment by causefx** [comment]
what is under ombi url?

**Comment by rix1337** [comment]
I have found out, how I broke it:
I did indeed change a thing. I named the Tab "Anfragen/Probleme" which is German for Requests/Problems

Renaming the tab to "Ombi" fixed it for me.

**Comment by causefx** [comment]
what the?  that shouldn’t effect it at all :|

**Comment by rix1337** [comment]
Could not believe it either, hence my "I did not change anything" attitude..
