### ISSUE TITLE
Pinging Plex Media Server on a local machine says it's up when it's down?

### ISSUE THREAD

**Issue by STaRDoGG** [causefx/Organizr#1007]
Using the latest version (1.80) when I enter in:

`192.168.0.123:32400` for the ping URL, and then shut Plex down on that machine as a test, the green icon still says it's "up". Looking at the live logs also show a 200 result.

Using Powershell `tnc 192.168.0.123 -port 32400` during that time correctly shows "WARNING: TCP connect to (192.168.0.123 : 32400) failed"

How come?

**Comment by christronyxyocum** [comment]
v1 isn’t developed or supported anymore. All time is now focused on v2. Please install the v2-develop branch or wait about one more week for v2-master to be up.

**Comment by STaRDoGG** [comment]
@christronyxyocum ok. I'm still new to Organizr and just grabbed the latest on the Releases page. Before I upgrade to version 2, if I just overwrite everything currently there in the 1.80 folder with the v2 stuff, will it screw anything up, or work fine as a direct drop in replacement? I just spent like 2 weeks fighting with Organizr and Caddy reverse proxies, lol.

**Comment by causefx** [comment]
Proxies will be fine as that is on the webserver.
