### ISSUE TITLE
Display issues with small resolutions

### ISSUE THREAD

**Issue by nemchik** [causefx/Organizr#1008]
###### Operating System: https://hub.docker.com/r/organizrtools/organizr-v2/ php-fpm tag
<hr>

##### Problem Description:
On devices with small resolutions (i'm not positive of the exact cutoff) some pages on have issues displaying. The first of which issues that I can reproduce on both my mobile (galaxy s6) using chrome, my desktop using chrome's emulated mobile mode (galaxy s5) is that the login screen is shifted to the left. This cuts off the left side of the screen and shows blank space on the right side. Desktop chrome emulating anything larger than galaxy s5 seems unaffected. I have cleared cache as well. I am loading the page from behind a reverse proxy for testing, but I can load the page directly if needed.

Extra Note, the iPhone 6/7/8 option in chrome's device toolbar indicate a resolution of 375x667 and DO NOT have this issue. The Galaxy S5 has a resolution of 360x640 and the iPhone 5/SE has a resolution of 320x568 and both of these DO have the issue.

I have another issue as well with the navigation being distorted after logging in but I can only reproduce it on my device and not in chrome's desktop emulating smaller resolutions. My wife's device which has a larger resolution does not have either of the two issues i'm having.

<hr>

##### Reproduction Steps:
On Desktop
* Logout of organizr
* Press f12 to open the browser console
* Enable the device toolbar (to display the page as if on mobile)
* Select Galaxy S5 or iPhone 5/SE
* Reload the page

On Mobile (note: this doesn't seem to affect devices with larger resolution)
* Logout of organizr
* Reload the page

<hr>

#### Errors on screen?  If so paste here:
![unknown](https://user-images.githubusercontent.com/725456/50175015-5df82d00-02c1-11e9-82a5-ab3c87c39497.png)

**Comment by nemchik** [comment]
![image](https://user-images.githubusercontent.com/725456/50175685-11adec80-02c3-11e9-8004-46e0005f7e68.png)
Here is iPhone 5/SE mode which seems even worse than Galaxy S5

**Comment by causefx** [comment]
i will check these out...

**Comment by gilbN** [comment]
@nemchik try and add 
```
.loginLogo {
    max-width: 100%;
}
```
In custom CSS.

Not sure if 100% is the best way to solve it though...

**Comment by nemchik** [comment]
That does seem to work @gilbN

**Comment by nemchik** [comment]
P.S. the `loginLogo` css fixes the issue on the login screen. There's another issue I've mentioned but haven't really gone into in this issue because I'm having a hard time reproducing it. The second issue isn't resolved by the `loginLogo` css. The second issue is distortion on the left side of the screen after logging in. I cannot reproduce this on desktop chrome in mobile mode, I only see this on my mobile. My wife's mobile (larger resolution) doesn't have the issue, so I'm thinking it might be resolution related as well. It's also possible that it's something to do with me having access to admin only links and homepage elements and others not having that same access so the things displayed would be different.

**Comment by gilbN** [comment]
> P.S. the `loginLogo` css fixes the issue on the login screen. There's another issue I've mentioned but haven't really gone into in this issue because I'm having a hard time reproducing it. The second issue isn't resolved by the `loginLogo` css. The second issue is distortion on the left side of the screen after logging in. I cannot reproduce this on desktop chrome in mobile mode, I only see this on my mobile. My wife's mobile (larger resolution) doesn't have the issue, so I'm thinking it might be resolution related as well. It's also possible that it's something to do with me having access to admin only links and homepage elements and others not having that same access so the things displayed would be different.

Does the distortion look like white jagged lines across the tab names ect?

**Comment by nemchik** [comment]
Also the "Login with plex account" button still cuts off the icon on the right side of the button even with the CSS fix in place. Maybe this could be shortened to just "Plex Login" ?

**Comment by nemchik** [comment]
> Does the distortion look like white jagged lines across the tab names ect?

Yes. Exactly.

**Comment by gilbN** [comment]
> Also the "Login with plex account" button still cuts off the icon on the right side of the button even with the CSS fix in place. Maybe this could be shortened to just "Plex Login" ?

another temp fix for you
```css
.login-box, .white-box>.btn-group-lg>.btn, .btn-lg {
    font-size: 17px;
}
```

**Comment by nemchik** [comment]
That new temp fix seems to resolve the distortion after logging in.

**Comment by gilbN** [comment]
![6e74672b-5d9e-4727-a9fc-3c77f6f3fc1f](https://user-images.githubusercontent.com/24592972/51043382-d7ccbf00-15be-11e9-9091-d51c4f95d94d.jpeg)
![f451b844-0aed-44b6-879f-8b6a77de4cf9](https://user-images.githubusercontent.com/24592972/51043383-d7ccbf00-15be-11e9-8775-d0e4341cef50.jpeg)
![5049c312-4294-4026-85b4-04cd0074455c](https://user-images.githubusercontent.com/24592972/51043384-d8655580-15be-11e9-85fe-7af96c85ba6e.jpeg)
![a33191af-d5f2-49b4-8ef0-156cd422dbb3](https://user-images.githubusercontent.com/24592972/51043385-d8655580-15be-11e9-9eac-99829ef9681e.jpeg)

**Comment by nemchik** [comment]
For me the distortion is worse than Gil's pictures, and it's not just with the menu open, and it's not only for tabs that are open. Also I'm seeing it on a Samsung Galaxy S6 running Android 7.0 using chrome 71.

**Comment by causefx** [comment]
has anyone still seen this?  i just tried again and dont see any issues..

**Comment by nemchik** [comment]
Right now i'm running `2.0.0-beta.980` from `v2-master` and I have removed all of the CSS fixes discussed here and on Discord and it seems like this issue is resolved.

**Comment by causefx** [comment]
:)
