### ISSUE TITLE
Errors after upgrade

### ISSUE THREAD

**Issue by Waseh** [causefx/Organizr#101]
Hey Causefx

After i upgraded to the newest version im getting breif errors on load and some graphical glitches causing the menu bar to look messed up.
Rolling back fixed the issues.

The errors im getting breifly before organizr loads are:
undefined index : loading in /my/organizr/folder/index.php on line 246
undefined index : hovertext in /my/organizr/folder/index.php on line 247

Trying a fresh install with settings restored from previous install gives the same error and graphical glitch

**Comment by Waseh** [comment]
I was being dense and missed the message about #upgrade - Never mind me!

**Comment by causefx** [comment]
no worries :)
