### ISSUE TITLE
Homepage blank

### ISSUE THREAD

**Issue by hackmonker** [causefx/Organizr#1010]
###### Operating System: Ubuntu server
<hr>

##### Problem Description:
Sorry if posting in wrong place but didn't know where else to go. i have a Complete Blank home page . Nothing on it. tried to put everything in the homepage setting but nothing appears. installing for the first time 

<hr>

##### Reproduction Steps:

1.Open organizr
2.Fill up the required Informations in homepage settings 
3.homepage still blank

![capture](https://user-images.githubusercontent.com/46002790/50251035-96565300-0408-11e9-8244-c40f45915769.PNG)

![capture2](https://user-images.githubusercontent.com/46002790/50251080-b4bc4e80-0408-11e9-8a7d-442edc124c45.PNG)

<hr>

#### Errors on screen?  If so paste here:

```


```

**Comment by christronyxyocum** [comment]
v1 is not really supported anymore and is no longer developed. If you're just getting started with Organizr I would highly suggest using the v2 Beta, which is VERY stable and a lot of user's daily drive. If you cloned the repository from GitHub you will need to specify the `v2-develop` branch.

**Comment by hackmonker** [comment]
Is the v2 available for docker?

**Comment by hackmonker** [comment]
Alright installed v2 but same thing 

here 
![capture3](https://user-images.githubusercontent.com/46002790/50271611-3b018080-045b-11e9-9388-aaa7a0716334.PNG)
![capture4](https://user-images.githubusercontent.com/46002790/50271617-418ff800-045b-11e9-86dd-0c34847ffab6.PNG)
![capture5](https://user-images.githubusercontent.com/46002790/50271624-481e6f80-045b-11e9-9e1d-b2958f64d92d.PNG)

what am i doing wrong?

**Comment by christronyxyocum** [comment]
v2 is available for Docker with the `organizrtools/organizr-v2:php-fpm` image. What was the solution to your issue in case it will help someone else in the future?

**Comment by mthax** [comment]
I have exactly the same Problem, everything working fine and fast, but Homepage displays nothing.

One thing i noticed is

`DevTools failed to load source map: Could not load content for https://organizer.xyz.com/js/tinycolor.min.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE`

**Comment by tronyx** [comment]
@mthax Please do not comment on an issue that is three years old and closed. Many things have changed since then.

Please open a new issue.

**Comment by HalianElf** [comment]
So you pick a 3 year old, closed issue to comment on? Should either come into Discord where we can help you live (considering this looks like a configuration issue on your side and not a bug) or make your own issue.

But as for that error, it means nothing, it's a DevTools thing.
