### ISSUE TITLE
Ombi

### ISSUE THREAD

**Issue by lastj1405** [causefx/Organizr#1012]
###### Operating System: Windows
<hr>

##### Problem Description:
Unsure my version, i installed from owi installer

Hi I am pretty new at this but I have Organizr working with Sonarr/Radarr/and Jacket.

I am trying to get ombi going and I can see requests on home page but when i go to my ombi tab I logged in, orange load bar goes at top and i have no GUI after that, ive tried my ip:port  ip:port/ombi
and both yield same results.

Thank you for any help

<hr>

##### Reproduction Steps:

<hr>

#### Errors on screen?  If so paste here:

```

```

**Comment by si0972** [comment]
Have you set a base-url in Ombi?

**Comment by lastj1405** [comment]
Yes I have it as /ombi, it works on my homepage tab just not on its own tab. Loads up then just black screen

**Comment by lastj1405** [comment]
none.

**Comment by causefx** [comment]
This is a reverse proxy issue, please jump on discord to get ya sorted out.
