### ISSUE TITLE
Can't run under Libreelec because it needs root

### ISSUE THREAD

**Issue by louisefindlay23** [causefx/Organizr#1013]
###### Operating System: Libreelec - Docker
<hr>

##### Problem Description:

I can't use Organizr on the docker host Libreelec because I can only use the root user and Organizr doesn't support that
<hr>

##### Reproduction Steps:

Run the Organizr container under the root user
<hr>

#### Errors on screen?  If so paste here:

```

```

**Comment by si0972** [comment]
This is not a organir issue, by default PHP wont run under root (because of all the typical issues running as root brings to the table.)
