### ISSUE TITLE
Login fails using Plex oAuth

### ISSUE THREAD

**Issue by kimsbrian** [causefx/Organizr#1014]
###### Operating System: Ubuntu
<hr>

##### Problem Description:

Plex oAuth for users other than admin fails. Users are prompted to login with their Plex credentials but after signing in, are given an error "Login error - Wrong username/email/password combo". At the same time, it also says oAuth was successful but users remain on the same login page.
<hr>

##### Reproduction Steps:

Set up Organizr using Plex admin data. Username on Organizr is the same on Plex. Under authentication, use Organizr DB + Plex backend and fill in the fields. Switch Enable Plex oAuth to on.
<hr>

#### Errors on screen?  If so paste here:

```
On the login page
Login error - Wrong username/email/password combo
oAuth Successful - Please wait...

Plex log
Login Function - Wrong Password ❌
Plex User Check - User not Approved User ❌
Plex User Check - Found User on Friends List ✔️
```

**Comment by causefx** [comment]
please pull again from GH. I added one tweak for you to test.

**Comment by kimsbrian** [comment]
Made a fresh installation with the new files but still receiving the same errors.

**Comment by causefx** [comment]
Please double check the machine ID

**Comment by kimsbrian** [comment]
I had remote access disabled so I was manually getting the machine ID. Ended up using the wrong machine ID. There appears to be two, one for the media container and another for the server. 
![fixed](https://user-images.githubusercontent.com/42874652/50528168-b813a200-0aba-11e9-9c14-900614b1e602.PNG) I was using the red ID but the blue is correct. Use this link to get right ID. https://plex.tv/api/users?X-Plex-Token=tokenhere

**Comment by si0972** [comment]
plex-ip:32400/identity should also give the correct ID
