### ISSUE TITLE
Auth issue with POST (get_iplayer reverse proxy)

### ISSUE THREAD

**Issue by yesluv** [causefx/Organizr#1015]
###### Operating System: Ubuntu
<hr>

##### Problem Description:
Having issue reverse publishing get_iplayer web PVR

With auth off it works fine. Auth work fine for other stuff (transmission sonarr etc etc)
I suspect its something to do with the bad code on the get_iplayer web pvr but not sure how to troubleshoot further with the Organizr auth module

The page load initially but clicking any link causes the error

i eventually get a 405 Not Allowed nginx error page and in the nginx logs i get an auth request unexpected error.

Auth block is
location ~ /auth-(.*) {
	internal;
	rewrite ^/auth-(.*) /api/?v1/auth&group=$1;
}

server block is
 location /getiplayer {
                auth_request /auth-0;
                rewrite /getiplayer(.*) /$1 break;
                proxy_pass http://x.x.x.x/;
                add_header X-Frame-Options "SAMEORIGIN";
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

php block is
location ~ \.php$ {
		fastcgi_split_path_info ^(.+\.php)(/.+)$;
		# With php7-fpm:
		fastcgi_pass unix:/var/run/php7-fpm.sock;
		fastcgi_index index.php;
		fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
		include /etc/nginx/fastcgi_params;

any help would be greatly appreciated

thanks

<hr>

##### Reproduction Steps:
1. Deploy Organizr-V2 docker
    https://hub.docker.com/r/organizrtools/organizr-v2/ (select php-fpm)
2. Deploy get_iplayer docker
    https://hub.docker.com/r/marginal/get_iplayer/
3. Change get_iplayer.cgi baseurl (edit ./start file command to include --baseurl /getiplayer)
4. Reverse publish through nginx organizr

<hr>

#### Errors on screen?  If so paste here:

```
*17 upstream timed out (110: Operation timed out) while reading response header from upstream, client: *, server: *, request: "POST /getiplayer/ HTTP/1.1", subrequest: "/api/index.php", upstream: "fastcgi://unix:/var/run/php7-fpm.sock", host: "*", referrer: "*"
*449 auth request unexpected status: 302 while sending to client, client: x.x.x.x, server: <fqdn>, request: "POST /getiplayer/ HTTP/1.1", host: "x.x.x.x", referrer: "http://x.x.x.x/getiplayer/"

nginx 405 not allowed
organise error 500 something happened
```

**Comment by yesluv** [comment]
Just to add to this, i see the same issue with tautull. Any ideas anyone?
auth request unexpected status: 302 while sending to client, client: x.x.x.x, server: *, request: "POST /tautulli/get_plex_log?log_type=server HTTP/1.1", host: "*", referrer: "https://*/tautulli/logs"

**Comment by yesluv** [comment]
Finally figured this one out. If anyone else has this issue the fix is below
I suspect that the POST from the website content was causing issues with the PHP Organizr auth script so change the auth block from a rewrite to proxy_pass whilst removing unwanted headers/body etc from the auth subrequest

The Organizr auth guide/wiki does kinda suggest this - but makes more sense now

	location ~ /auth-(.*) {
		internal;
		proxy_set_header Host $host;
		proxy_pass_request_body off;
    	        proxy_set_header Content-Length "";
		#rewrite ^/auth-(.*) /api/?v1/auth&group=$1;
		proxy_pass http://127.0.0.1:80/api/?v1/auth&group=$1;
	}

**Comment by causefx** [comment]
nice!  good job!
