### ISSUE TITLE
API finish install and add tabs

### ISSUE THREAD

**Issue by VacuousCoder** [causefx/Organizr#1016]
###### Operating System: Ubuntu
<hr>

##### Problem Description:
I'm working on scripting Organizr with ansible to deploy it, along with some other services. Once it's installed I was hoping to finish up the install silently and then configure tabs for the other services automatically. Is there a documented way to achieve this? 

Thanks

<hr>

**Comment by causefx** [comment]
i will be adding something like that...  it should be possible with the api tho.  only issue is, the setup needs to be complete to get an API Key.

**Comment by VacuousCoder** [comment]
Not exactly. I was able to complete the install silently with this bit of python

```
        # Autoconfig
        params = {'license': 'personal',
                  'username': 'admin',
                  'email': email,
                  'password': password,
                  'hashKey': password,
                  'registrationPassword': password,
                  'api': password,
                  'dbName': name,
                  'location': '/config/www/db'}

        formatted_params = {}
        i = 0
        for param in params:
            formatted_params['data[{0}][name]'.format(i)] = param
            formatted_params['data[{0}][value]'.format(i)] = params[param]
            i += 1

        url = r'https://{0}.{1}/api/?v1/wizard_config'.format(name, self.app.pargs.domain)
        request = requests.post(url=url, data=formatted_params)
```

Since I set the API key in my post I already have it. So, really I just need to figure out the proper way to auth against the API and then use it to add the tabs now.

**Comment by causefx** [comment]
right, that is what i meant.  you completed the setup using the api.  now you would just hit the end point:

`/api/?v1/settings/tab/editor/tabs`

the params still need to be in data array:
action = addNewTab
tabOrder = next tab # [which would be 3 if new install]
name = tab name
url = url address
url_local = local url
ping_url = can be null
default = 0 or 1
group_id = group id
image = url of image
type = 0,1,2 or 3

**Comment by VacuousCoder** [comment]
Fantastic. I'll give this a shot. I appreciate the help.

**Comment by causefx** [comment]
np, lmk

**Comment by causefx** [comment]
thanks for that, if you need anything just open issue back up
