### ISSUE TITLE
Changing username breaks Tautulli SSO autologin for guest users (manual login works fine)

### ISSUE THREAD

**Issue by ArbiterGR** [causefx/Organizr#1017]
###### Operating System: Ubuntu 18.04
<hr>

##### Problem Description:
Changing a user's username to a more friendly name instead of full e-mail from within organizr's users list, breaks Tautulli's guest auto log in. Organizr tries to pass the username instead of the user's e-mail address, resulting the latter not recognizing the user.

This is the error i'm getting

> DEBUG | Tautulli WebAuth :: Invalid user login attempt from '_{organizr username field}_'.

-- | --
Using the _"Enable Plex oAuth"_ solves that problem, but i prefer not to use that option for the time being, as i want my users to log in with their plex credentials right from my page.

A possible solution to this, would to always pass the user's email in the token, or if that breaks stuff, create some Display name fields for use inside organizr to be more "Display friendly".

<hr>

##### Reproduction Steps:

<hr>

#### Errors on screen?  If so paste here:

```

```

**Comment by causefx** [comment]
let me try changing to email and see what happens.

**Comment by causefx** [comment]
Looks like Tau only stores username in local DB...  I will not be able to make this change.  The only 2 options are:

1. use Plex OAuth
2. change organizr users usernames to match what tautulli for them.

**Comment by causefx** [comment]
@ArbiterGR so, i spoke with swiftpanda and he said that he does actually store the emails in the DB.  Making the change now.

**Comment by ArbiterGR** [comment]
Thanks @causefx ! I can confirm that username logins work fine now in Tautulli.

**Comment by causefx** [comment]
sweet!  good stuff!
