### ISSUE TITLE
Endless loading on Safari (macOS)

### ISSUE THREAD

**Issue by cmer** [causefx/Organizr#1018]
###### Operating System: macOS
<hr>

##### Problem Description:
When I visit my Organizr installation with Safari on macOS (Mojave), I get the spinning circle (ie: loading indicator) and the login form never shows up. It spins forever.

This does not happen on Chrome.

**Comment by causefx** [comment]
i just tested on my macbook

Mojave 10.14.1
Safari 12.0.1
everything works fine. login screen presented fine. logged in fine. you can try:


https://dev.organizr.app

**Comment by cmer** [comment]
That URL worked just fine. Could I privately give you the URL to my install
for you to see?

**Comment by cmer** [comment]
Ok I think I'm onto something. It works if I don't route traffic through
Cloudflare. They do something to the Javascript that prevents it from
running. I'll update this thread as I find out more.

**Comment by causefx** [comment]
i too run CF. turn off rocket loader.

**Comment by cmer** [comment]
Ok. 100% figured it out. Enabling Rocket Loader on Cloudflare breaks
Organizr. Oddly enough, it was working just fine up until a few weeks ago.

**Comment by cmer** [comment]
I posted the above via email just before seeing your response. thanks!

**Comment by causefx** [comment]
no worries. glad it’s all good :)

**Comment by marc0janssen** [comment]
I have the same problem and I have no rocket loader or whatever... I even killed/delete my complete container in docker / wiped all the config.. 

Still nothing. firefox is ok.

**Comment by marc0janssen** [comment]
Fixed it....

Problem occurs in Safari when you switch Language.

To fix it: Press remove all!

<img width="640" alt="yosemite-safari-preferences-privacy-details-search" src="https://user-images.githubusercontent.com/5788988/78070612-62eccd00-739c-11ea-842e-4a5e006baacd.png">

**Comment by causefx** [comment]
Language on org site or safari settings?

**Comment by marc0janssen** [comment]
Hi. Sorry for being unclear. 

If you change the language in the site (Organizr) then when using Safari the site will stay in an endless loop. (If you check in Firefox, it will still work).

If you then delete the tracking data in Safari, your site (Organizr) will work again.

Hopes this clarifies it.

**Comment by domaximus** [comment]
Safari 13.1.1 with Organizr 2.0.633 in a docker container. Also on Cloudflare. rocket loader disabled (wasn't enabled). Also did "Remove All" as described in this topic. No solution for me. Any more ideas on how to fix the endless loading of the page? I've found out 1 refresh of the page usually fixes it and the page is shown fine after that.

**Comment by bxlouis** [comment]
Experiencing the same issue on Safari and can’t figure out route cause. As mentioned by @domaximus 1 refresh usually fixes it. I can’t reproduce with Chrome and Firefox and I’m not using Cloudflare.

**Comment by causefx** [comment]
I will try using my macbook for a day and so and see if I see this...

**Comment by bxlouis** [comment]
@causefx any luck when trying on a mac?

**Comment by causefx** [comment]
I tested again and tried changing the language multiple times and refreshing the page with no issues.  What version are you using for browser and Organizr?

**Comment by bxlouis** [comment]
Apologies for the late reply.
I believe the issue is happening when accessing Organizr through Reverse Proxy (Traefik v2).
Issue happens on Safari 14.0.3 and Google Chrome (89.0.4389.82).
Oragnizr 2.1.235 runs on Docker.

**Comment by domaximus** [comment]
> Apologies for the late reply.
> I believe the issue is happening when accessing Organizr through Reverse Proxy (Traefik v2).
> Issue happens on Safari 14.0.3 and Google Chrome (89.0.4389.82).
> Oragnizr 2.1.235 runs on Docker.

Gave up on a solution. I've got the same setup as you have. Eventually got used to refresh the page first time.

**Comment by bxlouis** [comment]
> > Apologies for the late reply.
> > I believe the issue is happening when accessing Organizr through Reverse Proxy (Traefik v2).
> > Issue happens on Safari 14.0.3 and Google Chrome (89.0.4389.82).
> > Oragnizr 2.1.235 runs on Docker.
> 
> Gave up on a solution. I've got the same setup as you have. Eventually got used to refresh the page first time.

Maybe @causefx can help us find a solution? I could easily share my docker-compose settings in order to help debugging.

**Comment by causefx** [comment]
Can you try accessing Organizr via IP and Port - bypassing traefik to see if that is the actual underlying issue?

**Comment by bxlouis** [comment]
> Can you try accessing Organizr via IP and Port - bypassing traefik to see if that is the actual underlying issue?

@causefx this is what I meant in my original statement, sorry for the misunderstanding. I noticed that the issue does not happen when accessing directly Organizr via IP and Port, but only when using the domain name, through the Reverse Proxy.

**Comment by causefx** [comment]
I really don't use traefik... maybe post your config here and hopefully we can have someone chime in
