### ISSUE TITLE
Refused to display

### ISSUE THREAD

**Issue by seb972** [causefx/Organizr#102]
Hi,

Thank a lot for your work, i search for a long time for a website look like your. I have a bug on one website iframe "Synology NAS".

This is my error: Refused to display 'http://********:5000/' in a frame because an ancestor violates the following Content Security Policy directive: "frame-ancestors 'self' https://gofile.me http://gofile.me".

I have a blank page. I don't have Https andi have website run without any problem.
Can you help me to resolv this please?

**Comment by causefx** [comment]
Open this issue again after you restart and it doesnt work.
