### ISSUE TITLE
A static website with a light background has its background turn dark when viewed in an iframe

### ISSUE THREAD

**Issue by whalehub** [causefx/Organizr#1022]
###### Operating System: Debian
<hr>

##### Problem Description:
I have a static website with a light background that I serve from my server with the webserver Caddy as well as an instance of the backup software Duplicati which has a Web GUI which is being proxied by Caddy. Both sites look fine when I access them via their respective URLs, but when I add them to Organizr in an iframe and access them that way, the background on these sites is inexplicably dark.

Here are some screenshots where you can see the issue.

**Static website**

![screencapture-about-datahoarder-xyz-2019-01-08-15_13_20](https://user-images.githubusercontent.com/44198148/50835881-262c5480-1358-11e9-96d5-c0de65a97280.png)

![screencapture-datahoarder-xyz-2019-01-08-15_13_33](https://user-images.githubusercontent.com/44198148/50835897-2debf900-1358-11e9-8424-c4e5e0939631.png)

**Duplicati**

![screencapture-duplicati-datahoarder-xyz-ngax-index-html-2019-01-08-15_13_58](https://user-images.githubusercontent.com/44198148/50835911-33e1da00-1358-11e9-8200-a8c6c6b3674d.png)

![screencapture-datahoarder-xyz-2019-01-08-15_25_09](https://user-images.githubusercontent.com/44198148/50836508-a4d5c180-1359-11e9-9da9-63655a4b33bb.png)

<hr>

##### Reproduction Steps:

**Reproducing the issue with a static website**
1. Download [this](https://seafile.datahoarder.xyz/f/5b5db73355f54561a19d/) sample page from my website.
2. Extract it on your local machine.
3. Rename the .html file to index.html
4. Point your webserver at the extracted directory.
5. Add the URL of the site to Organizr in an iframe.
6. Access the site via Organizr.

**Reproducing the issue with Duplicati**
1. Download an install Duplicati on your machine.
2. Proxy the connection to Duplicati with a reverse proxy.
3. Add the URL for Duplicati to Organizr in an iframe.
4. Access the site via Organizr.

<hr>

#### Errors on screen?  If so paste here:
 N/A

**Comment by gilbN** [comment]
@whalehub in custom css add 
```css
.frame-Duplicati{background-color:white}
```

`Duplicati` is the name of the Tab

**Comment by causefx** [comment]
you can set orgs frame background to white if you like so it can inherit that color.

**Comment by whalehub** [comment]
@gilbN That fixed the issue for me, many thanks for your help!
