### ISSUE TITLE
iFrames causing issues; organizr not allowing iframe

### ISSUE THREAD

**Issue by XDGFX** [causefx/Organizr#1023]
###### Operating System: Ubuntu
<hr>

##### Problem Description:

iFrames don't seem to work properly. I have so far added Sonarr, Radarr, Tautulli and Plex. They are all set as 'iFrame' in tab editor. Selecting Radarr or Tautulli will bring a blank screen apart from this in the bottom left:

- 
- 
- 
- 

### Navigation

(literally four bullet points and 'Navigation')

For some reason Sonar started like this but is now working seemingly without issue.Plex displays a blank page.

I haven't found X-Frame-Options in any config file that isn't set to "SAMEORIGIN". I've restarted nginx and tried different web browsers to the same result.

Any ideas on what is causing this? The Sonarr and Radarr config files are almost identical so I assume it's an issue with some main nginx config. If it's relevant I have set up all the services to go through a reverse proxy and ssl is set up with LetsEncrypt. All configs are basically from elmerfdz/OrganizrInstaller.

<hr>

**Comment by christronyxyocum** [comment]
You're missing some headers and/or parameters. Please compare your nginx config for the various apps to our examples: https://github.com/organizrTools/Config-Collections-for-Nginx

**Comment by XDGFX** [comment]
All the app configs are identical to the examples you posted. I had a look through the other config files for anything related to headers and couldn't see anything - is there anywhere specific I should be looking? Thanks

**Comment by XDGFX** [comment]
Just worked out what it was - my urls in the Organizr tab settings were in the form

> www.domain.com/radarr

When they needed to be
> https://www.domain.com/radarr/

Also with Tautulli I needed to add the /home to the end of the url. Hopefully this helps someone else!
