### ISSUE TITLE
LDAP Auth not working

### ISSUE THREAD

**Issue by Grekkor** [causefx/Organizr#1024]
###### Operating System: Ubuntu
<hr>

##### Problem Description:
Whatever I try I cannot get LDAP to work. Works for other services but not this one.
Can someone create a detailed documentation on how it should be set up and check if this feature works properly?

<hr>

##### Reproduction Steps:
Here my config:
![image](https://user-images.githubusercontent.com/9094858/51116634-fa9fe300-180b-11e9-8a26-c6806b9c06e1.png)
SSL is set up correctly (works with other services).
<hr>

```

```

**Comment by causefx** [comment]
v2, out tomorrow
