### ISSUE TITLE
Error Populating Homepage Calendar

### ISSUE THREAD

**Issue by InfernoCV** [causefx/Organizr#1025]
Organizr Version: V 1.8
Branch: Master
WebSever: Nginx
Operating System: Ubuntu Server 18.04.1, Docker 18.01.1-ce
<hr>

##### Problem Description:

The homepage calendar does not show any information.  When checking the logs, there is a '401 Unauthorized' response when trying to access 'https://mydomain.com/radarr | sonarr/api/*' (both services have errors).

Organizr is setup in docker container on port 8090 (http://192.168.2.75:8090).
Sonarr is in docker container on port 8989 with URL base set to /sonarr (http://192.168.2.171:8989/sonarr)
Radarr is in docker container on port 7878 with URL base set to /radarr (http://192.168.2.171:7878/radarr)

All services proxied by LetsEncrypt Nginx container.

Sonarr & Radarr are setup identically in Nginx site-confs.  Both have Authentication set to 'None' in their General Options Panel.
```
location /sonarr {
                auth_request /auth-admin;
                proxy_pass http://192.168.2.171:8989;
                add_header X-Frame-Options "SAMEORIGIN";
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
}
location /radarr {
                auth_request /auth-admin;
                proxy_pass http://192.168.2.171:7878;
                add_header X-Frame-Options "SAMEORIGIN";
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
}
```
Authentication is setup following [Nginx Server Based Authentication](https://github.com/causefx/Organizr/wiki/Authentication-%7C-Server-Based)

I verified the API tokens are correct and have generated new ones to be sure.

<hr>

##### Reproduction Steps:

Enable Nginx based authentication for radarr/sonarr with /auth-admin requirement.  Calendar does not populate and get errors in Organizr logs.

Comment out the 'auth_request' lines for both services, the calendar works and no errors are thrown in Organizr.

<hr>

#### Errors on screen

```
RADARR ERROR: Client error: `GET https://mydomain.com/radarr/api/calendar?start=2018-12-15&end=2019-02-13` resulted in a `401 Unauthorized` response:

SONARR ERROR: Client error: `GET https://mydomain.com/sonarr/api/calendar?start=2018-12-15&end=2019-02-13` resulted in a `401 Unauthorized` response:
```

**Comment by causefx** [comment]
on the homepage settings, use local urls instead of the proxied urls

**Comment by InfernoCV** [comment]
That fixed it.  Thanks.
