### ISSUE TITLE
[V2] Google Calendar shows all-day event as 7:00pm the previous day

### ISSUE THREAD

**Issue by lukec11** [causefx/Organizr#1026]
###### Operating System: Ubuntu
<hr>

##### Problem Description:
When adding an event to calendar and setting the time to "All-Day," the event appears the previous day at 7:00 PM. This issue occurs in the monthly and weekly view of the calendar. In the daily section, it shows up on the specific day as an event without a time, but it also shows up the previous day as an event from 7:00 pm to 7:00 pm.  
![image](https://user-images.githubusercontent.com/15222474/51131639-4d729e00-17fe-11e9-9d9f-47294d795334.png)

![image](https://user-images.githubusercontent.com/15222474/51131670-67ac7c00-17fe-11e9-9274-fe2e2561f5d4.png)

The calendar works fine using Sonarr / Radarr.

<hr>

##### Reproduction Steps:
1. Add Event in Google Calendar
2. Set Event to "All Day"
3. Add Google Calendar to Organizr via iCal

<hr>

#### Errors on screen?  If so paste here:

```

```

**Comment by causefx** [comment]
i still need to look into this.

**Comment by Wintermuteau** [comment]
Also having this issue with the time for google calendar items being incorrect, in my case they are adding 7 Days + 11 hours (7pm turns into 6am), am in Sydney timezone (+11). Time from Sonarr calendar items are fine and correct.

Organizr on Windows, using OWI Installer, all working perfectly except for this.

**Comment by causefx** [comment]
I believe this is fixed now with the latest versions released.
