### ISSUE TITLE
[V2] Crash during initial language setup

### ISSUE THREAD

**Issue by BloodyAltair** [causefx/Organizr#1028]
###### Operating System: Docker image (organizrtools/organizr-v2)
<hr>

##### Problem Description:
The frontend application stuck with spinning loader at first load (before `organizr_lang` cookie value is defined) if there is no localization files for user agent language(`ru` in my case). JS console screenshot: [https://pasteboard.co/HWt1qTV.png](https://pasteboard.co/HWt1qTV.png)
<hr>

##### Reproduction Steps:
Just launch application in private browsing mode or new browser profile

**Comment by causefx** [comment]
Can you please try out this fix.

**Comment by BloodyAltair** [comment]
> Can you please try out this fix.

Yep. It works, thanks

**Comment by causefx** [comment]
awesome! thanks!
