### ISSUE TITLE
Custom Tile/Theme color

### ISSUE THREAD

**Issue by rix1337** [causefx/Organizr#103]
Please allow a modification of the theme-color (hardcoded to #2d89ef), see: [Search result for 2d89ef](https://github.com/causefx/Organizr/search?utf8=%E2%9C%93&q=2d89ef&type=Code)

This allows for theming the mobile frame border. You can see the light blue on Android using the Chrome browser.

Otherwise this is running extremely well!

**Comment by causefx** [comment]
hmmmm, what color do you want it?  you are the first to ask for this...

**Comment by rix1337** [comment]
I use the plex theme, so #E49F0C would be cool.

Its a minor issue, though ^^
