### ISSUE TITLE
As of Thursday, Jan. 3, 2019, the YQL service at query.yahooapis.com will be retired

### ISSUE THREAD

**Issue by minpark815** [causefx/Organizr#1031]
###### Operating System: Ubuntu
<hr>

##### Problem Description:
As of Thursday, Jan. 3, 2019, the YQL service at query.yahooapis.com will be retired
<hr>

##### Reproduction Steps:
Weather API url returns nodata

<hr>

#### Errors on screen?  If so paste here:

```
ERR_NAME_NOT_RESOLVED
```

**Comment by si0972** [comment]
V1.80 is not actively developed, things will break.

**Comment by causefx** [comment]
Please try switching over to 2.0 please.

**Comment by minpark815** [comment]
Ah okok I'll go ahead and do that. I'll report back if the issue is still there. Unless the weather url changed the issue i'm assuming will still be there though. In the v1.8 the file that has the query is js/jouery.simpleWeather.js.

Thanks for the quick response!

**Comment by causefx** [comment]
I have no implemented weather into v2 yet.  if people want it, we can do it.

**Comment by minpark815** [comment]
cool cool. this was not an essential feature request and I know you guys are busy so we're all good. thanks for the amazing work guys.

**Comment by causefx** [comment]
:) thank you

**Comment by causefx** [comment]
:) awesome!
