### ISSUE TITLE
homepage appears all scrambled up.

### ISSUE THREAD

**Issue by stormsz** [causefx/Organizr#1032]
using the image for the arm arch. lsioarmhf/organizr , ubuntu 18.04 lts on odroid xu4.

##### Problem Description:
the website loads all messed up and scrambled. browser console trows a bunch of errors.

##### Reproduction Steps:
docker-compose -f docker-compose.yml up -d organizr

docker compose:
`    organizr:
                container_name: organizr
                restart: always
                image: lsioarmhf/organizr-aarch64
                volumes:
                        - ${USERDIR}/docker/organizr:/config
                        - ${USERDIR}/docker/shared:/shared
                environment:
                        - PUID=${PUID}
                        - PGID=${PGID}
                        - TZ=${TZ}
                networks:
                        - traefik_proxy
                labels:
                        - "traefik.enable=true"
                        - "traefik.backend=organizr"
                        - "traefik.frontend.rule=Host:joaocunha.duckdns.org; Pa
thPrefixStrip: /organizr"
                        - "traefik.port=80"
                        - "traefik.docker.network=traefik_proxy"
                        - "traefik.frontend.headers.SSLRedirect=true"
                        - "traefik.frontend.headers.STSSeconds=315360000"
                        - "traefik.frontend.headers.browserXSSFilter=true"
                        - "traefik.frontend.headers.contentTypeNosniff=true"
                        - "traefik.frontend.headers.forceSTSHeader=true"
                        - "traefik.frontend.headers.SSLHost=example.com"
                        - "traefik.frontend.headers.STSIncludeSubdomains=true"
                        - "traefik.frontend.headers.STSPreload=true"
                        - "traefik.frontend.headers.frameDeny=true"

`

docker compose log:
https://imgur.com/a/Jl2ebHI

organizr page:
https://imgur.com/a/3YhWKwA

console errors:
https://imgur.com/a/u4cDh33

the red ones extended:
ReferenceError: addToHomescreen is not defined[Learn More] organizr:365:1
<anonymous>
https://joaocunha.duckdns.org/organizr:365:1
ReferenceError: localStorageSupport is not defined[Learn More] organizr:612:6
<anonymous>
https://joaocunha.duckdns.org/organizr:612:6
ReferenceError: $ is not defined[Learn More] organizr:627:4
<anonymous>
https://joaocunha.duckdns.org/organizr:627:4

let me know if you need anything else, or if this is not the right place to ask for help for the arm arch. if so just let me know and close it :)

**Comment by si0972** [comment]
You are using V1, this is not actively developed.
Seems like treafik isnt handling what seems to be a subfolder, correctly.

**Comment by stormsz** [comment]
ok, so i went ahead as asked the  linuxserver.io lads, and its appears an update to V2 is on the works and pretty close to reach pipeline. So if anyone is having my problem, just way :D thanks for your time.
case closed!

**Comment by si0972** [comment]
The wiki tells you how to get V2 now.
