### ISSUE TITLE
iOS add homescreen full screen?

### ISSUE THREAD

**Issue by pronsta** [causefx/Organizr#1033]
Hi,

Is it possible if I add the organzr v2 to iOS homescreen that it will launch as full screen instead of opening safari with the bar? 

Thanks

**Comment by jrdnlc** [comment]
It would have to be an actual app in that case. The `Add to Homescreen` feature of iOS is just a shortcut/bookmark.

**Comment by OrganicKobze** [comment]
Unless the home screen bookmark is installed as a managed webclip, in which case you have the option to load a webclip that launches in fullscreen.

**Comment by VibroAxe** [comment]
Just came looking for the same thing for Android, can you not achieve this with the correct implementation of a pwa manifest and display: fullscreen?

https://superpwa.com/doc/web-app-manifest-display-modes/

Had a quick look at the repo and couldn't see a manifest as yet but it seems to be launching in standalone atm which implies something is there?

Apologies for the issue necro if you think manifest is achievable I would mind submitting a pr, but appreciate your feedback first and it's 1am as I write this so I could have missed something important ;)
