### ISSUE TITLE
Homepage HTML refreshes when switching between tabs

### ISSUE THREAD

**Issue by gilbN** [causefx/Organizr#1035]
###### Operating System: docker
<hr>

##### Problem Description:
I notice that when just switching between open tabs and the back to the homepage tab the custom html will refresh everytime. Is this by design?

code for monitorr: 

```
<div id="announcementRow" class="row"><h4 class="pull-left"><span>Monitorr</span></h4><hr class="hidden-xs"></div>
<div style="overflow:hidden; height:260px">
<embed style="height:calc(100% + 50px)" width='100%' src='https://monitorr.domain.com/index.min.php' />
</div>
```

Code for grafana: 
```
 <style>
.flex {
    display: flex;
    flex-wrap: wrap;
    flex-direction: row;
    align-items: center;
    background: transparent;
    box-shadow: none !important;
    transition: all .4s ease-in-out;
}
/* -------------------Small widget------------------- */
.flex-child { padding: 3px; flex-grow: 1; flex-basis: 0;}
#grafanadwidget { position: relative; height: calc(80px); width: calc(100%);}
/* -------------------Small widget------------------- */

/* -------------------Big widget------------------- */
.flex-child-big { padding: 3px; flex-grow: 1; flex-basis: 0;}
#grafanadwidget-big { position: relative; height: calc(250px); width: calc(100%);}
/* -------------------Big widget------------------- */

#announcementRow { background-color:transparent !important;}
#announcementRow>h4 {
    padding-left: 15px;
    font-family: Rubik,sans-serif;
    margin: 10px 0;
    font-weight: 300 !important;
    line-height: 22px;
    font-size: 18px;
    color: #dce2ec;
}
.overflowhider { height: 100%; overflow: hidden;}
@media only screen and (max-width: 650px) {.flex-child-big {flex-basis: auto;min-width: auto !important;}}
@media only screen and (max-width: 1125px) {.flex-child-big {flex-basis: auto;min-width: 600px;flex-basis: fit-content;}}
@media only screen and (max-width: 1649px) {.flex-child {flex-basis: auto;}}
</style>

<!-- -------------------ADD TITLE HERE------------------- -->
<div id="announcementRow" class="row"><h4 class="pull-left">
    <span>Grafana</span></h4><hr class="hidden-xs"></div>

<!-- -------------------SMALL WIDGET START------------------- -->
    <div class="content-box flex">
    <!-- -------------------WIDGET------------------- -->
    <div class="flex-child" id="flex-grafanadwidget">
    <div class="overflowhider"><embed id="grafanadwidget" 
    src='ADD-URL-TO-GRAFANA-PANEL-HERE'/>
    </div></div>
    <!-- -------------------WIDGET------------------- --> 
    <div class="flex-child" id="flex-grafanadwidget">
    <div class="overflowhider"><embed id="grafanadwidget" 
    src='ADD-URL-TO-GRAFANA-PANEL-HERE'/>
    </div></div>
    <!-- -------------------WIDGET------------------- -->     
    <div class="flex-child" id="flex-grafanadwidget">
    <div class="overflowhider"><embed id="grafanadwidget" 
    src='ADD-URL-TO-GRAFANA-PANEL-HERE'/>
    </div></div>
    <!-- -------------------WIDGET------------------- --> 
    <div class="flex-child" id="flex-grafanadwidget">
    <div class="overflowhider"><embed id="grafanadwidget" 
    src='ADD-URL-TO-GRAFANA-PANEL-HERE'/>
    </div></div>
    <!-- -------------------WIDGET------------------- -->     
    <div class="flex-child" id="flex-grafanadwidget">
    <div class="overflowhider"><embed id="grafanadwidget" 
    src='ADD-URL-TO-GRAFANA-PANEL-HERE'/>
    </div></div>
    <!-- -------------------WIDGET------------------- -->     
    <div class="flex-child" id="flex-grafanadwidget">
    <div class="overflowhider"><embed id="grafanadwidget" 
    src='ADD-URL-TO-GRAFANA-PANEL-HERE' />
    </div></div>
</div>
<!-- -------------------SMALL WIDGET END------------------- -->

<!-- -------------------BIG WIDGET START------------------- -->   
<div class="content-box flex">
    <!-- -------------------BIG WIDGET------------------- -->        
    <div class="flex-child-big" id="flex-grafanadwidget-big">
    <div class="overflowhider"><embed id="grafanadwidget-big" 
    src='ADD-URL-TO-GRAFANA-PANEL-HERE' />
    </div></div>
    <!-- -------------------BIG WIDGET------------------- -->     
    <div class="flex-child-big" id="flex-grafanadwidget-big">
    <div class="overflowhider"><embed id="grafanadwidget-big" 
    src='ADD-URL-TO-GRAFANA-PANEL-HERE' />
    </div></div>
    <!-- -------------------BIG WIDGET------------------- -->     
    <div class="flex-child-big" id="flex-grafanadwidget-big">
    <div class="overflowhider"><embed id="grafanadwidget-big" 
    src='ADD-URL-TO-GRAFANA-PANEL-HERE' />
    </div></div>   
</div>
<!-- -------------------BIG WIDGET END------------------- --> 
```

<hr>

##### Reproduction Steps:
switch between homepage and other tabs

<hr>

#### Errors on screen?  If so paste here:
none

**Comment by causefx** [comment]
Are you sure it’s refreshing and not just flashing? what does the network tab do when you swap tabs?

**Comment by gilbN** [comment]
> Are you sure it’s refreshing and not just flashing? what does the network tab do when you swap tabs?
> […](#)
> Sent from my iPhone
> On Jan 18, 2019, at 12:29 AM, GilbN ***@***.***> wrote: Organizr Version: V 2 Branch: Develop WebSever: Nginx Operating System: docker Problem Description: I notice that when just switching between open tabs and the back to the homepage tab the custom html will refresh everytime. Is this by design? code for monitorr: <div id="announcementRow" class="row"><h4 class="pull-left"><span>Monitorr</span></h4><hr class="hidden-xs"></div> <div style="overflow:hidden; height:260px"> <embed style="height:calc(100% + 50px)" width='100%' src='https://monitorr.domain.com/index.min.php' /> </div> Code for grafana: <style> .flex { display: flex; flex-wrap: wrap; flex-direction: row; align-items: center; background: transparent; box-shadow: none !important; transition: all .4s ease-in-out; } /* -------------------Small widget------------------- */ .flex-child { padding: 3px; flex-grow: 1; flex-basis: 0;} #grafanadwidget { position: relative; height: calc(80px); width: calc(100%);} /* -------------------Small widget------------------- */ /* -------------------Big widget------------------- */ .flex-child-big { padding: 3px; flex-grow: 1; flex-basis: 0;} #grafanadwidget-big { position: relative; height: calc(250px); width: calc(100%);} /* -------------------Big widget------------------- */ #announcementRow { background-color:transparent !important;} #announcementRow>h4 { padding-left: 15px; font-family: Rubik,sans-serif; margin: 10px 0; font-weight: 300 !important; line-height: 22px; font-size: 18px; color: #dce2ec; } .overflowhider { height: 100%; overflow: hidden;} @media only screen and (max-width: 650px) {.flex-child-big {flex-basis: auto;min-width: auto !important;}} @media only screen and (max-width: 1125px) {.flex-child-big {flex-basis: auto;min-width: 600px;flex-basis: fit-content;}} @media only screen and (max-width: 1649px) {.flex-child {flex-basis: auto;}} </style>  <div id="announcementRow" class="row"><h4 class="pull-left"> <span>Grafana</span></h4><hr class="hidden-xs"></div>  <div class="content-box flex">  <div class="flex-child" id="flex-grafanadwidget"> <div class="overflowhider"><embed id="grafanadwidget" src='ADD-URL-TO-GRAFANA-PANEL-HERE'/> </div></div>  <div class="flex-child" id="flex-grafanadwidget"> <div class="overflowhider"><embed id="grafanadwidget" src='ADD-URL-TO-GRAFANA-PANEL-HERE'/> </div></div>  <div class="flex-child" id="flex-grafanadwidget"> <div class="overflowhider"><embed id="grafanadwidget" src='ADD-URL-TO-GRAFANA-PANEL-HERE'/> </div></div>  <div class="flex-child" id="flex-grafanadwidget"> <div class="overflowhider"><embed id="grafanadwidget" src='ADD-URL-TO-GRAFANA-PANEL-HERE'/> </div></div>  <div class="flex-child" id="flex-grafanadwidget"> <div class="overflowhider"><embed id="grafanadwidget" src='ADD-URL-TO-GRAFANA-PANEL-HERE'/> </div></div>  <div class="flex-child" id="flex-grafanadwidget"> <div class="overflowhider"><embed id="grafanadwidget" src='ADD-URL-TO-GRAFANA-PANEL-HERE' /> </div></div> </div>   <div class="content-box flex">  <div class="flex-child-big" id="flex-grafanadwidget-big"> <div class="overflowhider"><embed id="grafanadwidget-big" src='ADD-URL-TO-GRAFANA-PANEL-HERE' /> </div></div>  <div class="flex-child-big" id="flex-grafanadwidget-big"> <div class="overflowhider"><embed id="grafanadwidget-big" src='ADD-URL-TO-GRAFANA-PANEL-HERE' /> </div></div>  <div class="flex-child-big" id="flex-grafanadwidget-big"> <div class="overflowhider"><embed id="grafanadwidget-big" src='ADD-URL-TO-GRAFANA-PANEL-HERE' /> </div></div> </div>  Reproduction Steps: switch between homepage and other tabs Errors on screen? If so paste here: none — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

Yeah, it looks like it reloads in the network tab.  I'll give you access so you can have a look.

**Comment by gilbN** [comment]
Needed to use iframes! Thank you Causefx!
