### ISSUE TITLE
Joal's wont load in iFrame mode

### ISSUE THREAD

**Issue by romquenin** [causefx/Organizr#1036]
Organizr Version: V 2
Branch: Develop
WebSever: Nginx/Apache ? 
Operating System: Synology/Docker

Hello, first of all a great thanks for your awsome app, I love it. 

I had no problem to setup all my services (sab, radarr, sonarr, home assistant,...), i would also like to add the "Joal" docker container but unfortunately it doesn't work. 

Joal is a RatioMaster like service, set with a different adress then my other services(they all ends after the :ports) and will not load if the extra text after the port is missing
The working adress is : http://192.168.2.12:9000/joal/ui/

I wish there is a possible fix for this kind of ip adress. 

Thank you for your great work.

**Comment by causefx** [comment]
have you tried reverse proxying it?

**Comment by christronyxyocum** [comment]
This is due to the iFraming. Not all applications allow for it and would require different headers in order to function properly with an iFrame. So, like CauseFX said, you would most likely need to create a reverse proxy for it to function properly.

**Comment by romquenin** [comment]
> have you tried reverse proxying it?

Hello, thank you for yours reply. I haven't tried the reverse proxy because I have never did such a thing. 

I'm trying to understand on a Synology, if you have any advices to help the process I will be great full. 

Thanks.

**Comment by romquenin** [comment]
Ok i have founded a way to make reverse proxy on the synology.

I have done it for both Joal, Sonarr and Radarr.

For Sonarr and Radarr i now that my reverse proxy is working fine because i can access both service remotely without the ports in the adress (8989 and 8310). They look like this:
http://MYADRESSradarr.duckdns.org/
http://MYADRESSsonarr.duckdns.org/

For Joal it's different because i have to input "/joal/ui/" in the adress after the port. The only working adress i have found look like this: 
http://MYADRESS.duckdns.org:9000/joal/ui/
And when i add this adress to Organizr, unfortunately it wont load

I don't understand why it refuse to load in iframe.

**Comment by romquenin** [comment]
I have been i touch why "Joal"'s dev and he told me he's planning to update it soon.

The update will solve the iFrame issue.

Thanks.

**Comment by causefx** [comment]
thank you for the update.
