### ISSUE TITLE
Unsorted Tab Placement option reverses sort for all tabs 

### ISSUE THREAD

**Issue by manonstreet** [causefx/Organizr#1037]
###### Operating System: Ubuntu Server / Docker
<hr>

##### Problem Description:
Setting unsorted tab placement option to bottom reverses the tab order for all tabs within the categories.

<hr>

##### Reproduction Steps:
Observe tab order
Set Customize -> Appearance -> Options -> Unsorted Tab Placement = Bottom
Refresh
Note that while the tab order for uncategorized tabs is on the bottom as the feature intended, additionally and erroneously, all of the tabs in each category are also reversed.

**Comment by causefx** [comment]
all done
