### ISSUE TITLE
Loaded iframes do not regain focus on tab switching

### ISSUE THREAD

**Issue by BrowncoatShadow** [causefx/Organizr#1042]
###### Operating System: Linux (Docker)
<hr>

##### Problem Description:
Navigating to an already active tab does not cause iframe to regain focus.
This is an issue for applications that need to capture keyboard events (e.g. Guacamole).
Ideally, navigating to a tab should trigger action for the target iframe to regain focus, even if it has already been loaded.

I am not aware if v2 makes use of any keyboard shortcuts, if it does (or plans to) maybe a per-tab/global setting could be added to configure recapturing focus as needed.

<hr>

##### Reproduction Steps:
```
When I click a tab 1
Then iframe 1 is displayed and loaded
And keyboard events are captured by iframe 1

When I click tab 2
Then iframe 2 is displayed and loaded
And keyboard events are captured by iframe 2

When I click tab 1 again
Then iframe 1 is displayed and already loaded
# EXPECTED
And keyboard events are captured by iframe 1
```
ACTUAL: Keyboard events are **not** captured by iframe 1.

<hr>

#### Errors on screen?
N/A

**Comment by causefx** [comment]
that should do it.

**Comment by BrowncoatShadow** [comment]
I retested before and after forcing an update and verifying the change was pulled. Change appears to work as intended.

Thanks for the quick response!

**Comment by causefx** [comment]
sweet! thanks!
