### ISSUE TITLE
SQLite3 Not Found 

### ISSUE THREAD

**Issue by Comfubar** [causefx/Organizr#1044]
###### Operating System: Windows 10
<hr>

##### Problem Description:
SQLITE3 Dependency not found
 

<hr>

##### Reproduction Steps:
Installed Organizr V2 newest update all dependencies are found but SQlite3 installed sqlite3 onto system32 and added the path etc not sure if correct but Organizr is not finding SQlite3

I seen some posts about the "Extension_dir=" but if thats the issue I am unable to find it anywhere

<hr>

#### Errors on screen?  If so paste here:
Screenshot of Organizr 
https://i.imgur.com/alocV9G.png

**Comment by Comfubar** [comment]
Well after 10 more minutes of looking around and trying to figure this out found out 
that I had to add extension=sqlite3

Under Module Settings in the PHP.ini and the issue was resolved after restarting Apache

**Comment by causefx** [comment]
awesome. glad you got it sorted.
