### ISSUE TITLE
Unable to clone wiki docs on Windows due to file naming

### ISSUE THREAD

**Issue by CollinChaffin** [causefx/Organizr#1045]
There are two pages in the current documentation Wiki that due to the file naming used make it impossible to clone on Windows to have an up-to-date set of the wiki docs.  They are:

```
Authentication-|-Cookie-Based.md
Authentication-|-Server-Based.md
```
Neither the official Git for Windows GUI nor shell performs any filename escaping/conversion which of course results in error. The error is as shown due to the pipe `|` character not being legal:
```
λ  git clone https://github.com/causefx/Organizr.wiki.git .
Cloning into '.'...
remote: Enumerating objects: 5, done.
remote: Counting objects: 100% (5/5), done.
remote: Compressing objects: 100% (5/5), done.
remote: Total 584 (delta 1), reused 0 (delta 0), pack-reused 579 eceiving objects:  92% (538/584)
Receiving objects: 100% (584/584), 102.17 KiB | 2.49 MiB/s, done.
Resolving deltas: 100% (342/342), done.
error: unable to create file Authentication-|-Cookie-Based.md: Invalid argument
error: unable to create file Authentication-|-Server-Based.md: Invalid argument
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry the checkout with 'git checkout -f HEAD'
```

![snag_1-25-2019_23-20-39](https://user-images.githubusercontent.com/9301483/51782986-31bda080-20f8-11e9-957a-d9ef89e1e5c9.png)

Since this is a simple fix it would be very helpful if those two filenames could perhaps be renamed.  A suggestion would be to simply use the already used dash `-` or underscore `_`, both of which are legal on all filesystems (ie. `Authentication - Cookie-Based.md`).

**Comment by causefx** [comment]
try now please.

**Comment by si0972** [comment]
I just did a successful git-clone of the wiki.
