### ISSUE TITLE
Ombi sso only works with full email as user id

### ISSUE THREAD

**Issue by dejected1** [causefx/Organizr#1047]
###### Operating System: Windows
<hr>

##### Problem Description:
Ombi sso only works with full email as user id

<hr>

##### Reproduction Steps:
Was working on 2.0.0-BETA.600 but after organizr update ombi sso stopped working and hasn't worked since. Local db login and plex backend login did not pass sso login correctly to Omib. The debug always said cookie: failed. Today i tried loging into organizr with local db and my full email address. This successfully passes the token and logs me into Ombi using orgainizr sso. if i login using my user id to local db, without the email domain, orgainzr still logs me on but ombi sso fails again. Ombi sso fails using plex oauth when initiated with orgainizr, does not successfully pass the token. But when i use plex oauth from ombi directly, it works fine. 

I feel im close to getting this working i just dont know what to try. Plex won't let me change my user id to an email address, but when im at the plex oauth sign in page it says its using my full email address. I tried changing the ombi user id and orgainzr user id to an email address instead of a user id but then organizr sso fails completely. 

I've tried with the ombi url as https://myddns/ombi, http://127.0.0.1:5000/ombi, and http://127.0.0.1/ombi on the Ombi SSO settings in Org. So far none of the above have worked for Oauth. local db with full email address sso success only works with https://mydns/ombi 

I did alot here: 
https://github.com/causefx/Organizr/issues/970

<hr>

#### Errors on screen?  If so paste here:

```
When signing in withe plex oauth: 
enabled: true
cookie: false
url: https://mydns/ombi
api: true

When signing in using local db making the user id my full email address: 
enabled: true
cookie: true
url: https://mydns/ombi
api: true

```

**Comment by causefx** [comment]
are you the plex admin?

**Comment by dejected1** [comment]
yes

**Comment by causefx** [comment]
what do you have filled in under plex admin in org settings?

**Comment by dejected1** [comment]
the user id without the domain. just for giggles i tried changing it to the full email address. Now organizr plex oauth fails outright. I did notice that the user id being the full email does work to authenticate directly to plex thou. all my plex data is still coming through on my homepage for instance.

**Comment by causefx** [comment]
can you try now with todays commits

**Comment by Kaallis** [comment]
I confirm this is still an issue on 2.0.0 v2-master branch.
The SSO with Ombi only works with full email.

**Comment by dshokouhi** [comment]
@causefx I am having this issue and I am on the latest develop build 2.0.20 I think which was released yesterday.  My issue now is that if I leave admin username as my actual username then SSO will work with Plex however Ombi will not work forcing me to sign in.  If I change the admin field to my email address then the opposite takes place, Plex SSO fails requiring me to sign in and Ombi works allowing it to load.  I login to Organizr using my username.  When I look at Org logs it shows my username for Oganizr login however it shows Tautulli and Ombi with my email address instead.  This does not change when I modify my admin username field in SSO settings.  Let me know if you need any more details from  me.

**Comment by causefx** [comment]
what is email address in org settings for that username?

**Comment by dshokouhi** [comment]
it is the same email that I see in the logs

**Comment by causefx** [comment]
if you are dev docker, hit  retrieve branch and try now

**Comment by dshokouhi** [comment]
I am not using docker but I am using the develop branch, would retrieve branch still work for me? I installed in windows if that matters.

**Comment by causefx** [comment]
yeah it will work

**Comment by dshokouhi** [comment]
Ok it updated it is still not working.  Now when I leave my username or my email Plex SSO works as expected but Ombi SSO does not work.  Tautulli remains to work.

**Comment by causefx** [comment]
anything in org logs?

**Comment by dshokouhi** [comment]
its the same as before....Ombi fails to grab the token for my email even though I signed in with a username.

`Ombi Token Function - Ombi did not return Token`

**Comment by causefx** [comment]
this is an ombi issue then because we are sending the Plex Token to Ombi and it's not accepting it.  How is you user setup in ombi? the user type for your user.

On Mar 05, 2019, at 11:23 AM, Daniel Shokouhi <notifications@github.com> wrote:



its the same as before....Ombi fails to grab the token for my email even though I signed in with a username.

Ombi Token Function - Ombi did not return Token

**Comment by dshokouhi** [comment]
Hmm it looks like it shows up as Local User instead of Plex User like the others.  :/ I guess this has nothing to do with org then.

**Comment by causefx** [comment]
:| correct....


Needs to be Plex User...

On Mar 05, 2019, at 11:28 AM, Daniel Shokouhi <notifications@github.com> wrote:



Hmm it looks like it shows up as Local User instead of Plex User like the others. :/ I guess this has nothing to do with org then.

**Comment by dshokouhi** [comment]
ok thank you for your help :)

**Comment by causefx** [comment]
no problem.

**Comment by dshokouhi** [comment]
@causefx thank you for pointing me in the right direction to the issue :) I was able to use DB browser for SQlite to modify the user type in ombi.db to be a plex user and also added in my plex user id.  After doing so and saving the changes and clearing cache SSO works as expected again!

**Comment by causefx** [comment]
:) awesome! glad you git it!

**Comment by dejected1** [comment]
this does still not work for me as designed. When using plex sso it doesnt sign into ombi. only when i sign in using my full email address does it sign into everything. ombi sso still states cookie: false.  btw this after todays update.

**Comment by dejected1** [comment]
Well crap, i just tried the full email to login and now that doesnt work either. Before todays latest update i was able to sign in using sso if i used the full email address as the user id. now that no longer works.

**Comment by causefx** [comment]
Something is up with your Ombi then.  As today's update you can login using anything and it will match to plex as long as you have plex admin filled in org with either username or email.  What does your user type say in ombi?

**Comment by dejected1** [comment]
it says local user. prob because when you setup ombi it asks you to create a user before you have a chance to import any one from plex.

**Comment by dshokouhi** [comment]
@dejected1 look above at my comments to see how I fixed your exact issue.  I described all the steps I took.

**Comment by dejected1** [comment]
@dshokouhi i saw your post. Unforuntently i couldnt make head or tails of it. I installed sql lite and opened the ombidb but i couldnt find anything in relationship to users or user types. Sorry, i dont normally edit databases.

**Comment by causefx** [comment]
@dejected1 try this in ombi settings
![image](https://user-images.githubusercontent.com/16184466/53898771-ff0b9f80-3ff5-11e9-8e2c-a7176c4a6320.png)


make sure import admin is checked.

**Comment by dshokouhi** [comment]
@dejected1 its ok I can walk you through it.  You need to install DB browser for SQLite.  Then open Ombi.db in the editor.  From there you go to Browse Data and in the drop down select "AspNetUsers" then find your user ID and update "User Type" column to be `2` from `1` then you need to add your Plex ID.  I had to go in Tautulli and open my user profile to find the ID in the console.  Its doable, you just need to dig in developer tools (maybe someone has a better way to grab this lol).  Update your plex user id in the "ProviderUserId" column for your row. Then it should start working after you clear cache.

![image](https://user-images.githubusercontent.com/1634145/53898903-e0090f80-3fed-11e9-81ff-1dc3fdcbc7a2.png)


@causefx I tried that in my case but it did not work, I suspect it may not work for @dejected1  as well since the user was already created, even if I delete the account it won't add my admin.

**Comment by dejected1** [comment]
i tried to import user, but dshokoushi is correct. it wont add my admin user because its already there as a local user. i tried to remove it, but that fails as well because its the first user created and the main admin account. im worried about editing the ombidb. wouldn't i have to make this change every single time i update ombi? im going to try and reinstall ombi and create a different first user other then my admin from plex. hopefully that way when i import users it will work....

**Comment by causefx** [comment]
@dshokouhi off topic - but i'm thinking of buying a d7 and connecting it to home assistant and I came across this just now... LOL small world...

![image](https://user-images.githubusercontent.com/16184466/53899733-1c416d80-3ff8-11e9-8feb-717d227daa6f.png)

**Comment by dshokouhi** [comment]
@causefx haha yea I love my D7's they are great....the next HA release will have support for zoned cleaning too.  Nice to see another HA user!!  If you ever need any HA help feel free to reach out on Discord :) I am pretty deep in it if you look at my config on github :P 

@dejected1 if you don't feel comfortable editing the file, then starting over and creating a different admin account should work when you do the admin import.  I am just lazy and did not want to redo things :P

**Comment by dejected1** [comment]
ok so i reinstalled and it worked. when i installed ombi once upon a time the original user account was created as a local user. But when i reinstalled with the newest master just now it created my plex admin automatically as a plex user.... either way. sso works now.

**Comment by causefx** [comment]
nice! congrats!
