### ISSUE TITLE
Unable to create user with Name "TV"

### ISSUE THREAD

**Issue by 1n5aN1aC** [causefx/Organizr#1048]
###### Operating System: Linux (Docker)   [lsiocommunity/organizr]
<hr>

##### Configuration:
Proxied using nginx on linux/docker.
Authentication is set up as:  "Organizr & Emby_all"
"Create accounts as needed"  is enabled.

<hr>

##### Problem Description:
I am unable to create a user with the name "TV."
A user named "TV" exists in Emby, but when a login to Organizr is attempted, it fails. saying `log in error: password did not pass validation`

When attempting to create the user manually, It gives an error saying password did not validate.
HOWEVER, the password works if I name the user "TV2," and the password I am using is the same as is used in Emby.

<hr>

#### Errors seen when attempting to create user manually:

```
registration error: password did not pass validation
```

**Comment by jrdnlc** [comment]
v1 is no longer supported. Switch to v2 and let us know if the issue still persist. Official docker is `organizrtools/organizr-v2`

**Comment by 1n5aN1aC** [comment]
@jrdnlc @causefx thanks, didn't know there was a v2, I'll try it.
