### ISSUE TITLE
Unable to login using oAuth with plex admin

### ISSUE THREAD

**Issue by slyguy77** [causefx/Organizr#1049]
Version: 2.0.0-beta.960
Branch: v2-develop
Server OS: *nix
PHP: 7.2.13
Install Type: Official Docker
Auth Type: both
Auth Backend: plex
Installed Plugins: Nginx Configurator:1.0.1|Test Plugin:1.0.0
Installed Themes: Plex Theme:2.8.0
Theme: Organizr
Local: true
oAuth: true
Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98

misc: 
       oAuthLogin: true
       rememberMe: true
       rememberMeDays: 7
plex: 
       enabled: true
       cookie: true
       machineID: true
       token: true
       oAuthEnabled: true
       backend: true
ombi: 
       enabled: true
       cookie: false
       url: http://192.168.1.10:3579
       api: true
tautulli: 
       enabled: true
       cookie: true
       url: http://192.168.1.10:7171
<hr>

##### Problem Description:
I am no longer able to login with my plex admin account using Plex oAuth from "https://mydomain.com", I am still able to login with my plex admin from "http//localhost:port". Other plex users can login from both "https://mydomain.com" and "http//localhost:port" but a login error still appears but login is successful

<hr>

##### Reproduction Steps:

1 - Cleared cache on each device tested from.
2 - Cleared nginx cache (even though host is not configured to cache)
3 - Tried from incognito window
4 - Refreshed plex token and plex machineRreset admin password.
5 - Changed admin username
<hr>

#### Errors on screen?  If so paste here:

```
When loging in as Admin from "https://mydomain.com":
1 - oAuth Successful - Please wait
2 - Login Error
3 - Login Error: API Connection Failed
(Login fails)
Organizr logs show successful login - does not report failed login.

When loging in as Admin from "http://localhost:port":
1 - oAuth Successful - Please wait
2 - Login Error
(Login continues successfully)

When logging in as other Plex user from "https://mydomain.com" or "http://localhost:port"
1 - oAuth Successful - Please wait
2 - Login Error
(Login continues successfully)

```

**Comment by causefx** [comment]
I updated dev yesterday, can you pull that and clear cache and try again please?

**Comment by causefx** [comment]
any word on this?

**Comment by slyguy77** [comment]
Updated yesterday, cleared cache, tried incognito, still the same issue. Should I try something else?

**Comment by causefx** [comment]
Can you check the db scheme of tokens table?

**Comment by slyguy77** [comment]
sure, but you'll have to help me out.

**Comment by causefx** [comment]
please pull latest commits
