### ISSUE TITLE
Installer prerequisites missing

### ISSUE THREAD

**Issue by Nick2253** [causefx/Organizr#1054]
###### Operating System: Linux
<hr>

##### Problem Description:
When using the installer script, the installer does not check for its own prerequisites.  On installs on light OSes, especially for LXC containers, this can be a problem.

For example, installer requires:

- which
- sudo
- semanage

And these are not guaranteed to be present.

**Comment by elmerfdz** [comment]
I'll look into it or you can submit a pull request

**Comment by elmerfdz** [comment]
Assuming you used the centos installer, I've added the above to the dev branch, could you please test it out?

**Comment by causefx** [comment]
Closed due to inactivity
