### ISSUE TITLE
[V2] Close button (X) barely visible on ping notifications

### ISSUE THREAD

**Issue by 1activegeek** [causefx/Organizr#1056]
###### Operating System: Tron Docker
<hr>

##### Problem Description:

Can't see the close button on ping notifications when URLs go up/down. Blends right into the color of the background and hard to see.

Using Organizr Dark theme, with Izi notifications in Bottom Right.
<hr>

##### Reproduction Steps:

Down a system being pinged. 
<hr>

#### Errors on screen?  If so paste here:

![unknown](https://user-images.githubusercontent.com/6810720/52179757-2f201280-27ac-11e9-9908-5f15e184c501.png)

**Comment by causefx** [comment]
that is an img from that framework...

what you can do is add custom css

```
.iziToast {
    background: yellow !important;
}
```
