### ISSUE TITLE
mixed language

### ISSUE THREAD

**Issue by Zidichy** [causefx/Organizr#1057]
###### Operating System: Windows

<hr>

##### Problem Description:

When swedish language is selected as default the welcome text displays as mix with swedish and english text.
<hr>

##### Reproduction Steps:

Should be Välkommen Gäst
<hr>

#### Errors on screen?  If so paste here:

```

```
![1](https://user-images.githubusercontent.com/41482344/52183852-6aeac480-280c-11e9-9ea4-aab5136224a7.png)

**Comment by causefx** [comment]
The guest comes for the username.  I also disabled that box for now.
