### ISSUE TITLE
Could not resolve host

### ISSUE THREAD

**Issue by Sp33dFr34k** [causefx/Organizr#1058]
Getting the following message while trying to run Organizr in a Docker container:

Cloning into '/config/www/Dashboard'...
fatal: unable to access 'https://github.com/causefx/Organizr/': Could not resolve host: github.com

And a little bit down from that:

cp: cannot create regular file '/config/www/Dashboard/Docker.txt': No such file or directory

I've checked the config folder and it does create the 5 folders (keys, log, nginx, php and www), but it doesn't wanna create the Dashboard folder inside the www folder due to not being able to resolve github.com. I am using Google DNS servers in my router, and can browse to Github fine.

Obviously I'm getting a 404 error now, since it doesn't create any files in the www folder. Any ideas why it won't play nice for me?

**Comment by si0972** [comment]
ping github trough the container

`docker exec <ContainerName> ping github.com`

**Comment by Sp33dFr34k** [comment]
Thanks for your quick reply! It seems you're onto something: "ping: bad address 'github.com'"

If I try the same through for example my Pihole container it works fine.

**Comment by si0972** [comment]
paste the create/compose for docker

**Comment by Sp33dFr34k** [comment]
Ai, actually I don't use the composer but the Docker GUI that Synology provides... Basically I am adding 3 environment variables, TZ, PGID and PUID all tested working. 1 drive mapping for the /config, for the network I am using it in bridged mode and that's it. Is that something you can work with?

**Comment by si0972** [comment]
Does any of your other containers use the same network?

**Comment by Sp33dFr34k** [comment]
Yes, I have Monitorr and Transmission with VPN running in the same network. But even if I disable those it still won't work :(

**Comment by tombomb** [comment]
im not a helper or anything like that, but I have had this issue with one of my boxes once. If its still not working try restarting docker, if that dosent fix it, try checking the DNS in the docker. see https://stackoverflow.com/questions/20430371/my-docker-container-has-no-internet

**Comment by Sp33dFr34k** [comment]
@si0972 Monitorr cannot, Transmission can. Monitorr returns the same message as Organizrr: ping: bad address 'github.com'

@tombomb Thanks I will look into that!

**Comment by Sp33dFr34k** [comment]
Got it solved! It was a DNS problem indeed, I've added a file mapping in my Docker container to the etc/resolv.conf with the google nameservers in it and it works instantly... so happy right now!

Thanks to you both @si0972 and @tombomb 👍

**Comment by shersch** [comment]
I hate to revive the dead here 2 years later, but @Sp33dFr34k, I am in the same position you are and I can't figure it out.  I've even created a new resolv.conf file and mapped it to the /etc/ directory in the container, and still nothing.  all of my other containers work just fine on the bridge network.  any ideas?

**Comment by HalianElf** [comment]
> I hate to revive the dead here 2 years later, but @Sp33dFr34k, I am in the same position you are and I can't figure it out. I've even created a new resolv.conf file and mapped it to the /etc/ directory in the container, and still nothing. all of my other containers work just fine on the bridge network. any ideas?

On ARM? https://docs.linuxserver.io/faq#libseccomp

**Comment by shersch** [comment]
> > I hate to revive the dead here 2 years later, but @Sp33dFr34k, I am in the same position you are and I can't figure it out. I've even created a new resolv.conf file and mapped it to the /etc/ directory in the container, and still nothing. all of my other containers work just fine on the bridge network. any ideas?
> 
> On ARM? https://docs.linuxserver.io/faq#libseccomp

No, it's x86.  Synology DS918+.  Sorry, I should have mentioned that.

**Comment by Roxedus** [comment]
Please open a new issue, or hop onto our Discord.
