### ISSUE TITLE
Custom logo and loading question

### ISSUE THREAD

**Issue by saitoh183** [causefx/Organizr#106]
Man first off..great work on this !

I just wanted to know for the custom logo for title and loading icons, what dimensions do we need in order to to have everything look good in browser and and mobile? Maybe some guideline in that section would be good. Also URL does this mean it can be a file hosted elsewhere on the internet or it is just local/network path. If it is only local/network, maybe change URL for the work Path to avoid confusion.

**Comment by pyrostic** [comment]
Right click and view the properties of the images that are there for your clue on the sizes (or DL them and open in a photo editor).

As for the URL, yes it should work. However if it is locally hosted just usee the path or you'll run into issues with SSL sticking in the Iframe

**Comment by saitoh183** [comment]
im trying to tes the Title logo with your default.svg but i get a broken image..Is the title text by default?

**Comment by pyrostic** [comment]
Potentially?  Usually a 1 for 1 image swap does the trick

**Comment by causefx** [comment]
Thanks for the kind words... :)  the svg should work for you:
![image](https://cloud.githubusercontent.com/assets/16184466/23333045/aad53f48-fb41-11e6-9a2e-e60e4b7d1add.png)

for dimensions i put the max of: `max-width: 250px; max-height: 50px;`

that is good on mobile for like an iPhone 6 Plus...  you will need to make the width smaller for smaller phones.

**Comment by saitoh183** [comment]
im using a nginx reverse proxy and i symbolic link to put the folder in organizr folder in my www/html folder.

I see the following error:

[`error] 22172#22172: *3884 open() "/var/www/html/organizr/var/www/html/organizr/opt/organizr/images/default.svg" failed (2: No such file or directory), client: 192.168.13.1, server: cloud.saitoh.com, request: "GET /var/www/html/organizr/opt/organizr/images/default.svg HTTP/1.1", host: "cloud.saitoh.com", referrer: "https://cloud.saitoh.com/"`

my nginx entry looks like this:

```
 server {
        listen  443 ssl;
		root   /var/www/html/organizr;
		server_name cloud.saitoh.com;
        index index.php index.html index.htm;
		include /etc/nginx/snippets/ssl_saitoh.conf;

		access_log      /var/log/nginx/access/organizr/cloud.saitoh.access.log;
        error_log       /var/log/nginx/error/organizr/cloud.saitoh.error.log;


		# Static contents
    	location ~* ^.+.(jpg|jpeg|gif|png|ico|css|zip|tgz|gz|rar|bz2|doc|xls|exe|pdf|ppt|txt|tar|mid|midi|wav|bmp|rtf|js)$ {
        expires max;
    	}
		location ~ \.php$ {
			include snippets/fastcgi-php.conf;
            fastcgi_pass 127.0.0.1:9000;
				
    	}
	
     }

```

**Comment by causefx** [comment]
also thanks for the help @pyrostic

**Comment by causefx** [comment]
is this issue considered good?

**Comment by saitoh183** [comment]
yes i think so :) but still some extra documentation on customization would be good :) since changing loading screen might affect mobile view im guessing you need more then one size for the image?

**Comment by causefx** [comment]
we can resize for mobile view.

**Comment by saitoh183** [comment]
ok..well as i said issue can be closed , i would just suggest more documentation on image replacement

**Comment by causefx** [comment]
yeah I agree, docs will be ready before release.  it' still beta, want to work out as much as i can.
