### ISSUE TITLE
Add Pi-Hole image

### ISSUE THREAD

**Issue by srscott** [causefx/Organizr#1060]
###### Operating System: Windows/MacOS/Ubuntu
<hr>

##### Problem Description:

<hr>

##### Reproduction Steps:

<hr>

#### Errors on screen?  If so paste here:

```

```

**Comment by christronyxyocum** [comment]
There is essentially zero information here. Are you asking about a Docker image for Org that will run on a Raspberry Pi? Are you asking about an icon image for the PiHole application?

**Comment by jrdnlc** [comment]
I’m sure he means icon image for Pi-hole.

**Comment by srscott** [comment]
Sorry for the lack of information. I’m currently using version 1.80 on FreeNAS in a iocage jail. I’ll see about updating to v2. Does v2 include an image for Pi-hole?

**Comment by jrdnlc** [comment]
It does not but we can add it in a future release.

**Comment by srscott** [comment]
Kinda off topic here but is there a guide to update 1.8 to v2? Or a fresh FreeNAS jail install?

**Comment by jrdnlc** [comment]
You can’t update for v1 to v2. V2 needs to be a fresh install

**Comment by srscott** [comment]
Never mind I found it. Can I use existing settings etc... for v2 or start from scratch?

**Comment by christronyxyocum** [comment]
Start from scratch. It's a complete rewrite. v2 also has an Image Manager that allows you to upload your own custom icons for tabs and such as well.
