### ISSUE TITLE
[V2] Emby Connect authentication appears to be ignoring capitalization.

### ISSUE THREAD

**Issue by ddimick** [causefx/Organizr#1061]
###### Operating System: CoreOS/Docker
<hr>

##### Problem Description:
Emby Connect authentication appears to be ignoring capitalization. Emby Connect usernames using capitalization cannot authenticate to Organizr using Emby Connect backend.

<hr>

##### Reproduction Steps:
Set Organizr authentication backend to Emby Connect.
Create Emby Connect account that uses capitalization (i.e. TestUser123).
Invite TestUser123 to Emby Server, accept invite.
Verify you can login to Emby server as TestUser123.
Attempt to login to Organizr as TestUser123. Authentication will fail.
Organizr logs will show failed login attempt from testuser123, not TestUser123.

**Comment by causefx** [comment]
can you create a test user with all lower caps, does that work fine?

**Comment by ddimick** [comment]
Yes, all my users but one are all lowercase, and they work fine. It's just the mixed-case user that has a problem.

**Comment by causefx** [comment]
can you let me know exactly what the logs say when that user attempts to signin?

**Comment by ddimick** [comment]
I'm modifying the log entry since I do not want to make the actual username public, but the Emby Connect username in this case has the first letter capitalized and the rest is lowercase.

Organizr reports an all-lowercase login attempt in the logs.

organizrLog.json
`date":"2019-02-10T17:01:46Z","type":"error","username":"username","ip":"x.x.x.x","message":"Login Function - Wrong Password"},{"date":"2019-02-10 17:02:37","utc_`

organizrLoginLog.json
`date":"2019-02-10T17:01:46Z","username":"username","ip":"x.x.x.x","auth_type":"error"},{"
date":"2019-02-10 17:03:17","utc_`

**Comment by causefx** [comment]
Are you using emby connect or emby local or emby all?

**Comment by ddimick** [comment]
Authentication Backend is set to Emby Connect.

**Comment by causefx** [comment]
can toy try on Emby All.

**Comment by ddimick** [comment]
I set the Authentication Backend to Emby All, but no change in behavior.

**Comment by ddimick** [comment]
I'm not sure if it's meaningful in any way, but I can log into either Emby on my local server, or app.emby.media, and neither cares about the capitalization I use when logging in.

**Comment by causefx** [comment]
that is very odd.... as i just pass the credentials over as well. what version are you using of organizr?

**Comment by ddimick** [comment]
I'm running 2.0.0-beta.950 via the organizrtools/organizr-v2:latest docker image.

**Comment by ddimick** [comment]
If I comment out `$username = strtolower($username);` in In `api-functions.php` line 23, it works.

**Comment by causefx** [comment]
try changing that line to this:

`$username = (strpos($GLOBALS['authBackend'], 'emby') !== false) ? $username : strtolower($username);`

**Comment by ddimick** [comment]
Yup, that works.

**Comment by causefx** [comment]
LOL, no worries...  I don't question it... :)
