### ISSUE TITLE
ICS timezone incorrect

### ISSUE THREAD

**Issue by wire2111** [causefx/Organizr#1062]
###### Operating System: Unraid Docker
<hr>

##### Problem Description:

Thank you for this great software - I really enjoy it.

Importing a ics file that has X-WR-TIMEZONE as correct timezone and DTSTART/DTEND specified in local/floating times shows up with incorrect time in calendar on homepage (applies timezone from docker container I believe)
Cannot modify output ics to be in UTC

<hr>

##### Reproduction Steps:

Import attached ICS
Entries in calendar will be DTSTART/DTEND with timezone modification added (in my case date.timezone = America/Denver in php-local.ini which makes them be off by -7 hours)
For my test file the entry should be made for 5:59pm not 10:59 am

my testing ics file:
BEGIN:VCALENDAR
METHOD:PUBLISH
PRODID:-//192.168.1.16//NONSGML iCalcreator 2.4.3//
VERSION:2.0
X-WR-TIMEZONE:America/Denver
BEGIN:VEVENT
UID:20190210T150917MST-92572skKn8@192.168.1.16
DTSTAMP:20190210T220917Z
DESCRIPTION:description here.\n
 \n Will Record
DTEND:20190210T190000
DTSTART:20190210T175900
LOCATION:test location
SUMMARY:test summary
END:VEVENT
END:VCALENDAR
<hr>

#### Errors on screen?  If so paste here:

```

```

**Comment by causefx** [comment]
@rob1998 can you confirm?  i set php TZ as UTC as all times should be utc...

**Comment by rob1998** [comment]
@causefx 
All I can say for now is that all my times are showing up perfectly, but I can test his file tomorrow.

**Comment by causefx** [comment]
thanks bud. :)

**Comment by rob1998** [comment]
@causefx 
I just tested with the test file, in the file the start datetime is february 10, 2019 at 17:59
In my organizr calendar is shows up at 18:59, which makes sense cause in the Netherlands it's +1

**Comment by wire2111** [comment]
Hey guys,

Really appreciate your attention to this. For further clarity this test file entry is for 17:59 American/Denver time not utc. When it is opened in organizr since I am in American/Denver timezone no time correction should be applied and I expect to see its entry created for 17:59. Currently it gets applied a -6/-7 hour adjustment (depending on daylight savings time) to try and make it UTC I believe which results in it showing up at 10:59 on the homepage calendar.

I wrote a little python script this goes through that simply moves all times forward +6/+7 hours, organizr then moves it back +6/+7 hours and results in the correct 17:59 time showing in the homepage calendar.

Thanks and hopefully this is clear, sorry for any confusion.

**Comment by causefx** [comment]
Ah I understand, We currently only support UTC but will look into this in the future.

**Comment by wire2111** [comment]
Fair enough, thanks for your time and effort.
