### ISSUE TITLE
Any easy upgrade path to v2?

### ISSUE THREAD

**Issue by STaRDoGG** [causefx/Organizr#1063]
I just installed the docker version of v2 to check it out and like how it looks so far; but as far as I can tell the upgrade path is a 100% clean install? Is there any way to make this a smoother transition? It's a LOT of copying/pasting to upgrade from all the stuff I have in v1. So much so in fact that I'd end up just sticking to v1 as I don't really have the spare time to micromanage it, but would prefer to use v2.

**Comment by causefx** [comment]
I may add a tab importer but that is just about all i can import.  I can't import users as the user has to define the salt for the passwords.
