### ISSUE TITLE
401 qbittorrent not showing

### ISSUE THREAD

**Issue by evlo** [causefx/Organizr#1064]
###### Operating System: Ubuntu
<hr>

Hi, 
from the app launcher or whatever you want to call these things I like organizr the best 
I have installed this one  https://hub.docker.com/r/organizrtools/organizr-v2/  
but I'm having issues that if I try to open qbittorrent I get no page and in developer console I get 401, when I change it to open in new tab I get 401.

I found these, but I did not really understat the Nginx changes
https://github.com/causefx/Organizr/issues/838
https://www.reddit.com/r/organizr/comments/7c5317/qbittorrent_tab_not_loading/
I don't use any reverse proxy etc. Just my IP, not even dns, and ports.

**Comment by causefx** [comment]
can you open browser console and see what it says when trying to open that ip?

**Comment by evlo** [comment]
It is the thing under csr config in web-ui, just uncheck it, and it works. header checking or something like that

**Comment by causefx** [comment]
thanks @evlo
