### ISSUE TITLE
Default page based on role

### ISSUE THREAD

**Issue by aporzio1** [causefx/Organizr#1065]
###### Operating System: Debian
<hr>

I have a homepage for users and above but not for guest users, so currently they are brought to a blank page until they open a tab. Is there a way to set a default page for guest? I would like to be able to set a default for users and a different default for guest.

**Comment by christronyxyocum** [comment]
Not at this time, but the feature has been requested.

**Comment by causefx** [comment]
In the meantime, you can open up homepage itself to guest and use custom html to place a message for the guest.  I can write you some code to hide it from logged in users.

**Comment by causefx** [comment]
Actually, I already wrote the custom HTML for another user:

```
<script>
    if(activeInfo.user.groupID !== 999){
        var cssSettings = `
            .hidden-for-non-guest {
                display: none;
            }
        `;
        $('#guest-css').html(cssSettings);
    }
</script>
<style id="guest-css"></style>
<div class="hidden-for-non-guest">
    <h1>this is for Guests only</h1>
    <b>okay, thesadsan!</b>
    <h2>this is anotasdsadher</h2>
</div>
```
