### ISSUE TITLE
Plex Recently Added doesn't update.

### ISSUE THREAD

**Issue by calmcacil** [causefx/Organizr#1069]
###### Operating System: Unraid - Docker
<hr>

##### Problem Description:
I'm having an issue where my plex recently added does not update on the homepage, emby still works if I enable that but plex is stuck. Using the official docker image. 

##### Reproduction Steps:
I have only enable plex recently added, at which point its showing old cached data.

<hr>

#### Errors on screen?  If so paste here:

```
There are none that I could find looking in the logs.
```

**Comment by causefx** [comment]
This is a plex API issue.  They changed it in the last update...  I'm waiting to see if the fix it, if not I will have to do separate api calls per item type like how Tautulli is doing it now.

**Comment by causefx** [comment]
this is fixed - we did a workaround
