### ISSUE TITLE
[Feature Request] Timed refresh

### ISSUE THREAD

**Issue by eric-saintetienne** [causefx/Organizr#1071]
Hi,

How about the ability to periodically reload tabs? A per-tab configurable delay would be nice.

There are extensions to reload pages but they reload the organizr page as a whole, losing any context like which tab is openned or splitting.

If it already exists then please close this request and let me know how to use the existing auto-refresh functionality because I didn't find it anywhere in the organizr settings.

Thank you

**Comment by causefx** [comment]
Hmmmm... lemme think about this one...  I do have planned... timed tab closing.  May combine those.
