### ISSUE TITLE
LDAP Login against Active Directory

### ISSUE THREAD

**Issue by loibi** [causefx/Organizr#1074]
###### Operating System: /Ubuntu
<hr>

##### Problem Description:

tried to install php-ldap

then chose Authentication Organizr DB + Backend Ldap

Host Address ist ldap://IPOFDC:389

HostBaseDN is cn=%s,OU=User,OU=place,DC=domain,DC=com

Then when I try to login I just geht "wrong combi of user and password"

tried with user - domain\user - user@domain - nothing works
<hr>

##### Reproduction Steps:

<hr>

#### Errors on screen?  If so paste here:

```

```

**Comment by causefx** [comment]
can you try just this:

`cn=%s,dc=domain,dc=com`

**Comment by loibi** [comment]
tried - still the same error.
-Whats the correct Syntax for the User at the Login Page? user@domain?
-Do I have to create the User also inside organizr?

**Comment by causefx** [comment]
it’s supposed to be just user...  maybe i will install windows server in a vm later and test out getting AD to work... i do recall some people using it tho.

**Comment by loibi** [comment]
that would be great - tried several times with different settings today - just cant get it work.
for instance the Ubuntu Machine Organizr is running on can Authenticate with the AD without issues

**Comment by causefx** [comment]
fixed in latest commits.
