### ISSUE TITLE
[v2] Issue with menu CSS

### ISSUE THREAD

**Issue by STaRDoGG** [causefx/Organizr#1075]
Using **2.0.0-beta.980**

When I move the cursor over items in the menu, the items shift places, causing unwanted misclicks.

For example, I intend to click on Jackett, I end up clicking on SABNzbd instead. (unless I purposely wait long enough for the menu to open and shift, which I don't think is natural).

![organizrcapture](https://user-images.githubusercontent.com/1524526/53373825-30141200-391c-11e9-9ffd-b7995230a966.gif)

As you can see it starts happening around the 3rd menu item from the top.

Admittedly I use long names for menu items to help remind me what they do down the road, but it seems the menu should be dynamic enough to not be concerned about item name length, and just pop up as wide as it needs to.

Similar enhancement request: can you add a setting for us to choose a delay for the menu to pop open? i.e. I'd like for the menu not to open instantly on mouse over, but after a delay of say, 1000ms, but I think it should be customizable to the individual's preference rather than a hard coded 1000ms.

**Comment by causefx** [comment]
I will look into the animation...  for now you can use custom css

**Comment by causefx** [comment]
here is the custom css for ya:

```
@media (min-width: 768px)
.sidebar:hover {
    width: 240px;
    -webkit-transition: all 1s;
    transition: all 1s;
}
```

**Comment by jscottelblein** [comment]
Thanks.

I'm not real experienced with CSS so here's my hacky code to temporarily fix my issue. I'm sure someone with more experience in CSS can do a better job with it. It introduces 2 problems though;

1. The ping labels don't all line up like they should. I think they should all line up, floated to the far right of the hovered menu.
2. When keeping the menu hovered (open) each time the ping updates, the width of the menu doubles. I get around it for now by just not keeping the hovered menu open, lol.

```
.sidebar .label {
    font-size: 10px;
    border-radius: 60px;
    padding: 6px 8px;
    min-width: 30px;
    height: 20px;
    margin: 4px 0 0 14px; /* Last value keeps label edge from showing when sidebar isn't hovered */
}

@media (min-width: 768px) {
    .sidebar:hover {
        width: max-content; /* Allows full link + full ping label to be shown, however, introduces a bug as well. */
    }
}

/* .sidebar:hover .hide-menu {
    display: inline;
    margin-right: 10px;
}
*/
#side-menu>li>a {
    padding: 10px 100% 10px 15px; /* 2nd value allows hover background color to cover full width of menu when cursor is over an item */
    display: block;
    width: max-content; /* Places all individual items on their own single line */
    overflow: hidden;
}
```

Regarding the transition, I actually meant adding a delay between when you first pace the cursor over an icon in the closed menu, to when the menu actually opens/expands. i.e.  I mouse over the Plex icon, and a delay of 3 seconds passes before the :hover actually kicks in and the menu opens, so it's not an instant popup as it is now. the transition property from what I can tell just alters the speed at which the fully shown menu happens, but doesn't actually delay the actual showing of the hovered menu.

**Comment by STaRDoGG** [comment]
Btw, just out of curiosity, why was this issue closed if it wasn't actually fixed yet?

**Comment by jscottelblein** [comment]
DOH, just noticed you already added a fix, lol. I'm gonna go give that a try now instead of my own.

**Comment by causefx** [comment]
the delay is in the css i added. just change the 1s to 3s

let me know if my fix worked for u

**Comment by jscottelblein** [comment]
Almost perfect! There's still just a hint of an overlap of the ping time onto the link:

![image](https://user-images.githubusercontent.com/1524526/53621625-b77fb080-3bbc-11e9-8f6d-342d0bb5bb7b.png)
