### ISSUE TITLE
Error in header

### ISSUE THREAD

**Issue by matthewdavis** [causefx/Organizr#108]
I'm getting the following errors which is causing organizr to not function. It only displays a single entry on the side bar.

```
Notice: Undefined index: loading in /var/www/html/index.php on line 246

Notice: Undefined index: hovertext in /var/www/html/index.php on line 247
```

The code in question is:

```
            $loading = $row['loading'];
            $hovertext = $row['hovertext'];
```

If I remove/comment out those 2 lines it works just fine.

**Comment by causefx** [comment]
put a "@" in front of those for now.  or..... update the color theme and that should fix it.
