### ISSUE TITLE
Feature to disable/restrict debug area

### ISSUE THREAD

**Issue by Saduff** [causefx/Organizr#1080]
###### Operating System: Linux / Docker
<hr>

##### Problem Description:
There should be a setting to disable the debug area or restrict it to admins.
Should be restricted to (co-)admins by default.

<hr>

##### Reproduction Steps:
Log in with any user with any role. Click your name in the top right. Click Debug Area.

**Comment by tronyx** [comment]
I like that idea. Please submit a [FeatHub](https://feathub.com/causefx/Organizr) request and then close the issue.

**Comment by causefx** [comment]
should option be under customize or settings?

**Comment by tronyx** [comment]
I would think settings as that's where most debug switches are for other apps.
