### ISSUE TITLE
update from 2.0beta9 to 2.0.0 fail on debian stretch LXC container (PHP version issue)

### ISSUE THREAD

**Issue by tikismoke** [causefx/Organizr#1082]
###### Operating System: Debian
<hr>

##### Problem Description:
update from 2.0beta9 to 2.0.0 fail on debian stretch LXC container (PHP version issue)

<hr>

##### Reproduction Steps:
A working container with debian php 7.0 version
Update to stable 2.0.0
Udate done but fail to display anything and complains about php version

Php min version 7.1.3 is not available in debian stretch (at least in my current conf)
<hr>

#### Errors on screen?  If so paste here:
organizr complains about php 7 version not the correct one.
```

```

**Comment by causefx** [comment]
Debian 9?

**Comment by tronyx** [comment]
That's correct. This change was required for improved LDAP integration and you will need to upgrade the version of PHP that you have installed. We apologize for the inconvenience, but it's an unfortunate side effect of improving Organizr.

**Comment by causefx** [comment]
If you are unable to update to php 7.1.3+ then you can roll back if git was used to install or overwrite with this zip:

https://github.com/causefx/Organizr/archive/ea3ed475e2111c7612cc6bdf90926257add9b4e9.zip

**Comment by tikismoke** [comment]
I roll back easily with a proxmox backup of this container :)

Indeed I'm not able to install this version of php on Debian 9. I didn't take really time to add other Depot in fact it seems available but not with default's one.

**Comment by causefx** [comment]
Correct, we are updating the installer scripts to check if debian and install correct php now.  thanks for the catch,

**Comment by guydavis** [comment]
I also just encountered this on Ubuntu 16.04 LTS which defaults to PHP 7.0 when I upgraded  from the last Organzr v2 beta to the 2.0.0 release.  Needed to do the following:

```
sudo apt-get install software-properties-common
sudo add-apt-repository ppa:ondrej/php
sudo apt-get update
sudo apt-get install php7.1 php7.1-cli php7.1-common php7.1-json php7.1-opcache php7.1-mysql php7.1-mbstring php7.1-mcrypt php7.1-zip php7.1-fpm php7.1-sqlite3 php7.1-xml php7.1-curl
sudo systemctl stop php7.0-fpm.service
sudo systemctl disable php7.0-fpm.service
sudo systemctl restart php7.1-fpm.service
```

Changed path from 7.0 to `fastcgi_pass unix:/run/php/php7.1-fpm.sock;`  in `/etc/nginx/config/phpblock.conf` and restarted nginx.  Modified from this [blog post](https://www.rosehosting.com/blog/install-php-7-1-with-nginx-on-an-ubuntu-16-04-vps/).  Gave me `PHP 7.1.26` which loaded Organizr cleanly again.

Hope this helps any others on Ubuntu 16.04 who were running the v2 beta.  Kudos on Organizr v.2.0.0 final by the way!

**Comment by causefx** [comment]
thanks @guydavis for that, hope it finds someone searching for it :)

also, thanks for the kudos :)
