### ISSUE TITLE
Won't update

### ISSUE THREAD

**Issue by rickytin** [causefx/Organizr#1084]
Organizr Version: 2.0.0-BETA.980
Branch: Master
WebSever: Nginx
Operating System: Windows 10

I am trying to update, it download the file and then STARTING UNZIP and it go to 50% and it doesn't do anything else.
I have try many times to update.

**Comment by rickytin** [comment]
Download the OrganizrInstaller and reinstall it and it did the update .

**Comment by causefx** [comment]
I will revisit the update script.
