### ISSUE TITLE
[Security] Unauthenticated users can read debug area info

### ISSUE THREAD

**Issue by Saduff** [causefx/Organizr#1086]
###### Operating System: Linux / Docker
<hr>

##### Problem Description:
Related to #1080. Even though the debug area is hidden from the menu now, the info contained is sent to unauthenticated (Guest) users (also authenticated users) via the `GET /api/?v1/launch_organizr` response. All an attacker has to do is look at the JSON returned or use the console to run the "commands" you normally would in the debug area.

<hr>

##### Reproduction Steps:
1. Open Organizr as an unauthenticated (Guest) or as any authenticated user with no privilege to view the debug area.
2. Open the console (F12).
3. Type in `activeInfo` and press enter.

Now you get all the info you could get from the debug area. Plenty of useful info for an attacker such as the Organizr version, PHP version, install type (e.g. Docker), enabled plugins etc.

<hr>

Also a potential XSS vector in the debug area command input because the command is simply sent to `eval`. Type for example `alert(1)` there and hit enter. Only reason it can't be used for reflected XSS attacks is because an URL with the payload cannot be crafted (at the moment).

P.S. What's the procedure for responsible disclosure of security vulnerabilities in case I find more sensitive vulnerabilities in the future?

Edit to add: after a quick look, already found two high/critical vulnerabilities not suitable for immediate public disclosure.

**Comment by causefx** [comment]
either PM me (Discord) or email me causefx at me dot com

**Comment by causefx** [comment]
Fixed in Dev, will move to master today.
