### ISSUE TITLE
v2 nginx default install has wrong nginx error_page format

### ISSUE THREAD

**Issue by henrywhitaker3** [causefx/Organizr#1087]
###### Operating System: Debian
<hr>

##### Problem Description:
The auto installer for v2 sets the error_page to:
`error_page 400 401 403 404 405 408 500 502 503 504  /error.php?error=$status; #error page`
which is the v1 format so will always bring up a 404 error as error.php is not there. Fixed the issue by changing it to:
`error_page 400 401 402 403 404 405 408 500 502 503 504 $scheme://$server_name/?error=$status;`
as in the [wiki](https://github.com/causefx/Organizr/wiki/Authentication---Server-Based)
<hr>

##### Reproduction Steps:
Default install on linux from auto installer. In /etc/nginx/sites-available/organizr.local.conf

**Comment by causefx** [comment]
fixed with https://github.com/elmerfdz/OrganizrInstaller/pull/259
