### ISSUE TITLE
Deluge homepage no longer working after upgrade

### ISSUE THREAD

**Issue by torresdrew** [causefx/Organizr#1088]
###### Operating System: Linux
<hr>

##### Problem Description:
After upgrading from beta to 2.0 final deluge homepage item stopped working. When clicking test connection it states "Not Authenticated".

<hr>

##### Reproduction Steps:

<hr>

#### Errors on screen?  If so paste here:
Error code 1 not authenticated
```

```

**Comment by causefx** [comment]
what version were you on prior?  Is your egg file updated?

**Comment by torresdrew** [comment]
Updated the egg to 0.3.2 I was on the latest beta before upgrading, but after having other troubles I just did a clean install. This is the last issue I can't seem to work out.

**Comment by causefx** [comment]
I will get more people to test this.

**Comment by robflate** [comment]
I'm having the same issue;

Organizr version: 2.0.70
Deluge version: Linuxserver docker image with latest tag
WEBUI plugin egg file version: 0.3.2
Organizr error: Method requested returned an error (no. 1): Not authenticated

**Comment by Mikrz** [comment]
Just wanted to add that I was seeing this issue as well. I was getting a 403 response supposedly from Deluge on the auth.login call however once I changed from using a (newly setup) subdomain to a reverse-proxied subdirectory (from https://deluge.example.com to https://example.com/deluge). Deluge webui is still accessible via the subdomain and I can make manual CURL calls to the api through it from my desktop. It seems it might be some odd routing issue internally as direct IP connectivity is completely dead despite Deluge's docker being in host mode. I get "Host unreachable" errors instead.

Organizr version: Docker Image, 2.0.70
Deluge version: Linuxserver latest
WebUI egg: 0.3.2
Using Caddy webserver with "transparent" reverse proxy preset on both subdomain and subdirectory.

**Comment by causefx** [comment]
Good catch... also with the ongoing connectivity issues with deluge, i may be dropping support for it but will welcome PR's.

Thanks everyone.
