### ISSUE TITLE
Organizr has blocked the server's IP, preventing me from using it. (Server is on site)

### ISSUE THREAD

**Issue by Ryonez** [causefx/Organizr#1089]
###### Operating System: Docker
<hr>

##### Problem Description:

Can't add tabs, homepage won't load.
<hr>

##### Reproduction Steps:

Work on and add to many tabs. I've been heavily working on reverse proxy configs and have been reloading often.
<hr>

#### Errors on screen?  If so paste here:

Looking at the 'ORGANIZR LOGS', a whole bunch of:
```
ryonez | xxx.xxx.xxx.xxx | Killed Attack From [https://portal.xxx.xxx/]

```
https://portal.xxx.xxx/ is the url for the instance of Orginizr I run.

I can not find any way to reset or to add an exception to the ACL, and would be happy to disable it as my reverse proxy uses fail2ban itself.

**Comment by causefx** [comment]
Clear the cache...


You are on master?  That work was recently done on dev branch and is still being tested on.

**Comment by Ryonez** [comment]
"Clear the cache..."

Of what? My browser isn't the answer I'm sure, and I have no idea where to do that on the docker image.

It's come right now, but a way to manage/control it would be good.

"You are on master? "
Yes

**Comment by causefx** [comment]
yes the browser.  Code was added to function.js which i'm sure is cached.  

https://github.com/causefx/Organizr/blob/v2-develop/js/functions.js#L3291

load up the function.js?v=2.0.0 in your browser to verify that line

EDIT: What docker tag was used because 

```
ryonez | xxx.xxx.xxx.xxx | Killed Attack From [https://portal.xxx.xxx/]

```

that log entry isn't in Master yet

**Comment by Ryonez** [comment]
I'm sorry the anti spam feature is client side? I must not have a clear idea what attack means.

The docker image I currently use is: tronyx/docker-organizr-v2

**Comment by Ryonez** [comment]
Looks like I was using linuxservers image at one time, but changed to that for some reason.

**Comment by causefx** [comment]
ahhhh that is the old image.  need to see how that is pulling...

the new image is `organizrtools/organizr-v2`

that will put you back on master, right now you are somehow on dev.

if you want to stay on dev, use the tag: `dev-php-fpm`

as for that feature, it is about CSRF.  To not allow attackers to gain access to your org instance through hijacking your browser.  

EDIT* changed `attacked` to `attackers`

**Comment by Ryonez** [comment]
"it is about CSRF" Ahh, that makes more sense with the little I know of that, thank you.

I'm switching the image to sit in line with the main one now. And now I know how to reset the block, I'll close the issue. Thank you for your help!

**Comment by causefx** [comment]
No problem, let me know if the issue comes back.
