### ISSUE TITLE
Install on windows server

### ISSUE THREAD

**Issue by barbidule** [causefx/Organizr#109]
Hi,
I'm trying to install Organizr on a windows server 2016.
I installed sqlite and php 7, and modified php.ini to point to sqlite3
when trying to access Organizer I get this error : 
Fatal error: Uncaught PDOException: SQLSTATE[HY000] [14] unable to open database file in C:\inetpub\wwwroot\Organizr\user.php:168 Stack trace: #0 C:\inetpub\wwwroot\Organizr\user.php(168): PDO->__construct('sqlite:C:/inetp...') #1 C:\inetpub\wwwroot\Organizr\index.php(154): User->__construct('registration_ca...') #2 {main} thrown in C:\inetpub\wwwroot\Organizr\user.php on line 168

**Comment by causefx** [comment]
here ya go:

WINDOWS: Set you permissions on to Full Control for Everyonefor your directories

**Comment by barbidule** [comment]
Already did (on the Organizr folder).

**Comment by causefx** [comment]
is the db file and user folder in the Organizr folder or outside of it?  run check.php and see if anything is red.

**Comment by barbidule** [comment]
Thanks ! It was the parent folder of /Organizr who wasn't writable. Everything's working now !

**Comment by causefx** [comment]
Awesome :)
