### ISSUE TITLE
Custom icon uploading

### ISSUE THREAD

**Issue by dooz127** [causefx/Organizr#1090]
###### Operating System: Ubuntu
<hr>

##### Problem Description:
Custom icon uploading is not user friendly. Tried uploading different sized icons, 256x256, 200x200, and even a favicon.ico, but none of them "took." Icon uploader should automatically resize uploaded icons and allow you to crop.

<hr>

##### Reproduction Steps:
N/A

<hr>

#### Errors on screen?  If so paste here:

```
![image](https://user-images.githubusercontent.com/19983618/53711631-d322cb00-3df7-11e9-869f-deafa9f098f6.png)

```

**Comment by causefx** [comment]
That version of Organizr is no longer supported.

V2 was released this past Friday.
![image](https://user-images.githubusercontent.com/16184466/53711723-afb04e00-3e00-11e9-9b4c-dfabf3620197.png)

Unfortunately, there is no upgrade path to v2 as this was a complete rewrite.

**Comment by dooz127** [comment]
New version works great. Thanks!

**Comment by causefx** [comment]
thanks! :)
