### ISSUE TITLE
Clicking on iCal Calendar Item Locks Up GUI

### ISSUE THREAD

**Issue by HalianElf** [causefx/Organizr#1092]
###### Operating System: Ubuntu (Docker)
<hr>

##### Problem Description:

If you click on a calendar item that is from an iCal link, it does the overlay to dim out the background and just says "true" and prevents you from being able to do anything without refreshing the page.
<hr>

##### Reproduction Steps:

Click a calendar item from an iCal.
<hr>

#### Errors on screen?  If so paste here:

```
First click on calendar Item:
jquery.magnific-popup.min.js:4 Uncaught TypeError: b.content.find is not a function
    at t._setFocus (jquery.magnific-popup.min.js:4)
    at jquery.magnific-popup.min.js:4
Click on dimmed out page:
jquery-2.2.4.min.js:2 Uncaught TypeError: Cannot read property 'ownerDocument' of undefined
    at Function.fa.contains (jquery-2.2.4.min.js:2)
    at t._checkIfClose (jquery.magnific-popup.min.js:4)
    at HTMLDivElement.<anonymous> (jquery.magnific-popup.min.js:4)
    at HTMLDivElement.dispatch (jquery-2.2.4.min.js:3)
    at HTMLDivElement.r.handle (jquery-2.2.4.min.js:3)
```

**Comment by causefx** [comment]
any got an ical ink for me to test?

**Comment by HalianElf** [comment]
Yup! This is the one I've been using https://calendar.google.com/calendar/ical/pfutdblf1gi8jmfsvroh76f6jg%40group.calendar.google.com/public/basic.ics
