### ISSUE TITLE
LinuxServer.io - v2

### ISSUE THREAD

**Issue by homerr** [causefx/Organizr#1094]
###### Operating System: Docker
<hr>

##### Problem Description:

Hi there, maintainer of docker-organizr over at linuxserver.io here - is there any implication to updating our logic to pull from v2-master instead of v1-master? Thinking of existing users on v1 more than anything here.

We can either update :latest to be v2, or, add a :v2 tag if you'd prefer.
<hr>

##### Reproduction Steps:

<hr>

#### Errors on screen?  If so paste here:

```

```

**Comment by causefx** [comment]
Hi Homer...

Existing users will stay on v1 since there isn't any upgrade path.  With that being said, you are free to choose any process going forward with your image.

Thanks man.
