### ISSUE TITLE
Plex homepage items don't redirect to Plex when the tab name has special characters

### ISSUE THREAD

**Issue by perfectly-preserved-pie** [causefx/Organizr#1096]
I'm talking about the "Plex Play Button" on each media item under Recently Added Items.
That button doesn't redirect you to the specific Plex media item if (in my case) there are parentheses in the Plex tab name. 

This config **doesn't** work: http://bayimg.com/efd8d7b883c7cc901c2663440bbeeb77daabfb0a.jpg

This config **does** work: http://bayimg.com/2e771f9ed5c612b38fefcbd9d4a1d42db68edd86.jpg

In the console, I see a lot of `Error: Syntax error, unrecognized expression: #container-Plex (Watch Now)` whenever I click the Plex play button using the broken config.

I can also reproduce this issue when there's a hyphen in the Plex tab name.

**Comment by causefx** [comment]
Sorry about that, fixed in Dev

**Comment by perfectly-preserved-pie** [comment]
That was super fast, thanks! It's working for me now.
