### ISSUE TITLE
Calendar Highlighted Date Not Updating After Midnight

### ISSUE THREAD

**Issue by dshokouhi** [causefx/Organizr#1097]
###### Operating System: Windows 7
<hr>

##### Problem Description:

When the date changes the calendar on the homepage is not updating the highlighted date, user must refresh the tab for the highlighted date to change.  I remember when I first tried v2, after the beta announcement over a year ago, this issue was no longer present (as v1 had the same bug) but seems after some updates its no longer updating the selected date.
<hr>

##### Reproduction Steps:

1. Open up Organizr
2. Keep the home page open overnight (past 12am)
3. Observe how the calendar is still on yesterday
<hr>

#### Errors on screen?  If so paste here:

```

```
![image](https://user-images.githubusercontent.com/1634145/53894468-024a5f80-3fe5-11e9-8c09-d14b7e5c3638.png)

**Comment by causefx** [comment]
Hmmm, that is odd...  I will try and nail it down

**Comment by riqjuan** [comment]
this is still happening today on **2.0.325**

Any updates on this issue?

**Comment by causefx** [comment]
i think we need to reload the page, cant think of another way to do this.  For now set homepage to auto reload every couple of hours.
