### ISSUE TITLE
Accessing Tab Local URL via proxy while on local network 

### ISSUE THREAD

**Issue by jasonalsing** [causefx/Organizr#1098]
###### Operating System:  Ubuntu 18.04 LTS Running Docker
<hr>

##### Problem Description:

My Docker server is setup as described below, with Organizr (Docker) and all SERVICE containers (Docker) accessible via HOSTIP:PORT as well as reverse proxied via MYDOMAIN.COM/SERVICE

When I access Organizr via its HOSTIP:PORT, the tabs load via the TAB LOCAL URL as expected (confirmed by placing bogus URL in TAB LOCAL URL and seeing appropriate error)

When I access Organizr via MYDOMAIN.COM (Oranizr loads from the root level via proxy) tabs load via TAB URL as expected (also confirmed with bogus entry)

When I access Organizr via MYDOMAIN.COM WHILE ON MY LOCAL NETWORK (Same network as HOST,) tabs do not load. From the Chome Inspector I can see the HOSTIP:PORT in the source.

<hr>

##### Reproduction Steps:

1. Organizr V2 and multiple services (Sonarr, Radarr, etc.) accessible via HOSTIP:PORT
2. Organizr V2 and multiple services (Sonarr, Radarr, etc.) accessible via MYDOMAIN.COM/SERVICE via reverse proxy. 
3. Setup Organizr Tabs with services "Tab URL: MYDOMAIN.COM/SERVICE" and "Tab Local URL: HOSTIP:PORT
4. Access Organizr via MYDOMAIN.COM while on HOST network. 
<hr>

#### Errors on screen?  If so paste here:

```
Just black screen in iFrame area. 
```

**Comment by Roxedus** [comment]
This is not a "issue",  if you are using https on your domain. A http iframe wont load over a https site.

**Comment by tronyx** [comment]
The Internal Tab URL feature is great, in theory, but if you're doing things correctly to actually make sure that your setup is secure, it will not work as "designed".

**Comment by causefx** [comment]
@si0972 is correct.  I will have to think of a way to circumvent this....

**Comment by fedonr** [comment]
Hello @causefx , is this still the case or if you found a way to circumvent this issue ? As I have the similar issue, all my links are reverse proxied on HTTPs including Organizr which works great, there is only 1 HTTP link which is local and it won't work even if I'm on my LAN
