### ISSUE TITLE
REQ:  Make GitHub and Support movable

### ISSUE THREAD

**Issue by greengeek** [causefx/Organizr#1099]
###### Operating System: Windows Server 2012r2
<hr>

##### Problem Description:

It would be nice if the GitHub and Organizr Support links were found in the System Settings.  It would also be great if the current items, "Logout", "GitHub", and "Organizr Support", that are on the Tab could be in the Tab Editor so that we can move, group, or hide them.  When we start putting a lot of programs in the tab bar, that real estate becomes very limited.

Also a suggestion would be to add the Choose Language choice at the start of the installer, then after Organizr is installed to move it to the settings and remove it from the top bar.  

Thanks for you all your hard work on this program!!!!  It looks gorgeous and runs smoothly!
<hr>

##### Reproduction Steps:

<hr>

#### Errors on screen?  If so paste here:

```

```

**Comment by causefx** [comment]
regarding GH and Org Support, I can make a toggle to hide those...  As for Language, i cannot move to settings as regular users wouldn't have access it to it there.

**Comment by greengeek** [comment]
That makes sense.  It would be nice to free up some space by moving GH and Org Support

**Comment by tronyx** [comment]
In the meantime you can do this with custom CSS:

```
/*Hide Sign Out, Github and Support buttons in nav*/

#side-menu>.devider, .nav #menu-Organizr-Support{
    display: none;
}
```

**Comment by statik1983** [comment]
@causefx Have you added this feature yet?  I am not seeing it.

**Comment by causefx** [comment]
this was added sometime last year
