### ISSUE TITLE
Mobile View to tight for plex

### ISSUE THREAD

**Issue by rix1337** [causefx/Organizr#11]
Plex can be browsed fine on a mobile device, since it is not limiting the viewport.

Organizr does limit the vertical scrolling ability (and righteously so), but thus makes checking the plex website a true pain.

Is there a way to disable the mobile view size for the iframe (and only for select sites)?

Screenshot:
http://i.imgur.com/G1jDRc5.png

Also, the mobile site has a blue border frame. That should change with the theme.

*OT: I am spamming you with these requests, because organizr works so well for my Server needs! Within 12 hours it has completely replaced my previous setup.*

**Comment by rix1337** [comment]
http://i.imgur.com/G1jDRc5.png

**Comment by causefx** [comment]
Uh oh. That's not good. Hmmmm. This is going to be a tough one.

**Comment by rix1337** [comment]
It's actually a plex related issues. All other tools properly show mobile sites..

**Comment by causefx** [comment]
I don't know if that's a good or bad thing for me Haha.

**Comment by causefx** [comment]
Issue on Plex end, won't be able to fix

**Comment by rix1337** [comment]
Figured as much :/ Thx for trying!

**Comment by causefx** [comment]
no problem :)
