### ISSUE TITLE
Plugin page broken

### ISSUE THREAD

**Issue by ghost** [causefx/Organizr#1100]
###### Operating System: Ubuntu
<hr>

##### Problem Description:

Plugins display is slightly broken so cannot activate plugin (since newest release) not sure if its a me problem but happening on 2 different servers/installs 

<hr>

##### Reproduction Steps:

Install,
Settings,
plugins,
see screenshot bellow

<hr>

#### Errors on screen?  If so paste here:

```

```
![org_plugins](https://user-images.githubusercontent.com/42412447/53949396-dd77ea00-40c1-11e9-9136-665356bed677.png)

**Comment by GilbN** [comment]
Which browser are you using?

**Comment by ghost** [comment]
Chrome, I just tried on chrome on my phone and only speedtest was available to click on because it was on second row bellow the rest, so it was shown properly

Worked on my current browser until the latest update.

**Comment by GilbN** [comment]
Tried to clear cache / delete all cookies/browser data?

**Comment by ghost** [comment]
yeah I did, works fine on android firefox tho

**Comment by causefx** [comment]
are there any browser extensions installed?

I just tested with 3 browsers and they work fine.
