### ISSUE TITLE
Custom Javascript Not reliable

### ISSUE THREAD

**Issue by Logvin** [causefx/Organizr#1102]
###### Operating System: Ubuntu
<hr>

##### Problem Description:

Per @causefx recommendation, I added the following code to my Custom Javascript. It worked at first, but no longer does. I've also noticed that the code I put in gets changed at some point, with things like line breaks and html code disappearing. I will point out that my goal of showing the user's IP address never worked. It would simply print "Your IP address is:[object Object]", something I had not figured out, but can't figure out now because the Javascript isnt working anymore.

```
// Login box Custom JS
//var customHTML = 'Some friendly information for you:My hostname is: log.vinMy IP address is: 5.9.136.142Your IP address is:' + 'test' + 'The standard KORE internal SIP outbound NAT range is: 207.189.176.x';
if(activeInfo.user.loggedin === false){
    window.onload = checkForLoginBox;
}
var reset = 0;
function checkForLoginBox(){
    reset++;
    if ($('.login-box').length == 1) {
        var userIP = activeInfo.settings.user.ip;
        var customHTML = 'Some friendly information for you</br>My hostname is: log.vin</br>My IP address is: 5.9.136.142</br>Your IP address is:' + $(userIP) + '</br>The standard KORE internal SIP outbound NAT range is: 207.189.176.x';
        $(customHTML).appendTo($('.login-box .white-box'));
    } else if(reset <= 20) {
        setTimeout(function() {
            checkForLoginBox();
        }, 100);
    }
}
```
<hr>

##### Reproduction Steps:

Took the code @causefx posted on Reddit, tweaked it a bit. Can't even get his test code working anymore.
https://www.reddit.com/r/organizr/comments/awdb8w/wow_love_organizr_20_i_have_a_question_possible/
<hr>

#### Errors on screen?  If so paste here:

```

```

**Comment by causefx** [comment]
this is what i have @ https://dev.organizr.app

```
// Login box Custom JS
if(activeInfo.user.loggedin === false){
    reset = 0;
    console.log('user not logged in');
    window.onload = checkForLoginBox();
}
function checkForLoginBox(){
    console.log('resetting for the ' + reset + ' time');
    reset++;
    if ($('.login-box').length == 1) {
        var customHTML = '<div class="white-box">Your IP sucka - ' + activeInfo.settings.user.ip + '</div>';
        $(customHTML).appendTo($('.login-box .white-box'));
    } else if(reset <= 20) {
        setTimeout(function() {
            checkForLoginBox();
        }, 100);
    }
}

```

**Comment by Logvin** [comment]
OK, so looking at the code I pasted, the DIV tags were missing. I absolutely 100% had them in there orginally. They are getting parsed out at some point.

I'm saving my code out exactly how it is now (which is working btw) and I'll give it a few days.

**Comment by causefx** [comment]
the code was saving weird before i fixed the ace box

**Comment by causefx** [comment]
open this back up if you are having the same issue
