### ISSUE TITLE
Calendar does not show recurring events

### ISSUE THREAD

**Issue by vagamens** [causefx/Organizr#1104]
###### Operating System: Ubuntu 16.04
<hr>

##### Problem Description:
I have been trying to setup the calendar item for the homepage for a while. I have several calendars setup in it. They all show properly, but only for one-off events. It does not properly show recurring events. I am using Google Calendar for the calendars.

<hr>

##### Reproduction Steps:
Open Settings -> Tab Editor -> Homepage Items -> Calendar
Enable iCal, add an iCal URL, click Save
Create an event in the calendar.
Create a second event in the calendar, set it to recurring. Frequency doesn't matter, preferable something frequent so that it can be seen what it is doing.

The first recurring event should so up, but subsequent events do not, especially if the first event was quite some time in the past, such that the calendar widget does not collect it as part of its query.

**Comment by causefx** [comment]
@rob1998 want to look at this or shall I?

**Comment by causefx** [comment]
I just added a google event to repeat.... but google doesnt supply any repeat info in the ICS file:

```
BEGIN:VEVENT
DTSTART:20190328T223000Z
DTEND:20190328T233000Z
DTSTAMP:20190327T170826Z
UID:**********************@google.com
CREATED:20190327T170412Z
DESCRIPTION:
LAST-MODIFIED:20190327T170412Z
LOCATION:
SEQUENCE:0
STATUS:CONFIRMED
SUMMARY:repeating-test
TRANSP:OPAQUE
END:VEVENT
```
