### ISSUE TITLE
Email php plugin issues

### ISSUE THREAD

**Issue by fitzy2211** [causefx/Organizr#1105]
Version: 2.0.49
Branch: v2-master
Server OS: win
PHP: 7.3.0
Install Type: Native
Theme: Organizr
<hr>

##### Problem Description:
When using organizr on my mobile phone browser, I'm unable to the email centre correctly. 

It loads fine but when trying to insert a template, the template selection window is displayed too big for the screen size so I cannot see or scroll to the confirmation button. Pressing back also doesn't remove the template selection window. 

<hr>

##### Reproduction Steps:
1.On your mobile phone be on organizr homepage
2.Select your user name icon in top corner to show drop down of options
3.Choose "e-mail centre"
4.When new email box pops up, select insert template button and then issue occurs

<hr>

#### Errors on screen?  If so paste here:
no errors are shown

**Comment by causefx** [comment]
What mobile browser?  I was able to scroll with that pop up on iOS safari.  you have to scroll on the headed of popup
