### ISSUE TITLE
Password no longer works after upgrade

### ISSUE THREAD

**Issue by greengeek** [causefx/Organizr#1106]
###### Operating System: Windows Server 2012r2
<hr>

##### Problem Description:

I just performed the latest upgrade that Organizr just alerted that came out.  It claimed the download and install were successful.  I logged out and back into Organzr and it is a login error, invalid email, username, password combo.   Verified it with multiple browsers, with plugins disabled, and even with a password manager that had the saved password that worked properly before the update.  
<hr>

##### Reproduction Steps:

<hr>

#### Errors on screen?  If so paste here:

```

```

**Comment by greengeek** [comment]
Any ideas on how to get back in?  I rather not have to configure everything all over again.  I see that the config was backed up during the upgrade process, and that database appears to have been written to at that same time as the time stamp matches that of the backup config.  However there is not a backup database file.  Is there something I can change in the database or the config file to get back in?

**Comment by causefx** [comment]
did you setup the phpmailer plugin by any chance?

**Comment by greengeek** [comment]
i did not

**Comment by greengeek** [comment]
I turned on guest registration in the config file, used the registration password, the same that matched in the config file, and tried creating another account.  Nothing happens when I click the Login button.  No error or anything.  However the log files show:

`"message":"API ERROR: Unable to authenticate Form Key......`

and 

`"message":"Killed Attack From [https:....`

**Comment by causefx** [comment]
did you happen to set up plex or emby as a backend?

**Comment by greengeek** [comment]
I have plex setup and the Organizr home page pulling info from it.  I dont think I have SSO turned on.

**Comment by greengeek** [comment]
I got very lucky.  I found a machine that had a browser that I was still logged into.  I was able to change it from there.

**Comment by causefx** [comment]
by any chance do you know what version you are on?

**Comment by OrganicKobze** [comment]
I also have this issue. However, I do not have the luxury of a browser that is still logged in. Does anyone have any ideas?

**Comment by causefx** [comment]
can you check organizrlog.json?

**Comment by OrganicKobze** [comment]
It's saying 'timed out'. Also that I have failed to sign in with the correct password.

It also won't let me connect through ip/organizr or using duckdns.... My webserver is running. I'm not sure if that might be a separate issue.

**Comment by greengeek** [comment]
Mine is 2.0.49

**Comment by causefx** [comment]
this is very odd as nothing has changed in the login script.  @OrganicKobze do you have AnyDesk so i can remote in and troubleshoot?

**Comment by OrganicKobze** [comment]
Hey cause, I seem to have fixed it by restarting. Which is odd because my weekly restart would have taken place a couple of hours before!

**Comment by causefx** [comment]
thats so weird....  no clue what the heck is going on
