### ISSUE TITLE
Thinking about upgrading to v2

### ISSUE THREAD

**Issue by deg0nz** [causefx/Organizr#1111]
Hi, V2 looks really nice and I'd really like to upgrade.

But I use the `auth_request` solution from #141.
Is the auth file still available in V2, so I can leave my nginx config more or less as it is?

thanks and greetings
Beh

**Comment by Roxedus** [comment]
Did it cross your mind to check the [wiki](https://github.com/causefx/Organizr/wiki/Authentication)?

**Comment by deg0nz** [comment]
Ahh alright thank you very much!
No, my fault, didn't think of the wiki. Shame on me!
