### ISSUE TITLE
Request for available movies show as unavailable

### ISSUE THREAD

**Issue by fritzgeralds** [causefx/Organizr#1112]
###### Operating System: Raspian Stretch Lite
<hr>

##### Problem Description:
Requesting a movie already in Plex library from Ombi section on Homepage tab gives an error popup that the movie is already being monitored but, then adds the movie to request section and displays as unavailable.

<hr>

##### Reproduction Steps:
Configure Plex, Radarr, and Ombi homepage items.
Load homepage and click magnifying glass on requests section.
Search for a movie which you already have and click request.

<hr>

#### Errors on screen?  If so paste here:

```

```

**Comment by Roxedus** [comment]
So the request gets sent to ombi?

**Comment by fritzgeralds** [comment]
Yes, request processes and goes to Ombi but doesn't update showing that it's available. Bottom left of the popup shows "approved" and "unavailable". However, I requested a movie I just got done watching just to see what happens if you request something you already have. Requesting directly in Ombi errors out saying you already have it, Organizr will still pass it to Ombi somehow.

**Comment by Roxedus** [comment]
What version of ombi do you have?

**Comment by fritzgeralds** [comment]
Version	3.0.4256
Branch	master

**Comment by Roxedus** [comment]
Huh. You are correct, that does seem to be the case. This is a reintroduced bug.

**Comment by causefx** [comment]
it’s up to Ombi to error out.... I just pass the request over...

**Comment by fritzgeralds** [comment]
Ok. Can a toggle be added to hide the magnifying glass on the Requests header? That seems to be the confusion point for my users. Using the "Search my media" on the top bar will return available results and give an option to request something not found. Using the Ombi search just returns what you searched for giving no notice if it's available or not, understood that info is just being passed to Ombi and isn't a bug with Organizr.

If it's not an easy code change or not really a pain point for other users, I can dig through the code and remove it for myself.

**Comment by Roxedus** [comment]
The best solution is for ombi to fix the issue in the first place.

Sendt fra min iPhone

15. mar. 2019 kl. 17:19 skrev fritzgeralds <notifications@github.com<mailto:notifications@github.com>>:


Ok. Can a toggle be added to hide the magnifying glass on the Requests header? That seems to be the confusion point for my users. Using the "Search my media" on the top bar will return available results and give an option to request something not found. Using the Ombi search just returns what you searched for giving no notice if it's available or not, understood that info is just being passed to Ombi and isn't a bug with Organizr.

If it's not an easy code change or not really a pain point for other users, I can dig through the code and remove it for myself.

**Comment by causefx** [comment]
if you want to hide you can use custom css, i will get you the class soon once i get to computer.

**Comment by fritzgeralds** [comment]
causefx:
Thanks, I'll go the custom css route. The class would be helpful if it's not too much trouble. I don't mind finding it though.

si0972:
I'm in agreement with you and will cross post this on the Ombi GitHub.

**Comment by causefx** [comment]
@fritzgeralds 
```
#newRequestButton {
    display: none;
}
```
