### ISSUE TITLE
Ombi not connecting (token/API issue?)

### ISSUE THREAD

**Issue by mhbates** [causefx/Organizr#1113]
###### Operating System: Debian
<hr>

##### Problem Description:
Ombi fails to connect. When testing the connection, it throws an API Connection Failed error; curl error 28, connection timed out. Using Ombi's API key under both SSO settings and homepage item settings.

**Comment by HalianElf** [comment]
Do you have http:// in the URL box?

**Comment by mhbates** [comment]
Yes, and the correct port.

**Comment by HalianElf** [comment]
What's your setup look like - same box, dockers, ect?

**Comment by mhbates** [comment]
Yep, Ombi's on the same box. Docker for both.

**Comment by HalianElf** [comment]
Are you using the host IP for the URL and if so are you running a firewall that could be preventing it?

**Comment by mhbates** [comment]
Ah, opening up the port in UFW did it. Strange, Ombi looks to have been functioning just fine without having its port forwarded. Thanks for your help.
