### ISSUE TITLE
[Feature Request] Option to make iFrame 'read only' for users

### ISSUE THREAD

**Issue by XDGFX** [causefx/Organizr#1115]
It seems like there are a few ways to make iFrames 'read only' - where no mouse clicks are registered and no information can be changed, using CSS or other means.

An option to make tabs 'read only' for certain user groups would be really useful as you could allow users to view stuff like Deluge Web UI, Jackett, or Chronograf dashboards without them being able to change or fiddle with anything.

Of course it would need to be fairly robust; a few solutions which added a transparent element on top of the page could probably be bypassed with any ad blocker.

**Comment by Roxedus** [comment]
Deluge has a homepage item. What is interesting with a readonly of jackett? just bragging about the amounts of trackers? Chronograf has a readonly opotion.

**Comment by XDGFX** [comment]
I was unaware about Deluge, I'll look into that - though having different pages would mean the admins would have two tabs instead of one.

For jackett, yup that and users can check if trackers are down, and get an indication of limited download availability.

I've been looking but can't work out how to enable it; it seems there are read-only users but that would still require people to log-in where I really just want it visible to anyone

**Comment by causefx** [comment]
while this option would be cool - I don't see a practical way for this to be implemented as all solutions can be thwarted.
