### ISSUE TITLE
SSO doesn't work

### ISSUE THREAD

**Issue by G4Zz0L1** [causefx/Organizr#1116]
###### Operating System: Arch Linux
<hr>

##### Problem Description:
I think that there's some problem with the SSO, when I login to Organizr I see this in the log

![image](https://user-images.githubusercontent.com/13220636/54477529-08bcb080-4809-11e9-93af-cc630f0af67c.png)

But Plex, Tautulli or Ombi are logged off, and I've to relogin each service every time. Do you have some idead on how to debug this?

**Comment by Roxedus** [comment]
We have a guide. https://docs.organizr.app/books/setup-features/page/sso

**Comment by G4Zz0L1** [comment]
Oh, I didn't know that link, thanks. So, it looks like I've to have the Plex authentication active for the SSO, but what if I don't want users to use the Plex account to log in?

**Comment by Roxedus** [comment]
As long as the username and password are the same in ombi and organizr it should work.

**Comment by G4Zz0L1** [comment]
I mean that I don't want the users to have 2 possibility for login, like this.
![image](https://user-images.githubusercontent.com/13220636/54477793-59350d80-480b-11e9-9246-11243a5bd63d.png)

I've disabled the Plex Auth because I don't want 2 login form, but only the Organizr one, but if I disable the Plex Auth the SSO doesn't work.

Still, even with Plex Auth enabled, Plex and Tautulli SSO works, Ombi one still fails with the same error
![image](https://user-images.githubusercontent.com/13220636/54477821-b204a600-480b-11e9-988a-6a484b378670.png)

**Comment by Roxedus** [comment]
Is ombi on a subdomain?

**Comment by G4Zz0L1** [comment]
Nope, it's like localhost/ombi, like in the wiki

**Comment by causefx** [comment]
read the ombi tips in the docs

**Comment by Roxedus** [comment]
so ombis taburl is "localhost/ombi"?

**Comment by G4Zz0L1** [comment]
> so ombis taburl is "localhost/ombi"?

Exactly, my url is like that

> read the ombi tips in the docs

Everything in the ombi section is the same as my configuration, either in Organizr and Ombi

In the debug section in Organizr, the Ombi SSO command seems to work just fine, though

![image](https://user-images.githubusercontent.com/13220636/54479754-9ce64200-4820-11e9-9cb2-812b5ec4ed62.png)

**Comment by causefx** [comment]
it sounds like the user type may not be plex user in ombi. can you confirm?

**Comment by G4Zz0L1** [comment]
My user is like that on Ombi

![image](https://user-images.githubusercontent.com/13220636/54480181-90181d00-4825-11e9-8adc-ccb20d2a28a1.png)

Still when I login on Organizr, I have to login also to Ombi.

There is a method to enable the Plex Auth, so the SSO can work, but to exclude the Plex login in the home page?

**Comment by causefx** [comment]
does the username match in organizr from ombi?
also email and password?

if not using Oauth, all three need to match exactly.

**Comment by G4Zz0L1** [comment]
Yep, cheched right now. I've also tried to create a new user with the same username, email and password, still the same error

![image](https://user-images.githubusercontent.com/13220636/54484453-929b6680-4867-11e9-89a1-4d840369d345.png)

**Comment by G4Zz0L1** [comment]
After some digging in the code I've found the culprit: for unkown reason, the other SSO work ok even if the url ends with a slash, but Ombi doesn't like it.

I've opened a PR to fix this case https://github.com/causefx/Organizr/pull/1117
