### ISSUE TITLE
[V2 Request] Pop-out button for tab iframes

### ISSUE THREAD

**Issue by mhbates** [causefx/Organizr#1118]
It would be nice to be able to have tabs load as iframes initially, but with an option to pop out into a new browser window/tab as needed. Perhaps a pop-out button next to the refresh and close buttons.

**Comment by causefx** [comment]
ctrl+click on the tab

**Comment by mhbates** [comment]
Well that solves that. Thank you!

**Comment by causefx** [comment]
:)
