### ISSUE TITLE
[v2] Showing Update available even though up to date?

### ISSUE THREAD

**Issue by jscottelblein** [causefx/Organizr#1120]
I noticed the announcement that v2 was officially out, so I deleted my dev branch container, and grabbed the v2 master branch container. (docker pull organizrtools/organizr-v2)

Ran it and when visiting the main page I get this:

![Clipboard Image](https://user-images.githubusercontent.com/1524526/54804082-458d0b00-4c40-11e9-86ec-b38046bc50f7.png)

Looking at the current latest releases, the latest is indeed 2.0.70. Am I bugged? lol

**Comment by GilbN** [comment]
@STaRDoGG  check container logs

Remove `index.lock`if it tells you to. 
Restart container.

**Comment by jscottelblein** [comment]
Did the trick! thanks
