### ISSUE TITLE
Menu overlapping

### ISSUE THREAD

**Issue by GroupMaster** [causefx/Organizr#1122]
###### Operating System: Debian latest
<hr>

##### Problem Description:
When categories are used, the contents of a category expand without adjusting the current menu causing overlapping icons. This has happened with the last several versions and not limited to the latest version.

<hr>

##### Reproduction Steps:
1-Create category A with several menu items within.
2-Create category B with several menu items within below category A.
3-Expand and select one item in category A so it loads in the main window.
4-Collapse category A, do NOT close the page loaded into the main window.
5-Expand category B and open one of it's menu items into the main window.
6-Use the X (Close frame contents) at the top of the page while the site from category B is sill displayed. IF NEEDED, repeat using the X until the site in category A is shown in the main window.

This will cause category A to expand and the main window to display the first site loaded from step 3. Category A will then automatically expand to show all its menu items, one of which is for the foreground site, however the menu items below fail to adjust for this change. You should now have overlapping menu items.

![organizr SS](https://user-images.githubusercontent.com/34816464/54883644-2cea4400-4e3e-11e9-9c23-08cd19f1c549.png)

<hr>

#### Errors on screen?  If so paste here:

```

```

**Comment by GroupMaster** [comment]
HalianElf reported that they could reproduce the issue as outlined above.

**Comment by causefx** [comment]
this should be fixed in dev now.

**Comment by GroupMaster** [comment]
I will test it out tonight. Thanks for the update.

**Comment by GroupMaster** [comment]
Good to go. The menu expands upon activation of the hidden tab. :-) cheers.

**Comment by causefx** [comment]
awesome!  thanks for testing.
