### ISSUE TITLE
Organizr update from 2.0.0-beta.980 to 2.0.70 failed

### ISSUE THREAD

**Issue by ptitsnake** [causefx/Organizr#1125]
###### Operating System: Debian 9
<hr>

##### Problem Description:
Hello, I try to install the last update "2.0.70", I was in " 2.0.0-beta.980". And I get an error  "Syntax error unexpected token JSON...."

<hr>

##### Reproduction Steps:
I get the popup to update Organizr, the tab refresh but never finish to install the update. 
When I try to refresh the windows, I get the "Syntax error unexpected token JSON...."

<hr>

#### Errors on screen?  If so paste here:
"Syntax error unexpected token JSON...."
![image](https://user-images.githubusercontent.com/29523073/55025047-666aad00-5000-11e9-80b5-882b94507e0e.png)

**Comment by tronyx** [comment]
The update function in that version had problems that have since been fixed. Backup your database file and config.php file and just download and extract the zip of the files again.

**Comment by ptitsnake** [comment]
I have install the last zip of organizrr.

But now I get this error : 

> Organizr needs PHP Version: 7.1.3
> You have PHP Version: 7.0.33-0+deb9u3
> 

But I have update PHP to the 7.3.3 version : 
```
root@PI2-Ombi-Organizrr:~# php --version
PHP 7.3.3-1+0~20190307202245.32+stretch~1.gbp32ebb2 (cli) (built: Mar  7 2019 20:22:46) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.3, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.3-1+0~20190307202245.32+stretch~1.gbp32ebb2, Copyright (c) 1999-2018, by Zend Technologies
```

**Comment by causefx** [comment]
Wait, I'm confused...  How is organizr installed...?  You listed Synology Docker

What docker image is being used?

**Comment by ptitsnake** [comment]
Sorry, it was my old setup that was under Docker. 

This one is installed on a RPi2 under Debian 9.

**Comment by causefx** [comment]
Oh ok.  Since you updated php you need to update the path to the correct sock in the nginx config file.
find your php block in nginx...
```
location ~ \.php$ {
	fastcgi_split_path_info ^(.+\.php)(/.+)$;
	fastcgi_pass unix:/var/run/php7-fpm.sock;
	fastcgi_index index.php;
	include /etc/nginx/fastcgi_params;
}
```
we need to modify the line 

```
fastcgi_pass unix:/var/run/php7-fpm.sock;
```
to the correct name...

might be `php7.3-fpm.sock` or something... check the www.conf file in the php dir

**Comment by ptitsnake** [comment]
Thank you for your help CauseFX I managed to configure the file "config / organizr.local / phpblock.conf" by declaring the new version of php7.3.

But now when I restart the site I have the following message:
502 Bad Gateway
nginx / 1.10.3

And in the error_log file I get : 
2019/03/26 21:58:44 [crit] 403#403: *1 connect() to unix:/run/php/php7.3-fpm.sock failed (2: No such file or directory) while connecting to upstream, client: _MY_IP_ADDRESS_, server: www.organizr.local, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.3-fpm.sock:", host: "_my_domain_name_"

**Comment by causefx** [comment]
find the correct file name from www.conf in the php folder.

**Comment by ptitsnake** [comment]
Thanks I have simply, stop php7 and start php7.3 and install phpsqlite3.

Now the Organizrr interface is working properly again and I am in version 2.0.70.

Thank you for your help, and your response is super fast and almost instantaneous.

Great job and thank you again.

**Comment by causefx** [comment]
awesome!!!! good stuff :)

**Comment by ptitsnake** [comment]
I also had to add one of these two lines to increase the timeout at the start of the php7.3-fpm service.
File "/etc/systemd/system/multi-user.target.wants/php7.3-fpm.service" adding lines:
TimeoutStartSec = 300s
TimeoutStopSec = 300s
In the "Service" block

Now everything works correctly (even after a reboot).
