### ISSUE TITLE
No more split screen in V2 ?

### ISSUE THREAD

**Issue by Dazzler1985** [causefx/Organizr#1126]
###### Operating System: Ubuntu
<hr>

##### Problem Description:
I have installed v2 with succes but i mis a function or cant find out how to get it to work. I used the splitscreen function allot with my live tv backend so would be awesome if its still in there , if so could you point me in the right direction ? 

<hr>
<hr>

**Comment by causefx** [comment]
ATM, it is not there.  I may add it in the future but the general consensus was that most people didn't use it.  If people do want it, i will consider adding it back :)

**Comment by tronyx** [comment]
Feel free to submit a feature request on [FeatHub](https://feathub.com/causefx/Organizr), but for now we should close this out.

**Comment by jscottelblein** [comment]
+1 from me. I liked the split screen feature. =)

**Comment by Dazzler1985** [comment]
Close it i added it on feathub

**Comment by toxic0berliner** [comment]
+1 from me, also done on feathub ;)
Hope it could come back in even better shape than it was ;)
And congrats anyway on a great software !
