### ISSUE TITLE
Can't get Jackett tab working in Firefox

### ISSUE THREAD

**Issue by seanbaker74** [causefx/Organizr#1130]
###### Operating System: Ubuntu
<hr>

##### Problem Description:

I'm not able to get the Jackett url to work correctly in Firefox or Opera, but it does seem to be working in Chrome. I have Jackett behind an Apache2 reverse proxy. Other URLs in Firefox and Opera work correctly (Sonarr, Radarr, Tautulli, etc).

I'm seeing this error in the Firefox console:

Blocked loading mixed active content “http://tv.domain.com/jackett/UI/Login?ReturnUrl=%2Fjackett%2FUI%2FDashboard”

I'm guessing it's objecting to the mixing of http and https content on the same page, but I'm not sure how to figure out where the mismatch is occurring. Sonarr/Radarr/Tautulli are configured the same way as Jackett.

I'm not sure why it's using http://tv.domain.com/jackett, since the Jackett URL I configured is using https://tv.domain.com/jackett

<hr>

##### Reproduction Steps:

<hr>

#### Errors on screen?  If so paste here:

```
```

**Comment by seanbaker74** [comment]
Some additional info on this issue. I'm able to re-produce and fix the issue with the following steps. The fix is temporary, I have to perform these steps each time I close and open Firefox.

1. Open a Firefox private/incognito window
2. Open https://tv.domain.com in Firefox, which re-directs to https://tv.domain.com/organizr
3. Navigate to Jackett tab. I get a blank page and the web console shows the error: Blocked loading mixed active content “http://tv.domain.com/jackett/UI/Login?ReturnUrl=%2Fjackett%2FUI%2FDashboard”
4. Open a separate tab and navigate to “http://tv.domain.com/jackett/UI/Login?ReturnUrl=%2Fjackett%2FUI%2FDashboard”. This URL re-directs to https, since I  have a separate Apache site that permanently redirects all http://tv.domain.com traffic to https://tv.domain.com. The Jackett URL displays correctly.
5. Now go back to the Organizr Jackett tab, refresh, and it works correctly.

So I guess I don't know why the re-direct isn't working directly within Organizr without having to open the Jackett URL directly in a separate tab first. Also, I don't know where it's getting http://tv.domain.com/jackett to begin with, since the Jackett tab that I have configured in Organizr is pointing to https://tv.domain.com/jackett.

**Comment by causefx** [comment]
can you post your proxy config?

**Comment by seanbaker74** [comment]
Sure thing...

Here's the re-direct site:
```
<VirtualHost *:80>
        ServerName tv.domain.com
        Redirect permanent / https://tv.domain.com/
</VirtualHost>
```

And here's the ssl site:
```
<VirtualHost *:443>
    ServerName tv.domain.com
    SSLEngine On
    SSLProxyEngine On
    ProxyPreserveHost On
    SSLProxyVerify none
    SSLProxyCheckPeerCN off
    SSLProxyCheckPeerName off
    <IfModule mod_headers.c>
      Header always set Strict-Transport-Security "max-age=15552000; includeSubDomains"
    </IfModule>
    SSLCertificateFile /etc/letsencrypt/live/tv.domain.com/fullchain.pem
    SSLCertificateKeyFile /etc/letsencrypt/live/tv.domain.com/privkey.pem
    Include /etc/letsencrypt/options-ssl-apache.conf
    RedirectMatch ^/$ /organizr/
    <Location "/organizr">
        Order deny,allow
        Allow from all
        AuthType Shibboleth
        ShibRequestSetting requireSession true
        Require shib-attr uid user1
        rewriteEngine on
        RewriteRule ^/organizr$ https://tv.domain.com/organizr/ [R=301,L]
        RewriteCond %{HTTP_REFERER} "https://tv.domain.com/organizr/"
        RewriteCond %{REQUEST_URI} !^/organizr
        RewriteRule ^(.*)$ /organizr$1 [R=301,L]
        ProxyPass https://organizr.localdomain/
        ProxyPassReverse https://organizr.localdomain/
    </Location>
    <Location "/sonarr">
        Order deny,allow
        Allow from all
        AuthType Shibboleth
        ShibRequestSetting requireSession true
        Require shib-attr uid user1
        ProxyPass http://sonarr.localdomain:8989/sonarr
        ProxyPassReverse http://sonarr.localdomain:8989/sonarr
    </Location>
    <Location /jackett>
        order deny,allow
        allow from all
        AuthType Shibboleth
        ShibRequestSetting requireSession true
        Require shib-attr uid user1
        ProxyPass http://jackett1.localdomain:9117/jackett
        ProxyPassReverse http://jackett1.localdomain:9117/jackett
    </Location>
</VirtualHost>
```

**Comment by Ultraguy24** [comment]
Hey, I've recently had the same issue with firefox.

When attempting to access jackett via reverse proxy (through Organizr or just by going to www.domain.com/jackett) I receive this in the browser console

> The character encoding of the plain text document was not declared. The document will render with garbled text in some browser configurations if the document contains characters from outside the US-ASCII range. The character encoding of the file needs to be declared in the transfer protocol or file needs to use a byte order mark as an encoding signature. jackett

Accessing the Jackett server on the local network (i.e. 127.0.0.1:9117/jackett) works fine.

Please find my config with mirrors the organizr-tools github config:

`location /jackett/ {
proxy_pass http://127.0.0.1:9117/jackett/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        proxy_redirect  http://  $scheme://;
        proxy_http_version 1.1;
	proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_cache_bypass $cookie_session;
        proxy_no_cache $cookie_session;
        proxy_buffers 32 4k;
}`

Both Edge and Chrome appear to only give a 404 page now, this has happened more recently.

**Comment by angrycuban13** [comment]
> 
> 
> Hey, I've recently had the same issue with firefox.
> 
> When attempting to access jackett via reverse proxy (through Organizr or just by going to [www.domain.com/jackett](http://www.domain.com/jackett)) I receive this in the browser console
> 
> > The character encoding of the plain text document was not declared. The document will render with garbled text in some browser configurations if the document contains characters from outside the US-ASCII range. The character encoding of the file needs to be declared in the transfer protocol or file needs to use a byte order mark as an encoding signature. jackett
> 
> Accessing the Jackett server on the local network (i.e. 127.0.0.1:9117/jackett) works fine.
> 
> Please find my config with mirrors the organizr-tools github config:
> 
> 
```
location /jackett/ { 
proxy_pass http://127.0.0.1:9117/jackett/; 
proxy_set_header Host $host; 
proxy_set_header X-Real-IP $remote_addr; 
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; 
proxy_set_header X-Forwarded-Proto https; 
proxy_redirect http:// $scheme://; proxy_http_version 1.1; 
proxy_set_header Upgrade $http_upgrade; proxy_set_header Connection "upgrade"; 
proxy_cache_bypass $cookie_session; 
proxy_no_cache $cookie_session; proxy_buffers 32 4k; }
```
> 
> Both Edge and Chrome appear to only give a 404 page now, this has happened more recently.

I have no issues with Jackett on Firefox. I recommend creating a general proxy.conf and just adding an include to your Jackett RP. Try to add this to your reverse proxy block

```
#Jackett Reverse Proxy
location /jackett/ {
auth_request /auth-0;   #=Admin #Org Auth, no need to add this line if you aren't using Org Auth
proxy_pass http://127.0.0.1:38087/jackett/;
include C:/nginx/conf/proxy.conf;
```
This is what proxy.conf looks like

```
client_max_body_size 0;
client_body_buffer_size 128k;

#Timeout if the real server is dead
proxy_next_upstream error timeout invalid_header http_500 http_502 http_503;

#Advanced Proxy Config
send_timeout 5m;
proxy_read_timeout 240;
proxy_send_timeout 240;
proxy_connect_timeout 240;

#Basic Proxy Config
proxy_set_header Host $host:$server_port;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header X-Forwarded-Proto https;
proxy_redirect http:// $scheme://;
proxy_http_version 1.1;
proxy_set_header Connection "";
proxy_cache_bypass $cookie_session;
proxy_no_cache $cookie_session;
proxy_buffers 32 4k;
proxy_headers_hash_max_size 51200;
proxy_headers_hash_bucket_size 6400;
```

**Comment by causefx** [comment]
Is this still an issue?  If so, please open back up.
