### ISSUE TITLE
Encoding issues for custom javascript

### ISSUE THREAD

**Issue by henrywhitaker3** [causefx/Organizr#1134]
###### Operating System: Debian
<hr>

##### Problem Description:
In early march I was having an issue with the encoding of the custom javascript (characters being rewritten to "§". This was fixed in [this commit](https://github.com/causefx/Organizr/commit/e9e7d7e78ed5a6bbe3bbf7c9a3359967fb2a0af9). Now the problem has started happening again.

<hr>

##### Reproduction Steps:
Edit the custom JavaScipt, after saving and refreshing, go back to edit it and characters will have been changed

**Comment by causefx** [comment]
I have tried this a few times and havent come across this... are you still having issues?

**Comment by henrywhitaker3** [comment]
It's very intermittent, don't think it's happened since switching to the develop branch

**Comment by causefx** [comment]
i believe this was fixed, if not please reopen back up.
