### ISSUE TITLE
RFE: Sonarr/Radarr/etc homepage calendar items - Add Default Filter option

### ISSUE THREAD

**Issue by gostlund** [causefx/Organizr#1135]
###### Operating System: Docker (organizrtools/organizr-v2)
<hr>

##### Problem Description:
In a world where someone has many shows / movies / etc that are being monitored, and perhaps there are a great number of items released per day, it becomes necessary to use the filter in order to easily see at a glance where items have been missed... It would be convenient if the option to set the 'Filter' value on that homepage item existed along with the 'Default View' option.
<hr>

##### Reproduction Steps:
Have Sonarr monitoring pretty much all current TV series, then observe the calendar as a very pretty Christmas tree with all the red / green text... apply filter every time you reload the home page... wish for a way to set that filter as default.

<hr>

#### Errors on screen?  If so paste here:

```

```

**Comment by causefx** [comment]
This is in dev currently

![image](https://user-images.githubusercontent.com/16184466/57030453-9574cf80-6bf9-11e9-9b91-a48746d9c8b5.png)
