### ISSUE TITLE
Is there any configuration documentation?

### ISSUE THREAD

**Issue by git-Shorty** [causefx/Organizr#1136]
Hi, 

I could not get it managed to get it run. Today I spend at least 6 hours on the settings, while trying to start off with SABnzbd iFrame. 
I tried any possible combination of URL and local URL. Also made various settings to docker-compose ports and nginx as well. Just getting blank iFrames.
Next thing, it took me some minutes to realize that I better do not trust the notifications made by organizr. Where organize says its just fine to click refresh in the top bar, I need to do a complete site refresh or log out - log in, to see changes applied. 
Other thing, on various times the wrong icon was displayed while on tab-settings of specific webservice. 

When I try to find some Documentation, I will find a FAQ with two entries on a homepage where the specific ReverseProxy forwarding won't work. 

Overall the User experience with organizr feels kind of buggy. 

I now gave up and installed Heimdall Dashboad instead. Which works also fine and was fully setup (all my webservices plus icons and users) within minutes. 
But I like your iFrame feature, which Heimdall does not support yet. But I already made a suggestion and wait for an answer.

Is there any plan on working out some words to configure organizr? And make it less look like a 1-2-3-Homepage of 1and1, JIMDO, Wix and stuff?

**Comment by Roxedus** [comment]
1. By default sab blocks iframes. 
2. The notification which tells you to reload, has a hyperlink you click on. 
3. I have never seen the issue with the icons being wrong, do you have a screenshot?


4. We are in the process of moving the documentation over to [organizr.app](https://docs.organizr.app), it gets bigger by the week. 

We also have a discord which will help with any other questions you may have.
