### ISSUE TITLE
Mobile login form autocapitalises and auto-corrects

### ISSUE THREAD

**Issue by henrywhitaker3** [causefx/Organizr#1138]
###### Operating System: Debian
<hr>

##### Problem Description:
Mobile login form autocapitalises and auto-corrects.

<hr>

##### Reproduction Steps:
N/A

<hr>

#### Errors on screen?  If so paste here:

```

```

**Comment by tronyx** [comment]
Sounds like your phone/keyboard and not Organizr. If it was Organizr it would happen on all devices.

**Comment by henrywhitaker3** [comment]
As seen on [/api/pages/login.php](https://github.com/causefx/Organizr/blob/v2-master/api/pages/login.php), on line 56:
`<input id="login-username-Input" class="form-control" name="username" type="text" required="" placeholder="Username" lang="en" autofocus>` there is no `autocorrect="off"` and  `autocapitalize="off"` options set on the HTML element, so I doubt it is just an issue with my specific phone.

**Comment by tronyx** [comment]
Not having it explicitly set to off doesn't mean it's set to on. I cannot reproduce the issue on my phone in either Chrome or Safari. @causefx may want to look into explicitly setting the values to off, but I'm not sure.

**Comment by henrywhitaker3** [comment]
Ah okay, it auto-capitalises on Android 9 on both Chrome and Firefox
