### ISSUE TITLE
option for remove menu

### ISSUE THREAD

**Issue by JamesDAdams** [causefx/Organizr#1139]
###### Operating System: OpenMediaVault (docker)
<hr>

##### it would be an option to disable the area in red that is on the image
![Capture](https://user-images.githubusercontent.com/20860324/56085797-dc1ca880-5e49-11e9-9ad9-0c94a3906e65.PNG)

<hr>

##### Reproduction Steps:

<hr>

#### Errors on screen?  If so paste here:

```

```

**Comment by tronyx** [comment]
Why would you want that? That area holds a lot of functionality, especially within the profile drop-down.

**Comment by jrdnlc** [comment]
CSS can probably do it but it's not something we will implement.

**Comment by JamesDAdams** [comment]
because for me, it takes up too much space :/ 
![Capture](https://user-images.githubusercontent.com/20860324/56086063-03c23f80-5e4f-11e9-8a95-11c43b20b57a.PNG)

**Comment by JamesDAdams** [comment]
f not, I'll see if I can change the css

**Comment by causefx** [comment]
may look at making a theme for this
