### ISSUE TITLE
Fatal Error manual Linux install 

### ISSUE THREAD

**Issue by NoOneAtHome** [causefx/Organizr#1141]
###### Operating System: Linux
<hr>

##### Problem Description:
I am trying to do an manual install on a Linux shared seedbox.  It has instanced niginx and php. 
phpinfo(); runs fine and reports all the requirements are there. 
After cloning the repo and chown -R i get the below error. 
https://i.imgur.com/LAgoWQj.png

also on a side note the Linux manual Zip instructions need updated wget https://github.com/causefx/Organizr/archive/master.zip produces as 404 
<hr>

##### Reproduction Steps:
clone repo
access site for first time

<hr>

#### Errors on screen?  If so paste here:

```
https://i.imgur.com/LAgoWQj.png
```

**Comment by tronyx** [comment]
That was the Master branch for v1, as the note at the top of the page states:

https://github.com/causefx/Organizr/wiki/Installation-and-Troubleshooting

v2 Master is here: https://github.com/causefx/Organizr/archive/v2-master.zip

We've been having a rough time trying to keep up with the documentation.

What is the base OS? What version of  PHP do you have installed?

**Comment by NoOneAtHome** [comment]
PHP 7.3.4, I believe the seed box is using a version Gentoo

**Comment by tronyx** [comment]
Okay, and is there anything in the Organizr, Nginx, or PHP logs?

**Comment by NoOneAtHome** [comment]
nothing in the nginx or php logs, where locally are the Organizr logs?

**Comment by causefx** [comment]
well that’s new. what OS is this seed box?

**Comment by causefx** [comment]
just saw the previous replies after i replied. 🤦🏽‍♂️

when I return home I will try and reproduce.

**Comment by NoOneAtHome** [comment]
> just saw the previous replies after i replied. 🤦🏽‍♂️
> 
> when I return home I will try and reproduce.

Thanks if it helps the specific seedbox host is whatbox.ca

**Comment by NoOneAtHome** [comment]
User error.  Sorry for wasting everyone's time.  autoindex on to autoindex on in Nginx config and is working.

**Comment by causefx** [comment]
No worries.  good job.

**Comment by tronyx** [comment]
Good to close then?
