### ISSUE TITLE
[v2] Setting up JWT-based SSO

### ISSUE THREAD

**Issue by ghost** [causefx/Organizr#1142]
###### Operating System: Docker
<hr>

##### Problem Description:
I'd like to set up a JWT-based SSO for all my services by using the Organizr JWT token and checking its claims.

I'm using Caddy as a reverse proxy in front of both Organizr and a bunch of other services, all using Docker images (generally the lsio images). Caddy has a convenient JWT validation middleware to validate the JWT token and protect specific paths using JWT claims.

There are 2 slight problems with this approach:

1. The cookie name is dynamic. According to https://github.com/causefx/Organizr/blob/v2-develop/api/functions.php#L45 the cookie name includes a random UUID, such as `organizr_token_62d9e46e-cdad-4726-9db7-e25b85397f57`, which makes it difficult to set up in the proxy - though of course not impossible, as I can spy this value by simply checking the cookie name after a successful login... but it just complicates the initial setup and I guess this value could change over time (?). Is there any reason not to make this cookie name static?

2. More importantly, in order to validate the token my proxy will need to know the HS256 secret used by Organizr to sign the token. Since this is HS256 symmetric key, it's sensitive info and I understand it should not something static / hardcoded in Organizr code, and needs to be determined at runtime... but I don't know how. According to https://github.com/causefx/Organizr/blob/v2-master/api/functions/token-functions.php#L12 the secret is the value of `$GLOBALS['organizrHash']`... How can I conveniently get this value? Can I just look it up in db or in some logs?

PS: I initially tried to achieve the same result using the Reauth plugin and protect my sensitive paths using the Organizr authorization API... but performance is absolutely intolerable. I believe that reauth does not cache the outcome of the authorization API calls, so each and every single HTTP request needs to first call the Organizr authorization API - including statics... Maybe I'm missing something but I don't think this is really doable in practice...?

**Comment by ghost** [comment]
OK, after some more digging I found out that everything is persisted into `www/Dashboard/api/config/config.php` so I managed to make it work quite smoothly now, but the initial setup is still very manual, I wish there could be a more straightforward process, and I'm worried that either of these values could be reinitialized after some restart...

**Comment by causefx** [comment]
hi there.  the value is static once the initial setup is done. i haven’t even got around to writing a change function on it. but you should be good for now.

**Comment by ghost** [comment]
OK, seems cool then. Maybe I can contribute to the SSO wiki page to mention my setup, since I find it much more efficient than the reauth solution...
Btw thanks for the great work! Can't wait to see what the new releases will bring!

**Comment by causefx** [comment]
Awesome!  We are currently migrating away from the wiki docs over to https://docs.organizr.app

If you sign up there I can promote you to write the SSO part for Caddy

Just let me know your username

**Comment by ghost** [comment]
Sure, I creatively registered as Yann Jouanique :)

**Comment by causefx** [comment]
Perfect, I just promoted you, can you please logout and back in.  Let me know if it works.

**Comment by ghost** [comment]
Doesn't seem to be OK... I'm trying to edit
https://docs.organizr.app/books/setup-features/page/serverauth which I
think is the best place to add the JWT setup details, but I cannot see an
edit button anywhere...

**Comment by causefx** [comment]
fixed now... lemme know

**Comment by ghost** [comment]
Done at https://docs.organizr.app/books/setup-features/page/serverauth
If you're happy with it I guess we can close this issue.

**Comment by causefx** [comment]
thank you!

**Comment by rochdev** [comment]
@yannouchou Can you share your Caddy configuration? I can't seem to make this work as I always get a `401`, even though I can see the token is in the cookie sent to Caddy.

My current config:

```
tautulli.<domain> {
  import ssl

  proxy / http://tautulli:8181

  jwt {
    path /
    except /favicon.ico

    allow group Admin

    token_source cookie organizr_token_<uuid>
    secret /etc/secrets/app.txt
  }
}
```

**Comment by ghost** [comment]
Hello!
I actually didn't enable JWT validation for Tautulli since it has a built-in SSO with Organizr, however this is the block I'm using for other apps (in my case they are served under different root path in the same domain, so I just have several such blocks):

```
    {$DOMAIN} {
      # Disable http2 since it doesn't support websockets
      tls {
        alpn http/1.1
      }
      log stdout
      errors stdout
      gzip

      jwt {
        path /radarr
        allow group Admin
        allow group User

        redirect /
        token_source cookie {$ORGANIZR_COOKIE_NAME}
      }

      proxy /radarr http://radarr {
        header_upstream     X-Scheme        {scheme}
        transparent
        websocket
      }
    }
```

In my case, the secret used to validate the token is passed into the `JWT_SECRET` environment variable.
I haven't tried passing it as a text file though, but I would maybe check the permissions on the file, and make sure it doesn't have a trailing line break...

**Comment by ghost** [comment]
Few more comments:
* The JWT plugin is not available in the default Caddy builds, you need to build your own if you need to enable it... but I suppose you already know this and anyway Caddy would throw an error at startup if that were the problem
* There might be a conflict between the use of the `secret` configuration entry, the `JWT_SECRET` env variable, and the `JWT_PUBLIC_KEY` env variable... only one of these 3 should be defined at a time.

**Comment by rochdev** [comment]
Thanks for helping out @yannouchou! I tried all the above to no avail. At this point, I don't know what could possibly be wrong, so I opened https://github.com/BTBurke/caddy-jwt/issues/47

**Comment by ghost** [comment]
OK, sorry it didn't help... could it be that your token is successfully validated, but doesn't have the appropriate claim? What happens if you remove the `allow` directive?

**Comment by ghost** [comment]
Also are you sure it isn't Tautulli itself returning the 401?

**Comment by rochdev** [comment]
Yes, because I tried the same with other services and get exactly the same behavior. It also cannot be the `allow` directive because that would result in a 403.

It looks like the cookie configuration landed around 5 months ago, and my Caddy image was out of date. Updating the `http.jwt` plugin resolved the issue.

**Comment by causefx** [comment]
🙌
