### ISSUE TITLE
[V2] No Items in the "Homepage Items" tab

### ISSUE THREAD

**Issue by GabDug** [causefx/Organizr#1144]
##### Problem Description:
I'm unable to add anything to the HomePage. No items are showing on the "Homepage Items" tabs, only the HTML ones.

(Edited with answer below)

**Comment by causefx** [comment]
Did you happen to select business for the license?

**Comment by GabDug** [comment]
Yes I did.

Switched back to personal as told by the staff on the discord.

For future reference it's located at `www/Dashboard/api/config/config.php`
If deployed with Docker and PGBlitz, the full path is `/opt/appdata/organizr/www/Dashboard/api/config/config.php`

Thanks for your quick reply and incredible software.

**Comment by causefx** [comment]
:) no worries. glad it’s going well.
