### ISSUE TITLE
Tab Url choose image text/image is misaligned 

### ISSUE THREAD

**Issue by GilbN** [causefx/Organizr#1146]
###### Operating System: docker
<hr>

##### Problem Description:
As you can see in the screenshot the text is misaligned. 
Setting `line-height` back to 28px seems to fix it, it was 38px so typo? :-P
It also looks like `.select2-search--dropdown` is missing background color.  
<hr>

![ss](https://user-images.githubusercontent.com/24592972/56419099-64aba680-6299-11e9-9430-bebf4a095507.png)

##### Reproduction Steps:
click choose image on tab settings

<hr>

#### Errors on screen?  If so paste here:

```
nope
```

**Comment by KrunchMuffin** [comment]
Was just going to post this. These solutions should fix the issue.

remove `line-height` 
```
.select2-container--default .select2-selection--single .select2-selection__rendered {
    color: inherit;
    line-height: 38px;
}
```
Set `top` to 35%
```
.select2-container--default .select2-selection--single .select2-selection__arrow b {
    border-color: #888 transparent transparent transparent;
    border-style: solid;
    border-width: 5px 4px 0 4px;
    height: 0;
    left: 50%;
    margin-left: -4px;
    margin-top: -2px;
    position: absolute;
    top: 35%;
    width: 0;
}
```

set `background-color`
```
.select2-search--dropdown {
    display: block;
    padding: 4px;
    background-color: #1f1f1f;
}
```

after above fixes.

![image](https://user-images.githubusercontent.com/1037197/56710994-c5523d80-66f6-11e9-887d-a73a02e7f0ed.png)
