### ISSUE TITLE
Adding Radarr to homepage throws error

### ISSUE THREAD

**Issue by roontoon** [causefx/Organizr#1148]
###### Operating System: Ubuntu
<hr>

##### Problem Description:
When adding Radarr to homepage went to test and throws error and will not add to home page. Tab works.

<hr>

##### Reproduction Steps:

<hr>

#### Errors on screen?  If so paste here:
API Connection Failed
Client error: 'GET http://192.168.254.18:7878/api/systems/status' resulted in a '401 unauthorized' response: {"error":"Unauthorized"}
```

<img width="1280" alt="Organizr V2 error" src="https://user-images.githubusercontent.com/874090/56463618-d8d37080-63a5-11e9-837c-d32e45d24676.png">
```

**Comment by Roxedus** [comment]
Sounds like the API key is wrong

**Comment by roontoon** [comment]
I thought so too but copied and pasted it several times with same result.

**Comment by causefx** [comment]
Don't use the copy button in Radarr as it doesnt work.  Please manually copy it and double check it pasted correctly.

**Comment by mishac** [comment]
I'm having the same issue on a brand new install. API key is definitely correct.

**Comment by causefx** [comment]
That error code comes directly from Radarr. 
We build the api call to `system/status` then pass the API key...

401 means that the key is incorrect.  Not sure how we can help any further.


I put the wrong API key and get this error:
![image](https://user-images.githubusercontent.com/16184466/56510965-379d0500-64e0-11e9-8af6-75666880b0c1.png)

After fixing it and saving it and waiting at least one second and hitting test:
![image](https://user-images.githubusercontent.com/16184466/56510998-4edbf280-64e0-11e9-95c9-c04081c36a8c.png)

**Comment by mishac** [comment]
Maybe it could have something to do with organizr-authentication?  I've got radarr using organizr for auth with traefik.

**Comment by mishac** [comment]
Yep that seems to be it.  if I disable the `traefik.frontend.auth.forward.address` rule in the radarr section in my docker compose, it works fine.   Sonarr doesn't seem to have this issue, which is odd.

**Comment by causefx** [comment]
with that being said, what url was being used in homepage settings?  We suggest using local url that isnt behind any proxy

**Comment by mishac** [comment]
I was using http://radarr:7878 , which is the internal (within the docker network) host/ip....I have to think something was amiss in my docker/traefik set up.  works fine now, and I have no idea why.

**Comment by causefx** [comment]
LOL... computers right?!

**Comment by roontoon** [comment]
Just tried again with a physical copy of the token from Radarr and it shows success with the connection but no new icon shows on the homepage.
<img width="1135" alt="organizr" src="https://user-images.githubusercontent.com/874090/56694023-cd3cbe00-66b3-11e9-9217-a426ac4967cb.png">

**Comment by causefx** [comment]
successful is good, try changing calendar to Month there on the bottom and use the arrows to see if there is any data there.

**Comment by roontoon** [comment]
What you see on the screen shot is NZBget and Sonarr. No Radarr.  BTW how do you delete items. A suggestion... While adding a tab have a place to select to have that item added to the homepage as you already are adding a token if needed. One stop shop.

**Comment by causefx** [comment]
i'll look into it, the calendar is for all media pvr's.

**Comment by causefx** [comment]
Calendar example:
![image](https://user-images.githubusercontent.com/16184466/56698441-ca879c00-66a6-11e9-8942-047a7d5187a2.png)

**Comment by roontoon** [comment]
OK that makes sense as this is a new server with nothing to show yet. I assume Lidarr is also considered media as it too is not showing up. What about Lazy Librarian? Also I have been using Plex for years and for the life of me I don't know where I would find the token for it and I am also assuming that for the Plex Machine field that would be the machine name. Thanks!

**Comment by roontoon** [comment]
Duh... just saw lidarr on the pic above.

**Comment by causefx** [comment]
No worries, for the plex token, goto settings > SSO and you will see button to get token and machine,, save it and it will save in org.

**Comment by roontoon** [comment]
OK I'm officially a dunce..... do you need plexpass for this otherwise I don't see it.
<img width="218" alt="Plex Media Player" src="https://user-images.githubusercontent.com/874090/56703432-bfe4fb00-66d6-11e9-9e4e-5f3ccb46bed0.png">

**Comment by mishac** [comment]
@roontoon it's in the organizr settings, not the plex settings :)

**Comment by causefx** [comment]
@mishac is correct....

![image](https://user-images.githubusercontent.com/16184466/56705852-8c4ea480-66c7-11e9-88ed-d8b4148af798.png)

**Comment by roontoon** [comment]
Got it thanks.
