### ISSUE TITLE
Minify Organizr's JavaScript files

### ISSUE THREAD

**Issue by ghost** [causefx/Organizr#1149]
It would be great if Organizr's JavaScript files could be minified with [terser](https://github.com/terser/terser) prior to publishing a new release. This would speed up the app's loading time and responsiveness.

You can find a detailed overview of the JavaScript files which need to me minified on this page (be sure to check both the PageSpeed and YSlow tabs): https://gtmetrix.com/reports/datahoarder.dev/TaaT9fIB

**Comment by whalehub** [comment]
@causefx Can you give me your input on this request?

**Comment by causefx** [comment]
Eventually I will look into minifying all js and css

**Comment by whalehub** [comment]
Any update on this?

**Comment by whalehub** [comment]
@causefx Any update on this?

**Comment by whalehub** [comment]
@causefx Any update on this?

**Comment by causefx** [comment]
Added a few js files to be minified.

**Comment by causefx** [comment]
Most of these files are done now.
