### ISSUE TITLE
[Feature Request] So sort of home page

### ISSUE THREAD

**Issue by saitoh183** [causefx/Organizr#115]
Instead of defaulting to a specific app, maybe a general landing home page. Muximux did something similar in the latest version. it could be a page with all your applications (just there names to avoid ugly icons if they are not the right size) as a first step and maybe in the future add more functionality to it.

**Comment by elRadix** [comment]
I like this idea,  summarized dashboard of your pages with direct links, I would allow the option to show icons provided by organizr

**Comment by saitoh183** [comment]
yeah or give the choice in the config to show icons or just text..text in maybe a short of oval container

im sure people will as for more stuff on it like plex or emby online status...maybe a way to interface with Ombi and pull data to dashboard since they have a api key

**Comment by causefx** [comment]
this may take a while to design, but it's possible, i like all the ideas :)

**Comment by elRadix** [comment]
integration with plex/kodi etc stuff is already available with htpcmanager, https://github.com/Hellowlol/HTPC-Manager

I'm not sure if we need it, but the code is already available if you want to fork it :)

**Comment by lgromb** [comment]
I second this, either take the splash screen from Muximux or something more useful like HTPC Manager allowing us to see some stats from Plex or current downloads.

**Comment by pyrostic** [comment]
Htpc manage looks like it would offer great information.  I'd like this to only be available to new users though... I don't want some random person to see this.  Basically sign up, and you get dropped on HTPC manager.

**Comment by StevenChorkley** [comment]
I use plex status setup on a separate subdomain, then set that as the default tab. 
It'd be awesome to have it built into Organizr! So +1!

**Comment by causefx** [comment]
I play to have an array of option setup for the landing page.

**Comment by causefx** [comment]
This issue was updated with commit c5e06f6
