### ISSUE TITLE
Where can I find the config?

### ISSUE THREAD

**Issue by achmetinternet** [causefx/Organizr#1150]
##### Problem Description:
I can't find the config file that is described here https://www.ixsystems.com/community/resources/fn11-2-iocage-jails-plex-tautulli-sonarr-radarr-lidarr-jackett-transmission-organizr.58/
in the last section of the Organizr install guide which I should remove using these commands:

iocage exec organizr cp -a /usr/local/www/Organizr/config/config.php /config/config.php
iocage exec organizr rm /usr/local/www/Organizr/config/config.php
iocage exec organizr ln -s /config/config.php /usr/local/www/Organizr/config/config.php

<hr>

##### Reproduction Steps:

<hr>

#### Errors on screen?  If so paste here:
cp: /usr/local/www/Organizr/config/config.php: No such file or directory

**Comment by HalianElf** [comment]
Try /usr/local/www/Organizr/api/config/config.php

**Comment by achmetinternet** [comment]
Thanks, I will point this out to the author of the thread. Has this changed with v2, I assume?

**Comment by HalianElf** [comment]
Yea, that thread looks like it was for v1.
