### ISSUE TITLE
Main Login using Plex Popup not working in Microsoft Edge

### ISSUE THREAD

**Issue by ExeCuteUK** [causefx/Organizr#1151]
###### Operating System: Ubnuntu 16.04
<hr>

##### Problem Description:
When I click on "Plex Login" (Plex DB backend option enabled) to log into the main Organizr, the pop up box which is ment to load the plex login/auth page stays white and does not load in Edge browser. I have the same issue on multiple machines and separate users who use Edge.

When I installed Chrome the popup loads perfectly fine and I can log in.

<hr>

##### Reproduction Steps:
Organizr Settings > Authentication;

Auth Type : Backend Only
Auth Backend : Plex
Token : complete
Plex Machine : complete
Admin Username : selected
Enable Plex oAuth : YES

<hr>

#### Errors on screen?  If so paste here:

```

```

**Comment by causefx** [comment]
I don't beleive that pop works with Edge.  Just checked Tautulli that uses the same method and got the same issue.  

The good thing is Edge is being replaced with Edge Chromium.  

https://www.microsoftedgeinsider.com/en-us/

Which works fine at the moment.

**Comment by causefx** [comment]
Since the new edge has been released I will mark this as closed.
