### ISSUE TITLE
Overriding X-Frame-Options deny?

### ISSUE THREAD

**Issue by jscottelblein** [causefx/Organizr#1153]
Some web apps block opening in an iFrame; anyone know a way around this so that we can do so?

More detailed info here (saving myself some keystrokes ;) : https://caddy.community/t/overriding-x-frame-options-deny/5565

**Comment by Roxedus** [comment]
This NEEDS to be done on the webserver. Different methods for each webserver. I assume you use caddy?

**Comment by jscottelblein** [comment]
@si0972 yep, Currently using Caddy.

**Comment by Roxedus** [comment]
Then you would need to do whats highlighted in that blogpost
