### ISSUE TITLE
Does the calendar have it's own ical address?

### ISSUE THREAD

**Issue by kevinb77** [causefx/Organizr#1155]
Just trying to figure out if the calendar that is created has its own ical address that can be used externally? 
```

**Comment by Roxedus** [comment]
No. thats not its purpose. It gets rendered from organizrs json api

**Comment by kevinb77** [comment]
I would love to have this implemented, so I can add it to my Google calendar for reminder purposes.

**Comment by Roxedus** [comment]
Both Sonarr and Radarr has an exposed ical endpoint.

**Comment by kevinb77** [comment]
Didn't even think of that! Thanks so much!

**Comment by causefx** [comment]
to be honest i have thought about it.  will let ya know if I do it.

**Comment by lkin** [comment]
This would be a really amazing feature. I have a related question: would there be a way to render _other JSON sources_ in the same calendar? 
This [recorder](https://github.com/l3tnun/EPGStation/) integrates perfectly with organizr's iframe, but does not provide a calendar endpoint although stores its scheduled recordings in a JSON file as follows:
```
[{
	"program": {
		"id": 60021860855,
		"channelId": 600218,
		"eventId": 60855,
		"serviceId": 218,
		"networkId": 6,
		"startAt": 1562558400000,
		"endAt": 1562565600000,
		"startHour": 13,
		"week": 1,
		"duration": 7200000,
		"name": "若様やくざ 江戸っ子天狗",
		"description": "出演:大川橋蔵/丘さとみ/渡辺文雄/山形勲/進藤英太郎/入江若葉\r\n監督:工藤栄一 脚本:野上竜雄\r\n1963年91分",
		"channelType": "CS",
		"channel": "CS8",
		"videoType": "mpeg2",
		"videoResolution": "1080i",
		"videoStreamContent": 1,
		"videoComponentType": 179,
		"audioSamplingRate": 48000,
		"audioComponentType": 3
	}
}]
```
No ISO format dates, but could there be a way of having events like these show up in Organizr's calendar as well? Thank you

**Comment by causefx** [comment]
I think I could create some type of plugin

**Comment by causefx** [comment]
If you want the json plugin for calendar, please make a feature request
