### ISSUE TITLE
Can't login Token Creation Error

### ISSUE THREAD

**Issue by jaydee99** [causefx/Organizr#1156]
###### Operating System: Ubuntu
<hr>

##### Problem Description:

Hi,

I can't login anymore on Organizr. Every time i'm trying to connect, i get this error "Login Error : Token Creation Error". I tried with different accounts and different browsers (chrome, safari) and i get the same error every time. Any idea of how could i fix this ?

Thanx for helping !
<hr>

##### Reproduction Steps:

<hr>

#### Errors on screen?  If so paste here:

```

```

**Comment by Roxedus** [comment]
Are you using docker?

**Comment by jaydee99** [comment]
Nope

**Comment by Roxedus** [comment]
Are you connecting trough a Dynamic dns provider?

**Comment by jaydee99** [comment]
No either...

**Comment by jaydee99** [comment]
Nothing changed still it was working perfect...

**Comment by causefx** [comment]
can you check DB schema?

On April 29, 2019 at 11:22 AM, jaydee99 <notifications@github.com> wrote:



Nothing changed still it was working perfect...

**Comment by jaydee99** [comment]
what do you mean ?

**Comment by causefx** [comment]
Usually token creation error means it cant set the token in the DB... maybe something happened to the Token Table...? can you open DB and check that table?

**Comment by jaydee99** [comment]
Sorry but i don't understand what do i have to check... I can read/write the .db file but what do i have to look for ?

**Comment by jaydee99** [comment]
Just a question, my php version is 7.3.3, maybe this version is not supported ? Do i have to downgrade ?

**Comment by causefx** [comment]
was it working before with 7.3.3?

did you recently update php?

**Comment by jaydee99** [comment]
Actually, upgrading to php 7.3.4 just fixed the issue... Thanx for helping !
