### ISSUE TITLE
PHP Issue - deluge.class.php

### ISSUE THREAD

**Issue by BzowK** [causefx/Organizr#1157]
###### Operating System: Windows Server 2016
<hr>

##### Problem Description:
Hey Guys - 

Noticed many "nssm" entries in Application Event Logs recently and found they were due to PHP restarting.  I enabled logging in PHP and it's full of issues related to deluge.class.php.  Wanted to post here to see if that may be related to my issue.  Below are the messages from PHP's log and Event Log:

**PHP Log**
_Below is each unique message that appears.  Each appears multiple times and in no specific order:_
> [28-Apr-2019 17:12:04 UTC] PHP Fatal error:  Uncaught Exception: Method request returned an error (no. 1): Not authenticated in C:\nginx\html\api\functions\deluge.class.php:564
> Stack trace:
> #0 C:\nginx\html\api\functions\deluge.class.php(48): deluge->makeRequest('webapi.get_torr...', Array)
> #1 C:\nginx\html\api\functions\homepage-connect-functions.php(1002): deluge->getTorrents(NULL, 'comment, downlo...')
> #2 C:\nginx\html\api\functions\homepage-connect-functions.php(46): delugeConnect()
> #3 C:\nginx\html\api\index.php(357): homepageConnect(Array)
> #4 {main}
>   thrown in C:\nginx\html\api\functions\deluge.class.php on line 564
> [28-Apr-2019 17:13:15 UTC] PHP Fatal error:  Uncaught Exception: Could not log in due to curl error (no. 28): Connection timed out after 10000 milliseconds in C:\nginx\html\api\functions\deluge.class.php:556
> Stack trace:
> #0 C:\nginx\html\api\functions\deluge.class.php(28): deluge->makeRequest('auth.login', Array)
> #1 C:\nginx\html\api\functions\homepage-connect-functions.php(1001): deluge->__construct('http://192.168....', 'PASSWORD')
> #2 C:\nginx\html\api\functions\homepage-connect-functions.php(46): delugeConnect()
> #3 C:\nginx\html\api\index.php(357): homepageConnect(Array)
> #4 {main}
>   thrown in C:\nginx\html\api\functions\deluge.class.php on line 556
> [28-Apr-2019 17:14:08 UTC] PHP Fatal error:  Uncaught Exception: Could not log in due to curl error (no. 7): Failed to connect to 192.168.0.25 port 8112: Connection refused in C:\nginx\html\api\functions\deluge.class.php:556
> Stack trace:
> #0 C:\nginx\html\api\functions\deluge.class.php(28): deluge->makeRequest('auth.login', Array)
> #1 C:\nginx\html\api\functions\homepage-connect-functions.php(1001): deluge->__construct('http://192.168....', 'PASSWORD')
> #2 C:\nginx\html\api\functions\homepage-connect-functions.php(46): delugeConnect()
> #3 C:\nginx\html\api\index.php(357): homepageConnect(Array)
> #4 {main}
>   thrown in C:\nginx\html\api\functions\deluge.class.php on line 556
> [28-Apr-2019 17:17:09 UTC] PHP Fatal error:  Uncaught Exception: Method request returned an error (no. 2): Unknown method in C:\nginx\html\api\functions\deluge.class.php:564
> Stack trace:
> #0 C:\nginx\html\api\functions\deluge.class.php(48): deluge->makeRequest('webapi.get_torr...', Array)
> #1 C:\nginx\html\api\functions\homepage-connect-functions.php(1002): deluge->getTorrents(NULL, 'comment, downlo...')
> #2 C:\nginx\html\api\functions\homepage-connect-functions.php(46): delugeConnect()
> #3 C:\nginx\html\api\index.php(357): homepageConnect(Array)
> #4 {main}
>   thrown in C:\nginx\html\api\functions\deluge.class.php on line 564

**Event Log Messages**
_All 5 events (one per line below) appear every 20-30 minutes._
> Program C:\nginx\php\php-cgi.exe for service php exited with return code 0.
> Killing process tree of process 13236 for service php with exit code 0
> Killing PID 13236 in process tree of PID 13236 because service php is stopping.
> Service php action for exit code 0 is Restart. Attempting to restart C:\nginx\php\php-cgi.exe.
> Started C:\nginx\php\php-cgi.exe -b 127.0.0.1:9000 for service php in C:\nginx\php.

<hr>

##### Reproduction Steps:
Not sure how, but Deluge seems to work fine in Organizr and is set up within it as follows:
- Latest version of Deluge 
- Runs on different system (same LAN) which is Windows 10 x64
- Added as tab in Organizr using reverse proxy address
- Added as home page item using local IP:port address (same in errors)

Thanks!

**Comment by causefx** [comment]
I hate that I included this class instead of writing my own......

**Comment by BzowK** [comment]
So... does that mean that the issue is due to that class which someone else maintains?  Thanks

**Comment by causefx** [comment]
correct. i will check if any updates to it. if not i will try and fix.

**Comment by BzowK** [comment]
Appreciate it

**Comment by causefx** [comment]
I forgot to reply that there were no new updated to that class.  Is this issue still happening?  If so reopen this issue.
