### ISSUE TITLE
v2 docker doesn't run through setup

### ISSUE THREAD

**Issue by joshmans** [causefx/Organizr#1158]
###### Operating System: unraid
<hr>

##### Problem Description:
Install/setup of the docker container for v2 works great, but when i go to set up organizr instead of loading a page asking to setup credentials, it just loads the login screen.  I cannot find how to get it to let me create an admin (or any) user

<hr>

##### Reproduction Steps:
Install v2 on docker on unraid and browse to IP:port
<hr>

#### Errors on screen?  If so paste here:

```

```

**Comment by Roxedus** [comment]
Did you "upgrade" from v1 without clearing the appdata for the container?

I would clear the appdata for the container, and restart the container

**Comment by joshmans** [comment]
No, fresh install of v2, never had v1 setup.

**Comment by causefx** [comment]
I just spun up a new container for v2-master:

![image](https://user-images.githubusercontent.com/16184466/56977964-48c2c300-6b2b-11e9-8112-39cc31fb9b15.png)


worked fine.  can you post your config for that container.

**Comment by joshmans** [comment]
I figured it out. Sorry forgot to post an update.  I stopped docker,
deleted appdata, started docker and spun up a new container and it worked
as expected.  The key was stopping and starting docker. Just deleting the
appdata didn't work.

**Comment by causefx** [comment]
thanks for posting.  Odd that the container didnt work on first start though...
