### ISSUE TITLE
[Feature request] Seperate homepage for users and admin

### ISSUE THREAD

**Issue by AquaRelliux** [causefx/Organizr#1160]
###### Operating System: unRAID
<hr>

##### Feature requests:
Currently there is no way to have separate homepage depending on your access rights in Organizr. I would like it to be possible to have different homepages for my users that are separate from my admin login. As it is now if I add all the HTML pages I want for my users I will se both my admin HTML and user HTML as an logged in admin on my Organizr. Maybe there is a way to do this I just missed it?
```

**Comment by henrywhitaker3** [comment]
If it isn't sensitive data you want to put onto the admin page, you could do what I do: have an empty div in the html homepage item, then using the custom javascipt, check the value of activeInfo.user.groupID and you can decide from there what to do. So for example, for adding extra html for co-admin & admin, with this div in HTML homepage item:
```
<div id="emptyDiv"></div>
```
and this in the custom javascript:
```
if(activeInfo.user.groupID <= 1) {
    document.getElementById('emptyDiv').innerHTML = '<insert what you want to add here>';
}
```
It also doesn't matter hugely, for me at least, that users could see the HTML I'm adding for myself and not them, those pages are protected by nginx auth anyway so even with the link they can't see it.

**Comment by causefx** [comment]
This is not planned as we have custom html and js for that.
