### ISSUE TITLE
Allow custom URL for selfhosted version of healthchecks

### ISSUE THREAD

**Issue by mishac** [causefx/Organizr#1161]
###### Branch: Develop
<hr>

##### Problem Description:
I would like to set up healthchecks for my services, but I use a selfhosted copy of healthchecks, (with the linuxserver/healthchecks docker image) rather than using http://healthchecks.io.  

I'd like to be able to enter my selfhosted custom URL to use the health checking functionality on the Organizr homepgae
<hr>

##### Reproduction Steps:

1. self host a copy of healthchecks.io
2. try to use it with organizr
3. fail

<hr>

**Comment by causefx** [comment]
that'll be easy

**Comment by causefx** [comment]
Completed

**Comment by causefx** [comment]
@mishac can you test please?

**Comment by mishac** [comment]
It's working for me :smile:
