### ISSUE TITLE
Tab editor issue with SABnzbd

### ISSUE THREAD

**Issue by KrunchMuffin** [causefx/Organizr#1162]
###### Operating System: unRAID
<hr>

##### Problem Description:
In Tab Editor > Tabs, when clicking the house icon to edit SABnzbd, it brings up Sonarr instead.

<hr>

##### Reproduction Steps:
Same as problem

<hr>

#### Errors on screen?  If so paste here:
![image](https://user-images.githubusercontent.com/1037197/57100133-2b892280-6cec-11e9-93a8-9c54c1ca5c3f.png)

```

```

**Comment by KrunchMuffin** [comment]
non-issue. ignore.

**Comment by causefx** [comment]
was it something easy?

**Comment by KrunchMuffin** [comment]
Ya, make sure the URL is not for sonarr. 😀
Actually, speaking of that, why do we have to enter the URL again when we
already have it set up?

**Comment by causefx** [comment]
they could be different. proxy vs no proxy. all up to user
