### ISSUE TITLE
[v2] [UI Request] Calendar

### ISSUE THREAD

**Issue by KrunchMuffin** [causefx/Organizr#1163]
In FullCalendar, can you update the current day to be brighter? Can barely see it.
My suggestion: change the opacity to .5 from .1

```
.fc-unthemed .fc-today {
    border: 1px solid #ff7676;
    background: rgba(0,0,0,0.5)!important;
}
```

OLD
![image](https://user-images.githubusercontent.com/1037197/57101184-abb08780-6cee-11e9-9892-6edbe69279e3.png)

NEW
![image](https://user-images.githubusercontent.com/1037197/57101199-b0753b80-6cee-11e9-869b-4f6b37b3cfe2.png)

**Comment by tronyx** [comment]
You can use custom CSS:

`
/* Better today highlight for calendar */
.fc-unthemed .fc-today {
    background: #3D3D3D!important;
}
`

Adjust the color as you like.
![chrome_2019-05-02_15-53-01](https://user-images.githubusercontent.com/22502007/57102882-6f7f2600-6cf2-11e9-848a-9ac278fcda8c.png)

I believe there is a permanent change in the works that just hasn't been implemented yet.

**Comment by KrunchMuffin** [comment]
ahhh...didn't think about that. Be nice out-of-the-box however.

**Comment by causefx** [comment]
this was fixed a while ago - just never closed it. sorry.
