### ISSUE TITLE
[v2] Sonarr/Radarr homepage settings overwriting each other

### ISSUE THREAD

**Issue by KrunchMuffin** [causefx/Organizr#1164]
###### Operating System: unRAID
<hr>

##### Problem Description:
When editing the homepage settings for sonarr and radarr, they overwrite each other.

<hr>

##### Reproduction Steps:

1. Add radarr and sonarr as tabs.
2. go to tab editor
3. click the homepage settings icon beside sonarr
4. enter in the information and make sure to change settings under misc. options. take note of them.
5. save
6. reload the page with the browser reload not the reload at the top left. (doesn't actually reload)
7. click the homepage settings icon beside radarr
8. fill in the information and make sure to change the settings under misc. options and make sure they are not identical to sonarr. take note of them.
9. save
10. reload the page with the browser reload not the reload at the top left. (doesn't actually reload)
11. click the homepage settings icon beside sonarr
12. click the misc. options tab.
13. note that the settings are what you put under radarr, not the original settings for sonarr
14. change the misc settings.
15. save
16. reload the page with the browser reload not the reload at the top left. (doesn't actually reload)
17.  click the homepage settings icon beside radarr
18. note that the settings are  now what you just put in under sonarr
<hr>

#### Errors on screen?  If so paste here:
no errors.

**INITIAL SONARR SETTINGS**
![image](https://user-images.githubusercontent.com/1037197/57118309-69a83580-6d30-11e9-990d-206aed97ef15.png)

**INITIAL RADARR SETTINGS**
![image](https://user-images.githubusercontent.com/1037197/57118324-7d539c00-6d30-11e9-9be1-ff943b560447.png)

**AFTER UPDATING BOTH AND COMING BACK**
![image](https://user-images.githubusercontent.com/1037197/57118346-9ceac480-6d30-11e9-8687-101f65e60f31.png)

**UPDATE SONARR AND BACK TO RADARR**
![image](https://user-images.githubusercontent.com/1037197/57118380-f5ba5d00-6d30-11e9-9153-e166a5ba8fde.png)

**Comment by causefx** [comment]
Sorry. i should have noted that those are shared. if enough people want them separate, i can do that.

**Comment by KrunchMuffin** [comment]
Oh, I wouldn't mind all in one calendar. So just have to put different URLs
and they will merge?

**Comment by causefx** [comment]
correct. everything aggregates to one calendar on homepage.

**Comment by KrunchMuffin** [comment]
ok, u can close this then, but maybe add a blurb somewhere about it.
I don't have any movies coming up, so couldn't see that.
