### ISSUE TITLE
[Feature Request] Support for Google Analytics

### ISSUE THREAD

**Issue by ghost** [causefx/Organizr#1166]
I've been trying to add the Google Analytics agent snippet using the Theme custom Javascript, but it seems it's not working due to the way the GA lib wants to get loaded (via a script tag... and we cannot use plain JS to add this script tag for some reason).

I would like to suggest adding this as a built-in feature where we'd just specify the GA tracking token in the Organizr config so that Organizr adds the script tag itself in all its pages.

Would this be doable?

Many thanks!

**Comment by angrycuban13** [comment]
I dont think this should be added natively to Organizr. I dont personally want Google analyzing anything in my domain.

**Comment by GilbN** [comment]
> I dont think this should be added natively to Organizr. I dont personally want Google analyzing anything in my domain.

Remember that there's a business license option.

**Comment by angrycuban13** [comment]
I have a feeling that his request doesn't apply to the business license though.

**Comment by ghost** [comment]
Well, I didn't specify it explicitly, but naturally I'm not suggesting that this should be mandatory or even enabled by default - that would be a pretty irresponsible idea indeed, and I'm not even sure how that would work (which tracking id to use, who would administrate it, and how could we make it work cross-domains??).

So just to be clear, what I'm suggesting here is to create a new setting where admins can provide a GA tracking ID so that Organizr can add the tracker to all its pages.

I've actually put together a PR for that, but I haven't really tested this yet: #1167

**Comment by ghost** [comment]
Implemented in #1167 so closing this.
