### ISSUE TITLE
Syntax Error: Unexpected Token < at JSON Position 0

### ISSUE THREAD

**Issue by jkirkcaldy** [causefx/Organizr#1168]
###### Operating System: Ubuntu
<hr>

##### Problem Description:
Every now and again I get these errors:
Syntax Error: Unexpected Token < at JSON Position 0

Checking the console reveals multiples of this error message:
[DOM] Found 2 elements with non-unique id #accountEmail: (More info: https://goo.gl/9p2vKq) 

<hr>

##### Reproduction Steps:
Just browsing the website normally. Often happens when using sonarr/radarr

<hr>

#### Errors on screen?  If so paste here:

```
Syntax Error: Unexpected Token < at JSON Position 0

[DOM] Found 2 elements with non-unique id #accountEmail: (More info: https://goo.gl/9p2vKq) 


```
<img width="1677" alt="Screenshot 2019-05-09 at 13 24 58" src="https://user-images.githubusercontent.com/26098592/57453349-1b2df600-725e-11e9-90fb-a5ec771b51f7.png">

**Comment by causefx** [comment]
that means the api returned non json code.... Turn off debug errors and the error will be in console.

**Comment by angrycuban13** [comment]
Are you still having this issue?
