### ISSUE TITLE
Way to disable access to subpages outside of Organizr view

### ISSUE THREAD

**Issue by lgromb** [causefx/Organizr#117]
Hey.

I'm currently running Organizr as my landing page for my external access to my homelab. All of my pages are rerouted through nginx reverse proxy as xxx.xxx/sonarr /couchpotato and so on...

Thoses pages are still accessible outside of Organizr webview, I would like to know if there is any nginx configuration tricks to only authorize Organizr from showing thoses subfolders, and no one else.

Not really an issue but I thought that it belonged here more than on nginx git.

Thanks ! 🗡

**Comment by pyrostic** [comment]
This is a server config issue (setting).  I had this perfectly setup for
CaddyServer, however I've since switched to NGINX and haven't had a chance
to element it.   Basically what it said is that the user can only access
those domains if coming from domain.

**Comment by pyrostic** [comment]
Further note, I'm in the process of writing the Windows Installation Guide
for Organizr which includes server setup.  I plan on including the
authorization code in my sample NGINX config file.

**Comment by lgromb** [comment]
Thanks for the tip then, and since the domain is the same for both Organizr and other services, might be a bit hard to tell nginx the difference haha. Maybe if I set a custom header to the reverse proxy serving Organizr and let nginx serve the other services only if the matching header is passed on ? This is absolutly not an Organizr issue, but I thought I'd get more replies here.

**Comment by pyrostic** [comment]
Its not really hard, just don't know NGINX config too well yet.  It
basically dermines where you came from and says yae or nay.  You either get
to pass or not.

**Comment by lgromb** [comment]
Yeah but as I said, how nginx would tell the difference if you're coming and going to the same domain ? Well I might ask a lot of hard thinking for something that'd be really simple haha.

**Comment by causefx** [comment]
use the cookiePassword function in organizr.  then apply the check to your proxy block.

```
location /plexpy {
    if ($cookie_cookiePassword != "PASSWORDHERE") { return 403; }
    add_header X-Frame-Options "SAMEORIGIN";
    proxy_pass http://127.0.0.1:8181;
 }
```

**Comment by lgromb** [comment]
Working as intended, exactly what I was looking for, thanks a lot

**Comment by pyrostic** [comment]
I will ensure this gets added to the wiki if its not there.

**Comment by StevenChorkley** [comment]
I have no idea why, but I'm receiving a 403 error when accessing through Organizr. I've triple-checked the strings. 

Organizr is located at www.example.com, and PlexPy(or whatever) is at www.example.com/plexpy/

**Comment by pyrostic** [comment]
Do you have Cookie Auth on?

**Comment by StevenChorkley** [comment]
No, I certainly haven't turned it on. Do I need to enable auth_request?

**Comment by StevenChorkley** [comment]
I can't find how to enable it online.

**Comment by causefx** [comment]
what does your location block look like?

**Comment by StevenChorkley** [comment]
> server {
> 	listen 443 ssl http2;
> 	listen [::]:443 ssl http2;
> 
> 	ssl_certificate /etc/letsencrypt/live/www.example.com/fullchain.pem;
> 	ssl_certificate_key /etc/letsencrypt/live/www.example.com/privkey.pem;
> 	include snippets/ssl-params.conf;
> 
> 	root /var/www/www.example.com/www;
> 
> 	index index.php index.html index.htm index.nginx-debian.html;
> 
> 	server_name www.example.com;
> 
> 	location / {
> 		try_files $uri $uri/ =404;
> 	}
> 	location ~ \.php$ {
> 		include snippets/fastcgi-php.conf;
> 		fastcgi_pass unix:/run/php/php7.0-fpm.sock;
> 	}
> 	location ~ /\.ht {
> 		deny all;
> 	}
> 
> 	location /plexpy {
> 		if ($cookie_cookiePassword != "PASSWORDHERE") { return 403; }
> 		add_header X-Frame-Options "SAMEORIGIN";
> 		proxy_pass http://192.168.0.4:8181/plexpy;
> 	}
> 	location /sonarr {
> 		proxy_pass http://192.168.0.4:8989/sonarr;
> 	}
> 	location /radarr {
> 		proxy_pass http://192.168.0.4:7878/radarr;
> 	}
> 	location /nzbget {
> 		proxy_pass http://192.168.0.4:6789;
> 	}
> 	location /ombi {
> 		proxy_pass http://192.168.0.4:3579/ombi;
> 	}
> 	location /nzbhydra {
> 		proxy_pass http://192.168.0.4:5075/nzbhydra;
> 	}
> 	location /deluge {
> 		proxy_pass http://192.168.0.4:8112/;
> 		proxy_set_header X-Deluge-Base "/deluge/";
> 		add_header X-Frame-Options SAMEORIGIN;
> 		include snippets/proxy-control.conf;
> 	}
> 	location /jackett {
> 		proxy_pass http://192.168.0.4:9117/;
> 	}
> }
> 
I used a rather unimaginative password, but it'll do for testing.

**Comment by causefx** [comment]
Goto settings and click the cog icon... enter your password under cookie password.... log out and log back in.

**Comment by StevenChorkley** [comment]
logging out and back in did the trick, thanks!

**Comment by causefx** [comment]
:)

**Comment by StevenChorkley** [comment]
I can't seem to add this into the Wiki

**Comment by causefx** [comment]
the wiki is only editable to contributors.  have you forked it?

**Comment by StevenChorkley** [comment]
Yeah, forked and you've accepted my pull requests. It says contributor on my flair.

**Comment by causefx** [comment]
@StevenChorkley try now

**Comment by StevenChorkley** [comment]
sorted, thanks!

**Comment by lgromb** [comment]
Re-opening this. I tried to set up the cookie auth block to glances running at domain.com/glances

Applied everything with custom password in Organizr aswell, but apparently, nothing has changed at all, I'm still able to access Glances outside of Organizr, and it still works in Organizr, there's something I don't get here.

**Comment by StevenChorkley** [comment]
Are you using the exact-same domain for both Organizr and Glances?

**Comment by causefx** [comment]
also open up a different browser and goto glances, it should not load.

**Comment by lgromb** [comment]
Yes, I got https://home.domain.com/ redirecting via htaccess to https://home.domain.com/organizr and glances running at https://home.domain.com/glances . It's that simple. Tried with Edge and Firefox, Glance still availiable, cleared cache and everything.

**Comment by causefx** [comment]
Can you paste the location block?

**Comment by lgromb** [comment]
`location /glances/ {
        rewrite /glances/(.*) /$1 break;
        proxy_pass http://192.168.1.98:61208;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme; #doesn't do anything?
        if ($cookie_cookiePassword != "THISISATEST") { return 403; }
        add_header X-Frame-Options "SAMEORIGIN";
}`

**Comment by causefx** [comment]
have you tried the auth.php route yet?

https://github.com/causefx/Organizr/wiki/Authentication-%7C-Server-Based

**Comment by lgromb** [comment]
Just tried it, it either gives me a 500 or 401 (I think 401 means that the auth request cannot reach the auth.php page..

Here's the auth block. Organizr is sitting in /organizr

`location /auth {
        internal;
        rewrite ^ /organizr/auth.php?lgromb;`

and I tried to use it on Sonarr :
`location /sonarr        {
                auth_request /auth;
                proxy_pass http://link-sonarr:8989;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                }
`

**Comment by causefx** [comment]
sorry, you only need to put this on that location:

```
location /auth { 
    internal; rewrite ^ /organizr/auth.php?admin; 

}

you dont put you username there, you put the group.  if you want admin only, put admin, if you want anyone logged in, you put user.
```
