### ISSUE TITLE
Active streams plex - missing image - minor issue

### ISSUE THREAD

**Issue by evlo** [causefx/Organizr#1170]
###### Operating System: Ubuntu
<hr>

##### Problem Description:
Some image not showing for now playing in plex on homepage.

Images are working for recently added plex section on homepage.

<hr>

##### Reproduction Steps:
Enable active stream in settings > homepage > plex

<hr>

#### Errors on screen?  If so paste here:
https://i.imgur.com/EXzGnZI.png

**Comment by HalianElf** [comment]
Try clearing out the image cache in `/plugins/images/cache`

**Comment by evlo** [comment]
Where would I look for that if I'm using docker version on ubuntu server 18.4?

**Comment by HalianElf** [comment]
Where config is your mapped config folder: /config/www/Dashboard/plugins/images/cache

**Comment by evlo** [comment]
that did not help. I investigated a bit more and it looking, in current case, for image http://78.102.29.21/plugins/images/cache/788-np.jpg, that exists, but is probably broken. This is after deleting the cache. It actually contains text `<html><head><title>Internal Server Error</title></head><body><h1>500 Internal Server Error</h1></body></html>`

Similar thing with recently add, if i try to open some item, it opens url ie. http://*:20000/web/index.html#!/server/NUC/details?key=/library/metadata/827 but I always end up on plex homepage.

**Comment by causefx** [comment]
check nginx log or php log for errors please

**Comment by Orbsa** [comment]
I am having the same issue, Recently added and playlists aren't loading images either. Requested Item's are loading images, however.

There are no errors reported in either the nginx error log or the php error log.
Seems like the issue is from pulling images from plex itself. It's generating the files for the images from plex, but they are all 4.0Kb empty files (except from the ones pulled from Ombi)

**Comment by jonathanfinley** [comment]
@Orbsa can you check your permissions?

@evlo this seems like it could be a proxy issue.

**Comment by Orbsa** [comment]
> @Orbsa can you check your permissions?

Permissions are as they have always been. 644 on all images.
Images pulled from Organizr are working fine, It's just the images pulled from plex that are failing.
Even when using the search feature, movies backgrounds load blank images as well.

**Comment by causefx** [comment]
can you screenshot plex url on homepage settings?

**Comment by Orbsa** [comment]
Nevermind, looks like adding https:// to the url instead of just using the fqdn fixed the issue.
Weird. Thanks.

**Comment by jonathanfinley** [comment]
For homepage, as all that is pulled locally, I would not use a fqdn but instead use http://plexipaddress:32400

**Comment by causefx** [comment]
We prepend `http://` if it is not present, we will never prepend `https://` as we never know when it is secure.
