### ISSUE TITLE
Plex not showing on homepage

### ISSUE THREAD

**Issue by megapearl** [causefx/Organizr#1172]
###### Operating System: FreeBSD 12.0-RELEASE-p3
<hr>

##### Problem Description:
Plex Tab and Plex not showing on homepage

<hr>

##### Reproduction Steps:
Configure Plex, Test it (it connects succesful to Plex Api) Click on Homepage, see all services except plex.

<hr>

#### Errors on screen?  If so paste here:

```
No Errors.
```

**Comment by Roxedus** [comment]
What format is your homepage URL? It should start with http/https

https://img.roxedus.net/chrome-2019-05-13_19-23-05.png

**Comment by megapearl** [comment]
It's https://10-0-0-32.aa5b24199966409bacdc1a9651e2b680.plex.direct:32400/web

**Comment by Roxedus** [comment]
No need for /web. use local IP if you can.

**Comment by megapearl** [comment]
If I use http://10.0.0.32:32400 or https://10.0.0.32:32400 it says API connection failed...
When I use https://10-0-0-32.aa5b24199966409bacdc1a9651e2b680.plex.direct:32400/web it says API connection succesfull

**Comment by megapearl** [comment]
Tautulli is using the https://10-0-0-32.aa5b24199966409bacdc1a9651e2b680.plex.direct:32400/ scheme, I now copied the url from Ombi to Organizr which is using the https://10.0.0.32:32400 scheme with the Plex Authorization Token and that one is also connecting successfull and is showing on the homepage too!
Thanks for pointing me in the right direction.
