### ISSUE TITLE
CORS errors for whm / cpanel / roundcube

### ISSUE THREAD

**Issue by mircobabini** [causefx/Organizr#1173]
###### Operating System: MacOS (but self-installed on Linux Apache)
<hr>

##### Problem Description:
Can't make cpanel / webmail / whm tabs to work. When I put credentials, a console error about CORS is getting through.

<hr>

##### Reproduction Steps:
Add a tab with any cpanel / webmail url and try to log in.

<hr>

#### Errors on screen?  If so paste here:
```
Uncaught DOMException: Blocked a frame with origin "https://webmail.sedweb.it" from accessing a cross-origin frame.
    at ajaxObject.login_results [as _callback] (https://webmail.sedweb.it/:267:5771)
    at XMLHttpRequest.ajax.onreadystatechange (https://webmail.sedweb.it/:267:4569)
login_results @ (index):267
ajax.onreadystatechange @ (index):267
XMLHttpRequest.send (async)
ajaxObject.update @ (index):267
do_login @ (index):267
(index):267 XHR finished loading: POST "https://webmail.sedweb.it/login/?login_only=1".
```

**Comment by Roxedus** [comment]
This is not a Organizr issue. This is a basic security issue that comes with any iFrame. 

If you control the host, you need to allow the organizr domain to iFrame cpanel. If not, the security measure does what it is supposed to do, and there is lite to none you can do.
