### ISSUE TITLE
iFraming issues with IIS as webserver

### ISSUE THREAD

**Issue by Gamrin** [causefx/Organizr#1174]
###### Operating System: Windows
<hr>

##### Problem Description:
You always need that one idiot who wants to run something designed for NGINX/Apache on IIS.
My goal is to manage all services with powershell, preferably with object-oriented windows native features like IIS web server vs good old classic nginx.

When using Organizr on a IIS web server, the iframing just nopes the fuck out. The page isn't loaded.

When using nginx with a rewrite in the IIS webserver, this works.

<hr>

##### Reproduction Steps:
1. Install a windows server with IIS webserver.
2. Create a directory for Organizr. (I used inetpub/organizr)
3. Create a service account and an AppPoolID.
4. Give permissions on the webdir to the Organizr service account linked to the apppoolID
5. Add the Organizr files to the webdir
6. Configure PHPcgi in IIS
7. start the website
Organizr runs fine.
8. Configure tabs for Sonarr, radarr, ESXI on known good webaddress.
    Make sure to use iframing
9. open the tab in the main window
iframed page area remains black/empty. The rest of Organizr works fine.

<hr>

#### Errors on screen?  If so paste here:

```

```
#### Workaround
I am now running the NGINX server on a different port, and reverse proxy-ing it through IIS with the rewrite module. This works, and allows website control through powershell.

**Comment by causefx** [comment]
can you post what browser console says?

**Comment by Gamrin** [comment]
My production environment in which I used to produce this is error currently stricken with a case of the "multiple concurrent drive failures in the raid array". I will be reproducing this issue in a testing lab later this month.

**Comment by Gamrin** [comment]
Later this month is turning out to be later next month. I'm building a lab environment to reproduce the error with, but don't expect to deliver logs and dumps this or next week.

**Comment by causefx** [comment]
no worries

**Comment by edrock200** [comment]
Fwiw I have it working in iis. I did the steps you did, but also created a new service account and appool. The service account has right to organizr. The apppool uses this service account, and the site uses this apppool. The only other step I had to take was to add "extension=sqlite3" to my php.ini file. Sonarr/radarr/etc load correctly in iframe.
