### ISSUE TITLE
[v2] Cannot re-order new tabs from bottom upwards in Settings after adding many (50+)

### ISSUE THREAD

**Issue by cferrey** [causefx/Organizr#1175]
###### Operating System: Ubuntu
<hr>

##### Problem Description:
After adding a significant number of tabs (approximately 50) and re-ordering them without issue, I can no longer re-order new tabs after adding them (they sit at the very bottom).  When I try to drag and drop to move them up the list, they move up, but almost immediately revert back to the bottom.

<hr>

##### Reproduction Steps:
Add a whole 'lotta tabs (~50+), and then add one more and attempt to drag and drop to move it up from the bottom of the list in Settings.

<hr>

#### Errors on screen?  If so paste here:

```

```

**Comment by causefx** [comment]
Seems this is a limitation with serializeToJSON.

I will upgrade to the newest version and do some more testing.

https://github.com/raphaelm22/jquery.serializeToJSON

**Comment by cferrey** [comment]
> Seems this is a limitation with serializeToJSON.
> 
> I will upgrade to the newest version and do some more testing.
> 
> https://github.com/raphaelm22/jquery.serializeToJSON

Any updates on this?  Still experiencing this issue on v2.0.235.  Thanks for any updates!

**Comment by causefx** [comment]
I'm still thinking of a way to help improve this.  I updated to the newest version of serializeToJSON but that didn't help.  I may have to write or look for an alternative.

**Comment by cferrey** [comment]
@causefx Any updates?  Hoping some sort of fix can be implemented for those of us who are tab-crazy :)

**Comment by cferrey** [comment]
@causefx Any news on this front?  Thanks.

**Comment by causefx** [comment]
Sorry about that.  I haven't found anything to replace this at the moment.   How many tabs do you have right now?

**Comment by cferrey** [comment]
@causefx I have 62 currently, though most are hidden.

**Comment by causefx** [comment]
@cferrey I am asking from help from their dev on their repo:
https://github.com/raphaelm22/jquery.serializeToJSON/issues/14

**Comment by cferrey** [comment]
@causefx Thanks -- appreciate you looking into it with them.  In the meantime, is there any way I can manually force a certain order by editing certain config files/DB files while the container is not running?

**Comment by causefx** [comment]
you can edit the order in the db in the tab table

**Comment by causefx** [comment]
@cferrey 

@raphaelm22 pushed an update that fixed this issue, There is still an issue with the animations being a little slow on drag.  I will try and nail those down.

**Comment by cferrey** [comment]
@causefx Thanks, really appreciate it!  I just pulled the latest version from Docker Hub, 2.0.307, but am still seeing the old behavior.  I'm guessing the newest version just hasn't made it to the Docker repo yet?

**Comment by causefx** [comment]
sorry. it’s on the dev repo. are you on master?

**Comment by cferrey** [comment]
I think so, yeah -- I'm pulling via latest tag on Docker Hub (organizrtools/organizr-v2:latest).  No worries though, I'm more than happy to wait for it to make it into production -- great to know it's coming!

**Comment by causefx** [comment]
I'll push a version update tomorrow

**Comment by cferrey** [comment]
@causefx this still doesn't seem to be working in the Docker Hub image organizrtools/organizr-v2:latest (pulled today), which is loading v2.0.325 off the master branch according to the organizr settings page.  Is it possible the master branch is still behind this commit?

**Comment by causefx** [comment]
Can you take a video of whats happening?

**Comment by cferrey** [comment]
@causefx Sure thing, please see here, and let me know if I can help provide any other info: https://www.dropbox.com/s/wjon19gcku11nkw/organizr-reorder-issue.mov

**Comment by causefx** [comment]
thanks for that.  It seems that its refresh before saving tabs.  I will try and rework.

**Comment by cferrey** [comment]
@causefx Any luck with this?  Thank you for all your ongoing work on it!

**Comment by cferrey** [comment]
@causefx  Hi -- any progress on this one?

**Comment by causefx** [comment]
How many tabs do you have at the moment?

**Comment by cferrey** [comment]
@causefx Approximately 75 in total, but only about 50 active/visible.

Edit: scratch that, probably more like 75 total and 60 active.

**Comment by cferrey** [comment]
@causefx Any luck on this fix?  Just touching base, thanks!

**Comment by causefx** [comment]
@cferrey can you test out the latest dev commit - I added a save tab order button - I want to see how it behaves for you.

**Comment by cferrey** [comment]
> 
> 
> @cferrey can you test out the latest dev commit - I added a save tab order button - I want to see how it behaves for you.

@causefx sure thing -- is there an easy way for me to switch branches if I'm using the organizrtools/organizr-v2 image from Dockerhub?  I didn't see a recent tag there for dev branch.  If not, I can spin up a vm and try installing there without Docker.

**Comment by causefx** [comment]
if you use the `dev-php-fpm` or `dev-latest` tag, it will switch branches for you.

**Comment by cferrey** [comment]
@causefx Thanks.  Finally had time to give it a test with the dev-latest tag, but unfortunately it still doesn't seem to be saving the order.  I used the button at the top of the page, and got the "tab order saved" pop-up in lower right, but upon reloading the page the order reverts to what it was.

**Comment by causefx** [comment]
Can you take another video of that happening please? Also would it be possible to maybe use anydesk to remotely experience this....

**Comment by cferrey** [comment]
@causefx Hey, sorry for the delayed reply -- had a pretty big hardware failure a month back that I've only just finished rebuilding from.  Also realized that I was still using the organizrtools/organizr-v2 Dockerhub image...  D'oh!  Switched over to organizr/organizr:latest and am still experiencing this.  Have been taking the container offline and doing direct SQL edits to the DB to reorder tabs, which is workable if a bit cumbersome/risky.  Happy to do a live session -- just let me know how I can help.  Again, thanks for building such INCREDIBLE free software, and for all your attentiveness to user feedback -- it's super appreciated!

**Comment by causefx** [comment]
no worries. actually next week I'm going to rewrite the tab management portion. hopefully it will make it faster. also i rewrote the api in the dev branch in the meantime.

**Comment by cferrey** [comment]
@causefx Awsome, thank you so much.  I'll keep an eye out for that commit and can test the dev tag in the next couple weeks.  Will keep you posted.

**Comment by causefx** [comment]
@cferrey can you test the lastest dev branch?

**Comment by cferrey** [comment]
@causefx Seems to be working as expected on master branch now, at least for newly added tabs!  I also deleted a few to bring the total count down, which may have helped.  But the new "save tab order" button seems to be working.  Thanks.
