### ISSUE TITLE
Plex invites are lacking email setup/ are not being sent

### ISSUE THREAD

**Issue by achmetinternet** [causefx/Organizr#1176]
Version: 2.0.180
Branch: v2-master
Server OS: *nix
PHP: 7.2.17
Install Type: Native
Auth Type: internal
Auth Backend: 
Installed Plugins: 
Installed Themes: Plex Theme:2.8.0
Theme: Organizr
Local: true
oAuth: false
Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.157 Safari/537.36
<hr>

##### Problem Description:
I activated the Media Invites Plugin and tried to send a friend and myself an invite. When I hit the send button it says it was sent but neither my buddy and I have received an invite.

<hr>

##### Reproduction Steps:
see above

<hr>

#### Errors on screen?  If so paste here:

```

```

**Comment by Roxedus** [comment]
Have you set up the phpmailer plugin?

**Comment by achmetinternet** [comment]
Done it now but still have some issues, i.e. the mail is not being sent. Just that now I actually get an error.

**Comment by causefx** [comment]
send a test email with email plugin.  then go from there.

**Comment by achmetinternet** [comment]
Is there a debug log I can attach? Where do I find it?

causefx <notifications@github.com> schrieb am Do., 16. Mai 2019, 01:01:

**Comment by causefx** [comment]
no debug for mail, but there is a test button.  Make sure to save all settings before hitting test button:

![image](https://user-images.githubusercontent.com/16184466/57816021-998f0a00-772e-11e9-8e9a-92b7b6878117.png)
