### ISSUE TITLE
[Feature request] hide Organizr login in backend only | add multiple groups on the same tab

### ISSUE THREAD

**Issue by skillfr** [causefx/Organizr#1178]
Feature requests:

Hide "organizr-login-heading" when we choose "authentication backend only"
https://i.imgur.com/m14dKqa.png

----------------------------------------------------------------------------------

Add multiple groups on the same tab

Here are new features!
Thank you for this wonderful all in one

**Comment by jonathanfinley** [comment]
The purpose of leaving organizr-login-heading is so that when the Plex backend goes down you can still get into your site.

**Comment by skillfr** [comment]
Fix thanks

https://github.com/causefx/Organizr/commit/5445563859d81c1c8a8e40873ab33f15cfabeedf
