### ISSUE TITLE
Allow empty password for Deluge

### ISSUE THREAD

**Issue by quekky** [causefx/Organizr#1179]
###### Operating System: Windows/MacOS/Ubuntu
<hr>

##### Problem Description:
Deluge allow empty password.

When I leave the password empty in the Organizr settings, it doenst show on the homepage

<hr>

##### Reproduction Steps:

<hr>

#### Errors on screen?  If so paste here:

```

```

**Comment by angrycuban13** [comment]
I can reproduce this issue on Windows. When adding Deluge as a homepage item it will error out with the following: 
![image](https://user-images.githubusercontent.com/39564898/58522449-0cb06b80-8186-11e9-9641-0b4f988fdea7.png)

**Comment by ddimick** [comment]
Same here. I don't want/need a password for Deluge but am forced to set one for Organizr.

**Comment by causefx** [comment]
the issue lies with the deluge class wrapper - atm there isn't another out there.  If time permits in the future I will take a stab at it.

**Comment by ddimick** [comment]
Can you take another look? Just as a quick test, I set `$password = ""`  at the top of the deluge class construct function, and it worked just fine with a blank password configured on my Deluge system.

```php
class deluge
{
	private $ch;
	private $url;
	private $request_id;
	
	public function __construct($host, $password)
	{
		$password = "";
		$this->url = $host . (substr($host, -1) == "/" ? "" : "/") . "json";
		...
```

This edit also worked:
```php
function delugeConnect()
{
	if ($GLOBALS['homepageDelugeEnabled'] && !empty($GLOBALS['delugeURL']) && !empty($GLOBALS['delugePassword']) && qualifyRequest($GLOBALS['homepageDelugeAuth'])) {
		try {
			// $deluge = new deluge($GLOBALS['delugeURL'], decrypt($GLOBALS['delugePassword']));
			$deluge = new deluge($GLOBALS['delugeURL'], "");
```

**Comment by causefx** [comment]
i would edit this line instead:

```
public function __construct($host, $password = '')
```

if someone that has a password on their install I can push that fix if it works.

**Comment by ddimick** [comment]
If I apply that line and blank the Deluge password in the Settings/Homepage Items, it does not work. I verified that config.php shows `'delugePassword' => '',` when I blank the password in Settings.

If I leave a string in Settings/Homepage Items and just set `$password = ''` in the construct function, it does work. It must be picking up a non-empty string from somewhere.
