### ISSUE TITLE
[Feature Request] Allow change of the Settings icon

### ISSUE THREAD

**Issue by lgromb** [causefx/Organizr#118]
tl;dr : title

I've changed all of my icons for text png for quick referencing, I'd like aswell to change the Settings icon. Could dig through the ressources files but it'd be nice to have the same option under the Tab settings as well.

**Comment by causefx** [comment]
hmmm, can you show me what icon you want to use?

**Comment by lgromb** [comment]
Well basically it's a transparent png with white text on it : 

![plex](https://cloud.githubusercontent.com/assets/7590118/23410933/2c26e484-fdd1-11e6-9ee1-1a48d30df2bf.png)

**Comment by causefx** [comment]
ah ok.  for now upload it as settings.png then upload it again as settings2.png, when i code it, i will have it check for settings2.png and if it exists it will use that first.

**Comment by causefx** [comment]
also, it is hardcoded to spin that icon :/

**Comment by lgromb** [comment]
Oh yeah I forgot about the spinning icon... Just keep this as some kind of toggle for those who wants to change the icon to match the rest of theirs, it's absolutly non-critical :) thanks !

**Comment by causefx** [comment]
i have an idea.  i will let you know

**Comment by ahmdr1246** [comment]
كيف  نفهم الرمز  والتعامل مع التغيرا

**Comment by causefx** [comment]
for those wishing to use a ssecondary icon for settings just add an icon in the images folder named settings2.png this will use that icon instead and will disable the spinning.
