### ISSUE TITLE
Cardigann image

### ISSUE THREAD

**Issue by SavageAUS** [causefx/Organizr#1181]
###### Operating System: unRAID

Please add Cardigann image.
![cardigann 11a25e34](https://user-images.githubusercontent.com/17326832/58369365-69b6e200-7f38-11e9-94a2-86197df5dfa6.gif)

**Comment by angrycuban13** [comment]
This is in a GIF file extension. Do you have a file that ends in PNG?

**Comment by tronyx** [comment]
https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/cardigann.png

**Comment by tronyx** [comment]
This can now be closed.
