### ISSUE TITLE
Organizr V2 reset after re-deploy

### ISSUE THREAD

**Issue by kattsmurf** [causefx/Organizr#1182]
Organizr Version: 2.0.180
Branch: Master
WebSever: Nginx
Operating System: Ubuntu 18.04

Problem Description:
I pruned Docker, removing all images, containers etc. then pulled organizrtools/organizr-v2:php-fpm again and started it, and now Organizr acts like a fresh install. When I browse to Org I get to the setup wizard and everything's gone, even though I kept my config folder entirely intact since before the prune.
Every other container I'm running is exactly like before, except Organizr.
My db is in /config/www/db/organizr.db, so that's also intact.

Any ideas on what happened and if/how I can restore?

**Comment by kattsmurf** [comment]
Nevermind, I'm an idiot.

**Comment by causefx** [comment]
no worries brother. we all have those days.
