### ISSUE TITLE
Missing 'http://' passes test but doesn't work

### ISSUE THREAD

**Issue by DavHau** [causefx/Organizr#1183]
###### Operating System: Docker

When editing a Tab and not putting https:// in front of the url, then "Test Tab" succeeds with "Tab can be set as iFrame" but when the tab is actually used, firefox reports "The address wasn’t understood".

I would suggest to either automatically add "http://" if the user didn't specify the protocol, or force the user to type it in.

**Comment by angrycuban13** [comment]
Are you talking about Tab URL or Local Tab URL?

For Tab URL you should only have to specify either `/service` or if you have a subdomain you need to put the full address.

**Comment by DavHau** [comment]
I'm talking about Tab Url.
Yes, if you specif a subdomain without "http://" the test succeeds but visiting the iFrame fails.

**Comment by angrycuban13** [comment]
Having `http://` filled in automatically  in front of Tab URL will affect others, since users normally specify subfolders in there as well and you dont need to include the full URL for your subfolder. 

I'll let one of the devs/staff respond as they might have a better worded response as to why it is possible or why it is not.

**Comment by causefx** [comment]
If I am not mistaken, the browser treats it like how you would type the url in address bar.

**Comment by causefx** [comment]
If http or https isnt set it will auto add http

![image](https://user-images.githubusercontent.com/16184466/75799280-24300c80-5d35-11ea-82b0-8f18cd9d6ac8.png)


![image](https://user-images.githubusercontent.com/16184466/75799266-1e3a2b80-5d35-11ea-858f-b826c016caf8.png)
