### ISSUE TITLE
Typo in issue template

### ISSUE THREAD

**Issue by DavHau** [causefx/Organizr#1184]
The template for github issues has a small typo in line 4:
'###### WebSever: Nginx/Apache'
WebSever
WebServer

**Comment by tronyx** [comment]
You could've forked the repo, fixed the typo, and submitted a Pull Request all on your own, but I've done it for you with #1185 and #1186 for Master and Dev respectively. Please close this as it will be fixed when CauseFX approves the merges.

**Comment by tronyx** [comment]
This was resolved with https://github.com/causefx/Organizr/commit/4a8c245b96eb0cbb0672bc1c2f8abc6b1dc8591e
