### ISSUE TITLE
Healthchecks.io Tag issue?

### ISSUE THREAD

**Issue by herbi3** [causefx/Organizr#1196]
Organizr Version: V 2.0.235
Branch: Master
WebServer: Nginx
Operating System: Windows Server 2016
<hr>

##### Problem Description:
Tags within Healthchecks.io don't seem to work?

<hr>

##### Reproduction Steps:
Enter any tag within the same project, nothing returns apart from all items (Instead of specific tags)

<hr>

#### Errors on screen?  If so paste here:
I really have nothing to go off apart from refreshing the screen ¯\_(ツ)_/¯

**Comment by angrycuban13** [comment]
Show me an example of one of your tags

**Comment by herbi3** [comment]
for testing purposes, I tried the word "tag1"

**Comment by angrycuban13** [comment]
That's not how that works lol. Did you read the docs on it?

**Comment by herbi3** [comment]
I didn't think thats how it worked!. I've found extremely little support on this.. is this directly referring to the tags for the check itself within healthchecks.io?

**Comment by angrycuban13** [comment]
Oh wait are you talking about Organizr tags or the healthchecks site?

**Comment by herbi3** [comment]
healthchecks.io

Under the tag part, I ended up naming of the tags to tag1 within healthchecks.io, entered tag1 into organizr and still no luck. Am I missing something?

**Comment by angrycuban13** [comment]
Yeah so if you want an icon to appear next to the check you need to specify a URL that points to an image. Example:

`https:/domain.com/images/sonarr.png`

However, we were able to replicate the whole HealthChecks module disappearing from the Organizr homepage if using `tag1`

**Comment by tronyx** [comment]
It's for the tags you set on the checks within Healthchecks.io. For example, I created a tag called utilities for grouping Portainer and PiHole together. When I put that tag into the Homepage Items box it should only show those two checks, but instead, the Homepage Item no longer displays on the homepage. Seems there is an issue.

**Comment by tronyx** [comment]
I can confirm that the listed commit into Dev does resolve this issue.

**Comment by causefx** [comment]
Yeah, not sure how the `?` didn't make it in there....

**Comment by herbi3** [comment]
Thank you! Seems that single tags work, but not multiple tags.

**Comment by causefx** [comment]
It is working as designed by the healthchecks api:

https://healthchecks.io/docs/api/#list-checks
![image](https://user-images.githubusercontent.com/16184466/59228918-e6c79580-8b8d-11e9-99cd-4c9afa3a8283.png)

**EDIT**
To clarify my vague post.... (lol sorry)

The tags are filter tags...
```
Filters the checks, and returns only the checks that are tagged with the specified value.This parameter can be repeated multiple times.
--
```
As you can see in this test:

![image](https://user-images.githubusercontent.com/16184466/59229097-589fdf00-8b8e-11e9-8335-bddc90091bf2.png)


I have `docker` tags with about 15 entries and 2 that have both `set` and `docker`

**Comment by herbi3** [comment]
Whats the new delimiter for multiple tags within Organizr?

**Comment by causefx** [comment]
Sorry, check my edit from above, the delimiter is still `,`

**Comment by herbi3** [comment]
hmmmm. Im still having trouble with multiple tags. I found out health checks is case sensitive. Ive tried different delimiters (Comma doesn't seem to work?)

Ive tried changing the tag names etc to something simple, but no luck yet!

**Comment by causefx** [comment]
settings:
![image](https://user-images.githubusercontent.com/16184466/59229582-a49f5380-8b8f-11e9-92e1-87a26dfd1955.png)

hp:
![image](https://user-images.githubusercontent.com/16184466/59229596-ae28bb80-8b8f-11e9-8d0c-44d4989e5636.png)

**Comment by herbi3** [comment]
Healthchecks.io
<img width="94" alt="Screen Shot 2019-06-11 at 7 55 24 am" src="https://user-images.githubusercontent.com/11141749/59229663-60a75f80-8c1e-11e9-8b70-7b42e1c1ddf2.png">
Settings
<img width="638" alt="Screen Shot 2019-06-11 at 7 55 36 am" src="https://user-images.githubusercontent.com/11141749/59229666-60a75f80-8c1e-11e9-95c3-ad4ecf09e125.png">
Result
<img width="1547" alt="Screen Shot 2019-06-11 at 7 55 42 am" src="https://user-images.githubusercontent.com/11141749/59229667-60a75f80-8c1e-11e9-8e2a-6216e3a0ec0a.png">

**Comment by causefx** [comment]
do any of your healthchecks have both tags assigned to it?

**Comment by herbi3** [comment]
nope

**Comment by causefx** [comment]
that is why then...  The tag feature on healthchecks is a filter only, not sure why they did that.  Using two tags will only result in items that have both tags present....

![image](https://user-images.githubusercontent.com/16184466/59229839-6a828180-8b90-11e9-869f-16debb3d9a0c.png)

**Comment by herbi3** [comment]
¯\_(ツ)_/¯ adding a minimum of two tags worked!
