### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by rix1337** [causefx/Organizr#12]
A last request for tonight/now

Allow us to create translation files. I will gladly offer German strings!

**Comment by causefx** [comment]
This is certainly doable. I just have to figure out the UI on mobile.

**Comment by rix1337** [comment]
Cool, just had to get those ideas out. I'll leave you alone for now :P

You need a donation page btw!

**Comment by causefx** [comment]
lol no donations for me man. I'll probably put up a link for some type of charity.

**Comment by rix1337** [comment]
That's very kind of you.

**Comment by causefx** [comment]
Oh Snap?!
![image](https://cloud.githubusercontent.com/assets/16184466/21631983/ae97f1a0-d1fe-11e6-9e33-d08e38d232d5.png)

**Comment by rix1337** [comment]
Oh dang. That looks good

**Comment by causefx** [comment]
I will compile a list of strings and post here so you can help with the German words :)

**Comment by rix1337** [comment]
Gladly!

**Comment by causefx** [comment]
@rix1337 Help me out brother :)

https://github.com/causefx/Organizr/blob/develop/lang/en.ini

**Comment by rix1337** [comment]
Oh snap #60 
Thanks for the frequent updates!

**Comment by causefx** [comment]
:) thanks man!

**Comment by rix1337** [comment]
'welcome! I will fix any inconsistent string, once its implemented..

**Comment by rix1337** [comment]
A few things I found:

The cookie missmatch, login successful and incorrect login (bad_auth) warnings are still hardcoded English.
Also the log section is still to be translated.

Otherwise German is working fine 👍  Awesome!

**Comment by causefx** [comment]
yea for the login log, the strings are injected through javascript, that may be a while before those get implemented.

**Comment by rix1337** [comment]
Alright, that's fine with me. My users will never see that page, anyway.. 😄

**Comment by causefx** [comment]
lmao! true. Other than that, how's it working along?

**Comment by rix1337** [comment]
Really well, actually. It's the perfect interface for my needs. Fail2ban keeps out the bad guys (none so far, but you never know).

The last missing feature for me would be the proxy support. That would only keep organizr exposed to the web for authentification. Tiny attack vectors ftw. But that's an "enthusiast"'s thing to worry about... 

I have limited experience in actual coding, so no way to implement the proxy support myself.
Maybe another helpful person contributes to the project :D

Two things I would not add as feature requests:
- Persistent login on multiple devices would be cool (multiple valid auth tokens)
- noone cares about 2FA on a personal site, but I might look into implementing it myself... (no way I get the proxy working, though)

**Comment by causefx** [comment]
I will look into multiple devices and will let you know how it goes.  I'm still actively looking for proxy support but all the scripts are crap that i have found.  BTW: did you see my other message about the reverse proxy?

**Comment by rix1337** [comment]
I just blatantly ignored that one. I cannot check the baseurl feature right now. I am not using a reverse proxy for organizr, but can look into this later.

**Comment by causefx** [comment]
no worries, I just remembered that at one point you had it.  :)

**Comment by rix1337** [comment]
Alright :) the fail2ban demo and this test is still on my list. Hopefully for this week!

Cool stuff on the multilogin.

I figured as much on the PHP-Proxy side of things. It would have to work similarly to nginx.. and also reliably. No idea how to achieve that.

**Comment by causefx** [comment]
yea, it just has too many variables.  We shall see though.

**Comment by rix1337** [comment]
Yeah. Ill do some research on this as well..

**Comment by rix1337** [comment]
Most of the variables are properly translated now.

Only "Print" from the log page is not. It should show as "Drucken" in German

**Comment by causefx** [comment]
correct, Print and a few new strings I added, I need to add more to the help section so that will be even more.
