### ISSUE TITLE
[Feature Request] HealthChecks Homepage Groups

### ISSUE THREAD

**Issue by ilovepancakes95** [causefx/Organizr#1202]
###### Operating System: CentOS 7
<hr>

##### Feature Request:

Would be great to be able to group together certain HealthChecks entries on the homepage and then name the group, to be able to keep it a little more organized as opposed to having one giant table of them all.
<hr>

**Comment by causefx** [comment]
How would this work visually?

**Comment by ilovepancakes95** [comment]
> How would this work visually?
> […](#)
> Sent from my iPhone

I think the most space effective way looking at it now would be the groups showing up as columns with a group name on top and then the ability to move entries between columns or define which column/group they should be in somewhere else in settings. See attached mockup idea...

Ideally, within the column/group the entries would be sorted alphabetically (if not able to manual sort) and the services that go down and flash red would override sorting and go to the top of the column. Yep, I'm getting fancy here....

![Screen Shot 2019-06-20 at 7 25 58 PM](https://user-images.githubusercontent.com/52054078/59887423-4e04f700-9391-11e9-85e1-417d130d7897.png)

**Comment by tronyx** [comment]
Tough to do that when you can't even pull groups like that from the HC.io API.

**Comment by ilovepancakes95** [comment]
> Tough to do that when you can't even pull groups like that from the HC.io API.

Yeah I noticed a comment elsewhere that tags on HC.io don't work like that so figured it would be functionality that would have to be written into Organizr directly for sorting. I know not much about web design so no idea if that functionality takes 5 hours, 10 hours, or 100 hours to code.

**Comment by tronyx** [comment]
You can use CSS to organize them a bit and the failing ones automatically move to the very first tile.

**Comment by causefx** [comment]
I can play around with it, let ya'll know what i can come up with

**Comment by causefx** [comment]
We are moving Feature Requests away from **GitHub** and **FeatHub**.  We are now on **_FeatureUpvote_** which is located here:
### **https://vote.organizr.app**
If will also be a tab in Organizr update this Friday 22 Jan 2021


If this Feature Request was already on FeatHub it will get moved over within the week - no further action is needed.
If not, please create a new Feature Request at our new home so we can better keep track of them.
