### ISSUE TITLE
Homepage Loading Sections Displaying for Disabled Items

### ISSUE THREAD

**Issue by hirenshah** [causefx/Organizr#1204]
###### Operating System: Docker on Synology NAS
<hr>

##### Problem Description:
When the homepage is refreshed, "loading" sections are displayed for the various items before the actual content is shown.  Such sections are visible for items enabled under Emby and Plex (haven't tested others) even though the actual item is disabled.

Note: The first "Now Playing" section in my screenshots is for Plex, which is enabled.  The bottom 2 x "Loading" sections are for Emby.
<hr>

##### Reproduction Steps:
1)
Disable Emby Homepage Item
Enable Emby Active Sessions
Enable Emby Recently Added
Refresh Homepage (note the "Loading" sections)

2) 
Disable Emby Active Sessions
Disable Emby Recently Added
Refresh Homepage (note the "Loading" sections)
<hr>

![Emby Disabled with Active and Recents Enabled](https://user-images.githubusercontent.com/418112/60138111-09b69400-97a1-11e9-838d-478d9f64ff7c.png)

![Showing Emby Disabled](https://user-images.githubusercontent.com/418112/60138113-0e7b4800-97a1-11e9-83c2-a5bebe46e0fe.png)

![Showing Emby Active Enabled](https://user-images.githubusercontent.com/418112/60138117-12a76580-97a1-11e9-8aed-8a48b5bc820d.png)

This was enabled when the first screenshot was taken, and then disabled for the last one below:
![Showing Emby Recents Disabled (changed between first and second homepage screenshots)](https://user-images.githubusercontent.com/418112/60138124-163aec80-97a1-11e9-848a-adf6790bee85.png)

![Emby Disabled with Only Active Enabled](https://user-images.githubusercontent.com/418112/60138125-1935dd00-97a1-11e9-8843-d8d1a13d4563.png)

**Comment by angrycuban13** [comment]
Did you have those sections previously enabled? If so, have you cleared your cache?

**Comment by hirenshah** [comment]
Cheers for the quick fix @causefx 👍
