### ISSUE TITLE
Organizr User not seeing made requests

### ISSUE THREAD

**Issue by benzoto** [causefx/Organizr#1205]
**Organizr Version: 2.0.235
Branch: Master
WebServer: Nginx
Operating System: Ubuntu 18.04 - Docker Container**
<hr>

**Problem Description:**
Organizr User does not see the made requests in the Organizr Homepage.
Organizr Admin can see those requests.
On the homepage, it is only seen the recently added (Plex) and the request frame is empty however the User can make requests through thе magnifying glass.
The User is imported in both Organizr and Ombi as a Plex User. The Permissions in OMBI are defined. Tried to change the user to Power User but it didn't helped
<hr>

##### Reproduction Steps:

<hr>

#### Errors on screen?  If so paste here:
Error in the Logs - related to the Admin User -

26 юни 2019 10:32 | mbox03_admin@XXXXX.com | IP XXXXX | Ombi Token Function - Ombi did not return Token [Execution Time: 80.7ms]
-- | -- | -- | --

However I'm not sure whether those are related to the issue with the User.

```

**Comment by benzoto** [comment]
I've been trying to fix this for the last few days and just now I've noticed that it has a dependency on Limit to User setting for OMBI.
Not sure how this works exactly having in mind that the USER ID is the same in Plex/Orgranizr/OMBI and i can log everywhere with that user ID and the same password.
Can anyone explain it?

**Comment by angrycuban13** [comment]
Can you check if the homepage item permission is set correctly? If it is not set to user, they will not see the requests.

![image](https://user-images.githubusercontent.com/39564898/60182069-2aa2d780-97e9-11e9-8daa-fe1b14670438.png)

**Comment by causefx** [comment]
Limit to user does just that.  If the organizr username and ombi username match.... it will show the requests made by that user only.  If that option is off, it will show all requests, regardless of username

**Comment by tronyx** [comment]
Please close this if we were able to resolve the issue.
