### ISSUE TITLE
[V2] Can't make ombi requests form homescreen

### ISSUE THREAD

**Issue by paunsurfer** [causefx/Organizr#1208]
###### Operating System: Windows 7
<hr>

##### Problem Description:

There is no search icon in the ombi or plex sections of the homepage.
A search for media not on the server provides no results or option to request
<hr>

##### Reproduction Steps:

<hr>

#### Errors on screen?  If so paste here:

```

```

**Comment by angrycuban13** [comment]
Have you enabled the Ombi or Plex homepage item?

**Comment by HalianElf** [comment]
Ombi SSO also needs to be setup for the search button on the homepage.

**Comment by paunsurfer** [comment]
Ombi and Plex are both set up.

I get a "recently Added" plex module and a "Requests" ombi module on the homepage.

I have sso enabled in Ombi and ombi and plex are both successfully configured under organizer sso settings

**Comment by angrycuban13** [comment]
Did you test the home page items before you saved them?

**Comment by paunsurfer** [comment]
As in test the connections after inputting the API keys? If so, yes.

Here is a screenshot
![orghms](https://user-images.githubusercontent.com/52383616/60400932-d4f76380-9b37-11e9-975d-c85ba0ac611c.png)

**Comment by paunsurfer** [comment]
Thank you for helping me troubleshoot this. I can't believe how quickly you guys came to help. This community is awesome!

**Comment by HalianElf** [comment]
Username in the top right -> Debug area. What do you get when you run the SSO debug command?

**Comment by paunsurfer** [comment]
I get a False status returned for ombi, plex AND tatulli SSO.
It's showing as enabled in the organizr settings though.

**Comment by HalianElf** [comment]
Ok so that's why the button isn't on the homepage, just have to figure out why your SSO isn't working. Did you set up your SSO based on the information from here? https://docs.organizr.app/books/setup-features/page/sso

**Comment by paunsurfer** [comment]
i will confirm and report back

**Comment by paunsurfer** [comment]
Success!

Steps to resolve for others experiencing this issue:

Followed guide posted by HalianElf - https://docs.organizr.app/books/setup-features/page/sso

Restart Ombi and Tatulli

Log out of Organizer and log back in Using Plex instead of Organizer local account


Thank you!!!
