### ISSUE TITLE
Any plans to add Medusa as a Homepage item?

### ISSUE THREAD

**Issue by jscottelblein** [causefx/Organizr#1209]
Normally in most cases I'm able to just use the SickRage/SickBeard option when adding [Medusa](https://hub.docker.com/r/linuxserver/medusa/) in other apps, since it's a fork of SR/SB, but it doesn't seem to work in Organizr.

Showing this error in the console:

Sickrage Connect Function - Error: Client error: `GET http://192.168.0.294:1045/api/967dbdeef051839c161cb8dd509dc/?cmd=future&sort=date&type=missed%7Ctoday%7Csoon%7Clater` resulted in a `404 Not Found` response: Traceback (most recent call last): File "/app/medusa/ext/tornado/web.py", line 1569, in _execute result = self.pre (truncated...) [Execution Time: 272.9ms]

Or am I just doing it wrong?

**Comment by causefx** [comment]
Hi.

I don't see any mention of any calendar in their API.

https://medusaapi.docs.apiary.io/#

I will open back up if they do have it, or once they add it.
