### ISSUE TITLE
[Feature Request] Specify basic authorization for a tab

### ISSUE THREAD

**Issue by rcdailey** [causefx/Organizr#1212]
Please add the ability to inject basic authorization header to services loaded in a tab in Organizr v2. This is especially useful for services like Transmission and NZBGet, that do not use API keys. Here is the rationale/use cases:

1. I load Transmission via Organizr. I set up NGINX to authorize (via `auth_request /organizr/auth-0;`) Transmission with Organizr. However, I am prompted for basic authorization credentials after that. I don't want to be prompted for basic auth here since I authorize through Organizr. To prevent this, Organizr should send the appropriate basic auth HTTP headers to Transmission when loaded through the iframe/tab.

2. I load Transmission outside of Organizr through API only. Specifically, this is the `/transmission/rpc` endpoint. This is usually to support apps, like NZB360 on Android, that make RPC calls to Transmission to use it instead of going through the web interface. In this case, I want the app to specify the Transmission basic authorization credentials.

**Comment by GilbN** [comment]
Disable RPC authentication and https://docs.organizr.app/books/setup-features/page/serverauth#bkmrk-excluding-a-location

**Comment by rcdailey** [comment]
This won't work unfortunately. I apologize as this issue is difficult to explain. The RPC endpoint needs to be invoked from outside Organizr. If I disable RPC credentials then anyone outside can control transmission without a password.

**Comment by GilbN** [comment]
Disable it in transmission and add basic auth on /transmission/rpc with nginx?

**Comment by rcdailey** [comment]
If I do that anyone on the internet can make RPC calls to transmission without a password

**Comment by GilbN** [comment]
how can they do that when you have basic auth on the /transmission/rpc/ endpoint??

**Comment by GilbN** [comment]
```nginx
location /transmission {
	auth_request /auth-0;
	proxy_pass http://[IP]:[PORT]/transmission;
	
location /transmission/rpc {
	auth_request off;
	proxy_pass http://[IP]:[PORT]/transmission/rpc;
	auth_basic "Restricted";
	auth_basic_user_file /config/nginx/.htpasswd;
	}
}
```

Note you cant use custom errorpages when doing that. So you can use a subdomain without custom error pages.

**Comment by rcdailey** [comment]
Oh I see what you meant now. I think that won't work for a different reason though. The web interface still calls the RPC endpoint. And you might get a basic auth prompt in the browser. I'll test it but I already confirmed the browser uses it by watching the requests it makes.

**Comment by rcdailey** [comment]
Also: Why are you nesting the `location` blocks? I read the NGINX documentation but am still unclear on the behavioral differences. For example, how is it different than:

```
set $upstream_transmission http://transmission:9091;

location /transmission {
    auth_request /organizr/auth-0;
    proxy_pass $upstream_transmission;
}

location /transmission/rpc {
    proxy_pass $upstream_transmission;
    include /config/nginx/proxy.conf;
    auth_basic "Restricted";
    auth_basic_user_file /config/nginx/transmission.htpasswd;
}
```

**Comment by rcdailey** [comment]
I confirmed that this solution doesn't work. Even worse, the web UI doesn't prompt the user for basic auth credentials, the UI just doesn't show any updated information since the rpc endpoint call failed. One of the headers I get back in the response is:

```
www-authenticate: Basic realm="Restricted"
```

This is why I originally asked that Organizr be able to properly respond to the basic authorization when a site is accessed through it. It allows basic auth to be automated through Organizr, but still required when the site is used outside of Organizr. It's also much simpler because it doesn't require complex NGINX configuration.

**Comment by GilbN** [comment]
Right. I don't use transmission so I didn't really test it. @causefx will need to look at this.

**Comment by ArbiterGR** [comment]
I'm having the same Problem.

**Comment by itsecbern** [comment]
For me It would be as well really helpful, if someone could implement a new function to respond to the basic authorization of some backends when the pages are accessed through Organizer iframe. 

(E.g. A new Option in the Tabs settings where I could set Basic Auth to true and enter the creds would be great!)

**Comment by rcdailey** [comment]
@causefx I know you're busy, but if you get a spare few minutes I'd love to see what you think about this idea.

**Comment by stanthewizzard** [comment]
I have the same issue :/

**Comment by causefx** [comment]
I'm not sure I can inject headers from organizr in any way...
