### ISSUE TITLE
Add IDs to qBittorrent Homepage item?

### ISSUE THREAD

**Issue by jscottelblein** [causefx/Organizr#1213]
Any chance of adding something like:

    <td class="hidden-xs" id="qb-`+status+`">`+status+`</td>

in place of

    <td class="hidden-xs">`+status+`</td>

[Here](https://github.com/causefx/Organizr/blob/1ba1875777d3547c26de85674c9d4bce69897151//js/functions.js#L5223)?

I was thinking it'd be cool to add some custom CSS to colorize the text there based on it's status.

**Comment by causefx** [comment]
we can do this but it will have to be class not ID

**Comment by jscottelblein** [comment]
Whichever works best for ya. I just want to be able to for example, set completed torrents to green, paused to yellow, etc. etc. 👍

**Comment by causefx** [comment]
Added in dev branch

**Comment by jscottelblein** [comment]
Thanks!

**Comment by jscottelblein** [comment]
@causefx Heyas Bro, hate to sound like a [schnorrer](https://en.wikipedia.org/wiki/Schnorrer) (lol), but would it be possible to do the same for the other downloaders as well? (i.e. sabnzbd, nzbget) then I can color those as well, and use a single selector to do so.

![image](https://user-images.githubusercontent.com/1524526/76322915-f9543400-62b1-11ea-8606-044d3653f487.png)

I'd really appreciate it! <3

P.S. Quick question, next to the "completed" labels there's a blue bar with an asterisk in it; what's that for? I can't really tell, and inspecting it doesn't really say anything descriptive either? Just curious.

**Comment by causefx** [comment]
that is the category name
