### ISSUE TITLE
[Feature Request] Set of wallpapers for login page

### ISSUE THREAD

**Issue by keliansb** [causefx/Organizr#1214]
Currently we have the possibility to set a wallpaper to the login page (Settings -> Customize -> Login page) :
![image](https://user-images.githubusercontent.com/22099779/60789900-844bc000-a160-11e9-8365-5dca82070683.png)
It would be nice to set multiple wallpapers, and randomly pick one when accessing the login page.

**Comment by causefx** [comment]
i may be able to access a csv here.

**Comment by causefx** [comment]
Added in dev branch

**Comment by keliansb** [comment]
Thanks a lot @causefx !
