### ISSUE TITLE
Movies in library can still be requested

### ISSUE THREAD

**Issue by joecan2** [causefx/Organizr#1217]
###### Operating System: Unraid
<hr>

##### Problem Description:
Users are able to request movies and TV shows that already exist in the library. For example, if I try to request 'Ghostbusters' from the homepage, it will let me request it, even though it already exists. That request is then passed to Ombi. As a test, I tried to request Ghostbusters in Ombi directly, and it tells me it already exists. Everything marked as "available" in Ombi is 100% correct, but the search box in Organizr doesn't reflect that. This leads to a lot of requests for movies that I already have in my library. 

<hr>

##### Reproduction Steps:
Search for an existing movie/TV show from the homepage.

<hr>

#### Errors on screen?  If so paste here:

```
No errors
```

**Comment by Roxedus** [comment]
This is because ombis api doesn't reply with the fact that the item is already in the media library. It requires a few extra calls to ombi, which should have unnecessary to start with.

**Comment by joecan2** [comment]
It looks like Ombi has a separate "getextrainfo" endpoint that needs to be called in order to resolve this. I assume that's what you mean by "requires a few extra calls to ombi"?
https://github.com/tidusjar/Ombi/issues/2502

**Comment by causefx** [comment]
I will leave this up to you guys - Do you want the extra api call (Slower) for this check?

**Comment by joecan2** [comment]
How much slower is the extra api call? If it's a matter of a few seconds, it probably won't be a big deal. Is there a way to build a toggle switch so an admin can turn the extra api call on or off?

**Comment by causefx** [comment]
this was fixed already - sorry for late notice
