### ISSUE TITLE
[Feature Request] Homepage Qbt download names

### ISSUE THREAD

**Issue by Rangdazzlah** [causefx/Organizr#1218]
##### Request Description:
If possible, an option to replace Qbt name with Radarr/Sonarr/Lidarr name in the Qbt Homepage items settings
e.g. Hot.Shots.1991.1080p.BluRay.H264.AAC-RARBG > Hot Shots! (1991)

**Comment by causefx** [comment]
We only have the data qbit provides

**Comment by Rangdazzlah** [comment]
no problem, thanks

**Comment by causefx** [comment]
this did give me an idea.  i will play around with it tomorrow.

**Comment by Rangdazzlah** [comment]
Could the information from the 'Activity' tab from each of the arrs be combined and used as a different Homepage item?

**Comment by causefx** [comment]
That was the idea i am playing around with.

**Comment by causefx** [comment]
We are moving Feature Requests away from **GitHub** and **FeatHub**.  We are now on **_FeatureUpvote_** which is located here:
### **https://vote.organizr.app**
If will also be a tab in Organizr update this Friday 22 Jan 2021


If this Feature Request was already on FeatHub it will get moved over within the week - no further action is needed.
If not, please create a new Feature Request at our new home so we can better keep track of them.
