### ISSUE TITLE
Images randomly disappearing.

### ISSUE THREAD

**Issue by ghost** [causefx/Organizr#1219]
###### Operating System: Windows 10
<hr>

##### Problem Description:
Images not appearing on the "Recently added" section of the home page.
Ombi request image not appearing on the sidebar.
Ombi requests not updating if they're available.
<hr>

##### Reproduction Steps:
Tried to do a clean install of both the master and develop brach, BUT using my own database.

<hr>

#### Errors on screen?  If so paste here:

```

```

**Comment by causefx** [comment]
Check file permissions for the cache folder

**Comment by ghost** [comment]
I have full access to the cache folder.

**Comment by ghost** [comment]
Kinda fixed images not appearing at "Recently added" section by changing from regular URL to ip:port for Plex. I have to manually click on refresh for the image to appear. Upon reload of the webpage, the image is still blank.

**Comment by angrycuban13** [comment]
What does your homepage item configuration look like?

**Comment by Pyrogeen** [comment]
Encountered this bug too, it appears to be happening while organizr is accessing plex over a secure connection (https), thumbnails started working after switching the connection and cleaning image cache folder(www/Dashboard/plugins/images/cache)

**Comment by tronyx** [comment]
@KevinBarselaar Did you get this resolved with input from comments?

**Comment by ghost** [comment]
Did a complete reset of my server and did the whole installation from scratch, which solved it. 

Never found out what the problem was though.

**Comment by KevinBarselaar** [comment]
Did a complete reset of my server and did the whole installation from scratch, which solved it. 

Never found out what the problem was though.
