### ISSUE TITLE
Insta - lockout account

### ISSUE THREAD

**Issue by HexaPath** [causefx/Organizr#1220]
###### Operating System: Windows/MacOS/Ubuntu
<hr>

##### Problem Description:

When setting "failed attempts" or something for login, that number can go to -1.
So i tried it, forgot about it, and now it's not possible to login with my account anymore. 
It's still possible to create account, tho only USERS.

Mainly , just make sure, that number doesn't go under 0. shouldn't be that hard.
<hr>

##### Reproduction Steps:

security - something... something failed password... didn't remember the structure of settings bar.
<hr>

#### Errors on screen?  If so paste here:

```
Login Error
You have been Locked out
```

**Comment by tronyx** [comment]
If you're actually using v1, it's no longer developed as v2 is out. That issue was resolved in v2.
