### ISSUE TITLE
Unable to Send Test Email

### ISSUE THREAD

**Issue by Vektor2** [causefx/Organizr#1221]
Organizr Version: V 2.0.270
Branch: Master
WebServer: Nginx
Operating System: CentOS 7
<hr>

##### Problem Description:

I have just set up Organizr using the install script on CentOS 7. I am unable to send a test email getting error:

`Mail Function - E-Mail Test Failed[SMTP connect() failed. `

I have tested telnet can connect.

```
[user@organizr ~]$ sudo telnet smtp.zoho.com 587
Trying 136.143.191.189...
Connected to smtp.zoho.com.
Escape character is '^]'.
220 mx.zohomail.com SMTP Server ready July 24, 2019 4:42:04 PM     
```
I have also done some research and found other threads with this issue but I was unable to fix it with the things that causefx suggested such as the config.php edits (https://github.com/causefx/Organizr/issues/583). 

[Here are screenshots of my settings pages.](https://imgur.com/a/14lKTWA)

Here is the output of my config.php

```
'PHPMAILER-enabled' => true,
'PHPMAILER-logo' => 'https://raw.githubusercontent.com/causefx/Organizr/v2-develop/plugins/images/organizr/logo-wide.png',
'PHPMAILER-smtpHost' => 'smtp.zoho.com',
'PHPMAILER-smtpHostAuth' => true,
'PHPMAILER-smtpHostPassword' => 'ADWPSM+ANLIW=', // fake
'PHPMAILER-smtpHostPort' => '587',
'PHPMAILER-smtpHostSenderEmail' => 'organizr@domain.com',
'PHPMAILER-smtpHostSenderName' => 'Organizr',
'PHPMAILER-smtpHostType' => 'tls',
'PHPMAILER-smtpHostUsername' => 'organizr@domain.com',
'PHPMAILER-template' => 'default',
'PHPMAILER-verifyCert' => true,
```

I have tried Authentication "off" with port 25, "SSL" with 465, and "TLS" with 587. 

<hr>

##### Reproduction Steps:

Configure PHP Mailer within GUI, save configuration, click Test.
<hr>

#### Errors on screen?  If so paste here:

```
Mail Function - E-Mail Test Failed[SMTP connect() failed.
```

**Comment by tronyx** [comment]
For reference:

https://www.reddit.com/r/organizr/comments/chg54h/unable_to_send_test_smtp/

**Comment by Roxedus** [comment]
Is it a Zoho US, or Zoho EU account(when you log in, is the url .com or .eu)?

**Comment by Vektor2** [comment]
Thanks, I posted here as well as I haven't received much traffic on the Reddit post. It is US based Zoho, using smtp.zoho.com.

I have no issues with any other self-hosted application sending email using smtp.zoho.com on port 587 using TLS auth. I can even telnet on that port. It is just failing with a general error using PHPmailer.

**Comment by causefx** [comment]
Please switch to dev branch and enable debug output and sent test again, please paste the output from console.

**Comment by Vektor2** [comment]
> Please switch to dev branch and enable debug output and sent test again, please paste the output from console.

I have switched to dev branch. How to I enable debugging for PHP Mailer?

**Comment by causefx** [comment]
next to send test email button. there will be a toggle next to it. toggle it, then save it. wait 2 seconds and hit test button.  output will be in console.

**Comment by Vektor2** [comment]
I am not seeing the debug option. I did restart the server and disable/re-enable the plugin as well. Is there a way to fully reinstall PHP Mailer? https://imgur.com/NRcOkSs

**Comment by causefx** [comment]
sorry. forgot to mention after switching branches you need to force install branch from setttings.

**Comment by Vektor2** [comment]
I did do it with the "Force Install" branch button method and it went through successfully. Main page stats note that I am on v2-develop branch.

**Comment by causefx** [comment]
try clearing cache

**Comment by Vektor2** [comment]
Browser cache and cookies? Or in the app?

I ran in incognito session and no debug option still.

**Comment by causefx** [comment]
Might wanna try manually pulling...

not sure why it isn't updating for you.  I just tested on another install and the update worked...
![image](https://user-images.githubusercontent.com/16184466/62010492-51259c80-b120-11e9-9c9c-2d8ddcee172f.png)


@christronyxyocum @Roxedus does the toggle show up for you guys?

**Comment by tronyx** [comment]
Yep, I can see it just fine.

**Comment by Vektor2** [comment]
I was able to run the "Retrieve" on Force install again and was able to get the debug option. 

Here is the output. Let me know where I can find the .txt if needed:
https://imgur.com/qSiNMmu

I wonder if my Hash key is too complex or broken? I have it set at 30 characters with high complexity. I have verified authentication with this SMTP account using another application. Something is off with the PW that PHP Mailer is handing off to the SMTP server.

**Comment by causefx** [comment]
clear your is cache as it isn’t updated on your end. that dialog should say to push F11 to check console.

**Comment by causefx** [comment]
mobile... top should say js cache

**Comment by causefx** [comment]
found this on permission denied for CentOS:

```
$ getsebool httpd_can_sendmail
$ getsebool httpd_can_network_connect
```
if you get these:
```
httpd_can_sendmail --> off
httpd_can_network_connect --> off
```
run this:
```
$ setsebool -P httpd_can_sendmail 1
$ setsebool -P httpd_can_network_connect 1
```
you may need to run as root:
```
$ sudo setsebool -P httpd_can_sendmail 1
$ sudo setsebool -P httpd_can_network_connect 1
```

Now try to send again...

**Comment by Vektor2** [comment]
Thanks, that did it! The output was set to  "off". I ran the setsebool commands and was able to send mail successfully.
