### ISSUE TITLE
FTP backend broken?

### ISSUE THREAD

**Issue by xannor** [causefx/Organizr#1222]
organizrtools/organizr-v2:latest container as of today

<hr>

##### Problem Description:
When I enable the Organizr DB + backend and set the backed to FTP it is no longer possible to log into Organizr, on the front end I just API connection error.

<hr>

##### Reproduction Steps:
Enable FTP backend 

<hr>

#### Errors on screen?  If so paste here:

```
2019/07/27 18:58:20 [error] 326#326: *28 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Call to undefined function ftp_connect() in /config/www/Dashboard/api/functions/auth-functions.php:282
Stack trace:
#0 /config/www/Dashboard/api/functions/api-functions.php(104): plugin_auth_ftp('*****', '*****')
#1 /config/www/Dashboard/api/index.php(651): login(Array)
#2 {main}
  thrown in /config/www/Dashboard/api/functions/auth-functions.php on line 282" while reading response header from upstream, client: 192.168.**.***, server: _, request: "POST /api/?v1/login HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "*****", referrer: "http://*****/"
```

### More Info ###
I am trying to use FTP because I want to use the usernames and passwords of my UnRaid server and this seems to be the only way to "emulate" a single sign on concept that I have found so far.

**Comment by causefx** [comment]
Sounds like FTP isn't installed on the docker... odd... let me checl

**Comment by causefx** [comment]
It seems as the docker image does not have FTP installed.  @christronyxyocum This something we can add on next container update?

**Comment by tronyx** [comment]
@xannor Please try the `organizrtools/organizr-v2:dev-latest` image I just built and pushed.

**Comment by xannor** [comment]
Yes, that worked.

**Comment by tronyx** [comment]
Awesome. I pushed the change out across all images now as well. Please mark this as closed when you have a moment.
