### ISSUE TITLE
Doubt if it can reverse proxy

### ISSUE THREAD

**Issue by MiguelNdeCarvalho** [causefx/Organizr#1223]
Hey,
First of all congrats for this beautiful app. I searched a bit but couldn´t find a clear answer to this. Is it possible for Organizr to reverse proxy the services running on server? For example if I connect externally to Organizr can it connect to the local service running on the server or I need to have connection drectly with the service too?
Thanks,
Miguel de Carvalho

**Comment by HalianElf** [comment]
No, you do the reverse proxies yourself. Organizr just iframes whatever URLs you give it.

**Comment by MiguelNdeCarvalho** [comment]
Thanks, so what does the `internal ` mean?

**Comment by HalianElf** [comment]
I'm guessing you mean on the location block for auth? It means the location block is used for requests internal to the server.

**Comment by MiguelNdeCarvalho** [comment]
I mean on the `Type`

**Comment by HalianElf** [comment]
Oh, it's used for pages internal to Organizr so the Settings and the Homepage.

**Comment by MiguelNdeCarvalho** [comment]
Oh ok. Thanks for your help :D
