### ISSUE TITLE
iCal calendar not working?

### ISSUE THREAD

**Issue by jscottelblein** [causefx/Organizr#1225]
Using 2.0.270 in Docker I tried adding this iCal link to the calendar:

http://api.calreply.net/webcal/545392f9-6070-45dc-b27e-f96e64775d3d

And it's not showing any of the items. Did I do it wrong?

Also another question; is it possible to add more than 1 iCal link?

**Comment by causefx** [comment]
fixed in dev

**Comment by jscottelblein** [comment]
> fixed in dev

tyvm, I appreciate it.

**Comment by causefx** [comment]
np
