### ISSUE TITLE
version:2.0.270

### ISSUE THREAD

**Issue by skidda666** [causefx/Organizr#1227]
###### Operating System: Windows Server 2016
<hr>

##### Problem Description:
Organizr v2 stuck on updating, just sits at 50% for 'starting unzip', has been doing this for a couple of months now.

<hr>

##### Reproduction Steps:
i click to update, it downloads dependencies then just sits there, I've tried reinstalling and still same issue occurs

<hr>

#### Errors on screen?  If so paste here:
no errors
![error]

![error](https://user-images.githubusercontent.com/29529765/62449512-5d20e800-b738-11e9-80e2-59ff27dfd374.JPG)

```

```

**Comment by tronyx** [comment]
There was a minor issue with that version and the updater so you'll need to manually update the files. If you used `git` to clone to grab the files you can just perform a `git fetch` and then a `git pull` or, if you downloaded and extracted the Zip archive you can simply do that again.

**Comment by causefx** [comment]
above solution is correct.
