### ISSUE TITLE
jackett with nginx reverse proxy - firefox issue

### ISSUE THREAD

**Issue by alberto-bracci** [causefx/Organizr#1229]
Jackett Version 0.11.507.0 
Firefox 68.0.1

Hi, I have the following nginx jackett config on my nginx.conf file 

location /jackett {
	proxy_pass http://localhost:9117;
	proxy_set_header X-Real-IP $remote_addr;
	proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
	proxy_set_header X-Forwarded-Proto $scheme;
	proxy_set_header X-Forwarded-Host $http_host;
	proxy_redirect off;
}

When I navigate to https://mydomain.com/jackett it redirects me towards the following obiously not working url:
https://mydomain.com/jackett/UI/192.168.1.1://mydomain.com/jackett/UI/Login?ReturnUrl=%2Fjackett%2FUI%2FDashboard

whereas when I plug the same https://mydomain.com/jackett into a private/incognito firefox session it correctly leads me to the working https://mydomain.com/jackett/UI/Dashboard

I have several other services correctly working on the same nginx server, like sonarr, emby or others and everything works with usual firefox navigation

**Comment by Roxedus** [comment]
This is not a Organizr issue, *but* we can "solve" it in organizr. Set the taburl to `/jackett/`

Notice the last slash

**Comment by tronyx** [comment]
Exactly as our example shows:

https://github.com/organizrTools/Config-Collections-for-Nginx/blob/master/Apps/jackett.conf

As a safety measure, you can also add this above the existing block to make sure the trailing `/` is always included:

```
    # Jackett location redirect block
    location /jackett {
        return 301 /jackett/;
    }
```

**Comment by alberto-bracci** [comment]
I am really sorry but I was convinced I had opened the issue in the jackett repository. I am actually not using organizr, and this is indeed not an organizr issue.

Still, your example config works in private navigation but not in public, even with the redirect block added.

**Comment by Roxedus** [comment]
Clear browser cache

**Comment by tronyx** [comment]
Please close this if we were able to resolve the issue.
