### ISSUE TITLE
Qbittorrent showing incorrect order and torrents

### ISSUE THREAD

**Issue by spicerackk** [causefx/Organizr#1230]
###### Operating System: Windows
<hr>

##### Problem Description:
When having Qbittorrent set on the Home Page, I have selected sort by "Progress" and have ticked "Hide Completed". The widget is then showing completed torrents in the list, as well as not sorting by progress. 

<hr>

##### Reproduction Steps:
No matter whether the hide Completed toggle is ticked or not, it shows completed in the list. 

<hr>

#### Errors on screen?  If so paste here:

```

```

**Comment by causefx** [comment]
is this still happening?  if so please reopen issue.
