### ISSUE TITLE
[V2] Plex oAuth succesful but login fails with timeout

### ISSUE THREAD

**Issue by TristBella** [causefx/Organizr#1231]
Version: 2.0.270
Branch: v2-develop
Server OS: win
PHP: 7.3.7
Install Type: Native
Auth Type: both
Auth Backend: plex
Installed Plugins: 
Installed Themes: 
Theme: Organizr
Local: false
oAuth: true
<hr>

##### Problem Description:
After enabling Plex oath in the settings trying to log in with my admin's Plex oAuth fails. However the oAuth itself seems to have been succesfully completed. The notifcation "oAuth Successful - Please wait..." appears. However also the error "Login error - Wrong username/email/password combo" also appears. Login is cancelled afterwards.
I can however login when on the machine where Organizr exists. When using NGINX reverse proxy (which is the outside world) login fails with the following error in log:
"Plex Token Check Function - Error: cURL error 28: Resolving timed out after 10000 milliseconds [Execution Time: 11.08s | 11080.5ms]"
I can connect directly to Plex from the outside NGINX domain (https://plex.domain.com) and from local ip domain (http://192.1.1.1:32400) on the hosting box.

Tried resetting the token, didn't work.

Only thing that seems to work is rebooting the Windows machine, then it all works as expected, but this will only work for about a day or so. Unraid docker did not seem to have this issue.

<hr>

**Comment by tronyx** [comment]
The application is the same regardless of the platform that it's hosted on. Sounds like an issue with the Windows machine either no longer being able to resolve the connection information or a resource issue of some kind. Is there anything in the web server error logs or PHP error logs when this happens?

**Comment by TristBella** [comment]
No errors in the web or PHP logs. Doesn't matter which connection I use (local or web), the Plex connection should be the same local IP. I do not use network names to avoid conflicts. When i get an error from web login, i immediately try on local machine and the Plex auth works. Now that I think about it, there could be an error with the NGINX relay. I will check that and get back to you.

**Comment by TristBella** [comment]
I am going to chalk this up to a stupid Windows issue. I have no idea what the issue is as of yet, but when getting the error, a reboot of windows VM fixes the issue. I have no issues with anything else using the NGINX relay and no errors on the NGINX server. Stupid Windows!

**Comment by causefx** [comment]
I will be upping the response time from 10 seconds to maybe 30.  that will surely help

**Comment by TristBella** [comment]
Agree. Thanks.
