### ISSUE TITLE
Google iCal Not working

### ISSUE THREAD

**Issue by darkcloud784** [causefx/Organizr#1233]
###### Operating System: Ubuntu
<hr>

##### Problem Description:
I attempted to use my public ical url in organizr, I get an error in the nginx logs and on the calendar it is completely blank, nothing from sonaar/radarr or the ical. I see no errors in the organizr logs.

<hr>

##### Reproduction Steps:
Install Organizr
connect organizr to radarr/sonarr
enable calendar
input ical url and turn on ical
<hr>

#### Errors on screen?  If so paste here:

```
[error] 1479#1479: *23350 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Exception: DateTime::__construct(): Failed to parse time string (20190901T045959Z;BYMONTHDAY=1) at position 16 (;): Unexpected character in /var/www/dashboard.homelab.local/html/api/functions/homepage-connect-functions.php:1377
Stack trace:
#0 /var/www/dashboard.homelab.local/html/api/functions/homepage-connect-functions.php(1377): DateTime->__construct('20190901T045959...')
#1 /var/www/dashboard.homelab.local/html/api/functions/homepage-connect-functions.php(52): getCalendar()
#2 /var/www/dashboard.homelab.local/html/api/index.php(363): homepageConnect(Array)
#3 {main}
  thrown in /var/www/dashboard.homelab.local/html/api/functions/homepage-connect-functions.php on line 1377" while reading response header from upstream, client: 192.168.86.38, server: dashboard.homelab.local, request: "POST /api/?v1/homepage/connect HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.1-fpm.sock:", host: "dashboard.homelab.local", referrer: "dashboard.homelab.local"
```

**Comment by HalianElf** [comment]
I've been running a Google ical with sonarr/radarr for a long time now although mine is from a group. Is the URL of what you're using similar to this? https://calendar.google.com/calendar/ical/pfutdblf1gi8jmfsvroh76f6jg%40group.calendar.google.com/public/basic.ics

**Comment by darkcloud784** [comment]
> 
> 
> I've been running a Google ical with sonarr/radarr for a long time now although mine is from a group. Is the URL of what you're using similar to this? https://calendar.google.com/calendar/ical/pfutdblf1gi8jmfsvroh76f6jg%40group.calendar.google.com/public/basic.ics

Yes its the public iCal which points to basic.ics

**Comment by causefx** [comment]
i will research this today

**Comment by causefx** [comment]
Can you send me the ical link?

**Comment by darkcloud784** [comment]
> 
> 
> Can you send me the ical link?

Sure, whats your preferred way for me to send it?

**Comment by causefx** [comment]
causefx at me dot com

**Comment by darkcloud784** [comment]
> 
> causefx at me dot com
> […](#)
> Sent from my iPhone
> On Sep 4, 2019, at 5:01 PM, darkcloud784 ***@***.***> wrote: Can you send me the ical link? Sure, whats your preferred way for me to send it? — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.

Sent with the subject line of the github bug report.

**Comment by causefx** [comment]
@darkcloud784 can you pull latest from dev branch?

**Comment by darkcloud784** [comment]
> 
> 
> @darkcloud784 can you pull latest from dev branch?

Pulled, and see it is now working.
