### ISSUE TITLE
[Feature Request] add a ability to configure the first day of the week in the calendar

### ISSUE THREAD

**Issue by colmconn** [causefx/Organizr#1234]
###### Operating System: FreeNAS
<hr>

##### Problem Description:
The calendar view defaults to Monday as the first day of the week. Could you please add a configuration option to make this configurable to be Sunday or Monday (similarly to, for example, sonarr)?

**Comment by causefx** [comment]
That option is already there.  Goto homepage items and then calendar. Under misc options change start day.

**Comment by colmconn** [comment]
Excellent. Thanks.
