### ISSUE TITLE
Jumpy sidebar scroll in v2 (as opposed to smooth sidebar from v1)

### ISSUE THREAD

**Issue by cferrey** [causefx/Organizr#1237]
Per the title, the scrolling action on the left sidebar is no longer smooth in v2, making it difficult to control.  Is there any way to get it back to the way it was in the old version?

**Comment by tronyx** [comment]
Do you have a GIF or video of this? Mine is fine. Could be a performance problem and not a bug as no one has complained of the same in the 1 year plus that v2 has been available and beta tested.

**Comment by cferrey** [comment]
I don't, but I'll try to make one.  I might've used the wrong term -- I don't mean that it jumps around or is "freezy," but simply that each scrolling "tick" is a jump down the page.  Are you able to scroll down by one pixel at a time?  That's really what I'm referring to, and it was possible in v1 (but not in v2).
