### ISSUE TITLE
Add media search for Emby

### ISSUE THREAD

**Issue by hbooo** [causefx/Organizr#1238]
###### Operating System: unRAID
<hr>

##### Problem Description:
Media search is available for Plex but not for Emby, 

Is there any chance that you can add it?

Thanks in advance

<hr>

##### Reproduction Steps:

![image](https://user-images.githubusercontent.com/242125/64253182-fc462480-cf1c-11e9-8fab-6c089d00dce9.png)

**Comment by tronyx** [comment]
The completely redid their API and have zero documentation on it so it's highly unlikely that it's going to happen any time soon.

**Comment by hbooo** [comment]
So this is the old documentation for their API?

http://swagger.emby.media/?staticview=true#/SearchService/getSearchHints

**Comment by causefx** [comment]
I can check it out again

**Comment by causefx** [comment]
We are moving Feature Requests away from **GitHub** and **FeatHub**.  We are now on **_FeatureUpvote_** which is located here:
### **https://vote.organizr.app**
If will also be a tab in Organizr update this Friday 22 Jan 2021


If this Feature Request was already on FeatHub it will get moved over within the week - no further action is needed.
If not, please create a new Feature Request at our new home so we can better keep track of them.
