### ISSUE TITLE
[BUG] Dropdown arrows on Tab Groups not animating

### ISSUE THREAD

**Issue by 1activegeek** [causefx/Organizr#1239]
###### Operating System: MacOS (client) / Docker on unRAID (server)
<hr>

##### Problem Description:
Dropdown arrows for Tab Groups are no longer animating. They did animate at one point when clicking on the group. > for collapsed, \/ for exposed. Arrows now are stationary.

<hr>

##### Reproduction Steps:
When loading the core site, clicking on a tab group name will drop down the group, but will not animate the arrow. Reloading site, clearing cache, etc have no affect. Also, if you try to load the page with a tab name in a group (https://site.com/#tabname) it will load the page with the tab group arrow in exposed position for that group, and collapsed for any others. 

<hr>

#### Errors on screen?  If so paste here:

```
None
```

**Comment by tronyx** [comment]
Just adding my confirmation that this is reproducible.
