### ISSUE TITLE
logout loop

### ISSUE THREAD

**Issue by mamema** [causefx/Organizr#1241]
##### Problem Description:
After update organizr every version after 2.0.235, then login isn't possible anymore. Enter credentials and then the spinning wheel shows up, then a login error message pops up at the bottom of the screen and you're back at the login screen
<hr>

##### Reproduction Steps:
just update to later version

<hr>

#### Errors on screen?  If so paste here:

```
Login error
```
Restoring back to version 2.0.235 everything is working without changing anything.

**Comment by causefx** [comment]
https://github.com/causefx/Organizr/archive/1ba1875777d3547c26de85674c9d4bce69897151.zip

that is version 2.0.270, can you see if that has problem too?

**Comment by mamema** [comment]
Yes same habit!
________________________________

**Comment by causefx** [comment]
is there anything in php logs?

**Comment by mamema** [comment]
Nothing. I've enable php logging for errors, updated again, no error logs created.
Can i provide something else to help you?
________________________________

**Comment by causefx** [comment]
is this still happening?  If so please reopen the issue
