### ISSUE TITLE
Support Link is broken + context menu disabled?

### ISSUE THREAD

**Issue by YouveGotMeowxy** [causefx/Organizr#1243]
Hi

I'm using the latest dev version, on Docker, and wanted to click the support icon at the bottom left (life preserver icon) to ask a question about the context menu when I got this error in the main Window after clicking it:

> cl2.widgetbot.io’s server IP address could not be found.

(also, just a side note, I would love to have those 2 bottom left icons (support + ghub link) moved somewhere else to make room for 2 more of my server icons if possible? Maybe just add them somewhere in the System Settings tab area instead?)

But to my main question: is there any particular reason for disabling the right-click context menu on the login page? (e.g. when you time-out and the login form shows, for you to re-enter your pw.)

I use form fillers (both Bitwarden and LastPass) and like to bring them up by the context-menu rather than than the toolbar icons. maybe add a setting for us to disable the disabling of the context menu if we'd like?

thanks!
Kacey

**Comment by HalianElf** [comment]
I can't duplicate not getting a right click menu. (Widgetbot not working I can)

![chrome_Zl9KBkvsCP](https://user-images.githubusercontent.com/28244771/64701836-83dce780-d477-11e9-83b4-2d593249935e.png)

**Comment by YouveGotMeowxy** [comment]
Did you try the one I mentioned, after your session times out?

![image](https://user-images.githubusercontent.com/39491297/64749864-be2ca000-d4dc-11e9-8936-70b36d8899d8.png)

**Comment by causefx** [comment]
both are now fixed - thanks!

**Comment by YouveGotMeowxy** [comment]
@causefx Thank you!

btw, what's your opinion on the other aside that I mentioned of possibly moving the 2 (or 3) permanent items at the bottom left into an area off of the sidebar, to make more room for our servers icons?

I noticed 2 of them are dupes (the logout item is also available when clicking your profile at the top right)

![image](https://user-images.githubusercontent.com/39491297/64956638-b8261e80-d850-11e9-9f32-986ea786e1fc.png)

 and the GitHub item is also available under the logo on the About screen.

![image](https://user-images.githubusercontent.com/39491297/64956597-a0e73100-d850-11e9-8f9b-ed5369f7229d.png)

Thanks!
Kacey

**Comment by jscottelblein** [comment]
+1 for the icons idea.
