### ISSUE TITLE
2.0.307 - LDAP user is not added with the correct email

### ISSUE THREAD

**Issue by shocker2** [causefx/Organizr#1244]
Hello,
  When a user is automatically added from LDAP I have this PSv7EFgh10@placeholder.eml email.

By checking the email on FreeIPA, everything looks fine:
# ipa user-find dbtest|grep email
  Email address: user@domain.tld

I'm using: IPA server version 4.6.90.pre1+git20180411. API version 2.229

Thanks!

**Comment by causefx** [comment]
If you don't mind sharing your LDAP server with me I can write this function

**Comment by shocker2** [comment]
> If you don't mind sharing your LDAP server with me I can write this function

How can I send that privately?
Do you need only username or the admin credentials as well?

**Comment by causefx** [comment]
if you can create me a temp user that has email address tied to it...  then i would need those credentials plus the settings you have in organizr for LDAP so i can add to my test setup...


can either email me or pm me on discord.

causefx at me dot com

**Comment by shocker2** [comment]
> if you can create me a temp user that has email address tied to it... then i would need those credentials plus the settings you have in organizr for LDAP so i can add to my test setup...
> 
> can either email me or pm me on discord.
> 
> causefx at me dot com

Sent via email

**Comment by causefx** [comment]
received. thanks you.

**Comment by shocker2** [comment]
The issue is still present. Just tested with the latest version v2.1.120 and the added email was: "kZubiLnaUb@placeholder.eml".
