### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by alexdelorenzo** [causefx/Organizr#1247]
I'm a user and developer looking to improve Organizr. However, there is no indication of what software license Organizr's source is distributed under. 

I'd like to help contribute to Organizr, but I'm only contributing to free and OSS projects. 

###### Operating System: Windows/MacOS/Ubuntu
<hr>

##### Problem Description:
There is no LICENSE file, nor declaration of a software license for this project.

<hr>

##### Reproduction Steps:
N/A

<hr>

#### Errors on screen?  If so paste here:

```
N/A
```

**Comment by tronyx** [comment]
@causefx will need to add one, I guess, but I can assure you it's free and OSS. Just look at previous PRs as an example.

**Comment by elmerfds** [comment]
There's a license file for v1: https://github.com/causefx/Organizr/blob/v1-master/LICENSE , seems like @causefx might've forgot to import it to the v2 branch

**Comment by causefx** [comment]
Added to dev, thanks
