### ISSUE TITLE
2FA Question. "Remember this machine" option?

### ISSUE THREAD

**Issue by YouveGotMeowxy** [causefx/Organizr#1250]
Hi

I have been adding 2FA lately to all of my stuff wherever I can, and so far I think organizr is the only one that doesn't remember (or offer to remember) the current machine after successfully entering in the proper 2FA code, so that you don't have to enter it in every single time you login to organizr.

Would it be possible to add this in?

Thanks!
Kacey

**Comment by tronyx** [comment]
That feature does exist. Go to Settings -> Main -> Login and set it accordingly.

https://chrisyocum.com/Images/ShareX/firefox_2019-09-16_08-23-56.png

**Comment by tronyx** [comment]
Is this what you were looking for or did you mean something else? If yes, please close this out.

**Comment by causefx** [comment]
I think he meant remembering the actual browser.  So once 2fa code is entered for that particular machine it wont ask for a certain amount of time....

**Comment by tronyx** [comment]
Oh, ok. Most of the financial sites I use have that. Now I understand.

**Comment by YouveGotMeowxy** [comment]
@causefx is correct. :)

P.S. "he's" a "she", and not in the "it's MA'AM" sense, but no biggie. LOL

**Comment by causefx** [comment]
oh snap my bad. Yeah. i’ve thought about this for a little while. i’ll update organizr’s DB to include the table soon.

**Comment by tronyx** [comment]
@YouveGotMeowxy OMG, that made my morning!

Sorry for the confusion, but it sounds like it should be in Dev soon.

**Comment by tronyx** [comment]
@causefx I think I remember you committing changes for this, but can you confirm?

**Comment by causefx** [comment]
not yet. i want/need to plan this one out.

**Comment by tronyx** [comment]
Ah, got'cha, my bad.

**Comment by causefx** [comment]
We are moving Feature Requests away from **GitHub** and **FeatHub**.  We are now on **_FeatureUpvote_** which is located here:
### **https://vote.organizr.app**
If will also be a tab in Organizr update this Friday 22 Jan 2021


If this Feature Request was already on FeatHub it will get moved over within the week - no further action is needed.
If not, please create a new Feature Request at our new home so we can better keep track of them.
