### ISSUE TITLE
Debian 10 cURL dependancy error

### ISSUE THREAD

**Issue by ithinktech** [causefx/Organizr#1251]
###### Operating System: Debian
<hr>

##### Problem Description:

I have just updated to Debian v10.x from v9.x and can confirm cURL is installed, however after restarting, Organizr is advising that the prerequisite of cURL is failing.

How do I address this please.
<hr>

##### Reproduction Steps:

Simply load Organizr and be presented with the dependancies screen
<hr>

#### Errors on screen?  If so paste here:

```
Dependancy missing: cURL
```
![image](https://user-images.githubusercontent.com/49008262/65003019-24745100-d929-11e9-818d-1527f4782e89.png)

**Comment by HalianElf** [comment]
You have the php-curl extension installed (not just the normal curl)?

**Comment by ithinktech** [comment]
> You have the php-curl extension installed (not just the normal curl)?

Yes i have php-curl installed and on Buster (Debian 10) it is 7.3

**Comment by ithinktech** [comment]
PS this was an inline upgrade - Organizr was working correctly before the upgrade so i am thinking there may be something within organizr looking at a specific version?

**Comment by HalianElf** [comment]
And if you run `php -m` it lists it there?

**Comment by ithinktech** [comment]
Yep sure is

root@Plex-Media-Server:/home/plex# php -m
[PHP Modules]
calendar
Core
ctype
curl
date
dom
exif
fileinfo
filter
ftp
gd
gettext
hash
iconv
igbinary
json
libxml
mbstring
memcached
msgpack
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
pdo_sqlite
Phar
posix
readline
redis
Reflection
session
shmop
SimpleXML
sockets
sodium
SPL
sqlite3
standard
sysvmsg
sysvsem
sysvshm
tokenizer
wddx
xml
xmlreader
xmlwriter
xsl
Zend OPcache
zip
zlib

[Zend Modules]
Zend OPcache

**Comment by causefx** [comment]
check php version thru CLI and see if it is same on org page.

**Comment by ithinktech** [comment]
7.3

**Comment by ithinktech** [comment]
plex@Plex-Media-Server:~$ php -v
PHP 7.3.9-1+0~20190902.44+debian10~1.gbpf8534c (cli) (built: Sep  2 2019 13:33:22) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.9, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.9-1+0~20190902.44+debian10~1.gbpf8534c, Copyright (c) 1999-2018, by Zend Technologies

**Comment by causefx** [comment]
Seems they are not the same, they should be both listed as 7.3.9

can you post your webserver config for the php block?  maybe it's using the wrong sock?

**Comment by ithinktech** [comment]
By installing php7.1 i have now got Organizr working.  Thanks for your time.

**Comment by causefx** [comment]
thank you.  i will test with 7.3.9

**Comment by causefx** [comment]
7.3.9 is fine in docker.... not sure where the issue lies with this one.
