### ISSUE TITLE
[Request] LDAP Support Is Only Very Basic

### ISSUE THREAD

**Issue by InspireToCode** [causefx/Organizr#1253]
Feathub: https://feathub.com/causefx/Organizr/+108

When I use the backend of LDAP, I noticed a few things when I connected to my LDAP:

> When a user first logs in, their email does NOT match the one In Their LDAP profile, organizr fills the email field with a random one.

> No groups are imported, thus the user is automatically placed as the default group of user

> You can't add custom user name search parameters, like you can in various apps such as Nextcloud. This would allow the administrator to let users in the LDAP database to sign in using various different things in their profiles, for me I'd let me users login from 3 different aspects: their UID, real name, OR their email. All would link to the same account.

I'd be willing to throw some money to whomever works on this to help it get pushed along quicker, as it's rather important for what I'm doing with my Organizr set up. Hopefully we can come to an agreement in budget :)

**Comment by causefx** [comment]
We are moving Feature Requests away from **GitHub** and **FeatHub**.  We are now on **_FeatureUpvote_** which is located here:
### **https://vote.organizr.app**
If will also be a tab in Organizr update this Friday 22 Jan 2021


If this Feature Request was already on FeatHub it will get moved over within the week - no further action is needed.
If not, please create a new Feature Request at our new home so we can better keep track of them.
