### ISSUE TITLE
subdomin AUTH cookie issue

### ISSUE THREAD

**Issue by noah-witt** [causefx/Organizr#1254]
###### Operating System: Ubuntu
<hr>

##### Problem Description:
Auth does not work on a subdomain. this is because the cookie with emby auth is set at domain.com instead of .domain.com that leading . tells it to send it on subdomains.
<hr>

##### Reproduction Steps:

Use subdomain, auth login and it won't work edit the cookie with a . at the beginning and it will work. 
<hr>

**Comment by HalianElf** [comment]
Can you clarify this? I attached Emby local auth to Organizr, logged in with an Emby account and the cookie was set on both the subdomain and parent domain with the leading `.`
![image](https://user-images.githubusercontent.com/28244771/65395879-46793380-dd6e-11e9-8a22-ecbd2a6d803e.png)

**Comment by noah-witt** [comment]
I retested in another browser and it appears that adNausum the ad blocker I use caused the issue.
