### ISSUE TITLE
Sync profile image on login for Plex backend auth users

### ISSUE THREAD

**Issue by Archmonger** [causefx/Organizr#1255]
###### Operating System: N/A
<hr>

##### Problem Description:
Profile images within Organizr currently only sync with Plex once (upon account creation). Would be nice if on each login, Organizr would attempt to sync profile images with Plex for accounts that are known to have been created via Plex backend authentication.
<hr>

##### Reproduction Steps:
Set a profile image in Plex then realize that the Plex profile image currently does not directly sync to the Organizr profile image, even though it would be amazing if it could.
<hr>

#### Errors on screen?  If so paste here:
N/A

**Comment by Roxedus** [comment]
Its not getting profile images from Plex, it is using Gravatar for imported Plex users too.

**Comment by Archmonger** [comment]
Oh my bad. Do we know if the Plex API supports fetching profile images? If so then this could be a nice setting toggle within authentication settings.

**Comment by Roxedus** [comment]
Yes, Tautulli does it. However i think the decision was made with the fact that both ldap and Emby are methods of authorization.

**Comment by Archmonger** [comment]
Toggle only needs to exist when Plex authentication is selected. IMO it'd be a fantastic feature.

**Comment by causefx** [comment]
not sure if this is something I really want to do.  Maybe in the future.
