### ISSUE TITLE
[v2 Feature Request]

### ISSUE THREAD

**Issue by tronyx** [causefx/Organizr#1256]
Would be cool if we had the ability to assign Group permissions to categories, without the hierarchy structure that exists now, IE: I create a Group called Family and ONLY the members of that Group can then access that category, not them and any Groups above the Family Group.

**Comment by causefx** [comment]
We are moving Feature Requests away from **GitHub** and **FeatHub**.  We are now on **_FeatureUpvote_** which is located here:
### **https://vote.organizr.app**
If will also be a tab in Organizr update this Friday 22 Jan 2021


If this Feature Request was already on FeatHub it will get moved over within the week - no further action is needed.
If not, please create a new Feature Request at our new home so we can better keep track of them.
