### ISSUE TITLE
iframe flashes and doesn't log in (QBittorrent)

### ISSUE THREAD

**Issue by agneevX** [causefx/Organizr#1257]
###### Operating System: Debian
<hr>

##### Problem Description:
QBittorrent Web UI won't sign in on MobileSafari.
The iframe flashes each time I tap 'Submit'.

Edit: For the record, I'm able to login using the same credentials on other browsers. 

Edit 2: This issue is now present across all browsers. 

_iPad running iOS 13.1.2_
<hr>

**Comment by causefx** [comment]
still happening?

**Comment by agneevX** [comment]
Did something change? I gave up Organizr because literally everything broke down with nginx auth.

**Comment by causefx** [comment]
A lot of us (and I mean a lot) use nginx auth and many different services with no issues.  I don't use qbit at all so I am unable to test.  No worries if it wasn't a right fit for you.  Thanks.
