### ISSUE TITLE
502 Bad Gateway error permanently showing

### ISSUE THREAD

**Issue by behold81** [causefx/Organizr#1258]
###### Operating System: docker
<hr>

##### Problem Description:
it failed to have permissions to create the DB on first creation. Shut down and updated the PGID and PUID and restarted and then the 502 error occured. I have deleted and recreated the entire docker and used new locations and names. It still comes up with the error. V1 is still running fine (different name and location and ports)

<hr>

##### Reproduction Steps:
load web page on port 80

<hr>

#### Errors on screen?  If so paste here:

```

```

**Comment by tronyx** [comment]
What's your docker run command or docker-compose setup look like? Try dropping the PGID and PUID environment variables and chowning everything to 911:911 for that container.

**Comment by behold81** [comment]
removing the variables doesnt change anything. still no web access. 

Docker is in Synology so i have little control on what is set. I am using the official docker image in the registry

**Comment by tronyx** [comment]
Anything in the container logs? Similar issues reported seeing the following:

`[pool www] please specify user and group other than root`

Is that what you're seeing? Are you running Docker as root? You could take a look at the solution presented here:

https://github.com/Monitorr/Monitorr/issues/189

**Comment by behold81** [comment]
sorry for the delay I have been away. 

The only error i have is:

2019/10/14 07:06:03 [error] 346#346: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.17.0.1, server: _, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "192.168.2.5:8889"

**Comment by Roxedus** [comment]
We still haven't seen any run command.
