### ISSUE TITLE
Inability to install plugins

### ISSUE THREAD

**Issue by Nomelas** [causefx/Organizr#1259]
###### Operating System: Linux Docker
<hr>

##### Problem Description:
I can't install the inactive plugins. I believe normally there's a clickable icon to install them, but the icon is missing and there's no link. I've tried incog, clearing browser cache, hitting org directly, via outside my LAN, via my phone, etc...

Incidentally, I was able to install the speedtest plugin from my phone only (chrome browser on android)

I've had this problem forever. I used to run org on windows which ive since set up an unraid server and am using docker. It's a fresh install, nothing was migrated.

<hr>

##### Reproduction Steps:
See above

<hr>

#### Errors on screen?  If so paste here:
None in console, but here's a screenshot:

![image](https://user-images.githubusercontent.com/15185630/66650476-156e7f00-ec07-11e9-9f18-738d4a7df348.png)

**Comment by HalianElf** [comment]
Make sure you don't have an extension that's blocking the images.

**Comment by Nomelas** [comment]
incog has all extentions disabled. also I tried on my phone. Next step is to try with a vpn...

**Comment by Nomelas** [comment]
same issue with the vpn, so its not my browser, or internet, or any adblocking or my server....

**Comment by causefx** [comment]
wow this makes no sense.  usually its pi hole or an ad blocker blocking them.  can you right click and inspect the elements?

**Comment by Turbo123T3** [comment]
I'm having the same issue currently, 

Desktop: Chrome and Edge both have issues. Firefox/Brave are both good. 
Mobile: Chrome & Brave are both good.

As a bit of help here is a bit of the elements,

Firefox: https://i.imgur.com/MR93Hon.png

Brave: https://i.imgur.com/sqKzPix.png

Chrome: https://i.imgur.com/ynYGFVk.png

Chrome Incognito: https://i.imgur.com/2YVNBJi.png

My Chrome on Desktop has a ton of add-ons including Ad-block but Incognito has nothing. No other browsers have any add-ons. I don't have pi hole and it is the latest version available from GitHub.

**Comment by causefx** [comment]
if either of u can jump on discord so we can troubleshoot

**Comment by Nomelas** [comment]
somehow it just all of a sudden started working in chrome for windows (still doesn't in android)

On version 2.0.325

**Comment by hunterlong** [comment]
+1 same exact issue.......

**Comment by tronyx** [comment]
Seems like it was browser related, closing.
