### ISSUE TITLE
[Feature Request] Parent folder for tabs

### ISSUE THREAD

**Issue by saitoh183** [causefx/Organizr#126]
It would be great if we could create parent folders that would have the same type of settings as tabs (active,user and guess sliders) so that we can regroup certain tabs. I have almost 25 tabs and on certain pc screens im force to scroll a lot :) . For guess tabs might not be needed but i would suggest is that if you dont expose the parent folder to guess or user but the tab is exposed, it shows up at the root(same as now). The parent folder could also be customized with icons of course :)

**Comment by causefx** [comment]
same as #80
