### ISSUE TITLE
Slow 401 & Login Page (For nginx auth)

### ISSUE THREAD

**Issue by jwheeler91** [causefx/Organizr#1261]
###### Operating System: Docker
<hr>

##### Problem Description:
I don't have a particularly fast internet connection at home, so loading Organizr is quite slow for me when off my home network.

This isn't normally an issue, but using the nginx auth feature is frustratingly slow when all it needs to do is load a form, validate the form entry and redirect back.

Would it be possible to minimize the requirements of the 401 page so that it does not take so long to load?

It takes 36 seconds to load.

Obviously when cached, the site takes less than a second to load, but I am regularly met with a complete reload (esp. on mobile).

<hr>

##### Reproduction Steps:
Specific to my internet connection, but on a slow connection, access externally in a private tab (incognito) so that it doesn't use the cache.

<hr>

**Comment by Roxedus** [comment]
Sorry for taking a while to respond. What upload speeds are we talking about?

**Comment by jwheeler91** [comment]
1mbps (megabits not megabytes) Max.

I wouldn't worry about it as I've switched to Keycloak for logging in, Traefik for proxy and Heimdal as a lightweight links page.
