### ISSUE TITLE
forced to put external ip for both tab url and local tab url

### ISSUE THREAD

**Issue by tvann2182** [causefx/Organizr#1263]
###### Operating System: QNAP TS-1283
<hr>

##### Problem Description:
For some reason when i set the local tab ip for internal 192.168.1.xx and tab url to external address, and refresh then click on the tab while on internal network it gives the internal ip address its as if it is not seeing or realizing that i am on a external network. I have to set the external domain resolution for both which stops me from accessing it on my internal network

I run nginx reverse proxy on a separate raspberry pi from the qnap nas. So long as i am outside my network with both names resolving external i am ok, but once i get home it does not work because the reverse proxy on the inside of the network doesnt know what the domain itself is. I end up with site cannot be reached.

<hr>

##### Reproduction Steps:
enter external domain address in tab url
enter local ip and port for local tab url

then refresh and try both inside and outside network

<hr>

#### Errors on screen?  If so paste here:

```
no errors other than addresses seem to be reversed
```

**Comment by HalianElf** [comment]
You need to make sure your reverse proxy is passing the real IP in a header and that your Organizr nginx settings are set to read that header.

**Comment by causefx** [comment]
> click on the tab while on internal network it gives the internal ip address its as if it is not seeing or realizing that i am on a external network. 

I got confused by this line....

Also if you goto debug area under user menu, it will tell you if you are local or not...

![image](https://user-images.githubusercontent.com/16184466/66877053-e6d70800-ef68-11e9-83d0-aa06a9ec38d8.png)

**Comment by tronyx** [comment]
Also, if you're utilizing a Domain with an SSL certificate, you will most likely encounter issues when putting in the Local URL for the Tab along with the external URL.

**Comment by tvann2182** [comment]
thank you all, i was able to resolve this issue by making sure my nginx had the x-forwarded-for set to $remote_addr and now it shows the external on login as well as i can be on the internal ip when at home. I am still trying to figure out if i can connect to my domain internally but at the moment the only way for me to access organizr and my ips is by the internal ip... Thanks again for the help

**Comment by tvann2182** [comment]
I have the ngxconfigurator installed in plugins but do not know how to set it up yet
