### ISSUE TITLE
Organizr - Migration

### ISSUE THREAD

**Issue by BastionNtB** [causefx/Organizr#1271]
###### Operating System: Windows
<hr>

##### Problem Description:
Need data locations for a clean migration to a new server. I attempted to migrate, but it has failed repeatedly.

What do I need to carry over for a successful migration?

(A complexity is that the new install needs to utilize SSL, where as the old one was HTTP only)
<hr>

##### Reproduction Steps:

N/A
<hr>

#### Errors on screen?  If so paste here:

```

```

Thank you

**Comment by tronyx** [comment]
That's not a complexity at all. You need the Database file, wherever you selected to put it when you setup Organizr, and you need the config.php file found within the root folder where you put the Organizr files, then /api/config/.

**Comment by BastionNtB** [comment]
I moved the .db file created with previous install, moved the config file from the api/config, I had to point the db file to a new location in the config file, but it did not carry over everything. I am unable to log in, all I get is "login failed" after a successful OAuth to Plex.

**Comment by causefx** [comment]
check the size of the db file

**Comment by BastionNtB** [comment]
It's 116kb, the original setup is still running and functioning. I'm doing a live migration.

**Comment by causefx** [comment]
is the live setup also 116Kb?

**Comment by BastionNtB** [comment]
Correct. Both match identically.

**Comment by BastionNtB** [comment]
Welp... I don't know what to say... I did this like 3 times in a row, and I must have missed pointing the api config to the new location of the db, even though I explicitly remember setting it each time...

It's working now... This can be closed. Thanks for trying to help.

For those curious, what I moved:
NGINX\www\organizr\db\[dbname].db
NGINX\www\organizr\html\api\config\config.php
- Changed the 'dbLocation' tag to the new location after migration.

NGINX\www\organizr\html\plugins\images\tabs
- Copied entire folder on to new one, without overwriting. (Grabs tab images)

NGINX\www\organizr\html\plugins\theme_files
- Copied entire folder on to new one, without overwriting.

NGINX\www\organizr\html\css\themes
- Copied entire folder on to new one, without overwriting.

These steps and Oganizr runs exactly as I had it before (Though you may have additional configurations that require additional steps)
