### ISSUE TITLE
[WORK IN PROGRESS] Cockpit doesn't work anymore with Organizr after updating

### ISSUE THREAD

**Issue by LothaireCliquennois** [causefx/Organizr#1273]
###### Operating System: Debian Sid
<hr>

##### Problem Description:
I can't access Cockpit from anywhere since I installed Organizr.
Organizr is accessible, but not Cockpit. Most other services I use aren't as well.

<hr>

##### Reproduction Steps:
Organizr config + Cockpit install 

<hr>

Errors on screen:
Well first it's complaining about the certificate, which hasn't been a problem before, and it hangs when using Chromium.
I know for a fact that Cockpit is running, just not possible to access it.

```

```

**Comment by Roxedus** [comment]
Open the developer console in the browser, press f12 on your keyboard, switch to the console tab. any errors?

**Comment by LothaireCliquennois** [comment]
![image](https://user-images.githubusercontent.com/41753021/68118857-61100200-ff01-11e9-8276-9d36b1883b0b.png)

**Comment by Roxedus** [comment]
OK, that looks clear. I would resolve that certificate error.

**Comment by LothaireCliquennois** [comment]
Well then, so it is a problem on my end, or on Organizr's end ?
