### ISSUE TITLE
Feature Request: Sonarr homepage calendar link to sonarr page

### ISSUE THREAD

**Issue by mrzoops** [causefx/Organizr#1274]
I was hoping it would be possible, when using the Sonarr homepage calendar, when clicking on a show title, that it opens that series in the sonarr tab, instead of opening the generic splash page for the show.

**Comment by tronyx** [comment]
That would be changing the entire functionality of the calendar. If anything, I feel that this should be a request to add a button, just like the existing YouTube button, to open the corresponding app, be it Sonarr, Radarr, or Lidarr.

**Comment by mrzoops** [comment]
Yeah that's a good idea too.

**Comment by causefx** [comment]
We are moving Feature Requests away from **GitHub** and **FeatHub**.  We are now on **_FeatureUpvote_** which is located here:
### **https://vote.organizr.app**
If will also be a tab in Organizr update this Friday 22 Jan 2021


If this Feature Request was already on FeatHub it will get moved over within the week - no further action is needed.
If not, please create a new Feature Request at our new home so we can better keep track of them.
