### ISSUE TITLE
Idea: Relocate the Settings icon to the bottom

### ISSUE THREAD

**Issue by jscottelblein** [causefx/Organizr#1276]
![image](https://user-images.githubusercontent.com/1524526/68454999-e0325e00-01bf-11ea-85b9-4997f54456fd.png)

As is, the settings cog is right in the middle, between the non-grouped and grouped items, and you have to scroll up and down all the time to get to the settings icon when wanting to make changes; what are the chances of having it moved to a static location at the bottom of the list, perhaps just above the Github icon, or even better, save some real estate over there for another service icon by moving the settings icon up next to the Search icon in the top toolbar, over by your account icon?

I personally would prefer the entire left sidebar space available to only services, and anything like Settings icons, repo links, logout link, etc, moved off of it, perhaps all within the Account menu. That would remove some "screen clutter" as well. =)

**Comment by tronyx** [comment]
Just do what I did and create a Settings Tab Category and put the Settings Tab in it and then move the Category to the bottom.

https://chrisyocum.com/Images/ShareX/firefox_2019-11-08_08-29-35.png

**Comment by jscottelblein** [comment]
@christronyxyocum now why didn't I think of that? ;P 

I just put it in a pre-existing "System" group, so that s a bit better. I still think it makes a bit more sense to just place the settings link right about here:

![image](https://user-images.githubusercontent.com/1524526/68510287-b6694d80-0238-11ea-91df-bfaccec4ceeb.png)

though. *shrugs*

**Comment by tronyx** [comment]
Since a valid workaround was provided, and since I don't think this design is going to change anytime soon, I'm closing this.
