### ISSUE TITLE
Custom html email template gets embedded in the default Organizr email template. 

### ISSUE THREAD

**Issue by GilbN** [causefx/Organizr#1279]
###### Operating System: Windows
<hr>

##### Problem Description:
When adding a custom HTML email template from mailchimp, Organizr embeds that template inside the Organizr email template. 

<hr>

##### Reproduction Steps:

<hr>

#### Errors on screen?  If so paste here:

```

```

**Comment by GilbN** [comment]
A theme called custom that is blank would be a nice solution :)

**Comment by causefx** [comment]
im confused on this one

**Comment by causefx** [comment]
spoke to gil on discord about it.
