### ISSUE TITLE
Email template doesn't support UTF-8 charset

### ISSUE THREAD

**Issue by GilbN** [causefx/Organizr#1281]
###### Operating System: Windows
<hr>

##### Problem Description:
When adding the characters æøå its displayed as Ã¥ Ã ect. 
I see that the email theme has `<meta charset="utf-8">` but it doesn't work. 

<hr>

##### Reproduction Steps:

Add æøå or ÆØÅ in an email template. 
<hr>

**Comment by Roxedus** [comment]
(applies to anything in the database)

**Comment by GilbN** [comment]
I also tried saving the templates with `&#230;`  `&#248;`   `&#229;` instead of æøå 
And that worked for a little while, but it seems that org converts it back?

**Comment by GilbN** [comment]
> (applies to anything in the database)

What do you mean?

As far as I can see the templates are stored in config.php and the template themes in the misc folder

**Comment by Roxedus** [comment]
> What do you mean?

It also happens to characters stored in the database, and a database migration happens. May help cause in narrowing it down

**Comment by causefx** [comment]
still happening @gilbN ?
![image](https://user-images.githubusercontent.com/16184466/75824463-caddd280-5d60-11ea-9a5a-867ec1a2b5da.png)
![image](https://user-images.githubusercontent.com/16184466/75824474-cf09f000-5d60-11ea-847a-806188de8775.png)

**Comment by GilbN** [comment]
æøå works on my container, but I will test again on our windows setup at work.

**Comment by causefx** [comment]
my test was on windows but yeah - lmk
