### ISSUE TITLE
[Feature Request] right click open new tab instead of side-by-side

### ISSUE THREAD

**Issue by fserb** [causefx/Organizr#1283]
What the title says.

It would be nice to be able to disable side-by-side and make right click to open in new tab.

**Comment by tronyx** [comment]
The prompts for you to add information in the issue template are there for a reason.

Sounds to me like you're running, the now unsupported, v1 as v2 was released several months ago and does not include the split-screen functionality.

**Comment by jrdnlc** [comment]
Update. It will need to be a fresh install. Upgrading from V1 to V2 is not supported

https://hub.docker.com/r/organizrtools/organizr-v2

**Comment by fserb** [comment]
Oh, my bad.

I've been using [linuxserver/organizr](https://github.com/linuxserver/docker-organizr), and since it was frequently updated I thought I was on the latest branch.

Thanks for the help, I'll use the other docker.

**Comment by fserb** [comment]
I think the Request still remains though, as V2 seems to force right click to do the same thing as left click.

**Comment by tronyx** [comment]
What do you mean it forces right-click? Left click opens the tab in an iFrame. Right-click would open the standard context menu. The point of Organizr is to iFrame things and not have multiple tabs open. If you want to open a tab in Organizr in a new tab of your browser, then just hold CTRL and left click.
