### ISSUE TITLE
Organizr Function: Github Connection Failed

### ISSUE THREAD

**Issue by raphaelfuchter** [causefx/Organizr#1284]
Organizr Version: V 2.0.325
Type: Official Docker
Operating System: Raspbian

Problem Description:
I did a zero install by docker and markplace doesn't work, only this error appears in the browser console. I also tried to install manually and the same as the docker version happens. How to solve?

Errors:
```
Organizr Function: Github Connection Failed
```

**Comment by causefx** [comment]
That message means it cannot connect to github.com - can you ping it from that machine?

**Comment by raphaelfuchter** [comment]
Yes.

> pi@raspberrypi:/ $ ping github.com

> PING github.com (140.82.114.4) 56(84) bytes of data.

> 64 bytes from lb-140-82-114-4-iad.github.com (140.82.114.4): icmp_seq=1 ttl=48 time=144 ms

> 64 bytes from lb-140-82-114-4-iad.github.com (140.82.114.4): icmp_seq=2 ttl=48 time=144 ms

> 64 bytes from lb-140-82-114-4-iad.github.com (140.82.114.4): icmp_seq=3 ttl=48 time=142 ms

> 64 bytes from lb-140-82-114-4-iad.github.com (140.82.114.4): icmp_seq=4 ttl=48 time=142 ms

> --- github.com ping statistics ---

> 4 packets transmitted, 4 received, 0% packet loss, time 5ms

> rtt min/avg/max/mdev = 141.646/142.827/144.208/1.082 ms

**Comment by raphaelfuchter** [comment]
Any help? I've tried everything and can't solve it. :(

**Comment by causefx** [comment]
Try pinging from inside the container:

```
causefx@docker:~$ docker exec -it organizrV2 bash
root@organizrV2:/$ ping github.com
PING github.com (140.82.113.3): 56 data bytes
64 bytes from 140.82.113.3: seq=0 ttl=52 time=87.815 ms
```

**Comment by raphaelfuchter** [comment]
Sorry, I already removed Organizr and I no longer have the Raspberry to test. You will close the problem.
