### ISSUE TITLE
Dependency check fails incorrectly on PHP 7.4

### ISSUE THREAD

**Issue by luukvbaal** [causefx/Organizr#1288]
###### Operating System: Arch Linux ARM
<hr>

##### Problem Description:

After upgrading to php7.4 Organizr no longer works.  
<hr>

##### Reproduction Steps:

Run nginx webserver with php 7.4.
Go to Organizr interface and be greeted by dependency check incorrectly stating
"Dependencies Missing" and "Not Writable - Please fix permissions".
<hr>

#### Errors on screen?  If so paste here:

nginx log reveals:
```
[error] 1204#1204: *8 FastCGI sent in stderr: "PHP message: PHP Notice:  Trying to access array offset on value of type bool in usr/share/webapps/organizr/Organizr/api/index.php on line 1136PHP message: PHP Notice:  Trying to access array offset on value of type bool in /usr/share/webapps/organizr/Organizr/api/index.php on line 1137" while reading response header from upstream, client: 192.168.178.80, server: localhost, request: "GET /api/?v1/launch_organizr HTTP/1.1", upstream: "fastcgi://unix:/run/php-fpm/php-fpm.sock:", host: "192.168.178.100", referrer: "http://192.168.178.100/"
```
https://core.trac.wordpress.org/ticket/47704 seems related.
Didn't have time to look into it further.

**Comment by causefx** [comment]
I just tried on windows by upgrading to 7.4

Everything worked well.  I took off one dep to test:
![image](https://user-images.githubusercontent.com/16184466/70396038-4f1ef480-19c2-11ea-96c6-ded93f013a0d.png)

Added it back:
![image](https://user-images.githubusercontent.com/16184466/70396044-5c3be380-19c2-11ea-8836-c031ba037d18.png)

**Comment by causefx** [comment]
Either way, pushed a fix to develop for this.  Will merge to master once people have tested and see no issue.

**Comment by luukvbaal** [comment]
Still seeing the same issue. What I meant with incorrectly showing "Dependencies Missing" is this btw:
![image](https://user-images.githubusercontent.com/31730729/70397627-2c1d3080-1a14-11ea-8a70-c3568a6ad86a.png)
All dependencies checked but for some other reason it detects missing dependencies.
Same for write permissions:
```
[root@alarm Organizr]# pwd
/usr/share/webapps/organizr/Organizr
[root@alarm Organizr]# ls -l
total 92
-rwxrwxrwx 1 http http 35140 Dec  8 22:26 LICENSE
-rwxrwxrwx 1 http http  6058 Dec  8 22:26 README.md
drwxrwxrwx 7 http http  4096 Dec  8 22:29 api
drwxrwxrwx 6 http http  4096 Dec  8 22:29 bootstrap
drwxrwxrwx 5 http http  4096 Dec  8 22:29 css
-rwxrwxrwx 1 http http 18672 Dec  8 22:26 index.php
drwxrwxrwx 3 http http  4096 Dec  8 22:29 js
drwxrwxrwx 4 http http  4096 Dec  8 22:29 less
drwxrwxrwx 8 http http  4096 Dec  8 22:29 plugins
drwxrwxrwx 2 http http  4096 Dec  8 22:29 scripts
```
even with permissions set to to 777 temporarily but other wise running nginx as user http.

Updated from [AUR](https://aur.archlinux.org/packages/organizr-git/) but to confirm your changes were present:
```
[root@alarm Organizr]# cat /usr/share/webapps/organizr/Organizr/api/functions/api-functions.php | grep loadTabs
function loadTabs($type = null)
```

My setup still works after downgrading to php7.2 fyi.

**Comment by luukvbaal** [comment]
Installed php 7.4 and organizr on my laptop to try and debug further but I'm afraid I cant really be of any help as I struggled to figure out how to debug php. Can confirm that the issue is present (and gone using php7.2) on x86 aswell. Do let me know if you need anything from me.

**Comment by causefx** [comment]
after the update, any errors in logs?

**Comment by luukvbaal** [comment]
Sorry no, no further errors in nginx log. It seems the previous errors were unrelated to, or not the sole cause of the dependency check fail.

**Comment by causefx** [comment]
can you `ls -lah` this dir `/usr/share/webapps/organizr/Organizr`

**Comment by luukvbaal** [comment]
Sure here you go:
```
/usr/bin/ls -lah
total 100K
drwxrwxrwx 9 http http 4.0K Dec  9 22:16 .
drwxrwxrwx 3 http http 4.0K Dec  9 13:20 ..
drwxrwxrwx 7 http http 4.0K Dec  9 13:20 api
drwxrwxrwx 6 http http 4.0K Dec  9 13:20 bootstrap
drwxrwxrwx 5 http http 4.0K Dec  9 13:20 css
-rwxrwxrwx 1 http http  19K Dec  9 13:19 index.php
drwxrwxrwx 3 http http 4.0K Dec  9 13:20 js
drwxrwxrwx 4 http http 4.0K Dec  9 13:20 less
-rwxrwxrwx 1 http http  35K Dec  9 13:19 LICENSE
drwxrwxrwx 8 http http 4.0K Dec  9 13:20 plugins
-rwxrwxrwx 1 http http 6.0K Dec  9 13:19 README.md
drwxrwxrwx 2 http http 4.0K Dec  9 13:20 scripts
```

**Comment by causefx** [comment]
hmmm makes no sense....

i need to check release notes to see if either `is_writable` or `dir` was changed in 7.4

**Comment by causefx** [comment]
What OS is your laptop that you tried?

**Comment by luukvbaal** [comment]
Oh sorry. It's running Linux (Arch).

**Comment by Philz69** [comment]
This issue seems to have nothing to do with organizr itself, and more to do with Arch.

Quickly running a small php script using the same server confirms this
`<?php $filename = 'index.php'; if (is_writable($filename)) { echo 'The file is writable'; } else { echo 'The file is not writable'; }?> 
`
returns `The file is not writable`

For some reason, the folder that arch installs organizr to ( `/usr/share/webapps/organizr/Organizr` ) is not writable by php even with permissions set correctly.

Simply copying the folder's content into a new folder and setting permissions to http:http and 755 completely fixed the issue for me

**Comment by causefx** [comment]
good find @Philz69

**Comment by luukvbaal** [comment]
It still has something to do with the update to `php7.4` though as the issue is not present with `php7.2` .

**Comment by causefx** [comment]
i would rather say its an issue with `php7.4` **and** `Arch` together as this issue doesn't present itself on the two other OS i tested using php7.4

**Comment by luukvbaal** [comment]
Can confirm. `nginx` `root` in `/opt/Organizr` does work with
```
drwxr-xr-x  11 http http   4096 Dec 10 20:50 /opt/Organizr
drwxr-xr-x  12 root root   4096 Dec 10 21:12 opt
```
whereas `nginx` `root` in `/usr/Organizr` does not work with
```
drwxr-xr-x 11 http http 4096 Dec 10 20:50 /usr/Organizr
drwxr-xr-x   9 root root 4096 Dec 10 21:12 usr
```
Cannot fathom what's causing this :sweat_smile:

**Comment by Tim-tehgeek** [comment]
I'm not a PHP expert, so should we have one feel free to correct me. Since php7.4 breaks php-fpm (on at least Arch) I saw that it now uses **ProtectHome**, but also **ProtectSystem**.

```
# Mounts the /usr, /boot, and /etc directories read-only for processes invoked by this unit.
ProtectSystem=full
```

By commenting out **ProtectSystem** in my php-fpm config Organizr now loads like it did before.

**Comment by luukvbaal** [comment]
@Tim-tehgeek good catch, thanks!
I suppose the web folder for Organizr should not be stored in /usr anymore on arch systems to comply with this new default. I'll suggest the change in the AUR package.
