### ISSUE TITLE
[Feature Request] Customization of header

### ISSUE THREAD

**Issue by lgromb** [causefx/Organizr#129]
Hey,

I really thought I did open an issue on this like some time ago but didn't find it again, maybe I posted this on reddit or... w/e.

I'm mostly accessing Organizr outside of home, on my small 11" laptop with a resolution of 1366*768.

If you add Chrome tab bar + Chrome fav bar + Organizr header + (ie) Plex Header + Organizr Sidebar, there's very little room left for actual content on my website. 

Would it be possible to completly disable the header, or to do something like Muximux, having a "flat" header, I bet you see what I mean. 

Thanks ! ⚔️

**Comment by causefx** [comment]
I will certainly look into hiding the header after loading.

**Comment by causefx** [comment]
While I would love to do this, it conflicts with the sidebar.  I may rewrite the sidebar as it's own element as it is currently part of the top bar.  I will keep you informed.
