### ISSUE TITLE
Logging out produces a blank tab instead of 401

### ISSUE THREAD

**Issue by minuskaos** [causefx/Organizr#1293]
###### Operating System: Windows
<hr>

##### Problem Description:

If you log out while viewing a tab that requires greater than guest access the tab is blank instead of producing a 401 error
<hr>

##### Reproduction Steps:

Go to tab with greater than guest access and then log out of your account. 

<hr>

#### Errors on screen?  If so paste here:

[IMG](https://cdn.discordapp.com/attachments/374662006701293569/657791440142991370/unknown.png)

**Comment by causefx** [comment]
this has been fixed....
