### ISSUE TITLE
Add Non-Transparent Cardigann Image for Dark Themes

### ISSUE THREAD

**Issue by bakerbryce** [causefx/Organizr#1294]
###### Operating System: N/A
<hr>

##### Problem Description:
Add non-transparent Cardigann icon to the default images so that it doesn't blend into the background when using darker themes. Sample attached.
![cardigann-solid](https://user-images.githubusercontent.com/36087020/71509293-126b4e00-2848-11ea-94ec-d37c27b349c7.png)

<hr>

##### Reproduction Steps:
N/A

<hr>

#### Errors on screen?  If so paste here:
N/A

```

```

**Comment by causefx** [comment]
i this the best image?

**Comment by bakerbryce** [comment]
@causefx It works well and looks clean on my instance, yes.

**Comment by Roxedus** [comment]
@likeablebias Does it suffice with just filling the inside? 
![cardigann](https://user-images.githubusercontent.com/7110194/81510138-e7bdf580-930f-11ea-96e7-f29dae01ee34.png)

**Comment by bakerbryce** [comment]
@causefx That’s all I did also, but with gray so yes that should work.

**Comment by causefx** [comment]
added in dev
