### ISSUE TITLE
Plex oAuth: Error Connecting to oAuth Provider

### ISSUE THREAD

**Issue by Undeadllama** [causefx/Organizr#1299]
###### Operating System: CentOS 7.7
<hr>

##### Problem Description:
When using Plex oAuth for authentication I very often have to hit the login button more than once before oAuth connectivity is successfully established.

On first/second the Plex login popup window very briefly opens (for less than a second) and then immediately closes followed by a toast message on the Organizr page stating "Error Connecting to oAuth Provider".

A second or third attempt allows the Plex oAuth login screen to open successfully and proceed with login as normal.

It's very inconsistent - sometimes it will work fine on first attempt, but mostly it'll require hitting the login button 2/3/4 times.

Clearly as all works fine on the second or third attempt this is very low priority/impact.
However it would be interesting to understand more as to why this behaviour is happening and how it might be mitigated so that it consistently works the first time.

Are there any logs that might provide more details surrounding that error?
<hr>

##### Reproduction Steps:

 - Authentication Type: Organizr DB + Backend
 - Authentication Backend: Plex
 - Enable Plex oAuth: Enabled
 - Minimal Login Screen: Enabled
 - All pages/tabs of organizr configured to require minimum of 'User' permissions to view. Therefore when browsing to organizr while logged-out it defaults to the login page.
(If any relevant config is missing here please let me know)

1) Browse to organizr while not logged in. Defaults to login screen.
2) Select login with Plex auth
3) Hit login button on organizr page (onclick="oAuthStart('plex')")
Often the first/second attempt results in error "Error Connecting to oAuth Provider".
4) Hitting login 2-3 times allows Plex auth popup window to load successfully and allow user to enter login details and continue normally.
<hr>

#### Errors on screen?  If so paste here:

```
Error Connecting to oAuth Provider
```
![image](https://user-images.githubusercontent.com/3908975/71826639-463f4280-3096-11ea-9c1b-8b9249ceeaa5.png)

**Comment by causefx** [comment]
Can you video the next time you login?

**Comment by Undeadllama** [comment]
Sure, see attached.
I noticed while grabbing this that a 404 error is thrown on the organizr page when reaching out to the Plex API.

For example:
`GET https://plex.tv/api/v2/pins/589948574 404 (Not Found)`

Is that a URL generated by oranizr?

[PlexAPI_oAuth.zip](https://github.com/causefx/Organizr/files/4036644/PlexAPI_oAuth.zip)

**Comment by causefx** [comment]
wow that's super odd.  We query plex and get that url and use that to poll when logging in.  Have you tried on a different network to see if issue persists

**Comment by tronyx** [comment]
Closing due to 60+ days of inactivity.
