### ISSUE TITLE
symlink problem

### ISSUE THREAD

**Issue by ShoGinn** [causefx/Organizr#13]
So I keep all of my git items in the /opt folder and then symlink them to the root web directory.

because the user.php points to ../users.db its asking for rights to the /opt folder.

unless i move the repository to the root web directory it fails.

So traditionally i know that symlinks aren't a preferred practice but it has worked in the past ;)

**Comment by HeroCC** [comment]
You can edit user.php to set where the DB goes.

**Comment by ShoGinn** [comment]
@HeroCC I know you can modify it but the point is that if the version gets updated that file will get overwritten.

**Comment by causefx** [comment]
can you just add www-data to the group that has permissions to opt?

**Comment by ShoGinn** [comment]
@causefx I think for the purpose of the database files having them located elsewhere is necessary and configuring that is a good enhancement :)

**Comment by causefx** [comment]
@ShoGinn correct, I was just speaking in the meantime.

**Comment by hoopty** [comment]
@causefx, I would recommend that you have user.php include another (optional) config.php that can override the defaults you have there so folks can create/edit config.php with any server specific settings they need.  Also, please put config.php in .gitignore so that updates and gut pulls, etc. do not ever need to touch it.  Right now, we need to revert our customizations to users.php then get the latest & then re-appy those customizations.

**Comment by causefx** [comment]
I'm already working on something similar to that for v1.0

When first installing it will ask you where you would like for it to store the database. It will then save it in an another file.

**Comment by causefx** [comment]
just a heads up this is fixed.

**Comment by ShoGinn** [comment]
Thanks! I have been trying to implement this into a simpler solution and integration into a nginx location setup!

**Comment by ShoGinn** [comment]
so far I have:
```

   location ~ /(\.|users.db) {
        deny all;
    }
```


Any idea what you are going to do with that users folder??

**Comment by causefx** [comment]
what every location you specify on the startup when you update, will use that path for both the db file and users folder.

![image](https://cloud.githubusercontent.com/assets/16184466/21960961/5fef2b54-dab9-11e6-8238-b57b9bbaa782.png)
