### ISSUE TITLE
[Feature Request] Keep the week view calendar day in the middle and have the days shift over each day

### ISSUE THREAD

**Issue by Cookie-Monster-Coder** [causefx/Organizr#1302]
So, in the calendar week view, basically keep the current day highlighted in the middle and have the previous days slide to the left, 3 days until it disappears and have new days coming from the right, 3 days in advance.

Would be sweet if this is possible, because right now Sunday's slot is never visible until Sunday at midnight.

**Comment by causefx** [comment]
We use https://fullcalendar.io/ for the framework - I will see if this is possible.

**Comment by causefx** [comment]
We are moving Feature Requests away from **GitHub** and **FeatHub**.  We are now on **_FeatureUpvote_** which is located here:
### **https://vote.organizr.app**
If will also be a tab in Organizr update this Friday 22 Jan 2021


If this Feature Request was already on FeatHub it will get moved over within the week - no further action is needed.
If not, please create a new Feature Request at our new home so we can better keep track of them.
