### ISSUE TITLE
Ombi homepage plugin: Search feature not working for admins

### ISSUE THREAD

**Issue by 5-c-o** [causefx/Organizr#1303]
Basically the Ombi homepage plugin has an ability to search for movies/shows which is currently only visible to the admin. I've tried changing the settings within the plugin to show for Users+, tested all groups from Co-Admin down. Even with a Co-Admin account, the search option still won't appear.

**Comment by HalianElf** [comment]
The search requires SSO to be working with Ombi. Do those accounts have an associated plex/ombi account?

**Comment by 5-c-o** [comment]
> 
> 
> The search requires SSO to be working with Ombi. Do those accounts have an associated plex/ombi account?

Yeah SSO is configured although I'm not sure it's functioning correctly. Plex accounts are all synced up with Ombi and Organizer.

Should SSO auto sign Plex users into Ombi or should it still bring up the Plex login? At the minute, users have to click to sign in but it does remember saved credentials.

**Comment by HalianElf** [comment]
Yes, they should be signed in automatically if it's working properly. Since they're having to login afterwards, that would explain why the search isn't showing. If it's working for you, check the Organizr logs and see if there's anything in there for the SSO.

**Comment by Roxedus** [comment]
Closing due to lack of feedback. Please reach out if this is still a issue.
