### ISSUE TITLE
No longer showing 'Recently Added Movies'; only Music and Shows on the filter

### ISSUE THREAD

**Issue by D4rkSl4ve** [causefx/Organizr#1305]
###### Operating System: Ubuntu 18.04
<hr>

##### Problem Description:

Since update, the part where it shows Recently Added is not showing new movies.  It still shows new shows and music.  It was working prior to update.  Clicked on the filter, and it is only showing All, Shows, Music.  I am using Emby v4.4.0.7; same issue with v4.4.0.5.  Disabled Emby-Jellyfin from Settings / Homepage Items, and re-enabled; same issue.  Tried it on Chrome and Firefox; same issue.
<hr>

##### Reproduction Steps:

<hr>

#### Errors on screen?  If so paste here:

```

```

**Comment by causefx** [comment]
just installed 4.4.0.5 and movies are there for me....

**Comment by D4rkSl4ve** [comment]
Radarr was setup to:  Settings/Media Management/Change File Date:  In Cinema Date
thus causing the movies to be added with such, and they wouldn't show up on the Organizr homepage as Emby - Recently Added
