### ISSUE TITLE
Can setup Organizr.  Errors to Bad Gateway 502

### ISSUE THREAD

**Issue by marc0nline** [causefx/Organizr#1307]
###### Operating System: Windows Server 2016 (Standard)
<hr>

##### Problem Description:
Can't get to setup page.  Since I already use port 80, after initial install I change listening port to 60.  I then tried http://127.0.0.1:60 and http://192.168.1.2:60 to get to setup page but I get an error Bad Gateway 502
I also tried to run NGINX as admin, but it also fails to open
<hr>

##### Reproduction Steps:

<hr>

#### Errors on screen?  If so paste here:

```
2020/01/19 14:38:56 [error] 17400#14296: *25 CreateFile() "C:/nginx/www/organizr/html/favicon.ico" failed (2: The system cannot find the file specified), client: 127.0.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", host: "localhost:60", referrer: "http://localhost:60/"

2020/01/19 14:38:57 [error] 17400#14296: *25 connect() failed (10061: No connection could be made because the target machine actively refused it) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "localhost:60", referrer: "http://localhost:60/"

```

**Comment by tronyx** [comment]
v1 is no longer supported. Also, it says the machine refused the connection so you would need to make sure the port was open.

**Comment by marc0nline** [comment]
I'm sorry I was looking at the error and it said 1.16.1, but when I ran the installer it says I'm running version 2.5.6.  I updated the post.  I forwarded the port in the router, what else should I do?

**Comment by tronyx** [comment]
2.5.6 is not a valid version of Organizr either. How are you installing Organizr? Is the PHP service running? Did you restart the Nginx Service after changing the port to 60?

**Comment by marc0nline** [comment]
Yes I restarted the services.

Here is a pic of the installer, maybe this will help.  https://imgur.com/a/UMMIpNW

**Comment by marc0nline** [comment]
The PHP service wasn't running I had to manually update the password and start it.  I can get to the setup page now thanks.

**Comment by tronyx** [comment]
No problem. Please close this out then.
