### ISSUE TITLE
Issue adding cookie password into caddy

### ISSUE THREAD

**Issue by pavili0n** [causefx/Organizr#131]
I hope this is the right place to post this I can see examples for NGINX of blocking subpages from being browsed -  Can someone help me add this to caddy also ?

    if ($cookie_cookiePassword != "test123") { return 403; }
    add_header X-Frame-Options "SAMEORIGIN";

Thanks in advance

**Comment by causefx** [comment]
honestl, i'm not sure Caddy supports cookies in the config file.... What OS are you on?

**Comment by pavili0n** [comment]
Nice one for the quick response

Running windows unfortunately !

**Comment by pyrostic** [comment]
They don't.  I used to run Caddy and switched to NGINX, check out my
install tutorial on the wiki.  It uses a slightly harder to use server with
a lot more customizability

**Comment by pavili0n** [comment]
I am trying to get around an issue that some of my reverse proxy sites will only load up in Organizr once logged in on another page.

For example I must browse to my-site.dnymaicdns.com/sabnzbd and login on this page prior to it loading in Organizr

I would prefer to not move at the present but will look into the option if its the only solution.

**Comment by pyrostic** [comment]
That's the whole reason I left... You could add no direct link access to
caddy.  I'll see if I can dig something up.

**Comment by pavili0n** [comment]
Ah I think I have just found your post on their forum but to my understanding that means I would have to write a rewrite for every link - seems like I will have to migrate after all or wait for them to rewrite the feature.

**Comment by causefx** [comment]
You can use nginx... wnmp makes a nice package that comes with everything u need.

**Comment by pavili0n** [comment]
Thanks all

**Comment by pyrostic** [comment]
wnmp wprks alroght, but im a bigger fan of WPn-mx as it includes the
sendmail and PHP binaries.  anyway, if you stick with caddy, stick this at
the beginning of your server:

servername.ddns.net {

    rewrite / { # Secure the entire site
        if {path} not / # Except for the web root index
        if {>referer} not_has https://serername.ddns.net/ # Only if referer
isn't us
        to /forbidden
    }
    status 403 /forbidden
