### ISSUE TITLE
Issues with qBittorrent in Organizr

### ISSUE THREAD

**Issue by JimboJamez** [causefx/Organizr#1310]
###### Operating System: Windows 10
<hr>

##### Problem Description:
I have Qbitorrent v4.21 installed with nginx for reverse proxy on my Windows 10 machine. When I add a tab to Organizr for Qbittorrent the page loads but I get the attached partially loaded qBittorrent Web UI screen.
![qBittorrent](https://user-images.githubusercontent.com/25968238/74927455-c09c0a00-542b-11ea-9469-99112749b185.JPG)

All other apps are reachable from outside the network (sonarr, radarr, organizr etc), Qbitorrent is the only one having this issue.

I have the following location block set in my config file:

```
location /qbt/ {
            proxy_hide_header  Referer;
            proxy_hide_header  Origin;
            proxy_set_header   Referer           '';
            proxy_set_header   Origin            '';
            add_header X-Frame-Options "SAMEORIGIN";
            rewrite /qbt/(.*) /$1 break;
            proxy_pass http://127.0.0.1:8090;
        }
```

Any suggestions on how to resolve this?

<hr>

#### Errors on screen?  If so paste here:

```

```

**Comment by Roxedus** [comment]
What about the browser console? any errors there?

**Comment by JimboJamez** [comment]
I'm using Chrome @Roxedus . How do I check the console?

**Comment by Roxedus** [comment]
Press f12, or right click>inspect element, and go to the console tab in the new window/sidebar

**Comment by JimboJamez** [comment]
Thank you.

I can see the following error:

> Refused to load the script 'https://ajax.cloudflare.com/cdn-cgi/scripts/7089c43e/cloudflare-static/rocket-loader.min.js' because it violates the following Content Security Policy directive: "script-src 'self' 'unsafe-inline'". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.
> 
> 30Refused to load the font '<URL>' because it violates the following Content Security Policy directive: "default-src 'self'". Note that 'font-src' was not explicitly set, so 'default-src' is used as a fallback.

The page loads fine on localhost.

Any ideas what this issue would be?

**Comment by Roxedus** [comment]
We usually dont recommend leaving the rocket loader setting in cloudflare as on, due to issues like this.

**Comment by JimboJamez** [comment]
I've turned it off and it is now working!

Thank you @Roxedus , you are a star!
