### ISSUE TITLE
Small issue with Jackett and Organizr auth

### ISSUE THREAD

**Issue by YouveGotMeowxy** [causefx/Organizr#1311]
I'm using all of these in docker containers:

- Organizr
- [LSIO's LetsEncrypt](https://hub.docker.com/r/linuxserver/letsencrypt/) (Nginx container)
- [Jackett](https://hub.docker.com/r/linuxserver/jackett/)

In my Jackett.conf file for Nginx, I have this:

```
location ^~ /jackett {
    auth_request /auth-1;
    include /config/nginx/proxy.conf;
    resolver 127.0.0.11 valid=30s;
    set $upstream_jackett jackett;
    proxy_pass http://$upstream_jackett:9117;
}

location ~ /jackett/(api|dl) {
    auth_request off; # Disable Organizr auth for the API
    include /config/nginx/proxy.conf;
    resolver 127.0.0.11 valid=30s;
    set $upstream_jackett jackett;
    proxy_pass http://$upstream_jackett:9117;
}
```

When I enable the `auth_request /auth-1;` line and restart Nginx I'm able to access the Jackett webui when logged into Organizr, and get a 401 error when not logged in (perfect); however, even with the `auth_request off; ` line in the API block, I get errors accessing the Jackett indexers from other containers like NZBHydra.... (whether I'm logged into Organizor not.)

When I comment out the `auth_request /auth-1;` and restart Nginx I'm back to being able to access the Jackett indexers from Hydra.

Any idea what to do?

TIA

**Comment by HalianElf** [comment]
You should probably just use the docker network/host IP rather than trying to do it through the reverse proxy.

**Comment by YouveGotMeowxy** [comment]
@HalianElf I'm not sure I follow, can you give me an example, pls?

**Comment by HalianElf** [comment]
All of my stuff like that uses `http://container-name:port` if you're using the default bridge network, `http://host-ip:mapped-port`. It doesn't need to go through the reverse proxy when they're all local

**Comment by YouveGotMeowxy** [comment]
@HalianElf I have all 3 containers in a bridged network (but not the default one) and they work fine together with that config until I add the auth_request line. afaik the:

```
    resolver 127.0.0.11 valid=30s;
    set $upstream_jackett jackett;
    proxy_pass http://$upstream_jackett:9117;
```

stuff essentially is the same as directly doing a `http://container-name:port` but that it just resolves the container name first.

**Comment by HalianElf** [comment]
If you're using something like `http://jackett:9117` in your Hydra it shouldn't ever hit Organizr's auth

**Comment by YouveGotMeowxy** [comment]
@HalianElf Interesting. I spose I could try that, but I have something like 20 indexers in hydra that I'd have to manually change rather than just 1 line in the proxy config.

the other thing I'm concerned with is if/when I also would need to do the same for other API urls for other containers. It seems like it'd be a lot of work to go through and hand edit so many urls across a bunch of containers.

**Comment by HalianElf** [comment]
So the reason it's not working is because of your nginx regex. You have `^~` which is making it ignore the regex in the second block.

```nginx
location /jackett {

    # Organizr auth
    auth_request /auth-1;

    include /config/nginx/proxy.conf;
    resolver 127.0.0.11 valid=30s;
    set $upstream_jackett jackett;
    proxy_pass http://$upstream_jackett:9117;
}

location ~ /jackett/(api|dl) {
    include /config/nginx/proxy.conf;
    resolver 127.0.0.11 valid=30s;
    set $upstream_jackett jackett;
    proxy_pass http://$upstream_jackett:9117;
}
```
This works fine

**Comment by YouveGotMeowxy** [comment]
Thank you @HalianElf  and @nemchik for helping me to quickly resolve this.
