### ISSUE TITLE
Plex oAuth Login error

### ISSUE THREAD

**Issue by jscottelblein** [causefx/Organizr#1313]
My current Organizr info:

![image](https://user-images.githubusercontent.com/1524526/75061676-d0a4ff80-54a6-11ea-93ac-9831b225c3f0.png)

![image](https://user-images.githubusercontent.com/1524526/75061705-de5a8500-54a6-11ea-88e0-c324a4592249.png)

When I try to login with Plex, it shows the usual Plex popup, I click the login button on it, Organizr shows the Successful login in green to the right, then after a second, at the bottom left a popup shows:

> Login Error
> Wrong username/email/password combo

The green "successful" stays at the top, but nothing else ever happens, no matter how long I wait.

For kicks, after this happens Iclick the login with Organizr button and it doesn't show any fields to fill in, and clicking the button just shows that same error popup to the bottom left.

![image](https://user-images.githubusercontent.com/1524526/75062309-30e87100-54a8-11ea-960e-7120f2a71ce7.png)

To get around it all, I have to refresh the page and just use the regular Organzr login.

Here's a short vid of it happening. (apologies for the quality, I tried out a new gif capturing software and it had weird sizing issues; I had to resize it, and in doing so it made it a bit of a blurry mess, lol, but you can still get the gist).

![capture2](https://user-images.githubusercontent.com/1524526/75062485-80c73800-54a8-11ea-8966-07cca59ba8f1.gif)

I have re-entered my Plex credentials in both the SSO > Plex page and the Settings > Auth page, using Organizr's  Fetch buttons. I use the same creds for the Homepage to show Plex stuff and they do show, so it seems like it's not due to bad creds.

The most I see in the console is:

![image](https://user-images.githubusercontent.com/1524526/75062766-1662c780-54a9-11ea-815f-d6864a6989b1.png)

**Comment by causefx** [comment]
try changing the field Admin Username  to your plex email address.

**Comment by jscottelblein** [comment]
> try changing the field Admin Username to your plex email address.

Hmmmm. That does allow me to login now (using either my Plex email addy, or the Plex username I use with it) but then after logging into Org it's showing as a different user than my regular Admin ("Scott").

Any way to link the 2? I did try changing my Plex username to "Scott" but it just gives me an error saying the name is used already, and won;t let me; and I can't edit my Org user name (the field is locked).

**Comment by jscottelblein** [comment]
ok, I just made my Plex user a co-admin in Org and shared everything my admin acct. has to co-admin

**Comment by causefx** [comment]
Correct - you did it the right way... I need to reword the admin username part so people know I am speaking about the plex admin username.

**Comment by jscottelblein** [comment]
Thanks @causefx , I appreciate the help.
