### ISSUE TITLE
2.0.370 update not working

### ISSUE THREAD

**Issue by MartyIU13** [causefx/Organizr#1316]
###### Operating System: QNAP TS-253A
<hr>

##### Problem Description:
Update to 2.0.370 says it works when following steps, but after Organizr restart it still says to update.

<hr>

##### Reproduction Steps:
1. Receive popup that version 2.0.370 is available
2. Click on link in popup to go to the Updates Tab 
3. Click Install Update button for version 2.0.370 
4. Says completed (update cleanup finished) and Organizr restarts
5. When it restarts there is a popup that says update successful, but the popup to update to 2.0.370 is right below that successful update popup.

Have tried many times. It seems the updater isn't working for me.

<hr>

#### Errors on screen?  If so paste here:

```
No Errors on screen. Says it worked, but didn't
```

**Comment by causefx** [comment]
Can you check the folder permissions?

**Comment by MartyIU13** [comment]
Sorry if this is a noob question, but how? I installed in a QNAP. Which folder and what permissions would be needed? I can get into the QNAP with WinSCP but not sure where to look and what to do.

**Comment by stanthewizzard** [comment]
I also have an update not working on debian.
Folder permission are set to www-data recursivly 0777
Thanks

**Comment by hunterlong** [comment]
+1  just time using this, and it doesn't seem to do anything. kinda confused. fix?

**Comment by MartyIU13** [comment]
> I also have an update not working on debian.
> Folder permission are set to www-data recursivly 0777
> Thanks

May I ask how you check folder permissions? I'm running off a QNAP.

**Comment by causefx** [comment]
can you post /js/versions.json file?

**Comment by MartyIU13** [comment]
[version.json.txt](https://github.com/causefx/Organizr/files/4273232/version.json.txt)

**Comment by causefx** [comment]
thanks. can you now check to see if you have anything in either php logs or web server logs after an update?

**Comment by MartyIU13** [comment]
Don't see anything with those names, but here's some log files from the QNAP folder after I just tried to update now and got same issue.

[access_log.txt](https://github.com/causefx/Organizr/files/4284618/access_log.txt)
[organizrLog.json.txt](https://github.com/causefx/Organizr/files/4284621/organizrLog.json.txt)
[error_log.txt](https://github.com/causefx/Organizr/files/4284622/error_log.txt)
[Organizr73v2.log.txt](https://github.com/causefx/Organizr/files/4284623/Organizr73v2.log.txt)

**Comment by causefx** [comment]
It seems it can’t verify the github ssl certificate. 

i may just rewrite that to include our own certificate to verify with.

**Comment by causefx** [comment]
@MartyIU13 @stanthewizzard @hunterlong 

Please download this file:
https://github.com/causefx/Organizr/archive/v2-develop.zip

and overwrite all the files in your install.

After that please make sure you switch to dev branch if not on already and click force install branch after reloading setting page.

**Comment by MartyIU13** [comment]
@causefx The files copied over looks like it updated Organizr to 2.0.370, but when I change the branch to Develop and reload setting page, when I click Retrieve under Force Install Branch it says Update File Download Failed and sticks on 5%.

**Comment by causefx** [comment]
can you goto setting and then organizr logs and paste what’s there

**Comment by MartyIU13** [comment]
March 5, 2020 8:42 PM | MartyIU13 | 192.168.1.217 | Update Function - Downloaded Update File Failed for Branch: v2-develop [Execution Time: 85.7ms] |  
-- | -- | -- | -- | --
March 5, 2020 8:42 PM | MartyIU13 | 192.168.1.217 | organizr could not download https://github.com/causefx/Organizr/archive/v2-develop.zip [Execution Time: 01.54s \| 1547.4ms] |  
March 5, 2020 8:42 PM | MartyIU13 | 192.168.1.217 | Update Function - Started Upgrade Process [Execution Time: 25.1ms] |  
March 5, 2020 8:41 PM | MartyIU13 | 192.168.1.217 | Admin Function - Accessed Settings Page [Execution Time: 23.2ms] |  
March 5, 2020 8:08 PM | SYSTEM | 192.168.1.217 | Plex Connect Function - Error: cURL error 28: Operation timed out after 10000 milliseconds with 0 bytes received [Execution Time: 10.61s \| 10619.1ms] |  
March 5, 2020 8:08 PM | SYSTEM | 192.168.1.217 | Plex Connect Function - Error: cURL error 28: Operation timed out after 10003 milliseconds with 0 bytes received [Execution Time: 12.85s \| 12854.7ms] |  
March 5, 2020 8:05 PM | MartyIU13 | 192.168.1.217 | Update Function - Downloaded Update File Failed for Branch: v2-develop [Execution Time: 62.3ms] |  
March 5, 2020 8:05 PM | MartyIU13 | 192.168.1.217 | organizr could not download https://github.com/causefx/Organizr/archive/v2-develop.zip [Execution Time: 01.20s \| 1209.9ms] |  
March 5, 2020 8:05 PM | MartyIU13 | 192.168.1.217 | Update Function - Started Upgrade Process [Execution Time: 52.1ms] |  
March 5, 2020 8:05 PM | MartyIU13 | 192.168.1.217 | Admin Function - Accessed Settings Page [Execution Time: 31ms]

**Comment by causefx** [comment]
thank you. can you now post the same logs from beforr? the same 4 files.

**Comment by MartyIU13** [comment]
[organizrLog.json.txt](https://github.com/causefx/Organizr/files/4296242/organizrLog.json.txt)

**Comment by MartyIU13** [comment]
[Organizr73v2.log.txt](https://github.com/causefx/Organizr/files/4296243/Organizr73v2.log.txt)

**Comment by MartyIU13** [comment]
[error_log.txt](https://github.com/causefx/Organizr/files/4296244/error_log.txt)

**Comment by MartyIU13** [comment]
access_log is empty and won't let me post

**Comment by causefx** [comment]
this is a big help. thanks. will check it out

**Comment by causefx** [comment]
@MartyIU13 thanks for the logs - I think I may have nailed down the last function...  You can either redownload the zip again and overwrite.  or you can edit the file `normal-functions.php` located under `/api/functions/` and edit the function on line `310` to this:

*EDITED CODE*
```
function getCert()
{
	$url = 'http://curl.haxx.se/ca/cacert.pem';
	$file = __DIR__ . DIRECTORY_SEPARATOR . 'cert' . DIRECTORY_SEPARATOR . 'cacert.pem';
	$file2 = __DIR__ . DIRECTORY_SEPARATOR . 'cert' . DIRECTORY_SEPARATOR . 'cacert-initial.pem';
	$useCert = (file_exists($file)) ? $file : $file2;
	if($GLOBALS['selfSignedCert'] !== ''){
		if(file_exists($GLOBALS['selfSignedCert'])){
			return $GLOBALS['selfSignedCert'];
		}
	}
	$context = stream_context_create(
		array(
			'ssl'=> array(
				'verify_peer' => true,
				'cafile' => $useCert
			)
		)
	);
	if (!file_exists($file)) {
		file_put_contents($file, fopen($url, 'r', false, $context));
	} elseif (file_exists($file) && time() - 2592000 > filemtime($file)) {
		file_put_contents($file, fopen($url, 'r', false, $context));
	}
	return $file;
}
```

Then place this file: https://curl.haxx.se/ca/cacert.pem

inside `api/functions/cert/` leave it named that or name it `cacert-initial.pem` up to you

**Comment by MartyIU13** [comment]
@causefx Thanks! Looks like that worked. Now on 2.0.390. Clicking Retrieve under Force Install Branch on Dev worked. It loaded the file and auto restarted Organizr. Will play around with it for a while and let you know of any issues. Liking it so far.

**Comment by causefx** [comment]
awesome. thanks for nailing it down with me.

**Comment by fireheadman** [comment]
would like to comment on this...
I had the same issue.

Slight adjustment to the fix, but it still works for a fix!!
Running this on Freenas (jail)

vi /usr/local/www/Organizr/api/functions/normal-functions.php
 
**Before:** (Line is now starting at 559)
![image](https://user-images.githubusercontent.com/19847195/101965639-a6a60080-3bd2-11eb-8a36-e3eefcf5c6d6.png)

**After:** (Line 559 give/take)... this screenshot is after performing the update, so believe something new was inserted?)
![image](https://user-images.githubusercontent.com/19847195/101965604-88d89b80-3bd2-11eb-9889-7edcbd36b5b3.png)


Also noticed the cacert.pem is 0 bytes and I also have a cacert-initial.pem.
![image](https://user-images.githubusercontent.com/19847195/101965763-013f5c80-3bd3-11eb-969a-df664797ebae.png)

I downloaded the pem file and renamed it to cacert.pem

I did not have to restart ngix, just refreshed the page and fired off the update...
BAM, it works now!

**Comment by bagelskat** [comment]
> Also noticed the cacert.pem is 0 bytes and I also have a cacert-initial.pem.
> ![image](https://user-images.githubusercontent.com/19847195/101965763-013f5c80-3bd3-11eb-969a-df664797ebae.png)
> 
> I downloaded the pem file and renamed it to cacert.pem
> 
> I did not have to restart ngix, just refreshed the page and fired off the update...
> BAM, it works now!

Same issue. Replacing the cacert.pem and cacert.-initial.pem fixed the issue. No code changes. Still on master branch.

Thank you everyone.
