### ISSUE TITLE
Organizr become unresponsive after opening "Tab Editor" tab

### ISSUE THREAD

**Issue by Cookie-Monster-Coder** [causefx/Organizr#1319]
###### Operating System: Linux hosted on server
<hr>

##### Problem Description:
[It's the same issue as this 2 year old post but no solution seems to be found.](https://github.com/causefx/Organizr/issues/1009)
Increasing the pm limits don't seem to help. 
Happens only on the "Tab Editor" tab in settings.
Webpage becomes unresponsive.
Firefox shows a tab not responding notice (The yellow warning label).
My computer ram maxes out (Without the "Tab Editor" tab open, about 4-5 GB of ram is being used, when the tab is opened ram shoots up to 7.8 GB (Have 8 GB installed)).
Happens on every browser and device.

Here is my nginx config file:
```
error_log /home/<USER>/.config/nginx/error.log info;
pid /dev/null;
worker_processes auto;
events { worker_connections 4096; }
http {
        include mimes.conf; #for custom file types
        default_type application/octet-stream;
        access_log /home/<USER>/.config/nginx/access.log combined;

        client_body_temp_path /home/<USER>/.config/nginx/tmp/client_body;
        proxy_temp_path /home/<USER>/.config/nginx/tmp/proxy;
        fastcgi_temp_path /home/<USER>/.config/nginx/tmp/fastcgi;
        uwsgi_temp_path /home/<USER>/.config/nginx/tmp/uwsgi;
        scgi_temp_path /home/<USER>/.config/nginx/tmp/scgi;

        server_tokens off;
        sendfile on;
        tcp_nopush on;
        tcp_nodelay on;
        keepalive_timeout 4;

        output_buffers  1 32k;
        postpone_output  1460;

        server {
                listen <PORT> ssl; #IPv4
                listen [::]:<PORT> ssl; #IPv6
		gzip on;
		gzip_vary on;
		gzip_min_length 1000;
		gzip_proxied any;
		gzip_types text/plain text/css text/xml application/rss+xml application/vnd.ms-fontobject text/x-component application/xml application/json text/javascript font/truetype font/opentype application/x-javascript image/svg+xml application/javascript;
		gzip_disable "MSIE [1-6]\.";

                root /home/<USER>/.config/nginx/webroot/Organizr;
		server_name <WEBSITE>.com;

		location / {
			try_files $uri $uri/ =404;
			index index.php index.html index.htm index.nginx-debian.html;
			include /home/<USER>/.config/nginx/includes/php.conf;  #PHP Block
		}
```

Here is my php-fpm2 file:

```
[global]
daemonize = yes
error_log = /home/<USER>/.config/php-fpm2/error.log
    
[www]
listen = /home/<USER>/.config/php-fpm2/socket
    
listen.owner = <USER>
listen.group = <USER>
listen.mode = 0600

pm = dynamic
pm.max_children = 200
pm.start_servers = 15
pm.min_spare_servers = 15
pm.max_spare_servers = 25
pm.max_requests = 500
```

<hr>

##### Reproduction Steps:
1. Go to the Setting page
2. Open "Tab Editor" tab

**Comment by causefx** [comment]
Does this happen once clicking the edit tab button or when trying to click on the icons field?

If all possible can you install another instance of organizr and give me admin access to do some tests?

**Comment by Cookie-Monster-Coder** [comment]
Happens right when you click on edit tab button.
Yeah, I'll try to spin another one up.

**Comment by causefx** [comment]
Thanks - if you are on discord you can PM there or just click the support icon inside organizr on bottom left

**Comment by Cookie-Monster-Coder** [comment]
> 
> 
> Thanks - if you are on discord you can PM there or just click the support icon inside organizr on bottom left

Sorry it took long. Can I PM you on reddit? Discord won't let me login without putting in my cell phone number.

**Comment by causefx** [comment]
reddit is fine. same username

**Comment by Cookie-Monster-Coder** [comment]
Sent

**Comment by causefx** [comment]
@Cookie-Monster-Coder are you running the dev branch by any chance?

**Comment by Cookie-Monster-Coder** [comment]
> @Cookie-Monster-Coder are you running the dev branch by any chance?

On my main server, yes. But the same thing is happening on both branches I believe.

**Comment by causefx** [comment]
OK - i'm adding a toggle in the meantime to disable that dropdown box.... let me push the changes.

**Comment by causefx** [comment]
alright - there isnt a new version number - force pull from settings unless you installed with GIT.  clear cache and toggle atleast the icon switch.  

![image](https://user-images.githubusercontent.com/16184466/75731913-416dc800-5cae-11ea-9606-168cc7594b98.png)

**Comment by Cookie-Monster-Coder** [comment]
Works perfectly now, smooth like butter! Thank you!
Just curious on why the icon drop down box was causing so much lag? And why is it such a rare occurrence? I actually had to dig to find that 2 year old post.

**Comment by causefx** [comment]
it has a ton of icons. a few thousand. depending on web server and browser it will exceed the maximum stack

**Comment by nmusselman** [comment]
@causefx it's still doing this for me today on 13.0.8 and I can't find this setting in the UI?
