### ISSUE TITLE
Chrome: Tautulli no longer loads dashboard

### ISSUE THREAD

**Issue by Nostang3** [causefx/Organizr#1320]
###### Operating System: Freenas(FreeBSD) > Manual Install
<hr>

##### Problem Description:
I can load the login page but entering the correct credentials only reloads the page and does not let me access the dashboard. Chrome console says: 

> Blocked autofocusing on a form control in a cross-origin subframe.

This is new. It worked fine yesterday and today it doesn't. Works in Firefox. 
<hr>

##### Reproduction Steps:
Load Organizr page in chrome. Attempt to login to the Tautulli webpage. Page then refreshes login page. Rinse. Repeat.

<hr>

#### Errors on screen?  If so paste here:

```
No visible errors. 
```

**Comment by causefx** [comment]
can someone try chrome - works in edge chromium based.
![image](https://user-images.githubusercontent.com/16184466/75831162-0af88180-5d70-11ea-9e8b-e858e9f9350b.png)

**Comment by HalianElf** [comment]
Works ok in my chrome: https://sharex.helflix.app/Waxo2/POMORoHo98.png

**Comment by tronyx** [comment]
Works fine in Chrome. I am able to login without any issues using the Tautulli login. @causefx @HalianElf The user is saying login doesn't work, not that it doesn't load. Are you able to login?

**Comment by Nostang3** [comment]
Tautulli seems to register the login successfully as the log says: 
> 2020-03-03 18:25:40 - DEBUG   :: CP Server Thread-14 : Tautulli WebAuth :: Admin user 'XXXXX' logged into Tautulli using form login.

But it never leaves this page and go to the dashboard. I can login to Tautulli directly in chrome and see the dashboard. 
![image](https://user-images.githubusercontent.com/25465114/75831724-47cd7400-5d82-11ea-991f-89ea4db1a084.png)

**Comment by HalianElf** [comment]
Yes, it logs in fine

Both with the login form and the Plex button.

**Comment by tronyx** [comment]
@Nostang3 What version of Chrome are you running? Worked for me on 80.0.3987.122, I then checked for updates, which there was one available, and it also works on 80.0.3987.132.

**Comment by Nostang3** [comment]
@christronyxyocum It fails to load on 80.0.3987.132 and didn't work on the immediate previous version( I assume was probably .122 like you). So I tried to load the page, failed, updated chrome to .132, tried it again and it failed on the newest version as well.

**Comment by HalianElf** [comment]
So have you tried it outside of the iframe? I get the same error in console now that I setup a subdomain for it but it still logs in perfectly fine despite that error.

**Comment by Nostang3** [comment]
Do you mean manually going to Tautulli IP(192.168.x.x) address and logging in? If so, then yes. I can login, in chrome, directly to Tautulli without issue. It's just trying to load dashboard using the iframe.

**Comment by HalianElf** [comment]
So I was able to replicate this using the local ip:port when they're on different servers. You're not getting any errors because it's not erroring, it's just logging in only to immediately log back out. See here: https://sharex.helflix.app/Waxo2/wIjiBElE69.png

I don't know what you would be able to do to solve it, however. Reverse proxying it seems to work ok in the iframe so I'm not sure what in Tautulli is telling it to log out right after logging in.

**Comment by Nostang3** [comment]
I don't think that is my case because the Tautulli logs never show a logout for organizr during sign on attempt. All it shows is the logon attempt. 

>2020-03-03 18:21:11 - DEBUG   :: CP Server Thread-7 : Tautulli WebAuth :: Admin user 'XXXXXX' logged into Tautulli using form login.
2020-03-03 18:25:12 - DEBUG   :: CP Server Thread-13 : Tautulli WebAuth :: Admin user 'XXXXXX' logged into Tautulli using form login.
2020-03-03 18:25:37 - DEBUG   :: CP Server Thread-14 : Tautulli WebAuth :: Admin user 'XXXXXX' logged into Tautulli using form login.
2020-03-03 18:25:39 - DEBUG   :: CP Server Thread-14 : Tautulli WebAuth :: Admin user 'XXXXXX' logged into Tautulli using form login.
2020-03-03 18:25:40 - DEBUG   :: CP Server Thread-14 : Tautulli WebAuth :: Admin user 'XXXXXX' logged into Tautulli using form login.
2020-03-03 18:27:12 - DEBUG   :: CP Server Thread-11 : Tautulli WebAuth :: Admin user 'XXXXXX' logged into Tautulli using form login.
2020-03-03 18:31:03 - DEBUG   :: CP Server Thread-10 : Tautulli WebAuth :: Admin user 'XXXXXX' logged into Tautulli using form login.
2020-03-03 18:36:16 - DEBUG   :: CP Server Thread-13 : Tautulli WebAuth :: Admin user 'XXXXXX' logged into Tautulli using form login.
2020-03-03 18:36:27 - DEBUG   :: CP Server Thread-5 : Tautulli WebAuth :: Admin user 'XXXXXX' logged into Tautulli using form login.
2020-03-03 18:37:02 - DEBUG   :: CP Server Thread-9 : Tautulli WebAuth :: Admin user 'XXXXXX' logged into Tautulli using form login.

If I choose to sign out on the localip:8181 it will log it in the log. 

> 2020-03-03 22:13:14 - DEBUG   :: CP Server Thread-8 : Tautulli WebAuth :: Admin user 'XXXXXX' logged out of Tautulli.

**Comment by HalianElf** [comment]
My Tautulli log is showing the same.

**Comment by Nostang3** [comment]
I stand corrected then. I checked and its the same for me. So there is no fix? I guess I'll have to start using Firefox instead of Chrome now.

**Comment by HalianElf** [comment]
I brought it up in the Tautulli discord. If I find a solution, I will let you know.

**Comment by Nostang3** [comment]
@HalianElf Thanks. 

Thanks to everyone else that helped in the thread.

**Comment by HalianElf** [comment]
So after some back and forth with Swift, we've found out it has to do with some of the newer chrome flags. Specifically the `SameSite by default cookies` if you go into the chrome flags and disable it, it seems to fix it.

**Comment by tronyx** [comment]
Nevermind, you're not reverse proxying it.

**Comment by Nostang3** [comment]
That did indeed fix the issue. The weird thing is that by disabling that flag and just relaunching the browser I don't even have to log into Tautulli, it's already logged in. 

Anyway, thanks for the fix.

**Comment by HalianElf** [comment]
If you were logged in from the out of iframe tab, once disabling that flag it would then be able to see the cookie (or might have even still had the cookie from trying in the iframe, just couldn't access it)
