### ISSUE TITLE
Possible to Increase SSO timeout for Ombi and Tautulli?

### ISSUE THREAD

**Issue by Cookie-Monster-Coder** [causefx/Organizr#1321]
###### Operating System: Linux
<hr>

##### Problem Description:
I noticed that when my server is under load, mostly when downloading, SSO for Ombi and Tautulli are a hit or miss. Sometimes it works and other times it won't. 

I'm thinking of having Organizr request a token multiple times from Ombi and Tautulli before failing after one try.

<hr>

##### Reproduction Steps:
1. Login when server is under load
2. Organizr will sign you in, but SSO won't work always

<hr>

#### Errors on screen?  If so paste here:

```
Tautulli Token Function - Error: [http://localhost:13000/statistics]cURL error 28: Operation timed out after 10001 milliseconds with 0 bytes received [Execution Time: 18.99s | 18993.6ms]

Ombi Token Function - Error: cURL error 28: Operation timed out after 10000 milliseconds with 0 bytes received [Execution Time: 10.02s | 10028.6ms]
```

**Comment by causefx** [comment]
I wouldnt want to add that many calls - what I can do is add options to increase the seconds to wait for response back.  You may want to see if downloading is the actual bottleneck tho.

**Comment by Cookie-Monster-Coder** [comment]
> You may want to see if downloading is the actual bottleneck tho.

Yeah, after logging in multiple times and testing different downloading speeds, downloading is def the bottleneck. I put a speed limit in NZBGet of 18MB/s and it seems to now work 90% of the time. Without anything downloading it works 100% of the time. Might play with the numbers a little more tho to get better results.

If you could add a textbox/slider for a custom wait time that would be awesome and would allow more granular control.

**Comment by causefx** [comment]
what hardware is this running on?

**Comment by Cookie-Monster-Coder** [comment]
I'm using a seedbox vps, from what I gathered its has a Intel Xeon CPU E5-2697 v4 @ 2.30GHz x86_64. From my stats page it shows 72 bar usage for the CPU, so I am assuming it's getting load balanced between all the users. And for RAM there's about 380GB, again load balanced between all the users.

**Comment by tronyx** [comment]
Increasing the limits much more is really not a good idea, nor is coding it as a setting. This issue is indicative of a larger problem, IE: hardware usage, and, despite the fact that you're running it on a shared platform, it's still just a band-aid rather than an actual fix. Hopefully you can figure out a solid balance with your numbers to make things better.

**Comment by guydavis** [comment]
I see this sporadically (~50% of logins) as well on an old PC under my desk,  I would appreciate a way to extend the timeout on SSO call to Ombi as well.

**Comment by Roxedus** [comment]
I'm interested in seeing your servers IOWait under these loads. That will help find the bottleneck.

**Comment by Cookie-Monster-Coder** [comment]
When I drop my download speed to 10M/s IOWait % is about 6%, and SSO works about 100%. When download speeds are around 25-30M/s IOWait % is about 18-24%, this is where I see a major drop in successful SSO.

Honestly keeping low download speeds is fine with me, it helps a lot with performance.

**Comment by Roxedus** [comment]
That's ALOT of iowait. This is not a Organizr issue, but a systemissue
