### ISSUE TITLE
FEATURE REQUEST: Add Multiple Plex Servers

### ISSUE THREAD

**Issue by mperez02** [causefx/Organizr#1323]
###### Operating System: Raspberry Pi/Debian/Buster v10
<hr>

##### Problem Description:
Need to be able to see information from multiple PLEX servers on the same network.

<hr>

##### Reproduction Steps:
Current config options only allow for one server to be selected

<hr>

#### Errors on screen?  If so paste here:

```

```

**Comment by causefx** [comment]
We are moving Feature Requests away from **GitHub** and **FeatHub**.  We are now on **_FeatureUpvote_** which is located here:
### **https://vote.organizr.app**
If will also be a tab in Organizr update this Friday 22 Jan 2021


If this Feature Request was already on FeatHub it will get moved over within the week - no further action is needed.
If not, please create a new Feature Request at our new home so we can better keep track of them.
