### ISSUE TITLE
Ombi homepage item "Item limit" setting does not change the number of items displayed on the homepage

### ISSUE THREAD

**Issue by nameproof** [causefx/Organizr#1324]
###### Operating System: Unraid Docker
<hr>

##### Problem Description:
In the Ombi Homepage Item there's a setting for changing item limit. It has a default value of 50. The items shown in the homepage item is 50 items no matter what you change the item limit value to.

I changed this to 250 and left it like that for 1 full day to let the API hits update. Restarted Organizr, cleared cloudflare cache and opened a new window in private mode and it still only shows 50 items.

The setting does not appear to change anything.
<hr>

##### Reproduction Steps:

Set up Ombi homepage item -> Settings ->  Tab editor -> Homepage Items -> Ombi -> Misc options -> Change item limit to 250.

Expected change: Ombi homepage items shows 250 items. In reality it never changes from 50.
<hr>

**Comment by causefx** [comment]
error in my code - sorry - fixed now

**Comment by nameproof** [comment]
This issue started again with the latest API v2 update

**Comment by tronyx** [comment]
Reopening per @nameproof's request in Discord.

**Comment by causefx** [comment]
try with latest commit
