### ISSUE TITLE
[Feature Suggestion] Rclone homepage integration

### ISSUE THREAD

**Issue by ta-vroom** [causefx/Organizr#1325]
I think it would be nice to see rclone status on the home page for those who use it.

**Comment by causefx** [comment]
Rclone has an API?

**Comment by ta-vroom** [comment]
It does via [rc](https://rclone.org/rc/#supported-parameters). It also has a [webui](https://github.com/rclone/rclone-webui-react) which is in development.

**Comment by tronyx** [comment]
Then why not just create a tab for the webUI? Are you going to be running rClone so consistently that you'd need a Homepage Item like we have for rTorrent, NZBGet, etc?

**Comment by ta-vroom** [comment]
I have rclone mounted, so I figured it might be useful for people like me to see rclone activity. Of course I could look at network activity.

I've changed to title to "Suggestion" from "Request" because I'm willing to work on it if there's interest, but I don't feel strongly one way or another. I was just curious on the crossover between Organizr users and Rclone users.

**Comment by sirloinofbeef** [comment]
As a regular rclone user this would be awesome.
