### ISSUE TITLE
[FEATURE REQUEST] OpenLDAP integration not working as expected

### ISSUE THREAD

**Issue by technics3** [causefx/Organizr#1326]
###### Operating System: Debian 10 Buster
<hr>

##### Problem Description:

I have a working OpenLDAP that i try and connect to Organizr. 

I followed the doc, choose Organizr + backend method and setup as follow :

- host address : ldap://192.168.0.xx:389
- host base DN : dc=domain,dc=tld
- LDAP backend type : OpenLDAP
- Account prefix : uid=
- Account suffix : ,ou=People,dc=domain,dc=tld
- Bind username: cn=admin,dc=domain,dc=tld
- Password : *******************

The connection test is working, but i can't connect with any LDAP user account. 

**However** : the thing is working when i use "cn=" instead of "uid=" in the "Account prefix" field. I don't want my user to login with the cn attribute, so it doesn't work for me. 

I fill an issue because the documentation example is showing "uid=" on the "Account prefix" field, so i guess it is suppose to be working.

**Comment by HalianElf** [comment]
Do your users have a uid field? The documentation shows uid because that's how my users were set up in my OpenLDAP (they didn't have a CN field on mine). What you are able to use is dependent on what your LDAP has for them.

**Comment by technics3** [comment]
Yep, they've both a CN and uid field, the CN is for name + first name and uid for nickname. The RDN identifier for my users is CN tho, which may be the problem ? I guess Organizr is using this to identify user.

EDIT : Yep, that was the problem. I guess it'll be awesome to choose which field I want to use.

**Comment by causefx** [comment]
We are moving Feature Requests away from **GitHub** and **FeatHub**.  We are now on **_FeatureUpvote_** which is located here:
### **https://vote.organizr.app**
If will also be a tab in Organizr update this Friday 22 Jan 2021


If this Feature Request was already on FeatHub it will get moved over within the week - no further action is needed.
If not, please create a new Feature Request at our new home so we can better keep track of them.
