### ISSUE TITLE
Jackett is stuck in endless redirects

### ISSUE THREAD

**Issue by Nostang3** [causefx/Organizr#1327]
###### Operating System: FreeBSD/Freenas (Separate Device)
<hr>

##### Problem Description:
Recently, Jackett is getting stuck in an endless redirect. It looks like it's logging in but getting messed up on the redirect from what I can guess by looking at the console. Don't quote me. Issue is present in all current browser versions. Can open Jackett in it's own tab in every browser. Jackett itself has updated 3 times since I've had the issue(not sure if that's helpful but figured I'd add it.)

<hr>

##### Reproduction Steps:
Load into Organizr via desktop browser then try to view the Jackett iFrame. 

<hr>

#### Errors on screen?  If so paste here:
No Visible Errors
```

```

**Comment by causefx** [comment]
Is organizr and jackett on same domain when accessing?

![image](https://user-images.githubusercontent.com/16184466/76574484-afb64580-6479-11ea-843d-f6bbed15214f.png)

**Comment by Nostang3** [comment]
They both locally in the 192.168.1.X. I'm trying to connect to the Freenas jail from my PC.

**Comment by causefx** [comment]
from what i have observered in this very short time is that jackett is trying to write a cookie to the browser using the Lax flag on `SameSite`
![image](https://user-images.githubusercontent.com/16184466/76574740-63b7d080-647a-11ea-99a7-4f133d503389.png)
I believe this is what is causing the issue.  Is organizr and jackett on same ip?

**Comment by Nostang3** [comment]
No they are in separate jails with separate IP's.

**Comment by causefx** [comment]
unless you reverse proxy them - this issue will persist.

**Comment by Nostang3** [comment]
So if I move Organizr into the same jail it would fix the issue? 

What changed to cause this? It's been fine for like a year or more.

**Comment by causefx** [comment]
more than likely browser update or jackett updated how they store their cookies.

**Comment by HalianElf** [comment]
The change was made in Chrome as of v80 which was released last month.

**Comment by Nostang3** [comment]
But it happens in all browsers not just chrome. I'll try moving it into the same jail and see what happens.

**Comment by causefx** [comment]
you could also turn off the flags
Chrome://flags

**Comment by Nostang3** [comment]
I already have SameSite by default cookies disabled. Is there any other flags to turn off? 

I tried toggling the Samesite flag and it doesn't work enabled or disabled.
