### ISSUE TITLE
Sidebar doesn't load tabs on iPhone running iOS 13.4+

### ISSUE THREAD

**Issue by petercockroach** [causefx/Organizr#1328]
###### Operating System: macOS
<hr>

##### Problem Description:
When loading Organizr page on iPhone, tabs appear blank. You can still select them if you guess correctly. Also, occasionally tapping on one link shows two tabs below it briefly

<hr>

##### Reproduction Steps:
Navigate to Organizr page from iPhone running iOS 13.4+

<hr>

**Comment by causefx** [comment]
is 13.4 still beta?

**Comment by petercockroach** [comment]
Yes, it is at the moment

**Comment by tronyx** [comment]
This issue has been reported by at least one other user and confirmed by a member of our support team. As far as we can tell, it's an issue with the iOS version.

**Comment by petercockroach** [comment]
Do you know if the issue has been reported to Apple? I’m happy to do so but would need to know specifically what is failing to render, particularly if we could isolate the WebKit code.

**Comment by tronyx** [comment]
I honestly have no idea.

**Comment by owine** [comment]
I previously reported this to apple following some discussion in Discord when this beta cycle began.

**Comment by y0da822** [comment]
Issue exists also with general public release on chrome on iOS.

**Comment by petercockroach** [comment]
> Issue exists also with general public release on chrome on iOS.

Chrome on iOS will just use the same native WebKit that Safari uses. Now that 13.4 has been released publicly, this will be hit more commonly.

**Comment by causefx** [comment]
I just updated my phone to 13.4.  I will *try* and find this

**Comment by causefx** [comment]
If anyone is running dev - please test this out

**Comment by causefx** [comment]
confirmed fixed my multiple individuals.

**Comment by y0da822** [comment]
I downloaded the update and the problem was fixed but then a day later it came back again. Side bar is blacked out again. 

Cleared cached cookies on two browsers. Anyone else or just me?

**Comment by petercockroach** [comment]
It’s still working for me

**Comment by y0da822** [comment]
That sucks for me.

**Comment by causefx** [comment]
If you wanna pm me on discord I can test from my end.

**Comment by y0da822** [comment]
Ok sounds good. Dm me on discord. Appreciate it. 

Just signed up for discord. No idea how to use it.

**Comment by causefx** [comment]
https://discordapp.com/invite/TrNtY7N

join our room
