### ISSUE TITLE
Undefined index: HTTP_X_FORWARDED_SERVER error while reverse proxy

### ISSUE THREAD

**Issue by a-mrowiec** [causefx/Organizr#1329]
###### Operating System: Debian GNU/Linux 9 (stretch) on armv7l
<hr>

##### Problem Description:

Hello, I am using NGXConfigurator to set up reverse proxy for my sonarr running on same machine. But it seems like there is problem with organizr itself I think. Generated nginx configuration from plugin looks like below

```
location /sonarr {
        auth_request /auth-1;
        proxy_pass http://localhost:8989/sonarr/;
        proxy_set_header X-Real-IP $remote_addr; 
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_http_version 1.1;
        proxy_no_cache $cookie_session;
        location /sonarrapi {
			auth_request off;
			proxy_pass http://localhost:8989/sonarr/api;
		}
}	
```

and the error log for example request to sonar looks like
```
[error] 7033#7033: *1588 FastCGI sent in stderr: "PHP message: PHP Notice:  Undefined index: HTTP_X_FORWARDED_SERVER in /config/www/Dashboard/api/functions/organizr-functions.php on line 1694" while reading response header from upstream, client: 192.168.0.248, server: _, request: "GET /sonarr/Content/FontAwesome/fontawesome-webfont.woff?v=4.3.0 HTTP/1.1", subrequest: "/api/index.php", upstream: "fastcgi://unix:/var/run/php7-fpm.sock:", host: "192.168.0.104", referrer: "http://192.168.0.104/sonarr/Content/theme.css?h=sqzuUTVnu77HE+yk2zqXQQ"
```

I've checked connection to sonar from inside of docker image and it is working. Also there is changed 'base' url on sonarr so path `/sonarr` is valid for accessing sonarr app directly.

For me it is like there is missing `isset` check in organizr-functions.php:1694 but maybe problem is deeper. I manually fixed this line and it seems to be working, but you know, after restarting docker my fix was removed.

<hr>

##### Reproduction Steps:

1. Install clear docker image, and go through first configuration
2. Install NGXConfigurer
3. Add sonarr tab with url address `/sonarr`
4. Configure NGXConfigurer plugin to proxy to http://localhost:8989/sonarr
5. Click 'Write Config' in 'Actions' tab of NGXConfigurer plugin
6. Add proper `import` statement in `/config/nginx/site-confs/default`
7. Restart docker/reload configuration of nginx
8. Try to access http://organizrhost/sonarr
<hr>

#### Errors on screen?  If so paste here:

```

```

**Comment by Roxedus** [comment]
Already fixed in develop https://github.com/causefx/Organizr/commit/a9397c53dc0c008dc14f72d1b7406b11a2f5ba51
