### ISSUE TITLE
organizr does not have permissions to download the update

### ISSUE THREAD

**Issue by mikelagase** [causefx/Organizr#1332]
Running Organizr V2 version 2.0.320 on Synology and trying to perform an update of the app and I am getting "organizr does not have permissions to download the update". I went to /web and made sure that http had RW permissions on the organizr, db and web_images folder and still get the same error.

Where do I need to update permissions for this update to download and update successfully?

Mike

**Comment by HalianElf** [comment]
It downloads to the parent directory of where the Organizr files live.

**Comment by causefx** [comment]
If you goto Settings > About and click `Organizr Paths` you can see the folders

![image](https://user-images.githubusercontent.com/16184466/77715428-d0fa5400-6f98-11ea-8691-8447154b30ef.png)

**Comment by mikelagase** [comment]
That worked!! the root did not have correct permissions for http. Added write access and the update was successful. 

Much appreciated!!
