### ISSUE TITLE
Fix hardcoded limit on new tautulli module

### ISSUE THREAD

**Issue by G4Zz0L1** [causefx/Organizr#1341]
https://github.com/causefx/Organizr/blob/d2685cc64948c665279af67369e0adebf9e43164/js/functions.js#L6617

This row shoud change to:

```js
for(var i = 0; i < Math.min(5, e['rows'].length); i++) {
```

When there are less than 5 users on that report, the js breaks on that for.

**Comment by G4Zz0L1** [comment]
Another thing I've noticed, but I can't resolve now, it's the image url.

![image](https://user-images.githubusercontent.com/13220636/77895565-42772280-7277-11ea-929f-eee025ec401f.png)

I've put organizr in a custom url (like 'myserver.com/organizr') and the image doesn't get the correct url for the thumbs. It should take `/organizr/plugins/images/cache/` like the plex one does here, but instead it's `/plugins/images/cache/` and I can't get it to work.

https://github.com/causefx/Organizr/blob/e9c77f50e3340d188b59756f8dab338bf230ea56/api/functions/homepage-connect-functions.php#L372
https://github.com/causefx/Organizr/blob/e9c77f50e3340d188b59756f8dab338bf230ea56/api/functions/homepage-connect-functions.php#L532

**Comment by causefx** [comment]
the image url should be fixed now - please test

**Comment by G4Zz0L1** [comment]
Nope, it does the same thing.

![image](https://user-images.githubusercontent.com/13220636/77932026-39a14380-72ad-11ea-8109-3526b0171401.png)

**Comment by causefx** [comment]
my bad - forgot the hardcoded ones thanks!

**Comment by G4Zz0L1** [comment]
Perfect, now it works! Thanks a lot!
