### ISSUE TITLE
[Feature Request] Anyway to get SSO auth working with Synclounge

### ISSUE THREAD

**Issue by Cookie-Monster-Coder** [causefx/Organizr#1344]
https://github.com/samcm/synclounge#authentication

**Comment by Roxedus** [comment]
SSO currently works as long as you use the subfolder method, because it reads the same token Org sets for plex SSO.

Mentioning this for tracking purposes samcm/synclounge#168 (You should have done this)

**Comment by Cookie-Monster-Coder** [comment]
> Mentioning this for tracking purposes samcm/synclounge#168 (You should have done this)

Thanks for this! Still, kinda new to Github, so still learning.

> subfolder method

If you dont mind me asking, what's the subfolder method?

**Comment by Roxedus** [comment]
Running Synclounge with a webroot, rather than a subdomain.

**Comment by MagicalCodeMonkey** [comment]
PR https://github.com/samcm/synclounge/pull/169 made to update this on the SyncLounge side

**Comment by Cookie-Monster-Coder** [comment]
> Running Synclounge with a webroot, rather than a subdomain.

Ah, that makes sense. I was connecting directly to my servers IP to test things and didn't realize that all I had to do was edit my Nginx config and use my domain URL and everything would be good.

> PR samcm/synclounge#169 made to update this on the SyncLounge side

Thank you kind sir for adding subdomain support!
