### ISSUE TITLE
plex authentication not working

### ISSUE THREAD

**Issue by binyaminyblatt** [causefx/Organizr#1355]
###### Operating System: Windows
<hr>
![f](https://user-images.githubusercontent.com/15576348/78564089-9e681b00-7824-11ea-835f-8bc8bed5579c.PNG)

##### Problem Description:

i cant login 

this is from the chrome console
__________________________________________________________________________

chunk-0-36bd9bb5225e….31.0-b4fce07.js:41 Uncaught Error: Unexpected message received from: https://app.plex.tv for iFrameResizer0. Message was: [iFrameSizer]iFrameResizer0:0:410:init. This error can be disabled by setting the checkOrigin: false option or by providing of array of trusted domains.
    at chunk-0-36bd9bb5225e….31.0-b4fce07.js:41
    at C (chunk-0-36bd9bb5225e….31.0-b4fce07.js:41)
chunk-0-36bd9bb5225e….31.0-b4fce07.js:41 Uncaught Error: Unexpected message received from: https://app.plex.tv for iFrameResizer0. Message was: [iFrameSizer]iFrameResizer0:265:410:mutationObserver. This error can be disabled by setting the checkOrigin: false option or by providing of array of trusted domains.
    at chunk-0-36bd9bb5225e….31.0-b4fce07.js:41
    at C (chunk-0-36bd9bb5225e….31.0-b4fce07.js:41)
chunk-0-36bd9bb5225e….31.0-b4fce07.js:41 Uncaught Error: Unexpected message received from: https://app.plex.tv for iFrameResizer0. Message was: [iFrameSizer]iFrameResizer0:331:410:mutationObserver. This error can be disabled by setting the checkOrigin: false option or by providing of array of trusted domains.
    at chunk-0-36bd9bb5225e….31.0-b4fce07.js:41
    at C (chunk-0-36bd9bb5225e….31.0-b4fce07.js:41)
chunk-0-36bd9bb5225e….31.0-b4fce07.js:41 Uncaught Error: Unexpected message received from: https://app.plex.tv for iFrameResizer0. Message was: [iFrameSizer]iFrameResizer0:339:410:mutationObserver. This error can be disabled by setting the checkOrigin: false option or by providing of array of trusted domains.
    at chunk-0-36bd9bb5225e….31.0-b4fce07.js:41
    at C (chunk-0-36bd9bb5225e….31.0-b4fce07.js:41)
chunk-0-36bd9bb5225e….31.0-b4fce07.js:41 Uncaught Error: Unexpected message received from: https://app.plex.tv for iFrameResizer0. Message was: [iFrameSizer]iFrameResizer0:347:410:mutationObserver. This error can be disabled by setting the checkOrigin: false option or by providing of array of trusted domains.
    at chunk-0-36bd9bb5225e….31.0-b4fce07.js:41
    at C (chunk-0-36bd9bb5225e….31.0-b4fce07.js:41)
chunk-0-36bd9bb5225e….31.0-b4fce07.js:41 Uncaught Error: Unexpected message received from: https://app.plex.tv for iFrameResizer0. Message was: [iFrameSizer]iFrameResizer0:355:410:mutationObserver. This error can be disabled by setting the checkOrigin: false option or by providing of array of trusted domains.
    at chunk-0-36bd9bb5225e….31.0-b4fce07.js:41
    at C (chunk-0-36bd9bb5225e….31.0-b4fce07.js:41)
chunk-0-36bd9bb5225e….31.0-b4fce07.js:41 Uncaught Error: Unexpected message received from: https://app.plex.tv for iFrameResizer0. Message was: [iFrameSizer]iFrameResizer0:363:410:mutationObserver. This error can be disabled by setting the checkOrigin: false option or by providing of array of trusted domains.
    at chunk-0-36bd9bb5225e….31.0-b4fce07.js:41
    at C (chunk-0-36bd9bb5225e….31.0-b4fce07.js:41)
chunk-0-36bd9bb5225e….31.0-b4fce07.js:41 Uncaught Error: Unexpected message received from: https://app.plex.tv for iFrameResizer0. Message was: [iFrameSizer]iFrameResizer0:371:410:mutationObserver. This error can be disabled by setting the checkOrigin: false option or by providing of array of trusted domains.
    at chunk-0-36bd9bb5225e….31.0-b4fce07.js:41
    at C (chunk-0-36bd9bb5225e….31.0-b4fce07.js:41)
chunk-0-36bd9bb5225e….31.0-b4fce07.js:41 Uncaught Error: Unexpected message received from: https://app.plex.tv for iFrameResizer0. Message was: [iFrameSizer]iFrameResizer0:379:410:mutationObserver. This error can be disabled by setting the checkOrigin: false option or by providing of array of trusted domains.
    at chunk-0-36bd9bb5225e….31.0-b4fce07.js:41
    at C (chunk-0-36bd9bb5225e….31.0-b4fce07.js:41)
/auth/#!?clientID=3o…pd9v5hctmrbcvit96:1 Unchecked runtime.lastError: The message port closed before a response was received.
2
/auth-form/#!?client…pd9v5hctmrbcvit96:1 Unchecked runtime.lastError: The message port closed before a response was received.
/auth/#!?clientID=3o…pd9v5hctmrbcvit96:1 Unchecked runtime.lastError: The message port closed before a response was received.

**Comment by tronyx** [comment]
You provided zero information for this issue. Organizr v1, if that is the version you're running, is no longer supported or developed.

**Comment by binyaminyblatt** [comment]
sorry i pressed enter before i edited it refresh the page i edited it

**Comment by tronyx** [comment]
Ok, but what can't you log in to? Organizr or Plex? The image you linked is the Plex loading screen.

**Comment by Roxedus** [comment]
Could you also edit your issue with the version number of organizr?

**Comment by binyaminyblatt** [comment]
plex but it says its becose  of an iframe

**Comment by tronyx** [comment]
So you created a Plex tab in Organizr and have `app.plex.tv` as the Tab URL? Is that correct? If so, that will not work as they block iFraming, which is what Organizr tabs do.

**Comment by binyaminyblatt** [comment]
you want to see ill give u the url and pass

**Comment by tronyx** [comment]
No, I want you to answer my questions from my last comment.

**Comment by binyaminyblatt** [comment]
no i have it to my url and port

**Comment by tronyx** [comment]
Ok, that ends up being the same thing and gets blocked. You will need to properly create a reverse proxy for your Plex Server and then use that as the URL for the Tab.

**Comment by binyaminyblatt** [comment]
i couldn't get it to work with app.plex.tv

**Comment by binyaminyblatt** [comment]
i have a proxy

**Comment by jonathanfinley** [comment]
Could you please post your reverse proxy (without any identifying domain information, I.E. domain.com vs binyaminyblatt.com)

Thank you.

**Comment by binyaminyblatt** [comment]
RewriteRule ^/plex/?$   /web/index.html   [R=301]
  ProxyPass /web/   https://127.0.0.1:32400/web/
  ProxyPassReverse /web/   https://127.0.0.1:32400/web/
  ProxyPass /photo/:/  https://127.0.0.1:32400/photo/:/
  ProxyPassReverse /photo/:/  https://127.0.0.1:32400/photo/:/
  ProxyPass /:/websockets/  https://127.0.0.1:32400/:/websockets/
  ProxyPassReverse /:/websockets/  https://127.0.0.1:32400/:/websockets/
  ProxyPassMatch ^/(\w+-\w+-\w+-\w+-\w+)$ http://127.0.0.1:32400/$1
  RewriteCond %{REQUEST_URI}    !^/plexx
  RewriteCond %{HTTP:X-Plex-Product}   \w+
  RewriteRule .*     http://%{HTTP_HOST}/plexx%{REQUEST_URI}?%{QUERY_STRING} [NE,B]
  RewriteCond %{REQUEST_URI}  !^/plexx
  RewriteCond %{QUERY_STRING} X-Plex
  RewriteCond %{REQUEST_URI} !^/photo/:/
  RewriteRule .*  https://%{HTTP_HOST}/plexx%{REQUEST_URI}?%{QUERY_STRING} [NE,B]
  ProxyPass /plexx/ https://127.0.0.1:32400/
  ProxyPassReverse /  https://127.0.0.1:32400/
  ProxyPassReverseCookiePath /  /
  ProxyPass /media https://127.0.0.1:32400/media
  ProxyPassReverse /media  https://127.0.0.1:32400/media

**Comment by binyaminyblatt** [comment]
ssl as well

**Comment by Cookie-Monster-Coder** [comment]
Use this:

```
		location /plex {
    			proxy_pass https://localhost:32400;
			client_max_body_size 10m;
			client_body_buffer_size 128k;
			proxy_buffers 32 4k;
			#Timeout if the real server is dead
			proxy_next_upstream error timeout invalid_header http_500 http_502 http_503;
			# Advanced Proxy Config
			send_timeout 5m;
			proxy_read_timeout 240;
			proxy_send_timeout 240;
			proxy_connect_timeout 240;
			proxy_hide_header X-Frame-Options;
			# Basic Proxy Config
			proxy_set_header Host $host:$server_port;
			add_header X-Frame-Options "SAMEORIGIN";
			proxy_set_header X-Real-IP $remote_addr;
			proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
			proxy_set_header X-Forwarded-Proto https;
			proxy_redirect  http://  $scheme://;
			proxy_http_version 1.1;
			proxy_set_header Connection "";
			proxy_set_header Upgrade $http_upgrade;
			proxy_set_header Connection "upgrade";
			}
		}
```

**Comment by causefx** [comment]
he's using apache not nginx.  @binyaminyblatt not sure any of use can help...  we all use nginx.
