### ISSUE TITLE
Jquery error when attempting to change Authentication Type.

### ISSUE THREAD

**Issue by crunchysoft** [causefx/Organizr#1356]
###### Operating System: Linux
![Organizr_jquery_error](https://user-images.githubusercontent.com/305710/79009679-16d52180-7b2e-11ea-809c-f55f49919bb9.png)
![Organizr_jquery_error2](https://user-images.githubusercontent.com/305710/79009777-5439af00-7b2e-11ea-9381-051bb45a544f.png)

<hr>

##### Problem Description:
I am unable to change the Authentication setup for my Organizr install.

When attempting to make changes, the Save button 'bounces' as it normally does, but nothing happens when clicking it.
Checking the Console output, there is this error related to jquery in the background:

> Uncaught TypeError: Cannot use 'in' operator to search for 'length' in allow-presentation

This is the jquery function that throws the error:

```
    function s(a) {
        var b = !!a && "length"in a && a.length
          , c = n.type(a);
        return "function" === c || n.isWindow(a) ? !1 : "array" === c || 0 === b || "number" == typeof b && b > 0 && b - 1 in a
    }
```

<hr>

##### Reproduction Steps:

I am attempting to enabled Oraganize DB + Backend authentication with Plex.
Make changes in this section:
Settings > System Settings > Main > Authentication
Click "Save", and nothing happens.

<hr>

#### Errors on screen?  If so paste here:

```
jquery-2.2.4.min.js:formatted:213 Uncaught TypeError: Cannot use 'in' operator to search for 'length' in allow-presentation
    at s (jquery-2.2.4.min.js:formatted:213)
    at Function.each (jquery-2.2.4.min.js:formatted:146)
    at String.<anonymous> (functions.js?v=2.0.408:3042)
    at Function.each (jquery-2.2.4.min.js:formatted:148)
    at getSubmitSettingsFormValueObject (functions.js?v=2.0.408:3039)
    at Array.<anonymous> (functions.js?v=2.0.408:3074)
    at Function.each (jquery-2.2.4.min.js:formatted:152)
    at submitSettingsForm (functions.js?v=2.0.408:3071)
    at HTMLButtonElement.onclick (VM164 :1)
```

**Comment by causefx** [comment]
Good catch!!!  I redid the settings save function and it broke a few things - I thought I caught them all - guess not.  I will fix.

**Comment by causefx** [comment]
Once again, good fucking catch!  

fixed in dev.

**Comment by crunchysoft** [comment]
That was the fastest response and fix I've ever seen! haha
When will that be released in dev update?

**Comment by causefx** [comment]
how do you have it installed? native or docker?

**Comment by crunchysoft** [comment]
Native.
Well, a qpkg on QNAP NAS. But I've updated it through the app since it was installed.

**Comment by causefx** [comment]
goto settings where branch is and click force install branch. then clear your cache.

**Comment by crunchysoft** [comment]
Did that. Will the version change?
I still get the same jquery error as before, even in incognito mode.
Doesn't look like the Force Install Branch update worked for me.

**Comment by causefx** [comment]
no version change atm...

open up /js/functions.php look at line # 3074

can you paste that here?  Also, is your site setup with cloudflare or something similar?

**Comment by crunchysoft** [comment]
Scratch that. I killed my browser, and restarted it.
Now it works perfectly!

**Comment by causefx** [comment]
nice!

**Comment by crunchysoft** [comment]
Thanks again!!
