### ISSUE TITLE
Unable to run docker image on Raspberry Pi

### ISSUE THREAD

**Issue by Riiskyy** [causefx/Organizr#1362]
###### Operating System: Windows/MacOS/Ubuntu
<hr>

##### Problem Description:

I'm trying to run the docker image on my Raspberry Pi but it fails to start the container with the error:
` standard_init_linux.go:211: exec user process caused "exec format error"`

Looking online this usually indicates that the docker image is not built for the Pi. Would it be possible to get an RPi compatible image?
<hr>

##### Reproduction Steps:

Run docker container on RPi using the docker config in the installation guide.
<hr>

**Comment by tronyx** [comment]
You specified v1.x, which is no longer supported and we do not provide a Docker image for it. Are you actually using v1? What image did you use?

Our documentation, linked from the GitHub repo, shows the available tags for use, including one specific for the Raspberry Pi:

https://docs.organizr.app/books/installation/page/docker

**Comment by Riiskyy** [comment]
Hi sorry, I was trying the latest docker image pulled from dockerhub. The one linked in the readme page, thanks for the link i did not see those tags, I'll give that a try. Thanks

**Comment by Riiskyy** [comment]
Working now, closing.
