### ISSUE TITLE
Ombi SSO errors

### ISSUE THREAD

**Issue by dazw86** [causefx/Organizr#1364]
###### Operating System: Windows
<hr>

##### Problem Description:

When I log into Organizr with Plex SSO, I am unable to request new media from Ombi on the homepage. It appears to be an Ombi SOO issue as when I run the debug command it says cookie: false.
On the homepage, the search icon for Ombi does not show (which used to when I could request). I am also using the custom bottoms, which do show but when I try to request through here it errors with 'Not Org fault - ask Ombi'.

I know that is obvious it is not an org error but wondered if anyone knew how I could resolve?

- Ombi URL and API key in org settings is correct and when I open Ombi as a tab it opens fine
- When I view the login logs in org, it says Ombi token received
- In Ombi all users are Plex users
- In Ombi 'Import Plex Users and Admin' is enabled
- I have followed the SSO steps in the wiki

<hr>

##### Reproduction Steps:

Log into Organizr, view homepage, request new media
<hr>

#### Errors on screen?  If so paste here:

```
cookie: false.
Not Org fault - ask Ombi
```

**Comment by dazw86** [comment]
UPDATE: I re-installed Ombi today and so far so good. Will continue to monitor. :-)

**Comment by Roxedus** [comment]
Closing due to no negative response :)
