### ISSUE TITLE
Curl error 60 SSL

### ISSUE THREAD

**Issue by titi69lpb** [causefx/Organizr#1365]
###### Operating System: Linux VPS
<hr>

##### Problem Description:

Hi everyone, sorry to bother you, it's not an Organizr problem really but i'm stuck.

I run Organizr remotely on a Gandi instant, and it run smooth.
But i have some erros like this one :
Error: cURL error 60: SSL certificate problem: unable to get local issuer certificate

when Organizr try to connect locally hosted app like pihole, sonarr, tautulli etc
All app have a valid ssl certificat generated by Let's Encrypt.
All local app run on a windows server 2016 with nginx as proxy.
When i accesed all the app throught my browser everything is fine and work included ssl certificats handled by nginx.

<hr>

#### Errors on screen?  If so paste here:

```
Error: cURL error 60: SSL certificate problem: unable to get local issuer certificate
```

**Comment by causefx** [comment]
cant you check folder /api/config/cert ? what are the contents?

**Comment by titi69lpb** [comment]
Hi, thanks for the reply, there is no folder name cert :/
![image](https://user-images.githubusercontent.com/33924786/79896038-1ed37200-8408-11ea-9572-d78cfacaeade.png)

**Comment by titi69lpb** [comment]
i have the folder in "functions" 
![image](https://user-images.githubusercontent.com/33924786/79896519-c650a480-8408-11ea-8c15-85fd28d3ee88.png)

**Comment by causefx** [comment]
can you please list the contents.

**Comment by titi69lpb** [comment]
the content is just under on the screen

cacert-initial.pem
cacert.pem
index.html

**Comment by causefx** [comment]
You can try updating the cacert.pem file... 
https://curl.haxx.se/docs/caextract.html

**Comment by titi69lpb** [comment]
Done but same error. I don't think it's organizr the problem like a said but my local nginx said a wrong param for the cert when responding to Organizr :/
The part i don't understand is , when i navigate to all mudules hosted locally with https i don't have any problem with ssl :/

**Comment by titi69lpb** [comment]
Hi, i finally found the problem !

It's not organizr problem like i think, but thank you very much for helping !

For info, the problem was my acme client for ssl cert do not concatenate the chain cert inside the crt file generated beside the key of course. That was the problem of the chain error ! THANKS A LOT
