### ISSUE TITLE
ical results from exchange fail to parse

### ISSUE THREAD

**Issue by doug-w** [causefx/Organizr#1366]
###### Operating System: Ubuntu
<hr>

##### Problem Description:

ical results from exchange fail to parse.

Outlook / Exchange can use some non-standard Timezone names that causes Organizr to throw an unhandled exception and not render and dates.  In particular Instead of America/Los_Angeles the TZ is set as 'Pacific Standard Time'

<hr>

##### Reproduction Steps:

Create a calendar in outlook.com.  
Set some meetings with time in local time zone set.  
Import the iCal into organizr.
<hr>

#### Errors on screen?  If so paste here:

```
Stack trace:
#0 /config/www/Dashboard/api/functions/homepage-connect-functions.php(1383): DateTimeZone->__construct('Pacific Standar...')
#1 /config/www/Dashboard/api/functions/homepage-connect-functions.php(52): getCalendar()
#2 /config/www/Dashboard/api/index.php(364): homepageConnect(Array)
#3 {main}
  thrown in /config/www/Dashboard/api/functions/homepage-connect-functions.php on line 1383" while reading response header from upstream, client: 172.19.0.1, server: _, request: "POST /api/?v1/homepage/connect HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "organizr", referrer: "https://organizr"
```

**Comment by causefx** [comment]
seems like this wasn't closed when fixed
