### ISSUE TITLE
Unable to use same tab image on multiple tab adds without selecting different image first

### ISSUE THREAD

**Issue by doug-w** [causefx/Organizr#1369]
###### Organizr Version: V 2.0.408
######Branch: v2-master
######WebServer: Nginx
######Operating System: Ubuntu
<hr>

##### Problem Description:

If you select a make a new tab and select an image for it, after you save it the next new image has that image populated in **Choose Image** but not in  **Tab Image** if you wish to reuse it you need to select the drop down, choose a _different image_ then choose the original image again.

<hr>

##### Reproduction Steps:

Create and save new tab using custom1.png
Create second tab, observe Custom1.png is in Choose image but Tab Image is blank.
Attempt to save, save fails for Tab Image being empty.
Attempt to select Custom1.png from Choose Image picker, observe that it has no effect due to already being selected.

<hr>

#### Errors on screen?  If so paste here:

```
New Tab Error.
Please select a Tab Image.
```

**Comment by causefx** [comment]
fixed in dev - push to master tomorrow.
