### ISSUE TITLE
Automated install taking approx 10 minutes to start working

### ISSUE THREAD

**Issue by flying-sausages** [causefx/Organizr#1370]
###### Operating System: Ubuntu 18.04 LTS (Fresh Multipass VM)
<hr>

##### Problem Description:
I am attempting to integrate Organizr installation into Swizzin, and as part of that install script I'd like to complete the setup wizard from with some values automatically.
The curl calls return success JSONs like the one below. However, after this is done, it takes around 10 minutes for the application to actually let me through to the dashboard.
When I log in, I get a green "Login succesful" and I can see a cookie has been stored, but the UI stays on the login page.

<hr>

##### Reproduction Steps:
The PR with the code that is running is here https://github.com/liaralabs/swizzin/pull/295/files#diff-2f4d281154780ada3b9184c8b3aa70e2R26

If you'd like to attempt the swizzin install the way it is going right now in your VM, you can try this:
```bash
git clone git@github.com:flying-sausages/swizzin.git
cd swizzin
git checkout organizr
sudo -H bash setup.sh   ##Create a user only, do not install any apps
sudo rm -rf /etc/swizzin
sudo ln -sr ./ /etc/swizzin
box install nginx organizr
```
The log is store in /root/logs/swizzin.ltd

There is an nginx config installed with this that works with the basic http auth as well, which is default behaviour

```nginx
location /organizr {
  alias /srv/organizr;
  auth_basic "What's the password?";
  auth_basic_user_file /etc/htpasswd;

  location ~ \.php$ {
    include snippets/fastcgi-php.conf;
    fastcgi_pass unix:/run/php/$sock.sock;
    fastcgi_param SCRIPT_FILENAME /srv\$fastcgi_script_name;
  }
}
```

For quick reference, here is the code that is doing the curl (thanks again rodex!)
```bash
curl --location --request POST 'https://localhost/organizr/api/?v1/wizard_path' \
--header 'content-type: application/x-www-form-urlencoded' \
--header 'charset: UTF-8' \
--header 'Content-Encoding: gzip' \
--header 'Content-Type: application/x-www-form-urlencoded' \
--data-urlencode 'data[path]=/srv/organizr_db' \
--data-urlencode 'data[formKey]=' \
-sk --user "$user":"$pass" \
| python -m json.tool >> $log 2>&1
sleep 2

    # pass="$(head /dev/urandom | tr -dc A-Za-z0-9 | head -c16)"

api_key="$(head /dev/urandom | tr -dc A-Za-z0-9 | head -c16)"
hash_key="$(head /dev/urandom | tr -dc A-Za-z0-9 | head -c16)"
reg_pass="$(head /dev/urandom | tr -dc A-Za-z0-9 | head -c16)"

cat > /root/.organizr << EOF
API key = $api_key
Hash key = $hash_key
Registration pass = $reg_pass
EOF
#These are hardcoded for testing
#TODO check username and password are not the same
curl --location --request POST 'https://localhost/organizr/api/?v1/wizard_config' \
--header 'content-type: application/x-www-form-urlencoded' \
--header 'charset: UTF-8' \
--header 'Content-Encoding: gzip' \
--header 'Content-Type: application/x-www-form-urlencoded' \
--data-urlencode "data[0][name]=license" \
--data-urlencode "data[0][value]=personal" \
--data-urlencode "data[1][name]=username" \
--data-urlencode "data[1][value]=${user}" \
--data-urlencode "data[2][name]=email" \
--data-urlencode "data[2][value]=root@localhost" \
--data-urlencode "data[3][name]=password" \
--data-urlencode "data[3][value]=${pass}" \
--data-urlencode "data[4][name]=hashKey" \
--data-urlencode "data[4][value]=${hash_key}" \
--data-urlencode "data[5][name]=registrationPassword" \
--data-urlencode "data[5][value]=${reg_pass}" \
--data-urlencode "data[6][name]=api" \
--data-urlencode "data[6][value]=${api_key}" \
--data-urlencode "data[7][name]=dbName" \
--data-urlencode "data[7][value]=db" \
--data-urlencode "data[8][name]=location" \
--data-urlencode "data[8][value]=/srv/organizr_db" \
-sk --user "$user":"$pass" \
| python -m json.tool \
>> $log 2>&1
```

<hr>

#### Errors on screen?  If so paste here:

Nothing in the PHP logs as far as I can see, the only thing I see is the following

![image](https://user-images.githubusercontent.com/23618693/80338253-5f3d5080-884b-11ea-8a76-d2aba5482a58.png)

And here is the valid JSON I get back

```json
{
    "data": true,
    "generationDate": "2020-04-27T05:50:07Z",
    "generationTime": "52.8ms",
    "params": {
        "data": {
            "formKey": "",
            "path": "/srv/organizr_db"
        }
    },
    "request": "v1/wizard_path",
    "status": "success",
    "statusText": "success"
}
{
    "data": true,
    "generationDate": "2020-04-27T05:50:09Z",
    "generationTime": "273.9ms",
    "params": {
        "data": [
            {
                "name": "license",
                "value": "personal"
            },
            {
                "name": "username",
                "value": "test"
            },
            {
                "name": "email",
                "value": "root@localhost"
            },
            {
                "name": "password",
                "value": "test123"
            },
            {
                "name": "hashKey",
                "value": "Q8xvBeWE0QrkYDxf"
            },
            {
                "name": "registrationPassword",
                "value": "nZApsfo7uzxpMojE"
            },
            {
                "name": "api",
                "value": "tjECjkvTfzbdmmXy"
            },
            {
                "name": "dbName",
                "value": "db"
            },
            {
                "name": "location",
                "value": "/srv/organizr_db"
            }
        ]
    },
    "request": "v1/wizard_config",
    "status": "success",
    "statusText": "success"
}
```

**Comment by flying-sausages** [comment]
To sum up what we've found out while chatting and testing in private:
We don't have a clue what's happening. But we know it's something to do with the way the swizzin environment is set up. It's not the CURLs, as they are working against CauseFX's Pi's just fine when we tested them.

Changing the pool's `pm` to `ondemand` and increasing number of children doesn't seem to fix it.
The cookies that are given by organizr in the blocked timeframe are valid when checked against the API, and give all the info they should.

The thing that fixes it while it's in this "blocked" window, is restarting php-fpm. However, this restart needs to come from the command line and not from the install script. I'm not sure why that matters but it does.

I've had success with firefox by force-clearing cookies around 10 times, however it is possible this has forced the PHP to activate something on its own end to resolve this.

I tried with a browser I just downloaded from the internet called Epiphany (not the game) and I get the same results as in Chrome there: blocked from entering but with "login succesful" message and a cookie.

Liara mentioned this could be something with OPcache settings, and that will be the next thing I'll be looking into.

**Comment by flying-sausages** [comment]
So I was able to isolate this to "something with our PHP-FPM installation". Basically, triggering an opcache refresh from the terminal, or triggering a php-fpm reload works but only from the context of the terminal, not from the script.

I've been doing the same thing with installing nextcloud and it works quite alright there, so I'm not sure why this only happens with organizr and our FPM+opcache setup.

**Comment by flying-sausages** [comment]
Hey again, I've got some updates. So OPcache seems to cache the `config.php` file

```
root@exultant-mink:/srv# bash /etc/swizzin/scripts/php-fpm-cli -r "echo print_r(opcache_get_status());" | grep config.php -B1 -A7

            [/srv/organizr/api/config/config.php] => Array
                (
                    [full_path] => /srv/organizr/api/config/config.php
                    [hits] => 6
                    [memory_consumption] => 1000
                    [last_used] => Thu Jul  2 18:02:18 2020
                    [last_used_timestamp] => 1593709338
                    [timestamp] => 1593709183
                )
```

I just blacklisted the organizr `api/config` dir with this little thing and it works now.
```bash
$phpv=7.4 #internally set to right version
blacklist_path="/etc/php/$phpv/opcache-blacklist.txt"

if [[ ! -f $blacklist_path ]]; then 
  touch "$blacklist_path"
fi
echo "/srv/organizr/api/config/*" >> "$blacklist_path"
echo "opcache.blacklist_filename=$blacklist_path" >> /etc/php/$phpv/fpm/php.ini

reload_php_fpm #internal function to reload the right php-fpm instance
```
After running this, and checking the status of the opcache, the file is gone, and the setup works as intended.

**Comment by causefx** [comment]
oh snap. good find man. congrats!

**Comment by flying-sausages** [comment]
@Liara from Swizzin also found out you can run this at the end of our install script to trigger the creation of the UUID and clearing the opcache afterwards, instead of just blindly black-listing the opcache for the whole thing. the config.php gets cached when the index.php gets loaded, and doesn't then have the UUID if i understand correctly.

```bash
sleep 10
curl -k https://127.0.0.1/organizr/api/functions.php
. /etc/swizzin/sources/functions/php
reload_php_opcache
```
It would be nice if the UUID was generated when the actual `wizard_config` POST is being done, this would prevent the issues we were having.
