### ISSUE TITLE
Plex Theme - bug with images containing "ombi" in the file name.

### ISSUE THREAD

**Issue by crunchysoft** [causefx/Organizr#1372]
###### Operating System: Linux
<hr>

##### Problem Description:

The Plex theme has a bug that causes any image, with "ombi" in the name, to be replaced on the Tab page with a generic one.
This issue is not present in the default Organizr theme.
<hr>

##### Reproduction Steps:

I've created my own image, and it gets the same background (which is what shows in the tabs on the left).
If I take "ombi" out of the .png file name, then it works normally.
<hr>

#### Errors on screen?  If so paste here:

```

```
![ombi-default-theme](https://user-images.githubusercontent.com/305710/80617180-c86dc100-8a0f-11ea-9c61-f9944b804885.png)
![ombi-plex-theme](https://user-images.githubusercontent.com/305710/80617182-c86dc100-8a0f-11ea-98cf-cdbc09191e4f.png)

**Comment by Roxedus** [comment]
Let the author of the theme himself know. https://github.com/Burry/Organizr-Plex-Theme
