### ISSUE TITLE
Refused to frame qbittorrent

### ISSUE THREAD

**Issue by ottodoesntknow** [causefx/Organizr#1378]
###### Operating System: Ubuntu (Docker)
<hr>

##### Problem Description:

Trying to add a tab for qbittorrent but it just shows a blank page and drops "Refused to frame 'http://xxx.xxx.x.xx:8080/' because an ancestor violates the following Content Security Policy directive: "frame-ancestors 'self'"" on the console.
<hr>

##### Reproduction Steps:

No https or proxy. Just added a tab for qbittorrent with url http://xxx.xxx.x.xx:8080/'. If I open the same url in the browser it works good.
<hr>

#### Errors on screen?  If so paste here:

```
xxx.xxx.x.xx refused the connection
```

**Comment by GilbN** [comment]
This is not an Organizr issue. Qbittorrent blocks iframes by default. I don't use it but you might be able to allow organizr in the qbit settings. If thats not possible you will need to reverse proxy it and remove the csp header. 

```nginx
proxy_hide_header   "x-webkit-csp";
proxy_hide_header   "content-security-policy";
``` 

You can reverse proxy something without it being accessible outside your network btw.

**Comment by ottodoesntknow** [comment]
Finally got it working messing around with qbit security settings. Keep up the good work with Organizr!
