### ISSUE TITLE
Error after setting db location

### ISSUE THREAD

**Issue by memnos** [causefx/Organizr#138]
Hello, 
i'm tring to install organizr.
But when i choose db location and i press save i have this error:
Fatal error: Uncaught PDOException: could not find driver in /var/www/html/Organizr/user.php:174 Stack trace: #0 /var/www/html/Organizr/user.php(174): PDO->__construct('sqlite:/var/www...') #1 /var/www/html/Organizr/index.php(169): User->__construct('registration_ca...') #2 {main} thrown in /var/www/html/Organizr/user.php on line 174

Maybe i miss same packeges installed?

I'm using ubuntu 16.04

Tnx

**Comment by causefx** [comment]
LINUX: Install PHP Sqlite in the CLI using the following:
PHP5 -> Run sudo apt-get install php5-sqlite
PHP7 -> Run sudo apt-get install php7.0-sqlite

**Comment by memnos** [comment]
I've got an errore installing  php5-qlite


# apt-get install php5-sqlite
Reading package lists... Done
Building dependency tree
Reading state information... Done
Package php5-sqlite is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'php5-sqlite' has no installation candidate

**Comment by causefx** [comment]
Is php5 installed or 7

**Comment by memnos** [comment]
php -v
PHP 5.6.30-7+deb.sury.org~xenial+1 (cli)
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies

**Comment by causefx** [comment]
https://launchpad.net/ubuntu/xenial/+package/php5-sqlite

It's right wtf lol. 

Can u do an apt-get update and then try again...

**Comment by causefx** [comment]
http://stackoverflow.com/questions/36788873/package-php5-have-no-installation-candidate-ubuntu-16-04

looks like 16.04 doesnt have php5 packages.... Mine came with php7

**Comment by memnos** [comment]
I don't understand how to install php5.
I tried with https://launchpad.net/ubuntu/xenial/+package/php5-sqlite
But the problem still remains

**Comment by causefx** [comment]
intall php7.0

**Comment by memnos** [comment]
I installed php7.0 but got the same error.
Any other hint?

**Comment by causefx** [comment]
now: sudo apt-get install php7.0-sqlite

**Comment by memnos** [comment]
Yes, i did also that, but nothing changed.

**Comment by causefx** [comment]
php -v ?

**Comment by memnos** [comment]
php -v
PHP 7.0.16-4+deb.sury.org~xenial+1 (cli) (built: Mar  2 2017 10:36:04) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.16-4+deb.sury.org~xenial+1, Copyright (c) 1999-2017, by Zend Technologies

**Comment by causefx** [comment]
restart nginx and php

**Comment by causefx** [comment]
the goto check.php

**Comment by memnos** [comment]
I haven't got nginx , but apache2.
Should i need nginx?

I restart apache2, but nothing changed.
How to restart php?

**Comment by causefx** [comment]
sudo service php-7.0-fpm restart

**Comment by memnos** [comment]
service php-7.0-fpm restart
php-7.0-fpm: unrecognized service

**Comment by causefx** [comment]
damn thats odd...type sudo service php then push tab to see what autofills

**Comment by memnos** [comment]
sudo service php <tab> st <tab>
start  stop

**Comment by causefx** [comment]
try that, php stop then php start

then goto check.php

**Comment by memnos** [comment]
DO you mean this with check.php?
Current PHP version: 5.6.30-7+deb.sury.org~xenial+1

**Comment by causefx** [comment]
on your broswer, i wrote a script to check persmissions and such.

**Comment by memnos** [comment]
This?



PHP Version 5.6.30-7+deb.sury.org~xenial+1

System	Linux fabioseed 4.4.0-66-generic #87-Ubuntu SMP Fri Mar 3 15:29:05 UTC 2017 x86_64
Server API	Apache 2.0 Handler
Virtual Directory Support	disabled
Configuration File (php.ini) Path	/etc/php/5.6/apache2
Loaded Configuration File	/etc/php/5.6/apache2/php.ini
Scan this dir for additional .ini files	/etc/php/5.6/apache2/conf.d
Additional .ini files parsed	/etc/php/5.6/apache2/conf.d/10-opcache.ini, /etc/php/5.6/apache2/conf.d/10-pdo.ini, /etc/php/5.6/apache2/conf.d/20-calendar.ini, /etc/php/5.6/apache2/conf.d/20-ctype.ini, /etc/php/5.6/apache2/conf.d/20-exif.ini, /etc/php/5.6/apache2/conf.d/20-fileinfo.ini, /etc/php/5.6/apache2/conf.d/20-ftp.ini, /etc/php/5.6/apache2/conf.d/20-gettext.ini, /etc/php/5.6/apache2/conf.d/20-iconv.ini, /etc/php/5.6/apache2/conf.d/20-json.ini, /etc/php/5.6/apache2/conf.d/20-phar.ini, /etc/php/5.6/apache2/conf.d/20-posix.ini, /etc/php/5.6/apache2/conf.d/20-readline.ini, /etc/php/5.6/apache2/conf.d/20-shmop.ini, /etc/php/5.6/apache2/conf.d/20-sockets.ini, /etc/php/5.6/apache2/conf.d/20-sysvmsg.ini, /etc/php/5.6/apache2/conf.d/20-sysvsem.ini, /etc/php/5.6/apache2/conf.d/20-sysvshm.ini, /etc/php/5.6/apache2/conf.d/20-tokenizer.ini
PHP API	20131106
PHP Extension	20131226
Zend Extension	220131226
Zend Extension Build	API220131226,NTS
PHP Extension Build	API20131226,NTS
Debug Build	no
Thread Safety	disabled
Zend Signal Handling	disabled
Zend Memory Manager	enabled
Zend Multibyte Support	disabled
IPv6 Support	enabled
DTrace Support	enabled
Registered PHP Streams	https, ftps, compress.zlib, php, file, glob, data, http, ftp, phar
Registered Stream Socket Transports	tcp, udp, unix, udg, ssl, sslv3, tls, tlsv1.0, tlsv1.1, tlsv1.2
Registered Stream Filters	zlib.*, string.rot13, string.toupper, string.tolower, string.strip_tags, convert.*, consumed, dechunk, convert.iconv.*

**Comment by causefx** [comment]
no sorry, goto your broswer, and goto where organizr is... then type in check.php instead of index.php. 

you should see this:
![image](https://cloud.githubusercontent.com/assets/16184466/23827477/8ad369f0-0671-11e7-9f7e-fb6f95fc12c4.png)

**Comment by memnos** [comment]
![immagine](https://cloud.githubusercontent.com/assets/25641404/23827499/69f901ba-06b5-11e7-9aa0-70c694068372.png)

**Comment by causefx** [comment]
i too have 16.04 and dont have these problems.

any way i can teamviewer in to help you?

**Comment by memnos** [comment]
Tnx for your help.
I have to go away from pc now, but if you will be available in another moment i'll run teamviewer.
I'll get back i think tomorrow or on monday.
tnx

**Comment by causefx** [comment]
ok
no problem

**Comment by memnos** [comment]
Which is the best hour for you to teamviwer me?
I see you are from us while im from europe.

**Comment by causefx** [comment]
any time is good, you can catch me the gitter chat room

**Comment by memnos** [comment]
What is the gitter chat room?

**Comment by causefx** [comment]
open organizr, goto settings then about page, click join chat

**Comment by bjay1404** [comment]
Looks like I have the same problem. On check.php with Apache on 16.04 I'm missing

PDO_SQLITE
PDO_SQLITE is NOT loaded! Please install it before proceeding
If you are on Windows, please uncomment this line in php.ini: ;extension=php_pdo_sqlite.dll

and this - which seems really strange. WHy does the entire html dir need to be writable?

/var/www/html is NOT writable! Please change the permissions to make it writtable by the PHP User.

**Comment by bjay1404** [comment]
Ah just needed a restart of Apache for the top one - the entire web root didn't go away. Could you explain why we need the entire web root writable?

**Comment by pyrostic** [comment]
I see this a lot, use a good text editor  and search for sqlite uncomment
all lines associated.  Then search for Ext and ensure you link to the ext
directory (usually "ext" is the sub directory) your DB is typically created
in the root directory, ensure you delete it before trying to set it up
again. I didn't get a chance to read through your entire thread so, I
recommend if you are windows to simply follow the wiki I wrote on Windows
install. Most of these errors are from a simple misunderstanding of
instruction etc.

**Comment by causefx** [comment]
the html folder is needed if you place the database there, you are more than welcome to place it in the same directory as organizr.
