### ISSUE TITLE
Special Characters in page title are removed

### ISSUE THREAD

**Issue by u2618** [causefx/Organizr#1381]
###### Operating System: FreeBSD
<hr>

##### Problem Description:

Special characters of the tab name are replaced in the title of the browser tab.

<hr>

##### Reproduction Steps:

* Add a new tab with a name containing a special character, e.g. "Übersicht" (german: overview)
* open the organizr-tab -> in the browser-tab title the special char is replaced by a minus, e.g. "-bersicht"

<hr>

#### Errors on screen?  If so paste here:

```

```
![organizr](https://user-images.githubusercontent.com/29153223/80858762-b6805e00-8c5b-11ea-9eda-c93269e08568.png)

**Comment by causefx** [comment]
seems i must have fixed this at some point as it works now :)
