### ISSUE TITLE
Feature Request: Generic OAuth2 or SAML authentication support

### ISSUE THREAD

**Issue by cobrafast** [causefx/Organizr#1382]
I would like to use Organizr in conjunction with [Keycloak](https://www.keycloak.org/) which only offers OpenID-Connect (OAuth2) or SAML for authentication, no LDAP/AD.

**Comment by Ryonez** [comment]
Exact same case I'm in. Using Keycloak, and wanting to use oauth.

**Comment by PhyberApex** [comment]
> Exact same case I'm in. Using Keycloak, and wanting to use oauth.

Just FYI you can use keycloak already with a reverse proxy and proxy auth. In case you didn't know.

**Comment by PhyberApex** [comment]
Sorry my bad. I wanted to actually quote @Ryonez with that comment just to let them know that keycloak (you are right only login) is already possible. 

~Cheers

**Comment by Ryonez** [comment]
> 
> 
> > Exact same case I'm in. Using Keycloak, and wanting to use oauth.
> 
> Just FYI you can use keycloak already with a reverse proxy and proxy auth. In case you didn't know.

Won't that disable guest access though? If I use gatekeeper (Keycloak's auth proxy) for this, it'll ask that you be signed in, meaning that guests can't use Organizr, which is important because this is meant to be the hub to all my various services.

**Comment by PhyberApex** [comment]
> > > Exact same case I'm in. Using Keycloak, and wanting to use oauth.
> > 
> > 
> > Just FYI you can use keycloak already with a reverse proxy and proxy auth. In case you didn't know.
> 
> Won't that disable guest access though? If I use gatekeeper (Keycloak's auth proxy) for this, it'll ask that you be signed in, meaning that guests can't use Organizr, which is important because this is meant to be the hub to all my various services.

Yes that is correct. A native integration for OAuth / openid-connect would be the best way for that.

~Cheers

**Comment by ghost** [comment]
@Ornias1993 @PhyberApex Is there currently any solution to this since native OAuth/openid-connect is not implementing? I have mailcow, seafile, and Organizr and want to tie all these together. Any suggestions to easily achieve this?

**Comment by ghost** [comment]
> 
> 
> Besides a reverse proxy and header authentication, there is nothing integrated into Organizr itself and I personally stopped using it.
> You could look into Authelia for example.

Is there something like organizr that has oauth support native?

**Comment by causefx** [comment]
We are moving Feature Requests away from **GitHub** and **FeatHub**.  We are now on **_FeatureUpvote_** which is located here:
### **https://vote.organizr.app**
If will also be a tab in Organizr update this Friday 22 Jan 2021


If this Feature Request was already on FeatHub it will get moved over within the week - no further action is needed.
If not, please create a new Feature Request at our new home so we can better keep track of them.

**Comment by Ryonez** [comment]
Feature request for OAuth2 made here: 
https://vote.organizr.app/suggestions/150238/generic-oauth2-support

**Comment by rtest12** [comment]
I vote too

**Comment by wokawoka** [comment]
+1
