### ISSUE TITLE
Feature Request: Weather homepage in other language like French

### ISSUE THREAD

**Issue by EricG66** [causefx/Organizr#1386]
Organizr Version: V 2.0.570
Branch: Master / v2-develop
WebServer: Nginx
Operating System: Windows

Feature Request: Add the abilities to get the Weather homepage in other language like French:

**Comment by tronyx** [comment]
That item is brand new and actually still a WIP. Translations will most likely come once the design is finalized, at which time we will ask for help with translations.

**Comment by EricG66** [comment]
I can help for French translation, no problem !

**Comment by Roxedus** [comment]
@EricG66 That's great. Send me an email and I will add you. me(at)roxedus.dev

**Comment by Roxedus** [comment]
Invited to translate, however the weather strings are not inn yet. Waiting for @causefx on that one.
