### ISSUE TITLE
Can't login anymore

### ISSUE THREAD

**Issue by Sigri44** [causefx/Organizr#1387]
###### Operating System: Docker
<hr>

##### Problem Description:
```
2020/05/08 09:22:16 [error] 276#276: *31 FastCGI sent in stderr: "PHP message: PHP Warning:  gmdate() expects parameter 2 to be integer, float given in /config/www/Dashboard/api/functions/normal-functions.php on line 101
PHP message: PHP Warning:  gmdate() expects parameter 2 to be integer, float given in /config/www/Dashboard/api/functions/normal-functions.php on line 107
PHP message: PHP Warning:  gmdate() expects parameter 2 to be integer, float given in /config/www/Dashboard/api/functions/token-functions.php on line 92" while reading response header from upstream, client: 192.168.1.64, server: _, request: "POST /api/?v1/login HTTP/1.1"
```

<hr>

##### Reproduction Steps:
I don't remember a precise step, but possibly in link I modified via the web interface the cookies/login parts to 9999999999999 seconds because despite some options, I had to reconnect every hour, so I put all the parameters in link with very high values.

<hr>

**Comment by causefx** [comment]
for now just edit /api/config/config.php

make sure to change back to these values:
![image](https://user-images.githubusercontent.com/16184466/81419689-83c6e180-9103-11ea-9515-c55cf1c9f782.png)

**Comment by Sigri44** [comment]
Works fine, very thank you !! (I have put 9999 days directly)
