### ISSUE TITLE
Update to 2.0.570 stuck in loop

### ISSUE THREAD

**Issue by Strap1** [causefx/Organizr#1389]
###### Operating System: Ubuntu 18.04
<hr>

##### Problem Description:
Updating from 2.0.408 to 2.0.570 appears successful but then prompts the same update again. I've tried to perform the update several times but I keep coming back to the same thing: prompts for update, I run it, it appears successful then prompts again.
I even tried a fresh install (reupload of zip of v2-master and created new DB in the setup). That brought me to myurl.com/#Settings which was blank. On page reload I was prompted for the update again.
There are no errors in organizrLog.json nor in nginx error log.

Maybe my brain's gone and I'm missing something simple...

<hr>

##### Reproduction Steps:
Click Update. Wait.

<hr>
![image](https://user-images.githubusercontent.com/6105839/81482554-30a27b00-9238-11ea-9447-156f47a3a952.png)
#### Errors on screen?  If so paste here:

```


```

**Comment by Roxedus** [comment]
How about the php log?

**Comment by Strap1** [comment]
No errors or warnings there either.

Restarting php7.2-fpm service has fixed the issue (update applied successfully), which makes me lean towards maybe a caching issue, but I've not managed to pinpoint the exact cause.

**Comment by Roxedus** [comment]
Did you manage to get the update? If so, please close the issue.
