### ISSUE TITLE
duplicate homepage items for monitoring different servers

### ISSUE THREAD

**Issue by xsolinsx** [causefx/Organizr#1390]
![immagine](https://user-images.githubusercontent.com/16761752/81508784-880f1c80-9306-11ea-952f-5eee5348749b.png)

<hr>

##### Problem Description:
I have two servers on my network and I installed netdata in both of them, I wonder if there's any way I can duplicate the netdata homepage item, put both on the homepage and point them to the respective servers.
My problem is specific to the netdata item but it could also be applied to the other items as well

<hr>

##### Reproduction Steps:

<hr>

#### Errors on screen?  If so paste here:

```

```

**Comment by tronyx** [comment]
The only way to achieve this, at this time, is to manually display the data like has been done for a couple of years now before the Homepage Item was added:

https://technicalramblings.com/blog/spice-up-your-homepage/
https://technicalramblings.com/blog/spice-up-your-homepage-part-ii/
