### ISSUE TITLE
Login screen is a bit shy (runs off to the left)

### ISSUE THREAD

**Issue by ervee** [causefx/Organizr#1393]
##### Problem Description:
Hi, whenever I open the Organizr page on my Nokia 7.2 Andoid 10 phone the login part of the login page runs off left to the screen. I can then swipe it back so I can see it.

It is just a little GUI bug I guess.
<hr>

##### Reproduction Steps:
Log out.
Close the Chrome tab
Open new Chrome tab
Go to Organizr URL
<hr>

#### Errors on screen?  If so paste here:

```
Nope
```
![Screenshot_20200514-194827](https://user-images.githubusercontent.com/4435930/81968139-4808ac00-961c-11ea-8f38-5fa779f5ac35.jpg)

[MOV_0003_edit.zip](https://github.com/causefx/Organizr/files/4630087/MOV_0003_edit.zip)

**Comment by causefx** [comment]
Wow! that sucks... 

Unfortunately I am unable to test this on my end as I don't have a Nokia device.  Have you tried downloading a theme from the marketplace in org settings to test those as well?

I only have access to these on BrowserStack:
![image](https://user-images.githubusercontent.com/16184466/81969248-79f52080-95d2-11ea-98b5-8dafd9f632c1.png)

They have all passed as well...

**Comment by ervee** [comment]
Hi,

The Hotline and Plex theme I just tried and they seem to **not** run away on me :) So I'll stick with Plex because Hotline is just... not exactly my thing.

On the Blue and Organizr theme it keeps shifting too far to the left (to the left, to the left...). Dang I keep putting songs in my own head... Sorry...

The Plex theme just has no sweeping visuals, also not on the user dropdown thingy top right so there is probably something in the stock theme which annoys Chrome on my Nokia. Should have bought the new One Plus...

**Comment by causefx** [comment]
LOL :)

No worries...  If I am able to test down the road, I will nail it down.
