### ISSUE TITLE
how am i supposed to install this?

### ISSUE THREAD

**Issue by keijigo** [causefx/Organizr#1398]
###### Operating System: Windows
<hr>

##### Problem Description:
where's the exe? how do i install this? wtf is docker? where are the instructions? the website says it is "easy to install" your readme includes zero instructions or information on actually getting this thing to work wiki's empty is this actually a science experiment to see how to drive people insane?

<hr>

##### Reproduction Steps:

<hr>

#### Errors on screen?  If so paste here:

```

```

**Comment by Roxedus** [comment]
Here is the link to the Windows part of our installation guide, linked to from the wiki page on this repository. 
https://docs.organizr.app/books/installation/page/windows

**Comment by keijigo** [comment]
when i went to the wiki page from this respository it was just a blank wiki.

oh i see now you linked to a link
