### ISSUE TITLE
Improved username is already taken error

### ISSUE THREAD

**Issue by hucknz** [causefx/Organizr#1399]
###### Operating System: Ubuntu
<hr>

##### Problem Description:
The current "Invite error. Username error: Has already been taken." is too vague. It doesn't make it clear that usernames need to be unique across all of Plex. 

An improved message indicating that the issue lies with Plex would be more helpful. 

<hr>

##### Reproduction Steps:
Invite user with generic name, e.g. "test", and attempt to sign up. 

<hr>

#### Errors on screen?  If so paste here:

```

```

**Comment by causefx** [comment]
the error message comes directly from plex.
