### ISSUE TITLE
Translations not working

### ISSUE THREAD

**Issue by sloanja** [causefx/Organizr#140]
Essentially, this is a new install on CentOS 6.8, php 5.3.3.  I used the Linux unzip method as directed in the wiki.

All of the translations are not working.  Aside from the text, I have a blank white screen with no pictures.
Warning: syntax error, unexpected $end in lang/en.ini on line 171 in /path/to/translate.php on line 11 Translation not found for: LOGIN

![image](https://cloud.githubusercontent.com/assets/17954642/23827196/70373a52-0673-11e7-9e72-e0edf1c98605.png)

**Comment by sloanja** [comment]
Found issue for images not loading by looking at error_log.  It was showing for example:
"GET /%3C?=$baseURL;?%3Ebower_components/jquery/dist/jquery.min.js " with a 404. 
Obviously the php wasn't replacing the baseURL and was simply passing that in the html code.

Turns out 5.3.3 needs to have short_open_tag turned on (which is not checked by check.php).  Since PHP 5.4.0, <?= is always available.

Closing because i didn't see php 5.6 was required.

**Comment by causefx** [comment]
thank you for clearing that up :)
