### ISSUE TITLE
[feature request] different colors for different ical feeds

### ISSUE THREAD

**Issue by HypKin** [causefx/Organizr#1400]
can we overhaul the way that ical feeds are added to the calendar?

I'd like to have a way to choose a color for each ical feed that i've added.

past items could all have the same color but id like to be able to choose different colors for different feeds.

**Comment by causefx** [comment]
We are moving Feature Requests away from **GitHub** and **FeatHub**.  We are now on **_FeatureUpvote_** which is located here:
### **https://vote.organizr.app**
If will also be a tab in Organizr update this Friday 22 Jan 2021


If this Feature Request was already on FeatHub it will get moved over within the week - no further action is needed.
If not, please create a new Feature Request at our new home so we can better keep track of them.
