### ISSUE TITLE
OpenLDAP connection

### ISSUE THREAD

**Issue by jjsoueix** [causefx/Organizr#1401]
Organizr Version: V 2.0.570
Branch: Master
WebServer: Nginx/1.16.1
Operating System: FreeBSD
PHP version : 7.3.11

<hr>
##### Problem Description:
<hr>
I have a pb to connect Organizr to our openLdap.
I followed the doc, choose Organizr + backend method and setup as follow :

    host address : ldaps://X.X.X.X:636
    host base DN : dc=domain,dc=tld
    LDAP backend type : OpenLDAP
    Account prefix : uid=
    Account suffix : ,ou=users,dc=domain,dc=tld
    Bind username: uid=adminuser,dc=domain,dc=tld
    Password : *******************

The connection test failed with messages "Testing Now ..." and "Organizr Error".
I have tried with our active directory too and no pb.

**Comment by HalianElf** [comment]
Your Host Base DN is wrong. It should be the full DN of a user with `%s` plugged in for the username like it shows in the box and is stated on the [docs](https://docs.organizr.app/books/setup-features/page/ldap-authentication).
![image](https://user-images.githubusercontent.com/28244771/87229803-4d167d00-c379-11ea-9fcc-bd644154a726.png)

You also may need to drop the Bind Username/Password. Neither AD nor OpenLDAP needed it in my testing.

**Comment by HalianElf** [comment]
@Ornias1993 Well it's on the docs page, like I linked in the post above yours...
