### ISSUE TITLE
Homepage not loading items

### ISSUE THREAD

**Issue by natelandau** [causefx/Organizr#1402]
###### Reverse Proxy: Traefik v2.2 pointing to a subdomain
<hr>

##### Problem Description:
The homepage is blank and not loading any items.  The Console shows a number of 404s trying to find elements.  Specifically, these assets are not loading.  It was working for quite some time and a few weeks ago (wish I knew the exact date) it stopped loading.

```
https://subdomain.site.com/plugins/bower_components/calendar/dist/fullcalendar.js
https://subdomain.site.com/js/plyr.js.map
https://subdomain.site.com/js/tinycolor.min.map
```

All other assets are loading correctly.

<hr>

##### Reproduction Steps:
Start the Docker image
Configure and then load the homepage

<hr>

#### Errors on screen?  If so paste here:

In addition to the 404s noted above, the following error is thrown in console in `https://subdomain.site.com/js/jquery-2.2.4.min.js` function `globalEval`
```
TypeError: undefined is not a function (near '...$this.$calendar.fullCalendar...')
```

**Comment by Roxedus** [comment]
We have had a few reports of this lately. Any errors in the php and nginx error logs? `/config/log/nginx/error.log` or  `/config/log/php/error.log`

**Comment by natelandau** [comment]
both error logs are free of errors

**Comment by causefx** [comment]
can you try hitting the test api connection on the homepage items?

**Comment by natelandau** [comment]
Hitting the `Test Connection` button shows success for all the items

**Comment by causefx** [comment]
yeah with no error logs we really can debug what is happening...  unless you want to give us access to the organizr instance to check...

**Comment by shawnthompson** [comment]
I'm having this problem too

My error log showed 

```
var/run/php7-fpm.sock failed (2: No such file or directory) while connecting to upstream
```

I'm following the [Ultimate Docker Home Server with Traefik 2, LE, and OAuth / Authelia [2020]](https://www.smarthomebeginner.com/traefik-2-docker-tutorial/) guide.

**Comment by shawnthompson** [comment]
Now it works and I didn't do anything, maybe my issue was a caching with CloudFlare problem

**Comment by causefx** [comment]
glad you got it fixed. closing main issue due to inactivity
