### ISSUE TITLE
Monitorr homepage module not working

### ISSUE THREAD

**Issue by themeatsweats** [causefx/Organizr#1403]
###### Operating System: Docker on Ubuntu Server
<hr>

##### Problem Description:

Monitorr module does not appear on homepage when enabled. Browser console shows:
```
functions.js?v=95e8ac53e7b9cd13b91920751d8df59b8d40dea2:7184 Uncaught TypeError: Cannot read property 'titleToggle' of undefined
    at buildMonitorr (functions.js?v=95e8ac53e7b9cd13b91920751d8df59b8d40dea2:7184)
    at Object.<anonymous> (functions.js?v=95e8ac53e7b9cd13b91920751d8df59b8d40dea2:7215)
    at i (jquery-2.2.4.min.js:2)
    at Object.fireWith [as resolveWith] (jquery-2.2.4.min.js:2)
    at z (jquery-2.2.4.min.js:4)
    at XMLHttpRequest.<anonymous> (jquery-2.2.4.min.js:4)
```
`?v1/homepage/connect` network response tab shows:
```
{"request":"v1\/homepage\/connect","params":[],"status":"error","statusText":"The function requested is not defined for method: GET","generationDate":"2020-05-28T19:13:20Z","generationTime":"40.5ms"}
```

<hr>

##### Reproduction Steps:

Have tried restarting container, recreating container (with existing `/config`), toggling Title and all other module settings in the UI. 
I am using `monitorr/monitorr:latest` v1.7.6m
<hr>

#### Errors on screen?  If so paste here:

```
none
```

**Comment by themeatsweats** [comment]
Also tested with completely new instance and new config path. Same result

**Comment by henrywhitaker3** [comment]
This error doesn't actually have anything to do with the title settings of the homepage item. This happens when the request Organizr makes to Monitorr times out.

Monitorr doesn't have an API, so currently it uses regular expressions to get the status from `http://<Monitorr URL>/assets/php/loop.php` and if this takes more than 10 seconds to load, the request times out.

If you have loads of services configured in Monitorr, you could remove some to try and get that page to load faster. Or you can try to replicate Monitorr using [healthchecks](https://healthchecks.io).

**Comment by causefx** [comment]
we just need to wrap it in a try

**Comment by henrywhitaker3** [comment]
Already is in the PHP. Would just need to add an error field to the data array the function returns and then look for that error field in the JS.

**Comment by themeatsweats** [comment]
changed my config from the proxied duckdns address to localip:port and it seems to working fine now (even off of my network)

**Comment by henrywhitaker3** [comment]
Ah nice one. Yeah for homepage items you generally use local ip:port as the back-end fetches the data rather than your device

**Comment by YouveGotMeowxy** [comment]
I'm having the same issue.

I have the monitorr and Organizr containers in the same network, and then use `monitorr:80` as the Ip:port in the monitorr widget's settings.

I get this error now all the time:

> Monitorr error: cURL error 28: Operation timed out after 10006 milliseconds with 0 bytes received

If I log into the Organizer container's console and try pinging the monitorr container directly:

> PING monitorr (172.30.0.6): 56 data bytes
64 bytes from 172.30.0.6: seq=0 ttl=64 time=0.100 ms
64 bytes from 172.30.0.6: seq=1 ttl=64 time=0.102 ms
64 bytes from 172.30.0.6: seq=2 ttl=64 time=0.201 ms
64 bytes from 172.30.0.6: seq=3 ttl=64 time=0.089 ms
64 bytes from 172.30.0.6: seq=4 ttl=64 time=0.096 ms
64 bytes from 172.30.0.6: seq=5 ttl=64 time=0.079 ms
64 bytes from 172.30.0.6: seq=6 ttl=64 time=0.086 ms
64 bytes from 172.30.0.6: seq=7 ttl=64 time=0.074 ms
64 bytes from 172.30.0.6: seq=8 ttl=64 time=0.086 ms

The strange thing is, when I first added the monitorr widget it was loading the items on the homepage no problem, but out of nowhere without me making any changes whatsoever in monitorr or it's widget, I now get the timeout. :/

**Comment by causefx** [comment]
that is a timeout issue which was just fixed today.  will be in master tomorrow
