### ISSUE TITLE
stray / in index.php and js/functions.php

### ISSUE THREAD

**Issue by colmconn** [causefx/Organizr#1408]
###### Operating System: FreeBSD(freeNAS jail)
<hr>

##### Problem Description:

I have Orgainzr installed on https://dashboard.home.lan/OrganizrV2  rather than the server root. I noticed some errors in error.log about missing files. This turned out to be due to two stray /, one in each of index.php and js/functions.php. The attached patch fixes both issues.

```
--- index.php.orig      2020-06-09 10:38:41.068768235 -0400
+++ index.php   2020-05-21 12:36:22.206926797 -0400
@@ -287,7 +287,7 @@
 <script src="plugins/bower_components/mousetrap/mousetrap.min.js"></script>
 <script src="plugins/bower_components/bootstrap-treeview-master/dist/bootstrap-treeview.min.js"></script>
 <script src="plugins/bower_components/jquery.easy-pie-chart/dist/jquery.easypiechart.min.js"></script>
-<script src="/js/gauge.min.js"></script>
+<script src="js/gauge.min.js"></script>
 <script src="js/jquery.mousewheel.min.js"></script>
 <script src="js/ua-parser.min.js"></script>
 <script src="js/plyr.js"></script>
--- js/functions.js.orig        2020-06-09 10:38:49.508565422 -0400
+++ js/functions.js     2020-05-22 11:02:02.636459015 -0400
@@ -3731,7 +3731,7 @@
 }
 function allIcons() {
     return $.ajax({
-        url: "/js/icons.json",
+        url: "js/icons.json",
     });
 }
 function organizrConnect(path){

```

<hr>

##### Reproduction Steps:

<hr>

#### Errors on screen?  If so paste here:

```

```

**Comment by causefx** [comment]
good catch, thanks!

**Comment by colmconn** [comment]
I'm also getting the following errors, can they be safely ignored or are the indicative of other issues in need of fixing?

`2020/05/29 16:16:03 [error] 28713#102103: *40574 open() "/usr/local/www/OrganizrV2/js/plyr.js.map" failed (2: No such file or directory), client: 192.168.1.51, server: dashboard.home.lan, request: "GET /Organizr/js/plyr.js.map HTTP/1.1", host: "dashboard.home.lan"
2020/05/29 16:16:03 [error] 28714#102515: *40573 open() "/usr/local/www/OrganizrV2/js/tinycolor.min.map" failed (2: No such file or directory), client: 192.168.1.51, server: dashboard.home.lan, request: "GET /Organizr/js/tinycolor.min.map HTTP/1.1", host: "dashboard.home.lan"
2020/05/29 16:16:15 [error] 28708#103186: *40569 open() "/usr/local/www/OrganizrV2/css/icons/material-design-iconic-font/scss/_path.scss" failed (2: No such file or directory), client: 192.168.1.51, server: dashboard.home.lan, request: "GET /Organizr/css/icons/material-design-iconic-font/scss/_path.scss HTTP/1.1", host: "dashboard.home.lan"
2020/05/29 16:16:15 [error] 28708#103186: *40569 open() "/usr/local/www/OrganizrV2/css/icons/material-design-iconic-font/scss/_core.scss" failed (2: No such file or directory), client: 192.168.1.51, server: dashboard.home.lan, request: "GET /Organizr/css/icons/material-design-iconic-font/scss/_core.scss HTTP/1.1", host: "dashboard.home.lan"
2020/05/29 16:16:15 [error] 28708#103186: *40569 open() "/usr/local/www/OrganizrV2/css/icons/material-design-iconic-font/scss/_icons.scss" failed (2: No such file or directory), client: 192.168.1.51, server: dashboard.home.lan, request: "GET /Organizr/css/icons/material-design-iconic-font/scss/_icons.scss HTTP/1.1", host: "dashboard.home.lan"
2020/05/29 16:16:15 [error] 28708#103186: *40569 open() "/usr/local/www/OrganizrV2/css/icons/material-design-iconic-font/scss/_extras.scss" failed (2: No such file or directory), client: 192.168.1.51, server: dashboard.home.lan, request: "GET /Organizr/css/icons/material-design-iconic-font/scss/_extras.scss HTTP/1.1", host: "dashboard.home.lan"
2020/06/09 11:30:06 [error] 61102#102111: *5743 open() "/usr/local/www/OrganizrV2/js/tinycolor.min.map" failed (2: No such file or directory), client: 192.168.1.51, server: dashboard.home.lan, request: "GET /Organizr/js/tinycolor.min.map HTTP/1.1", host: "dashboard.home.lan"
2020/06/09 11:30:06 [error] 61102#102111: *5743 open() "/usr/local/www/OrganizrV2/js/plyr.js.map" failed (2: No such file or directory), client: 192.168.1.51, server: dashboard.home.lan, request: "GET /Organizr/js/plyr.js.map HTTP/1.1", host: "dashboard.home.lan"
2020/06/09 11:33:00 [error] 62542#103284: *6 open() "/usr/local/www/OrganizrV2/js/tinycolor.min.map" failed (2: No such file or directory), client: 192.168.1.51, server: dashboard.home.lan, request: "GET /Organizr/js/tinycolor.min.map HTTP/1.1", host: "dashboard.home.lan"
2020/06/09 11:33:00 [error] 62542#103284: *6 open() "/usr/local/www/OrganizrV2/js/plyr.js.map" failed (2: No such file or directory), client: 192.168.1.51, server: dashboard.home.lan, request: "GET /Organizr/js/plyr.js.map HTTP/1.1", host: "dashboard.home.lan"`

**Comment by causefx** [comment]
yea they can be
