### ISSUE TITLE
Simple auth test to return 200 (ok) or 401 (unauthorized)

### ISSUE THREAD

**Issue by kendokan** [causefx/Organizr#141]
I'm using nginx's [auth_request](http://nginx.org/en/docs/http/ngx_http_auth_request_module.html), which checks a defined URL for a HTTP response when any page is requested. If 200, it passes the request through. If 401, it doesn't.

The request is for a simple script (or maybe something like /index.php?auth-status) that returns 200 if a user is logged in, or 401 if not. It doesn't need to output anything else beyond just the header, and it should process as quickly as possible since it will be called every time a URL is requested.

**Comment by causefx** [comment]
would the cookie check not suffice?

**Comment by kendokan** [comment]
Static shared secrets aren't a particularly good security model. Auth-request exists for exactly this use case. I'll take a look and see if I can figure out where to put this in.

**Comment by kendokan** [comment]
Something like this, pretty short and sweet inserted immediately after the $USER object is created in index.php:

```
    # When index.php?auth_request is called, return 200 if logged in, 401 if not.
    if (isset($_GET['auth_request'])) {
        if($USER->authenticated)
            exit(http_response_code(200)); # OK
        else
            exit(http_response_code(401)); # Unauthorized
    }
```

In nginx config:

```
location /whatever {
    auth_request /index.php?auth_request; # this refers to Organizr's index.php. If logged into Organizer, nginx will permit. Otherwise it will deny.
}
```

Additionally you can redirect an unauthenticated user right back to the main page like so:

```
error_page 401 = @error401;
location @error401 {
    return 302 /index.php;
}
```

**Comment by causefx** [comment]
ahhhhh, i get what you are saying...  we can do that.

**Comment by causefx** [comment]
i will make a new php file, that will be lightweight for this.  I will not include it in the index file.

**Comment by causefx** [comment]
@kendokan are you there right now?

**Comment by causefx** [comment]
@kendokan 

so I was able to setup a file named `auth.php` where you can check two variables: `user` & `admin`

`user`  will check if the user is logged in and return either Status codes 200 or 401.
`admin` will check if the user is logged in as well as check if the user is an admin and will also return the same status codes.

The file works perfect but I was having trouble on the nginx side. 

I was unable to set my config in the location block like this:
```
location /tv {
                auth_request /auth.php?admin;
                proxy_pass http://usenet.home.lab:8989;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
}
```
I kept getting Error 500 on nginx.  My workaround was to create a separate nginx block like this:
```
location /auth-admin {
                proxy_pass https://localhost/auth.php?admin;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
}
```
Which then allowed me to insert `auth_request` like so:
```
location /tv {
                auth_request /auth-admin;
                proxy_pass http://usenet.home.lab:8989;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
}
```

I'm not too sure what was causing it to throw those errors.  Have any insight on that?

**Comment by kendokan** [comment]
I just went and looked at my production nginx.conf and your solution is similar to how I'm actually running it. I think I just was going too fast when I typed up the sample config, I'm sorry about that.

I use a rewrite rule rather than proxy_pass, and I add the internal directive so that the auth script isn't exposed outside of the server.

```
location = /auth_request {
    internal;
    rewrite ^ /auth.php?admin;
}
```

**Comment by causefx** [comment]
@kendokan Awesome!  I will try this out today and if it work well, we can make forward.  We will just have two different blocks, one for logged in and one for admin...

**Comment by kendokan** [comment]
Great, thank you for adding this feature.

**Comment by JigSawFr** [comment]
Great initiative to require logging for all 3rd party apps with Organizr !
Just need to integrate Plex login and it will be perfect !

**Comment by causefx** [comment]
OK, last update before I commit this tomorrow.

I have included custom error pages for everyone to use if they like.  It is styled with whatever theme you have selected.  All you need to do it include one line on your nginx config.

`error_page 400 401 402 403 404  /error.php?error=$status;`

Preview:
![image](https://cloud.githubusercontent.com/assets/16184466/23985412/3286f7d0-09dc-11e7-9d1f-680d1f7c0618.png)

As for the security part, I went ahead and put in another variable.  You may now choose to not allow certain users to access a URL as well.  All you need to do in your auth block is include `ban=USERNAME1,USERNAME2` make sure to separate usernames with a comma.
```
location /auth-admin {
                internal;
                rewrite ^ /auth.php?admin&ban=someone,thisperson;
}
```

**Comment by JigSawFr** [comment]
nice !

**Comment by kendokan** [comment]
Thank you!

**Comment by causefx** [comment]
:)
