### ISSUE TITLE
Emby homepage item missing recently added items

### ISSUE THREAD

**Issue by oonqt** [causefx/Organizr#1410]
###### Operating System: Docker (Linux Guest) (Windows Host)
<hr>

##### Problem Description:
Recently Added items returned are incorrect. I only see 3 recently added items on the home screen. The only item types that I see are of type "audiobook" and "shows", looking under the filter those are the only types that I see as well. 

<hr>

##### Reproduction Steps:
Using: Emby Server 4.4.0.12 (Windows 10)
Fill in connection fields, Enabled recent items, item limit 50, refresh 1 minute, minimum auth co-admin

**Comment by causefx** [comment]
tested on:
![image](https://user-images.githubusercontent.com/16184466/85050339-c93aed80-b14a-11ea-8378-be2ffa670c90.png)
 and 
![image](https://user-images.githubusercontent.com/16184466/85050486-056e4e00-b14b-11ea-9026-9315e877be59.png)

both worked:
![image](https://user-images.githubusercontent.com/16184466/85050534-14ed9700-b14b-11ea-803b-e207b9e4f23a.png)

**Comment by pXius** [comment]
I was able to recreate the issue on my side.

So with Item Limit set to 15, I get about 5 items on the home screen. With 50, I get about 8. Setting it to 100 gives me about 12 recently added items. Finally, setting it to 1000 gives me just over 60 items. So that's a workaround for anyone who needs it.

I can also confirm that it's pulling from all my categories, including; TV, Movies, Audio Books, Anime and Documentaries.

**Comment by causefx** [comment]
@pXius can you try logging in as a different user while limit is like 15?  I want to see what happens...

**Comment by pXius** [comment]
> @pXius can you try logging in as a different user while limit is like 15? I want to see what happens...

Just tested. Logged in with another "user" level account. Same result. Saw 7 on both accounts with with limited set at 15.

edit:
Here's something interesting. While I was testing, something got added to Emby, so "recently added" got updated with the new item. However, the visible count now dropped from 7, to 5. Still set at 15.

**Comment by causefx** [comment]
is this still an issue, i think i fixed it before.  if not please open up issue again
