### ISSUE TITLE
LDAP with STARTTLS support

### ISSUE THREAD

**Issue by francescocarzaniga** [causefx/Organizr#1411]
###### Operating System: Solaris
<hr>

##### Problem Description:

LDAP integration does not work if the server requires TLS. Other services work fine both with port 636 and 389.

<hr>

##### Reproduction Steps:
Set LDAP server to only support secure connections. Set authentication backend as LDAP, type OpenLDAP. Set uri ldaps://\<ldap-host\>:636, or ldaps://\<ldap-host\>:389, or ldap://\<ldap-host\>:389. 

<hr>

#### Errors on screen?  If so paste here:

When using port 389:
```
API Connection Failed
Confidentiality required
```
When using port 636:
```
API Connection Failed
Can't contact LDAP server
```

**Comment by francescocarzaniga** [comment]
Setting
```
$useTLS  = true;
```
in 
```
api/vendor/adldap2/adldap2/src/Connections/Ldap.php
```
solves the issue. I image this is intended to be a toggle that has not been implemented yet.

**Comment by causefx** [comment]
If you are on Dev branch, you can try the latest fix.
