### ISSUE TITLE
Jellyfin homepage widget not working

### ISSUE THREAD

**Issue by CMclarty** [causefx/Organizr#1412]
###### Operating System: Ubuntu 18.04
<hr>

##### Problem Description:
Hi all. Jellyfin doesn't see to want to appear on the homepage. I can connect to the api at:

`curl http://localhost:8096/jellyfin/System/Info/Public`

And receive responses internally, but entering:

`http://localhost:8096/jellyfin/`

into the organizr homepage tab section doesn't result in anything appearing in the homepage (organizr is located on the same host). It's hard to troubleshoot where along the process the issue is as there's no 'test connection' option for Jellyfin. For the same reason, I have no error messages/logging to attach.

Happy to provide more info if need. Discord suggested I create an issue report here in case the Jellyfin team have altered the API

Thanks

**Comment by causefx** [comment]
What version of Jellyfin?
I just tested and is working:
![image](https://user-images.githubusercontent.com/16184466/85039816-f4b6db80-b13c-11ea-9ec9-0e8266eeae1d.png)
![image](https://user-images.githubusercontent.com/16184466/85039852-fe404380-b13c-11ea-9e38-0166bc4f5ee5.png)
![image](https://user-images.githubusercontent.com/16184466/85039872-04cebb00-b13d-11ea-81b2-68d2ff31e865.png)
![image](https://user-images.githubusercontent.com/16184466/85039921-13b56d80-b13d-11ea-85c2-0118a4ea03f4.png)

**Comment by GiowGiow** [comment]
@causefx Interesting to see your screenshots, I'm using the same version of Jellyfin but in Organizr the addon shows with Emby Icons (and URLs when clicking on active stream). Do you know what parameter in the code is being used to identify if it's an Emby or Jellyfin server?  
I'm using Jellyfin as a subdomain without the base URL .

**Comment by causefx** [comment]
the /jellyfin is needed on the url to apply the change

try using local address

**Comment by GiowGiow** [comment]
@causefx Thanks for the explanation! that's the cause I was suspecting it was and thanks for the tip I forgot I was already doing that.

**Comment by causefx** [comment]
glad u got it sorted

**Comment by tronyx** [comment]
@CMclarty Have you tried the suggestions above from @causefx that seem to have resolved the issue for another user?

**Comment by CMclarty** [comment]
Hi @christronyxyocum and @causefx. Thanks for your reply.

I've attached screenshots, but I already had the /jellyfin appended as you can see. Jellyfin is 1.5.5 and Organizr 2.0.650

![Screenshot 2020-07-22 at 15 56 41](https://user-images.githubusercontent.com/22944380/88192279-40750d00-cc34-11ea-890d-cc3145928f81.png)
![Screenshot 2020-07-22 at 15 56 36](https://user-images.githubusercontent.com/22944380/88192280-410da380-cc34-11ea-9c55-25e5214d76fa.png)

Interestingly, no mention of the term 'jellyfin' at all in logs

**Comment by causefx** [comment]
these are now separate items in organizr 2.1 - is this still an issue? if so please open up issue again.
