### ISSUE TITLE
Feature Request: Sonarr calendar filtering options

### ISSUE THREAD

**Issue by roquemore92** [causefx/Organizr#1417]
###### Operating System: Docker on Ubuntu 18.04 guest on Windows Server 2019 host
<hr>

##### Problem Description:
Sonarr v3 offers offers an option on their calendar view to "Collapse multiple episodes airing on the same day" 
This makes it much easier to use the calendar view. In the June view on Sonarr, I currently have 4 weeks with shows that are dropping entire seasons on a single day. Collapsing makes all the episodes for the season show up in the space of a single episode, with the option to expand/collapse as desired. For example, when looking at the June calendar in Sonarr, when not collapsed, I can see 1 week of shows on a 1440p screen before having to scroll. With them all collapsed, I can see 3 weeks at a time. 

Would love to see the same option for the homepage calendar in Organizr as well!

If that option is already there, I apologize, I can't seem to find it.

**Comment by causefx** [comment]
We are moving Feature Requests away from **GitHub** and **FeatHub**.  We are now on **_FeatureUpvote_** which is located here:
### **https://vote.organizr.app**
If will also be a tab in Organizr update this Friday 22 Jan 2021


If this Feature Request was already on FeatHub it will get moved over within the week - no further action is needed.
If not, please create a new Feature Request at our new home so we can better keep track of them.
