### ISSUE TITLE
losing access to settings

### ISSUE THREAD

**Issue by macbean101** [causefx/Organizr#1418]
###### Operating System: Ubuntu 18.04
<hr>

##### Problem Description:
When the weather module is active and Homepage is set to default, Settings only shows the top level items.   

https://imgur.com/UaQe4G3

This happens in Edge and Chrome (even with respective incognito/private modes) but does NOT happen in Firefox.  meaning, if I have the weather module enabled and set Homepage to default, i lose access to all settings unless I log in using Firefox.

EDIT: seems I was wrong.  it /was/ working normally in firefox but now that is giving me the same issue.  
<hr>

##### Reproduction Steps:

Enable Weather on the homepage, set Homepage to default, use Chrome/Edge (edit: and firefox)

<hr>

#### Errors on screen?  If so paste here:

```
No errors seen
```

**Comment by HalianElf** [comment]
I can't replicate this. Are there any logs in the browser console? (F12 -> console tab) Or maybe have you checked your PHP logs? Maybe need to make some [PHP Tweaks](https://technicalramblings.com/blog/optimizing-php-fpm-to-get-faster-load-times-of-tabs-in-organizr/)

**Comment by macbean101** [comment]
This is what I see.  There are no errors to be seen in my php logs.  

Tab Function: Loading new tab for: Settings
Uncaught TypeError: Cannot set property 'className' of undefined
    at CBPFWTabs._show (cbpFWTabs.js?v=2.0.633:68)
    at CBPFWTabs._init (cbpFWTabs.js?v=2.0.633:50)
    at new CBPFWTabs (cbpFWTabs.js?v=2.0.633:28)
    at eval (eval at globalEval (jquery-2.2.4.min.js:2), <anonymous>:8:13)
    at Array.forEach (<anonymous>)
    at eval (eval at globalEval (jquery-2.2.4.min.js:2), <anonymous>:7:61)
    at eval (eval at globalEval (jquery-2.2.4.min.js:2), <anonymous>:10:7)
    at eval (<anonymous>)
    at Function.globalEval (jquery-2.2.4.min.js:2)
    at ua (jquery-2.2.4.min.js:3)
DevTools failed to load SourceMap: Could not load content for https://<sniphostname>/js/tinycolor.min.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load SourceMap: Could not load content for https://<sniphostname>/js/plyr.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

**Comment by macbean101** [comment]
It /might/ be resolved?  I'm not sure yet and i'm not sure why the change I made would affect it.  

however, after making the homepage default, i also reordered settings to be lower.  it looks like settings populates fairly consistently now?

**Comment by causefx** [comment]
Fixed in dev now!  Thanks for the issue :)
