### ISSUE TITLE
Don't display 'Software up to date' every time the page is loaded.

### ISSUE THREAD

**Issue by evulhotdog** [causefx/Organizr#142]
![image](https://cloud.githubusercontent.com/assets/365456/23828093/580be2a4-0694-11e7-959a-baa12f700b59.png)

1. Would like to prevent this from showing every time you log in. Ideally it would check in the background and tell you when you are out of date, not when you are up to date. Can get annoying and intrusive at times.
2. As an enhancement to 1, ideally you'd be able to click anywhere on any of the notifications to dismiss, not just the x.

**Comment by causefx** [comment]
Good idea :)
