### ISSUE TITLE
Monitorr link opening new windows instead of directing to Org Tab.

### ISSUE THREAD

**Issue by pXius** [causefx/Organizr#1421]
Version: 2.0.633
Branch: v2-master
Server OS: *nix
PHP: 7.3.11
Install Type: Official Docker
<hr>

##### Problem Description:
While using the Monitorr homepage widget with an active link to direct to a service -- When clicked a new windows is opened with the service instead opening the the selected service's tab in organizr.

Expected behavior:
Directs to Org tab in current page.

Actual behavior: 
A new window is opened. 

<hr>

##### Reproduction Steps:
ie. 
Ombi is monitored by Monitorr. With link set to direct to Https://example.com/ombi (same as tab address) when clicked.
Monitorr widget is added to homepage.
Ombi is set to iFrame
When clicked, instead of going to Ombi tab, a new window is launched with a new Ombi instance.

<hr>

The issue stems from the function getMonitorr() function, in homepage-connect-functions.php
line 2694.
```
$linkPattern = '/<a class="servicetile" href="(.*)" target="_blank" style="display: block"><div id="serviceimg"><div><img id="' . strtolower($service) . '-service-img/'; 
```
or more specifically,
```
target="_blank"
```
is causing the link to be opened in a new window.

This is normal behavior in Monitorr, but in the context of Organizr, we would expect to be redirected to the tab iFrame without creating a new page.

**Comment by tronyx** [comment]
That would require the app to actually have an Organizr tab, which it may or may not depending on the user's preference. It would also need to be able to determine the name of the Tab, which again, is user preference, in order to load the corresponding tab for the application. Seems like a potentially problematic thing with the fact that it's all so customizable for the user. All that being said, I'm inclined to believe that it is working as designed, for best practice with how Organizr works.

**Comment by henrywhitaker3** [comment]
Should be fairly easy to implement, as long as the org tab is the URL set in Monitorr. 

I think a good way to do it would be to have a toggle to turn this functionality on, and fallback to opening a new browser tab if there isn't a corresponding org tab.

Also worth noting that https://domain.com/ombi wouldn't open an Organizr tab anyway, would need to be set to https://domain.com/#Ombi (or whatever your tab name is for ombi)

**Comment by tronyx** [comment]
That would be a simple workaround, however, if you set the URL in Monitorr to the Org Tab URL, simply browsing to Monitorr would now be broken as it would try to open the Org Tab.

**Comment by henrywhitaker3** [comment]
Wait, I'm confused, I have the URL in monitorr set to org tabs and it opens fine:

![image](https://user-images.githubusercontent.com/36062479/86398537-ac033480-bc9d-11ea-9bc9-0c7ebb2934cf.png)

**Comment by tronyx** [comment]
Something must've changed over the last few months or a year (has it really been that long? lol) because I remember when that didn't work. Seems like it's a viable option for @pXius then.

**Comment by causefx** [comment]
We can also add in checks for this... shouldn't be hard to do...

**Comment by pXius** [comment]
> Wait, I'm confused, I have the URL in monitorr set to org tabs and it opens fine:
> 
> ![image](https://user-images.githubusercontent.com/36062479/86398537-ac033480-bc9d-11ea-9bc9-0c7ebb2934cf.png)

Any chance you can test with emby or ombi. Have my set exactly like that, no luck.

**Comment by HalianElf** [comment]
Like I said in Discord, they're hard coded to open in a new window right now. The PR I put in last night will look for a `#` in the URL and if there is, assume it's a tab and change the link to open it in the tab. (Non-Organizr links will still open in a new window)

If you want to test it out, you can grab my v2-develop branch for now.

**Comment by tronyx** [comment]
@pXius Are you running the develop branch? If so, have you updated and tested the changes?
