### ISSUE TITLE
Feature Request: Emby Connect + LDAP backend autentification

### ISSUE THREAD

**Issue by shocker2** [causefx/Organizr#1425]
Hello,
  In my setup, I'm using LDAP for emby auth and it would be nice to have way to enable emby connect login as well.

Thanks!

**Comment by angrycuban13** [comment]
Pretty sure EmbyConnect API was deprecated per https://github.com/MediaBrowser/Emby/issues/3553

**Comment by Roxedus** [comment]
@angrycuban13 https://github.com/causefx/Organizr/commit/87d943690bff898f9df4676eefd89059af95a485

**Comment by angrycuban13** [comment]
I thought the username Emby auth was called something else not EmbyConnect 🤦‍♂️

**Comment by cj2tech** [comment]
Emby Connect is what Emby use to access your login via their servers(external login). "All while still solving the original goal of Emby Connect, which is enabling easy remote connections without having to remember your server IP address."

**Comment by shocker2** [comment]
That's why it would be nice to have Emby Connect + LDAP (for internal login) ;) Now we only have Emby Internal + Emby Connect but if Emby internal is set to LDAP backend it's not working.

**Comment by cj2tech** [comment]
Emby dropped their api to do this https://github.com/MediaBrowser/Emby/issues/3553

**Comment by cj2tech** [comment]
Considering it's been a year since it was last comment on this was over a year ago. Most likely wont be coming back

**Comment by Roxedus** [comment]
@cj2tech We recently enabled it, but somewhat less secure

**Comment by pXius** [comment]
Keep in mind this will work with the local username in the emby database, and not the Emmmby Connect name. From my experimenting anyway.

**Comment by causefx** [comment]
We are moving Feature Requests away from **GitHub** and **FeatHub**.  We are now on **_FeatureUpvote_** which is located here:
### **https://vote.organizr.app**
If will also be a tab in Organizr update this Friday 22 Jan 2021


If this Feature Request was already on FeatHub it will get moved over within the week - no further action is needed.
If not, please create a new Feature Request at our new home so we can better keep track of them.
