### ISSUE TITLE
Tautulli not loading(Blank tab) 2.0.650

### ISSUE THREAD

**Issue by thu3n** [causefx/Organizr#1428]
###### Operating System: Windows
<hr>

##### Problem Description:
Cannot seem to get Tautulli to load, only gets to blank tab. I have tested all kinds of settings. I have a subdomain for it:
tautulli.domain.com
and tried /tautulli in the end.

And i have tried to add iframe with my internal address including port number and also "/tautulli" in the end.

I have stumbled across debugging area where i wrote a command to see if Cookies and  something else(don't remember) was set to true,  and it was set to true.

And stumbled across a old thread where i should name the tab "Tautulli" which i have but didn't make any differents..

I have also enabled the SSO with the guide in DOC.  

I'm getting hair less..... 
<hr>

##### Reproduction Steps:
i don't know what to write here..

<hr>

#### Errors on screen?  If so paste here:
No Error screens
```

```

**Comment by HalianElf** [comment]
Are you including https:// in the tab url? Anything in the console tab when you hit F12 in your browser?

**Comment by tronyx** [comment]
@thu3n Bumping for a response.

**Comment by thu3n** [comment]
> Are you including https:// in the tab url? Anything in the console tab when you hit F12 in your browser?

hmm could have sworn that i have tried https:// but now it actually works! haha, so tired of being my self sometimes....


> @thu3n Bumping for a response.

Sorry for the slow answer. Have been busy :)
