### ISSUE TITLE
Tautulli Widget not showing posters?

### ISSUE THREAD

**Issue by YouveGotMeowxy** [causefx/Organizr#1432]
###### Operating System: Windows/MacOS/Ubuntu
<hr>

Organizr version 2.0.650 Dev (container)

##### Problem Description:

It's pulling in all of the correct text info, but the images for the posters are broken.

Looking in the console, their URL looks like this:

`https://my.domain/plugins/images/cache/102785-list.jpg`

does that look right?

**Comment by tronyx** [comment]
You provided zero information. You say you're using v1.x and, if that is the case, it is no longer supported and has not been for a while now. The template is there for you to provide information and you didn't update any of it. Please provide the requested information, any errors/warnings found in the browser console or logs, etc. so that we can try and help you.

**Comment by YouveGotMeowxy** [comment]
> You provided zero information. You say you're using v1.x and, if that is the case, it is no longer supported and has not been for a while now. The template is there for you to provide information and you didn't update any of it. Please provide the requested information, any errors/warnings found in the browser console or logs, etc. so that we can try and help you.

You were too fast with the scolding. ;)

I created the post and accidentally hit the button. I immediately clicked the Edit link and started filling it in when I saw your reply.

**Comment by tronyx** [comment]
Ah, got'cha. My bad. As you can guess, we get a lot of posts like that.

Anyway, yes, those are the correct image URLs. If the images are not loading have you tried another browser or incognito/private mode? Also, you can try removing everything from inside that directory to force it to regen the image cache.

**Comment by causefx** [comment]
also check file permissions

**Comment by YouveGotMeowxy** [comment]
> If the images are not loading have you tried another browser or incognito/private mode? Also, you can try removing everything from inside that directory to force it to regen the image cache.

@christronyxyocum ty. I just tried both. I deleted all files in that cache folder, as well as trying with Chrome, Edge, and Opera, and they're still all broken.

@causefx Which file permissions should I check, and what should they set to? (I'm not super educated in this stuff, lol.)

**Comment by HalianElf** [comment]
Are you using the internal (ip:port) or external address for the Tautulli connection?

**Comment by ksufinger** [comment]
**Edit:** Disregard,  I think the API errors I was seeing were caused because I was using **https://www.example.com/api/v2** as the connection URL instead of **https://www.example.com**

> I'm seeing the same issue.  The Tautulli widget is working for me, but some posters are not loading.  Checking the Tautulli logs, I'm seeing a number of API errors.  Is this related?
> 
> Timestamp | Level | Message
> -- | -- | --
> 2020-07-23 07:49:35 | DEBUG | Tautulli APIv2 :: Parameter apikey is required.
> 2020-07-23 07:49:35 | DEBUG | Tautulli APIv2 :: API called with kwargs: {'img': '/library/metadata/2082/art/1595040754', 'rating_key': '2082', 'width': '400', 'height': '600'}

**Comment by ksufinger** [comment]
If you are using Organizr ServerAuth to authenticate requests to Tautulli, then you may need to specify an API URL in the Organizr Tautulli settings that is not restricted by ServerAuth.  This was my issue.  I had made an exception for /api in my proxy settings, but the module also needs access to other Tautulli URL paths.

**Comment by HalianElf** [comment]
Yup, that's exactly why I asked what I did. The images are pulled from `<tautulli url>/pms_image_proxy`

**Comment by jscottelblein** [comment]
I see another minor issue when an item is deleted; it'll also show a broken image icon: (i.e. after watching that fight in the #1 spot I deleted it from the server, but Tautulli still shows it's info anyway)

![image](https://user-images.githubusercontent.com/1524526/89548289-7259a800-d7cc-11ea-9a83-312e3756305d.png)

Is there any way to add logic to detect a deleted media file, and if so add some sort of generic icon in it's place? It'd give a more polished appearance.

**Comment by Healzangels** [comment]
> Yup, that's exactly why I asked what I did. The images are pulled from `<tautulli url>/pms_image_proxy`

I'm seeming to have this issue and am using Nginx Proxy Manager, what would this configuration look like exactly here. A bit new and still learning but trying to find things to correct as I go. Thanks!

**Comment by definedlegend** [comment]
Any fix for this issue? I am currently having the same issue. Where do I add the <tautulli url>/pms_image_proxy line? I'm learning alot as I go. It took me 2 hours to reverse proxy it on a subdomain haha.
