### ISSUE TITLE
Requests from Ombi not showing

### ISSUE THREAD

**Issue by devi59** [causefx/Organizr#1436]
###### Operating System: 

Linux 5.3.0-62-generic #56-Ubuntu SMP Tue Jun 23 11:20:52 UTC 2020
--

<hr>

##### Problem Description:
Looking at my website the Requests section is completely empty showing No Items. I have a bunch that I can go look at Ombi and see them, there has to be something I am doing wrong to not show any.

<hr>

##### Reproduction Steps:
I've double checked, SSO is working and the test connections is working but it is showing no items. I have tried changing the minimum user and it is set to guest now for everything. When I open a new incognito tab I see the section but it is blank there too.

<hr>

#### Errors on screen?  If so paste here:

```

```

**Comment by angrycuban13** [comment]
Are there any errors on your browser console?

**Comment by devi59** [comment]
I refreshed and looked through the console. The only error I see is one server my friend has is not up so it is showing an error on that (I believe I have plex set to preload) other then that, nothing else that I can see.

**Comment by tronyx** [comment]
Please double-check the version you have listed for Organizr in your OP as there is no v3 for Organizr at this time.

This is a known "problem" and it's based around what you have the item limit set to in conjunction with the TOTAL number of requests along with any filters you have applied to the view for that item. Let's say you have the limit set to 10. That includes ALL types of requests, IE: available, unavailable, approved, unapproved, etc. because the API call will just say "give me the 10 most recent requests from the list" and THEN apply the filters that you have set. If you set the filter to unavailable, let's say there are 2, and the other 8 requests ARE available, then you will ONLY see the 2 unavailable. Now, if you set the limit to 20, you have 6 unavailable within that limit, and 14 available, you will ONLY see those 6 that are unavailable.

So, with that being said, what filters, if any, do you have applied for that Homepage Item and what is the Limit set to within the Ombi Homepage Item settings?

**Comment by devi59** [comment]
> This is a known "problem" and it's based around what you have the item limit set to in conjunction with the TOTAL number of requests along with any filters you have applied to the view for that item. Let's say you have the limit set to 10. That includes ALL types of requests, IE: available, unavailable, approved, unapproved, etc. because the API call will just say "give me the 10 most recent requests from the list" and THEN apply the filters that you have set. If you set the filter to unavailable, let's say there are 2, and the other 8 requests ARE available, then you will ONLY see the 2 unavailable. Now, if you set the limit to 20, you have 6 unavailable within that limit, and 14 available, you will ONLY see those 6 that are unavailable.
> 
> So, with that being said, what filters, if any, do you have applied for that Homepage Item and what is the Limit set to within the Ombi Homepage Item settings?

I had under Misc Options
Item Limit set to 50. ( tried 5 a moment ago after your response, same issue, no items)
Minimum group to request is at User.
Limit to user is off
Refresh seconds is 30
Use Ombi Alias Names is on

Under Default Filter all are set to on
When I use test connection it says API connection Success

In Ombi I have a large list of requests sitting when I go click on that tab in Ombi. I am not using any filtering on Organizr homepage--All are on. I tried different combos and no changes.

**Comment by 5H3RM** [comment]
Having the same problem, I knew it was a known issue but I thought the problem had to deal more with Ombi rather than Organizr

**Comment by DustyTurtleDip** [comment]
Same issue

Organizr Version: 2.0.740
Branch: Develop
Operating System: Windows 10 
![2020-08-10_08h33_29](https://user-images.githubusercontent.com/38813688/89782989-32eccd80-dae4-11ea-9807-476fcfb8e08c.png)

OMBI version : 4.0.424

![2020-08-10_08h29_52](https://user-images.githubusercontent.com/38813688/89782641-b22dd180-dae3-11ea-839b-2d41ef7a86db.png)

**Comment by causefx** [comment]
i believe this issue was fixed in December, please open back up if issue is still there.

**Comment by grasuoare** [comment]
Hi!

I'm having the same issue. 

Organizr Version:  2.1.476
Branch: v2-master
Official Docker

Requests No items

Test connection -> API connection Success

Could you help me, please, @causefx ?

**Comment by causefx** [comment]
can you click the copy json button on the settings homepage item screen?

**Comment by grasuoare** [comment]
{
	"Enable": {
		"homepageOmbiEnabled": true,
		"homepageOmbiAuth": "999"
	},
	"Connection": {
		"ombiURL": "http://192.168.90.23:3579",
		"ombiToken": "**********",
		"ombiFallbackUser": "grasuoare",
		"ombiFallbackPassword": "**********"
	},
	"Misc Options": {
		"homepageOmbiRequestAuth": "4",
		"ombiTvDefault": "all",
		"ombiLimitUser": false,
		"ombiLimit": "50",
		"ombiRefresh": "5000",
		"ombiAlias": true
	},
	"Default Filter": {
		"ombiDefaultFilterAvailable": true,
		"ombiDefaultFilterUnavailable": true,
		"ombiDefaultFilterApproved": true,
		"ombiDefaultFilterUnapproved": true,
		"ombiDefaultFilterDenied": true
	}
}

**Comment by causefx** [comment]
did you remove what was in ombiToken before commenting?  if so, it should have been redacted already, if not, that is the issue.

**Comment by grasuoare** [comment]
`{
	"Enable": {
		"homepageOmbiEnabled": true,
		"homepageOmbiAuth": "999"
	},
	"Connection": {
		"ombiURL": "http://192.168.90.23:3579",
		"ombiToken": "**********",
		"ombiFallbackUser": "grasuoare",
		"ombiFallbackPassword": "**********"
	},
	"Misc Options": {
		"homepageOmbiRequestAuth": "4",
		"ombiTvDefault": "all",
		"ombiLimitUser": false,
		"ombiLimit": "50",
		"ombiRefresh": "5000",
		"ombiAlias": true
	},
	"Default Filter": {
		"ombiDefaultFilterAvailable": true,
		"ombiDefaultFilterUnavailable": true,
		"ombiDefaultFilterApproved": true,
		"ombiDefaultFilterUnapproved": true,
		"ombiDefaultFilterDenied": true
	}
}`

Because of the paste here. Both Token and Password are filed. Test connection is also ok

**Comment by grasuoare** [comment]
Could we check some log files? Or could you tell .e what else to check? Ombi is working as it should, taking request, etc.

**Comment by causefx** [comment]
how many requests are in ombi ATM?  how many movies, how many shows, how many music requests?

**Comment by grasuoare** [comment]
Movies:
Processing: 22
Available: 68

Shows:
Processing: 3
Available: 5

**Comment by grasuoare** [comment]
Wow, i just renew the ombi app token and repasted it over the old one it in Organizr -> Ombi SSO.
It works now. 

Thank you for the time.

**Comment by causefx** [comment]
that is super odd, the test should have failed.... lemme check the test script

**Comment by causefx** [comment]
there was a slight issue with the test button - i will push the fix

**Comment by grasuoare** [comment]
Thank you again!
