### ISSUE TITLE
Auth Proxy header is case sensitiv

### ISSUE THREAD

**Issue by PhyberApex** [causefx/Organizr#1437]
###### Branch: Develop

<hr>

##### Problem Description:
It did take me a while to figure out what I was doing wrong with proxy auth. Turns out all Headers are checked case sensitiv which means I had to change the header from "X-OIDC-EMAIL" which I put in at my proxy to "X-Oidc-Email" to work as in PHP headers are cased like that. I would propose to either remove the case sensitivity or exlipicitly add a tooltip mentioning the case sensitivity in the auth proxy tab. I would be glad to open a PR if you'd tell me which way you'd prefer.

<hr>

##### Reproduction Steps:
Pulling hair out while trying to get auth proxy to work :)

~Cheers

**Comment by causefx** [comment]
we fixed this - didn't we?  if not  - please open back up and we can discuss
