### ISSUE TITLE
Change interface language?

### ISSUE THREAD

**Issue by coen800** [causefx/Organizr#1440]
###### Operating System: Docker
<hr>

##### Problem Description:
Is there a way to force change interface language for some reason it switched mine to dutch but I want it in English.

<hr>

**Comment by HalianElf** [comment]
Click the Language icon next to your avatar in the top right.

**Comment by tronyx** [comment]
Click the language icon in the upper, right-hand corner of the Organizr screen.

**Comment by tronyx** [comment]
User assisted in Discord, closing.
