### ISSUE TITLE
Scroll bar on homepage calendar (month view) should not appear (firefox only)

### ISSUE THREAD

**Issue by mouseron** [causefx/Organizr#1441]
###### Operating System: docker container /organizrtools/organizr-v2:latest
<hr>

##### Problem Description:

Homepage calendar displays a scroll bar when in month view on Firefox 78.0.2 (macOS). Was not able to replicate in Safari.

Firefox:
![firefox](https://user-images.githubusercontent.com/68985076/88885329-a9cfce00-d27b-11ea-9ac7-56a9a274df81.png)

Safari:
![safari](https://user-images.githubusercontent.com/68985076/88885337-accabe80-d27b-11ea-90b9-56d7e6f3fa39.png)

<hr>

**Comment by mouseron** [comment]
It's been a minute since I posted this issue. I know there are much bigger issues to address, but this surely is a simple fix. It would be great if you could take a look at it please. Currently still present as of version 2.1.83.

Thanks!

**Comment by causefx** [comment]
i will install firefox to test out

**Comment by causefx** [comment]
should be fixed now in dev

**Comment by mouseron** [comment]
> should be fixed now in dev

Amazing. Thanks!
