### ISSUE TITLE
Organizr no longer working

### ISSUE THREAD

**Issue by skidda666** [causefx/Organizr#1442]
###### Operating System: Windows/MacOS/Ubuntu = Unraid
<hr>

##### Problem Description:
was told that organizr v2 was deprected and no longer being supported, so I saw the 'new' organizrv2 in the docker hub and installed it, well that didn't word as expected. It's no longer operational, it does not assign anything other than ports to it (443 and 80) and it no longer allows for opening within the Web UI, so now it's just sitting in my docker collection with no real way to open it and reset it back up. Am I missing something?

<hr>

##### Reproduction Steps:

<hr>

#### Errors on screen?  If so paste here:

```

```

**Comment by Roxedus** [comment]
Atleast provide some container logs

**Comment by skidda666** [comment]
not sure where to go to get the  container logs however i found this 

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 10-adduser: executing...

-------------------------------------
GID/UID
-------------------------------------
User uid: 99
User gid: 100
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 20-config: executing...
[cont-init.d] 20-config: exited 0.
[cont-init.d] 30-setup: executing...
[cont-init.d] 30-setup: exited 0.
[cont-init.d] 35-fpm: executing...
[cont-init.d] 35-fpm: exited 0.
[cont-init.d] 40-install: executing...
-----------------------
| Installing Organizr |
-----------------------
Cloning into '/config/www/organizr'...
fatal: unable to access 'https://github.com/causefx/Organizr/': Could not resolve host: github.com
[cont-init.d] 40-install: exited 1.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.

**Comment by Roxedus** [comment]
Your container has networking issues, due to me missing a field in the template. Add a network to the container.

**Comment by Roxedus** [comment]
I have pushed a update to the template that will fix this for new installs done after a couple of hours from now.

**Comment by skidda666** [comment]
yeah i saw that it was automatically disabled and went and ahead and put it as bridged, however it's wanting to use ports 443 and 80 and it's not allowing me to change that as I am already using those ports for something else. Any way to change those ports to something other than 443 and 80 so that I would able to access the GUI?

**Comment by Roxedus** [comment]
You can remove port 443. Edit port 80, set the **host** port to a port of your choosing
