### ISSUE TITLE
Emby has updated their URL for item details

### ISSUE THREAD

**Issue by MischievousMet** [causefx/Organizr#1443]
###### Operating System: Windows 10
<hr>

##### Problem Description:
Emby has updated their URL for item details.

Current link generated for recently added items etc.
https://mydomain.tv/emby/web/#!/item/item.html?id=[item **id]

Link needs to change to https://mydomain.tv/emby/web/index.html#!/item?id=[item **id]
<hr>

##### Reproduction Steps:

Click Emby link button on any recently added item and item detail shows blank screen
<hr>

#### Errors on screen?  If so paste here:

```
Access Denied
```

**Comment by causefx** [comment]
fixed in dev - pushing to master tomorrow
