### ISSUE TITLE
No Option to Remove Repo/Docs from Sidebar

### ISSUE THREAD

**Issue by jonfairbanks** [causefx/Organizr#1444]
###### Operating System: Docker
<hr>

##### Problem Description:

As of a recent update, links to the Organizr Repo and Organizr Docs were added to the sidebar. In checking the settings, it is not possible to remove these. As an Admin, I did not set these and I do not want them shown to other users. 

<img width="43" alt="Screenshot_5" src="https://user-images.githubusercontent.com/1957806/89704004-1b0b2300-d905-11ea-9d95-229892776605.png">

You can force them out with CSS, but this should not be required. Please revert to the previous behavior or add a toggle.

<hr>

##### Reproduction Steps:

Install the Docker container and load the UI, then look at the sidebar.
<hr>

#### Errors on screen?  If so paste here:

```

```

**Comment by GilbN** [comment]
![8379AD9B-7BF7-4762-8A44-E9A5A333B99E](https://user-images.githubusercontent.com/24592972/89704297-ed4ccb00-d952-11ea-844c-b5a58fb31930.jpeg)

Switch to develop.

**Comment by jonfairbanks** [comment]
A fast reply and an even faster fix, thanks!

**Comment by HalianElf** [comment]
Those settings are in master too just FYI
