### ISSUE TITLE
API V2 and Apache

### ISSUE THREAD

**Issue by G4Zz0L1** [causefx/Organizr#1450]
###### Operating System: Arch Linux
<hr>

##### Problem Description:
I've a normal folder in the web directory and everything worked fine, until the latest commit.
Now it doesn't work, and it fails on https://github.com/causefx/Organizr/blob/v2-develop/js/functions.js#L9478 because it tries to fetch `/organizr/api/v2/launch` which doesn't exist.
I've checked this page (https://docs.organizr.app/books/setup-features/page/api-v2-webserver-changes-needed) but it doesn't mention Apache rewrite, so I've tried to mimic the nginx one.
```
RewriteCond %{HTTP_REFERER} "https://myddns/organizr/"
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteCond %{REQUEST_URI} !^/organizr/api/v2/
RewriteRule ^(.*)$ /organizr/api/v2/index.php$1 [R=301,L]
```
Now everything goes through `/organizr/api/v2/` so everything is a 404.
I've tried to reset the repo to the latest working commit, and even switch to v2-master, but it fails to load the home, with a JSON error.
What should I do to use v2-develop in Apache?

**Comment by McGeaverBeaver** [comment]
They broke the database or forgot files .. You can't even backout to master branch because this call looks to be in the database!

**Comment by G4Zz0L1** [comment]
So, Organizr isn't working for everyone on the latest commit of v2-develop branch?
It seems strange, on the db there isn't much apart from users data or tabs info.

EDIT: same error even on recent last commit.

EDIT: this was an answer for someone who deleted the comment. Ignore the rest above.

**Comment by McGeaverBeaver** [comment]
STRANGE ..comment deleted! Came here to update it. I must of over clicked last time..

Regarding DB issue on rollback -> I attempted to install a v2-master branch , use my config and database and was still having the same errors in server logs looking for v2/launch.. 

I went back to my orig files and confirmed again my nginx config was updated and I am not getting anymore errors , just a blank page..
![9c9342b84RS](https://user-images.githubusercontent.com/29310945/91465477-d287bb00-e85b-11ea-974d-f396447954a3.png)


![image](https://user-images.githubusercontent.com/29310945/91465527-e3383100-e85b-11ea-9107-b18d7e0b5bdf.png)

![image](https://user-images.githubusercontent.com/29310945/91465566-ed5a2f80-e85b-11ea-86e2-aae3be4ea39b.png)

![image](https://user-images.githubusercontent.com/29310945/91465601-f8ad5b00-e85b-11ea-9c23-3174f45691e2.png)

**Comment by HalianElf** [comment]
@McGeaverBeaver your issue is completely different from this. Please open your own issue.

**Comment by G4Zz0L1** [comment]
Actually the outcome is identical. But I'm on apache.
It seems that I can't get a redirect rule that matches the ones for nginx.

**Comment by HalianElf** [comment]
Outcome may be the same but the reason is completely different.

**Comment by McGeaverBeaver** [comment]
@HalianElf  Elaborate how this is different ? If you have info please provide to support this being different?

**Comment by HalianElf** [comment]
You rolled back and are getting the 404 because the tab url in the db needs to be fixed back to the old API link.

**Comment by McGeaverBeaver** [comment]
I agree when rolled back with the above statement. 

The above screenshots posted are on rolled forward with the latest v2-dev branch deployed & the correct re-write rules added as per the latest document.

**Comment by HalianElf** [comment]
But then you're not getting a 404 and are just getting JS errors which again has nothing to do with the Apache rewrite rules.

**Comment by G4Zz0L1** [comment]
What I was saying it's that I've the same error, if I comment out the apache rewrite rules

![image](https://user-images.githubusercontent.com/13220636/91468081-c3bbfb00-e891-11ea-98c5-8e690857f483.png)

**Comment by McGeaverBeaver** [comment]
Right, and my authentication is clearly not working.. I can go incognito and get to all my pages such as /tv ect.. 

The rewrite for auth is clearly not working and not loading the login page.. that's my guess

**Comment by McGeaverBeaver** [comment]
Also TO FURTHER note.. on a fresh upgrade I do get errors with 

2020/08/27 12:17:10 [error] 2581#2581: *816 FastCGI sent in stderr: "PHP message: PHP Parse error:  syntax error, unexpected ')' in /usr/share/nginx/www/Organizr/api/homepage/lidarr.php on line 133" while reading response header from upstream, client: 192.168.1.170, server: DOMAIN, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.2-fpm.sock:", host: "DOMAIN", referrer: "DOMAIN"

this is a simple miss of an extra " , " to be removed on line 133..

$results = $downloader->getCalendar($startDate, $endDate, );

to 


$results = $downloader->getCalendar($startDate, $endDate );


Still result in the same JS error , I have also reuploaded v2-develop manually to the server to ensure no files were missed.. Same JS error.

**Comment by causefx** [comment]
for apache can you try:

```
RewriteEngine On
RewriteBase /api/v2
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^ index.php [QSA,L]
```

OR

```
<Location /api/v2>
    RewriteEngine On
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteRule ^ /api/v2/index.php [QSA,L]
</Location>

```
no idea if it'll work

**Comment by McGeaverBeaver** [comment]
Saw the updates pushed to the index file on v2 folder.. Pushed that .. Same java error.

**Comment by causefx** [comment]
> Saw the updates pushed to the index file on v2 folder.. Pushed that .. Same java error.

Are you on 2.0 or 2.1

if 2.1 can you access `http://org/api/v2/status`

**Comment by McGeaverBeaver** [comment]
I can, 

{
    "response": {
        "result": "success",
        "message": null,
        "data": {
            "status": "ok",
            "api_version": "2.0",
            "organizr_version": "2.1.0"
        }
    }
}

**Comment by McGeaverBeaver** [comment]
Looks like you fixed it, but now calendar is not loading. 

![image](https://user-images.githubusercontent.com/29310945/91480058-619ece00-e870-11ea-8cb4-6c80dc5eaa06.png)

**Comment by causefx** [comment]
check nginx logs and do another force pull for branch...

@G4Zz0L1 lemme know when you try both code blocks from above please.

**Comment by McGeaverBeaver** [comment]
Did a force pull - refreshed, fixed.. thanks @causefx

**Comment by G4Zz0L1** [comment]
Nope, nothing of the above works.
I've put together something between yours and mine, I've come up with this
```
RewriteCond %{HTTP_REFERER} "https://myddns/organizr/"
RewriteCond %{REQUEST_URI} ^/organizr/api/v2/
RewriteCond %{REQUEST_URI} !^/organizr/api/v2/index.php
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^/organizr/api/v2/(.*)$ /organizr/api/v2/index.php?$1 [R=301,QSA,L]
```

Now the problem seems to be the new rewrited url, I don't know what's the correct format.
With the form `/organizr/api/v2/index.php?launch` I get a 404.
I don't know how it has to be to work, can you give me an example url?

**Comment by causefx** [comment]
The endpoint should be: 

`/api/v2/launch`

**Comment by causefx** [comment]
I just installed apache on my windows machine... and added the rewrite to my directory structure and it worked...
```
<Directory />
    AllowOverride none
    Require all denied
</Directory>

DocumentRoot "C:\Projects\Organizr-V2"
<Directory "C:\Projects\Organizr-V2">
    Options Indexes FollowSymLinks
    AllowOverride None
    Require all granted
	RewriteEngine On
	RewriteBase /api/v2
	RewriteCond %{REQUEST_FILENAME} !-f
	RewriteCond %{REQUEST_FILENAME} !-d
	RewriteRule ^ index.php [QSA,L]
</Directory>
AddHandler application/x-httpd-php .php
AddType application/x-httpd-php .php .html
LoadModule php7_module "C:\Users\CauseFX\Downloads\php\php7apache2_4.dll"
PHPiniDir "C:\Users\CauseFX\Downloads\php"
```

![image](https://user-images.githubusercontent.com/16184466/91581476-534dc200-e903-11ea-9966-266835b7c755.png)

**Comment by causefx** [comment]
This also worked...
```
RewriteEngine On
RewriteBase /api/v2
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^ /api/v2/index.php [QSA,L]
```

**Comment by G4Zz0L1** [comment]
Nope, they don't work here, I've tried both methods.
Same result as before, it does the redirect, but it does it wrong.
What is the expected url on the framework?
Not the `/api/v2/launch`, that's the external one.
I think that the framework expects it in some other way, if I can get that I hope it's ok.

![image](https://user-images.githubusercontent.com/13220636/91590881-51fcb380-e95c-11ea-97ea-e92384207b39.png)

**Comment by G4Zz0L1** [comment]
I don't think I can fix this.
I've tried every combination of the apache rewrite rule that I know and I've used.
From the apache logs I've found this, I don't know if it's useful.
```
[Sat Aug 29 03:45:26.596734 2020] [proxy_fcgi:error] [pid 130506:tid 140129850713664] [client xxx.xxx.xxx.xxx:xxxxx] AH01071: Got error 'PHP message: Slim Application Error:
Type: Slim\\Exception\\HttpNotFoundException
Code: 404
Message: Not found.
File: /webfolder/organizr/api/vendor/slim/slim/Slim/Middleware/RoutingMiddleware.php
Line: 91
Trace: #0 /webfolder/organizr/api/vendor/slim/slim/Slim/Middleware/RoutingMiddleware.php(57): Slim\\Middleware\\RoutingMiddleware->performRouting()
#1 /webfolder/organizr/api/vendor/slim/slim/Slim/MiddlewareDispatcher.php(123): Slim\\Middleware\\RoutingMiddleware->process()
#2 /webfolder/organizr/api/vendor/slim/slim/Slim/Middleware/ErrorMiddleware.php(89): class@anonymous->handle()
#3 /webfolder/organizr/api/vendor/slim/slim/Slim/MiddlewareDispatcher.php(123): Slim\\Middleware\\ErrorMiddleware->process()
#4 /webfolder/organizr/api/v2/index.php(135): class@anonymous->handle()
#5 /webfolder/organizr/api/vendor/slim/slim/Slim/MiddlewareDispatcher.php(212): {closure}()
#6 /webfolder/organizr/api/v2/index.php(76): class@anonymous->handle()
#7 /webfolder/organizr/api/vendor/slim/slim/Slim/MiddlewareDispatcher.php(123...', referer: https://myddns/organizr/
```
I'm close to give up and reset to master branch.

**Comment by G4Zz0L1** [comment]
Finally solved it with the help of @causefx on discord, the commit https://github.com/causefx/Organizr/commit/9d93a87ccaa3630205cd12b9e2cc62f01712f4f6 and the apache conf like this:
```
<Directory "/webfolder/organizr">
    Options Indexes FollowSymLinks
    AllowOverride None
    Require all granted
    RewriteEngine On
    RewriteBase /organizr/api/v2
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteRule ^ /organizr/api/v2/index.php [QSA,L]
</Directory>
```
