### ISSUE TITLE
Cannot load Dakboard

### ISSUE THREAD

**Issue by Bboy486** [causefx/Organizr#1451]
V2
Master
Nginx
Windows

##### Problem Description:
Dakboard uses a private url to access  --- https://dakboard.com/app/screenPredefined?p=urlstring. 

Usually you login and then you can access the dakboard. However using Dakboard via HTML iframe does not let me log in in Optimizr V2. 

HTML 5 iFrame
Dakboard url 
When the Dakboard splash screen shows I cannot login to see my screen

<hr>

#### Errors on screen?  If so paste here:
https://prnt.sc/u756ys
```

```

**Comment by causefx** [comment]
it could be the samesite cookie issue...

you can login w/o iframe correct?

**Comment by Bboy486** [comment]
Yes I can log into it outside of Organizr. This is also affecting my other iframes

Omni, Grafana Dashboards, anything using iframes. 

https://prnt.sc/u7ttrm

**Comment by Bboy486** [comment]
Just following up on this issue.

**Comment by HalianElf** [comment]
It's SameSite issues like Cause said.

https://docs.organizr.app/books/troubleshooting/page/redirect-looping---samesite-errors

And Grafana blocks iframing by default so you need to edit the config: https://grafana.com/docs/grafana/latest/administration/configuration/#allow_embedding

**Comment by Bboy486** [comment]
Thank you very much. I did not follow what you had originally mentioned. That worked!
