### ISSUE TITLE
New container healthcheck fails after migration

### ISSUE THREAD

**Issue by lateparty** [causefx/Organizr#1453]
###### Operating System: Linux host Docker “Official Docker“ i.e. “organizr/organizr”
<hr>

##### Problem Description:
The container healthcheck has started failing, and then the container becomes unresponsive. Following this, when watchtower attempts to load an update the container cannot be stopped/killed/removed and if that does somehow succeed, the container remains in the docker network config and can’t be removed even with a disconnect and the whole docker service/system needs to be restarted.

Swapped from the organizrtools repo to organizr without changing anything but that line in my docker run script.

<hr>

**Comment by Roxedus** [comment]
What are you using to deploy the container? Portainer? docker-compose?

**Comment by lateparty** [comment]
I have a bunch of docker run shell scripts that I maintain from when I moved over from Synology DSM to a dedicated Linux machine. With files for mass create, stop, and stop and remove and let the docker service and operating system (Arch systemd) sort out the rest as it has done a good job of it.

I do run portainer but not for deployment, just because I am not always up for debugging in the terminal.

If it helps, here’s my docker run command
#!/bin/bash
#old container variable organizrtools/organizr-v2
docker run \
  -d \
  --name=organizr-bugged \
  --privileged \
  --restart always \
  -e PUID=1020 -e PGID=100 \
  -e TZ=Australia/Sydney \
  -p 6000:80 \
  -v /containers/organizr:/config \
  --label=com.centurylinklabs.watchtower.enable=true \
  organizr/organizr

**Comment by Roxedus** [comment]
Do this for me: `docker inspect organizr-bugged -f='{{.Config.Healthcheck}}'`

**Comment by lateparty** [comment]
{[CMD-SHELL curl -ILfSs http://localhost:8080/nginx_status > /dev/null || curl -ILfkSs https://localhost:8080/php_status > /dev/null || exit 1] 0s 0s 1m0s 0}

Nice one.

8080 ain’t going anywhere, I reserve that for my Linux machine, none of my containers have it. (But I may be reading it wrong and that is localhost within the container.)

**Comment by Roxedus** [comment]
Yea, 8080 is just bound to the container.  Could you post the default file? /config/nginx/site-confs/default

**Comment by lateparty** [comment]
cat ./nginx/site-confs/default
#V0.0.4
server {
  listen 80 default_server;
  root /config/www/organizr;
  index index.html index.htm index.php;

  server_name _;
  client_max_body_size 0;

  #Real Docker IP
  #Make sure to update the IP range with your Docker IP subnet
  real_ip_header X-Forwarded-For;
  #set_real_ip_from 172.17.0.0/16;
  real_ip_recursive on;

  #Deny access to Org .git directory
  location ~ /\.git {
    deny all;
  }

  location / {
    try_files $uri $uri/ /index.html /index.php?$args =404;
  }

  location /api/v2 {
    try_files $uri /api/v2/index.php$is_args$args;
  }

  location ~ \.php$ {
    fastcgi_split_path_info ^(.+\.php)(/.+)$;
    fastcgi_pass 127.0.0.1:9000;
    fastcgi_index index.php;
    include /etc/nginx/fastcgi_params;
    fastcgi_hide_header X-Powered-By;
    fastcgi_buffers 32 32k;
    fastcgi_buffer_size 32k;
  }


——
Note I’m currently on mobile chrome and can’t figure out how to easily paste in “code” formatted stuff, so I’ve removed some of the spaces between the “#” and the first proceeding character, but that’s the only change.

**Comment by Roxedus** [comment]
Thanks, I may have found the error, atleast for the healtcheck. Fetch a new image in about 30 minutes

**Comment by lateparty** [comment]
Got a bit of free time, and have just rebooted (have to reboot it turns out) removed organizr, and pruned all images.

sh organizr-create.sh 
Unable to find image 'organizr/organizr:latest' locally
latest: Pulling from organizr/organizr
df20fa9351a1: Pull complete 
2ac1e4f3af5e: Pull complete 
af86ee507f13: Pull complete 
c7faa54820f2: Pull complete 
Digest: sha256:78e8c9268c9f29145f75d78dfec74dbd4826def7c0e440e5d0838ef3e662da2d
Status: Downloaded newer image for organizr/organizr:latest
af12b93fc8868c1adf5f584fc8c002d711e15d6f3ff0ad610ef8b70569e9df42

I’ll double post for notification sake how things go, unless you would like me to troubleshoot something now with this image set. Happy to follow further instructions.

**Comment by lateparty** [comment]
It went into unhealthy pretty quickly even with the new image. But even currently, where it's been unhealthy for about 10 hours, when I run docker exec -it -u root organizr-bugged /bin/bash to get into the container, and actually do the health check, it returns 0 per

`root@af12b93fc886:/$  curl -ILfSs http://localhost:8080/nginx_status > /dev/null && curl -ILfkSs http://localhost:8080/php_status > /dev/null || exit 1
`
`
root@af12b93fc886:/$ echo $?
0
`

Looking at other containers that have healthchecks, those that rely on a curl result all fail within a certain period of time after starting and remain failing until my system restarts. One container that uses just "ping" and "pgrep" in its healthcheck shell command, remains healthy (providing the conditions are met of course)

**Comment by Roxedus** [comment]
Im inclined to think that there is some underlying system issue going on. Do you have Netdata?

**Comment by lateparty** [comment]
I don't know what that is sorry.

Just found this https://github.com/containerd/containerd/issues/4509

I am on the reported impacted version.

**Comment by tr1plus** [comment]
Hey

I am getting the same issue. I've just migrated from the old container to the new one. All looks good, except that my container is reporting as unhealty. The previous image has always been healthy.

Portainer also shows 

> 

Last output | curl: (22) The requested URL returned error: 404 Not Found curl: (35) error:1408F10B:SSL routines:ssl3_get_record:wrong version number
-- | --


Not sure if this is of any help. I'll keep looking on my end too if anything special pops up

**Comment by Roxedus** [comment]
@tr1plus That was fixed 12 hours ago

**Comment by lateparty** [comment]
@Roxedus considering this is all but not an Organizr issue, I'll be happy to close this with a link to the containerd issue above if you like. Thank you for your assistance troubleshooting and it's great that a coincidental issue was able to be resolved as a result.

**Comment by Roxedus** [comment]
I would like to keep in open, so i will remember to check how it turns out

**Comment by tr1plus** [comment]
Hmm I started looking into this less than 12 hours ago - but I now see that for whatever reason docker is not pulling the latest image.

This seems to be on my end, thanks for the help anyway :)

`sudo docker pull organizr/organizr
Using default tag: latest
latest: Pulling from organizr/organizr
Digest: sha256:78e8c9268c9f29145f75d78dfec74dbd4826def7c0e440e5d0838ef3e662da2d
Status: Image is up to date for organizr/organizr:latest
docker.io/organizr/organizr:latest
`

**EDIT:**
To be fair - I'm still not 100% positive. When pulling the latest image I get the following one(as you can see, create 15 hours ago which is your last update. the SHA256 doesn't match, but according to some googeling this is normal with multi arch images):
`organizr/organizr           latest              sha256:78e8c9268c9f29145f75d78dfec74dbd4826def7c0e440e5d0838ef3e662da2d   d06c59324c4f        15 hours ago        67.5MB`

Still getting the same error.

`

Last output | curl: (22) The requested URL returned error: 404 Not Found curl: (35) error:1408F10B:SSL routines:ssl3_get_record:wrong version number
-- | --


`

My containerd is not on the impacted version, so it should work...
` containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
`

I'll keep digging...

**Comment by HalianElf** [comment]
Just to confirm, are you updating the container/changing the image out within portainer? It doesn't seem to update the healthcheck when switching it in portainer based on some of the some users in discord and I wouldn't be surprised if something similar is happening when updating it through there as well.

**Comment by tr1plus** [comment]
I tried both via portainer and via cli. I even removed all organizr images and re downloaded using the latest tag. The only thing I haven't tried is creating a fresh config directory,  currently I am using my existing dir migrated from the old container. Just using latest, no dev or other branch

**Comment by Roxedus** [comment]
Handled upstream. 

@tr1plus Please open a issue on https://github.com/Organizr/docker-organizr if your issue is still active
