### ISSUE TITLE
First entry in recently added is always an old entry without a cover image

### ISSUE THREAD

**Issue by poiy23** [causefx/Organizr#1455]
###### Operating System: UNRAID
<hr>

##### Problem Description:

The first entry in recently added
is always an old entry without a cover image.
The error cannot be corrected by emptying the cache.
<hr>

##### Reproduction Steps:

Homepage
<hr>

#### Errors on screen?  If so paste here:

<a href="https://ibb.co/yyH2wcH"><img src="https://i.ibb.co/2tGJD1G/Unbenannt1.png" alt="Unbenannt1" border="0" /></a>

**Comment by poiy23** [comment]
I have solved it. I moved the series/movie from the folder and deleted the entry in Plex. Then I added the movie again and in Organizr I updated the browser 50 times. This solved the problem

**Comment by causefx** [comment]
Yeah we just get the data from plex. glad you solved it.
