### ISSUE TITLE
[v2-develop] /api/v2/login error 422

### ISSUE THREAD

**Issue by DunklerPhoenix** [causefx/Organizr#1458]
###### Operating System: Docker Image / Debian
<hr>

##### Problem Description:
I upgraded to Organizr v2 API v2 through v2-develop branch. It worked without any problems, but then came the autologout. 
(was logged in through the old cookie) Now I can't login anymore. The login field is after entering the username and password or after using plex oauth out of function:
![EYQy732WG2](https://user-images.githubusercontent.com/1261305/92337346-30f93880-f0a9-11ea-8206-8d823f0e2e0f.png)

Somehow the login endpoint gives a 422. 
I don't know why this error happens, but I don't have more logs. PHP doesn't throw any error.

<hr>

#### Errors on screen?  If so paste here:

Error in Chrome Dev Console:
```
jquery-2.2.4.min.js:4 POST https://xxxxx/api/v2/login 422
send @ jquery-2.2.4.min.js:4
ajax @ jquery-2.2.4.min.js:4
organizrAPI2 @ functions.js?v=74197052808e7345a29d222d7609ee2da2087fba:3745
(anonymous) @ custom.min.js?v=74197052808e7345a29d222d7609ee2da2087fba:1
dispatch @ jquery-2.2.4.min.js:3
r.handle @ jquery-2.2.4.min.js:3
trigger @ jquery-2.2.4.min.js:4
(anonymous) @ jquery-2.2.4.min.js:4
each @ jquery-2.2.4.min.js:2
each @ jquery-2.2.4.min.js:2
trigger @ jquery-2.2.4.min.js:4
oAuthSuccess @ functions.js?v=74197052808e7345a29d222d7609ee2da2087fba:8459
success @ functions.js?v=74197052808e7345a29d222d7609ee2da2087fba:8419
i @ jquery-2.2.4.min.js:2
fireWith @ jquery-2.2.4.min.js:2
z @ jquery-2.2.4.min.js:4
(anonymous) @ jquery-2.2.4.min.js:4
load (async)
send @ jquery-2.2.4.min.js:4
ajax @ jquery-2.2.4.min.js:4
poll @ functions.js?v=74197052808e7345a29d222d7609ee2da2087fba:8411
(anonymous) @ functions.js?v=74197052808e7345a29d222d7609ee2da2087fba:8433
setTimeout (async)
complete @ functions.js?v=74197052808e7345a29d222d7609ee2da2087fba:8433
i @ jquery-2.2.4.min.js:2
fireWith @ jquery-2.2.4.min.js:2
z @ jquery-2.2.4.min.js:4
(anonymous) @ jquery-2.2.4.min.js:4
load (async)
send @ jquery-2.2.4.min.js:4
ajax @ jquery-2.2.4.min.js:4
poll @ functions.js?v=74197052808e7345a29d222d7609ee2da2087fba:8411
(anonymous) @ functions.js?v=74197052808e7345a29d222d7609ee2da2087fba:8433
setTimeout (async)
complete @ functions.js?v=74197052808e7345a29d222d7609ee2da2087fba:8433
i @ jquery-2.2.4.min.js:2
fireWith @ jquery-2.2.4.min.js:2
z @ jquery-2.2.4.min.js:4
(anonymous) @ jquery-2.2.4.min.js:4
load (async)
send @ jquery-2.2.4.min.js:4
ajax @ jquery-2.2.4.min.js:4
poll @ functions.js?v=74197052808e7345a29d222d7609ee2da2087fba:8411
(anonymous) @ functions.js?v=74197052808e7345a29d222d7609ee2da2087fba:8433
setTimeout (async)
complete @ functions.js?v=74197052808e7345a29d222d7609ee2da2087fba:8433
i @ jquery-2.2.4.min.js:2
fireWith @ jquery-2.2.4.min.js:2
z @ jquery-2.2.4.min.js:4
(anonymous) @ jquery-2.2.4.min.js:4
load (async)
send @ jquery-2.2.4.min.js:4
ajax @ jquery-2.2.4.min.js:4
poll @ functions.js?v=74197052808e7345a29d222d7609ee2da2087fba:8411
(anonymous) @ functions.js?v=74197052808e7345a29d222d7609ee2da2087fba:8438
(anonymous) @ jquery-2.2.4.min.js:2
i @ jquery-2.2.4.min.js:2
fireWith @ jquery-2.2.4.min.js:2
e.<computed> @ jquery-2.2.4.min.js:2
success @ functions.js?v=74197052808e7345a29d222d7609ee2da2087fba:8374
i @ jquery-2.2.4.min.js:2
fireWith @ jquery-2.2.4.min.js:2
z @ jquery-2.2.4.min.js:4
(anonymous) @ jquery-2.2.4.min.js:4
load (async)
send @ jquery-2.2.4.min.js:4
ajax @ jquery-2.2.4.min.js:4
getPlexOAuthPin @ functions.js?v=74197052808e7345a29d222d7609ee2da2087fba:8369
PlexOAuth @ functions.js?v=74197052808e7345a29d222d7609ee2da2087fba:8391
oAuthStart @ functions.js?v=74197052808e7345a29d222d7609ee2da2087fba:8471
onclick @ (index):1
custom.min.js?v=74197052808e7345a29d222d7609ee2da2087fba:1 Uncaught TypeError: Cannot read property 'response' of undefined
    at Object.<anonymous> (custom.min.js?v=74197052808e7345a29d222d7609ee2da2087fba:1)
    at i (jquery-2.2.4.min.js:2)
    at Object.fireWith [as rejectWith] (jquery-2.2.4.min.js:2)
    at z (jquery-2.2.4.min.js:4)
    at XMLHttpRequest.<anonymous> (jquery-2.2.4.min.js:4)
```

IMAGES BEFORE EDIT:

![owrXOxW6JK](https://user-images.githubusercontent.com/1261305/92337347-3191cf00-f0a9-11ea-9f12-3905a65f8fba.png)
![eOrTHq76Cg](https://user-images.githubusercontent.com/1261305/92337345-30f93880-f0a9-11ea-8ff7-19fe74ba52f6.png)
![wtSSUItUr8](https://user-images.githubusercontent.com/1261305/92337348-3191cf00-f0a9-11ea-93ef-1f612e413a91.png)
![1bA3hsfZtO](https://user-images.githubusercontent.com/1261305/92337343-3060a200-f0a9-11ea-9ca4-3513e5845ef8.png)

**Comment by DunklerPhoenix** [comment]
It seems to be the 2FA. I found a device where I was logged in and disabled the 2FA for my account. Now I can login normally again, but if I enable 2FA it breaks again.

**Comment by causefx** [comment]
let me test 2fa locally...
thanks for letting me know.

**Comment by causefx** [comment]
https://l.sonflix.com/5a/2372

seems to have worked here... can you check org logs?

could i remote in and check what error you got as well?

**Comment by DunklerPhoenix** [comment]
https://console.kartoffel.cloud/
DEMOUSER
DEMOUSER

I can't give you direct access, but you can take a look via teamviewer if you want.

**Comment by DunklerPhoenix** [comment]
There are also some design problems with my instance. I'll try to backup config & db and try to import them into a new instance first.

**Comment by DunklerPhoenix** [comment]
I created a new separate instance of organizr: 
https://#.cloud traefik proxy
http://#.cloud:23554  direct (EDIT)

EDIT: Removed error handler in proxy

Its not configured, but I tested it and it also happens with this one. Just create a user, enable 2FA and then try to login with enabled 2FA (in separate incognito window)
There is also a design problem while enabling the 2FA. The 2FA windows appears behind the config window.

Personal Settings:
German, Chrome 86 / FireFox 75

Links to LogFiles:
http://#.cloud/css/access.log (nginx)
http://#.cloud/css/error.log (nginx)
http://#.cloud/css/status_errors.log (nginx)
http://#.cloud/css/php.error.log (php)

**Comment by causefx** [comment]
anydesk would be ideal. i’m available on discord.  

i will try these credentials tho. 
Sent from my iPhone

**Comment by causefx** [comment]
2 things...

Try logging in locally - not using your proxy and see if 2FA works...

Is traefik overwriting error pages?  it seems the 422 code is being taken over by a 404 page with a ghost on it.

**Comment by DunklerPhoenix** [comment]
> anydesk would be ideal. i’m available on discord. i will try these credentials tho. Sent from my iPhone

can you please delete the address in your message? I changed the post above completely with another address. ( https://github.com/causefx/Organizr/issues/1458#issuecomment-687991505 )
You can try it with the instance in this comment (locally or proxy). It's the same problem.

The error 404 was my first thought, but it will throw if you make a GET request to the /api/v2/login . With POST there is no 404. It seems only to accept POST Requests https://github.com/causefx/Organizr/blob/v2-develop/api/v2/routes/login.php

I think I will be online for RemoteControl in 12-13 hours

**Comment by DunklerPhoenix** [comment]
My added middleware in traefik https://docs.traefik.io/middlewares/errorpages/ was the problem. Now I'm using the "Enable Traefik Auth Redirect" option under Organizr -> System Settings -> Main -> Security. Works like a charm
