### ISSUE TITLE
Splash Screen - change background Image

### ISSUE THREAD

**Issue by Soneji** [causefx/Organizr#1459]
###### Operating System:Ubuntu 
<hr>

##### Problem Description:

Maybe I'm missing something, but I can't figure out how to change the splash screen background picture. It always shows as a picture of a laptop. I have tried to find this in the documentation, but without avail. 
<hr>

**Comment by causefx** [comment]
its the same as login wallpaper

sorry about that

**Comment by Soneji** [comment]
Oh, right. Thank you!
