### ISSUE TITLE
http:// should be implied if not specified

### ISSUE THREAD

**Issue by wickedshrapnel** [causefx/Organizr#146]
First I would like to say that Organizer is awesome. Great job! 

Added all my sites using the URL I would normally use in a browser to access them. www.name.com
They show up on the left hand side but when I click on each one nothing is displayed in the main area of the page. I can see the URL at the top change with the #name extension but the page does not display and I don't get any errors. Troubleshooting I added http://www.name.com and the websites then display. I can see this being a common issue so it would be nice for the application to except website names without the http:// specified maybe hardcode the http:// into the URL field

**Comment by SgtBatten** [comment]
Works fine for me without typing http in. Must be something else playing funny buggers

**Comment by causefx** [comment]
that's odd.  I will take a look into this.

**Comment by fryfrog** [comment]
If http:// or https:// was hard coded, it would break using a reverse proxy. For example, my Sonarr entry is just '/sonarr' because I can access it through reverse proxy.

**Comment by causefx** [comment]
i'll try and write a function that will read the url and make the appropriate URL based of the host and connection.

**Comment by causefx** [comment]
will look into this later
