### ISSUE TITLE
Auth Proxy Whitelist isn't working properly

### ISSUE THREAD

**Issue by rv10guy** [causefx/Organizr#1460]
###### Operating System: Ubuntu
<hr>

##### Problem Description:
The only value that seems to work for Auth Proxy Whitelist is 0.0.0.0/0

When I try limiting it down it shows fails verification in the logs. 

The exact log message I am getting are:

Auth Proxy Function - Starting Verification for IP: 173.185.17.92 for request on: 172.18.0.12 against IP/Subnet: 173.185.19.1/24 [Execution Time: 22.7ms]

Auth Proxy Function - IP: 173.185.17.92 has failed verification [Execution Time: 39.6ms]

<hr>

##### Reproduction Steps:
Nothing entered into Auth Proxy Whitelist except 0.0.0.0 works. However if I put 0.0.0.0/0 it seems to work every time.

<hr>

#### Errors on screen?  If so paste here:

```

```

**Comment by HalianElf** [comment]
You're misunderstanding what that setting is for. That setting is to limit what the header can come from which in your case looks to be a docker network, meaning you'd want to set it to 172.18.0.0/16.

**Comment by rv10guy** [comment]
@HalianElf Thanks. I appreciate the clarification.
