### ISSUE TITLE
Minor discrepancy in documentation

### ISSUE THREAD

**Issue by YouveGotMeowxy** [causefx/Organizr#1461]
Just came across this while upgrading my container and thought I'd point it out in case it slipped by anyone.

https://github.com/Organizr/docker-organizr#migration

![image](https://user-images.githubusercontent.com/39491297/92554182-595c7080-f22a-11ea-89c0-70ffd78aa855.png)

https://docs.organizr.app/books/setup-features/page/organizr-20--%3E-21-migration-guide

![image](https://user-images.githubusercontent.com/39491297/92554221-6ed19a80-f22a-11ea-993b-58d7007543f3.png)

One page says to use "dev", the other says "v2-develop"

I haven't tried to see if one works and the other doesn't, or they both work, but just thought it might be worth a mention.

**Comment by Roxedus** [comment]
They both work, I like my shorthand flags 😄

**Comment by YouveGotMeowxy** [comment]
I'm just wondering if it might cause a little bit of unnecessary confusion for users. I know I was mildly confused, which is why I came to post about it here. :)
