### ISSUE TITLE
[Feature Request] TDarr Homepage Intergration

### ISSUE THREAD

**Issue by MMagTech** [causefx/Organizr#1462]
Wondering the possibility of adding https://github.com/HaveAGitGat/Tdarr as an option for the home screen?  Not sure if it would be a limitation on the Tdarr end.  It seems like Organizr has a  lot of functionailty build in for monitoring media automation and Tdarr would be a nice addition.  Would love to have the ability to see how many transcodes are running via home screen.  Currently have it as a tab on the sidebar.  Thanks for the excellent app and all the hard work you have put into it.

**Comment by Roxedus** [comment]
We would have to resort to scraping, as Tdarr don't have an api
