### ISSUE TITLE
question regarding dockstarter (dockerstarter.com) for my configuration using letsencrypt

### ISSUE THREAD

**Issue by tvann2182** [causefx/Organizr#1463]
###### Operating System: Ubuntu
<hr>

##### Problem Description:
Question regarding utilizing dockstarter.com and letsencrypt container pushing all nginx configs for apps
i use dockstarter to configure all my apps and keep them current, my question is whether or not i need to update what is currently listed or uncomment any sections for its config moving forward with the new api as i never uncommented it and its working fine so far. below is how it is currently listed in my nginx letsencrypt docker config

# In order to use this location block you need to edit the default file one folder up and comment out the / location

location / {
    # enable the next two lines for http auth
    #auth_basic "Restricted";
    #auth_basic_user_file /config/nginx/.htpasswd;

    # enable the next two lines for ldap auth, also customize and enable ldap.conf in the default conf
    #auth_request /auth;
    #error_page 401 =200 /login;

	
    include /config/nginx/proxy.conf;
    resolver 127.0.0.11 valid=30s;
    set $upstream_organizr organizr;
    proxy_pass http://$upstream_organizr:80;
}

#location ~ /auth-(admin|user) {
#    # This is used for Organizr V1
#    internal;
#    include /config/nginx/proxy.conf;
#    resolver 127.0.0.11 valid=30s;
#    set $upstream_organizr organizr;
#    proxy_pass http://$upstream_organizr:80/auth.php?$1;
#    proxy_set_header Content-Length "";
#}

#location ~ /auth-([0-9]+) {
#    # This is used for Organizr V2
#    internal;
#    include /config/nginx/proxy.conf;
#    resolver 127.0.0.11 valid=30s;
#    set $upstream_organizr organizr;
#    proxy_pass http://$upstream_organizr:80/api/?v2/auth&group=$1;
#    proxy_set_header Content-Length "";
#}

<hr>

##### Reproduction Steps:
edit my organizr.subfolder.conf to view current layout of container

<hr>

#### Errors on screen?  If so paste here:

```

```

**Comment by Roxedus** [comment]
All the required changes is done in our image, except the server auth, if you used that. You would need to change the organizr-auth.* file with the new location.

**Comment by tvann2182** [comment]
Rox, i get that everything is completed on orgs side, my question is do i need to uncomment those sections above as they have always been commented and i have not had a problem with utilizing organizr for over a year?

**Comment by Roxedus** [comment]
You dont need to do anything for the base config. If you enabled organizrs server auth, you need to adapt that. Your issue is malformed, so actually seeing your config is hard.

**Comment by tvann2182** [comment]
I have attached my actual lets encrypt config for organizr. I hope this helps with the malformation.
[organizr.subfolder.conf.zip](https://github.com/causefx/Organizr/files/5210343/organizr.subfolder.conf.zip)

**Comment by Roxedus** [comment]
So you do not use anything outside of the core setup, so you dont need to do anything.
