### ISSUE TITLE
Cant add any tabs. Every tab is blank

### ISSUE THREAD

**Issue by vikasunnava** [causefx/Organizr#1465]
###### Operating System: Ubuntu
<hr>

##### Problem Description:
I added a bunch of tabs for Plex, Sonarr and other applications. Any tab I go to I get the same client side error. The tab config is correct as the connection works, and I have homepage items setup which work well.

<hr>

##### Reproduction Steps:
Add tab to organize, and navigate to it.

<hr>

#### Errors on screen?  If so paste here:

On inspecting logs in the browser, this is what I see:
```
Failed to launch 'plex:32400' because the scheme does not have a registered handler.
```

**Comment by HalianElf** [comment]
Your tabs need to be full urls that are actually accessible. Organizr doesn't do any proxying so your docker hostname isn't going to work as a tab url. (You can keep them for the homepage) You would also need scheme for anything that's not a subfolder (http:// or https://)

Also switch over to the new docker image (organizr/organizr)

**Comment by vikasunnava** [comment]
Thank you. I didn't realize the config needs to be formatted different for tabs vs desktop. It makes sense why.

Updated the image, and thanks for your help.
