### ISSUE TITLE
Ombi won't accept admin password input

### ISSUE THREAD

**Issue by zin105** [causefx/Organizr#147]
When trying to log into my admin account on Ombi, I can enter my username, but after entering my password and pressing Sign In nothing happens.

**Comment by causefx** [comment]
mobile or browser?

**Comment by zin105** [comment]
Browser.

**Comment by causefx** [comment]
anything in the browser log?

**Comment by fryfrog** [comment]
FWIW, I just setup Organizr and added Ombi, behind an apache reverse proxy. It works fine.

**Comment by zin105** [comment]
`POST http://192.168.1.217:3579/ombi/userlogin/password 500 (Internal Server Error)
(anonymous) @ VM104:2
send @ jquery-2.2.1.min.js:4
ajax @ jquery-2.2.1.min.js:4
(anonymous) @ userlogin:185
dispatch @ jquery-2.2.1.min.js:3
r.handle @ jquery-2.2.1.min.js:3
userlogin:204 Object {readyState: 4, responseText: "{"statusCode":500,"message":"Something went horrib… context, ErrorPipeline pipeline, Exception ex)"}", responseJSON: Object, status: 500, statusText: "Internal Server Error"}`

**Comment by causefx** [comment]
that's odd, that error is from the ombi side.  can you login straight from http://192.168.1.217:3579/ombi/

**Comment by zin105** [comment]
Yes, no problem at all.

sön 12 mars 2017 kl 20:19 skrev causefx <notifications@github.com>:

**Comment by causefx** [comment]
can you try clearing cookies and cache please?

**Comment by zin105** [comment]
No difference.

**Comment by causefx** [comment]
I honestly dont know why it would be preventing you from logging in as we dont interact with it at all, it just displays the page.

**Comment by elmerfdz** [comment]
@zin105 Do you reverse proxy Ombi? the Ombi link used on Organizr, is that a reverse proxied link?

**Comment by zin105** [comment]
I use reverse proxy for external access, but Organizr was pointed directly to the web interface of Ombi.

Anyways I gave up on Organizr sorry. Had too many little problems like this one so I'm back to browser bookmarks. Great tool though.

**Comment by pyrostic** [comment]
Just an outside of the box question.  You're using your Ombi/plex password
not your organizr password on ombi right?
