### ISSUE TITLE
qBittorrent wrong status in homepage (v2-dev)

### ISSUE THREAD

**Issue by darkknight6722** [causefx/Organizr#1470]
###### Operating System: Ubuntu
<hr>

##### Problem Description:

In qBittorrent homepage item, if a torrent is force stared it shows torrent status as "complete" even though it is still downloading.
If its just started normally, it shows downloading.
(qBittorrent-nox  v4.2.5)

<hr>

##### Reproduction Steps:

<hr>

#### Errors on screen?  If so paste here:

```
First three is force started
Last one just started normally


```
![screenshot-8f721b74](https://user-images.githubusercontent.com/68375196/94226002-1aaa0400-ff14-11ea-9875-927542f84816.jpg)

**Comment by causefx** [comment]
unfortunately i do not have qbit to test and fix atm

**Comment by darkknight6722** [comment]
size also varies between qbittorrent client and organizr homepage
