### ISSUE TITLE
Google SSO iframe not working

### ISSUE THREAD

**Issue by IIIdefconIII** [causefx/Organizr#1472]
###### Operating System: Docker
<hr>

##### Problem Description:
      - "traefik.http.routers.organizr-rtr.middlewares=chain-oauth@file" # Google OAuth 2.0
in Traefik, all website are ok and are working with SSO, anyway in Organizr i need to login again.
But as Google doesnt allow iFrame i cannot use it. Is there any option i can use to get around this?
I couldnt find a forum website so i posted it here.

<hr>

##### Reproduction Steps:
Open organizr, login with SSO
Then open a organizr tab like sonarr and i need to login to a other tab first before it works.

<hr>

#### Errors on screen?  If so paste here:

```
accounts.google.com heeft de verbinding geweigerd.
```

**Comment by causefx** [comment]
@Roxedus you know anything about this?

**Comment by Roxedus** [comment]
I don't think google would be cool with bypassing CSP

**Comment by causefx** [comment]
I'm sorry - I'm not quite sure what I can do about this.
