### ISSUE TITLE
Moved Organizr to different Server (Fresh install) - Reverse Proxy no longer working

### ISSUE THREAD

**Issue by CozyRocket** [causefx/Organizr#1476]
###### Operating System: Ubuntu
<hr>

##### Problem Description:
Previously, I had my organizr installed on my ClearOS Firewall (CentOS), I just moved it over to its own stand-alone container inside Proxmox running Ubuntu 20.04, installed using the automated installer.

I've transferred over my DB and config.php file as per the instructions on the website I had some issues, about the Token not being right, after some investigation, figured out the files weren't owned correctly, a quick chown later and its all working, or so I thought.

About 3 of my 15 or so reverse proxies are working, all the rest return a error 500. However, these worked on my previous install, and to rule out me going crazy I fired up the old install and yes, they still work. Now I also copied all my .conf files for all my applications, un-commented it in the .conf file to include /conf.d/apps/*.conf but it still just throws up an 500 error. I'm not exactly sure what is causing the issue.

Best thing I can see inside the Console is Uncaught TypeError (see below)

<hr>

##### Reproduction Steps:
1. Have Organizr installed on ClearOS (Centos)
2. Fire up a Ubuntu VM inside proxmox
3. Install Organizr using the automated script
4. Copy the DB, config.php and all .conf from nginx
5. Most of them return error 500

<hr>

#### Errors on screen?  If so paste here:
```
Uncaught TypeError: Cannot read property 'SimpleBar' of undefined
    at new t (simplebar.js:10)
    at tabProcess (functions.js?v=2.0.650:2724)
    at Object.<anonymous> (functions.js?v=2.0.650:9258)
    at i (jquery-2.2.4.min.js:2)
    at Object.fireWith [as resolveWith] (jquery-2.2.4.min.js:2)
    at z (jquery-2.2.4.min.js:4)
    at XMLHttpRequest.<anonymous> (jquery-2.2.4.min.js:4)
```

Is there anything I should be looking for?

**Comment by HalianElf** [comment]
Check your nginx error log. It should say why you're getting the error 500.

**Comment by CozyRocket** [comment]
I've now checked it and I can see that it returns "auth request unexpected status: 302" I'm not sure how I would fix this, I do note, my previous install was a v1 API and now it is v2 API

**Comment by HalianElf** [comment]
Based on the version number you posted, you'll need to change the auth rewrite back to the v1 api url: `/api/?v1/auth&group=$1` until Cause is comfortable that all the bugs are out in v2.1 to merge it.

**Comment by CozyRocket** [comment]
After changing all instances of the v2 back to ?v1 the auth request no longer works and everything is just opened.

**Comment by HalianElf** [comment]
Are you checking from incognito or at least being logged out? It being open is expected if you have a cookie.

**Comment by CozyRocket** [comment]
Tried from different browser and incognito, still allows direct connecting like the auth doesn't exist.

**Comment by HalianElf** [comment]
You didn't remove the `auth_request` for troubleshooting or enable the Auth Debug toggle in the Organizr settings, right? That's the only other reason I can think of to explain that.

**Comment by CozyRocket** [comment]
Nope, haven't done either. I had a similar issue on my ClearOS box when trying to convert over to v2 api and auth where it just opened everything up. The only reason why some of my stuff is working is because there is no auth_request inside the config file for that service.

**Comment by CozyRocket** [comment]
Issue has been fixed by HalianElf on discord.

If anyone else is having issues, ensure read the doco and not just change v2 to ?v1.
