### ISSUE TITLE
Healthchecks io doesn't show any items on homepage

### ISSUE THREAD

**Issue by bastienboutonnet** [causefx/Organizr#1481]
###### Operating System: Raspbian
<hr>

##### Problem Description:
New install of organizr from the official docker image healthchecks is configured with proper API keys, I can see it load in the homepage but it doesn't display anything although I have some services in there.

It used to work on the previous version of organizr really well. This is a fully new install pointing to a totally new data directory so I don't foresee issues with migration

<hr>

##### Reproduction Steps:
new install, new healthchekcs API keys. I'm really puzlled

<hr>

**Comment by causefx** [comment]
I believe it has to do with Healthchecks changing cert providers this week.  I will continue to look into it.

**Comment by bastienboutonnet** [comment]
Could be hehe I had not used organizr for a long while so I have no recent reference point. Thanks a lot for checking, let me know if I can help @causefx

**Comment by GAS85** [comment]
As per #1488 it is Certificate issue:
```
HealthChecks  Connect Function - Error: cURL error 60: SSL certificate problem:  unable to get local issuer certificate [Execution Time: 116.3ms]

**Comment by causefx** [comment]
fixed in dev

**Comment by bastienboutonnet** [comment]
@causefx would it be a good idea for me to try spinning up a docker using the dev branch instead of master? Or do you have plans to merge this fix to master down the line?

**Comment by causefx** [comment]
This was merged to master already.
