### ISSUE TITLE
auth_request with nginx throws 404 Error with api-v2

### ISSUE THREAD

**Issue by Pfuenzle** [causefx/Organizr#1482]
###### Operating System: Official Docker Image
<hr>

##### Problem Description:

I tried to protect a service with a subdomain with the ServerAuth API from organizr. I followed the steps, but I cant get it to work, nginx (my reverse proxy) always throws a 500 Internal server error, because the organizr api-v2 throws an error 404. (I pasted the whole error below). 
When accessing the API directly in the browser via "<ip>/api/v2/auth" it just responds with "File not found". Im using the unchanged, up-to-date dockerimage from organizr/organizr and nginx as a reverse proxy.

From looking at the comments on the docs page for ServerAuth, Im not the only one with the 404 error.

Here is my nginx config:
```
server {
        server_name <redacted>;
        location / {                
                auth_request /auth-0;
                proxy_pass http://127.0.0.1:1447;               
                add_header X-Frame-Options "SAMEORIGIN";
                proxy_set_header Host $host;                
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;        
        }

        location ~ ^/auth-(.*) {
                proxy_pass http://127.0.0.1:9983/api/v2/auth?group=$1;                
                proxy_pass_request_body off;
                proxy_set_header Content-Length "";        
        }

    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/dl.blyatflix.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/dl.blyatflix.com/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

}
server {
    if ($host = <redacted>) {
        return 301 https://$host$request_uri;
    } # managed by Certbot

    server_name <redacted>;
    listen 80;
    return 404; # managed by Certbot 
}
```
<hr>

##### Reproduction Steps:

1. Make subdomain config in nginx
2. Enable auth_request in config
3. Error 404
<hr>

#### Errors on screen?  If so paste here:

```
2020/10/26 19:41:17 [error] 5801#5801: *7 auth request unexpected status: 404 while sending to client, client: <IP>, server: <domain>, request: "GET / HTTP/1.1", host: "<domain>"
```

**Comment by Roxedus** [comment]
V2 api has not arrived to master yet.

**Comment by Pfuenzle** [comment]
Does it not matter that im using  the v2-master branch?
If so, im sorry for this issue, it said in the organizr news that the changes to API v2 will be merged 2nd of October.
Also, I looked into the docker container under <dockerdata>/nginx/site-confs/default, and there is only a location redirect for API v2, and none for API v1.

```
location /api/v2 {
    try_files $uri /api/v2/index.php$is_args$args;
  }
```

But still thanks, for your answer, im gonna use v1 then.

**Comment by tronyx** [comment]
The changes haven't been merged into the master branch yet. We decided to push off that date, as you can see by no update being available to you within your Organizr instance, to do further testing.

**Comment by causefx** [comment]
Changes are in master now.
