### ISSUE TITLE
User list error

### ISSUE THREAD

**Issue by jendru214** [causefx/Organizr#1487]
###### Operating System: Windows
<hr>

I cought one error when looking at user list
go to users, jump to the second page, change the view amount to for example 180 (so there is no page 2 anymore), boom you cant go back to page 1 and you see an empty page. You can only change view back to for example 10 users, go back to 1st page change back to 180

<hr>

##### Reproduction Steps:
Do the above :D 

<hr>

#### Errors on screen?  If so paste here:

```
![image](https://user-images.githubusercontent.com/67014283/97639771-89acd800-1a3f-11eb-8625-58d0ed0efa21.png)

```

**Comment by causefx** [comment]
hmmmm thanks!  no to think of a way to fix this.... lol

**Comment by jendru214** [comment]
I guess something needs to count the pages after the change and go to the last one?
