### ISSUE TITLE
Error loading site after new update

### ISSUE THREAD

**Issue by Cookie-Monster-Coder** [causefx/Organizr#1490]
###### Operating System: Ubuntu
<hr>

##### Problem Description:
<img width="955" alt="Screenshot 2020-10-30 174005" src="https://user-images.githubusercontent.com/53286741/97762719-67ff2f80-1ad7-11eb-844f-b8c870d9bbb4.png">

**Comment by Roxedus** [comment]
You need to include the php file in the api location

**Comment by Cookie-Monster-Coder** [comment]
>  php file in the api location

That did it, Thank you! Would it be safe to take it out of  ```location /```?

**Comment by Roxedus** [comment]
You need it in both

**Comment by HalianElf** [comment]
If you did the include just in the server block it should work but having it inside the root one makes you need it in both.

**Comment by Cookie-Monster-Coder** [comment]
> If you did the include just in the server block it should work but having it inside the root one makes you need it in both.

Ah, I see. Thank you!
