### ISSUE TITLE
docker fresh install, 502 error, config.php: No such file or directory

### ISSUE THREAD

**Issue by tserversbfs** [causefx/Organizr#1493]
docker fresh install:
docker run -d \
        --name=organizr \
        -v $HOME/srv_cfg/organizr:/config \
        -e PGID="${dGID}" -e PUID="${dUID}"  \
        -p 80:80 \
        -e fpm="true" \
        -e branch="v2-master" \
    organizr/organizr

with linuxserver/swag and
authelia/authelia

Both working as expected.

##### Problem Description:
fresh install: 502 Bad Gateway
loading as a subdomian reverse proxy using swags organzr template with both Authelia lines uncommented.

Looking through access logs, 300 lines long full of "http://mymail.mysite.com/" 
Went to that address and there is organizr.

#### Errors on screen?  If so paste here:

-------------------------------------
GID/UID
-------------------------------------
User uid:    1998
User gid:    1998
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 20-config: executing... 
[cont-init.d] 20-config: exited 0.
[cont-init.d] 30-setup: executing... 
[cont-init.d] 30-setup: exited 0.
[cont-init.d] 35-fpm: executing... 
Performing convertion to use sockets
[cont-init.d] 35-fpm: exited 0.
[cont-init.d] 40-install: executing... 
-----------------------
|  Updating Organizr  |
-----------------------
Updating files: 100% (4824/4824), done.
HEAD is now at 8a22b9fe Merge pull request #1485 from causefx/v2-develop
Already on 'v2-master'
Your branch is up to date with 'origin/v2-master'.
HEAD is now at 8a22b9fe Merge pull request #1485 from causefx/v2-develop
Already up to date.
sed: /config/www/organizr/api/config/config.php: No such file or directory
[cont-init.d] 40-install: exited 0.
[cont-init.d] 50-debug: executing... 
-----------------------
|     Kernel Info     |
-----------------------
Linux 8dd6bd156809 4.19.0-12-amd64 #1 SMP Debian 4.19.152-1 (2020-10-18) x86_64 GNU/Linux
Time Zone: Etc/UTC
[cont-init.d] 50-debug: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.

**Comment by HalianElf** [comment]
So it works if you go directly to it and not through SWAG? If so 502 means SWAG's nginx can't talk to Organizr and you'll need to fix your config so it can.

**Comment by tserversbfs** [comment]
> 
> 
> So it works if you go directly to it and not through SWAG? If so 502 means SWAG's nginx can't talk to Organizr and you'll need to fix your config so it can.

Why would it be under the subdomain of mymail? Is that in the docs?

I would have guessed it was at orgamizr.mysite.com in the same format as all my other dockers.

**Comment by HalianElf** [comment]
I don't know. That's completely dependent on your SWAG configs and has nothing to do with the Organizr container. You would need to provide your configs for us to be able to tell you.
