### ISSUE TITLE
Fails to update to 2.1

### ISSUE THREAD

**Issue by LecrisUT** [causefx/Organizr#1494]
###### Operating System: CentOS
<hr>

##### Problem Description:

Trying to update organizr to v2.1 either via github or the app's update tag fails to do so. It reports `Update successful`, however the version does not change and the update available still pops up.
<hr>

##### Reproduction Steps:

Update either via the web interface or `git pull`
<hr>

**Comment by tronyx** [comment]
Clear your cache, try incognito/private browser, etc.

**Comment by LecrisUT** [comment]
Sorry it seems I had some leftover `root` authenticated files that the updater failed to override, e.g. `index.php`.
That being said, now I am getting a few other issues configuring the tabs/homepage items, but I'm sure I will eventually figure those out

**Comment by tronyx** [comment]
Since the original issue seems to be resolved, which I am glad to hear, I am going to close this. If you need help you can open another issue or hop on our Discord Server.
