### ISSUE TITLE
[Feature Request] Multiple Download Client Support

### ISSUE THREAD

**Issue by djrarky** [causefx/Organizr#1495]
###### Operating System: CentOS
<hr>

Hi, 

Is it possible to have multiple download client support on the homepage?   
I'm wishing to have 2x instances of qbittorrent on the combined downloader. One for local, another for colo. 

I'd request on feathub, but it looks like the page has been taken down. 

Kind Regards,
Steve

**Comment by causefx** [comment]
We are moving Feature Requests away from **GitHub** and **FeatHub**.  We are now on **_FeatureUpvote_** which is located here:
### **https://vote.organizr.app**
If will also be a tab in Organizr update this Friday 22 Jan 2021


If this Feature Request was already on FeatHub it will get moved over within the week - no further action is needed.
If not, please create a new Feature Request at our new home so we can better keep track of them.
