### ISSUE TITLE
Menu overlaps main app/iFrame

### ISSUE THREAD

**Issue by 03c** [causefx/Organizr#1499]
###### Operating System: unRAID / Docker
<hr>

##### Problem Description:
Since version 2.1 the CSS seems slightly out. The menu is always covering up the iFrame/App page. I can submit a PR to fix this (based on my best guess as to what fixes it on my machine!), but wasn't sure if it is wide spread or just my machine.

See the below screenshot of what the settings page looks like. This is the same for all other apps as well.

![image](https://user-images.githubusercontent.com/996720/97886877-177b1280-1d21-11eb-921d-be33a8606b8f.png)

**Comment by HalianElf** [comment]
Are you using any custom CSS to pin the sidebar open or anything? It's supposed to overlap when open but drop back down to just the icons if you're not hovering over it.

**Comment by 03c** [comment]
That might make sense, it's been that long since I set it up! I'll check that out. Thanks.

**Comment by 03c** [comment]
I'll close this! Turns out I have loads of custom CSS that I don't remember adding!

Thanks again.
