### ISSUE TITLE
foreach() Errors

### ISSUE THREAD

**Issue by grokdesigns** [causefx/Organizr#15]
I get the following error on launching for the first time:
> Warning: Invalid argument supplied for foreach() in /usr/share/nginx/access/index.php on line 26

Then, when I try to register a user, I get:

> Warning: Invalid argument supplied for foreach() in /usr/share/nginx/access/user.php on line 501
Warning: Invalid argument supplied for foreach() in /usr/share/nginx/access/user.php on line 514
Warning: Invalid argument supplied for foreach() in /usr/share/nginx/access/user.php on line 522
Warning: Invalid argument supplied for foreach() in /usr/share/nginx/access/user.php on line 532
Warning: Invalid argument supplied for foreach() in /usr/share/nginx/access/index.php on line 26

This is running on NGINX. This subdirectory is the root of the URL I'm trying to use. www-data has ownership of 'users' and 'users.db'.

Thanks!

**Comment by causefx** [comment]
what version php do you have?  can you send some screenshots to see how it looks please?

**Comment by grokdesigns** [comment]
First time loading the page:
<img width="1680" alt="screen shot 2017-01-03 at 21 51 35" src="https://cloud.githubusercontent.com/assets/742476/21632020/119f928a-d1ff-11e6-9a14-903dbe622c52.png">

After trying to register the admin user:
<img width="1680" alt="screen shot 2017-01-03 at 21 51 56" src="https://cloud.githubusercontent.com/assets/742476/21632019/11996d10-d1ff-11e6-86bf-e7e00e3c5b39.png">

PHP Info:
<img width="942" alt="screen shot 2017-01-03 at 21 53 03" src="https://cloud.githubusercontent.com/assets/742476/21632018/1188d662-d1ff-11e6-9b61-f669a1e84785.png">

**Comment by causefx** [comment]
can you open up check.php and post that please?  I was pretty sure this would work with php 5.5

**Comment by grokdesigns** [comment]
Side note, type on "permissions" ;)
<img width="1619" alt="screen shot 2017-01-03 at 21 59 55" src="https://cloud.githubusercontent.com/assets/742476/21632107/01c20e0a-d200-11e6-9571-5dcfbae423aa.png">

**Comment by causefx** [comment]
Damn these chubby fingers of mine! lol.... 

this is odd as it supposed to show 2 directories.  the folder the index.php is in and the parent directory of that folder.

**Comment by grokdesigns** [comment]
I put the 'users' folder and 'users.db' file in a subdirectory one level above the web root. I edited the check.php to reflect these directories and get this:
<img width="1619" alt="screen shot 2017-01-03 at 22 11 14" src="https://cloud.githubusercontent.com/assets/742476/21632243/aec19926-d201-11e6-8c77-8a8b477d071c.png">

**Comment by causefx** [comment]
I wonder if it has to do with php 5.6 then... I will try installing that version of php later and try installing it. I have php 7 right now

**Comment by grokdesigns** [comment]
Awesome, thanks! If you can't reproduce, I'll install PHP 7 tomorrow and see how it goes.

**Comment by causefx** [comment]
Thanks for understanding.

**Comment by grokdesigns** [comment]
Update: I updated to PHP7 this morning and I'm still getting identical errors.
![capture](https://cloud.githubusercontent.com/assets/742476/21647603/3b82a656-d258-11e6-9305-38c65701d050.PNG)

**Comment by grokdesigns** [comment]
Disregard. This was my own dumb issue. When setting it up, I 'touch'ed the users.db file to make sure the permissions on the file were correct. So there was an empty users.db file that your script was trying to loop through (line 25). I deleted the users.db file and all was well upon first launch.

**Comment by causefx** [comment]
Crap. I wonder what the difference is between your setup and the rest.

**Comment by grokdesigns** [comment]
I think we posted at the same time. See my update for what the issue is!

**Comment by causefx** [comment]
Awesome!  i did not know you created a temp file.  Yea the webapp creates that file upon launch.
