### ISSUE TITLE
Feature Request: Uncategorized Items on Top and Bottom of Nav bar

### ISSUE THREAD

**Issue by davidnewhall** [causefx/Organizr#1500]
```
Organizr Version: V 2.x
Branch:           master
WebServer:        nginx
Operating System: unRAID
```
<hr>

##### Problem Description:

I'd like to put some links at the top of the nav bar, above folders, and some at the bottom below them. Instead of forcing the operator to choose top or bottom for all, can we replace the `Uncategorized` option with options for `Top` and `Bottom`?

For example, I want Plex and Ombi at the top, above my handful of folders. I want my support and status links at the bottom, below the folders.

**Comment by causefx** [comment]
not a bad idea - let me brainstorm about this

**Comment by causefx** [comment]
We are moving Feature Requests away from **GitHub** and **FeatHub**.  We are now on **_FeatureUpvote_** which is located here:
### **https://vote.organizr.app**
If will also be a tab in Organizr update this Friday 22 Jan 2021


If this Feature Request was already on FeatHub it will get moved over within the week - no further action is needed.
If not, please create a new Feature Request at our new home so we can better keep track of them.
