### ISSUE TITLE
Add transmission port status (open/close)

### ISSUE THREAD

**Issue by GAS85** [causefx/Organizr#1501]
###### Operating System: Ubuntu / docker
<hr>

##### Problem Description:
What about to add Transmission Port status, is it open or closed? 
You need to forward `{"method":"port-test"}` to `rpc` to see the status as 1 or 0.

<hr>

**Comment by neo-neo1** [comment]
Oddly specific, won't be useful to anyone

**Comment by DocDrydenn** [comment]
Useful to anyone using Transmission behind a VPN that may drop the forwarded port. PIA is an example (but only if you don't maintain the "keep-alive").

**Comment by causefx** [comment]
This is do-able - with that being said, please open up a feature request on our new feature site:

We are moving Feature Requests away from **GitHub** and **FeatHub**.  We are now on **_FeatureUpvote_** which is located here:
### **https://vote.organizr.app**
If will also be a tab in Organizr update this Friday 22 Jan 2021


If this Feature Request was already on FeatHub it will get moved over within the week - no further action is needed.
If not, please create a new Feature Request at our new home so we can better keep track of them.
