### ISSUE TITLE
Radarr connection since V2.1.60

### ISSUE THREAD

**Issue by fana13** [causefx/Organizr#1504]
###### Operating System: Debian Buster
<hr>

##### Problem Description:
Since new update 2.1.60 there is no connection to radarr in homepage
Not display in calendar

<hr>

##### Reproduction Steps:
Test radarr connection in homepage elements
<hr>

#### Errors on screen?  If so paste here:
"API Error
https://mydomain/radarr: Response was not JSON"
```

```

**Comment by HalianElf** [comment]
What version of Radarr?

**Comment by fana13** [comment]
Radarr Version 0.2.0.1504
In Organizr version 2.0.650, it was ok

**Comment by causefx** [comment]
i need to test with non v3

**Comment by rafael-maia09** [comment]
I’m having this same issue with the current organizr and radarr v3. This is happening for a couple of weeks now.  I think it was since I changed the docker image following the guide.

**Comment by HalianElf** [comment]
For Radarr v3 the test button is broken but the rest should work ok. Radarr v2 is currently broken.

Edit for more clarification: the test button is broken on all *arr homepage items. The version check to switch between the Radarr v2 and v3 API is broken, it's always hitting the v3 api endpoints.

**Comment by causefx** [comment]
fixed in dev. i’ll push soon
