### ISSUE TITLE
NGXConfigurator Settings cant loading

### ISSUE THREAD

**Issue by hjm79** [causefx/Organizr#1505]
Organizr Version: V 2.1.6.0
Branch: Master
WebServer: Nginx
Operating System: Ubuntu
<hr>

##### Problem Description:

<hr>

##### Reproduction Steps:

NGXConfigurator Settings cant loading
<hr>

#### Errors on screen?  If so paste here:

```
![9](https://user-images.githubusercontent.com/51636240/98454439-c303e700-21a7-11eb-8727-57cbc39f9f2b.png)

https://i.ibb.co/P5p4cJj/9.png

```

**Comment by causefx** [comment]
please remove the plugin for now, we need to update it for new API
