### ISSUE TITLE
Feature Request: Two Pi-hole Hompage Items

### ISSUE THREAD

**Issue by joelang1699** [causefx/Organizr#1506]
Any chance of implementing another Pi-hole Hompage Item?

I have two Pi-holes on my network: Primary & Secondary in case of crashes.

**Comment by HalianElf** [comment]
Comma separate them

Edit: it even says it when you expand the help text:
> Please make sure to use local IP address and port and to include '/admin/' at the end of the URL. You can add multiple Pi-holes by comma separating the URLs.

example: `http://172.27.1.7/admin,http://172.27.1.8/admin`

**Comment by joelang1699** [comment]
Silly me 😂

Now working!

Thanks for the help.
