### ISSUE TITLE
Cannot shutdown Organizr (Windows)

### ISSUE THREAD

**Issue by Erythros** [causefx/Organizr#1507]
###### Operating System: Windows 10
<hr>

##### Problem Description:

Since Organizr is running a web server, sometimes (not always) it blocks port 9000. Because I need this port for some stuff every now and then, I'd like to shut down Organizr and all its related processes. However, I haven't found any way to do s o
<hr>

Haven't found anything like this in the docs either. Therefore, is there a way to fully shutdown Organizr and unblock all the ports it uses? (I don't care too much about restarting it. I can just restart my computer).

**Comment by Roxedus** [comment]
Organizr is not a application in that sense, but it uses php, which the default port is 9000.

**Comment by Erythros** [comment]
Is there any way to kill it? Or what options do I have?

**Comment by Roxedus** [comment]
Sure, depends on how you installed it. It could be a service, just stopping it should suffice if that's the case.

**Comment by Erythros** [comment]
I installed it using the windows installer.
I haven't found any service. Or I didn't look for the right one.

**Comment by Roxedus** [comment]
Owi sets up a service for php, and calls it php

**Comment by Erythros** [comment]
Thanks, that worked. Didn't know what service to look for.
Could you also recommend the best way to uninstall organizr completely?

**Comment by Roxedus** [comment]
Organizr is still not a application, so you don't really uninstall it, but owi has a uninstaller script that removes the services, and nginx and php
