### ISSUE TITLE
Error 500 since update

### ISSUE THREAD

**Issue by titi69lpb** [causefx/Organizr#1508]
###### Operating System: Linux
<hr>

##### Problem Description:

Since last update - Error 503 Backend fetch failed
Backend fetch failed

Varnish cache server

error 500 follow
<hr>

##### Reproduction Steps:

just update throught organizr
<hr>

#### Errors on screen?  If so paste here:

```

```

**Comment by HalianElf** [comment]
Can you check your webserver logs for more details on the error 500?

**Comment by titi69lpb** [comment]
Hi, last error in php ww eror log:
 [09-Nov-2020 14:16:33 UTC] PHP Fatal error:  Cannot declare trait TautulliHomepageItem, because the name is already in use in /srv/data/web/vhosts/plexcrew.bricefeniello.tech/htdocs/api/homepage/tautulli.php on line 3

No error in apache

**Comment by HalianElf** [comment]
Do you have the the misspelled `tatutulli.php` in `/api/homepage`? If you do delete that and see if it fixes it.

**Comment by titi69lpb** [comment]
> Do you have the the misspelled `tatutulli.php` in `/api/homepage`? If you do delete that and see if it fixes it.

Yes i have it, i try and be back to you

**Comment by titi69lpb** [comment]
Perfect it works !! Thanks a lot 👍
