### ISSUE TITLE
Help needed on reverse proxy configuration for Ombi

### ISSUE THREAD

**Issue by Th0mC** [causefx/Organizr#1509]
###### Operating System: Raspberry Pi OS
<hr>

##### Problem Description:
Hi all,
I'm pretty sure this is not an issue but I'm working on it since 3 days and I'm lost. I need help ;).

I have organizr installed with a Let's Encrypt certificate.
So I'm trying to use reverse proxy to access Ombi with my DuckDns "domain".

Here is my configuration : 
- Ombi base URL : /ombi
- Nginx reverse proxy conf (/etc/nginx/conf.d/apps/ombiv3.conf)
>\# Ombi v3 Reverse proxy
>\# Be sure to set your Base-URL in Ombi v3
> location /ombi/ {
>     allow all
>     proxy_pass http://192.168.1.62:5000;
>     proxy_set_header Host $host;
>     proxy_set_header X-Forwarded-Host $server_name;
>     proxy_set_header X-Real-IP $remote_addr;
>     proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
>     proxy_set_header X-Forwarded-Ssl on;
>     proxy_set_header X-Forwarded-Proto $scheme;
>     proxy_read_timeout  90;
>     proxy_redirect http://192.168.1.62:5000 https://$host;
> }

When I accees to http://192.168.1.62:5000 --> No problem
When I try to access to https://<mydomain>.duckdns.org/ombi --> https://<mydomain>.duckdns.org/?error=404 --> https://<mydomain>.duckdns.org/#Settings
<hr>

Any help would be appreciate

**Comment by tronyx** [comment]
This is not an issue with Organizr, which is what this feature of GitHub is for. If you need help with the configuration for things not related to Organizr you can post on our [Subreddit](https://www.reddit.com/r/organizr/) or join our [Discord Server](https://organizr.app/discord).
