### ISSUE TITLE
jdownloader on Homepage not work curl failure 28

### ISSUE THREAD

**Issue by SkalCore** [causefx/Organizr#1510]
###### Operating System: Linux qnap
<hr>

##### Problem Description:
jdownloader api no access. Using rix1337/docker-myjd-api as docker Image. if i try to add the configuragation and test connection, then i get curl 28 failure. if i access the IP from myjd-api directly via Browser then i get the data without problems. 

<hr>

##### Reproduction Steps:
Access via browse works, this is the result it gaves me on screen:

{"downloader_state":"IDLE","grabber_collecting":false,"packages":{"downloader":false,"linkgrabber_decrypted":[{"done":"0","enabled":true,"eta":null,"filenames":["xxx.rar"],"hosts":["dd.com"],"linkids":[xxx],"links":1,"name":"xxx","path":"/opt/JDownloader/Downloads/xxx","percentage":0,"size":"379.33 MB","speed":null,"urls":"https://dd.com/xxx","uuid":xxx}],"linkgrabber_failed":false,"linkgrabber_offline":false},"update_ready":false}
mark the links with xxx,, you see it works as intended, only on organizr i have this problem.

<hr>

#### Errors on screen?  If so paste here:

```curl error 28, Connection timed out after 100001 milliseconds```

**Comment by causefx** [comment]
I can up the timeout so it doesn't fail.

**Comment by SkalCore** [comment]
here are the Timings if necessary: [pic 1](https://i.imgur.com/8tO1Kfc.png) and [pic 2](https://i.imgur.com/CaZTnl3.png)

**Comment by HalianElf** [comment]
If you run the curl from the organizr container with the url how you have it in the homepage item settings does it work?

**Comment by causefx** [comment]
yea those timing are super small - usually they are higher as jdownload site is slow responding....

my local instance...
![image](https://user-images.githubusercontent.com/16184466/98856880-788aa080-241b-11eb-8346-751c7b486380.png)

**Comment by SkalCore** [comment]
Running jdownloader headless on my qnap....so using only myjdownloader to connect. accessing with local IP

**Comment by HalianElf** [comment]
That doesn't really mean anything... You can do a `curl http://192.168.1.25:7069` or whatever url you're using in the homepage item settings from inside the container through the container station ui or using `docker exec` from cli. If you're getting that low of a response time from your browser it sounds more like the url you're trying to use for the homepage isn't able to be reached from inside the organizr container.

**Comment by SkalCore** [comment]
same internal IP Adress works well with sonarr and radarr for example...so this is not the main reason why it is not working. opened up the IP not via Curl or via cli. opend up in a normal Browser.and i tried it with my external ip. the same response time.

**Comment by causefx** [comment]
fixed in dev
