### ISSUE TITLE
issue with special character in password (rutorrent module) like in #1309

### ISSUE THREAD

**Issue by xfouloux** [causefx/Organizr#1511]
###### Operating System: Docker (organizr/organizr:latest)
<hr>

passwords with specials characters like # or ! break the authentication, see #1309 for same issue on other modules that was fixed.

Thanks.

**Comment by causefx** [comment]
I think i had some leftover code from before.  Let me fix

**Comment by causefx** [comment]
This was pushed to master yesterday, please let me know if it worked.

**Comment by xfouloux** [comment]
Thanks for the quick fix, pulling image right now =)

**Comment by xfouloux** [comment]
Indeed ! It works now =) !
I guess all the modules have the issue, maybe you wanna fix all before closing this issue ? or have an issue per module @causefx  ?

Thanks !

**Comment by causefx** [comment]
issue per module would work please.
