### ISSUE TITLE
Plex Auth login saying succesful but then reloads login page

### ISSUE THREAD

**Issue by Dazzler1985** [causefx/Organizr#1514]
Organizr Version: V 2.x
 Branch: Master
WebServer: Nginx
Operating System: Ubuntu
<hr>

Problem Description:
i have a user that authenticates with plex but when he does it says login succesful after that it does not go to the homepage but comes back to login again.

in console i found this  Autofocus processing was blocked because a document's URL has a fragment '#Homepage'.

<hr>

Reproduction Steps:
i cannot reproduce it on my own pc . 
i checked all his addons etc even a clean install of chrome and firefox.

<hr>

Errors on screen?  If so paste here:
Autofocus processing was blocked because a document's URL has a fragment '#Homepage'.
in console of browser.
```

```

**Comment by causefx** [comment]
you may be running into this problem:
https://docs.organizr.app/books/troubleshooting/page/plex-login-error---api-connection-failed

**Comment by Dazzler1985** [comment]
This can be closed @causefx your a hero it indeed solved the problem for my m8.
What is the reason why he has the problem but others don't ?

**Comment by causefx** [comment]
could be the SSO cookies being returned.  The values could be bigger or something.  I need to see about combing cookies on my end.
