### ISSUE TITLE
Wizard is failing as API Error: Not authorised

### ISSUE THREAD

**Issue by flying-sausages** [causefx/Organizr#1515]
###### Operating System: Ubuntu 20.04
<hr>

##### Problem Description:

After a clone, when setting up the wizard by hand, I cannot "finish" as the POST gets rejected with a 401. This works fine when I'm trying it out with this setup on a 2.0 commit (585d79fa7c2bce1d1241853fd382e70ab8bd8384). Note that the installer **does not attempt** to use the API during setup, that will all come later.
<hr>

##### Reproduction Steps:

```bash
sudo su
git clone https://github.com/swizzin/swizzin.git
git checkout fix-organizr-v21
dev=true bash swizzin/setup.sh #just make a user and skip all apps
touch /root/logs/swizzin.log && tail -f /root/logs/swizzin.log &
#press enter
box install nginx organizr
```

This installs this nginx block FYI
```nginx
location /organizr {
  root /srv;
  index index.php;
  try_files $uri $uri/ =404;

  location ~ \.php$ {
    include snippets/fastcgi-php.conf;
    fastcgi_pass unix:/run/php/php7.4-fpm.sock;
    fastcgi_param SCRIPT_FILENAME /srv$fastcgi_script_name;
    fastcgi_buffers 32 32k;
    fastcgi_buffer_size 32k;
  }

  location /organizr/api/v2 {
    try_files $uri /organizr/api/v2/index.php$is_args$args;
  }
}
```
<hr>

#### Errors on screen?  If so paste here:
Here is the form data being posted
![](https://media.discordapp.net/attachments/374662006701293569/777673017148571648/unknown.png)

Here is the console output
![](https://media.discordapp.net/attachments/374662006701293569/777678514802655262/unknown.png?width=2520&height=516)

Here is `nginx`'s `error.log` message which gets triggered when the form is submitted
```
2020/11/16 01:29:15 [error] 37579#37579: *698 FastCGI sent in stderr: "PHP message: PHP Notice:  Undefined index: organizrHash in /srv/organizr/api/classes/organizr.class.php on line 3572PHP message: PHP Warning:  file_put_contents(): Filename cannot be empty in /srv/organizr/api/classes/organizr.class.php on line 3532PHP message: PHP Warning:  file_put_contents(): Filename cannot be empty in /srv/organizr/api/classes/organizr.class.php on line 3532" while reading response header from upstream, client: 192.168.118.1, server: _, request: "POST /organizr/api/v2/wizard HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.4-fpm.sock:", host: "192.168.118.5", referrer: "https://192.168.118.5/organizr/"
```

**Comment by flying-sausages** [comment]
Start of the related Discord discussion https://discord.com/channels/374648602632388610/374662006701293569/777672914283266070

**Comment by causefx** [comment]
Can you try this without sending any payload?

**Comment by flying-sausages** [comment]
Already is the case. This just clones and does nginx. The function is declared but the actual call is not executed.

~L158 iirc

**Comment by causefx** [comment]
try with latest dev please

**Comment by flying-sausages** [comment]
Works for me on af66a04da16fa9744ff9245d9b71085db1bafde2 right now, thanks!
