### ISSUE TITLE
So Stuck - Migration 2 - 2.1

### ISSUE THREAD

**Issue by bixtool** [causefx/Organizr#1516]
Can someone please tell me which file and where to add this code in my Apache server to get v2.1 Working?  I am at a complete loss.

```
RewriteEngine On
RewriteBase /api/v2
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^ /api/v2/index.php [QSA,L
```

**Comment by tronyx** [comment]
Should go inside the `<Directory>` part of your `httpd.conf` file.

**Comment by bixtool** [comment]
I tried that but I get an Apache 500 internal error.

**Comment by causefx** [comment]
you're also missing a closing bracket on the last line...
```
RewriteRule ^ /api/v2/index.php [QSA,L]
```

**Comment by bixtool** [comment]
Thanks, I caught that typo when I pasted the code.

Still getting an Apache internal error

Here is the relevant portion of my httpd.conf file

```
DocumentRoot "C:/xampp/htdocs"
<Directory "C:/xampp/htdocs">
    #
    # Possible values for the Options directive are "None", "All",
    # or any combination of:
    #   Indexes Includes FollowSymLinks SymLinksifOwnerMatch ExecCGI MultiViews
    #
    # Note that "MultiViews" must be named *explicitly* --- "Options All"
    # doesn't give it to you.
    #
    # The Options directive is both complicated and important.  Please see
    # http://httpd.apache.org/docs/2.4/mod/core.html#options
    # for more information.
    #
    RewriteEngine On
    RewriteBase /api/v2
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteRule ^ /api/v2/index.php [QSA,L]

    Options Indexes FollowSymLinks Includes ExecCGI

    #
    # AllowOverride controls what directives may be placed in .htaccess files.
    # It can be "All", "None", or any combination of the keywords:
    #   AllowOverride FileInfo AuthConfig Limit
    #
    AllowOverride All

    #
    # Controls who can get stuff from this server.
    #
    Require all granted


</Directory>



```
I tried it at the end of the file as well.

Should this code be inside it's own <directory> listing?

**Comment by causefx** [comment]
Here is the local instance I setup that works:

Located @ `C:\Projects\Organizr-V2\`

```
DocumentRoot "C:\Projects"
<Directory "C:\Projects">
    Options Indexes FollowSymLinks
    AllowOverride None
    Require all granted
	RewriteEngine On
	RewriteBase /Organizr-V2/api/v2
	RewriteCond %{REQUEST_FILENAME} !-f
	RewriteCond %{REQUEST_FILENAME} !-d
	RewriteRule ^ /Organizr-V2/api/v2/index.php [QSA,L]
</Directory>
```

**Comment by bixtool** [comment]
Interesting development:

![image](https://user-images.githubusercontent.com/11953215/99455821-f3aff300-2902-11eb-9688-28439e0efd0a.png)

Here is my code:

```
DocumentRoot "C:\xampp\htdocs"
<Directory "C:\xampp\htdocs">
    Options Indexes FollowSymLinks
    AllowOverride None
    Require all granted
	RewriteEngine On
	RewriteBase /Organizr-2/api/v2
	RewriteCond %{REQUEST_FILENAME} !-f
	RewriteCond %{REQUEST_FILENAME} !-d
	RewriteRule ^ /Organizr-2/api/v2/index.php [QSA,L]
</Directory>

#
```

**Comment by causefx** [comment]
change the Capital O to lowercase in apache config
or change the lowercase O to uppercase in URL in browser

**Comment by bixtool** [comment]
Wow! You nailed it! Days & days of brooding. Thanks so much for your help. I've come to rely on Organizr....totally lost without it.

I'm hoping to have time to delve more deeply into the advanced features soon.

**Comment by causefx** [comment]
glad u got it sorted.

**Comment by 338lm** [comment]
Thank you so much! I couldn't figure this out from the tutorial either.. finally got it sorted!

**Comment by deejayexe** [comment]
![organizr](https://user-images.githubusercontent.com/26825471/102694329-36256200-4218-11eb-9602-58e41d53f346.jpg)

Hi! i try to update my organizr dashboard that which has been running smoothly for 1 year. Organizr is hosted on a main domain and redirected with .htaccess to a folder inside public_html, but I have tried the configuration for apache and I can't get it to work due to the error in the image

If i try to change **RewriteRule ^ /dashboard_organizr_v2/api/v2/index.php [QSA,L]** to full path (**/home/eybtgfxl/public_html/dashboard_organizr_v2/api/v2/index.php**) it redirect to https://www.domain.com/api/v2/status 

mydomain.com I have hidden it to avoid problems

What do you think may be because I am trying with the latest master version directly clean and then update my organizr

This is my .htaccess code from public_html to folder dashboard_organizr_v2 here is the installation.

```
RewriteEngine on

# En el siguiente codigo debe colocar el nombre de su dominio.

RewriteCond %{HTTP_HOST} ^(www.)?mydomain.com$

# Debes cambiar 'subdirectory' por el nombre del subdirectorio que desea apuntar.

RewriteCond %{REQUEST_URI} !^/dashboard_organizr_v2/

# No hacer ningun cambio en este codigo 

RewriteCond %{REQUEST_FILENAME} !-f

RewriteCond %{REQUEST_FILENAME} !-d

# Volvemos a insertar el nombre del subdirectorio que estamos utilizando.

RewriteRule ^(.*)$ /dashboard_organizr_v2/$1

# Cmabia *tudominio por el nombre de tu dominio

# Sustituye 'subdirectory' por el nombre del subdirectorio a utilizar 

RewriteCond %{HTTP_HOST} ^(www.)?mydomain.com$

RewriteRule ^(/)?$ dashboard_organizr_v2/index.php [L]



RewriteBase /dashboard_organizr_v2/api/v2
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^ /dashboard_organizr_v2/api/v2/index.php [QSA,L]

```

**Comment by deejayexe** [comment]
If i use it

```
RewriteBase /dashboard_organizr_v2/api/v2
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^ /home/eybtgfxl/public_html/dashboard_organizr_v2/api/v2/index.php [QSA,L]
```

https://www.domain.com/api/v2/update/migrate/2.1.0

```
response |  
-- | --
result | "error"
message | "Endpoint Not Found or Defined"
data |  
endpoint | "/api/v2/update/migrate/2.1.0"
method | "GET"

```



if I try to enter incognito mode it redirects me to this page from www.domain.com
https://www.domain.com/api/v2/status
```

  |  
-- | --
response |  
result | "success"
message | null
data |  
status | "ok"
api_version | "2.0"
organizr_version | "2.1.120"
```
