### ISSUE TITLE
Update 2.1.83 at 20%

### ISSUE THREAD

**Issue by bixtool** [causefx/Organizr#1519]
Update fails on Windows 10 from 2.1.74. Update Error: timeout. ESC key successfully cancels modal window.

**Comment by causefx** [comment]
going to need more info.  what does browser console say? yeah what does webserver logs say? what does organizr logs say?

**Comment by bixtool** [comment]
Checked today and both my test server and main both now show 2.1.83 installed.  Auto update?

**Comment by causefx** [comment]
Auto updates are only through docker containers. 

only if they are restarted or rebuilt tho.
