### ISSUE TITLE
[Feature Request] Homepage *arr History

### ISSUE THREAD

**Issue by issues-guy** [causefx/Organizr#1523]
Currently the NZBGet homepage item can show not only the Queue but the History as well.

Adding this same history tab to Sonarr, Radarr, Lidarr, etc would be a great addition!

**Comment by causefx** [comment]
it’s planned. thank you.

**Comment by causefx** [comment]
We are moving Feature Requests away from **GitHub** and **FeatHub**.  We are now on **_FeatureUpvote_** which is located here:
### **https://vote.organizr.app**
If will also be a tab in Organizr update this Friday 22 Jan 2021


If this Feature Request was already on FeatHub it will get moved over within the week - no further action is needed.
If not, please create a new Feature Request at our new home so we can better keep track of them.
