### ISSUE TITLE
Pull to refresh in chrome for android no longer working in 2.1.83

### ISSUE THREAD

**Issue by dshokouhi** [causefx/Organizr#1524]
###### Operating System: Windows 10
<hr>

##### Problem Description:

<hr>
Pull to refresh in chrome for android is no longer working with Organizr after the 2.1 update (I am not sure if it happened in a point release but it was working before the 2.1 update)

##### Reproduction Steps:

<hr>
1. load organizr in browser tab
2. Attempt to pull to refresh from the top down

The page scrolls instead of refreshing like all othe chrome tabs
#### Errors on screen?  If so paste here:

```
N/A on mobile
```

**Comment by causefx** [comment]
hmmmm. nothing changed in the UI in a very long time. i kinda have no clue how to even fix.

**Comment by dshokouhi** [comment]
sorry I forgot to mention asides from updating organizr to 2.1.x I also updated PHP to the latest 7.4.12 because I was on 7.1.x and it was no longer supported.  Dont know if that is the cause or not?

**Comment by causefx** [comment]
I think this is caused by the new scroll bars....  I will try and nail down
