### ISSUE TITLE
nginx auth error - migrating to 2.1

### ISSUE THREAD

**Issue by s0mm3rb** [causefx/Organizr#1528]
###### Operating System: docker container
<hr>

##### Problem Description:

I am migrating from local installed 2.0.375 to 2.1 inside docker
so far everything is working
except nginx authentication on redirected sub urls
I don't use subdomains

on the client I get: `500 Internal Server Error`
on the server: `[error] 372#372: *4 auth request unexpected status: 404 while sending to client`

I've updated the auth block to
```
location ~ /auth-(.*) {
	rewrite ^/auth-(.*) /api/v2/auth?group=$1;
}
```
redirected urls without authentication work (like ombi)
but on sonarr, radarr, ... it does not
my redirects look like this
```
location /container{
  auth_request /auth-0;
  proxy_pass http://<containerIP>:<port>;
  ...
}
```
organizr, ombi, radarr, all the containers are on the same docker subnet
I use `/auth-*` for all the containers 
<hr>

##### Reproduction Steps:
I've migrated the database and config from nginx/1.14.0 and organizr 2.0.375 on Ubuntu to the current v2 container

#### Errors on screen?  If so paste here:

```
[error] 372#372: *4 auth request unexpected status: 404 while sending to client, client: <removed>, server: <removed>, request: "GET /portainer/ HTTP/1.1", host: "<removed>", referrer: "https://<removed>/"
[error] 378#378: *12 auth request unexpected status: 404 while sending to client, client: <removed>, server: <removed>, request: "GET /tautulli/ HTTP/1.1", host: "<removed>", referrer: "https://<removed>/"
```

thanks

**Comment by causefx** [comment]
is organizr running at root?

if not paste organizr reverse proxy block

**Comment by s0mm3rb** [comment]
nope the container runs with 33 (www-data)
`docker create --name=organizr --network=<removed> --ip 172.18.0.32 -v /mnt/docker/organizr:/config -e PGID=33 -e PUID=33 -p 80:80 -p 443:443 -e fpm="true" --restart unless-stopped organizr/organizr`

I am using the included nginx server I have no reverse block for organizr
I modified the default config of the container to enable ssl and include the config for the other containers (in the site-confs/default):
```
# V0.0.4
server {
  listen 80 default_server;
  server_name <removed>;
  return 301 https://$server_name$request_uri;
}

server {
  listen 443 ssl;
  server_name  <removed>;
  root /config/www/organizr;
  index index.html index.htm index.php;

  location ~ /auth-(.*) {
    rewrite ^/auth-(.*) /api/v2/auth&group=$1;
  }

  client_max_body_size 0;

  # Real Docker IP
  # Make sure to update the IP range with your Docker IP subnet
  real_ip_header X-Forwarded-For;
  set_real_ip_from 172.18.0.0/16;
  real_ip_recursive on;

  ssl_session_cache  builtin:1000  shared:SSL:10m;
  ssl_protocols TLSv1.2;
  ssl_ciphers HIGH:!aNULL:!eNULL:!EXPORT:!CAMELLIA:!DES:!MD5:!PSK:!RC4;
  ssl_prefer_server_ciphers on;

  ssl_certificate /config/letsencrypt/live/<removed>/fullchain.pem; # managed by Certbot
  ssl_certificate_key /config/letsencrypt/live/<removed>/privkey.pem; # managed by Certbot

  # Deny access to Org .git directory
  location ~ /\.git {
    deny all;
  }

  location / {
    try_files $uri $uri/ /index.html /index.php?$args =404;
  }

  location /api/v2 {
    try_files $uri /api/v2/index.php$is_args$args;
  }

  location ~ \.php$ {
    fastcgi_split_path_info ^(.+\.php)(/.+)$;
    fastcgi_pass unix:/var/run/php7-fpm.sock;
    fastcgi_index index.php;
    include /etc/nginx/fastcgi_params;
    fastcgi_hide_header X-Powered-By;
    fastcgi_buffers 32 32k;
    fastcgi_buffer_size 32k;
  }
  include /config/nginx/containers.conf;
}
```

**Comment by tronyx** [comment]
The Organizr container is not designed for that. It's simply an application container. You should be using the LinuxServer.io SWAG container for your SSL and reverse proxy needs.

**Comment by s0mm3rb** [comment]
> The Organizr container is not designed for that. It's simply an application container. You should be using the LinuxServer.io SWAG container for your SSL and reverse proxy needs.

alright I'll try it
thanks

(don't really know why it shouldn't just work, I mean it's still nginx isn't it?)

is there an updated guide or will the one from 2017 still work?
https://blog.linuxserver.io/2017/11/28/how-to-setup-a-reverse-proxy-with-letsencrypt-ssl-for-all-your-docker-apps/

only found this in your docs
https://docs.organizr.app/books/tutorials/page/configuring-your-letsencrypt-reverse-proxy%28part-5%29

**Comment by jneljeff** [comment]
Forgive the resurrection of a closed thread, but I'm having the exact same issue since updating to SWAG and Organizr 2.1 and I'm not sure I understand what the solution here was.  Everything works fine if I comment out the /auth-#

Organizr is in it's own container and reverse proxied under a subdomain.  Sonarr and Radarr are subfolders under that same subdomain.

**RESOLUTION:**

OK, I'm an idiot.  For those who like me missed the note about the proxy_pass under auth location being different than the example or didn't understand what that meant, you have to replace organizr-upstream with your Organizr containers local IP and port number.

Replace this:

```
location / {
    root /opt/organizr/html;
    index index.php index.html index.htm index.nginx-debian.html;
    add_header X-Frame-Options "SAMEORIGIN";
    proxy_pass http://<organizr IP>:<port>
    location ~ ^/auth-(.*) {
        ## Has to be local ip or local DNS name or if Proxied use proxy address
        proxy_pass http://organizr-upstream/api/v2/auth?group=$1;
        proxy_pass_request_body off;
        proxy_set_header Content-Length "";
        }

  }
```
With this:

```
location / {
    root /opt/organizr/html;
    index index.php index.html index.htm index.nginx-debian.html;
    add_header X-Frame-Options "SAMEORIGIN";
    proxy_pass http://<organizr IP>:<port>;
        location ~ ^/auth-(.*) {
        ## Has to be local ip or local DNS name or if Proxied use proxy address
        proxy_pass http://<organizr IP>:<port>/api/v2/auth?group=$1;
        proxy_pass_request_body off;
        proxy_set_header Content-Length "";
        }

  }
```
