### ISSUE TITLE
your connection to this site is not fully secure

### ISSUE THREAD

**Issue by pavili0n** [causefx/Organizr#153]
Hi Again,

Once again I would like to say thanks for the great app ! Is there a donation feature ???

My current issue is HTTPS SSL when I browse to admin.my-domain.com which points to Organizr the site loads with HTTPS and a cert but shows "your connection to this site is not fully secure" if I browse any other of my sites that are nested within Organizr i.e. admin.my-site.com/sonarr the page shows fully secure.

Is this a problem with Organizr or something I have done from my end ?

**Comment by causefx** [comment]
one of your tabs is mixing content.  if you open your browser console it should tell you.  if you serve Organizr thru https, everything else has to be https...  it's probably one tab just loading an image from somewhere else.

**Comment by pavili0n** [comment]
Thanks for the quick response I will take a look now. I think it might be one of my logos.

@causefx on another note do you have a donations page ?

**Comment by causefx** [comment]
You're welcome.

and no sir, won't ever take a dime for any of this.  :+1:

**Comment by pavili0n** [comment]
quick update just incase anyone else stumble over this it was a logo that I had pointed to an external address 

@causefx surely someone can buy you a pint !!! Thanks any how for all the time and good work you have put into this it has made my life 10x easier.

**Comment by causefx** [comment]
:)  no worries!  knowing that you enjoy the app is good enough for me.
