### ISSUE TITLE
Results jackett on homepage are undefined

### ISSUE THREAD

**Issue by fana13** [causefx/Organizr#1531]
Organizr Version: 2.1.83
Branch: Master
WebServer: Nginx
Operating System: Debian Buster
<hr>

##### Problem Description:
Links of jackett results are undefined and links for download too

<hr>

##### Reproduction Steps:
On homepage, when i do a jackett search, the links of results and downloads are broken

<hr>

#### Errors on screen?  If so paste here:

```

```

**Comment by kriegalex** [comment]
I observed the same thing.

![Screenshot 2020-11-29 192749](https://user-images.githubusercontent.com/2486182/100550258-ff8fa380-3278-11eb-9274-4633cc06c48a.png)

**Comment by causefx** [comment]
i will fix this week

**Comment by causefx** [comment]
fixed in dev
