### ISSUE TITLE
Distances between the panels not equal

### ISSUE THREAD

**Issue by poiy23** [causefx/Organizr#1536]
###### Operating System: Unraid Docker
<hr>

##### Problem Description:
Hello
I have a small visual error on the homepage. It's nothing wild, but it bothers me. The distances between the different panels are not equal.
I would like to have the same distances everywhere.
I think that's how it should be .
I would be happy about an answer
With kind regards Poiy

<a href="https://ibb.co/qmN3CPC"><img src="https://i.ibb.co/qmN3CPC/myplex.png" alt="myplex" border="0"></a> <a href="https://ibb.co/CQRR759"><img src="https://i.ibb.co/CQRR759/myplex1.png" alt="myplex1" border="0"></a>

<hr>

##### Reproduction Steps:

<hr>

#### Errors on screen?  If so paste here:

```

```

**Comment by HalianElf** [comment]
I see you're using the Plex theme. Can you try with the default theme and make sure it's not just an issue with that theme?

**Comment by poiy23** [comment]
Yes, it was the Theme. I just change the order and  put a custom HTML-elemet inbetween.
Thanks for the fast response.
Topic can be closed

**Comment by HalianElf** [comment]
Sounds good. If you want to try to get it fixed the repo for that theme is here: https://github.com/Burry/Organizr-Plex-Theme
