### ISSUE TITLE
Cannot activate or deactivate Tab Icon apps

### ISSUE THREAD

**Issue by mamema** [causefx/Organizr#1537]
##### Problem Description:
I'm no longer able (dunno since when..) to enable or disable apps. Even though i click the correct buttons, a sucessful done message appears, but neither the enabled apps get disabled, nor get the disabled apps enabled. 

Nothing special in the logs about this. Also not in the Developer tools of the client browsers. tested with firefox/chrome

##### Reproduction Steps:
click on active column icons. nothing changes except the sucess message appear

**Comment by HalianElf** [comment]
Are you refreshing after enabling/disabling? It requires a page refresh to show up.

**Comment by causefx** [comment]
please let us know if what elf said helped you. thanks

**Comment by mamema** [comment]
no, refresh doesn't help. Cache cleaning, 3 browser brands tested

**Comment by causefx** [comment]
can you take a video of this happening?

**Comment by mamema** [comment]
sure, can i send you a onedrive link privately?

**Comment by causefx** [comment]
causefx at me dot com

**Comment by mamema** [comment]
latest docker image from yesterday.... nothing change. I can still not enable or disable icons

**Comment by causefx** [comment]
Was this installed from swizzin?

Edit: nvm - i see this docker.

**Comment by Procuria** [comment]
Hello ! I have the same problem here. Running on Docker, master branch, V. 2.1.120. I recorded an animated Screenshot and dropped it here in my self-hosted CryptPad. 
https://notes.dunst.be/file/#/2/file/9OUGz2yV5gU5jbstnHkrE9hs/

**Comment by causefx** [comment]
do either of you have opcache installed?

**Comment by Procuria** [comment]
Thank you for your rocket-fast reply. The host hasn't even PHP installed, so there is no opcache (I guess). The docker container is invoked with: 
`docker run -d --restart always  --name=organizr -v /home/dockervolumes/organizr:/config -p 8090:80 -e fpm=true organizr/organizr`

**Comment by causefx** [comment]
lemme test on the container further. 

Can you also check the permission of database?

**Comment by Procuria** [comment]
Check - there you go :) 
<img width="723" alt="2021-01-11_01h16_50" src="https://user-images.githubusercontent.com/37988494/104139326-fd0d8700-53aa-11eb-9e9f-8dd3f0e32caa.png">

**Comment by mamema** [comment]
I have also no opcache installed

Here's my compose file

> version: "3"
services:
  organizr:
    container_name: organizr
    cpu_shares: 50
    entrypoint:
      - /init
    environment:
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      - S6_REL=2.1.0.2
      - S6_ARCH=amd64
      - S6_BEHAVIOUR_IF_STAGE2_FAILS=2
      - TZ=Etc/UTC
      - 'PS1=$(whoami)@$(hostname):$(pwd)$ '
      - HOME=/root
      - TERM=xterm
      - fpm=true
      - branch=v2-master
      - PUID=1024
      - PGID=100
    hostname: organizr
    image: organizr/organizr:latest
    ipc: shareable
    labels:
      base.maintainer: christronyxyocum,Roxedus
      base.s6.arch: amd64
      base.s6.rel: 2.1.0.2
      maintainer: christronyxyocum,Roxedus
      org.label-schema.description: 'Baseimage for Organizr'
      org.label-schema.name: organizr/base
      org.label-schema.schema-version: 1.0
      org.label-schema.url: https://organizr.app/
      org.label-schema.vcs-url: https://github.com/organizr/docker-base
      org.opencontainers.image.created: 2020-12-24_23
      org.opencontainers.image.source: https://github.com/Organizr/docker-organizr/tree/master
      org.opencontainers.image.title: organizr/base
      org.opencontainers.image.url: https://github.com/Organizr/docker-organizr/blob/master/README.md
    logging:
      driver: db
      options: {}
    mac_address: 02:42:ac:11:00:13
    networks:
      bridge:
        aliases:
    ports:
      - 0.0.0.0:3000:80/tcp
    stdin_open: true
    tty: true
    volumes:
      - /volume1/docker/organizr/config:/config:rw
networks:
  bridge:
    external: true


My permissions are as you can see like the coresponding user on the host. this user has rw rights (PGID,PUID)

<img width="519" alt="Bildschirmfoto 2021-01-15 um 16 25 53" src="https://user-images.githubusercontent.com/18702616/104745513-7b24b180-574e-11eb-9a16-81457bc5cac3.png">

**Comment by causefx** [comment]
So it allows you to add tabs - just not update them?

**Comment by mamema** [comment]
partly it's just not possible to enable/disable. Other changes are possible.
Perhaps important: Clicking on Enable/Disable sets the  entry as homepage default entry instead of enable/disable

**Comment by causefx** [comment]
what the hell? can you setup another instance of organizr and give me access?

**Comment by Procuria** [comment]
Same like @mamema here ! Will (hopefully) set up an instance for you in the next hour. Thank you for your efforts !

**Comment by mamema** [comment]
you've got mail @causefx

**Comment by Procuria** [comment]
I think I have a clue - I could reproduce the error in the test instance with the plex-theme. When I switch back to organizr-theme all runs smooth. Will test it now in my prod-instance.

@causefx you've got mail 
@mamema are you using the plex theme too ?

**Comment by Procuria** [comment]
I can confirm - the issue is caused by the theme. See attached screenshot gif of my prod-instance.
![2021-01-23_22h56_03](https://user-images.githubusercontent.com/37988494/105615119-655a6080-5dce-11eb-8c65-23cda2b7544d.gif)

**Comment by causefx** [comment]
Thanks guys, you all were correct, it was the Plex theme...

For a temp fix: goto Settings > Appearance > Theme Css and paste this:

```
input[type="radio"] {
    min-width: 20px !important;
}
```
