### ISSUE TITLE
Organizr as a external proxy

### ISSUE THREAD

**Issue by hubbcaps** [causefx/Organizr#154]
While Organizr is fantastic in what it does, a good way to advance the functionality quite a bit would be to have it's default behavior be to load the saved tabs as though they are local to the network where organizr lives. Currently it tries the urls against whatever network you are on, i.e. a mobile network, work network, etc etc.

How I'd like it to work is to be able to hit it from where ever using my home address + specified port I've forwarded i.e. hubcaps.example.com:8080, and then when it attempts to hit the default pages IP+Port it looks for it locally relative to the Organizr installs network.

Could this be easily attainable?

**Comment by causefx** [comment]
I have been trying to find away how to do this for a very long time :/

**Comment by hubbcaps** [comment]
Could you point me to the portion of the code that actually handles loading the iframe for the selected resource? I'll see what I can do to implement, I've never touched front end dev, so I'm not sure where to look, but I might as well give it a swing.

**Comment by hubbcaps** [comment]
Nevermind, should of just searched in the first place. Taking a look.

**Comment by hubbcaps** [comment]
And so ends my foray into front end lol

Thought the iframes were handled by PHP, not javascript. Javascript is all ran on the local browser, so yeah, externalizing this isn't gonna happen via that method.

Glad I took a look and learned a bit though. Closing this out.

**Comment by causefx** [comment]
Yea. I've been searching for a long time. :/
