### ISSUE TITLE
Feature request: Exclude certain libraries from the plex Recently Added homepage item

### ISSUE THREAD

**Issue by jonathanturcotte** [causefx/Organizr#1540]
##### Problem Description:
As with #1534 , I have a library of music that I don't share with my users, and as a result would like to exclude from the recently added homepage item.

<hr>

The exact same fix used in #1534 would be perfect, just added to the recently added settings.

**Comment by causefx** [comment]
We are moving Feature Requests away from **GitHub** and **FeatHub**.  We are now on **_FeatureUpvote_** which is located here:
### **https://vote.organizr.app**
If will also be a tab in Organizr update this Friday 22 Jan 2021


If this Feature Request was already on FeatHub it will get moved over within the week - no further action is needed.
If not, please create a new Feature Request at our new home so we can better keep track of them.

**Comment by causefx** [comment]
done in dev
