### ISSUE TITLE
Feature request: Jellyfin Invite through Organizr

### ISSUE THREAD

**Issue by Cookie-Monster-Coder** [causefx/Organizr#1541]
Since Jellyfin SSO has been implemented it would be nice to have Jellyfin Invites through Organizr.

**Comment by angrycuban13** [comment]
Have you looked at jfa-go?

**Comment by Cookie-Monster-Coder** [comment]
> Have you looked at jfa-go?

Just saw it, seems promising. But it looks like it's an Organizr replacement?

**Comment by Killianbe** [comment]
Open frame with jfa-go inside, and all good

**Comment by angrycuban13** [comment]
Not necessarily a replacement for Organizr but it kind of does what you want.

**Comment by causefx** [comment]
We are moving Feature Requests away from **GitHub** and **FeatHub**.  We are now on **_FeatureUpvote_** which is located here:
### **https://vote.organizr.app**
If will also be a tab in Organizr update this Friday 22 Jan 2021


If this Feature Request was already on FeatHub it will get moved over within the week - no further action is needed.
If not, please create a new Feature Request at our new home so we can better keep track of them.
