### ISSUE TITLE
Method not allowed

### ISSUE THREAD

**Issue by Hakker** [causefx/Organizr#1542]
###### Operating System: Windows 10
<hr>

##### Problem Description:

Whenever I try to edit a tab or delete a tab I get Method not Allowed.
Creating a new tab work but as soon as I try to edit that one I get the same message
<hr>

##### Reproduction Steps:

upgrade from 2.0.x to 2.1.x and trying to edit a tab on said OS and webserver
<hr>

#### Errors on screen?  If so paste here:

```
Error Method not allowed
```

##### additional info:

Was on Discord with the problem as well and no one  could help me further there as well
<hr>

**Comment by causefx** [comment]
would you be able to make me an admin acct so i can test?  You can dm on discord

**Comment by Hakker** [comment]
Okay as at least a temporary solution we (me and causefx) found out that it will work again when you disable webdav in windows.

so in Windows it's

Control Panel -> Programs and Features -> Turn Windows features on or off -> IIS -> World Wide Web Services -> Common HTTP Feature -> WebDAV Publishing.

some more information on possible solution although some didn't work for me can be found here...
https://stackoverflow.com/questions/6739124/iis-7-5-enable-put-and-delete-for-restful-service-extensionless
