### ISSUE TITLE
Feature Request: Overseerr Integration

### ISSUE THREAD

**Issue by rix1337** [causefx/Organizr#1543]
This looks like a promising Ombi replacement/competitor:
https://github.com/sct/overseerr

<p align="center">
<img src="https://i.imgur.com/TMoEG7g.png" alt="Overseerr">
</p>
<p align="center">
<img src="https://github.com/sct/overseerr/workflows/Overseerr%20Release/badge.svg?branch=master" alt="Overseerr Release" />
<img src="https://github.com/sct/overseerr/workflows/Overseerr%20CI/badge.svg" alt="Overseerr CI">
</p>
<p align="center">
<a href="https://discord.gg/PkCWJSeCk7">
<img src="https://img.shields.io/discord/783137440809746482" alt="Discord">
</a>
<img src="https://img.shields.io/docker/pulls/sctx/overseerr" alt="Docker pulls">
<a href="https://hosted.weblate.org/engage/overseerr/">
<img src="https://hosted.weblate.org/widgets/overseerr/-/overseerr-frontend/svg-badge.svg" alt="Translation status" />
</a>
<a href="https://lgtm.com/projects/g/sct/overseerr/context:javascript"><img alt="Language grade: JavaScript" src="https://img.shields.io/lgtm/grade/javascript/g/sct/overseerr.svg?logo=lgtm&logoWidth=18"/></a>
<img alt="GitHub" src="https://img.shields.io/github/license/sct/overseerr">

<a href="#contributors-"><img alt="All Contributors" src="https://img.shields.io/badge/all_contributors-8-orange.svg"/></a>

</p>

**Overseerr** is a free and open source software application for managing requests for your media library. It integrates with your existing services such as **Sonarr**, **Radarr** and **Plex**!

## Current Features

- Full Plex integration. Login and manage user access with Plex!
- Integrates easily with your existing services. Currently Overseerr supports Sonarr and Radarr. More to come!
- Syncs to your Plex library to know what titles you already have.
- Complex request system allowing users to request individual seasons or movies in a friendly, easy to use UI.
- Incredibly simple request management UI. Don't dig through the app to simply approve recent requests.
- Granular permission system
- Mobile friendly design, for when you need to approve requests on the go!

**Comment by angrycuban13** [comment]
This is too alpha to integrate.

**Comment by causefx** [comment]
yeah i replied to their reddit announcement that I will integrate once they are out of beta... or once enough ppl are using it.

**Comment by SavageAUS** [comment]
+1 for overseerr, even in alpha it works great.
Would love to see the integration happen and an icon added for tabs etc.

**Comment by goldenpipes** [comment]
![os_logo_square](https://user-images.githubusercontent.com/6140137/103431357-2a308d00-4b94-11eb-8d57-fa3aad480428.png)
icon for tab

**Comment by causefx** [comment]
this should be there in dev branch

**Comment by Flight777** [comment]
+1 for this, using it for 2 weeks now and rock solid, even though it is still under heavy development... Have less issues with it than Ombi and my users all greatly prefer it to Ombi 👍 

Support from Organiz for this would help make it popular and sway alot of people I guess to install it. For me that was also the only doubt bringing issue, because I'd like to use Organizr as my entry point, not Overseerr directly.

**Comment by HalianElf** [comment]
Try out the dev branch

**Comment by Flight777** [comment]
@HalianElf I'm aware of the logo, but there is no integration yet with the request system (as with Ombi). That is what I'm +1ing for :)

**Comment by HalianElf** [comment]
Full integration, no not yet but there is some (SSO for now): https://github.com/causefx/Organizr/commit/8689bf810fcdcc1953800e18ff506fabc3091fc2

**Comment by EvilTactician** [comment]
I've added this suggestion to Feathub as it wasn't there yet: https://feathub.com/causefx/Organizr/+126

I guess if you're interested, get voting as this helps CauseFX prioritise what people are generally interested in.

**Comment by causefx** [comment]
We are moving Feature Requests away from **GitHub** and **FeatHub**.  We are now on **_FeatureUpvote_** which is located here:
### **https://vote.organizr.app**
If will also be a tab in Organizr update this Friday 22 Jan 2021


If this Feature Request was already on FeatHub it will get moved over within the week - no further action is needed.
If not, please create a new Feature Request at our new home so we can better keep track of them.
