### ISSUE TITLE
Emby HomePage Add-in - Item Details URL Needs updating #1290 - take2

### ISSUE THREAD

**Issue by whereisglenn** [causefx/Organizr#1545]
Please reopen issue  #1290. The issue has still not been resolved (neither in the old v1 nor the latest v2. Thanks.

**Comment by Roxedus** [comment]
What version are you on? Please use the issue template when they exist. Is this regarding jellyfin or emby?

**Comment by whereisglenn** [comment]
###### Organizr Version: V 2.1.120
###### Branch: Master
###### WebServer: IIS
###### Operating System: Windows
<hr>

##### Problem Description:
Emby has updated their URL for item details.

Current link generated for recently added items etc.
http://app.emby.media/#!/itemdetails.html?id=[item id]

Link needs to change to http://app.emby.media/#!/item/item.html?id=[item id]

<hr>

##### Reproduction Steps:
Click Emby link button on any recently added item and item detail shows blank screen


<hr>

#### Errors on screen?  If so paste here:

```

```

**Comment by causefx** [comment]
with the amount of changes they make to their url's - Both emby and Jellyfin - I have made a new input field that will allow the user to edit how they see fit :)

I of course will still update the default URL but users will no longer need to wait on us to make the changes.

![image](https://user-images.githubusercontent.com/16184466/102272231-ae6cea00-3edd-11eb-9d6c-799e16e84c5e.png)

**Comment by whereisglenn** [comment]
Thank you for such fast support resolution. Will keep an eye out when you push the next update.
