### ISSUE TITLE
Option for keeping Categories expanded by default

### ISSUE THREAD

**Issue by ex0nuss** [causefx/Organizr#1550]
###### Operating System: Docker
<hr>

##### Problem Description:
Hello, 
is it possible to keep an category expanded by default, so every item in this category is visible?

<hr>

##### Reproduction Steps:
/

<hr>

#### Errors on screen?  If so paste here:

```
/
```

**Comment by angrycuban13** [comment]
What category? Can you share a screenshot of what you mean?

**Comment by ex0nuss** [comment]
Thx for the quick reply. I mean the tab categories.

When creating an category it looks like this by default:
![default](https://user-images.githubusercontent.com/61937793/103154036-4e0b6180-4795-11eb-8dc1-b82fc1d67acb.png)

But I would like to have it automatically expanded when opening the page. Like this:
![expanded](https://user-images.githubusercontent.com/61937793/103154038-506dbb80-4795-11eb-9110-d78c7ed31327.png)

**Comment by ex0nuss** [comment]
Does anyone have any ideas?

**Comment by causefx** [comment]
you can simulate the click using js.

**Comment by causefx** [comment]
added option in dev branch
