### ISSUE TITLE
Upgraded to v2.1 on master branch homepage interactions sluggish/delayed

### ISSUE THREAD

**Issue by JReich2609** [causefx/Organizr#1551]
###### Operating System: Windows
<hr>

##### Problem Description:
Just recently upgraded from v2.0 to v2.1. The upgrade process went fine but after the upgrade was completed I got the error that the webblock information needed to be added. After some research I located the migration guide and the information that needed to be added into nginx. Once added the system loaded. If I load into the settings area everything operates correctly and quickly without any problems. 

However, when I go to the homepage the system is slow/sluggish/and almost non-responsive. If I hover over an item like settings it will not highlight as though I'm on it. If I scroll down the page nothing happens for 30-45 seconds before the page finally moves. If I click on a link that I've added into the NAV bar on the left again 30-45 seconds before the click happens and the page loads. Extremely unresponsive. Please help!

<hr>

##### Reproduction Steps:
Upgrade to newest release and go to the homepage in my instance happens every time. Once at the home page I also cannot go back into Settings without opening a new browser window and navigating there directly. But as I said above once there the settings area works as expected.

<hr>

#### Errors on screen?  If so paste here:
No errors shown.
```

```

**Comment by causefx** [comment]
Maybe there is some cache issues.  the UI didn't change beside the new API calls.  You can open up the network tab on the browser console and see which API call is taking the longest.  We can go from there.

**Comment by JReich2609** [comment]
I can confirm with 100% confidence that Organizr is running slow when I have all of the OMBI settings turned on. As disabling the menu bar link, and the information presented on the homepage resolved the problem. I am going to attempt to upgrade OMBI and report back as to whether the problem still exists.

**Comment by JReich2609** [comment]
Upgraded OMBI to the newest version I could find under the V4 branch to 4.0.779.0. Slowness immediately returns to the home page of the Organizr screen. 

With this URL taking the longest to fire - http://[SERVERNAME]/api/v2/homepage/ombi/requests

**Comment by causefx** [comment]
hmmm this is very odd...  as all the calls should be independent of each other and shouldn't slow any other down...

**Comment by JReich2609** [comment]
Agreed. Anything else you need from me in the meantime? Or is it in your ball court to do some digging? Just want to make sure I am not holding you up in anyway.

**Comment by causefx** [comment]
still happening with Ombi?
