### ISSUE TITLE
OpenID Connect/SAML/OAuth

### ISSUE THREAD

**Issue by mprajescu** [causefx/Organizr#1553]
I'm just opening this issue to request an update if there any plans to implement OAuth /OpenID Connect/ SAML integration for SSO to have the users in Keycloak and provide a SSO experience with the Organizr?

**Comment by causefx** [comment]
We are moving Feature Requests away from **GitHub** and **FeatHub**.  We are now on **_FeatureUpvote_** which is located here:
### **https://vote.organizr.app**
If will also be a tab in Organizr update this Friday 22 Jan 2021


If this Feature Request was already on FeatHub it will get moved over within the week - no further action is needed.
If not, please create a new Feature Request at our new home so we can better keep track of them.
