### ISSUE TITLE
Organizer won't load monitorr widget on Home screen when any device is offline

### ISSUE THREAD

**Issue by bdorr1105** [causefx/Organizr#1554]
###### Operating System: Ubuntu
<hr>

##### Problem Description:
I have monitorr setup and I added to my home page. First of all, this is really awesome. Anyways, Everything loads great, but only when everything is green/online. If any of my devices go offline, monitorr shows it, but the widget will not load on organizer at all

<hr>

##### Reproduction Steps:
I shut down a device that was online, problem surfaced. Brought the device back online, everything loaded just fine

<hr>

#### Errors on screen?  If so paste here:
 No errors
```

```
![organizer-v2-home](https://user-images.githubusercontent.com/12386911/103497738-63753100-4e10-11eb-8f9b-f888c46b702f.PNG)

![offline](https://user-images.githubusercontent.com/12386911/103497743-65d78b00-4e10-11eb-8b7f-751a14c843d4.PNG)

**Comment by causefx** [comment]
@henrywhitaker3 want me to take a stab at this?

**Comment by henrywhitaker3** [comment]
Might be able to have a look some time this weekend @causefx , but if you've got the time knock yourself out

**Comment by causefx** [comment]
will do, I wonder if it is timing out...  I will see if I can borrow someones monitorr url

**Comment by causefx** [comment]
try the latest commit, open issue if it didnt fix
