### ISSUE TITLE
PHP Mailer not working (cannot connect to host error)

### ISSUE THREAD

**Issue by vMotionFailed** [causefx/Organizr#1555]
###### Operating System: Servers are linux, client it Windows 10 (New Edge Browser)
<hr>

##### Problem Description:
PHP Mailer doesn't send test emails.  Claims it can't connect to host, the host is smtp.office365.com which is reachable from the webserver.  

<hr>

##### Reproduction Steps:
Set up PHP Mailer plugin and hit test email.

<hr>

#### Errors on screen?  If so paste here:

```
Mail Function - E-Mail Test Failed[SMTP Error: Could not connect to SMTP host.] [Execution Time: 153ms]
```
![image](https://user-images.githubusercontent.com/1287511/103701141-7f451800-4f73-11eb-9faa-cf4dc95899be.png)

**Comment by causefx** [comment]
Have you tried using `Enable Debug Output on Email Test`

**Comment by vMotionFailed** [comment]
@causefx I did but it didn't seem to do anything (didn't see anything new in the console).  I just toggled it on (saw the debug in the console) and the emails are now sending correctly, and I disabled the debug and the emails are still sending correctly.  Maybe it was a caching issue?  Thanks for the quick reply!

**Comment by causefx** [comment]
nice, yeah no clue what it could've been.  👍🏽
