### ISSUE TITLE
Tautulli not showing on the Homepage

### ISSUE THREAD

**Issue by Glasti1** [causefx/Organizr#1556]
###### Operating System: unRAID
<hr>

##### Problem Description:
Tautulli not showing on the Homepage. using `http://10.12.3.100:8181`, `Test Connection` gives `API Connection Success`

Can curl the tautulli API from within the container. Fixed the Tautulli library.

<hr>

##### Reproduction Steps:
Been troubleshooting with KP and Tautulli devs, but not able to reproduce anywhere else.  

<hr>

#### Errors on screen?  If so paste here:

```
Failed to load resource: the server responded with a status of 500 ()
functions.js?v=de49712860211d826e8eb9d033362cc557833f4d:10321  Organizr API Function  
cURL error 28: Operation timed out after 10000 milliseconds with 0 bytes received 
```

**Comment by Glasti1** [comment]
i am mainly posting this to see if more people will have this issue. This issue does not have a high priority to get fixed for me.

**Comment by causefx** [comment]
i can enable higher load times.

**Comment by Glasti1** [comment]
That would be worth a try! 

I was thinking about it, i do have a reasonable big music library, around 280K songs atm. 
Maybe that will make it exceed the 10 seconds.

**Comment by causefx** [comment]
you can  try calling the API from the tau itself and see how long it takes

**Comment by Glasti1** [comment]
root@ded5f05904b0:/$ curl -w "@/config/curl-format.txt" -o /dev/null -s "http://10.12.3.100:8181/api/v2?apikey=XXXX&cmd=get_home_stats"
     time_namelookup:  0.000019s
        time_connect:  0.000089s
     time_appconnect:  0.000000s
    time_pretransfer:  0.000126s
       time_redirect:  0.000000s
  time_starttransfer:  0.156870s
                     ----------
          time_total:  0.156942s 
          
    This is what is so confusing
    
    from within the ORG container

**Comment by Glasti1** [comment]
Think i found the issue. My music library is rather big, and it takes a while for Tautulli to get the request back from Plex . Thats why i think it exceeds the 10 second limit.

**Comment by causefx** [comment]
fixed in dev. pushing to master tomorrow
