### ISSUE TITLE
Cannot remove users on v2.1.120

### ISSUE THREAD

**Issue by shocker2** [causefx/Organizr#1558]
How to reproduce:
Settings -> User management -> Click the red trash bin to delete the user -> Confirm the user deletion popup -> Refresh and the user is still in the table, nothing happens.
By manually running in sqlite DELETE FROM users WHERE id='xx'; the user is deleted and it's not in the user namagement table anymore.

**Comment by causefx** [comment]
How is organizr installed?

**Comment by shocker2** [comment]
Nginx as reverse proxy for apache. The api for v2 is in .htaccess of my Apache.

**Comment by causefx** [comment]
Can you try accessing via apache and removing a user there...?

**Comment by shocker2** [comment]
Tried via apache directly, not working.

This is the error I get:
XHR DELETE http://organize.tld:8080/api/v2/users/261 [HTTP/1.1 405 Method Not Allowed 3ms]
Uncaught TypeError: xhr.responseJSON is undefined jquery-2.2.4.min.js line 2 > eval:159:14

**Comment by causefx** [comment]
seems apache is blocking those methods...  I would assume all PUT is blocked.  Do you have a LIMIT block somewhere in your config?

**Comment by shocker2** [comment]
No, there are no limits. All the controls are on the Nginx level as apache is only used with the reverse proxy. Also, v2.0 worked fine this only occurs after the upgrade to v2.1.

**Comment by causefx** [comment]
2.1 changed the whole api methods.  
So this error is from Apache correct? 

```
XHR DELETE http://organize.tld:8080/api/v2/users/261 [HTTP/1.1 405 Method Not Allowed 3ms]
```
Either way, something in that respective webserver is blocking that method from running.

**Comment by shocker2** [comment]
Yes, it's from apache directly. Apache is running on 8080 and Nginx is reverse proxying on 80/443

**Comment by shocker2** [comment]
Also, there is no trigger on the error log.

**Comment by causefx** [comment]
It may be just a straight Apache error, or also may be related to WebDav...  I know you arent using Plesk, but check out this thread:
https://support.plesk.com/hc/en-us/articles/115002202793-Unable-to-use-DELETE-PUT-or-PATCH-HTTP-verbs-with-php-files-or-Web-API-on-Plesk-server-405-HTTP-verb-used-to-access-this-page-is-not-allowed

**Comment by shocker2** [comment]
Found with debugging this error: AH01623, will dig about it in a sec.

**Comment by shocker2** [comment]
Fixed, for the HTTP methods, I only had activated GET, HEAD, POST. I have enabled all of the GET, HEAD, POST, PUT, DELETE, PATCH and now it's fixed :) Not sure if put/patch is used by Organizer but just in case :) Maybe worth mentioning somewhere in the wiki to help others with AH01623 error.

Thanks for the help with the troubleshooting!

**Comment by causefx** [comment]
Good find!  Can you paste your block so I can add to docs.

**Comment by shocker2** [comment]
```
<Directory "/path/to/organizr">
    <Limit GET HEAD POST PUT DELETE OPTIONS>
          Require all granted #or allow from all for older apache servers I think <2.4 needs that.. not sure to be honest.
    </Limit>
</Directory>
```

Also, the <Limit> tag can be used in .htaccess for a quick fix, like:
```
    <Limit GET HEAD POST PUT DELETE OPTIONS>
          Require all granted #or allow from all for older apache servers I think <2.4 needs that.. not sure to be honest.
    </Limit>
```

But you should mention that this is only for the AH01623 error, not sure if this is enabled by default.
