### ISSUE TITLE
LDAP user is not added with the correct email bug is not resolved.

### ISSUE THREAD

**Issue by shocker2** [causefx/Organizr#1559]
Tested with v2.1.120 and the bug is still present, the new user is added with placeholder. I'm using FreeIPA.

Related with #1244

**Comment by causefx** [comment]
is the email under the `mail` attribute?

**Comment by shocker2** [comment]
It should, for example, I have added now a username from the linux cli with: `# ipa user-add 'theusername' --first='first name' --last='last name' --password --email='the.user.test@gmail.com'` and I have the same result.

From LDAP IPA db:
![image](https://user-images.githubusercontent.com/24977727/105458410-28d51a80-5c91-11eb-91fb-a64969627e00.png)

**Comment by Drazzilb08** [comment]
Can confirm this is still an issue even with the latest version.
Version: `2.1.400`
