### ISSUE TITLE
Forgot password with LDAP backend is not working

### ISSUE THREAD

**Issue by shocker2** [causefx/Organizr#1560]
If only the LDAP backend is used, the password reset is not resetting the password to LDAP.

**Comment by causefx** [comment]
this may be possible if I migrate to: 
https://github.com/DirectoryTree/LdapRecord

**Comment by shocker2** [comment]
It might worth it as there are lots of issues with ldap. Password reset, password change and user added with placeholder is not working with FreeIPA.
