### ISSUE TITLE
no being able to update from 2.1.83 to 2.1.120

### ISSUE THREAD

**Issue by FGOD1983** [causefx/Organizr#1561]
###### Operating System: Ubuntu
<hr>

##### Problem Description:
It seems to not update to 2.1.120 when I press the install update button. It does say it is succeeded and so does the logs, but it keeps mentioning the update and the update tab is still saying my installed version is 2.1.83.

Date | User | IP Address | Message | Type
-- | -- | -- | -- | --
12 januari 2021 17:14 | FGOD | IP-ADDRESS | Admin Function - Accessed Settings Page [Execution Time: 4.4ms] |  
12 januari 2021 17:13 | FGOD | IP-ADDRESS | Update Function - Update Completed [Execution Time: 5.1ms] |  
12 januari 2021 17:13 | FGOD | IP-ADDRESS | Update Function - Deleted Update Files from Branch: v2-master [Execution Time: 211ms] |  
12 januari 2021 17:13 | FGOD | IP-ADDRESS | Update Function - Files overwritten using Updated Files from Branch: v2-master [Execution Time: 260ms] |  
12 januari 2021 17:13 | FGOD | IP-ADDRESS | Update Function - Unzipped Update File for Branch: v2-master [Execution Time: 01.01s \| 1010.8ms] |  
12 januari 2021 17:13 | FGOD | IP-ADDRESS | organizr unzipped upgrade.zip [Execution Time: 34.7ms] |  
12 januari 2021 17:13 | FGOD | IP-ADDRESS | Update Function - Downloaded Update File for Branch: v2-master [Execution Time: 04.10s \| 4109.7ms] |  
12 januari 2021 17:13 | FGOD | IP-ADDRESS | organizr created upgrade zip file from github zip file [Execution Time: 10.8ms] |  
12 januari 2021 17:13 | FGOD | IP-ADDRESS | organizr finished downloading the github zip file [Execution Time: 04.10s \| 4108.7ms] |  
12 januari 2021 17:13 | FGOD | IP-ADDRESS | Update Function - Started Upgrade Process [Execution Time: 3.5ms]

<hr>

##### Reproduction Steps:
press update in the update tab

<hr>

#### Errors on screen?  If so paste here:

```

```

**Comment by causefx** [comment]
Do you have opcache installed?

**Comment by FGOD1983** [comment]
I don't believe I did.

I also tried a new install, which is using the newest version (backed up my old version to test stuff when you respond), but seems I also can't open any page that I setup on the tab settings. I just end up with nginx errors or blank pages while opening in a new tab does work.

**Comment by causefx** [comment]
is this all local?  what does the browser console say when opening a tab?

**Comment by FGOD1983** [comment]
depending on what you mean with local. I don't run it in a container or anything, but I do access it over another computer through the setup virtual host with nginx.

The Chrome console gives me the following output when I try to open the Plex page over my tab:

```
 Tab Function  Loading new tab for: Plex 
jquery-2.2.4.min.js:3 Mixed Content: The page at 'https://[organizr page url]/#Plex' was loaded over HTTPS, but requested an insecure frame 'http://[plex url]/web/index.html'. This request has been blocked; the content must be served over HTTPS.
```
Seems it is having issues with ssl?

**Comment by causefx** [comment]
seems that issue is related to mixing insecure content with a secure connection.

**Comment by FGOD1983** [comment]
so it should be better to remove the ssl for organizr?

**Comment by causefx** [comment]
if you serve organizr over http, tabs can be either http or https.

if you serve organizr over https, all tabs must be https.

**Comment by FGOD1983** [comment]
hmmm, i am trying to remove the ssl from the vhost block in Nginx, but now I am getting 404's on Organizr, saying that i need to complete the migration. Is there a easy way to redo the installation without ssl? 

I was looking to the installation script for ubuntu, but that only let's me add ssl.

If not, how can I make sure that http tabs are also working on ssl organizr?

**Comment by causefx** [comment]
If you aren't reverse proxying your tabs - you could try that.  I will test locally how my tabs handle this.

**Comment by FGOD1983** [comment]
while trying to revive my setup, I thought it would be easier to redo the whole install of organizr.

This let to issues with certbot on the install script on my ubuntu 20.04 setup. I decided to do the install manually due to this and redid certbot with snap. 

That did seem to work, but now I am left with a organizr setup that is stuck on the check page due to PDO_SQLITE and SQLITE3 not being loaded somehow.

I was looking online and came across this post on reddit: https://www.reddit.com/r/organizr/comments/6phgdg/sqlite3_is_not_loaded_please_install_it_before/

I decided to take a look at the php.ini and sqlite3 and pdo_sqlite were indeed commented out. I uncommented them and restarted both my php7.4 and nginx services, but somehow they are not being released.

Any ideas on that?

**Comment by FGOD1983** [comment]
```
; - Many DLL files are located in the extensions/ (PHP 4) or ext/ (PHP 5+)
;   extension folders as well as the separate PECL DLL download (PHP 5+).
;   Be sure to appropriately set the extension_dir directive.
;
;extension=bz2
;extension=curl
;extension=ffi
;extension=ftp
;extension=fileinfo
;extension=gd2
;extension=gettext
;extension=gmp
;extension=intl
;extension=imap
;extension=ldap
;extension=mbstring
;extension=exif      ; Must be after mbstring as it depends on it
;extension=mysqli
;extension=oci8_12c  ; Use with Oracle Database 12c Instant Client
;extension=odbc
;extension=openssl
;extension=pdo_firebird
;extension=pdo_mysql
;extension=pdo_oci
;extension=pdo_odbc
;extension=pdo_pgsql
extension=pdo_sqlite
;extension=pgsql
;extension=shmop

; The MIBS data available in the PHP distribution must be installed.
; See http://www.php.net/manual/en/snmp.installation.php
;extension=snmp

;extension=soap
;extension=sockets
;extension=sodium
extension=sqlite3
;extension=tidy
;extension=xmlrpc
;extension=xsl
```

**Comment by FGOD1983** [comment]
seems I found part of the problem:

```
php -i | grep extension_dir         
extension_dir => /usr/lib/php/20200930 => /usr/lib/php/20200930
sqlite3.extension_dir => no value => no value
```

**Comment by FGOD1983** [comment]
nevermind, seems somehow some php7.4 modules were deleted which caused sqlite3 to be there but not the php7.4 sqlite3 module

**Comment by FGOD1983** [comment]
oke, back to the same issue.

The new install is unsecure (no ssl) and still has issues with my plex page or ombi (ssl). With organizr as frame it gives a blank screen and with iframe I get a Nginx 404. When I do a new window option it goes to the following url:

`http://organizr.domain.nl/plex.domain.nl` 

that should off course be `plex.domain.nl`

due to having the same results on both iframe and new window, it seems that both are trying to open that url instead of the normal url

edit: this is also shown by the console when I try iframe, because then too it goes to this url

edit2: seems that the whole problem I am now facing is due to not having the http/https in the front of the url path. I changed the url to include this and that fixed the iframe

**Comment by HalianElf** [comment]
You should have scheme in your tab urls. It's now Organizr's job to guess what scheme you're using.

**Comment by causefx** [comment]
Sounds good, so what issues are you left with?

**Comment by FGOD1983** [comment]
@causefx it seems that my issues are solved now although I managed to install it again without SSL (which reverted back to what you said about SSL organizr not being able to do non SSL tabs). 

So unless you see that as an issue, my problems are all solved :)

Thx for the help :)

**Comment by causefx** [comment]
The issue about SSL comes from the browser.  They way around that is the make sure everything is using ssl.  So like reverse proxying your tabs,

**Comment by FGOD1983** [comment]
I see, thx for the explanation
