### ISSUE TITLE
UniFi controller 6 and 2FA support

### ISSUE THREAD

**Issue by Eds1989** [causefx/Organizr#1562]
###### Operating System: Windows
<hr>

##### Problem Description:
More of a feature request;
Since the recent Ubiquiti data breach, I have enabled 2FA on my account. I have also updated my Unifi CloudKey Gen2 to the latest firmware version, which has changed the underlying UnifiOS and auth system.
I'd love to see some way to reintroduce the Unifi section on the homepage, with the ability to connect to this new Unifi infrastructure.

<hr>

##### Reproduction Steps:
N/A

<hr>

#### Errors on screen?  If so paste here:
Connectivity tests for Unifi homepage item now fail
```

```

**Comment by causefx** [comment]
Your best bet currently is to create a separate local API user to read info.

**Comment by angrycuban13** [comment]
You should have been using a `read only` account from the beginning. Found out the hard way 😂

**Comment by Eds1989** [comment]
Oh right, so it is currently possible? I thought the URL scheme had also changed in some way?
I'm fine with creating a read-only local user if it is still compatible.

**Comment by causefx** [comment]
![image](https://user-images.githubusercontent.com/16184466/104962818-77836b80-5996-11eb-89b1-afac543742aa.png)

You should be all good :)

above is what i use.

**Comment by Eds1989** [comment]
Got it, thanks!
Out of interest, what kind of stats do other people see?
I literally only see WLAN basic stats:
![image](https://user-images.githubusercontent.com/37086102/104973639-323e5880-59ed-11eb-86ef-f81f6dad6594.png)

**Comment by HalianElf** [comment]
If you only have APs, that's all that you should see. If you had a USG/UDM you'd get WAN, WWW and LAN stats as well

**Comment by Eds1989** [comment]
Ah ok. So basic switches don't generate any LAN info without a USG.
All good, at least it is something to add to my home page :)
