### ISSUE TITLE
Content wrapper causing obstructed view of tab content

### ISSUE THREAD

**Issue by yenoromm** [causefx/Organizr#1567]
Organizr Version: 2.1.165
Branch: V2-Master
WebServer: Nginx
Operating System: Ubuntu

Problem Description:
`content-wrapper` class is applied to body under when ~1170px wide but the sidebar doesn't disappear until below ~768px. This causes part of the content to not be displayed on the right-hand side of the screen. 

Reproduction Steps:
Screen width between ~768px and ~1170px. Reproducible on Firefox OSX and Windows, Edge on Windows and Safari on OSX.

**Comment by causefx** [comment]
fixed in dev - thank you
