### ISSUE TITLE
Trakt Authorization not working (due to reverse proxy config issue ?) 

### ISSUE THREAD

**Issue by Procuria** [causefx/Organizr#1571]
<img width="451" alt="malformed_redirect_uri_remote_access" src="https://user-images.githubusercontent.com/37988494/106401580-27d88180-6425-11eb-8f00-96012ce33616.png">
<img width="451" alt="not_authorized_local_access" src="https://user-images.githubusercontent.com/37988494/106401582-2b6c0880-6425-11eb-8d18-eaf5c5c1fdf3.png">

###### Operating System: Ubuntu
<hr>

##### Problem Description:
Trakt Home-Page Item _Connect Account_ not possible because of:

a) malformed Redirect URI when accessing Organizr via web/remote
b) 'not authorized'  when accessing Organizr via local browser 

<hr>

##### Reproduction Steps:
Configure Trakt App, setup redirect URI, fill out needed creds, hit _Connect Account_  - Button. It seems quite clear if I use a 'remote browser' because my localhost on the client machine isn't the localhost at the Organizr-instance. What made me curious is that when I use the browser on the Organizr-instance, I get error b) I tried to proxy-pass the Oauth-Url but that doesn't change anything (although I am not sure if I did it right). 

<hr>

#### Errors on screen?  If so paste here:

```
<img width="451" alt="malformed_redirect_uri_remote_access" src="https://user-images.githubusercontent.com/37988494/106401403-2f4b5b00-6424-11eb-88fa-a2514a5dfac9.png">
<img width="451" alt="not_authorized_local_access" src="https://user-images.githubusercontent.com/37988494/106401413-3a9e8680-6424-11eb-96c7-ee9f36b4ea0d.png">
```

**Comment by causefx** [comment]
Are you typing in the URL that the homepage item says to use?  You can setup multiple URLs in trakt as well.  

![image](https://user-images.githubusercontent.com/16184466/106401707-cb547280-63e2-11eb-9aee-9298682e26d3.png)

If you access Organizr from local url - it will show local url here etc...  

Edit: Also make sure you are signed in when you pasted that in bottom screenshot

**Comment by Procuria** [comment]
Thanks for the rocket-fast reply.
Yes, I typed in the URL and I'm signed in too. In my setup, it always shows the 'local' URL, regardless if I access it 'remote' or 'local'. Maybe it's an NGINX proxy config issue. Would it help if I paste my location-block ?
<img width="272" alt="2021-02-01_00h52_21" src="https://user-images.githubusercontent.com/37988494/106402241-e0ec8b00-6428-11eb-9a8c-861c69091ae3.png">
 
Edit: and as stated in the initial post - the 'not authorized'-error occurs when I try it on the Organizr-instance as well.
Edit: and I also tried it with several URL's in the Trakt config (localhost _and_ my.domain.tld/organizr/...

**Comment by causefx** [comment]
Yes, please paste your block...  You can type in the url:

`https://portal.dunst.be/organizr/api/v2/oauth/trakt`
into Trakt.

**Comment by Procuria** [comment]
I also tried the mentioned URL, but without success. 
I just tested a dockerized Organizr-instance without a reverse proxy in front of it and all worked well. 
So it _has_ to be a reverse-proxy issue :( 
I would totally understand if you don't have the time to support the Nginx config of an individual user but would be extraordinarily happy if you could point me in the direction regarding the config. 
[causfx_troubleshooting_nginx_location_block.txt](https://github.com/causefx/Organizr/files/5906844/causfx_troubleshooting_nginx_location_block.txt)

**Comment by causefx** [comment]
any reason you are running at `/organizr` when you dont have to?

**Comment by causefx** [comment]
Also replace all proxy_set_header with these:
```
proxy_set_header Host $host:$server_port;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header X-Forwarded-Proto https;
proxy_set_header X-Forwarded-Host $host;
proxy_set_header X-Forwarded-Ssl on;
```

so it will look like this:
```
location /organizr/  {
            proxy_pass  http://localhost:8090/;
            proxy_set_header Host $host:$server_port;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto https;
            proxy_set_header X-Forwarded-Host $host;
            proxy_set_header X-Forwarded-Ssl on;
            add_header              X-Frame-Options         "SAMEORIGIN"; # see note
}

```

**Comment by Procuria** [comment]
Thank you so much - I guess this will work, because now the URI is shown 'correct' in the Trakt dialogue! 
But (I guess due to my lack of understanding NGINX) I'm running on /organizr/ because if I use the 'standard' /-location-block I always end up with a white screen instead of the magical mystery planes of Organizr-ing ... or even worse, an Organizr 404 despite I'm running it dockerized.

Therefore I now have to tinker around how to get the base-url `/organizr` to work, because I just get `https://my.domain.tld/api...` in the Trakt dialogue.  
 
My last question would be the " Why does this work, what does it do?", but I think I better ask, "Where should I look in the NGINX-Docs?" to enable myself solving this. 

Thank you very much again - for the help and the possibility to learn!

**Comment by causefx** [comment]
i may need to change the code for the correct url to show...  As for changing it just make your block like so:
```

    #
	# Add headers to serve security related headers
	#  
	# HSTS (ngx_http_headers_module is required)
	# In order to be recoginzed by SSL test, there must be an index.hmtl in the server's root
	add_header Strict-Transport-Security "max-age=63072000; includeSubdomains" always;
	add_header X-Content-Type-Options "nosniff" always;
	# Usually this should be "DENY", but when hosting sites using frames, it has to be "SAMEORIGIN"
	add_header Referrer-Policy "same-origin" always;
	add_header X-XSS-Protection "1; mode=block" always;
	add_header X-Robots-Tag none;
	add_header X-Download-Options noopen;
	add_header X-Permitted-Cross-Domain-Policies none;
	
	#
	#Organizr        
	location / {
				proxy_pass  http://localhost:8090/;
				proxy_set_header Host $host:$server_port;
				proxy_set_header X-Real-IP $remote_addr;
				proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
				proxy_set_header X-Forwarded-Proto https;
				proxy_set_header X-Forwarded-Host $host;
				proxy_set_header X-Forwarded-Ssl on;
				add_header              X-Frame-Options         "SAMEORIGIN"; # see note
	}
	
	location ~ ^/auth-(.*) { rewrite ^/auth-(.*) /api/v2/auth?group=$1; }
	error_page 401 403 $scheme://$host/?error=$status&return=$scheme://$http_host$request_uri;  #error page
	error_page 404 $scheme://$host/?error=$status;  #error page
}
```

Make sure to paste the beginning of the server block that is missing from your original pasting

**Comment by Procuria** [comment]
Okay - I tinkered around with the config mentioned above and found a lot of never seen before error-screens...but in the end it only works with the attached config. 
It may be ugly, but it works for around about 3 years so please be kind to my config file :) 
[causfx_troubleshooting_nginx_troubleshooting.txt](https://github.com/causefx/Organizr/files/5907505/causfx_troubleshooting_nginx_troubleshooting.txt)

**Comment by causefx** [comment]
Try this
```
server {
	listen 80;
	server_name portal.dunst.be 144.76.41.226;
 
	root /var/www;
	
	location ^~ /.well-known/acme-challenge {
		proxy_pass http://127.0.0.1:81;
		proxy_redirect off;
	}
  
  location / {
		# Enforce HTTPS
		# Use this if you always want to redirect to the DynDNS address (no local access).
		return 301 https://$server_name$request_uri;
		
		# Use this if you also want to access the server by local IP:
		#return 301 https://$server_addr$request_uri;
    }		
}

server {
	listen 443 ssl http2;
	server_name portal.dunst.be 144.76.41.226;
 
	#
	# Configure SSL
	#
	ssl on;
  
	# Certificates used
	ssl_certificate /etc/letsencrypt/live/portal.dunst.be/fullchain.pem;
	ssl_certificate_key /etc/letsencrypt/live/portal.dunst.be/privkey.pem;
  
	# Not using TLSv1 will break:
	#	Android <= 4.4.40
	#	IE <= 10
	#	IE mobile <=10
	# Removing TLSv1.1 breaks nothing else!
	ssl_protocols TLSv1.2;
	
	# Using the recommended cipher suite from: https://wiki.mozilla.org/Security/Server_Side_TLS
	ssl_ciphers 'ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-DSS-AES128-GCM-SHA256:kEDH+AESGCM:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-DSS-AES128-SHA256:DHE-RSA-AES256-SHA256:DHE-DSS-AES256-SHA:DHE-RSA-AES256-SHA:!aNULL:!eNULL:!EXPORT:!DES:!RC4:!3DES:!MD5:!PSK';
  
	# Diffie-Hellman parameter for DHE ciphersuites, recommended 2048 bits
	ssl_dhparam /etc/nginx/ssl/dhparams.pem;
  
	# Specifies a curve for ECDHE ciphers.
	# High security, but will not work with Chrome:
	#ssl_ecdh_curve secp521r1;  
	# Works with Windows (Mobile), but not with Android (DavDroid):
	#ssl_ecdh_curve secp384r1;
	# Works with Android (DavDroid):
	ssl_ecdh_curve prime256v1; 
 
	# Server should determine the ciphers, not the client
	ssl_prefer_server_ciphers on;
  
	# OCSP Stapling
	# fetch OCSP records from URL in ssl_certificate and cache them
	ssl_stapling on;
	ssl_stapling_verify on;
	ssl_trusted_certificate /etc/letsencrypt/live/portal.dunst.be/fullchain.pem;
	resolver 8.8.8.8;
  
	# SSL session handling
	ssl_session_timeout 24h;
	ssl_session_cache shared:SSL:50m;
	ssl_session_tickets off;
 
	#
	# Add headers to serve security related headers
	#  
	# HSTS (ngx_http_headers_module is required)
	# In order to be recoginzed by SSL test, there must be an index.hmtl in the server's root
	add_header Strict-Transport-Security "max-age=63072000; includeSubdomains" always;
	add_header X-Content-Type-Options "nosniff" always;
	# Usually this should be "DENY", but when hosting sites using frames, it has to be "SAMEORIGIN"
	add_header Referrer-Policy "same-origin" always;
	add_header X-XSS-Protection "1; mode=block" always;
	add_header X-Robots-Tag none;
	add_header X-Download-Options noopen;
	add_header X-Permitted-Cross-Domain-Policies none;

	#Organizr        
	location / {
		proxy_pass  http://localhost:8090;
		proxy_set_header Host $host:$server_port;
		proxy_set_header X-Real-IP $remote_addr;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		proxy_set_header X-Forwarded-Proto https;
		proxy_set_header X-Forwarded-Host $host;
		proxy_set_header X-Forwarded-Ssl on;
		add_header              X-Frame-Options         "SAMEORIGIN"; # see note
	}

}
```

**Comment by causefx** [comment]
closed due to inactivity...

**Comment by jscottelblein** [comment]
I just tried connecting Trakt.tv to Organizr last night and have run into an issue:

in the screenshot, the numbers indicate the settings from both Organizr and trakt, and it's result when trying to auth from within Org.

The bottom image is  what results when I try to just auth from Trakt itself, when I click that "authorize" button.

![image](https://user-images.githubusercontent.com/1524526/108609809-23551800-7396-11eb-831a-9a1c5a4b5dec.png)

I noticed something with the `code` param in the urls, which don't seem to match, which I put red rectangles around; dunno whether or not they're an issue in this case.

If I go directly to the redirect URL Organizr gives me, I get this:

```
{
    "response": {
        "result": "error",
        "message": "Endpoint Not Found or Defined",
        "data": {
            "endpoint": "/api/v2/oauth/trakt%20Authorize",
            "method": "GET"
        }
    }
}
```

I use the LinuxServer Swag Nginx RP for all my stuff, so all the headers you mentioned above are already "baked  in"  to each RP, so to speak (i.e. I don't have to add them manually each time).

here's the full error I get when trying to auth from within Org:

```
Slim Application Error
The application could not run because of the following error:

Details
Type: GuzzleHttp\Exception\RequestException
Code: 0
Message: cURL error 77: error setting certificate verify locations: CAfile: /config/www/organizr/api/functions/cert/cacert.pem CApath: none (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)
File: /config/www/organizr/api/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php
Line: 201
Trace
#0 /config/www/organizr/api/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(155): GuzzleHttp\Handler\CurlFactory::createRejection()
#1 /config/www/organizr/api/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(105): GuzzleHttp\Handler\CurlFactory::finishError()
#2 /config/www/organizr/api/vendor/guzzlehttp/guzzle/src/Handler/CurlHandler.php(43): GuzzleHttp\Handler\CurlFactory::finish()
#3 /config/www/organizr/api/vendor/guzzlehttp/guzzle/src/Handler/Proxy.php(28): GuzzleHttp\Handler\CurlHandler->__invoke()
#4 /config/www/organizr/api/vendor/guzzlehttp/guzzle/src/Handler/Proxy.php(51): GuzzleHttp\Handler\Proxy::GuzzleHttp\Handler\{closure}()
#5 /config/www/organizr/api/vendor/guzzlehttp/guzzle/src/PrepareBodyMiddleware.php(66): GuzzleHttp\Handler\Proxy::GuzzleHttp\Handler\{closure}()
#6 /config/www/organizr/api/vendor/guzzlehttp/guzzle/src/Middleware.php(29): GuzzleHttp\PrepareBodyMiddleware->__invoke()
#7 /config/www/organizr/api/vendor/guzzlehttp/guzzle/src/RedirectMiddleware.php(70): GuzzleHttp\Middleware::GuzzleHttp\{closure}()
#8 /config/www/organizr/api/vendor/guzzlehttp/guzzle/src/Middleware.php(59): GuzzleHttp\RedirectMiddleware->__invoke()
#9 /config/www/organizr/api/vendor/guzzlehttp/guzzle/src/HandlerStack.php(71): GuzzleHttp\Middleware::GuzzleHttp\{closure}()
#10 /config/www/organizr/api/vendor/guzzlehttp/guzzle/src/Client.php(361): GuzzleHttp\HandlerStack->__invoke()
#11 /config/www/organizr/api/vendor/guzzlehttp/guzzle/src/Client.php(113): GuzzleHttp\Client->transfer()
#12 /config/www/organizr/api/vendor/guzzlehttp/guzzle/src/Client.php(130): GuzzleHttp\Client->sendAsync()
#13 /config/www/organizr/api/vendor/league/oauth2-client/src/Provider/AbstractProvider.php(608): GuzzleHttp\Client->send()
#14 /config/www/organizr/api/vendor/league/oauth2-client/src/Provider/AbstractProvider.php(621): League\OAuth2\Client\Provider\AbstractProvider->getResponse()
#15 /config/www/organizr/api/vendor/league/oauth2-client/src/Provider/AbstractProvider.php(537): League\OAuth2\Client\Provider\AbstractProvider->getParsedResponse()
#16 /config/www/organizr/api/functions/oauth.php(23): League\OAuth2\Client\Provider\AbstractProvider->getAccessToken()
#17 /config/www/organizr/api/v2/routes/oauth.php(6): Organizr->traktOAuth()
#18 /config/www/organizr/api/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(43): {closure}()
#19 /config/www/organizr/api/vendor/slim/slim/Slim/Routing/Route.php(384): Slim\Handlers\Strategies\RequestResponse->__invoke()
#20 /config/www/organizr/api/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): Slim\Routing\Route->handle()
#21 /config/www/organizr/api/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): Slim\MiddlewareDispatcher->handle()
#22 /config/www/organizr/api/vendor/slim/slim/Slim/Routing/Route.php(341): Slim\MiddlewareDispatcher->handle()
#23 /config/www/organizr/api/vendor/slim/slim/Slim/Routing/RouteRunner.php(84): Slim\Routing\Route->run()
#24 /config/www/organizr/api/vendor/slim/slim/Slim/Middleware/RoutingMiddleware.php(59): Slim\Routing\RouteRunner->handle()
#25 /config/www/organizr/api/vendor/slim/slim/Slim/MiddlewareDispatcher.php(147): Slim\Middleware\RoutingMiddleware->process()
#26 /config/www/organizr/api/vendor/slim/slim/Slim/Middleware/ErrorMiddleware.php(107): class@anonymous->handle()
#27 /config/www/organizr/api/vendor/slim/slim/Slim/MiddlewareDispatcher.php(147): Slim\Middleware\ErrorMiddleware->process()
#28 /config/www/organizr/api/v2/index.php(90): class@anonymous->handle()
#29 /config/www/organizr/api/vendor/slim/slim/Slim/MiddlewareDispatcher.php(313): {closure}()
#30 /config/www/organizr/api/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): class@anonymous->handle()
#31 /config/www/organizr/api/vendor/slim/slim/Slim/App.php(215): Slim\MiddlewareDispatcher->handle()
#32 /config/www/organizr/api/vendor/slim/slim/Slim/App.php(199): Slim\App->handle()
#33 /config/www/organizr/api/v2/index.php(129): Slim\App->run()
#34 {main}
Go Back
```

**Comment by jscottelblein** [comment]
For more info on my RP config:

organizer RP:
```
# In order to use this location block you need to edit the default file one folder up and comment out the / and ~ \.php$ locations

location / {
    # Tell search engines not to crawl/add this domain
    add_header X-Robots-Tag "noindex, nofollow, nosnippet, noarchive";

    include /config/nginx/proxy.conf;
    resolver 127.0.0.11 valid=30s;
    set $upstream_app organizr;
    set $upstream_port 80;
    set $upstream_proto http;
    proxy_pass $upstream_proto://$upstream_app:$upstream_port;
}

# Optional redirect server errors to organizr error pages
error_page 400 402 403 404 405 408 500 502 503 504  $scheme://$http_host/?error=$status;
```

proxy.conf:

```
## Version 2019/10/23 - Changelog: https://github.com/linuxserver/docker-letsencrypt/commits/master/root/defaults/proxy.conf

client_body_buffer_size 128k;

#Timeout if the real server is dead
proxy_next_upstream error timeout invalid_header http_500 http_502 http_503;

# Advanced Proxy Config
send_timeout 10m;
proxy_read_timeout 1200;
proxy_send_timeout 1200;
proxy_connect_timeout 1200;

# TLS 1.3 early data
proxy_set_header Early-Data $ssl_early_data;

# Basic Proxy Config
proxy_set_header Host $http_host;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header X-Forwarded-Proto https;
proxy_set_header X-Forwarded-Host $http_host;
proxy_set_header X-Forwarded-Ssl on;
proxy_redirect http:// $scheme://;
proxy_http_version 1.1;
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection $connection_upgrade;
proxy_cache_bypass $cookie_session;
proxy_no_cache $cookie_session;
proxy_buffers 32 4k;
proxy_headers_hash_bucket_size 128;
proxy_headers_hash_max_size 1024;
```

**Comment by Procuria** [comment]
Sorry @causefx for the heavy latency - but better late than never: _THANK_ you so much for your effort. Your suggested switch to the root dir in my nginx conf worked out like a charm :)

**Comment by louisefindlay23** [comment]
> I just tried connecting Trakt.tv to Organizr last night and have run into an issue:
> 
> in the screenshot, the numbers indicate the settings from both Organizr and trakt, and it's result when trying to auth from within Org.
> 
> The bottom image is what results when I try to just auth from Trakt itself, when I click that "authorize" button.
> 
> ![image](https://user-images.githubusercontent.com/1524526/108609809-23551800-7396-11eb-831a-9a1c5a4b5dec.png)
> 
> I noticed something with the `code` param in the urls, which don't seem to match, which I put red rectangles around; dunno whether or not they're an issue in this case.
> 
> If I go directly to the redirect URL Organizr gives me, I get this:
> 
> ```
> {
>     "response": {
>         "result": "error",
>         "message": "Endpoint Not Found or Defined",
>         "data": {
>             "endpoint": "/api/v2/oauth/trakt%20Authorize",
>             "method": "GET"
>         }
>     }
> }
> ```
> 
> I use the LinuxServer Swag Nginx RP for all my stuff, so all the headers you mentioned above are already "baked in" to each RP, so to speak (i.e. I don't have to add them manually each time).
> 
> here's the full error I get when trying to auth from within Org:
> 
> ```
> Slim Application Error
> The application could not run because of the following error:
> 
> Details
> Type: GuzzleHttp\Exception\RequestException
> Code: 0
> Message: cURL error 77: error setting certificate verify locations: CAfile: /config/www/organizr/api/functions/cert/cacert.pem CApath: none (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)
> File: /config/www/organizr/api/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php
> Line: 201
> Trace
> #0 /config/www/organizr/api/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(155): GuzzleHttp\Handler\CurlFactory::createRejection()
> #1 /config/www/organizr/api/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(105): GuzzleHttp\Handler\CurlFactory::finishError()
> #2 /config/www/organizr/api/vendor/guzzlehttp/guzzle/src/Handler/CurlHandler.php(43): GuzzleHttp\Handler\CurlFactory::finish()
> #3 /config/www/organizr/api/vendor/guzzlehttp/guzzle/src/Handler/Proxy.php(28): GuzzleHttp\Handler\CurlHandler->__invoke()
> #4 /config/www/organizr/api/vendor/guzzlehttp/guzzle/src/Handler/Proxy.php(51): GuzzleHttp\Handler\Proxy::GuzzleHttp\Handler\{closure}()
> #5 /config/www/organizr/api/vendor/guzzlehttp/guzzle/src/PrepareBodyMiddleware.php(66): GuzzleHttp\Handler\Proxy::GuzzleHttp\Handler\{closure}()
> #6 /config/www/organizr/api/vendor/guzzlehttp/guzzle/src/Middleware.php(29): GuzzleHttp\PrepareBodyMiddleware->__invoke()
> #7 /config/www/organizr/api/vendor/guzzlehttp/guzzle/src/RedirectMiddleware.php(70): GuzzleHttp\Middleware::GuzzleHttp\{closure}()
> #8 /config/www/organizr/api/vendor/guzzlehttp/guzzle/src/Middleware.php(59): GuzzleHttp\RedirectMiddleware->__invoke()
> #9 /config/www/organizr/api/vendor/guzzlehttp/guzzle/src/HandlerStack.php(71): GuzzleHttp\Middleware::GuzzleHttp\{closure}()
> #10 /config/www/organizr/api/vendor/guzzlehttp/guzzle/src/Client.php(361): GuzzleHttp\HandlerStack->__invoke()
> #11 /config/www/organizr/api/vendor/guzzlehttp/guzzle/src/Client.php(113): GuzzleHttp\Client->transfer()
> #12 /config/www/organizr/api/vendor/guzzlehttp/guzzle/src/Client.php(130): GuzzleHttp\Client->sendAsync()
> #13 /config/www/organizr/api/vendor/league/oauth2-client/src/Provider/AbstractProvider.php(608): GuzzleHttp\Client->send()
> #14 /config/www/organizr/api/vendor/league/oauth2-client/src/Provider/AbstractProvider.php(621): League\OAuth2\Client\Provider\AbstractProvider->getResponse()
> #15 /config/www/organizr/api/vendor/league/oauth2-client/src/Provider/AbstractProvider.php(537): League\OAuth2\Client\Provider\AbstractProvider->getParsedResponse()
> #16 /config/www/organizr/api/functions/oauth.php(23): League\OAuth2\Client\Provider\AbstractProvider->getAccessToken()
> #17 /config/www/organizr/api/v2/routes/oauth.php(6): Organizr->traktOAuth()
> #18 /config/www/organizr/api/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(43): {closure}()
> #19 /config/www/organizr/api/vendor/slim/slim/Slim/Routing/Route.php(384): Slim\Handlers\Strategies\RequestResponse->__invoke()
> #20 /config/www/organizr/api/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): Slim\Routing\Route->handle()
> #21 /config/www/organizr/api/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): Slim\MiddlewareDispatcher->handle()
> #22 /config/www/organizr/api/vendor/slim/slim/Slim/Routing/Route.php(341): Slim\MiddlewareDispatcher->handle()
> #23 /config/www/organizr/api/vendor/slim/slim/Slim/Routing/RouteRunner.php(84): Slim\Routing\Route->run()
> #24 /config/www/organizr/api/vendor/slim/slim/Slim/Middleware/RoutingMiddleware.php(59): Slim\Routing\RouteRunner->handle()
> #25 /config/www/organizr/api/vendor/slim/slim/Slim/MiddlewareDispatcher.php(147): Slim\Middleware\RoutingMiddleware->process()
> #26 /config/www/organizr/api/vendor/slim/slim/Slim/Middleware/ErrorMiddleware.php(107): class@anonymous->handle()
> #27 /config/www/organizr/api/vendor/slim/slim/Slim/MiddlewareDispatcher.php(147): Slim\Middleware\ErrorMiddleware->process()
> #28 /config/www/organizr/api/v2/index.php(90): class@anonymous->handle()
> #29 /config/www/organizr/api/vendor/slim/slim/Slim/MiddlewareDispatcher.php(313): {closure}()
> #30 /config/www/organizr/api/vendor/slim/slim/Slim/MiddlewareDispatcher.php(81): class@anonymous->handle()
> #31 /config/www/organizr/api/vendor/slim/slim/Slim/App.php(215): Slim\MiddlewareDispatcher->handle()
> #32 /config/www/organizr/api/vendor/slim/slim/Slim/App.php(199): Slim\App->handle()
> #33 /config/www/organizr/api/v2/index.php(129): Slim\App->run()
> #34 {main}
> Go Back
> ```

Having the same issue as above. Should I open a separate issue?
