### ISSUE TITLE
[UI Error] When entering in the wrong login info a "Welcome Login Successful" message appears and then goes back to the login screen

### ISSUE THREAD

**Issue by Cookie-Monster-Coder** [causefx/Organizr#1575]
###### Operating System: Ubuntu
<hr>

##### Problem Description:
When entering in the wrong login info a "Welcome Login Successful" message appears and then goes back to the login screen. When it should say "Error, invalid username or password."

<hr>

##### Reproduction Steps:
1. Try login in with wrong username/password
2. See error

<hr>

#### Errors on screen?  If so paste here:

```
Welcome
Login Successful
```

**Comment by causefx** [comment]
![image](https://user-images.githubusercontent.com/16184466/106550484-7000ae00-64d0-11eb-9faf-5e2725706819.png)

i just tried on mobile and worked as intended. i will try on computer shortly.

**Comment by causefx** [comment]
same on PC:
![image](https://user-images.githubusercontent.com/16184466/106550922-5d3aa900-64d1-11eb-8037-d23a1a9acb3a.png)

**Comment by Cookie-Monster-Coder** [comment]
I just tried it with a fresh install to. Maybe it's Nginx caching issue. I'll try to clear them now

**Comment by causefx** [comment]
The fresh install was fine?

**Comment by Cookie-Monster-Coder** [comment]
No, same issue

**Comment by causefx** [comment]
try logging in without reverse proxy...

**Comment by Cookie-Monster-Coder** [comment]
Yeah, I think it has something to do with my nginx
