### ISSUE TITLE
Nginx Won't Start - Logon Failure

### ISSUE THREAD

**Issue by wglynn01** [causefx/Organizr#1578]
Organizr Version: V2
Branch: v2-master
WebServer: Nginx 1.16.1
Operating System: Windows 10
<hr>

##### Problem Description:
Sorry in advance. I barely know what I am doing. I tried to open Organizr today and it gave me an error that the site can't be reached. Checked the nginx service and it wasn't started. Tried starting it and it gave an error that there was a logon failure. Tried updating with my windows username and pw, still logon failure. Tried uninstalling organizr and reinstalling, getting "the service did not start due to a logon failure" during setup. If I complete the installation and try to open Organizr, I get "502 Bad Gateway". Windows did recently install an update. Haven't looked into that yet. Not sure where to go from here. Thanks.

<hr>

##### Reproduction Steps:

<hr>

#### Errors on screen?  If so paste here:

```

```

**Comment by wglynn01** [comment]
Others are getting responses and I'm not, so I'm assuming I'm doing something wrong here. Would someone be so kind to help a idiot out and point me in the right direction so I can get this working again?

**Comment by causefx** [comment]
where did you update user/pass? nana or services in windows?

**Comment by wglynn01** [comment]
Services in windows. Thanks for the reply!

**Comment by wglynn01** [comment]
:-(

**Comment by causefx** [comment]
not sure where to troubleshoot from there....

If you sign up on github sponsor or patreon we could remote in and check it out real quick.
