### ISSUE TITLE
Does this happen to anyone else?

### ISSUE THREAD

**Issue by jscottelblein** [causefx/Organizr#1580]
![image](https://user-images.githubusercontent.com/1524526/107074590-8e0b2e80-67ae-11eb-998d-cf1f525817ca.png)

<hr>

##### Problem Description:
On the Recently Added Plex widget, when first loading the home page, the posters for audio files (mp3) tile over the whole page for a few seconds before going to the normal size. It's not app-breaking, but pretty ugly.

<hr>

##### Reproduction Steps:
Add a bunch of mp3's to your Plex server so that they show up in the recently added widget, then load the Organizr homepage.

I haven't pinned it down exactly yet, but seems to happen when you nav away from the homepage to another Organizr page (i.e. settings  page) and then go back to the homepage. It may help to do a ctrl+f5 on the settings page before going back to the homepage.

So far it doesn't seem to trigger when going to another app though, i.e. sonarr, and then going back to the home page.

<hr>

#### Errors on screen?  If so paste here:

![image](https://user-images.githubusercontent.com/1524526/107075247-797b6600-67af-11eb-8c85-19d3df22306c.png)

In the screenshot, all of those Howard Stern covers are mp3's, the mandalorian covers are vids. After a few seconds, all of those Howard Stern covers disappear and go to their proper place and size in a single row in the widget.

**Comment by causefx** [comment]
hmmm wtf lol..... it seems the owl component is breaking or something....  I tried replicating but couldn't.  I will keep this open to see if I see it.

**Comment by STaRDoGG** [comment]
@causefx maybe  I can hook ya up with a few of these mp3s, for a more direct test?

**Comment by bxlouis** [comment]
@STaRDoGG sorry to ask here but where did you find your "Coding" and "System" category icons? 
Do they come with Organizr? I did not find any under plugins/images/categories/
If not, would you mind sharing them?

**Comment by jscottelblein** [comment]
@bxlouis Notta problem. I just dug em up from image searches on the  web, trying to find  some that sort of matched with the rest of the icons. Here ya go.

![Settings 48x48](https://user-images.githubusercontent.com/1524526/107108111-3c3cc580-67fb-11eb-8e74-ee871a715aad.png)
![coding](https://user-images.githubusercontent.com/1524526/107108112-3cd55c00-67fb-11eb-8e83-398fe2750dde.png)

**Comment by jscottelblein** [comment]
@causefx I made a mistake in my description of the problem. It looks like what it's doing is loading all covers (of any type, mp3 or otherwise) like that at first, and then when they're done loading, "moves" them to the single row of covers. The single row is the row that's blurred out. I wonder if a "fix" would be to just set the visibility of the covers hidden until they're all done loading, then unhide them again. Then you just wouldn't see that while loading the covers.

**Comment by causefx** [comment]
what is the item limit you have set in the plex homepage item setttings

**Comment by jscottelblein** [comment]
> what is the item limit you have set in the plex homepage item setttings

@causefx I have it set to 50 (which is the default I think?)

**Comment by jscottelblein** [comment]
still an issue Gitbot. ;)

**Comment by causefx** [comment]
i still have yet to replicate this issue.

**Comment by jscottelblein** [comment]
@causefx It might've been due to a (slower) CPU. I had the issue when Organizr was running on a Phenom II 965, which was plenty fast for pretty much everything, but recently upgraded that machine's CPU to a Phenom II 1100T, just because I was adding a new CPU fan, so why not upgrade the CPU while I'm at it, lol, and I haven't noticed it since.

My assumption is that it's actually still happening, but the new CPU is just fast enough to not actually "see" it happen anymore.
