### ISSUE TITLE
[Bug Maybe] Having `auth_request /auth-4` in the Jellyfin location block breaks SSO for Jellyfin

### ISSUE THREAD

**Issue by Cookie-Monster-Coder** [causefx/Organizr#1581]
###### Operating System: Ubuntu
<hr>

##### Problem Description:

First of all I don't know if this Intentional and it's supposed to do this. But having ```auth_request /auth-4``` in the Jellyfin location block breaks SSO for Jellyfin.

As I type this, I'm thinking it's working as intended since Organizr can't "contact" Jellyfin until after I successful logged it, but idk.
<hr>

##### Reproduction Steps:

1. Enable SSO for Jellyfin
2. Add ```auth_request /auth-4``` in the jellyfin location block
3. Login and see that jellyfin is not logged in

<hr>

**Comment by causefx** [comment]
is it not setting the cookie or what is happening

**Comment by Cookie-Monster-Coder** [comment]
Yeah, I'm pretty sure it's not able to get the cookie as having auth_request /auth-4 blocks it from communicating to jellyfin

**Comment by causefx** [comment]
maybe has something to do with: #1585
