### ISSUE TITLE
LDAP with TLS fails negotiation

### ISSUE THREAD

**Issue by CSmither** [causefx/Organizr#1582]
###### Operating System: Debian
<hr>

##### Problem Description:
When setting up LDAP with TLS under settings > main > authentication it fails to connect to the LDAP server, always giving the following error on the openLDAP server logs
```
openldap        | 6023e682 conn=2744 fd=17 ACCEPT from IP=xx.xx.xx.xx:50272 (IP=0.0.0.0:636)
openldap        | TLS: can't accept: An unexpected TLS packet was received..
openldap        | 6023e682 conn=2744 fd=17 closed (TLS negotiation failure)
```

I have taken a look at #1411 and tried the fix in there. But it seems like that issue has been fixed since then. So no luck there
<hr>

##### Reproduction Steps:
- ##### configure ldap authentication with the following options.... #####
    Authentication Type: `Backend Only`
    Authentication Backend: `Ldap`
    Ignore External 2FA on Local Subnet: `off`
    Host Address: `ldaps://ldap.example.com:636`
    Host Base DN: `ou=user,dc=example,dc=com`
    LDAP Backend Type: `OpenLDAP`
    Account Prefix: `uid=`
    Bind Username: 'cn=admin,dc=example,dc=com'
    Enable LDAP SSL: `off`
    Enable LDAP TLS: `on`
- ##### Click on `Test Connection` #####
- Error Message on UI and in LDAP Logs

<hr>

#### Errors on screen?  If so paste here:
- ##### Organizr UI Error #####
```
API Error
Can't connect to LDAP server
```
- ##### LDAP Server Error #####
```
openldap        | 6023e682 conn=2744 fd=17 ACCEPT from IP=xx.xx.xx.xx:50272 (IP=0.0.0.0:636)
openldap        | TLS: can't accept: An unexpected TLS packet was received..
openldap        | 6023e682 conn=2744 fd=17 closed (TLS negotiation failure)
```

**Comment by CSmither** [comment]
Not Stale

**Comment by causefx** [comment]
I will have someone test this soon.... i hope.
