### ISSUE TITLE
Transmission Connect Function - Error: Could not get session ID

### ISSUE THREAD

**Issue by jpf4e** [causefx/Organizr#1583]
###### Operating System: CentOS 8
<hr>

##### Problem Description:
When testing the homepage integration with Transmission, it gives the following error:
`Transmission Connect Function - Error: Could not get session ID`
This error also appears in logs.
Using Transmission v3.00

<hr>

##### Reproduction Steps:
Configure the Transmission download client in the homepage.

<hr>

#### Errors on screen?  If so paste here:

```

```

**Comment by causefx** [comment]
can you share or  screenshot your settings?

**Comment by jpf4e** [comment]
Organizr:
![image](https://user-images.githubusercontent.com/20103641/107708539-8e7a5c80-6cbb-11eb-9e0f-556e6c3540aa.png)

Transmission settings:
```
{
    "alt-speed-down": 4092,
    "alt-speed-enabled": false,
    "alt-speed-time-begin": 540,
    "alt-speed-time-day": 127,
    "alt-speed-time-enabled": false,
    "alt-speed-time-end": 1020,
    "alt-speed-up": 2048,
    "bind-address-ipv4": "0.0.0.0",
    "bind-address-ipv6": "::",
    "blocklist-enabled": false,
    "blocklist-url": "http://www.example.com/blocklist",
    "cache-size-mb": 4,
    "dht-enabled": true,
    "download-dir": "/home/joao/Downloads",
    "download-queue-enabled": false,
    "download-queue-size": 15,
    "encryption": 1,
    "idle-seeding-limit": 30,
    "idle-seeding-limit-enabled": false,
    "incomplete-dir": "/var/lib/transmission/Downloads",
    "incomplete-dir-enabled": false,
    "lpd-enabled": false,
    "message-level": 1,
    "peer-congestion-algorithm": "",
    "peer-id-ttl-hours": 6,
    "peer-limit-global": 500,
    "peer-limit-per-torrent": 50,
    "peer-port": 51413,
    "peer-port-random-high": 65535,
    "peer-port-random-low": 49152,
    "peer-port-random-on-start": false,
    "peer-socket-tos": "default",
    "pex-enabled": true,
    "port-forwarding-enabled": true,
    "preallocation": 1,
    "prefetch-enabled": true,
    "queue-stalled-enabled": true,
    "queue-stalled-minutes": 5,
    "ratio-limit": 2,
    "ratio-limit-enabled": true,
    "rename-partial-files": true,
    "rpc-authentication-required": false,
    "rpc-bind-address": "0.0.0.0",
    "rpc-enabled": true,
    "rpc-host-whitelist": "",
    "rpc-host-whitelist-enabled": true,
    "rpc-password": "{8d130c0c4674af592fe9feb3a8793dd5caee3b06pE6Pfu9q",
    "rpc-port": 9091,
    "rpc-url": "/transmission/",
    "rpc-username": "",
    "rpc-whitelist": "127.0.0.1,::1",
    "rpc-whitelist-enabled": false,
    "scrape-paused-torrents-enabled": true,
    "script-torrent-done-enabled": false,
    "script-torrent-done-filename": "",
    "seed-queue-enabled": false,
    "seed-queue-size": 10,
    "speed-limit-down": 100,
    "speed-limit-down-enabled": false,
    "speed-limit-up": 2048,
    "speed-limit-up-enabled": false,
    "start-added-torrents": true,
    "trash-original-torrent-files": false,
    "umask": 2,
    "upload-slots-per-torrent": 14,
    "utp-enabled": true
}
```

Also, after making a change to the URL and Test the connection sometimes the error is this one instead:
`Transmission Connect Function - Error: cURL error 60: SSL certificate problem: unable to get local issuer certificate [Execution Time: 24.4ms]`

I am not using any kind of proxy for transmission and I use HTTP to access it.

**Comment by jpf4e** [comment]
Okay, I needed to include this as the config: http://192.168.1.81:9091/transmission/
However, curiously enough, it failed the test the first time I clicked Test connection. But after trying the second time and on it worked.
Also, when I loaded my homepage I needed to refresh the transmission section to see the items.

**Comment by causefx** [comment]
Do you know if `/transmission` or `/transmission/rpc` is even configurable in the transmission settings?

**Comment by jpf4e** [comment]
`/transmission`:
No, it won't let you access the web interface:
![image](https://user-images.githubusercontent.com/20103641/107712123-c0da8880-6cc0-11eb-83ce-6e02c0f8cc25.png)
It doesn't print logs. This time this appears on the home page:
`Connection Error to transmission`

`/transmission/web`:
It also doesn't let you.
![image](https://user-images.githubusercontent.com/20103641/107712446-56761800-6cc1-11eb-8c9b-b92765756fed.png)
