### ISSUE TITLE
Homepage recents add /jellyfin unusable link

### ISSUE THREAD

**Issue by SavageAUS** [causefx/Organizr#1588]
###### Operating System: unraid
<hr>

##### Problem Description:
Opening movie from jellyfin "widget" produces non working link by adding /jellyfin 

<hr>

##### Reproduction Steps:
Add jellyfin to homepage, configure, click movie from recently added, link opens with /jellyfin added.
![Screen Shot 2021-02-17 at 10 49 25 pm](https://user-images.githubusercontent.com/17326832/108203424-6a62c380-7172-11eb-88d4-953160274152.png)

<hr>

#### Errors on screen?  If so paste here:

```

```

**Comment by HalianElf** [comment]
Did you fill out the Jellyfin Homepage Link URL under under Misc Options in the Jellyfin Homepage Item settings? It should be building the link based off of what's in there.

**Comment by SavageAUS** [comment]
Yes it would appear when setting up the link somehow an extra /jellyfin was added.
