### ISSUE TITLE
Youtube preview not working with own API key

### ISSUE THREAD

**Issue by gshlomi** [causefx/Organizr#1591]
##### Problem Description:
When trying to play a youtube trailer from the homepage, with a private API key added via Custom homepage item, getting an error popup saying:
YouTube API Error
Bad response from YouTube

##### Reproduction Steps:
Set a youtube API key following https://www.slickremix.com/docs/get-api-key-for-youtube/, try to press the Youtube icon on any 
of the items under Recently Added on Requests

#### Errors on screen?  If so paste here:
```
![image](https://user-images.githubusercontent.com/4084415/108531804-c860e980-72df-11eb-9a6b-b2ec423e9880.png)

```

**Comment by causefx** [comment]
sorry about the delay. i'll be checking this out tomorrow.

**Comment by causefx** [comment]
Hi i tested with 4 new keys and got results each time

**Comment by gshlomi** [comment]
Thanks,
Tried again now, works great.

**Comment by neo-neo1** [comment]
Is this still working? I tried 2 different (known good) API keys and Organizr throws error `Bad response from YouTube`

**Comment by keesfluitman** [comment]
where do you actually add the api? I cant find it.

**Comment by HalianElf** [comment]
Homepage items > Misc

**Comment by gehx** [comment]
Where is "Homepage Items"? Organzr Version: 2.1.2490
