### ISSUE TITLE
Unifi Monitor gives error3

### ISSUE THREAD

**Issue by maichai** [causefx/Organizr#1592]
###### Operating System: Linux Slackware / Unraid
<hr>

##### Problem Description:
Unifi Monitor says: API Error Unifi response error3
<hr>

##### Reproduction Steps:
In Tab Editor > Homepage Item > Unifi monitor click on Test connection

Comments: retrieving the site list does work, so in general the API does work and the connection should also be there. The Unifi controller is the last V5, NOT V6! 
<hr>

#### Errors on screen?  If so paste here:

```
API Error Unifi response error3
```

**Comment by angrycuban13** [comment]
Are you trying to connect using an account that has 2FA on?

**Comment by maichai** [comment]
No 2FA, only local connect, not via cloud.

**Comment by angrycuban13** [comment]
Can you hit F12 and look in the console for any errors when you click on `Test Connection`?

**Comment by maichai** [comment]
The api test POST has a "409 conflict", after that it gives "unifi response error3"

**Comment by angrycuban13** [comment]
Could you please post a screenshot of the console while blurring any PII?

**Comment by maichai** [comment]
![blurb](https://user-images.githubusercontent.com/47572832/108776899-4da80080-7563-11eb-9588-f027d976fccc.png)

**Comment by alesnav** [comment]
I get the same error HTTP 409 when Organizr sends a request to `https://<organizr>/api/v2/homepage/unifi/data`

```
{
    "response": {
        "result": "error",
        "message": "Unifi response error3",
        "data": null
    }
}
```

Organizr version 2.1.235

**Comment by Riza-Aslan** [comment]
Same issue here. Organizr and the Unifi controller are both in Docker containers. I've also another "issue". When I click on the "Grab Unifi Site" button it shows me a pop-ip with the correct site name, but if I click on it, I get a notification "Grabbed Site", but there is nothing in the site name field. Not a big deal to enter it manually, but maybe it has something todo with the other issue.

**Comment by RangerFX4** [comment]
Have also the same issue cant somehow make unfi work when grabbing the site a white popup appears. Then when testing connection the API Error Unifi response error3 will appear.

unraid 6.9 with latest docker img of organizrv2.
![Capture](https://user-images.githubusercontent.com/13778998/111018563-8ade1080-83f4-11eb-9120-d4dce04159a2.PNG)

**Comment by causefx** [comment]
try typing “default” into site name

**Comment by RangerFX4** [comment]
> try typing “default” into site name
> […](#)
> Sent from my iPhone
> On Mar 12, 2021, at 9:09 PM, RangerFX4 ***@***.***> wrote: ﻿ Have also the same issue cant somehow make unfi work when grabbing the site a white popup appears. Then when testing connection the API Error Unifi response error3 will appear. unraid 6.9 with latest docker img of organizrv2. — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

This worked thanks! but when pressing grabbing the site still same popup with white background using latest edge browser.

**Comment by maichai** [comment]
using "default" as site name does not produce the error I described, but it doesn't help either, as I am not using the default site, so in the home screen it shows "Unifi:" and nothing else.

**Comment by maichai** [comment]
This should not be closed

**Comment by maichai** [comment]
This should not be closed

**Comment by BastLeblanc** [comment]
+1 same issue

**Comment by angrycuban13** [comment]
Bump

**Comment by causefx** [comment]
cuban are you running controller via non unifi OS as well?

**Comment by angrycuban13** [comment]
I am running it on Docker. I haven't seen it but I was just bumping it 😂

**Comment by ghost** [comment]
Confirmed the same issue here running on an Ubuntu-based VM.

**Comment by ghost** [comment]
Default corrects this issue, but it also pulls no data because I'm not using the default site.

**Comment by causefx** [comment]
Does anyone want to give me limited api access to test this?

**Comment by thousandbuckle** [comment]
I am having the same issue getting the saner error when I go to Test Connection. I can grab the Unifi site ID just fine on the connection tab but when I go to the Test Connection I get API Error Unifi Response error3.

**Comment by causefx** [comment]
i think i have an old cloud key somewhere around here...

**Comment by thousandbuckle** [comment]
That would be awesome if you can figure this out. I really would like to use this we can get it working. Thank you!!!!

**Comment by causefx** [comment]
if anyone is on dev branch, can you test latest commit?

**Comment by Ninja-FSE** [comment]
> if anyone is on dev branch, can you test latest commit?

I updated to the dev branch and now it works!

**Comment by causefx** [comment]
> > if anyone is on dev branch, can you test latest commit?
> 
> 
> 
> I updated to the dev branch and now it works!

awesome!!! thank you. i will push this to master tomorrow.
