### ISSUE TITLE
Cusom pages fonctionality request

### ISSUE THREAD

**Issue by webac** [causefx/Organizr#160]
Organizer is nice PHP app that I use since some weeks to organize all my dockerized apps.

But I miss one this nice functionality, the ability to add customize PHP pages directly inside Organizr,
So instead of using an url as a default start page I can use a custom page with some gadgets that I can add.

Thank you
L

**Comment by causefx** [comment]
Can you explain this a little more please?

**Comment by webac** [comment]
What I mean is that currently we can add tabs that match links,
the idea is to have another option that permit to add to tabs a custom pages (using maybe an WYSIWYG editor).

It maybe a bad idea that does not correspond to the purpose of this application :)

**Comment by webac** [comment]
ok I didn't seen this
https://github.com/causefx/Organizr/issues/115

**Comment by causefx** [comment]
ah yea, im still working on something for that. thanks.
