### ISSUE TITLE
Tautulli Widget Not Loading on Homepage

### ISSUE THREAD

**Issue by theradiostar** [causefx/Organizr#1603]
###### Operating System: UnRAID
<hr>

##### Problem Description:
When loading the Homepage, the Tautulli widget times out and fails to load.

From the logs:

`March 4, 2021 11:24 AM | SYSTEM | 192.168.1.118 | Tautulli Connect Function - Error: cURL error 28: Operation timed out after 10001 milliseconds with 0 bytes received [Execution Time: 11.34s \| 11344.5ms]`

<hr>

**Comment by causefx** [comment]
it seems your server is taking to long to respond. trying upping the homepage item refresh time.
