### ISSUE TITLE
Android Mobile Chrome won't scroll on Splash screen

### ISSUE THREAD

**Issue by jonesnotathome** [causefx/Organizr#1604]
###### Operating System: Ubuntu
<hr>

##### Problem Description:
After logging into Organizr and presented with the Splash screen buttons I cannot scroll on Android Mobile. The 'Close Splash' button is present and allows me to close the splash and scrolling is then enabled. Again. I suspect something wrong with the focus layer on the page.

> HERE--->

<hr>

##### Reproduction Steps:
Create a splash screen with enough buttons to fill up the Android Mobile Chrome browser. Try to scroll to additional items.

<hr>

#### Errors on screen?  If so paste here:
No errors present.
```

```

**Comment by causefx** [comment]
i will fix soon
