### ISSUE TITLE
Login Error: API Connection Failed when using Opera Browser

### ISSUE THREAD

**Issue by dma9** [causefx/Organizr#1608]
###### Operating System: Ubuntu
<hr>

##### Problem Description:
Just recently switched from Chrome to Opera on same Windows 10 client. When attempting to login to my Organizr instance on a separate Ubuntu container using Opera, I get the following message in the bottom right hand corner: "Login Error: API Connection Failed" and am not logged in. If I attempt to login again, nothing happens and no message is presented. If I refresh the page and try to login again, I get the same error. 

I've disabled all extensions and ad-blocking in Opera. When I switch back to Chrome it works just fine.

Any thoughts or suggestions on how I might be able to remedy would be most appreciated.

<hr>

##### Reproduction Steps:
1. Download and install Opera
2. Access Organizr webpage
3. Attempt to login to Organizr.

<hr>

#### Errors on screen?  If so paste here:

```
Login Error: API Connection Failed
```

**Comment by HalianElf** [comment]
Are you using just the Organizr login or Plex oAuth? It sounds like you're hitting this: https://docs.organizr.app/books/troubleshooting/page/plex-login-error---api-connection-failed

**Comment by causefx** [comment]
Check Hailian's response as I just installed Opera to test and logged in fine:
![image](https://user-images.githubusercontent.com/16184466/110706210-becaf300-81b4-11eb-82f5-002b5fe71420.png)

**Comment by dma9** [comment]
Thanks to both of you. Very puzzling. I am not using Plex oAuth. In Settings/Main/Authentication, Authentication Type is set to Organizr DB. I also checked the nginx error log and it was empty. Just tried it again in Opera and got the same error, then tried Chrome again and it works just fine. Perhaps not surprising, but the logs in the web ui don't identify any login attempt. Very puzzling, and clearly something specific to my install given your ability to login. I dunno. If you have any thoughts on how I might further be able to diagnose, do let me know. Not hugely critical as I can always just revert to Chrome to use Organizr.

**Comment by causefx** [comment]
you can try to log into the demo organizr site:


https://demo.organizr.app

username:
demo_admin
password:
demo_password

**Comment by dma9** [comment]
Hey thanks for the suggestion. I can log into the demo site just fine. Still no luck with my own, unfortunately.

**Comment by causefx** [comment]
I would assume it has to do with your nginx proxy.  Can you post those settings

**Comment by dma9** [comment]
Hey thanks again. Settings in the .conf file are as follows:

```
server {
        listen 80;
        listen [::]:80;
#        listen 443 ssl http2;
#        listen [::]:443 ssl http2;
        server_name organizr.dcn.ma;
        root /var/www/organizr.dcn.ma/html;
        index index.php index.html index.htm index.nginx-debian.html;
        location ~ /auth-(.*) { rewrite ^/auth-(.*) /api/?v2/auth?group=$1; } #Org Auth
        location /api/v2 {
                try_files $uri /api/v2/index.php$is_args$args;
        }
        error_page 401 $scheme://$server_name/?error=$status&return=$request_uri;
        error_page 400 402 403 404 405 408 500 502 503 504 $scheme://$server_name/?error=$status;
        location / {try_files $uri $uri/ =404;}
        include config/organizr.dcn.ma/phpblock.conf;  #PHP Block
        include conf.d/apps/*.conf;  #apps
}
```

**Comment by causefx** [comment]
can you make me a temp user acct on your install and DM (discord) or email the url and user details?
causefx at me dot com

**Comment by dma9** [comment]
I could but unfortunately I don't have the install exposed to the internet - only the LAN.
