### ISSUE TITLE
Heads up: New Jellyfin API

### ISSUE THREAD

**Issue by polhaghverdian** [causefx/Organizr#1609]
Hello,

After installing new Jellyfin 10.7.0 the integration doesn't seem to work anymore. They have changed the API which could be the cause?

https://github.com/jellyfin/jellyfin/releases/tag/v10.7.0

Client/Plugin (API/ABI) Developer Notes

    We have migrated from ServiceStack to ASP.NET. Web API endpoints no longer accept HTTP Form requests; everything must be application/json. NOTE: Plugins that implement endpoints will also have to migrate.
    Plugins must now target net5.0.
    IHttpClient removal: Now inject IHttpClientFactory instead.
    HttpException removal: Now catch HttpResponseException instead.
    Services can be registered to the DI pipeline.

Please see the Jellyfin Development Matrix channel for questions or further details on these changes.

**Comment by causefx** [comment]
thanks, I will check this out.

**Comment by LeVraiRoiDHyrule** [comment]
Yes, the SSO doesn't work (and never did for me) with Jellyfin. The homepage item works but not SSO and my users and I have to re-sign in to jellyfin everytime.

**Comment by HalianElf** [comment]
SSO requires a subfolder same as Plex due to the way the cookie is

**Comment by LeVraiRoiDHyrule** [comment]
> 
> 
> SSO requires a subfolder same as Plex due to the way the cookie is

I have an nginx reverse proxy and my jellyfin is with a /jellyfin subpath. Is that what you are talking about ?

**Comment by HalianElf** [comment]
Yes, but I just tested... it appears the API hasn't changed but the name of the cookie has so it will be busted with 10.7

**Comment by LeVraiRoiDHyrule** [comment]
Ok I understand. Is there a way I could fix this myself ? Or can I expect a fix from Organizr later ?

**Comment by HalianElf** [comment]
It's not going to be a very simple fix... the cookie name now has the user id in it so it's going to require looking at the API response to see if it gives that and also looks like the whole cookie json changed as well

**Comment by causefx** [comment]
SSO should be fixed in dev now
