### ISSUE TITLE
Monitorr image paths not working

### ISSUE THREAD

**Issue by goose-ws** [causefx/Organizr#1612]
###### Operating System: Debian 10
<hr>

##### Problem Description:
Images in the "Monitorr" home page item are not properly displaying.

![image](https://user-images.githubusercontent.com/874014/111626625-a2d2dd00-87c4-11eb-9bc7-42b985ea37d3.png)

For reference, the images for `Vergil` and `BitWarden` are both user-uploaded, while the images for `Plex` and `Ombi` are both already provided by Monitorr.

The console shows a 404 for `config/www/organizr/plugins/images/cache/no-list.png`. Inspecting the images shows:

![image](https://user-images.githubusercontent.com/874014/111626859-d6156c00-87c4-11eb-8eee-896fa9681df3.png)

**Comment by GilbN** [comment]
Does it happen when using the default theme?

**Comment by goose-ws** [comment]
Yes, same result with default theme.

**Comment by causefx** [comment]
fixed in dev - will push to master today
