### ISSUE TITLE
SABNzbd homepage order not working

### ISSUE THREAD

**Issue by Fronix** [causefx/Organizr#1614]
###### Operating System: Debian
<hr>

##### Problem Description:
SABNzbd homepage item not being ordered correctly. It's always at the bottom of the homepage.

![image](https://user-images.githubusercontent.com/631180/111871182-22110e00-8989-11eb-93b3-4cb1f5cfa981.png)

![image](https://user-images.githubusercontent.com/631180/111871282-63a1b900-8989-11eb-88ad-17128926d3d9.png)

![image](https://user-images.githubusercontent.com/631180/111871298-76b48900-8989-11eb-96b7-6ce50edaca86.png)

<hr>

##### Reproduction Steps:
1. Enable SABNzbd homepage item
2. Go to hompage order and choose a spot
3. Check on homepage

<hr>

#### Errors on screen?  If so paste here:

```

```

**Comment by HalianElf** [comment]
I can't replicate this. Can you try moving it somewhere else and then moving it back? There was a bug with the order numbering a while back and it may just need a reset on the numbers.

**Comment by Fronix** [comment]
> I can't replicate this. Can you try moving it somewhere else and then moving it back? There was a bug with the order numbering a while back and it may just need a reset on the numbers.

I tried disabling everything and enabling it again. Reordered everything and now it seems to work.
