### ISSUE TITLE
Request: New Homepage Item for Disk Usage

### ISSUE THREAD

**Issue by nuentes** [causefx/Organizr#1616]
Yes, I know that I can install NetData or Monitorr. I don't want to. I don't see any need for installing a full blown monitoring service on my server when all I want is disk usage, which can be acquired with a simple SMB or NFS connection with read-only permissions.

I'd imagine the config would simply ask for a list of SMB paths along with a customizable drive label. Then the widget would simply show the corresponding Drives with the path and drive label, and a graphic showing a dial with total space vs remaining space. Possible? And if I should post this elsewhere, let me know. Thanks!

**Comment by HalianElf** [comment]
Please use [FeatureUpvote](https://vote.organizr.app) for feature requests
