### ISSUE TITLE
New Bookmarks section enhancement/suggestion

### ISSUE THREAD

**Issue by tvann2182** [causefx/Organizr#1617]
###### Operating System: Ubuntu
<hr>

##### Problem Description:
This is in regards to bookmarks tab addition. This should have an option for either iframe or open new window as this opens directly on top of your organizr instance and then you have to hit the back button in order to get back to organizr. Also to add when it comes to the background color and text color, if you do not know hex values you have to look them up as there is no way to type the word grey you have to know the hex #ffffff 

<hr>

##### Reproduction Steps:
create a new bookmark, list the required fields i.e. name, address, icon, background color and text color via hex#. then open the bookmarks section. from there when you click on the book mark it takes your current page and becomes your newly clicked bookmark. if you want to return to organizr you either have to open a new tab or hit the back button until you reach your organizr again.

<hr>

#### Errors on screen?  If so paste here:

```

```

**Comment by HalianElf** [comment]
Color picker is in #1606, new window would be nice though

**Comment by causefx** [comment]
#1606 merged with dev
