### ISSUE TITLE
Changing position of Sonarr-queue in Tab Editor>Homepage Order has no effect

### ISSUE THREAD

**Issue by zilexa** [causefx/Organizr#1618]
###### Using the official docker image
<hr>

##### Problem Description:
Cannot change the position of Sonarr Queue on the homepage. 
<hr>

##### Reproduction Steps:

1. Tab Editor > Homepage Order> move `Sonarr Queue` to any other position than bottom. Save.
2. Open Organizr in a private tab or clean cache and open. 
3. Notice it is still at the very bottom. 

Regardless of its position in the Editor, it will always stay at the very bottom (even with a clean browser). 

<hr>

#### Errors on screen?  If so paste here:
no errors reported.

**Comment by causefx** [comment]
can you goto api/config/config.php

and paste all the items that start with `homepageOrder`

**Comment by zilexa** [comment]
Sorry for the delay, had some hardware related issues to fix first: 

```
	'homepageOrderJackett' => '5',
	'homepageOrderMonitorr' => '27',
	'homepageOrderNetdata' => '1',
	'homepageOrderOctoprint' => '31',
	'homepageOrderPihole' => '11',
	'homepageOrderRadarrQueue' => '30',
	'homepageOrderSonarrQueue' => '6',
	'homepageOrderSpeedtest' => '29',
	'homepageOrderWeatherAndAir' => '28',
	'homepageOrdercalendar' => '4',
	'homepageOrdercustomhtml' => '12',
	'homepageOrdercustomhtmlTwo' => '13',
	'homepageOrderdeluge' => '16',
	'homepageOrderdownloader' => '24',
	'homepageOrderembynowplaying' => '14',
	'homepageOrderembyrecent' => '15',
	'homepageOrderhealthchecks' => '9',
	'homepageOrderjdownloader' => '25',
	'homepageOrderjellyfinnowplaying' => '2',
	'homepageOrderjellyfinrecent' => '3',
	'homepageOrdernzbget' => '17',
	'homepageOrderombi' => '22',
	'homepageOrderplexnowplaying' => '19',
	'homepageOrderplexplaylist' => '21',
	'homepageOrderplexrecent' => '20',
	'homepageOrderqBittorrent' => '7',
	'homepageOrderrTorrent' => '23',
	'homepageOrdersabnzbd' => '18',
	'homepageOrdertautulli' => '26',
	'homepageOrdertransmission' => '9',
	'homepageOrderunifi' => '8',
```

Sonarr queue is still shown at the very bottom, below Unfi wifi. The numbers don't really make sense to me as I dragged Unifi to the bottom and it is shown at the bottom, but has number 8.
