### ISSUE TITLE
Incorrect Custom Error Pages documentation

### ISSUE THREAD

**Issue by VibroAxe** [causefx/Organizr#1620]
###### Documentation Page:https://docs.organizr.app/books/setup-features/page/custom-error-pages
<hr>

##### Problem Description:
The documentation for Custom Error Pages is incorrect when using subdomains with nginx
```error_page 401 $scheme://organizr.app/?error=$status&return=$request_uri; # We only want the Unauthorized code to redirect back to the loginpage```

Should include the scheme and host in addition to the return uri, otherwise Organizr will redirect to organizr.app$request_uri

```error_page 401 $scheme://organizr.app/?error=$status&return=$scheme://$host$request_uri; # We only want the Unauthorized code to redirect back to the loginpage```

**Comment by VibroAxe** [comment]
I'd happily submit a PR to fix this, but I can't find the source for docs.organizr.app anywhere

**Comment by HalianElf** [comment]
It's Bookstack so you wouldn't be able to PR anything since it doesn't use git. Either way, I added it.
