### ISSUE TITLE
Transmission Connection Failure when using special characters in the password

### ISSUE THREAD

**Issue by jeffwrusso** [causefx/Organizr#1623]
###### Operating System: Docker/Synology
<hr>

##### Problem Description:
When setting up the connection to Transmission it fails with the following:
Error: cURL error 6: Could not resolve host: <username you entered>

<hr>

##### Reproduction Steps:
Setup Transmission homepage item and have a Transmission connection password that has special characters in it (for example # and *).  Connection works fine if you update the password to remove special characters.

<hr>

#### Errors on screen?  If so paste here:

```
Error: cURL error 6: Could not resolve host:
```

Since the connection is made in this format `http://user:passsword@192.168.1.1:9091/transmission/rpc` the following will fix it.  I have tested and verified it's working for me.

Find in transmission.php twice:
`$this->decrypt($this->config['transmissionPassword'])`

And replace with:
`rawurlencode($this->decrypt($this->config['transmissionPassword']))`

**Comment by causefx** [comment]
added in dev, thank you!
