### ISSUE TITLE
Docker, reverse proxy, and baseurl

### ISSUE THREAD

**Issue by sjthespian** [causefx/Organizr#1624]
###### Operating System: Alpine (Docker image from organizr/organizr:latest)
<hr>

##### Problem Description:
I found an old feature request in #69 for support for a baseurl in Organizr to allow for reverse-proxy to a subdirectory when running as a docker container. While that issue is closed, I don't see anything in it or the documentation that says that this was ever implemented.

Would it be possible to get support for a baseurl to allow reverse-proxying Organizr under a subdirectory instead of a base domain? This is common in most of the Plex utilities that Organizr supports such as sonarr (and the other *arrs) and Tautulli.

I have tried a couple options for just trying to do this with the Organizer nginx config, but haven't found a working config yet. All of my attempts so far have resulted in `This Server has been wrongly configured`. Even if I do get it working, I'm worried that an upgrade will rewrite the config and erase my changes.

<hr>

##### Reproduction Steps:
1. Install Organzr via. docker on some port, for example 8089
2. Set up an nginx server pointing to Organizr as a reverse proxy:
```
upstream organizr {
        server yourhost:8089;
}
server {
        listen [::]:80;
        # ... standard nginx server setup ...
        location /organizr {
                proxy_pass http://organizr;
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection $http_connection;

        }
}
```
3. Go to http://yourhost/organzir and receive a 404
4. Find a message similar to the following in the Organizr access log:
```
172.26.0.1 - - [03/Apr/2021:21:25:16 -0700] "GET /organizr/ HTTP/1.1" 404 181 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36"
```

<hr>

#### Errors on screen?  If so paste here:

```

```

**Comment by HalianElf** [comment]
Add `rewrite /organizr(.*) $1 break;` to your location block

**Comment by sjthespian** [comment]
Unfortunately that only works for the main page, not everything else (it's actually what I was laying in bed thinking about last night and planning on trying this morning). With that it throws:
```
Webserver not setup for Organizr v2.1
Please goto Migration guide to complete the changes...
Webserver Error:
404 Not Found
```

And `Fatal Error: You need to update web server location block... check browser console for migration URL`.

The console shows:
```
https://docs.organizr.app/books/setup-features/page/organizr-20--%3E-21-migration-guide
  API V2 API
  If you see a 404 Error for api/v2/launch below this line, you have not setup the new location block... See URL above this line 
Failed to load resource: the server responded with a status of 404 ()    /organizr/api/v2/launch:1
```

I've been tweaking things to find the right combination of rewrites to get this working, and I think I'm close though... I'l update when I have something.

**Comment by HalianElf** [comment]
You're doing something wrong then. I just tested and it worked fine with this config.
```nginx
location /organizr {
    return 301 $scheme://$host/organizr/;
}
location /organizr/ {
    include /config/nginx/proxy.conf;
    #resolver 127.0.0.11 valid=30s;
    set $upstream_app organizr;
    set $upstream_port 80;
    set $upstream_proto http;
    proxy_pass $upstream_proto://$upstream_app:$upstream_port;

    rewrite /organizr(.*) $1 break;
}
```
Everything in Organizr is set on relative paths so it should work fine just with that. (The top location block is to stop nginx from throwing an error if you go to `/organizr` due to the rewrite)

**Comment by sjthespian** [comment]
Ah, you're adding the redirect on the proxy end! I was trying to add it to the config used by the Organizr container. That did the trick, thanks!

Great job on the application btw, I was just working on a landing page for all of my Plex related apps when I ran across this.
