### ISSUE TITLE
fatal error

### ISSUE THREAD

**Issue by arissaraiva** [causefx/Organizr#1625]
###### Operating System: Windows
<hr>

##### Problem Description:
I´ve just installed a new HD and when I installed and opened organizr page gives me: "fatal error you need to update webserver location block.... check borwser console for migration url" I did found migration but couldn´t understand what I´m supposed to change, need some help please.

<hr>

##### Reproduction Steps:

<hr>

#### Errors on screen?  If so paste here:

```[error] 2696#8212: *22 CreateFile() "c:/nginx/www/organizr/html/api/v2/launch" failed (2: FormatMessage() error:(15105)), client: 192.168.xxxxxxx, server: localhost, request: "GET /api/v2/launch HTTP/1.1", host: "192.168.0.47", referrer: "http://192.168.xxxxx/"


```

**Comment by tronyx** [comment]
User is being helped in Discord, closing this.
