### ISSUE TITLE
Don't open splash when directly navigating to the page

### ISSUE THREAD

**Issue by Gagi2k** [causefx/Organizr#1627]
How to reproduce:

1. Create a tab, show it in the splash
2. Open the new tab
3. Url changes to <url>#<tabname>
4. Open <url>#<tabname> in new browser tab (or just press reload)
5. The splash screen is shown again

Exptected behavior:

The splash screen is a nice way to show all available tabs in a grid form for fast selection, but for direct navigation to certain page it would be great to skip the splash screen in those cases.

**Comment by causefx** [comment]
fixed in dev.  thanks!
