### ISSUE TITLE
Enable categories in the splash screen

### ISSUE THREAD

**Issue by Gagi2k** [causefx/Organizr#1628]
When you configure your tabs in categories, it would be great to use the same categories/grouping also on the splash page.

With that it would be possible to great a nice dashboard page e.g.:

![](https://www.yeetpc.com/blog/homer-services-dashboard/Images/dashboard.png)

**Comment by HalianElf** [comment]
There is already a feature request in for this: https://vote.organizr.app/suggestions/150923/add-categories-to-splash-screen
