### ISSUE TITLE
There is no radarrNew4k icon [I have attached a temporary one]

### ISSUE THREAD

**Issue by kvn1351** [causefx/Organizr#1629]
There's no 4k version of the RadarrNew icon. So I made a temporary one for now.

If I could get the source of the icon I could make a more professional job.

Here's the one I made meanwhile:

![radarr4knew](https://user-images.githubusercontent.com/11823348/114629539-129b9100-9cb9-11eb-94a8-803fabc27d9e.png)

Have a nice day all of you.

**Comment by causefx** [comment]
added in dev.

**Comment by Excessive12** [comment]
What are the chances of a Sonarr one that's the same :)

**Comment by HalianElf** [comment]
> What are the chances of a Sonarr one that's the same :)

this already exists https://github.com/causefx/Organizr/blob/v2-master/plugins/images/tabs/sonarr4k.png
