### ISSUE TITLE
After doing interactions in Emby tab, Organizr stops responding

### ISSUE THREAD

**Issue by 3lysium** [causefx/Organizr#163]
1. When I navigate a few seconds in the created Emby tab, Organizr sidebar stops responding and I need to reload the page because button clicks do nothing.

2. When theme music is enabled and start playing in an Emby detail screen, you cannot navigate. This behaviour is not always visible, but sometimes.

**Comment by causefx** [comment]
assuming this is desktop and not mobile correct?  if so, anything in the console log?

**Comment by 3lysium** [comment]
Yes, Desktop. 

It seems it has to do with SABnzbd? There are no errors in console, but it seems when I go on the SABnzbd tab and then go back to another Console gives out "blablabla is active already" and the log gets flooded by SABnzbd messages.

Just realized that Organizr seems to be a fork of Muximux and there it's not happen.

This is the consol snippet when error begins. I hope you can find something since I like Organizr very much.

`(index):128 XHR finished loading: GET "https://mydomain/sabnzbd/tapi?mode=queue&search=&start=0&limit=20&output=json&apikey=a52f1fc3d9f59e3c2953c4c43cea8a68&_=1490030688364".
(index):128 XHR finished loading: GET "https://mydomain/sabnzbd/tapi?mode=history&search=&failed_only=0&st…030297&output=json&apikey=a52f1fc3d9f59e3c2953c4c43cea8a68&_=1490030688365".
(index):1173 https://mydomain/sabnzbd/ is active already
(index):128 XHR finished loading: GET "https://mydomain/sabnzbd/tapi?mode=queue&search=&start=0&limit=20&output=json&apikey=a52f1fc3d9f59e3c2953c4c43cea8a68&_=1490030688366".
(index):128 XHR finished loading: GET "https://mydomain/sabnzbd/tapi?mode=history&search=&failed_only=0&st…030297&output=json&apikey=a52f1fc3d9f59e3c2953c4c43cea8a68&_=1490030688367".
(index):128 XHR finished loading: GET "https://mydomain/sabnzbd/tapi?mode=queue&search=&start=0&limit=20&output=json&apikey=a52f1fc3d9f59e3c2953c4c43cea8a68&_=1490030688368".
(index):128 XHR finished loading: GET "https://mydomain/sabnzbd/tapi?mode=history&search=&failed_only=0&st…030297&output=json&apikey=a52f1fc3d9f59e3c2953c4c43cea8a68&_=1490030688369".
(index):1173 https://mydomain/sabnzbd/ is active already
(index):128 XHR finished loading: GET "https://mydomain/sabnzbd/tapi?mode=queue&search=&start=0&limit=20&output=json&apikey=a52f1fc3d9f59e3c2953c4c43cea8a68&_=1490030688370".
(index):128 XHR finished loading: GET "https://mydomain/sabnzbd/tapi?mode=history&search=&failed_only=0&st…030297&output=json&apikey=a52f1fc3d9f59e3c2953c4c43cea8a68&_=1490030688371".
(index):128 XHR finished loading: GET "https://mydomain/sabnzbd/tapi?mode=queue&search=&start=0&limit=20&output=json&apikey=a52f1fc3d9f59e3c2953c4c43cea8a68&_=1490030688372".
(index):128 XHR finished loading: GET "https://mydomain/sabnzbd/tapi?mode=history&search=&failed_only=0&st…030297&output=json&apikey=a52f1fc3d9f59e3c2953c4c43cea8a68&_=1490030688373".
(index):128 XHR finished loading: GET "https://mydomain/sabnzbd/tapi?mode=queue&search=&start=0&limit=20&output=json&apikey=a52f1fc3d9f59e3c2953c4c43cea8a68&_=1490030688374".
(index):128 XHR finished loading: GET "https://mydomain/sabnzbd/tapi?mode=history&search=&failed_only=0&st…030297&output=json&apikey=a52f1fc3d9f59e3c2953c4c43cea8a68&_=1490030688375".
(index):128 XHR finished loading: GET "https://mydomain/sabnzbd/tapi?mode=queue&search=&start=0&limit=20&output=json&apikey=a52f1fc3d9f59e3c2953c4c43cea8a68&_=1490030688376".
(index):128 XHR finished loading: GET "https://mydomain/sabnzbd/tapi?mode=history&search=&failed_only=0&st…030297&output=json&apikey=a52f1fc3d9f59e3c2953c4c43cea8a68&_=1490030688377".
(index):128 XHR finished loading: GET "https://mydomain/sabnzbd/tapi?mode=queue&search=&start=0&limit=20&output=json&apikey=a52f1fc3d9f59e3c2953c4c43cea8a68&_=1490030688378".
(index):128 XHR finished loading: GET "https://mydomain/sabnzbd/tapi?mode=history&search=&failed_only=0&st…030297&output=json&apikey=a52f1fc3d9f59e3c2953c4c43cea8a68&_=1490030688379".
(index):128 XHR finished loading: GET "https://mydomain/sabnzbd/tapi?mode=queue&search=&start=0&limit=20&output=json&apikey=a52f1fc3d9f59e3c2953c4c43cea8a68&_=1490030688380".
(index):128 XHR finished loading: GET "https://mydomain/sabnzbd/tapi?mode=history&search=&failed_only=0&st…030297&output=json&apikey=a52f1fc3d9f59e3c2953c4c43cea8a68&_=1490030688381".`

**Comment by causefx** [comment]
That log looks normal,  Sab is just sending GET requests, which it is logging in the console log.  I will test emby in a tab today when I get home.  I will try and see what is happening.  

As for the muximux comment, Organizr isn't a fork of that.  Organizr is completely written from the ground up.

**Comment by 3lysium** [comment]
Sorry, just tried it out because I found a comment of you in the issues from muximux stating you forked it. Did not assume that it's a full rewrite from scratch. Sorry.

Just tried on mobile, the "not working tab buttons" occurs there also after some tab switching. Even the Emyb back button in detail screen left top side freezes then. I hope you can reproduce to solve it.

Thanks!

**Comment by causefx** [comment]
ahhh, yea that was a different project.  "iDashboard"  

I will check back tonight when i get home.

**Comment by causefx** [comment]
did you still notice this?

**Comment by Cerothen** [comment]
Closing as there was no response for 24 days

**Comment by 3lysium** [comment]
Sorry, busy at home. No everything is perfect now! Thanks!
