### ISSUE TITLE
Jellyfin homepage items do nothing

### ISSUE THREAD

**Issue by RoryNesbitt** [causefx/Organizr#1630]
###### Operating System: Unraid/Docker (Bridge network)
<hr>

##### Problem Description:

Neither the Jellyfin homepage items (current playing and recent) show anything on the home page. On a refresh the module shows as loading but after a couple seconds just disappears as if it hasn't found anything
<hr>

##### Reproduction Steps:

Jellyfin has been added by the local IP and both active streams and recent items have been activated.
![connection](https://user-images.githubusercontent.com/33930918/115229929-88fe2000-a10b-11eb-8b75-129af8a47b91.PNG)
Testing the Connection always succeeds.
Misc options are left at default.
<hr>

**Comment by causefx** [comment]
What version of jellyfin? Also, what is your base URL?
Edit:
I just tested on 10.7.2
![image](https://user-images.githubusercontent.com/16184466/115468686-48c09f80-a1e8-11eb-8565-d972a25bfbda.png)
![image](https://user-images.githubusercontent.com/16184466/115468783-6c83e580-a1e8-11eb-8ad9-cc677406392a.png)
![image](https://user-images.githubusercontent.com/16184466/115468819-79083e00-a1e8-11eb-91a6-766db9617826.png)

**Comment by RoryNesbitt** [comment]
This took literally days to finally fix (and I never got the notification that you replied, apologies for ghosting) but turns out it was a copy paste issue. 
The api key, while looking correct, had a tab at the end of it. Removing this fixed the issue
