### ISSUE TITLE
Tautulli iFrame Login Loop

### ISSUE THREAD

**Issue by gdtms247** [causefx/Organizr#1636]
###### Operating System: Official Docker
<hr>

##### Problem Description:
When set to iFrame I can't log into tautulli using plex auth. Its successfully popping out a new tab, I login then it closes the tab however organizr is still sitting at same page. I have the SSO enabled and its working for Plex and Ombi however tautulli doesn't work. I can log into it successfully in its own tab, and if I log into iframe window i'm actually signed out of the tab so its "working" I believe. I've been running Organizr for a few months now and this is now the last "thing" I haven't gotten working properly so time to sort out why (its never worked as iframe for me and I honestly gave up on initial setup and left it as pop out window). 

One strange thing is in Organizr I see Ombi and tatutuli both in logs even though i've yet to log into ombi. I cleared all cookies/cache in my browser after logging out of organizr with no luck as well.

<hr>

##### Reproduction Steps:
Set tautulli to use iframe. Log in using Plex auth. 

<hr>

#### Errors on screen?  If so paste here:
No errors on screen. Infact logs for both show success.

Organizr Log:
April 29, 2021 10:25 AM	admin	192.168.38.22	Tautulli Token Function - Grabbed token from: http://192.168.37.201:8181/home [Execution Time: 362.5ms]	
April 29, 2021 10:25 AM	admin	192.168.38.22	Ombi Token Function - Ombi did not return Token [Execution Time: 478ms]	

Tautulli Log:
Tautulli WebAuth :: Admin user 'jmontague' logged into Tautulli using Plex OAuth login.

**Comment by HalianElf** [comment]
Are Organizr and Tautulli on the same domain/IP?

**Comment by gdtms247** [comment]
All are on their own IP, all running as docker in unraid


plex | 192.168.37.200
tautulli | 192.168.37.201
organizr | 192.168.37.212
ombi | 192.168.37.213

**Comment by HalianElf** [comment]
It's this then: https://docs.organizr.app/books/troubleshooting/page/redirect-looping---samesite-errors

Not an Organizr issue, you have to fix your setup.

**Comment by gdtms247** [comment]
Ive yet to see "Are you seeing some console errors in your browser about SameSite Cookies?" where would I validate?

I have no proxy in play here, and everything is done by IP address. I validated in chrome I have same site cookies disabled.

**Comment by HalianElf** [comment]
Tautulli hard sets it to not allow SameSite which it says on that docs page I linked so I don't think you'll see an console error.

Proxy doesn't matter, different IPs are considered different domains and therefore fall under SameSite rules.

**Comment by gdtms247** [comment]
Option #1 - If you are browsing locally, you can add host records to your network or machine that you are browsing with. 
Option #2 - If you are browsing from WAN, you can create reverse proxies. 
Option #3 - Depending on your browser software you can just turn off this check.

host records would only be used for DNS resolution, which nothing is using. Im accessing local so option 2 doesn't come into play, and option 3 is done I have this disabled on Chrome. Organizr still can't log into Tautulli so whats my next step?

**Comment by HalianElf** [comment]
Since Tautulli hard sets it, Option 3 isn't an option... that only changes the behavior if it's *not* set.

Your options are the first two - which if you don't want to switch to using DNS, your only option is new window.

**Comment by gdtms247** [comment]
So if I set FQDN for everything in my local domain and access sites using FQDN vs IP samesite doesn't come into play?

**Comment by HalianElf** [comment]
Correct since everything would share the parent domain at that point which is considered SameSite and allowed.

**Comment by gdtms247** [comment]
Man i've spent past few years getting out of using FQDN to simplify my life :) so much for that. I'll get it entered and try it out thanks for the help!

**Comment by gdtms247** [comment]
Using DNS is a winner, loads perfectly. Thanks @HalianElf!
