### ISSUE TITLE
Update Error, Download Failed

### ISSUE THREAD

**Issue by Cookie-Monster-Coder** [causefx/Organizr#1638]
###### Operating System: Ubuntu
<hr>

##### Problem Description:
Keep getting Update Error, Download Failed error. Tried new browser and and cleared cache. I haven't made any changes from the last update. When I wget https://github.com/causefx/Organizr/archive/v2-develop.zip the file downloads successfully.

<hr>

##### Reproduction Steps:

<hr>

#### Errors on screen?  If so paste here:

```
Update Function - Downloaded Update File Failed for Branch: v2-develop [Execution Time: 5.1ms]	
organizr could not download https://github.com/causefx/Organizr/archive/v2-develop.zip [Execution Time: 18ms]	
Update Function - Started Upgrade Process [Execution Time: 2.3ms]
```

**Comment by Cookie-Monster-Coder** [comment]
Found this post (https://github.com/causefx/Organizr/issues/1316#issuecomment-743489588)

I went to ```/var/www/domain.com/html/api/functions/cert``` and noticed that I had ```cacert-initial.pem``` with about 223,000 bytes and ```cacert.pem``` with 0 bytes. I deleted ```cacert.pem``` and renamed ```cacert-initial.pem``` to ```cacert.pem``` and that seemed to worked.

**Comment by causefx** [comment]
i'll research this further to fix the root problem.

**Comment by Pupwiz** [comment]
also had issue - Did as Cookie said and all good now

**Comment by causefx** [comment]
Issue should be fixed now - thanks guys
