### ISSUE TITLE
During installation, I always get the same error, no matter what.

### ISSUE THREAD

**Issue by AHumanPerson** [causefx/Organizr#164]
I keep getting this error:

Fatal error: Uncaught PDOException: SQLSTATE[HY000] [14] unable to open database file in /var/www/html/Organizr/user.php:191 Stack trace: #0 /var/www/html/Organizr/user.php(191): PDO->__construct('sqlite:/var/www...') #1 /var/www/html/Organizr/index.php(72): User->__construct('registration_ca...') #2 {main} thrown in /var/www/html/Organizr/user.php on line 191

no matter what I do. I did attempt to give everyone permissions via chmod 777, change chown to multiple users, nothing. I tried the steps listed in the troubleshooting guide, please help.

**Comment by AHumanPerson** [comment]
already checked check.php and everything is green, don't see anything on line 191 but was having trouble installing sudo apt-get install php5-sqlite, returning package not found. php5-sqlite3 was my only option if that is of any value.

**Comment by causefx** [comment]
where is the db file?

in relation to /var/www/html/Organizr

what OS?

**Comment by AHumanPerson** [comment]
In /Organizer/DB

On ubuntu server

**Comment by causefx** [comment]
that directory needs to be writable by www-data

**Comment by AHumanPerson** [comment]
It is

**Comment by causefx** [comment]
can you do command `ll` on /Organizr so i can see the print out?

**Comment by AHumanPerson** [comment]
The database file is inside the Organizr directory. I also tried moving it out and allowing read write execute permissions to all users for /html via chmod

**Comment by causefx** [comment]
delete databaseLocation.ini.php
reload Organizr
for DB Path, choose /var/www/html/Organizr

see if it loads that way first...

**Comment by AHumanPerson** [comment]
OK. Give me a few minutes

**Comment by causefx** [comment]
ok

**Comment by AHumanPerson** [comment]
Thank you so much! It worked!

**Comment by AHumanPerson** [comment]
Not completely related  to this issue, don't know if I should create a new one. 

None of the webpages show up when I add them. I had the same problem when using a docker container for this. If I use hostname:9000, its empty, if i do 127.0 0.1:9000 , then it says:

Not Found

The requested URL /Organizr/127.0 0.1:9000 was not found on this server.

Apache/2.4.18 (Ubuntu) Server at hostname Port 80

**Comment by causefx** [comment]
try with http://

**Comment by causefx** [comment]
also what service is it?

**Comment by AHumanPerson** [comment]
Good call that's probably it as it affects all devices and sites. Will have to try tommorow.

**Comment by causefx** [comment]
lemme know if it works.

**Comment by AHumanPerson** [comment]
Worked thanks
