### ISSUE TITLE
Login Error - API Connection Failed

### ISSUE THREAD

**Issue by ibracorp** [causefx/Organizr#1641]
###### Operating System: Docker on Unraid
<hr>

##### Problem Description:
When trying to sign in get an error 
- Only way to use Organizr is with a session already signed in from days ago.
- The same user cannot sign in to a new or private web browser session
- While in an already signed-in session, can confirm that LDAP backend connection tests OK without issues.

Everything has been working fine before today. I noticed that there's a new update (today) to Organizr, unsure if it related or not.

<hr>

##### Reproduction Steps:
- Using LDAP Backend only
- Try sign in using a known working account
- Receive error

<hr>

#### Errors on screen?  If so paste here:

```
Login Error
API Connection Failed
```
![image](https://user-images.githubusercontent.com/67491741/116851177-4bce7d80-ac35-11eb-9750-36e6f8f64e2b.png)

**Comment by ibracorp** [comment]
- Changed Auth to Organizr DB + Backend
- Created a local user
- Signed in successfully

Also done the following:
- Created a new user in FreeIPA
- Attempted to log in as the user in Organizr
- Received the error reported above
- Checked the user list using my local account and the user did indeed get pulled from FreeIPA successfully.

Not sure what's happening? Inside Organizr I can test the connection to LDAP without issues, so why is the login screen different?

Thanks CauseFX.

**Comment by CAPS3** [comment]
I'm currently using LDAP and can report the same symptoms.  Local accounts work fine. 

After some messing around with a test instance, I think the issue might be related to settings under "System Settings --> Single Sign-On --> Jellyfin" as toggling this option from Enabled to Disabled seemed to resolve the API Connection Failed error (when accessed externally via https://fqdn). 

I'm using http://IP:PORT/jellyfin/ as the Jellyfin API url (with /jellyfin base url configured in jellyfin and nginx-proxy-manager), and https://domain.com/jellyfin/ as the Jellyfin SSO URL.   If I sign into Organizr via the local IP , there's no issues (except for jellyfin SSO not working). 

Worth noting that in my test environment, organizr auth was set to Jellyfin backend only and Jellyfin configured with LDAP, so users have been able to sign into organizr with just email address.  

I agree that it seems to be related to the most recent update ( #1609?)  Happy to do some testing if you need me to try anything in dev :) .

**Comment by causefx** [comment]
@ibracorp can you check both Organizr logs and nginx logs (container and proxy)

**Comment by ibracorp** [comment]
Sure @causefx 

Organizr
```
-----------------------
| Updating Organizr |
-----------------------
From https://github.com/causefx/Organizr
3853bf89..d32ccc94 v2-master -> origin/v2-master
7e27d2fe..74858260 v2-develop -> origin/v2-develop
HEAD is now at d32ccc94 Merge pull request #1640 from causefx/v2-develop
Already on 'v2-master'
Your branch is up to date with 'origin/v2-master'.
HEAD is now at d32ccc94 Merge pull request #1640 from causefx/v2-develop
hint: Pulling without specifying how to reconcile divergent branches is
hint: discouraged. You can squelch this message by running one of the following
hint: commands sometime before your next pull:
hint:
hint: git config pull.rebase false # merge (the default strategy)
hint: git config pull.rebase true # rebase
hint: git config pull.ff only # fast-forward only
hint:
hint: You can replace "git config" with "git config --global" to set a default
hint: preference for all repositories. You can also pass --rebase, --no-rebase,
hint: or --ff-only on the command line to override the configured default per
hint: invocation.
Already up to date.
[cont-init.d] 40-install: exited 0.
[cont-init.d] 50-debug: executing...
-----------------------
| Kernel Info |
-----------------------
Linux a037c0cee5b3 5.10.28-Unraid #1 SMP Wed Apr 7 08:23:18 PDT 2021 x86_64 GNU/Linux
Time Zone: Australia/Sydney
[cont-init.d] 50-debug: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
```
NGINX Proxy Manager
```
[5/4/2021] [9:29:45 AM] [Nginx ] › ℹ info Reloading Nginx
```
Important to note that neither generated any additional logs after trying to log in. The logs above already existed. I had the logs and the login screen side by side and nothing was generated.

**Comment by ibracorp** [comment]
I can confirm what @CAPS3 has said regarding setting the Jellyfin SSO option to OFF - this resolves the issue and allows sign-in as normal.

Here's my settings in case that's the cause:
![image](https://user-images.githubusercontent.com/67491741/116946476-8c71d980-acbd-11eb-9b22-1d0a1b6d7275.png)

**Comment by causefx** [comment]
That leads me to believe you need to update your reverse proxy to include:
```
proxy_buffer_size          128k;
proxy_buffers              4 256k;
proxy_busy_buffers_size    256k;
```
(this is usally the proxy.conf file)
I bet if you goto local address of Organizr container - and log in it will be fine.

**Comment by ibracorp** [comment]
Yeah, that's correct as @CAPS3 mentioned locally it seems to work. 
I'll add those to the NGINX Proxy Manager config for Organizr and report back.

**Comment by ibracorp** [comment]
@causefx seems to have resolved it. At first, a popup came up after login and presented a 521 error from Cloudflare, so the page within it didn't load. But clicking "Close" took me to the homepage as normal.

Closed the session then started a new incognito and the sign-in worked as expected, with no pop-up box. Could have been a Changelog type thing?

Also, the SSO for Jellyfin still isn't working but my suspicion is that it's because of Cloudflare. Here's sample log:
```
[09:32:09] [INF] [12] Emby.Server.Implementations.Session.SessionWebSocketListener: Sending ForceKeepAlive message to 1 inactive WebSockets.
[09:33:09] [INF] [18] Emby.Server.Implementations.Session.SessionWebSocketListener: Sending ForceKeepAlive message to 1 inactive WebSockets.
[09:33:17] [INF] [18] Jellyfin.Server.Implementations.Users.UserManager: Authentication request for admin has succeeded.
[09:33:17] [INF] [18] Emby.Server.Implementations.Session.SessionManager: Current/Max sessions for user admin: 1/0
[09:33:17] [INF] [18] Emby.Server.Implementations.Session.SessionManager: Reissuing access token: 5764e07ab2ad4002a444978e65009a12
[09:34:09] [INF] [36] Emby.Server.Implementations.Session.SessionWebSocketListener: Sending ForceKeepAlive message to 1 inactive WebSockets.
[09:35:09] [INF] [39] Emby.Server.Implementations.Session.SessionWebSocketListener: Sending ForceKeepAlive message to 1 inactive WebSockets.
[09:35:32] [INF] [45] Jellyfin.Server.Implementations.Users.UserManager: Authentication request for admin has succeeded.
[09:35:32] [INF] [45] Emby.Server.Implementations.Session.SessionManager: Current/Max sessions for user admin: 1/0
[09:35:32] [INF] [45] Emby.Server.Implementations.Session.SessionManager: Reissuing access token: 5764e07ab2ad4002a444978e65009a12
[09:36:09] [INF] [53] Emby.Server.Implementations.Session.SessionWebSocketListener: Sending ForceKeepAlive message to 1 inactive WebSockets.
[09:37:09] [INF] [47] Emby.Server.Implementations.Session.SessionWebSocketListener: Sending ForceKeepAlive message to 1 inactive WebSockets.
[09:38:09] [INF] [23] Emby.Server.Implementations.Session.SessionWebSocketListener: Sending ForceKeepAlive message to 1 inactive WebSockets.
[09:39:00] [INF] [45] Jellyfin.Server.Implementations.Users.UserManager: Authentication request for admin has succeeded.
[09:39:00] [INF] [45] Emby.Server.Implementations.Session.SessionManager: Current/Max sessions for user admin: 1/0
[09:39:00] [INF] [45] Emby.Server.Implementations.Session.SessionManager: Reissuing access token: 5764e07ab2ad4002a444978e65009a12
[09:39:09] [INF] [96] Emby.Server.Implementations.Session.SessionWebSocketListener: Sending ForceKeepAlive message to 1 inactive WebSockets.
[09:40:09] [INF] [71] Emby.Server.Implementations.Session.SessionWebSocketListener: Sending ForceKeepAlive message to 1 inactive WebSockets.
[09:41:09] [INF] [36] Emby.Server.Implementations.Session.SessionWebSocketListener: Sending ForceKeepAlive message to 1 inactive WebSockets.
[09:42:09] [INF] [60] Emby.Server.Implementations.Session.SessionWebSocketListener: Sending ForceKeepAlive message to 1 inactive WebSockets.
[09:42:29] [INF] [23] Emby.Server.Implementations.HttpServer.WebSocketManager: WS IP_REDACTED request
[09:42:39] [INF] [42] Emby.Server.Implementations.HttpServer.WebSocketManager: WS IP_REDACTED closed
[09:42:53] [INF] [60] Jellyfin.Server.Implementations.Users.UserManager: Authentication request for admin has succeeded.
[09:42:53] [INF] [60] Emby.Server.Implementations.Session.SessionManager: Current/Max sessions for user admin: 1/0
[09:42:53] [INF] [60] Emby.Server.Implementations.Session.SessionManager: Creating new access token for user 0243dc4c-a074-4bd7-a11d-69f53464ed14
[09:42:54] [INF] [4] Emby.Server.Implementations.HttpServer.WebSocketManager: WS IP_REDACTED request
[09:42:58] [INF] [12] Emby.Server.Implementations.HttpServer.WebSocketManager: WS IP_REDACTED closed
[09:43:09] [INF] [4] Emby.Server.Implementations.Session.SessionWebSocketListener: Sending ForceKeepAlive message to 1 inactive WebSockets.
[09:44:09] [INF] [56] Emby.Server.Implementations.Session.SessionWebSocketListener: Sending ForceKeepAlive message to 1 inactive
```
In any case - anyone using NGINX Proxy Manager, go to your Organizr host > Advanced > Custom Configuration > Paste the below and Save:
```
proxy_buffer_size 128k;
proxy_buffers 4 256k;
proxy_busy_buffers_size 256k;
```
Double-check spaces as it sometimes adds additional ones. 

Thanks @causefx !

**Comment by causefx** [comment]
Can you see if you have a cookie for `jellyfin_credentials` after you logged in?

**Comment by ibracorp** [comment]
@causefx yes I can see the cookie in Chrome. Also realised that after initial sign in the homepage won't display until I refresh the page.

**Comment by causefx** [comment]
can you take a video or gif of that?

**Comment by ibracorp** [comment]
Are my Jellyfin SSO settings correct above? I have the FQDN in the SSO URL and the local address in the API URL. 

Yeah sure thing

**Comment by causefx** [comment]
it looks fine, it should have also created a 2nd cookie, with user credentials.  The only issue is, it only works if Jelly in on same domain, proxied as subfolder, not subdomain.

**Comment by ibracorp** [comment]
> it looks fine, it should have also created a 2nd cookie, with user credentials. The only issue is, it only works if Jelly in on same domain, proxied as subfolder, not subdomain.

Ahhh that's the issue then. I am using a subdomain for Jellyfin which is different to the Organizr subdomain. Look I'm not to worried about that anyway, as long as LDAP is working across both I'm happy and don't want to dilute the original issue.

I tested in an incognito session again and everything seems fine now, had one Error 520 from Cloudflare but meh.

If you have time could you help me understand why the extra info for proxy fixes the issue? Just for knowledge sake.
I assume it's this: https://docs.organizr.app/books/troubleshooting/page/plex-login-error---api-connection-failed

**Comment by causefx** [comment]
correct it was because of that. the issue is with adding new SSO options it increases the amount of cookies. that in turn increases the size of the header.

**Comment by ibracorp** [comment]
gotcha. That makes sense. Thanks for the help! I've shared the link around for anyone else having similar issues. 

Cheers

**Comment by CAPS3** [comment]
Hi All, 

Sorry for the delay - in Aus, so only just got a chance to take a look at the workaround.
I'm using home.domain.com and serving jellyfin from home.domain.com/jellyfin   (so they're both being served from the same domain)

If I add the workaround into the NGINX conf, I can sign in with one of my users, but if I try some others, I receive 
> 400 Bad Request
> Request Header Or Cookie Too Large
> nginx/1.18.0

If I add the workaround into the ~auth(.) location, the authentication seems successful (I.E I can hit /jellyfin which is behind the auth proxy) but the homepage never loads, It's like I just get redirected to the login screen.

**Comment by causefx** [comment]
and locally thru container ip and port it's fine 100% of the time?

**Comment by CAPS3** [comment]
Hi Causefx,

Yeah, I receive the same error locally (with local IP and port).

It's weird - I have 2 accounts (my main AD account and a test account) that get the above error locally, but most of the other accounts I've tested with seem to work without any issues. 

I might put it down to a configuration issue with those accounts; I'll recreate them in AD with same values, and assign to same groups and see if the issue still occurs.

**Comment by CAPS3** [comment]
Hi All - sorry for the thread necro - thought I'd post an update after messing around some more..., 

Not sure how to fix this issue permanently for the users with errors, but I found that there's issue might be because there's duplicate cookies that seem to be set? Removing just one of the cookies and refreshing the page allows it to load correctly. 
![image](https://user-images.githubusercontent.com/43501711/119472553-ae76ed00-bd8d-11eb-8a74-bcfa700c0a8d.png)

The duplicate cookies appear to be set once for my main domain, and once again for the subdomain that organizr is hosted off of. 

Can anyone suggest any other workaround to increase the size of the cookies? I've tried setting 
```
large_client_header_buffers 8 64k;
client_header_buffer_size 64k;    
```
in my nginx conf but this seems to result in cookies not being set at all (despite the toast message saying "login successful", i just get routed back to the login screen). I've tried exclusivly with the commands above, as well as with these values set. 
```
proxy_buffer_size 128k;
proxy_buffers 4 256k;
proxy_busy_buffers_size 256k;
```

The largest one is the "user-71e1f80f...." cookie (of which there are 2 due to the duplicates mentioned above) which displays the the size as 2860. I am using LDAP for jellyfin authentication, and the LDAP plugin was updated recently. I also recently enabled LiveTV in my jellyfin instace as well. When I look at the affected user accounts, I can see that they both have values for LDAP and LiveTV (among other things) set, and I wonder if this is what has caused the "Cookie or Header too Large" issue?

**Comment by HalianElf** [comment]
Is yours a native install and not docker with a reverse proxy?

**Comment by CAPS3** [comment]
Hi HalianElf, 
I currently use the organizr/organizr docker container and jc21/nginx-proxy-manager docker container.

**Comment by HalianElf** [comment]
The duplicate cookie thing is normal and expected (it's how server auth works when using a subdomain for Organizr and subdomains for the other applications as well) so I guess we're going to need clarity on what you're seeing when you are getting the cookies. Is it just jellyfin SSO not working or is it something with Organizr? It sounds like you may have a separate issue from what this issue was.

**Comment by CAPS3** [comment]
Initially, my error was the same as ibracor;  it was the API connection failure which was caused by the Jellyfin SSO option. This was resolved with the proxy buffer lines that CauseFX posted above, expect for some users I'd still get the "Header or Cookie too Large"

I will try to jump into Discord at some stage in the week and see if I can supply some more information :)
