### ISSUE TITLE
Adding SSL to Organizr stops some tabs from loading

### ISSUE THREAD

**Issue by RoryNesbitt** [causefx/Organizr#1644]
###### Operating System: Docker
<hr>

##### Problem Description:

I have Organizr set up behind a reverse proxy using Nginx-proxy-manager as well as each of the tabs. This works perfectly over http but when I give Organizr an ssl cert about half of the tabs fail to load. 
They continue to work as expected when organizr is accessed with the ip or if http is forced but never over https
<hr>

##### Reproduction Steps:

Setup reverse proxy and ssl
Compare tabs over http and https

**Comment by tronyx** [comment]
That's because HTTP content cannot be accessed over HTTPS. This is not an Organizr issue. You would need to configure reverse proxies for all of the applications you would wish to access as Tabs via HTTPS.
