### ISSUE TITLE
Downloaded Update File Failed but can fetch file without issue

### ISSUE THREAD

**Issue by ChaosBlades** [causefx/Organizr#1646]
###### Operating System: TrueNAS-12.0-U3.1 iocage jail
<hr>

##### Problem Description:
Getting "organizr could not download https://github.com/causefx/Organizr/archive/v2-master.zip [Execution Time: 175.8ms]"
I can 'fetch https://github.com/causefx/Organizr/archive/v2-master.zip' within the jail without issue

Tried the obvious things like reboot the jail/server. I also updated php from 7.2 to 8.0.5 and this did not resolve the issue.

Log file is not super helpful other than simply saying it can't be downloaded. I had no issues updating to the current version I am on.

Some insight as to what might be the culprit would be helpful.

<hr>

##### Reproduction Steps:
Try to update via WebUI

<hr>

#### Errors on screen?  If so paste here:

```
Download Error Download Failed
```

**Comment by HalianElf** [comment]
Check nginx logs?

**Comment by causefx** [comment]
This is a code issue that has now been fixed.  Please navigate to /api/functions/cert/

check if file `cacert.pem` is zero bytes... if it is rename `cacert-initial.pem` to `cacert.pem`

**Comment by ChaosBlades** [comment]
43 bytes

```
-rw-r--r--  1 www  www  223687 Feb 27 01:23 cacert-initial.pem
-rw-r--r--  1 www  www      43 Apr 30 19:07 cacert.pem
-rw-r--r--  1 www  www      28 Feb 27 01:23 index.html
```

This one?
https://github.com/causefx/Organizr/issues/1177

**Comment by causefx** [comment]
Hmmm can you cat that file to see what is in it?  Also for now just replace it with the initial file and redo the update.

**Comment by ChaosBlades** [comment]
`GIF89a^A^@^A^@�^@^@�^@^@^@^@^@!�^D^E^P^@^@^@,^@^@^@^@^A^@^A^@^@^B^B^D^A^@;`

That worked.
