### ISSUE TITLE
Netdata timedout

### ISSUE THREAD

**Issue by Shidapu** [causefx/Organizr#1647]
###### Operating System: Windows everything else, and Netdata on Ubuntu LTS
<hr>

##### Problem Description:
Netdata accessible via browser both locally and externally via subdomain.
Auth basic authentication setup on Nginx externally only, works great.

Organizr times out with error in Homescreen:
Netdata Connect Function - Error: cURL error 28: Operation timed out after 10012 milliseconds with 0 bytes received [Execution Time: 10.04s | 10043.9ms]

issue both externally and locally.
Specifying https://username:password@domain.com & ip:port
<hr>

**Comment by causefx** [comment]
sorry for the long time to respond, I will dig into this.

**Comment by Cookie-Monster-Coder** [comment]
To add to this, Netdata does try to load on the homepage but fails. Looking at inspect elements the homepage tries to load "https://domain.com/api/v2/homepage/netdata/data" but it get sent an "404 Not Found" error. Looking at the 404 error response it states "File does not exist, or is not accessible: /usr/share/netdata/web/data"

**Comment by causefx** [comment]
this will now use the timeout of the refresh status.

```
$options = $this->requestOptions($url, $this->config['homepageNetdataRefresh'], $this->config['netdataDisableCertCheck'], $this->config['netdataUseCustomCertificate']);
			$response = Requests::get($dataUrl, [], $options);
```

updated in dev, master on friday
