### ISSUE TITLE
Transmission home page module hangs on PHP 8

### ISSUE THREAD

**Issue by aniqueta** [causefx/Organizr#1648]
###### Operating System: Ubuntu
<hr>

##### Problem Description:

Transmission home page module hangs on PHP 8
<hr>

##### Reproduction Steps:

1. Fresh install of Organizr using nginx 1.19 and PHP 8.
2. Setup Transmission homepage module; test API works
3. Activate combined downloaded for Transmissions
3. Visit home page

<hr>

#### Errors on screen?  If so paste here:
Loading spinner spins indefinitely and no data loads from Transmission. Checking the nginx error log reveals a PHP deprecation issue. I don't know if the above behavior is explained by this.

```
FastCGI sent in stderr: "PHP message: PHP Deprecated:  usort(): Returning bool from comparison function is deprecated, return an integer less than, equal to, or greater than zero in /var/www/organizr/api/homepage/transmission.php on line 243" while reading response header from upstream, client: 255.255.255.255, server: example.com, request: "GET /api/v2/homepage/transmission/queue HTTP/2.0", upstream: "fastcgi://unix:/var/run/php/php8.0-fpm.sock:", host: "example.com"

```

**Comment by causefx** [comment]
thank you for this. i will take a look at this soon.

**Comment by causefx** [comment]
fixed in dev - lemme know if it works for you please

**Comment by aniqueta** [comment]
@causefx Solved. Thanks.
