### ISSUE TITLE
Can't set timezone

### ISSUE THREAD

**Issue by escservices** [causefx/Organizr#165]
After updating to version 1.10 under timezone if I change it to NY and save, it defaults back to the first timezone in the list.  Not sure if it actually saves NY as the timezone and the GUI just doesn't change or if its just not saving to the database. Awesome work by the way.

**Comment by causefx** [comment]
hmmmm, crap, Lemme try on mine.

**Comment by 3lysium** [comment]
Can confirm, no timezone setting possible in 1.10, after saving changes and reloading it defaults back.

**Comment by causefx** [comment]
This has been fixed for the next commit which is tomorrow :)

**Comment by AHumanPerson** [comment]
Was also affecting me.
