### ISSUE TITLE
Home Assistant iFrame problem after upgrade - 2021.05.1

### ISSUE THREAD

**Issue by marcutzo84** [causefx/Organizr#1650]
###### Operating System: Ubuntu Server
<hr>

##### Problem Description:
Hi all,

I found issue on iFrame support or similar on Home Assistant after upgrade to 2021.05.1. I see blank page with a top bar, empty as well. If I open in a new page the contents are showed correctly.

Any thoughts on this?

Thanks

**Comment by jasonalsing** [comment]
There is already an issue opened in HA for this:

https://github.com/home-assistant/frontend/issues/9114

**Comment by causefx** [comment]
I believe this was fixed in HA.

**Comment by EricFROL** [comment]
Still without being fixed...

**Comment by HalianElf** [comment]
> Still without being fixed...

You'll need to bring that up with HA or fix whatever config is blocking it then. There's nothing we can do to if the browser is blocking it being iframed.
