### ISSUE TITLE
Changes in the account settings when authentication set to backend/Ldap

### ISSUE THREAD

**Issue by tmkklivecom** [causefx/Organizr#1655]
###### Operating System: Docker
<hr>

##### Problem Description:

Authentication set to Backend/Ldap .
User (hosted on the ldap) is  signed in.
User goes to Account settings
User changes password. Unfortunately this has no effect.
User cannot successfuly sign in with the new password .

The best solution would be the changes in the account settings (name, email, password) change backend records in the proper backend system (in ldap or organizr db).

The quick & dirty solution is making changes impossible  in the account settings when the  user is stored in the ldap . 
<hr>

##### Reproduction Steps:

<hr>

#### Errors on screen?  If so paste here:

```

```

**Comment by tronyx** [comment]
https://github.com/causefx/Organizr/issues/1245
