### ISSUE TITLE
[Feature Request] Add these icons for commonly used applications

### ISSUE THREAD

**Issue by Dazog** [causefx/Organizr#166]
Can you add an icon for Ubiquiti Unfi: https://p6.zdassets.com/hc/settings_assets/77613/200012210/IW7arRmaKMuOvLcUhBTklA-ubnt_logo_u_color_200x200.png

Also an icon for Netdata:

https://raw.githubusercontent.com/Data-Monkey/docker-templates/master/Data-Monkey/img/netdata.jpg

I added them manually for now, but i am sure alot of users will appreciate this.

**Comment by causefx** [comment]
I'll add those to tonights commit.
