### ISSUE TITLE
Potential Security Issue

### ISSUE THREAD

**Issue by JamieSlome** [causefx/Organizr#1660]
Hello @causefx,

A potential vulnerability was disclosed to us by @hakkk3r. I tried looking for an e-mail on your profile, on the repo, and also tried looking for a security policy, but couldn't find one.

If you would like me to share the details with you, I can e-mail it over or share it through some other preferred method for you? Happy to facilitate.

Otherwise, you can visit the advisory page [here](https://huntr.dev/bounties/1-other-causefx/Organizr/). It is private to you and the discloser.

Let me know if you have any questions.

-- Jamie

**Comment by causefx** [comment]
shoot me an email @ causefx at me dot com

**Comment by causefx** [comment]
Issue was regarding Organizr's Google API Keys.
