### ISSUE TITLE
installation issue

### ISSUE THREAD

**Issue by ranjit-git** [causefx/Organizr#1661]
why i receiving this issue everytime try to installl

SETUP
=====
apache2 linux
php 7.4 

![Screenshot from 2021-05-31 10-30-42](https://user-images.githubusercontent.com/25035884/120142156-70e5ea00-c1fb-11eb-8ac8-b5af28001050.png)

When running in docker then getting this error
![Screenshot from 2021-05-31 10-32-25](https://user-images.githubusercontent.com/25035884/120142208-8eb34f00-c1fb-11eb-81e9-53f5732c738a.png)

**Comment by HalianElf** [comment]
That docker log looks normal. For the apache install did you follow the instructions at the link for apache?
