### ISSUE TITLE
Radarr v4 Connection Issues

### ISSUE THREAD

**Issue by titi69lpb** [causefx/Organizr#1663]
###### Operating System: Linux
<hr>

##### Problem Description:

radarr lync with organizr error : 
API Error
https://xxx.xxx.com: Client error: `GET https://xxx.xxx.com/api/rootfolder` resulted in a `404 Not Found` response: { "message": "NotFound" }
<hr>

##### Reproduction Steps:

<hr>

#### Errors on screen?  If so paste here:

```

```

**Comment by tronyx** [comment]
If it's for the Homepage Item, you should be using the local connection information whenever possible. If you don't have the API endpoint exposed via the reverse proxy, it's going to fail.

**Comment by titi69lpb** [comment]
hi, thx for your reply.
i have change nothing. i don't know why it  doesnt work anymore.
port open on my firewall and external acces with traefik is ok. sonnar for exemple with the same config work perfectly

**Comment by titi69lpb** [comment]
I think radarr change the api to this one : https://radarr.video/docs/api/

In radarr update i see "
 4.0.0.5077
—
31 May 2021
Remove Legacy API"

**Comment by tronyx** [comment]
I know you say that you have changed nothing, but that's irrelevant, as you may be using the "wrong" thing to begin with. What is the URL you are using for the Radarr Homepage Item?

**Comment by titi69lpb** [comment]
The url is https://radarr.DOMAIN.tech

**Comment by tronyx** [comment]
Ok, but as I said, all Homepage Items should use the local connection URL if possible. Also, what version of Radarr are you using? Please provide the full version number.

**Comment by titi69lpb** [comment]
Hi, radarr and organizr are not on the same network...
Radarr version : 
4.0.0.5079

**Comment by tronyx** [comment]
@causefx This is the issue with the code logic, maybe, of Radarr v4 being wonky. Looking at the code, it seems it should be okay, but it's obviously not.

**Comment by titi69lpb** [comment]
API Error
https://radarr.XXXXXXX.tech: Client error: `GET https://radarr.XXXXXXX.tech/api/rootfolder` resulted in a `404 Not Found` response: { "message": "NotFound" }

**Comment by causefx** [comment]
i will start looking into this

**Comment by causefx** [comment]
Yea since they removed the legacy api, we can no longer even check the version number.  I will force everything through the new api endpoint now.
