### ISSUE TITLE
SSO failing due to timeout error white getting tokens

### ISSUE THREAD

**Issue by hackmonker** [causefx/Organizr#1665]
###### Operating System: Ubuntu
<hr>

##### Problem Description:
I have sso setup for both tautulli and overseer. They were working fine till the last update. After updating both sso stopped working and logs gave timeout error while getting tokens for both apps.

<hr>

##### Reproduction Steps:
1. Login to organizr using plex auth
2. Open Tautulli tab and it asks for login
3. Open overseer tab and it asks for login

<hr>

#### Errors on screen?  If so paste here:

```
Overseerr Token Function - Error: cURL error 28: Operation timed out after 1001 milliseconds with 0 bytes received [Execution Time: 02.25s | 2258.6ms]

Tautulli Token Function - Error: [http://plexpy:8181]cURL error 28: Operation timed out after 1001 milliseconds with 0 bytes received [Execution Time: 01.14s | 1144.7ms]

```

**Comment by magnocapite** [comment]
I've just noticed the same with my setup. Have had SSO configured for Ombi, Overseer and Tautulli, all 3 are now giving this same timeout error.

**Comment by causefx** [comment]
fixed in dev.  Thank you!
