### ISSUE TITLE
Password lost, cannot recover

### ISSUE THREAD

**Issue by serif** [causefx/Organizr#1668]
###### Operating System: Docker
<hr>

##### Problem Description:
Password lost, cannot recover. ~~I use a password manager, so I don't know how the saved password could have been saved wrong, but that could be user error, idk.~~ edit: it was user error

Plex auth not configured. SMTP not configured.

Followed the steps [here](https://docs.organizr.app/books/troubleshooting/page/forgot-my-organizr-account-password) to reset using Organizr's SMTP server. I got my hash and used it [here](https://api.organizr.app/encrypt.php) with the temp password. Got the message below in each of three attempts. Checked inbox and junk/spam. Nothing received. 

![Screen Shot 2021-06-09 at 8 26 07 PM](https://user-images.githubusercontent.com/62613995/121447870-90e87c80-c964-11eb-881b-c907213cad80.png)

It would be nice if I could nuke only the user info in my `/config`. I'd also like to second the request for a no-password option for installs not exposed to the public.

Organizr is great. Thank you for creating it.

**Comment by serif** [comment]
Checked email again - that reset messages were never received - but that's okay.

Problem solved:

Exported to sql the `tabs` table from my .db file. Nuked my `/config` folder. Restarted the container and entered initial config. Deleted the `tabs` table entries in the new database and imported the sql of my old data.

_(Also: Recreating my account triggered a memory. The lost password was my fault. It wasn't an Organizr glitch.)_

Thanks again for the great app.

**Comment by causefx** [comment]
in the future use this endpoint in that help doc.

http://organizrAddress/api/v2/help/smtp?apikey=12345678901234567890

then use the reset password screen.

**Comment by cornernote** [comment]
Is there any way to do it by changing the password in sqlite?

**Comment by cornernote** [comment]
If trying to send email, in `config.php`:

```
        'disableRecoverPass' => false,
```
