### ISSUE TITLE
Feature: double-click tab icon in menu to reload target/iframe.

### ISSUE THREAD

**Issue by kendokan** [causefx/Organizr#167]
Something like:

    $("li[class^='tab-item']").dblclick(function(){
        var thisidfull = $(this).attr("id");
        var thisid = thisidfull.substr(0, thisidfull.length-1);
        var thisframe = $("#content div[data-content-url^='"+thisid+"']").children('iframe');
        $(thisframe).attr('src', $(thisframe).attr('src'));
    });

**Comment by causefx** [comment]
we can do that.
