### ISSUE TITLE
LDAP Backend will not retrieve user with Proxy Auth (Authelia)

### ISSUE THREAD

**Issue by DevEkode** [causefx/Organizr#1670]
###### Web browser : Firefox 89.0
<hr>

##### Problem Description:

Organizr refused to log on new users who pass by Authelia.

My setup is :
1. Traefik 2.2.1 as my reverse proxy and middleware manager.
2. Authelia for my SSO provider.
3. Organizr using Backend Only with my AD and Proxy Auth configured.

API Connection with Active Directory works and Organizr seems to retrieve Remote-User header from Authelia.
<hr>

##### Reproduction Steps:

1. Create new account into Active Directory (wait 5min for Authelia to register it)
2. Go to Organizr url (ex : organizr.mydomain.com)
3. Authelia screen appear, enter username & password.
4. Gets redirected to Organizr login page.
5. Login failed, errors listed in next section.

I found out that, manually login into Organizr (with the new user) finally loads AD information into Organizr (is this the intended workflow ?)
<hr>

#### Errors on screen?  If so paste here:

On the web page :
![image](https://user-images.githubusercontent.com/12038808/121941032-1302e780-cd4f-11eb-8ae1-8cd7d091f771.png)

In browser console :
```
Organizr Function: API Connection Failed (oAuthLoginNeededCheck)
Organizr Function: Password was set but empty (oAuthLoginNeededCheck)
```

Hope you can help me, 
Have a nice day !

**Comment by causefx** [comment]
OOF.  This is a doozy.  As for the user not being in the DB, that is normal, it doesnt get created until they first login.  Still, it shouldn't effect the login at all.  I haven't used Authelia, does it just sent the username over in a header?

**Comment by DevEkode** [comment]
Yeah, Authelia uses `Remote-User` (and others) header to send over the username to the webserver :
![image](https://user-images.githubusercontent.com/12038808/122106819-ac4b0000-ce1a-11eb-8d70-79968b70dee9.png)

I didn't think that the first login was intended, but it makes sense. So that's explain my issue.

Another thing, could the "disconnect" on organizr trigger the Authelia logout script as well ?
Because if I :
1. Log into organizr through Authelia with `user1`.
2. Logout with authelia (because using Organizr disconnect feature automatically logs me back on -> SSO)
3. Log into organizr through Authelia with `user2`.
4. And Organizr show up with `user1` still authenticated.

I can make another issue thread if you want !

**Comment by causefx** [comment]
This was fixed in dev yesterday :)

**Comment by causefx** [comment]
Is there an api endpoint for Authelia logout?

**Comment by DevEkode** [comment]
Nice job !
Yup, you can use the following api `GET` endpoint : `https://authelia.example.com/logout`.
And add the `rd` parameter to redirect the user after logout : `?rd=https://home.example.com`

**Comment by causefx** [comment]
That will work if the user uses Organizr to logout... but i do see the issue if they use Authelia to logout.  As they still still be logged into Organizr.  Does Authelia have webhooks?

**Comment by DevEkode** [comment]
I don't think so...
One thing I could do is to create a custom HTML5 page to redirect them to the logout page (instead of using the organizr one)

**Comment by causefx** [comment]
No need...

Just Goto settings > Customize > Custom Javascript

```
function logout(){
	message('',' Goodbye!',activeInfo.settings.notifications.position,'#FFF','success','10000');
	organizrAPI2('GET','api/v2/logout').success(function(data) {
		try {
			var html = data.response;
		}catch(e) {
			organizrCatchError(e,data);
		}
		local('set','message','Goodbye|Logout Successful|success');
		history.replaceState(null, null, ' ');
		window.location.replace("https://authelia.example.com/logout?rd=https://home.example.com");

	}).fail(function(xhr) {
		OrganizrApiError(xhr, 'Logout Failed');
	});
}
```

That will override Organizr's logout function
