### ISSUE TITLE
Can't set correct tab type after re-adding the homepage

### ISSUE THREAD

**Issue by Terror-Gene** [causefx/Organizr#1671]
###### Operating System: UnRAID
<hr>

##### Problem Description:
After re-adding the homepage `api/v2/page/homepage` the tab type can not be changed from `iframe` causing the homepage to be broken.

I had to search & find [this page](https://docs.organizr.app/books/setup-features/page/tabs) to re-add the homepage & following those instructions in that order did not work.

Ideally re-adding the homepage should be a simple click operation.
Or it should not be able to be deleted.

<hr>

##### Reproduction Steps:
Delete the homepage, try to re-add it & try to change the tab type.

<hr>

##### Workaround:
Add & save a new tab with any other URL, change the tab type to `Organizr` , then change the URL to `api/v2/page/homepage`.

**Comment by causefx** [comment]
What you need to do is make a new tab and name it something random.  Then add some random string for the tab url, then save it.  Now change that tab to type => Organizr on the tab list page.  Now you can edit the url to `api/v2/page/homepage`

I will look into fixing this.

**Comment by causefx** [comment]
fixed in dev
