### ISSUE TITLE
Update Overseerr Logo

### ISSUE THREAD

**Issue by camkidd** [causefx/Organizr#1678]
Overseerr have updated their [logo/icon](https://github.com/sct/overseerr/tree/develop/public). 
Now that they are in beta I'd say the recent icon change won't be changing again anytime soon so would be good to see it updated as below. 

![overseer-512x512](https://user-images.githubusercontent.com/1066576/125193232-b41d8900-e28e-11eb-801b-3b643f672536.png)

PS. Thanks for all the work you put into such a great project. 🍺

**Comment by causefx** [comment]
doing this now. thank you.
