### ISSUE TITLE
Homepage

### ISSUE THREAD

**Issue by andyrav** [causefx/Organizr#168]
Hi trying to test out the new homepage.php but getting a page of errors:

Warning: simplexml_load_file(): I/O warning : failed to load external entity "home.xxxxxx.info:32400/library/recentlyAdded?X-Plex-Token=xxxxxxxxxxxxxxxxxxxxxx" in /var/www/html/Dashboard/functions.php on line 146

Warning: Invalid argument supplied for foreach() in /var/www/html/Dashboard/functions.php on line 152

all green when loadup check.php
simplexml is loaded and ready to rock-n-roll! Good 2 Go!
any ideas?

**Comment by causefx** [comment]
Include http:// or https:// sorry. I will fix.

**Comment by andyrav** [comment]
yes that fixed it. many thanks
