### ISSUE TITLE
Unable to change settings

### ISSUE THREAD

**Issue by DRXAquosus** [causefx/Organizr#1684]
###### Operating System: Windows 2019
<hr>

##### Problem Description:
Whenever I try to change a setting I get an error.
For example if toggle the 'Active' switch for the Homepage tab I get "Tab Enable Error error"
A similar error happens for every setting.

<hr>

##### Reproduction Steps:

<hr>

#### Errors on screen?  If so paste here:

```
[https://nexus.mckeenet.us/tabenableerror.png](url)
```

**Comment by causefx** [comment]
anything in webserver logs?

**Comment by DRXAquosus** [comment]
Nothing that I can see, in order to narrow it down I opened it on the server's browser via localhost.
The error changed to "Tab Enable Error Method Not Allowed"

**Comment by causefx** [comment]
that makes sense. You need to allow PUT on your webserver.

**Comment by causefx** [comment]
take a look at #1542 and allow PUT PATCH and DELETE

**Comment by DRXAquosus** [comment]
That makes sense, now that you say that and I look at the logs closer every log line that starts with PUT ends with 405.

Example:
2021-07-20 01:24:01 ::1 PUT /api/v2/tabs/2 - 8090 - ::1 Mozilla/5.0+(Windows+NT+10.0;+Win64;+x64;+rv:65.0)+Gecko/20100101+Firefox/65.0+IceDragon/65.0.2 http://localhost:8090/ 405 0 1 1

Sorry, I'm new to webservers and didn't realize I was looking at the error the whole time. :)

Thanks for the link, I'll dive into that and will update with the results.

**Comment by DRXAquosus** [comment]
Checked both the main web server and my reverse proxy, neither have WebDAV Publishing.

https://nexus.mckeenet.us/webdav.PNG

I'll try other things in that stack exchange post

**Comment by causefx** [comment]
maybe trying installing it? i don't have much experience with IIS

**Comment by mesheree** [comment]
I was getting this same thing using IIS and didn't have its 'WebDAV Publishing' sub-feature enabled.  I had to look up how to "allow PUT PATCH and DELETE" because I'm not super-familiar with any web servers or PHP, but enabling them in IIS is apparently done in the **handlers** section of the **C:\Windows\System32\inetsrv\config\applicationHost.config** file, and I'm not getting that error any more.

**Comment by DRXAquosus** [comment]
@mesheree 
Thanks that did the trick, a couple of things to note

The part to look for in the applicationHost.config file is where ever it says path="<whatever verbs>", replace that with path="*"

The other place to check is in the web.config file for the site itself (located in the root directory of the site).
Do the same thing to every verb= tag in here as well.

Also WebDAV had to be uninstalled.

Thank you again @mesheree and @causefx for your assistance!

**Comment by causefx** [comment]
glad you got it sorted
