### ISSUE TITLE
Sonarr v3 calendar not showing items on home page

### ISSUE THREAD

**Issue by goku-son** [causefx/Organizr#1685]
###### Operating System: Windows/MacOS/Ubuntu
Docker latest

####Problem Description:
Sonarr v3 does not load calendar on home page.  Others like lidarr and radarr load no problem. There are not errors in the logs.  I have tried reloading the page and enabling/disabling the Sonarr home item.  Test connection works. 

##### Reproduction Steps:
Set up Sonarr home item
View empty calendar in home page
Confirm calendar not empty in Sonarr itself 

<hr>

#### Errors on screen?  If so paste here:
```

```
No errors in logs, so unsure what to look at for clues.

**Comment by angrycuban13** [comment]
Look at the console tab when you press F12 and you're on the homepage. The errors might be there

**Comment by causefx** [comment]
can you paste the output of:
yourOrganizr/api/v2/homepage/sonarr/calendar

**Comment by goku-son** [comment]
> yourOrganizr/api/v2/homepage/sonarr/calendar

Here is what I get back:

```
{
    "response": {
        "result": "success",
        "message": null,
        "data": null
    }

```
When I change the above to use radarr I can see results come back. If I look at the Sonarr calendar itself I also see items.  

Sonarr version is 3.0.6.1265.

**Comment by almontef** [comment]
Even though the test connection worked, I noticed that my API key was entered twice. Fixed that and now the calendar loads Sonarr items! No big deal, but I noticed the connection tab on Sonarr is different than on Radarr. For Sonarr, you have to input the items and then select them to be added into the field, while on Radarr you can directly add them to the field. Perhaps Sonarr tab should work like the Radarr tab.

**Comment by almontef** [comment]
This issue can be closed and takes for all your help.
