### ISSUE TITLE
SSO for Tautilli not working keeps redirecting back to login screen

### ISSUE THREAD

**Issue by almontef** [causefx/Organizr#1687]
###### Operating System: Windows/
<hr>

##### Problem Description:
I have SSO working fine with Ombi and Plex using Plex oAuth. However, Tautulli does not work. When I try and sign in, I get prompted for user/pw combo and even if I put that in, it redirects me back to the prompt. This is setup according to the Organizr SSO documentation. The home page stats for Tautulli show up just fine, just unable to log in. 

Organizr is on a different IP than Plex, Ombi, and Tautilli. However the issue is only with Tautilli. I have local DNS setup, so I don't think that is the issue. I have also tried using IP address instead of FQDN, but the issue remains.

<hr>

##### Reproduction Steps:
Set up SSO for Tautulli according to the documentation and then attempt to access it's tab. 

<hr>

#### Errors on screen?  If so paste here:

I see no errors in the organizr logs. In the Firefox deveoper's console, I see the following errors:
```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://127.0.0.1:32400/media/providers?X-Plex-Product=Plex%20Web&X-Plex-Version=4.59.2&X-Plex-Client-Identifier=ky15sabvq88x5w315wip4ohp&X-Plex-Platform=Firefox&X-Plex-Platform-Version=90.0&X-Plex-Sync-Version=2&X-Plex-Features=external-media%2Cindirect-media&X-Plex-Model=bundled&X-Plex-Device=Windows&X-Plex-Device-Name=Firefox&X-Plex-Device-Screen-Resolution=1860x887%2C1920x1080&X-Plex-Language=en. (Reason: CORS request did not succeed).
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://127.0.0.1:32400/?X-Plex-Product=Plex%20Web&X-Plex-Version=4.59.2&X-Plex-Client-Identifier=ky15sabvq88x5w315wip4ohp&X-Plex-Platform=Firefox&X-Plex-Platform-Version=90.0&X-Plex-Sync-Version=2&X-Plex-Features=external-media%2Cindirect-media&X-Plex-Model=bundled&X-Plex-Device=Windows&X-Plex-Device-Name=Firefox&X-Plex-Device-Screen-Resolution=1860x887%2C1920x1080&X-Plex-Language=en. (Reason: CORS request did not succeed).
```
Debug command shows that the cookie is false:
```
enabled: true
cookie: false
url: http://tautulli.home:8181/
```

**Comment by HalianElf** [comment]
Sounds more like a [SameSite](https://docs.organizr.app/books/troubleshooting/page/redirect-looping---samesite-errors) issue. You need to have your local DNS be a something.domain.tld and not just something.tld to follow SameSite rules

**Comment by almontef** [comment]
So if I understand correctly, my domain record for tautulli is tautulli.home. Are you saying that I need to change that to something like tautulli.home.com?

**Comment by HalianElf** [comment]
Yes and then use something with `home.com` for Organizr as well. Otherwise Tautulli will block the browser from being able to read the cookie while it's in the iframe

**Comment by almontef** [comment]
That worked! Thanks so much!
