### ISSUE TITLE
"You have been blacklisted from this site"  on local host

### ISSUE THREAD

**Issue by DrRickDaglessMD** [causefx/Organizr#1688]
###### Operating System: Windows
<hr>

##### Problem Description:
When accesing Organizr on local host, getting a message to say I have been blacklisted, other IPs on same subnet have no issue, have checked settings and no IPs listed as blacklisted
<hr>

##### Reproduction Steps:
Happens every time when trying to access site

<hr>

#### Errors on screen?  If so paste here:
"You have been blacklisted from this site"
```

```

**Comment by causefx** [comment]
I will install on my windows machine this coming Monday.

**Comment by causefx** [comment]
So I went ahead and installed this on my local windows machine.  

I accessed it via:

`http://localhost/` and `http://10.0.0.20/` and both loaded fine...
![image](https://user-images.githubusercontent.com/16184466/127928441-42528253-5bcb-478a-87df-53d7091dc9ef.png)

I too have nothing in the blacklisted portion.

**Comment by DrRickDaglessMD** [comment]
Ok, I just tested via localhost and that works, using the local IP I still get the blacklisted error message though... very strange.  Any ideas on what could cause that?

**Comment by causefx** [comment]
Whoa that makes no sense.  Are you on master or dev branch?  I can make some quick changes to dev to output some info - if you have some time to test.

**Comment by DrRickDaglessMD** [comment]
Set as dev,  2.1.426 if that matches?

Interestingly in the NGINX logs I see the access via localhost coming in as 127.0.0.1 and the fails coming from the IP.  Last succes via the IP I see is on June 29th but not exactly sure when this started.  Happy to do a test, just let me know what you need

**Comment by causefx** [comment]
That was what I was going to test.  what is the scheme of the failing ip?

**Comment by DrRickDaglessMD** [comment]
192.168.0.x

**Comment by DrRickDaglessMD** [comment]
If I blacklist 127.0.0.1 I then get same error via localhost as well, I tried adding and removing blacklist on the local IP but still the same

**Comment by causefx** [comment]
under /api/config.php 

```
'blacklisted' => '',
```

is it like this?

**Comment by DrRickDaglessMD** [comment]
'blacklisted' => '',

Thats in /api/config/config.php

**Comment by causefx** [comment]
I wonder if you have some type of cache or something...  The blacklist should never even execute...

```
	public function checkIfUserIsBlacklisted()
	{
		if ($this->hasDB()) {
			$currentIP = $this->userIP();
			if ($this->config['blacklisted'] !== '') {
				if (in_array($currentIP, $this->arrayIP($this->config['blacklisted']))) {
					$this->debug('User was sent to blackhole');
					die($this->config['blacklistedMessage']);
				}
			}
		}
	}
```
First part checks if DB is setup 
then checks if blacklisted value is not empty or blank 
then checks if current IP is in blacklisted list...

**Comment by DrRickDaglessMD** [comment]
Happy to give it a go, did try clearing cache and haven't ever made changes to blacklist.  Where shall I add this code to run?   Any adjustments needed?

Or is this just the function as it should work?

**Comment by causefx** [comment]
pull latest dev branch from settings page

**Comment by causefx** [comment]
once it updates, you should try and access organizr from blocked IP.... then from good IP check organizr logs:

![image](https://user-images.githubusercontent.com/16184466/127938212-74107d26-b13a-463c-ab35-11bcc52b2090.png)

**Comment by DrRickDaglessMD** [comment]
It now works!  I guess that tell us nothing about why it didn't originally though...

**Comment by causefx** [comment]
Yeah - I can't think of any reason at all as all we did was add a debug message and the core was unchanged.  

Computers........ eh...

**Comment by DrRickDaglessMD** [comment]
Bizarre... Thanks for the help anyway, ghost in the machine somewhere I guess

**Comment by causefx** [comment]
haha yeah i hear that!  No worries.
