### ISSUE TITLE
Ios mobile (14.7.1) won’t scroll on splash screen

### ISSUE THREAD

**Issue by ThrawnJL** [causefx/Organizr#1692]
###### Synology Dsm7 (Docker)
<hr>

##### Problem Description:

After logging into organizr on iphone and being shown the splash screen I cannot scroll on on the phone. The close splash button works and it allow me to get into the non splash version where scroll DOES work

<hr>

##### Reproduction Steps:

Make a splash screen with enough buttons to more then fill up the screen and then try scrolling to additional buttons

<hr>

#### Errors on screen?  If so paste here:

```
None
```

**Comment by Budlyte** [comment]
It isn't just iphone, android too. Looks like it's mobile view.  Did this happen after the fix for the Splash screen closing when hitting a button?

**Comment by causefx** [comment]
fixed in master now
