### ISSUE TITLE
[Request] See dashboard as a certain type of user

### ISSUE THREAD

**Issue by NicolasFerec** [causefx/Organizr#1698]
Hello,

Just thought it could be very cool to be able to see what the dashboard looks like as a certain type of user.
For those who use local user base they can just create one with a certain group and connect with it. But for some of us who use backend only (Plex in my case) it could be nice to see what the dashboard looks like for a non admin user.

Hope this feature is easy to implement. 
Thanks for your hard work, wishing you the best.

**Comment by causefx** [comment]
it would be easy enough for me to do a mock-up style outlining which items will be loaded for a certain group with no real data.  I'll look into showing actual data.

**Comment by causefx** [comment]
also, please open up this as a feature request @ vote.organizr.app
