### ISSUE TITLE
Not need load GA script when not set gaTrackingID value

### ISSUE THREAD

**Issue by EINDEX** [causefx/Organizr#1699]
###### Operating System: Offical Docker
<hr>

##### Problem Description:

Not no need to load the GA(Google Analytics) scripts, when I did not want to use it.
This script. https://apis.google.com/js/client.js?onload=googleApiClientReady
Could we enable this when the gaTrackingID configuration has value?
<hr>

##### Reproduction Steps:

<hr>

#### Errors on screen?  If so paste here:

```

```

**Comment by causefx** [comment]
good catch, I completely forgot about that script.  I will make the change.

**Comment by causefx** [comment]
fixed in dev, master push tomorrow
