### ISSUE TITLE
homepage - plex images not displayed

### ISSUE THREAD

**Issue by JigSawFr** [causefx/Organizr#170]
Hello, 
Tahnsk for this home page feature,
it's working as expected but not for images of Plex
I can see slideshow with resumes, but with broken images,
My flex media serveur is under a reverse proxy:
ex: https://plex.my-domain.fr

So homepage config to get it works is:
- Plex URL: https://plex.my-domain.fr
- Plex Port: **blank - no port**
- Plex Token: _Plex generated token_

Do you have an idea to solve this issue ?
Thanks

**Comment by AHumanPerson** [comment]
It's still in beta and being developed. Only current integration is plex so I recommend just setting plex as default for now.

**Comment by causefx** [comment]
that's odd that it pulls info but not images.  I will look into it.  Will you be able to get on gitter?

**Comment by escservices** [comment]
Yeah same issue here but mine is not under a reverse proxy just port forwarded and dynamic dns.  Info is there but no pictures.  The sonarr calendar is awesome, wanted something like that for awhile.  My php is a little rusty but I think I found the problem or at least may be somewhere you can start looking.  The issue is in image.php
 `$image_src = $plexAddress . '/photo/:/transcode?height='.$image_height.'&width='.$image_width.'&upscale=1&url=' . $image_url . '&X-Plex-Token=' . PLEXTOKEN;`   Line 29    I think the issue is with trying to use the plex photo transcoding function, I was able to get the images working and back up by changing that entire line to `$image_src =  $image_url . '?X-Plex-Token=' . PLEXTOKEN;` I replaced the `&X-Plex-Token` with `?X-Plex-Token` Wish I had the time to do more, hope this helps.

**Comment by causefx** [comment]
@escservices what url and port did you use?

**Comment by escservices** [comment]
Port is 32400 standard Plex port and the URL is my own domain that is linked to my IP which is theescservice.ddns.net

**Comment by causefx** [comment]
Is Plex on the same box as the webserver? Or same network?

**Comment by escservices** [comment]
Plex is on my home network, organizr runs on a host  out side the network like GoDaddy.

**Comment by escservices** [comment]
Pictures worked with the last version but not the current one until I made those code changes.

**Comment by escservices** [comment]
It works if i replace the vars with the correct data an replace the links with localhost and run it on my Plex server it works.  $plexAddress . '/photo/:/transcode?height='.$image_height.'&width='.$image_width.'&upscale=1&url=' . $image_url . '&X-Plex-Token=' . PLEXTOKEN;

**Comment by causefx** [comment]
let me think about this.

**Comment by causefx** [comment]
weird, that it would work before and not now.  All i did was include the transcode function

**Comment by causefx** [comment]
leave port blank, and in url:

try: https://theescservice.ddns.net:32400

then 

try: http://theescservice.ddns.net:32400

if neither work try this too:
https://theescservice.ddns.net:32400/photo/:/transcode?height=150&width=150&upcale=1&url=GETMETADATAFROMHOMEPAGE&X-Plex-Token=

metadata will look like this:
/library/metadata/630581/thumb/1490212645

**Comment by escservices** [comment]
Just to explain what I said in my last comment was that the link below doesn't work it gives a not found 404 error, but if I replace my domains with localhost and go-to it on chrome on the server that has Plex on it it works fine.  I even tried my other domains that forward Plex.theescservice.com.  I just saw what you your last comment I'll try it. 


http://theescservice.ddns.net:32400/photo/:/transcode?url=http://theescservice.ddns.net:32400/library/metadata/278944/thumb/1489620228%20&X-Plex-Token=iiiiiiiiiiiiiiiii&height=150&width=100&upscale=1

**Comment by causefx** [comment]
I just tried using a ddns for me....

http://causefx.chickenkiller.com:32401/photo/:/transcode?height=150&width=150&upcale=1&url=/library/metadata/630581/thumb/1490212645&X-Plex-Token=gfhgfhgfhgfhgfh

it loaded an image.  So i tried in Org and you're right nada, I will work on this tonight.

**Comment by escservices** [comment]
I'll do some research and see if I can find anything, I'll let you know if I find anything else useful.

**Comment by causefx** [comment]
fixed it.  I'll try and do the commit today.

**Comment by escservices** [comment]
Awesome, that was fast.
