### ISSUE TITLE
Proposal: generic SSO for basic auth apps

### ISSUE THREAD

**Issue by Yann-J** [causefx/Organizr#1704]
I _think_ there might be a way to implement a generic SSO solution for applications that support basic auth.

What I have in mind is:

* We specify in the settings the internal link to a login endpoint supporting basic auth, as well as some hardcoded credentials (maybe a different set for each Organizr user group)
* At Organizr login time (or whenever the SSO agents kick in) organizer places these login calls on behalf of the user, and then forwards any Set-Cookie header (maybe even modifying them to loosen the SameSite policy) down to the user on some future response, so that it gets stored in the user's cookies.
* As long as the application is served under the same domain, these application cookies should then work...

I have a few apps in mind that I think should work with that model: pyload, portainer.

I don't know how that would fit with the current SSO logic...

**Comment by causefx** [comment]
this is exactly how the sso logic works now minus adding the url in the tab settings.  that is a good idea tho.   Can you open this as a feature request here https://vote.organizr.app
