### ISSUE TITLE
iframe CSP issue w/ qbittorrent

### ISSUE THREAD

**Issue by mrkoven** [causefx/Organizr#1708]
###### Operating System: Windows/MacOS/Ubuntu
<hr>

##### Problem Description:
Using Nginx Proxy Manager/Cloudflare DNS.

Browser console shows error below for Qbittorrent:
Refused to frame 'https://qbittorrent.mydomainname.com/' because an ancestor violates the following Content Security Policy directive: "frame-ancestors 'self'"

organizr.mydomain.com 

qbit.mydomain.com - won't load in iframe, loads fine in new window/ctrl+click. Clickjack and CSRF both unchecked in Qbittorrent WebUI setting.

radarr.mydomain.com - works fine in iframe, along w/ other apps in *.mydomain.com

Not sure why there's a frame-ancestors self CSP issue when it is on same domain. Any idea?

<hr>

##### Reproduction Steps:

<hr>

#### Errors on screen?  If so paste here:

```

```

**Comment by causefx** [comment]
I think this is more of an issue between Qbit and NPM
