### ISSUE TITLE
[Request] Separate settings to each user tab

### ISSUE THREAD

**Issue by xavier84** [causefx/Organizr#171]
Hi!

Is it possible to add settings to modify the tab for each user? 

Admin can adjust the option separatly and not for all.

Thank's in advance ;)

**Comment by causefx** [comment]
can you clarify?

**Comment by xavier84** [comment]
I would like to be able to assign by user some tabs and not others

**Comment by BaneOfSerenity** [comment]
Being able to assign users to groups and assign the groups to tabs would be nice.

**Comment by causefx** [comment]
This is on the roadmap for the next main version out next year maybe.

**Comment by chasgames** [comment]
Good idea! Was also after something similar
