### ISSUE TITLE
Minimal Login Page has changed layout

### ISSUE THREAD

**Issue by tedtramonte** [causefx/Organizr#1715]
###### Operating System: Docker on CentOS 7
<hr>

##### Problem Description:
Did the Minimal Login Screen layout change? A while back, I set my log in screen up such that the page was just the login box with the logo above it, all centered vertically and horizontally, no background image. Here is an old screenshot I managed to dig up:
![expected](https://user-images.githubusercontent.com/16464115/134813356-7cb1ee94-14bb-43d4-ab8f-751658e473a5.png)

Recently I noticed it had switched back to having the login box on the right side, no logo anywhere, and the default stock photo laptop background:
![actual](https://user-images.githubusercontent.com/16464115/134813414-a47e7b13-a5c7-454f-8d55-637cf1764cfa.jpg)

I haven't edited any aesthetic settings since that expected screenshot. The only management has been upgrading docker containers, and in organizr's case, restarting the container to upgrade the application.

My Login Page settings point to my logo, select "Use Logo instead of Title on Login Page", provide no wallpaper, and select "Minimal Login Screen" (which is what I believe got my desired layout). My Theme is Organizr - Dark, and I'm using no Custom CSS, Theme CSS, Custom JS, or Theme JS.

Any insights?

**Comment by tronyx** [comment]
This is the CSS that I am using for it and it still works just fine for me:

```
/* loginpage sidemenu */ 
@media (max-width: 480px) {
    .login-register > .login-box > .white-box {
     margin-top: auto !important;
     width: 100% !important;
	-webkit-box-shadow: 0 0 10px rgba(0, 0, 0, 0) !important; 
    box-shadow: 0 0 10px rgba(0, 0, 0, 0) !important;   
   }
   }
   
/* logo */ 
	.white-box .visible-xs {
		display: block!important;
	}
	.loginLogo {
    border: 0;
    margin-top: -60%;
    transform: translateY(-10%);
    max-width: 350px;
    max-height: 225px;
    width: auto;
	}
	@media (max-width: 480px) {
		.loginLogo {
		margin-top: -10% !important;  
		}
	}	
	.blockUI {
		opacity: 1 !important;
		background-color: transparent !important;
	}
	.blockMsg {
		background: rgba(0, 0, 0, 0.9) !important;
		border: none !important;
	}
	
    .login-register > .login-box > .white-box {
    background: transparent !important;
	-webkit-box-shadow: 0 0 10px rgba(0, 0, 0, 0.6);
    box-shadow: 0 0 10px rgba(0, 0, 0, 0.6);
    }
   
    .login-register {
        background: #1f1f1f !important;
        height: 100%;
        position: fixed;
    }

	.slideInRight {
		-webkit-animation-name: none;
		animation-name: none;
	}

	.login-register  .login-box  .white-box  .bg-org {
		background-color: transparent !important;
    }
    
	/*2FA login button*/
	.panel-wrapper .panel-body > .btn-warning, .btn-warning.disabled {
        background: hsla(0, 0%, 0%, 0.25) !important;
        border: 1px solid #ffc36d00 !important;
        }
        
        /*2FA animation header*/
        .panel-warning .panel-heading, .panel-yellow .panel-heading {
        color: #fff;
        border-radius: 3px;
        background-color: rgba(0, 0, 0, 0.3);
        border-color: #00000000;
        }
        
        /*oAuth Successful*/
        .panel-green .panel-heading, .panel-success .panel-heading {
        color: #53e69d;
        text-align: center;
        text-transform: uppercase;
        border-radius: 3px;
        background-color: transparent;
        border-color: transparent;
        }
        
	/*Login sidebar*//*Login sidebar*//*Login sidebar*/
	.login-box.login-sidebar,
	#login-panels .panel-body,
	#login-panels .panel {
		background: transparent !important;
	}

	/*Center login Box*/
	.login-sidebar {
		position: relative;
		right: initial;
	}

	#lockScreen .white-box {
		width: 400px;
		height: 345px;
	}
	.login-sidebar .white-box {
		width: 100%;
		position: absolute;
		top: 50%;
		transform: translateY(-50%);
	}
```

**Comment by HalianElf** [comment]
Your first screenshot looks like you were using @GilbN's [Dark theme](https://github.com/GilbN/theme.park/) which has the CSS that @tronyx posted included. The base Organizr Dark never looked like that and you'll need to add it yourself.

**Comment by tedtramonte** [comment]
> 
> 
> Your first screenshot looks like you were using @GilbN's [Dark theme](https://github.com/GilbN/theme.park/) which has the CSS that @tronyx posted included. The base Organizr Dark never looked like that and you'll need to add it yourself.

I think that's possible, but reinstalling that theme and activating it has all kinds of messed up colors such that the text is unreadable. After clearing my cookies and cache, the text looks fine. The wallpaper is still there, but I can replace it with # I guess.

So did something in Organizr change and cause the theme to reset without me noticing? Same with the wallpaper setting.

**Comment by HalianElf** [comment]
Yea, GilbN did change it to make it so you can set your own wallpaper. I believe this is the custom css you want if you want it back (grabbed it from the customization-theming channel in discord)
```css
.login-register {
    background: url(plugins/images/userTabs/image.png) center center/cover no-repeat !important;
}
```
