### ISSUE TITLE
Monkey Head

### ISSUE THREAD

**Issue by koolershaker** [causefx/Organizr#1716]
###### Operating System: Docker Container on Arch Install
<hr>

##### Problem Description:
when you move the mouse pointer in the lower right corner a monkey head pops up with rolling eyes and sticks out his tongue at you.
Yeah i know sounds stupid but that's whats happening.
Anyway is there a way to turn this off?
<hr>

##### Reproduction Steps:
Move Mouse in Low-right Corner Monkey Head pops up

        <div class="org-rox">
            <div class="hair"></div>
            <div class="head">
                <div class="ear left"></div>
                <div class="ear right"></div>
                <div class="face">
                    <div class="eye left"></div>
                    <div class="eye right"></div>
                    <div class="nose"></div>
                    <div class="mouth"></div>
                </div>
            </div>
        </div>
    

<hr>

#### Errors on screen?  If so paste here:

```

```

**Comment by tronyx** [comment]
It's an Easter Egg. Do you just not like fun?

**Comment by koolershaker** [comment]
No, the problem is it*s a hot corner on my desktop to get an overview and i use both this function and organizr a lot... 
it gent's kind of annoying after some time.
And the head stays kinda in cache and pops up in the overview etc (wayland on arch)

**Comment by HalianElf** [comment]
Throw this in custom css until a toggle is added
 ```css
.org-rox-trigger {
    display: none;
}
```

**Comment by koolershaker** [comment]
> Throw this in custom css until a toggle is added
> 
> ```css
> .org-rox-trigger {
>    display: none;
> }
> ```

Thank you, that's a good solution.

**Comment by causefx** [comment]
Toggle coming today.

**Comment by flammable** [comment]
I triggered this by accident just now, and had no idea what was happening. I thought my stuff might have been compromised. Thanks for creating this GitHub issue, and thanks for the toggle to turn it off!
