### ISSUE TITLE
Tautulli Homepage Item Failing

### ISSUE THREAD

**Issue by tucker19** [causefx/Organizr#1724]
###### Operating System: Ubuntu
<hr>

##### Problem Description:
I am trying to setup Tautulli and when I go into `Connection` the URL box will not let me type anything.

<hr>

##### Reproduction Steps:
Try and add Tautulli to homepage and add connections

<hr>

**Comment by tronyx** [comment]
No one else has reported such an issue. Have you tried multiple web browsers?

**Comment by causefx** [comment]
i just fixed a clearing bug that might maybe help with whatever problem you are having.  the fix was pushed to dev branch.

**Comment by tronyx** [comment]
Any update here @tucker19?

**Comment by tucker19** [comment]
Have not had a chance to check out the dev branch

**Comment by tucker19** [comment]
Looks to be working now
