### ISSUE TITLE
iCal Failure with 2+ iCal Links

### ISSUE THREAD

**Issue by tucker19** [causefx/Organizr#1725]
###### Operating System: Ubuntu
<hr>

##### Problem Description:
Trying to add multiple iCal to the calendar but seems as only the first one is working. Currently have 2 in the Urls fields and only first one is showing in calendar.

<hr>

##### Reproduction Steps:
Try and add a second iCal link to iCal Homepage feature

<hr>

**Comment by causefx** [comment]
I cannot duplicate this.

**Comment by tucker19** [comment]
I asked about this in the discord and at least 1 other person confirmed this. I don't know if it matters but both are Google Calendar Private links.

**Comment by causefx** [comment]
you are correct about @HalianElf saying that but she checked again today and she said it worked fine. can you provide me the ical link to test?

**Comment by tucker19** [comment]
Both my calendars are private but I am actually seeing both now. The only issue is the second one is showing events from 2013 instead of 2021. Could I get your email and I'll send the links that way, then I am not posting private things in a public place.

**Comment by causefx** [comment]
causefx at me dot com

**Comment by tucker19** [comment]
> 
> 
> causefx at me dot com

Just sent email. Thank you for the help
