### ISSUE TITLE
[Suggestion] Sickrage Support

### ISSUE THREAD

**Issue by JigSawFr** [causefx/Organizr#173]
It's fine that Organizr support Sonarr,
But the only thing that prevent me to use Sonarr,
Is this great app can't auto download from torrents trackers (usenet only for auto-dl)
So, i'm blocked on sickrage, damn.
Do you have plans to support sick rage too as you done with Sonarr ?
Thanks you

**Comment by causefx** [comment]
Does sick rage have an API where I can pull past and upcoming shows?

**Comment by elRadix** [comment]
Yes sickrage has api support 

check this, al lot more modules available on  
https://github.com/Hellowlol/HTPC-Manager

**Comment by JigSawFr** [comment]
if you need a php wrapper for sickrage API or some examples, you can take a look at https://github.com/Kryptonit3/SickRage

**Comment by StevenChorkley** [comment]
btw @JigSawFr that's why [Jackett](https://github.com/Jackett/Jackett) exists. Works like a charm with Sonarr.

**Comment by JigSawFr** [comment]
@StevenChorkley i know i'm a member of Jackett lol but Sonarr is unable to handle automatic searching on trackers (with Jackett or not, it's the same) (only in usenet), it's intended by Sonarr devs to not surcharge trackers of requests, as they said in many issues and docs on their GitHub repository. But yes of course, you can trigger a manual search or automatic search (manually triggered) on Sonarr GUI, but you have not any tasks scheduled to perform automatic search on trackers.
