### ISSUE TITLE
takes 7+ minutes to start up each time with high CPU load? (Docker)

### ISSUE THREAD

**Issue by wivaku** [causefx/Organizr#1736]
###### Operating System: Docker Desktop 4.1.1 (MacOS Big Sur 11.6)
<hr>

##### Problem Description:
**startup takes 7+ minutes and high CPU load**

Using Organizr in Docker environment (organizr/organizr, master branch) on MacOS (Docker Desktop 4.1.0).

When doing a `docker-compose up` or `docker-compose start` it takes 7+ minutes to start up, and this always includes an "updating" activity, even when I do two `up`/`start`s in a row.

These steps take a long time (example of test with `docker-compose up`):
- organizr  | [cont-init.d] 20-config: executing... → **0:42 min**
- organizr  | [cont-init.d] 30-setup: executing... → **2:49 min**
- organizr  | |  Updating Organizr  | → **2:18 min**
- organizr  | Already up to date. → **1:40 min**

CPU load is pretty much at 100% during all this time.

<hr>

##### Reproduction Steps:
docker-compose:

```
  organizr:
    container_name: organizr
    restart: unless-stopped
    image: organizr/organizr
    volumes:
      - ${CONFIG}/organizr:/config
    ports:
      - "8800:80"
    environment:
      - branch=master
      - PGID=${GID}
      - PUID=${UID}
      - TZ=Europe/Paris
```

Docker-compose log:

```
organizr  | [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
organizr  | [s6-init] ensuring user provided files have correct perms...exited 0.
organizr  | [fix-attrs.d] applying ownership & permissions fixes...
organizr  | [fix-attrs.d] done.
organizr  | [cont-init.d] executing container initialization scripts...
organizr  | [cont-init.d] 10-adduser: executing...
organizr  |
organizr  | -------------------------------------
organizr  | GID/UID
organizr  | -------------------------------------
organizr  | User uid:    501
organizr  | User gid:    20
organizr  | -------------------------------------
organizr  |
organizr  | [cont-init.d] 10-adduser: exited 0.
organizr  | [cont-init.d] 20-config: executing...
organizr  | [cont-init.d] 20-config: exited 0.
organizr  | [cont-init.d] 30-setup: executing...
organizr  | [cont-init.d] 30-setup: exited 0.
organizr  | [cont-init.d] 40-install: executing...
organizr  | -----------------------
organizr  | |  Updating Organizr  |
organizr  | -----------------------
Updating files: 100% (5262/5262), done.62)
organizr  | HEAD is now at a9a22244 Merge pull request #1735 from causefx/v2-develop
organizr  | Already on 'v2-master'
organizr  | Your branch is up to date with 'origin/v2-master'.
organizr  | HEAD is now at a9a22244 Merge pull request #1735 from causefx/v2-develop
organizr  | Already up to date.
organizr  | [cont-init.d] 40-install: exited 0.
organizr  | [cont-init.d] 50-debug: executing...
organizr  | -----------------------
organizr  | |     Kernel Info     |
organizr  | -----------------------
organizr  | Linux c9b27807c130 5.10.47-linuxkit #1 SMP Sat Jul 3 21:51:47 UTC 2021 x86_64 GNU/Linux
organizr  | Time Zone: Europe/Paris
organizr  | [cont-init.d] 50-debug: exited 0.
organizr  | [cont-init.d] done.
organizr  | [services.d] starting services
organizr  | [services.d] done.
```
<hr>

#### Errors on screen?  If so paste here:

```

```

**Comment by tronyx** [comment]
Sounds like something unique to you or your system. Perhaps an issue with Docker for MacOS? No one has ever reported any issues similar to this without it ending up being something weird with their machine. I can't even reproduce this on a Raspberry Pi 2 B+ system. The operations being performed by the container shouldn't use up that much CPU, at all, ever. It's all basic copy, rename, sed, and git operations. Nothing complex about the setup of the image at all.

Is this "${CONFIG}/organizr" a network share or a local disk on your machine? If it is a network share, that is not recommended with any containers that use SQLite, as Organizr does, so try switching to a real local directory on the machine.

**Comment by wivaku** [comment]
Glad to hear this is not the expected behavior.   
Not sure what would be special about my system / setup.  
When testing I use Docker without any other containers running, and CPU load is pretty much 0% before I start.
The config folder is a regular local folder.

**Comment by Roxedus** [comment]
Does it have the same behavior with no volume defined?

**Comment by wivaku** [comment]
Good question @Roxedus. In that case (re)start just takes seconds.  
I've seen issues about MacOS + Docker Volumes, but did not realize the performance was that dramatic. And it seems organizr is affected more than other containers.  
Using `:delegated` seems to help a bit.

```
    volumes:
      - ${CONFIG}/organizr:/config:delegated
```
