### ISSUE TITLE
Fail2Ban doesn't work anymore due to the new logs. The organizrLoginLog.json was last modified in September.

### ISSUE THREAD

**Issue by Cookie-Monster-Coder** [causefx/Organizr#1743]
###### Operating System: Ubuntu 20.04
<hr>

##### Problem Description:
Fail2Ban doesn't work anymore due to the new logs. The ```/var/www/xxxxxxxxx.com/db/organizrLoginLog.json``` was last modified in September.

Would the new path in jail.local be ```/var/www/xxxxxxxxx.com/db/logs/organizr-*.log```? 

and would the filter still be
```
[Definition]
failregex = ","username":"\S+","ip":"<HOST>","auth_type":"error"}*
ignoreregex =
```

<hr>

**Comment by HalianElf** [comment]
Yes, `logpath=/opt/organizr/www/db/logs/organizr*.log` and new filter regex is `failregex = {"log_level":"WARNING","message":"Wrong Password".*,"remote_ip_address":"<HOST>"`

**Comment by causefx** [comment]
sorry we need to update the docs...

Path:
```
logpath = /path/to/organizr/organizr*.log
```

Regex:
```
[Definition]
failregex = {"log_level":"WARNING","message":"Wrong Password".*,"remote_ip_address":"<HOST>"
```

**Comment by causefx** [comment]
lol beat me to it kp

**Comment by Cookie-Monster-Coder** [comment]
I also noticed that fail2ban does not pick up the new log files that are created by date after fail2ban has started.

So I'm thinking of running a cronjob everyday.
```2 0 * * * /etc/init.d/fail2ban restart```

Is there a better way of solving this problem?

**Comment by causefx** [comment]
i will test my setup tomorrow.
