### ISSUE TITLE
Cannot access ARR apps anymore

### ISSUE THREAD

**Issue by dirtymike0330** [causefx/Organizr#1745]
I'm not sure if this is an organizr issue or an nginx issue, so I have cross posted in both. I can access my arr apps (sonarr, radarr, etc) locally, but I stopped getting access today via the rev proxy. I am assuming something has gone wrong with nginx or within organizr? Any ideas? I am getting the attached screen cap when trying to access the apps via the reverse proxy address or by clicking on the tab within organizr. I have tried rebooting the router and restarting various dockers to no avail. Nothing out of the ordinary happened on my network today, as far as I can tell.
![help](https://user-images.githubusercontent.com/61566782/140253871-329e9c3b-5e35-4c1d-a6a6-f0c5311ea5e2.png)

**Comment by HalianElf** [comment]
I assume you're using NPM? jc21/nginx-proxy-manager#1319

**Comment by dirtymike0330** [comment]
Correct!

**Comment by dirtymike0330** [comment]
Oops, just noticed you linked me a solution :) Will check it out, thank you.
