### ISSUE TITLE
Webserver not setup for Organizr v2.1

### ISSUE THREAD

**Issue by ibracorp-sycotix** [causefx/Organizr#1747]
Organizr Version: V v2
###### Operating System: Ubuntu 18.04
<hr>

##### Problem Description:
On first deployment and accessing via the subdomain, an error is presented 

<hr>

##### Reproduction Steps:
- Install the container
- Label is added for Traefik
- Try to access organizr.domain.com
- Error is shown

<hr>

#### Errors on screen?  If so paste here:

```
Webserver not setup for Organizr v2.1
Please go to Migration guide to complete the changes...
Webserver Error:
404 Not Found
nginx
```
![image](https://user-images.githubusercontent.com/85398607/140601531-6884f7b9-8a25-4019-bd0b-492a7aad8264.png)

**Comment by GilbN** [comment]
Which container did you use?

**Comment by causefx** [comment]
I believe this was due to the wrong image being used.  Can we close this @ibracorp-sycotix ?

**Comment by ibracorp-sycotix** [comment]
That's correct, was using the old image. Updated to new one and everything works correctly. 

Sorry for the oversight. 

Cheers
