### ISSUE TITLE
Can not access tabs after update

### ISSUE THREAD

**Issue by tymanthius** [causefx/Organizr#1749]
###### Operating System: Unraid
<hr>

##### Problem Description:
Prior to updating Nov 5th I could access all tabs from outside my network with a simple port forward on my router.

After teh update, only Oganizr internal pages will display. Any external tabs (*arr, etc) give white page w/o any data (page not found sad face icon).

I suspect an nginx issue?

<hr>

##### Reproduction Steps:

Run unraid with this docker on port 5555

port forward via pfsense your WAN to unraid server, port 5555

Attempt to access from the WWW.

<hr>

#### Errors on screen?  If so paste here:

```

```

**Comment by causefx** [comment]
Not sure how you were accessing the other pages from WAN without proxying those services.  Organizr doesn't handle any proxying at all.

**Comment by tymanthius** [comment]
That's interesting, because it was working. 

BTW, added firewall rules and although I can get to <domain>:8989 If use :5555 and get to organizr the tabs still don't load.
