### ISSUE TITLE
LDAP query support 

### ISSUE THREAD

**Issue by bentamircea** [causefx/Organizr#1751]
###### Operating System: Windows/MacOS/Ubuntu
<hr>

##### Problem Description:

LDAP search is limited to find by DN prefix+uid+suffix. In addition match validation is based on "mail" attribute.

It would be nice to use $provider.query and let the user provide LDAP query string and the attribute to validate, i.e. memberOf query + "uid" attribute check.
<hr>

##### Reproduction Steps:

<hr>

#### Errors on screen?  If so paste here:

```

```

**Comment by HalianElf** [comment]
Sounds like you're referring to this: https://feature.organizr.app/posts/87/ldap-search-parameters

If not there are a few other LDAP requests there and if none of them match, make a feature request there where it belongs.
