### ISSUE TITLE
New feature: Integrate Uptime-kuma in homepage items

### ISSUE THREAD

**Issue by the-lazy-fox** [causefx/Organizr#1754]
Hi,

Uptime Kuma is a wonderful monitoring project (https://github.com/louislam/uptime-kuma/) to monitor the responseness of all your websites. 
They propose a status page to know if everything is up and running or if something is wrong.
It will be great in integrate this in Organizr to have a quick eye on it.

Thanks a lot!

![Status](https://user-images.githubusercontent.com/1336778/134628766-a3fe0981-0926-4285-ab46-891a21c3e4cb.png)

**Comment by HalianElf** [comment]
https://feature.organizr.app/posts/106/add-uptime-kuma-frontpage-support
