### ISSUE TITLE
URL on login page not consistent

### ISSUE THREAD

**Issue by Jerrk** [causefx/Organizr#1757]
###### Operating System: Unraid
<hr>

##### Problem Description:

When getting force logged after 30 days the URL is not changed so password managers like bitwarden don't recognize the page change and outputs the wrong username/password.
<hr>

##### Reproduction Steps:

EAsiest way to reproduce is to logout from organizr and change the url to something like http://url:9876/#Grafana. this will still show the login page even though the URL is referencing a different page.
<hr>

I would suggest that the URL should always be changed to http://url:9876/ when on the login page. or perhaps give it a suffix like http://url:9876/login or something to make it more consistent.

**Comment by HalianElf** [comment]
You'd be better off just having your password manager match the domain (which really should be the default on most if not all of them) which for bitwarden anyway, you can do per saved item and override whatever your default is.
![image](https://user-images.githubusercontent.com/28244771/142727694-ee037d91-bc89-4437-b758-5550c5c145bd.png)

More info: https://bitwarden.com/help/article/uri-match-detection/

**Comment by Jerrk** [comment]
The issue with that is that it will match my organizr username/password on every single tab which is the express reason why i'm using "exact". 
I dont want my organizr username/password matched and autofilled on URL/#radarr or URL/#syncthing, etc.

**Comment by causefx** [comment]
i'll come up with something.

**Comment by Jerrk** [comment]
waiting 
just commented so bot doesnt close

**Comment by causefx** [comment]
holidays... fixed in dev now.
