### ISSUE TITLE
Middle-clicking in firefox creates an extra tab named javascript:void(0)

### ISSUE THREAD

**Issue by Jerrk** [causefx/Organizr#1758]
###### Operating System: Unraid
<hr>

##### Problem Description:

When middle clicking to open a new tab it is creating an extra tab named javascript:void(0)
![](https://i.imgur.com/bN2yK2b.gif)
Firefox nightly 96.0a1
Organizr 2.1.1140
<hr>

##### Reproduction Steps:

Middle-click an organizr tab in firefox.
<hr>

this started happening a couple of months ago i think, when the function was released this issue was not present.

#1474

**Comment by Jerrk** [comment]
not stale, waiting on dev response

**Comment by causefx** [comment]
not sure what to do with this one, I suppose I can install FF to test this out.

**Comment by Jerrk** [comment]
Still an issue in version 2.1.1690

**Comment by bholland-bh** [comment]
Still happening Version: 2.1.2330
