### ISSUE TITLE
Custom CSS, Theme CSS can only save if a character is entered, not when deleted

### ISSUE THREAD

**Issue by Jerrk** [causefx/Organizr#1759]
###### Operating System: Unraid
<hr>

##### Problem Description:

When editing the Custom CSS i noticed that if i am just backspacing the save dialogue will not appear, i have to actually enter a character to be able to save the changes.
![](https://i.imgur.com/6ADdn21.gif)
<hr>

##### Reproduction Steps:

enter any changes to "Custom CSS", "Theme CSS", "Custom Javascript", or "Theme Javascript".
Save.
refresh the page
go back to either of the tabs
backspace anything
the save dialogue should not appear
<hr>
i tried it in both edge and firefox, both have the issue

**Comment by Jerrk** [comment]
not stale, waiting on dev response

**Comment by causefx** [comment]
let me check on this.

**Comment by causefx** [comment]
fixed in dev
