### ISSUE TITLE
Autoupgrade broken (

### ISSUE THREAD

**Issue by kendokan** [causefx/Organizr#176]
```
Warning: mkdir(): File exists in /config/www/Dashboard/settings.php on line 166
can't make dir
Fatal error: Uncaught Error: Class 'ZipArchive' not found in /config/www/Dashboard/settings.php:204 Stack trace: #0 /config/www/Dashboard/settings.php(270): unzipFile('upgrade.zip') #1 {main} thrown in /config/www/Dashboard/settings.php on line 204
```

```
$ php7 -v
PHP 7.0.16 (cli) (built: Feb 18 2017 15:05:55) ( NTS )

```

**Comment by causefx** [comment]
has it worked for you before?  if not you need to install php-zip

**Comment by kendokan** [comment]
It's probably just because the linuxserver.io letsencrypt Docker container I'm using doesn't include the library.

**Comment by causefx** [comment]
yup

**Comment by JigSawFr** [comment]
@kendokan please use this image https://github.com/linuxserver/docker-organizr instead of cloning directly organizr in letsEncrypt container.

This issue was fixed in their docker file 17 days ago: https://github.com/linuxserver/docker-organizr/issues/4
