### ISSUE TITLE
Documentation of how to create a plugin

### ISSUE THREAD

**Issue by SingingDwarf** [causefx/Organizr#1762]
Need some documentation on how to create a new plugin.

Would like to contribute with plugins for

>  MythTV 

> VirtualRadarServer

but unsure where to begin.

**Comment by causefx** [comment]
that is on my todo list. hopefully after thanksgiving

**Comment by causefx** [comment]
not inactive. on list to do.

**Comment by causefx** [comment]
Preliminary: https://docs.organizr.app/development/plugin-development
