### ISSUE TITLE
CustomJS not working

### ISSUE THREAD

**Issue by 000MDK** [causefx/Organizr#1763]
docker, organizr/organizr:latest
Chrome latest, but for testing also Edge-Chromium without addons

Not working in my production env, so:

new container, new db, fresh setup to confirm / new test env 

- added `//test` to customjs in UI
- confirmed it's in config.php ( `'customJava' => '//test',` )
- restarted the container, just to make sure
- reloaded the page

-->

```
<script id="custom-theme-javascript"></script>
<script id="custom-javascript"></script>
```

=> customJS not working

**Comment by causefx** [comment]
i just tested and got the correct thing.
![image](https://user-images.githubusercontent.com/16184466/144464225-67916f07-9ff4-4d10-aefe-a3ec71cb5431.png)

Is there any error in browser console?

**Comment by 000MDK** [comment]
Okay, I created a VM on another computer and also did not have this error.
So, I deleted/redownloaded the docker image and did a coldstart of the server. All good now.
edit: missing latest tag and changed the image -> misconfiguration on my side
