### ISSUE TITLE
[Feature Suggestion] Schedue Backups

### ISSUE THREAD

**Issue by neo-neo1** [causefx/Organizr#1764]
Would be useful if we could configure organizr to automatically create backups every x days. Plus an option to delete backups over x days old.

Besides automating backups it also adds pseudo incremental backups.

Sonarr/Radarr/Prowlarr have this feature and it's very incredibly useful.

Thanks for this great app

**Comment by tronyx** [comment]
Please use our official feature request site rather than submitting an issue: https://feature.organizr.app/
