### ISSUE TITLE
Sonarr api/v3/rootfolder not found

### ISSUE THREAD

**Issue by DuvelCorp** [causefx/Organizr#1765]
###### Sonarr Version 2.0.0.5344
<hr>

##### Problem Description:

Organizr is running on Ubuntu server in my LAN 192.168.1.x. Sonarr (and all the rest of the seedbox/jellyfin softwares) are running on different Ubuntu servers in the DMZ 192.168.2.x. 
All my config in Organizr is set with internal IPs and no domain names, thus no proxy between the servers.
Basically all my configured stuff has URLs like http://192.168.2.x:defaultport 

Sonarr tab do work. What doesn't work is the homepage features (I see nothing for Sonarr in combined downloads for instance)
Everything else on the homepage do work :  downloaders, indexers, jellyfin, ombi

![image](https://user-images.githubusercontent.com/33682764/144759466-eb30089a-66f5-4528-bd2e-c09a8198aeff.png)

When I test connection in Sonarr config I got this:
![image](https://user-images.githubusercontent.com/33682764/144758788-66a481af-2b96-4666-bc5c-ccd3c533de86.png)

Sonarr config is 
`{
	"Enable": {
		"homepageSonarrEnabled": true,
		"homepageSonarrAuth": "1"
	},
	"Connection": {
		"sonarrURL": "http://192.168.2.6:8989",
		"sonarrToken": "***redacted***",
		"sonarrDisableCertCheck": false,
		"sonarrUseCustomCertificate": false
	},
	"API SOCKS": {
		"sonarrSocksEnabled": false,
		"sonarrSocksAuth": "999"
	},
	"Queue": {
		"homepageSonarrQueueEnabled": true,
		"homepageSonarrQueueAuth": "1",
		"homepageSonarrQueueCombine": true,
		"homepageSonarrQueueRefresh": "60000"
	},
	"Calendar": {
		"calendarStart": "14",
		"calendarEnd": "14",
		"calendarFirstDay": "1",
		"calendarDefault": "month",
		"calendarTimeFormat": "h(:mm)t",
		"calendarLocale": "en",
		"calendarLimit": "1000",
		"calendarRefresh": "60000",
		"sonarrUnmonitored": true
	}
}`

I tried to enable API socks and it doesn't help.

What is strange is that when I first added Sonarr tab and configured the Home page settings for it, I THINK that it worked when I tested.

If I test manually the reported URL, I got :

![image](https://user-images.githubusercontent.com/33682764/144759060-8a7789ae-62ea-493a-bb2a-ba2e10eb9053.png)

<hr>

**Comment by causefx** [comment]
what version of sonarr?

**Comment by DuvelCorp** [comment]
I specified that in my post :) 
Sonarr Ver. 2.0.0.5344

**Comment by HalianElf** [comment]
You need to upgrade. v2 is long past unsupported

**Comment by tronyx** [comment]
Closing as upgrading to a current, supported version of Sonarr will resolve the issue.

**Comment by causefx** [comment]
> I specified that in my post :) 
> 
> Sonarr Ver. 2.0.0.5344

my bad. i skimmed on mobile. but yeah v2 is no longer supported.
