### ISSUE TITLE
Form Submission Broken

### ISSUE THREAD

**Issue by NeoVance** [causefx/Organizr#1767]
###### Operating System: Windows & Ubuntu
<hr>

##### Problem Description:

Form submission button fails using desktop chromium/webkit based browsers. Seems that jQuery is not able to locate the elements from the supplied query. Works in Chrome on Android though, strangely.
<hr>

##### Reproduction Steps:

* run v1 in docker with host volume mounted to `/config` directory.
* replace the container with a new v2 container using same host volume mounted to `/config` directory
* complete initial setup in any chromium/webkit based browser.
* go to any settings form and modify it
* attempt to save changes
<hr>

#### Errors on screen?  If so paste here:

```
functions.js?v=cf2b91b031b1d3c438a058339e96311918b5a188:3437 
        
       Uncaught TypeError: Cannot read properties of null (reading 'length')
    at functions.js?v=cf2b91b031b1d3c438a058339e96311918b5a188:3437
    at Function.each (jquery-2.2.4.min.js:2)
    at submitSettingsForm (functions.js?v=cf2b91b031b1d3c438a058339e96311918b5a188:3435)
    at HTMLButtonElement.onclick (VM1961 :1)
```

**Comment by tronyx** [comment]
There is no upgrade path from v1 to v2, you have to start fresh, so this is not an issue.

**Comment by causefx** [comment]
Can you try a fresh install?

**Comment by NeoVance** [comment]
I did the installation again. Here are the steps I followed for the fresh install:

```bash
devon@linux-xu19:/storage/docker/organizr> docker container ls | grep organ
devon@linux-xu19:/storage/docker/organizr> docker service scale apps_organizr=0
apps_organizr scaled to 0
overall progress: 0 out of 0 tasks 
verify: Service converged 
devon@linux-xu19:/storage/docker/organizr> docker container ls | grep organizr
devon@linux-xu19:/storage/docker/organizr> docker image ls | grep organizr
organizr/organizr                 <none>    3f2eb3965652   4 weeks ago     73.3MB
devon@linux-xu19:/storage/docker/organizr> docker image rm 3f2eb3965652
Untagged: organizr/organizr@sha256:d8b03b33ea1c65023ef7085bf06d13b0045a099e82fc833c9ac35c071b3e88a8
Deleted: sha256:3f2eb396565267f132e9dee5a2cc2ee494ad99a9b1709fd452b29eb39e42661a
Deleted: sha256:008296b30e5149346f1ff0a8697b5beeea90f32206371e4cbc0d6b441ab0a2f2
Deleted: sha256:8444a001047067e5e77f58d79d8478919f0ee1a5aa41bd3db5d726a6160e2f67
Deleted: sha256:31ce959191d62eebacd7734237a568b8cad02ade92c5f25b5d46894861a6b710
Deleted: sha256:e2eb06d8af8218cfec8210147357a68b7e13f7c485b991c288c2d01dc228bb68
devon@linux-xu19:/storage/docker/organizr> rm -rf ./*
devon@linux-xu19:/storage/docker/organizr> ls -la
total 8
drwxr-xr-x  2 devon docker 4096 Dec  9 13:22 .
drwxr-xr-x 18 devon users  4096 Dec  6 18:03 ..
devon@linux-xu19:/storage/docker/organizr> docker service scale apps_organizr=1
apps_organizr scaled to 1
overall progress: 1 out of 1 tasks 
1/1: running   [==================================================>] 
verify: Service converged
```
After that, I run through the initial setup wizard in the frontend GUI. The next part doesn't really matter. The same problem appears on all of the settings forms, but after the setup wizard completed, I go to `System Settings -> Main -> Authentication`. I change the Auth Method to `Organizr DB + Backend`, choose `Plex` backend, retrieve my plex token, and click save. The save button doesn't do anything. The following is output to the browser console:

```
functions.js?v=cf2b91b031b1d3c438a058339e96311918b5a188:11485 https://docs.organizr.app/help/faq/migration-guide#version-2-0-greater-than-version-2-1
functions.js?v=cf2b91b031b1d3c438a058339e96311918b5a188:11282  API V2 API  If you see a 404 Error for api/v2/launch below this line, you have not setup the new location block... See URL above this line 
functions.js?v=cf2b91b031b1d3c438a058339e96311918b5a188:11517  Organizr  2.1.1140 
functions.js?v=cf2b91b031b1d3c438a058339e96311918b5a188:11518  Status  Starting Up... 
functions.js?v=cf2b91b031b1d3c438a058339e96311918b5a188:5081  Style  dark 
functions.js?v=cf2b91b031b1d3c438a058339e96311918b5a188:5073  Theme  Organizr 
functions.js?v=cf2b91b031b1d3c438a058339e96311918b5a188:2860  Welcome  azdbagley 
functions.js?v=cf2b91b031b1d3c438a058339e96311918b5a188:11282  Tab Function  Loading new tab for: Settings 
functions.js?v=cf2b91b031b1d3c438a058339e96311918b5a188:11572  Organizr  DOM Fully loaded 
VM141 :1 
        
       Tracking Prevention blocked access to storage for https://www.gravatar.com/avatar/f1a3f67bc00351727299c2133a6123cf?s=100&d=mm.
jquery-2.2.4.min.js:4 
        
       [Deprecation] Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
send @ jquery-2.2.4.min.js:4
functions.js?v=cf2b91b031b1d3c438a058339e96311918b5a188:11282  JS Loader  js/Sortable.min.js?v=cf2b91b031b1d3c438a058339e96311918b5a188 
functions.js?v=cf2b91b031b1d3c438a058339e96311918b5a188:11282  JS Loader  Checking if script is loaded... 
functions.js?v=cf2b91b031b1d3c438a058339e96311918b5a188:11282  JS Loader  Script is NOT loaded... Loading now... 
2functions.js?v=cf2b91b031b1d3c438a058339e96311918b5a188:11282  Update Function  Already running latest version: 2.1.1140 
functions.js?v=cf2b91b031b1d3c438a058339e96311918b5a188:11282  Update Function  Organizr Docker - Up to date 
functions.js?v=cf2b91b031b1d3c438a058339e96311918b5a188:11282  Organizr Function  Loading Appearance 
functions.js?v=cf2b91b031b1d3c438a058339e96311918b5a188:11282  Organizr Function  Loading Main 
VM141 :1 Autofocus processing was blocked because a document already has a focused element.
functions.js?v=cf2b91b031b1d3c438a058339e96311918b5a188:3437 
        
       Uncaught TypeError: Cannot read properties of null (reading 'length')
    at functions.js?v=cf2b91b031b1d3c438a058339e96311918b5a188:3437
    at Function.each (jquery-2.2.4.min.js:2)
    at submitSettingsForm (functions.js?v=cf2b91b031b1d3c438a058339e96311918b5a188:3435)
    at HTMLButtonElement.onclick (VM141 :1)
DevTools failed to load source map: Could not load content for https://www.xkvator.com/js/tinycolor.min.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://www.xkvator.com/js/plyr.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
```

**Comment by tronyx** [comment]
Where, exactly, is the "/storage/docker/organizr" path located? Local to the Sever or is it a mounted share?

**Comment by NeoVance** [comment]
Local. Also, it's a single node swarm, so no worries about replication.

**Comment by causefx** [comment]
navigate to that same settings part again and paste this in browser console: 
```
$( "#settings-main-form" ).serializeToJSON();
```

**Comment by NeoVance** [comment]
So specifically, functions.js `submitSettingsForm` is not handling some null values being added to the form list by jQuery.

```javascript
function submitSettingsForm(form, homepageItem = false){
    var list = $( "#"+form ).serializeToJSON();
    var size = 0;
    var submit = {};
    $.each(list, function(i,v) {
        var values = false;
        if(typeof v === 'object' && typeof v.length === 'undefined') // v == null, and typeof null is 'object'
```

The two nulls I see in the query results are:
```
blacklist: null,
...
localIPList: null
```

The solution is simply to check for null... or better yet, since you are checking for the `length` property, use `Array.isArray(v)` instead of checking for an object with the `length` property. Alternatively I guess you can figure out why the lists are initialized as null rather than an empty array.

**Comment by causefx** [comment]
yeah not sure why they are returning `null` instead of `undefined`...

can you try going back and pasting this: 
```
$( "#settings-main-form" ).serializeToJSON().blacklisted
```
and 
```
typeof $( "#settings-main-form" ).serializeToJSON().blacklisted
```

**Comment by NeoVance** [comment]
```
$( "#settings-main-form" ).serializeToJSON().blacklisted
null
typeof $( "#settings-main-form" ).serializeToJSON().blacklisted
'object'
```

**Comment by causefx** [comment]
that is so wild lol...  I'll just add in a check for null i suppose....  I'll look into converting objects later.

**Comment by NeoVance** [comment]
My suggestion would be using `Array.isArray(v)` instead. Far less verbose, and less fragile than `typeof v == 'object' && v !== null && typeof v.length !== 'undefined'` and it is pretty well supported.

> ```
> Array.isArray([1, 2, 3]);  // true
> Array.isArray({foo: 123}); // false
> Array.isArray('foobar');   // false
> Array.isArray(undefined);  // false
> Array.isArray(null); // false
> ```
> [https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/isArray](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/isArray)

This has the potential to be a problem in the future, since any object with a length property could be passed in... but specifically, you want an object that implements the Array prototype, because it is then passed to `$.each`, which expects:
```
array
Type: ArrayLikeObject
The array or array-like object to iterate over.
```

**Comment by causefx** [comment]
I wish it was that simple without a re-write.  Reason being some of the objects are not object Arrays....  So a catch all for `Array.isArray` won't work here...

A few examples:
![image](https://user-images.githubusercontent.com/16184466/145488814-e0dc37a4-2a42-4628-b024-8c00d66d71ea.png)

![image](https://user-images.githubusercontent.com/16184466/145488859-c42967cd-b0da-41a9-b591-e872cf149f5e.png)

![image](https://user-images.githubusercontent.com/16184466/145488914-2cd4c932-496d-4c49-9298-6fa4fa4a77a2.png)

One last thing, can you type this in for me please:

```
Object.prototype.toString.call($( "#settings-main-form" ).serializeToJSON().blacklisted)
```
 
should be `[object Null]`

**Comment by NeoVance** [comment]
```
Object.prototype.toString.call($( "#settings-main-form" ).serializeToJSON().blacklisted)
'[object Null]'
```

**Comment by NeoVance** [comment]
Yeah, and I just checked with jQuery. `each` is pretty indiscriminate. It will iterate through an object's key/values regardless. It doesn't really care if an object is **"ArrayLike"** or not. The only thing you can do is: `typeof v === 'object' && v !== null` I noticed that jQuery really doesn't care if there is a `length` property or not though. The only issue with not having the length property would be that if the length property isn't there the order of the keys may not be guaranteed.

**Comment by causefx** [comment]
i have a fix already. :)

**Comment by NeoVance** [comment]
Awesome.

**Comment by causefx** [comment]
If you are on dev, you can try the latest commit.

**Comment by causefx** [comment]
@NeoVance were you able to test?

**Comment by NeoVance** [comment]
Yeah. I updated to using the Dev branch, and it seems to be working.
