### ISSUE TITLE
two iframe tabs can't work

### ISSUE THREAD

**Issue by zzz929625** [causefx/Organizr#1768]
##### Problem Description:
I have set two tabs which is emby and overseerr,and if I only use one tab,both emby and overseerr works fine.But if set two tabs,whatever I click emby or overseerr,It's always open overseerr.Both use iFrame,and I tried new window,both can't open
Check the log,no error shows up.

I use proxy manager to reverse my emby and overseerr,and the web is like “video.example.com:10443" for emby,"overseerr.example.com:10443" for overseerr,I don't know if the domain broken the iframe

**Comment by zzz929625** [comment]
find the problem,it's the tab name.I use the Chinese for the tab name and can't works two iframe tab,Change back to english all seems fine.
Should I close the comment?

**Comment by causefx** [comment]
hmmmm
i need to figure this out

**Comment by causefx** [comment]
can you paste the tabs name in here please?

**Comment by causefx** [comment]
any update?

**Comment by zzz929625** [comment]
sorry for the delay🤣，I change back to Chinese for test,when i use Chinese for emby tab name like "媒体",and "请求" for ombi
![image](https://user-images.githubusercontent.com/49552476/161298306-68bda88d-49ae-4932-b315-75bddeffbf20.png)
when i click emby page,the iframe will jump to ombi,can't open emby by click the icon,and I'm noticed that lihgt bar means selected always side with the homepage
If I click overseerr tab,looks fine
![image](https://user-images.githubusercontent.com/49552476/161299258-624d09d6-959f-47f0-afcb-c2bda290bf4f.png)

**Comment by causefx** [comment]
![image](https://user-images.githubusercontent.com/16184466/161318828-e549e558-4fc5-4620-a4f6-76f1d44c1047.png)

fixed in dev now.  Will push to master later today

**Comment by zzz929625** [comment]
> ![image](https://user-images.githubusercontent.com/16184466/161318828-e549e558-4fc5-4620-a4f6-76f1d44c1047.png)
> 
> fixed in dev now. Will push to master later today

after update,all works fine
thx
