### ISSUE TITLE
Where is this "Homepage"

### ISSUE THREAD

**Issue by rudyvarner** [causefx/Organizr#177]
I have entered in all of my information, at least I think I have correctly.  But where is this elusive homepage?

**Comment by kendokan** [comment]
https://github.com/causefx/Organizr/wiki/Optional-Homepage

**Comment by causefx** [comment]
@rudyvarner it's still beta for the homepage, but add in your info, then add a new tab with the url homepage.php

**Comment by causefx** [comment]
@rudyvarner are you good with this?

**Comment by rudyvarner** [comment]
Yes.  Worked like a charm once you pointed me to the instructions.  I checked the wiki the other day and could not find anything relating to it.  Also, will you be changing the homepage to follow the theme colors?

**Comment by causefx** [comment]
yes that is on the table right now. :)
