### ISSUE TITLE
Organizr 2 timesout while updating

### ISSUE THREAD

**Issue by tessierp** [causefx/Organizr#1770]
It seems that Organizr timesout while an update is underway. I get to the point where the logs show  : 
Updating Organizr, stays there a while then a kill term is sent and a status of the update with percentages. Not sure if this kind of update could be done elsewhere instead of during load time, it would be more efficient and could help solve this issue.

`[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 10-adduser: executing... 

-------------------------------------
GID/UID
-------------------------------------
User uid:    80
User gid:    80
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 20-config: executing... 
[cont-init.d] 20-config: exited 0.
[cont-init.d] 30-setup: executing... 
[cont-init.d] 30-setup: exited 0.
[cont-init.d] 40-install: executing... 
-----------------------
|  Updating Organizr  |
-----------------------
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
Updating files:   0% (44/5314)
Updating files:   1% (54/5314)
Updating files:   1% (84/5314)
Updating files:   1% (103/5314)
Updating files:   2% (107/5314)
Updating files:   2% (139/5314)
Updating files:   3% (160/5314)
Updating files:   3% (186/5314)
Updating files:   4% (213/5314)
Updating files:   4% (219/5314)
Updating files:   4% (261/5314)
Updating files:   5% (266/5314)
Updating files:   5% (283/5314)
Updating files:   6% (319/5314)
Updating files:   6% (346/5314)
Updating files:   7% (372/5314)
Updating files:   7% (417/5314)
Updating files:   8% (426/5314)
Updating files:   9% (479/5314)
Updating files:   9% (481/5314)
Updating files:   9% (491/5314)
Updating files:   9% (506/5314)
Updating files:  10% (532/5314)
Updating files:  10% (548/5314)
Updating files:  11% (585/5314)
Updating files:  11% (633/5314)
Updating files:  12% (638/5314)
Updating files:  13% (691/5314)
Updating files:  13% (697/5314)
Updating files:  14% (744/5314)
Updating files:  14% (764/5314)
Updating files:  14% (768/5314)
Updating files:  14% (770/5314)
Updating files:  14% (771/5314)
Updating files:  14% (781/5314)
Updating files:  14% (782/5314)
Updating files:  14% (783/5314)
Updating files:  14% (784/5314)
Updating files:  14% (785/5314)
Updating files:  15% (798/5314)
Updating files:  15% (811/5314)
Updating files:  15% (837/5314)
Updating files:  16% (851/5314)
Updating files:  16% (870/5314)
Updating files:  17% (904/5314)
Updating files:  17% (916/5314)
Updating files:  17% (919/5314)
Updating files:  17% (920/5314)
Updating files:  17% (936/5314)
Updating files:  18% (957/5314)
Updating files:  18% (982/5314)
Updating files:  19% (1010/5314)
Updating files:  19% (1017/5314)
Updating files:  20% (1063/5314)
Updating files:  20% (1068/5314)
Updating files:  20% (1071/5314)
Updating files:  20% (1105/5314)
Updating files:  21% (1116/5314)
Updating files:  22% (1170/5314)
Updating files:  22% (1176/5314)
Updating files:  23% (1223/5314)
Updating files:  23% (1250/5314)
Updating files:  24% (1276/5314)
Updating files:  24% (1313/5314)
Updating files:  24% (1320/5314)
Updating files:  24% (1321/5314)
Updating files:  24% (1323/5314)
Updating files:  25% (1329/5314)
Updating files:  25% (1331/5314)
Updating files:  26% (1382/5314)
Updating files:  26% (1412/5314)
Updating files:  27% (1435/5314)
Updating files:  28% (1488/5314)
Updating files:  28% (1496/5314)
Updating files:  29% (1542/5314)
Updating files:  29% (1545/5314)
Updating files:  29% (1570/5314)
Updating files:  30% (1595/5314)
Updating files:  30% (1600/5314)
Updating files:  31% (1648/5314)
Updating files:  31% (1651/5314)
Updating files:  31% (1681/5314)
Updating files:  31% (1682/5314)
Updating files:  31% (1690/5314)
Updating files:  32% (1701/5314)
Updating files:  32% (1716/5314)
Updating files:  32% (1718/5314)
Updating files:  32% (1720/5314)
Updating files:  32% (1731/5314)
Updating files:  32% (1733/5314)
Updating files:  33% (1754/5314)
Updating files:  33% (1803/5314)
Updating files:  34% (1807/5314)
Updating files:  35% (1860/5314)
Updating files:  35% (1868/5314)
Updating files:  36% (1914/5314)
Updating files:  36% (1924/5314)
Updating files:  37% (1967/5314)
Updating files:  37% (1971/5314)
Updating files:  37% (2017/5314)
Updating files:  38% (2020/5314)
Updating files:  39% (2073/5314)
Updating files:  39% (2075/5314)
Updating files:  39% (2108/5314)
Updating files:  40% (2126/5314)
Updating files:  41% (2179/5314)
Updating files:  41% (2185/5314)
Updating files:  42% (2232/5314)
Updating files:  42% (2241/5314)
Updating files:  42% (2271/5314)
Updating files:  42% (2272/5314)
Updating files:  42% (2273/5314)
Updating files:  42% (2275/5314)
Updating files:  42% (2276/5314)
Updating files:  42% (2277/5314)
Updating files:  42% (2278/5314)
Updating files:  42% (2281/5314)
Updating files:  42% (2282/5314)
Updating files:  43% (2286/5314)
Updating files:  43% (2322/5314)
Updating files:  44% (2339/5314)
Updating files:  44% (2360/5314)
Updating files:  45% (2392/5314)
Updating files:  45% (2424/5314)
Updating files:  46% (2445/5314)
Updating files:  46% (2471/5314)
Updating files:  46% (2483/5314)
Updating files:  47% (2498/5314)
Updating files:  47% (2540/5314)
Updating files:  48% (2551/5314)
Updating files:  49% (2604/5314)
Updating files:  49% (2618/5314)
Updating files:  49% (2627/5314)
Updating files:  49% (2631/5314)
Updating files:  49% (2633/5314)
Updating files:  49% (2641/5314)
Updating files:  49% (2649/5314)
Updating files:  49% (2655/5314)
Updating files:  50% (2657/5314)
Updating files:  50% (2684/5314)
Updating files:  51% (2711/5314)
Updating files:  51% (2745/5314)
Updating files:  52% (2764/5314)
Updating files:  52% (2778/5314)
Updating files:  53% (2817/5314)
Updating files:  53% (2833/5314)
Updating files:  54% (2870/5314)
Updating files:  54% (2893/5314)
Updating files:  55% (2923/5314)
Updating files:  55% (2945/5314)
Updating files:  56% (2976/5314)
Updating files:  56% (3010/5314)
Updating files:  57% (3029/5314)
Updating files:  57% (3046/5314)
Updating files:  57% (3052/5314)
Updating files:  57% (3065/5314)
Updating files:  57% (3076/5314)
Updating files:  57% (3080/5314)
Updating files:  58% (3083/5314)
Updating files:  58% (3086/5314)
Updating files:  58% (3093/5314)
Updating files:  59% (3136/5314)
Updating files:  59% (3144/5314)
Updating files:  60% (3189/5314)
Updating files:  60% (3211/5314)
Updating files:  61% (3242/5314)
Updating files:  61% (3276/5314)
Updating files:  62% (3295/5314)
Updating files:  62% (3307/5314)
Updating files:  62% (3311/5314)
Updating files:  63% (3348/5314)
Updating files:  63% (3363/5314)
Updating files:  64% (3401/5314)
Updating files:  64% (3406/5314)
Updating files:  64% (3436/5314)
Updating files:  65% (3455/5314)
Updating files:  65% (3500/5314)
Updating files:  66% (3508/5314)
Updating files:  66% (3514/5314)
Updating files:  66% (3516/5314)
`

**Comment by causefx** [comment]
@Roxedus is this a limitation of the container image?  i'm unaware of any timeouts on `git` commands.

**Comment by Roxedus** [comment]
Log cuts out too early, but there is no additional limitations set by us, no.

**Comment by tessierp** [comment]
I have looked for other log sources to see if I could find something that could help. What I do know is the update doesn't always stop at 66%. Sometimes at 64%, sometimes a little more. So there is some kind of timeout going on. I have tried to find a way to extend the timeout for the container but so far whatever I have used in my docker compose doesn't work.

**Comment by causefx** [comment]
disk space issue?

**Comment by Roxedus** [comment]
It does not sound like a traditional timeout at all, as that's logged in the same place. It almost looks like it gets stuck on some files, bad IO maybe?

**Comment by tessierp** [comment]
Definitely not a disk space issue. I retried this a couple of times before and the percentage kept going up so I presume it skips files that are up to date but there is a time issue here.  Perhaps this update could happen somewhere else, maybe after the app loaded via a update button.

**Comment by tessierp** [comment]
To explain what is going on. I recently migrated all of my docker data volumes to my TrueNAS server. All of them are fine except for Organizr which, as you know, timeouts while updating. For some reason the update takes a long time here and I am not sure why.

If I instead use local data volumes (on the docker server), everything works. I'm not sure why the IO is so bad because TrueNAS is exceptionally fast.

**Comment by tessierp** [comment]
Small update, it eventually worked but, it took many retries to get all the files updated. I would  highly suggest this kind of an  update to be done after the application start if possible. Now all is fine and I still have the data volume on my TrueNAS server but it tools like 20 retries to get all of the updates through. Again, I do not understand why the IO is so poor here. Did a data transfer test and I'm getting 120 mb/s

**Comment by Roxedus** [comment]
This update step would also install Organizr if it was not present

**Comment by tessierp** [comment]
What I am saying is, perhaps it is not the best place to do it, or it is assumed that everything comes packaged in the docker package for instance, no need to download. I am sure there could be other places to do this step instead of in the middle of bootstrapping the application. If not, as it stands, there is no way to have organizr 2 working in a shared drive like I am doing right now. And TrueNAS is not slow.

At least, if you must, check if the application is there already.. But I insist, this is something, an update or install step that should be done elsewhere, not in the middle of an application loading.

**Comment by HalianElf** [comment]
Organizr itself is not part of the image. It gets download (and updated) via git during that that script on start. And yes you are correct, you should not be running it on a shared drive. SQLite doesn't like it and it's not a supported configuration.

**Comment by tessierp** [comment]
Correction, it should be on a shared drive exactly because it runs on a swarm and any node can pick up the data. I have ran many databases system including SQLIte on major systems and this was never an issue btw. What shouldn't happen is downloading the entire application while it is loading up. There should be an option to already have all the files there and only do an update when necessary. But suit yourself if you think that is good practice, I certainly do not think so.

I guess this means  Organizr is not the right product for a high availability environment. I'll look elsewhere. Perhaps one day you realize this needs to be changed and not have the app download everything in the middle.

**Comment by HalianElf** [comment]
> Correction, it should be on a shared drive exactly because it runs on a swarm and any node can pick up the data. I have ran many databases system including SQLIte on major systems and this was never an issue btw. What shouldn't happen is downloading the entire application while it is loading up.

You're just lucky. Using SQLite on network storage is just asking for corruption: https://www.sqlite.org/draft/useovernet.html

> There should be an option to already have all the files there and only do an update when necessary. But suit yourself if you think that is good practice, I certainly do not think so.

I never said it was good practice. We've talked about putting it in the image but it requires changes in the way Organizr is coded to do it properly so it is what it is right now.

**Comment by tessierp** [comment]
It has nothing to do with luck when you make sure only one container at a time has access to the data, plain and simple.

Another recommendation aside from pre-packaging the binaries would be to support a SQL server such as PostgreSQL. SQLite is great for embedded applications but using it in the docker world means people will probably want to stuff on multiple nodes eventually or in my case, when they realize the issue, they will only have a single node running the app at any given time.

**Comment by angrycuban13** [comment]
SQLite's own documentation tells you that it is not a good idea. 

```
This simple, "remote database" approach is usually not the best way to use a single
SQLite database from multiple systems (even if it appears to "work"), 
as it often leads to various kinds of trouble and grief. 
Because these problems are inevitable with some usages, 
but not frequent or repeatable, it behooves application developers to not rely 
on early testing success to decide that their remote database use will work as desired.
```

> Another recommendation aside from pre-packaging the binaries would be to support a SQL server such as PostgreSQL

Be the change you want to see. This is all open source after all and you are welcome to contribute.

**Comment by tessierp** [comment]
@angrycuban13 I have read the documentation. And I have actually used SQLite in the past working on applications. I have 20 years experience with backend systems. That being said this is why I did CLEARLY say "ONLY ONE INSTANCE AT A TIME IS ACCESSING THE DATA". This means there is no risk of data corruption. The only difference with my approach is, the data is safe in a central place as opposed to a single server where an application is running, if something bad happens to it is it gone. I'm sorry but you need to learn to read.. The documentation clearly says "MULTIPLE SYSTEMS". I am not using MULTIPLE SYSTEMS. I am only using multiple nodes yes but I don't have multiple replicas of that application, JUST ONE! And if I am lucky, I guess I've been lucky for years. But this is no luck, this is just understanding what the situation is and adapting it in the right way. The only difference here, as opposed to embedded in the same location, I have decoupled it but it is only use by one app, remotely. The only issue that can happen here, is if the data becomes unavailable.. Well the application doesn't get its date then.

As for contributing, I am making a suggestion. You assume I have the time or am not already involved in other projects.  Does me making a recommendation mean anything other than proposing something that would make the project better? If I would contribute to everything where I put in a recommendation I would have no more time for myself. According to your standard, making a proposal means you have to work on it yourself. If that would be true of everything, everyone would keep to themselves. But no, I think that when something can benefit from a positive feedback and recommendation why not do it!

That being said, there are other solutions out there that I am currently trying out but would like to see Organizr support more. Doesn't mean they have to but I am sure others out there would probably like this. Up tot he community to decide!

**Comment by causefx** [comment]
this is something on the roadmap for sure. just not any time soon.

**Comment by tessierp** [comment]
> this is something on the roadmap for sure. just not any time soon.

**Comment by tessierp** [comment]
Sorry didn't mean to close this.. Good to know it is on the roadmap and looking forward to it :)
