### ISSUE TITLE
Proxy Auth not logging me in

### ISSUE THREAD

**Issue by toxic0berliner** [causefx/Organizr#1771]
###### Operating System: docker on ubuntu
<hr>

##### Problem Description:
Organizer is behind traefik using 
thomseddon/traefik-forward-auth  that is setting X-Forwarded-User header to my gmail account. I enabled ProxyAuth with this header for email and some other invalid value for username. Even tried empty for the username header and X-Forwarded-User for email, but no luck : I get forwarded to Gmail and login successfuly but when I am forwarded back to organizr I am prompted for a login instead of being logged in.
All this using organizer internal db.
I can indeed login with the email that is passed as header and with the proper password, but I never get logged in automatically by organizr recognizing the header...

**Comment by causefx** [comment]
Did you set the the IP subnet for the allow list?

**Comment by toxic0berliner** [comment]
Yes I had but obviously I had it wrong. Now I fixed it to my docker ip and got stuck later on.
My traefik-forward-auth only adds a header with the email and none for the username as traefik has no idea about my organizr username.
I can't seem to find a way to auto login with this.

Putting X-Forwarded-User in the username fails the login (error showing up on organizr login screen)
Putting it only in the email header section and leaving the username empty doesn't trigger auto login at all:(

To be clearer, my username is toxic0berliner and my email is somethingelse@gmail.com but I only have one header being added that contains somethingelse@gmail.com and it doesn't get picked up if I put it in the second field of proxy auth and leave the first one empty. Putting in the first or both fields on the proxy auth settings page just results in "User credentials incorrect" error

**Comment by causefx** [comment]
I think i see the issue...  any way you can switch to dev branch?

**Comment by toxic0berliner** [comment]
Sure, I'm the only user so I just switched my compose file to say branch=v2-develop and it's now up and running on dev branch ;)
Still getting the error but ready to test if you push any kind of update ;)

Current error : 
![image](https://user-images.githubusercontent.com/10488124/146407543-88c463fd-150a-44ed-a46a-f9182a9ebf26.png)
Current settings : 
![image](https://user-images.githubusercontent.com/10488124/146407681-32e954ab-3d4e-44f7-9132-414db35e5b53.png)
(will switch to a more specific whitelist and unexpected header once we got this working ;) )

**Comment by causefx** [comment]
anything in the logs?

**Comment by toxic0berliner** [comment]
I see "Wrong Password" when I never input a password and don't expect ProxyAuth to give passwords, and after that "User has failed verification using Auth Proxy"

**Comment by causefx** [comment]
That means the server address isnt inside the whitelist range.

**Comment by causefx** [comment]
let me add more logging info there.

**Comment by causefx** [comment]
Ok, update org once more and change log level to debug and try again.

**Comment by toxic0berliner** [comment]
I'm not that proficient with my traefik so not sure I can have a look at the exact http request that gets forwarded to organizr but with a little bit of help I could probably find it in organizr logs checking both ip of the server and content of forwarded user header ;)
The range is containg all IPs that my docker hands out, I just tried with only the IP of the traefik container ans still the same.
Just reading your ask to update, will do !

**Comment by toxic0berliner** [comment]
Somehow I'm not seeing updates available, but now I get this : 
User has been verified using Auth Proxy
 /config/www/organizr/api/classes/organizr.class.php#L2772
But it is actually still not logging me in automatically, but putting only my user id in the login form and not putting a password does log me in ;)
Need to go for a few hours, will try later to look at the webserver's logs or try anything you proposed/ask inbetween. Thanks a lot for your time, see you later ;)

**Comment by causefx** [comment]
sounds good, i just pushed another update for dev branch.   Just by loading organizr it should check.

**Comment by toxic0berliner** [comment]
Perfect! Now clicking logout just brings me back to the homepage with a nice "Login successful" message as it automatically logs me back in again using the header! Perfect!
Thanks a lot and congratulations on the reactivity and point on fix !

Now it still gives me an idea for an enhancement, after login me out if I could setup the logout url of my proxy auth it would be great if organizer can log me out then redirect me to that url that would fully log me off.
To be clear, traefik-forward-auth provides a auth.example.com/_oauth/logout url that will clear the proxy cookie and make this logout a real logout for my config. But logout feature is really optional for me and would require UI changes in organizr admin I think.

Again, thanks a lot !

**Comment by causefx** [comment]
Let me think about this.

**Comment by causefx** [comment]
@toxic0berliner do I just need to GET request `auth.example.com/_oauth/logout` or do I need to send that user to that URL?

**Comment by toxic0berliner** [comment]
You would need to send the user to that url I believe as I think it will probably clear some cookies and not only invalidate the session. You could probably do a get but you would have to also send the ProxyAuth session cookies and I think that's getting complicated for no gain.
Sending the user to that url would be best.

**Comment by causefx** [comment]
I can add an input box to overwrite the logout url

**Comment by toxic0berliner** [comment]
That would do the trick and would be very nice for me and anyone using Proxy Auth with a logout url ;)

**Comment by toxic0berliner** [comment]
I just checked and it seems the trusted proxy field is only allowing static IP, and is not accepting CIDR notation for IP range. As my proxy is on docker and with a changing IP when traefik gets updated, it stopped working for me until I changed the field to the new IP of my proxy. I get that this is probably an edge case for which I'm probably one of the few users, but as you fixed the previous issue so fast I dare ask here if you could add CIDR notation so that setting 172.17.0.0/16 as trusted proxy, any IP in this range would be considered trusted.

**Comment by causefx** [comment]
lemme check the code again

**Comment by causefx** [comment]
It seems it already accepts the subnet.  If you enable debug logging you can see what it is checking and if the range was set.   You will just have to convert from ip2long to long2ip.

**Comment by causefx** [comment]
![image](https://user-images.githubusercontent.com/16184466/148606073-b68f14b2-b96e-400d-9638-cc199c2e2043.png)

**Comment by toxic0berliner** [comment]
I got this working, sorry to have bothered you !

In fact, something was wrong in my config, probably due to me editing the setting with a theme enabled as I had this : 
![image](https://user-images.githubusercontent.com/10488124/148629472-59249692-0cf3-47ac-b2bb-548169320d79.png)
with this config : 
![image](https://user-images.githubusercontent.com/10488124/148629483-db6440f7-825f-4488-891b-5a677c9ffb2a.png)

But now I've updated it, it does have a start and end range and I managed to set it so all my docker IPs will fall into it ;) perfect, thanks !

**Comment by causefx** [comment]
added logout url for authProxy people

**Comment by toxic0berliner** [comment]
I'm on the develop branch still and using the docker image but somehow the authproxy broke again several weeks ago, not seeing any attempts at logging me in even if I have the traefik forward auth working. I'm not sure if it's an issue with my reverse proxy though, maybe organizr is getting an empty X-Real-User header as I've seen some bug report on my forward auth extension. Will look into it and report but it might be a month until I can get into it.

**Comment by toxic0berliner** [comment]
Just checked, hat to "force the branch installation" since I did not see the setting, but now it works like a charm !

Than you very much !

**Comment by causefx** [comment]
thanks.
