### ISSUE TITLE
Tautulli Homepage item throws error, preventing me from editing it

### ISSUE THREAD

**Issue by uofirob** [causefx/Organizr#1776]
###### Operating System: TrueNAS Scale (Docker Image on K3S)
<hr>

##### Problem Description:
I edited Tautulli's Homepage item information, saved, checked and it worked.  I've closed the homepage item box, and when I try to go back to edit it, I get this error:  "Tautulli Homepage Error - Unable to get list of libraries: cURL error 7: Failed to connect to tautulli.ix-tautulli.svc.cluster.local port 36108 after 1 ms: Connection refused" and I'm unable to get the box to re-open for me to edit the values.

<hr>

##### Reproduction Steps:
Log in -> Settings -> tab Editor -> Homepage Items -> Tautull -> Get red box error

<hr>

#### Errors on screen?  If so paste here:
```
Tautulli Homepage Error - Unable to get list of libraries: cURL error 7: Failed to connect to tautulli.ix-tautulli.svc.cluster.local port 36108 after 1 ms: Connection refused
```

**Comment by uofirob** [comment]
Any suggestion on going and editing a value behind the scenes to get this editable again?

**Comment by causefx** [comment]
you can edit the tautulli values in `api/config/config.php`

**Comment by uofirob** [comment]
Thank you!  Do you know why it would cause the entire editing page to no longer work?

**Comment by causefx** [comment]
i have to check - is the issue the url or port?

**Comment by uofirob** [comment]
I think it's the port.  I think I used the k3s external port instead of the internal one.

**Comment by uofirob** [comment]
I've been able to fix it by fixing the port.  Thanks for the location of the config.php file!

**Comment by causefx** [comment]
this has been fixed
