### ISSUE TITLE
Feature Request: duplicate button

### ISSUE THREAD

**Issue by bitshiftnetau** [causefx/Organizr#1778]
##### Problem Description:
Would be great if we could simply duplicate an existing tab and it then appeared underneath the tab it was duplicated from. This would save some time when setting up various similar environments.

**Comment by causefx** [comment]
please request this over at: https://feature.organizr.app/

**Comment by bitshiftnetau** [comment]
Do me a favour and put that in your github somewhere? 

I've just submitted 3 requests here and 1 initially over at the docker-organizr github. Would help to avoid wasting people's time.

**Comment by bitshiftnetau** [comment]
Oh ffs it requires yet another login.. there are perfectly adequate templates on github which could have been utilized. Over-complicating the process helps exactly no-one.

**Comment by causefx** [comment]
you don't **have** to make the request over there.... 🤷🏽‍♂️

**Comment by bitshiftnetau** [comment]
You also don't HAVE to make it difficult or re-invent the wheel but here we are.

**Comment by causefx** [comment]
lol cool beans dude.
