### ISSUE TITLE
Saving password on phone

### ISSUE THREAD

**Issue by Miicker** [causefx/Organizr#178]
Hello guys,

I have the following issue: whenever I use Organizr on my phone, I can't use the srored password, because it saved the hashed password and that one only works one time.

I think this happens because when you hit "Login" the password in the password field changes, I can't store my real password. If I do store my real password (which only works one time) it is not saved after logging in, because the password gets automatically updated to the hashed password.

Is it possible for you guys to change this so it does not happen?

Thank you!

**Comment by causefx** [comment]
What OS is this on?

**Comment by Miicker** [comment]
I use Safari on iOS (newest version on iPhone 7)

**Comment by Miicker** [comment]
Is someone looking into this @causefx ?

**Comment by causefx** [comment]
i will try and figure out a work around.

**Comment by Miicker** [comment]
Thanks! 👍

**Comment by Cerothen** [comment]
Same as #265
