### ISSUE TITLE
Feature Request: visual dashboard

### ISSUE THREAD

**Issue by bitshiftnetau** [causefx/Organizr#1780]
Would love to see a visual representation of the apps I have configured, much like Heimdall. 

Example:

![heimdall](https://user-images.githubusercontent.com/26871600/148575370-18e43e25-12ad-4601-8f08-b5c16771891b.png)

**Comment by HalianElf** [comment]
So the Splash screen? Also as you were told with your other FR, requests go to https://feature.organizr.app

**Comment by bitshiftnetau** [comment]
> So the Splash screen? Also as you were told with your other FR, requests go to https://feature.organizr.app

In case you didn't notice those requests were made in quick succession so I didn't see the comment.. but good work on being unhelpful and snarky..

It's like developers these days are just born arrogant and stupid. Incredible.

**Comment by causefx** [comment]
lol - chill the fuck out dude.  Not entirely sure why you are so hostile...  This is just a side project... no need to get all in a hissy fit.  It would have literally taken you less than 1 minute to copy and paste everything you did into the feature request site.  That site even allows you to login with your Github credentials.  Instead, you choose to go on a tangent about this and that...  Relax.... and just carry on man.  It's all good.

**Comment by bitshiftnetau** [comment]
Whatever dude, I've taken time out of my day to try and approach your project and after a few goes at it your crew have done nothing but waste my time and be snarky fucks. Have a good one.

**Comment by HalianElf** [comment]
I'm sorry I'm so unhelpful for telling you the thing you wanted.
