### ISSUE TITLE
Organizr top bar covers iFrame content in browsers on iOS platform.

### ISSUE THREAD

**Issue by salsabeard** [causefx/Organizr#1781]
###### Operating System: Docker Container running on Synology Diskstation
<hr>

##### Problem Description:
When opening iFrame content in a browser on iOS (tested on iPhone 11 Pro with Safari and Chrome running iOS 15.3), the top bar of Organizr is rendered over top of the content of the iFrame.  It almost seems that the anchor point of the div for the menu bar is in the same spot as the anchor point of the content div.

<hr>

##### Reproduction Steps:
I've predominantly noticed this issue with iFrames of Sonarr and Radarr.  The option to add new content is in a burger menu that is presented in the top bar of these pages.  When rendering the page on the mobile browsers in portrait mode, the top bar of organizr will render on top of the content making it impossible to access the Sonarr/Radarr menu options

Interestingly enough, this same behavior manifests when tilting to landscape mode, but it manifests slightly differently.  In landscape, the overlay isn't as bad, and in safari, the organizr menu bar was shifting back to the side instead of the top.  In both browsers, you can actually access the underlying menus because they are slightly exposed.  Here's where it gets slightly more interesting.  While in landscape mode, you can also pinch to zoom out, and this seems to allow the rendering to correct itself.

<hr>

#### Errors on screen?  If so paste here:

```
I have not observed any specific errors generated.  
``
![sonarr_example](https://user-images.githubusercontent.com/8974123/148592797-9a5d0280-8e93-4d19-91c7-2f20ec73ba46.png)
`

**Comment by causefx** [comment]
is 15.3 beta?

**Comment by salsabeard** [comment]
I’m running the beta, yes.  But my wife’s phone does the same thing and she’s running the standard release.  To be totally honest, I can’t recall if this was ever working differently.

**Comment by causefx** [comment]
https://user-images.githubusercontent.com/16184466/148631175-78e551a4-5212-4aaa-b1c0-ab6962f970ce.MOV

I'm on 15.2 and this is my exp.

**Comment by danielhelmstedt** [comment]
I can attest to this, it has predated iOS15. Also for me the bottom of the iFrame overflows offscreen, possibly by the same amount.
I have sometimes been able to scroll the Organizr window independently of the iFrame, which allows me to uncover the iFrame's top bar. Not sure what causes the 2 scroll bars though, as it's not every use.

Does Organizr use padding: env(safe-area-inset-top) to account for the notch?

**Comment by cwilford** [comment]
I am having the same problem. On mobile it will make some apps nearly unusable because they have a bottom menu.

**Comment by issues-guy** [comment]
I am able to see the top of rendered i-frame pages, but as @cwilford pointed out, the bottom of the pages overflow beyond the bottom. I can alleviate this by rotating the phone to landscape mode or opening and closing a text input dialog

**Comment by cwilford** [comment]
Still having this issue.

**Comment by causefx** [comment]
this should be fixed now
