### ISSUE TITLE
Netdata doesn't load data on the homepage. Wrong API URL?

### ISSUE THREAD

**Issue by Cookie-Monster-Coder** [causefx/Organizr#1782]
###### Operating System: Ubuntu
<hr>

##### Problem Description:
Looking at inspect elements the homepage tries to load "https://domain.com/api/v2/homepage/netdata/data" but it get sent an "404 Not Found" error. Looking at the 404 error response it states "File does not exist, or is not accessible: /usr/share/netdata/web/data"

When you remove ```/data``` from ```https://domain.com/api/v2/homepage/netdata/data``` it seems to be on the correct api page.

<hr>

##### Reproduction Steps:
1) Enable Netdata
2) Go to hopepage

<hr>

#### Errors on screen?  If so paste here:

```
File does not exist, or is not accessible: /usr/share/netdata/web/data
```

**Comment by causefx** [comment]
if i remember correctly this was an issue with the reverse proxy...

**Comment by causefx** [comment]
another user that had that issue said this:

> so just to close the loop on this, looks like there was some old configuration in the site-confs file, once I updated it everything started working :/

**Comment by Cookie-Monster-Coder** [comment]
In Organizr I am using 127.0.0.1:19999 as the url so it's not even going through nginx.
