### ISSUE TITLE
Unable to transfer a certificate

### ISSUE THREAD

**Issue by SebastienRiv** [causefx/Organizr#1783]
###### Operating System: FreeBSD / TrueNAS Core
<hr>

##### Problem Description:

Hello, I have a problem with the certificate transfer. When I try to place a certificate in the provided parameter area it tells me that there has been a save error moreover what type of certificate is supported by Organizr
<hr>

##### Reproduction Steps:

System Setting => Main => Certificate => Forward Certificate
<hr>

#### Errors on screen?  If so paste here:

```
Error Saving file...
```

**Comment by causefx** [comment]
should be a pem file

**Comment by causefx** [comment]
yeah, pem
![image](https://user-images.githubusercontent.com/16184466/149677656-b52c8a7c-88a9-4a7d-9c01-ec1a4755d8be.png)

**Comment by SebastienRiv** [comment]
Thanks I will try it tomorrow

**Comment by SebastienRiv** [comment]
<img width="367" alt="ERROR" src="https://user-images.githubusercontent.com/46841731/149713004-04b20e5a-12d1-4f0f-8108-93fbeee9b2c2.png">
It doesn't work, I still get the error.

**Comment by causefx** [comment]
the file has combined into a .pem file

**Comment by SebastienRiv** [comment]
Thank you very much, it works now, but I can't connect with https

**Comment by HalianElf** [comment]
I think you're misunderstanding what that's for. That's used for using untrusted certs for the Organizr homepage/SSO/ect connections (so you don't have to disable the cert checking), not the make your site run on SSL.

**Comment by SebastienRiv** [comment]
Oh ok thanks for your help
