### ISSUE TITLE
WAN url needed in sonarr/lidarr/radarr

### ISSUE THREAD

**Issue by Pinezerka** [causefx/Organizr#1784]
###### Operating System: Docker
<hr>

##### Problem Description:

![ss](https://cdn.discordapp.com/attachments/374662006701293569/932887863828295700/unknown.png)
so this links to my docker network _http://sonarr:8989/series/ozark_ any way we can make it iframe using wan url ?

**Comment by jessehickman** [comment]
It doesn't currently use the Settings > Tab Editor > Tabs settings. It uses the first URL in the Multiple URL's setting in Settings > Tab Editor > Homepage Items > Sonarr. I assume your docker network is the first URL listed there?

**Comment by jessehickman** [comment]
I have added a pull request that will allow users to select which URL they want to use for the icon click in https://github.com/causefx/Organizr/pull/1793. This will continue to open it in a new window versus iframe until a reliable way is found to target the correct tab.

**Comment by jessehickman** [comment]
I have also added a new pull request https://github.com/causefx/Organizr/pull/1796 that allows the user to select an existing tab to load inside of versus loading in a new window.

**Comment by causefx** [comment]
this was added by @jessehickman
