### ISSUE TITLE
Rtorrent in Combined Downloader has inappropriate entries

### ISSUE THREAD

**Issue by ronoray** [causefx/Organizr#1785]
###### Operating System: Windows 10
<hr>

##### Problem Description:
The rtorrent in Combined Downloader in the Homepage is continuously showing 3 files that are always seeding though completed. Whereas in that downloader there are more than 300 files seeding and completed. The necessary screenshots are attached with the issue.

![2022-01-16 (2)](https://user-images.githubusercontent.com/47646056/149999356-c1c56aa1-1a8e-47ed-9af6-4ed6e5f7ca3c.png)
![2022-01-18 (3)_LI](https://user-images.githubusercontent.com/47646056/149999359-6bc4cffb-29ea-4054-9c5c-69a1e93ccffe.jpg)
![2022-01-18 (5)](https://user-images.githubusercontent.com/47646056/149999363-13c8a539-b038-49be-8f1e-c88c063c6a47.png)
>

<hr>

##### Reproduction Steps:

<hr>

#### Errors on screen?  If so paste here:

```

```

**Comment by ronoray** [comment]
There are no errors on the homescreen. It just shows 3 torrents seeding.

**Comment by ronoray** [comment]
The issue is yet to be resolved; if only someone can have a look at it.

**Comment by causefx** [comment]
will check on this tomorrow.

**Comment by causefx** [comment]
checked on this, not sure how that is happening on your end.  the `connectionState` is leech on your end but rTorrent is either saying it is completed...??? so weird..

**Comment by causefx** [comment]
if you are on dev, you can try the latest commit.

**Comment by causefx** [comment]
closed due to no response
