### ISSUE TITLE
LDAP user with email address field set recieves 400 error on login

### ISSUE THREAD

**Issue by rdragonz** [causefx/Organizr#1786]
###### Operating System: Ubuntu 20.04
<hr>

##### Problem Description:

If the email address field is set in the AD user properties of an account accessible through LDAP, the user will receive a "400 Bad Request" error with reason "Request Header Or Cookie Too Large". Removing the email from the user and then clearing cookies in your browser will allow you to log in. I also noticed that a cookie larger than 2k gets set, and removing just that cookie will allow the user to log in. See screenshot for cookie details
![image](https://user-images.githubusercontent.com/57777173/150083066-92a0f302-975c-43f1-850f-831510d0884d.png)

No errors are output in the nginx logs.
<hr>

##### Reproduction Steps:

1. Set up an Organizr instance with Authentication Type "Organizr + Backend" with the backend configured for LDAP running through Active Directory.
2. Create a new user in AD
3. Set the email field under the user's properties page
4. Log in to Organizr instance and notice that a 400 error is displayed
<hr>

#### Errors on screen?  If so paste here:

```
400 Bad Request
Request Header Or Cookie Too Large
nginx/1.18.0 (Ubuntu)
```

**Comment by causefx** [comment]
are you logging in via a proxied organizr?

**Comment by causefx** [comment]
also is this a docker install or native?

**Comment by rdragonz** [comment]
This is a native install. I installed per the native install instructions available in the documentation, and it is not currently running via a proxy.

**Comment by causefx** [comment]
you need to increase the header size in nginx

**Comment by causefx** [comment]
closed due to no response
