### ISSUE TITLE
Overseerr Requests Show as Requested by "null"

### ISSUE THREAD

**Issue by dbowles1975** [causefx/Organizr#1787]
Organizr Version: V 2.1.1140
Branch: Master/Develop
WebServer: Nginx
Operating System: Windows 10 Pro

**Problem Description:**
Overseerr Requests Show as Requested by "null"

**Reproduction Steps:**
Use Overseerr as homepage item and request through Overseerr in Organizr.

Image showing issue here: https://imgur.com/a/o0peOMl

**Comment by NOnooSS** [comment]
Hello , same issue for me too. Any update ? [https://i.imgur.com/YFcHLsx.png](https://i.imgur.com/YFcHLsx.png)

**Comment by causefx** [comment]
lemme test today

**Comment by causefx** [comment]
can either of you run this url in your browser:

```
http://organizr-url/api/v2/homepage/overseerr/requests
```

**Comment by dbowles1975** [comment]
> ```
> http://organizr-url/api/v2/homepage/overseerr/requests
> ```

No, I just created a co-admin user in Organizr and I login with that user instead of admin. Requests show correctly.

**Comment by dbowles1975** [comment]
> Hello , same issue for me too. Any update ? https://i.imgur.com/YFcHLsx.png

No, I just created a co-admin user in Organizr and I login with that user instead of admin. Requests show correctly.

**Comment by causefx** [comment]
so admin was broken and co-admin worked fine?

**Comment by dbowles1975** [comment]
> http://organizr-url/api/v2/homepage/overseerr/requests

Yeah, so it looks like there's no "user" field being populated for the "userAlias" of the admin account.

**Comment by dbowles1975** [comment]
> so admin was broken and co-admin worked fine?

Correct. Co-admin shows a "user" while admin does not. 

` "user": null,
  "userAlias": "Person's Name",`

**Comment by slimshizn** [comment]
Noticed this isn't working for 'guest' either. Any update to this? Thank you.

**Comment by causefx** [comment]
it says null for guest?

**Comment by slimshizn** [comment]
Yes and on stripe the error is 
```
resource_missing - line_items[0][price_data][product]

We could not find the product object you referenced in the product attribute. Please check that the product object exist.

If you need to, you can also list product objects inline by using the product_data attribute. See our guide on migrating to prices for more details.
Was this useful?
```

**Comment by slimshizn** [comment]
Got it working, was using the product API and not the product ID. My mistake.

**Comment by causefx** [comment]
ill check this out today or tomorrow. I will get some people to request some stuff.

**Comment by dbowles1975** [comment]
> ill check this out today or tomorrow. I will get some people to request some stuff.

Any luck figuring this one out? It seems to be showing null for all users except my co-admin account.

**Comment by slimshizn** [comment]
Are you using the product ID?

**Comment by dbowles1975** [comment]
> Are you using the product ID?

I'm not sure what you're referring to.

**Comment by causefx** [comment]
Can you all paste or PM me the json details for your homepage item?

**Comment by dbowles1975** [comment]
You can download it here: [Organizr - Overseer JSON](http://davebowles.asuscomm.com:8887/JSON.txt)

**Comment by causefx** [comment]
perfect and now can you goto homepage settings for overseerr and click copy json settings there too plz

**Comment by dbowles1975** [comment]
> perfect and now can you goto homepage settings for overseerr and click copy json settings there too plz

I'm not sure what you're asking. Can you give me an API URL so I can make sure I send you the right thing?

**Comment by causefx** [comment]
click this button please:
![image](https://user-images.githubusercontent.com/16184466/164917030-748d0e1b-7d93-4a0b-a1be-486da38def09.png)

**Comment by dbowles1975** [comment]
[JSON2.txt](https://github.com/causefx/Organizr/files/8548107/JSON2.txt)

Attached.

**Comment by causefx** [comment]
Super weird...  clicking on a request on the homepage so it brings up the metadata info and poster, does it say null for username there too?

**Comment by dbowles1975** [comment]
> Super weird... clicking on a request on the homepage so it brings up the metadata info and poster, does it say null for username there too?

Yeah, it does. The only time it doesn't show null on the homepage is if I am logged into Organizr as co-admin. I created a local account in Overseerr with the same credentials which may be why those requests show up correctly. All requests show correctly directly through Overseerr.

**Comment by causefx** [comment]
I'm not sure what is wrong but I can't replicate this issue on any of my test instances.  I will keep trying.

**Comment by dbowles1975** [comment]
> I'm not sure what is wrong but I can't replicate this issue on any of my test instances. I will keep trying.

I don't know if this helps but I completely uninstalled everything and reinstalled from scratch and the issue persists.

**Comment by causefx** [comment]
i think i will change the logic in the js file.

**Comment by dbowles1975** [comment]
> 

Okay... so manually adding display names in Overseerr seems to have fixed this issue for me completely. It appears that when Overseerr imports Plex users it does not populate the display name which I assume is the user alias field Organizr uses to tag the requests on the home page. 

I appreciate the help with this.
