### ISSUE TITLE
Errors in Log: UnauthorizedRunning cron job...

### ISSUE THREAD

**Issue by Nyurael** [causefx/Organizr#1789]
###### Operating System: Debian 11.2
<hr>

##### Problem Description:
Errors in Log after Container is started.

##### Reproduction Steps:
Start Docker-Container

<hr>

#### Errors on screen?  If so paste here:
Log:

Linux organizr 5.10.92-v7l+ #1514 SMP Mon Jan 17 17:38:03 GMT 2022 armv7l GNU/Linux
Time Zone: Europe/Berlin
[cont-init.d] 50-debug: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
Running cron job...
UnauthorizedRunning cron job...
UnauthorizedRunning cron job...
UnauthorizedRunning cron job...

**Comment by causefx** [comment]
Have you gone through the setup wizard yet?

**Comment by Nyurael** [comment]
THX, that was the reason.
After the setup wizard it works.

2022-01-27T10:06:00.743202295Z Running cron job...
2022-01-27T10:07:00.744275500Z Running cron job...
2022-01-27T10:08:00.751765126Z Running cron job...
