### ISSUE TITLE
Organizr having trouble telling whether to use `Tab URL`, or `Tab Local URL`

### ISSUE THREAD

**Issue by flatline-studios** [causefx/Organizr#1790]
###### Operating System: Windows
<hr>

##### Problem Description:
I have tabs setup with `Tab URL` and `Tab Local URL`, and am using a Tailscale VPN (Wireguard) to access my remote server.

The problem is that it's loading the local URL, rather than the remote URL.

I get no errors in the console, or anywhere else I can see, the IFRAMEs just fail to load.

<hr>

##### Reproduction Steps:
It's tricky, as my network setup is quite complicated. I also use CloudFlare's DNS+WARP VPN, but have added my tailscale search domain and internal DNS server to its split DNS.

<hr>

#### Errors on screen?  If so paste here:

```

```

<hr>

#### Additional notes:
I can simply remove the `Tab Local URL`, but this machine moves around quite a lot, and when I'm local to the server, I don't really want it routing files through my VPN network, as it's adding unnecessary bandwidth.

How is this detection implemented? I use two different TLD's (`.vpn` for remote, `.local` for, well, local), so it would be handy if I could just indicate which TLD is which, and have organizr check the URL the requests are made to, but I digress.

Are there some kind of troubleshooting checks I can perform?

Thanks.

**Comment by flatline-studios** [comment]
Thinking about it, this could be solved simply if I was able to define networks (in CIDR notation) that are deemed `local` for incoming requests... But I can't find anywhere that allows this in the settings?

**Comment by HalianElf** [comment]
You can, Settings> Main > Login > Override Local IP or Subnet... All RFC1918 space is already considered local so you should only fill in public IPs there if needed

**Comment by flatline-studios** [comment]
I see now. I used the:

Settings -> System Settings -> Main -> Login -> Override Local IP or Subnet

And set it to:

`192.168.0.1-192.168.1.255`

Which relates to my two local subnets, and Organizr no longer seems to be getting confused with my `100.0.0.0/8` Tailscale generated IP addresses.

I'm not near to the server at the moment to test if it works completely, but will check again next time I'm on the same network. :)

**Comment by HalianElf** [comment]
That range is already included in the local ranges by default ([normal-functions.php#L524](https://github.com/causefx/Organizr/blob/v2-master/api/functions/normal-functions.php#L524)). 100.0.0.0/8 isn't so that doesn't make sense.

**Comment by flatline-studios** [comment]
It might be being routed through another classes range (probably 10.0.0.0/8), but I can't actually check at the moment to confirm.

But putting in the override for my actual local network, rather than the blanket private IP ranges seems to have resolved it for now. 😄

**Comment by causefx** [comment]
sweet - thanks!
