### ISSUE TITLE
Feature Request: Tautulli | Multiple Instances on Homepage

### ISSUE THREAD

**Issue by jjjonesjr33** [causefx/Organizr#1791]
###### Operating System: Ubuntu
<hr>

##### Problem Description:
Unable to add multiple instances of Tautilli to the homepage. 

<hr>

##### Reproduction Steps:

Tested with using IP, Hostname, HTTP, and HTTPS versions and was unable to get more than one to work.
![image](https://user-images.githubusercontent.com/29973406/153121225-d9e70bf4-ad69-4c0b-bf87-f307087c7ce1.png)
<hr>

#### Errors on screen?  If so paste here:

```
N/A
```

**Comment by HalianElf** [comment]
This isn't really a bug as much as it needs a feature request. How to make it take multiple needs to be worked out. The field takes multiple for the socks and SSO functions (which can do multiple)

**Comment by jjjonesjr33** [comment]
Ahh, that makes more sense then. For it to have the option to add multiple in that field lead me to believe it would work for multiple. Maybe a general notice on the Tautilli tab or an under the Multiple URL help button might be needed as a warning until that is in place.

**Comment by causefx** [comment]
lemme try this out tomorrow. i'll try and get to it before the soccer game lol

**Comment by jjjonesjr33** [comment]
> lemme try this out tomorrow. i'll try and get to it before the soccer game lol

Awesome 👍🏻 Many thanks 😄

**Comment by causefx** [comment]
for now, can you create this request on https://vote.organizr.app

**Comment by causefx** [comment]
hopefully this was create on feature request side :)
