### ISSUE TITLE
iCal widget on homepage does not show recurring events

### ISSUE THREAD

**Issue by Konsonanz** [causefx/Organizr#1792]
###### Operating System: Ubuntu 22.04 running docker: docker.io	20.10.12-0ubuntu2
<hr>

##### Problem Description:

I connected the iCal widget to a public calendar on my local nextcloud instance (23.0.1) containing non-recurring and recurring events. Only the non-recurring events are shown.
<hr>

##### Reproduction Steps:

Setup a public calendar (reported problem occured with nextcloud calendar function) with non-recurring and recurring events, connect the iCal widget and see that recurring events are not displayed in the widget.

My test calendar with the problematic behaviour produces the following .ics file:
```
BEGIN:VCALENDAR
VERSION:2.0
CALSCALE:GREGORIAN
PRODID:-//SabreDAV//SabreDAV//EN
X-WR-CALNAME:Test calendar (xxx)
X-APPLE-CALENDAR-COLOR:#D6B461
REFRESH-INTERVAL;VALUE=DURATION:PT4H
X-PUBLISHED-TTL:PT4H
BEGIN:VTIMEZONE
TZID:Europe/Berlin
BEGIN:DAYLIGHT
TZOFFSETFROM:+0100
TZOFFSETTO:+0200
TZNAME:CEST
DTSTART:19700329T020000
RRULE:FREQ=YEARLY;BYMONTH=3;BYDAY=-1SU
END:DAYLIGHT
BEGIN:STANDARD
TZOFFSETFROM:+0200
TZOFFSETTO:+0100
TZNAME:CET
DTSTART:19701025T030000
RRULE:FREQ=YEARLY;BYMONTH=10;BYDAY=-1SU
END:STANDARD
END:VTIMEZONE
BEGIN:VEVENT
CREATED:20220209T175502Z
DTSTAMP:20220209T175641Z
LAST-MODIFIED:20220209T175641Z
SEQUENCE:4
UID:89c5fad2-a45b-48b5-b706-6e6170b8b344
DTSTART;TZID=Europe/Berlin:20220210T100000
DTEND;TZID=Europe/Berlin:20220210T110000
STATUS:CONFIRMED
SUMMARY:Not recurring
END:VEVENT
BEGIN:VEVENT
CREATED:20220209T175655Z
DTSTAMP:20220209T175722Z
LAST-MODIFIED:20220209T175722Z
SEQUENCE:3
UID:71f86269-7252-4857-85f7-800c9b2eec38
DTSTART;TZID=Europe/Berlin:20220210T100000
DTEND;TZID=Europe/Berlin:20220210T110000
STATUS:CONFIRMED
SUMMARY:Recurring
RRULE:FREQ=YEARLY;BYMONTH=2
END:VEVENT
END:VCALENDAR
```
<hr>

#### Errors on screen?  If so paste here:
None.

**Comment by HalianElf** [comment]
I have a calendar with a reoccurring event. It does show up, however not on the right date (looks like it just does the current week's Tuesday for a reoccurring that's supposed to be 4th Tuesday of the month). So it looks like it's actually a bug with the way they're parsed.

Org calendar:
![image](https://user-images.githubusercontent.com/28244771/153267510-f173adf8-58c1-48c6-9ec5-66a365f4f9a4.png)

Actual calendar: 
![image](https://user-images.githubusercontent.com/28244771/153267680-5a9277ed-15a6-4811-ae61-9312c35fb371.png)
(link: https://calendar.google.com/calendar/ical/gi3sakm5ol1f94iic6ejmth1hk%40group.calendar.google.com/public/basic.ics)

**Comment by causefx** [comment]
will check this out too

**Comment by causefx** [comment]
just about done with this, ran into some issues but hope to get it solved soon

**Comment by causefx** [comment]
fixed in dev

**Comment by Konsonanz** [comment]
@causefx Thanks for the quick fix!
Daily, weekly and monthly re-occuring events now display correctly for me, but yearly events do not. Rather they are always displayed for today.

See this nextcloud calendar:
![nc](https://user-images.githubusercontent.com/46794176/153758584-014b689b-dd7f-4b04-a572-5016c7009d3b.png)

Resulting in this iCal widget display:
![org](https://user-images.githubusercontent.com/46794176/153758589-fadf6626-f989-48be-8610-7381e881686a.png)

.ics file for test calendar:
```
BEGIN:VCALENDAR
VERSION:2.0
CALSCALE:GREGORIAN
PRODID:-//SabreDAV//SabreDAV//EN
X-WR-CALNAME:Test calendar (xxx)
X-APPLE-CALENDAR-COLOR:#D6B461
REFRESH-INTERVAL;VALUE=DURATION:PT4H
X-PUBLISHED-TTL:PT4H
BEGIN:VTIMEZONE
TZID:Europe/Berlin
BEGIN:DAYLIGHT
TZOFFSETFROM:+0100
TZOFFSETTO:+0200
TZNAME:CEST
DTSTART:19700329T020000
RRULE:FREQ=YEARLY;BYMONTH=3;BYDAY=-1SU
END:DAYLIGHT
BEGIN:STANDARD
TZOFFSETFROM:+0200
TZOFFSETTO:+0100
TZNAME:CET
DTSTART:19701025T030000
RRULE:FREQ=YEARLY;BYMONTH=10;BYDAY=-1SU
END:STANDARD
END:VTIMEZONE
BEGIN:VEVENT
CREATED:20220213T143338Z
DTSTAMP:20220213T143421Z
LAST-MODIFIED:20220213T143421Z
SEQUENCE:2
UID:3a3b3b00-0b49-4a09-8720-a1fa0ff563a3
DTSTART;TZID=Europe/Berlin:20220213T200000
DTEND;TZID=Europe/Berlin:20220213T210000
STATUS:CONFIRMED
SUMMARY:Today weekly occurence
RRULE:FREQ=WEEKLY;BYDAY=SU
END:VEVENT
BEGIN:VEVENT
CREATED:20220213T143623Z
DTSTAMP:20220213T143643Z
LAST-MODIFIED:20220213T143643Z
SEQUENCE:2
UID:0dc82cc0-28f0-4c4a-bf6e-a9081bd8872c
DTSTART;VALUE=DATE:20220214
DTEND;VALUE=DATE:20220215
STATUS:CONFIRMED
SUMMARY:Tomorow monthly occurence
RRULE:FREQ=MONTHLY;BYMONTHDAY=14
END:VEVENT
BEGIN:VEVENT
CREATED:20220213T143648Z
DTSTAMP:20220213T143711Z
LAST-MODIFIED:20220213T143711Z
SEQUENCE:2
UID:2ba1f885-8027-4e1c-aa81-b2b122b290f2
DTSTART;VALUE=DATE:20220215
DTEND;VALUE=DATE:20220216
STATUS:CONFIRMED
SUMMARY:After tomorrow yearly occurence
RRULE:FREQ=YEARLY;BYMONTH=2
END:VEVENT
BEGIN:VEVENT
CREATED:20220213T143908Z
DTSTAMP:20220213T143938Z
LAST-MODIFIED:20220213T143938Z
SEQUENCE:2
UID:f817381d-9454-467e-9e45-5813daa79363
DTSTART;VALUE=DATE:20220217
DTEND;VALUE=DATE:20220218
STATUS:CONFIRMED
SUMMARY:Thursday yearly occurence
RRULE:FREQ=YEARLY;BYMONTH=2
END:VEVENT
END:VCALENDAR
```

**Comment by causefx** [comment]
let me know if this commit fixes it for you.

**Comment by Konsonanz** [comment]
Tested again, now everythings working as expected.
Thanks for the quick patch, again!
