### ISSUE TITLE
Feature Request: Open bookmarks in new tab?

### ISSUE THREAD

**Issue by kpatdev** [causefx/Organizr#1794]
###### Operating System: Ubuntu
<hr>

##### Problem Description:
When opening a bookmark, it opens in current tab. Would love to be able to specify if the bookmarks open in current tab or new tab (to quickly open multiple bookmarks).

**Comment by HalianElf** [comment]
https://feature.organizr.app/posts/113/bookmark-opening-option

**Comment by Antalis** [comment]
Travis Patton · Apr 2022
The above snippet doesn't work anymore
