### ISSUE TITLE
Calendar failure after adding specific ical link

### ISSUE THREAD

**Issue by listy-bit** [causefx/Organizr#1797]
###### Operating System: Ubuntu 20.04
<hr>

##### Problem Description:
Calendar fails to load when a specific ics link is added. No items from any ics or Sonarr load. Removing that ics link restores all calendar function.
<hr>

##### Reproduction Steps:
Add https://www.wrc.com/?proxy=daten/WRC.ics to the ical list.
<hr>

**Comment by causefx** [comment]
fixed now:
![image](https://user-images.githubusercontent.com/16184466/154613231-ed8cd05a-0184-4b94-b8b0-f348f861778f.png)
