### ISSUE TITLE
Tautulli homepage item settings can't be edited when server is unreachable

### ISSUE THREAD

**Issue by bdonohoe** [causefx/Organizr#1798]
###### Operating System: *nix / official docker
<hr>

##### Problem Description:
If the Tautulli homepage item is configured to point to point to a server that's not responding, you can't open the settings to change it to point to something else. It throws cURL error 7 and refuses to open the settings. It looks like it's trying to hit the server to get the list of libraries to populate the settings, but when the server doesn't respond, it can't open the settings at all.

<hr>

##### Reproduction Steps:
1. Edit Homepage Items > Tautulli and make it point to a non-existent address (or just take your already configured Tautulli server offline).
2. Attempt to edit Homepage Items > Tautulli again.

<hr>

#### Errors on screen?  If so paste here:

```
Tautulli Homepage Error - Unable to get list of libraries: cURL error 7: Failed to connect to [server] port 8181 after 16ms: Connection refused
```

**Comment by bdonohoe** [comment]
Oh, I also had some libraries configured to be excluded from library and viewing stats. Not sure if the failure is due to validating those library names or if it's prefetching all the libraries for the auto-complete on those fields.

**Comment by causefx** [comment]
fixed in dev
