### ISSUE TITLE
Option for show login if nothing enabled for guests

### ISSUE THREAD

**Issue by ImperialXT** [causefx/Organizr#18]
It would be nice that if there are no tabs enabled for guest access to just take people straight to the login page.

Might also be worth having the login/logout options under the user portrait menu in the top right hand corner instead, as it's a bit odd at least from my perspective to have to go to the small option in the left hand bar that's initially hidden etc.

**Comment by rix1337** [comment]
And also disabling gravatar for guests.

**Comment by lgromb** [comment]
I second this.

**Comment by causefx** [comment]
fair points, I won't be able to disable gravatar if I put the login under the top bar user menu.  I'll leave both options for login and log out.

**Comment by rix1337** [comment]
that's reasonable. Leave it in, then

**Comment by lgromb** [comment]
What about the first request then? ⁣

Le 4 janv. 2017 16:59, à 16:59, RiX <notifications@github.com> a écrit:

**Comment by causefx** [comment]
I will work on that as well.
