### ISSUE TITLE
Jackett connection is missing connection testing

### ISSUE THREAD

**Issue by pentago** [causefx/Organizr#1800]
Jackett connection is missing connection testing while a bunch (if not all) other like Sonarrm Radarr, Emby has it.

I entered what I think are the correct connection parameters but my connection isn't working and I can't debug it.

Can we get connection testing for Jackett as well?

For example, Sonarr connection testing: https://i.imgur.com/UrnjsD9.png
Jackett: https://i.imgur.com/MAL6JFG.png

**Comment by causefx** [comment]
i will try and add this soon, i need to reinstall jackett to test

**Comment by causefx** [comment]
completed in dev
