### ISSUE TITLE
Accessing Transmission through iFrame - v2-develop

### ISSUE THREAD

**Issue by JSKershaw** [causefx/Organizr#1803]
###### Operating System: Docker
<hr>

##### Problem Description:
When I go to Transmission within an i-Frame I get this error:
409: Conflict
Your request had an invalid session-id header.

This error was not present in the Master branch

<hr>

##### Reproduction Steps:
Tab Settings:
Tab URL: http://192.168.0.139:9091/transmission/web/
Type being used is iFrame

<hr>

#### Errors on screen?  If so paste here:

```
409: Conflict
Your request had an invalid session-id header.

To fix this, follow these steps:

When reading a response, get its X-Transmission-Session-Id header and remember it
Add the updated header to your outgoing requests
When you get this 409 error message, resend your request with the updated header
This requirement has been added to help prevent [CSRF](https://en.wikipedia.org/wiki/Cross-site_request_forgery) attacks.

X-Transmission-Session-Id: NArqlOoDI1Z3zYbbg51RYnmnIGpu67T5vIQB2OApIlcLPNH2
```
![screenshot-192 168 0 139_86-2022 03 04-21_53_22](https://user-images.githubusercontent.com/10111172/156865109-95b1fd6e-4550-41e6-9da4-e816d328afb1.jpg)

**Comment by JSKershaw** [comment]
Hmm...  I seem to have fixed it with a strange fix I just found:

I changed the Tab URL to: http://192.168.0.139:9091/transmission/web/#files

Very strange considering the v2-master branch didn't require this.

**Comment by cadavor** [comment]
Hi,
Just updated my Organizr to version 2.1.1680 (latest master) and since I get the same error on my Transmission tab (error 409).
I tried the solution above without success

**Comment by causefx** [comment]
can someone run org-domain/api/v2/launch in the browser url and paste the section on tabs.

**Comment by cadavor** [comment]
Mine :   
             {
                    "id": 3,
                    "order": 2,
                    "category_id": 1,
                    "name": "Transmission",
                    "url": "http://192.168.0.202:9091/transmission/web",
                    "url_local": "",
                    "default": 0,
                    "enabled": 1,
                    "group_id": 0,
                    "image": "plugins/images/tabs/transmission.png",
                    "type": 1,
                    "splash": null,
                    "ping": 1,
                    "ping_url": "192.168.0.202:9091",
                    "timeout": "null",
                    "timeout_ms": 0,
                    "preload": 1,
                    "access_url": "http://192.168.0.202:9091/transmission/web"
                },

It seems that the last "/" is missing in the URL
The correct and working URL is "http://192.168.0.202:9091/transmission/web/" as configured

![test](https://user-images.githubusercontent.com/910119/156889190-00490dd7-d997-47f9-8fb6-666c2a88b1b9.png)

**Comment by FieldofClay** [comment]
This is not just affecting Transmission. It looks like Organizr is now always removing the trailing / from the tab URL.

**Comment by HalianElf** [comment]
Yes, and it's fixed in the develop branch

**Comment by cadavor** [comment]
> Yes, and it's fixed in the develop branch

Thank you, re-save the tab config and works well now...
