### ISSUE TITLE
HTPC-Manager not showing after update to 2.1.1690

### ISSUE THREAD

**Issue by phairplay** [causefx/Organizr#1805]
###### Operating System: Windows
<hr>

##### Problem Description:
HTPC-Manager page not loading after upgrading from 2.1.1140 to 2.1.1690

<hr>

##### Reproduction Steps:
upgraded noticed it disappeared, installed a backup copy and it returned. unsure of why this would happen

 

<hr>

#### Errors on screen?  If so paste here:

```
No error appears, just a blank Iframe screen
```

**Comment by causefx** [comment]
what is the tab url you have for that item?

**Comment by phairplay** [comment]
https://xxxx.com/stats
works on the 2.1.1140

**Comment by causefx** [comment]
is HTPC docker container?  if so, which image so i can test please.

**Comment by phairplay** [comment]
No I'm running in python 2 on windows 10

https://github.com/Hellowlol/HTPC-Manager
I've never updated as it's always works fine for my need.
monitor my system with the ability to run custom scripts

**Comment by phairplay** [comment]
Sorry I can’t give you more information. There isn’t any errors
I just know of any alternative to htpc manager

**Comment by causefx** [comment]
can you me on discord or email me the URL so i can test on my end?  causefx at me dot com

**Comment by phairplay** [comment]
Sorry I appreciate the help, is there anyway 
As I’m conscious that htpc provides a lot of private information, I hope you can understand.

**Comment by causefx** [comment]
i just installed it...   and loaded the iframe...

![image](https://user-images.githubusercontent.com/16184466/157295438-72239d64-806b-4e09-b423-1708e67dcb3b.png)

**Comment by causefx** [comment]
can you add a username and password to it?  just so i can see the login page at least?

**Comment by phairplay** [comment]
hmmm

could my nginx have something to do with it.

```
    location /htpc {
        auth_request /auth-0;
        proxy_pass http://127.0.0.1:8085;
        add_header X-Frame-Options "SAMEORIGIN";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
```
it just odd everything is fine of the previous version

**Comment by phairplay** [comment]
Hi, just dropped you an email

**Comment by causefx** [comment]
I got it thanks, lastly you will need to comment out this line from proxy. `auth_request /auth-0;` as i cannot access it :)

**Comment by causefx** [comment]
might as well comment this out too `add_header X-Frame-Options "SAMEORIGIN";` just so i can test iframe too

**Comment by phairplay** [comment]
sorry try now

**Comment by causefx** [comment]
![image](https://user-images.githubusercontent.com/16184466/157299313-0713c776-6d4f-42b9-a384-3c40130b794d.png)
Very odd - worked on my end again.

**Comment by causefx** [comment]
i was testing locally - when i checked via https proxy i got an error...

```
jquery-2.2.4.min.js:3 
        
       Mixed Content: The page at 'https://organizr.dev/#This-is-a-test' was loaded over HTTPS, but requested an insecure frame 'http://yoursite.com/htpc/auth/login'. This request has been blocked; the content must be served over HTTPS.
```

**Comment by phairplay** [comment]
What does this mean?

**Comment by causefx** [comment]
it points to an issue with the proxy itself.  Let me try and proxy my test instance.

**Comment by causefx** [comment]
Proxy worked on mine... try and add this url to your organizr: `https://organizr.dev/htpc`

**Comment by phairplay** [comment]
Okay even stranger that works, but mine won’t

**Comment by causefx** [comment]
try adding this to your proxy:

```
proxy_redirect  http://  $scheme://;
```

**Comment by phairplay** [comment]
i added the above and also renamed the webdir which seem to have fixed it

thank you for taking the time to help me out,

**Comment by causefx** [comment]
no worries - glad its sorted.
