### ISSUE TITLE
Sonarr and Radarr calendar api's not using v3 version

### ISSUE THREAD

**Issue by PearsonFlyer** [causefx/Organizr#1807]
Organizr Version: V 2.1.1690
Branch: Master
WebServer: Nginx
Operating System: Windows 10
<hr>

##### Problem Description:
The calendar for Sonarr and Radarr on the home page of Organizr are blank. Both hits to /api/v2/homepage/radarr/calendar and /api/v2/homepage/sonarr/calendar show this result:

{
    "response": {
        "result": "success",
        "message": null,
        "data": null
    }
}

I believe this is because v1 api has been decommissioned from Radarr, and because I'm running an alpha v4 version of Sonarr, it has also been decommissioned from that version of Sonarr (and even v3 of Sonarr should be using the v3 api instead of the v1 api).

I looked through the code, and I couldn't find the spot where the URL is built to tell for sure, so I thought this might be the best way to validate whether this is true or not. The calendar used to work, which makes me think that it's because of the deprecation of the /api endpoint and the requirement to use the /api/v3 endpoint instead for both pieces of software.

<hr>

##### Reproduction Steps:
Install Radarr v4 or Sonarr v4, calendar is completely empty.

<hr>

#### Errors on screen?  If so paste here:
There are no errors on the screen, it's just not getting any results any longer.
```

```

**Comment by causefx** [comment]
organizr exclusively using v3 endpoint for the arrs. i will check on v4

**Comment by PearsonFlyer** [comment]
Thank you. I heard from some others using the same versions of Sonarr and Radarr that I am who are not experiencing this issue, so it sounds like it is not API related, after all. I'll close this, sorry for the false alarm.
