### ISSUE TITLE
option to disable items on homepage for None logged in  Users

### ISSUE THREAD

**Issue by andyrav** [causefx/Organizr#181]
Hi
Be great it you could add the Option to disable items on homepage for None logged in  Users

cheers

**Comment by causefx** [comment]
yes sir, that is planned for all of them, I just need to get all the integration working first.

**Comment by Cerothen** [comment]
Implemented in https://github.com/causefx/Organizr/commit/7795f4a2341e976e7ab36b5f8f36999389819d54
