### ISSUE TITLE
The option in the language setting is Chinese, but is still Chinese (Traditional ) after setting.

### ISSUE THREAD

**Issue by yaoshuangshl** [causefx/Organizr#1813]
The option in the language setting is Chinese, but is still Chinese (Traditional ) after setting.

**Comment by causefx** [comment]
fixed in dev.

**Comment by yaoshuangshl** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
