### ISSUE TITLE
Haven't been able to update since v2.1.1140

### ISSUE THREAD

**Issue by stayxnegative** [causefx/Organizr#1814]
###### Operating System: Windows
<hr>

##### Problem Description:
Haven't been able to update since v2.1.1140, it installs updates and refreshes and still shows v2.1.1140, no matter if I remove the image and container, redeploy the docker, or install update right in Organizr. 

<hr>

##### Reproduction Steps:

<hr>

#### Errors on screen?  If so paste here:

```

```

**Comment by HalianElf** [comment]
Check your docker logs. You probably have a git lock file that needs to be deleted

**Comment by causefx** [comment]
update @stayxnegative ?

**Comment by causefx** [comment]
closed due to no reply.
