### ISSUE TITLE
update available notification when no update is available

### ISSUE THREAD

**Issue by toxic0berliner** [causefx/Organizr#1815]
###### Operating System: docker image organizr/organizr
<hr>

##### Problem Description:
Using Firefox mobile on Android, but I believe also with Firefox on PC windows 10, I constantly get notified at the bottom of the page that an update is available, with 2 links to see differences or perform the update, but there is nothing to update.

Any way to disable this constant notification or insure it only shows when needed would be great.

I already am using watchtower so the docker image is updated daily if available.

It's been some time (months) that this happens with Firefox on Android, maybe I'm one of the few Firefox/android users or maybe it shows up because I'm on develop branch.

Thx in advance for any help.

**Comment by causefx** [comment]
If you are using our container and you are on the dev branch you may get that popup several times a day as I am constantly pushing updates to the dev branch.  The dev branch doesn't really use version numbers with each change it goes but the github commit hash.  If you like you can turn on auto-update in the settings and set it to the desired cron run time.  We do have a new docker image coming out soon that will fix this either way as the github project will be actually built with the container.

**Comment by toxic0berliner** [comment]
Hmm, seems not to be the only problem...
I've just switched back to the master branch running the image organizr/organizr with Firefox 99.0.1 and I get this : 
![github-issue-organizrpng](https://user-images.githubusercontent.com/10488124/166203581-b5060b72-97e1-45a0-a4a2-2d7a4975b7be.png)
It knows it's up to date and still notifies...
Couldn't find a way to turn off notifications alltogether as well, maybe I'm just not good enought, sorry :S
@causefx shall I open a new issue or you can reopen this one ?

**Comment by HalianElf** [comment]
Is there anything in your docker logs?

**Comment by toxic0berliner** [comment]
No, nothing in the docker logs.
Only this : 
```
grep: /etc/crontabs/root: Permission denied

./40-install: line 83: /etc/crontabs/root: Permission denied
```

So that might not help the hourly update Cron but nevertheless I still get this notification, both on Android and windows using Firefox

**Comment by causefx** [comment]
Please check the branch you are on thru the container env var.  Then check the branch listed at `/org-root/data/config/config.php`

**Comment by toxic0berliner** [comment]
Hmmm, I don't have such a file. I'm running Image 	organizr/organizr@sha256:9c648f33e6b0767eb3538d1013752053c80d2f599ee427db4bc73f0e0dfca8c4
Env var is correct on v2-master branch. Searching for a config.php file...

Note that I have a persistent volume on /config that I haven't touched for a while and was on v2-develop at some point a few months ago

**Comment by HalianElf** [comment]
`/org-root` was meant to be the path to your `/config/www/organizr` on the host.

**Comment by toxic0berliner** [comment]
/config/www/organizr/data/config/config.php was still on v2-develop I switched it to v2-master all fine now, thanks for the help!

**Comment by causefx** [comment]
that kinda confirms that the container isn't writing to that file huh kp. i'll check the script again.

**Comment by causefx** [comment]
fixed now
