### ISSUE TITLE
Chat Plugin - Add close/hide button

### ISSUE THREAD

**Issue by thorin8k** [causefx/Organizr#1816]
###### Operating System: docker
<hr>

##### Description:

It would be nice if the chat window has a close button or something to hide it. It's behaviour now its not very intuitive as i have to click on another tab to force it to hide.

<hr>

##### Reproduction Steps:

1. Activate chat plugin
2. Access chat window
3. There is no button to hide it
4. Clicking on 'Tab Close' button does nothing.

![image](https://user-images.githubusercontent.com/50626175/161742583-99438be2-f293-4952-bd85-c405ce2b092e.png)

<hr>

> Maybe allow the chat window to open as an oragnizr tab could be a workaround but i haven't found any way to do so.

**Comment by causefx** [comment]
fixed in dev
