### ISSUE TITLE
Errors on crontab

### ISSUE THREAD

**Issue by G4Zz0L1** [causefx/Organizr#1820]
###### Operating System: Arch Linux
<hr>

##### Problem Description:
Crontab has started to report this errors, I've set it up to email me directly by cron.
Same thing if I launch the script manually as the http user with

```bash
sudo -u http /bin/bash -c "/usr/bin/php /srv/http/organizr/cron.php"
```

I've updated directly from git (as I do always) but I don't remember the previous version I was at.
It started from the last pull,  I think I was like around the 2.1.1790 commits.

<hr>

##### Reproduction Steps:
Launch crontab as I've done above, or set crontab to run every minute (with a valid email for outputs) and wait.

<hr>

#### Errors on screen?  If so paste here:

```
PHP 8192:  Return type of Dibi\ResultIterator::current() should either be compatible with Iterator::current(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /srv/http/organizr/api/vendor/dibi/dibi/src/Dibi/ResultIterator.php on line 61
PHP 8192:  Return type of Dibi\ResultIterator::key() should either be compatible with Iterator::key(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /srv/http/organizr/api/vendor/dibi/dibi/src/Dibi/ResultIterator.php on line 51
PHP 8192:  Constant FILTER_SANITIZE_STRING is deprecated in /srv/http/organizr/api/functions/log-functions.php on line 215
PHP 8192:  strtolower(): Passing null to parameter #1 ($string) of type string is deprecated in /srv/http/organizr/api/functions/log-functions.php on line 224
```

**Comment by causefx** [comment]
thank you for this , what version of PHP you running?

**Comment by G4Zz0L1** [comment]
```
PHP 8.1.4 (cli) (built: Mar 16 2022 11:32:47) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.4, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.4, Copyright (c), by Zend Technologies
    with Xdebug v3.1.2, Copyright (c) 2002-2021, by Derick Rethans
```

**Comment by causefx** [comment]
i'll update a local copy i have and do some testing

**Comment by causefx** [comment]
Go ahead and update please....  let me know if it works.

**Comment by G4Zz0L1** [comment]
Yep, the errors are gone with the latest update.

Thanks for the fast fix, as always!

**Comment by causefx** [comment]
sweet! thanks!
