### ISSUE TITLE
Org Auth make vnc websocket not work

### ISSUE THREAD

**Issue by PilaScat** [causefx/Organizr#1825]
###### Operating System: Docker organizr/organizr
<hr>

##### Problem Description:
When using Auth with NPM, websocket on vnc/noVNC pages stops working
This only from 2.1.1840 (maybe)
<hr>

##### Reproduction Steps:
Make a proxy host for a vnc app (like krusader, jdownloader or mkvtoolnix), add auth and watch it not working, without auth it works
<hr>

#### Errors on screen?  If so paste here:
Not from organizr but from vnc:
```
Websocket error: 1006
```

**Comment by causefx** [comment]
I'm not sure how I would even fix on my end.  My solution would be turn off auth on the websocket location block.  But I would assume you are just using the tickbox to activate the websocket support... Try manually creating the location block for the WS.

**Comment by PilaScat** [comment]
Unfortunately I don't know how to do it
