### ISSUE TITLE
Passwords longer than 63 characters are not encrypted in the config

### ISSUE THREAD

**Issue by Gerben-Tx** [causefx/Organizr#1826]
###### Operating System: Ubuntu
<hr>

##### Problem Description:

Password longer than `63` characters are not encrypted in the config
<hr>

##### Reproduction Steps:

1. Open Deluge plugin and go to `Connection` tab
2. Choose a password of 64 chars
   ```
   aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
   ```
3. Press save icon (don't close settings screen)
4. Go to `Test Connection` tab and click `Test Connection` button
5. Go to `YOUR_ORGANIZR_URL/api/v2/config`
6. See that `delugePassword` is not encrypted

You can try again with a password that is `63` chars and you will notice it is encrypted fine.

Didn't test this with other passwords, but looking at the code i suspect this will happen for (at least) every settings option (using https://github.com/causefx/Organizr/blob/c2c0d131c33235f849ced2b3ebf6311de66c205f/api/functions/option-functions.php#L18)
<hr>

#### Errors on screen?  If so paste here:

No errors directly, but i had to debug the deluge php code to find out why the Deluge plugin wasn't working..

**Comment by causefx** [comment]
I see the issue, I'm trying to figure out why i hardcoded a true on length of 64....  65 should be fine

**Comment by causefx** [comment]
fixed in dev
