### ISSUE TITLE
2.1.1880  update loop

### ISSUE THREAD

**Issue by fireheadman** [causefx/Organizr#1828]
v2 master

##### Problem Description:
trying to apply 2.1.1880, it succeeds and will reload, then prompts that it wants to update again.... same version.
seems there are others on reddit experiencing this issue....

<hr>

##### Reproduction Steps:
apply update via UI, you will see..

<hr>

#### Errors on screen?  If so paste here:
There are no errors.
update loop
```

```

**Comment by stanthewizzard** [comment]
Same here

**Comment by causefx** [comment]
fixed, thanks guys!

**Comment by fireheadman** [comment]
Thanks. Works for me now
