### ISSUE TITLE
SABnzbd port problem

### ISSUE THREAD

**Issue by rudyvarner** [causefx/Organizr#183]
When trying to save the SABnzbd port it gets saved into the NZBget field and the following error appears on the homepage.

Warning: file_get_contents(http://127.0.0.1/api?mode=queue&output=json&apikey=35673f6577c51fdff7a30ef6badaf187): failed to open stream: HTTP request failed! HTTP/1.1 404 Not Found in C:\xampp\htdocs\functions.php on line 543

Warning: Invalid argument supplied for foreach() in C:\xampp\htdocs\functions.php on line 551

**Comment by causefx** [comment]
my bad, I will fix this tonight, for now, on URL put `http://127.0.0.1:PORTHERE`  that will make it work.
