### ISSUE TITLE
qBittorrent Not Hiding Completed Torrents

### ISSUE THREAD

**Issue by ghost** [causefx/Organizr#1834]
###### Operating System: Ubuntu Server 20.04
<hr>

##### Problem Description:

qBittorrent still shows completed torrents after choosing to hide them.
<hr>

##### Reproduction Steps:

Open qBittorrent in Homepage items
Enable Hide Completed
<hr>

No errors
![image](https://user-images.githubusercontent.com/64925440/167346771-f8375460-fec7-4dd9-a4ab-32677ced872e.png)

**Comment by ghost** [comment]
Nevermind, it seems to be showing errored torrents as completed which is weird.
Is it able to be fixed?

**Comment by causefx** [comment]
i will have to get a qbit instance i can test on.

**Comment by causefx** [comment]
Can you get me the output of `org/api/v2/homepage/qbittorrent/queue`

**Comment by ghost** [comment]
> Can you get me the output of `org/api/v2/homepage/qbittorrent/queue`

Sorry, I took so long
I deleted the errored torrents when troubleshooting so I had to manually make an errored torrent but it takes a while for qBittorrent to realize the files are actually missing.

Now I got it back to how it was before, how do I find what you linked?

**Comment by causefx** [comment]
on browser goto `http://your-org/api/v2/homepage/qbittorrent/queue`

**Comment by ghost** [comment]
I couldnt upload the .json so here is it on 0bin
https://0bin.net/paste/7YNAxDpT#iIP5QxQhxH8dtYa-Rl2JYsVyjGERafG3cfgmSLjlDau

**Comment by causefx** [comment]
i'm not able to access the file

**Comment by ghost** [comment]
https://pastebin.com/yzF1vAXp
Sorry, hopefully this works

**Comment by causefx** [comment]
new link is 404'd

**Comment by ghost** [comment]
Seriously?
I'll just use picoshare then
https://share.theinternet.ga/!L6pecRHan2/pasted-2022-05-16T010434.932Z.txt

**Comment by causefx** [comment]
perfect. thank you.

**Comment by causefx** [comment]
are any of the attached items completed and not hiding?

**Comment by ghost** [comment]
I really need to find a way to get notifications, sorry for the very late response
Im pretty sure most of the errors are because the torrent finished and I moved/deleted them manually.
