### ISSUE TITLE
Cannot customize the background of the login page

### ISSUE THREAD

**Issue by windtalkers9112** [causefx/Organizr#1837]
###### Operating System: Ubuntu
<hr>

##### Problem Description:
Under the setting custom login page, after opening the use random media wallpaper from media server button and entering RUL, the random login background image does not appear, and the plex movie poster always appears in the background. Tried many times and it doesn't work...

<hr>

##### Reproduction Steps:

1. Fill in the Login Wallpaper URL: https://api.xygeng.cn/Bing/
2. Turn on the Use Random Media Wallpaper From Media Server switch

<hr>

#### Errors on screen?  If so paste here:

```

```

**Comment by causefx** [comment]
Sorry i need to make those options more clear.  It's either one or the other.  If you want to use the bing link, turn off `Use Random Media Wallpaper From Media Server`
