### ISSUE TITLE
SSO Fallback for Komga

### ISSUE THREAD

**Issue by MVethana** [causefx/Organizr#1838]
###### Operating System: Windows 10
<hr>

##### Problem Description:
Komga SSO not compatible with Plex Backend only

<hr>

##### Reproduction Steps:
Komga SSO when authentication is set to Plex Backend only fails with php-requests/1.7 Password Bad credentials due to no password existing, enable plex backend only and SSO to komga fails

<hr>

#### Errors on screen?  If so paste here:
Screenshots and conversation available from discord here
https://discord.com/channels/374648602632388610/374662006701293569/976985278977835048

**Comment by HalianElf** [comment]
Are you using oAuth to login or the login form? It should work fine with login form with Plex Backend only.

**Comment by MVethana** [comment]
oauth no password and komga sso requires a password which is what is causing the issue

**Comment by HalianElf** [comment]
Right, you need to use the login form. oAuth isn't compatible with any SSO that doesn't use Plex tokens. So you either need to disable the oAuth login method and only use the login form or deal with not using SSO for Komga. This isn't a bug and is not fixable.

**Comment by MVethana** [comment]
When talking with @causefx on discord he mentioned he had thought of a workaround before utilizing a master password but just needed to figure out how he wanted to implement it. Since he mentioned it is something he wants to make compatible in the future the issue should be left open to track progress on the implementation

**Comment by HalianElf** [comment]
Ok I'll reopen it then. Sounds like what he's talking about is basically SSO fallback like we have for Ombi/Petio/Overseerr so not really true SSO.

Edited the title to reflect that but this should really go to Feature Requests.

**Comment by MVethana** [comment]
Komga SSO already has a fallback account. 

What we discussed was using the oauth as the username and a master password so that any komga users aren't all put into the same fallback account as a fix to the fact that oauth isn't compatible in komgas current implementation.

As an alternative Komga does support OAuth which could also be used

https://komga.org/installation/oauth2.html#advanced-configuration

**Comment by causefx** [comment]
added in dev
