### ISSUE TITLE
homepage.php & NZBGet

### ISSUE THREAD

**Issue by compil3** [causefx/Organizr#184]
Warning: file_get_contents(http://192.168.1.9/admin:gIO1IMGSx5fiRLvqIRlu/jsonrpc/listgroups): failed to open stream: HTTP request failed! HTTP/1.1 401 Unauthorized in /config/www/Dashboard/functions.php on line 473

Warning: Invalid argument supplied for foreach() in /config/www/Dashboard/functions.php on line 481

I've noticed that the port number isn't being saved (it comes out blank).

**Comment by causefx** [comment]
yea, i fucked it up last night with a type, for now clear the port on SAB and NZBGET in Org settings.

For NZBGet URL put `http://192.168.1.9:PORTHERE`

**Comment by compil3** [comment]
Yup that worked.  Thanks for letting me know.
