### ISSUE TITLE
FATAL ERROR After Update

### ISSUE THREAD

**Issue by Nexxus-LMT** [causefx/Organizr#1845]
####Version: 2.1.2320
####Branch: v2-master
####Server OS: *nix
####PHP: 7.4.28
####Install Type: Official Docker
####Auth Type: internal
####Auth Backend: 
####Installed Plugins: 

####Installed Themes: 

####Aquamarine:

####name: Aquamarine

####path: data/themes/Aquamarine_theme

####repo: https://github.com/Organizr/Organizr-Themes

####version: 2.0.2

Theme: Aquamarine
Local: false
oAuth: false
Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:100.0) Gecko/20100101 Firefox/100.0
<hr>

Using with mariadb database docker.

##### Problem Description:

FATAL ERROR POPUP
Account Settings area says  'Content Not Found'
Dashboard seems to work alright otherwise. Not sure where to find logs for the error.
<hr>

##### Reproduction Steps:

Once Logged in or refresh browser.
<hr>

#### Errors on screen?  If so paste here:

```
via organizr
FATAL ERROR

via Browsers

Source map error: Error: request failed with status 404
Resource URL: https://domain.tld/dashboard/js/tinycolor.min.js

TypeError: v.created.indexOf is not a function
.....
....
```

**Comment by causefx** [comment]
can you clear out the tokens table?

**Comment by Nexxus-LMT** [comment]
cleared out my tokens table but no luck. ERROR and settings issue persist

Also backed up both containers  & volumes ... deleted them.  then recreated two instances of the same version as follows

organizr (organizr/organizr:latest)

- using sqlite
no fatal error messages
account settings accesible

-using mariaDB (linuxserver/mariadb:latest)
FATAL ERROR on LOGIN
account settings "content not found'

performed same on seperate machine and results were similar as initial diagnosis.


> can you clear out the tokens table?
> […](#)
> Sent from my iPhone
> On May 28, 2022, at 9:05 PM, WaitukuNexx ***@***.***> wrote: ﻿ ####Version: 2.1.2320 ####Branch: v2-master ####Server OS: *nix ####PHP: 7.4.28 ####Install Type: Official Docker ####Auth Type: internal ####Auth Backend: ####Installed Plugins: ####Installed Themes: ####Aquamarine: ####name: Aquamarine ####path: data/themes/Aquamarine_theme ####repo: https://github.com/Organizr/Organizr-Themes ####version: 2.0.2 Theme: Aquamarine Local: false oAuth: false Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:100.0) Gecko/20100101 Firefox/100.0 Using with mariadb database docker. Problem Description: FATAL ERROR POPUP Account Settings area says 'Content Not Found' Dashboard seems to work alright otherwise. Not sure where to find logs for the error. Reproduction Steps: Once Logged in or refresh browser. Errors on screen? If so paste here: via organizr FATAL ERROR via Browsers Source map error: Error: request failed with status 404 Resource URL: https://domain.tld/dashboard/js/tinycolor.min.js TypeError: v.created.indexOf is not a function ..... .... — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.

**Comment by Nexxus-LMT** [comment]
not very particular about what db connections i will have to use but just wanted to alert you of the issue and provide information according to my usage. I have a question... it's always been my preference but is there a noticeable advantage of using external db as most configs i see online don't bother to mention it?

**Comment by causefx** [comment]
i believe mariadb would be the way to go with concurrent use. I will try and dig into this today.

**Comment by CollinChaffin** [comment]
I think I'm almost done using this app - every time I restart my container and it updates - it friggin breaks.  Now, no tabs "contact your administrator".  Does anyone actually TEST these dev builds before pushing them?!?  So what do we do when there's now not even a "settings"? Just this screen
![chrome_BDw9MNW8R7](https://user-images.githubusercontent.com/9301483/170881605-2ffd8956-8cdb-4c0c-a718-30e9d5e177e8.png)

**Comment by causefx** [comment]
I believe this goes back to sqlite limitiations.  Especially if the db is mounted on a network share.  I can add in another check as i think the DB's are locking in those instances.  For now since you are logged in goto these URL's.

```
http://org-url/api/v2/update/reset/groupmax
http://org-url/api/v2/update/migrate/2.1.2200
```

**Comment by causefx** [comment]
Also @CollinChaffin  I would love your logs to see if it that is the issue.  And if it isn't, i need to dig in further.

**Comment by CollinChaffin** [comment]
Thanks for the quick reply! So, posting screenshots to help others. 1st url execution looked bad, with failure, BUT 2nd was success.  Then, after that, reverting to homepage url restored tabs
![chrome_5uo1pZ1F4d](https://user-images.githubusercontent.com/9301483/170882112-8009498f-99ea-4f9b-96d5-ee8b632eac35.png)
![chrome_bNPf7pxqND](https://user-images.githubusercontent.com/9301483/170882127-d73f96bb-825c-4997-a8fa-bd2a27444325.png)
.

**Comment by causefx** [comment]
perfect, were you able to check the logs?  should be some errors from before on updating the DB.

**Comment by causefx** [comment]
@Nexxus-LMT this was fixed in last release.
