### ISSUE TITLE
[FIXED] Composer error while upgrading docker version of Organizr.

### ISSUE THREAD

**Issue by Guillaume-iov42** [causefx/Organizr#1847]
I used the internal link to update Organizr today (installed as a docker image on my Synology NAS), which usually works fine with no problem.

But today, it didn't: when trying to access the URL, instead of the organizr I have a message: "Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 7.4.0".

How to fix that?

**Comment by Guillaume-iov42** [comment]
I've fixed it by updating the docker image to latest.

**Comment by causefx** [comment]
thank you for following up.
