### ISSUE TITLE
Login Error - Api connection failed

### ISSUE THREAD

**Issue by stanthewizzard** [causefx/Organizr#1848]
###### Operating System: Ubuntu 22.04
PHP 8.1
<hr>

##### Problem Description:

I'm unable to login 

<hr>

#### Errors on screen?  If so paste here:

```
Login Error - Api connection failed
```
Nginx error log

2022/06/01 12:26:58 [error] 2800#2800: *1 FastCGI sent in stderr: "PHP message: Organizr E_DEPRECATED:  Return type of Requests_Cookie_Jar::offsetExists($key) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /opt/Organizr/api/vendor/rmccue/requests/library/Requests/Cookie/Jar.php on line 63PHP message: Organizr E_DEPRECATED:  Return type of Requests_Cookie_Jar::offsetGet($key) should either be compatible with ArrayAccess::offsetGet(mixed $offset): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /opt/Organizr/api/vendor/rmccue/requests/library/Requests/Cookie/Jar.php on line 73PHP message: Organizr E_DEPRECATED:  Return type of Requests_Cookie_Jar::offsetSet($key, $value) should either be compatible with ArrayAccess::offsetSet(mixed $offset, mixed $value): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /opt/Organizr/api/vendor/rmccue/requests/library/Requests/Cookie/Jar.php on line 89PHP message: Organizr E_DEPRECATED:  Return type of Requests_Cookie_Jar::offsetUnset($key) should either be compatible with ArrayAccess::offsetUnset(mixed $offset): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /opt/Organizr/api/vendor/rmccue/requests/library/Requests/Cookie/Jar.php on line 102PHP message: Organizr E_DEPRECATED:  Return type of Requests_Cookie_Jar::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /opt/Organizr/api/vendor/rmccue/requests/library/Requests/Cookie/Jar.php on line 111PHP message: Organizr E_DEPRECATED:  Return type of Requests_Utility_CaseInsensitiveDictionary::offsetExists($key) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWill
2022/06/01 12:26:58 [error] 2800#2800: *1 upstream sent too big header while reading response header from upstream, client: 192.168.0.180, server: xxx.yyy..com, request: "POST /api/v2/login HTTP/2.0", upstream: "fastcgi://unix:/run/php/php-fpm.sock:", host: "xxx.yyy..com", referrer: "https://xxx.yyy..com/"

Thanks (againà) for help

**Comment by stanthewizzard** [comment]
I deleted everything.
Did a git
from scratch, it works
with the backup not

I rebuilted everything instead

**Comment by causefx** [comment]
was this error right after you updated?

**Comment by stanthewizzard** [comment]
I have updated. But I was logged in.
After being logged out ... I was never able to relog again.

The nuke method was right

But If you have any idea ...

**Comment by guydavis** [comment]
Started to see this issue as well this week.  I am running the `organizr/organizr` Docker image, master branch normally.  Tried `develop` branch just now and same behavior.  I run on Unraid behind a Swag proxy (containerized). Please let me know how to triage this further.  Thanks!

![image](https://user-images.githubusercontent.com/12936/172062859-e5f6c269-65bf-40b6-91c0-3b768869764f.png)

![image](https://user-images.githubusercontent.com/12936/172063005-91df1b3c-9055-43db-ad0c-f64e011a2837.png)

**Comment by HalianElf** [comment]
@guydavis yours is actually the same as the OP with the `PHP message: Organizr E_DEPRECATED: Return type of Requests_Cookie_Jar::offsetExists($key)` and isn't just [this](https://docs.organizr.app/help/faq/organizr-login-error)?

**Comment by guydavis** [comment]
> @guydavis yours is actually the same as the OP with the `PHP message: Organizr E_DEPRECATED: Return type of Requests_Cookie_Jar::offsetExists($key)` and isn't just [this](https://docs.organizr.app/help/faq/organizr-login-error)?

Great! By updating/adding these lines to `/config/nginx/proxy.conf` inside the Swag container and restarting Swag, I am now able to login into Organizr again.  

```
proxy_buffer_size          128k;
proxy_buffers              4 256k;
proxy_busy_buffers_size    256k;
```

**Comment by stanthewizzard** [comment]
Thanks it worked

**Comment by Naomarn** [comment]
Users are getting this error when trying to log in. There are a couple things here.
1. Is there a way to run import Jellyfin users on schedule?
2. Can users log in without an email address since Jellyfin does not have this option, Ombi would be a great option to have since it has the email field for users.
3. If I just want to use Manage Invites Plugin this will send an email for user to sign up and then asks if they have Emby account not Jellyfin, if they click no and put in information they also get the API connection failed error

Here is a screen from the log, which is confusing because they for sure did not log in
![image](https://user-images.githubusercontent.com/116525162/198093020-be5e4f34-b90d-4fda-899d-e6aa34fc7cdc.png)

**Comment by Naomarn** [comment]
Disregard the log in issues, I had my Jellyfin URL in authentication set to the FQDN. I would still like to know about the import of Jellyfin users because until I click the button myself users cant log in
