### ISSUE TITLE
Install Issues (PHP Service)

### ISSUE THREAD

**Issue by hbkidjb1** [causefx/Organizr#1850]
###### Operating System: Windows/MacOS/Ubuntu
<hr>

##### Problem Description:
I am having the same problem as was discussed in this post, except the resolution for him did not work for me.  Can anyone help?
https://github.com/causefx/Organizr/issues/422

<hr>

##### Reproduction Steps:

<hr>

#### Errors on screen?  If so paste here:

```

```

**Comment by HalianElf** [comment]
Based on the last few people in support, likely has to do with missing VS redistributables - 64-bit linked from the install php page: https://aka.ms/vs/16/release/VC_redist.x64.exe

If you need 32-bit it's in the sidebar on the php for windows download page.

**Comment by hbkidjb1** [comment]
Thank you, that got the PHP service to run successfully.  Now, for some reason, the Nginx service is giving me the same error that I was getting from PHP.

**Comment by hbkidjb1** [comment]
Thank you for your help.  It's finally working!
