### ISSUE TITLE
Update loop [2.1.2320 > 2.1.2330]

### ISSUE THREAD

**Issue by solid-pixel** [causefx/Organizr#1852]
###### Operating System: Debian 4.19.208-1
<hr>

##### Problem Description:
I'm trying to update from 2.1.2320 to 2.1.2330. I go through the update process from the Update tab, everything seems to work correctly and it says Organizr is restarting. Then once the process ends, the update notification pops up again as the update didn't in fact apply, and I'm still stuck on 2.1.2320 with this notification bugging me wherever I go :(

I've enabled debug logging before running an update and  then checked the logs under System Settings > Logs, and nothing relevant shows up:

![image](https://user-images.githubusercontent.com/18260178/173878672-b8debf4b-8a4e-4075-b3fd-ed66cc3fa2c1.png)

Restarting my server also didn't help.

Attaching a video of the problem: https://www.loom.com/share/4a6a026d578c4a4281d86bebe966a2c7

Let me know if you need any more info!
Thanks a lot.

**Comment by HalianElf** [comment]
Try adding the execute flag to the `<root of organizr>/scripts/linux-update.sh` file.

**Comment by solid-pixel** [comment]
ahhhhh that fixed it indeed, thanks a lot @HalianElf !
