### ISSUE TITLE
I Broke My Setup

### ISSUE THREAD

**Issue by TonyBirt** [causefx/Organizr#1855]
###### Operating System: Windows 11
<hr>

##### Problem Description:
I added Tidal Web Player (https://listen.tidal.com/) as an iframe and set it to load automatically, with the help of chrome extension (Iframe Allow).  When opening Organizr now Tidal takes over web address and organizr can't be used.  Is there a way to remove the tab outside of Organizr interface?  Any help would be greatly appreciated.

<hr>

##### Reproduction Steps:

<hr>

#### Errors on screen?  If so paste here:

```

```

**Comment by causefx** [comment]
you will need to edit the database using DB Browser (SQLite)...

open up the Database and then goto the tabs tables and set preload for tidal to `0`
