### ISSUE TITLE
Request: setting for backup location

### ISSUE THREAD

**Issue by ofersadan85** [causefx/Organizr#1859]
As far as I can see the backup location cannot be changed, and is using the default location for the db itself as can be seen [here](https://github.com/causefx/Organizr/blob/4f2e6c5f0ceb37841051c32aeafba41467ac62e1/api/functions/backup-functions.php#L40) and [here](https://github.com/causefx/Organizr/blob/4f2e6c5f0ceb37841051c32aeafba41467ac62e1/api/functions/backup-functions.php#L57).

It would be extremely helpful to have the option to change the backup location (perhaps a setting in `config.php`). This would be especially good when using the docker image, as this location can be mapped to another filesystem if needed.

Also, I would be willing to handle this issue myself and send in a pull request if needed

**Comment by ofersadan85** [comment]
Anyone know if this is on the agenda or not?

**Comment by causefx** [comment]
i like this idea...  is there a feature request for it?  
https://vote.organizr.app

**Comment by ofersadan85** [comment]
@causefx I couldn't find anything like it over there, but this is somewhat related: https://feature.organizr.app/posts/151/support-for-external-databases

**Comment by causefx** [comment]
yeah that is different. go ahead and create a new one please

**Comment by ofersadan85** [comment]
Here: https://feature.organizr.app/posts/160/setting-for-backup-location

**Comment by ofersadan85** [comment]
@causefx can we expect this any time soon?

**Comment by causefx** [comment]
i have had some life issues lately but i am getting back into it now.

**Comment by causefx** [comment]
completed in dev
