### ISSUE TITLE
Request for coutchpotato on homepage

### ISSUE THREAD

**Issue by andyrav** [causefx/Organizr#186]
Request for coutchpotato on homepage

**Comment by causefx** [comment]
will check their api out.

**Comment by MrMxyzptlk** [comment]
I 2nd this request. Radarr is still too buggy and CouchPotato still works best...for me : )

**Comment by moosedookie** [comment]
I would also like to see Couchpotato make it's way to the homepage

**Comment by masterxdk** [comment]
+1

**Comment by causefx** [comment]
This is complete now in 174021c

**Comment by moosedookie** [comment]
@causefx 
Thanks for adding it! I'll check it out here in a little bit.
Thanks again!

**Comment by causefx** [comment]
lemme know if this works for you please.

**Comment by moosedookie** [comment]
It seems like it is working. Movies are now showing up in the calendar. Thanks!
