### ISSUE TITLE
[BUG] Failure to properly parse tautulli API data results in error.

### ISSUE THREAD

**Issue by iambryan37** [causefx/Organizr#1860]
###### Operating System: Windows/MacOS/Ubuntu
<hr>

##### Problem Description:

The data received from the `api/v2/homepage/tautulli/data` API call, is not properly parsed and results in an error. 
The code at line [8179-8251](https://github.com/causefx/Organizr/blob/v2-master/js/functions.js#L8179-L8251), attempts to access `e['rows'][0]` without checking if the API actually returns any rows for the specific stat. 
In my case this results in an error while at [https://github.com/causefx/Organizr/blob/v2-master/js/functions.js#L8190](https://github.com/causefx/Organizr/blob/v2-master/js/functions.js#L8190) while trying to access the art property. 

Proposed fix:
Add a length check at line [8178](https://github.com/causefx/Organizr/blob/v2-master/js/functions.js#L8178). e.g. `if(e['stat_id'] == stat && e['rows'].length > 0) {` 
<hr>

##### Reproduction Steps:

Don't watch movies (or TV series?) for a long time, I guess?
<hr>

#### Errors on screen?  If so paste here:

```
TypeError: Cannot read properties of undefined (reading 'art')
```
![image](https://user-images.githubusercontent.com/98959921/177499748-c42b3c87-2921-458f-a5df-15daaeac4f78.png)

**Comment by causefx** [comment]
thank you - i will look at this today
