### ISSUE TITLE
FEATURE: Ability to open Organizr tab in new browser tab

### ISSUE THREAD

**Issue by tylerbrockett** [causefx/Organizr#1866]
###### Operating System: Windows/MacOS/Ubuntu
<hr>

##### Problem Description:
Would like ability to open Organizr tab in new browser tab

<hr>

##### Reproduction Steps:

<hr>

#### Errors on screen?  If so paste here:

```

```

**Comment by tronyx** [comment]
All feature requests should go on our official FR page: https://feature.organizr.app/
