### ISSUE TITLE
Change/set language option missing

### ISSUE THREAD

**Issue by X1pheR** [causefx/Organizr#1868]
###### Operating System: Windows
<hr>

##### Problem Description:

Organizr displays in dutch but I want it to display in english. However I can't find a setting to force this. I did came across #1440 where it states that there should be a language option in the profile menu but I don't have it. I have custom javascript but also tried removing it so everything is default. But still no show.
<hr>

##### Reproduction Steps:

Just a clean install
<hr>

#### Errors on screen?  If so paste here:

```
No errors
```

**Comment by tronyx** [comment]
It should be to the left of your profile drop-down:
![language](https://user-images.githubusercontent.com/22502007/180884087-7847c667-c918-4f88-a25e-ab6508b260ab.png)

If not, and you're using a non-default theme, try changing to the default and checking again.

**Comment by X1pheR** [comment]
Ah thanks! Didn't think the theme would be the problem. Resolved 👍

**Comment by tronyx** [comment]
No problem. Glad you got it sorted.
