### ISSUE TITLE
Jackett is freezing in UI on API 500 Error

### ISSUE THREAD

**Issue by GAS85** [causefx/Organizr#1869]
###### Operating System: Ubuntu
<hr>

##### Problem Description:

If Jackett search been used and API call returns 500 Error, than UI will simply show endless "progress ring" and not reacting till whole page refresh. It should be an error shown in UI.

<hr>

##### Reproduction Steps:

E.g. put jacket down and do Jacket Search via Organizer UI.
Check in Developer --> Network that there is a 500 error received
UI part of Jackett is frozen - no error was shown.

<hr>

#### Errors on screen?  If so paste here:

```

```

**Comment by GAS85** [comment]
Than it is not my fault 😛

**Comment by causefx** [comment]
fixed in dev.  thanks!
