### ISSUE TITLE
nzbget homepage HTTP/1.1 401 Unauthorized

### ISSUE THREAD

**Issue by roblandry** [causefx/Organizr#187]
OK, let me start with I am using nginx as a reverse proxy with location blocks for all of my apps.
I am using auth as described within the wiki.

Most things seem to be working without a hitch, with the exception of the nzbget on the homepage. If i just use the local url http://hostip and port it works fine.

When using the https://hostname i end up getting 401 unauthorized. I do have authorization set up for nzbget within the location block which works fine otherwise. how would i pass the user and password of an Organizr user to the user.php login while loading nzbget?

Warning: file_get_contents(https://apps.myhost.me/nzbget/:/jsonrpc/listgroups): failed to open stream: HTTP request failed! HTTP/1.1 401 Unauthorized in /home/name/www/apps/Organizr/functions.php on line 473

**Comment by causefx** [comment]
SSL is a little funky for some reason, i'm working on that.

**Comment by fryfrog** [comment]
In your reverse proxy, maybe you could whitelist 127.0.0.1?

**Comment by causefx** [comment]
so since all the api calls happen in the backend, you want to use ip and port.
