### ISSUE TITLE
Jackett - please add support of "Blackhole"

### ISSUE THREAD

**Issue by GAS85** [causefx/Organizr#1870]
###### Operating System: Ubuntu
<hr>

##### Problem Description:

Jackett could be configured to download torrent file automatically on request and put it to blackhole of torrent client. This Link is presented in API call answer of Organizr:
```JSON
{
    "response": {
        "result": "success",
        "message": null,
        "data": {
            "content": {
                "Results": [
                    {
                        "FirstSeen": "0001-01-01T00:00:00",
                        "Tracker": "Some",
                        "TrackerId": "Some",
                        "TrackerType": "Some",
                        "CategoryDesc": "Some",
                        "BlackholeLink": "BLABLABLA"
...
```
Please add Action to trigger Jackett backend Blackhole use.

<hr>

##### Reproduction Steps:

<hr>

#### Errors on screen?  If so paste here:

```

```

**Comment by tronyx** [comment]
All feature requests should go here: https://feature.organizr.app/
