### ISSUE TITLE
Organizr jellyfin_credential cookie from Jellyfin SSO stops syncplay from working in Jellyfin

### ISSUE THREAD

**Issue by ianabney** [causefx/Organizr#1871]
###### Operating System: Organizr docker container running on PopOS 22.04
<hr>

##### Problem Description:
Whenever I have Jellyfin SSO enabled in Organizr, syncplay doesn't work in Jellyfin. If I disable Jellyfin SSO, syncplay works as expected.
If I have Jellyfin SSO enabled in Organizr and login, I get the jellyfin_credential cookie with the jellyfin access token in it. This cookie is somehow preventing Jellyfin's syncplay from working because if I delete this cookie and reload Organizr and go back to Jellyfin I'm prompted to login because the cookie for SSO isn't there, but once I log in syncplay works as expected.

<hr>

##### Reproduction Steps:
1. Log into Organizr with Jellyfin SSO enabled.
2. Go to the Jellyfin Tab and it should be logged in already
3. In Jellyfin tab hit create group in the syncplay button.
4. Group is created in Jellyfin but you are not in the group and can not join the group (No popup that says "Syncplay enabled")
5. Delete jellyfin_credential cookie
6. Refresh Organizr
7. Go to Jellyfin Tab and log in
8. In Jellyfin tab hit create group in the syncplay button.
9. Group is created and you are in it and popup says "Syncplay enabled."

<hr>

**Comment by ianabney** [comment]
This is a wild guess but it could possibly be caused because the cookie jellyfin_credentials that is created in [sso-functions.php](https://github.com/causefx/Organizr/blob/4f2e6c5f0ceb37841051c32aeafba41467ac62e1/api/functions/sso-functions.php) only has part of the data from the response of Jellyfin's [AuthenticationResult](https://jellyfin.org/docs/plugin-api/MediaBrowser.Controller.Authentication.AuthenticationResult.html). The cookie has the ServerID, User, and AccessToken properties, but not the [SessionInfo](https://jellyfin.org/docs/plugin-api/MediaBrowser.Controller.Session.SessionInfo.html?q=sessioninfo). I think that SessionInfo's Capabilities property is the one that would show that it supports sync.
I'm new to all this so I maybe wrong, or there maybe some limitation that would not let this work.

**Comment by causefx** [comment]
you are more than likely correct.  i will see what information is returned.

**Comment by ianabney** [comment]
I'd still like this to be looked into if possible.

**Comment by causefx** [comment]
It seems that no extra info is in the `jellyfin_credentials` localStorage key that is set.  I do see that it sets 2 more keys:
`user-xxxxxxxxxxxxxxxxxxxxxxxx-xxxxxxxxxxxxxxxxx` and `_deviceId2` which I can set if needed, just not sure if that is what is missing.

**Comment by ianabney** [comment]
I did some more looking and I think that the $token returned from the /Users/authenticatebyname request in the sso-functions.php has some more values that may be needed in order for syncplay to work. The $token that is created from that response is a nested array (the token that is used to create the jellyfin_credentials by using the $token['User'] ['Id'] etc). But I couldn't figure out a good way to see what was in those arrays because I'm pretty new to web debugging. Is there a way to see what the full response from the request is?

**Comment by causefx** [comment]
I already have all the new info, i just need to know if those 2 local storage items i listed above are what's needed.  Can you manually delete those and see if it still works.

**Comment by ianabney** [comment]
While connecting directly to jellyfin I do not need either of those local storage keys for syncplay to work correctly.

Also in my testing, when I use the Jellyfin SSO in organizr and then go to jellyfin (either iFrame or new tab) I won't be able to join syncplay groups. If I then just log out and log back into jellyfin, the syncplay is able to work correctly.
So it seems like the problem isn't the cookie like I initially thought beacuse I don't need to clear the cache or delete any cookies, just log off and back in.

I looked into the possibility that the websockets for the two different login methods being the issue, but from what I can tell they have the same request headers and payload. The only difference I found was that the request call stack under the Initiator tab was different.
The organizr where I logged off and back into jellyfin (syncplay working):
![image](https://user-images.githubusercontent.com/39421160/186550882-b24353db-9e06-46f6-bb3d-71a4f63d9f19.png)
The organizr where I didn't log off and back on (syncplay broken):
![image](https://user-images.githubusercontent.com/39421160/186550991-ce42560b-653f-4141-874c-6f13902a9e83.png)

**Comment by ianabney** [comment]
I ended up deciding to reconfigure my Jellyfin as a subdomain instead of a subpath for reverse proxying which allows Jellyfin to remember my credentials through organizr because it's a different site. This doesn't actually solve the problem because I'm just bypassing Organizr's Jellyfin SSO but it works for me.
