### ISSUE TITLE
Cannot sort/move Categories or Tabs 

### ISSUE THREAD

**Issue by Healzangels** [causefx/Organizr#1875]
###### Operating System: Docker/Unraid
<hr>

##### Problem Description:

Having an issue sorting categories and tabs. If I create a new tab or category they show up fine and the hamburger option or little hand option appear for attempting to sort the order however I can't drag/move them. 
Attempted in different browsers/Incog window.
I am using Authenik with reverse proxy for auth. 
<hr>

##### Reproduction Steps:

Attempt to move item, will not move.
I have also attempted this with no theme apply/custom css

<hr>

#### Errors on screen?  If so paste here:

```
No errors present

```

**Comment by causefx** [comment]
which browsers tested along with versions?

**Comment by causefx** [comment]
also try logging into demo.organizr.app

see if you can sort there

**Comment by Healzangels** [comment]
Thanks so much for the super fast response!
So think its me... or at least this computer for some reason. 

demo.organizr.app same issue but that got me thinking why didn't I try on another computer sooner. 
Gave that a whirl from another computer also running Chrome and moving tabs/categories is functioning just fine! *Phew* 

Cleared my settings/advanced clear of cache etc on this desktop but still issue so thinking maybe some sort of Network setting or adblocking or something similar I've got going on. More digging on my part required!

Thanks again for the super quick response saved me from going to rebuild everything to test!
 
I'll be getting some beer money your way!
Thanks for the awesome application/support

-Cheers

**Comment by causefx** [comment]
Glad you were able to narrow it down slightly. I would also suggest opening browser console when opening organizr. it may show you an error. think F12 opens it
