### ISSUE TITLE
Qbit Login/Search with Chrome

### ISSUE THREAD

**Issue by awshifts** [causefx/Organizr#1876]
Organizr Version: V2
 Branch: Master
 WebServer: Nginx
 Operating System: Windows

Problem Description:
I just installed Organizr, it's working well for most of everything I am doing. 

I have an issue with Google Chrome, everything works as expected in firefox (I use chrome for most of my stuff but wanted to test in firefox just in case), however with Qbittorrent I am unable to log in if I have force login, if I disable user login requirement, I can access Qbit fine, but I can not perform searches, however If I use firefox I have no issues at all.

**Comment by causefx** [comment]
anything happening in browser console (F12) when trying in chrome?

**Comment by awshifts** [comment]
See Below 

![Snag_16774159](https://user-images.githubusercontent.com/34609736/187053618-c1288946-57b5-49d2-a40c-2c4dd7b7bcec.png)


xhr.js:210          GET http://10.0./api/v2/sync/maindata 403 (Forbidden)
(anonymous) @ chunk-vendors.a5b83856.js:14
t.exports @ chunk-vendors.a5b83856.js:14
t.exports @ chunk-vendors.a5b83856.js:14
h.request @ chunk-vendors.a5b83856.js:14
n.forEach.h.<computed> @ chunk-vendors.a5b83856.js:14
(anonymous) @ chunk-vendors.a5b83856.js:14
getMainData @ app.75207d8a.js:1
updateMainData @ app.75207d8a.js:1
(anonymous) @ chunk-vendors.a5b83856.js:58
(anonymous) @ chunk-vendors.a5b83856.js:58
(anonymous) @ chunk-vendors.a5b83856.js:58
x._withCommit @ chunk-vendors.a5b83856.js:58
x.commit @ chunk-vendors.a5b83856.js:58
commit @ chunk-vendors.a5b83856.js:58
(anonymous) @ app.75207d8a.js:1
setInterval (async)
INIT_INTERVALS @ app.75207d8a.js:1
(anonymous) @ chunk-vendors.a5b83856.js:58
x.dispatch @ chunk-vendors.a5b83856.js:58
dispatch @ chunk-vendors.a5b83856.js:58
created @ 490.b31a1a66.js:1
Di @ chunk-vendors.a5b83856.js:52
di @ chunk-vendors.a5b83856.js:52
Wn.t._init @ chunk-vendors.a5b83856.js:52
a @ chunk-vendors.a5b83856.js:52
Ae @ chunk-vendors.a5b83856.js:52
init @ chunk-vendors.a5b83856.js:52
i @ chunk-vendors.a5b83856.js:52
g @ chunk-vendors.a5b83856.js:52
f @ chunk-vendors.a5b83856.js:52
I @ chunk-vendors.a5b83856.js:52
M @ chunk-vendors.a5b83856.js:52
I @ chunk-vendors.a5b83856.js:52
M @ chunk-vendors.a5b83856.js:52
(anonymous) @ chunk-vendors.a5b83856.js:52
t._update @ chunk-vendors.a5b83856.js:52
n @ chunk-vendors.a5b83856.js:52
t.get @ chunk-vendors.a5b83856.js:52
t.run @ chunk-vendors.a5b83856.js:52
ki @ chunk-vendors.a5b83856.js:52
(anonymous) @ chunk-vendors.a5b83856.js:52
Ni @ chunk-vendors.a5b83856.js:52
Promise.then (async)
Bi @ chunk-vendors.a5b83856.js:52
Zi @ chunk-vendors.a5b83856.js:52
Ii @ chunk-vendors.a5b83856.js:52
t.update @ chunk-vendors.a5b83856.js:52
t.notify @ chunk-vendors.a5b83856.js:52
set @ chunk-vendors.a5b83856.js:52
(anonymous) @ chunk-vendors.a5b83856.js:32
(anonymous) @ chunk-vendors.a5b83856.js:32
Qt.updateRoute @ chunk-vendors.a5b83856.js:32
(anonymous) @ chunk-vendors.a5b83856.js:32
(anonymous) @ chunk-vendors.a5b83856.js:32
n @ chunk-vendors.a5b83856.js:32
n @ chunk-vendors.a5b83856.js:32
Ht @ chunk-vendors.a5b83856.js:32
(anonymous) @ chunk-vendors.a5b83856.js:32
n @ chunk-vendors.a5b83856.js:32
(anonymous) @ chunk-vendors.a5b83856.js:32
(anonymous) @ chunk-vendors.a5b83856.js:32
(anonymous) @ chunk-vendors.a5b83856.js:32
(anonymous) @ chunk-vendors.a5b83856.js:32
Promise.then (async)
(anonymous) @ chunk-vendors.a5b83856.js:32
(anonymous) @ chunk-vendors.a5b83856.js:32
(anonymous) @ chunk-vendors.a5b83856.js:32
Gt @ chunk-vendors.a5b83856.js:32
(anonymous) @ chunk-vendors.a5b83856.js:32
p @ chunk-vendors.a5b83856.js:32
n @ chunk-vendors.a5b83856.js:32
n @ chunk-vendors.a5b83856.js:32
(anonymous) @ chunk-vendors.a5b83856.js:32
(anonymous) @ chunk-vendors.a5b83856.js:32
(anonymous) @ app.75207d8a.js:1
p @ chunk-vendors.a5b83856.js:32
n @ chunk-vendors.a5b83856.js:32
n @ chunk-vendors.a5b83856.js:32
Ht @ chunk-vendors.a5b83856.js:32
Qt.confirmTransition @ chunk-vendors.a5b83856.js:32
Qt.transitionTo @ chunk-vendors.a5b83856.js:32
e.push @ chunk-vendors.a5b83856.js:32
(anonymous) @ chunk-vendors.a5b83856.js:32
be.push @ chunk-vendors.a5b83856.js:32
login @ 475.f652df1e.js:1
await in login (async)
keyup @ 475.f652df1e.js:1
Di @ chunk-vendors.a5b83856.js:52
i @ chunk-vendors.a5b83856.js:52
r._wrapper @ chunk-vendors.a5b83856.js:52

**Comment by HalianElf** [comment]
Is your Org on that same 10.0 IP? I would bet it's the SameSite issue.

**Comment by awshifts** [comment]
> Is your Org on that same 10.0 IP? I would bet it's the SameSite issue.

No, org is 10.0.1.x and qbit is 10.0.14.x   Different subnets

**Comment by HalianElf** [comment]
https://docs.organizr.app/help/faq/login-looping-samesite-errors

Kinda surprised it's not an issue in Firefox too, they have implemented the same rules as far as I was aware.
