### ISSUE TITLE
[Enhancement] Add some options right to the "add" popup

### ISSUE THREAD

**Issue by YouveGotMeowxy** [causefx/Organizr#1878]
When adding a new service and filling out it's info, it would be super handy to also have these settings on the same form so that we can select them when saving the entire service we're adding (rather than having to save it first, and then set these options from the "big list" only.

![image](https://user-images.githubusercontent.com/39491297/189979097-e0c5f8b4-fe57-44b6-a78d-ee0f090942cd.png)

(the switch is the enable/disable switch; it would be nice to immediately be able to enable it when saving it as well).

**Comment by YouveGotMeowxy** [comment]
oof. Didn't think this idea was _**so**_ bad that it'd just get crickets. LOL

**Comment by causefx** [comment]
sorry about this - i have been MIA for a little bit.  Can you post this @ https://vote.organizr.app
