### ISSUE TITLE
Update script not working

### ISSUE THREAD

**Issue by koolmon10** [causefx/Organizr#1881]
###### Operating System: Ubuntu
<hr>

##### Problem Description:

Update doesn't want to work. Was getting success message but update not actually applied, progress bar would shoot to 100% immediately when ran. Eventually I forced a git reset from the shell to update, and now I am getting an "update script permissions error" whenever I try to force a file redownload. I've checked the script is there, has execute permissions, and runs successfully as my nginx user. 

<hr>

##### Reproduction Steps:

<hr>

#### Errors on screen?  If so paste here:

```
{"log_level":"WARNING","message":"Update script doesn't exist","channel":"Update","username":"REDACTED","trace_id":"4cf6b6f4-5770-45cc-b840-52b3776868fd","file":"/var/www/Organizr/api/functions/update-functions.php","line":19,"context":{"file":"/var/www/Organizr/scripts/linux-update.sh v2-develop > /var/www/Organizr/scripts/log.txt 2>&1"},"remote_ip_address":"192.168.1.191","server_ip_address":"192.168.1.48","user_agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:105.0) Gecko/20100101 Firefox/105.0","datetime":"2022-10-01 03:04:40.256084","timezone":"UTC","process_time":1.8208026885986328}

```

**Comment by GunbleR** [comment]
Organizr Version: V 2.1.2330
Branch:  v2-master
php: 8.1
WebServer: Nginx
Operating System: freebsd 13.1 jail (truenas)

same. 
in Update-Functions.php
functions file_exists and is_executable didnt like the additional parameters in $script.
if i trim the parameters from $script variable and re-add them after "testScriptFilePermissions" check, update functions normally.

edit: i did try chmod +x linux-update.sh and chown before trying this^, it didnt help me.
`{"log_level":"WARNING","message":"Update script doesn't exist","channel":"Update","username":"","trace_id":"1605cabe-13e2-4745-b8fe-2f033d1e9be1","file":"/usr/local/www/Organizr/api/functions/update-functions.php","line":19,"context":{"file":"/usr/local/www/Organizr/scripts/linux-update.sh v2-master > /usr/local/www/Organizr/scripts/log.txt 2>&1"},"remote_ip_address":"10.0.3.138","server_ip_address":"10.0.3.83","user_agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:105.0) Gecko/20100101 Firefox/105.0","datetime":"2022-10-01 21:40:27.096690","timezone":"UTC","process_time":3.531932830810547}`

**Comment by jeffgroth** [comment]
I was having the same issue `chmod +x linux-update.sh` fixed it for me.

**Comment by koolmon10** [comment]
I did try that, but it still didn't work in Organizr. I was able to run it
from terminal that way though.

**Comment by qudiqudi** [comment]
Same here, updating via GUI does nothing, except site refresh. Running it from the cli with chmod +x works though.

**Comment by olesk75** [comment]
In my case, `chmod +x linux-update.sh` did actually allow the web update process to run normally.

**Comment by selfdigest** [comment]
I was having this problem too, and `chmod +x` didnt work, but running it from terminal showed me that it was trying to use unzip, which I didnt have. (i use p7zip) Installed unzip, tried from the webui again, and it worked.

It worked before now, so donno what changed, but glad it was an easy fix for me.

**Comment by causefx** [comment]
@sek0n what OS you on?

**Comment by selfdigest** [comment]
That was on Debian/Linux.

**Comment by BastionNtB** [comment]
I too am having this issue.

I have confirmed that throughout the entirety of the site www folder, www-data has full read/write/execute (775) permissions and is both the owner, and group owner of the data.

I have restarted the server as well, but all I get is "Permission denied" from the log.txt
`sh: 1: /var/www/websites/[REDACTED]/scripts/linux-update.sh: Permission denied`

and in the website itself, it reports "UPDATE SCRIPT DOESN'T EXIST" though, I have confirmed it does, I have also confirmed that php-fpm is being run via www-data user and group as per it's configuration file.

I would very much like this to not have to be a manual process. Any help would be appreciated.


Edit: some background information
Ubuntu 22.04.1 LTS
php-fpm7.4
Organizr Version:  2.1.2370 v2-master

All organizr paths are considered writable from the website
![image](https://user-images.githubusercontent.com/15705306/211428440-f6501b13-c633-40c5-9be1-f9adaa2902d6.png)

**Comment by GunbleR** [comment]
still not working on freebsd.
as posted in my privious post, on freebsd, functions file_exists and is_executable seems to return false when supplied with parameters in addition to filename.

suggestion: 
adding parameters after  testScriptFilePermissions($script).
the following seems to work (in addition to fixing bash bin location https://github.com/causefx/Organizr/issues/1906).

                $script = $this->root . DIRECTORY_SEPARATOR . 'scripts' . DIRECTORY_SEPARATOR . 'linux-update.sh';
                $checkScript = $this->testScriptFilePermissions($script);
                $script = $script . ' ' . $branch . ' > ' . $logFile . ' 2>&1';

**Comment by BastionNtB** [comment]
Bump.

**Comment by BastionNtB** [comment]
Update

I tried to update the shebang manually and then have it run from inside organizr, it still didn't work for me.

I even tried using `which bin` to show exactly where my bin executable was located and updated the shebang to it as well, but it gave the same error as before.

I've manually updated organizr at this point. I hope it won't be a problem next update, I will post if it does. Thanks for looking into it.

**Comment by BastionNtB** [comment]
Just an FYI, attempting to update to the latest version will give no error, restart organizr, but not update.

**Comment by causefx** [comment]
anything in the script log folder?

**Comment by BastionNtB** [comment]
There's no date or timestamp, but this is what's in there:
/var/www/websites/site/scripts/linux-update.sh: line 23: unzip: command not found

Guess I need unzip lol.

It worked after I did 'sudo apt install unzip -y' on ubuntu 22.04

Not sure if I missed the prereq or not but yeah. Thanks!

**Comment by causefx** [comment]
awesome. thank you.
