### ISSUE TITLE
Problem login after latest update

### ISSUE THREAD

**Issue by pasuva** [causefx/Organizr#1883]
###### Operating System: Debian
<hr>

##### Problem Description:

Hi everyone,

I made the last update (2.1.2370) and now when I try to login in the Login Page, Organizr V2 show me a message: Please waiting ... The problem is that never make the login, still waiting forever. Although, I can access to the homepage with mi IP/#Homepage and because I have my user session always open I can get in Organizr. But I can't login if I close my user session.

Anyone have this problem after the latest update??

Thanks, Cheers,

Patricia

**Comment by pasuva** [comment]
Another clue, if I register a new user with login page, automatically login me with the new user, then if I close the session and try to login again with the new user I can't I have the same problem: Please waiting infinite.

**Comment by pasuva** [comment]
Another clue, now I see an error: API CONECTION FAILED at de login page

**Comment by causefx** [comment]
you may have too many SSO options... causing header to become to big - can you check webserver logs?

**Comment by pasuva** [comment]
`2022/10/07 09:02:10 [error] 13122#13122: *2362 FastCGI sent in stderr: "PHP message: Organizr E_DEPRECATED: Return type of Requests_Cookie_Jar::offsetExists($key) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/patflix.ddns.net/html/api/vendor/rmccue/requests/library/Requests/Cookie/Jar.php on line 63PHP message: Organizr E_DEPRECATED: Return type of Requests_Cookie_Jar::offsetGet($key) should either be compatible with ArrayAccess::offsetGet(mixed $offset): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in`

**Comment by pasuva** [comment]
And in the log in Organizr I see this: 7 de octubre de 2022 14:29 Authentication User has logged in

6f7e341b-45e5-4140-9d67-24e32466cb36Trace ID
patUser
AuthenticationFunction
/var/www/---/html/api/classes/organizr.class.php#L3834



So really I log in but Organizr never go out of the login page to go to the Homepage

**Comment by pasuva** [comment]
Now I see the problem. There is a bug between login in Organizr and the single-sing-on, I had activate this configuration with Ombi, and after the latest update failed and send me this kind of errors. Now I delete this configuration and the login problem dissapear
