### ISSUE TITLE
Cannot vertically scroll on andriod

### ISSUE THREAD

**Issue by jessielw** [causefx/Organizr#1888]
If I go into a tab and press back I can then scroll. 

However the close splash screen stays right up on top.

**Comment by jessielw** [comment]
This is definitely still an issue

**Comment by causefx** [comment]
i will check this out

**Comment by jessielw** [comment]
Awesome! Let me know.

**Comment by jessielw** [comment]
Bumping since it's attempting to close this

**Comment by jessielw** [comment]
Negative

**Comment by jessielw** [comment]
0.o

**Comment by jessielw** [comment]
😶
