### ISSUE TITLE
settings.php resetting nzbgetport

### ISSUE THREAD

**Issue by roblandry** [causefx/Organizr#189]
Line [#515](https://github.com/causefx/Organizr/blob/a1ebdc594092ee2bd3cf28a12d6cbe67c8f863df/settings.php#L1515) of settings.php is causing the nzbport to be deleted. this should be saving the port number for sabnzbd.

`<input type="text" class="form-control material input-sm" name="nzbgetPort" placeholder="<?php echo $language->translate("SABNZBD_PORT");?>" autocorrect="off" autocapitalize="off" value="<?php echo SABNZBDPORT;?>">`

should be 
`<input type="text" class="form-control material input-sm" name="sabnzbdPort" placeholder="<?php echo $language->translate("SABNZBD_PORT");?>" autocorrect="off" autocapitalize="off" value="<?php echo SABNZBDPORT;?>">`

**Comment by causefx** [comment]
You. Thank you. I fixed this already just need to commit it
