### ISSUE TITLE
backup goes wrong and keep getting bigger,

### ISSUE THREAD

**Issue by casselluu** [causefx/Organizr#1891]
###### Operating System: unraid/linux5.19
<hr>

##### Problem Description:

for some unknown reason the backup is keep doubling itself,from 135kb to 263kb,521kb,1mb,2mb....untill i noticed it goes to 64GB,seems every time it is doubling.
<hr>

##### Reproduction Steps:

<hr>

#### Errors on screen?  If so paste here:

```

```

**Comment by causefx** [comment]
are you able to open the zip and see what is big

**Comment by casselluu** [comment]
after manual backup and open the zip,it seems  backup all the old version of backups.
Maybe because i use defult location   "/config/www/organizr/data/ZA4NjAsnkX/backups/ "?
backup[2022-11-13_07-40 - ll][2.1.2370]
-config
--config.php
--config.bak.php
-ZA4NjAsnkX
--logs
--organizr-2022-10-27.log
---organizr-2022-10-28.log
---organizr-2022-10-30.log
---organizr-2022-10-31.log
---organizr-2022-11-06.log
---organizr-2022-11-13.log
--organizr.db
-organizr.db
backup[2022-11-13_23-38 - vs][2.1.2370]
-config
--config.php
--config.bak.php
-ZA4NjAsnkX
--backups
---backup[2022-11-13_23-38 -Pzl][2.1.2370].zip
---backup[2022-11-13_23-38 - Bn][2.1.2370].zip
---backup[2022-11-13_07-40 - ll][2.1.2370].zip
--logs
---organizr-2022-10-27.log
---organizr-2022-10-28.log
---organizr-2022-10-30.log
---organizr-2022-10-31.log
---organizr-2022-11-06.log
---organizr-2022-11-13.log
--organizr.db
-organizr.db

**Comment by causefx** [comment]
ahhh that'll do it.  Maybe I can loop through the data directory and remove the backup folder if present...  Currently Organizr backs up the entire `data` folder plus the db file.

**Comment by brandonvu99** [comment]
Ran into this issue as well. Will it be fixed?

**Comment by causefx** [comment]
fixed in dev.
