### ISSUE TITLE
Switch between open tabs [enhancement request]

### ISSUE THREAD

**Issue by derekoharrow** [causefx/Organizr#1892]
Organizr enables you to open multiple iframes/pages.

It would be great to have a way of switching between those open pages.

This could be done in a couple of ways:

- Implement an ALT-TAB and SHIFT-ALT-TAB type approach to switch to the next or previous open window
- Implement a WIN-TAB type approach to open a page that shows the open windows (and perhaps a snapshot view of them).

**Comment by HalianElf** [comment]
Please submit feature requests to the feature request site: https://feature.organizr.app/
