### ISSUE TITLE
Transmission Integration: Could not get session ID

### ISSUE THREAD

**Issue by larsenv** [causefx/Organizr#1894]
Organizr Version: 2.1.2370
Branch: Master/Develop
WebServer: Nginx
Operating System: Linux
<hr>

##### Problem Description:

When trying to set up the Transmission homepage integration, I receive an error, "Could not get session ID".
<hr>

##### Reproduction Steps:

Go to Homepage Integrations, select Transmission, fill in the URL and password and press Test. You will see the error.
<hr>

#### Errors on screen?  If so paste here:

```
Transmission Connect Function - Error: Could not get session ID
```

**Comment by tronyx** [comment]
A quick Google search would yield the following resolved issues for what you're seeing:

https://github.com/causefx/Organizr/issues/885

https://github.com/causefx/Organizr/issues/1583
