### ISSUE TITLE
Latest Pi-Hole breaks stats if password enabled

### ISSUE THREAD

**Issue by SAS-1** [causefx/Organizr#1896]
###### WebServer: Docker
<hr>

##### Problem Description:
If you have a password enabled on your Pi-Hole web interface then Organizr will no longer show stats on the home page. This is due to a change made to require an auth token when using the API. https://discourse.pi-hole.net/t/upcoming-changes-authentication-for-more-api-endpoints-required/59315 removing the password allows stats to be shown.

The issue is down to the API change if there is no password then the API is

http://pi.hole/admin/api.php?status

if a password is enabled then the API needs to be

http://pi.hole/admin/api.php?status&auth=<TOKEN>

There is no option to add a token to the Pi-Hole stats settings. 

<hr>

##### Reproduction Steps:
Update to latest Pi-Hole
Refresh Homepage - Stats disappear
Remove Password from Pi-Hole using pihole -a -p and leaving blank
Refresh Homepage - Stats Appear
Add password back 
Refresh Homepage - Stats disappear

<hr>

#### Errors on screen?  If so paste here:

```
None Shown and unable to see anything in logs. 
```

**Comment by causefx** [comment]
checking now.
