### ISSUE TITLE
2.1.2370 Fails to update via GUI with missing script error

### ISSUE THREAD

**Issue by Nostang3** [causefx/Organizr#1899]
###### Operating System: TrueNAS-13.0-U3.1 - FreeBSD
<hr>

##### Problem Description:

I"m trying to update via the GUI and it's saying `Update Error Update script permissions error` in a pop up window. The logs show a warning for `Update script doesn't exist`. If I navigate to `/usr/local/www/Organizr/scripts/` I see `linux-update.sh` exists with `-rwxrwxr-x  1 www  www  1286 Oct  4 20:33 linux-update.sh` for permissions and ownership. 

I think this issue happened on the last version update but I manually ran the script from the directly to update and didn't make a post about it thinking it might get resolved in the next update or something. I haven't changed any permissions or ownership for this to start happening. Did I miss a change lately that caused this?

<hr>

##### Reproduction Steps:

Normal GUI update.
<hr>

#### Errors on screen?  If so paste here:

If I look at the log Details this is in the context section:

```
"file": "/usr/local/www/Organizr/scripts/linux-update.sh v2-master > /usr/local/www/Organizr/scripts/log.txt 2>&1"

```

**Comment by WanderlustRaincoat** [comment]
I too am getting this same message and manually handled it last time. Interested as well to see if I need to adjust something to have the GUI update work.
edit: figured I should add I am running on an Ubuntu 18.04 VM

**Comment by spuniun** [comment]
This same issue persists through versions 2.1.2380 and 2.1.2400

**Comment by ProtoGitt** [comment]
Same issue here, permissions are definitely fine.

**Comment by causefx** [comment]
Can you run ls-lah on the scripts directory?Sent from my iPhoneOn Jan 5, 2023, at 3:52 PM, ProtoGitt ***@***.***> wrote:﻿
Same issue here, permissions are definitely fine.

**Comment by ProtoGitt** [comment]
Sure thing. Permissions on the scripts directory are:
`drwxr-xr-x  2 www-data www-data 4.0K Oct  1 20:32 scripts`

Scripts folder contents permissions:
```
-rwxr-xr-x  1 www-data www-data 1.3K Oct  1 20:32 linux-update.sh
-rw-r--r--  1 www-data www-data 807K Oct  1 20:32 log.txt
-rw-r--r--  1 www-data www-data 2.3K Oct  1 20:32 windows-update.bat
```

**Comment by Nostang3** [comment]
Here is mine. Everything looks to be www:www in mine. From `Organizer/` folder down. 

```
root@organizr:/usr/local/www/Organizr/scripts # ls -lah
total 27
drwxr-xr-x   2 www  www     5B Oct  4 20:34 .
drwxr-xr-x  15 www  www    24B May 28  2022 ..
-rwxrwxr-x   1 www  www   1.3K Oct  4 20:33 linux-update.sh
-rw-r--r--   1 www  www    63B Oct  4 20:27 log.txt
-rw-r--r--   1 www  www   2.3K Oct  4 20:33 windows-update.bat
```

**Comment by Swiftnesses** [comment]
Same issue here.

**Comment by codedesperate** [comment]
Exact same issue. I ran the linux-update.sh script manually and worked without issue. The GUI gave me the permissions error.

**Comment by reloxx13** [comment]
+1

**Comment by causefx** [comment]
if anyone has time we can try a remote session to try and fix this

**Comment by causefx** [comment]
fuck -  i think i know the issue!

**Comment by causefx** [comment]
if anyone would like to test out the latest change that would help greatly.

**Comment by ProtoGitt** [comment]
Yup downloaded and replaced the update-functions.php file. Update worked without an issue via the GUI. Running 2.1.2400 now.

**Comment by codedesperate** [comment]
Great work @causefx ! I have updated the update-functions.php file as well. I am already on newest version, so I will see next time there is an update. If I still get the error I'll report back here.

**Comment by causefx** [comment]
thanks guys. i'll merge to master today

**Comment by Nostang3** [comment]
> if anyone would like to test out the latest change that would help greatly.

I can test now that I'm home. How do I find the update file(s)?

EDIT: Github is only letting me comment and close the file at the same time. What is this crap?

**Comment by WanderlustRaincoat** [comment]
Applied the latest update from today after updating the file and it was successful for me.

**Comment by causefx** [comment]
awesome!!! thank you

**Comment by Nostang3** [comment]
I am still getting permission errors and Update Script doesn't exist when trying the new  .2420

**Comment by WanderlustRaincoat** [comment]
Did you manually update that file? You either need to either replace or update the existing file for update-functions.php. I just mv the existing to .old and made a new file, pasted the whole deal in from https://raw.githubusercontent.com/causefx/Organizr/5858680b406dfb507d2a1f11226288f5120ec577/api/functions/update-functions.php.

**Comment by causefx** [comment]
did you make the change listed on the commit above, if not manually run the script and you will no longer need to do that.

**Comment by Nostang3** [comment]
I replaced the file that was linked above by underoath23 but when I run the update via GUI it doesn't give me an error but it doesn't update. If I understand you I should run the update script in the scripts folder now and going forward I should be fine?

**Comment by causefx** [comment]
so you are still on the old version?

**Comment by Nostang3** [comment]
I"m on 2.1.2370.

**Comment by codedesperate** [comment]
@causefx As promised I just tested the script now that there is a new update. Worked flawlessly! :D

**Comment by causefx** [comment]
@mikkelzzz3 thank you.

@Nostang3 anything in logs?

**Comment by Nostang3** [comment]
@causefx No, the only thing showing in the log section is my access to admin setting page.

**Comment by causefx** [comment]
anything in scripts folder log.txt?

**Comment by Nostang3** [comment]
`sh: /usr/local/www/Organizr/scripts/linux-update.sh: not found`

And I just checked and the file is there with www:www and executable property.

**Comment by causefx** [comment]
is this running in a jail?

does `/bin/bash` exist?

**Comment by Nostang3** [comment]
Yes, running in an truenas iocage jail and no /bin/bash does not exist.

**Comment by causefx** [comment]
@Nostang3 @mikkelzzz3 @ProtoGitt @underoath23 
can each of you change the shebang on the linux script file to `#!/usr/bin/env bash` and see if it still works?

**Comment by ProtoGitt** [comment]
Changed it, ran it manually and still works. I'm running it on Ubuntu 20.04 for what it's worth.

**Comment by causefx** [comment]
thank you.

**Comment by Nostang3** [comment]
@causefx I changed the line in `linux-update.sh` but it still won't update via the gui. Would you like me to run it manually?

Edit: There is no errors in the GUI tab and same error in the `log.txt` but it is the from earlier by the date/time stamp.

**Comment by causefx** [comment]
you can try manually running it to see what happens

**Comment by Nostang3** [comment]
Manually running the file updated things but that's how it worked on the last update. I had to manually run it because it wouldn't work from the GUI.

**Comment by causefx** [comment]
1. clear the log.txt. file
2. change the shebang once more to : `#!/usr/bin/env bash`
3. click this button: 

![image](https://user-images.githubusercontent.com/16184466/214968886-77fa9d87-a5a3-4ead-bd05-60fe960830ef.png)

report back what happens and what log.txt. says

**Comment by Nostang3** [comment]
I'll attach the file too but here is everything after the extracting. I thumbed through most of the directories listed that I could find and they were all www:www. 

```
cp: /usr/local/www/Organizr/scripts/../plugins/images/tabs/zwavejs.png: Permission denied
cp: /usr/local/www/Organizr/scripts/../plugins/images/tabs/Duplicati.png: Permission denied
cp: /usr/local/www/Organizr/scripts/../js/langpack/ar-sa[Arabic (Saudi Arabia)].json: Permission denied
cp: /usr/local/www/Organizr/scripts/../api/vendor/Expectation.php: Permission denied
cp: /usr/local/www/Organizr/scripts/../api/homepage/prowlarr.php: Permission denied
cp: /usr/local/www/Organizr/scripts/../api/homepage/adguard.php: Permission denied
cp: /usr/local/www/Organizr/scripts/../api/plugins/shuck-stop/cron.php: Permission denied
cp: /usr/local/www/Organizr/scripts/../api/plugins/shuck-stop/config.php: Permission denied
cp: /usr/local/www/Organizr/scripts/../api/plugins/shuck-stop/drives.json: Permission denied
cp: /usr/local/www/Organizr/scripts/../api/plugins/shuck-stop/logo.png: Permission denied
cp: /usr/local/www/Organizr/scripts/../api/plugins/shuck-stop/api.php: Permission denied
cp: /usr/local/www/Organizr/scripts/../api/plugins/shuck-stop/plugin.php: Permission denied
```
[log.txt](https://github.com/causefx/Organizr/files/10514080/log.txt)

**Comment by codedesperate** [comment]
> @Nostang3 @mikkelzzz3 @ProtoGitt @underoath23 can each of you change the shebang on the linux script file to `#!/usr/bin/env bash` and see if it still works?

Changed /scripts/linux-update.sh and ran manually, still works. I'm on Ubuntu Server 22.04

**Comment by reloxx13** [comment]
how to update now with the broken script in docker?

**Comment by causefx** [comment]
@reloxx13 nothing was changed for docker, what error do you have?

**Comment by causefx** [comment]
@Nostang3 when i get home from out of town i will keep looking into this.

**Comment by Nostang3** [comment]
> @Nostang3 when i get home from out of town i will keep looking into this.

No rush. I'm currently out of town myself till Monday night so I couldn't dedicate much time to troubleshooting.

**Comment by causefx** [comment]
thank you.

**Comment by reloxx13** [comment]
> @reloxx13 nothing was changed for docker, what error do you have?

the same as OP, i cannot update over gui, it says updating but the version stays the same.
i tried rebuilding the docker with pulling latest image (tried both dev & master).
And i also tried the force git update which also did not change anything, still old version.

~~forget it, i wanted to gather logs and version now for bugreort and just saw its on another version now and not prompting to update anymore. does it also autoupdate ? i also have watchtower running for docker image updated so anyway, something has happed and updated now. thank you.~~

**Comment by causefx** [comment]
can you check the container logs?Sent from my iPhoneOn Jan 29, 2023, at 2:30 PM, reloxx13 ***@***.***> wrote:﻿

@reloxx13 nothing was changed for docker, what error do you have?


@reloxx13 nothing was changed for docker, what error do you have?

the same, i cannot update over gui, it says updating but the version stays the same.
i tried rebuilding the docker with pulling latest image (tried both dev & master).
And i also tried the force git update which also did not change anything, still old version.

**Comment by reloxx13** [comment]
im sorry i was wrong, its not fixed and not updated, stuck at 2.1.2370.    
I was stressed yesterday and did not check it correctly.    
[_Organizr_logs.txt](https://github.com/causefx/Organizr/files/10534246/_Organizr_logs.txt)

i remove the lockfile in the container `rm /config/www/organizr/.git/index.lock`
added +x to the linux script `chmod +x /config/www/organizr/scripts/linux-update.sh`
ran the script `/config/www/organizr/scripts/./linux-update.sh`

its up-to-date now

![grafik](https://user-images.githubusercontent.com/14855001/215440098-b947dec4-d535-4185-b6dd-a286446cedb6.png)

**Comment by Swiftnesses** [comment]
I updated manually via the script, then tried a force branch install from the GUI, same permissions error. Script works fine manually still.

Any ideas @causefx?

**Comment by causefx** [comment]
what branch @Swiftnesses

**Comment by Nostang3** [comment]
@causefx Should I reopen this since it still won't update? I tried 2.1.2430 and it gives no errors in the GUI. In the script folder the log file says: 

`sh: /usr/local/www/Organizr/scripts/linux-update.sh: not found`

**Comment by causefx** [comment]
paste the contents of the linux update file here please. also anything in organizr log?

**Comment by Nostang3** [comment]
```
#!/bin/bash
if [ -z "$1" ]
  then
  echo 'No branch setup.. using v2-master'
  BRANCH="v2-master"
elif [ "$1" == "v2-develop" ] || [ "$1" == "develop" ] || [ "$1" == "dev" ]
  then
  BRANCH="v2-develop"
elif [ "$1" == "v2-master" ] || [ "$1" == "master" ]
  then
  BRANCH="v2-master"
else
  echo "$1 is not a valid branch, exiting"
  exit 1
fi
SCRIPTPATH="$( cd -- "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )"
UPGRADEPATH=$SCRIPTPATH"/upgrade"
UPGRADEFILE=$SCRIPTPATH"/upgrade/upgrade.zip"
FOLDER=$UPGRADEPATH"/Organizr-"${BRANCH#v}
URL=https://github.com/causefx/Organizr/archive/${BRANCH}.zip
mkdir -p $UPGRADEPATH                                                  && \
curl -sSL ${URL} > $UPGRADEFILE                                        && \
unzip $UPGRADEFILE -d $UPGRADEPATH                                     && \
cd $FOLDER                                                             && \
cp -r ./ $SCRIPTPATH/../                                               && \
cd $SCRIPTPATH                                                         && \
rm $UPGRADEFILE                                                        && \
rm -rf $FOLDER                                                         && \
rm -rf $UPGRADEPATH                                                    && \
exit 0
```
Nothing shows in the gui. The only log file I could find was the one in the scripts folder and it shows what I put up in my last comment. I did a recursive search and I found a couple `log.php` files. Do you want them?

**Comment by causefx** [comment]
after changing the shebang on that script file and running the update again. what happens

**Comment by Nostang3** [comment]
I changed it to match the line in match the latest: `#!/usr/bin/env bash` and now when I run it I get this in the log file after skipping the creating process: 

```
cp: /usr/local/www/Organizr/scripts/../plugins/images/tabs/zwavejs.png: Permission denied
cp: /usr/local/www/Organizr/scripts/../plugins/images/tabs/Duplicati.png: Permission denied
cp: /usr/local/www/Organizr/scripts/../js/langpack/ar-sa[Arabic (Saudi Arabia)].json: Permission denied
cp: /usr/local/www/Organizr/scripts/../api/vendor/Expectation.php: Permission denied
cp: /usr/local/www/Organizr/scripts/../api/homepage/prowlarr.php: Permission denied
cp: /usr/local/www/Organizr/scripts/../api/homepage/adguard.php: Permission denied
cp: /usr/local/www/Organizr/scripts/../api/plugins/shuck-stop/cron.php: Permission denied
cp: /usr/local/www/Organizr/scripts/../api/plugins/shuck-stop/config.php: Permission denied
cp: /usr/local/www/Organizr/scripts/../api/plugins/shuck-stop/drives.json: Permission denied
cp: /usr/local/www/Organizr/scripts/../api/plugins/shuck-stop/logo.png: Permission denied
cp: /usr/local/www/Organizr/scripts/../api/plugins/shuck-stop/api.php: Permission denied
cp: /usr/local/www/Organizr/scripts/../api/plugins/shuck-stop/plugin.php: Permission denied
```

Here is the permissions for those last files. From the looks of the other ones I can find they are the same `www:www`.


```
root@organizr:/usr/local/www/Organizr/scripts/upgrade/Organizr-2-master/api/plugins/shuck-stop # ls -l
total 739
-rw-r--r--  1 www  www    1725 Jan 25 15:07 api.php
-rw-r--r--  1 www  www     446 Jan 25 15:07 config.php
-rw-r--r--  1 www  www     343 Jan 25 15:07 cron.php
-rw-r--r--  1 www  www   40257 Jan 25 15:07 drives.json
-rw-r--r--  1 www  www  716056 Jan 25 15:07 logo.png
-rw-r--r--  1 www  www   11613 Jan 25 15:07 plugin.php

```

**Comment by Swiftnesses** [comment]
Any update on this, for now I'm just running linux-update.sh manually...
