### ISSUE TITLE
2FA Support

### ISSUE THREAD

**Issue by rix1337** [causefx/Organizr#19]
For the security fanatics out there.

Why not include Google 2FA sometime in the future?

**Comment by causefx** [comment]
that's a good idea but I'm not sure i will have enough time to do it.  Let me see if my buddy wants to help on this one.

**Comment by rix1337** [comment]
not a priority. its about the potential your project has :)

**Comment by rix1337** [comment]
This looks promising (well written readme)

RobThree/TwoFactorAuth/blob/master/README.md

**Comment by causefx** [comment]
i will bookmark this.

**Comment by JigSawFr** [comment]
@rix1337 very usefull library, used to create a plugin for a professionnal community system !

**Comment by petersry** [comment]
[Authy](https://www.authy.com/developers/) also has libraries for integrating their service or TOTP/Google 2FA.

**Comment by causefx** [comment]
I will look into this later on :)

**Comment by Cerothen** [comment]
I like this idea, I'll see what I can swing

**Comment by mow4cash** [comment]
+1 for 2FA.

**Comment by IronTooch** [comment]
Another possibility (that is used in Guacamole) is Duo. Similar operation to Google's, works well in the Guacamole project (duo.com).

**Comment by StevenChorkley** [comment]
I would love 2fa!!

**Comment by causefx** [comment]
this will be implemented in 2.0, if you have more FR, please post on http://feathub.com/causefx/Organizr

**Comment by XDGFX** [comment]
Do we have any update regarding this now 2.0 is in beta? Maybe it will be out with the full release?

**Comment by causefx** [comment]
yes. it is completed in the beta. full release very soon.
