### ISSUE TITLE
Watching trailers on plex causes php errors on home page

### ISSUE THREAD

**Issue by roblandry** [causefx/Organizr#190]
When someone watches a trailer on plex, the homepage displays errors because "clip" is not found so the variables are not defined. Adding this fixes.         

Change line
[#334](https://github.com/causefx/Organizr/blob/a1ebdc594092ee2bd3cf28a12d6cbe67c8f863df/functions.php#L334) to

		}elseif($type == "clip"){

			$title = $child['title'];
			$summary = ($child['summary'] != "" ? $child['summary'] : "<i>No summary loaded.</i>");
			$thumb = ($child['thumb'] != "" ? $child['thumb'] : 'images/nadaplaying.jpg');
			$image = "movie";
			$height = "150";
			$width = "100";
		}

I also added a bit of error checking as i dont think any summary is loaded and i dont think a good thumb is added.

**Comment by causefx** [comment]
lol i didnt even people watch clips...  learned something new today.

**Comment by roblandry** [comment]
yeah, its for trailers. I actually changed the code to include the words trailer also. Changed it to read:

	}elseif($type == "clip"){

		$title = $child['title'].' - Trailer';
		$summary = ($child['summary'] != "" ? $child['summary'] : "<i>No summary loaded.</i>");
		$thumb = ($child['thumb'] != "" ? $child['thumb'] : 'images/nadaplaying.jpg');
		$image = "movie";
		$height = "150";
		$width = "100";
	}

**Comment by roblandry** [comment]
i am not sure of any other reason for the type "clip". maybe there is. I even tried watching a home video on plex and it showed as a "movie" so for now i think this is safe.

**Comment by causefx** [comment]
thanks, i'll include
