### ISSUE TITLE
Changed Plex account password and Plex SSO no longer works

### ISSUE THREAD

**Issue by ehaughee** [causefx/Organizr#1900]
###### Operating System: Ubuntu
<hr>

##### Problem Description:
I changed my Plex account password and now I cannot log into Organizr with the new credentials.

Apologies if this was already answered but I couldn't find anything from multiple searches.

<hr>

##### Reproduction Steps:
1. Setup Organizr with Plex SSO
2. Change Plex account password
3. Try to login

<hr>

#### Errors on screen?  If so paste here:
```
In a toast:

Login error
User credentials incorrect
```

**Comment by causefx** [comment]
was it the admin password?  usually that invalidates the plex Token.  if that is the case just update the plexToken field in the /data/config/config.php file

**Comment by ehaughee** [comment]
That sounds right.  How do I retrieve the new Plex token?

Also, my `volumes` section of my docker-compose.yaml file has `/home/eric/docker/organizr:/config` but in `/home/eric/docker/organizr` there is no `data` folder nor `config` folder.  I see the following folders: keys, log, nginx, php, and www.  Is something misconfigured there?

**Comment by causefx** [comment]
i believe its `/home/eric/docker/organizr/www/organizr/data/config`

**Comment by ehaughee** [comment]
Thanks 👍🏻

Assuming I got the correct token (followed [these instructions](https://support.plex.tv/articles/204059436-finding-an-authentication-token-x-plex-token/)), I replaced the `plexToken` value in `/home/eric/docker/organizr/www/organizr/data/config/config.php` with the new token and restarted the container but still get the same issue.

**Comment by ehaughee** [comment]
Any thoughts?  Current best option seems to be a complete reinstall which is unfortunate.

**Comment by ehaughee** [comment]
Digging around some more, I've noticed that the form data from the login submission has empty `oAuth` and `oAuthType` parameters.  Not sure if that matters.  Continuing to investigate.

**Comment by ehaughee** [comment]
Ok I've tried to statically follow the code and I think I am failing the password hash check at this line: https://github.com/causefx/Organizr/blob/v2-master/api/classes/organizr.class.php#L3730

So it seems like the password hash from the request does not match the item in a database.  Not sure if the `plexToken` has anything to do with that or not.

**Comment by causefx** [comment]
i can jump on discord today to remote in and try and help you.

**Comment by ehaughee** [comment]
I can't today but I appreciate the offer.  Is there an easy way, from within the docker container, to check the contents of the db?  That was going to be my next attempt, manually modify the db.

**Comment by causefx** [comment]
the password is salted in the DB... you can use db browser for sqlite

**Comment by ehaughee** [comment]
I see a couple potentially interesting things about my user entry
1. `plex_token` is empty, maybe expected given I'm the admin though
2. `auth_service` is internal, which isn't surprising at this point given I saw the log entries from that code path but I am surprised given I thought I was using plex auth.

I am now wondering if I made a mistake during setup and just ended up using my plex email and password for login without using plex as an SSO provider.  However, I was unable to login after changing my plex password so I'm not sure.

As far as the salting, is the salt defined during install and then stored somewhere on disk?  If so, where does it get stored?

**Comment by causefx** [comment]
if it's internal password change on plex shouldn't have mattered. for now change that field to "both". 


then change backend to "plex"

**Comment by ehaughee** [comment]
Ok changed `auth_service` for my (and the only) user in Organizr `users` table to `both` and set `authBackend` to `plex`.  Then ran `docker compose down` and `dock compose up -d` in my organizr dir but I still get "User credentials incorrect".

**Comment by causefx** [comment]
sorry i meant on config.php

**Comment by ehaughee** [comment]
Ok, in `config.php` I set `authType` to `both` and `authBackend` is still `plex`.  Did a restart with docker and still get "credentials incorrect".  Also tried resetting my user's `auth_service` back to `internal` but same issue.

Also, just to clarify, I appreciate the responses but I am not in a hurry so a response whenever you have some free time is totally fine by me (not that it would matter if it wasn't fine haha).

**Comment by causefx** [comment]
can you check the logs? Sent from my iPhoneOn Jan 24, 2023, at 6:19 PM, Eric Haughee ***@***.***> wrote:﻿
Ok set I set authType to both and authBackend is still plex.  Did a restart with docker and still get "credentials incorrect".  Also tried resetting my user's auth_service back to internal but same issue.

**Comment by causefx** [comment]
also make sure to have your plex admin username or email in the confit value of plexAdmin

**Comment by ehaughee** [comment]
I do and here are the log entries from my latest login attempt:

I obfuscated my email below mainly to avoid scrapers but it is the same email in the `plexAdmin` configuration value and the one I am using for username during login.

```json
{"log_level":"DEBUG","message":"Starting OAuth login check","channel":"Oauth","username":"Guest","trace_id":"225f6694-4fe6-4451-a49b-209886b8656f","file":"/config/www/organizr/api/classes/organizr.class.php","line":352,"context":[],"remote_ip_address":"192.168.1.11","server_ip_address":"172.23.0.2","user_agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/109.0","datetime":"2023-01-25 01:31:18.405893","timezone":"UTC","process_time":5.8689117431640625}
{"log_level":"DEBUG","message":"OAuth not triggered","channel":"Oauth","username":"Guest","trace_id":"db460759-02c2-4401-8fdd-4b42c4999d6e","file":"/config/www/organizr/api/classes/organizr.class.php","line":368,"context":{"enabled":false,"header_name":"","header_name_email":"","whitelist":""},"remote_ip_address":"192.168.1.11","server_ip_address":"172.23.0.2","user_agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/109.0","datetime":"2023-01-25 01:31:18.411895","timezone":"UTC","process_time":0.016927719116210938}
{"log_level":"DEBUG","message":"Starting login function","channel":"Authentication","username":"<obfuscated email>","trace_id":"d6c8d094-333f-4f7d-9bdc-b510f0c3b6ba","file":"/config/www/organizr/api/classes/organizr.class.php","line":3677,"context":[],"remote_ip_address":"192.168.1.11","server_ip_address":"172.23.0.2","user_agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/109.0","datetime":"2023-01-25 01:31:18.415832","timezone":"UTC","process_time":0.017881393432617188}
{"log_level":"WARNING","message":"Wrong Password","channel":"Authentication","username":"<obfuscated email>","trace_id":"1400c1b7-5fde-4c6e-b966-b77320311511","file":"/config/www/organizr/api/classes/organizr.class.php","line":3851,"context":[],"remote_ip_address":"192.168.1.11","server_ip_address":"172.23.0.2","user_agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/109.0","datetime":"2023-01-25 01:31:19.035272","timezone":"UTC","process_time":0.029802322387695312}
{"log_level":"DEBUG","message":"User has not exceeded maximum login attempts","channel":"Authentication","username":"<obfuscated email>","trace_id":"eb186999-fe49-4713-9bd4-915c193e3ce4","file":"/config/www/organizr/api/classes/organizr.class.php","line":3858,"context":[],"remote_ip_address":"192.168.1.11","server_ip_address":"172.23.0.2","user_agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/109.0","datetime":"2023-01-25 01:31:19.035382","timezone":"UTC","process_time":0.014066696166992188}
```

**Comment by causefx** [comment]
lastly try switching this config value to true. plexoAuth

then use that button to login.

**Comment by ehaughee** [comment]
And that got me in!  I must've done something wrong in the setup process because it's never actually used Plex as an OAuth provider for login before.  Thanks for your help.  I assume next time I change my Plex password it will just work (or I may have to change my Plex token but that's not too bad).

Thanks again 👍🏻

**Comment by causefx** [comment]
yeah if you change plex admin password you will need to refresh the token.  also by any chance do u have 2fa on plex acct?

**Comment by ehaughee** [comment]
I do have 2fa on for Plex

**Comment by causefx** [comment]
yeah using the password for plex without oauth requires you to add the 2fa at the end of password i believe. u can try it if you like.
