### ISSUE TITLE
Multiple Errors on Tab Editor

### ISSUE THREAD

**Issue by dlwebmaestro** [causefx/Organizr#1903]
###### Operating System: Windows 11 Pro Version 22H2
<hr>

##### Problem Description:
Whenever I add a new tab, if I try to switch the "Active" toggle to green, I get a "Tab Enable Error"
Additionally, I cannot activate or de-activate any existed tabs without getting the same error. 
I also get a "Tab Type Error" whenever I try to change any of the Tab Types.
In fact, anything I try on the Tab Editor results in an error.

<hr>

##### Reproduction Steps:
Change tab type, or...
Make tab active, or...
Make tab inactive, or...
change any option on Tab Editor for that matter. 

<hr>

#### Errors on screen?  If so paste here:

```
Tab Category Error
Tab Group Error
Tab Type Error
Tab Enable Error
Tab Splash Error
Tab Ping Error
Tab Preload Error
Tab Add to Admin Error
```

**Comment by causefx** [comment]
Can you check the webserver logs?  It may be blocking PUT - POST - DELETE methods

**Comment by dlwebmaestro** [comment]
Sorry for the delay; I've been out of the country. You are absolutely correct, sir! I have edited my nginx.conf accordingly and everything is gravy. Thank you!
