### ISSUE TITLE
linux_update script not wirking on freebsd jail

### ISSUE THREAD

**Issue by GunbleR** [causefx/Organizr#1906]
Organizr Version: V 2.1.2400
Branch: Master
WebServer: Nginx
Operating System: Freebsd 13.1 jail (truenas core)

in freebasd **jail**, bash installs in /usr/local/bin/bash thus update script fails.
editing the script's shebang from #!/bin/bash to #!/usr/local/bin/bash fixes the issue 
(in addition to freebsd specific fix in [1881](https://github.com/causefx/Organizr/issues/1881)).
imo pin this issue untill (if) you implement a fix

**Comment by causefx** [comment]
hmmm... i need to see if i can differentiate between the two.

**Comment by causefx** [comment]
can you test if this shebang works: `#!/usr/bin/env bash`

**Comment by PWTech98** [comment]
Hi i am experiencing the same issue and makeing them changes did not fix the issue.
