### ISSUE TITLE
Script File Permissions Error - QNap Organizr Update

### ISSUE THREAD

**Issue by baxterblk** [causefx/Organizr#1908]
###### Operating System: QTS - QNap NAS TS h251+
<hr>

##### Problem Description:

Expected behaviour:
Update when updates are available
Currently Behaviour:
Getting "Script Permissions Error" and don't know where to look for this script nor what permissions are needed.
**note**-- this is not installed as a docker; it's a natural .qpkg

<hr>

##### Reproduction Steps:

<hr>

#### Errors on screen?  If so paste here:

```
Update Script Permissions Error
```

**Comment by causefx** [comment]
I added a change that i just need someone to test

**Comment by baxterblk** [comment]
Hello 👋
How can I help?

**Comment by causefx** [comment]
hey there. it seems they tested the fix on the other thread. i will merge to master today.

**Comment by baxterblk** [comment]
Great! Let me know if I can help further down the road.

Also, I wasn't aware that I was part of this group?
Where might I have signed up for these emails??
It's not a problem as I am eager to help but am curious how this started.

Thank you!

**Comment by causefx** [comment]
are you talking about emails for this thread or the other thread i mentioned? if this thread, GH automatically sets up the email alerts when you opened the issue. you can toggle it online to the right side
