### ISSUE TITLE
ICal Not really Working

### ISSUE THREAD

**Issue by reddexx** [causefx/Organizr#1909]
###### Operating System: Raspian (Docker)
<hr>

##### Problem Description:
Only 1 entry
![image](https://user-images.githubusercontent.com/6242840/213000959-539d61ae-6e00-441e-aa06-93269d91f28c.png)

in my Google Calendar is this
![image](https://user-images.githubusercontent.com/6242840/213001181-8f410f23-0d5e-46cd-ad84-dacf47c321e7.png)

here my iCAL URL:
https://calendar.google.com/calendar/ical/a1a38e38efac3af9f760187bb2944b019e870a50a0a5129460f1a541fe8c2dde%40group.calendar.google.com/public/basic.ics

**Comment by causefx** [comment]
i’ll check this outSent from my iPhoneOn Jan 17, 2023, at 1:09 PM, reddexx ***@***.***> wrote:﻿

Organizr Version: V2.1.2400
Branch: Latest (Docker)
WebServer: Nginx/Apache
Operating System: Raspian (Docker)

Problem Description:
Only 1 entry

in my Google Calendar is this

here my iCAL URL:
https://calendar.google.com/calendar/ical/a1a38e38efac3af9f760187bb2944b019e870a50a0a5129460f1a541fe8c2dde%40group.calendar.google.com/public/basic.ics

**Comment by causefx** [comment]
if you are on dev try the latest commit.

**Comment by reddexx** [comment]
Working, very Thanks.

is it possible to get a local calendar with import function?

**Comment by causefx** [comment]
can you elaborate a little more on that please?

**Comment by reddexx** [comment]
a local Calendar with import Function (Upload a .ICS file to the Local Calendar)
and create new Calendar Entry´s
