### ISSUE TITLE
AuthRequest - Cookies are not valid for subdomains

### ISSUE THREAD

**Issue by JigSawFr** [causefx/Organizr#191]
Hello,
I try to use AuthRequest with subdomains, for examples:
- www.domain.fr -> Organizr
- torrents.domain.fr -> Rutorrent

Actually it's done in Nginx Config,
The only thing that prevent me to enter to Rutorrent,
Is that cookies set by Organizr are not valid for subdomains,
But only for www.domain.fr (must be to domain.fr to work)

Can you fill domain option when using setCookie function in PHP to create subdomains accessible cookies ?

Thanks you !

**Comment by JigSawFr** [comment]
Successfully tested by replacing the 14 set cookie functions in user.php
Now AuthRequest works great with subdomains config :)

**Comment by causefx** [comment]
have you tried the auth.php yet?

**Comment by JigSawFr** [comment]
@causefx yes i use auth.php too, but user can't be granted as cookies set by main domain are not valid for subdomains (where I use AuthRequest with proxy pass). Adding just "domain.fr" as domain option to set cookie functions in user.php solve the problem ;)

**Comment by causefx** [comment]
so you actually typed in your domain?  i was wondering if "./" would work

**Comment by JigSawFr** [comment]
@causefx for example in my case:

```
setcookie("Organizr", $this->get_user_token($username), time() + (86400 * 7), "/", 'domain.fr');
setcookie("OrganizrU", $username, time() + (86400 * 7), "/", 'domain.fr');
```

and **in servers block for subdomains**, i added:

```
error_page 400 401 402 403 404 https://www.domain.fr/error.php?error=$status;

	location = /auth-admin {
    	internal;
    	proxy_pass https://www.domain.fr/auth-admin;
    	proxy_pass_request_body off;
    	proxy_set_header Content-Length "";
    	#proxy_set_header X-Original-URI $request_uri;
	}
```

And now auth works for any subdomains (*.domain.fr).

**Comment by causefx** [comment]
not sure how i would do this with messing something up for other users with more complex domains.  

i.e.  www.example.co.uk or en.this.example.com

I could use `$_SERVER['HTTP_HOST']` but like i said, could mess things up for other people.  I could include an option in settings, and let users decide what goes in....

**Comment by JigSawFr** [comment]
@causefx yes, the better choice is to add an option in my mind (why not with $_SERVER['HTTP_HOST'] used to suggest domain in input), but if we use a reverse proxy, we need to override this var by setting manually your input :)

**Comment by causefx** [comment]
coding it now
