### ISSUE TITLE
Login to Organizr via External Auth Proxy Prompts for 2FA Code, But Cannot Login

### ISSUE THREAD

**Issue by owine** [causefx/Organizr#1910]
###### Operating System: Ubuntu 22.04
<hr>

##### Problem Description:
When accessing Organizr via an external auth proxy (Traefik/Authelia) and 2FA configured for the existing Organizr user, the login page prompts for 2FA code to login to Organizr. When populating the 2FA code, Organizr does not login and displays an error regarding missing username. If I disable 2FA on the Organizr user, the login occurs without intervention.

I'm not sure if the intended behavior is for the auth proxy to bypass 2FA (this would be my preference) or to prompt for 2FA, but either way it is not working as intended.

<hr>

##### Reproduction Steps:
Configure Organizr user to require TOTP 2FA
Configure Auth Proxy to recognize `Remote-User` header from Authelia.
Access Organizr while authenticated to proxy
Observe 2FA code prompt
![CleanShot 2023-01-19 at 11 21 41](https://user-images.githubusercontent.com/4283702/213515678-84af4c37-25f3-476f-adb6-d294b80596ca.png)
Populate 2FA code and submit
Observe error
![CleanShot 2023-01-19 at 11 21 52](https://user-images.githubusercontent.com/4283702/213515759-694427b8-45d0-466d-8b0f-c9ad31353fbd.png)

<hr>

#### Errors on screen?  If so paste here:

```
Screenshots above
```

**Comment by causefx** [comment]
lemme look into it

**Comment by causefx** [comment]
try latest dev commit plz

**Comment by owine** [comment]
That fixes it - thanks!
