### ISSUE TITLE
Updating is a pain for seedbox users

### ISSUE THREAD

**Issue by jsmdy** [causefx/Organizr#1912]
###### Operating System: Ubuntu
<hr>

##### Problem Description:
Maybe it's secondary, but I'm using Organizr on a seedbox service, I can't update version directly from the app, I've to uninstall/reinstall to get last version (some app on my seedbox, like radarr, can updated but some, like Organizr don't). This is the origin of my trouble but, there is a manual solution with backup/restore. 
The problem is, I can backup but I can't restore, as there is still no restore possibility from a downloaded .zip, we need to put unzipped files it in the right folder. But I can't access in the irght db folder,  nore with the filebrowser or SSH access of my seedbox, in fact there is 0 folder of organizr. 

So it can be really great (I won't update until it will be resolve, as I will lost time at each update to reconfig everything), if there is an "external" folder (in .config by example) to make a link of accessibility with the db folder. Or a possibility to download a backup zip.

<hr>

```

```

**Comment by causefx** [comment]
What seedbox service?  I would like to see the logs if any to see where it fails to update.

**Comment by jsmdy** [comment]
seedit4me, I didn't have access to server logs it seems, is there a log page link in organizr? anyway I've to wait a future update to have something in a log as I can't downgrade app

**Comment by causefx** [comment]
can you goto settings page and paste the about portion?

**Comment by jsmdy** [comment]
![image](https://user-images.githubusercontent.com/62148532/218732184-6c65f6a8-372e-45e6-b92c-d2645457a48b.png)

**Comment by jsmdy** [comment]
the last update works, but I'd the same message than the previous update, with a blocking progress at 20%, but I left my PC and few hours after, when I update the page I see that I'm now using the last version... With my original update trouble, I can't affirm you I give more than 10min to the 20% stop and alert. So maybe the integrated update was fix in the 2.1.2420, or maybe user have to don't pay attention to alert and blockage at 20% and leave it some times for a working update.

I have to precise that when I re parameters last time, there is sometimes small windows alert, finally it works. But the Home page usage is a pain, its like it save app parameters randomly (or it takes some minutes, I tried hard browser refresh, no changes), I finally don't use the Home tab. Maybe there is a link, like an update communication trouble.

Sorry for all the approximative data, hope it can help you anyway.

**Comment by causefx** [comment]
now that you are on latest version, can you click the `Retrieve` button on the `Force Install Branch` section in Github page

**Comment by jsmdy** [comment]
done, it works well
