### ISSUE TITLE
500 response from web server; Error: Class 'Organizr' not found in /config/www/organizr/index.php:3

### ISSUE THREAD

**Issue by kencomputes** [causefx/Organizr#1921]
###### Operating System: Ubuntu
<hr>

##### Problem Description:
500 response from web server; see log error below.

<hr>

##### Reproduction Steps:

- Run docker image organizr/organizr as a service
- Attempt to connect to the web UI in a browser
- Observe 500 response in dev tools network tab

<hr>

#### Errors from log:
```
FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Class 'Organizr' not found in /config/www/organizr/index.php:3
```

**Comment by tronyx** [comment]
I just spun up another test container and it is fine. Can you check and see if there is anything else in the Org logs or the container logs? Maybe it didn't do the git pull correctly?

**Comment by kencomputes** [comment]
Hmm, yeah I spun up a new one and it works as expected. It looks like things have changed quite a bit since I initially set up my service, especially relating to the DB. I guess I'm just going to go back through all of the setup process again. Thanks for checking into this tronyx.
