### ISSUE TITLE
A removed user can still use organizr until they logout

### ISSUE THREAD

**Issue by jonathanturcotte** [causefx/Organizr#1925]
###### Operating System: Ubuntu 20.04
<hr>

##### Problem Description:
I've been doing some testing on removing a user on my setup and found that the removed user can still refresh, access tabs, etc, even after I delete them from the User Management tab. 

I am using Organizr with Authentication Type set to `Backend-Only`, and Authentication Backend set to `Plex`. I have stopped sharing the library with the test user and removed it as a friend on Plex, which correctly unshares the Plex library with that account. I then delete the user from the User Management page, which I would expect to force the user to re-login on next request, but when I refresh the Organizr page that the removed user has open it still allows them to do everything like they're still authenticated. Logging out the test user and then trying to log them back in using Plex SSO fails as expected.

I am assuming this is temporary until the Plex Auth token expires (or something like that), but I don't know how long it takes for that to expire. I would expect deleting the user from the User Management tab to invalidate that header or otherwise trigger a re-auth somehow when the user refreshes the page or tries to access something.

<hr>

##### Reproduction Steps:
 - As the admin: Setup Organizr Auth as above, with Type set to `Backend-Only`, and Backend set to `Plex`
 - As the admin: Share your plex library with a dummy plex user
 - As the dummy user: Log in to Organizr using that new plex account using Plex SSO so they now have Organizr open in a browser
 - As the admin: unshare the Plex library. Observe that the dummy plex user can no longer view the library
 - As the admin: delete the dummy user from the User Management tab
 - As the dummy user: refresh the Organizr browser window, or click on tabs, etc. Observe that the user can still do everything like normal.

<hr>

**Comment by causefx** [comment]
I will add token removal on user delete.   Good catch.

**Comment by causefx** [comment]
fixed in dev. thanks!
