### ISSUE TITLE
Require option for imprint and privacy policy on login page

### ISSUE THREAD

**Issue by RodBelaFarin** [causefx/Organizr#1927]
###### Operating System: Ubuntu
<hr>

##### Problem Description:
To launch my website in Germany using Organizr I would require the option to add an imprint and a privacy policy URL on the login page.

<hr>

##### Reproduction Steps:
Go to settings -> customize -> Login Page -> There is no option to add imprint and privacy policy URLs

<hr>

**Comment by RodBelaFarin** [comment]
still open.

**Comment by RodBelaFarin** [comment]
Hi,

nice to see activity on merge requests currently. May I put [this issue itself](https://github.com/causefx/Organizr/issues/1927#issue-1633731490) on the table again.

Btw @causefx I am a huge fan of this project of yours! I tried to add it "statically" and that kind of worked for me. But since I am using Organizr in a Container after an update it's gone again.

If you like, I could send you a PR with the changes I made to get it running for myself by changing your source code everytime after an update ^^
Maybe you can use that as a starting point to get it in a more elegant way done - I have absolotely no clue about PHP and it seems really complicated and unstructured from my point as a Python programmer - so maybe you better think of some option to add an imprint and a privacy policy URL on the login page by yourself in the first place ^^

> ###### Organizr Version: V Organizr Version 2.1.2430
> ###### Branch: Master
> ###### WebServer: Nginx
> ###### Operating System: Ubuntu
> ##### Problem Description:
> To launch my website in Germany using Organizr I would require the option to add an imprint and a privacy policy URL on the login page.
> 
> ##### Reproduction Steps:
> Go to settings -> customize -> Login Page -> There is no option to add imprint and privacy policy URLs

**Comment by causefx** [comment]
let me dive into this. :) gimmie a little bit.

**Comment by causefx** [comment]
send me what u have at the moment too. :)
