### ISSUE TITLE
Category editor not available when using Android

### ISSUE THREAD

**Issue by syskiller** [causefx/Organizr#1931]
###### Operating System: Ubuntu/doker
<hr>

##### Problem Description:

<hr>When using Android, it is not selected even if you press the basic setting, editor, and delete icon of the category editor

##### Reproduction Steps:

<hr>

#### Errors on screen?  If so paste here:

```

```

**Comment by causefx** [comment]
Can you screen-record that please?

 

From: syskiller ***@***.***> 
Sent: Tuesday, April 25, 2023 12:47 AM
To: causefx/Organizr ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [causefx/Organizr] Category editor not available when using Android (Issue #1931)

 


Organizr Version: V 1.x


Branch: Master/Develop


WebServer: Nginx/Apache


Operating System: Windows/MacOS/Ubuntu

  _____  


Problem Description:

  _____  


When using Android, it is not selected even if you press the basic setting, editor, and delete icon of the category editor 


Reproduction Steps:

  _____  


Errors on screen? If so paste here:
