### ISSUE TITLE
[Enhancement]allow nesting Categories

### ISSUE THREAD

**Issue by b52src** [causefx/Organizr#1936]
###### Operating System: Windows/MacOS/Ubuntu
<hr>

##### Enhancement Description:
Allow nesting Categories for tabs and Bookmarks

**Comment by HalianElf** [comment]
Feature requests belong on [here](https://feature.organizr.app)

**Comment by b52src** [comment]
hep sorry looks like it exists here: https://feature.organizr.app/posts/161/ability-to-create-multiple-unsorted-or-unnested-categories
