### ISSUE TITLE
Error when I want to update

### ISSUE THREAD

**Issue by fana13** [causefx/Organizr#194]
Hi,

When I want to proceed to update I've got this message : 

`Warning: mkdir(): File exists in /var/www/Organizr/settings.php on line 166
can't make dir
Fatal error: Uncaught Error: Class 'ZipArchive' not found in /var/www/Organizr/settings.php:204 Stack trace: #0 /var/www/Organizr/settings.php(270): unzipFile('upgrade.zip') #1 {main} thrown in /var/www/Organizr/settings.php on line 204`

Actual version : 1.20
Could help me please ?
Thanks ;)

**Comment by JigSawFr** [comment]
@fana13 lib ZpiArchive is missing from your php installation, app can't unzip download update.

**Comment by fana13** [comment]
Thanks @JigSawFr !!
Missing php-zip for me ;)

**Comment by JigSawFr** [comment]
You're welcome
