### ISSUE TITLE
Can't login to SABnzbd or Prowlarr

### ISSUE THREAD

**Issue by dma9** [causefx/Organizr#1942]
###### Operating System: Ubuntu 22.04
<hr>

##### Problem Description:

I recently installed SABnzbd (4.0.2) and added a tab in organizr  [2.1.2430) for it. Initially, it didn't work at (page wouldn't load) but managed to fix that by unchecking "x_frame_options" in SABnzbd's special settings. Unfortunately now I'm encountering a problem with logging into to SABnzbd as presented in Organizr. The login page appears, but when I fill in and click login, all it does is clear the fields. When setting up the tab for SABnzbd, I specified the IP address for SABnzbd, not the hostname as I had found a thread elsewhere that indicated this might fix the problem. 

I'm also now experiencing the same issue with Prowlarr, which has previously been working just fine.

Login for both works just fine when opening either in a new tab in the browser. I'm using Chrome. 

Not sure if it's relevant but I'm running Organizr, SABnzbd and Prowlarr in separate LXC containers, each running Ubuntu 22.04 and all hosted on a Debian server.

Any suggestions would be greatly appreciated.

<hr>

##### Reproduction Steps:

1. Add tab for SABnzbd using IP address of SABnzbd
2. Try to login to SABnzbd in Organizr
3. User and password fields are cleared. Login screen otherwise remains unchanged.
<hr>

#### Errors on screen?  If so paste here:

```

```

**Comment by HalianElf** [comment]
Sounds like a [SameSite](https://docs.organizr.app/help/faq/login-looping-samesite-errors) issue.

**Comment by klitzkedakota** [comment]
if you recently updated SABnzbd, i recommend going to SABnzbd configuration, under "special", and verifying that "x_frame_options" is unchecked. It must be unchecked.
