### ISSUE TITLE
[Feature Request] Require 2FA from users

### ISSUE THREAD

**Issue by BastionNtB** [causefx/Organizr#1945]
###### Operating System: Ubuntu 22.04.3 LTS
<hr>

##### Feature Description:

I think an option to require 2FA would be nice. It would require people to enroll into an 2FA of their choice when they log in next if they aren't setup already. Just an idea.

As always, love your work!
<hr>

**Comment by HalianElf** [comment]
This is not the place for Feature Requests and this Feature request already exists: https://feature.organizr.app/posts/108/option-to-enforce-2-factor-for-all-users
