### ISSUE TITLE
Google Authenticator disabling

### ISSUE THREAD

**Issue by krauthaus** [causefx/Organizr#1946]
###### Operating System: Ubuntu
<hr>

##### Problem Description:
My google auth stopped working. It claims my code is not correct.

<hr>

##### Reproduction Steps:

<hr>

#### Errors on screen?  If so paste here:

```

```

Ist there any way to deactivate the plugin without access to the web-backend? It is my server and I still got access to database, ubuntu, docker and all the fun stuff.

I looked in the db but was not very lucky finding something.

**Comment by causefx** [comment]
you need to edit the db in the user table, you will see the column for the authenticator - just delete the value

**Comment by krauthaus** [comment]
I tried that, but it wass not working. I only got "auth_service=internal" left.

**Comment by causefx** [comment]
did you write the changes to the db?  that field is the only thing that would pop up the 2fa box.
