### ISSUE TITLE
Calender not scaling on mobile

### ISSUE THREAD

**Issue by YaASlowpoke** [causefx/Organizr#1949]
###### Operating System: Unraid/Docker
<hr>

##### Problem Description:
The scaling of the calender item doesn't seem to work.

When on mobile, when only the "Calender" part of the homepage is active (IE. for guests) the available space isn't being used and stays near the top of the webpage in a small box. It instead should expand using a much larger portion of the screen.

Tested several themes that are included with Organizr, however these don't't change the results. Tested on a iPhone 13 Pro, please check the screenshot linked underneath.

<hr>

##### Reproduction Steps:

1. Go to settings;
2. Set "Homepage" to guest;
3. Under "Tabs Editor/Tabs" set everything else to either "User" or above;
4. Go to "Homepage Items";
5. Pick either/both Radarr/Sonarr active instance, whichever has past/future shows;
6. Fill in the necessary data to connect, enable it and save;
7. Navigate to organizr on mobile, stay in guest mode or logout;
8. Observe scaling problem.

<hr>

#### Errors on screen?  If so paste here:
https://i.imgur.com/JkDMEQz.jpg

**Comment by causefx** [comment]
how is it without that theme?
Edit: nvm, saw you mentioned that same result...

**Comment by causefx** [comment]
maybe i'll change this default behavior in favor for max full height

**Comment by mrbuckwheet** [comment]
Is there a way to force desktop mode in organizr?
