### ISSUE TITLE
 Dependencies Missing FILEINFO & MBSTRING

### ISSUE THREAD

**Issue by FancyNerd92** [causefx/Organizr#1954]
###### Operating System: Windows/MacOS/Ubuntu
<hr>

##### Problem Description:
i have dependency missing files for fileinfo & mbstring after latest upldate. Before that i works like a charm.
![Screenshot 2023-11-22 012631](https://github.com/causefx/Organizr/assets/76796004/fef17ef7-32de-475c-9327-1aef88208253)

<hr>

##### Reproduction Steps:

<hr>

#### Errors on screen?  If so paste here:

```

```

**Comment by causefx** [comment]
you should be able to uncomment out them in the php ini file. i need to go back and check to see while i required them too.  lemme do that.

**Comment by geogolem** [comment]
I am experiencing this after attempting to update tonight as well.

**Comment by mjesticfalco** [comment]
I'd also like to report the same issue.

**Comment by Digital-Trucker** [comment]
Same issue here

**Comment by causefx** [comment]
everyone running native and not docker?

**Comment by mjesticfalco** [comment]
> everyone running native and not docker?

Yup, native. I'll include some screenshots of my error with the system info underneath, just in case it comes in handy for troubleshooting as well.
![Screenshot 2023-11-22 170728](https://github.com/causefx/Organizr/assets/51226191/4b514acb-7be0-4594-871f-9a2df6d2ec83)
![Screenshot 2023-11-22 170810](https://github.com/causefx/Organizr/assets/51226191/1cfaab8a-7c49-47bf-963e-1251839c43b1)
![Screenshot 2023-11-22 170836](https://github.com/causefx/Organizr/assets/51226191/61e699af-e4d4-434b-a07b-d22f4f4d0ac8)

**Comment by jiznon** [comment]
> you should be able to uncomment out them in the php ini file. i need to go back and check to see while i required them too. lemme do that.

Thanks! This helped in the meantime. Really awesome to see updates!

**Comment by holt3000** [comment]
Same issue over here

**Comment by codedesperate** [comment]
Just updated, I get the missing mbstring error. I don't having missing fileinfo error. Running native

**Comment by jackmeat** [comment]
same issue, native windows user, and stuck remote to fix.both mbstring and fileinfo missing

**Comment by dunnie1982** [comment]
> same issue, native windows user, and stuck remote to fix.both mbstring and fileinfo missing

Me too, I fiddled around with the php.ini file, but I wasn't sure what to uncomment out make it work, so I just ctr-z the file back to its default.

**Comment by justinpeterson13** [comment]
> you should be able to uncomment out them in the php ini file. i need to go back and check to see while i required them too. lemme do that.

This worked for me!

**Comment by codedesperate** [comment]
> > you should be able to uncomment out them in the php ini file. i need to go back and check to see while i required them too. lemme do that.
> 
> This worked for me!

@justinpeterson13 
What did you do, and what exactly did you uncomment? I couldn't figure it out when I tried :/

**Comment by causefx** [comment]
search for mbstring.dll and fileinfo.dll

remove the ';' in front of those lines.

**Comment by Digital-Trucker** [comment]
Workaround worked for me as well, although I had to leave the .dll off of the search to find the lines to uncomment. Thanks much, @causefx

**Comment by AtomicClown** [comment]
> search for mbstring.dll and fileinfo.dll
> 
> remove the ';' in front of those lines.

I'm unable to find these lines, am I looking in the wrong place? Could someone show me the file path on Windows?

**Comment by causefx** [comment]
it would be in your php folder. file should be something like php.ini
or a variation of that name with .ini

**Comment by carfa34** [comment]
Fix for me was to uncomment the lines like causefx said. 

Go to the "php.ini" in "C:/nginx/php/" or wherever you have that folder. 
Remove the ";" in front of "extension=fileinfo" and "extension=mbstring" and save the file. They were around line 900.
Finally, run "services.msc" and restart both PHP and NGINX or you could probably just restart your computer.

Everything seems to be working again.

**Comment by codedesperate** [comment]
I'm on Ubuntu though. 
I go /etc/nginx/php8.2/cli
and /etc/nginx/php8.2/fpm

In both directories I open the php.ini file
Then remove the ";" from mbstring and fileinfo., 

Then I do /etc/init.d/php8.2-fpm restart
systemctl nginx restart

And the above does not solve it. I still get missing dependency :/

**Comment by causefx** [comment]
for linux try installing via package manager. 

`apt-get install php8.2-mbstring`

**Comment by codedesperate** [comment]
Small correction. I have php 8.1 not 8.2. 

I did `apt-get install php8.1-mbstring` and it installed. I then rebooted. 

I still get the error. And for me, it is for mbstring only. 

<img width="472" alt="image" src="https://github.com/causefx/Organizr/assets/29740063/e99a4852-c9d5-412b-b82c-093ef29fae33">

**Comment by causefx** [comment]
you can check via cli if the module is installed.  `php -m`

**Comment by codedesperate** [comment]
It is installed. 

```
zeroz@zeroz:~$ php -m
[PHP Modules]
calendar
Core
ctype
curl
date
dom
exif
FFI
fileinfo
filter
ftp
gettext
hash
iconv
json
libxml
mbstring
openssl
pcntl
pcre
PDO
pdo_sqlite
Phar
posix
readline
Reflection
session
shmop
SimpleXML
sockets
sodium
SPL
sqlite3
standard
sysvmsg
sysvsem
sysvshm
tokenizer
xml
xmlreader
xmlrpc
xmlwriter
xsl
Zend OPcache
zip
zlib

[Zend Modules]
Zend OPcache
```

**Comment by causefx** [comment]
so your cli version and web version aren't the same. check your webserver and see what version it is. `php -v` will show the version that cli is too.

**Comment by codedesperate** [comment]
It was indeed that. It makes sense now!

I ran the organizr isntaller just to update dependencies, and that installed php8.1. But I did not think that `/etc/nginx/config/CENSORED/phpblock.conf` still referred to version 7.4 ! 

Thank you :)

**Comment by causefx** [comment]
glad you got it sorted! :)

**Comment by jackmeat** [comment]
> Fix for me was to uncomment the lines like causefx said.
> 
> Go to the "php.ini" in "C:/nginx/php/" or wherever you have that folder. Remove the ";" in front of "extension=fileinfo" and "extension=mbstring" and save the file. They were around line 900. Finally, run "services.msc" and restart both PHP and NGINX or you could probably just restart your computer.
> 
> Everything seems to be working again.

Nailed it, made it easy,even on phone.thank you

**Comment by dshokouhi** [comment]
Just commenting this is still an issue and uncommenting the 2 lines fixes the issue
