### ISSUE TITLE
Plex Oauth Login not working

### ISSUE THREAD

**Issue by jscottelblein** [causefx/Organizr#1956]
###### Branch: Master
<hr>

##### Problem Description:

- Clicking the Plex Login button brings up the separate Plex oauth browser window as usual, asking me if I want to allow Organizr as usual;
- I click the usual ok button;
- that window closes, as usual
- but then during the 'waiting' period to actually login where the "oauth successful" tip shows, suddenly the "login error, bad credentials" popup shows at the bottom, and login fails:

![image](https://github.com/causefx/Organizr/assets/1524526/2615800d-fadd-4900-85f9-eef0075f8242)

I'm also able to successfully login using my regular Organizr creds, so not a huge deal right now, but thought it worth mentioning in case no one else has yet (didn't see it doing an issues search).

**Comment by tronyx** [comment]
FYI `:latest` is not a valid version of Organizr. Should be something like `2.1.2460` from the Settings page. Plex OAuth is working for me with no issues with multiple accounts so I don't really see this as an issue with Organizr. Are you sure the credentials you're using do, in fact, work with Plex?

**Comment by causefx** [comment]
double check plex token in settings too...
