### ISSUE TITLE
[Feature Request] Way to script in the tab information so the user doesnt have to.

### ISSUE THREAD

**Issue by RXWatcher1** [causefx/Organizr#196]
I would like to be able to pre-populate the urls and the api information for my users.

If I have a user of 'user', I'd like to prepopulate the information somehow so the user doesnt have to.

Say sonarr is at https://server/user/sonarr and https://server/user/radarr/ 
etc

Do you know if that is possible?

Thank you!

**Comment by causefx** [comment]
Can you give more detail on the use case?

**Comment by RXWatcher1** [comment]
yes, of course.

I'm looking at building a docker based seedbox script.
It's partially built now:  https://github.com/RXWatcher1/docker-seedbox

Essentially it will have a shell script menu that the user can select from a variety of docker images..mostly from linuxserver.io. The project uses Traefik to dynamically reverse proxy the containers.

Organizr would be the main web page the user would come to and then from there link to the other URLs.

The pull for Organizr:
docker run -d \
  --restart always \
  --name=$USER-organizr \
  -v $DOCKER_CONFIG/organizr:/config \
  -e PGID=$(id -g) \
  -e PUID=$(id -u) \
  -e TZ=$(cat /etc/timezone) \
 -l traefik.port=80 \
 -l traefik.protocol=http \
 -l traefik.frontend.rule="PathPrefixStrip: /$USER" \
lsiocommunity/organizr

This would produce an organizr that is available at https://server/user/
others are like:
https://server/user/rutorrent/
https://server/user/sonarr/
https://server/user/couchpotato

I would basically like to have organizr be pre-populated with the above links so the user just has to click and go. I can pull things like API values from most of the config files.

The list of apps is dynamic..one user might want x,y,z and another a,b,c and z. The list of apps can be changed at any time..I decide I no longer want sonarr and I remove the container, I would want organizr to be updated to remove the tab for it.

Thanks for your time
-RX

**Comment by RXWatcher1** [comment]
I've been able to script in the tabs via sqlite. I know..not the best way because you can change the db structure on me but its working for now.

**Comment by JigSawFr** [comment]
@RXWatcher1 thanks for Traefik, didn't know it before your post.
I'm using actually letsEncrypt Docker with subdomain, but your solutions seems to be great.
Did your source code for your seedbox script is publicly available somewhere ?
There is a nice script for seedbox: quickbox.io, but it's destroying host by running so many script that changes a huge part. It could be great to have a similar solution but docker based.

**Comment by RXWatcher1** [comment]
lol..I am part of quickbox.io :)  I am breaking off into my own solution because I want something docker based, multi-user and minimal impact on the host. I can trash it all without rebuilding my server.

 It's not quite there yet..give me a week or so and I'll have it packaged into something you can try.

https://github.com/RXWatcher1/docker-seedbox

I need a better name for it...I'm lame.

Anyway, check back in a week or so on it.

**Comment by JigSawFr** [comment]
@RXWatcher1 world is small lol yeah it's the only point why i'm not using quickbox script, I don't want to destroy my host lol, all my apps are running in docker container (hourra to linux server.io).
And yeah with docker, we can trash all things without reinstall the server !
I will watch your progress on it, do you plan to reintegrate quick box interface and other things ?

**Comment by RXWatcher1** [comment]
@JigSawFr I'm not sure on the interface. I guess we'll see how the project goes. I dont want to over-complicate the project. QB is build on apache..at the very least it would need to be moved over to nginx.
I didnt have a hand in writing the QB gui so I'm gun shy about using it or porting it.

I like Organizr as the base point per user to the apps and then I figured using Grafana as a tab on there for system and docker stats.

Right now I'm looking at using the 'box' script from QB for installing/removing dockers. This is run by the end user so the user can select the dockers they want. I need to use scripts because there is some post processing (setting the base) on a lot of them.

If I can use Grafana for stats, Organizr for the launch point, what am I missing? a web based installer and control to turn the containers on/off...I havent found that yet.

I would be ok if this rolls into the QB project..no biggie to me. I just think we're going in different directions. I think a lot of the user issues evolve around the locally installed apps..by using dockers, I'm isolating them in to their own little worlds and I have a ton more out there without having to do a lot of scripting. I stand on the shoulders of the linuxserver.io guys..they did all the heavy lifting.

**Comment by causefx** [comment]
@RXWatcher1 looks like you figured it out, I dont play on changing the DB scheme, but if I do, I will give you a heads up.  Also, Organizr, auto updates the database on upgrades, so in the end it may not even matter :)

**Comment by RXWatcher1** [comment]
Thanks for Organizr..I do really appreciate it. I'll close this.
