### ISSUE TITLE
Calendar Item's backdrop images are missing

### ISSUE THREAD

**Issue by mannbadal** [causefx/Organizr#1963]
###### Operating System: Docker
<hr>

##### Problem Description:
Calendar Item's backdrop images are missing. It shows empty modal when clicked on an item. Only happening with the new items, old items are showing images (like the continuing shows from last year with the same backdrop images), indicating the images for new items are not getting downloaded.

<img width="1652" alt="image" src="https://github.com/causefx/Organizr/assets/108790470/0d868dfd-e5b8-4670-a932-306f2cef3b13">
<img width="1844" alt="image" src="https://github.com/causefx/Organizr/assets/108790470/f4a32daa-3409-466f-8359-1afd35f4f4ba">

In Dev tools, there is an error that the image is missing 
<img width="368" alt="image" src="https://github.com/causefx/Organizr/assets/108790470/e3cfc025-5188-4e6c-8e73-ce79207e016c">

Docker permissions are ok as new images for Tautulli's viewing stats are getting added to the same directory `/config/www/organizr/data/cache`

<img width="474" alt="image" src="https://github.com/causefx/Organizr/assets/108790470/50424601-701c-42a7-97a8-ed75e4912cda">

<hr>

##### Reproduction Steps:

1. Click on Homepage calendar item
2. Item's backdrop image missing for new/upcoming items
3. Check error in browser's dev tools
4. After adding image manually, the image will appear

<hr>

#### Errors on screen?  If so paste here:

```
No error on screen just the image is missing
```

##### Note: 
I did migrate my docker stack and the mysql db to another server over a month ago, but unsure if that is related because I updated IPs in config and everything else seems to be working fine.
I have also tried removing cache folder and recreating container, still the same behaviour. Do I need to add my own TMDB API somewhere?
Any help is appreciated :)

**Comment by mannbadal** [comment]
Possibly linked to [https://github.com/causefx/Organizr/issues/1943](url)

I am using 
Sonarr - 4.0.1.987 - develop
Radarr - 5.2.6.8376 - master

Sonarr API results 

```
  {
    "seriesId": 878,
    "tvdbId": 9549476,
    "episodeFileId": 0,
    "seasonNumber": 1,
    "episodeNumber": 2,
    "title": "Bomber Leather Jacket",
    "airDate": "2024-01-26",
    "airDateUtc": "2024-01-26T05:00:00Z",
    "runtime": 0,
    "hasFile": false,
    "monitored": true,
    "unverifiedSceneNumbering": false,
    "series": {
      "title": "Masters of the Air",
      "sortTitle": "masters of the air",
      "status": "upcoming",
      "ended": false,
      "overview": "During World War Il, airmen risk their lives with the 100th Bomb Group, a brotherhood forged by courage, loss, and triumph.",
      "network": "Apple TV+",
      "images": [
        {
          "coverType": "banner",
          "remoteUrl": "https://artworks.thetvdb.com/banners/v4/series/370853/banners/65abf3cfc58b7.jpg"
        },
        {
          "coverType": "poster",
          "remoteUrl": "https://artworks.thetvdb.com/banners/v4/series/370853/posters/65708a6ed7984.jpg"
        },
        {
          "coverType": "fanart",
          "remoteUrl": "https://artworks.thetvdb.com/banners/v4/series/370853/backgrounds/65708cf3a7b4d.jpg"
        },
        {
          "coverType": "clearlogo",
          "remoteUrl": "https://artworks.thetvdb.com/banners/v4/series/370853/clearlogo/651f2db8adf76.png"
        }
      ],
      "originalLanguage": {
        "id": 1,
        "name": "English"
      },
      "seasons": [
        {
          "seasonNumber": 0,
          "monitored": false
        },
        {
          "seasonNumber": 1,
          "monitored": true
        }
      ],
      "year": 2024,
      "path": "/TV/TV Shows/Masters of the Air",
      "qualityProfileId": 7,
      "seasonFolder": true,
      "monitored": true,
      "monitorNewItems": "all",
      "useSceneNumbering": false,
      "runtime": 0,
      "tvdbId": 370853,
      "tvRageId": 0,
      "tvMazeId": 44388,
      "firstAired": "2024-01-26T00:00:00Z",
      "lastAired": "2024-03-15T00:00:00Z",
      "seriesType": "standard",
      "cleanTitle": "mastersair",
      "imdbId": "tt2640044",
      "titleSlug": "masters-of-the-air",
      "genres": [
        "Drama",
        "History",
        "Mini-Series",
        "War"
      ],
      "tags": [
        1
      ],
      "added": "2023-10-06T19:37:23Z",
      "ratings": {
        "votes": 0,
        "value": 0
      },
      "languageProfileId": 1,
      "id": 878
    },
    "grabbed": false,
    "id": 39600
  }
```

**Comment by mannbadal** [comment]
I tested this on a fresh install and the issue is still there.

**Comment by Ryderjj89** [comment]
Also have this issue on a new install. Can see the description and name, but no image. Getting a 404 in console log.

**Comment by causefx** [comment]
fixed in dev
