### ISSUE TITLE
Feature suggestion: Import tabs from CSV

### ISSUE THREAD

**Issue by abcasada** [causefx/Organizr#1966]
###### Operating System: Ubuntu
<hr>

##### Problem Description:
I would like to be able to import tabs from a CSV. I was thinking about trying to build this myself, but wanted to gauge the devs' interest before spending time on it.

This would be useful when the user wants to create a larger set of tabs.

My idea is to add a button beside the Help and Add New Tab buttons on the Tab Editor page, and accept a CSV file with columns matching both the properties on the Add New Tab popup and the columns on the Tab Editor page.

**Comment by causefx** [comment]
i'd welcome it.
