### ISSUE TITLE
Add link to how to get plex token in plex homepage setting

### ISSUE THREAD

**Issue by fryfrog** [causefx/Organizr#197]
It wasn't hard to find, but if you added a link to Plex's how to find your token article right below the token field, it would be super keen.

https://support.plex.tv/hc/en-us/articles/204059436-Finding-an-authentication-token-X-Plex-Token

**Comment by JigSawFr** [comment]
@fryfrog great feature will be auto get of Plex token as PlexPy do it :)

**Comment by StevenChorkley** [comment]
I don't a link needs adding as it's documented in the WIKI. Fetching the token would be cool though!

**Comment by Cerothen** [comment]
I do think its pretty easy to find, but its equally easy for me to just toss a link in.

![image](https://cloud.githubusercontent.com/assets/9008757/25343806/188035b0-28de-11e7-9110-8e0d5f37f1cf.png)
https://github.com/causefx/Organizr/commit/45105fde9eb772a8cce420f73523792149d60a9d
