### ISSUE TITLE
Test Contributors

### ISSUE THREAD

**Issue by causefx** [causefx/Organizr#1977]
@all-contributors please add @Roxedus for test

**Comment by causefx** [comment]
does this only work if its in master?

**Comment by tronyx** [comment]
Add him how? Just a mention? Assign to the issue?

@Roxedus

**Comment by causefx** [comment]
think it works only in master branch.  i will test it

**Comment by causefx** [comment]
@all-contributors please add @tronyx for test

**Comment by causefx** [comment]
@all-contributors please add @Roxedus for test

**Comment by causefx** [comment]
https://github.com/all-contributors please add @HalianElf for test

**Comment by causefx** [comment]
@all-contributors please add @HalianElf for test

**Comment by causefx** [comment]
@all-contributors please add @HalianElf for test
