### ISSUE TITLE
Correct configuration for sonarr/radarr in homepage?

### ISSUE THREAD

**Issue by fryfrog** [causefx/Organizr#198]
I've got Plex and NZBGet working on the homepage, but neither Sonarr nor Radarr show up.

For NZBGet, pointing it directly at my reverse proxy destination works fine: https://i.imgur.com/9mr0B3S.png

But for Sonarr/Radarr, it doesn't: https://i.imgur.com/azV1MD3.png

I've tried:
`192.168.1.2` and `8989`
`http://192.168.1.2/sonarr` and `8989`
`http://192.168.1.2` and `8989`
`/sonarr` w/o port filled

What am I doing wrong?

**Comment by causefx** [comment]
try this again:
`http://192.168.1.2` and `8989`

then goto homepage.php and view source, scroll towards bottom and see what error shows please.

**Comment by fryfrog** [comment]
Looking at the code for the url...

https://github.com/causefx/Organizr/commit/9285061e2e43a85ea5d5f2f5ee9c5e90b45e808b#diff-78cd5aa3783a74555c9938a2a81d01c6R382

It looks like just /sonarr should have worked and generating that link manually does return results, like...

https://apollo.fryfrog.com/sonarr/api/calendar?apikey=<hidden>

**Comment by fryfrog** [comment]
View source shows the problem, if I didn't have a url_base set in Sonarr/Radarr, it'd work.

`http://192.168.1.2/sonarr:8989` is what it tries to hit.

**Comment by causefx** [comment]
u shouldnt need the base url for api

**Comment by causefx** [comment]
if you want to try with base url

leave port blank and only input this into URL

`http://192.168.1.2:8989/sonarr`

**Comment by fryfrog** [comment]
That is actually what I just tried and it works in view source, it is able to pull data from sonarr, radarr and headphones w/ that entry.

But nothing shows up on homepage.php, just in the source. :(

**Comment by causefx** [comment]
do you mind jumping on https://gitter.im/Organizrr/Lobby

PM me your URL....  we will get it worked out real quick

**Comment by fryfrog** [comment]
The end result was that the best thing for url was `http://ip:port/url` and leaving port blank. The issue turned out to be Headphones not escaping " or ', according to @causefx. :)
