### ISSUE TITLE
Both qBittorrent Complete and Seeding show up even though set to hide.

### ISSUE THREAD

**Issue by devanteweary** [causefx/Organizr#1985]
###### Operating System: Unraid - (Docker container repository: organizr/organizr)
<hr>

##### Problem Description:
Completed downloads not being hidden.

Happens with both torrents that have been completed and the files removed and also torrents that are complete and seeding.

Same issue as: https://github.com/causefx/Organizr/issues/1834

<hr>

##### Reproduction Steps:
Enabled both "Hide Seeding" and "Hide Completed" in Organizr Settings > Tab Editor > Homepage Items > qBittorrent > Misc Options.
<hr>

#### Errors on screen?  If so paste here:
```
No errors.
```

![image](https://github.com/causefx/Organizr/assets/29805497/1fed34ee-80b3-4de2-937e-00bd550f7f9d)

For example, the torrent of **Ayoade_On_Top_by_Richard_Ayoade.epub** exists and is seeding.
The torrent of **A Thin Line Between Love And Hate (1996) [1080p] [BluRay] [YTS.MX]** is complete, the file has been deleted, but the torrent is still in qBittorrent. (eventually I clean these out but while they are in qbittorrent, they still appear in Organizr).

I pasted the **api/v2/homepage/qbittorrent/queue** as that was requested in issue 1834.

Please find it here: https://justpaste.it/organizr

Thank you for taking the time!!

**Comment by jiznon** [comment]
Same issue here since i first started using Organizr many years ago. I don't use it for this reason.

**Comment by jiznon** [comment]
Btw, how did you get the "Download Status" header on there? I can't seem to find it anywhere. Custom CSS?

**Comment by devanteweary** [comment]
> Btw, how did you get the "Download Status" header on there? I can't seem to find it anywhere. Custom CSS?

Yeah. That's the HTML widget set before the qBittorrent widget.  
It's just this:

```
<html>
<head>
<style>

    .button {
      background-color: #499fb6;
      color: #000000;
      padding: 10px 20px;
      border: none;
        }

    </style>
    </head>

<body>

    <b>
<button class="button">Download Status</button>

    </b>

    </body>
    </html>
```

**Comment by jiznon** [comment]
Neat, thanks!

**Comment by jiznon** [comment]
Any ideas on this before it’s auto closed?

**Comment by devanteweary** [comment]
> Any ideas on this before it’s auto closed?

I'm thinking the project's dead brother.

**Comment by HalianElf** [comment]
What version of qbit? Mine works as expected.

**Comment by causefx** [comment]
i would need access to a broken one to test. Sent from my iPhoneOn May 26, 2024, at 3:37 PM, HalianElf ***@***.***> wrote:﻿
What version of qbit? Mine works as expected.

**Comment by devanteweary** [comment]
> What version of qbit? Mine works as expected.

Oh snap, I guess it isn't dead!
Sorry about that.

Using the following qBittorrent container:

- qBittorrent v4.6.4 Web UI (64-bit)
- Repository: binhex/arch-qbittorrentvpn:latest

and using the following version of Organizrrv2:
- Organizrr v2.1.2490
- Branch:  [v2-master](https://github.com/causefx/Organizr/commits/v2-master)
- Repository: organizr/organizr

@causefx , we can do Discord screenshare or Windows Quick Assist if you wanna try that. 
Let me know.

I'm DevanteWeary on Discord.
