### ISSUE TITLE
Tautulli SSO does log in but does not log out

### ISSUE THREAD

**Issue by Gabigeek** [causefx/Organizr#1987]
###### Operating System: Docker (Linux)
<hr>

##### Problem Description:

So I have spent some hours and didn't find anyone having the exact same problem as me : 
**TL;DR, When logging into Organizr, I can successfully load the Tautulli tab (I can see a tautulli_token_XXX successfully being created).
However, when I log out of Organizr, I don't get logged out of Tautulli and the interface remains accessible.**

Some configuration infos :
- I Use Plex oAuth to log both into organizr and Tautulli. (I can also use static Credentials, which result in the same behavior)
- I followed the Tautulli SSO guide (enabled Plex admin, guest access etc.)
- My reverse proxy is configured in **subdirectory** mode for each service, example :
      - Tautulli : https://local_domain.com/tautulli  (**after logout, this is the URL can be used to bypass Organizr and access the logged in tautulli interface ...**)
      - Organizr (at root) : https://local_domain.com/
- I used my self-signed PKI to sign the certificate pushed by the reverse proxy when accessing frontend (https), all backend services are running in http. (CA pub key has been installed on all web clients hosts to avoid errors in browsers)

I also configured **SSO** with **Ombi**, but this time it's working **flawlessly**.

<hr>

##### Reproduction Steps:

I think I might have a clue of what is not working. Even tho a tautulli cookie is successfully created when entering the tautulli tab, Organizr does not seem to detect the cookie ! (Tautulli SSO debug shows cookie : **False** ).

![Capture d'écran 2024-04-28 175140](https://github.com/causefx/Organizr/assets/43895120/31f0b271-3f72-4ee4-889c-334945383665)
![image](https://github.com/causefx/Organizr/assets/43895120/a3cf4268-9323-406c-aa25-1b4a182964fa)

So there's a question which is : why am I being logged in if Organizr didn't create any cookie according to the Organizr debug tool ?
Another thing I noticed with DevTools is that the Ombi cookie is being created immediately after Organizr login. However, Tautulli cookie only gets generated when opening the tab... maybe it's normal ?
 
 I'm out of Ideas, so I'll be very grateful if someone has a clue of what is going on 👍

<hr>

#### Errors on screen?  If so paste here:

```

```

**Comment by causefx** [comment]
It's odd you have two domains with those cookies...  try clearing out all cookies using the button to the right of filter.  then login, check how many cookies are there and then logout and check again.  I tested here just now and it seemed fine.

The relevant code to clear the tautulli code is:
```php
	public function clearTautulliTokens()
	{
		foreach (array_keys($_COOKIE) as $k => $v) {
			if (strpos($v, 'tautulli') !== false) {
				$this->coookie('delete', $v);
			}
		}
	}
```
It deletes any cookie that has the word `tautulli`

**Comment by Gabigeek** [comment]
Hello, thank you for your response !
Here's a more detailed view of what the domain looks like :
![image](https://github.com/causefx/Organizr/assets/43895120/dfffd50d-3886-413c-98a0-750dc142a12a)
(sorry, I had to censor my domain because it is related to one of my precise physical location ...)

Is it maybe related to the fact that my whole installation under **sub**.domain.com ? I'm not very familiar with how cookie works...
Also, Sorry but could you please tell me how can I run the can you provided to me ? Do I need to create a PHP file in Organizr's webserver root ?

Also, I tried clearing all cookies using devtools and here's what my cookies looks like when starting from a fresh browser (chrome incognito mode)  :

- New private tab : everything logged out
![1](https://github.com/causefx/Organizr/assets/43895120/73cc3d5a-5c61-4408-b173-10a7d2af161c)

- Logged in Organizr (no tautulli cookie on organizr's side since the tab has not been opened yet.)
![2](https://github.com/causefx/Organizr/assets/43895120/9599b0f9-51eb-442e-9ce9-c8489262b47d)

- Logged out of Organizr (Organizr side : cookies are gone, tautulli; direct access : cookie still present)
![3](https://github.com/causefx/Organizr/assets/43895120/715cb611-c4c5-44d9-942c-6a745c6de692)


Note : I Tried to repeat those steps and opened the Tautulli tab which obviously added the Tautulli tokens on organizr side. After loging out, the tautulli cookie is cleared, but still on Organizr side only (Result is the same as the step 3 result showed above).

Thank you again for helping me.

**Comment by causefx** [comment]
can you screenshot the sso page for tautulli

**Comment by Gabigeek** [comment]
Sure, here it is :
![image](https://github.com/causefx/Organizr/assets/43895120/1def17ec-1cfc-4ea8-8b15-d2ff91a3de5c)

**Comment by causefx** [comment]
if you are available i can try and debug via remote desktop.

**Comment by Gabigeek** [comment]
Sounds great to me, when would you like to connect ?
For me, I'll be available everyday past 6:30PM UTC+2 (Paris) (18:30)
I don't think we are in the same timezone, so if it doesn't suit you, I'm free Wednesday or in the weekend at almost any hour.

For security purposes, I've set up a Windows VM with full network access to my servarr (and docker if needed) stack for you to remotely connect.
(Sorry I'm doing this for security purposes because you kinda never know what can happen when sharing your computer over the internet to someone you don't know hahaha)

Please tell me if you need any extra software, I'll install them in advance.

Also, which remote desktop software do you want to use ?

Thanks !

**Comment by i1mran92** [comment]
were u able to solve this? i'm having the same issue. not just tautulli. plex itself will not sign out when i sign out of organizr. if i open plex.tv website, the account is still logged in

clear cache/everthing, in the browser, logged in organizr, and opening separate tabs for tautulli and plex.tv will show as logged in. 
logging out of organizr, tautulli and plex.tv still show as logged in.

**Comment by Gabigeek** [comment]
@i1mran92 I still have the problem but given than my Organizr instance is for my own private use and not exposed to the internet, I just passed on this issue because I don't think it's that critical.

However, I only have the issue with tautulli, not Plex or Ombi. did you try in Private navigation ton make sure there's no "login creds/cookies residue" on your browser, logging you in ?
