### ISSUE TITLE
Emby media link doesn't work

### ISSUE THREAD

**Issue by Ryderjj89** [causefx/Organizr#1990]
###### Operating System: Docker for Windows on WSL2
<hr>

##### Problem Description:
Emby button on the item doesn't do anything from Recently Added. The box just disappears. It doesn't open Emby, doesn't switch to the sidebar tab I've created, nothing.

I'm using the Nord theme, but also tested with the default themes, no difference. I click the item from the Recently Added, click the Emby button, the box disappears. Nothing in the browser console log when that happens either.

![image](https://github.com/causefx/Organizr/assets/1996734/aa8f1cfa-6e78-4075-b3a9-dc7166694315)

The URL it's attempting is what I have in the Misc Options. [https://REDACTED.DOMAIN/web/index.html#!/item?id={id}&serverId={serverId}](https://redacted.domain/web/index.html#!/item?id=%7Bid%7D&serverId=%7BserverId%7D)

Let me know what I can get for this. I've tried multiple log levels, nothing shows up in the log when this doesn't work.

<hr>

##### Reproduction Steps:
Click a Recently added item.
Click the Emby button next to the Youtube trailer button.

<hr>

#### Errors on screen?  If so paste here:

```

```

**Comment by HalianElf** [comment]
What's in your `Emby Tab Name`?

**Comment by Ryderjj89** [comment]
Just Emby for the link in the sidebar. From the Homepage Items configuration, it's just Emby as well. Should I have something specific?

Sidebar
![image](https://github.com/causefx/Organizr/assets/1996734/9eb3221d-b635-476b-b81e-d01f78d02912)

Homepage Item Config
![image](https://github.com/causefx/Organizr/assets/1996734/d9e9fcf2-0874-4167-a532-f8e2546a998c)

**Comment by HalianElf** [comment]
Switch the tab name for the ID number in that box

**Comment by Ryderjj89** [comment]
Can you clarify on which ID number you mean? The serverId or the item ID?

**Comment by HalianElf** [comment]
The tab ID number, you can get it if you hover over the icon on the tab editor page.

**Comment by Ryderjj89** [comment]
Ohhh. Yep that did it. Phew that could use some clarification lol. The tab was named Emby so I had no idea it wanted an ID number and there's no little tooltip on that one to tell you what it's looking for.

**Comment by HalianElf** [comment]
Yea it used to take the name but was changed to fix it not working with non english names but the fields never got updated to reflect it.
