### ISSUE TITLE
MySQL 8.4.0 API Error

### ISSUE THREAD

**Issue by Salvora** [causefx/Organizr#1993]
###### Operating System: Docker Synology NAS
<hr>

##### Problem Description:
I am trying to set up Organizr with mysqli trying to connect my mysql 8.4.0 server. During the initial wizard, I correctly enter all the values for the connection.
I also tried activating the mysql_native_password with a user with global mysql privileges and tried to set it up but did not work.
Tried with root mysql user:
I get this popup 
![image](https://github.com/causefx/Organizr/assets/6360098/ad859995-978a-42ff-a579-513056235d6c)
and after openning a new tab, I get this
![image](https://github.com/causefx/Organizr/assets/6360098/ec03957c-c0d9-4b9a-8d96-f03a95350fcb)

docker container logs show:
```log
PHP Fatal error:  Uncaught Error: Call to a member function query() on null in /config/www/organizr/api/classes/organizr.class.php:7885

Stack trace:
#0 /config/www/organizr/api/classes/organizr.class.php(1563): Organizr->processQueries()
#1 /config/www/organizr/api/classes/organizr.class.php(1610): Organizr->getGuest()
#2 /config/www/organizr/api/classes/organizr.class.php(323): Organizr->guestUser()
#3 /config/www/organizr/api/classes/organizr.class.php(164): Organizr->setCurrentUser()
#4 /config/www/organizr/cron.php(3): Organizr->__construct()

}
  thrown in /config/www/organizr/api/classes/organizr.class.php on line 7885
PHP Fatal error:  Uncaught Error: Call to a member function query() on null in /config/www/organizr/api/classes/organizr.class.php:7885

Stack trace:
#0 /config/www/organizr/api/classes/organizr.class.php(1563): Organizr->processQueries()
#1 /config/www/organizr/api/classes/organizr.class.php(1610): Organizr->getGuest()
#2 /config/www/organizr/api/classes/organizr.class.php(323): Organizr->guestUser()
#3 /config/www/organizr/api/classes/organizr.class.php(164): Organizr->setCurrentUser()
#4 /config/www/organizr/cron.php(3): Organizr->__construct()

}
  thrown in /config/www/organizr/api/classes/organizr.class.php on line 7885
```
and after checking the MySQLserver, I see that the database has been created but no more action.

<hr>

##### Conclusions:
Organizr can definitely reach MySQL server and can send queries since it can create a db in the MySQLserver
I tried this with MariaDB 10, and connection worked without a problem.

**Comment by causefx** [comment]
might be an issue with that version or just mysql in general.  i will have to do some testing.
