### ISSUE TITLE
Title issue

### ISSUE THREAD

**Issue by halali** [causefx/Organizr#2]
If i make title witch 2 words than title is in 2 rows.

Sorry for my english

**Comment by causefx** [comment]
Ahhh, I just tried and I see that, I will fix today.

**Comment by aporzio1** [comment]
I also noticed it does not load links if I access Organizr using https, the frame loads but the pages are blank white.

**Comment by causefx** [comment]
what links are they, if you are access Organizr thru https then it should be fine, if you are accessing it through http, then all content must be http.

**Comment by roquemore92** [comment]
> I also noticed it does not load links if I access Organizr using https, the frame loads but the pages are blank white.

I also have this same issue. Accessing Organizr via http allows for http and https pages to load. Accessing Organizr via https allows https pages to load, while http pages just show up blank. No error or anything like that. Not sure it's an issue with my setup or just something with the browser. Personally it doesn't matter much to me, but just verifying what aporzio1 said.

**Comment by causefx** [comment]
if you are using Chrome, you will see a shield in the top right of URL bar.  clicking that will break your HTTPS connection and allow you to use http content.  

If you are serving Organizr through HTTPS, all content must be HTTPS.

**Comment by SgtBatten** [comment]
I am using 3 words and the 3rd word is still on a second line below the top bar after this fix

**Comment by causefx** [comment]
what is the Phrase that you are using so I may test the length?
