### ISSUE TITLE
Page taking to long to respond

### ISSUE THREAD

**Issue by dejected1** [causefx/Organizr#200]
IM not sure if this is my nginx code or not. When im on the local network everything works fine. Im using ddns pointing to port 9111. When i leave the local network i can get to the landing page for organizr but when i click on my tabs it says taking to long to respond. If i open the port for the tabs directly on the router (ie port foward sonarr) i can access sonarr directly without organizr but not from within organizr. Still get page taking too long to respond. Help. 

here is my conf
#user  nobody;
worker_processes  2;

#error_log  logs/error.log;
#error_log  logs/error.log  notice;
#error_log  logs/error.log  info;

#pid        logs/nginx.pid;

events {
    worker_connections  1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;

    #log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
    #                  '$status $body_bytes_sent "$http_referer" '
    #                  '"$http_user_agent" "$http_x_forwarded_for"';

    #access_log  logs/access.log  main;

    sendfile        on;
    #tcp_nopush     on;

    #keepalive_timeout  0;
    keepalive_timeout  65;

    #gzip  on;

    server {
        listen       9111;
        server_name  192.168.2.87;

        #charset koi8-r;

        #access_log  logs/host.access.log  main;

        location / {
            root   html;
            index  index.php index.html index.htm;
        }

        #error_page  404              /404.html;

        # redirect server error pages to the static page /50x.html
        #
        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   html;
        }

        # proxy the PHP scripts to Apache listening on 127.0.0.1:80
        #
        #location ~ \.php$ {
        #    proxy_pass   http://127.0.0.1;
        #}

        #pass the PHP scripts to FastCGI server listening on 127.0.0.1:9000
        #
        location ~ \.php$ {
            root           html;
            fastcgi_pass   127.0.0.1:9000;
            fastcgi_index  index.php;
            fastcgi_param  SCRIPT_FILENAME  c:/nginx/html$fastcgi_script_name;
            include        fastcgi_params;
        }

         #deny access to .htaccess files, if Apache's document root
         #concurs with nginx's one
        
        location ~ /\.ht {
            deny  all;
        }
    }

    # another virtual host using mix of IP-, name-, and port-based configuration
    #
    #server {
     #   listen       9111;
      #  listen       192.168.2.87:9111;
        #server_name  192.168.2.87  alias  another.alias;

#        location / {
 #          root   html;
  #         index  index.php index.html index.htm;
   #     }
    #}

    # HTTPS server
    #
    #server {
    #    listen       443 ssl;
    #    server_name  localhost;

    #    ssl_certificate      cert.pem;
    #    ssl_certificate_key  cert.key;

    #    ssl_session_cache    shared:SSL:1m;
    #    ssl_session_timeout  5m;

    #    ssl_ciphers  HIGH:!aNULL:!MD5;
    #    ssl_prefer_server_ciphers  on;

    #    location / {
    #        root   html;
    #        index  index.html index.htm;
    #    }
    #}

}

**Comment by causefx** [comment]
Can you tell me the URL on the tab?

**Comment by dejected1** [comment]
http://dejected.asuscomm.com:9111/#sonarr

**Comment by dejected1** [comment]
or did you mean where the tab is pointing: http://192.168.2.87:8989/calendar

**Comment by causefx** [comment]
ahh, ok, there is the problem.  that url will only work for local access. 

You have two options:

1. replace that url with http://dejected.asuscomm.com:8989/calendar & open up that port on your router
2. setup reverse proxy so you dont have to open up additional ports.

**Comment by dejected1** [comment]
ah ok. that makes sense i guess. i guess i have some googling to do. id rather not open all those ports so i need to figure out how to make nginx do reverse proxy

**Comment by dejected1** [comment]
so just one question. What should i make the location when doing the proxy pass in nginx? i tried the /#sonarr and /sonarr no go. any direction would be helpful.

**Comment by causefx** [comment]
```
location /sonarr {

    proxy_pass http://192.168.2.87:8989;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

}
```

**Comment by causefx** [comment]
then in Sonarr:
![image](https://cloud.githubusercontent.com/assets/16184466/24373645/d398fbb0-12e6-11e7-8c79-bf8bfb4007c6.png)

**Comment by dejected1** [comment]
yeah thats what i thought. i had done that already and i still get a to long to respond error. changed url base in sonarr to /sonarr (then restarted) copied you code into nginx just in case i missed something. 
I also tried changing the tab url to my ddns address. no change. i tried it with the ip again to, no change. maybe a guide for those of us on how to setup reverse proxy. and ive port forwarded my open port to ip in router

**Comment by causefx** [comment]
just tried to access http://dejected.asuscomm.com:9111//sonarr and got a 404 error.  Are you restarting nginx when you are doing changes?  also check for errors `sudo nginx -t`

**Comment by dejected1** [comment]
I had turned it all off so i didn't have to worry about it. I just turned it on and success! i wasn't specifying the new /sonarr in the tab address. it seems to be working now. thanks for your help

**Comment by causefx** [comment]
Good stufff :)
