### ISSUE TITLE
[Feature] Auto tab generation

### ISSUE THREAD

**Issue by phyzical** [causefx/Organizr#2001]
##### Feature Description:

Just curious if anyone had requested this before, but basically similar logic to swags auto-proxy or auto-kuma soultions, where we can just add container labels to auto generate tabs for organizr to manage?

Would just be a matter of having a cron organizr side that talks to the docker proxy endpoint ( i suppose theres the possiblity the feature might be used by k8 pods? or the docker .sock directly)

just the following labels would be the minimum id think
* icon url
* tab name
* minimum permission
* order? but that might get annyoing
<hr>

Alternatively is there any other way that exists to autogenerate i.e based of some file, as i guess i could just have a cron automate this file and mount that instead

**Comment by HalianElf** [comment]
Feature requests belong on the feature request site - [Fider](https://feature.organizr.app/)

**Comment by phyzical** [comment]
👍 https://feature.organizr.app/posts/201/automated-service-discovery-using-labels-on-docker-containers

**Comment by phyzical** [comment]
Created this plugin to support it https://github.com/phyzical/autoOrganizr
