### ISSUE TITLE
Plugin cron functionailty 

### ISSUE THREAD

**Issue by phyzical** [causefx/Organizr#2002]
Hey i've created this plugin to support auto discovery https://github.com/phyzical/autoOrganizr

i was just wondering if there is logic to allow plugins to create a cron to be run in the core of the application?

Just want to run this logic https://github.com/phyzical/autoOrganizr/blob/main/plugin.php#L267 in the background some how

Just to avoid users being forced to click the menu item to sync the tabs

**Comment by causefx** [comment]
yes, just create a cron.php file in plugin root with code like:

```php
<?php
/*
 * Simple Cron job
 */
$GLOBALS['cron'][] = [
	'class' => 'ShuckStop', // Class name of plugin (case-sensitive)
	'enabled' => 'SHUCKSTOP-cron-run-enabled', // Config item for job enable
	'schedule' => 'SHUCKSTOP-cron-run-schedule', // Config item for job schedule
	'function' => '_shuckStopPluginRun', // Function to run during job
];
```

**Comment by phyzical** [comment]
well i feel silly that i didn't even bother to search it... 

Thanks for the speedy reply though!
