### ISSUE TITLE
[Feature Reaquest] Hide login page when using auth-proxy

### ISSUE THREAD

**Issue by an0t8** [causefx/Organizr#2005]
I finally got SSO working with Authentik and Organizr.  The only slight hiccup is that it takes about 5 seconds or so to start logging the user in.  During this time the organizr login page is displayed.  My users are frequently asking do I need to log in again, before the OAuth login process removes the page.

It would be nice if while attempting an Oauth login organizr would keep the login page hidden.  Only if Oauth failed would it display which would still allow local login.

**Comment by tronyx** [comment]
Please use the Feature Upvote site for this: https://organizr.featureupvote.com/
