### ISSUE TITLE
Refresh iframe but stay on the current URL

### ISSUE THREAD

**Issue by alanmilinovic** [causefx/Organizr#2008]
###### Operating System: Debian
<hr>

##### Problem Description:

If I refresh the iframe with the button (next to the logo in the upper, left-hand corner) then the iframe is reloaded, I guess the url defined in tab definition is called again.

What I would like to have when refresh is clicked is to refresh an iframe while staying on the same URL path. For example if my iframe url is domain.com and I navigate to domain.com/somepage. After refesh I am back on domain.com page. How to preserve current url and refresh current url?
<hr>

##### Reproduction Steps:

Define a new Tab as iframe. Open iframe and navigate on some page. Click refresh button. You awill be back on the first page that was initially loaded with the iframe.
<hr>

**Comment by alanmilinovic** [comment]
Don't close it.

**Comment by HalianElf** [comment]
This only works if you're using relative paths. If you're using separate subdomains, the browser blocks the parent from being able to read the URL that's in the iframe.

**Comment by alanmilinovic** [comment]
Understood, thank you.
