### ISSUE TITLE
[Feature request] Aesthetic modifications

### ISSUE THREAD

**Issue by lgromb** [causefx/Organizr#201]
- Logo dimensions in the wiki ? Both top bar and main loading logo

- Option to change the default font of the top bar title ?

- Error.php is designed to be sitting at the root of the domain. Can we modify the page to be held anywhere is the domain (or subdomain?)

- Login form inside homepage.php for guest users

**Comment by Cerothen** [comment]
Latest beta has full homepage authentication by service and overall

**Comment by lgromb** [comment]
From your branch right ? How can I switch easily between beta and master ?

**Comment by Cerothen** [comment]
Currently there isn't a way. I think @causefx will be adding a way to select the branch in the next version, he can comment more.
For now if you wanted to try it out you could download the zip make a new folder and copy/paste your db and config/config.php
