### ISSUE TITLE
v1.22 error:  "Why you trying to access this without logging in?!?! " when accessing from remote system

### ISSUE THREAD

**Issue by 14ngr15t** [causefx/Organizr#202]
Since upgrading to 1.22, when I login from a remote system on my network (not the system that Organizr is running on ) and go to the settings icon, I get the error message "Why you trying to access this without logging in?!?!".

I saw one old closed issue about this, but there wasn't really any resolution to it.  I have tried clearing the cache on browsers, logged in and out (I only have one, admin, user), and tried checking and unchecking the "Remember Me" option.

Any ideas why this is occurring?

**Comment by causefx** [comment]
Can you delete all the cookies please?

**Comment by 14ngr15t** [comment]
That did it.  Thanks!

**Comment by causefx** [comment]
last update changed the way the cookies worked, sorry about that.
