### ISSUE TITLE
Homepage is blank

### ISSUE THREAD

**Issue by mattman86** [causefx/Organizr#203]
I enabled the homepage but it just shows a blank screen. I'm not even sure where to get any logs to post.

**Comment by JigSawFr** [comment]
@mattman86 did you try a reload ?

**Comment by causefx** [comment]
did you enable the apps by inputting the URL's and API keys?

**Comment by causefx** [comment]
did you figure it out @mattman86

**Comment by mattman86** [comment]
Where do I put the URLs?

**Comment by causefx** [comment]
in settings there is a home icon, you set up the apps there. once done, add a new tab going to homepage.php

**Comment by mattman86** [comment]
Hey! There we go. Thanks, I like that much more than just opening up to one of the other tabs.

**Comment by causefx** [comment]
:)
