### ISSUE TITLE
Auth broken

### ISSUE THREAD

**Issue by roblandry** [causefx/Organizr#205]
I am not sure what has changed with regards to auth recently, however now i am unable to view anything other than the home page. When going to my homepage, it prompts for auth, and is successful, however when going to anything else including the settings page, it is not allowing me. on the settings page i see "Why you trying to access this without logging in?!?!" and on all other pages (using auth blocks in nginx) i get the unauthorized image and page.

**Comment by causefx** [comment]
Please delete all cookies. Then log back in.

**Comment by roblandry** [comment]
I wish that were the fix. but it is the same case across multiple browsers, android chrome, ubuntu firefox, and windows chrome. It very well could be related to my nginx reverse proxy, but i dont think anything changed with that in the last day or so. And the moment i am done logging in, the first page that appears is the unauthorized page.

**Comment by causefx** [comment]
can u email me you URL?  causefx at me dot com

**Comment by roblandry** [comment]
great support. multiple loging settings maybe? works now.
