### ISSUE TITLE
[Feature Request]Tabs for users, but not admin

### ISSUE THREAD

**Issue by atebeta** [causefx/Organizr#207]
I would like to be able to set a different default page for when a user is logged in/out. Right now it just shows a blank page if you set a default page that is not available for the guest group. 

Also, I would like to activate certain tabs for just the user group, but not admin.

**Comment by StevenChorkley** [comment]
Having a different default page would be awesome! +1

**Comment by causefx** [comment]
this will be in 2.0 in the future,
