### ISSUE TITLE
[Wiki Change] Authorization block causes issues

### ISSUE THREAD

**Issue by phendryx** [causefx/Organizr#208]
I personally have a few applications that have their own authentication behind organizr, though I am not sure if it's the other applications authentication causing the issue. 

When attempting to playback media in Emby, clicking "Play", the request timed out (I did not get logs of this).

When trying to log into DokuWiki, I got the following:

> 2017/03/28 07:41:04 [error] 100#100: *1 upstream timed out (110: Connection timed out) while reading response header from upstream, client: [ip address], server: [my domain], request: "POST [post url] HTTP/1.1", subrequest: "/auth.php", upstream: "[upstream url]", host: "[my domain]", referrer: "[referrer url]"

> 2017/03/28 07:41:04 [error] 100#100: *1 auth request unexpected status: 504 while sending to client, client: [ip address], server: [my domain], request: "POST [post url] HTTP/1.1", host: "[my domain]", referrer: "[referrer url]"

> 2017/03/28 07:45:23 [error] 99#99: *1 upstream timed out (110: Connection timed out) while reading response header from upstream, client: [ip address], server: [my domain], request: "POST [post url] HTTP/1.1", subrequest: "/auth.php", upstream: "[upsream url]", host: "[my domain]", referrer: "[referrer url]"

> 2017/03/28 07:45:23 [error] 99#99: *1 auth request unexpected status: 504 while sending to client, client: [ip address], server: [my domain], request: "POST [post url] HTTP/1.1", host: "[my domain]", referrer: "[referrer url]"

I was able to fix it by changing the authorization request in nginx from:

`
    location /auth-user {
        internal;
        rewrite ^ /auth.php?user;
    }
`

to

`
    location /auth-user {
        internal;
        proxy_pass https://[my domain]/auth.php?user;
    }
`

My suggestion is to change the wiki example to not rewrite, but to do a proxy_pass with full url to auth.php.

**Comment by causefx** [comment]
are you serving it to a different subdomain?

**Comment by phendryx** [comment]
Not a different subdomain, just subdirectories. LIke <host>/wiki, <host>/emby.

**Comment by phendryx** [comment]
Thinking about it, my forward facing nginx is doing proxy_pass to my organizr container, so that might be why. That being said, being part of the linuxserver.io group, I can guarantee many users of organizer are using this on unraid the way that I am and could run into the same issue.  Maybe list my solution as another example vs replacing your example?

**Comment by causefx** [comment]
we can do that :)

**Comment by JigSawFr** [comment]
@phendryx  i'm using your docker image to run organizr in a container and using let's encrypt image in front of it with nginx proxy pass, i'm using too full URL to make it work under subdomains. So full urls could be great for everyone and to cover all solutions.

**Comment by phendryx** [comment]
@JigSawFr yep, same setup here with letsencrypt + organizr + everything else, only I don't have subdirectories. I think it has to do with the fact that orgainzr itself is proxy_pass'ed and not being served directly from the nginx instance with the auth block.

**Comment by phendryx** [comment]
@causefx awesome work btw.. Ive handrolled a http auth solution with another similar app to organizr that was... bad (my solution, not the app). This is a great deal better with auth baked in. Few more things that I've seen in other issues (groups, adding users to groups, adding groups to tabs) that if implemented is only going to make orgainzr better.

Great job!

**Comment by JigSawFr** [comment]
@phendryx if you need an example of frontend nginx config for lets encrypt with subdomains / organizr auth support / errors handling / proxy pass and so let me know ;)

**Comment by phendryx** [comment]
@JigSawFr Thank you for the offer. The auth block was the only issue I was running into with orgainzr. The old app and the horribly implemented basic http auth has been retired from my setup :).

**Comment by causefx** [comment]
@phendryx thanks!  I appreciate it.  I'm still trying to plan out the groups options and such.  Trying to figure out how to make it seemless on an upgrade.

**Comment by phendryx** [comment]
@causefx My personal suggestion would be to make a default group, all tabs and users are part of that group and let the user change it after that.

**Comment by pyrostic** [comment]
Hey Paul, are you by chance on Windows? I'm looking for an automated method
for let's encrypt on Windows, right now I do it all manual and it's a drag

**Comment by phendryx** [comment]
@pyrostic I'm using the nginx+letsencrypt container made by a fellow member of LinuxServer.io, which is backed by either ubuntu or alpine linux (can't remember which).

I'm assuming when you say windows, you are using IIS? I did a quick search and found some suggestions on the first hit, [here](https://weblog.west-wind.com/posts/2016/feb/22/using-lets-encrypt-with-iis-on-windows). No idea if that helps or not but the LetsEncrypt-Win-Simple solution looks pretty automated for setup and cert renewal.

**Comment by pyrostic** [comment]
I'm using nginx

**Comment by suineg** [comment]
@JigSawFr I would love to see that config. I am playing with mine right now and hoping to get it working by myself but if not, an example would pull me out of a rut.

**Comment by phendryx** [comment]
@pyrostic Sorry for the delay. Didn't notice the reply until there was another reply on the thread today. Nginx + windows + automation, I have no clue about with letsencrypt. I'm sure it could be done by frankensteining a script together from both realms (windows+iis and *nix+nginx).

**Comment by JigSawFr** [comment]
@suineg yes, you can take a look here: https://github.com/causefx/Organizr/issues/210#issuecomment-290334534

**Comment by causefx** [comment]
this is completed now.
