### ISSUE TITLE
PHPmailer instead of php's own mail-sender

### ISSUE THREAD

**Issue by si0972** [causefx/Organizr#209]
My current setup is a machine running Win10 with nginx and PlexPy add Sonarr. I reach my server with a sub-domain with a DNS forwarder, i use my webhost's mail-service, which do not allow sending smtp requests without auth.  I read online to discover PHPMailer did this. is it a easy way to implement/edit sending mail via PHPMailer.

**Comment by causefx** [comment]
Already done. This will be on next update :)

**Comment by si0972** [comment]
Thanks :)
Keep on the amazing work.

**Comment by JigSawFr** [comment]
@causefx integration of SparkPost could be great too ;) https://www.sparkpost.com
_Email delivery services built for developers, by developers_
Official PHP library available here : https://github.com/sparkpost/php-sparkpost

**Comment by causefx** [comment]
@JigSawFr what are the advantages over https://github.com/PHPMailer/PHPMailer

**Comment by pyrostic** [comment]
I'm using Sendmail with Auth.  Not hard.

**Comment by JigSawFr** [comment]
@causefx it's two different things, php mailer is a php library to send emails via smtp protocols. SparkPost is an emailing service (free/paid 3rd party) which expose an API to send emails. They could be implemented together.
