### ISSUE TITLE
Fatal error: Uncaught PDOException

### ISSUE THREAD

**Issue by levy4858** [causefx/Organizr#21]
Hey,

I get this error:

Fatal error: Uncaught PDOException: could not find driver in /var/www/html/organizr/user.php:153 Stack trace: #0 /var/www/html/organizr/user.php(153): PDO->__construct('sqlite:../users...') #1 /var/www/html/organizr/index.php(17): User->__construct('registration_ca...') #2 {main} thrown in /var/www/html/organizr/user.php on line 153

Can you help me with it?

**Comment by rix1337** [comment]
Are you sure you have php5-pdo_sqlite & php5-sqlite3 installed?

**Comment by causefx** [comment]
exactly what @rix1337 said,  open up check.php and it will tell you whats wrong.

**Comment by levy4858** [comment]
I use php 7.0 and this is what i get now:

Fatal error: Uncaught PDOException: SQLSTATE[HY000] [14] unable to open database file in /var/www/html/Organizr/user.php:153 Stack trace: #0 /var/www/html/Organizr/user.php(153): PDO->__construct('sqlite:../users...') #1 /var/www/html/Organizr/index.php(17): User->__construct('registration_ca...') #2 {main} thrown in /var/www/html/Organizr/user.php on line 153

I've done apt-get install php7.0-sqlite

**Comment by causefx** [comment]
open the check.php file and post the output please.

**Comment by levy4858** [comment]
/var/www/html was not writable... 

Thanks for your help!

**Comment by causefx** [comment]
Awesome.  so you are good to go?

**Comment by phairplay** [comment]
hi sorry to high jack
im also getting the top error and have php 7 ive uncommented both sqlite in the php.ini
do i need to install php sqlite and if so how do i did it on windows 10?

**Comment by levy4858** [comment]
Yes :) It's works well!

**Comment by levy4858** [comment]
I think you needed also sqlite but I am not sure

**Comment by phairplay** [comment]
i can see sqlite.dll files in the ext folder of php

**Comment by causefx** [comment]
In comment the pdo_sqlite file

**Comment by phairplay** [comment]
sorry do you mean un comment?
extension=php_pdo_sqlite.dll
which ive done

**Comment by causefx** [comment]
Yes. Restart apache/nginx. Open up check.php. Paste output please

**Comment by phairplay** [comment]
sorry where is check.php or how do i do it?

**Comment by phairplay** [comment]
PDO_SQLITE
PDO_SQLITE is NOT loaded! Please install it before proceeding
If you are on Windows, please uncomment this line in php.ini: ;extension=php_pdo_sqlite.dll
PDO
PDO is loaded and ready to rock-n-roll! Good 2 Go!
C:\nginx-1.8.0\html
Permissions: 777
C:\nginx-1.8.0\html is writable and ready to rock-n-roll! Good 2 Go!
C:\nginx-1.8.0
Permissions: 777
C:\nginx-1.8.0 is writable and ready to rock-n-roll! Good 2 Go!

**Comment by causefx** [comment]
And that ext folder to php.ini

**Comment by phairplay** [comment]
Yes it is

**Comment by causefx** [comment]
How do u have it typed up?

**Comment by phairplay** [comment]
extension=php_pdo_sqlite.dll 
all i did was remove ;

**Comment by causefx** [comment]
you also need to have:
`
extension_dir = C:\path\to\php\ext\
`

**Comment by phairplay** [comment]
That's is thank you :)

**Comment by causefx** [comment]
:) you're welcome
