### ISSUE TITLE
plexy py reverse proxy

### ISSUE THREAD

**Issue by dejected1** [causefx/Organizr#210]
So ive been able to setup reverse proxy with nginx on all my service except plexpy. When i try and access it, says page is taking to long to respond. After it says that the address bar redirects to: ddns:8181/plexpy/. even thou i typed in ddns:9111/plexpy. 

I set the http root in plexy py to /plexpy and pointed ngnix using: 

#plexpy	
		location /plexpy {
		  proxy_pass http://192.168.2.197:8181;
		    proxy_set_header Host $host;
		    proxy_set_header X-Real-IP $remote_addr;
		    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    	}

I also tried location /plexpy/ and  proxy_pass http://192.168.2.197:8181/; No change. 
I also tried setting plexpy back to / for http root and then using in nginx: 

#plexypy
		location /plexpy/  {
			proxy_pass  http://192.168.2.197:8181/;
    proxy_redirect                off;
    proxy_set_header              Host            $host;
    proxy_set_header              X-Real-IP       $remote_addr;
    proxy_set_header              X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header              X-plexpy-Base   "/plexypy/";
    proxy_pass_header             Set-Cookie;
    proxy_pass_header             P3P;
   	}

No go. I had success with the second config in setting up other programs. 
I also tried location /plexpy and proxy_pass  http://192.168.2.197:8181 and proxy_set_header              X-plexpy-Base   "/plexypy"; .

NO change. Any help would be great. ive setup 10 other programs using the above 2 methods successfully for reverse proxy. Only plexpy is being stupid.

**Comment by causefx** [comment]
plexpy always give me a hastle too.  I will take a look at my setup when i get home

**Comment by lgromb** [comment]
The only way I got it working is to point directly to ddns:port/plexpy/auth/login or /home

Better to put the URL to point to /auth/login so you won't have the automatic redirection on /home if you're not logged in.

**Comment by dejected1** [comment]
igromb: i have done so many iterations of this code its starting to blur together what i've tried and what i haven't' would you mind posting you nginx lines for plexpy and what your pointing it too in organizr?

**Comment by lgromb** [comment]
Sorry about formatting, I still can't figure out how Github handles chariotting.

nginx :

`#PlexPy - Plex Stats
location /plexpy        {
        auth_request /auth;
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header    X-Forwarded-Proto   $scheme;
        proxy_set_header    X-Forwarded-Ssl     on;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_pass http://192.168.1.33:8181;`

I use https://my.domain.fr/plexpy/auth/login to enter plexpy. I can access it via  https://my.domain.fr/plexpy/home after I'm logged in but otherwise it redirects me to the local listening port of nginx which obviously is not open outside of my Lan.

**Comment by dejected1** [comment]
Success! I had the code right the whole time i just never thought to manually point it to plexpy/home. I love this program and this is far and way the most help i've ever received on the internet. You have a subscriber for life with me.

**Comment by lgromb** [comment]
That's nice to hear! But I'm not sure it's the right way to handle reverse proxy with plexpy. It should be able to rewrite itself to /home as long as the http root setting is right in its settings. Having this kind of redirection is a little bit tricky in terms of security for me as anyone who tries your URL will have a glance of your inside LAN setup because of poorly configured redirections. It works as is, but I'm pretty sure we are missing something.

**Comment by dejected1** [comment]
noted

**Comment by JigSawFr** [comment]
This is my nains config file with organizr server block and plexpy server block as a great working example (with ssl, organizr auth, upstreams, proxy_pass and subdomains):

```
# listening on port 80 disabled by default, remove the "#" signs to enable
# redirect all traffic to https
server {
	listen 80;
	server_name _;
	return 301 https://$host$request_uri;
}

##########################
## UpStreams - All APPs ##
##########################
upstream organizr-upstream 	{ server 172.17.0.1:900; }
upstream plex-upstream 		{ server 172.17.0.1:901; }
upstream plexpy-upstream 	{ server 172.17.0.1:902; }
upstream rutorrent-upstream { server 172.17.0.1:903; }
upstream sickrage-upstream 	{ server 172.17.0.1:904; }
upstream nextcloud-upstream { server 172.17.0.1:905; }
upstream radarr-upstream 	{ server 172.17.0.1:906; }
upstream jackett-upstream 	{ server 172.17.0.1:907; }

#####################################
## Organizr -- Domain Server Block ##
#####################################
server {

	listen 443 ssl default_server;

	root /config/www;
	index index.html index.htm index.php;

	# Domain
	server_name _;

	ssl_certificate /config/keys/letsencrypt/fullchain.pem;
	ssl_certificate_key /config/keys/letsencrypt/privkey.pem;
	ssl_dhparam /config/nginx/dhparams.pem;
	ssl_ciphers 'ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-DSS-AES128-GCM-SHA256:kEDH+AESGCM:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-DSS-AES128-SHA256:DHE-RSA-AES256-SHA256:DHE-DSS-AES256-SHA:DHE-RSA-AES256-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:AES:CAMELLIA:DES-CBC3-SHA:!aNULL:!eNULL:!EXPORT:!DES:!RC4:!MD5:!PSK:!aECDH:!EDH-DSS-DES-CBC3-SHA:!EDH-RSA-DES-CBC3-SHA:!KRB5-DES-CBC3-SHA';
	ssl_prefer_server_ciphers on;

	client_max_body_size 0;

	# Errors Page
	error_page 400 401 402 403 404 /error.php?error=$status;

	# Reverse Proxy App
	location / {
		proxy_pass http://organizr-upstream;
		include /config/nginx/proxy.conf;
    	proxy_bind $server_addr;
    	proxy_set_header X-Forwarded-Host $server_name;
    	proxy_set_header X-Forwarded-Ssl     on;
		add_header X-Frame-Options SAMEORIGIN;
	}

	# Authentication
	location /auth-admin {
        #internal;
        rewrite ^ /auth.php?admin;
	}

}

######################################
## PlexPy -- Subdomain Server Block ##
######################################
server {
	listen 443 ssl;

	root /config/www;
	index index.html index.htm index.php;

	# Subdomain
	server_name stats.domain.fr;

	ssl_certificate /config/keys/letsencrypt/fullchain.pem;
	ssl_certificate_key /config/keys/letsencrypt/privkey.pem;
	ssl_dhparam /config/nginx/dhparams.pem;
	ssl_ciphers 'ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-DSS-AES128-GCM-SHA256:kEDH+AESGCM:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-DSS-AES128-SHA256:DHE-RSA-AES256-SHA256:DHE-DSS-AES256-SHA:DHE-RSA-AES256-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:AES:CAMELLIA:DES-CBC3-SHA:!aNULL:!eNULL:!EXPORT:!DES:!RC4:!MD5:!PSK:!aECDH:!EDH-DSS-DES-CBC3-SHA:!EDH-RSA-DES-CBC3-SHA:!KRB5-DES-CBC3-SHA';
	ssl_prefer_server_ciphers on;

	client_max_body_size 0;

	# Errors Page
	error_page 400 401 402 403 404 https://www.domain.fr/error.php?error=$status;

	# Authentication
	location = /auth-admin {
    	internal;
    	proxy_pass https://www.domain.fr/auth-admin;
    	proxy_pass_request_body off;
    	proxy_set_header Content-Length "";
    	#proxy_set_header X-Original-URI $request_uri;
	}

	# Reverse Proxy App
	location / {
		auth_request /auth-admin;
		proxy_pass http://plexpy-upstream;
		include /config/nginx/proxy.conf;
    	proxy_bind $server_addr;
    	proxy_set_header X-Forwarded-Host $server_name;
    	proxy_set_header X-Forwarded-Ssl     on;
	}
}
```

My proxy.conf:
```
client_max_body_size 10m;
client_body_buffer_size 128k;

#Timeout if the real server is dead
proxy_next_upstream error timeout invalid_header http_500 http_502 http_503;

# Advanced Proxy Config
send_timeout 5m;
proxy_read_timeout 240;
proxy_send_timeout 240;
proxy_connect_timeout 240;

# Basic Proxy Config
proxy_set_header Host $host:$server_port;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header X-Forwarded-Proto https;
proxy_redirect  http://  $scheme://;
proxy_http_version 1.1;
proxy_set_header Connection "";
proxy_cache_bypass $cookie_session;
proxy_no_cache $cookie_session;
proxy_buffers 32 4k;
```

Some things can be optimized :)
