### ISSUE TITLE
error on first run

### ISSUE THREAD

**Issue by Giantdouche33** [causefx/Organizr#211]
Fatal error: Uncaught PDOException: could not find driver in /srv/rutorrent/home/Organizr/user.php:208 Stack trace: #0 /srv/rutorrent/home/Organizr/user.php(208): PDO->__construct('sqlite:/srv/rut...') #1 /srv/rutorrent/home/Organizr/index.php(72): User->__construct('registration_ca...') #2 {main} thrown in /srv/rutorrent/home/Organizr/user.php on line 208

**Comment by causefx** [comment]
* **WINDOWS:** Set your permissions on to `Full Control` for `Everyone `for your directories 
 * **LINUX:** Run `sudo chown -R www-data:www-data /path/to/Organizr`
 * **Synology**

**Comment by Giantdouche33** [comment]
thankyou for your help. it was already chowned. tried the sqllite install and it's setup but still getting the same error

**Comment by causefx** [comment]
what OS?
