### ISSUE TITLE
More Images - Don't look at me lol

### ISSUE THREAD

**Issue by causefx** [causefx/Organizr#212]
![organizr_logo](https://cloud.githubusercontent.com/assets/16184466/24440635/1e5c3378-140a-11e7-8168-23ad4743b5fe.png)
![organizr_logo_d](https://cloud.githubusercontent.com/assets/16184466/24440636/1e5e2002-140a-11e7-8da1-1cd68745cedd.png)
![organizr-logo-h](https://cloud.githubusercontent.com/assets/16184466/24440646/24c97996-140a-11e7-92a8-5fe9fa7fe7d1.png)
![organizr-logo-h-d](https://cloud.githubusercontent.com/assets/16184466/24440647/24d98a0c-140a-11e7-9867-687096325489.png)
![organizr_logo](https://cloud.githubusercontent.com/assets/16184466/24440653/29eb3ebe-140a-11e7-9f2a-edf23a372f99.png)
![organizr_logo_d](https://cloud.githubusercontent.com/assets/16184466/24440654/29ecd364-140a-11e7-966c-949b5ea06cd9.png)

**Comment by SgtBatten** [comment]
Ooohhh nice

**Comment by JigSawFr** [comment]
Great logo !

**Comment by causefx** [comment]
:+1:  LOL, title said don't look at me.... jk
