### ISSUE TITLE
Error on Homepage with SabNZBD

### ISSUE THREAD

**Issue by rudyvarner** [causefx/Organizr#214]
Getting the following error now in the SABNZBD section of the homepage:

Notice: Use of undefined constant HTTP_REFERER - assumed 'HTTP_REFERER' in C:\xampp\htdocs\downloader.php on line 3

**Comment by causefx** [comment]
crap, i forgot to include the quotes.

can you try this for line 3:

`$auth = strpos($_SERVER['HTTP_REFERER'], "homepage.php");`

**Comment by rudyvarner** [comment]
Yes, that fixes it.

**Comment by pyrostic** [comment]
Also have it on NZB get. Probably same fix

**Comment by twofacedsquare** [comment]
Confirmed same fix for NZBGet. 

Thanks
