### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by fryfrog** [causefx/Organizr#216]
Episodes and movies in calendar of home page should link to the entry in the daemon, so you can click it and go directly to the show (in sonarr/sickbeard/etc) or movie (radarr/cp/etc).

**Comment by causefx** [comment]
thats a good idea but im not sure it can be implements seamlessly, as some people don't forward their services to the outside.  What i could do is link it to one of these services:

```
"tvdbId": 281470,
      "tvRageId": 38804,
      "tvMazeId": 1589,
      "imdbId": "tt3501584
```

**Comment by SgtBatten** [comment]
That would work nicely
