### ISSUE TITLE
homepage inaccessible and can't add tabs.

### ISSUE THREAD

**Issue by croaking** [causefx/Organizr#219]
Sorry if this is a straightforward question.  I've used Muximux in the past, like the screenshots of Organizr, so I decided to give it a try.  This is on top of nginx and as a reverse proxy.  Upon first login it let's me specify the location of the auth databse, which I've done, and create a user, then login.  Once I'm logged in, however I can see a white gear icon on the red tab in the top left, but clicking on it does nothing.  Clicking on the 3 parallel lines in the top left corner expands that frame out but that's it.  Clicking on settings does nothing.  I've tailed through the nginx error and auth logs and see nothing either.

This is ubuntu 16.04.2 LTS with NGINX.  Guessing that maybe it has something to do with php or a missing dependency, here's the output of dpkg:

croaking@home:/var/log/apache2$ dpkg-query -l | grep php
ii  libapache2-mod-php                                          1:7.0+35ubuntu6                               all          server-side, HTML-embedded scripting language (Apache 2 module) (default)
rc  libapache2-mod-php5                                         5.6.11+dfsg-1ubuntu3.3                        amd64        server-side, HTML-embedded scripting language (Apache 2 module)
ii  libapache2-mod-php7.0                                       7.0.15-0ubuntu0.16.04.4                       amd64        server-side, HTML-embedded scripting language (Apache 2 module)
ii  php-common                                                  1:35ubuntu6                                   all          Common files for PHP packages
ii  php-json                                                    1:7.0+35ubuntu6                               all          JSON module for PHP [default]
ii  php-mysql                                                   1:7.0+35ubuntu6                               all          MySQL module for PHP [default]
ii  php-zip                                                     1:7.0+35ubuntu6                               all          Zip module for PHP [default]
rc  php5-cli                                                    5.6.11+dfsg-1ubuntu3.3                        amd64        command-line interpreter for the php5 scripting language
ii  php5-common                                                 5.6.11+dfsg-1ubuntu3.3                        amd64        Common files for packages built from the php5 source
rc  php5-json                                                   1.3.7-1                                       amd64        JSON module for php5
rc  php5-readline                                               5.6.11+dfsg-1ubuntu3.3                        amd64        Readline module for php5
ii  php7.0-cli                                                  7.0.15-0ubuntu0.16.04.4                       amd64        command-line interpreter for the PHP scripting language
ii  php7.0-common                                               7.0.15-0ubuntu0.16.04.4                       amd64        documentation, examples and common module for PHP
ii  php7.0-fpm                                                  7.0.15-0ubuntu0.16.04.4                       amd64        server-side, HTML-embedded scripting language (FPM-CGI binary)
ii  php7.0-json                                                 7.0.15-0ubuntu0.16.04.4                       amd64        JSON module for PHP
ii  php7.0-mysql                                                7.0.15-0ubuntu0.16.04.4                       amd64        MySQL module for PHP
ii  php7.0-opcache                                              7.0.15-0ubuntu0.16.04.4                       amd64        Zend OpCache module for PHP
ii  php7.0-readline                                             7.0.15-0ubuntu0.16.04.4                       amd64        readline module for PHP
ii  php7.0-sqlite3                                              7.0.15-0ubuntu0.16.04.4                       amd64        SQLite3 module for PHP
ii  php7.0-xml                                                  7.0.15-0ubuntu0.16.04.4                       amd64        DOM, SimpleXML, WDDX, XML, and XSL module for PHP
ii  php7.0-zip                                                  7.0.15-0ubuntu0.16.04.4                       amd64        Zip module for PHP

Screenshot attached, I appreciate any help you all can provide:
![2017-03-31_15-30-50](https://cloud.githubusercontent.com/assets/16194696/24568311/279a311e-1627-11e7-9636-88f38e214a6a.png)

**Comment by causefx** [comment]
Can you access it by bypassing the reverse proxy by going to URL:port?  Does setttins load that way?

Does console log say anything in browser?

**Comment by croaking** [comment]
Sandbox access violation in the browser console:  
Blocked a frame from accessing a page at "null"

![2017-03-31_16-59-43](https://cloud.githubusercontent.com/assets/16194696/24570866/7ff3ee16-1633-11e7-9e5a-5cd880b7266b.png)

**Comment by croaking** [comment]
Looks like I need something like this in the nginx config?
add_header X-Frame-Options SAMEORIGIN;

**Comment by causefx** [comment]
Actually the opposite. Proxy_hide_header

**Comment by causefx** [comment]
I'm mobile right now but when I get home I can help.

**Comment by croaking** [comment]
not sure how this got closed, but that wasn't intentional

**Comment by causefx** [comment]
`proxy_hide_header 'x-frame-options';` add that to your reverse proxy block

**Comment by JigSawFr** [comment]
Exactly :)
