### ISSUE TITLE
[Feature Request] Deluge on home page

### ISSUE THREAD

**Issue by roblandry** [causefx/Organizr#220]
I would love to have deluge added to the home page if at all possible just like nzbget.

**Comment by causefx** [comment]
will look into it :)

**Comment by WindfallProphet** [comment]
@causefx Could you take a look at including other torrent clients as well, such as rTorrent and Transmission? If it'd be easier, I can open another issue.

**Comment by MrMxyzptlk** [comment]
I 2nd this request...Deluge is my torrent down loader of choice.

**Comment by xFilosofx** [comment]
Yep, it's can be nice extension for HomePage

**Comment by causefx** [comment]
This is on v2 now.
