### ISSUE TITLE
New settings layout on smaller screens

### ISSUE THREAD

**Issue by lgromb** [causefx/Organizr#222]
Hi, it's me and my small laptop again. You did some awesome improvements with the "slim topbar" but now, since you've moved the settings tab to the left, some options are not aligned within the tabs tab (?)

ie : the "No iframe" button is chariotted because there is not enough width on the line for it to show next to others.

Please think of small screens :D

PS : When you click on any tab on the left (in the settings), there is no way of closing the current tab to return to the tab settings.

**Comment by StevenChorkley** [comment]
I can't seem to be able to scroll in the settings app on my phone either. The homepage settings are in a weird location too. I'd try to fix it, but my CSS is below par! 

![20170403_105922](https://cloud.githubusercontent.com/assets/10834935/24605454/d60f3aa6-1860-11e7-9ffc-af70cc0a1db2.png)

**Comment by causefx** [comment]
What is the resolution of your screen?

**Comment by causefx** [comment]
I fixed the scroll bug last night. I will release today.

**Comment by StevenChorkley** [comment]
Thank you! The resolution given to web pages is 412 x 732

It's a Galaxy S7 if that helps

**Comment by causefx** [comment]
sorry, the resolution question was for @lgromb

**Comment by lgromb** [comment]
Sorry for the short answer :

1366*768

Envoyé depuis Alto
On mardi 4 avril 2017 à 00:30 causefx <notifications@github.com> wrote:

sorry, the resolution question was for @lgromb

**Comment by causefx** [comment]
this is how mine looks when I resize to 1366x768:
![image](https://cloud.githubusercontent.com/assets/16184466/24635133/7de8c04c-1886-11e7-8420-328e6bc620cd.png)


I will try and make it smaller for you.

**Comment by lgromb** [comment]
Love the new menu, thanks a lot mate :)
