### ISSUE TITLE
Since latest update I cannot touch scroll or pinch to zoom on mobile

### ISSUE THREAD

**Issue by SgtBatten** [causefx/Organizr#223]
When I edit my homepage settings for example I click a field I want to type in. My phone zooms in to help me see what I'm typing and now I can no longer swipe in any direction or pinch to zoom back out.

Basically I am unable to move my view to see the save button and I have to refresh the entire site.

**Comment by SgtBatten** [comment]
Edit: the issue is with the panel that slides in from the right.

If I click settings then click homepage the panel slides in from the right. 

Now I can pinch to zoom if I use the portion of the screen on the left not covered by the new panel. If I try to pinch to zoom on the right side where the panel is though it does nothing.

**Comment by causefx** [comment]
yup, this was a bug that is now fixed.  I'm getting ready to commit the new version.
