### ISSUE TITLE
Homepage plex integration with Plex cloud

### ISSUE THREAD

**Issue by SgtBatten** [causefx/Organizr#224]
I am trying to get my homepage to work with Plex cloud.

It successfully can read the new movies and TV shows added but I get a bunch of errors at the same time.

https://imgur.com/gallery/FqIwV

**Comment by causefx** [comment]
ahhhh, never tried with Plex CLoud..... can you join gitter real quick?

**Comment by SgtBatten** [comment]
I'll have to come in later bro sorry. In about 3 hours as of this message if you're around

**Comment by SJ50** [comment]
how to use this?
