### ISSUE TITLE
Latest Update (.29) Makes Portrait View Garbled

### ISSUE THREAD

**Issue by JoeStratton** [causefx/Organizr#227]
See image, newest design layout looks great, but not on portrait. 

![capture](https://cloud.githubusercontent.com/assets/6180439/24658984/3b23d2fe-1900-11e7-8909-47794599a55c.PNG)

**Comment by causefx** [comment]
how big is the resolution on your screen?

**Comment by JoeStratton** [comment]
1080x1920

**Comment by causefx** [comment]
ahhh ok, so i will mess around with a 1080 width.

**Comment by JoeStratton** [comment]
Thanks! I like my PLP monitor layout :)
