### ISSUE TITLE
Receiving Chrome out of memory errors after 1.29 upgrade

### ISSUE THREAD

**Issue by JoeStratton** [causefx/Organizr#228]
I am not sure what to provide, but after a good amount of time (15-45 min) my organizr tab in chrome will die with an out of memory error. I have to refresh the page. This never happened until the upgrade.

Happy to provide anything needed.

**Comment by causefx** [comment]
it's only that tab?

**Comment by JoeStratton** [comment]
Any tab from within organizr, does not matter which.

**Comment by causefx** [comment]
what does the memory usage look like?

**Comment by JoeStratton** [comment]
On first load it is sitting around 300MB (using chrome's task manager) and im up to 3.5GB so far and rising...

**Comment by causefx** [comment]
I have Org open with about 7 Org inner tabs open plus settings:

![image](https://cloud.githubusercontent.com/assets/16184466/24677862/170aed16-193d-11e7-9c4f-ae6efd368368.png)

**Comment by JoeStratton** [comment]
Yes any tab I use hits about 4GB before crashing. Maybe it is specific to the docker container I am using? I am not sure how to troubleshoot that.

**Comment by causefx** [comment]
this is super odd.  make all tabs non-guest and log out

see what it looks like that,

**Comment by JoeStratton** [comment]
Up to 1.2GB so far, doesnt seem to be an improvement. I cleared my cache as well.

**Comment by causefx** [comment]
hmmm, yeah something is off.  I will keep looking.

**Comment by causefx** [comment]
can you email me the URL?  I will see if it uses alot of mem on my end.

**Comment by JoeStratton** [comment]
What is your email

**Comment by causefx** [comment]
oh yeah, causefx at me dot com

**Comment by JoeStratton** [comment]
sent

**Comment by JoeStratton** [comment]
just an update, same thing occurring in 1.30

**Comment by Cerothen** [comment]
Still happening on the latest?

**Comment by JoeStratton** [comment]
nope, appears to be fixed

**Comment by Cerothen** [comment]
Great
