### ISSUE TITLE
Trouble Installing on Ubuntu 16.04

### ISSUE THREAD

**Issue by derekbcaldwell** [causefx/Organizr#231]
I installed from git on /var/www/html/Organizr and when I visit in browser to check.php it downloads the php file. I need some help getting php, nginx, and my DB setup... I am definitely a noob at all of this and I would really appreciate the help.

Thanks!

**Comment by causefx** [comment]
you need to uncomment the php block on your nginx conf file

**Comment by trancefam** [comment]
I had the same problem yesterday. Total noob on Ubuntu myself. I did what causefx said and along with installing php and it worked after that.

**Comment by derekbcaldwell** [comment]
Cool I will try doing that when I get home. If I have no luck I will post in my nguni confused file for further help. Thanks for the help so far! What installations of PHP do I need for ubuntu?

**Comment by causefx** [comment]
php-7.0-fpm

**Comment by derekbcaldwell** [comment]
Here is my nguni config:

server {
    listen 80;
    listen [::]:80;

    root /var/www/html/Organizr;
    index index.php index.html index.htm;

    server_name localhost;

    location / {
        try_files $uri $uri/ =404;
    }

    location ~ \.php$ {
        try_files $uri =404;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass unix:/var/run/php7-fpm.sock;
        fastc
Here is my nguni config:

server {
    listen 80;
    listen [::]:80;

    root /var/www/html/Organizr;
    index index.php index.html index.htm;

    server_name localhost;

    location / {
        try_files $uri $uri/ =404;
    }

    location ~ \.php$ {
        try_files $uri =404;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass unix:/var/run/php7-fpm.sock;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
    }
}

**Comment by derekbcaldwell** [comment]
I have narrowed it down to the PHP 7.0 fpm service not starting.
<img width="1112" alt="screen shot 2017-04-06 at 8 55 02 pm" src="https://cloud.githubusercontent.com/assets/23532884/24781153/70f97994-1b0b-11e7-8f27-33e87b2d7a3c.png">

**Comment by causefx** [comment]
was php-fpm.conf edited?

**Comment by derekbcaldwell** [comment]
Php-fpm was never installed. Fixed! And I'm digging the interface! Thanks so much!!!

**Comment by causefx** [comment]
Thank you. I appreciate it.
