### ISSUE TITLE
Trying to reset password, leads to 504 error

### ISSUE THREAD

**Issue by trancefam** [causefx/Organizr#232]
I seem to have gotten myself into a bit of trouble. I have organizer installed on Ubuntu 16.04 running nginx reverse proxy. Everything is running smooth except for an unforeseen snag. I entered my email information, enabled mail in settings and then logged out of organizr. I immediately clicked forgot password to verify that it works, but when I do it just loads and eventually leads to 504 gateway timeout.  Now I am unable to login with my old password and still didn't receive the reset email. That was the only admin account :( Is there anything I can do, so I don't have to start over?

I am pretty new to Ubuntu, and the command line is a bit daunting. Any help is greatly appreciated.

**Comment by causefx** [comment]
was the smtp settings setup?

**Comment by trancefam** [comment]
Yes. I actually set up smtp settings in ombi first and verified they were correct, then copied those same settings to organizer. After that I clicked to enable mail at the very bottom of the settings page, clicked save, logged out, and then hit reset password. 

There is always a chance I typed something wrong. Is there any way for me to edit the user db file to promote another profile I have to an admin?

**Comment by causefx** [comment]
can you mount the file path to your computer?  if so, you can download DB Browser for SQLite.


also `cat databaseLocation.ini.php` to check your settings

**Comment by causefx** [comment]
also FYI, my gmail settings are like this:

```
smtpHost = "smtp.gmail.com"
smtpHostPort = "587"
smtpHostAuth = "true"
smtpHostUsername = "email@gmail.com"
smtpHostPassword = "Password"
smtpHostSenderName = "Organizr"
smtpHostSenderEmail = "no-reply@Organizr"
```

**Comment by trancefam** [comment]
I took a look at the databaseLocation.ini.php file and changed the port. Yahoo email says you can use port 465 or 587. I had 465, so I changed it to 587 and restarted nginx. Password reset link now works.

Thanks for your help!

**Comment by causefx** [comment]
sweet! i'm glad
