### ISSUE TITLE
Improve Color Editing

### ISSUE THREAD

**Issue by SubNoizey** [causefx/Organizr#234]
Hey,

Saw your post on reddit and figured I'd remind you here as it's easier to keep track of. 

Can you expose all the new elements of the homepage and settings slider/menu to perhaps a revamped edit colors/theme page.

There's a lot of white that I'd like to tone down and a lot of text color I'd like to change.

**Comment by causefx** [comment]
you want to add color options to color section for homepage design?

**Comment by SubNoizey** [comment]
basically yeah. I want to make a dark theme and I can make everything dark except for all the new elements you've since added. (the homepage and settings is still all white)

**Comment by causefx** [comment]
this is now achieved through custom HTML and CSS options.
