### ISSUE TITLE
Plex Images Broken

### ISSUE THREAD

**Issue by rudyvarner** [causefx/Organizr#238]
Looks like the images from Plex are now broken on the homepage as of 1.30 release. Is there anything that I can do to check to verify it's not on my end?

![image](https://cloud.githubusercontent.com/assets/5005529/24808918/c9d19602-1b8b-11e7-9b36-2fa700d2530a.png)

**Comment by causefx** [comment]
Right click and check the link on the image. Try loading in URL?

**Comment by lucidonlinenet** [comment]
Having the same issue.  Opening the image in a new tab I am getting Organizr-master/image.php?img=/library/metadata/31832/thumb/1491379121&height=150&width=100

**Comment by rudyvarner** [comment]
same here. http://_private_/image.php?img=/library/metadata/211637/thumb/1489710328&height=150&width=100

**Comment by lucidonlinenet** [comment]
If I roll back the image.php file to the 1.29 version everything works again.

**Comment by Cerothen** [comment]
What happens when you try this in a new tab:

http://private/image.php?source=plex&img=/library/metadata/211637/thumb/1489710328&height=150&width=100

**Comment by rudyvarner** [comment]
The image displays when I open it in a new tab,

**Comment by Cerothen** [comment]
That's been added in the current development branch but just in case we also applied a fix directly to the images file to hopefully resolve the issue for good.
