### ISSUE TITLE
Request: Persistent Logins

### ISSUE THREAD

**Issue by grokdesigns** [causefx/Organizr#24]
Can persistent logins via cookie be added? I have my dashboard set as the homepage of my browser and I would be awesome if I didn't have to log in every time I opened it.

**Comment by causefx** [comment]
We can just change the session time of the logins, it is currently in the users.php file. I'll see about making it a custom variable.

**Comment by SgtBatten** [comment]
A per user basis would be awesome but if it's just the admin account that can be easily increased or sit indefinitely that would be awesome

**Comment by grokdesigns** [comment]
The issue is that currently, the PHPSESSID cookie that gets created has a default lifetime of '0' and is destroyed when the browser closes. I added the following to the top of user.php and it now works as I hoped:

```
$cookiename='Organizr'; //Name the cookie
$lifetime=86400; //Cookie lifetime in seconds (86400=24 Hours)
$path='/'; //Set the path
$domain='.domain.com'; //Domain cookie is stored under (period before TLD will apply to all subdomains)
session_start();
setcookie($cookiename,session_id(),time()+$lifetime,$path,$domain);
```

**Comment by causefx** [comment]
yea, we are using PHP Session variables instead of Cookies for security reasons.

**Comment by grokdesigns** [comment]
I can understand that. Maybe adding a "Remember Me" option to the login form would be an acceptable compromise?

**Comment by causefx** [comment]
I will follow up on this prior to v1.0 :)
