### ISSUE TITLE
Login Error when Plex auth is enabled

### ISSUE THREAD

**Issue by tanjer45** [causefx/Organizr#245]
First thing first: Great job with Organizr, it´s great!

I´m on the lates release of Organizr and enabled the Plex auth feature. I saved the Changes and logged out.

When i try to login again, using Plex credentials or my default organizr credentials the application is getting a "Fatal Error"

`Fatal error: Uncaught Error: Call to undefined function curl_init() in /var/www/Organizr/functions.php:271 Stack trace: #0 /var/www/Organizr/functions.php(145): curl_get('https://plex.tv...', Array) #1 /var/www/Organizr/user.php(680): plugin_auth_plex('Username', 'Password') #2 /var/www/Organizr/user.php(309): User->login_user('Username', '548f3c4dde204f1...', true, 'Password') #3 /var/www/Organizr/user.php(261): User->login() #4 /var/www/Organizr/user.php(242): User->process('registration_ca...') #5 /var/www/Organizr/index.php(72): User->__construct('registration_ca...') #6 {main} thrown in /var/www/Organizr/functions.php on line 271`

I have restarted the server and cleared my cookies, but it did not help.
I have edited my username and password to "Username" "Password"
Hope we can solve it!  :)

**Comment by causefx** [comment]
please install curl :)

**Comment by tanjer45** [comment]
Thank you! Mabe put the dependency in check.php? :)

**Comment by causefx** [comment]
Yes sir. Doing that now.
