### ISSUE TITLE
Unexpected error after entering NZBget credentials

### ISSUE THREAD

**Issue by dabigc** [causefx/Organizr#246]
Hey there, I am now getting the error below immediately after saving NZBget credentials and URL info in Organizr. My check.php page says everything is good to go as seen here: http://coco.d.pr/oE1n

Any thoughts?

Warning: syntax error, unexpected $end, expecting TC_DOLLAR_CURLY or TC_QUOTED_STRING or '"' in databaseLocation.ini.php on line 47 in /var/www/html/org/user.php on line 33

Fatal error: Uncaught PDOException: SQLSTATE[HY000] [14] unable to open database file in /var/www/html/org/user.php:237 Stack trace: #0 /var/www/html/org/user.php(237): PDO->__construct('sqlite:/users.d...') #1 /var/www/html/org/index.php(72): User->__construct('registration_ca...') #2 {main} thrown in /var/www/html/org/user.php on line 237

**Comment by causefx** [comment]
did you credentials have a single quote or double quote?

**Comment by dabigc** [comment]
Yes. My password is generated and has a double quote in it.

**Comment by causefx** [comment]
Ok. We will fix. For now edit database location.ini.php to take that value out
