### ISSUE TITLE
Cant authenticate with Plex as backend.

### ISSUE THREAD

**Issue by tanjer45** [causefx/Organizr#247]
This is my settings
<img width="408" alt="settings" src="https://cloud.githubusercontent.com/assets/25377421/24831126/31403448-1c94-11e7-870a-4e1f710f62a8.png">

I have tested with my public ip, Plex.tv and my local address as my backend IP. I ´have also tested HTTP and HTTPS.
Everytime i try to login it gives me "Error: the specified username/password combination is incorrect." I have tried with several Plex-usernames that i have "friended" on Plex. 

Any Thoughts ?

**Comment by causefx** [comment]
reload url/js/user.js

**Comment by causefx** [comment]
or just clear cache

**Comment by tanjer45** [comment]
Thanks, its working now. But it seems that i cant login with my own username, the same username i have selected as "Plex Username" in the Organizr under Advance Options. But it is not a problem. 

Great work! Do you have any feature request page ?

**Comment by causefx** [comment]
that will be fixed on next commit.  

set this up but havent really used it yet:

http://feathub.com/causefx/Organizr

**Comment by tanjer45** [comment]
Great! :)
