### ISSUE TITLE
Feature requests - toggle for showing nzbget for normal users

### ISSUE THREAD

**Issue by PotatoQuality** [causefx/Organizr#248]
Right now, only admin can see the status of nzbget.
I like to show it also to the normal users.
Is it possible to make a toggle to enable that?

**Comment by causefx** [comment]
yup, we can do that.

**Comment by SuperPotatoMen** [comment]
sweet <3

**Comment by Cerothen** [comment]
Implemented in https://github.com/causefx/Organizr/commit/7795f4a2341e976e7ab36b5f8f36999389819d54
