### ISSUE TITLE
Can't get new plex backend auth to work

### ISSUE THREAD

**Issue by trancefam** [causefx/Organizr#249]
I am having trouble getting plex authentication to work. Every time I try to log in with a username/password that is a plex username/pass combination (or even my prior organizr admin account) it says the combo is incorrect. These are my settings in databaseLocation.ini.php:

` authType = "both"
authBackend = "plex"
authBackendCreate = "true"
authBackendHost = "10.0.0.54"
authBackendPort = "32400"
authBackendDomain = ""
embyToken = ""
plexUsername = "myplexusername"
plexPassword = "myplexpassword" `

what exactly should go in authBackendDomain?
what does authType = both mean?

My goal is to be able to have users sign into organizr without having to set up an organizr account. Are these correct?

**Comment by causefx** [comment]
clear cache please.  or just load yourURL/js/user.js

**Comment by trancefam** [comment]
Okay, that made my original organizr admin login work again. However, now when I try to log in with a user/pass combo that is from Plex, it says invalid. When I open a separate tab and go directly to 10.0.0.54:32400 (plex) and log in with that same user/pass, it works. Ideas?

my username does have a period in it...would that matter?

**Comment by causefx** [comment]
hmmm, i havent tried with a period in the username.  I will have to try that out

**Comment by causefx** [comment]
![image](https://cloud.githubusercontent.com/assets/16184466/24835133/5ffa7424-1cad-11e7-8c6c-da83f5eb7675.png)
![image](https://cloud.githubusercontent.com/assets/16184466/24835134/65d862a2-1cad-11e7-891a-c38f20f080ae.png)

I created a plex acct with cause.fx

It logged me in fine.

does the password have something funky?

**Comment by trancefam** [comment]
nothing funky in the password. The period in my username is at the very end ex: **testplex.** 

Also, in advanced settings of organizr, that is the same account that I have entered for plex backend user/pass.

**Comment by causefx** [comment]
so this acct has all the users associated with it?

**Comment by causefx** [comment]
I will be pushing an update tomorrow morning.  we will test a little bit more then.

**Comment by trancefam** [comment]
okay, so I made another plex account and added it to my server. Tried logging in with that and it successfully logged in and created an account in organizr. So it looks like it just doesn't work with the primary account as of now.

**Comment by causefx** [comment]
ohhhhhh..... my bad. yes this has been fixed!  It will be out tomorrow :)

if you want to fix it now....

Find this:

```
// Pass credentials to Plex Backend
function plugin_auth_plex($username, $password) {
```

Add this next:

```
if ((strtolower(PLEXUSERNAME) == strtolower($username)) && $password == PLEXPASSWORD) {
    return true;
}
```

**Comment by trancefam** [comment]
working great now! Thanks a bunch!
