### ISSUE TITLE
Homepage calendar show times

### ISSUE THREAD

**Issue by ICDeadPpl** [causefx/Organizr#250]
The show times on the Organizr homepage shows the airing times truncated.
"a" and "p" instead of "am and "pm".
![bild](https://cloud.githubusercontent.com/assets/357885/24835184/9969ee40-1cfa-11e7-9960-20885a72870a.png)

I'd like to have the option to choose between 12/24 hour format for the calendar, preferably.
After all, the 24-hour time representation format is the standard used almost everywhere, except in US, UK, PH, CA, AU, NZ, IN, EG, SA, CO, PK, MY.

**Comment by causefx** [comment]
i do plan on adding that.  I'll keep this open as a reminder :)

**Comment by Cerothen** [comment]
Done

https://github.com/causefx/Organizr/commit/fcd464445c9b53afaa2a258b91932d15c363c61d
