### ISSUE TITLE
[Feature Request] - Option to disable "create new account"

### ISSUE THREAD

**Issue by trancefam** [causefx/Organizr#251]
Now that we have wonderful backend login support, would it be possible to have an option to remove the create new account button on the login page? As of now I have a password required to setup, but it looks like there isn't currently a way to set up fail2ban for this page so it couldn't be bruteforced.

Thanks!

**Comment by causefx** [comment]
Remove the password on registration password. That will remove the create acct button.

**Comment by trancefam** [comment]
Got it! Thank you
