### ISSUE TITLE
Unable to use PLEX Auth w/ auto-create function

### ISSUE THREAD

**Issue by seanvree** [causefx/Organizr#252]
I understand this is a new feature, so I figured I'd help debug. 

Running Organizr behind Windows IIS reverse PROXY:

Orgznizr ver:  1.3.1

Advanced Config:  

Auth: BOTH
Backend: PLEX / Create accnts as needed
Host:  Tried LAN PLEX IP and FQDN
Backend port: 32400  (Yes, I can acesss that via WAN)
Using admin UN and PW for AUTH to backend. 

PROBLEM:

SO, users can get to my page, and see all enabled GUEST tabs. 
However, when they click on LOGIN and enter PLEX creds -  will see this error:

And they will get an invalid UN and PW in Organzier front end. 

```
"Warning: Invalid argument supplied for foreach() in C:\inetpub\wwwroot\Organizr\functions.php on line 147"

```

 and NOTHING is wrote to The Organzir Logs.  

Any Ideas?

**Comment by leram84** [comment]
same... ill watch here

**Comment by seanvree** [comment]
I think this bug might actually be an big issue.

So, after I enabled it and tested it with a non-admin user and was getting the error above.

However, I hadn't logged all the way out with ADMIN yet.  So, I just did, and now I can't get in AT ALL. with local Admin or not.  

but, now, I can't get in with the admin or ANY user
I get error 

```
Invalid argument supplied for foreach() in C:\inetpub\wwwroot\Organizr\functions.php on line 147
```


So how can I set the settings in a config file somewhere in the root dir?

**Comment by seanvree** [comment]
How to recreate issue:


1...enabled PLEX auth, set to BOTH
2....removed a local user so that I could test auth
3....opened new ignito chome session on plexbox
4....refreshed browser
5...tried to log in with PLEX user
6...recevied error above
7....refreshed OTHER local browser session logged in as local ADMIN
8....got same eror on that session
9....closed broser
10...reopened and tried to AUTH with local ADMIN
11....got same error
12....locked out completely of UI
*first time touching files on local DIR:*
12....changed dbloc.ini: line 56, changed to internal, removed all lines blelow:
```
authType = "internal"
authBackend = "plex"
authBackendCreate = "false"
authBackendHost = "OMIT"
authBackendPort = "32400"
authBackendDomain = "MYDOMAIN"
plexUsername = "OMIT"
plexPassword = "OMNIT"
```
13...got back in under local ADMIN accnt
14....yay
15....tired to change settings via local admin accnt
16...error:

```
Fatal error: Uncaught PDOException: SQLSTATE[HY000]: General error: 14 unable to open database file in C:\inetpub\wwwroot\Organizr\settings.php:307 Stack trace: #0 C:\inetpub\wwwroot\Organizr\settings.php(307): PDO->exec('DELETE FROM tab...') #1 {main} thrown in C:\inetpub\wwwroot\Organizr\settings.php on line 307
```


Result:  I can now get back in with the local admin accnt, but I can't make any changes.

**Comment by tanjer45** [comment]
I had a similar problem yesterday, i needed to install curl and cleared my cache.

**Comment by seanvree** [comment]
@ImperialXT  - Cleared cache from the box running organizr and PMS?

FYI:  I have curl installed

**Comment by seanvree** [comment]
hey @causefx  - thx for fixing this.  follow up question:

thx for fixing that bug
question tho;
so once the user is created with PLEX auth, I'm seeing their email is 0Mg7b1t9I9z8o373I5xxxxR60560W77xt330@placeholder.eml
is that by design?
if so, can I change that to anything?
if so, does it AHVE To be their plex email?

**Comment by causefx** [comment]
yes they can change it, we will allow admin changing in future.  It doesn't have to be their plex email.
