### ISSUE TITLE
"Set cookie" Flags: Secure/HttpOnly

### ISSUE THREAD

**Issue by rix1337** [causefx/Organizr#264]
Securityheaders.io is very satisfied with my config, except for the following:
Set-Cookie	The 'httpOnly' flag is not set on this cookie. The 'secure' flag is not set on this cookie.

If viable, please enable an option to
a) Set-Cookie as secure (so its only available through https)
b) Set-Cookie as httpOnly (so client side fiddling is mitigated)

**Comment by Starbix** [comment]
Hi! What does your CSP config look like?

**Comment by rix1337** [comment]
I cheaped out on that one, because I run so many services.. Would not make sense to really limit them.

Its' just: 
```frame-ancestors https://MYURI; report-uri https://MYHOST.report-uri.io/r/default/csp/enforce```

To limit frame ancestors to my own site.

**Comment by Starbix** [comment]
Thanks I'll check that out

**Comment by Starbix** [comment]
@causefx any news on this?
