### ISSUE TITLE
Password not saved correctly

### ISSUE THREAD

**Issue by henkiespenkie** [causefx/Organizr#265]
Hello guys, I am using Organizr for some time now and I love it. I have one problem on my phone, and that is that the password that my iPhone stores is not the correct password.

The password stored in iCloud is way longer than my password. Every time I open Organizr I need to log in again and manually fill in the password, otherwise I can't login. I tried to change the stored password, but it just gets overwritten with a new (wrong) password next time I login.

Can you please solve this? Thanks in advance.

**Comment by causefx** [comment]
it is because the password gets hashed, i will see about bypassing.

**Comment by SgtBatten** [comment]
Google chrome saves my password fine and I just hit login

**Comment by Cerothen** [comment]
@henkiespenkie is your saved password exactly 16 characters long?

It's probably related to this

https://github.com/causefx/Organizr/blob/master/js/user.js#L117

**Comment by trancefam** [comment]
@cerothen I am also having this problem on iPhone 7 safari. I just checked and every time I log in, the saved password is overwritten with a 16 character hash

**Comment by Miicker** [comment]
I have the same problem, posted it a while ago:
https://github.com/causefx/Organizr/issues/178

**Comment by Cerothen** [comment]
Maybe this will work?

https://github.com/causefx/Organizr/commit/f85332b1bc530eb3b2b277c179a4a06abde6b8eb

**Comment by Cerothen** [comment]
I am putting this one as resolved since I haven't heard anything back

**Comment by Miicker** [comment]
Why? I don;t want a workaround, I just want a permanent fix for this.

**Comment by Cerothen** [comment]
That isn't a workaround it will be in the next release.. I asked you if that change would work, didn't get a response for 12 days. Without feedback I assumed it was fine.

Try the latest version beta https://github.com/causefx/Organizr/tree/cero-dev let me know if its still happening if it is then we can reopen this item and try something else.

**Comment by Miicker** [comment]
Alright I tried the suggested change and it works, thanks.
