### ISSUE TITLE
don't show homepage.php to not logged in users

### ISSUE THREAD

**Issue by PotatoQuality** [causefx/Organizr#266]
users don't need to login at the moment to see the homepage.php

for security  it will be nice to not showing this kind of information to the whole internet

**Comment by elmerfdz** [comment]
For now you can lockdown the homepage using the following method

Assuming you're using a Nginx webserver, setup server authentication first: [server auth wiki](https://github.com/causefx/Organizr/wiki/Authentication-%7C-Server-Based)

and add the following location block, to lock down homepage.php

```
location ^~/homepage.php {
					                        
	                    #Organizr auth check
                            auth_request /auth-user;
                            location ~ \.php$ {
		            include snippets/fastcgi-php.conf;
			    fastcgi_pass unix:/run/php/php7.0-fpm.sock;
                            }
                    }
```

**Comment by Cerothen** [comment]
Implemented in Development Build

https://github.com/causefx/Organizr/commit/7795f4a2341e976e7ab36b5f8f36999389819d54

**Comment by dejected1** [comment]
i tried adding this to my ngnix config and now the nginx services won't start. Specifically this bit causes it to stop working: 
                            location ~ \.php$ {
		            include snippets/fastcgi-php.conf;
			    fastcgi_pass unix:/run/php/php7.0-fpm.sock;
                            }

Am i missing something? homepage works fine without this part, it's just exposed without auth.

**Comment by Cerothen** [comment]
@dejected1 Can you confirm that you are using php 7.0 and not 5.X?

Homepage authorization will be out in the next release. It's been implemented at both the global and service level.

**Comment by dejected1** [comment]
no worries then. Im pretty sure i installed 5.x anyway so that why its not working.

**Comment by camjac251** [comment]
I tried out
`    location /auth-user {
                internal;
                rewrite ^ /auth.php?user&ban=someone,thisperson;
}
location ^~/homepage.php {
    auth_request /auth-user;
    location ~ \.php$ {
    include /etc/nginx/fastcgi_params;
    fastcgi_pass unix:/run/php/php7.1-fpm.sock;
   	}
}`

but after rebooting nginx, the homepage.php url will return blank with nothing in the nginx error log, but shows 401 Authorization Required when logged out. I'm accessing it as an admin
