### ISSUE TITLE
Apache equivalent of webserver auth?

### ISSUE THREAD

**Issue by mmolitor87** [causefx/Organizr#267]
I currently use http auth either per application or set in the reverse proxy. This allows me to login to muximux once with http auth and it automatically trickles down to each other application, allowing seamless access. If you try to access each individual application they are still blocked. This is the last hurdle keeping me from moving completely to organizr.

I like the idea of accessing the applications only through organizr and them looking like they don't exist at when accessed via https://domain.com/sonarr as an example.

I looked at the nginx webserver auth and can't find a way to replicate it for apache. I've continued to use apache for the last 17 years because i'm familiar with the commands, but I think I might have finally found the thing that makes me switch.

**Comment by causefx** [comment]
dont think there is one, the other option is to use cookie Password but that is for anyone logged into Org, with Nginx you can do it by group and also exclude users.

**Comment by Cerothen** [comment]
Perhaps this will work for you @mmolitor87 

https://github.com/kitech/mod_authnz_external
