### ISSUE TITLE
Blank White Pages

### ISSUE THREAD

**Issue by Aireezz** [causefx/Organizr#269]
Some Pages (Sonarr, Radarr, NZBGET, Ombi) show up fine, but others (Plexpy, headphones, phpmyadmin, and multicraft) show up as just white pages. Anyway to fix this?

**Comment by causefx** [comment]
anything show in browser console?

**Comment by Cerothen** [comment]
Try this
https://chrome.google.com/webstore/detail/ignore-x-frame-headers/gleekbfjekiniecknbkamfmkohkpodhe

**Comment by PotatoQuality** [comment]
did you use http for plexpy headphones? If you browser https and content is http it will be blocked by the browser

**Comment by Aireezz** [comment]
@PotatoQuality Yes, my browser uses HTTPS, but every application uses http. I will try to change plexpy over and see if it works.

**Comment by Aireezz** [comment]
I don't see anything in the log's @causefx and @PotatoQuality is it possible to use plexpy as http if you use a reverse proxy? I don't have issues going to plexpy via https in a single tab, only when I try to load through Organizr.

**Comment by Cerothen** [comment]
In V2.0 we will look at reporting to users why a page didn't load so that it is more obvious to the end user if it is a browser restriction eg Http when org was loaded as HTTPS
