### ISSUE TITLE
Why you trying to access this without logging in?!?!

### ISSUE THREAD

**Issue by andyrav** [causefx/Organizr#27]
Hi
on last pull now getting Why you trying to access this without logging in?!?! when i try and go into settings.

**Comment by causefx** [comment]
Are you logged in, have you tried logging out after the upgrade?

**Comment by andyrav** [comment]
yes it logs me in ok, and tried loggin out and back in but alway get the same msg

**Comment by causefx** [comment]
when signing in, is the Remember Me checked or unchecked?  Any errors in the console log?

**Comment by causefx** [comment]
also, try clearing cache and reloading.

**Comment by causefx** [comment]
@andyrav anything on this bud?
