### ISSUE TITLE
[FR] Add option to stop "auto-scrolling" in HOMEPAGE

### ISSUE THREAD

**Issue by CBers** [causefx/Organizr#270]
Can an option be added so that auto-scrolling of new movies or TV Shows can be disabled please.

There are already the left/right arrows, so that would suffice for me.

Thanks.

**Comment by SgtBatten** [comment]
Alternatively I would love just the posters all In a row without the descriptions

**Comment by elmerfdz** [comment]
Like how it's displayed on PlexPy? 

![image](https://cloud.githubusercontent.com/assets/22656503/24954044/8e6b8a80-1f75-11e7-9df6-d6129406dcae.png)

**Comment by schmittyd** [comment]
Configurable would be good... that way I think most people will be happy

**Comment by causefx** [comment]
we have changed the layout now so this is a non issue now.
