### ISSUE TITLE
Help with HTTPS Proxy

### ISSUE THREAD

**Issue by derekbcaldwell** [causefx/Organizr#273]
So I have PlexPy setup on my server running through a proxy for an ssl certificate. In a separate tab I can visit https://mydomain/plexpy and it works great.

When I add it to Organizr by just using /plexpy, after I refresh the settings and go to that tab, I see nothing but a white page.

Help?

Thanks!

**Comment by elmerfdz** [comment]
Try enabling HTTPS on PlexPy

**Comment by derekbcaldwell** [comment]
It is enabled and is pointing to my cert and key on /etc/ssl. Accessing it works great in browser, just not in Organizr.

**Comment by derekbcaldwell** [comment]
Fixed by pointing Organizr to /plexpy/home in case anyone comes across this thread and needs help.
