### ISSUE TITLE
New Install Errors

### ISSUE THREAD

**Issue by kushfest** [causefx/Organizr#274]
Hi there...Just installed this for the first time. I'm able to load the screen where I'm asked to select my database file location and language. I make my selections and then receive this error:

`Fatal error: Uncaught PDOException: could not find driver in /var/www/nerdserver/user.php:160 Stack trace: #0 /var/www/nerdserver/user.php(160): PDO->__construct('sqlite:/var/www...') #1 /var/www/nerdserver/index.php(67): User->__construct('registration_ca...') #2 {main} thrown in /var/www/nerdserver/user.php on line 160`

I'm stumped. Any suggestions? Thanks.

**Comment by elmerfdz** [comment]
Open check.php in your browser, should show you whether you have all the required extensions and permissions or not.

List of requirements
https://github.com/causefx/Organizr/wiki

Make everything is green on check.php

![image](https://cloud.githubusercontent.com/assets/22656503/25070950/e964298a-22a2-11e7-9395-75fa7fac9cf4.png)

**Comment by kushfest** [comment]
Thank you for the quick response! That made all the difference. I thought I had already installed PDO_SQLITE, but it looks like it needed a reinstall. I think I'm good now!
