### ISSUE TITLE
Minor Bug: Minimum Password length

### ISSUE THREAD

**Issue by camjac251** [causefx/Organizr#276]
I had used the password `6+;(hwDAU]s$1kjyAFrdcegiebtas5xp` for my account and as soon as I hit submit, it started loading but had shown on the first password field that the minimum length was 4 characters.
It's happened every time I've reinstalled the script. The password works fine and I'm logged in and have no issues after, but it can be confusing to see from a first time install.

**Comment by camjac251** [comment]
Happens with logging in as well with pasted passwords

**Comment by causefx** [comment]
i will take a look at this

**Comment by leveraged7** [comment]
#332 , #298 

If I am wrong I apologize, but my issue #332, I see the same errors as #276 and #298 as I have been messing with it.

**Comment by causefx** [comment]
fixed
