### ISSUE TITLE
Plex Authentication Backend doesn't exist

### ISSUE THREAD

**Issue by camjac251** [causefx/Organizr#277]
I am unable to see the Plex option on the advanced settings for authentication. Has it been removed? I'm on the master branch.

![image](https://cloud.githubusercontent.com/assets/6313132/25077242/a1accf0c-22ed-11e7-896c-a5881b7621de.png)

**Comment by causefx** [comment]
please install php curl.

**Comment by camjac251** [comment]
Thanks, will try it right now. I thought only curl needed to be installed, not the php extension.
I couldn't see it in the check.php checker. Everything looked ok.

**Comment by causefx** [comment]
yea, i need to update that.  sorry.

**Comment by camjac251** [comment]
If anyone else has this problem in the future and doesn't know how to fix, I had PHP7.1 on Ubuntu and ran `apt-get install php7.1-curl` and afterward, reloaded the page and plex was showing up as an option.

**Comment by causefx** [comment]
we are adding that info in the next release as well, it will show in a disabled state also saying you are missing the dependency.
