### ISSUE TITLE
Hiding/Showing Tabs - Additional User Class

### ISSUE THREAD

**Issue by camjac251** [causefx/Organizr#278]
I'd like to give someone access to a few tabs that the admin class has access to but still be able to have the users class not able to access these tabs.

Is it possible to maybe whitelist tabs based on users? Or being able to assign them a custom group then have that group show up for tab options? 

If another user class would be created, could it also support the authentication function as well for apps and admin could become say superadmin. or the newer created class could be operator.

**Comment by StevenChorkley** [comment]
This has already been requested: #171

**Comment by camjac251** [comment]
Sorry about that, I tried looking up keywords like whitelist or user class and couldn't find any results.
