### ISSUE TITLE
Webpage hangs while loading with the dot in the centre.

### ISSUE THREAD

**Issue by SgtBatten** [causefx/Organizr#28]
I have primarily been using my phone to access my organizr page remotely.

Possibly only since the last patch I am unable to access it on any other device using my DDNS url. 
It definitely was working previously.

Now when I load the url on any other device it brings up the background colour and the pulsing dot in the centre as normal. The website finishes loading (as in the loading indicator stops spinning/ the loading bar fills up and disappears) but the little dot in the centre just keeps on pulsing and nothing further happens.

I can log in and out on my phone no issues and it all loads fine.

Any thoughts?

**Comment by causefx** [comment]
that really odd, I'm using the same version, well with more edits as I am still working on it.  If possible can you email me the link to you site so i can try on my end too?  causefx@me.com

**Comment by SgtBatten** [comment]
Just remoted into the localhost.

Localhost/Organizr/ works
192.168.1.X/Organizr hangs
127.0.0.1/Organizr/ hangs

**Comment by causefx** [comment]
Ok, I ran your site and checked the console log and it says you are missing these files:
/bower_components/smoke/dist/css/smoke.min.css
/js/common.js

**Comment by SgtBatten** [comment]
That's so strange. Git hub is reporting the same files missing. I have discarded changes and resynced and it is now all working again.
I never deleted those myself. 

Anyway, next time I'll check git GUI first haha. Thanks man

**Comment by causefx** [comment]
Yeah, that's freaking strange.  Anywho, good stuff.
