### ISSUE TITLE
Welcome Banner Sometimes is unremoveable

### ISSUE THREAD

**Issue by JoeStratton** [causefx/Organizr#285]
Hi, Maybe 1 in 10 times, the Welcome, User banner is unremovable. When you click the "X" to close it it just opens the settings page. A refresh of Organizr always seems to solve the issue.

Not a big deal, just an FYI.

**Comment by elmerfdz** [comment]
@causefx I've had this happen to me as well but could never replicate this consistently, it's quite random.

**Comment by causefx** [comment]
It's really not random, it only happens when the notification pops up and you switch views to another screen.

**Comment by elmerfdz** [comment]
My bad, you're right :/

**Comment by causefx** [comment]
fixed
