### ISSUE TITLE
Best way to put this behind nginx reverse proxy?

### ISSUE THREAD

**Issue by pageb018** [causefx/Organizr#286]
So I am running the Let's Encrypt docker on unRAID. When I put in the proxy pass config for Organizr, I can load the main page, but none of the tabs load. I tried using both the internal ips and the reverse proxied full hosts, nada. Not exactly sure where I am going wrong. 

Awesome work, can't wait to get this sorted and use it externally.

**Comment by Cerothen** [comment]
Depending on how your reverse proxy is configured and the services that you are using you are likely running into cross origin request issues. eg.

if you have organizer on https://domain.com and you have owncloud at https://owncloud.domain.com you wont actually be able to load the tab as owncloud sets the X-Frame-Options header. You would need to remove this header or use an extension like such as https://chrome.google.com/webstore/detail/iframe-allow/gifgpciglhhpmeefjdmlpboipkibhbjg?hl=en.

You can see if the iframe content is being blocked by hitting F12 on most browsers and looking at the console

**Comment by pageb018** [comment]
Gotcha. That makes sense. 

Thanks

**Comment by JigSawFr** [comment]
You can also override headers sent by owncloud via your nguni proxy, search in issues somewhere in this repo ;) I've posted my nguni config for subdomains in an issue.
