### ISSUE TITLE
Error loading Organizr in Firefox

### ISSUE THREAD

**Issue by schmittyd** [causefx/Organizr#287]
![image](https://cloud.githubusercontent.com/assets/12869594/25214063/733f02be-25d8-11e7-9937-0e904435dd42.png)

**Comment by PotatoQuality** [comment]
you are trying to connect to port 8097:80 ?!?!?!

**Comment by schmittyd** [comment]
Hmm... I'll have to check that

**Comment by Cerothen** [comment]
make sure you use the fill scheme

http://localhost:8097

**Comment by schmittyd** [comment]
Fill scheme?

**Comment by causefx** [comment]
URL scheme.

**Comment by schmittyd** [comment]
Ah ok

**Comment by schmittyd** [comment]
Is that in nginx.conf or org?

**Comment by schmittyd** [comment]
I updated nginx and php, could that be the reason?

**Comment by schmittyd** [comment]
I can not figure it out. There is nothing in nginx.conf or Organizr that specifies localhost:8096:80.

**Comment by Cerothen** [comment]
it might be a bug, I will give it a look

**Comment by Cerothen** [comment]
Fixed https://github.com/causefx/Organizr/commit/2d60c186461c9729f914a6a95d3c8e3c806235b7
