### ISSUE TITLE
[FR] Remove WATCHED items from the EMBY information on HOMEPAGE

### ISSUE THREAD

**Issue by CBers** [causefx/Organizr#289]
Since having Emby added to the HOMEPAGE, I get all the latest TV and MOVIES.

I watch quite a lot of these once added, so can WATCHED items be excluded from the pull from Emby please.

Thanks.

**Comment by Cerothen** [comment]
https://github.com/causefx/Organizr/commit/3b2d766f4033696295c7c08643bc218237daa46d

This goes based on the user that is logged in. If the username matches one in emby then it will use that user's watched status. If its a user that doesn't exist in emby it will just show everything

**Comment by CBers** [comment]
That won't work for me, as my Emby account is not an Admin on Organizr. 

Perhaps we should have Emby account in the settings to use when pulling the Emby information.

**Comment by CBers** [comment]
Also, how/where do the Emby users get pulled in?

**Comment by Cerothen** [comment]
Emby (all backend accounts) are generated at the time of login by that account (assuming you have create accounts on).

Is there a reason you don't have a matching username between Emby and Organizr? (just out of interest, you are naturally able to call your accounts whatever suits you.)

**Comment by CBers** [comment]
When I installed Organizr, Emby wasn't integrated, so called the Admin account CBers. 

My accounts in Emby are different.
