### ISSUE TITLE
[FR] Custom HTML area of Homepage

### ISSUE THREAD

**Issue by kernelkaribou** [causefx/Organizr#291]
I have the homepage enabled and only using Plex plugin at this time. Would be nice to allow for customization of the homepage, if just a set area to allow for custom HTML. I would like to embed some grafana dashboard panels for instance.

Thanks, big fan so far!

**Comment by causefx** [comment]
good idea

**Comment by Cerothen** [comment]
https://github.com/causefx/Organizr/commit/cd6bc4f77645a74ce732393c6982d8031fe25db7
