### ISSUE TITLE
Bug: Edit Homepage doesn't save

### ISSUE THREAD

**Issue by camjac251** [causefx/Organizr#292]
When I try to hit save for the edit homepage options, the page doesn't reload or tell me that the settings have saved, and after refreshing, nothing changes

What used to happen was Firefox would show something like "Please match the requested format" or something similar, although it doesn't happen now. This is on the cero-dev branch

**Comment by Cerothen** [comment]
https://github.com/causefx/Organizr/commit/c46eb4a7f0b28f8048b5005eab31a0b22e7c81b1 https://github.com/causefx/Organizr/commit/b5d75aeb7fcbde8af02078dbb007bc9738d5b56a

The submit action can't focus a form field hidden in a tab. What I have done is added direct feedback to the validation section showing if some data does not comply. It will validate on the fly as it is being typed in, in your case if you are an emby user there was a bug where it was saving the emby token in the settings as a plex token which is probably the root of your issues. In any case just page through the settings and look for big red fields like depicted below when trying the absolute latest.

![image](https://cloud.githubusercontent.com/assets/9008757/25338325/dcbc0c86-28cc-11e7-97ed-577c24ded4ae.png)
