### ISSUE TITLE
Can not select Emby All in advanced settings

### ISSUE THREAD

**Issue by schmittyd** [causefx/Organizr#293]
When in the advanced settings page, I am only given the option of ftp or Emby Local in Select backend to use.

![image](https://cloud.githubusercontent.com/assets/12869594/25319753/71540094-28e4-11e7-9024-2b6e86c9d0fa.png)

**Comment by causefx** [comment]
You Need to install php curl

**Comment by schmittyd** [comment]
Oh ok. I'll have jump on Google then.

**Comment by schmittyd** [comment]
Is this the correct one?
https://github.com/php-curl-class/php-curl-class

**Comment by schmittyd** [comment]
Never mind, sorted it out. I realised it was an extension in php.ini
