### ISSUE TITLE
Buttons not appearing at bottom of Advanced Settings page

### ISSUE THREAD

**Issue by schmittyd** [causefx/Organizr#294]
The Loading Screen, Enable Mail and Enable Slim Bar are not appearing at the bottom of the Advanced Settings page.

![image](https://cloud.githubusercontent.com/assets/12869594/25319889/4e087a10-28e5-11e7-9812-5be7adc384f8.png)

**Comment by Cerothen** [comment]
The settings pages for Colour, Homepage and Advanced have been completely redesigned. I am going to close this for now, if when the new version comes out you still have issues then please reopen or make a new issue.

If you feel like trying out the latest you can always download
https://github.com/causefx/Organizr/tree/cero-dev

This is pretty smooth at this point though may have bugs still.

**Comment by schmittyd** [comment]
How do I download it? can't find a link

**Comment by Cerothen** [comment]
![image](https://cloud.githubusercontent.com/assets/9008757/25344025/d2d5ef86-28de-11e7-9095-58ade4da1a3d.png)

**Comment by schmittyd** [comment]
Thanks, I'll give it a go.
