### ISSUE TITLE
Plex Auth fails if there is a "$" character in the plex account password

### ISSUE THREAD

**Issue by AevumDecessus** [causefx/Organizr#295]
If there is a "$" character in your plex password, PHP reads it as an undefined variable in the config.php array when it stores the "plexPassword" variable data.

Shows up as "Undefined variable: <PART OF PASSWORD AFTER $ CHARACTER> in Organizer_DIR/config/config.php on line 42"

**Comment by Cerothen** [comment]
Thanks for pointing that out, should be fixed with this one.

https://github.com/causefx/Organizr/commit/4b714c36fc574044fbb2524e8c0e91da03261001

**Comment by Cerothen** [comment]
https://github.com/causefx/Organizr/commit/616d5ca88ddc43bb395e9404e8cc73406a78b889

Just in case the above didn't work. Just changed it around.

Tested with this char set and it saves and loads every character

```1234567890qwertyuiop[]\asdfghjkl;'zxcvbnm,./ `~!@#$%^&*()_+QWERTYUIOP{}|ASDFGHJKL:"ZXCVBNM<>?~```
