### ISSUE TITLE
Error during install

### ISSUE THREAD

**Issue by Aesculapius** [causefx/Organizr#296]
After pulling from github, I get a nice bumping logo and the question for a database location and timezone. If I provide that (and no matter what I provide), clicking on next immediately results in a server error:
Fatal error: Uncaught PDOException: could not find driver in /var/www/html/Organizr/user.php:160 Stack trace: #0 /var/www/html/Organizr/user.php(160): PDO->__construct('sqlite:/var/www...') #1 /var/www/html/Organizr/index.php(67): User->__construct('registration_ca...') #2 {main} thrown in /var/www/html/Organizr/user.php on line 160

So I can't finish installation...

**Comment by elmerfdz** [comment]
Looks like you don't have all the requirements, open check.php and install the missing requirements, see issue https://github.com/causefx/Organizr/issues/274

**Comment by Aesculapius** [comment]
Thanks for that tip - I was missing the PDQ-SQLite module. Appears to be going well now...
