### ISSUE TITLE
Losslessly compress images to speed up initial site load.

### ISSUE THREAD

**Issue by Dazog** [causefx/Organizr#297]
Losslessly compressing both these files then resizing them to the sizes required would reduce loading time of login page.

Losslessly compressing images/sowwy.png could save 14.6KiB (17% reduction).
Losslessly compressing images/organizr_logo_d.png could save 5.4KiB (20% reduction).

/images/organizr_logo_d.png is resized in HTML or CSS from 600x600 to 192x192. 
Serving a scaled image could save 24.7KiB (89% reduction).

/images/sowwy.png is resized in HTML or CSS from 520x520 to 200x200. 
Serving a scaled image could save 77.1KiB (85% reduction).

Very minor.

**Comment by camjac251** [comment]
I had already compressed most of the images losslessly, optimizing them. They are saved in the cero-dev and develop branches, and don't have their scales changed either.
Also too, if you scale down the logo, then you miss out on if someone scales up their webpage or views on mobile with a high dpi if its low res.

**Comment by Dazog** [comment]
Well the cat is really not needed at all. and the organizr logo should be on screen log enough to look low res if this site loads faster.

But I am nitpicking.

**Comment by causefx** [comment]
this was done a few versions back.
