### ISSUE TITLE
Case-Sensitive Admin Registration Required to Pass Validation

### ISSUE THREAD

**Issue by Robbbbbbbbb** [causefx/Organizr#298]
Not sure if this is known or not, but on the initial admin registration page after a fresh install, the username and email address needs to be entered in lower-case, otherwise they will fail validation. If this is by design, that's fine, but there's no clear indication of this that I could find.

Thanks all!

**Comment by Cerothen** [comment]
This should be fixed in the latest.

https://github.com/causefx/Organizr/blob/cero-dev/user.php#L570
