### ISSUE TITLE
index.php will not load

### ISSUE THREAD

**Issue by BillyMichael** [causefx/Organizr#300]
I have installed Organizr with nginx on centos7. When accessing the index page i can pick a database location. Once this is done i get the following errors:

```
Warning: fopen(config/config.php): failed to open stream: Permission denied in /usr/share/nginx/html/functions.php on line 729

Warning: fwrite() expects parameter 1 to be resource, boolean given in /usr/share/nginx/html/functions.php on line 730

Warning: fclose() expects parameter 1 to be resource, boolean given in /usr/share/nginx/html/functions.php on line 731

Notice: Undefined variable: configReady in /usr/share/nginx/html/index.php on line 645

Notice: Undefined variable: configReady in /usr/share/nginx/html/index.php on line 710
Organizr
Notice: Undefined variable: configReady in /usr/share/nginx/html/index.php on line 738

Notice: Undefined variable: configReady in /usr/share/nginx/html/index.php on line 744

Notice: Undefined variable: showPic in /usr/share/nginx/html/index.php on line 750

Notice: Undefined variable: configReady in /usr/share/nginx/html/index.php on line 795

Notice: Undefined variable: configReady in /usr/share/nginx/html/index.php on line 864

Notice: Undefined variable: configReady in /usr/share/nginx/html/index.php on line 930
```

I also get the following despite changing the user and permissions

![image](https://cloud.githubusercontent.com/assets/13979763/25509421/d6e63e58-2bb0-11e7-89b2-29bb0c2f2efb.png)

**Comment by causefx** [comment]
what command are you using to change permissions?

**Comment by BillyMichael** [comment]
I have tried `chown -R nginx:nginx /usr/share/nginx` and `chmod -R 777 /usr/share/nginx`

**Comment by causefx** [comment]
Can u do an ls -l

**Comment by BillyMichael** [comment]
![image](https://cloud.githubusercontent.com/assets/13979763/25516783/4833e9f6-2be4-11e7-8954-e5eb64e04a46.png)

![image](https://cloud.githubusercontent.com/assets/13979763/25516798/578a89b4-2be4-11e7-8d3e-5bc139c9c9a3.png)

![image](https://cloud.githubusercontent.com/assets/13979763/25516824/80f8231a-2be4-11e7-9108-6c4b9c8e4644.png)

**Comment by Cerothen** [comment]
If you try a Apache with PHP (just temporally) does that seem to resolve the issue?

**Comment by BillyMichael** [comment]
I ended up running Organizr in Docker which has worked perfectly. I will close this now.
