### ISSUE TITLE
plex webtools reverse proxy

### ISSUE THREAD

**Issue by dejected1** [causefx/Organizr#301]
Weird one. I setup a reverse proxy using NGINX for plex web tools. The local address is localhost:33400/login 
I can get this to resolve and the page loads all the html text except the actual login portion. When going directly to site without proxy pops up fine. Behind proxy everything pops up except the login and password box. 
Here is my code:
		#plex webtools
		location /webtools/ {
		auth_request /auth-user;
		proxy_pass  http://192.168.2.197:33400/;
		    proxy_set_header Host $host;
		    proxy_set_header X-Real-IP $remote_addr;
		    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		    add_header X-Frame-Options SAMEORIGIN;
    	}

**Comment by dejected1** [comment]
after a lot of google it looks like ngnix isn't loading the javascript

**Comment by Cerothen** [comment]
Nginx doesn't load JavaScript at all it's a web server, but it's more likely that you need to set a base url in Plex tools, I don't have access to Plex or it's associated programs though

**Comment by ukdtom** [comment]
Not yet released V3 of WebTools will have support for BaseURL

Beta:
https://github.com/ukdtom/WebTools.bundle/wiki/Beta-V3

Settings:
https://github.com/ukdtom/WebTools.bundle/wiki/Configure

**Comment by causefx** [comment]
sweet!  is the beta open @ukdtom

**Comment by ukdtom** [comment]
By invitation, and mentioned in the beta FAQ I linked towards

**Comment by ukdtom** [comment]
And FUI @causefx 

Next version of WebTools supports multiple languages in it's GUI.
I teamed up with https://poeditor.com
They allow a free translation site, if open source!

**Comment by causefx** [comment]
Free for 1000 strings?! Nice. Thank you.

**Comment by ukdtom** [comment]
Huh....AFAIK, there's no limit, if approved as OpenSource!
Meaning one of the following licences:
https://opensource.org/licenses/alphabetical

**Comment by ukdtom** [comment]
> If your software has an OSI approved license,
we'll give you unlimited strings to localize it.

**Comment by causefx** [comment]
sweet, i will contact them,  sorry i read the website on my phone.
