### ISSUE TITLE
Booksonic loginscreen overwrites Organizr

### ISSUE THREAD

**Issue by rune3132** [causefx/Organizr#303]
When having to log into Booksonic, it reloads the entire page and opens the default page (x.x.x.x:4040/login.view?) instead.

**Comment by Cerothen** [comment]
The way some services handle their redirects this happens some times. There is a toggle on the tab settings for services that don't properly support iframes.

If that application has basic authentication you could use that and the scheme https://user:pass@x.x.x.x:4040/login.view?
