### ISSUE TITLE
404 error when using reverse proxy

### ISSUE THREAD

**Issue by Rockapella** [causefx/Organizr#304]
Bare with me here as I just started learning all this stuff about 2 days ago. So I have a domain setup and I also have an ssl certificate setup on my domain, which I've implemented into my server.conf file. I am able to access organizr by navigating to domain.com/organizr and it is secure so I know that my certificates are implemented correctly. My problem occurs when I add Sonarr (or any other) service as a page. I'm using a reverse proxy the looks like this in my server.conf file:

```
location /sonarr {
    #include C:/WPNXM/bin/nginx/conf/cookie_direct_blocking.conf;
        proxy_pass http://:127.0.0.1:8989;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }    
```

I've gone into Sonarr/Settings/General and put in the URL base "/sonarr" and restarted the sonarr service. When I create my tab in organizr, I'm using "http://domain.com/sonarr" as my tab url. When I apply the changes and click on the tab, it works on the computer I'm using as the server. On any other computer connected to the same network, I can load organizr fine, but when I select the sonarr tab it shows a "404 not found" page. The weird part here is I can access sonarr by typing in https://domain.com/sonarr and it works perfectly fine on other computers connected to the same network. Its only when im trying to access it through organizr that I get the 404. There must be some simple explanation for this. Thank you for your help in advance.

**Comment by elmerfdz** [comment]
Have you tried using org tab url as "/sonarr" ?

**Comment by Rockapella** [comment]
Ive decided to drop WPN-XM and just install Nginx. I will open another ticket with some Issues im having with that.
