### ISSUE TITLE
Bug:  Warning: fsockopen(): unable to connect to 192.168.1.25:8096:80

### ISSUE THREAD

**Issue by untotren** [causefx/Organizr#305]
My configuration:
host: http://192.168.1.25
port: 8096
API Key: Is present

Cannot login using local emby, getting the following error:
Warning: fsockopen(): unable to connect to 192.168.1.25:8096:80 (Failed to parse address "192.168.1.25:8096:80") in C:\Servers\Nginx\html\Organizr\functions.php on line 345

**Comment by Cerothen** [comment]
This is already fixed in the development build, also it is a duplicate.

https://github.com/causefx/Organizr/commit/2d60c186461c9729f914a6a95d3c8e3c806235b7
