### ISSUE TITLE
Undefined index in homepage with emby

### ISSUE THREAD

**Issue by Kiina** [causefx/Organizr#307]
So I'm using emby and the homepage.php. The Problem is when you have shows/movies that aren't on tvdb you can't really scrape them, so they have no real metadata it breaks the homepage. Maybe it should just silently log it and only display what it can so the page doesn't look like this:

![image](https://cloud.githubusercontent.com/assets/2419591/25567427/4d6ece08-2ded-11e7-8311-057362938f92.png)

if you have files in "Latest Episodes" that only have a filename and image.

```
Notice: Undefined index: SeriesName in /config/www/Dashboard/functions.php on line 403
Notice: Undefined index: ParentIndexNumber in /config/www/Dashboard/functions.php on line 403
Notice: Undefined index: IndexNumber in /config/www/Dashboard/functions.php on line 403
Notice: Undefined index: SeriesId in /config/www/Dashboard/functions.php on line 404
```

**Comment by causefx** [comment]
@Cerothen Emby calling you lol.

**Comment by Cerothen** [comment]
I'll take a look at dealing with missing data more elegantly. I also want to give an alternative to the carousel display since some people asked about that

**Comment by Cerothen** [comment]
https://github.com/causefx/Organizr/commit/2ff5b4d66e92bf096e9586431408fd3b7673ff92

**Comment by Kiina** [comment]
Cherry-picked your commit, works fine. Thank you
