### ISSUE TITLE
Plex Auth

### ISSUE THREAD

**Issue by chrisvdgeld** [causefx/Organizr#308]
Just wondering, I've seen so many things about Plex Auth in the issue section. Where can I turn on Plex Auth?

**Comment by causefx** [comment]
Advanced Settings:
![image](https://cloud.githubusercontent.com/assets/16184466/25568401/f671f0ca-2db6-11e7-9a68-6b0750e36ba6.png)

**Comment by Kiina** [comment]
You need php-curl

**Comment by chrisvdgeld** [comment]
Version 1.323
I can't see that option mmh :o

http://i.imgur.com/RW0gMAy.jpg

**Comment by Kiina** [comment]
![image](https://cloud.githubusercontent.com/assets/2419591/25575693/db9e3260-2e59-11e7-860a-c0f0247484f0.png)

Select Organizr plus other and you will get the Backend options below. If they dont appear you need php-curl

**Comment by chrisvdgeld** [comment]
Thanks! ;)
