### ISSUE TITLE
homepage sonarr/radarr

### ISSUE THREAD

**Issue by chrisvdgeld** [causefx/Organizr#310]
I can't seem to get calendar etc. to work. I filled in sonarr and radarr:

https://domain.com/sonarr
b5379b5245f3s48baa9ekwnla9sk2j9a (fictional api)

https://domain.com/radarr
b5379b5245f3s48baa9ekwnla9sk2j9a (fictional api)

Yet all I get to see is this:

https://puu.sh/vD2wX/9b91e82ae4.jpg

Now I've found this link in other problems, so I thought I'd test it out, so it means the host and the api do actually work:
https://domain.com/sonarr/api/calendar?apikey=b5379b5245f3s48baa9ekwnla9sk2j9a

```
 {
    "seriesId": 94,
    "episodeFileId": 0,
    "seasonNumber": 4,
    "episodeNumber": 16,
    "title": "Moo Moo",
    "airDate": "201........... etc.
```

**Comment by chrisvdgeld** [comment]
Mh, reboot fixed it for some reason

**Comment by untotren** [comment]
I had the same thing with Radarr.
