### ISSUE TITLE
Forwarding port 80 requests using reverse proxy

### ISSUE THREAD

**Issue by Rockapella** [causefx/Organizr#311]
Hello,

I am not very technologically savvy in the networking realm and I apologize if I fall behind on certain terminology ahead of time.

I have a dynamic dns domain through noip.com, which I will reference as domain.example. I also have a public IP address which I will reference as 68.***.***.***.

The dynamic dns domain (domain.example) is assigned to my public IP address (68.***.***.***). I have an AirPort Extreme that I can open ports on and I have it configured as such: http://imgur.com/a/Ig0Ay

Basically what I am trying to do is when someone accesses domain.example, I want nginx to forward them to domain.example:3001. Currently I am able to open port 80 on my router and I can navigate to domain.example with my LAN, but as soon as I travel outside of my house, it doesn't work... I know that my ISP blocks 80 for residential accounts and this is why I am attempting to setup this domain forwarding. Please any help would be greatly appreciated!

This is my current nginx configuration:
   ```
 #user  nobody;
    worker_processes  1;

    #error_log  logs/error.log;
    #error_log  logs/error.log  notice;
    #error_log  logs/error.log  info;

    #pid        logs/nginx.pid;


    events {
        worker_connections  1024;
    }


    http {
        include       mime.types;
        default_type  application/octet-stream;

        #log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
        #                  '$status $body_bytes_sent "$http_referer" '
        #                  '"$http_user_agent" "$http_x_forwarded_for"';

        #access_log  logs/access.log  main;

        sendfile        on;
        #tcp_nopush     on;

        #keepalive_timeout  0;
        keepalive_timeout  65;

        #gzip  on;

        server {
            listen 80;

            server_name 68.***.***.*** domain.example localhost;

            #charset koi8-r;

            #access_log  logs/host.access.log  main;

            location / {
                root   html;
                index  index.php index.html index.htm;
                proxy_pass http://127.0.0.1:3001;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

            }

            #error_page  404              /404.html;

            # redirect server error pages to the static page /50x.html
            #
            error_page   500 502 503 504  /50x.html;
            location = /50x.html {
                root   html;
            }

            # proxy the PHP scripts to Apache listening on 127.0.0.1:80
            #
            #location ~ /.php$ {
            #    proxy_pass   http://127.0.0.1;
            #}

            #pass the PHP scripts to FastCGI server listening on 127.0.0.1:9000
            #
             location ~ \.php$ {
                root           html;
            fastcgi_pass   127.0.0.1:9000;
            fastcgi_index  index.php;
            fastcgi_param  SCRIPT_FILENAME  c:/nginx/html$fastcgi_script_name;
            include        fastcgi_params;
        }

         #deny access to .htaccess files, if Apache's document root
         #concurs with nginx's one

        location ~ /\.ht {
            deny  all;
        }
```

**Comment by Cerothen** [comment]
If port 80 is blocked by your ISP there is nothing you can do internally to redirect port 80 to 3001.

You could get a super cheap virtual private server from lowendbox.com setup nginx/apache/haproxy and redirect or proxy your traffic through there.

I know it isnt ideal but you could pick up a vpn for as cheap as a few dollars per year.

**Comment by Rockapella** [comment]
Thanks for the reply Cerothen! I actually do have a VPN. How would I configure it with my VPN?

**Comment by Cerothen** [comment]
My apologies I typed it out on my phone I meant VPS (virtual private server) it must have been auto-corrected. Though if your VPN provider allows you to forward ports then you could inquire with them about how you could do it with them.
