### ISSUE TITLE
FR: Allow tabs to have overlay action

### ISSUE THREAD

**Issue by untotren** [causefx/Organizr#313]
Instead of opening page in iframe allow tabs to be popped over the current tab.  I want to implement a chat that pops up over current tab like facebook messenger.  So people can chat without flipping between tabs.

**Comment by Cerothen** [comment]
It's an interesting idea, perhaps we could make floating iframes to create a desktopesc experience.

**Comment by untotren** [comment]
Yes please!  Anything that can be utilized for a messenger type situation.

**Comment by untotren** [comment]
@Cerothen Were you able to make any progress on this?  Preferably like facebook where it's a small slider on the bottom.

**Comment by causefx** [comment]
With the evolution of org, i'm not sure i will be looking into this.   sorry.
