### ISSUE TITLE
Fatal error: Uncaught Error: Class 'PDO' not found in

### ISSUE THREAD

**Issue by mow4cash** [causefx/Organizr#317]
Fresh install first time using x64 Docker by LinuxServer.io

I make it to the setup page and use the default database location and set my timezone, then I get this error. 

Fatal error: Uncaught Error: Class 'PDO' not found in /config/www/Dashboard/user.php:160 Stack trace: #0 /config/www/Dashboard/index.php(67): User->__construct('registration_ca...') #1 {main} thrown in /config/www/Dashboard/user.php on line 160

**Comment by mow4cash** [comment]
It seems to be an issue with the latest Docker image

**Comment by justinglock40** [comment]
I'm getting this also using windows server and CaddyServer

**Comment by Cerothen** [comment]
```
<?php
phpinfo();
```
If you run this can you confirm that you have php-sqlite?

**Comment by justinglock40** [comment]
I figured out my issue it was on windows I didn't edit to php.ini and uncomment the files required. All good now.
