### ISSUE TITLE
possible bug?

### ISSUE THREAD

**Issue by untotren** [causefx/Organizr#320]
Line 14 of ajax.php seems like auth is commented out, not sure if this is an issue/intentional, just letting you know homie!

// Authorization
	# Check if user is currently active and allowed to access resource
	//require_once("user.php");
	# ^^ I think adding this does that?

**Comment by Cerothen** [comment]
The ajax.php in master was just a first framework for the ajax file.

This is the current version.
https://github.com/causefx/Organizr/blob/cero-dev/ajax.php
