### ISSUE TITLE
FR: Sync Emby DB from Organizr

### ISSUE THREAD

**Issue by untotren** [causefx/Organizr#321]
I really want to move toward a universal login, Since Organizr supports LDAP (hopefully SSO one day? :)) this is a step in the direction I wish to go.  If we have Organizr update Emby, we can use a backend auth that can be used across multiple services.

It doesn't look very difficult, only 4 related API calls.  I listed below:

2674: Update user PW
2736: Reset user PW
2849: Create user
2867: Update user

https://github.com/MediaBrowser/Emby.ApiClient.Javascript/blob/master/apiclient.js

**Comment by Cerothen** [comment]
Currently there are no plans update backend databases with password changes performed in organizr. It is possible that we will include hooks so other people can create their own functions to do that, for now were are mostly looking for allowing people to login with the same username/password from the specified backend database.

**Comment by untotren** [comment]
Understandable, I am working on trying to dev this as well.  I think the universal data would just be amazing and it would really set Organizr ahead of any other solution as it would be a roadmap to SSO.

**Comment by untotren** [comment]
@Cerothen This would be awesome as we could use self service as well for our users and a backend hook, maybe to update LDAP so you have a hack together centralauth.

**Comment by untotren** [comment]
@Causefx is this implemented?  It was changed to enhancement but I have seen no update.
