### ISSUE TITLE
php server on windows

### ISSUE THREAD

**Issue by marshy919** [causefx/Organizr#322]
Hey,

Very new to this nginx/php.

Followed the instructions given (not the advanced install).

Nginx is working, running as service through NSSM.
PHP is running as service also.
Installed Organizr to C:\Nginx\html\
The index.php file is under that folder.
Done the "nssm set ServiceName AppNoConsole 1" for the above services.
Installed Redistributable for Visual Studio 2015

From what I have read in other comments, I need SQLite.
I also saw that you could run check.php, however I can't seem to open the file.

Accessing localhost opens the nginx welcome page.
Accessing localhost/index.php downloads the index.php file.

Using Chrome inside a Virtualbox running Win10 Creators.

Any help would be much appreciated.
I've used manage-this-node all along, would like to see this in action, but is a bit more complicated ;)

Thanks!

**Comment by elmerfdz** [comment]
Assuming your folder structure is as below
Nginx = c:\nginx 
Php = c:\nginx\php

Replace your nginx.conf file contents with the sample code from https://github.com/causefx/Organizr/wiki/Windows-Installation:--Nginx-%7C-PHP-%7C-Organizr#sample-config-files

Reload nginx: `nginx -s reload `

**Comment by marshy919** [comment]
That's all I needed.
Thankyou very much!

**Comment by elmerfdz** [comment]
Np :)
