### ISSUE TITLE
Notice: Use of undefined constant

### ISSUE THREAD

**Issue by mow4cash** [causefx/Organizr#323]
Notice: Use of undefined constant PLEXHOMEAUTH - assumed 'PLEXHOMEAUTH' in /config/www/Dashboard/homepage.php on line 278

Notice: Use of undefined constant EMBYHOMEAUTH - assumed 'EMBYHOMEAUTH' in /config/www/Dashboard/homepage.php on line 292

Notice: Use of undefined constant SONARRHOMEAUTH - assumed 'SONARRHOMEAUTH' in /config/www/Dashboard/homepage.php on line 306

Notice: Use of undefined constant RADARRHOMEAUTH - assumed 'RADARRHOMEAUTH' in /config/www/Dashboard/homepage.php on line 306

Notice: Use of undefined constant HOMEPAGECUSTOMHTML1 - assumed 'HOMEPAGECUSTOMHTML1' in /config/www/Dashboard/homepage.php on line 333

Notice: Use of undefined constant HOMEPAGECUSTOMHTML1 - assumed 'HOMEPAGECUSTOMHTML1' in /config/www/Dashboard/homepage.php on line 335
HOMEPAGECUSTOMHTML1

Notice: Use of undefined constant SONARRHOMEAUTH - assumed 'SONARRHOMEAUTH' in /config/www/Dashboard/homepage.php on line 406

Notice: Use of undefined constant RADARRHOMEAUTH - assumed 'RADARRHOMEAUTH' in /config/www/Dashboard/homepage.php on line 406

**Comment by Cerothen** [comment]
Please confirm that your file "/config/configDefaults.php" looks like the file here

https://github.com/causefx/Organizr/blob/cero-dev/config/configDefaults.php

Did you do a fresh install or did you upgrade your install by overwriting the contents of the directory?

**Comment by mow4cash** [comment]
That was it. I overwrote the contents and skipped that file. oops

**Comment by Cerothen** [comment]
Great, glad it was an easy fix
