### ISSUE TITLE
password_verify()

### ISSUE THREAD

**Issue by 1cu** [causefx/Organizr#326]
In user.php there is a "new" password_verify function that isn't defined anywhere else. 

It was introduced with commit #235 and causes an undefined call resulting in users being unable to login.

**Comment by Cerothen** [comment]
What version is your php? The php.net page indicates this function was introduced in 5.5

http://php.net/manual/en/function.password-verify.php

**Comment by 1cu** [comment]
Well it's PHP 5.4.45 from Debian 7.

**Comment by Cerothen** [comment]
The password verify is there due to plans to replace the sha1 hash with a more secure hashing method.

Is there a reason you haven't updated or don't want to update?
http://stackoverflow.com/a/29201696

**Comment by Cerothen** [comment]
Didn't mean to close it.

**Comment by 1cu** [comment]
Fixed it :-)

Kudos to you.

**Comment by Cerothen** [comment]
Great, glad it was an easy fix
