### ISSUE TITLE
New version wipes out Tabs / Theme settings [windows]

### ISSUE THREAD

**Issue by seanvree** [causefx/Organizr#329]
Windows 10E

when upgrading to 1.34 from 1.32 Organizr will reset all tabs and theme settings. Users will still be there, homepage settings will still be there.

It will make a users.bak.db before it upgrades, but if you replace the new .db with the .bak.db the settings will still be gone.

I've tried the following:

 - tried to restore the previous .db from 1.32 but that throws this error:

```
Fatal error: Uncaught PDOException: SQLSTATE[HY000]: General error: 1 no such column: order in C:\inetpub\wwwroot\Organizr\index.php:120 Stack trace: #0  C:\inetpub\wwwroot\Organizr\index.php(120): PDO->query('SELECT * FROM t...') #1 {main} thrown in C:\inetpub\wwwroot\Organizr\index.php on line 120
```

- tried to upgrade via the GUI and doing a GIT PULL.  
Same problem.

Thanks!

**Comment by zarevnotek** [comment]
Hello, i have the same problem.

`Fatal error: Uncaught exception 'PDOException' with message 'SQLSTATE[HY000]: General error: 1 no such column: order' in /var/www/base/index.php:120 Stack trace: #0 /var/www/base/index.php(120): PDO->query('SELECT * FROM t...') #1 {main} thrown in /var/www/base/index.php on line 120`

On a other server, no problem with update.

Have a nice day!

**Comment by Cerothen** [comment]
Sorry for the inconvenience, I'll check it out tonight to see how I can fix that

**Comment by zarevnotek** [comment]
No problem, good luck to you! ;)

**Comment by Cerothen** [comment]
Can someone who had a failed backup send to me (through gitter.im or a method of your choice) the backup and new database? I would need to look at some details to get a better idea what has happened.

**Comment by seanvree** [comment]
@Cerothen I can do that  - hang tight

**Comment by seanvree** [comment]
@Cerothen  - Here you go. 

https://drive.google.com/file/d/0B7OujkYtbxFNNXBYRDY4WkJRRWc/view?usp=sharing

obvi the .old is the entire root DIR before the upgrade was initialized.  the .new is the new root DIR on the new version, but all the tabs wiped out. 

This is on Windows 10E x64

**Comment by Cerothen** [comment]
Got it, you can take the file down now

**Comment by Cerothen** [comment]
@seanvree https://github.com/causefx/Organizr/commit/17b3aee82c914187d12c50d32df1c98557db567c

After doing this fix the install you included above appears to properly upgrade without issue. Apparently the escape syntax is different for single quotes in sqlite... I wasn't aware of this.

**Comment by zarevnotek** [comment]
And for my case? What i can do? Thank you :)

**Comment by Cerothen** [comment]
Restore the backup of both the config.php (backup config.bak.php) and users.db (backup users.bak.db) after upgrading the functions file with the fix above. It should upgrade correctly and have the new column.

**Comment by seanvree** [comment]
@Cerothen 

So, do I change the functions.php AFTER I upgrade or before?

**Comment by Cerothen** [comment]
the changes are rolled into master repull master then restore the backup files and it should upgrade properly

**Comment by seanvree** [comment]
@Cerothen - Got it.  Trying now.

**Comment by seanvree** [comment]
awesome! THX!
