### ISSUE TITLE
Move the scroll bar on the menu more towards the right edge

### ISSUE THREAD

**Issue by Githubtordl** [causefx/Organizr#33]
Could you please move the scroll bar more towards the right? on the edge of the menu maybe? 

At the moment it doesn't look bad when the menu is expanded but when it's collapsed, it's a bit too close to the icons. (see picture below)

![image](https://cloud.githubusercontent.com/assets/22656503/21803931/534f3ec2-d724-11e6-9c2c-ff9eb8585e32.png)

**Comment by causefx** [comment]
good feedback,  I will look into that tonight.

**Comment by Githubtordl** [comment]
Thanks

**Comment by causefx** [comment]
On this [Line](https://github.com/causefx/Organizr/blob/master/bower_components/malihu-custom-scrollbar-plugin/jquery.mCustomScrollbar.css#L116) we need to add: `margin-left: 13px;`

If this is good we can submit it.

**Comment by Githubtordl** [comment]
Perfect!

![image](https://cloud.githubusercontent.com/assets/22656503/21819310/15ca0106-d763-11e6-8db0-df8a9141b33b.png)

**Comment by causefx** [comment]
sweet!
