### ISSUE TITLE
Mail server fails if there is a Dash (-)

### ISSUE THREAD

**Issue by duffkiligan** [causefx/Organizr#330]
Example:

smtp-relay.gmail.com
SMTP Host - Does not match pattern!

**Comment by Cerothen** [comment]
This is an easy fix, I forgot hostnames can have dashes

**Comment by Cerothen** [comment]
https://github.com/causefx/Organizr/commit/8f469d0c56b0669b2f8c5754b5aed1dbc9cd9004
