### ISSUE TITLE
Fatal error: Maximum execution time of 30 seconds exceeded in C:\Servers\Nginx\html\Organizr\functions.php on line 399

### ISSUE THREAD

**Issue by untotren** [causefx/Organizr#334]
This happens frequently.  Almost to the point that it is unusable.  HALP!

**Comment by untotren** [comment]
@causefx any idea on this?

**Comment by causefx** [comment]
when does this happen? on homepage? main site?

**Comment by causefx** [comment]
after looking into L#399, this may have to do with Emby logins.

**Comment by untotren** [comment]
@causefx Homepage.  It displays the loading.gif for ~30 seconds then displays this.  Honestly, I am having a few issues, perhaps logging could alleviate most issues so we could actually give more technical detail too?

**Comment by untotren** [comment]
I would not object to having a call or allowing you remote system access.  Alpha tester?

**Comment by Cerothen** [comment]
@untotren, depending on how much stuff your trying to show on your homepage this could happen. Eg calendar for 1000 days before and after, or if your hostnames aren't right for one (or more) of the services and it's timing out.

In any case you can increase the execution time in the php.ini file.

Before that I would check all the host names though

**Comment by untotren** [comment]
Calendar seems to cause a lot of issues, I made a previous issue for that though, about dynamically loading only when a user hits next etcto fix this.
