### ISSUE TITLE
Main page freeze 

### ISSUE THREAD

**Issue by mashranga** [causefx/Organizr#335]
I am a very new user. I have installed xampp as server and then set up organizer.  After that i have set up admin user and i can login to admin account . But after login to admin account , left hand side i got a menu , but no click working on that menu !! i wondered why ?? (Logout, fulscreen, refresh button at top right corner is working , 3 line button over top left corner also working )

I tried both in chrome and Firefox ..but shows the same problem . 
Can any one tell me , whats the problem ? 
if require more info about the problem , please let me know . 
But i need help , Thanks .

**Comment by causefx** [comment]
Can you email me the URL? Causefx at me dot come

**Comment by mashranga** [comment]
main sent. Please check . 
Thanks

**Comment by causefx** [comment]
what version did you update from, or is this a fresh install?

**Comment by mashranga** [comment]
1.34 ..i have used the zip file .

**Comment by causefx** [comment]
so it was a brand new install?

**Comment by mashranga** [comment]
yes ..it was

**Comment by causefx** [comment]
OK, when I get home i will try to install on windows box with fresh install to test.

**Comment by mashranga** [comment]
can you test over my server ?

**Comment by causefx** [comment]
can u install a fresh install?

**Comment by mashranga** [comment]
yes , i have already install a fresh zip . 
and after posting this issue, i have reinstall everything (xammp, organizer)

**Comment by causefx** [comment]
ok, i would need to be at setup screen

**Comment by mashranga** [comment]
start up screen mean ? without creating admin user ?

**Comment by causefx** [comment]
yes, fresh install with no DB

**Comment by mashranga** [comment]
ok .. done ..you can check .

**Comment by causefx** [comment]
can you delete db one more time please?

**Comment by mashranga** [comment]
done :)

**Comment by causefx** [comment]
good to go, same login details you gave me

**Comment by mashranga** [comment]
great !! but what did you do ? 
if i reinstall the whole system , will i face the same problem ?

**Comment by causefx** [comment]
its the db path for windows machines, we will research it
