### ISSUE TITLE
Unable to change Base URL

### ISSUE THREAD

**Issue by ewaroowar** [causefx/Organizr#337]
I have Organizr and Let's Encrypt setup in Unraid as separate dockers. Let's Encrypt works fine for my other internal web servers as I can change their base url but whenever I change Organizr's base url in index.php it goes mad with the page formatting.

Is there any way to give organizr a base url so I can get it working with Let's Encrypt?

**Comment by Cerothen** [comment]
This doesnt seem to make much sense to me. letsencrypt is a Certificate Authority. are you referring to your reverse proxy?

**Comment by Cerothen** [comment]
I thought about it and the best way to do this is to just make a folder on your web server for the baseurl that you want and put your organisr install there.

Eg if you want a base url of "ickypotatobeans" (random I know) and your webserver path is /var/www. Then put all the files at /var/www/ickypotatobeans.

You can then browse to http(s)://hostname.tld/ickypotatobeans to load up organizer
