### ISSUE TITLE
chrome unsafe scripts with proxy

### ISSUE THREAD

**Issue by porkie02** [causefx/Organizr#339]
I have installed Organizr and running through a Nginx Letsencrypt proxy, all works fine and certs work on initial load on login but to make proxied  links work correctly I have to click the shield in chromes address bar to load unsafe scripts so they load. Once I do this the page becomes unsecured. 

Is this normal or just bad configuration?

**Comment by untotren** [comment]
Bad configuration.  I use IIS ARR to reverse proxy, never got an error.

**Comment by Cerothen** [comment]
@porkie02 Is this happening with all your tabs or is it specific to one tab? Its likely that one of the tabs is loading content that is unsafe (eg over http instead of https)

**Comment by porkie02** [comment]
yeah I think its something like that, if I use a domain link for the proxy its fine, if I use local address it turns insecure. Only problem with the domain link is that for radarr/sonarr I want to use the line below to auth which only works if I use local address

if ($cookie_cookiePassword != "[cookiePassword]") { return 403; }

**Comment by Cerothen** [comment]
@causefx this is probably you.

**Comment by porkie02** [comment]
maybe this was the problem, I just updated sonarr/radarr and saw this in the notes.

https://i.imgur.com/G9kdJ11.png

**Comment by Cerothen** [comment]
was this resolved?

**Comment by porkie02** [comment]
No but its fine, Im only using it locally at the moment but if I was away it would be different. The error makes not usable on my phone.

**Comment by Cerothen** [comment]
More than likely it's not organizr as it is. it would be caused by the content of one of your tabs
