### ISSUE TITLE
[Feature Request] Option to save custom colour scheme

### ISSUE THREAD

**Issue by Githubtordl** [causefx/Organizr#34]
This is something for after 1.0 maybe, could you maybe be look into adding an option to save custom colour schemes and ability to pick my custom themes like the current default ones?

![image](https://cloud.githubusercontent.com/assets/22656503/21819118/47596050-d762-11e6-96c9-609190a4afaa.png)

**Comment by causefx** [comment]
hmmmm, let me think about that.

**Comment by Githubtordl** [comment]
sure, if it's too much trouble then never mind.

**Comment by SubNoizey** [comment]
Also is there a way to get the default theme back? I changed it and now the default black/red isn't an option

**Comment by causefx** [comment]
I didn't think someone actually liked those colors...  Those were the very first set of colors I did.

- $topbar = "#eb6363"; 
- $topbartext = "#FFFFFF";
- $bottombar = "#eb6363";
- $sidebar = "#000000";
- $hoverbg = "#eb6363";
- $activetabBG = "#eb6363";
- $activetabicon = "#FFFFFF";
- $activetabtext = "#FFFFFF";
- $inactiveicon = "#FFFFFF";
- $inactivetext = "#FFFFFF";

I'll add a button for default
