### ISSUE TITLE
Cant save any changes to Advanced settings

### ISSUE THREAD

**Issue by dejected1** [causefx/Organizr#340]
Just as it says. I can make the changes and hit save in the upper right. For example: enable mail . I don't get a apply thou. If i log out and log back in the changes have not taken effect. If i make the changes on the advanced tab then hit save for the tab screen i get the apply but then all the changes i made on the advanced tab haven't taken effect. Fully updated v1.34. Cache and cookies recently cleared.  Windows 10. Seemed to happen after most recent update.

**Comment by Cerothen** [comment]
If you hit control-shit-I that will bring up the developer console in chrome, if you hit save it should pop up some sort of error. Can you let me know what that error is. If its something like can't focus a particular field then check out the contents of that field and ensure that its a proper value.

**Comment by Cerothen** [comment]
https://github.com/causefx/Organizr/commit/c3e5af861ad04ac321f3e6af118821d4c318ee04

**Comment by dejected1** [comment]
just in case anyone looks afterwards ( i know you already closed it....) the upgrade to 1.342 fixed this.
