### ISSUE TITLE
Clicked autoupgrade, everything died.

### ISSUE THREAD

**Issue by untotren** [causefx/Organizr#342]
It tells me to register, then says it's not a correct URL.  I click login and use my old admin credentials, then I get a fun error:

Error: Only HTTP request are supported, please use cURL to add HTTPS support! (https://myembyurl.com)

**Comment by causefx** [comment]
What OS are you on?

**Comment by untotren** [comment]
Windows 7 Ultimate

**Comment by untotren** [comment]
It's a hyperv image, but I am just using a stock NGINX setup

**Comment by jowy** [comment]
same happened here. Ubuntu everything stock

**Comment by andrewparra** [comment]
I am seeing the same error as Jowy after clicking Auto Upgrade.  Running on Mac.

Fatal error: Uncaught PDOException: SQLSTATE[HY000]: General error: 1 no such column: order in /Applications/MAMP/htdocs/index.php:120 Stack trace: #0 /Applications/MAMP/htdocs/index.php(120): PDO->query('SELECT * FROM t...') #1 {main} thrown in /Applications/MAMP/htdocs/index.php on line 120

**Comment by causefx** [comment]
@jowy did you update today or earlier?

@andrewparra same question.

**Comment by andrewparra** [comment]
I updated today.  I also clicked the manual download button before I auto-updated, and tried a clean install of that in the hotdogs directory.  I was given the login page, but once logged in, I got the same error.

**Comment by causefx** [comment]
a clean install gave the same error, we will look into this, thank you.

**Comment by untotren** [comment]
@causefx Thank you for being so responsive and diligent, I know you have a life to tend to as well.  Check your Hangouts/Gchat, I messaged you.

**Comment by causefx** [comment]
@untotren i didnt see anything on Hangouts.  which email did you use?

**Comment by Cerothen** [comment]
Can everyone post the following so we can try and hammer it down:

OS:
OS Version:
Web Server:
Web Server Version
PHP Version:

For those of you that upgraded and had issues can you check your users.db/config.php directories and send all the .bak files (and the most recent non .bak version) in a zip package using gitter @cerothen. Only do this if your files are dated/versioned (users[2017-05-15_02-44-23][1.32].bak.db since that will show all the steps that occured during the upgrade process.

**Comment by untotren** [comment]
In good conscious of my users, there is no way I can send you my user database... Hashed or not.

**Comment by causefx** [comment]
you could always delete the user part of the db.

**Comment by andyrav** [comment]
I have the same problem

**Comment by jowy** [comment]
Sent.

OS: Ubuntu
OS Version: 16.04.2 LTS (Kernel: 4.4.0-75-generic)
Web Server: nginx
Web Server Version: 1.10.0
PHP Version: 7.1.5-1+deb.sury.org~xenial+1

**Comment by jowy** [comment]
@causefx Sorry for late response... I upgraded an hour or so before my comment on May 15th

**Comment by Cerothen** [comment]
Anyone who had a failed upgrade but has backups and wants to try again please download: https://github.com/causefx/Organizr/tree/cero-dev and unpack/overwrite the directory and try again, this should resolve the issues.

**Comment by wessel145** [comment]
> jowy commented 3 days ago • edited
> same happened here. Ubuntu everything stock
> 
> Fatal error: Uncaught PDOException: SQLSTATE[HY000]: General error: 1 no such column: order in /var/www/Organizr/index.php:120 Stack trace: #0 /var/ww

I got the same error after the auto update (before the update everything in check.php was green). can't seem to fix this...

**Comment by Cerothen** [comment]
Rolled new update into master, those with backups can restore and upgrade again those without @causefx apologizes for trusting me ;-).

**Comment by jowy** [comment]
Thanks, all!

**Comment by untotren** [comment]
Where are backups stored? I don't remember if I did but that sucks

**Comment by Cerothen** [comment]
Backups are stored with the original files. and have a .bak section to the filename
