### ISSUE TITLE
RFE: LDAP bind user

### ISSUE THREAD

**Issue by lbeltrame** [causefx/Organizr#344]
Some LDAP installations will forbid searching for users without authentication ("anonymous bind"). They usually have a "LDAP bind user" with minimal privileges which is used to perform the search and return the found user.

I'm not sure if Organizr needs this for LDAP: if it does, it would be a welcome addition.

**Comment by Cerothen** [comment]
Currently it just tried to log in as the user you specified, so if that succeeds then its good to go. It doesnt do group lookups or anything like that
