### ISSUE TITLE
MySQL Support

### ISSUE THREAD

**Issue by escservices** [causefx/Organizr#35]
My shared host will never let me put a db or anything outside the main hosted public directory.  Currently I used an .htaccess rule to deny access to any files ending in .db not positive how secure that is because it's still not as secure as being completely outside the public space.  How difficult would it be to implement MySQL? PDO Sqlite looks very similar to PDO MySQL but not too sure I don't do much with PHP.

**Comment by causefx** [comment]
I'm planning on adding a customizable path for the DB location.  for now if you still want to try it, just edit this file @ line 11: [user.php](https://github.com/causefx/Organizr/blob/master/user.php#L11) 

change to:
Line 11:
`define('USER_HOME', __DIR__ . '/users/');`

Line 12:
`define('DATABASE_LOCATION', __DIR__ . '/');`

**Comment by escservices** [comment]
That's exactly what I did, it's been working fine.  I also added 
`<Files ~ "\.db$">
    Order allow,deny
    Deny from all
</Files>`
to the .htaccess to protect the db.

**Comment by causefx** [comment]
Hopefully I will have this done soon, so your setup can survive upgrades.

**Comment by causefx** [comment]
Same Issue as #13
