### ISSUE TITLE
Homepage leaks Emby API if it can't contact Emby.

### ISSUE THREAD

**Issue by kendokan** [causefx/Organizr#351]
When homepage.php is configured for Emby and is loaded when it's unable to contact the Emby server, it exposes the API key. It's possible this happens with other services as well, but I haven't tested.

`Warning: file_get_contents(http://emby:8096/Users?api_key=<redacted>): failed to open stream: php_network_getaddresses: getaddrinfo failed: Name does not resolve in /config/www/Dashboard/functions.php on line 640`

**Comment by Cerothen** [comment]
https://github.com/causefx/Organizr/commit/d2352cf0246047bf26be4de3bdb51ca871f6ab91

This should resolve the issue.
