### ISSUE TITLE
Autoupdate from 0.99 to latest version fails

### ISSUE THREAD

**Issue by barbidule** [causefx/Organizr#352]
Error message : Fatal error: Uncaught PDOException: SQLSTATE[HY000]: General error: 1 no such column: order in C:\inetpub\wwwroot\Organizr\index.php:119 Stack trace: #0 C:\inetpub\wwwroot\Organizr\index.php(119): PDO->query('SELECT * FROM t...') #1 {main} thrown in C:\inetpub\wwwroot\Organizr\index.php on line 119
Windows 2016 server

**Comment by causefx** [comment]
when did you update?

**Comment by barbidule** [comment]
19th of may. Since it's broken, I can't see the versions anymore :/
It was running (fine) on IIS.

**Comment by barbidule** [comment]
Ah, found it. It was upgrading to 1.342

**Comment by barbidule** [comment]
Is there a way to roll back to an older version ?

**Comment by goldserve** [comment]
I get the same error:

Fatal error: Uncaught PDOException: SQLSTATE[HY000]: General error: 1 no such column: order in /config/www/Dashboard/index.php:138 Stack trace: #0 /config/www/Dashboard/index.php(138): PDO->query('SELECT * FROM t...') #1 {main} thrown in /config/www/Dashboard/index.php on line 138

Looks like the database is not in sync with what is expected. Maybe database update code failed? Doesn't seem to find the column: 'order' in my database.

**Comment by causefx** [comment]
What OS and webserver? What version did you update from?

**Comment by goldserve** [comment]
Upgraded from 1.323 and running lsiocommunity/organizr docker

**Comment by causefx** [comment]
Auto upgrade in GUI or docker refresh?

**Comment by barbidule** [comment]
For me, autoupdate in gui

Le 23 mai 2017 20:45, "causefx" <notifications@github.com> a écrit :

Auto upgrade in GUI or docker refresh?

Sent from my iPhone


> On May 23, 2017, at 11:34 AM, goldserve <notifications@github.com> wrote:
>
> Upgraded from 1.323 and running lsiocommunity/organizr docker
>
> —
> You are receiving this because you commented.

> Reply to this email directly, view it on GitHub, or mute the thread.
>

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/causefx/Organizr/issues/352#issuecomment-303495128>,
or mute
the thread

**Comment by goldserve** [comment]
For me, I also used autoupdate in GUI.

**Comment by goldserve** [comment]
I am able to use organizr again by deleting all "ORDER BY `order` asc" from index.php and settings.php.

**Comment by Jaybeam** [comment]
After deleting all "ORDER BY order asc" I can also use most off organizr but still cant acces the settings page.

`Fatal error: Uncaught PDOException: SQLSTATE[HY000]: General error: 1 no such table: options in /volume1/web/Organizr/functions.php:1767 Stack trace: #0 /volume1/web/Organizr/functions.php(1767): PDO->query('SELECT * FROM o...') #1 /volume1/web/Organizr/settings.php(30): loadAppearance() #2 {main} thrown in /volume1/web/Organizr/functions.php on line 1767`

(Update from GUI)

**Comment by barbidule** [comment]
I deleted ORDER BY `order` asc' from index.php and settings.php, but now I'm getting a http error 500

**Comment by barbidule** [comment]
Is there a way to download the latest working version ?

**Comment by causefx** [comment]
can you get to settings.php at all?

**Comment by causefx** [comment]
you could also download the new zip, and overwrite the files.

**Comment by goldserve** [comment]
I just spun up a new docker, put two browser windows side by side and copied all the settings over. Now I'm in the latest and I hope it doesn't break again.

**Comment by causefx** [comment]
that issue should have been a one time issue as we changed the DB.

**Comment by barbidule** [comment]
I downloaded the latest zip and overwrote files, I still get 
Fatal error: Uncaught PDOException: SQLSTATE[HY000]: General error: 1 no such column: order in C:\inetpub\wwwroot\Organizr\index.php:138 Stack trace: #0 C:\inetpub\wwwroot\Organizr\index.php(138): PDO->query('SELECT * FROM t...') #1 {main} thrown in C:\inetpub\wwwroot\Organizr\index.php on line 138

**Comment by causefx** [comment]
Can you edit `functions.php` and change **Line 5** to `1.32`

https://github.com/causefx/Organizr/blob/master/functions.php#L5

**Comment by barbidule** [comment]
Just did, still same error

Fatal error: Uncaught PDOException: SQLSTATE[HY000]: General error: 1 no such column: order in C:\inetpub\wwwroot\Organizr\index.php:138 Stack trace: #0 C:\inetpub\wwwroot\Organizr\index.php(138): PDO->query('SELECT * FROM t...') #1 {main} thrown in C:\inetpub\wwwroot\Organizr\index.php on line 138

**Comment by causefx** [comment]
very odd, What OS and Webserver?

**Comment by barbidule** [comment]
Windows server 2016 / IIS

**Comment by causefx** [comment]
Thank you for the info, we will keep trying to figure out the problem.

**Comment by barbidule** [comment]
Tanks for your help !
