### ISSUE TITLE
Fatal error: Uncaught PDOException

### ISSUE THREAD

**Issue by schmittyd** [causefx/Organizr#354]
Hi,
 I have just tried a fresh install of Organizr and get the following error after creating the admin account

Fatal error: Uncaught PDOException: SQLSTATE[HY000]: General error: 1 no such column: order in D:\nginx\html\organizr\index.php:138 Stack trace: #0 D:\nginx\html\organizr\index.php(138): PDO->query('SELECT * FROM t...') #1 {main} thrown in D:\nginx\html\organizr\index.php on line 138

**Comment by elmerfdz** [comment]
Open check.php and see if you meet all the requirements

**Comment by schmittyd** [comment]
Everything is fine

**Comment by causefx** [comment]
what webserver?

**Comment by schmittyd** [comment]
NGINX

**Comment by causefx** [comment]
That's odd, i just installed a fresh 1.342 on nginx on windows 10, no issue at all.

**Comment by schmittyd** [comment]
Fixed it! Had to delete db from the live server and also delete config.php from test and live servers, then restart NGINX. They were both linking to the same db.
