### ISSUE TITLE
Bug (Emby HTTPS)

### ISSUE THREAD

**Issue by untotren** [causefx/Organizr#355]
Error: Only HTTP request are supported, please use cURL to add HTTPS support! (https://myembyurl.com)

**Comment by Cerothen** [comment]
This doesnt sound like a bug it sounds like you are missing php5-curl

**Comment by untotren** [comment]
It was working until the update, it's a solo hyperv-vm that has not changed at all and this is all it is hosting.

**Comment by untotren** [comment]
Also, not sure if it matters, but it's on a windows 7 machine.

**Comment by untotren** [comment]
Also, just checked, php service is running.

**Comment by untotren** [comment]
also, php_curl.php is in the ext folder.

**Comment by untotren** [comment]
Do I need to set an environment variable or anything? I didn't see anything suggesting as such in the docs, I did everything by the book.

**Comment by Cerothen** [comment]
![image](https://cloud.githubusercontent.com/assets/9008757/26360261/a947a3ca-3fa5-11e7-9a2c-ab86061eb6e4.png)

Does the config screen show disabled like in this view?

**Comment by untotren** [comment]
I cant even get to the config.  I get this error right after signing in.

**Comment by causefx** [comment]
Can you change the emby URL to http?

**Comment by untotren** [comment]
I cannot, it is public, and I cannot force my users on a non-TLS channel over extranet.  I can test it if that is what you mean, but the host is forced HTTPS only, so it would not load.

**Comment by untotren** [comment]
Sorry, I just take security very seriously for my users.

**Comment by Cerothen** [comment]
Remove the line from the config/config.php file ```'authBackend' => '???????????',```

This will disable the calls to emby, to the best of my memory the only things that call that function are related to authentication. This will permit you to login using your regular organizr only credentials. you can then respond to my earlier item and let me know if you have dependencies missing

**Comment by Cerothen** [comment]
Any updates?

**Comment by untotren** [comment]
Yup, it says PHP Curl is missing when I got it working doing what you said.  but as I pointed out, it is not missing and is fully configured properly.

**Comment by untotren** [comment]
Welp, it booted and let me login as the default admin.  And it deleted all my settings/users and auth doesn't work.  Also, I made a new user using register user and immediately tried logging in and it failed.

**Comment by untotren** [comment]
Finally got a user created, I didn't have an email in the new user so it would never commit the create user command, no error handling or message.....  I login with the test user, and I get an error saying I don't have proper access to view the homepage, but I set homepage to user only needed, not admin, nice.

**Comment by causefx** [comment]
i find it very odd that it says PHP curl missing when you say it is installed and configured properly.  Can you goto check.php and post a screenshot of this section?

![image](https://user-images.githubusercontent.com/16184466/27068283-1ffe99dc-4fc4-11e7-91a0-f988d3626023.png)

**Comment by Cerothen** [comment]
Last chance to submit the info @causefx asked for, otherwise we will close this one up.

**Comment by untotren** [comment]
I will shortly

**Comment by causefx** [comment]
anything on this?  if so reply back and we will open again
