### ISSUE TITLE
How important is the sidebar for the guest page?

### ISSUE THREAD

**Issue by leram84** [causefx/Organizr#36]
ok, like most things, i have no idea how practical this is, just want to see what you think. What if for the guest page we get rid of the side bar? I was just thinking that its kind of a waste, and unnecessary when you only have a few icons (as i would imagine most do for the guest page). Instead, hide everything in the drop down. So you only see the apps available in the drop down menu, but the running app will take the full width of the screen. Then you could, instead of having "Organizr" at the top, you could have the title of whatever app you're in (plex, ombi, whatever). Also if you ever add a single sign on method, you could add that to the top right of the top bar, so it would either say "Login" or a "Signed in as <account name>" button with a drop down for "Log Out". I feel like this would make the guest page look a lot more like a familiar website/app. Otherwise the guest page looks like it has a sidebar of apps.... that's missing a lot of apps. I like the layout for admin, cuase it gives you fast switching ability without needing to click the drop down first, but since guests will only switch apps maybe like once each time they log in, there's no need for that quick access sidebar. 

Again, i don't know how difficult this would be, but it seems very similar to the way mobile works (other than the dynamically switching header title), so im hopping it would be an easy layout option to add. ehh?

**Comment by causefx** [comment]
Good write up.  I understand everything you are saying.  All of this would be a fairly large change.  I'm not entirely sure everyone would agree with that request.  There is quite a bit of javascript that runs to make all the side bar stuff work.  I will take this into consideration :)

**Comment by leram84** [comment]
no worries, im just glad i was able to explain that without having to subject anyone to my drawing skills lol.

**Comment by causefx** [comment]
lol, no worries, keep the ideas coming tho :)

**Comment by leram84** [comment]
yeah, my main focus has really been the guest page, which is the main reason im using all this to begin with. Im just trying to build something as close to a professional full featured webapp as i can. It's all come so far since i started down this path! but yeah, im sure ill think of other stuff to want :)

**Comment by causefx** [comment]
haha yea!  Yeah I too have come a long way since iDash :)

**Comment by SgtBatten** [comment]
Also worth noting that any new visitor to the page won't have the sidebar pinned by default so in a way it is hidden initially.

**Comment by causefx** [comment]
Haha. True.

**Comment by causefx** [comment]
After thinking about this, I'm planning to keep it the same.  Sorry.
