### ISSUE TITLE
Add support for Mylar in Homepage Calender

### ISSUE THREAD

**Issue by hubbcaps** [causefx/Organizr#360]
I'd like to request support for [Mylar](https://github.com/evilhero/mylar) be added to the homepage calender. The actual api command I would like added is the getUpcoming method, this exposes an issueDate, issueNumber and ComicName for new comics coming up that week that you have tracked. That would be useful info on the calender.

The command is as follows:

`curl -i http://<mylarip>:<mylarport>/api\?apikey\=<apikeyt>\&cmd\=getUpcoming`

I can see where the other parts for plex and Sonarr/Radarr are added into the homepage.php but I'm not sure how to expose that graphically in the settings so I'm refraining from trying to implement it myself at this time.

**Comment by causefx** [comment]
we can do that

**Comment by causefx** [comment]
Closing all Feature Requests and will communicated thru FeatHub
