### ISSUE TITLE
User accounts not created if email address already in use 

### ISSUE THREAD

**Issue by CBers** [causefx/Organizr#361]
If you try to create a new Organizr user using the same email address as another account, then the account doesn't get created, but there are no error messages. 

v1.343

**Comment by CBers** [comment]
Will set up remote access if you're unable to replicate.

**Comment by FrostByteLXV** [comment]
New user today loaded v1.343 and got the same issue which is related to another issue I had where the original account I created flashed a quick message something like "Account is too similar to another account".  This was my only account at the time, so I assumed it was referring to my Emby account or something else so I tried creating another account using the same email

Steps
1. Manage Users
2. Fill out data using same email address of current user
3. Create Account
4. Page refreshes, but when you go back to Manage Users the account isn't created

**Comment by causefx** [comment]
Fixed on 1.40 0e36837
