### ISSUE TITLE
Can't delete original user account

### ISSUE THREAD

**Issue by FrostByteLXV** [causefx/Organizr#362]
I wanted to remove the original account I created because it kept flashing a message saying something like "Account is too similar to another account" every time I logged in even though it was my only account.  Mmaybe it was aware of my Emby connect logon?  

Anyhow, after creating a second admin account and logging in with the new account, the system still would not allow me to remove the original account and just showed a circle with the slash through it when I hovered over the "Delete" button.  Fix action was delete the user.db and start over by creating an initial account which wasn't similar to my Emby account for the Organizr logon.

**Comment by causefx** [comment]
At the moment it isn't possible to delete the first admin acct.  We will look into adding that, or even just changing the username.

**Comment by FrostByteLXV** [comment]
Thanks causefx

**Comment by CBers** [comment]
Good catch FrostByteLXV. 

I knew those 7 hours weren't wasted :)

**Comment by causefx** [comment]
errors are corrected on v2
