### ISSUE TITLE
Organizr similar account name error at login

### ISSUE THREAD

**Issue by FrostByteLXV** [causefx/Organizr#363]
On my first setup of Organizr I received a real quick message just to the right of the hamburger menu which said something like "Can't use account because it's too similar to another account".  That may not be the exact message, but it flashed real quick every time I logged in.

Since this was my only account in Organizr at the time the only thing I could think of was that the account name I used was the same as my Emby connect account even though I hadn't even configured Emby on any of the tabs yet it still flashed this message every time.

Fix was to remove the user.db and create a new intitial account because Organizr would not allow me to delete the original account even from a new Admin account.

Not sure how to fix, but if this is really associated with Emby then maybe reject the account name, or display a message saying not to use a Plex or Emby account.

If not associated with Emby, then not sure what account it would be referring to because this was the only Organizr account at the time.

**Comment by causefx** [comment]
This only happens because the values were still stored in POST. We will fix it.  As soon as you close the window and go back it will be fine.

**Comment by FrostByteLXV** [comment]
Makes sense, thanks again

**Comment by CBers** [comment]
Good catch FrostByteLXV.

**Comment by causefx** [comment]
errors corrected on v2
