### ISSUE TITLE
Calendar view on homepage is forgotten after updating tabs using Edge browser

### ISSUE THREAD

**Issue by FrostByteLXV** [causefx/Organizr#366]
After making changes to tabs you are required to apply changes which causes Organizr to forget the calendar view (Today, Month, Day, Week) you have chosen when using MS Edge browser.  This doesn't appear to be a problem with Chrome. 

Steps to recreate
1. Click Settings, Edit Tabs
2. Click Save Tabs
3. Click green Apply Changes box (Organizr page refreshes)
4 Click Homepage tab
5. Calendar only shows the header and you have to click Weekly, or whatever option you want, in order to see any data

**Comment by CBers** [comment]
I am also seeing this in EDGE, but it is OK in Chrome,
