### ISSUE TITLE
Blank Screen on mobile. 

### ISSUE THREAD

**Issue by tdunks** [causefx/Organizr#369]
Currently having an issue where nothing within the iframes shows on mobile. I see the header and the tabs but the main area is always blank even in settings. This issue persists in mobile and desktop view on Samsung galaxy S8 and S7 in both Samsung browser and chrome.

**Comment by Cerothen** [comment]
Its likely not an Organizr issue, its just how iframes work:

URLs need to be served over the same protocol: http/https
URLs need to be accessible directly (if you can't load it directly it wont load in a frame)
If the host is different you need to ensure that the framed page doesnt have xframe deny or sameorigin headers

**Comment by tdunks** [comment]
It is working fine on desktop, just not mobile.

**Comment by causefx** [comment]
On desktop it works locally and outside network?
