### ISSUE TITLE
Rename icon folder

### ISSUE THREAD

**Issue by andyrav** [causefx/Organizr#37]
Hi On ubuntu  with apache2 the icon folder by default is protected

Default installations of Apache usually alias /icons to Apache's icons directory which cannot be overridden in an .htaccess file. If you do not control the Apache configuration of a server, and for maximum compatibility, it is always best to never have an /icons directory at a website's root level

could you change the name of the folder?

**Comment by causefx** [comment]
thanks for that.  I use Nginx so never ran into that problem.
