### ISSUE TITLE
Issue/Feat Request:  FTP Back-end Auth will not update creds after initial auto-generation

### ISSUE THREAD

**Issue by seanvree** [causefx/Organizr#370]
This was tested on Org ver  1.344  and using MS IIS 10 and FTP back-end AUTH running on Windows10.

So, IF you are using FTP back-end auth and an account is auto-generated when a user initially logs on using their FTP creds, the Organizr Db is NOT updated if that user were to change their creds via the FTP server.

In addition,  if user is deleted from the FTP server, the user will remain in the orgainzr user Db and will be able to log on. 

NOTE;  The initial user creation using the FTP back-end auth, works great.  This issue is ONLY relevant if the user is updated via the IIS user management. 

More of a feature request, but this is an important issue IF you rely on FTP auth. 

THX

**Comment by Cerothen** [comment]
Authorization will be fully rewritten in 2.0. currently logins are looked up in the backend every time when a user logs in. Currently when the user logs in the password should be updated to the successful password. This does mean that the prior password will work until they log in with the new one. It also means that if the user is removed then they could still log into organisr with the last password they used

**Comment by seanvree** [comment]
@Cerothen  - thanks!  

Ahh, okay, yeah, that's what I"m seeing. 

"it also means that if the user is removed then they could still log into organizr with the last password they used"

Are you saying this is what it should do on the current version, or what it WILL do on 2.0?

**Comment by Cerothen** [comment]
What it currently does do. We haven't finished authentication for 2.0

**Comment by seanvree** [comment]
got it! THANKS!
