### ISSUE TITLE
Problem with LDAP binding

### ISSUE THREAD

**Issue by budbay** [causefx/Organizr#373]
I'm trying to get LDAP working but keep getting this error: : ldap_bind(): Unable to bind to server: Invalid DN syntax in /organizr/functions.php on line 33. My LDAP server is on same as Apache so I set "ldap://localhost:389", then for dn I have tried many different variations, but my users are at " ou=people,dc=test,dc=com”

**Comment by budbay** [comment]
Sorry hit submit as I'm typing on mobile,  this is probably an issue on my end somewhere but could use some help finding the issue. Thanks

**Comment by budbay** [comment]
forgot to mention using openLdap on Ubuntu 16.04, slapd error shows: do_bind: invalid dn (ou=people,dc=test,dc=com\user)

**Comment by budbay** [comment]
ok, i figured out how to get it working.  for reference i am running openLdap and apache on a ubuntu 16.04 server. i dont know much about php so this may be a bit crude but i modified the functions.phpin two ways:
first to correct the invalid DN sytax error i added the following line after line number 32
       $ldapUser = 'uid='.$username.','.AUTHBACKENDDOMAIN;
This then created a new error, invalid protocol, which i corrected by adding the following after the last line:
        ldap_set_option($ldap, LDAP_OPT_PROTOCOL_VERSION, 3);
then changed the ldap bind line to read:
       if ($bind = ldap_bind($ldap,$ldapUser,$password)) {
everything now works as expected, at least as far as i have tested.  So in the future you will probably need to add some kind of check on ldap version and authenticate accordingly. i assume the existing code was maybe for AD. any feedback would be appreciated. thanks.

**Comment by causefx** [comment]
@Cerothen how do you think this will handle other connections?
