### ISSUE TITLE
Calendar not showing on homepage

### ISSUE THREAD

**Issue by mattman86** [causefx/Organizr#374]
The calendar doesn't show up on the homepage. I've checked URLs, ports and API keys and all is correct.

**Comment by causefx** [comment]
Email me the URL. Causefx at me dot com

Open up homepage security please.

**Comment by mattman86** [comment]
I fixed it by reinstalling.

**Comment by untotren** [comment]
What do you mean by, 'reinstalling'?  I am getting the same issue.

**Comment by causefx** [comment]
@untotren what issue are you having?

**Comment by blackley** [comment]
I have the same problem - i have never been able to get the calendar working on the homepage.

**Comment by untotren** [comment]
@causefx no calendar showing up.
