### ISSUE TITLE
[FR] More classes

### ISSUE THREAD

**Issue by chrisvdgeld** [causefx/Organizr#377]
Hi,

Is it possible for Organizr to have more user classes? I'd like to have 1 userclass for clients, 1 userclass for clients and config and 1 admin (I don't want anyone but me access to organizr settings, but I want multiple users access to sonarr.. just not everyone.)

Chat function works amazing guys!

**Comment by chrisvdgeld** [comment]
I was blind, sorry. Was already requested before!

**Comment by causefx** [comment]
This is planned for 2.0 :)
