### ISSUE TITLE
Chat beta SQLite3 error

### ISSUE THREAD

**Issue by gilbN** [causefx/Organizr#378]
I get this error after I add chat.php

Fatal error: Uncaught Error: Class 'SQLite3' not found in /config/www/organizr/www/Dashboard/chat.php:139 Stack trace: #0 {main} thrown in /config/www/organizr/www/Dashboard/chat.php on line 139

**Comment by causefx** [comment]
what OS?

**Comment by Dukko** [comment]
Same here on Windows 10

**Comment by mattman86** [comment]
You need to uncomment _extension=php_sqlite3.dll_ in your php.ini file.

**Comment by gilbN** [comment]
Sorry, forgot. It's on the linuxserver docker container

**Comment by gilbN** [comment]
@mattman86 This is the content of the php.ini file in the chat directory 

post_max_size = 15M
upload_max_filesize = 10M

**Comment by mattman86** [comment]
You might be able to just add the line to that file.

**Comment by gilbN** [comment]
@mattman86  didn't work, probably because I don't have sqlite3 installed.

**Comment by untotren** [comment]
Same error here: 
Fatal error: Uncaught Error: Class 'SQLite3' not found in C:\Servers\Nginx\html\Organizr\chat.php:139 Stack trace: #0 {main} thrown in C:\Servers\Nginx\html\Organizr\chat.php on line 139

On server 2k12R2 with sql3 installed.

**Comment by untotren** [comment]
With the update this still occurs, any ideas? @causefx

**Comment by causefx** [comment]
for people on windows on php.ini uncomment `extension=php_sqlite3.dll`

**Comment by untotren** [comment]
It wasn't even in the file, I added it, rebooted nginx nothing, rebooted server, nothing.

**Comment by untotren** [comment]
@causefx Where in here does it say to install sql or download anything sql..?

https://github.com/causefx/Organizr/wiki/Windows-Installation:--Nginx-%7C-PHP-%7C-Organizr

**Comment by causefx** [comment]
@untotren sqlite is included in the download of php.  What does your extension folder say in php.ini?

**Comment by untotren** [comment]
I see no folder named extensions, can you provide more detail some of your responses are hard to decipher as they don't include directories etc.

**Comment by causefx** [comment]
sorry, in php.ini should be a line like this:

`extension_dir='C:/BLAH/BLAH'`

**Comment by untotren** [comment]
I am assuming you mean php.ini located in the subfolder, 'chat'?

**Comment by causefx** [comment]
no sir. php.ini on your server... maybe c:/php ?

**Comment by untotren** [comment]
Ah okay, see you guys not specifying directories ive been editing php.ini in chat this whole time.....

It says:
extension_dir = "ext"

**Comment by causefx** [comment]
uncomment the previous line i mentioned in that php.ini

**Comment by untotren** [comment]
It did nothing.  Rebooted too.

**Comment by causefx** [comment]
can you post your php.ini?

**Comment by causefx** [comment]
going to chat.php still says sqlite not loaded?

**Comment by untotren** [comment]
yup, and I will do later once I make sure there's nothing sensitive.
