### ISSUE TITLE
Cant drag down tab icon selection

### ISSUE THREAD

**Issue by richowen** [causefx/Organizr#381]
Just a little thing, when you click on the little diamond for the tab icon thing not tab pictures you cant drag the scroll bar down it just moves the whole tab settings. 
https://i.gyazo.com/ed22a84e1e762c832db726e219adaf07.mp4

**Comment by causefx** [comment]
ahhhh ok, I will look at the css of this, thanks.

**Comment by causefx** [comment]
this was fixed in 1.40 - fc27949
