### ISSUE TITLE
Server not found Cyberfox can’t find the server at error.php.

### ISSUE THREAD

**Issue by richowen** [causefx/Organizr#383]
Not getting error pages showing up, error 999 is redirecting to https://error.php not https://example.example.com/error.php. Using Linuxserver docker, organizr version 1.36. 

Set hompage auth to min lvl user, removed guest auth from all tabs then opened organizr in an incognito tab get "can’t find the server at error.php."]

[error firefox log.txt](https://github.com/causefx/Organizr/files/1065055/error.firefox.log.txt)

**Comment by causefx** [comment]
what is the location blocks?  can you post those>?

**Comment by richowen** [comment]
must have been something on my end, cant reproduce, will close this, ty for the reply
