### ISSUE TITLE
Settings.php hangs

### ISSUE THREAD

**Issue by untotren** [causefx/Organizr#385]
This was working great a few months ago, now it seems like the whole solution is basically falling apart/imploding on itself. 

Ever since the auto-upgrade destruction this app has been falling apart.  Now I just reinstalled the whole thing and it's very buggy.  I added nothing but Emby, Sonarr and Radarr along with the home.php as the only tab.  Home loads fine, when I click settings it just loads indefinitely, no errors, no useful debug info, just nothing.  What is going on?

**Comment by causefx** [comment]
can you install a separate instance and email me the login details?  I would love to see what it is doing.

**Comment by untotren** [comment]
@causefx Do you have a google hangouts?

**Comment by causefx** [comment]
I do not. We hang out in the gitter chat room.
