### ISSUE TITLE
[Request] Export in new Tab

### ISSUE THREAD

**Issue by seb972** [causefx/Organizr#388]
Hi,

Can you add an export button near the refresh or the full screen button please. Just for open the page in a new tab of the browser please?

**Comment by causefx** [comment]
That's actually a great idea.

**Comment by untotren** [comment]
+1

**Comment by causefx** [comment]
this is completed.
![image](https://user-images.githubusercontent.com/16184466/27232950-b362ffa6-526c-11e7-8b71-f9daf2c9245e.png)
will be on next update.

**Comment by untotren** [comment]
Good form sir!
