### ISSUE TITLE
[FR] Reverse Proxy

### ISSUE THREAD

**Issue by untotren** [causefx/Organizr#389]
Right now, a user cannot see tabs unless they are granted permission.  Which is great, but not very secure at all.  BUT, the tab only points to a public URL, so even if they cannot see the tab as it is protected via organizr, if they figure out/know the public URL, they can just visit it outside Organizr.

This is basically security via obscurity, which we all know is not secure at all.

It would be best if organizr could utilize local, non private URLs, in a method like reverse proxying.

There are a few projects on github using php to reverse proxy, which may help get this started:
https://github.com/nbhr/php-reverse-proxy
https://github.com/chricke/php5rp_ng

More references:
http://fuzzytolerance.info/blog/2007/11/30/2007-11-30-a-quick-and-dirty-reverse-proxy-with-php/
http://facat.github.io/a-php-based-reverse-proxy.html

**Comment by causefx** [comment]
You can secure all reverse proxies using Organizr.

https://github.com/causefx/Organizr/wiki/Authentication-%7C-Server-Based

**Comment by untotren** [comment]
I'm going to have to look at this.  I am trying to hack this together as an SSO with emby, owncloud etc with my dev.

**Comment by causefx** [comment]
ahhh nice

**Comment by untotren** [comment]
Is there no way to do SSO for Emby via this?  It seems possible.

**Comment by causefx** [comment]
I have researched almost all available proxies and none seem to do the trick properly.  We may revisit in the future.
