### ISSUE TITLE
Plex Auth with Windows Nginx server not working.

### ISSUE THREAD

**Issue by justinpeterson13** [causefx/Organizr#391]
Users cannot login to Organizr using their Plex credentials, only the main account is able to do so. Myself and a few other Org enthusiasts narrowed it down to a Windows Nginx server.

Thanks!

**Comment by causefx** [comment]
I will install nginx on my machine tonight and do some testing.

**Comment by justinpeterson13** [comment]
Awesome!

I briefly brought up the issue before in a chat but until now I thought it was only me having the issue.

Justin

**Comment by causefx** [comment]
do the users have any special characters in username or password?

**Comment by justinpeterson13** [comment]
The users i’ve tried don’t have special characters in the username. The passwords have a ‘?’ in some.

Justin

**Comment by blackley** [comment]
This is what you need for plex to work correctly with Nginx.
upstream plex-upstream 		{ server 127.0.0.1:32400;}
  include config/proxy.conf;
    location /web/ {
    proxy_pass https://plex-upstream;
    }

    location /plexserver/ {
    proxy_pass https://plex-upstream/web/;
    }

I have it running on Linux and Windows no problems.

**Comment by justinpeterson13** [comment]
Wow, i feel stupid now. Plex wasn’t working with iframe so I turned it off a while ago. I don’t know why I didn’t add it along with sonarr etc. in the nginx.conf. I’ll give it a try here after lunch and let you know.

Thanks!

**Comment by justinpeterson13** [comment]
Got Plex working with iframe...but still no luck with Plex Auth.

**Comment by causefx** [comment]
just setup nginx on my windows 10 machine.  made a test user on my plex share, with password containing `$?!` and it worked perfect.

![image](https://user-images.githubusercontent.com/16184466/27248730-c3b3039c-52bc-11e7-9804-d24680129e4a.png)

**Comment by SgtBatten** [comment]
Just tried adding that to my conf file.

"upstream" directive is not allowed here in C:\Wnmp/conf/nginx.conf:186

I put it just above my other location blocks.

Guessing it goes somewhere specific.

**Comment by SgtBatten** [comment]
Okay, moved the upstream line out of the server block. Tick.

New error, could not find proxy.conf file. Realised I don't have one so I deleted that line.

Set Plex tab in or as /plexserver and turned off IFrame.

It now opens it Ina new tab but with my server url, nice.

Question.... This isn't going to cause extra traffic to go through my htpc if someone watches Plex on that link is it?

**Comment by causefx** [comment]
no, none extra

**Comment by justinpeterson13** [comment]
Okay, so I've fresh installed nginx and i'm still having the same issue. Does Org keep logs that I could look at to diagnose this?

**Comment by causefx** [comment]
would you mind sending me the url and sharing your plex with me?  I can see if i can log on...  just to test... if not that is okay to... we can chat via email - causefx at me dot com

**Comment by causefx** [comment]
for people googling this thread.  the problem was not having ca.curl info in php.ini
