### ISSUE TITLE
FR:  new activity count on tabs (like on android)

### ISSUE THREAD

**Issue by bbrunner11** [causefx/Organizr#392]
If eg, NZBGet is downloading something, I have no idea unless I click on the tab or click on the homepage.  Please add something to distinguish between inactive pages and active pages.  Thanks

**Comment by causefx** [comment]
i will look into something, maybe cross domain functionality.

**Comment by causefx** [comment]
Currently there is now way to do this.  I may look into using the api to do it.  Closing for now.
