### ISSUE TITLE
[FR] Chat: OTR Encryption

### ISSUE THREAD

**Issue by untotren** [causefx/Organizr#393]
I was going to implement an OTR, Onion chat server/client, but if you are including it perhaps we can look at this as an expansion.  Could you possibly make it XMPP compliant?

**Comment by causefx** [comment]
chat messages are encrypted.  AES-256-CBC

**Comment by untotren** [comment]
OTR?

**Comment by untotren** [comment]
What backend?  Because ideally I wanted to have it all via tor.

**Comment by untotren** [comment]
@causefx

**Comment by causefx** [comment]
Currently no plans to implement OTR protocol.  I will accept a PR for this though.
