### ISSUE TITLE
Update URL when navigated pages in iframe

### ISSUE THREAD

**Issue by Fma965** [causefx/Organizr#397]
I believe this is possible thanks to technologies in HTML5

https://gist.github.com/luisnomad/6595170#file-modify-the-url-without-reloading-the-page

Would be a great addition.

**Comment by Cerothen** [comment]
I am not quite sure what you are looking for? When you change the tab it adds a hash. The actual iframe urls have never pushed through to the header.

Also using the push/replace state commands only changes after the host. you cant change the actual host location.

**Comment by Fma965** [comment]
> I am not quite sure what you are looking for? When you change the tab it adds a hash. The actual iframe urls have never pushed through to the header.

This is what i'm suggesting. when i press F5 i forget its in a iframe and it refreshes the whole browser page meaning i then need to re-navigate to the page in organizr.

I've just tested this in the chrome console so now know it's definitely possible.
window.top.history.pushState("string", "Title", "https://www.google.co.uk/?gfe_rd=cr&ei=BNZIWf6_Cefv8AeJq7WYDA#q=hello");

So each time the contents of the iframe changes you could do this.

This is how facebooks image preview works, it opens in a popup without refreshing the whole content then updates the URL to match that popup

**Comment by Fma965** [comment]
A possible addon to this could be to do someting like 

/index.php?url=URL FROM IFRAME, so if i refresh the page it will still go to organizr and go directly back to the same page my iframe was on before refreshing. is this something that you would add? if so i can get a PR for this sorted.

**Comment by Fma965** [comment]
so after some failed attempts, this works.

```
var iframeurl;
setInterval(function(){
if (iframeurl != document.getElementById("leftiframe").contentWindow.location.href) {
iframeurl = document.getElementById("leftiframe").contentWindow.location.href;
window.top.history.pushState(null, null, iframeurl);
```

**Comment by causefx** [comment]
This was already done:
https://github.com/causefx/Organizr/blob/master/index.php#L1430
https://github.com/causefx/Organizr/blob/master/index.php#L1447

the lines are commented out right now, as we were testing some home page issues.  But if the problem you are having when you refresh, are you not using the refresh button on top right?

**Comment by Fma965** [comment]
Hi,

based on my understanding of that code that doesn't follow links that are clicked in the iframe though, it only gets the initial value from the iframe.

i don't use the refresh button often as i press F5 more than i use my mouse to refresh

**Comment by causefx** [comment]
I may revisit this soon, for now we will put this on the backburner.

**Comment by inonio** [comment]
This works well for me, for both multi-page and single page web apps. Put it in your custom JavaScript:
```
function iframeOnLoadEvent(iframe) {
  function updateTitle(title) {
    if (title === 'Plex') return; // plex is always 'Plex', better to just keep the title in the tab's config
    document.title = title + ' - My Website;
  }
  var iframeTitle = $(iframe).contents()[0].title;
  updateTitle(iframeTitle);

  var target = $(iframe).contents()[0].querySelector('title');
  var observer = new MutationObserver(function(mutations) {
    mutations.forEach(function(mutation) {
      updateTitle($(iframe).contents()[0].title);
    });
  });
  var config = {
    childList: true,
  };
  observer.observe(target, config);
}

$('.iFrame-listing iframe').on('load',function(e) {
  iframeOnLoadEvent(e.target);
});
$('.iFrame-listing').on('DOMNodeInserted', 'iframe', function(e) {
  $(e.target).on('load',function(ee) {
    iframeOnLoadEvent(ee.target);
  });
}); 
```

**Comment by causefx** [comment]
nice stuff.

one caveat is that this should only work on iframes with content from the same domain correct?

**Comment by inonio** [comment]
Same domain / reverse proxy. I have improved on this code, and added support for URLs. I'm testing it now. 

e.g, if you put this url in the browser:
www.yoursite.com/#Tab/some/path/?query=params#hash
It'll open Organizer on the tab and will navigate its iframe to
www.yoursite.com/tab_url/some/path/?query=params#hash

It'll also update the URL (and the title) in Organizr's main window when navigating the iframe / hitting back / forward (works on single / multi page apps).

If there's interest in it, I can share it. I don't want to create a PR as I'm not sure if it works with different organizer configurations other than mine (local tab URLs etc).
