### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by Ublala** [causefx/Organizr#399]
I've had Organizr up and running for months now. Today I decided to update but after the update I get the following error:

Fatal error: Uncaught PDOException: SQLSTATE[HY000]: General error: 1 no such column: order in C:\nginx\html\index.php:119 Stack trace: #0 C:\nginx\html\index.php(119): PDO->query('SELECT * FROM t...') #1 {main} thrown in C:\nginx\html\index.php on line 119

when I check it now says that sqlite3 is not installed:
![organizr_check](https://user-images.githubusercontent.com/24647877/27377001-03d4902a-5674-11e7-99ae-f01da29d4b19.jpg)

I've looked at other issues but those solutions do not seem to work for me. Any idea how I can get it up and running again?

**Comment by Ublala** [comment]
I've deleted everything and did a fresh install. Have everything set up again.

**Comment by causefx** [comment]
there was a slight error on and old version check, we couldn't nail it down.
