### ISSUE TITLE
[Feature Request] Add a failed logins log

### ISSUE THREAD

**Issue by Githubtordl** [causefx/Organizr#41]
Could you please add a failed logins log in settings? will be quite useful to see if anyone is being naughty.

**Comment by rix1337** [comment]
And even better, we could write a fail2ban filter for the login page!

http://www.fail2ban.org/wiki/index.php/Main_Page

+1

**Comment by causefx** [comment]
@rix1337 that would be awesome but Fail2Ban relies on Python.  Not sure everyone knows how to set that up.  we can have it as on option maybe.

**Comment by rix1337** [comment]
I phrased it wrong.

Assuming one has set up fail2ban already, if Organizr offered a log containing 

`timestamp - IP - bad auth`

We could write a fail2ban rule, that would work properly.

Look at how those configs work at: https://snippets.aktagon.com/snippets/554-how-to-secure-an-nginx-server-with-fail2ban

**Comment by causefx** [comment]
Ahhhh yes. :)

**Comment by causefx** [comment]
@rix1337 @Githubtordl 

I'm storing the info in a file on the server that is written in JSON.

Here is the preview:
![image](https://cloud.githubusercontent.com/assets/16184466/22119288/475ee584-de38-11e6-83c6-f894b0bc351e.png)

**Comment by rix1337** [comment]
Making the log path configurable would be perfect.

Looking very good so far, I guess we can easily set up a regex rule for fail2ban then!

**Comment by causefx** [comment]
Yea that is what I was thinking on both suggestions.

**Comment by rix1337** [comment]
This should work with fail2ban. Will test over the weekend:
https://gist.github.com/rix1337/d87b4b59200bcfe4efd2273d3991cb32

**Comment by rix1337** [comment]
I've just checked the fail2ban manual:
http://www.fail2ban.org/wiki/index.php/MANUAL_0_8#Filters

> In order for a log line to match your failregex, it actually has to match in two parts: the beginning of the line has to match a timestamp pattern or regex, and the remainder of the line has to match your failregex.

Any way you could (also) produce a standard log file more similar to the nginx one?

>20-01-2017 01:02:03 [1.2.3.4] "user" "bad_auth"

They do not offer a way to regex custom timestamps..

> The pattern or regex to match the time stamp is currently not documented, and not available for users to read or set

**Comment by causefx** [comment]
i can make the time stamp match this: 20-01-2017 01:02:03

**Comment by rix1337** [comment]
It's fail2ban that can't.. 
From what I've read fail2ban needs newlines beginning with the timestamp.. it offers no way to identify time by itself

**Comment by rix1337** [comment]
For some reason they allow identifying the host in logs with the <HOST> tag.. not the timestamp, however

**Comment by causefx** [comment]
hmmm
ok, i'll check this tonight

**Comment by rix1337** [comment]
I tried it right now, and fail2ban is not limited by the way the timestamp is offered, but it requires newlines.

Could you add a newline before every {"date" tag? as in:
https://gist.github.com/rix1337/d66f7d9a1c81d9345e37491e6084790c

The working bad_auth regex for fail2ban is
**```","username":"\S+","ip":"<HOST>","auth_type":"bad_auth"}```** 

```fail2ban-regex /config/organizr/loginLog.json '","username":"\S+","ip":"<HOST>","auth_type":"bad_auth"}'

Running tests
=============

Use   failregex line : ","username":"\S+","ip":"<HOST>","auth_type":"bad_...
Use         log file : /config/organizr/loginLog.json
Use         encoding : UTF-8


Results
=======

Failregex: 2 total
|-  #) [# of hits] regular expression
|   1) [2] ","username":"\S+","ip":"<HOST>","auth_type":"bad_auth"}
`-

Ignoreregex: 0 total

Date template hits:
|- [# of hits] date format
|  [5] Year(?P<_sep>[-/.])Month(?P=_sep)Day 24hour:Minute:Second(?:,Microseconds)?
`-

Lines: 6 lines, 0 ignored, 2 matched, 4 missed
[processed in 0.00 sec]

|- Missed line(s):
|  {"logType":"login_log","auth":[
|  {"date":"2017-01-20 00:18:07","username":"rix","ip":"21.43.5.6","auth_type":"good_auth"},
|  {"date":"2017-01-20 06:25:58","username":"rix","ip":"21.43.5.6","auth_type":"good_auth"},
|  {"date":"2017-01-20 09:42:30","username":"rix","ip":"21.43.5.6","auth_type":"good_auth"},
`-`
```

That would be all I need, and the json is still readable by organizr.

In contrast, the current json oneliner is not parsed correctly
```
fail2ban-regex /config/organizr/loginLog.json '","username":"\S+","ip":"<HOST>","auth_type":"bad_auth"}'

Running tests
=============

Use   failregex line : ","username":"\S+","ip":"<HOST>","auth_type":"bad_...
Use         log file : /config/organizr/loginLog.json
Use         encoding : UTF-8


Results
=======

Failregex: 1 total
|-  #) [# of hits] regular expression
|   1) [1] ","username":"\S+","ip":"<HOST>","auth_type":"bad_auth"}
`-

Ignoreregex: 0 total

Date template hits:
|- [# of hits] date format
|  [1] Year(?P<_sep>[-/.])Month(?P=_sep)Day 24hour:Minute:Second(?:,Microseconds)?
`-

Lines: 1 lines, 0 ignored, 1 matched, 0 missed
[processed in 0.00 sec]
```

**Comment by causefx** [comment]
by new line, do you mean like a break in line?

**Comment by rix1337** [comment]
yeah! instead of 

>foo bar spam eggs

>foo
>bar
>spam
>eggs

sorry, english is not my primary language ^^

**Comment by causefx** [comment]
no worries, I can try that out tonight unless you want to edit yourself and try.

**Comment by rix1337** [comment]
I'll give it a shot. and thank you

**Comment by causefx** [comment]
lemme give you the line.

**Comment by rix1337** [comment]
user php, 602?

**Comment by causefx** [comment]
https://github.com/causefx/Organizr/blob/master/user.php#L610

change to `$writeFailLog = json_encode($gotFailLog, JSON_PRETTY_PRINT);`

https://github.com/causefx/Organizr/blob/master/user.php#L614

change to `$writeFailLog = json_encode($failLogEntryFirst,  JSON_PRETTY_PRINT);`

**Comment by rix1337** [comment]
ill give it a shot, though i am only familiar to xml. seems easy to get the format, though.

**Comment by causefx** [comment]
no worries man :) let me know how it goes.

**Comment by rix1337** [comment]
I tried my best, and the PR works for the front-end, as well as the fail2ban log daemon.

I really would like this functionality implemented (even if a proper log file, not breaking the json would be the better way). With this hack I am now successfully banning people after their third bad login attempt to my site!

**Comment by causefx** [comment]
nice, did the JSON_PRETTY_PRINT not work either?

**Comment by rix1337** [comment]
No, not really.

I know duplicate file creations make this project less clean, but could you just implement a function that on a bad login appended

Timestamp - [ip] - [username] - bad auth

to a simple somthing.log? I would really feel bad about the hack I wrote, just to get this feature going. Even though it works

**Comment by causefx** [comment]
the hack isnt bad.

**Comment by rix1337** [comment]
thank you,

> nice, did the JSON_PRETTY_PRINT not work either?
> 
> Edit: Also this line doesn't need to be edited: $getFailLog = str_replace("\r\ndate", "date", file_get_contents(FAIL_LOG));
> 
> as you already apply str_replace on the variable than encodes the json.
> 
> Edit: Nevermind, i misread that line.

At first i thought so, too. New log entrys will go missing without it, though..

**Comment by causefx** [comment]
what do you mean?

**Comment by rix1337** [comment]
nvm, was just confirming the line needs an edit 👍

**Comment by causefx** [comment]
ahhh yes, I need to see if my local hosted dev branch is updated, if it is i will pull this merge request into dev.

**Comment by rix1337** [comment]
cool stuff. i contributed 🥇  😄

**Comment by causefx** [comment]
haha yes sir, thanks!

**Comment by rix1337** [comment]
just a heads up: the reformated log file may cause issues with existing logs from this version..

since it's beta this should be fine..

**Comment by causefx** [comment]
Hmmmm. I'll take a look.
