### ISSUE TITLE
[Feature request] go directly to a tab

### ISSUE THREAD

**Issue by benbar21** [causefx/Organizr#42]
Sorry if I explain this poorly!

Say I have two tabs: Plex and Ombi. Plex is the default tab. It'd be great if I could somehow go directly to Ombi by going to domain.com/ombi or domain.com#ombi, for example. 

I'm not sure how hard this'd be to add, but it would be really useful!

**Comment by SgtBatten** [comment]
You can do this outside of Organizr.
If you only have 2 tabs and don't want to have to click the one button to swap tabs then you probably don't need Organizr.

Lets face it though. It's less 'clicks' to load the dafault page and then click the tab then to type out /ombi

**Comment by causefx** [comment]
I think i'll be able to add this in, might require rewriting a few things but do-able.

**Comment by benbar21** [comment]
@SgtBatten I know I can do it outside of Organizr, but I have 8 tabs right now, and it'd just be nice to be able to go 'sonarr.domain.com' and still have the benefits of Organizr. Plus it'd be far simpler for the people I share it with to be able to do this, I assume at least.

@causefx  Great! Let me know if you want me to help test it sometime.

**Comment by SgtBatten** [comment]
Sorry man. You initial post hinted you only had 2 tabs.

I have 8 as well although I only share 2 with anyone else. They don't need sonarr or SAB or plexpy etc, just Plex and ombi. Works for me but I know that's not for everyone.

Also worth noting for inexperienced users having one url to type/ favourote / remember is simpler.

Glad cause might be able to help you in any case. GL.

**Comment by benbar21** [comment]
@SgtBatten No problem. I was just trying to explain what I meant, haha. I also only share 2 with anyone else, with both also being Plex and Ombi!

I just know that my Dad likes to bookmark stuff, and so it would be great if he could have one bookmark that goes to plex on organizr and one that goes to ombi on organizr. Hopefully this'll also help others too!

**Comment by causefx** [comment]
this is already done. :)  I'll push the commit sometime today.

**Comment by benbar21** [comment]
Hey,

The latest update broke this! If you could fix it it'd be great :)

**Comment by causefx** [comment]
can you send screenshot of console, it works fine on my end.

**Comment by benbar21** [comment]
is there any way to send you a pm? I could just give you the link to it and the admin account, since the console seems to be showing nothing relevant?

**Comment by causefx** [comment]
Causefx at me dot com

**Comment by benbar21** [comment]
Related to this, would it be possible to have it so when you click on a specific tab the address bar changes? So if I go to domain.com#nzbget and then click on couchpotato it switches to domain.com#couchpotato? If this is difficult to do it isn't worth it as functionally it isn't an issue, but if it's an easy change it'd be nice to have the address bar reflect what tab is open!
