### ISSUE TITLE
Fatal error: Uncaught PDOException: SQLSTATE[HY000]: line 138

### ISSUE THREAD

**Issue by phairplay** [causefx/Organizr#420]
hi 
im trying to install i get the registration page and when hit the button i get this message 

Fatal error: Uncaught PDOException: SQLSTATE[HY000]: General error: 1 no such column: order in C:\nginx-1.8.0\html\index.php:138 Stack trace: #0 C:\nginx-1.8.0\html\index.php(138): PDO->query('SELECT * FROM t...') #1 {main} thrown in C:\nginx-1.8.0\html\index.php on line 138

**Comment by causefx** [comment]
is this on a new install?

**Comment by phairplay** [comment]
Yes it is.
I moved the user db to the html folder with Organizr in and all it good.

Also my HTPC page fits perfectly in IFrame :+1:  :+1: 

Great work fella it looks amazing

**Comment by causefx** [comment]
:)
