### ISSUE TITLE
Looking for guidance on URLs for services on tabs

### ISSUE THREAD

**Issue by SlothCroissant** [causefx/Organizr#421]
#Hi team! I've got a situation I could use some guidance on.

I've got my services set up behind a single domain `url.com`, with a wildcard cert set up to sit behind it all. Nginx currently reverse proxies everything so users access services at `plex.url.com`, `plexpy.url.com`, `sonarr.url.com`, etc. Nginx handles HTTP>HTTPS redirection as well, if it matters (see conf below).

I'd like organizr to sit at `web.url.com`, and have created the reverse proxy in my existing nginx configuration. When I go to add the URLs in the tab config page of organizr, I'm never able to load the tabs.

- `https://plex.url.com` yeilds a `401 unauthorized` and a `(failed) net::ERR_BLOCKED_BY_RESPONSE`
- `https://plex.url.com/web/index.html` yields `(failed) net::ERR_BLOCKED_BY_RESPONSE`
- `http://10.0.1.4:32400/web/` throws `blocked:mixed-content`. Throwing /index.html in there doesn't change the result. 

Any thoughts would be most appreciated!

Here is an example of my `plex.conf` in nginx:
```
server {
  listen *:80;
  server_name plex.url.com;
  return 302 https://plex.url.com$request_uri;
}

server {
  listen *:443 ssl;
  server_name plex.url.com;

  ssl_certificate /etc/nginx/keys/url_tv.pem;
  ssl_certificate_key /etc/nginx/keys/url_tv.key;

  ssl on;
  ssl_protocols  TLSv1 TLSv1.1 TLSv1.2;
  ssl_ciphers 'ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-DSS-AES128-GCM-SHA256:kEDH+AESGCM:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-DSS-AES128-SHA256:DHE-RSA-AES256-SHA256:DHE-DSS-AES256-SHA:DHE-RSA-AES256-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:AES:CAMELLIA:DES-CBC3-SHA:!aNULL:!eNULL:!EXPORT:!DES:!RC4:!MD5:!PSK:!aECDH:!EDH-DSS-DES-CBC3-SHA:!EDH-RSA-DES-CBC3-SHA:!KRB5-DES-CBC4-SHA';
  ssl_prefer_server_ciphers on;
  ssl_dhparam /etc/nginx/keys/dhparams.pem;

  add_header X-Frame-Options SAMEORIGIN;
  add_header X-XSS-Protection "1; mode=block";
  add_header Strict-Transport-Security "max-age=31536000; includeSubdomains";

  location / {
    	proxy_pass http://10.0.1.4:32400;
		proxy_set_header Host $http_host;
		proxy_set_header X-Real-IP $remote_addr;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  }
}
```

**Comment by causefx** [comment]
you have two options"

1.  Change `add_header X-Frame-Options SAMEORIGIN;` to `add_header X-Frame-Options ALLOW-FROM https://web.domain.com;` but this doesn't work on chrome.
2.  Change the above line to `proxy_hide_header X-Frame-Options;`

**Comment by SlothCroissant** [comment]
Top notch work, thanks!

Did option 2 above, everything works like a charm now. Thanks for the assistance!

**Comment by causefx** [comment]
awesome!  :)
