### ISSUE TITLE
Install Issues (PHP Service)

### ISSUE THREAD

**Issue by Kinematic9** [causefx/Organizr#422]
Hi - I am going through the install guide and am currently having issues with the PHP install. NGINX installed properly and is set as a service through NSSM but when I get to starting the PHP service, I receive this:

![untitled](https://user-images.githubusercontent.com/26988920/27517936-bc0274c4-59a2-11e7-8851-e89536e332bc.png)

I can't get a specific error out of this (it is not the VCRUNTIME mentioned) but have not gone past this point. Any ideas? Thanks!

**Comment by causefx** [comment]
can you maybe start cmd as admin?

**Comment by Kinematic9** [comment]
I can't do that either - this is the response (it says it's running, but running means paused in the services.msc). Tried restarting as well - NGINX is perfectly fine along with sonarr,radarr, ombi and plexpy.

![untitled](https://user-images.githubusercontent.com/26988920/27518012-2b3c43e6-59a4-11e7-9386-d413729fdcf5.png)

**Comment by causefx** [comment]
can you post the values of the nssm editor?

**Comment by causefx** [comment]
also di you try running `php-cgi.exe` manually?

**Comment by Kinematic9** [comment]
I could not run it directly and will post when I am back tonight. Running
direct would just hang a cmd box. Thanks for help, will update shortly.

**Comment by elmerfdz** [comment]
Not sure, if you've already done the following:

Grab the latest pre-release build of NSSM https://nssm.cc/build, move the nssm file to the appropriate folder and run the following command against your PHP service `nssm set php AppNoConsole 1`

**Comment by elmerfdz** [comment]
If the above doesn't work could you edit the php service via nssm and post a screenshot of the application tab.

**Comment by Kinematic9** [comment]
It looks like the nssm set php appnoconsole command again helped, I did not change anything but tried again when I got home and I have everything up and running now, services all start automatically. Thanks for your help, sorry for the inconvenience.
