### ISSUE TITLE
Better logging/debug

### ISSUE THREAD

**Issue by si0972** [causefx/Organizr#423]
Been trying to add plex to homepage, but the best i can do is : **Could not load!**
Better logging or help would be appreciated.

**Comment by causefx** [comment]
by any chance are you using https in homepage settings for plex?

**Comment by si0972** [comment]
Been trying both, everything else goes trough https

**Comment by si0972** [comment]
https://pastebin.com/RHwRc85B i get this when i use the same adress like my plex-tab

**Comment by causefx** [comment]
can you goto check.php is everything green?

**Comment by causefx** [comment]
also is plex running on name machine or same network as your webserver?

**Comment by si0972** [comment]
I got it working just as you replied. plex suddenly didnt like my manual port, turned that off, and used the port it choose. now it works, probably gonna be broken when plex chooses another port.

**Comment by causefx** [comment]
so its 32400 now?

**Comment by si0972** [comment]
No, 18703, the port it choose for public.
my setup is dockerbased, plex running in official docker, and organizr in a letsencrypt nginx docker.

**Comment by causefx** [comment]
ahhh... and the url you put in, the local ip or external?

**Comment by si0972** [comment]
all external, just edited from domain.com:ManualPort to domain.com:PortPlexChoose

**Comment by causefx** [comment]
if you dont mind, can you test localip:manualport

sorry man, thank you for bringing this up.

**Comment by si0972** [comment]
Cheeky little trick :)
tried it before posting, i had to add http:/ infront, maybe add that to the discription field for Plex URL.

**Comment by causefx** [comment]
awesome!  thank you.
