### ISSUE TITLE
plex homepage url patern to 'aggressive'

### ISSUE THREAD

**Issue by DeveloperForge** [causefx/Organizr#424]
the URL setting for the Plex homepage won't allow for reverse proxy setups.
 eg.
"remote access" is disabled in Plex
reverse proxy setup to proxy all requests to 127.0.0.1:32400 on ports 80/443
access URL is something like https://plex.hostname.tld/

**Comment by causefx** [comment]
just dont put the trailing `/`

**Comment by DeveloperForge** [comment]
the first time i tried it was red the entire time i typed it, weird....seems to work fine.
