### ISSUE TITLE
[Feature Request] Stay in current tab post-refresh

### ISSUE THREAD

**Issue by benbar21** [causefx/Organizr#43]
This might go against your image for Organizr, but it would be great (in my opinion) if when I refresh Organizr it doesn't go back to the default tab (unless I am already on the default tab)

Let me know if you need any further explanation!

**Comment by SgtBatten** [comment]
Use the Organizr refresh button and this is exactly what it does do. Don't use your browser refresh

**Comment by causefx** [comment]
@SgtBatten is correct, unless you are trying to refresh the main page for some reason... if so, can you explain why you are needing to refresh the entire page and not just the current tab.

**Comment by benbar21** [comment]
@causefx Nevermind! I didn't notice the refresh button.

**Comment by causefx** [comment]
Ahhh no worries.
