### ISSUE TITLE
Homepage hangs if Plex server is offline. 

### ISSUE THREAD

**Issue by escservices** [causefx/Organizr#437]
Is there anyway for the homepage to still load if the server is down, that way my users can still check it for updates on the server.  For instance I might put up a message saying server reboot in progress but they can't see it because the site never loads.  Also I found it difficult to even load the settings page using the /#settings option when the server is down.  Maybe you can even turn this into a new feature where if it doesn't load you can have a status area saying it's down on the homepage.  Thanks, and great work!

**Comment by causefx** [comment]
i will look into checking the services.

**Comment by causefx** [comment]
Added in 6527471
