### ISSUE TITLE
unable to open file

### ISSUE THREAD

**Issue by kaplannn** [causefx/Organizr#438]
I am getting this error after i specified the database:

"Fatal error: Uncaught PDOException: SQLSTATE[HY000] [14] unable to open database file in /var/www/html/Organizr/user.php:171 Stack trace: #0 /var/www/html/Organizr/user.php(171): PDO->__construct('sqlite:/opt/org...') #1 /var/www/html/Organizr/index.php(70): User->__construct('registration_ca...') #2 {main} thrown in /var/www/html/Organizr/user.php on line 171"

I have read in the wiki about this issue. So i tried to get the right permissions. I changed it to www-data:www-data, root:root,  but nothing seems to work.

Could you guys maybe help me with that?

i also tried to do chmod 777, just in case....

Greets :)

**Comment by causefx** [comment]
goto check.php

see that the persmissions say there.  Also what OS are you running?

and last, create a test php file with this code:

```
<?php

echo 'Current webserver user: ' . getenv('USER');

```
Let me know what the output is.

**Comment by kaplannn** [comment]
I am using Ubuntu 16.04

check.php says that:

![image](https://user-images.githubusercontent.com/17184697/27673157-70200260-5c9f-11e7-9399-a4787b953538.png)

this is the only red thing.

My user is: www-data

![image](https://user-images.githubusercontent.com/17184697/27673195-9e2ba2f4-5c9f-11e7-90da-959e4acbf685.png)

Linux Permissions on the Folder:

![image](https://user-images.githubusercontent.com/17184697/27673209-aea258ee-5c9f-11e7-8e84-dec1dc02da06.png)


Is it because of the zip? strange due to i have installed zip....

Thanks and Greetings :)

**Comment by kaplannn** [comment]
fuck me... i installed the wrong zip. now everything is green when i am accessing check.php but i still get the error:

Fatal error: Uncaught PDOException: SQLSTATE[HY000] [14] unable to open database file in /var/www/html/Organizr/user.php:171 Stack trace: #0 /var/www/html/Organizr/user.php(171): PDO->__construct('sqlite:/opt/org...') #1 /var/www/html/Organizr/index.php(70): User->__construct('registration_ca...') #2 {main} thrown in /var/www/html/Organizr/user.php on line 171

**Comment by causefx** [comment]
can you also do `sudo chown -R www-data:www-data /var/www/html`

**Comment by kaplannn** [comment]
i did that already.. still not working ):

**Comment by causefx** [comment]
can u `ls -l` both /var/www/html & /var/www/html/Organizr please and post output

**Comment by causefx** [comment]
anything?

**Comment by kaplannn** [comment]
sorry i was on holidays...

for /var/www/html:

![image](https://user-images.githubusercontent.com/17184697/28287838-651c5e7a-6b3d-11e7-915a-77f27651319f.png)

for /var/www/html/Organizr:

![image](https://user-images.githubusercontent.com/17184697/28287867-76e39402-6b3d-11e7-8503-baefc69ea801.png)

**Comment by causefx** [comment]
actually i see the problem now, you specified /opt/organizr or something for DB location.  can you make sure that folder is readable and writable by www-data

**Comment by kaplannn** [comment]
ohh that did it! changed /opt/organizr to www-data as the owner.

thank you very much :)

**Comment by causefx** [comment]
:)
