### ISSUE TITLE
Cannot create admin

### ISSUE THREAD

**Issue by tidusjar** [causefx/Organizr#44]
So i'm on the screen after providing a database location and I cannot create an admin user.

I fill in the username, email and both passwords, press the register button and nothing happens.

Nothing in the console, no requests are being sent when pressing register 😢

**Comment by tidusjar** [comment]
Pressing enter works fine after tabbing to the Register button, but clicking doesnt...

**Comment by causefx** [comment]
Crap... haha thanks for the heads up.... how do u like it so far?

**Comment by tidusjar** [comment]
I like it! Yeah, looks good, 
I have no uses for the multiple users thing but it's cool.

I like your styling, could use your ability in Ombi! haha.

**Comment by causefx** [comment]
@tidusjar LOL, let me know if you need help with anything :)

**Comment by tidusjar** [comment]
Hey, i'd like your input on Ombi, Some of the area's are real rough.... Whenever you get time 😄

**Comment by causefx** [comment]
sure, hit me up on email.... causefx at me dot com
