### ISSUE TITLE
Enable "Open in new Window" on mobile

### ISSUE THREAD

**Issue by rix1337** [causefx/Organizr#441]
Could we enable the "open in own window" button for the mobile layout? Plex (and others) dont work inside an iframe on my phone. Ideally on a per-tab basis.

**Comment by rix1337** [comment]
see https://github.com/causefx/Organizr/issues/11

**Comment by causefx** [comment]
i can do that but it wont be much space lol

**Comment by rix1337** [comment]
I know .. I am just desperate 🤣

**Comment by rix1337** [comment]
The recent update brought a dysfunctional "close second view" button. Should that have been the "open in new window" one

**Comment by causefx** [comment]
i forgot about this one.  also the "X" doesnt work for you on closing the frame?
