### ISSUE TITLE
Homepage Crashes Organizr

### ISSUE THREAD

**Issue by pavili0n** [causefx/Organizr#442]
I posted this a while back but I decided to just turn off the homepage and deal with it - after the recent updates I really want to begin using it. Currently I cannot browse to admin.mysite.com which is where Organizr sits but I can browse to admin.mysite.com/sabnzbd etc.

If I restart my web server it comes back for a couple of hours. If I turn off the homepage it doesn't break. 

Please can you let me know where I would begin diagnosing this issue.

**Comment by causefx** [comment]
What webserver and OS?

**Comment by pavili0n** [comment]
Running CaddyServer and on Windows 10

**Comment by causefx** [comment]
https://github.com/causefx/Organizr/issues/390 try the fixes in this thread please.
