### ISSUE TITLE
Download Speed and time remaining with NZBget panel on HomePage

### ISSUE THREAD

**Issue by jwestan** [causefx/Organizr#451]
Not sure this is the same as issue #75 but would like to see if it is possible to add the download speed and time remaining to the NZBget panel on the Homepage?

**Comment by causefx** [comment]
API doesn't have this info in listgroups....

:(

**Comment by poornachandratejasvi** [comment]
do we have any update on having the download speed and remaining time in 2021

**Comment by causefx** [comment]
i can check again if I can get someones API to test
