### ISSUE TITLE
error /path/to/downloaded/cacert.pem in php.ini

### ISSUE THREAD

**Issue by blackley** [causefx/Organizr#452]
I am getting this error reported in the logs - "error occured logging into plex might want to check curl.cainfo=/path/to/downloaded/cacert.pem in php.ini"

How and where do I fix this, please?

**Comment by causefx** [comment]
What OS and webserver?

Also, is the plex login not working?

I have edited this error on the new version coming out soon.

**Comment by blackley** [comment]
Plex login appears to be working - i am getting content from plex on the homepage.

OS is Ubuntu 17.04
WS is Nginx

**Comment by blackley** [comment]
FYI i have never seen any calendar content on the homepage no matter what i have done - don't know if this information is helpful?

**Comment by LastStarFighter** [comment]
This is might be a TLS issue with curl when it's trying to grab user credentials using Plex Auth and not being able to verify the certificate provided by the server since it can't find/access the local root store.

**Comment by causefx** [comment]
the calendar is populated with sonarr, radarr, sickrage and headphones.  

As for the homepage that doesnt use the plex login, it only uses the token.

**Comment by that1guy** [comment]
I am also incurring the error `error occured logging into plex might want to check curl.cainfo=/path/to/downloaded/cacert.pem in php.ini`

![image](https://user-images.githubusercontent.com/1218940/27850711-49c7fa44-610b-11e7-82e7-0cd35d395fb8.png)

I'm running the x64 Docker by LinuxServer.io container which runs version `1.38` of Organizr.

When I exec into this docker container I find one `php.ini` file at `/etc/php7/php.ini` and in there I see the following curl configs

```
[curl]
; A default value for the CURLOPT_CAINFO option. This is required to be an
; absolute path.
;curl.cainfo =
```

I'm not sure what I'm supposed to do from here to resolve this issue.  Thanks for next steps @causefx!  Organizr is amazing!
