### ISSUE TITLE
error /path/to/downloaded/cacert.pem in php.ini

### ISSUE THREAD

**Issue by that1guy** [causefx/Organizr#455]
FYI: Related to **closed** ticket: https://github.com/causefx/Organizr/issues/452

I am incurring the error `error occured logging into plex might want to check curl.cainfo=/path/to/downloaded/cacert.pem in php.ini`

![image](https://user-images.githubusercontent.com/1218940/27850711-49c7fa44-610b-11e7-82e7-0cd35d395fb8.png)

I'm running the x64 Docker by LinuxServer.io container which runs version `1.38` of Organizr.

When I exec into this docker container I find one `php.ini` file at `/etc/php7/php.ini` and in there I see the following curl configs

```
[curl]
; A default value for the CURLOPT_CAINFO option. This is required to be an
; absolute path.
;curl.cainfo =
```

I'm not sure what I'm supposed to do from here to resolve this issue.  Thanks for next steps @causefx!  Organizr is amazing!

**Comment by causefx** [comment]
can you curl -I your plex url with token?

**Comment by that1guy** [comment]
Seems to be working.

![image](https://user-images.githubusercontent.com/1218940/27895438-a4774a32-61c7-11e7-95e4-9fad32d7e1df.png)

This is the same plex token in Organizr settings here:

![image](https://user-images.githubusercontent.com/1218940/27895482-ec68048a-61c7-11e7-938f-7cc34347cfc1.png)

**Comment by causefx** [comment]
i'll be pushing an update that will give a better error message

we will narrow it down

**Comment by that1guy** [comment]
Np! I'll wait here for next steps.  Happy to help narrow things down. Cheers!

**Comment by causefx** [comment]
update is live, can you test now?

**Comment by that1guy** [comment]
Updated to 1.4.0 and still seeing same issue.  I even created a new plex.tv account with another test email and shared my server with that new account and then tried to sign in with a second test account.  I'm seeing different errors though.  I'm not typing in my username/password incorrectly I've quadruple checked myself.

```
organizr node 2017-07-07 20:02:53|error|email@example.com is not an authorized user or entered invalid password
organizr node 2017-07-07 20:02:53|error|email@example.com tried to sign-in with the wrong password
```

**Comment by that1guy** [comment]
Whats curious though is that another user that I recently invited signed in perfectly today.  I have no idea why it worked for him as both of my test accounts still wont let me in so that I can experience what my users experience.

**Comment by causefx** [comment]
let me make a plex acct that has an email address as username, that might be it.

**Comment by that1guy** [comment]
@causefx the test accounts I created had an email address associated with them (plex.tv requires this) but the username itself was never an email address.  I created a new user and documented things for you just to be crystal clear.

1) Create a new plex.tv user.
![image](https://user-images.githubusercontent.com/1218940/27997357-8381ca1e-64ab-11e7-9979-4592823a1cba.png)

2) Share my plex server with that new user
![image](https://user-images.githubusercontent.com/1218940/27997371-c14ee872-64ab-11e7-92ad-5495ff18ffd3.png)

3) Confirm the test user has access to my Plex server
![image](https://user-images.githubusercontent.com/1218940/27997416-6dea9432-64ac-11e7-9fee-dd2d0633f3bc.png)

4) Test user tries to log in to Organizr using email address
![image](https://user-images.githubusercontent.com/1218940/27997440-eb0367c8-64ac-11e7-845f-d79117a6cd65.png)


5) Test user tries to log in to Organizr user plex username
![image](https://user-images.githubusercontent.com/1218940/27997445-16ba9d64-64ad-11e7-9252-74a216ee8327.png)


6) Logs exposed in Organzr UI
![image](https://user-images.githubusercontent.com/1218940/27997477-ac8661fc-64ad-11e7-8bc0-35e782e9c039.png)

**Comment by causefx** [comment]
what do org logs say?

**Comment by that1guy** [comment]
Not sure I know which logs you're asking for.  Which log file do you want me to tail?  I can report back with that.

**Comment by causefx** [comment]
under logs, there is button on top left, [Organizr Log] click that

**Comment by that1guy** [comment]
Here you go.. I created a bunch of different plex tv account to test many different scenarios.. No luck.

![image](https://user-images.githubusercontent.com/1218940/27997781-5debfc1c-64b4-11e7-86e4-58d77b599c5a.png)

![image](https://user-images.githubusercontent.com/1218940/27997800-99edb66a-64b4-11e7-8110-3f924f7ef50c.png)

**Comment by causefx** [comment]
do the passwords have any special characters?

**Comment by that1guy** [comment]
Nope.  At one point I had a test account whose password had a `0` in it.  But in the many tests I've conducted I've used extremely simple passwords.

**Comment by causefx** [comment]
this is really odd.

can you try `curl -I https://plex.tv/pms/friends/all`

**Comment by causefx** [comment]
also, edit functions.php

```
		//Get User List
		$userURL = 'https://plex.tv/pms/friends/all';
		$userHeaders = array(
			'Authorization' => 'Basic '.base64_encode(PLEXUSERNAME.':'.PLEXPASSWORD), 
		);
		$userXML = simplexml_load_string(curl_get($userURL, $userHeaders));
		prettyPrint($userXML);//NEW LINE
		die();//NEW LINE
```

Add those two lines... try signing in with accts, let me know the output

**Comment by that1guy** [comment]
```
root@a7d4b7cb0205:/$ curl -I https://plex.tv/pms/friends/all?X-Plex-Token=my_plex_token
HTTP/1.1 200 OK
Cache-Control: no-cache
Content-Type: application/xml; charset=utf-8
Date: Wed, 12 Jul 2017 01:50:34 GMT
Server: nginx
Set-Cookie: _mkra_ctxt=96d93a5522c37d822385582e305c622d--200; path=/; max-age=5; secure
Status: 200 OK
Vary: Origin
X-Content-Type-Options: nosniff
X-Frame-Options: DENY
X-Plex-Container-Start: 0
X-Plex-Container-Total-Size: 15
X-Request-Id: e7ea30aa-3f17-472d-aed8-9519016b723b
X-Runtime: 0.186571
X-UA-Compatible: chrome=1
X-XSS-Protection: 1; mode=block
Connection: keep-alive
```

After editing functions.php I got this error

```
SimpleXMLElement Object
(
    [error] => Invalid email, username, or password.
)
```

I then went to config.php to see what password was stored in there and the password was jibberish.  It was not my password that I had entered.  Whats interesting is that I've been seeing the same thing happen for my `nzbgetPassword` and `cookiePassword`.  Intermittently they keep changing to jibberish (maybe base64 encoded?  I'll check this next time a password changes).

Anywho, that was the issue.  My `plexPassword` was incorrect and I think something is causing my passwords to change from time to time.  Any ideas what is causing this?

**Comment by causefx** [comment]
are you using any password managers?  extensions?

**Comment by that1guy** [comment]
Actually yes!  1Password.  And it's dialog box does pop up quite often when
I submit forms in Organizr.

**Comment by causefx** [comment]
can you ignore certain boxes?

**Comment by that1guy** [comment]
I can ignore certain domains and I've done this now to see if the issue with passwords resetting continues.  keep you posted.  Closing this ticket for now.  Thanks Cause.
