### ISSUE TITLE
Radarr Icon

### ISSUE THREAD

**Issue by SlackMaster** [causefx/Organizr#46]
Hello,

Can you please add an icon for Radarr? It's a fork of Sonarr being developed for movies. Looks very promising.

https://github.com/Radarr/Radarr

**Comment by SlackMaster** [comment]
They have their own icon.

![128](https://cloud.githubusercontent.com/assets/353988/22042110/c2ea2f4a-dcd7-11e6-9af6-07eb730a11d6.png)

**Comment by causefx** [comment]
sweet!  I'll add it.  Thanks!
