### ISSUE TITLE
SMTP logs

### ISSUE THREAD

**Issue by that1guy** [causefx/Organizr#470]
I'm testing reset password functionality and I don't receive any emails from organizr.  Below are my email settings (same credentials I'm using in Sonarr and Radarr, btw).  How do I tail logs to see what SMTP error Organizr is experiencing?

```
smtpHost = "smtp.gmail.com"
smtpHostPort = "587"
smtpHostUsername = "email@mydomain.com"
smtpHostPassword = "Password"
smtpHostSenderName = "Organizr"
smtpHostSenderEmail = "organizr@mydomain.com"
smtpAuthType = SSL

Toggle Switches
SMTP Auth = enabled
Enable Mail = enabled
```

![image](https://user-images.githubusercontent.com/1218940/27982276-32748dae-6353-11e7-833f-fc939ce27670.png)

**Comment by causefx** [comment]
port 587 is for TLS

**Comment by si0972** [comment]
The SMTP aut is done with [this project.](https://github.com/PHPMailer/PHPMailer) Have a look at their [Wiki](https://github.com/PHPMailer/PHPMailer/wiki/SMTP-Debugging), once you enabled logging(SMTPDebug = 2), they appear on screen when you send a mail (like creating a user).

**Comment by that1guy** [comment]
@causefx @si0972 Thank you both.  I enabled `SMTPDebug' and learned that SSL auth simply doesn't work with my gmail account (not sure why) so I firmly stayed on port `587` switched to TLS  and everything began working.  Enabling logs really helped me.  Cheers.

**Comment by si0972** [comment]
@that1guy Yea, i was strugeling with that too, needed that debug myself. I think Cause would appriciate if you would close the issue. :)

**Comment by that1guy** [comment]
@si0972 yep, sorry.  Closing issue!
