### ISSUE TITLE
Closing a second page closes the 1st instead.

### ISSUE THREAD

**Issue by firedomain** [causefx/Organizr#475]
When i try to close the 2nd (right) page using the "X" icon after opening a second page with right click it closes the 1st page instead & leaves the 2nd page stuck on the right causing me to refresh the site to remove it.

v1.40

**Comment by richowen** [comment]
same here. firefox, chrome and Edge, org 1.4 [https://i.gyazo.com/2c67069e2a0f56280e0280d9f240a436.mp4](url)

**Comment by causefx** [comment]
the actions have changed, sorry I should have been more clear.

Left click closes left/main tab - Right click closes right tab.

**Comment by firedomain** [comment]
Oh, ok. In that case, left clicking clears the left page but leaves the left column open. I would assume the intention was to close the left column & expand the right/secondary column to become the primary window?
Either way, thanks for all the work!

**Comment by causefx** [comment]
Yea for now it just closes the tab.  I will look into expanding the right side but I really dont see the functionality.  either way thanks for bringing it up :)
