### ISSUE TITLE
Calendars stop working after login.

### ISSUE THREAD

**Issue by si0972** [causefx/Organizr#476]
I managed to get my calendars up and working, but they disapear when any user login. I have been playing with different aut. levels, but they will only show before login.

**Comment by causefx** [comment]
what auth level is radarr/sonarr?

**Comment by si0972** [comment]
I have tested different settings, now i have sonarr on none, and radarr on user. I ran with both on user and admin and i still got nothing.

**Comment by causefx** [comment]
can you email me the URL?  causefx at me dot come

**Comment by si0972** [comment]
Sent

**Comment by si0972** [comment]
Changing to develop worked. Thanks.

**Comment by causefx** [comment]
check org logs to see error too :)
