### ISSUE TITLE
Replace use of Plex Tokens

### ISSUE THREAD

**Issue by nemchik** [causefx/Organizr#479]
As noted on the [page](https://support.plex.tv/hc/en-us/articles/204059436-Finding-an-authentication-token-X-Plex-Token) where the Plex homepage settings prompts for a token, the tokens are temporary and there is a different way that Plex intends for apps to obtain a token.

Would it be possible for you to switch Organizr to the preferred method of obtaining tokens?

**Comment by causefx** [comment]
you'd rather us generate one?

**Comment by nemchik** [comment]
That seems to be how Ombi and PlexPy get their tokens. I'm not sure if this is better or worse, but at least that Plex wiki recommends it as opposed to fishing out a token from the XML.

**Comment by causefx** [comment]
no problem, i just coded it all now :)

![image](https://user-images.githubusercontent.com/16184466/28043597-78345bfe-6587-11e7-98ec-d745df2e3213.png)

**Comment by nemchik** [comment]
Damn you're good!

**Comment by causefx** [comment]
still have a few things to do, but hopefully release tomorrow.
