### ISSUE TITLE
Constantly shown how to add to homescreen.

### ISSUE THREAD

**Issue by SgtBatten** [causefx/Organizr#48]
This pop-up seem to appear each time I visit the page. I have added it to my homescreen already but it still appears and I have to click x to close it.

**Comment by causefx** [comment]
since you have added it to homescreen, are you going thru safari or clicking the new homescreen icon?

**Comment by rix1337** [comment]
It's always there after login on chrome mobile

**Comment by SgtBatten** [comment]
It happens in both cases. Using the homescreen icon or going to the url directly.

I am using Chrome on android

**Comment by causefx** [comment]
Crap. I just asked my buddy to try it and yup it keeps doing it. Just switch to iPhone haha. Jk. I will work on this today.

**Comment by causefx** [comment]
@SgtBatten  @rix1337 

let me asks you guys a question, need your opinion.  

Would you want to only show this to your users once?  twice? Once a Week?  of course this is only until they add it or just show it once and then forget about it.

**Comment by SgtBatten** [comment]
Personally once and then forget it. If possible maybe a reminder one week later because people might want to play with it a little first.

But once is enough for me persobally. If you or others really want to remind people more often I'd say a monthly one would be okay.

**Comment by causefx** [comment]
thanks for your input

**Comment by Githubtordl** [comment]
I've tested this on Android, I don't get the popup. Looks like the fix worked.

**Comment by rix1337** [comment]
Seems fixed for me. Monthly should be fine, maybe less often for logged in users...

**Comment by causefx** [comment]
:)
