### ISSUE TITLE
Plex web app only works locally

### ISSUE THREAD

**Issue by nemchik** [causefx/Organizr#484]
I'd like to have a tab that uses https://app.plex.tv/web/app# but that doesn't seem to work, it only loads a blank white page. I can get a local tab with http://my.public.ddns:32400/web/ to work without issue.

**Comment by causefx** [comment]
that is because Plex Block iFrames,  what werbserver are you running?

**Comment by nemchik** [comment]
I didn't know plex blocks iFrames, that sucks! I'm using nginx (not sure which version) on ubuntu server 17.04

**Comment by causefx** [comment]
you can proxy plex to block it :)  I would suggest subdomain.  ie.  plex.domain.com

**Comment by nemchik** [comment]
I haven't yet figured out how to proxy with nginx. I know there's tons of tutorials but I just haven't bothered with it yet, I've got a pretty sloppy setup. I've mostly relied on https://github.com/htpcBeginner/AtoMiC-ToolKit/ and modified it to include my ddns to get organizr working, but i really feel like there's got to be a better way of setting it up.

**Comment by causefx** [comment]
nginx proxy is super easy and the best way
 you can also lock down things with org in it.

**Comment by nemchik** [comment]
Thanks for the info. I'll close this and look into proxy.

**Comment by causefx** [comment]
if you need help jump on gitter, we can help.
