### ISSUE TITLE
Fatal error since last update

### ISSUE THREAD

**Issue by Miicker** [causefx/Organizr#485]
Since the last update, I get this message on the homepage:
Fatal error: Uncaught Error: Call to undefined function curl_get() in `/volume1/web/Organizr/functions.php:929 Stack trace: #0 /volume1/web/Organizr/homepage.php(485): getPlexStreams(12, 'true', 'admin') #1 {main} thrown in /volume1/web/Organizr/functions.php on line 929`

Any idea how to solve this?

**Comment by causefx** [comment]
what OS and what PHP version?

if NIX,  PHP7 -> sudo apt-get install php-curl | PHP5 -> run sudo apt-get install php5.6-curl

**Comment by Miicker** [comment]
I am on DSM6.1.2, setting Organizr in the webserver to use PHP 5.6 did the trick. Thanks.
