### ISSUE TITLE
Speed Test Showing Upload Speed Same as Download

### ISSUE THREAD

**Issue by JoeStratton** [causefx/Organizr#486]
I am not sure if this is app specific or container specific, but I am using linuxserverio's Docker container and the speed test from the home page is showing my download speed as my upload.

For example, my internet is 300/30, but my speed tests are showing about 300/300. My guess is this is container related, but not sure if its a fix for you guys or linuxserver.

Thanks!

**Comment by causefx** [comment]
that is correct.  if you are testing on your own network.... the Speeds are correct because:

Are you on wifi?  same network or outside of network?

**Comment by JoeStratton** [comment]
Ahh I misinterpreted its use case. Tested it off my local network and that makes sense.

Thanks!
