### ISSUE TITLE
Error curl_get after update to 1.40

### ISSUE THREAD

**Issue by Kaminogoroshi** [causefx/Organizr#494]
So after i updated to the new version i'm getting this error i had no issues bvefore that it worked like a charm.
I installed it the way it is in the wiki and i used php 7.1 i'm on windows 10

Fatal error: Uncaught Error: Call to undefined function curl_get() in C:\nginx\html\Organizr\functions.php:929 Stack trace: #0 C:\nginx\html\Organizr\homepage.php(485): getPlexStreams(12, 'true', 'admin') #1 {main} thrown in C:\nginx\html\Organizr\functions.php on line 929

**Comment by Kinematic9** [comment]
I used the auto update to 1.4 and on the homepage I also get:

Fatal error: Uncaught Error: Call to undefined function curl_get() in C:\nginx\html\functions.php:929 Stack trace: #0 C:\nginx\html\homepage.php(485): getPlexStreams(12, 'true', 'admin') #1 {main} thrown in C:\nginx\html\functions.php on line 929

**Comment by causefx** [comment]
you need to install php curl.

<b>cURL</b> not enabled, uncomment ;extension=php_curl.dll in the file php.ini

**Comment by Kinematic9** [comment]
I am not that technically oriented, other than following your install on
wiki. Is there a link to show this? Everything was working properly before
this update. Thanks.

**Comment by Kaminogoroshi** [comment]
Thx it worked like a charm

in the wiki there is a section going about how to enable extension=php_openssl.dll and others as well same deal with curl

**Comment by Kinematic9** [comment]
That fixed it, thank you

**Comment by causefx** [comment]
sounds good, in the new version it will stop and error out to tell you waht to do :)
