### ISSUE TITLE
Log in issue after upgrade.

### ISSUE THREAD

**Issue by Antpam** [causefx/Organizr#495]
Team after completing a upgrade I receive this error after trying to log in. I have deleted the whole folder and re-downloaded the zip and move it back to my server and I still receive this error. 

Fatal error: Call to undefined function password_verify() in /home1/antpam/public_html/iplex.site/user.php on line 606

**Comment by causefx** [comment]
what version of PHP are you runnung?  You need to be on 5.6 or later.
