### ISSUE TITLE
Calendar not working

### ISSUE THREAD

**Issue by spaceboy76** [causefx/Organizr#496]
Hi, I'm having 2 issues with organizr:

first i dont get any sonarr, radarr or headphones data showing in the homepage. i understand from other users that they are supposed to display in a calendar format but i dont see this. i see the calendar settings within edit homepage but they only seem to be for display options.
second organizr is inaccessible after sometime. i see 502 bad gateway errors in the caddy window. i have tried the fix recommended at the bottom of the caddy install page by editing the system variables but organizr still becomes inaccessible after a while

let me know if i can provide any more information!

**Comment by causefx** [comment]
for caddy did you set the variable in the environment? 

as for calendar, you can switch to dev to get the updated log errors or you can jump on gitter and i can help you figure it out really quick.
