### ISSUE TITLE
[FR] Admin generated Recommendation/highlighted media Rows below "Recently Added"

### ISSUE THREAD

**Issue by leram84** [causefx/Organizr#498]
Would be great to have a tab in homepage settings that would let you create and reorder "rows" and specify the amount of items allowed. They would look identical to "recently added" and link through to plex/emby the same as well. Then in "media search" on HP, the admin would see a + button next to any item that comes up in search. clicking it would show the list of "rows"... you choose the row and it gets added.

You could make a Recommended Movies row, Recommended tv, Recommended comedy... winter holiday specials... etc etc etc. It's often requested for plex, but would be even better for org imo.

**Comment by causefx** [comment]
wtf,lol..... no idea even where to start.  hmmmm...will have to think about this.

**Comment by leram84** [comment]
ha! i could just as easily have seen you say Sure! and knock this out with like 8 lines. LOL, anyway yeah, just meant to bookmark this as a thought for future integrations... I was originally thinking that if the plex api ur using for recently added, also includes playlist updates, we could get running feeds of custom playlists, so u could add stuff by just adding to the plex playlist of whatever row (with matching names to the playlist) you want, from the admin plex account. But figured this might actually be easier... idk, feel free to close this if its too far out in left field lol, i kinda figured you could do this easily by cloning "recently added", but add a different (user manageable) source.
