### ISSUE TITLE
Fresh install on windows server fails

### ISSUE THREAD

**Issue by barbidule** [causefx/Organizr#499]
Fresh install on windows 2016 server, I get the following error : 
![image](https://user-images.githubusercontent.com/6185569/28276556-935e75dc-6b17-11e7-9b07-1d4d47981994.png)

**Comment by causefx** [comment]
when did this happen?  were you able to create an admin account?

**Comment by barbidule** [comment]
Yes it happens after the screen where you select DB location and admin
login/password.

**Comment by causefx** [comment]
can you make sure the location with the DB and org files have 777 permissions for now?

**Comment by barbidule** [comment]
It's a windows server, but I gave everybody full control. Still the same
error.
[image: Inline images 1]

**Comment by causefx** [comment]
fixing this now.  :0 this was my fault.

**Comment by causefx** [comment]
please download the dev branch.  that should fix it.

**Comment by barbidule** [comment]
Tried the dev branch, I get this error after the first screen (where you pick timezone and db location) : 
![image](https://user-images.githubusercontent.com/6185569/28347387-08d2fe12-6c37-11e7-8bc4-de9b78b8a077.png)

**Comment by causefx** [comment]
sorry, i forgot to tell you, you still need to clear your old files.  the config.php that is in the config folder.  as well as any users.db created, since it errored on you, there should be two.

**Comment by barbidule** [comment]
I did a fresh install, and I still get the same error :/

**Comment by causefx** [comment]
can u see if it created a users.db file?  if so where?  check the path you specified as well as the where the index.php is.

**Comment by barbidule** [comment]
The problem was the path : it was the parent folder of the orgarnizr
folder, when I switched to the organizr folder itself, it worked perfectly.

Thanks a lot !
