### ISSUE TITLE
Wrong image in Recently Added

### ISSUE THREAD

**Issue by WindfallProphet** [causefx/Organizr#505]
I've since changed the image (it was just grabbing a thumbnail), but Organizr has re-cached the image. Is there away to force it to re-grab the image? 

`http://private/ajax.php?a=plex-image&img=/library/metadata/25711/thumb/1499642436&height=444&width=300&key=25711-list`

**Comment by causefx** [comment]
delete 25711-list.jpg from images/cache

I will be adding an option soon.

**Comment by WindfallProphet** [comment]
Would it be possible to check if via hashing? Not sure if it would be a good idea, though, as I am in the midst of learning php.

**Comment by causefx** [comment]
possible, for now it replaces cache every 7 days.

**Comment by causefx** [comment]
will add reload soon.
