### ISSUE TITLE
Synology Docker Install - Settings Cannot Be Saved in Organizr...

### ISSUE THREAD

**Issue by MrMxyzptlk** [causefx/Organizr#508]
Synology Docker Install - Settings Cannot Be Saved in Organizr...

Sucessful install, but when I access the web GUI, and after initial configuration (DB location, Password, etc), When make any changes in Organizr; it displays 'Settings cannot be saved' at the top of the GUI?

I did not change any settings in the Docker install, other than changing the network ports. I just downloaded the image and powered it on.

**Comment by causefx** [comment]
are you changing the homepage part or advanced settings? or just saving tabs?

**Comment by MrMxyzptlk** [comment]
If I go to 'Edit Tabs' and then either save 'Save Tabs' or 'New Tabs' then 'Save Tabs'.

Interestingly enough the 'Apply Changes' dialog button appears after I try saving?

**Comment by causefx** [comment]
is there anything in the browser console?  F12

**Comment by MrMxyzptlk** [comment]
After I clicked on 'Save Tabs' this is in the console window.

1.40
settings.php:2339 You Are on Current Version
settings.php:2290 tab-box
settings.php:124 Object {}
ajax.js?v=1.40:117 Object {readyState: 1, getResponseHeader: function, getAllResponseHeaders: function, setRequestHeader: function, overrideMimeType: function…}
settings.php:1906 disabled this func

**Comment by causefx** [comment]
hmmm there is no error.

**Comment by MrMxyzptlk** [comment]
Here is the screen shot after I click on 'Save Tabs'

![image](https://user-images.githubusercontent.com/1753001/28429268-203879d8-6d4a-11e7-95b6-ed7ee5262964.png)

**Comment by MrMxyzptlk** [comment]
It also happens if I create a tab and then proceed to save.

**Comment by causefx** [comment]
create tab and click save then look in console again please.

**Comment by MrMxyzptlk** [comment]
OK, it worked this time. The only thing I can think of is that I didn't have all of the necessary fields filled out the first time.

Thank you for chasing this wild goose!

**Comment by causefx** [comment]
:)
