### ISSUE TITLE
IPad view issues

### ISSUE THREAD

**Issue by phairplay** [causefx/Organizr#51]
Hi 
i would really love to move over from dashboard but I use it solely on my mobile and iPad

On Idashboard every looks good on my default page (stats from htpc manager)

http://imgur.com/LlfYq9N

Yet on this versions it off 
http://imgur.com/gzNsVjK

Is this something that could be fixed 
:)

**Comment by causefx** [comment]
looks like this has to do with the width.  On iDashboard, can you turn off margins in the settings and see if it messes up the page too?

**Comment by phairplay** [comment]
Yes turning off margins messes it up

**Comment by causefx** [comment]
We can edit the code in HTPC manager to force the mobile version if that is what you like...  We have no control over it on Organizr.

**Comment by phairplay** [comment]
Please that would be fantastic

**Comment by causefx** [comment]
can you email me a link to that page so I can look at their css? causefx at me dot com

**Comment by phairplay** [comment]
It's on github 
https://github.com/Hellowlol/HTPC-Manager
I have the stats section ran through nginx

Or should I email you my Web link?

**Comment by causefx** [comment]
your link would be better as i can see it running and edit it in the console

**Comment by phairplay** [comment]
Email sent
Many thanks for this

**Comment by phairplay** [comment]
Hi did it come through?

**Comment by causefx** [comment]
Lemme check

**Comment by causefx** [comment]
found it:
/htpc/css/themes/onyx/bootstrap-responsive.min.css

change all these values `max-width:767px` to `max-width:739px`

also

change all these values `min-width:768px` to `min-width:740px`

**Comment by phairplay** [comment]
I've change it but nothing's happened

**Comment by causefx** [comment]
reset cache

**Comment by phairplay** [comment]
Went to iPad settings and clicked clear history and web site data and still no change

**Comment by causefx** [comment]
crap, i think it went the other way.  how big is the screen size of your ipad?

**Comment by phairplay** [comment]
iPad Air 2 9.7 inches

**Comment by causefx** [comment]
hmmmm, does this seem right to you? 

Resolution	1536 x 2048 pixels (~264 ppi pixel density)

**Comment by phairplay** [comment]
yes that it

**Comment by causefx** [comment]
can i goto your link again?

**Comment by phairplay** [comment]
Yeah your good to go

**Comment by causefx** [comment]
thanks

**Comment by causefx** [comment]
i dont have an ipad so i'm trying to use chrome with the ipad user agent

**Comment by phairplay** [comment]
Oh okay
I really appericate it

**Comment by causefx** [comment]
which is weird, because it displays fine...
![image](https://cloud.githubusercontent.com/assets/16184466/22161839/44a9c94a-df09-11e6-8ddb-9a84e50964d3.png)

**Comment by phairplay** [comment]
Sorry wary about in portrait mode

**Comment by phairplay** [comment]
The idashboard looks perfect it's just I I would like to use this new version

**Comment by causefx** [comment]
wary?  the SS was portrait.  Maybe i just need to buy an ipad.

**Comment by phairplay** [comment]
Sorry *what 
No worries thank you for trying :+1:

**Comment by causefx** [comment]
im still trying

**Comment by causefx** [comment]
the problem is the value in IP in and IP out

**Comment by phairplay** [comment]
On the Idashboard I get the same view as my mobile but bigger. Now it looks like the pc view

**Comment by causefx** [comment]
we can make it so on big screens it goes to the mobile site, im not sure why it's loading different.

**Comment by causefx** [comment]
do you only run HTPC manager for the computer stats?

**Comment by phairplay** [comment]
Yes and to run custom created scripts

**Comment by causefx** [comment]
once last thing to try:
htpc/css/themes/onyx/bootstrap-responsive.min.css


change this `.row-fluid{width:100%}` to `.row-fluid{width:100%;overflow:hidden}`

**Comment by phairplay** [comment]
No dice

**Comment by causefx** [comment]
Load up the CSS in your browser so it refreshes

**Comment by phairplay** [comment]
Again no luck.
I'm going to look at replacing htpc as all the other sites are fine

**Comment by causefx** [comment]
Phpsysinfo

**Comment by phairplay** [comment]
Cheers
