### ISSUE TITLE
Request for enhancement: Add LazyLibrarian to home page

### ISSUE THREAD

**Issue by MrMxyzptlk** [causefx/Organizr#511]
This application has been update tremendously in the last 6 months and works great for downloading ebooks, audio books, and magazines.

This app started out by using the codebase from Headphones so it should be fairly easy to implement?

**Comment by causefx** [comment]
which fork is this?

**Comment by MrMxyzptlk** [comment]
https://github.com/DobyTang/LazyLibrarian

Phil Borman took this over in the last year, and has made tremendous improvements.
It now works reliably and very well.

**Comment by causefx** [comment]
Closing all Feature Requests and will communicated thru FeatHub
