### ISSUE TITLE
Refused to display 'https://drunkenslug.com/' in a frame because it set 'X-Frame-Options' to 'sameorigin'.

### ISSUE THREAD

**Issue by nemchik** [causefx/Organizr#513]
I'm trying to load drunken slug as a tab in Organizr and it used to work (before they had some recent downtime) but now that it's back up it no longer lets me load the site as a tab in Organizr. I found an error in Chrome's developer console saying "Refused to display 'https://drunkenslug.com/' in a frame because it set 'X-Frame-Options' to 'sameorigin'." That looks like an HTTP Header to me (server config) but I might not be correct on that. I reached out to slug and he suggested I check here to see if it could possibly be an issue on this end.

**Comment by causefx** [comment]
Looks like he changed his server config.

Results for https://drunkenslug.com/:


```
HTTP/1.1 200 OK => Date => Fri, 21 Jul 2017 04:28:34 GMT
Content-Type => text/html; charset=UTF-8
Connection => close
Set-Cookie => PHPSESSID=e26k2g56eqsojb6h0v968sq8f3; path=/; secure; HttpOnly
Vary => Accept-Encoding
Expires => Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control => no-store, no-cache, must-revalidate
Pragma => no-cache
Strict-Transport-Security => max-age=31536000; includeSubdomains; preload
X-Frame-Options => SAMEORIGIN
X-Content-Type-Options => nosniff
X-XSS-Protection => 1; mode=block
Server => cloudflare-nginx
CF-RAY => 381b69e8ad24562b-ORD
```

He has now added: `X-Frame-Options => SAMEORIGIN` which breaks iFrames unless it comes from his own domain. 

There are only 2 options now:

1.  Use the plugin for your browser to bypass it, it is located in the help section under the Info tab in settings.
2. Have him take that header off his webserver.
