### ISSUE TITLE
Auth module not allowing uploads

### ISSUE THREAD

**Issue by AciDCooL** [causefx/Organizr#514]
Heya im using the auth module like explained on the wiki. And it's working like a charm. I noticed 1 issue though. For one when using it for NZBHydra I can't send nzb's to SAB.
Unless I use this workaround: 

// notchanged this block, just for good measure:
        location /hydra {
                auth_request /auth-admin;
                include ./conf.d/proxy.conf;
                #X-Forwarded-For is used for forwarding IP addresses
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_pass http://mediamonster.local:5075/hydra;
        }

//workaround (disabled auth_request)
        location /hydra/internalapi/addnzbs {
                auth_request off;
                include ./conf.d/proxy.conf;
                #X-Forwarded-For is used for forwarding IP addresses
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_pass http://mediamonster.local:5075/hydra/internalapi/addnzbs;
        }

Since I had the same issue with utorrent, but I cant reverse proxy utorrent that well like I can nzbhydra, so its hosted under /gui 
I have auth_request disabled, and using utorrents buildin http authentication. Not perfect but this works for the time being.
Seems that when using POST then auth module does some weird stuff. Here is some logging to back this up:

Utorrent:
2017/07/21 10:28:21 [error] 61200#61200: *271 upstream prematurely closed connection while reading response header from upstream, client: xxxxxxxx, server: xxxxx, request: "POST /gui/?token=MsKSNiNXTLhAz5eOCvPlWBNeRIKuVVgHAAAAAGB-VqQAAAAA9grBU8S6cVkAAAAA&action=add-file&download_dir=0&path= HTTP/1.1", subrequest: "/auth-admin", upstream: "https://192.168.0.2:443/auth.php?admin", host: "xxxxxx", referrer: "https://xxxxxxx/gui/web/index.html"
2017/07/21 10:28:21 [error] 61200#61200: *271 auth request unexpected status: 502 while sending response to client, client: xxxxxxx, server: xxxxxx, request: "POST /gui/?token=MsKSNiNXTLhAz5eOCvPlWBNeRIKuVVgHAAAAAGB-VqQAAAAA9grBU8S6cVkAAAAA&action=add-file&download_dir=0&path= HTTP/1.1", host: "xxxxxx", referrer: "https://xxxxxxx/gui/web/index.html"

And the same for hydra:
2017/07/21 12:33:18 [error] 62616#62616: *1589 upstream prematurely closed connection while reading response header from upstream, client: xxxxxx, server: xxxxxxx, request: "PUT /hydra/internalapi/addnzbs HTTP/1.1", subrequest: "/auth-admin", upstream: "https://192.168.0.2:443/auth.php?admin", host: "xxxxxx"
2017/07/21 12:33:18 [error] 62616#62616: *1589 auth request unexpected status: 502 while sending response to client, client: xxxxx, server: xxxxxx, request: "PUT /hydra/internalapi/addnzbs HTTP/1.1", host: "xxxxxx"

All of this is done within the organizr iFrame but that should not matter since it's probably a redirect\POST issue.

**Comment by causefx** [comment]
to use the top block you need to whitelist your IP within the auth block.

post your auth-admin block please.

**Comment by AciDCooL** [comment]
## Authenticationblock Organizr Admin
location /auth-admin {
                internal;
                rewrite ^ /auth.php?admin;
#                proxy_pass https://xxxxxxxx/auth.php?admin;
}

And I already was using the local ip to sab in hydra. Whitelist seems like an idea, any docs on that?
Looking at the code it should be something like;

rewrite ^ /auth.php?admin&whitelist=192.68.0.2;

thanks for thinking with me on this one.

**Comment by causefx** [comment]
please try using your external ip, lemme know if that works.
