### ISSUE TITLE
Cannot add new tabs

### ISSUE THREAD

**Issue by WindfallProphet** [causefx/Organizr#516]
Just upgraded php to 7.1, so that's probably the issue, but hoping I can resolve it sans a complete reinstall.

`http://organizr/ajax.php?a=submit-tabs 500 (Internal Server Error)`

**Comment by WindfallProphet** [comment]
Looking in the nginx error log yields this error.

`"PHP message: PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000]: General error: 8 attempt to write a readonly database in /apps/organizr/functions.php:2394`

**Comment by causefx** [comment]
set permissions recursively

**Comment by WindfallProphet** [comment]
Done, but still the same error.

**Comment by WindfallProphet** [comment]
Well I decided to try a refresh and now I'm getting this
`"PHP message: PHP Notice:  Undefined variable: configReady in /apps/organizr/index.php on line 615...`

**Comment by causefx** [comment]
what does check.php say?

**Comment by causefx** [comment]
also is there a config/config.php file?

**Comment by WindfallProphet** [comment]
check.php said that it did not have write access, so I went back and found that php-fpm was running under apache, not nginx, the user I was setting permissions for.  

Had to change the user running php-fpm by changing www.conf, not by changing the systemd file.
