### ISSUE TITLE
Headphones / Calendar ???issue???

### ISSUE THREAD

**Issue by MrMxyzptlk** [causefx/Organizr#522]
Not sure if this is a feature or bug...every week my calendar shows all of the music in Headphones on a 'random' day. Last week it was showing on the Wednesday heading in the Organizr calendar, this week it showed up on Monday? 

I'm trying to figure out why, and then how to filter or adjust this setting. 

On the particular day that it shows, there are thousands of 'events' almost all from Headphones.
Organizr is correctly showing my movies and TV.

**Comment by causefx** [comment]
wanted or downloaded?  can you post a Screenshot?

**Comment by MrMxyzptlk** [comment]
It's the default calendar on the dashboard. Here is Monday which has several hundred items...I only screenshot what I could see at once.

![image](https://user-images.githubusercontent.com/1753001/28533454-269352f2-706b-11e7-929b-de2fb222816d.png)

**Comment by causefx** [comment]
wow thats odd, can you pull up the api as paste part of it:

http://url/api?apikey=key&cmd=getWanted

**Comment by MrMxyzptlk** [comment]
Here is the first little bit...


[{"Status": "Wanted", "AlbumASIN": "B00000JH1M", "DateAdded": "2016-06-02", "AlbumTitle": "Ratt", 
"UserScore": null, "ArtistName": "Ratt", "ThumbURL": "https://lastfm-img2.akamaized.net/i/u/64s/24ba29acd5e700f1ef1896fa254f009a.png", "ReleaseCountry": null, "ReleaseDate": "1999", "AlbumID": "09f03706-511b-3b83-b848-e33b7d16f503", "ArtistID": "e0827234-3be3-4973-be59-1aa9575b9c76", "ArtworkURL": "https://lastfm-img2.akamaized.net/i/u/arQ/24ba29acd5e700f1ef1896fa254f009a.png", "ReleaseFormat": null, "SearchTerm": null, "CriticScore": null, "ReleaseID": "09f03706-511b-3b83-b848-e33b7d16f503", "Type": "Album"}, {"Status": "Wanted", "AlbumASIN": "B0034K7QXM", "DateAdded": "2016-06-02", "AlbumTitle": "Infestation", "UserScore": null, "ArtistName": "Ratt", "ThumbURL": "https://lastfm-img2.akamaized.net/i/u/64s/a1dba8a7b003460ec6b180002c88d4e5.png", "ReleaseCountry": null, "ReleaseDate": "2010-04-20", "AlbumID": "35377902-cf13-43fc-af9b-a49c977516a0", "ArtistID": "e0827234-3be3-4973-be59-1aa9575b9c76", "ArtworkURL": "https://lastfm-img2.akamaized.net/i/u/arQ/a1dba8a7b003460ec6b180002c88d4e5.png", "ReleaseFormat": null, "SearchTerm": null, "CriticScore": null, "ReleaseID": "35377902-cf13-43fc-af9b-a49c977516a0", "Type": "Album"}, {"Status": "Wanted", "AlbumASIN": "B000002IPR", "DateAdded": "2016-06-02", "AlbumTitle": "Detonator", "UserScore": null, "ArtistName": "Ratt", "ThumbURL": "https://lastfm-img2.akamaized.net/i/u/64s/d6c31f81a9ec01ea3bd88b5164a07743.png", "ReleaseCountry": null, "ReleaseDate": "1990", "AlbumID": "5e32177c-a238-3e22-8ecd-e0e2751bde10", "ArtistID": "e0827234-3be3-4973-be59-1aa9575b9c76", "ArtworkURL": "https://lastfm-img2.akamaized.net/i/u/arQ/d6c31f81a9ec01ea3bd88b5164a07743.png", "ReleaseFormat": null, "SearchTerm": null, "CriticScore": null, "ReleaseID": "5e32177c-a238-3e22-8ecd-e0e2751bde10", "Type": "Album"}, {"Status": "Wanted", "AlbumASIN": "B000091KOJ", "DateAdded": "2016-06-02", "AlbumTitle": "Invasion of Your Privacy", "UserScore": null, "ArtistName": "Ratt", "ThumbURL": "https://lastfm-img2.akamaized.net/i/u/64s/a5bd8b983c1c223fb775eca0c4943531.png", "ReleaseCountry": null, "ReleaseDate": "1985", "AlbumID": "60012039-d590-33e0-9f1f-57ff93f62432", "ArtistID": "e0827234-3be3-4973-be59-1aa9575b9c76", "ArtworkURL": "https://lastfm-img2.akamaized.net/i/u/arQ/a5bd8b983c1c223fb775eca0c4943531.png", "ReleaseFormat": null, "SearchTerm": null, "CriticScore": null, "ReleaseID": "60012039-d590-33e0-9f1f-57ff93f62432", "Type": "Album"}, {"Status": "Wanted", "AlbumASIN": "B000002INI", "DateAdded": "2016-06-02", "AlbumTitle": "Reach for the Sky", "UserScore": null, "ArtistName": "Ratt", "ThumbURL": "https://lastfm-img2.akamaized.net/i/u/64s/9fec86f46b5c6022d2f772f25a8228b5.png", "ReleaseCountry": null, "ReleaseDate": "1988-11-01", "AlbumID": "a80c8d3f-96e9-3bd6-8fc7-efe24bfa0f05", "ArtistID": "e0827234-3be3-4973-be59-1aa9575b9c76", "ArtworkURL": "https://lastfm-img2.akamaized.net/i/u/arQ/9fec86f46b5c6022d2f772f25a8228b5.png", "ReleaseFormat": null, "SearchTerm": null, "CriticScore": null, "ReleaseID": "a80c8d3f-96e9-3bd6-8fc7-efe24bfa0f05", "Type": "Album"}, {"Status": "Wanted", "AlbumASIN": "B000008JT4", "DateAdded": "2016-06-02", "AlbumTitle": "Ratt", "UserScore": null, "ArtistName": "Ratt", "ThumbURL": "https://lastfm-img2.akamaized.net/i/u/64s/24ba29acd5e700f1ef1896fa254f009a.png", "ReleaseCountry": null, "ReleaseDate": "1983", "AlbumID": "de955bfe-87ee-314a-8737-af801391a615", "ArtistID": "e0827234-3be3-4973-be59-1aa9575b9c76", "ArtworkURL": "https://lastfm-img2.akamaized.net/i/u/arQ/24ba29acd5e700f1ef1896fa254f009a.png", "ReleaseFormat": null, "SearchTerm": null, "CriticScore": null, "ReleaseID": "de955bfe-87ee-314a-8737-af801391a615", "Type": "EP"},

**Comment by causefx** [comment]
looks like headphones has some dates that are only years.  Let me write something up real quick.

**Comment by causefx** [comment]
Change Line 2912 of functions.php to this please:

`$albumDate = (strlen($child['ReleaseDate']) > 4) ? $child['ReleaseDate'] : $child['ReleaseDate']."-01-01";`

**Comment by MrMxyzptlk** [comment]
2912 starts with function GetPlatform.
That doesn't look like the correct line to change?

There are also 3 other functions.php locations...the one I'm currently looking at is in the 'Dashboard' folder.

**Comment by causefx** [comment]
are you on 1.42?  if so 2912 should be $albumDate...  

https://github.com/causefx/Organizr/blob/master/functions.php#L2912

Why is there 3 functions.php...?  it should be the one in same location as index.php

**Comment by MrMxyzptlk** [comment]
OK, I made the change to functions.php...but since the calendar isn't working I can't test it : )
Ha!

**Comment by causefx** [comment]
can u PM me on gitter your URL?

**Comment by causefx** [comment]
Fixed in 3614954

**Comment by MrMxyzptlk** [comment]
OK, I deleted my install, but backed up my config.
I used GIT to pull the new updates, the calendar is working again, but the long long list of albums that I have is showing still in the calendar.

I checked line 2912 in functions.php and it is correctly showing what you wanted?

**Comment by MrMxyzptlk** [comment]
Which URL do you want me to PM?

**Comment by causefx** [comment]
One where I can access your homepage

**Comment by MrMxyzptlk** [comment]
OK, I just PMd you on Gitter with the info...

**Comment by causefx** [comment]
Fixed in 9ce5dce
