### ISSUE TITLE
(MyUserName) IS NOT ALLOWED, BECAUSE IT IS TOO SIMILAR TO OTHER USER NAMES.

### ISSUE THREAD

**Issue by tridiumcontrols** [causefx/Organizr#525]
Running latest origanizr 1.42 on ubuntu 16.04, apache2, with php7.0. 

Created a tab with a https webpage, and got the error above, I created a proxmox VM tab and that worked great, but not sure why this won't work. 

What does this mean? Where is to similar? I'm the only user in the system.

**Comment by causefx** [comment]
This happened when adding a new tab or creating a new user?

**Comment by tridiumcontrols** [comment]
Adding new tab, very first one I tried. Added 5 more after that and worked fine but I'm referencing the 5 with static IPs on the internal network,

The one i'm having issues on is I Tried using the internal IP instead and works, but when I enter domain https://mdxxxx.com it fails.

**Comment by tridiumcontrols** [comment]
Issue can be closed, rebooted ubuntu server and issue went away, must of been a config issue of some sort. 

Rebooted server, and re-added the tab and no issue.

**Comment by causefx** [comment]
awesome!  thank you.
