### ISSUE TITLE
HTTPS with self signed certs, not opening.

### ISSUE THREAD

**Issue by tridiumcontrols** [causefx/Organizr#526]
Running latest Organizr 1.42 on ubuntu 16.04, with php7.0. 

I have several services that run on https on my internal network with self signed certificates, and I get a webpage might be temporary down (screenshot attached), but if I disable iFrame then a chrome tab opens and devices is accessable. Does organizr support https with self signed certs? I have pfSense and tried it as well, and get the same webpage might be down error. 

![screen shot 2017-07-24 at 11 15 53 pm](https://user-images.githubusercontent.com/22411662/28558512-08c0f07a-70c7-11e7-856d-340e6b05c5af.png)

**Comment by causefx** [comment]
in the browser console, F12, what does it say?

**Comment by tridiumcontrols** [comment]
This can be closed, I get a error on webconsole about x-frame. 

Refused to display 'https://xxxxxxx.com/ord/file:%5Epx/dashboard.px' in a frame because it set 'X-Frame-Options' to 'sameorigin'.

Guess it'll have to be a no-iframe option.
