### ISSUE TITLE
How do I migrate to new server? What files need move to retain configuration?

### ISSUE THREAD

**Issue by MrMxyzptlk** [causefx/Organizr#527]
How do I migrate to new server? What files need move to retain configuration?

**Comment by MrMxyzptlk** [comment]
Figured it out.
I needed config.php and users.db
I had to edit the config.php to properly point to the db and correct directories on the new server.

Feature request to back and restore with some sort of auto config between servers...

**Comment by causefx** [comment]
i will look into zipping them :)

**Comment by jonfinley** [comment]
Second this idea. For back up purposes.
