### ISSUE TITLE
Calendar not showing anything in 1.42 upgrade...1.40 was working fine

### ISSUE THREAD

**Issue by MrMxyzptlk** [causefx/Organizr#528]
Calendar not showing anything in 1.42 upgrade...1.40 was working fine

**Comment by tridiumcontrols** [comment]
Same issue here,

**Comment by causefx** [comment]
anything logs?  Settings>View Logs>Org Logs

**Comment by MrMxyzptlk** [comment]
No errors in Org Log...

**Comment by causefx** [comment]
can u guys force pull the branch, this has been fixed. Fixed in 3614954

**Comment by MrMxyzptlk** [comment]
Working now...thank you!
