### ISSUE TITLE
Cant Login

### ISSUE THREAD

**Issue by mrdeadlocked** [causefx/Organizr#53]
Page loads. I created an admin account. I try to login and it flips right to  "great now that you've made an admin account its time to make tabs" asking me to login. I tried my original saved pass and reset the pass also.

**Comment by causefx** [comment]
what does the pop up on the top right say when you try logging in?

**Comment by mrdeadlocked** [comment]
![image](https://cloud.githubusercontent.com/assets/461352/22167428/3ae839fc-df34-11e6-9f71-e97d7773ed55.png)

**Comment by causefx** [comment]
can you delete your users.db file and try creating an account again?

**Comment by mrdeadlocked** [comment]
that seemed to work..thanks

**Comment by causefx** [comment]
good deal, thanks
