### ISSUE TITLE
Feature request: Allow searching and 'display' Plex photos on homepage dashboard.

### ISSUE THREAD

**Issue by MrMxyzptlk** [causefx/Organizr#543]
This is the only media format that is not showing at the moment.
Photos would complete the 'circle'.

Thanks in advance...

**Comment by causefx** [comment]
I'll have to add some photos to my library so i can test.

**Comment by MrMxyzptlk** [comment]
Thank you!

**Comment by MrMxyzptlk** [comment]
Did you get a chance to add some photos?

**Comment by causefx** [comment]
I added a bunch but none of them come up in the plex api search

**Comment by MrMxyzptlk** [comment]
Are you using the official API, or someone else's?

**Comment by causefx** [comment]
correct that is what i'm using:

![image](https://user-images.githubusercontent.com/16184466/28936091-71027926-783b-11e7-995c-08a9c52f437a.png)

Noting is returned when searching for photos.

```
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<MediaContainer size="4" identifier="com.plexapp.plugins.library" mediaTagPrefix="/system/bundle/media/flags/" mediaTagVersion="1501031320">
<Provider key="/system/search" title="Local Network" type="mixed"/>
<Provider key="/search?type=10" title="Tracks" type="tracks"/>
<Provider key="/search/actor" title="Actors" type="actors"/>
<Provider key="/search/director" title="Directors" type="directors"/>
</MediaContainer>
```

**Comment by causefx** [comment]
currently this is not possible.
