### ISSUE TITLE
Sub-tabs don't work in Settings

### ISSUE THREAD

**Issue by justinpeterson13** [causefx/Organizr#544]
After auto-upgrading to 1.42 none of the tabs within settings function. I'm unable to administer the system.

**Comment by causefx** [comment]
did you try deleting org.log?

**Comment by justinpeterson13** [comment]
Sorry for the late response, I tried deleting the log but it didn't help.

**Comment by justinpeterson13** [comment]
Fixed it! Turns out the SMTP email fields in the config.php were the problem, specifically the password field. I erased all the email settings in the config.php and voila!
