### ISSUE TITLE
cURL not enabled

### ISSUE THREAD

**Issue by Adrimau** [causefx/Organizr#546]
After the last update, I've this problem "_cURL not enabled_". Organizr is install with Docker on my Synology NAS and cURL was ticked (I use PHP 5.6) in Web Station's settings before this update.

Already tried to restart PHP package and Webserver.

**Comment by causefx** [comment]
which docker image did you use?

**Comment by Adrimau** [comment]
https://hub.docker.com/r/lsiocommunity/organizr/

**Comment by causefx** [comment]
can you try rstarting that docker, this is weird as that image has php7 and curl already enabled

**Comment by Adrimau** [comment]
I've tried to restart the package and after the container, same problem.

**Comment by causefx** [comment]
if you goto ip:port of container do you see the same problem?

**Comment by Adrimau** [comment]
Yes.
<img width="2014" alt="capture d ecran 2017-07-28 a 17 59 16" src="https://user-images.githubusercontent.com/21692746/28725696-8bdd3e9c-73be-11e7-9497-eae0a47da4bd.png">

**Comment by causefx** [comment]
you may need to post an issue here:

https://github.com/linuxserver/docker-organizr/issues

It is very weird because the image has curl installed for sure.  is there anyway to "update" the docker?

**Comment by Adrimau** [comment]
No other way to update the container. I've tried to create a copy of it and same problem. Even if I create a new container with the same image, so I will try an other one.

**Comment by lost101** [comment]
I had the same problem with linux server container... assumed it updates itself but was actually running V20 of that container. I installed watchtower docker and it updated to latest.
https://blog.rylander.io/2016/12/14/automate-docker-image-and-container-updates/

**Comment by causefx** [comment]
@lost101 thanks for that  I don't use dockers at all so i can't really offer any help.

**Comment by Finalfx** [comment]
I was experiencing the same issue but am not using a Synology.  For anyone having this issue you can run the following commands to fix it.

sudo docker pull lsiocommunity/organizr
sudo docker stop <container name>; sudo docker rm <container name>

This will download the latest image and remove the existing container.  Once you have completed this you can reinstall your Organizr container and it will run off the latest image which has curl and functions properly.

**Comment by Adrimau** [comment]
I confirm that after create a totally new container with the same image, my problem has been solved.

Thanks.
