### ISSUE TITLE
Setting tab not displaying properly anymore

### ISSUE THREAD

**Issue by XTREEMMAK** [causefx/Organizr#549]
I believe this happened after the recent update. I'm no longer able to browse through my settings tab. I'm just getting a skinny bar that performs roll over, but no actions. The format of the settings menu is also messed up. I've also checked this on another computer, and my phone. I've also deleted the cookies just in case. No change.

![image](https://user-images.githubusercontent.com/6014700/28801922-db5ae086-7621-11e7-8ac8-586750443362.png)

**Comment by causefx** [comment]
What size resolution is this monitor?

**Comment by XTREEMMAK** [comment]
I've tested on both a 1360X768 and a 1920x1080 resolution monitor. Even the responsive version when scaling the resolution down yields no return from input. I also tried on tablet that has never run the site before, as well as my cell phone and another laptop. Same result.

**Comment by causefx** [comment]
have you added any custom css?

**Comment by XTREEMMAK** [comment]
I turned on one of the provided templates, but other than that no.

**Comment by causefx** [comment]
can you open up org.log?  does it look like there is a formatting issue?

**Comment by XTREEMMAK** [comment]
I saw in a previous post that I should try deleting that first. I have not tried that yet as I couldn't find it. Where can I find that log file?

**Comment by causefx** [comment]
should be in root folder along with index.php

**Comment by XTREEMMAK** [comment]
That might be a problem, I don't seem to have one. Should I create one or just do a fresh install? Also, preserving config?

**Comment by causefx** [comment]
you can do a force branch install.  that will overwrite all files except your settings :)

**Comment by XTREEMMAK** [comment]
My apologies,
Being a Freenas install, I forgot I had this in the Nginx folder. Found the install folder, deleted the org.log file, and now all is well :).

**Comment by causefx** [comment]
by any chance did you have a backup of that file?  I would love to see what broke it.

**Comment by XTREEMMAK** [comment]
Unfortunately no :( As a possible hint, the end of the file was referencing a few images I uploaded. My theory is that it could have been possibly linked to an wrong sized file (as I do remember it returning an error on an image upload some time ago). Tried testing it with turning off some CSS on the left hand bar but no dice though...

**Comment by causefx** [comment]
that's okay, i think I just fixed it anyway.  :)

**Comment by XTREEMMAK** [comment]
Sweet. Thanks for the help!

**Comment by causefx** [comment]
no problem
