### ISSUE TITLE
Request: List Music below TV and Movies on Calendar

### ISSUE THREAD

**Issue by MrMxyzptlk** [causefx/Organizr#551]
On any given day, if I add a new artist to Headphones, it may download hundreds of tracks, and these all show on the Organizr calendar. New TV shows or Movies will always be in much smaller quantities. If you display TV and Movies at the 'top' of the calendar, then I don't have to scroll down through hundreds of music tracks to get to the couple of TV and Movie listing for the day.

The other thought is that maybe the items in the calendar have sub-group...in other words, just show the artist if new tracks or albums are available, and then you click on the one listing to get a drop down or such that shows the available tracks or albums.

Or some way to filter and sort the aggregate and calendar better.

**Comment by causefx** [comment]
it shouldn't be adding tracks, it should only be adding albums.  As for the calendar it sorts by time, which movies and albums dont have times so they appear at the top.
