### ISSUE TITLE
EdgeRouterX webUI no longer loads in Organizr frame

### ISSUE THREAD

**Issue by cowboytronic** [causefx/Organizr#555]
I have an Organizr tab for my router's webUI so I can check real-time bandwidth, etc.  I only access this on my LAN.

I upgraded my Ubiquiti EdgeRouterX from firmware version 1.9.1.1 to 1.9.7. and now the webUI no longer loads in the tab.  I assume this is due to a change in their web page, maybe somehow breaking iframes, but I don't know.

I'm using Safari so there is no plugin available in Settings> About> Help

**Comment by causefx** [comment]
I just posted on the Ubnt Forums:

https://community.ubnt.com/t5/EdgeMAX/1-97-GUI-blocked-in-iFrame/m-p/2017331#U2017331

**Comment by causefx** [comment]
So far, Ubnt has said anything.  If we do find a solution we can paste here if anyone is looking.

**Comment by cowboytronic** [comment]
oh well, thanks for trying
