### ISSUE TITLE
Splash screen squishes icons on mobile

### ISSUE THREAD

**Issue by Cruv** [causefx/Organizr#556]
Hello, 

Thank you for adding the splash screen. It looks fantastic and loads super fast on desktop browsers. However some of my users use mobile to requests content (I have ombi in an iFrame and as the default page). When I turned on the splash screen feature and navigated to the page using my android chrome browser the 4 icons on the page were squished into slim rectangles all trying to fit on one row. Is there any way to set a fixed width or something to solve this?

**Comment by Cruv** [comment]
Here is a screenshot of what I am talking about.
![organizr mobile splashscreen](https://user-images.githubusercontent.com/16615493/28976832-84fa0f52-790d-11e7-9c3e-f91dd8b5bbc0.png)

**Comment by jonfinley** [comment]
same issue on iOS

**Comment by elmerfdz** [comment]
I'm not 100% sure if @causefx has pushed the fix out to the master branch as well but this issue has been on the dev branch, you might have to clear your browser cache as well.

**Comment by causefx** [comment]
sorry, yes it is fixed on master :)

**Comment by Cruv** [comment]
Thanks guys! Keep up the great work!
