### ISSUE TITLE
Wierd PEM events in org log

### ISSUE THREAD

**Issue by si0972** [causefx/Organizr#559]
Since yesterday my org log, have been adding PEM events. it hadd 925 pages when i just purged them,
I get this: 

2017-08-07 18:30:42 | CERT PEM: downloaded new pem file | Success

[Screen](https://www.røstvik.no/cap/2017-08-07_18-31-18.png)
While writing, it has generated 10 pages.

I have been playing with my certs, getting PlexPy to work, this may be a reason.

**Comment by justinpeterson13** [comment]
Same issue here

**Comment by si0972** [comment]
We fixed it over at gitter, happens to folks there too. Dont worry, guess update soon

Sendt fra min iPhone

Den 8. aug. 2017 kl. 17.44 skrev justinpeterson13 <notifications@github.com<mailto:notifications@github.com>>:


Same issue here

**Comment by si0972** [comment]
Fixed in DEV build.
