### ISSUE TITLE
[Feature Request] Option to change browser tab icon

### ISSUE THREAD

**Issue by saitoh183** [causefx/Organizr#566]
We already have the option to change the loading screen and logo but we need the same option to change the Browser tab icon as well.

**Comment by causefx** [comment]
all icons are in favicons folder in images directory.  overwrite them and make those files read-only.

**Comment by saitoh183** [comment]
Yeah i know but it would be nice if we could do it from the UI just like we do for the loading and tabs

**Comment by causefx** [comment]
currently the easiest way to do it is like above, if I find time i  will revisit this issue.
