### ISSUE TITLE
[Feature Request] Newsletter/Messege for plex and emby

### ISSUE THREAD

**Issue by saitoh183** [causefx/Organizr#567]
It would be cool to have a sort of newsletter that can be programmable with latest content on plex/emby or to just send a mass email to users... sort of like what Ombi has but a bit more flexible. Here are a few ideas of what it could  contain

- CSS/HTML customization (like Homepage) but also have a default template
- timer setting(like a calendar) so you can configure the frequency of email send-off
- field to add extra email addresses (in case you want to send it to someone outside your user base)
- field to exclude users from userbase (could be via email or plex/emby username)
- system should be able to retrieve userbase from plex/emby (like Ombi)
- Field to add custom message
- Ability to choose what you want to send
  - TV shows only
  - Movies only
  - Per library chose (ie: Send a New content email of only Anime (even if it is part of TV shows it is a separate library )
  - No library just need to send a message 
- Ability to create/save different email templates for quick send outs
- Ability to assign a template to auto-send and assign a template for manual send
- Multiple timers with different assigned templates for auto sending different templates at different inter-vols/times

Having this would rival Ombi version and even PlexMail

**Comment by TATUMTOT** [comment]
+1
