### ISSUE TITLE
Set Timezone default is broken, filled with warning instead of example.

### ISSUE THREAD

**Issue by RlndVt** [causefx/Organizr#57]
Starting with fresh git install, the 'Set Timezone' default box is filled with the text below:

> `<br /><b>Warning</b>:  : It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone. in <b>/var/www/organizr/index.php</b> on line <b>667</b><br />UTCdate_default_timezone_get()`

**Comment by causefx** [comment]
crap, let me look into that.

**Comment by causefx** [comment]
also, what version of PHP are you using?

**Comment by RlndVt** [comment]
PHP 5.6.30,

I've also got a problem after filling in both boxes, the next screen I get is blank.

Could be related to faulty input or something I'm missing, but lets tackle one problem at a time.

**Comment by causefx** [comment]
[index.zip](https://github.com/causefx/Organizr/files/722201/index.zip)

try this file

**Comment by RlndVt** [comment]
Yeh that works. I could also upgrade to php version 7.x if you prefer?

But then I get this on my next screen:

> Fatal error: Uncaught Error: Call to undefined function session_start() in /var/www/user.php:147 Stack trace: #0 /var/www/index.php(115): User->__construct('registration_ca...') #1 {main} thrown in /var/www/user.php on line 147

**Comment by causefx** [comment]
I'd upgrade to be safe, thats an odd error.  session start is for sure defined.

**Comment by RlndVt** [comment]
Ok I'll stick to the new version.

I don't know what to tell you. This is my first time using freenas, so I'm also just trying to figure things out as I go along. Could it be that I'm missing something?

I don't know if you have more experience with  freenas/freebsd, but I could spin up a jail for you to access and try things out with.

**Comment by causefx** [comment]
sure, send me the info.

**Comment by RlndVt** [comment]
Sent you a pm on reddit
