### ISSUE TITLE
My docker instance just died

### ISSUE THREAD

**Issue by nuentes** [causefx/Organizr#572]
I have had [this](https://hub.docker.com/r/lsiocommunity/organizr/) installed on my ubuntu server for a while. I don't know what I was thinking a couple hours ago, but I clicked Auto Update in Organizr, and all hell has broken loose since then. The page will now only load [this](https://i.imgur.com/yLkOgbm.jpg), and I can't figure out how to get back up and running. I've restarted the container a few times, as well as start/stop, and that has no change. 

`docker logs organizr` results in the following information scrolling forever.

```
nginx: [emerg] bind() to 0.0.0.0:80 failed (98: Address in use)
nginx: [emerg] bind() to 0.0.0.0:80 failed (98: Address in use)
nginx: [emerg] bind() to 0.0.0.0:80 failed (98: Address in use)
nginx: [emerg] bind() to 0.0.0.0:80 failed (98: Address in use)
nginx: [emerg] bind() to 0.0.0.0:80 failed (98: Address in use)
nginx: [emerg] still could not bind()
```

Things like
```
docker exec organizr service php7 restart
docker exec organizr service nginx restart
docker exec organizr apt-get install php-curl
docker exec organizr sudo apt-get install php-curl
```

all result in `rpc error: code = 2 desc = containerd: container not started`

I apparently don't know enough about docker to get myself out of this mess, and I'm hoping someone here does...
Thanks for any help...

**Comment by nuentes** [comment]
Full disclosure - I just cross posted this issue into https://github.com/linuxserver/docker-organizr as well

**Comment by nuentes** [comment]
Resolved. If this is happening to you, see here: https://github.com/linuxserver/docker-organizr/issues/15

**Comment by causefx** [comment]
Awesome!  Good job!
