### ISSUE TITLE
PFSense Tab

### ISSUE THREAD

**Issue by HidYn** [causefx/Organizr#574]
Hi All,

Loving Organizr and have it setup and running great with all my services running on the same box using nginx reverse proxy.

I am struggling to get it to work with PFSense as a tab though and would love some guidance if possible.

My PFSense box is a different server to the server running nginx.

Thanks in advance.

**Comment by MrMxyzptlk** [comment]
+1

**Comment by si0972** [comment]
It is probably a iFrame issue, google "pfsense iframe" for help on alowwing iFrame.

**Comment by jonfinley** [comment]
What is your pfsense block?

**Comment by HidYn** [comment]
I've currently got to this point with the block.

`		location /pfsense {
		proxy_pass http://pfsense.local;
		proxy_set_header Host pfsense.local;
		
	}	`

**Comment by causefx** [comment]
try adding this header:
`proxy_hide_header X-Frame-Options;`

if that doesn;t work, re-open this thread
