### ISSUE TITLE
settings.php and homepage.php  404

### ISSUE THREAD

**Issue by drkmachine** [causefx/Organizr#575]
pretty new to some of this so bare with me if you will. I have a reverse proxy setup with nginx on one machine and Org in a docker container on another. Locally Org works perfectly, but accessing it from outside the network, Both the Homepage.php and settings page give me a 404 error. 
Any help would be appreciated.

**Comment by si0972** [comment]
Which port is exposed on the docker? how does your organizr block look like in nginx?

**Comment by causefx** [comment]
yes, please post the blocks.

**Comment by drkmachine** [comment]
sorry for the delay, 80 is exposed in docker and rerouted to 8081. here is the current working block.

`http {
    include       mime.types;
    default_type  application/octet-stream;

    #log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
    #                  '$status $body_bytes_sent "$http_referer" '
    #                  '"$http_user_agent" "$http_x_forwarded_for"';

    #access_log  logs/access.log  main;

    sendfile        on;
    #tcp_nopush     on;

    #keepalive_timeout  0;
    keepalive_timeout  65;

    #gzip  on;

    server {
        listen 80;
        server_name theguild.myftp.org;
        return 301 https://$host$request_uri;
    }

    server {
        listen       443 ssl;
        server_name  theguild.myftp.org;
        include ssl_common.conf;
        include proxy_setup.conf;

        #charset koi8-r;

        #access_log  logs/host.access.log  main;

        location / {
            proxy_pass http://192.168.1.14:8081;
            proxy_redirect off;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            }
        location ~ [^/]\.php(\/|$) {
            try_files $uri =404;
            fastcgi_split_path_info ^(.+?\.php)(\/.*)$;

            # Mitigate https://httpoxy.org/ vulnerabilities
            fastcgi_param HTTP_PROXY "";

            fastcgi_pass unix:/var/run/php-fpm.sock;
            fastcgi_index index.php;
            include fastcgi_params;
            }
        }`

**Comment by causefx** [comment]
remove this:

```
    location ~ [^/]\.php(\/|$) {
        try_files $uri =404;
        fastcgi_split_path_info ^(.+?\.php)(\/.*)$;

        # Mitigate https://httpoxy.org/ vulnerabilities
        fastcgi_param HTTP_PROXY "";

        fastcgi_pass unix:/var/run/php-fpm.sock;
        fastcgi_index index.php;
        include fastcgi_params;
        }
```

**Comment by drkmachine** [comment]
::facepalm:: gah!! Thank you. Fantastic work on this by the way

**Comment by causefx** [comment]
:) you're welcome!  👍
