### ISSUE TITLE
Plex on Homepage "Fatal Error: Uncaught Error"

### ISSUE THREAD

**Issue by YourCrush** [causefx/Organizr#582]
I am on version 1.44, although this was happening on the previous version as well.

Receiving this error on the homepage after setting up Plex:

```Fatal error: Uncaught Error: Call to undefined function simplexml_load_string() in /var/www/html/Organizr/functions.php:955 Stack trace: #0 /var/www/html/Organizr/homepage.php(417): getPlexStreams(12, 'true', 'admin') #1 {main} thrown in /var/www/html/Organizr/functions.php on line 955```

I tried looking through current Github issues and could not find anything related, although I may have skipped over it. 

Any ideas? I'm not sure how to get more information from this error. 

I have Organizr hosted on a Vultr server because my home network does not want to let me use port 80, and forwarding another port to port 80 breaks more things than fixes. Plex is hosted locally on my network at home, with port 32400 forwarded to the server.

**Comment by si0972** [comment]
what does check.php say?

**Comment by elmerfdz** [comment]
Seems like you don't have simplexml installed

**Comment by YourCrush** [comment]
Alright, thanks elmerfdz! That looked to be the issue.

In case anyone else has this problem, here is what I did:

```sudo add-apt-repository -y ppa:ondrej/php && sudo apt update && sudo apt install -y php7.0-mbstring php7.0-zip php7.0-xml
```

```sudo /etc/init.d/apache2 restart```
