### ISSUE TITLE
404 Error Page Not Working

### ISSUE THREAD

**Issue by kmlucy** [causefx/Organizr#585]
I have the following line in my NGINX server block: 

```
error_page 400 401 402 403 404 /error.php?error=$status;
```

I correctly get the Organizr 400 and 401 error pages upon testing, but I still get the NGINX default 404 error page. I found a recommendation to include `proxy_intercept_errors on;` in my Organizr block, and that does allow the correct 404 page, but the page listed is wrong. No matter what page I test with, I get this message instead of the correct location:

```
http://FQDN/error.php?error=404 was not found on this server.
```

**Comment by causefx** [comment]
is this all on one block or across subdomains?

**Comment by kmlucy** [comment]
All in one block. All my services are in subdirectories.

**Comment by causefx** [comment]
this is how i have it:

```
error_page 400 401 403 404 405 408 500 502 503 504  /error.php?error=$status;
location / { try_files $uri $uri/ =404; }
```

**Comment by kmlucy** [comment]
I already have my `location /` block set for `proxy_pass` for Organizr:

```
error_page 400 401 402 403 404 405 408 500 502 503 504 /error.php?error=$status;

# Organizr
location / {
        proxy_pass http://IP_ADDR:9080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_intercept_errors on;
        }
```

**Comment by kmlucy** [comment]
Looking at the code of `error.php`, it seems like the information in `$_SERVER` is being pulled from the error page, not the originally requested page.

**Comment by causefx** [comment]
try adding that to the docker nginx conf.

**Comment by kmlucy** [comment]
Add what exactly to my nginx conf? I have attempted many variation of the try_files lines with no success.

**Comment by causefx** [comment]
`error_page 400 401 402 403 404 405 408 500 502 503 504 /error.php?error=$status;` 

adding that line to the docker nginx conf.

Actually let me ask @gilbn to see if he uses it with docker.

**Comment by kmlucy** [comment]
Actually, I just got it mostly figured out. I set that line inside the docker nginx conf, and set the same line, but without the 404 inside the reverse proxy conf. It now works as expected, with the one exception of 404 errors within other locations blocks. 

So if I get a 404 page by going to https://URL/sonarr/test, the 404 is handled by Sonarr. I don't think there is a way around that, however.

**Comment by causefx** [comment]
yea sonarr handles their own
