### ISSUE TITLE
[Feature Request] rigtclick open in windows, open right window

### ISSUE THREAD

**Issue by si0972** [causefx/Organizr#586]
Both the close button and refresh button works this way, on open in window it opens rightclik menu.

**Comment by causefx** [comment]
will do.

**Comment by si0972** [comment]
I still want this :)

**Comment by si0972** [comment]
Wonder if V2 gets it

**Comment by causefx** [comment]
v2 has button clicks now

**Comment by leram84** [comment]
... now can we have the option to disable them all please? :)))))
