### ISSUE TITLE
Undefined variable: configReady

### ISSUE THREAD

**Issue by gogo199432** [causefx/Organizr#588]
Hey, I just installed Organizr on my OMV in nginx, but I'm having several issues. First of all it wants to place my database in the hdd root, where all my shared folders live. And of course php user (which I'm assuming is supposed to be www-data) doesn't have write permission to. But even after setting it to 0777 permissions, I'm getting the error you can see in the title.

![nevtelen](https://user-images.githubusercontent.com/9107561/29571677-20a7d83a-875a-11e7-8994-7b151f250841.png)

I have no idea what to do :/

**Comment by causefx** [comment]
can you show permissions for that directory?  also what does check.php say?

**Comment by gogo199432** [comment]
it has permission 0777
check.php is full green except for the parent library (which is the actual hdd) where it says that php user doesn't have access. But even after setting that folder to 0777 the error persists. (btw this is another thing I would need to get fixed, don't want to have my main data folder have 0777 permission)

**Comment by gogo199432** [comment]
Hey, any luck with this issue? I'm soon leaving and wont have access to my server for several months :(

**Comment by gogo199432** [comment]
I seem to have fixed the problem. I'm not quite sure how, but I increased the time settings in the nginx plugin -> pools . It loads now correctly.

**Comment by causefx** [comment]
awesome!
