### ISSUE TITLE
loginLog.json is in the root directory and accessible for everyone

### ISSUE THREAD

**Issue by grOGH** [causefx/Organizr#589]
In my default installation, the login logs are placed directly in the root directory under /loginLog.json. There is no setting to change that.

With a standard nginx config, that file will be served to anyone simply by navigating to HOST/loginLog.json without any authentication.

Granted, I can add an nginx directive to deny serving json files in the root dir, but simply placing sensitive data (such as login logs that include user names and IP adresses) in the root dir is a security issue. 

Logs should be protected, for example by placing them in a log directory with a restrictive .htaccess.

**Comment by maximm07** [comment]
you could add this to server config;


# Block access to check (contains verbose server info)
   location ^~ /check.php {
   return 404;
}

# Block access to log
   location ^~ /loginLog.json {
   return 404;
}

**Comment by causefx** [comment]
i will be adding this to WIKI:

```
	location ~ \.(log|json|db)$ {
		deny all;
	}
```
