### ISSUE TITLE
Add Option to default to login screen

### ISSUE THREAD

**Issue by JoeStratton** [causefx/Organizr#590]
It would be nice to have a toggle to make the default home page the login screen for those of us who do not use the "none" authentication feature.

**Comment by si0972** [comment]
You achive this by making none of the tabs available for guests.

**Comment by JoeStratton** [comment]
all that does is show a blank screen before you login. I am saying a much more elegant solution would be to show the login screen instead.

**Comment by si0972** [comment]
Thats not how it is suposed to work, it showed a blank page for me before, then somehow it started showing the login screen. You should try in incognito to check if it may be a cookie issue. A few people has commented this.

Sendt fra min iPhone

Den 28. aug. 2017 kl. 17.02 skrev Joe Stratton <notifications@github.com<mailto:notifications@github.com>>:


all that does is show a blank screen before you login. I am saying a much more elegant solution would be to show the login screen instead.

**Comment by JoeStratton** [comment]
Tried clearing my cache, different browsers and devices, and even different networks. They all show just a blank broken page until i hit the login button. sometimes it will say "error.php took to long to load" or a 503

**Comment by JoeStratton** [comment]
![capture](https://user-images.githubusercontent.com/6180439/29781309-a055d5d8-8bcd-11e7-8d4e-84686a1982f2.PNG)

**Comment by causefx** [comment]
try dev build, this will be out tomorrow.

**Comment by seanvree** [comment]
@causefx  Did this ever get implemented?  I was assuming it would be done by setting the homepage min auth to something other than NONE, right?

![image](https://user-images.githubusercontent.com/8906637/34639014-61865316-f28c-11e7-90bf-22a5709cdcad.png)

When I do this, I get the 404...Of course, I can click on the MENU, then LOGIN, but is there not a way to access the forms login directly?  If not: login.ASPX yo.
