### ISSUE TITLE
Air/libre/sub/madsonic

### ISSUE THREAD

**Issue by Tailchakra** [causefx/Organizr#593]
Is there any love for the *sonics?

AirSonic is the latest fork because Madsonic isn't opensource and sub and libre are depricated, my users use the *sonics quite much, would be amazing to be able to use it within Organizr as well (I don't know about their API). Such as being able to see what's being played on homepage(?)

**Comment by causefx** [comment]
i will have to see if there is an API and what it is capable of doing

**Comment by chrisvdgeld** [comment]
https://github.com/airsonic/airsonic/tree/master/subsonic-rest-api

Theoretically they all use the same API. Airsonic is the most recent version, but it should also work with libre/sub and madsonic. (Same framework, mobile sync also works on all versions).

**Comment by causefx** [comment]
Closing all Feature Requests and will communicated thru FeatHub
