### ISSUE TITLE
Can no longer select Edit Tabs or any other options under it

### ISSUE THREAD

**Issue by kevinb77** [causefx/Organizr#599]
Not sure what happened, but I can no longer select the "Edit Tabs" option or any other options below it. Has anyone else had this issue?

**Comment by si0972** [comment]
how big is the org.log file?

**Comment by QuickShotx** [comment]
Same thing is happening to me.  I've tried reinstalling and the issue just came back, not sure what's going on.    
My Organizr\log\nginx\error.log is just being spammed with this http://imgur.com/a/DnkvK

Org.log also had some errors, but that seemed to be a Radarr Calendar error.... Just disabled that and those errors went away.  Believe I had the wrong URL.

**Comment by si0972** [comment]
@QuickShotx How does /check.php look?

**Comment by QuickShotx** [comment]
@si0972 
Not sure how to tell if anything is wrong, but this is my /check.php

[Check.txt](https://github.com/causefx/Organizr/files/1290861/Check.txt)

**Comment by si0972** [comment]
@QuickShotx I mean screenshot from when you visit domain.com/check.php

**Comment by QuickShotx** [comment]
@si0972 Ah, my bad.  Everything is green and "ready to rock-n-roll"

**Comment by si0972** [comment]
@QuickShotx What size is org,log? its known to cause some issues to the settings.

**Comment by QuickShotx** [comment]
@si0972 It's only about 268KB

**Comment by kevinb77** [comment]
my org.log file under C:\nginx\html is 1455kb

**Comment by haltdev** [comment]
@kevinb77 Reload your site via the browser reload.  Then click on settings tab, and give it 5ish seconds to load before clicking on "Edit Tabs" or any other option.  Does it work then?

**Comment by kevinb77** [comment]
Unfortunately no dice on any browser I use or times I reload the site.

**Comment by haltdev** [comment]
Did you try waiting for 5 or 10 seconds after clicking Setting tab but BEFORE clicking any of the options?

Click Settings.  Wait 10 seconds.  Then click Edit Tabs.

**Comment by kevinb77** [comment]
yes, I waited just like you suggested

**Comment by causefx** [comment]
@kevinb77 @QuickShotx 

delete org.log plz.  For some reason when the file size is above 1.25 MB's it crashed PHP, I have coded some corrections to help in the next update.

**Comment by kevinb77** [comment]
that did it! Thanks for all the help folks!

**Comment by causefx** [comment]
👍
