### ISSUE TITLE
After logging in to organizr the Plex requests search bar is active causing the keyboard to appear on mobile

### ISSUE THREAD

**Issue by SgtBatten** [causefx/Organizr#6]
Requires Plex requests to be the first tab of course, but is it possible to not highlight the search field upon loading? I'd prefer to have to touch it to bring up the keyboard manually.

**Comment by causefx** [comment]
not sure this is possible as the focus is done on Plex Requests' app.  Let me see if I can drive focus away.

**Comment by SgtBatten** [comment]
No worries.

Low priority man.

**Comment by causefx** [comment]
Fixed.
