### ISSUE TITLE
Nginx auth_module and api calls

### ISSUE THREAD

**Issue by solaris765** [causefx/Organizr#603]
This is more of a tip then anything else but I have found that api requests behind the nginx auth_request_module obviously get blocked. However for people who would still like the api available while using the auth module you can setup a secondary location to by pass it for that subdirectory only like so:

--In this block we exclude the auth_request call
>location ^~ /sabnzbd/api {
>    proxy_pass https://127.0.0.1:9090/sabnzbd/api;
>    proxy_set_header Host $host;
>    proxy_set_header X-Real-IP $remote_addr;
>    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
>}
--And in this block we include it
>location ^~ /sabnzbd {
>    auth_request /auth-admin;
>    proxy_pass https://127.0.0.1:9090;
>    proxy_set_header Host $host;
>    proxy_set_header X-Real-IP $remote_addr;
>    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
>}

Now for people familiar with nginx, this might seem obvious, though since I was still learning the nature of location blocks I was unsure if a re-write was necessary with the full path. (kept trying to write my location block as: "location /api" thinking it would work for all my services. 

If there's a better way, please let me know. But for now this is how I've managed to secure my internal sites while maintaining access to api keys without a login.
At least for Sabnzbd haven't tested with anything else yet

**Comment by causefx** [comment]
are you using the keys internally?

**Comment by solaris765** [comment]
I'm using them in an external android application.

**Comment by causefx** [comment]
ahhhh, yeah, that is still on the backburner for me.  I need to think of a solution

**Comment by solaris765** [comment]
Could this even be solved internal to organizr? Or would you need it to be? This is mostly functional as is. 

Though something is up with sonarr and radarr I can query their api's in a web browser but in my app and on the organizr homepage I get nothing. sabnzbd works flawlessly like this though

**Comment by causefx** [comment]
for org, use the whitelist function:

```
	location /auth-admin { rewrite ^ /auth.php?admin&whitelist=vpn.domain.com; }
	location /auth-user { rewrite ^ /auth.php?user&whitelist=vpn.domain.com; }
```

**Comment by solaris765** [comment]
Oh I've got those working, I was talking about using keys externally while the auth-admin blocks where in place. Which is what I got got working with sabnzbd. but not sonarr & radarr, Though at this point I'm sure its my setup for those two

**Comment by causefx** [comment]
yeah, i have auth on all my services they can all access eachother with my whitelist

**Comment by solaris765** [comment]
In your whitelist are you using internal addresses or public reverse proxied addresses?

**Comment by causefx** [comment]
main server public IP and internal server IP

**Comment by solaris765** [comment]
hmm, ok. I'm still getting errors for radarr and sonarr, any clue on this error?

>RADARR ERROR: cURL error 60: SSL certificate problem: unable to get local >issuer certificate (see http://curl.haxx.se/libcurl/c/libcurl-errors.html) | Error
>-- | --
>SONARR ERROR: cURL error 60: SSL certificate problem: unable to get local >issuer certificate (see http://curl.haxx.se/libcurl/c/libcurl-errors.html) | Error

**Comment by causefx** [comment]
what address is listed in homepage settings for radarr/sonarr?

**Comment by solaris765** [comment]
https://domain.ext/sonarr
But I got it.  Not even organizr related. I was using the standard crt file in nginx instead of my crt chain file. http://nginx.org/en/docs/http/configuring_https_servers.html
Thank you for your help!

I now have all reverse proxied api's available inside and outside my network while maintaining the auth_request authentication system.

**Comment by causefx** [comment]
awesome!  good job man!

**Comment by solaris765** [comment]
For the record
---------------------------------
outside <- Nginx for reverse proxy <- apache for Organzr (couldn't get php running well enough on nginx)
All other services also behind nginx.

ssl autorenew with https://github.com/Lone-Coder/letsencrypt-win-simple (which provided the ssl chain and all other crt parts)
