### ISSUE TITLE
Gravatar Background

### ISSUE THREAD

**Issue by rix1337** [causefx/Organizr#61]
Through some extensive testing I found another issue:

If the gravatar is of the same color as the top bar, it becomes invisible. Any chance to add another color for the gravatar background? Or a border for the gravatar?
![bug](https://cloud.githubusercontent.com/assets/9930448/22207706/720dca70-e180-11e6-91ac-b1882604fdeb.PNG)

**Comment by causefx** [comment]
lol, that is weird, i should still show the white in the icon.  I will replicate and fix :)

**Comment by rix1337** [comment]
I've attached my avatar, for testing
![loading](https://cloud.githubusercontent.com/assets/9930448/22211134/685a6428-e18c-11e6-8c7a-420d735cee12.png)

**Comment by causefx** [comment]
ahhhh, transparency.  hmmmm...  yea, no way to fix that without putting a color in the background which defeats the purpose.

**Comment by rix1337** [comment]
alright, that's fine with me. was just looking for ways to beat the system 😄

**Comment by causefx** [comment]
no worries, thanks for bringing it up.  We are getting closer to v1.0

**Comment by rix1337** [comment]
this is exciting 🥇

**Comment by causefx** [comment]
:) right, thanks for the effort.
