### ISSUE TITLE
Synology Not Opening

### ISSUE THREAD

**Issue by mccorkled** [causefx/Organizr#614]
I setup a tab for my server. I get this error:

Blocked by Content Security Policy
This page has a content security policy that prevents it from being loaded in this way.
Firefox prevented this page from loading in this way because the page has a content security policy that disallows it.

**Comment by causefx** [comment]
was the synology option checked in the security settings?

**Comment by mccorkled** [comment]
I'm not sure where you mean.

**Comment by causefx** [comment]
in the DSM settings there should be an option to allow iframing.

**Comment by mccorkled** [comment]
Judging by the security settings, iFraming looks to be allowed.

![1](https://user-images.githubusercontent.com/13697804/31189727-11a6e32a-a907-11e7-8bc4-795ff9987939.png)

**Comment by causefx** [comment]
![image](https://user-images.githubusercontent.com/16184466/31258206-73adb5da-a9f2-11e7-8dde-4d905f819704.png)
un check these two and try again

**Comment by mccorkled** [comment]
The first one did nothing. The seconds one stopped the browser error but still nothing is loading in the window.

**Comment by causefx** [comment]
let me as on Gitter

**Comment by mccorkled** [comment]
Let you on what?

**Comment by causefx** [comment]
ask* sorry.

**Comment by xkelly** [comment]
Having the same issue, as well. I have the same settings as mccorkled. On DSM 6.1.3-15152 Update 8.

**Comment by causefx** [comment]
are you all proxying these or just using the port?

**Comment by xkelly** [comment]
No proxy. just using the port. Also tried the SSL port. Same issue.

**Comment by filoor** [comment]
Any update facing the same problem

**Comment by filoor** [comment]
After disabling 
![image](https://user-images.githubusercontent.com/3647638/33162876-128c3e24-d02c-11e7-9040-165a7e6d3d1f.png)
it works thanks

**Comment by ghost** [comment]
I am still having this issue. Not proxying. Have tried my reverse proxy name, have tried ZeroTier address, have tried LAN IP. Page just shows up blank.
