### ISSUE TITLE
Add option to change current day color on calender

### ISSUE THREAD

**Issue by Saltystew** [causefx/Organizr#617]
I find the light yellow color hard to see at a glance, something similar to the color used in sonarr/radarr would be nice, adding it as an option under theme would work well.

**Comment by causefx** [comment]
custom CSS will do this :)

Also LayerCake will be included in the next update:)  couple more days

**Comment by Saltystew** [comment]
> custom CSS will do this :)

Is there a place in organizr that I'd do that in so it'd persist through updates or your saying just edit the files themselves?

No idea what layercake is but new stuff is always nice to hear about.

**Comment by causefx** [comment]
This area:
Mine will look a little different from yours as im still building the new version

![image](https://user-images.githubusercontent.com/16184466/30769464-b0658194-9fcd-11e7-97d1-40a04561b8ab.png)

**Comment by Saltystew** [comment]
Awesome! Thanks for the help.
