### ISSUE TITLE
Loading URL, Logo URL and Avatar

### ISSUE THREAD

**Issue by chrisvdgeld** [causefx/Organizr#62]
Hi,

I can't seem to add loading icon URL and/or logo icon URL. Whenever I paste one in, save it and refresh it just deletes again. 

Also, how do I add a avatar on my user account?

Other than that, great dashboard!

**Comment by Githubtordl** [comment]
Not sure on your issue with loading icon and logo icon, it's working fine for me but I can help you with the avatar. I didn't realise Organizr had support for Gravatar until rix1337 mentioned in the other thread.

You need to have an account at gravatar.com. Make sure you set the same username that you have on Organizr also on Gravatar, not sure if you need the same email as well but I've gone with the same email & username and it works for me.

**Comment by causefx** [comment]
gravatar is based off of email :) as for the URL, save it and refresh the entire page, not just the iframe.

**Comment by chrisvdgeld** [comment]
Got the loading icon to work, however - it does not delete the current loading icon:

http://puu.sh/twSR8/7d4c68d537.png

I'll try to do the gravatar! Isn't it possible to make a upload avatar option? My users are people like my mother, who do like an avatar but god know how to set up gravatar ;p

**Comment by causefx** [comment]
the pulse will always be there.  As for Avatar, i have to think about it.  Might be able to do something.

**Comment by chrisvdgeld** [comment]
Oh, mixing two loading pictures isn't very nice haha! Will keep the pulse then, it isn't too bad. Just not a fan of the colour.

Thanks!

**Comment by causefx** [comment]
the color changes with the theme.

**Comment by causefx** [comment]
BTW: do you the have the URL of the loading icon you used, so i can see how it looks?

**Comment by chrisvdgeld** [comment]
I was using http://www.brainpecks.com/wp-content/uploads/2014/02/loading-1.gif because I thought it would replace the pulse. Already trying to create a static image that looks nice around the pulse 👍

**Comment by causefx** [comment]
oh ok, Thanks!
