### ISSUE TITLE
Clicking links for emby goes to static url

### ISSUE THREAD

**Issue by untotren** [causefx/Organizr#620]
When on the homepage clicking new media or what's playing, it leads me to app.emby.com, which is not correct.  It should use the URL from the emby tab that I specified, not a static url, since that static URL does not even work for my setup.

**Comment by Magic815** [comment]
+1.

And it should be done in a way that custom ports in the emby tab URL don't mess it up. This is what I was requesting back in #569 .

Nudge nudge @causefx ;)
