### ISSUE TITLE
[Improvement] Clear Plex images cache

### ISSUE THREAD

**Issue by JigSawFr** [causefx/Organizr#625]
Hello,
A great think could be in the future to be able to clear Plex images cache,
I have two images that are blank and so not generated, but don't have the possibility to retry generation of them :)
Another thing, if you change cover in Plex, so changes can't be reflected in Organizr. Why not add a TTL to our image cache ?
Thank you for your great work ;)

**Comment by causefx** [comment]
currently the time is set at:
$cachetime = 604800;

which is 7 days, i can lower it.  I will look into adding a clear cache.

**Comment by causefx** [comment]
Cache clear will be in 1.6

**Comment by Quiksmage** [comment]
Hi, Where is the option to do this? Since some fixes to the plex images, some of my shows still show a blank image. I think that clearing the cache here would fix my issue. Thanks!

**Comment by causefx** [comment]
hover over image on homepage, it will show reload icon.
