### ISSUE TITLE
[Improvement] Add PlexPy support

### ISSUE THREAD

**Issue by JigSawFr** [causefx/Organizr#626]
Hello,
I think we can use PlexPy (if available, else fallback to organize methods) API to have so much infos we need. (Covers cache, stats, last added, currently viewing, users, and many many more).
What do you think about it ?

**Comment by causefx** [comment]
what kinda stats and where would you like them:?

**Comment by jneljeff** [comment]
I think having most watched stats on the homepage would be cool at the very least... or maybe a list of recently watched.  I'd just be happy with SSO for PlexPy.

**Comment by Saltystew** [comment]
I also think it'd be nice to have the names of the users nickname from plexpy for now playing on home page, instead of email or their username.

**Comment by causefx** [comment]
went the SSO route
