### ISSUE TITLE
Unable to create admin account

### ISSUE THREAD

**Issue by TeamDom** [causefx/Organizr#629]
Hi,

Got Organizr installed and started in a Freenas (9.10) Jail, however as soon as I enter the details for an admin account and click to proceed I get:

Fatal error: Call to undefined function hash() in /usr/local/www/Organizr/user.php on line 818

Lines 817 and 818 are (I think):

                // if this is a properly logged in user, this will contain the data directory location for this user
                var $userdir = false;

I'm guessing a permissions error or perhaps a PHP issue but not too sure.  I'm using PHP 5.6.  Had a bit of a Google and look through the issues but can't see anything.  

Any ideas?

Thanks.

**Comment by causefx** [comment]
https://github.com/causefx/Organizr/blob/master/user.php#L818

that line is for hashing the token password.

PHP says it was added in 5.12
http://php.net/manual/en/function.hash.php

Can you update php or run in a docker?

**Comment by TeamDom** [comment]
Unable to run in docker on Freenas and PHP is up to date.  Nevermind, it was just a hope.  Thanks for looking.

**Comment by andrewmiskell** [comment]
I have the same problem, but the hash function was added in 5.1.2 (not 5.12). I have 5.6.x installed so I should have the hash function present.

**Comment by andrewmiskell** [comment]
@TeamDom I figured it out, it's because the hash function is part of a separate package on FreeBSD/FreeNAS and not part of the core php packages.

Do pkg install php56-hash and install that package, then it'll work just fine.

**Comment by TeamDom** [comment]
@andrewmiskell - amazing, that worked a charm.

Thanks a lot.

**Comment by causefx** [comment]
good work guys!
