### ISSUE TITLE
Authorization issue

### ISSUE THREAD

**Issue by chrisnijdam** [causefx/Organizr#631]
Hi!

First of all, I love Organizr, it's very nice. However i'm experiencing soms trouble. I enabled the homepage.php, which is working fine when i'm logged in with an admin account. When a regular user logs in they get the organizr frame and can see all tabs, But when clicked on the homepage a nginx 404 error is shown. When I open the page in another chrome tab the adress shows */organizrerror.php?error=401
I've read that the 401 error in Organizr is an authorization error, but the homepage is enabled for regular users.
I tried updating from the master branch to pre develop but no luck.

Can you help me fix this?

I'm running Organizr on Ubuntu 16.04 with nginx
![1](https://user-images.githubusercontent.com/1921884/31021400-02b22caa-a536-11e7-897b-77a5697a796a.PNG)
![2](https://user-images.githubusercontent.com/1921884/31021404-069e1a86-a536-11e7-9279-86b1eaca2145.PNG)

**Comment by causefx** [comment]
Under edit homepage, what does the first drop down say?

**Comment by chrisnijdam** [comment]
I'm so stupid, it says Admin, i thought it was for the speedtest.
Now it's working fully.
Thank you very much and keep up the good work. I'll put in a donation!

Chris

**Comment by causefx** [comment]
thank you!
