### ISSUE TITLE
on-screen permanent error with both local and ldap auth backend

### ISSUE THREAD

**Issue by Daryes** [causefx/Organizr#636]
When using both local and ldap for user authentification, the following error appears when a local user is used : 
`Warning: ldap_bind(): Unable to bind to server: Invalid credentials in <...>organizr/functions.php on line 37`
No problem with a user from the ldap backend

**Comment by causefx** [comment]
what version are you on?

**Comment by Daryes** [comment]
Latest release (v1.44), installed a few days ago

**Comment by causefx** [comment]
can you update to the latest dev build, we made some changes with LDAP that need to be tested.

**Comment by Daryes** [comment]
Done
First, there's many error when using the 1.44 config.php, like for example :
`Use of undefined constant CHAT - assumed 'CHAT' in organizr/organizr-develop-20171002/index.php on line 137` 
It's related to the fact the 1.44 config.php only have user set/changed variables (around 20 lines) , when the latest dev config has all of then (~ 100 lines)

The way I do an upgrade might have a link with this : I usually download the latest version and unpack it in a dedicated directory, then link the conf+data from the previous version.
The process is automated. This allow me to do a fallback to the previous version in a blink if something is amiss

Back on the ldap issue, when starting the dev branch with the default config, it's still the same with a organizr + ldap backend

- ok when connecting with a ldap user
- getting those errors with an organizr user : 
```
Warning: ldap_bind(): Unable to bind to server: Invalid credentials in /server/websites/organizr/organizr-develop-20171002/functions.php on line 38

Warning: ldap_bind(): Unable to bind to server: Invalid credentials in /server/websites/organizr/organizr-develop-20171002/functions.php on line 38
```
It seems to me the current user credentials are sent to ldap first, or both

Maybe as another option than the current one : 
- define the available backends in the adv settings panel
- store the backend type with each user in the db
- when manually creating a new user on the user management panel, select the used backend (and show/hide the password inputboxes)
 This way each user will have the correct backend, and only when a user is unknown, his credentials will be passed to each backend (all availables, or with an option to be used for new users)


By the way, the advanced settings' tabs should have a subtitle, I didn't recognize the auth tab at first.

Also, the "Domain to use for LDAP" should change the input format to user@domain (with a static user@) : LDAP accept user@domain, Microsoft also allow domain\user

And what is "domain & format" for ? Is it the search filter, the starting OU level, or something else ?
