### ISSUE TITLE
German Translations

### ISSUE THREAD

**Issue by causefx** [causefx/Organizr#64]
German Translations needed.

**Comment by causefx** [comment]
@rix1337 can you hook it up again?

**Comment by rix1337** [comment]
sure thing..

life has sure got me busy right now, but those stings I will update

thanks for the recent updates. I smell 1.0!

**Comment by causefx** [comment]
yes sir!  maybe today or tomorrow.

**Comment by rix1337** [comment]
voila !

keep being awesome

**Comment by causefx** [comment]
damn youre fast

**Comment by rix1337** [comment]
Haha, thanks :)

Its all about timing and priorities. Keeping organizr up2date was important.. and i had time to spare

**Comment by causefx** [comment]
amen, brother.
