### ISSUE TITLE
Homepage editor is extremely sluggish when connected remotely

### ISSUE THREAD

**Issue by Lockszmith** [causefx/Organizr#647]
The homepage editor is very sluggish when connected remotely.

My connection is a speedy one - Google Fiber with symmetrical 100 Mbps up/down.
I'm running Organizr on a docker container, the host machine is connected via wired Ethernet.
The Organizr is behind an nginx-ssl reverse-proxy (I chose to add another layer, so I will not change the organizr container configuration)

When on the LAN everything works fine.
When connecting remotely, the homepage editor is very sluggish.

Please let me know if there is anything I can collect, if a remote session is needed, we can setup one via WebEx from my workplace should that be helpful.

**Comment by causefx** [comment]
what version are you one?

**Comment by Lockszmith** [comment]
I'm on 1.44.
I'm using the docker image made available by linuxserver.io:
https://hub.docker.com/r/lsiocommunity/organizr/

**Comment by causefx** [comment]
1.5 will be out tomorrow. settings page changed all around.

**Comment by causefx** [comment]
@Lockszmith how is this on new version?

**Comment by Lockszmith** [comment]
I'm going to close the issue, as it seems the sluggishness I was previously experiencing seems to be stemming from the plethora of chrome-extensions I have enabled on my remote pc.
The new look shows a lot of promise, However (not opening a new issue yet), the entire settings section is a bit slow to load (with or without those browser extensions)
