### ISSUE TITLE
[Bug] "New Tab" options control previously active row in "Edit Tabs" Screen

### ISSUE THREAD

**Issue by LettuceSnob** [causefx/Organizr#659]
v1.5 Master Branch

When on the Edit Tabs screen, if you add a new tab and then click on "more" to expand options, it will instead expand the previously edited row.

I have not tested all possible scenarios where this is true, but it's at least true when adding multiple rows under "Edit Tabs" without saving in between additions.

**Comment by causefx** [comment]
uh oh... lol.. i will test and fix.

**Comment by causefx** [comment]
fixed in 7055b02
