### ISSUE TITLE
iFrame: "ancestor violates the following Content Security Policy directive"

### ISSUE THREAD

**Issue by that1guy** [causefx/Organizr#661]
If the user logs into organizr, but they area not already logged into plex, then the iframed plex app `plex.mydomain.com` redirects to a new login page at http://app.plex.tv.  This new login page has a header that disallows it to be embeded in an iframe.  e.g. The user cannot get into plex once signed into Organzir.

Does reverse proxying the plex application through nginx allow me to solve this?  If so, can someone please send plex reverse proxy settings?  I haven't been able to get `mydomain.com/plex`to work.. which is why I've been loading plex through my subdomain.

![image](https://user-images.githubusercontent.com/1218940/31323173-c390adba-ac58-11e7-8a4e-1e43063a172c.png)

**Comment by si0972** [comment]
This is a known issue, there is nothing we can do(without getting some pitchforks). Cause have been in contact with the developers, and got a build that was "working"(opening a new window instead of a redirect). Maybe @causefx can update us on the situation(even notify users on readme.md).

**Comment by Starbix** [comment]
This was fixed in PMS 1.9.2 but stopped working again in 1.9.3. Plex is aware of this problem

**Comment by that1guy** [comment]
Since Organizr is (probably) signing the user (I use plex SSO) couldn't Organizr just sign them into Plex too, avoiding this whole issue?

**Comment by that1guy** [comment]
@Starbix Any idea where the plex guys are tracking this issue?  I'd like to keep an eye on that.  Thanks.

**Comment by Starbix** [comment]
https://forums.plex.tv/discussion/comment/1532185
<https://forums.plex.tv/discussion/comment/1532185#Comment_1532185>


Von: Brad Davis <notifications@github.com> <notifications@github.com>
Antworten: causefx/Organizr
<reply@reply.github.com>
<reply@reply.github.com>
Datum: 11. Oktober 2017 at 07:14:47
An: causefx/Organizr <organizr@noreply.github.com>
<organizr@noreply.github.com>
CC: Cédric L. <cedric.laubacher@gmail.com> <cedric.laubacher@gmail.com>,
Mention <mention@noreply.github.com> <mention@noreply.github.com>
Betreff:  Re: [causefx/Organizr] iFrame: "ancestor violates the following
Content Security Policy directive" (#661)

@Starbix <https://github.com/starbix> Any idea where the plex guys are

**Comment by that1guy** [comment]
Thanks.  I've asked the plex forum where we can formally track this.  I see
two alternate solutions, but I'm not entirely sure they are viable.

1) reverse prox PMS and strip the offending headers?

2) determine if there is a way to create a plex.tv browser session for the
user since they used their plex credentials to sign into Organizr anyway?

This seems like an important issue to solve because it really breaks the
entire "first-run" user experience.

Thoughts?

@causefx

**Comment by causefx** [comment]
@that1guy I'm confident that Plex will fix this as they previously fixed it and then recently broke it again.  I will post again in the forums and send them an email.

**Comment by that1guy** [comment]
@causefx Okay, thanks for pushing in the right direction.

**Comment by causefx** [comment]
@that1guy I just emailed Plex's CTO again.  I will update once I hear more.

**Comment by Starbix** [comment]
It's now fixed
https://forums.plex.tv/discussion/comment/1535193#Comment_1535193

**Comment by jonfinley** [comment]
eh....not seeing it. @Starbix. running 1.9.4.4325 and having the isssue.

**Comment by Starbix** [comment]
It's fixed in 1.9.5

**Comment by causefx** [comment]
i replied to that thread.

**Comment by that1guy** [comment]
Okay, so I'm running 1.9.5 PMS and we're a step closer to the goal, but not quite there I think.  Here's a video of what I'm seeing.  https://screencast.com/t/IdHjkFnqOcr

Basically:
1) User signs into organizr
2) User is asked to sign into their plex account within an iframe (good!)
3) When user clicks to sign into plex it opens in a new tab where they can then sign in.
4) Then the user should close plex and go back to the organizr tab and refresh.  (no good :( )

**Comment by that1guy** [comment]
Okay, so it seems Plex has resolved this and there is a decent workflow now.

1. User signs into organizr
2. User is asked to sign into their plex account within an iframe (good!)
3. When user clicks to sign into plex it opens in an external tab where they can then sign in.
4. Then the user should close plex and when they go back back to the organizr plex is magically signed in.

I think we can close this.  And I've opened up this ticket to discuss how to auto-sign-in to applications once the user is inside Organizr. https://github.com/causefx/Organizr/issues/673
