### ISSUE TITLE
Disable weather / Location access

### ISSUE THREAD

**Issue by Fma965** [causefx/Organizr#662]
Can we get an option to disable the weather and therefore also disable the "website wants to know your location" popup

**Comment by dejected1** [comment]
im sure this is a simple answer but,  i don't see any weather functions. I dont have a weather ticker after updating to 1.5.0, i don't see any prompt either asking for location. Im sure im missing something im just not sure what....i cleared my cache and cookies and reset ngnix already.

**Comment by causefx** [comment]
@Fma965 I will add that in.  

Do you have any themes enabled?  Push F12 to see if there is any message.

**Comment by dejected1** [comment]
i had layer cake from version 1.44, advanced. f12 shows errors everything else works fine. error is: 


getWeather @ (index):983
(index):986 grabbing weather
(index):1290 http://organizr.asuscomm.com:9111/807ec5355c754f3f8911e4a2b68d0f27
fg.js:195 Initialized content script
(index):1 Error in event handler for (unknown): TypeError: Cannot read property 'state' of undefined
    at chrome-extension://enmgcoifcfalfohmfibbhiaojhafpehm/content.js:10:24

**Comment by causefx** [comment]
hmmmm, that error isnt related to org.

**Comment by dejected1** [comment]
i got nothing else. where is the ticker supposed to be? is it in on every page or just the homepage. top or bottom.

**Comment by causefx** [comment]
user panel

**Comment by dejected1** [comment]
![image](https://user-images.githubusercontent.com/26720061/31355495-5d77402e-acef-11e7-86df-7189758474a6.png)

**Comment by dejected1** [comment]
Does this help?

![image](https://user-images.githubusercontent.com/26720061/31355740-567c97dc-acf0-11e7-9fac-e0598b8d1a90.JPG)

**Comment by causefx** [comment]
```
(index):885 [Deprecation] getCurrentPosition() and watchPosition() no longer work on insecure origins. To use this feature, you should consider switching your application to a secure origin, such as HTTPS. See https://goo.gl/rStTGz for more details.
```

this is the error it shows.

looks like it needs to switch to https.

**Comment by dejected1** [comment]
girrr. well that's crappy. as i understand it thats not an easy transition. I really don't want to pay for a ssl cert to get a weather ticker. or am i misunderstanding what needs to happen here?

**Comment by causefx** [comment]
CloudFlare offers it free. I can help you set it up :)

**Comment by dejected1** [comment]
Does cloudflare offer free domain hosting too? Right now I'm just using the free domain for my router.

**Comment by causefx** [comment]
you will need a domain.  my suggestions are, google domains or namecheeap

**Comment by dejected1** [comment]
as much as i would like to set this up, having an extra bill for weather seems silly. i know ssl is more secure but i can't justify the cost. if https is the reason then i imagine alot of other users may be having the same issue.... thanks thou.

**Comment by causefx** [comment]
no worries.  Just an FYI, i cant fix this on my end as these are browser rules.

**Comment by dejected1** [comment]
understood. thanks for the help.

**Comment by dejected1** [comment]
Just for a follow up i tested this: if i access organizr as localhost (without https) its given full security features and i am prompted for my location and the weather does work. Im behind a vpn anyway so without being able to set a location manually it doesn't really do much. Just thought id put the resolution here for anyone google it. @causefx wouldn't this work if we just set the location manually instead of prompting chrome to ask for location. As i understand it, the powerful features google has decided to move to https is the location prompt.
