### ISSUE TITLE
Link going wrong place... i'm really not sure how to explain this... VIDEO!

### ISSUE THREAD

**Issue by Fma965** [causefx/Organizr#664]
Link going wrong place... i'm really not sure how to explain this... VIDEO!

Hopefully this makes sense... basically plexpy is loading instead of plex when clicking the icon from my home screen.

**Comment by leram84** [comment]
I can't see the video you posted (says its processing still) but this sounds like an old bug... can you post your custom html you added to make that plex button? I'm guessing you have a line like `window.parent.$("li[name^='"+$(this).attr('tab')+"']").click();` that needs to be replaced with `window.parent.$("li[name='"+$(this).attr('tab')+"']").click();`

**Comment by Fma965** [comment]
i haven't used any custom html, what makes you think that? its all native organizr functionality, and the video is processinig youtube is being slow :/

**Comment by Fma965** [comment]
here is a download link for the video

https://drive.google.com/file/d/0B_6GzxtXtF-sNnBVSWhoX0xTUmM/view?usp=sharing

**Comment by Fma965** [comment]
New video link - https://streamable.com/xmhsl

**Comment by causefx** [comment]
ahhh, i will look at splash code.

**Comment by leram84** [comment]
ahhh yeah, thats splashscreen not homepage. Ok, yeah, i gotcha now... cause will straighten u out :)

**Comment by Fma965** [comment]
yeah i'm sure he will, doesn't bother me in the slightest but as a developer my self i like to report these issues, i know that if you don't report them many more people may have them and you don't even know.

i had a website login issue for months, no one told me till 1 day 1 guy told me, no idea how many users i lost during that.

**Comment by causefx** [comment]
lol i hear that.

**Comment by Fma965** [comment]
:) take your time, even though i'm sure it's a easy fix i can wait :)

Thanks both of you for the quick replies though.

PS: which file is the splash code in?

**Comment by causefx** [comment]
index.php, it is fixed if you wanna pull Pre-Dev

**Comment by Fma965** [comment]
i'm using the linuxserver docker, i know i could manually update it but i'm in no rush.

Thanks

**Comment by causefx** [comment]
sounds good.
