### ISSUE TITLE
plex invite invalid url

### ISSUE THREAD

**Issue by dejected1** [causefx/Organizr#665]
So i had a chance to use the plex invite system for the first time. It generated the email and sends it but when you try and click on the link i get this from google. 
: 
Redirect Notice
 The previous page is sending you to an invalid url (http://organizr.asuscomm.com%5C?inviteCode=KCNJ2O).

 If you do not want to visit that page, you can return to the previous page.

here is the url to the redirect page google sends me to. 
https://www.google.com/url?hl=en&q=http://organizr.asuscomm.com%255C?inviteCode%3DKCNJ2O&source=gmail&ust=1507849543070000&usg=AFQjCNHGEV3gZvFg9HFak1T8hnGEB8MwUQ

So its generating a incorrect url but im not sure why. It also generates two lines in the plex invite interface but it only sends one email.

**Comment by causefx** [comment]
what goes the bottom of the email say?

![image](https://user-images.githubusercontent.com/16184466/31480238-88d1f3ac-aed1-11e7-91e2-e76ce5307313.png)

**Comment by causefx** [comment]
@dejected1 anything on this?

**Comment by dejected1** [comment]
![image](https://user-images.githubusercontent.com/26720061/31531870-a4b48ea4-af9e-11e7-864b-43d670befc01.JPG)

**Comment by causefx** [comment]
is your webserver on windows?

**Comment by dejected1** [comment]
Yes nginx on windows 10

**Comment by causefx** [comment]
gotcha, i will take a look.

**Comment by compil3** [comment]
I have an issue where Plex doesn't send the invite to the user at all, unless this isn't actually automated and requires I manually invite them??

**Comment by causefx** [comment]
@compil3 do you have mail setup in settings?
