### ISSUE TITLE
Updated to 1.50, extremely large tab icons and error messages

### ISSUE THREAD

**Issue by TheFirstQuestion** [causefx/Organizr#666]
I updated to version 1.50 a few days ago. When seeing Organizr for the first time after the update, I immediately noticed two issues: (see screenshot) ![screenshot from 2017-10-07 17-41-27](https://user-images.githubusercontent.com/16431286/31529073-e351fa42-afa4-11e7-841c-8402096794a9.png)

1. My tab icons are super tall (long?), almost the height of my screen. I can't see more than one tab at a time, forcing me to have to scroll very far to switch tabs.

2. I'm getting a lot of error messages (see below). They're mostly concerning undefined constants, but they don't seem to make much sense to me. The area where the errors are appearing push the actual application (Plex, etc) to be lower on the screen and prevent me from accessing controls on the bottom edge.

I'm running Organizr with Apache on (headless) Ubuntu 16.04.3 LTS. If there is anything I can do to fix this problem or to assist you in any way, please let me know! Thank you for everything you do in creating such an awesome tool.

Here are some of the errors I'm getting:

Notice: Use of undefined constant COUCHHOMEAUTH - assumed 'COUCHHOMEAUTH' in /var/www/html/settings.php on line 1135
Notice: Use of undefined constant COUCHURL - assumed 'COUCHURL' in /var/www/html/settings.php on line 1145
Notice: Use of undefined constant COUCHAPI - assumed 'COUCHAPI' in /var/www/html/settings.php on line 1152
Notice: Use of undefined constant CALENDARREFRESH - assumed 'CALENDARREFRESH' in /var/www/html/settings.php on line 1373
Notice: Use of undefined constant AUTHBACKENDDOMAINFORMAT - assumed 'AUTHBACKENDDOMAINFORMAT' in /var/www/html/settings.php on line 1544
Notice: Use of undefined constant CHATAUTH - assumed 'CHATAUTH' in /var/www/html/settings.php on line 1833

**Comment by causefx** [comment]
can you make sure that config/configDefaults.php is still there.

**Comment by TheFirstQuestion** [comment]
It is indeed! I have:

config[2017-10-07_17-26-37][1.40].bak.php  
configDefaults.php
config.bak.php                            
 config.php

**Comment by causefx** [comment]
can you paste the contents of configDefaults.php

**Comment by TheFirstQuestion** [comment]
configDefaults.php:

<?php
return array(
	"database_Location" => false,
	"user_home" => false,
	"timezone" => "",
	"plexURL" => "",
	"plexToken" => "",
	"plexRecentMovie" => "false",
	"plexRecentTV" => "false",
	"plexRecentMusic" => "false",
	"plexPlayingNow" => "false",
 	"plexShowNames" => false,
	"plexHomeAuth" => false,
	"plexSearch" => false,
	"plexRecentItems" => "20",
	"plexPlaylists" => "false",
	"plexTabName" => "",
	"embyURL" => "",
	"embyToken" => "",
	"embyRecentMovie" => "false",
	"embyRecentTV" => "false",
	"embyRecentMusic" => "false",
	"embyPlayingNow" => "false",
 	"embyShowNames" => false,
	"embyHomeAuth" => false,
	"embySearch" => false,
	"embyRecentItems" => "20",
	"sonarrURL" => "",
	"sonarrKey" => "",
	"sonarrHomeAuth" => false,
	"sickrageURL" => "",
	"sickrageKey" => "",
	"sickrageHomeAuth" => false,
	"radarrURL" => "",
	"radarrKey" => "",
	"radarrHomeAuth" => false,
	"nzbgetURL" => "",
	"nzbgetUsername" => "",
	"nzbgetPassword" => "",
	"nzbgetHomeAuth" => false,
	"sabnzbdURL" => "",
	"sabnzbdKey" => "",
	"sabnzbdHomeAuth" => false,
	"headphonesURL" => "",
	"headphonesKey" => "",
	"headphonesHomeAuth" => false,
	"calendarStart" => "0",
	"calendarView" => "basicWeek",
	"calendarStartDay" => "30",
	"calendarEndDay" => "30",
	"authType" => "internal",
	"authBackend" => "",
	"authBackendCreate" => "true",
	"authBackendHost" => "",
	"authBackendDomain" => "",
	"plexUsername" => "",
	"plexPassword" => "",
	"titleLogo" => "",
	"loadingIcon" => "",
	"cookiePassword" => "",
	"domain" => $_SERVER['HTTP_HOST'],
	"registerPassword" => "",
	"smtpHost" => "",
	"smtpHostPort" => "",
	"smtpHostAuth" => "true",
	"smtpHostUsername" => "",
	"smtpHostPassword" => "",
	"smtpHostSenderName" => "Organizr",
	"smtpHostSenderEmail" => "no-reply@Organizr.tld",
	"notifyEffect" => "bar-slidetop",
	"multipleLogin" => "true",
	"loadingScreen" => "true",
	"enableMail" => "false",
	"slimBar" => "true",
	"gravatar" => "true",
	"calTimeFormat" => "h(:mm)t",
	"homePageAuthNeeded" => false,
	"homepageCustomHTML1" => "",
	"homepageCustomHTML1Auth" => false,
	"git_branch" => "master",
	"git_check" => true,
	"speedTest" => false,
	"smtpHostType" => "tls",
	"homepageNoticeTitle" => "",
	"homepageNoticeMessage" => "",
	"homepageNoticeType" => "success",
	"homepageNoticeAuth" => "false",
	"homepageNoticeLayout" => "elegant",
	"ipInfoToken" => "ddd0c072ad5021",
	"historyRefresh" => "120000",
	"downloadRefresh" => "30000",
	"organizrAPI" => "",
	"splash" => "false",
);


ls -lah /var/www/html/config/configDefaults.php:

-rw-r--r-- 1 root root 2.5K Sep 10 13:07 /var/www/html/config/configDefaults.php

**Comment by causefx** [comment]
looks like that file didnt get updated.  is apache running as root?  might want to change persmissions on all the files and manually update that file with the values from the github repo.

**Comment by TheFirstQuestion** [comment]
That fixed it! 

No, apache isn't running as root. Every other file in config is owned by the proper user, just not that one. Weird. But manually updating it fixed both my issues!

Thank you so much for your quick and efficient help, and also for creating such an awesome tool in the first place.

**Comment by causefx** [comment]
No worries!  Thanks and You're welcome!
