### ISSUE TITLE
Splash link to wrong page

### ISSUE THREAD

**Issue by joshuaavalon** [causefx/Organizr#668]
Here is my testing result.

| Tab Name | Enable Splash | Link To |
|:--------:|:-------------:|:-------:|
|   Plex   |      True     |   PlexPy  |
|  PlexPy  |     True     |  Plexpy |

| Tab Name | Enable Splash | Link To |
|:--------:|:-------------:|:-------:|
|   Plex   |      True     |  PlexPy |
|  PlexPy  |     False     |    -    |

| Tab Name | Enable Splash | Link To |
|:--------:|:-------------:|:-------:|
|   Plex   |      True     |   Plex  |
|  2PlexPy |      True     | 2PlexPy |

It seems that it tries to link with partial match not exact match.

**Comment by causefx** [comment]
yes, this has been fixed in dev already.

**Comment by joshuaavalon** [comment]
I close the issue then,
