### ISSUE TITLE
Restore from Backup

### ISSUE THREAD

**Issue by jflatz** [causefx/Organizr#670]
I may be overlooking it but I can not find any documentation on how to restore from a backup.

**Comment by jonfinley** [comment]
In the webui, this option is not available yet. If you extract and place the files in the correct locations, you will be able to restore your installation.

**Comment by jflatz** [comment]
Great. Thanks for the update. Where do I put the file(s)? And do I need to unzip them?

**Comment by causefx** [comment]
unzip, and the files will be in folders they need to go into

**Comment by causefx** [comment]
dont need to stop anythin

**Comment by jflatz** [comment]
I am unable to successfully restore. I'm curious if this is related to #671 as I can also no longer add new tabs, I can only delete existing ones.

**Comment by causefx** [comment]
you have a tab name with quotes?

**Comment by jflatz** [comment]
No I was unable to create on

**Comment by causefx** [comment]
can u screenshot you tab area in settings?

**Comment by jflatz** [comment]
https://imgur.com/a/vJgtG

**Comment by jflatz** [comment]
When adding a new tab, i click save. and it acts as though it saved, but when i refresh the new tab doesn't exist.

**Comment by causefx** [comment]
anything in organzir log?  or nginx logs/?

**Comment by causefx** [comment]
wow nothing since the 17th?

**Comment by jflatz** [comment]
yea :/ thats when I started playing with the special characters mentioned in #671

**Comment by causefx** [comment]
http://sqlitebrowser.org/

download that and change the value.

**Comment by jflatz** [comment]
Bare with me while I try to figure out how to do this. I have Organizr running in a freeBSD jail

**Comment by causefx** [comment]
the file is user.db  it should be in the location when you first setup org.  or goto settings > about and top right will tell you where it is.

**Comment by jflatz** [comment]
What am I changing the value of? I expected to find a tab with a bad name but that's not the case.

**Comment by causefx** [comment]
can you create me an admin account in your org so I can try and find the problem?

**Comment by jflatz** [comment]
I would be happy to but this is not internet facing. It is in my homelab.

**Comment by causefx** [comment]
can you open that port to test?

**Comment by jflatz** [comment]
is there a way you can pm/im your IP so I can whitelist it?

**Comment by causefx** [comment]
sure.  Jump on Gitter chat room plz

**Comment by jflatz** [comment]
message sent
