### ISSUE TITLE
Auto sign-in Ombi, Plex.

### ISSUE THREAD

**Issue by that1guy** [causefx/Organizr#673]
I'm considering applying my time to solving the following issue - please point me towards anyone who has begun trying to solve this..  The problem is that the Organizr user needs to sign into three applications with their Plex credentials.

1) User signs into Organizr with their Plex credentials.
2) Then the user clicks in Organizr to open Plex and is asked to sign-in with their Plex credentials again.
3) Then the user clicks in Organizr to open Ombi and is asked to sign-in with their Plex credentials again.

It seems to me the user should be able to sign into Organizr and then all the other apps should automatically login when the first opens them.  

Any tips on how I should begin solving this?  Building cookies ahead of time for each app (not sure how this is done).  Nginx reverse proxy passes in Plex credentials to app URLs (not sure this will work because Plex and Ombi don't use basic authentication).  Maybe look into Javascript field auto-population (ugly hack).

**Comment by si0972** [comment]
This is currently semi-working in the dev branch, with some undocumented requierd changes that needs to be done.

**Comment by causefx** [comment]
OMBI SSO is complete, Plex SSO is complete but for sub directory proxies only.

**Comment by that1guy** [comment]
@causefx When you say:

> Plex SSO is complete but for sub directory proxies only.

You mean it doesn't work `plex.mydomain.com` and only works for `mydomain.com/plex`, right?

If this is correct would have happen to have nginx plex reverse proxy configs.  I've tried to get this to work but have failed.  Thanks.  Really appreciate this SSO implementation!  Ombi v3 works great!

**Comment by eddgeywing** [comment]
> 1. User signs into Organizr with their Plex credentials.
> 2. Then the user clicks in Organizr to open Plex and is asked to sign-in with their Plex credentials again.
> 3. Then the user clicks in Organizr to open Ombi and is asked to sign-in with their Plex credentials again.
> 
> It seems to me the user should be able to sign into Organizr and then all the other apps should automatically login when the first opens them.

I am still having this issue. I have tried more configurations than I could relate and every single time I still have to click the "Sign In With Plex" button for Ombi and Plex after logging in to Organizr. I am on Organizr 2.0.0-beta.800 and Ombi 3.0.3945. Ombi is setup as a sub-directory. I have never gotten this to work in 6 months of tinkering.

**Comment by si0972** [comment]
@eddgeywing Open new issue, this one is a year old, and related to the implementation
