### ISSUE TITLE
Use Post/Redirect/Get instead of Post

### ISSUE THREAD

**Issue by joshuaavalon** [causefx/Organizr#676]
This is **NOT**  a feature request or bug report. It is about the code. After you submit data using POST, when you tried to go back to previous, the browser says you will resubmit the data or something like that. This can be avoid by using Post/Redirect/Get.

The concept is simple. Instead of returning a page for POST, return a redirect header. So user can navigate only using GET.

[Here  is a simple example.] (https://stackoverflow.com/a/4142969/3673259)

**Comment by causefx** [comment]
fixed in v2

**Comment by joshuaavalon** [comment]
@causefx Any ETA of v2 release? Just curious.

**Comment by causefx** [comment]
hoping beta in a month or so.
