### ISSUE TITLE
Chat SQL error

### ISSUE THREAD

**Issue by JoeStratton** [causefx/Organizr#679]
I get the following error after a few minutes:

Warning: SQLite3::exec(): locking protocol in /config/www/Dashboard/chat/connect.php on line 5

Warning: SQLite3::query(): Unable to prepare statement: 15, locking protocol in /config/www/Dashboard/chat/refreshmessages.php on line 16

Notice: Undefined variable: newmessages in /config/www/Dashboard/chat/refreshmessages.php on line 135

Notice: Undefined variable: newmessages in /config/www/Dashboard/chat/refreshmessages.php on line 141

**Comment by JoeStratton** [comment]
this is using linuxserverio's docker container

**Comment by causefx** [comment]
hmmm
i will look into it

**Comment by JoeStratton** [comment]
Thanks, just a bit more info:

Chat works fine until this error happens. After this error I can still send messages but they do not show up. When i refresh the page the errors go away and it shows me that the message did in fact go through. After a few minutes the error will then return.

**Comment by causefx** [comment]
I will increase the timeouts.
