### ISSUE TITLE
[Feature Request] Email Templates and scheduler

### ISSUE THREAD

**Issue by saitoh183** [causefx/Organizr#680]
Would it be possible to implement a way to save custom messages so that we can easily re-use them. Adding a scheduler so we can set recurring emails. (ie payment reminders)

**Comment by causefx** [comment]
not a bad idea

**Comment by Magic815** [comment]
Just had this same thought about saved messages and glad to see it already mentioned. I'm planning to use the 'Email Users' function to email out initial invites with instructions for creating an Emby account and then signing into Organizr. It would be great to have this message saved in Org so I don't have to keep pasting it in.
