### ISSUE TITLE
Protect Sonarr + Radarr + Transmission via single login?

### ISSUE THREAD

**Issue by joq3** [causefx/Organizr#681]
Hi,

I tried Organizr for the first time yesterday, like the look and the function. But the main reason for wanting to keep everything in one place is to only need one login for everything.
Is it possible to deactivate login for Sonarr + Radarr + Transmission and protect them with Organizr somehow?
Right now all my services are reachable from SSL domains like sonarr.domain.com etc.

Is this something that is possible?

Thank you!

**Comment by Lockszmith** [comment]
Yes, this is exactly what Organizr does best.
You'll need to setup the web server (I use nginx) to limit access to the
services via it's authorization access.
There is full details on how to do it in the wiki.

I'm on s phone right now, later on I'll send you a link to resource I used
to setup my system with Organizr

**Comment by joq3** [comment]
Found the resource here: https://github.com/causefx/Organizr/wiki/Authentication-%7C-Server-Based
But I can't make it work.

This is how my NGINX Reverse proxy is setup, which is a file places in sites-enabled and makes me reach my sites (like tv.domain.com takes me to Sonarr and mov.domain.com takes me to Radarr). This works fine, but I am not sure how to implement everything described in the link above?
`server {
listen 80;
server_name tv.domain.com;
return 301 https://$server_name$request_uri;
}
server {
        listen 443 ssl;
        server_name tv.domain.com;
        ssl_certificate /etc/letsencrypt/live/mydomain.com/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/mydomain.com/privkey.pem;
        ssl on;
        ssl_session_cache  builtin:1000  shared:SSL:10m;
        ssl_protocols  TLSv1 TLSv1.1 TLSv1.2;
        ssl_ciphers HIGH:!aNULL:!eNULL:!EXPORT:!CAMELLIA:!DES:!MD5:!PSK:!RC4;
        ssl_prefer_server_ciphers on;

        location / {
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header Host $host;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
                proxy_pass              http://localhost:8989;
                proxy_read_timeout      90;
                proxy_redirect          http://localhost:8989 https://tv.domain.com;
    }
}
`

"Place a new location block under your server config like this", is this in the nginx.conf or in the file I have the above text in? Because I have multiple server blocks in that file for every subdomain, maybe 10 like the one above.

I only have one user with username admin, and should I disable the authentification on sonarr and radarr after this is up and running?

Please help me out! Thank you!

**Comment by causefx** [comment]
jump on Gitter, we will get you sorted
