### ISSUE TITLE
DNS address could not be found.

### ISSUE THREAD

**Issue by speedyflipper** [causefx/Organizr#682]
I setup tabs for each one of the application (sonarr, radarr) I need however each tab receives the same error "DNS address could not be found.". The computer is capable of pinging the DNS and the server hosting sonarr and radarr.

The homepage is correctly pulling the calendar for sonarr.

The web server which has Organizr is Ubuntu 16.04 and sonarr/radarr are installed on Windows Server 2016. The reverse proxy works correctly as well

**Comment by causefx** [comment]
what address are you using?

**Comment by speedyflipper** [comment]
Im using the internal DNS address which is the same I use when I setup the reverse proxy.

I tried using the ip address and I get a took too long to respond error
