### ISSUE TITLE
Plex links

### ISSUE THREAD

**Issue by roblandry** [causefx/Organizr#683]
Organizr v 1.50
Plex v 1.9.5.4339
I have my plex server behind a nginx reverse proxy with ssl. The link to plex is https://hostname/plex
This works great.

I have noticed that when creating the links on the homepage, it appends /web/... to the link which causes it to not work. ie. https://hostname/plex/web/...

I get a 404 not found error.

I edited the functions.php to correct the error and point directly to the link i provide via the 
homepage ->plex tab.

Starting at line 904:
```php
if (PLEXTABURL) {
	# My Edit
	$address = PLEXTABURL."/index.html#!/server/$server/details?key=/library/metadata/".$item['ratingKey'];
	//$address = PLEXTABURL."/web/index.html#!/server/$server/details?key=/library/metadata/".$item['ratingKey'];
}else{
	$address = "https://app.plex.tv/web/app#!/server/$server/details?key=/library/metadata/".$item['ratingKey'];
}
```
Starting at line 3530:
```php
if (PLEXTABURL) {
	# My Edit
	$link = PLEXTABURL."/index.html#!/server/$server/details?key=/library/metadata/".$results['ratingkey'];
	//$link = PLEXTABURL."/web/index.html#!/server/$server/details?key=/library/metadata/".$results['ratingkey'];
}else{
	$link = "https://app.plex.tv/web/app#!/server/$server/details?key=/library/metadata/".$results['ratingkey'];
}
```
Now, i am not sure if this is a error with my reverse proxy or the code, but i figured i would let you know what i found and what is working.

**Comment by causefx** [comment]
change your plex proxy to:

```
	location /plex/ {
		proxy_pass          http://plex-upstream/;
	}
	if ($http_referer ~* /plex/) {
		rewrite ^/web/(.*) /plex/web/$1? redirect;
	}
```
