### ISSUE TITLE
Plex images not showing on homescreen

### ISSUE THREAD

**Issue by Quiksmage** [causefx/Organizr#684]
Hi, I just installed this today and I'm finding it quite great.

I noticed that on my homescreen the recently added items had blank pictures.
clicking the links work fine and shows information in there and links to the correct item in plex
As you can see, emby's images are loading fine.
![image](https://user-images.githubusercontent.com/12449533/32090958-d57d4ce8-baa6-11e7-8fb4-9f25bbe0f53e.png)

I had originally added plex through my reverse proxy, but tried many variations, none of which will show images

https://domain.com:port/plex/  < nginx reverse proxy
http://192.168.1.30:32400
https://192.168.1.30:32400
https://publicip:publicport
http://publicip:publicport 

I should probably note my settings as well
![image](https://user-images.githubusercontent.com/12449533/32090935-bcb818aa-baa6-11e7-90eb-ffcde44193ef.png)

Since I'm not referencing my plex tab in these settings, I assume it doesn't matter how I have the tab setup, correct?

I have the tab setup through my nginx reverse proxy of https://domain.com:port/plex/

**Comment by gilbN** [comment]
You shouldn't need the port part in the link. Just try /Plex/

**Comment by Quiksmage** [comment]
my organizr is on a different subdomain than everything else, so I don't think I can do that in the tab.

org.domain.com:nginxport
domain.com:nginxport/plex

**Comment by causefx** [comment]
@Quiksmage i will be pushing an update today, it may fix this problem.

**Comment by Quiksmage** [comment]
Thanks!
