### ISSUE TITLE
Multiple Sonarr/Radarr - can't click sequentially through them

### ISSUE THREAD

**Issue by Quiksmage** [causefx/Organizr#685]
Hi, I have 2 Sonarr and 2 Radarr installations
![image](https://user-images.githubusercontent.com/12449533/32091268-45335090-baa8-11e7-81c8-228947c6312e.png)
I have them listed in order in my tabs.
When I click them to intially load, everything is fine. When I try to move from sonarr 1 to 2, once they are both loaded, nothing happens. Same thing with 2 to 1. I get stuck on the initial sonarr or radarr page when trying to move to my other sonarr/radarr page respectively.

I can click on something else other than sonarr and then click the other one just fine.

The same thing happens with radarr.

I don't know if this is a bug with Organizr or just a function of the way the website works with sonarr/radarr, but I thought I'd throw it out here.

On another, but unrelated, note, it'd be great to add multiple radarr/sonarr/plex/etc to the homescreen page if possible :).

Thanks!

**Comment by causefx** [comment]
can you name the tabs something different?

ie.

1. Sonarr
2. Sonarr2

**Comment by Quiksmage** [comment]
yes, URLs are different and the tabs are named differently as well.

see below

![image](https://user-images.githubusercontent.com/12449533/32123402-e1a6c6da-bb18-11e7-9925-ff15ee7a2fcb.png)

The censored part is identical on all 4.
https://domain.com:nginxport/xxx

**Comment by causefx** [comment]
please upgrade to new version just released, then open browser console.  Click on each tab a few times and paste the output of console.

**Comment by Quiksmage** [comment]
I'm in a container :(. I know it's frowned upon to upgrade the version in the container instead of waiting for the container to update.

**Comment by causefx** [comment]
ahh ok, soon then

**Comment by Quiksmage** [comment]
Hi, I've updated to the latest 1.61

When on the sonarr tab, with sonarr 2 loaded already, I get the following

```
(index):1702 https://publicIP:Port/sonarr2 is active already
(index):1702 https://publicIP:Port/sonarr2 is active already
(index):1702 https://publicIP:Port/sonarr2 is active already
```
When going from something else (radarr for instance) to Sonarr 2 to Sonarr 1, it works correctly now showing the following in the console

```
(index):1707 https://publicIP:Port/radarr - reactivating iFrame
(index):1707 https://publicIP:Port/sonarr2 - reactivating iFrame
(index):1707 https://publicIP:Port/sonarr - reactivating iFrame
```

So, since on the new version, I can now go from radarr to sonarr 1 to sonarr 2, but once on a sonarr, I can no longer go to the other sonarr.

When I click radarr, then sonarr 2, then sonarr 1, then sonarr 2, I get the following

```
(index):1707 https://publicIP:Port/radarr - reactivating iFrame
(index):1707 https://publicIP:Port/sonarr2 - reactivating iFrame
(index):1707 https://publicIP:Port/sonarr - reactivating iFrame
(index):1702 https://publicIP:Port/sonarr2 is active already
```

Hopefully this better explains what is going on to you.

This gif doesn't really show my points or clicks, but when I try to go from sonarr 1 to sonarr 2, you can see nothing happens.
![organizr](https://user-images.githubusercontent.com/12449533/32812255-eff4cfd6-c958-11e7-9256-ee2880b5f728.gif)

Thanks!

**Comment by causefx** [comment]
Yes, I have fixed this is dev now.  Update will be out soon.

**Comment by Quiksmage** [comment]
Thanks!

**Comment by Quiksmage** [comment]
I can confirm this is now fixed. Thanks!
