### ISSUE TITLE
iOS problems, Sonarr/Radarr not loading

### ISSUE THREAD

**Issue by joq3** [causefx/Organizr#689]
Hi,

Love the work you are doing! And thank you for the help yesterday!
I have a small problem with using Organizr on my iPhone 6S.
First one is clicking a movie/show on Homepage, some parts are off screen and unreadable.
The other is that when I use Organizr after saving it to my iPhone as an icon/app, sometimes Somarr and Radarr wont load at all. But when trying in Safari it always works which is weird because both are using Safari i think!

Check out pictures here https://imgur.com/gallery/jmc9E

Thank you!

**Comment by causefx** [comment]
No worries!

On the first one, we still need to figure out styling on mobile.  As for the second one, let me test on my iPhone .

**Comment by joq3** [comment]
I understand! It does work sometimes but not always, and when it dont i get stuck like on the screenshot without being able to do anything. In safari it never happens!

**Comment by joq3** [comment]
Did you experience the same issue?

**Comment by causefx** [comment]
they both loaded fine on my phone.

**Comment by joshuata** [comment]
Both Sonarr and Radarr work fine for me, but when I use the "Save to homepage" button Organizr requires me to login every time I load the app.

**Comment by causefx** [comment]
Hmmmm. I can look into persistently storing data on iOS.
