### ISSUE TITLE
BASEURL Support for Dockers

### ISSUE THREAD

**Issue by causefx** [causefx/Organizr#69]
Need to see about adding Base URL support.

**Comment by rix1337** [comment]
if anyone is interested in a docker container with built in nginx, auto updates and fail2ban:
https://github.com/rix1337/docker-organizr

Based on the awesome linuxserver.io container images.

**Comment by causefx** [comment]
@rix1337 do you still have Organizr setup with reverse Proxy?  can you test out this block for me?

```
location ^~ /organizr/ {
proxy_pass http://localhost/Organizr/;
proxy_set_header Host $host;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
}
```

That should forward everything appropriately.

**Comment by rix1337** [comment]
Ah, dang I use Google Inbox and checked the latest github responses.

I am not reverse proxying anymore, your reply about keeping it in the webserver's base just made sense to me. I could try this out later this week. Will be away from my home setup for a few days..

**Comment by causefx** [comment]
no worries, thank you.

**Comment by causefx** [comment]
will work on this later.

**Comment by JoeStratton** [comment]
This would be amazing for container reverse proxy support!
