### ISSUE TITLE
auth_request

### ISSUE THREAD

**Issue by roblandry** [causefx/Organizr#694]
I have auth request setup and am using nginx as a reverse proxy.

I recently setup cachet to display up or down status.

I created a custom php script to check my services which works great.

The last issue i am running into, i am trying to check whether some of my proxied apps are running, however i am getting a response as 401, which is good. 

Is there a way to append the api key or something to get around auth to check whether the service is up (ie. response 200, 301 etc.) instead of a 401?

**Comment by causefx** [comment]
whitelist their domain.

**Comment by roblandry** [comment]
This fixed the problem. Thanks.

**Comment by causefx** [comment]
:)
