### ISSUE TITLE
Null function in /Dashboard/functions.php

### ISSUE THREAD

**Issue by Codehhh** [causefx/Organizr#695]
## PHP Errors:
![image](https://user-images.githubusercontent.com/12055335/32135390-7e46b1e0-bbcc-11e7-8f8a-7078996588a9.png)
```
Warning: array_map(): Argument #2 should be an array in /config/www/Dashboard/functions.php on line 500

Warning: in_array() expects parameter 2 to be array, null given in /config/www/Dashboard/functions.php on line 500
```
## Docker Logs:
![image](https://user-images.githubusercontent.com/12055335/32135383-7135696a-bbcc-11e7-8850-7835b4b431ff.png)

## Steps to reproduce
Pull fresh docker, complete initial setup

**Comment by causefx** [comment]
i think i know the fix.

**Comment by causefx** [comment]
Master has been updated.

**Comment by Codehhh** [comment]
That fixed it, thanks
