### ISSUE TITLE
pfSense Tab issue part 2

### ISSUE THREAD

**Issue by ayoo88** [causefx/Organizr#698]
Hi,

   First off, THANK YOU! for sharing such a great software. Im loving it.

Now on to the issue. At first pfSense was not loading in the tab. But after reading the help section and installing the 

> Chrome: Ignore X-Frame headers by Guillaume Ryder 

i was able to see the tab load pfSense. 

But pfSense seems to be loaded in a fullscreen mode with no Organizr overlay. Due to this, i am unable to tab back and forth between the apps/tabs ive added. So far the only way to get back to Organizr is by refreshing the page.  

I am currently using Chrome, but i also attempted this on Firefox and can confirm the same issue.
Also, i did find a ticket called  PFSense Tab #574 ( now closed ) which advised adding the following to the header: `proxy_hide_header X-Frame-Options;`

Now i figured (assumed..smh to the old saying of this word) i did not need to add what was advised above to the header since the browser plug-in is ignoring it. Also i didnt know what organizr file i would need to nano into, to add that line in the header. (kinda a noob, but i learn quick :-) )

what steps can i take to resolve this? 
also if i did miss a solution to this else where, then sorry about opening this ticket. if you can point to that solution i would appreciate it.

Thanks in advance.

**Comment by causefx** [comment]
Hi there.

If you proxy pfSense.  you can add the hide header to the proxy you created for PF.  If all else fails, I will ask in Gitter if anyone uses PF in their organizr.

**Comment by ayoo88** [comment]
I used nginx and created a proxy for pfSense. Below is the conf file i created under sites-enabled.
not sure if i set this up right since it is still not working.
pfSense still opens with no organizr overlay as the other tabs do
 
```
server {

            listen 80;
            server_name testserver.local;
            location /organizr/#pfSense {

            proxy_hide_header X-Frame-Options;
            proxy_pass "http://192.168.1.1"
                 }
}
```

**Comment by zackbcom** [comment]
To enable the use of pfSense in an I-frame do the following:

1. Edit /usr/local/www/guiconfig.inc:Line 28
Comment out
Header("X-Frame-Options: SAMEORIGIN");

2. Edit /usr/local/www/csrf/csrf-magic.php:Line 120
Change to false
$GLOBALS['csrf']['frame-breaker'] = false;

3. Go to System -> Advanced -> Admin Access - Uncheck Browser HTTP_REFERER enforcement

**Comment by neo-neo1** [comment]
> To enable the use of pfSense in an I-frame do the following:
> 
>     1. Open Diagnostics -> Edit File
> 
>     2. Edit /usr/local/www/guiconfig.inc:Line 28
>        Comment out
>        Header("X-Frame-Options: SAMEORIGIN");
> 
>     3. Edit /usr/local/www/csrf/csrf-magic.php:Line 120
>        Change to false
>        $GLOBALS['csrf']['frame-breaker'] = false;
> 
>     4. Go to System -> Advanced -> Admin Access
>        _Uncheck_ Browser HTTP_REFERER enforcement

This doesn't seem to work with pfSense 2.4.5-p1. Any idea on how to fix it?

**Comment by havy1601** [comment]
@neo-neo1 Have you found a solution to this?
Try to display pfsense webpage on home assistant dashboard as an iframe.

**Comment by x86txt** [comment]
> This doesn't seem to work with pfSense 2.4.5-p1. Any idea on how to fix it?

Hi, I just used this method on 2.6 and it works perfectly.

**Comment by squidds** [comment]
> To enable the use of pfSense in an I-frame do the following:
> 
> 1. Open Diagnostics -> Edit File
> 2. Edit /usr/local/www/guiconfig.inc:Line 28
>    Comment out
>    Header("X-Frame-Options: SAMEORIGIN");
> 3. Edit /usr/local/www/csrf/csrf-magic.php:Line 120
>    Change to false
>    $GLOBALS['csrf']['frame-breaker'] = false;
> 4. Go to System -> Advanced -> Admin Access
>    _Uncheck_ Browser HTTP_REFERER enforcement


![kIv6S1rh4g](https://user-images.githubusercontent.com/64927214/169725783-742d6438-8994-46f4-b41b-684feecbafda.png)

I know this is an old fix, but it did allow the page to load inside of Organizr. Is there a way to supress this warning? It's not allowing me to login.
