### ISSUE TITLE
Admin username with 3 characters not possible

### ISSUE THREAD

**Issue by rix1337** [causefx/Organizr#7]
I tried to use ```rix``` (for obvious reasons) which would not allow me to set up an admin account.

**Comment by causefx** [comment]
I will fix on the next commit.  If you would like to destory the database and start over, you can edit this line: https://github.com/causefx/Organizr/blob/master/js/user.js#L44

change it to: length<2

**Comment by rix1337** [comment]
Thx, that worked superbly!
