### ISSUE TITLE
Cannot access settings

### ISSUE THREAD

**Issue by christronyxyocum** [causefx/Organizr#701]
###### Operating System: Linux Docker Container
<hr>

##### Problem Description:
Just setup the Organizr Docker container, love it by the way, but now, after I login, I cannot go to settings. It gives me a 401 error that I must be logged in. I login again, click settings, same thing. Restarted the container, but that hasn't helped.

Screenshot [HERE](https://i.imgur.com/FdxEiHg.png).

<hr>

##### Reproduction Steps:
Browse to Organizr, login, try to access settings.

<hr>

#### Errors on screen?  If so paste here:
Just an error when the container first starts and Organizr is not running:
```
nginx: [alert] could not open error log file: open() "/var/lib/nginx/logs/error.log" failed (2: No such file or directory)
2017/10/29 13:25:30 [emerg] 549#549: open() "/var/lib/nginx/logs/error.log" failed (2: No such file or directory)
```
I connect to the container, create the dir, create the log file, then chown the dir and file to the abc user, then Organizr is accessible. I do not think this is related to my issue though.

**Comment by causefx** [comment]
sorry, i just sent a fix now, 

Please goto either config/config.php or config/configDefaults.php and edit `multiplelogins` to false

**Comment by christronyxyocum** [comment]
Thanks, but I'm not seeing either file in the /config dir. Do you happen to know the full path?

**Comment by causefx** [comment]
can you repull the docker?  the fix is in there already.  

im not sure how docker handles the path to the config file.

**Comment by christronyxyocum** [comment]
FYI, filepath is:

`/config/www/Dashboard/config/configDefaults.php`

**Comment by causefx** [comment]
awesome!
thanks!
