### ISSUE TITLE
Moved files to new server

### ISSUE THREAD

**Issue by arnie311** [causefx/Organizr#711]
###### Operating System: Windows
<hr>

##### Problem Description:
Moved files from www/ on one server to another and now it is unable to open users.db but I am able to open and view the tables.
error from chrome dev tools
<br />
<b>Fatal error</b>:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [14] unable to open database file' in C:\WPN-XM\www\organizr-old\user.php:173
Stack trace:
#0 C:\WPN-XM\www\organizr-old\user.php(173): PDO-&gt;__construct('sqlite:C:/WPNXM...')
#1 C:\WPN-XM\www\organizr-old\user.php(31): User-&gt;__construct()
#2 C:\WPN-XM\www\organizr-old\index.php(68): require_once('C:\\WPN-XM\\www\\o...')
#3 {main}
  thrown in <b>C:\WPN-XM\www\organizr-old\user.php</b> on line <b>173</b><br />
<br />
<b>Warning</b>:  Unknown: open(C:\WPNXM\temp\sess_0q0hcm7ad6gli3vmmvcv9fk2t2, O_RDWR) failed: No such file or directory (2) in <b>Unknown</b> on line <b>0</b><br />
<br />
<b>Warning</b>:  Unknown: Failed to write session data (files). Please verify that the current setting of session.save_path is correct (C:\WPNXM\temp) in <b>Unknown</b> on line <b>0</b><br />
![screenshot_110117_124114_am](https://user-images.githubusercontent.com/10731453/32261579-8c556460-be9d-11e7-9aa6-07e571c79e5e.jpg)

In case of relevance, I downloaded the newest master and tried run that. It let me create an account but won't let me save new tabs.
{"notify":{"html":"<strong>Settings have been Saved<\/strong>","icon":"floppy-o","type":"success","length":"5000","layout":"bar","effect":"slidetop"},"show_apply":true}<br />
<b>Warning</b>:  Unknown: open(C:\WPNXM\temp\sess_0q0hcm7ad6gli3vmmvcv9fk2t2, O_RDWR) failed: No such file or directory (2) in <b>Unknown</b> on line <b>0</b><br />
<br />
<b>Warning</b>:  Unknown: Failed to write session data (files). Please verify that the current setting of session.save_path is correct (C:\WPNXM\temp) in <b>Unknown</b> on line <b>0</b><br />

I followed the advanced install steps on the first server and moved both edited files over to the new one in the same path

C:\WPNXM\bin\php\php.ini
C:\WPNXM\bin\nginx\conf\domains-enabled\server.conf

<hr>

##### Reproduction Steps:
see above

<hr>

#### Errors on screen?  If so paste here:

```
n/a
```

**Comment by causefx** [comment]
you need to edit config/config.php and edit both userHome and database_Location to new paths.

**Comment by arnie311** [comment]
hmm...fixed that now i see a prompt to create a new admin (that does nothing...resets if i click submit)
and this error in the background:
Warning: Invalid argument supplied for foreach() in C:\WPN-XM\www\organizr\index.php on line 75

**Comment by arnie311** [comment]
![screenshot_110217_093953_pm](https://user-images.githubusercontent.com/10731453/32358740-78fb9a36-c016-11e7-8022-668c248a6200.jpg)
error in background and the only error i can see in the network logs

**Comment by causefx** [comment]
Did you end up getting this to work?
