### ISSUE TITLE
Unable to create new user

### ISSUE THREAD

**Issue by christronyxyocum** [causefx/Organizr#712]
###### Operating System: lsiocommunity/organizr
<hr>

##### Problem Description:
Trying to create a new user results in blank blue info bar at the top of the page.

<hr>

##### Reproduction Steps:
Try to create a new user.

<hr>

#### Errors on screen?  If so paste here:

```

2017-11-01 15:23:18 | foobar on IP 172.17.0.1 is trying to hack your Organizr | Error
-- | -- | --
2017-11-01 15:15:57 | wfender on IP 172.17.0.1 is trying to hack your Organizr | Error
```

**Comment by si0972** [comment]
Try log out, then inn

**Comment by christronyxyocum** [comment]
I swear I tried it, but that did it. Thanks!
