### ISSUE TITLE
Mixed content

### ISSUE THREAD

**Issue by chasgames** [causefx/Organizr#717]
##### Problem Description:
HTTP doesn't load if I make organizr HTTPS.

Mixed Content: The page at  was loaded over HTTPS, but requested an insecure resource. This request has been blocked; the content must be served over HTTPS.
<hr>

Is the best way to use Organizr, to make it HTTP, so it can serve mixed content? Or is there a way to make this work with HTTPS on Organizr?

Thanks!

**Comment by si0972** [comment]
Organizr works on HTTPS. it maybe that you are serving a tab over HTTP, that needs to be TTPS too.

**Comment by chasgames** [comment]
Yes - Just wondering how to keep organizr on HTTPS and still serve mixed contents. Can you proxy HTTP websites to HTTPS through nginx? or is it best just to keep organizr on standard HTTP so you can handle anything. 

Thanks

**Comment by si0972** [comment]
You shouldnt mix, i recomend setting up SSL on all your sites. Which sites do you have trouble with?

**Comment by causefx** [comment]
Yes, proxy everything through nginx.  What services are mixed>?

**Comment by chasgames** [comment]
I like to use this to load some external websites along with local services, and some of the  sites don't support SSL, 

For example, if i want to load http://www.dailymail.co.uk

I'm not too familiar with doing this in nginx, have you got an example? 

I'm using the docker container, so I think i just need to add some kind of location block to my /organizr/config/nginx/site-confs/default   file, and docker-compose restart?
