### ISSUE TITLE
[Translation] NL

### ISSUE THREAD

**Issue by chrisvdgeld** [causefx/Organizr#72]
WELCOME = "Welkom"
OPTIONS = "Opties"
EDIT_INFO = "Bewerk Info"
UPDATE = "Update"
GO_BACK = "Terug"
LOGOUT = "Uitloggen"
LOGIN = "Inloggen"
DO_YOU_WANT_TO_LOGOUT = "Wil je uitloggen?"
YES_WORD = "Ja"
NO_WORD = "Nee"
EMAIL_ADDRESS = "E-mail Adres"
EMAIL = "E-mail"
PASSWORD = "Wachtwoord"
PASSWORD_AGAIN = "Herhaal wachtwoord"
ADMIN = "Adminstrator"
USER = "Gebruiker"
HOLD_UP = "Wacht!"
LOOKS_LIKE_YOU_DONT_HAVE_ACCESS = "Het lijkt dat je geen toegang hebt."
USERNAME = "Gebruikersnaam"
REMEMBER_ME = "Onthouden"
FORGOT_PASSWORD = "Wachtwoord vergeten"
RESET_PASSWORD = "Reset wachtwoord"
DATABASE_PATH = "Database Pad"
SPECIFY_LOCATION = "Specificeer de locatie waar je de database bestanden op wilt slaan."
CURRENT_DIRECTORY = "Huidige map"
PARENT_DIRECTORY = "Bovenliggende map"
SET_DATABASE_LOCATION = "Database locatie instellen"
SET_TIMEZONE = "Tijdzone instellen"
DONT_WORRY = "Geen zorgen! Je database is er nog, zorg ervoor dat je de locatie gebruikt waar je database in staat."
SAVE_LOCATION = "Sla locatie op"
TIME_TO_LOGIN = "Nu je een administator account hebt aangemaakt, kun je inloggen en en beginnen aan je tabbladen..."
AWESOME = "Geweldig!"
REGISTER = "Registreer"
CREATE_ADMIN = "Creëer Adminstrator"
CREATE_ACCOUNT = "Creëer Adminstrator account voor Administrator toegang"
SETTINGS = "Instellingen"
UPLOAD_ICONS = "Upload iconen"
VIEW_ICONS = "Bekijk iconen"
ALL_ICONS = "Alle iconen"
CLICK_ICON = "Klik op het icoon om hem te kopiëren"
TABS = "Tabbladen"
TYPE_HIT_ENTER = "Typ je nieuwe tabblad naam en druk op enter."
ACTIVE = "Actief"
GUEST = "Gast"
NO_IFRAME = "Geen iFrame"
OR = "OF"
DEFAULT = "Standaard"
NEW_TAB_NAME = "Nieuw Tabblad Naam"
TAB_URL = "Tabblad URL"
ICON_URL = "Icoon URL"
SAVE_TABS = "Sla Tabbladen Op"
CHOOSE_THEME = "Kies Thema"
SAVE_OPTIONS = "Sla Opties Op"
TITLE = "Titel"
TITLE_TEXT = "Titel Tekst"
NAVIGATION_BARS = "Navigatiebalken"
TOP_BAR = "Boven Balk"
BOTTOM_BAR = "Onder Balk"
SIDE_BAR = "Sidebar"
HOVER_BG = "Hover Achtergrond"
ACTIVE_TAB = "Actieve Tabblad"
ACTIVE_TAB_BG = "Actieve Tabblad Achtergrond"
ACTIVE_TAB_ICON = "Actieve Tabblad Icoon"
ACTIVE_TAB_TEXT = "Actieve Tabblad Tekst"
INACTIVE_TAB = "Inactive Actieve Tabblad"
INACTIVE_ICON = "Inactieve Tabblad Icoon"
INACTIVE_TEXT = "Inactieve Tabblad Tekst"
LOGIN_STATUS = "Login Status"
LAST_SEEN = "Laatst gezien"
USER_GROUP = "Gebruikers groep"
USER_ACTIONS = "Gebruikers acties"
DELETE = "Verwijderen"
LOGGED_IN = "Ingelogd"
LOGGED_OUT = "Uitgelogd"
GOOD_LOGINS = "Succesvolle aanmeldingen"
BAD_LOGINS = "Mislukte aanmeldingen"
DATE = "Datum"
IP_ADDRESS = "IP Address"
TYPE = "Typ"
NOTHING_LOG = "Niets in log..........."
PURGE_LOG = "Leeg Log"
LOGO_URL_TITLE = "Logo URL Voor Titel"
LOADING_ICON_URL = "Laad Icoon URL"
ABOUT = "Over"
INSTALLED_VERSION = "Geïnstalleerde  Versie"
CURRENT_VERSION = "Huidige Versie"
DELETE_DATABASE = "Verwijder Database"
DELETE_WARNING = "Doe dit alleen als het nodig is voor een upgrade. Hierdoor zal je database verwijderd worden en dit kan niet terug gedraaid worden. Zorg er dus voor dat je een backup hebt, ook van je gebruikers."
SUBMIT_ISSUE = "Dien Aanvraag Of Klacht In"
VIEW_ON_GITHUB = "Bekijk Op GitHub"
CHAT_WITH_US = "Chat Met Ons"
TABS_SAVED = "Tabbladen Opgeslagen!"
APPLY_CHANGES = "Wijzigingen Toepassen"
APPLY_RELOAD = "Wijzigingen toepassen om de pagina te vernieuwen!"
OK = "OKE"
COLORS_SAVED = "Kleuren opgeslagen!"
NEW_VERSION = "Nieuwe Versie Beschikbaar"
CLICK_INFO = "Klik Op Info Tabblad"
WHATS_NEW = "Wat is er nieuw in"
CHANGES = "Veranderingen"
AUTO_UPGRADE = "Automatisch Upgraden"
SOFTWARE_IS = "Software is"
UP_TO_DATE = "Actueel!"
PREVIOUS = "Vorige"
NEXT = "Volgende"
PRINT = "Print"
SEARCH = "Zoek"
SHOW_ENTRYS = "Toon"
ENTRIES = "INZENDINGEN"
SHOW_ENTRY_CURRENT = "Laat %1 tot %2 tot %3 inzendingen zien"

**Comment by causefx** [comment]
Sweet! thank you for this!  I will create a pull request today for this, unless you want to do it so it has your name on the file :)

**Comment by chrisvdgeld** [comment]
I don't mind who's name is on the file! ;). It's all credits to you anyway hehe!

**Comment by causefx** [comment]
LOL, OK, I will make the file.  Thanks!

**Comment by chrisvdgeld** [comment]
Updated the language file. Also fixed a faulty line

**Comment by causefx** [comment]
did you do a pull request?

**Comment by causefx** [comment]
my bad, i just saw you edited it.  Can you tell me which other line you edited?

**Comment by chrisvdgeld** [comment]
I'll figure out the pulling, saves time for you and this way I can keep editting it every time a update comes. 

`SHOW_ENTRY_CURRENT = "Laat huidige inzendingen zien"
`

**Comment by causefx** [comment]
thank you I will fix that line too
