### ISSUE TITLE
'Emby All' backend does not auto-login the first time if 'Remember me' is unchecked

### ISSUE THREAD

**Issue by Magic815** [causefx/Organizr#720]
###### Operating System: Windows 8.1
<hr>

##### Problem Description:

When an Emby user of mine logs into Organizr for the first time, and they check "Remember me," it will create their Organizr account AND seamlessly log them into Organizr.

However, if "Remember me" is not checked on this first log in, Organizr simply says "CREATED USER ACCOUNT FOR NEWNAME & E-MAIL SENT!", but then does not log them in. Instead, the user now has to enter their account info again to sign into Organizr.

Any chance of changing it so that first time Organizr logins work automatically regardless of whether "Remember me" is checked or not?
<hr>

**Comment by causefx** [comment]
works in v2
