### ISSUE TITLE
Emby Homepage - 'Recent Movies/TV/Music/Playing' trows an 504.

### ISSUE THREAD

**Issue by justin-p** [causefx/Organizr#721]
###### Emby Version: Version 3.2.35.0
<hr>

##### Problem Description:
Whenever I try to add Emby to the homepage and enable 'Recent Movies/TV/Music' or 'Now Playing' the homepage trows an 504. Emby is added with its exposed port from docker, no proxy. Happens on a clean install of Organizr. 

<hr>

##### Reproduction Steps:
Add an Emby connection under 'Homepage Settings' and enable any 'Recent' or the 'Now Playing' slider.

<hr>

#### Errors on screen?  If so paste here:
No log entrys in the PHP or NGINX error logs. Just the 504.
```
504 Gateway Time-out

nginx/1.12.2
```

**Comment by Waseh** [comment]
I was wondering why i was suddenly getting 504's but this seems to be the reason. Removed Emby from homepage and it seems to have fixed it.

**Comment by causefx** [comment]
I will have some other emby users test as well.

**Comment by justin-p** [comment]
@causefx No, it also trows a 504. I updated the issue to better reflect that.

**Comment by Waseh** [comment]
I didn't even have anything enabled under Emby, only the hostname filled out. But i would also only get 504's when trying to sign in. When signed in i didnt have any problems. Since removing the info yesterday i haven't had any 504's.

**Comment by justin-p** [comment]
Just noticed if I add an Sonarr connection I get the same problem, only now instead of just not loading the homepage Organizr in its entirety gives a 504. Only way to restore it is to start with a clean install.

**Comment by justin-p** [comment]
For anyone else struggling with this, if you have your containers running in --net=host instead of exposing the ports, stop using --net=host and start exposing them. Did the trick for me.
