### ISSUE TITLE
[Feature Request] htpasswd support for homepage items

### ISSUE THREAD

**Issue by justin-p** [causefx/Organizr#722]
###### Operating System: Ubuntu 16.04 (Organizr runs in a Docker Container.)
<hr>

##### Problem Description:
I currently use htpasswd on some services like Sonarr and Radarr so that they can be 'safely' accessed externally with something like nzb360. 

Organizr does not allow user:pass@ in the URL field on the 'Homepage Settings' tabs. 
```
https://user:pass@domain.tld:port
```

As far as i can see it this means if you use htpasswd for Sonarr/Radarr you can't use the homepage functionally of Organizr for those services. Since characters like : and @ are filtered using a regex filter.

Changing the [urlPattern](https://github.com/causefx/Organizr/blob/f13725a3f09c49776ab1dba2de1f27f987c53f8e/settings.php#L803) in settings.php:
```
([hH][tT][tT][pP][sS]?):\/\/([\w\.\-]{1,250})(?::(\d{1,5}))?((?:\/[^?.\s]+))?
```

to something like [this](https://regex101.com/r/5TXQyP/1):
```
([hH][tT][tT][pP][sS]?):\/\/([\w\.\$\&\+\,\:\;\=\?\@\#\|\'\<>\\.^\*\(\)\%\!\-]{1,250}[:][\w\$\&\+\,\:\;\=\?\@\#\|\'\<>\\.^\*\(\)\%\!\-]{1,250}[@])([\w\.\-]{1,250})(?::(\d{1,5}))?((?:\/[^?.\s]+))?
```
should allow htpasswd's, but could allow a user/admin to break things. Adding a separate option/field for htpasswd could be a nice way to bypass that problem. 

<hr>

##### Reproduction Steps:
Setup Sonarr/Radarr with 'Basic (Browser popup)' authentication (htpasswd) and try to add it to the Organizr homepage.

<hr>

#### Errors on screen?  If so paste here:

```
Fields have errors: sonarrURL!
```

**Comment by si0972** [comment]
Homepage items work fine with internal ip:port, use this instead.

**Comment by causefx** [comment]
Yes, please use local ip.

**Comment by alanmilinovic** [comment]
@Roxedus can you please elaborate, why it is only working for internal ip:port? Is it blocked when it is called inside iframe with public host address?

One of the things that for sure can be done is to make it work in case homepage item is configured to be opened in a new window. @causefx is there a chance that you consider to make it work for at least new window items?

With items configured in "Bookmark" plugin it is all working fine, but problem with bookmarks is that they are all opened in a new window and I cannot add them to the menu where homepage items are located.
