### ISSUE TITLE
TABS are not visible, only white pages

### ISSUE THREAD

**Issue by outkastm** [causefx/Organizr#725]
###### Operating System: Linux
<hr>

##### Problem Description:

Organizr run on the same system with the services i try to connect.
On tabs, i cannot establish a connection if i use localhost:port or 127.0.0.1:port or systemIP:port, nevertheless the ping is successful. I only get white pages
Can only establish a connection if i use my WANIP:port, with the port forwarded on my router. 

<hr>

##### Reproduction Steps:

<hr>

#### Errors on screen?  If so paste here:

```

```

**Comment by causefx** [comment]
can you check browser console?  F12

are you using http or https on tabs?

**Comment by outkastm** [comment]
I'm using https and accessing Organizr through https://WANIP. 
I did some more test. If i access Organizr through https://systemIP, i can connect to services configured with https://systemIP:port. If i access Organizr through http://systemIP, i can connect to services configured with http://systemIP:port.
To access the tabs from external network they have to be configured with WANIP:port and open the ports on my router ? My goal was to access them through Organizr without opening the ports on my router.

**Comment by causefx** [comment]
to access externally you will still need to setup a reverse proxy, which is easy to do.  If you head over to our Discord, https://organizr.us/discord we can help there.

**Comment by si0972** [comment]
To add, organizr doesnt do any sort of magic with your services (reverse proxy), they need to be done by your webserver. There needs to be one atleast one open port in your router, this is for serving the webpage.

**Comment by outkastm** [comment]
Thanks for clarify. I will see then to configure a reverse proxy and see how it works this way.
