### ISSUE TITLE
Can't Login after using Forgot Password and got SMTP error

### ISSUE THREAD

**Issue by Tamburra** [causefx/Organizr#726]
###### Operating System: Ubuntu
<hr>

##### Problem Description:

I recently clicked Forgot Password to check the feature out and got an SMTP connect error.  I now am unable to login to my Organizr cause the password was changed but I didn't get any email.  I do not have another admin account to log into to fix.  I was able to browse the sql lite db but everything is hashed.  What can i do to fix this?  I have also tried looking at the config.php to see if my smtp password was incorrect but it seems to be hashed there as well with some 20 Character hash.  Am I locked out for good?  
<hr>

##### Reproduction Steps:

<hr>

#### Errors on screen?  If so paste here:

```
Error: Mailer Error: SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting
```

**Comment by causefx** [comment]
Edit config.php and Change smtp password. Then reset password again...

Do you happen to use a password manager?

**Comment by causefx** [comment]
inactivity.
