### ISSUE TITLE
Can't get homepage.php to show up for users (Server-based auth)

### ISSUE THREAD

**Issue by l-t-k** [causefx/Organizr#727]
###### Operating System: Docker (linuxserver.io)
<hr>

##### Problem Description:
I try to implement server based authentication as described here: 
https://github.com/causefx/Organizr/wiki/Authentication-%7C-Server-Based
with this nginx default file:
https://pastebin.com/jXM1vLx5
homepage.php settings:
https://imgur.com/a/wkZAQ

Unfortunately, the homepage.php page is not accessable for users. As an admin, I am able to view this page. All other created pages (ombi, sonarr etc.) work as expected.

<hr>

#### Errors on screen?  If so paste here:
Error = 404 (Not found, /error.php was not found on this server.)

**Comment by si0972** [comment]
Why use server auth? You can achive the same, without using sever based auth, by toggling all the homepage elements minimum to users only.

**Comment by kooimens** [comment]
Tried that one already. Same result: Error = 404 (Not found, /error.php was not found on this server.)

**Comment by si0972** [comment]
Thats not how it should react, you would get a 401

**Comment by causefx** [comment]
you dont need a homepage block in nginx

**Comment by l-t-k** [comment]
Removed everything and did a clean new docker pull. Everything is working as expected now! Thanks for the support
