### ISSUE TITLE
[suggestion] Keyboard shortcuts?

### ISSUE THREAD

**Issue by benbar21** [causefx/Organizr#73]
Hey again!

While using Organizr I realized that it may be great if there were some form of keyboard shortcut for navigating between tabs. I'm used to control-tabbing between my various open apps, and think if there were some alternative for Organizr it would become even better.

I am not entirely sure what the shortcuts would be, and not even sure as to the possibility of implementing them, but I figure the following could use some form of shortcut:

Open tab bar
Navigate between tabs (up and down)
Go to currently selected tab
And maybe a quick selector (so like control shift 1 goes to your first tab, for example).

I'm not really sure what keys would work well. Perhaps something like control-left arrow to open the menu, control-up and control-down to navigate between, control-right to enter a tab, and control-shift-number to quickly go to a tab.

Let me know what you think!

Ben

**Comment by causefx** [comment]
let me see what we can do with JS.

**Comment by nkean** [comment]
https://github.com/madrobby/keymaster

**Comment by nkean** [comment]
That bookmark finally came in handy

**Comment by causefx** [comment]
im glad it did!  :)

i also found this: https://craig.is/killing/mice

**Comment by causefx** [comment]
the only thing that sucks is if you are in the focus of the iFrame, it wont work.

**Comment by nkean** [comment]
That one looks a little more polished. Keymaster is still in active dev.

**Comment by causefx** [comment]
yea it works quite nice

**Comment by nkean** [comment]
Ah. That would be a problem.

**Comment by benbar21** [comment]
so I take it ya both like my idea? yay

**Comment by benbar21** [comment]
@causefx I'm happy to test anything out before you push it as a release here, just send me an email if you want me to try something

**Comment by causefx** [comment]
no worries, what timezone you in?

**Comment by benbar21** [comment]
est

**Comment by causefx** [comment]
ahhh ok, I'm in AZ.

**Comment by causefx** [comment]
got the previous tab working

**Comment by benbar21** [comment]
Hey my brother's in Tucson! and exciting

**Comment by causefx** [comment]
lol nice, previous and next are done.... Ctrl+Shift+Up/Down

**Comment by benbar21** [comment]
Great!

So are the only two ctrl-shift-up and ctl-shift-down? Or is there some way to open the menu too so we can see where each app is?

I suppose for the other part of a quick switcher there could be another option for each tab as to what number it is for the quick switch, and then ctl-shift-[#] would go to that tab? 

Again, thanks for all the speedy responses/development, it's really impressive

**Comment by causefx** [comment]
there is also, "S S" which will take you to settings.  As for the #'s we will only be able to goto 9 tabs, so let me think about that one.  There is no way that I know of that will drive focus away from the iframe.

**Comment by benbar21** [comment]
I don't understand this stuff beyond a few courses I took in first year but there seem to be some (supposed) ways of doing it according to some stackoverflow people?

Like:

http://stackoverflow.com/questions/5076409/return-focus-from-iframe-to-parent
http://stackoverflow.com/questions/7208064/prevent-an-iframe-from-stealing-focus

Sorry if these links are useless haha. But there must be some way... hmm

**Comment by causefx** [comment]
those guys are talking about after the destroy an iframe.... :(

**Comment by benbar21** [comment]
hmm, I'll try to ask a few friends if they have any ideas!

**Comment by benbar21** [comment]
could you implement something in the iframe that when selected selects something outside the frame? (I have no idea if that even makes sense)

**Comment by causefx** [comment]
That won't work as we can inject any js to the iframe if not in same domain, and if we were able to, it would cause a loop where you wouldn't be able to do anything in the iframe.

**Comment by chrislessard** [comment]
@causefx is right with that last comment, and subverting that feature would be a pretty huge security problem for iframes in general. That being said, is it not at least possible to give the window focus on an initial page load? Even if that meant setting the focus to some superficial element (i.e. an empty div) outside of the iframe, it would be better than nothing.

**Comment by causefx** [comment]
I haven't checked the initial load but I believe the parent has focus if I'm not mistaken. I should check.

**Comment by causefx** [comment]
@benbar21 i just coded it so the first 9 tabs have the short cut CTRL+SHIFT+1 through 9
