### ISSUE TITLE
Whitelist

### ISSUE THREAD

**Issue by roblandry** [causefx/Organizr#731]
This is more of a question than an issue.

I have a camera that i am going to reverse proxy with nginx. I embeded the basic auth for the camera in the reverse proxy block which works fine. I am trying to use Organizr as a one stop shop and would like to use its auth to lock it down.

First, is it possible to whitelist based on location tags? Im not trying to open up Organizr, just allow access to the stream from a particular ip address.

Secondly, is it possible to display the login page if not authenticated? Since the ip address of the camera is different than my server, i just get a blank page.

**Comment by roblandry** [comment]
Ok, i figured it out myself.
I added an additional authorization block, specifically for the camera, and whitelisted what i wanted there. That way, the camera is not following the normal auth method for all other reverse proxy blocks.

Additionally I commented out the exit(); found on line 24 of error.php. It appears it stops the script from running if the error is anything other than a 404.

**Comment by causefx** [comment]
that exit is for when there is a $_GET and sets a cookie and carries on.

**Comment by roblandry** [comment]
Hmmm, then any idea what is causing it to not display? I even tried making the correct full url to the error.php script, but was just a blank page. Now that its not exiting, it is working, but i would assume that by commenting that out it is potentially breaking other things...

**Comment by causefx** [comment]
what error is it trying to display?  the error code.

**Comment by roblandry** [comment]
401

**Comment by causefx** [comment]
that is very strange
