### ISSUE TITLE
Plex users can't login with their email-address as username

### ISSUE THREAD

**Issue by l-t-k** [causefx/Organizr#732]
Ombi have this feature build-in. Users can use their email address instead of their username to login.

**Comment by causefx** [comment]
in settings for plex username do you have your plex username or plex email?

**Comment by l-t-k** [comment]
Checked that one already. Have them both. Relatively older accounts have a username different than their email. New users have an username equal tot their email (and are thus the only one able to use their email to login)

**Comment by causefx** [comment]
this is good to go now on pre-dev

**Comment by l-t-k** [comment]
You're right. Should have mention that one in OP. Thanks (again) for the fast response!

**Comment by causefx** [comment]
no problem.
