### ISSUE TITLE
Auth Admin on subdomain not working anymore

### ISSUE THREAD

**Issue by JigSawFr** [causefx/Organizr#734]
###### Operating System: Ubuntu
<hr>

##### Problem Description:

Auth are checked on subdomain for admin (auth.php?admin)
It's working on main domain -> 200
But don't work anymore on subdomain -> 401
It worked before ;) Maybe a change on auth verification

**Comment by causefx** [comment]
it is working on my subdomains.  

Can you check the following:

Log out and log back in to Organzir.

In settings, what is filled in for domain name

**Comment by JigSawFr** [comment]
It seems that I've a Nginx config problem, I'm investigating:
`017/11/21 08:40:42 [error] 332#332: *1602 auth request unexpected status: 500 while sending to client, client: 172.17.0.1, server: monitoring.mu-domain, request: "GET /auth.php?admin HTTP/1.1", host: "monitoring.my-domain.fr", referrer: "https://monitoring.my-domain.fr/"
`

**Comment by causefx** [comment]
sorry i just saw that you edited your message.

here is the location blocks for main server block:
```
	location /auth-admin { rewrite ^ /auth.php?admin&whitelist=vpn.sonflix.com; }
	location /auth-user { rewrite ^ /auth.php?user&whitelist=vpn.sonflix.com; }
```

here is my include for including the auth location blocks into subdomains:
```
location = /auth-admin {
	proxy_pass https://web.home.lab/auth-admin;
	proxy_pass_request_body off;
	proxy_set_header Content-Length "";
}
location = /auth-user {
	proxy_pass https://web.home.lab/auth-user;
	proxy_pass_request_body off;
	proxy_set_header Content-Length "";
}
```

**Comment by causefx** [comment]
you could also turn on debug in auth.php temporarily to see the status codes.
