### ISSUE TITLE
Chat is showing "Invalid date" within date/time stamp in Safari only

### ISSUE THREAD

**Issue by Tamburra** [causefx/Organizr#735]
###### Operating System: Ubuntu
<hr>

##### Problem Description:

Within my chat window I am getting invalid date where the time stamps should be.  Instead of the date and time.
<hr>

##### Reproduction Steps:

<hr>

#### Errors on screen?  If so paste here:

```

```

**Comment by causefx** [comment]
is this a new error or has it always been like that?

**Comment by Tamburra** [comment]
I have had the date and time stamp actually display correctly just last week on the same version of organizr.  I have deleted the chat database through advanced settings and since then it hasn't displayed correctly.

**Comment by Tamburra** [comment]
I should have tested this before on different browsers.  My bad.  This seems to be a Safari browser problem i assume as the date and time displays fine in chrome and firefox. I am on a fully updated OSX High Sierra computer.

**Comment by causefx** [comment]
I will code in a browser check.

**Comment by Tamburra** [comment]
I have not looked at the code to see how the timestamp code is displayed but will check later.  I did find this thread that might have some helpful information though.  I will report back with my findings when i get time if there aren't any updates by then.

https://stackoverflow.com/questions/4310953/invalid-date-in-safari
