### ISSUE TITLE
ombi v3 not working on home page

### ISSUE THREAD

**Issue by dejected1** [causefx/Organizr#736]
###### Operating System: Windows 10 x64
<hr>

##### Problem Description:
I added ombi v3 to the home page but it doesn't seem to work. 

I get the error: Undefined offset: 0 in C:\nginx\html\functions.php on line 4951

Ombi is v 3.0.2363

<hr>

##### Reproduction Steps:
add ombi. 

<hr>

#### Errors on screen?  If so paste here:

```
Notice: Undefined offset: 0 in C:\nginx\html\functions.php on line 4951
```

![image](https://user-images.githubusercontent.com/26720061/33092135-7bf8734a-ceb6-11e7-8110-1dadb085af17.jpg)

**Comment by causefx** [comment]
I will look into this one

**Comment by zybeon** [comment]
I also receive a page full of errors when enabling Ombi for the homepage. Boxes appear for requested content but doesn't display the boxart. I don't see any search box for ombi (should there be one?). Also all other tabs are gone and I can't change any settings through the user interface anymore.

Undefined index: access_token in /var/www/******/html/functions.php on line 4847
Warning: Illegal string offset 'posterPath' in /var/www/******/html/functions.php on line 4930
Warning: Illegal string offset 'theMovieDbId' in /var/www/******/html/functions.php on line 4932 
Warning: Illegal string offset 'title' in /var/www/******/html/functions.php on line 4933 
Warning: Illegal string offset 'posterPath' in /var/www/******/html/functions.php on line 4934 
Warning: Illegal string offset 'posterPath' in /var/www/******/html/functions.php on line 4934 
Warning: Illegal string offset 'approved' in /var/www/******/html/functions.php on line 4935 
Warning: Illegal string offset 'available' in /var/www/******/html/functions.php on line 4936 
Warning: Illegal string offset 'denied' in /var/www/******/html/functions.php on line 4937 
Warning: Illegal string offset 'deniedReason' in /var/www/******/html/functions.php on line 4938 
Warning: Illegal string offset 'requestedUser' in /var/www/******/html/functions.php on line 4939 
Warning: Illegal string offset 'userName' in /var/www/******/html/functions.php on line 4939 
Warning: Illegal string offset 'id' in /var/www/******/html/functions.php on line 4940 
Warning: Illegal string offset 'requestedDate' in /var/www/******/html/functions.php on line 4941 
Warning: Illegal string offset 'releaseDate' in /var/www/******/html/functions.php on line 4942 
Warning: Illegal string offset 'posterPath' in /var/www/******/html/functions.php on line 4930 
Notice: Uninitialized string offset: 0 in /var/www/******/html/functions.php on line 4930 
Warning: Illegal string offset 'theMovieDbId' in /var/www/******/html/functions.php on line 4932 
Notice: Uninitialized string offset: 0 in /var/www/******/html/functions.php on line 4932 
Warning: Illegal string offset 'title' in /var/www/******/html/functions.php on line 4933 
Notice: Uninitialized string offset: 0 in /var/www/******/html/functions.php on line 4933 
Warning: Illegal string offset 'posterPath' in /var/www/******/html/functions.php on line 4934 
Notice: Uninitialized string offset: 0 in /var/www/******/html/functions.php on line 4934 
Warning: Illegal string offset 'posterPath' in /var/www/******/html/functions.php on line 4934 
Notice: Uninitialized string offset: 0 in /var/www/******/html/functions.php on line 4934 
Warning: Illegal string offset 'approved' in /var/www/******/html/functions.php on line 4935 
Notice: Uninitialized string offset: 0 in /var/www/******/html/functions.php on line 4935 
Warning: Illegal string offset 'available' in /var/www/******/html/functions.php on line 4936 
Notice: Uninitialized string offset: 0 in /var/www/******/html/functions.php on line 4936 
Warning: Illegal string offset 'denied' in /var/www/******/html/functions.php on line 4937 
Notice: Uninitialized string offset: 0 in /var/www/******/html/functions.php on line 4937 
Warning: Illegal string offset 'deniedReason' in /var/www/******/html/functions.php on line 4938 
Notice: Uninitialized string offset: 0 in /var/www/******/html/functions.php on line 4938 
Warning: Illegal string offset 'requestedUser' in /var/www/******/html/functions.php on line 4939 
Notice: Uninitialized string offset: 0 in /var/www/******/html/functions.php on line 4939 
Warning: Illegal string offset 'userName' in /var/www/******/html/functions.php on line 4939 
Notice: Uninitialized string offset: 0 in /var/www/******/html/functions.php on line 4939 
Warning: Illegal string offset 'id' in /var/www/******/html/functions.php on line 4940 
Notice: Uninitialized string offset: 0 in /var/www/******/html/functions.php on line 4940 
Warning: Illegal string offset 'requestedDate' in /var/www/******/html/functions.php on line 4941 
Notice: Uninitialized string offset: 0 in /var/www/******/html/functions.php on line 4941 
Warning: Illegal string offset 'releaseDate' in /var/www/******/html/functions.php on line 4942 
Notice: Uninitialized string offset: 0 in /var/www/******/html/functions.php on line 4942 
Warning: Illegal string offset 'childRequests' in /var/www/******/html/functions.php on line 4951 
Warning: Illegal string offset 'childRequests' in /var/www/******/html/functions.php on line 4951 
Notice: Uninitialized string offset: 0 in /var/www/******/html/functions.php on line 4951 
Notice: Uninitialized string offset: 0 in /var/www/******/html/functions.php on line 4951

![error](https://user-images.githubusercontent.com/361249/33738438-38b9c1ca-db67-11e7-83f0-a7c9d6ed3873.png)

**Comment by dejected1** [comment]
after 1.7.0 update this seems to work now.

**Comment by justinpeterson13** [comment]
I’m currently having this issue but on Org 1.7.0, Ombi 3.0.3004 Any ideas?

**Comment by jordandrako** [comment]
Same problem on Org 1.7.5 and Ombi 3.0.3000

**Comment by MatthewYax** [comment]
same thing... 

Warning: Illegal string offset 'posterPath' in /var/www/organizr/functions.php on line 5046

Warning: Illegal string offset 'theMovieDbId' in /var/www/organizr/functions.php on line 5048

Warning: Illegal string offset 'title' in /var/www/organizr/functions.php on line 5049

Warning: Illegal string offset 'posterPath' in /var/www/organizr/functions.php on line 5050

Warning: Illegal string offset 'posterPath' in /var/www/organizr/functions.php on line 5050

Warning: Illegal string offset 'approved' in /var/www/organizr/functions.php on line 5051

Warning: Illegal string offset 'available' in /var/www/organizr/functions.php on line 5052

Warning: Illegal string offset 'denied' in /var/www/organizr/functions.php on line 5053

Warning: Illegal string offset 'deniedReason' in /var/www/organizr/functions.php on line 5054

Warning: Illegal string offset 'requestedUser' in /var/www/organizr/functions.php on line 5055

Warning: Illegal string offset 'userName' in /var/www/organizr/functions.php on line 5055

Warning: Illegal string offset 'id' in /var/www/organizr/functions.php on line 5056

Warning: Illegal string offset 'requestedDate' in /var/www/organizr/functions.php on line 5057

Warning: Illegal string offset 'releaseDate' in /var/www/organizr/functions.php on line 5058

Warning: Illegal string offset 'childRequests' in /var/www/organizr/functions.php on line 5067

**Comment by causefx** [comment]
This has been caused by Omni and fix is in develop. Waiting on push to master.

**Comment by gillespies** [comment]
Any update here guys?

**Comment by causefx** [comment]
You will have to check on Ombi GitHub as the issue was on their end
