### ISSUE TITLE
Extra user class "superuser" request

### ISSUE THREAD

**Issue by rourke** [causefx/Organizr#737]
###### Operating System: Ubuntu
<hr>

##### Request
I would like to have a 4th user class. Besides guest, user and admin I'd like to have a "superuser" in between user and admin. This allows me to elevate my friends account that can support me in applications not accesible by users (Sonarr, Radarr), but prevents access to admin-only applications (Wetty, Deluge).

**Comment by si0972** [comment]
This is beeing done in V2. It is still EARLY ALPHA, so just hold your horse a bit more.
