### ISSUE TITLE
[suggestion] pass through tab's title to browser tab

### ISSUE THREAD

**Issue by benbar21** [causefx/Organizr#74]
I'm not really sure how to explain this in terms of which words to use so sorry if the title makes no sense!

So with NZBGet the browser tab for NZBGet provides a really basic status of the app: how many things are downloading and at what speed.

In organizr the browser tab only shows organizr. Would it be possible to pass through the current active tab's text or whatever it is called? I feel like it may not be, but it'd be really useful if it is.

Thanks!

**Comment by causefx** [comment]
yea, we can have it change the title of the tab.  thats easy

**Comment by causefx** [comment]
done

**Comment by benbar21** [comment]
Woah, that was fast!

But it's not exactly what I meant. So now it passes through whatever the tab is called, which is much better than before, but I more meant passing through the tab that the app in the iframe itself provides. 

So for example, nzbget through organizr now shows "NZBGet", because that's what I named the tab.
nzbget directly, however, currently shows "[70] 56.7 MB/s - NZBGet". And it updates every few seconds with a new download count and speed. Is it possible to have that show? 

thanks again,

ben

**Comment by causefx** [comment]
ahhhh, yeah thats not possible.  Well, not entirely possible...  meaning...... if the page is hosted on your server, then yes in theory we should be able to parse it through jQuery, but the code would break once it ran into a hiccup.... such as, from another domain etc.....

**Comment by benbar21** [comment]
Yea I figured that it wouldn't be possible, though wasn't really sure why haha.

Having the current tab is still great though, thanks. If you wanted to try to keep the Organizr branding on it a bit more you could do something like 'Organizr - NZBGet'. It'd be entirely reasonable for you to do that, in my opinion at least.

**Comment by causefx** [comment]
:) it's all good.  The main page will have it on startup so thats good with me.

**Comment by droric** [comment]
Is there a setting that needs to be changed or a trick to get this to work with Chrome?  I am trying to use this feature to help automate password entry for a 3rd party password management program.  My tab shows 'Organizr V2' regardless of what tab I have selected.  I also tried with Edge with no success.

**Comment by causefx** [comment]
@droric what version are you running?

**Comment by droric** [comment]
I just upgraded to 2.0.270 but the issue seems to remain.  I've tried it in Edge and Chrome on 2 different computers and it seems to be the same result.  The tab always shows 'Organizr' as the title.

**Comment by causefx** [comment]
docker or native?

**Comment by droric** [comment]
It's running as a FreeNAS jail.

**Comment by droric** [comment]
I can confirm this is now working after the update today.

**Comment by causefx** [comment]
sorry about that. i hadn’t pushed a build to master in a while.
