### ISSUE TITLE
Cannot login anymore - how to reset the password

### ISSUE THREAD

**Issue by gabriellluz** [causefx/Organizr#740]
###### Operating System: Windows
<hr>

##### Problem Description:
I can't login anymore. I want to change tabs and customize it but I can't anymore. I don't know what happened but I didn't create a password. I've tried to remove it and reinstall it but the same problem occurs. How do I reset the password? (I didn't even set up one password)

<hr>

##### Reproduction Steps:
I just try to setup but no success.

<hr>

#### Errors on screen?  If so paste here:

```

```

**Comment by causefx** [comment]
Not sure how that is possible, as when Organizr is first setup, you have to create an Admin account.  Did you setup smtp?

**Comment by gabriellluz** [comment]
Yes, I did. But it shows me no option to actually recover or reset the password. Can you provide me a link?

**Comment by gabo77** [comment]
You could update the value un users.db directly. You can get in there with `sqlite3 users.db` while in the `www` directory. You would need to update both the hashed password and token.

For example, the following will update the token and the password hash corresponding to the string `password` for the first user created in the DB, which would be the original admin user:

`UPDATE users SET password = '4f18b92010c3bbed6516152f556428727d6f527c3c160a91de70ecce09dc008d' token = '2d778635d06883540c6b2e96d568dc5d' WHERE id = 1;`

You can then login with the password `password`

**Comment by EvilMilkshake** [comment]
This happens with each update. Editing the DB with the above doesn't allow a login.

**Comment by causefx** [comment]
nothing changed with the DB.  seems like something happened on the update.  can you use the backup db it created?

**Comment by EvilMilkshake** [comment]
There was nothing in the backups folder, nor anything in the user folder besides a folder with the username. I'm wondering if this docker container is misbehaving.

I tried to restore with a backup copy of the config folder, and that didn't work either. I can recreate the container, but no way of restoring my settings it seems.

**Comment by gabriellluz** [comment]
Hi. I don't know but I did a clean reinstall and it works. It didn't happen to me on last update.

**Comment by EvilMilkshake** [comment]
Interesting. This has happened more than once, and I nuked everything and did a clean install before this last update. 

Is it possible to have an option to not require a login? I don't use this in an environment that requires one.
