### ISSUE TITLE
[Feature Request] Loading Mini-game (instead of just icon)

### ISSUE THREAD

**Issue by k2trf** [causefx/Organizr#741]
Had an interesting /r/ShowerThoughts just now, related to the loading screen/icon.

I sometimes change up my icon from a little pool of them I have, just to mix it up at different points. But sometimes (especially on mobile data, when I'm just peeking), it can take quite a while to load (like a solid minute or two).

What if, instead of just watching a gif animated, we could instead/additionally have a little JS game run, like Chrome does when you can't load a page (go to chrome://network-error/-106 to see it in action), presumably because of no internet connection.

Just hit start/tap to start the game, and same to jump. The ability to change the 9 sprites in use (Dino, Clouds, Small Cacti, Large Cacti, Tri Cacti, Bird, Road and Sun/Moon) if one desired would be phenomenal as well. That'd be rather neat, and easy (left click or tap if on mobile), but makes it somewhat interactive whilst you're waiting.

You can see it if you go to a URL that won't parse, but since its actually a part of Chrome, I figured including the hard link may help to dig at its code.

-----

EDIT: I was about to way-overcomplicate this. Shower Thoughts may be good, but they don't create a nominal working mental pattern. Somebody has already ripped it out so it can be played online, from any browser, here: http://apps.thecodepost.org/trex/trex.html

Just viewing the source (view-source:http://apps.thecodepost.org/trex/trex.html) shows that the entire thing is JS, plus the 3 audio files and 2 sprite sheets. I'll leave the links to my keybase, where I had pulled these resources from, as that site still uses IDs to reference the files.

Rendered: http://k2trf.keybase.pub/chrome-game
Raw: https://keybase.pub/k2trf/chrome-game/index.md

-----

So this just got boiled down to "here's some JS and five external resources. Can we have a way to use something like this in lieu of a loading image? Or maybe switch between the two?"

**Comment by causefx** [comment]
this is a cool idea, it just outside my scope, sorry.
