### ISSUE TITLE
Server auth breaks some Sonarr/Radarr icons

### ISSUE THREAD

**Issue by bdelwood** [causefx/Organizr#742]
###### Docker: 17.05.0-ce
<hr>

##### Problem Description:
It appears that server authentication through Nginx breaks some icons in Sonarr/Radarr. Namely, the "Install Latest" icon does nothing when clicked. Also, the "Search for..." and "Update movie/series info and scan disk" icons in the movie/series pane does not work right. After selecting the icon a "[refreshmovies]" or "[moviessearch]" notification is supposed to come up, but it never does. Both icons have animations for after they're clicked too. The popup message for running the commands twice in a row works though. The scan/search still activates (checked logs), but there's no indication of it on the web interface. 

I pinned it down to the server auth by removing the "auth_request" lines from the location blocks as a test. Sure enough, the behavior afterwards is as expected.  

I am using the organizr and letsencrypt docker images from lsioarmhf. I am using the letsencrypt nginx to reverse proxy to my Organizr container and the Sonarr/Radarr containers. The nginx config is default in the Organizr container, but the relevant parts of the nginx main server block is as follows (only Radarr shown as an example):

```
server {
        listen 443 ssl default_server;

        root /config/www;
        index index.html index.htm index.php;

        server_name _;

        ssl_certificate /config/keys/letsencrypt/fullchain.pem;
        ssl_certificate_key /config/keys/letsencrypt/privkey.pem;
        ssl_dhparam /config/nginx/dhparams.pem;
        ssl_ciphers 'ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-DSS-AES128-GCM-SHA256:kEDH+AESGCM:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-DSS-AES128-SHA256:DHE-RSA-AES256-SHA256:DHE-DSS-AES256-SHA:DHE-RSA-AES256-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:AES:CAMELLIA:DES-CBC3-SHA:!aNULL:!eNULL:!EXPORT:!DES:!RC4:!MD5:!PSK:!aECDH:!EDH-DSS-DES-CBC3-SHA:!EDH-RSA-DES-CBC3-SHA:!KRB5-DES-CBC3-SHA';
        ssl_prefer_server_ciphers on;

        client_max_body_size 0;


        error_page 401 = @error401;
        location @error401 {
        return 302 /index.php;
        }

        error_page 400 401 402 403 404 405 408 500 502 503 504 /error.php?error=$status;




        # Organizr
        location / {
                proxy_pass http://[Organizr Docker]:80;
                #proxy_intercept_errors on;
                include /config/nginx/proxy.conf;
        }

    # Radarr
    location /radarr/ {
            auth_request /auth-admin;
            proxy_pass http://[Radarr Docker]:7878/radarr/;
            add_header X-Frame-Options "SAMEORIGIN";
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

       location /auth-admin {
                internal;
                rewrite ^ /auth.php?admin;
                proxy_pass_request_body off;
                proxy_set_header Content-Length "";
                proxy_set_header X-Original-URI $request_uri;
    }
}
```

#### Images

![2017-12-10 8](https://user-images.githubusercontent.com/19536361/33802867-e65f0eb8-dd4f-11e7-8d08-89ff31169db6.png)
![2017-12-10 6](https://user-images.githubusercontent.com/19536361/33802875-f1bf97a0-dd4f-11e7-9252-5e2d9679dfc4.png)
![2017-12-10 9](https://user-images.githubusercontent.com/19536361/33802876-f4026c04-dd4f-11e7-9c2a-09ec449c6f4b.png)

```

```

**Comment by si0972** [comment]
I use server auth with radarr/sonarr, and i dont see the same behaviour as you describe.
Would you mind trying out some other /auth-admin locations?
`
location /auth-admin {
internal;
proxy_pass http://192.168.1.2:8282/auth.php?admin;
proxy_set_header Content-Length "";
}
`

**Comment by bdelwood** [comment]
Worked perfectly. Must've not been redirecting requests to Organizr correctly. Thanks!
