### ISSUE TITLE
Organizr fresh install won't save any settings

### ISSUE THREAD

**Issue by petwri** [causefx/Organizr#743]
###### Operating System: Ubuntu 16.04
<hr>

##### Problem Description:

After a fresh install of Organizr, I cannot save any settings.
<hr>

##### Reproduction Steps:
Edit any setting within Organizr, after reloading the page the settings will be reset to default values.
Screen message shows that the settings are saved. The database path  `/var/www/html/organizr/` has the proper permissions for the user `www-data`:

```drwxrwxr-x  6 www-data www-data 4096 Dec 12 21:14 organizr```

<hr>

**Comment by elmerfdz** [comment]
Try installing via the auto installer script: https://github.com/causefx/Organizr/wiki/Linux-Installation#auto-installer-for-linux-debianubuntu-only

Delete the organizr folder before you do.

**Comment by petwri** [comment]
@elmerfdz thats what I already did in the first place.

**Comment by elmerfdz** [comment]
Is this a fresh Ubuntu install as well?
Do you remember which option you used on the script?
Open check.php and see if there are anything marked in red.
What's your db path? is it /var/www/html/organizr/db ?

**Comment by petwri** [comment]
The database path is /var/www/html/organizr/, the ubuntu install of course is not a fresh one, and everything is green on check.php

**Comment by petwri** [comment]
Is there any way to check more detailed logs for organizr?

**Comment by elmerfdz** [comment]
Sorry! a bit busy at the moment, try our [Discord](https://discordapp.com/invite/TrNtY7N), someone will help you out

**Comment by causefx** [comment]
when you click save, what does browser console say?  it should have the data being saved.

**Comment by petwri** [comment]
Yes, it says that the settings have been saved, but after a refresh of the
page, they get reverted to the previous values.

**Comment by petwri** [comment]
Ok. I just did a fresh install with purging all nginx files and redownloading the latest version. Database from check.php says "/var/www/html/organizr/db/users.db Permissions: 644 /var/www/html/organizr/db/users.db is writable!"

**Comment by petwri** [comment]
Oh, and I forgot: problem still the same.

**Comment by petwri** [comment]
After a little help over on discord I finally figured out what it was: cache.
Doing the same settings on chrome in incognito worked just fine.
