### ISSUE TITLE
API invite-user only invites specific user

### ISSUE THREAD

**Issue by vertig0ne** [causefx/Organizr#745]
###### Operating System: Ubuntu
<hr>

##### Problem Description:

Invite user on API does not invite user but instead invites CauseFX
<hr>

##### Reproduction Steps:
Use API to invite any user.

<hr>

#### Errors on screen?  If so paste here:
```
No errors
```

**Comment by causefx** [comment]
this was a work in progress.... api hasnt been touched yet.  :(
