### ISSUE TITLE
Transmission on the homepage doesn't work

### ISSUE THREAD

**Issue by deandmx** [causefx/Organizr#750]
###### Operating System: MacOS
<hr>

##### Problem Description:
Entering Transmission credentials for the homepage doesn't show any downloads

<hr>

##### Reproduction Steps:
Settings > Edit Homepage > Transmission. Enter credentials, go to homepage. Transmission is there but doesn't show the active downloads. Checking the logs shows this error:

<hr>

#### Errors on screen?  If so paste here:

```
TRANSMISSION ERROR: could not connect - check URL and/or check token and/or Username and Password - if HTTPS, is cert valid
```

**Comment by dimitrijp** [comment]
try using url like this http://localhost:9091/transmission/, change the RPC_url name if using something different than default /transmission/

**Comment by causefx** [comment]
What url was used?

**Comment by deandmx** [comment]
So I've tried: 
http://10.0.1.2:9091/transmission/web/
http://10.0.1.2:9091/transmission/
http://10.0.1.2:9091/

To no joy. I get the same errors.

**Comment by G4Zz0L1** [comment]
Yep, me too. I can access the http://localhost:9091/ without problem, even by outsite network (I've ddns) but Organizr can't fetch it, and it returns the same error: `TRANSMISSION ERROR: could not connect - check URL and/or check token and/or Username and Password - if HTTPS, is cert valid
`

**Comment by dannyvfilms** [comment]
EDIT: Disregard. Removed localhost IP and actually used the word localhost. That fixed the issue. Leaving comment for future newbies like me.

I've gone through the same steps updating the link from G4Zz0L1's last post, but I am having the same issue. Granted, I wasn't able to hack the code at all
