### ISSUE TITLE
Notifications whether an app is offline or online

### ISSUE THREAD

**Issue by gabriellluz** [causefx/Organizr#752]
###### Operating System: Windows/MacOS/Ubuntu
<hr>

##### Problem Description:

<hr>

I suggest that a notification system is created so that we know if an app is offline. It can help us to know if a service stopped running or something like that. We could have notifications and, when we access the apps line-up, the icon gets a red flag when it's offline.

**Comment by seanvree** [comment]
Are you talking a "pop-up" notification?  Becuase The red/green indicator is already implemented. 

Also, use the below site for feature requests:

https://feathub.com/causefx/Organizr
