### ISSUE TITLE
Plex invite email does not direct to server address

### ISSUE THREAD

**Issue by dejected1** [causefx/Organizr#753]
###### Operating System: Windows 10 x64
<hr>

##### Problem Description:
Referencing issue: #665. The link generated from the plex invite email does not include the needed port for my server address. Server address requires a port at end of domain to work for me. IE: domain.com:9999 
<hr>

##### Reproduction Steps:
The email has several iterations of the link. First the line that says:
"Head over to my website and enter the code to join: domain.com:9999" 

This line is correct. When its clicked it brings me to my server but does not prompt me to enter in a invite code.  Then when clicking on the button that says "use invite code", it takes me to 

http://domain.com/?inviteCode=AAAAA

This is wrong. If i add the port manually to the address it sends me to, in other words i make the url manually say:

http://domain.com:9999/?inviteCode=AAAAA

it works fine. It then brings up the invite code screen and seems to work.  Lastly the link all the way on the bottom of the email does not include my required port. It just says:

domain.com

Again, if i change it to domain.com:9999 it works fine. 

<hr>

#### Errors on screen?  If so paste here:

```

```

**Comment by GCandez** [comment]
You need to include the port on your NGINX configs, for instance:
Change:
```nginx
server_name domain.com;
```
to

```nginx
server_name domain.com:9999;
```

**Comment by dejected1** [comment]
Worked like a charm. Never would have thought to change that since ngnix specifies a listening port right above the server name.
