### ISSUE TITLE
Edit Homepage -> Password fields being modified

### ISSUE THREAD

**Issue by 1activegeek** [causefx/Organizr#755]
###### Operating System: Alpine - Docker
<hr>

##### Problem Description:
If editing anything in the Edit Homepage section of settings, the nzbget password gets replaced with a string that looks like the hashed version of the password being entered. The problem is that anytime a change is made, one needs to go back to the nzbget settings and alter the password again.

EDIT: It would appear this applying to ALL password fields. I noticed that suddenly my Plex base authentication wasn't happening properly, and I also had a note for Transmission - > which never seems to work actually.

<hr>

##### Reproduction Steps:
1. Login to Org
2. Go to the Edit Homepage section.
3. Set a username/password for NZBget and save.
4. Validate password is set in config.php properly.
5. Go to Edit Homepage in Org and make a change to ANY other section besides NZBget, and save.
6. Read out config.php file having wrong password set now.
7. Additionally or alternatively, check NZBget logs to notice new requests coming in with username:pass which are incorrect. 

Additionally, you can use the setting of Transmission password or Plex password as well. 

<hr>

#### Errors on screen?  If so paste here:
From Organizr Logs:
```
2017-12-19 09:54:05 | NZBGET ERROR: could not connect - check URL and/or check token and/or Username and Password - if HTTPS, is cert valid
```

**Comment by causefx** [comment]
Do you have a password manager installed on that computer?

**Comment by 1activegeek** [comment]
I do - 1Password. Seems using Chrome without the browser extension enabled, it's fine. Is there any type of workaround? Or a way to alter the behavior of these being able to be automatically filled without this happening? I've never had a site automatically fill in suggested passwords or anything.

**Comment by causefx** [comment]
Let me read up more on these password manager behavior

**Comment by 1activegeek** [comment]
Thanks, I'm going to try running some testing as well to validate if I can isolate it being 1Password or Safari browser suggestions. I have an inkling that it's actually Safari suggested passwords. I'll let you know what I can find out.
Transmission however, is still an issue. I don't know if it should, but even with no password, it's showing the transmissionPassword line in the config file but no transmissionUsername line. I think this may be why Transmission is error-ing out because it may be passing a null password when there isn't one enabled.

**Comment by 1activegeek** [comment]
Ok so I went to do some testing, and it seems 1Password is the culprit. I re-enabled the extension in Chrome first, and was able to see this behavior as soon as I attempted a new save. So I'd say the target is definitely 1Password doing something, somehow - or interacting in some odd way it would seem. Let me know if there is anything I can do to help test/debug. Happy to try as this is a nuisance when I'm making changes. Have to keep remembering to use Chrome vs Safari so I don't have to keep making changes.

As mentioned - Transmission still shows this behavior. I think this may be due to a bug since I know this was a newer Homepage option. I'm wondering though if this has anything to do with the proxying? I know for Transmission in my nginx block I have an extra attrib and another block for the RPC and Upload connections:
```
  location /transmission {
    proxy_pass  http://transmission:9091;
    proxy_pass_header X-Transmission-Session-Id;
    include /config/nginx/auth-admin.conf;
    include /config/nginx/proxy.conf;
  }
  location /rpc { ## Required for Transmission
    proxy_pass  http://transmission:9091/rpc;
    include /config/nginx/auth-admin.conf;
  }
  location /upload { ## Required for Transmission
    proxy_pass  http://transmission:9091/upload;
    include /config/nginx/auth-admin.conf;
  }
```

**Comment by causefx** [comment]
Thanks for all the info.  We will nail it down.  As for transmission. You are using the proxy url in homepage settings? Can you try the local up address instead.

**Comment by 1activegeek** [comment]
Correct - if I set it to the proxy URL, it works. If I try using the local IP:Port - I get the error messages. I'm running these and all my apps in Docker containers. So in this instance, Org and Trans are running on Bridge2, which has name resolution. So using `http://transmission:9091` should be working as all my others map the same: NZBget = `http://nzbget:6789`. Minus the pass snafu of course. ;)

**Comment by causefx** [comment]
fixed in v2
