### ISSUE TITLE
Can't purge Organizr logs via UI Purge Data button

### ISSUE THREAD

**Issue by 1activegeek** [causefx/Organizr#756]
###### Operating System: Alpine - Docker (LS.io)
<hr>

##### Problem Description:
Trying to cleanup logs from testing, and unable to do so. Login logs are purging fine, but Organizr logs are not able to be purged through the UI. 

Checked on permissions on filesystem, and the following is the output (of note, using PUID/PGID to match local filesystem perms per usual LS.io containers):
```
-rw-rw---- 1 storage users  3799 Dec 19 11:10 loginLog.json
-rw-r--r-- 1 storage users 16435 Dec 19 11:10 org.log
```
Tried altering permissions on org.Log to 664 and 777, restarted containers to make sure changes take effect - still no good. As mentioned, loginLog.json is properly getting purged, but not org.log.
<hr>

##### Reproduction Steps:
1. Login to console.
2. Open View Logs section.
3. Select Organizr Logs button.
4. Click Purge Logs.
5. Message pops: Settings could not be saved
6. Validate on command line, logs are not cleared

<hr>

#### Errors on screen?  If so paste here:
```
Settings could not be saved
```

**Comment by causefx** [comment]
allow me to look into this

**Comment by causefx** [comment]
fixed in v2
