### ISSUE TITLE
make help easier to find

### ISSUE THREAD

**Issue by ytjohn** [causefx/Organizr#760]
I was trying to figure out how to close side by side with no luck.  If you go to settings -> help & chat, that brings up discord.  It was only after asking in a channel on there that I learned of a second help area (settings -> about -> help).

The About page has links to github, chat, and the actual help documentation.  Having a very obvious [?} button that says "Help and Chat", but doesn't provide the help screen gives the impression that the only help available is through the chat.

**Comment by si0972** [comment]
I cant say why "about" didnt get changed. but the discord "help" was a sudden change that got added. I doubt you will see a change in V1.

**Comment by christronyxyocum** [comment]
This can probably be closed.
