### ISSUE TITLE
Add Refresh Button for the Frames

### ISSUE THREAD

**Issue by brookd2404** [causefx/Organizr#763]
###### Operating System: Windows/MacOS/Ubuntu
<hr>

##### Problem Description:
Great work on Organizr, I love it. 
Just one request, can you please add a refresh button to reload the current frame only? 

At the moment I am right-clicking, selecting - This Frame - Reload Frame. 

Thanks 

<hr>

##### Reproduction Steps:

<hr>

#### Errors on screen?  If so paste here:

```

```

**Comment by causefx** [comment]
its currently in the user menu on the right.

**Comment by Lockszmith** [comment]
Also, double-clicking the icon will refresh the page.
