### ISSUE TITLE
Add ldap_bind configuration to auth settings

### ISSUE THREAD

**Issue by andrewrmoore** [causefx/Organizr#764]
###### Operating System: Debian 9 (Stretch)
<hr>

##### Problem Description:

When attempting to authenticate using LDAP against an Active Directory server, if anonymous auth is disabled, you must provide a user to initiate the bind connection.

In php-ldap this can be done using the ldap_bind function.
http://php.net/manual/en/function.ldap-bind.php

An example application that I've used that does this with php-ldap is Icinga 2, screenshot of their configuration page:
https://www.xinux.net/images/1/1b/Ldap-icigna-resource.jpg

<hr>

##### Reproduction Steps:

Configure LDAP auth against an Active Directory server and attempt to logon using domain/user.

My config:
```
Server: ldap://home.domain.co.uk:389
Basic Domain: dc=home,dc=domain,dc=co,dc=uk
Advanced Domain: sAMAccountName=s,ou=Users,dc=home,dc=domain,dc=co,dc=uk
```
<hr>

#### Errors on screen?  If so paste here:

In php log:
```
2018/01/09 14:04:14 [error] 712#712: *4707 FastCGI sent in stderr: "PHP message: PHP Warning:  ldap_bind(): Unable to bind to server: Invalid credentials in /var/www/organizr01.home.domain.co.uk/html/functions.php on line 112" while reading response header from upstream, client: 172.16.1.15, server: www.organizr01.home.domain.co.uk, request: "POST / HTTP/1.0", upstream: "fastcgi://unix:/run/php/php7.0-fpm.sock:", host: "172.16.1.16", referrer: "https://domain.co.uk/"
```
In Organizr log:
```
user tried to sign-in with the wrong password
LDAP could not authenticate
```

**Comment by causefx** [comment]
can you try v2? or update to 1.75

**Comment by Tilton53** [comment]
Use for the BindDN in 2.0 "Domain\%s" for MicrosoftAD with sAMaccountname
