### ISSUE TITLE
Organizr rendered unusable with "Strict site isolation" activated.

### ISSUE THREAD

**Issue by riccla0321** [causefx/Organizr#765]
###### Web Browser: Chrome 63.0.3239.132
<hr>

##### Problem Description:
Iframes in Organizr was completely unclickable. I figured out why.
After recent events with the reveal of Meltdown and Spectre, I took the security precaution of enabling "Strict site isolation" in Chrome, since Google won't update it until the end of January. When this is activated, Organizr doesn't work. 

I'm not sure if that is how Organizr is supposed to react to that setting, but I just wanted you to know, in case this would become a permanent issue with Chrome after the update.

<hr>

##### Reproduction Steps:
In Chrome, go to [chrome://flags/#enable-site-per-process](chrome://flags/#enable-site-per-process) and activate "Strict site isolation".

<hr>

**Comment by causefx** [comment]
interesting...

I did enable it and tried on orgv1 and it would not let me click around unifi site.

I added that same site to orgv2 and it worked fine...

I will have to see what I did different.

![image](https://user-images.githubusercontent.com/16184466/34786950-de79128c-f5f2-11e7-8f3f-f0b952da7f12.png)
