### ISSUE TITLE
[Feature Request] Homepage Transmission - ability to hide seeding/completed downloads

### ISSUE THREAD

**Issue by Lockszmith** [causefx/Organizr#768]
posting here because http://feathub.com/causefx/Organizr is not accessible. Seems like http://feathub.com is not accessible to me for some reason.

Update: feathub is online, posted there as well: https://feathub.com/causefx/Organizr/+36

**Comment by causefx** [comment]
Closing all Feature Requests and will communicated thru FeatHub
