### ISSUE TITLE
After visiting the site getting the following error

### ISSUE THREAD

**Issue by lastb0isct** [causefx/Organizr#77]
Fatal error: Uncaught PDOException: could not find driver in /var/www/html/dash/user.php:164 Stack trace: #0 /var/www/html/dash/user.php(164): PDO->__construct('sqlite:/var/www...') #1 /var/www/html/dash/index.php(150): User->__construct('registration_ca...') #2 {main} thrown in /var/www/html/dash/user.php on line 164

Any idea what could be causing this?  It looks to be an issue with the database.  Whenever i set the database location/timezone it pops back out to that same error.  I had your previous dashboard installed on this same machine so it should have all the necessary requirements.

**Comment by causefx** [comment]
Php 5 or 7?

Goto check.php and see what it says about PDO

**Comment by lastb0isct** [comment]
Ah, thats pretty cool...sorry, not a big web guy.

PDO SQLite not loaded...
&
Zip is not loaded...

**Comment by causefx** [comment]
Install PDO SQLite and zip on your Linux machine. Almost home. I'll help you out.

**Comment by lastb0isct** [comment]
Just need to know what the PDO SQLite package is on Ubuntu/Debian.  I installed unzip so fine there...

**Comment by causefx** [comment]
`sudo apt-get install php7.0-sqlite`

**Comment by lastb0isct** [comment]
Thanks! That did it...i tried php7-sqlite...

**Comment by causefx** [comment]
sweet!
