### ISSUE TITLE
[Feature Request] Import/Export of tabs configuration

### ISSUE THREAD

**Issue by Lockszmith** [causefx/Organizr#770]
posting here because http://feathub.com/causefx/Organizr is not accessible.

I have my entire system setup in a group of docker-compose folders.
It would make everything much more easier to duplicate if the tab list could be exported and imported separately from the rest of the configuration database.

Update: feathub is online, posted there as well: https://feathub.com/causefx/Organizr/+34

**Comment by causefx** [comment]
Closing all Feature Requests and will communicated thru FeatHub
