### ISSUE TITLE
Webpage Garbled On First Install

### ISSUE THREAD

**Issue by peternm22** [causefx/Organizr#774]
###### Operating System: Windows 10
<hr>

##### Problem Description:
I can't seem to get Organizr installed properly. The webpage is all garbled up (almost as if the CSS or javascript isn't loading). This is what it looks like:
![garbled](https://user-images.githubusercontent.com/5466762/35203339-92783776-fedc-11e7-9acd-42072e5bbeb9.png)
<hr>

##### Reproduction Steps:

I originally tried to install on Caddy, and it produced the garbled web pages. I thought it might just be Caddy, so I decided to try Nginx and loaded a fresh copy of all the Organizr files. The result is identical. I ran check.php and everything comes up okay there. I tried loading the webpage in both Firefox and Chrome, same result for both.

Obviously I'm missing a setup step somewhere. Any ideas?

<hr>

#### Errors on screen?  If so paste here:

```

```

**Comment by causefx** [comment]
Do you have pihole installed?

**Comment by peternm22** [comment]
I've been meaning to try out pihole, but I don't currently have it going. I thought it may be Ublock Origin blocking things, but disabling it doesn't help.

Antivirus is plain old Windows Defender, so nothing fancy there.

**Comment by causefx** [comment]
can you open up browser console to see what is happening?

**Comment by causefx** [comment]
Please submit new issue if this is still happening.
