### ISSUE TITLE
Actor/Actress profile pictures are broken.

### ISSUE THREAD

**Issue by CorneliousJD** [causefx/Organizr#775]
Organizr Version: V 1.7
Branch: Master
WebSever: Nginx
Operating System: unRAID Docker
<hr>

##### Problem Description:

Actor profile pictures are shown as broken links.
![image](https://user-images.githubusercontent.com/724777/35606125-46e033b8-061b-11e8-996a-8ea59b610864.png)

<hr>

##### Reproduction Steps:

Add any movie and on homepage recent media it will show actor images, but they are broken.
<hr>

#### Errors on screen?  If so paste here:

No specific errors, but here's an example.
It tries to load this image.
https://image.tmdb.org/t/p/w150/o6O7WP3vokKstxJFMiiyRMNyPsH.jpg

w150 is not a supported image size.
w500 seems to be widely supported by all. a smaller size may work, but this is seemingly a recent problem w/ movie posters from tmdb.org as well. Had to submit same bug to Ombi team and he made a code correction to load w500 instead of w150.

**Comment by causefx** [comment]
Thanks. I noticed this today as well.

**Comment by jneljeff** [comment]
For reference here is the thread where Travis Bell states these sizes aren't officially supported. 
 Alternatively you can grab w154 which seems to work instead...  [https://www.themoviedb.org/talk/5a5bf3860e0a260d9d0013c5](url)

**Comment by jneljeff** [comment]
You can change this by hand without waiting for an update by editing homepage.php line 974.  Just change the w150 to w154.

`result += '<div class="col-lg-4 col-xs-4"><div class="zero-m"><img class="pull-left" style="border-radius:10%;margin-left: auto;margin-right: auto;display: block;" height="100px" src="https://image.tmdb.org/t/p/w154'+value['profile_path']+'" alt="profile"><h5 class="text-center"><strong>'+value['name']+'</strong></h5><h6 class="text-center">'+value['character']+'</h6></div></div>';`

**Comment by causefx** [comment]
fixed
