### ISSUE TITLE
[Feature Request] Add simple link to popup page in another tab

### ISSUE THREAD

**Issue by fabiomanzoni** [causefx/Organizr#776]
###### Operating System: Windows/MacOS/Ubuntu
<hr>

##### Problem Description:

Please add support for http linking outside the iframe ( to be available as a simple popup to a new window or in a new tab in browser). This would allow to add pages that doesn't accept being used in "iframes" (like Synology DSM without reducing security).

This is important for newbie users (my wife for example :) ) to have a unique main page that has all the links that are important to memorize (even those that cannot be put in a iframe). It is nice to have Organizr opening all important pages in a iframe, however it would be better to allow also creating popup windows for those that are not compatible with iframes.

Thanks,
<hr>

##### Reproduction Steps:

<hr>

#### Errors on screen?  If so paste here:

```

```

**Comment by causefx** [comment]
This is already there. On tab creation enable pop out.
