### ISSUE TITLE
Notice insert link open link in new window option greyed out

### ISSUE THREAD

**Issue by statecowboy** [causefx/Organizr#781]
###### Operating System: unRaid
<hr>

##### Problem Description:
When inserting a link into a homepage notice the "Open in new window" option is greyed out for link insertion.

<hr>

##### Reproduction Steps:

<hr>

#### Errors on screen?  If so paste here:

```

```

**Comment by christronyxyocum** [comment]
I can reproduce this in FF and Chrome. No errors seen in console. Cursor turns into hand as if it's clickable, but nothing happens when you click on it. No errors in console when trying to click on it either.

**Comment by statecowboy** [comment]
It was pointed out by GilbN[unRAID/Docker/Org/Nginx] in the discord channel that you can switch to HTML mode and insert an a tag link (you must then switch back to text mode to save your notice).  This method works for the intended purpose, but the issue still remains.

**Comment by causefx** [comment]
changed editors in v2
