### ISSUE TITLE
Plex Auth Not working

### ISSUE THREAD

**Issue by ohdear1994** [causefx/Organizr#783]
###### Operating System: Ubuntu
<hr>

##### Problem Description:
After setting up organizr the only thing that does not seem to be working is Plex Auth, for the SSO etc.
Working with @jonfinley, he tried his own credentials and it all led to the error 
`error occured logging into plex might want to check curl.cainfo=/path/to/downloaded/cacert.pem in php.ini`

Homepage works just fine with the Token.
<hr>

##### Reproduction Steps:
Enter any Plex credential into the Advanced settings and try to login with Plex Auth Backend enabled

**Comment by jonfinley** [comment]
I manually downloaded the cacert as well to `/etc/ssl/certs/` and edited the php.ini to point the `curl.cainfo` same issue.

running `curl -I https://plex.tv` works perfectly like it is supposed to.

**Comment by jonfinley** [comment]
working with v2-develop.... seems that now it cannot pull recently added from Plex.

**Comment by causefx** [comment]
fixed in v2 as we now use token
