### ISSUE TITLE
Can't login after Fresh install (Organizr-v2)

### ISSUE THREAD

**Issue by iMowgli** [causefx/Organizr#785]
###### Operating System: Fedora 27
<hr>

##### Problem Description:
Hi! I can't login after a fresh install of Organizr-v2.
When i login with credential configured at the installation it return me always to the login page with a message: "Welcome Guest".

When i try with a wong password , a message return me wrong password.

<hr>

##### Reproduction Steps:
1. fresh install of branch develop-v2
2. Installation
3. Try to login

<hr>

#### Errors on screen?  If so paste here:

No error , just a loop on the login page 
```

```

**Comment by halali** [comment]
Are you able to login from localhost ?

**Comment by iMowgli** [comment]
I will try with a SSH Tunnel, i keep you in touch.

**Comment by iMowgli** [comment]
Same issue with SSH Tunnel and connect via localhost

![organizr2](https://user-images.githubusercontent.com/33395211/36903051-bfca8b06-1e2c-11e8-9b82-0be0bcca29ae.gif)

**Comment by kevinb77** [comment]
Try using the actual IP address of the machine. I too had this problem.

**Comment by causefx** [comment]
Looks like it can't create the cookie. I will fix.

**Comment by dejected1** [comment]
having same issue. works with local ip but not public.

**Comment by causefx** [comment]
Does your IP include port too?

**Comment by iMowgli** [comment]
I was connecting with the private IP of the server, i use a custom port (8080).

**Comment by pikeupe** [comment]
Organizr Version: V 2
Branch: Develop v2
Operating System: synology docker

Hello

same problem. works with local IP but not public.

**Comment by halali** [comment]
for me it works with external IP but not with external HOST

**Comment by causefx** [comment]
By any chance is your external host with no-ip?

**Comment by halali** [comment]
My host is ddns, dont think i have any other host from provider.

**Comment by hbooo** [comment]
I have the same behaviour with an host generated by azure : xxxxx.westeurope.cloudapp.azure.com

**Comment by causefx** [comment]
Something happens with ddns.net and ddns.com I updated v2 to fix those. As for the extra long one, I will have to look into that...

**Comment by causefx** [comment]
Also, for anyone checking this later, http://freedns.afraid.org/ offers Free DDNS that allows me to set cookie on root domain.

**Comment by halali** [comment]
Yes that works.

**Comment by causefx** [comment]
no clue why ddns - noip block it

**Comment by KAJed82** [comment]
Has anyone else had luck getting noip to work? I'm having the same issue.

**Comment by causefx** [comment]
What version are you on?

**Comment by KAJed82** [comment]
Running on the v2-develop you posted. Same as above running with noip, nginx. Works fine via localhost. Also I'm running through SSL.

**Comment by causefx** [comment]
Noip doesn’t allow cookies on root domain... 

What domain is it? Xxxx.noip.com ?

Afraid.org is also free and doesn’t have restrictions

**Comment by causefx** [comment]
Or select a domain on line 30 of 
https://github.com/causefx/Organizr/blob/v2-develop/api/functions/normal-functions.php

**Comment by deranjer** [comment]
I think I have the same issue with my setup using duckdns.org for my dynamic DNS, keeps logging me in as guest.  The only solution is a different dynamic DNS provider?

**Comment by causefx** [comment]
I can add a toggle asking if domain is a ddns... currently there is no way of me knowing which ddns providers allow root domain cookies.

**Comment by KAJed82** [comment]
If a toggle would fix it it seems like it would be useful. I did end up getting my router set up with DDNS with freedns and now have everything working. I needed to use a Merlin firmware instead of stock.

**Comment by deranjer** [comment]
@causefx  So just to be clear, the ONLY solution would be switching to a different dynamic DNS provider?  If so, that would really suck since I love duckdns.

**Comment by causefx** [comment]
Is the domain xxxxx.duckdns.org?

**Comment by deranjer** [comment]
@causefx Yes it is.

**Comment by deranjer** [comment]
Oh, that was all I had to do?  Well I've modified that file myself and it works fine, thanks!

**Comment by causefx** [comment]
nice!  good stuff

**Comment by hbooo** [comment]
I also tried to add 'westeurope.cloudapp.azure.com', but it doesn't work with a DNS like this : 

myuser.westeurope.cloudapp.azure.com/Organizr2 (run by a wamp server)

**Comment by HerrNovad** [comment]
I'm having the same issue with xxx.myqnapcloud.com..  

Will try the workaround later though.

**Comment by causefx** [comment]
What domain from no-up?

**Comment by EricG66** [comment]
I added 'dnsalias.com'  to badDomains in api/functions/normal-functions.php to be able to connect

**Comment by f948lan** [comment]
Also had this issue - related but slightly different cause. I run an internal only DNS with a subdomain of my public domain. At least this tread pointed me in the right direction.
The code seems to assume a maximum domain length, so my url of portal.admin.xxx.co.uk has too many components, and thus ends up trying to make a cookie for a 'mid' domain!
Don't quite understand  the reason for stripping the domain name for cookies in the first place(?), so I've 'fixed' it by just returning Domain from parseDomain after the port is stripped and ignoring the other logic.

**Comment by causefx** [comment]
Yeah I think I will be scraping this function and will do something different.

**Comment by RealTacosaurus** [comment]
Jonfinley asked me to comment with my ddns as it's not working either. I use kozow.com, which is provided by dynu. They provide a bunch of options: accesscam.org, camdvr.org, casacam.net, ddnsfree.com, ddnsgeek.com, dynu.net, freeddnes.org, glize.com, gleeze.com, kozow.com, loseyourip.com, myddns.rocks, mywire.org, theworkpc.com, webredirect.org

**Comment by causefx** [comment]
please update now, this should fix the problem.

**Comment by RealTacosaurus** [comment]
It looks like this may have only solved the issue when accessing from a subdomain. When I access from my main domain, I get the cycle issue on login or logout, as before. If I access with a subdomain, I do not have this issue.

**Comment by causefx** [comment]
What is subdomain u are using www?

**Comment by RealTacosaurus** [comment]
It works from any subdomain I want, www, organizr. The issue is when I don't use a subdomain, and instead use a subfolder. If i have my URL for organizr as mydomain.kozow.com/, then I am unable to log in and out. If I have it as organizr.mydomain.kozow.com, it works no problem.

**Comment by causefx** [comment]
do you own this domain?

**Comment by RealTacosaurus** [comment]
This is on DDNS, so no, I don't own the overall domain.

**Comment by causefx** [comment]
can you put the ddns service so i can sign up and test?

**Comment by RealTacosaurus** [comment]
Yeah it's DYNU

**Comment by tserversbfs** [comment]
I seem to be having a similar problem to others. I am running under in an lxd container. Apache > reverse proxy into lxd > apache > organizr. AND I am trying to access Organzr by using a subdomain. As I am testing Organizr my URL is formatted like: https://subdomain.fulldomain.com/organizr 

Any help would be appreciated. 
Thanks in advance.

**Comment by causefx** [comment]
what version of organizr

**Comment by tserversbfs** [comment]
> what version of organizr
I cannot find where the version is stated, but i used this command less than 24 hours ago: git clone -b v2-develop https://github.com/causefx/Organizr

**Comment by causefx** [comment]
can you login if you access through ip:port?

**Comment by tserversbfs** [comment]
> 
> 
> can you login if you access through ip:port?

I can try that, but ugh, i would have to ... it will take a few days until i can try that. 

The only cookie it is setting right now is language. trying to log in comes up saying "welcome guest". If i use the wrong password it comes up with an error message.

**Comment by LEdiodes** [comment]
I am also experiancing this problem. Fresh install of Organizr V2 in docker.
connecting via ip:port works, connecting via xxxxx.ddns.net works. What doesn't work is when connecting to the root of a domain I own through GoDaddy that redirects to xxxxx.ddns.net:port.

Any idea would be greatly appreciated.

**Comment by causefx** [comment]
login loop or what happens?

**Comment by LEdiodes** [comment]
> login loop or what happens?

Yes, login loop. I get a message saying OAuth successful and then it brings me to the login page again.

**Comment by causefx** [comment]
did you recently update php?

**Comment by LEdiodes** [comment]
> did you recently update php?
I have not. I just ran the following;
docker create --name=organizr --restart=always -v H:\Organizr:/config -e PGID=1001 -e PUID=1001 -p 9090:80 organizrtools/organizr-v2
