### ISSUE TITLE
Valid TLD of .us does not pass email validation

### ISSUE THREAD

**Issue by JesseHawkins** [causefx/Organizr#786]
###### Operating System: Docker under Ubuntu Server
<hr>

##### Problem Description:
Email validation fails on valid, albiet unusual email addresses.

<hr>

##### Reproduction Steps:
Create an account using the email address someone@somewhere.us, which is a valid TLD as per https://en.wikipedia.org/wiki/.us. The account creation will fail saying that the email did not pass validation.

<hr>

#### Errors on screen?  If so paste here:
REGISTRATION ERROR: EMAIL ADDRESS DID NOT PASS VALIDATION
```

```

**Comment by causefx** [comment]
fixed in v2
