### ISSUE TITLE
Bug: Undefined index: user in /var/www/sso.domain.co.uk/html/functions.php on line 312

### ISSUE THREAD

**Issue by jkirkcaldy** [causefx/Organizr#788]
###### Operating System: Ubuntu
<hr>

##### Problem Description:
whilst testing to make sure everything works as expected I changed the password of my test user. When logging on using the new password (either by changing it in the user update box or using the forgot password email) this error pops up and nothing but the homepage.php page is available. 

Undefined index: user in /var/www/sso.domain.co.uk/html/functions.php on line 312

<hr>

##### Reproduction Steps:
Change password for a user using the update user box (as the user) or using the forgot password button on login. 

Login using new password

<hr>

#### Errors on screen?  If so paste here:

```
Undefined index: user in /var/www/sso.domain.co.uk/html/functions.php on line 312
```

**Comment by causefx** [comment]
fixed in v2
