### ISSUE TITLE
Plex invites defaults to sharing all libraries

### ISSUE THREAD

**Issue by jordandrako** [causefx/Organizr#789]
###### Operating System: Ubuntu
<hr>

##### Problem Description:
When I invite somebody to plex it shares all my libraries by default. Since many have private libraries, it'd be nice if we had the option of which libraries are shared when somebody accepts an organizr invite.

**Comment by causefx** [comment]
This is will be a v2 feature

Currently being worked on now.

**Comment by jordandrako** [comment]
Is it also supposed to create an Organizr account for those that accept the invite? New users aren't created for me when they accept an invite, but they are added to the server.

**Comment by si0972** [comment]
No, its not. because we have no way of knowing what password it sets. you can fix this by setting the backend to plex, and allow usercreation.

**Comment by causefx** [comment]
fixed in v2
