### ISSUE TITLE
 ORGNIZR & NGINX WINDOWS

### ISSUE THREAD

**Issue by rolotos** [causefx/Organizr#790]
Good morning. Hello,
I have a seedbox PC running Windows 10 (yes I know and that's fine, I won't change it) with various associated services (sonarr, radarr, qbittorrent, etc.) and I recently installed organizr to have central access to all this and open my seedbox to friends with a simplified interface but I can't set up the external access... I tried to fudge in the conf nginx file to make proxies lapels but I can't... My tabs are easily accessible in localhost but as soon as I get out of my LAN it crap... Is someone here using all this and could they point me in the right direction? I found topics on the internet but most of them talk about nginx under debian/ubuntu: /

Translated with www.DeepL.com/Translator

**Comment by causefx** [comment]
Just need to setup nginx with RP’s. Jump on discord we can help

**Comment by rolotos** [comment]
Hello and how i find you in discord ? because i never used discord !

**Comment by jonfinley** [comment]
https://discord.gg/XvbT6nz

**Comment by christronyxyocum** [comment]
Can probably close this.
