### ISSUE TITLE
Organizr v2 : What's hashkey / password in wizard ?

### ISSUE THREAD

**Issue by jaydee99** [causefx/Organizr#791]
##### Problem Description:

Hi,

First i'd like to tell you i really love Organizr, thank you for your hard work !

I'd like to test v2. I cloned the dir using v2-develop branch.

Installation wizard is asking for hashkey / password and there's no info on this anywhere... Where can i find this hashkey / password please ?

Thanx !

**Comment by jonfinley** [comment]
Thanks for testing v2!

hash key and password are created using that page. We don't have documentation quite yet on v2.

Hash Key = your database encryption, for passwords, etc.
Registration password =  is your register password. new users.

Thanks!

**Comment by jaydee99** [comment]
Hi,

I don't see any button to create them and it won't let me continue if i don't fill the infos... Did i miss something ?

Thanx for helping !

**Comment by causefx** [comment]
You fill it in manually with any you choose. :)

**Comment by CollinChaffin** [comment]
Don't have documentation YET?  It's now over a YEAR after this issue was closed and there is still not a single wiki page simply explaining the mere handful of config wizard pages needed to even start with organizr.  Any chance a simple one-page doc detailing things like these mystery hash keys gets created anytime soon?

**Comment by Roxedus** [comment]
@CollinChaffin Thanks for commenting on this *closed* issue. If you would like to help documenting, head over to the [docs site.](https://docs.organizr.app/)

**Comment by ScarUY** [comment]
> You fill it in manually with any you choose. :)
> […](#)
> Sent from my iPhone
> On Mar 4, 2018, at 11:55 AM, jaydee99 ***@***.***> wrote: Hi, I don't see any button to create them and it won't let me continue if i don't fill the infos... Did i miss something ? Thanx for helping ! — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

So, I just beat up my keyboard and forget about it or is this something that I need to save/remember for the future (migrations or something) does it have a minimum/maximum amount of characters/complexity? 

A "Help" button or a pop up baloon (or whatever is the name of those) would be very helpful

**Comment by cleverestx** [comment]
I came to this page hoping for the same answer as the last guy who posted this eons ago...am I just keyboard spamming this hash and password field and forgetting about it, or do I need to retain one or more of these hash/password fields? Anyone?

**Comment by Vothm** [comment]
> I came to this page hoping for the same answer as the last guy who posted this eons ago...am I just keyboard spamming this hash and password field and forgetting about it, or do I need to retain one or more of these hash/password fields? Anyone?

Quite frankly... Yes you can just do that. Or come up with a random string and store it in a text file just in case you need it
