### ISSUE TITLE
Allow loading internal services remotely

### ISSUE THREAD

**Issue by thejacer87** [causefx/Organizr#793]
Example: My media server is remote. I've setup remote access to organizr at `organizr.my-domain.com`. But, in order to stay "organized" I don't want to setup proxies for every service. I want to set up my tabs to have some sort of local IP/host resolution (ie in the tab URL, localhost:8989 will load sonarr bcuz that service is running on the same server organizr is running, which i feel like would be most common)

**Comment by si0972** [comment]
This isnt possible. organizr doesnt load the services, your browser does. so the browser would need to see the service, hence why localhost:port wont work.

**Comment by causefx** [comment]
Correct, currently this is not possible.
