### ISSUE TITLE
Org v2 - Can't re-order categories and tabs together

### ISSUE THREAD

**Issue by 1activegeek** [causefx/Organizr#798]
###### Operating System: MacOS
<hr>

##### Problem Description:

No ability to put categories in a specific place with regard to tabs. Currently Categories appear at the bottom of the tabs list below the last tab. I've not been able to find a way to re-order the tabs or categories so that a category can be at the top of the list. 

I'd assume the easiest method would be to choose if categories appear at top or bottom. Sorting categories intermingled with tabs is likely a bit difficult without combining some other type of gui layout. Simplicity would be a switch to set for categories at top, or bottom, or perhaps even off. 
<hr>

##### Reproduction Steps:

Create a few tabs. Create a category. Add a tab to it. The category will appear at the bottom of the list. 
<hr>

#### Errors on screen?  If so paste here:

```

```

**Comment by causefx** [comment]
DEfault is top, i will look into toggle.

**Comment by 1activegeek** [comment]
Cool, that'd be great! Thanks Cause!

**Comment by causefx** [comment]
Closing all Feature Requests and will communicated thru FeatHub
