### ISSUE TITLE
[Request] Add Plex API to Login Options

### ISSUE THREAD

**Issue by SuperPotatoMen** [causefx/Organizr#8]
Is it possible to make a option to connect with the plex api? So the users can login with there plex username and password?

**Comment by Githubtordl** [comment]
@SuperPotatoMen are you thinking something like PlexAuth (https://github.com/hjone72/PlexAuth) ? if so that would be fantastic, Organizr looks great, I've already moved from iDashboard and adding PlexAuth would complete it as the Ultimate dashboard IMO.

**Comment by causefx** [comment]
I can look into the plex api for logins.  Is it pretty easy to do?

**Comment by Githubtordl** [comment]
Not sure mate, I haven't tried setting it up but I did find it's Plex forum page, hopefully this might be of some help to you, the dev seems quite active on there helping users.
http://forums.plex.tv/discussion/220697/php-plexauth-authentication-for-your-domain-using-plex

**Comment by causefx** [comment]
Plex Auth wont work for this as it requires nginx.  We would need to create our own script.

**Comment by Githubtordl** [comment]
Oh! ok, I'm running my webserver on nginx but not everyone is so fair enough, thanks for looking into this though

**Comment by causefx** [comment]
no problem :)

**Comment by SuperPotatoMen** [comment]
@causefx hi thanks Maybe @tidusjar can help from https://github.com/tidusjar/Ombi ?

**Comment by StevenChorkley** [comment]
It looks like they've made a similar UI to Organizr, but this guy went about adding PlexAuth to PlexPy directly: https://github.com/hjone72/plexpy

I would love for Organizr to support PlexAuth!

**Comment by STX2k** [comment]
+1 for this Feature <3

**Comment by StevenChorkley** [comment]
Oh my god, thank you so much!

**Comment by SuperPotatoMen** [comment]
@causefx can you help me? I was using this brand new option but i got everytime a 
Error: the specified username/password combination is incorrect.
when i try to login.
I config my admin plex account, but is look like it doesn't work :(
