### ISSUE TITLE
Foreach() errors, cannot create admin account

### ISSUE THREAD

**Issue by R41K** [causefx/Organizr#802]
###### Operating System: FreeBSD
<hr>

##### Problem Description:
After initial install I am getting errors in the login/register screen after configuring database and time zone. I can't create an admin user.

<hr>

##### Reproduction Steps:
Fresh install, using the following packages:
nginx php56 php56-curl php56-hash php56-json php56-openssl php56-pdo php56-pdo_sqlite php56-session php56-simplexml php56-sqlite3 php56-zip git ca_root_nss

<hr>

#### Errors on screen?  If so paste here:

```
Warning: Invalid argument supplied for foreach() in /usr/local/www/Organizr/user.php on line 934
Warning: Invalid argument supplied for foreach() in /usr/local/www/Organizr/user.php on line 940
Warning: Invalid argument supplied for foreach() in /usr/local/www/Organizr/index.php on line 75
```
![organizr_error](https://user-images.githubusercontent.com/35241087/37251871-28352042-2518-11e8-8b7c-b019a9731b23.PNG)

**Comment by SaberSHO** [comment]
I am having the same issue on a fresh docker install (image = lsiocommunity/organizr:latest). The same Warnings are showing. My gut is telling me this may be a permission issue on the db, but if anyone has any pointers on what to check, it would be appreciated.

**Comment by causefx** [comment]
let me try a fresh install

**Comment by causefx** [comment]
I just did a clean install of 1.75 and all was well.  Please wipe install and reinstall and to test put permission as 777.  to see if it will work.

**Comment by ak2k** [comment]
I am having the issue on a freenas jail install, following these instructions: https://forums.freenas.org/index.php?resources/fn11-1-jails-for-plex-plexpy-sonarr-radarr-headphones-jackett-ombi-transmission-organizr.58/

I get the exact same errors and am unable to create a user. The users.db gets created and has the appropriate permissions, but remains a zero size.

**Comment by causefx** [comment]
can you try v2 alpha?
