### ISSUE TITLE
Tautulli SSO not working

### ISSUE THREAD

**Issue by jaydee99** [causefx/Organizr#803]
###### Operating System: Debian
<hr>

##### Problem Description:
Hi,

Tautulli 2.0.22 Plex SSO doesn't seem to work here.

It works with Plex and Ombi perfectly. But i can't get it working with Tautulli and i'm always redirected to login page. I have enabled plex admin auth in Tautulli's settings. Is there something special to do to make it work ?

Thanx !!

<hr>

##### Reproduction Steps:

<hr>

#### Errors on screen?  If so paste here:

```

```

**Comment by causefx** [comment]
Let me update my Tau and test.

**Comment by causefx** [comment]
can you check your cookies when loggin in:

is there a cookie named:

tautulli_token_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

**Comment by jaydee99** [comment]
How do you check that please ? I'm using chrome...

**Comment by causefx** [comment]
CTRL+SHIFT+I

Then goto Application on top then Cookies on left then your domain:

![image](https://user-images.githubusercontent.com/16184466/37358884-755531e0-26a9-11e8-9540-9e447fe2f573.png)

**Comment by jaydee99** [comment]
Ok thanx !
And no there is no tautulli_token...

**Comment by jaydee99** [comment]
It was /plexpy/ and i just replaced it with /plexpy (without the end slash)

Good news is that i now have a tautulli_token in cookies. Bad news is that i'm still redirected to login page...

**Comment by causefx** [comment]
is there numbers and letters after token_

**Comment by jaydee99** [comment]
Yes

**Comment by si0972** [comment]
Tautulli SSO only works for OrganizrV2- ALPHA, your issue stated 1.75

**Comment by marc0janssen** [comment]
I also have this problem.. I'm on latest MacOS

**Comment by HalianElf** [comment]
This is a known issue - please see https://docs.organizr.app/books/troubleshooting/page/redirect-looping---samesite-errors and #1320 which would have been a better one to comment on rather than a 2 year old issue.

Edit to add: if it's not actually the cookie issue like has been for the majority of these lately, check the troubleshooting stuff here: https://docs.organizr.app/books/setup-features/page/sso

**Comment by marc0janssen** [comment]
Thanks @HalianElf for helping out. And Thanks for your friendly comment about the 2 year old issue. I'm just looking for help. Did stubble upon the older stuff.

**Comment by marc0janssen** [comment]
This fixed it for me:
1. Edit the localhost file on my MAC to point to the server I have Tautulli on [ 192.168.1.x         hostname]
2. Disabling the "Prevent cross-site tracking in Safari"

![privacy_tab__thumb800](https://user-images.githubusercontent.com/5788988/78753856-d2535580-7976-11ea-80ef-d0f8ca779af4.jpg)

**Comment by causefx** [comment]
are organizr and tautulli not on same domain?

**Comment by marc0janssen** [comment]
Hi @causefx 

The Organizr Container is on 192.168.1.2
The Tautulli Container is on 192.168.1.7

The I have have 2 Docker systems running.

So yes they are in the same collision-domain but I have no DNS setup here.

So I know sure what you mean by "domain" , DNS or IP-collision-domain.
