### ISSUE TITLE
v2: deluge on homepage not working

### ISSUE THREAD

**Issue by dejected1** [causefx/Organizr#804]
###### Operating System: Windows 10 pro x64
<hr>

##### Problem Description:
homepage deluge

<hr>

##### Reproduction Steps:
trying to get both to display on hompeage, no bueno. I installed the webapi.egg into deluge. It shows up but when i enable it it just disables itself. Doesn't matter if i do it from the web ui or the dameon. I can also browse to  deluge through web proxy. However, since i cant login yet through my public address to v2 im using local addresses. 

<hr>

#### Errors on screen?  If so paste here:

```
no on screen errors but console shows:

Tab Function: Switching to tab: Homepage
VM6876:1 POST http://192.168.2.2:9111/v2/api/?v1/homepage/connect 500 (Internal Server Error)
(anonymous) @ VM6876:1
send @ jquery-2.2.4.min.js:4
ajax @ jquery-2.2.4.min.js:4
organizrAPI @ functions.js?v=2.0.0-alpha.250:1502
homepageDownloader @ functions.js?v=2.0.0-alpha.250:2442
(anonymous) @ functions.js?v=2.0.0-alpha.250:2450
functions.js?v=2.0.0-alpha.250:2447 Organizr Function: API Connection Failed

```

**Comment by causefx** [comment]
Can you check the php logs

**Comment by dejected1** [comment]
Sure, if you can tell me where to find them....

**Comment by causefx** [comment]
On Windows you may have to enable them in php.ini

**Comment by dejected1** [comment]
[12-Mar-2018 01:02:52 UTC] PHP Fatal error:  Uncaught Exception: Method request returned an error (no. 2): Unknown method in C:\nginx\www\v2\api\functions\deluge.class.php:490
Stack trace:
#0 C:\nginx\www\v2\api\functions\deluge.class.php(49): deluge->makeRequest('webapi.get_torr...', Array)
#1 C:\nginx\www\v2\api\functions\homepage-connect-functions.php(673): deluge->getTorrents(NULL, 'comment, downlo...')
#2 C:\nginx\www\v2\api\functions\homepage-connect-functions.php(36): delugeConnect()
#3 C:\nginx\www\v2\api\index.php(262): homepageConnect(Array)
#4 {main}
  thrown in C:\nginx\www\v2\api\functions\deluge.class.php on line 490

**Comment by dejected1** [comment]
there seems to be an open issue for the webapi not staying enabled on the developers github. i posted a me too and the issue page. https://github.com/idlesign/deluge-webapi/issues/6

**Comment by causefx** [comment]
i will monitor that issue on their page
