### ISSUE TITLE
OrgV2 - Auth block not working ?

### ISSUE THREAD

**Issue by jaydee99** [causefx/Organizr#805]
###### Operating System:Ubuntu
<hr>

##### Problem Description:
Hi,

What's the new block to include in organizr v2 to make auth working like it was with v1 please ?

https://localhost/auth.php?admin and https://localhost/auth.php?user is now returning a 404 not found error... I can''t find nothing about those changes...

Thanx !!

<hr>

##### Reproduction Steps:

<hr>

#### Errors on screen?  If so paste here:

```

```

**Comment by causefx** [comment]
hi, the new auth system changed slightly to adopt user groups...

new address: 

`/api?v1/auth&group=0` - for Group 0 which is admin and so on

**Comment by jaydee99** [comment]
Ok thanx !

**Comment by jaydee99** [comment]
Still not working with this block
`location /auth-admin {
                internal;
                proxy_pass https://localhost/api?v1/auth&group=0;
                proxy_pass_request_body off;
                proxy_set_header Content-Length "";
                proxy_set_header X-Original-URI $request_uri;
}
`
Did i miss something ?

**Comment by causefx** [comment]
My bad I had a typo. Need a slash between API and ?

/api/?v1/auth

**Comment by jaydee99** [comment]
Still no luck...

**Comment by adnanklink** [comment]
This looks like its working for me.

location /auth-admin {
                internal;
                proxy_pass http://localhost:81/api/?v1/auth&group=0;
                proxy_pass_request_body off;
                proxy_set_header Content-Length "";
                proxy_set_header X-Original-URI $request_uri;
        }
location /plexpy/ {
                auth_request /auth-admin;
                proxy_pass http://plexpy-upstream;
        }

**Comment by jaydee99** [comment]
Ok working for me too ! Stupid me, i was trying with a co-admin account and group set to 0, that's why it wasn't working ;)
