### ISSUE TITLE
Speed test results are incorrectly displayed as Mbps instead of MBps

### ISSUE THREAD

**Issue by jake661** [causefx/Organizr#806]
Speed test results are incorrectly displayed as Mbps instead of MBps

**Comment by djismgaming** [comment]
maybe there could be an option in Settings for this as some people may like the speed represented in Mbps (like me for remote locations) or MBps (like me for when I'm using Organizr locally. 

-  test Internet speed from a remote location (Mbps) 
- test local network throughput when locally near the server (MBps).

**Comment by joe-eklund** [comment]
Clarification would be nice. Are you referring to:

1. The numbers displayed are shown in megabytes / second (MBps), and the units are in megabits / second (Mbps).

2. The number and units are shown both in Mbps but _should_ be displayed in MBps.


If you are referring to number 1 above, at least on the current master branch, it _correctly_ displays "Mbit/s". I get ~1000 Mbit/s on my gigabit local LAN. My other numbers make sense too when testing on other devices. Can you provide some more information? Screenshots perhaps and what version you are running. 

If you are referring to the number 2 situation above, I disagree. Mbps has become the standard in speedtests. Here is an old [reddit post](https://www.reddit.com/r/explainlikeimfive/comments/1at0fr/why_do_we_measure_internet_speed_in_megabits_per/) explaining why.

**Comment by causefx** [comment]
correct, will be keeping as Mbps
