### ISSUE TITLE
Plex SSO

### ISSUE THREAD

**Issue by thamilton91** [causefx/Organizr#810]
I’m having trouble getting Plex SSO to work. 

When the page loads within Organizr, it shows a Sign In button (which if clicked, opens in a new window/tab). 

I looked at the headers loading and it looks like plex.tv receives a 403 error. 

Any ideas?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by causefx** [comment]
what URL is in the plex tab?  

also make sure you have this box filled in under homepage - plex

![image](https://user-images.githubusercontent.com/16184466/38057230-8de9c248-3293-11e8-9d35-6f0f74ad4de4.png)
