### ISSUE TITLE
Hamburger menu overlaps part of the application layout in upper left corner

### ISSUE THREAD

**Issue by riemers** [causefx/Organizr#811]
###### Operating System: Ubuntu
<hr>

##### Problem Description:
When wanting to click in an application in the top left corner, the div.cross overlaps and opens the hamburger menu instead.
![image](https://user-images.githubusercontent.com/682041/38057969-76062dda-32e1-11e8-8150-ade09c5e4fdd.png)

##### Reproduction Steps:
Take any app you have, then click near the top left corner, you will notice it will open the hamburger menu instead. 

Not the biggest problem in the world, but i do click often on the back arrows on the picture and forget each time to be a bit lower ;)

**Comment by riemers** [comment]
```
a:not(.gn-selected) .cross {     
    display: none;
}
```

This fixes the issue. If i know where you want it in the css, i can do a PR.

**Comment by causefx** [comment]
hi,

PR to this file:
https://github.com/causefx/Organizr/blob/master/css/style.css
