### ISSUE TITLE
[Feature Request] New r+r keyboard shortcut to refresh current tab

### ISSUE THREAD

**Issue by JohanSF** [causefx/Organizr#812]
###### Operating System: unRAID
<hr>

##### Suggestion Description:
I would find it very useful if a new keyboard shortcut to refresh the page (like double-clicking the icon in the bar to the left) is introduced. For example
- [r]+[r] will refresh the current tab

,in accordance with the other shortcuts in the image below.

![image](https://user-images.githubusercontent.com/6782603/38090556-481bee8c-3363-11e8-8328-d0e6243a7c1a.png)
<hr>

**Comment by causefx** [comment]
`R + R` is a function already , i guess i never listed it.
