### ISSUE TITLE
Stretched Org Header Visibly Blocks i-Framed Headers Under Certain Circumstances

### ISSUE THREAD

**Issue by LettuceSnob** [causefx/Organizr#815]
###### Operating System: Debian Jessie ARM (RPi)
<hr>

##### Problem Description:
https://i.imgur.com/I0vSmYy.png

Because the domain I'm on blocks access to gravatar.com, the resulting placeholder box stretches the Org header past its normal vertical limit. The result actually blocks the headers for the i-Framed contents (in this case Tautulli), so I can't navigate to other pages within the tabbed service.

<hr>

##### Reproduction Steps:
N/A

<hr>

#### Errors on screen?  If so paste here:
N/A - F12 Console shows that my domain/proxy (work) blocks secure.gravatar.com.

**Comment by causefx** [comment]
tag me on discord when you are at work i want to try something

**Comment by causefx** [comment]
we;ll take this offline.... :)
