### ISSUE TITLE
Latest Update breaks container in unRAID

### ISSUE THREAD

**Issue by JoeStratton** [causefx/Organizr#82]
Fresh install, no config, working pre .9998 update. Now causes this after pointing it to a DB location:

Fatal error: Uncaught Error: Call to undefined function session_start() in /config/www/Dashboard/user.php:150 Stack trace: #0 /config/www/Dashboard/index.php(150): User->__construct('registration_ca...') #1 {main} thrown in /config/www/Dashboard/user.php on line 150

If this is a container issue I apologize, please let me know.

**Comment by causefx** [comment]
let me do some testing.

**Comment by causefx** [comment]
can you do me a favor?

can you edit check.php

underneath Line 168
https://github.com/causefx/Organizr/blob/master/check.php#L168

Can you add:

`check("session");`

or if you dont want to do that can you just load up check.php and scroll to the phpinfo portion and see if you have a Session section...  if so, is it enabled?

![image](https://cloud.githubusercontent.com/assets/16184466/22429842/49200d28-e6c9-11e6-872c-4e2a0dedcfdc.png)

**Comment by JoeStratton** [comment]
I added that line but I didnt see any change/information so I went to:
IP:1338/check.php and found the phpinfo portion. There was NOT a session subsection.

Just let me know if there's anything else I can check for you, happy to help.

**Comment by causefx** [comment]
what os is on that container?

**Comment by JoeStratton** [comment]
Here is the repo from linuxserverio: 
https://github.com/linuxserver/docker-organizr/

and here is the listed distro base: FROM lsiobase/alpine.nginx:3.5

**Comment by causefx** [comment]
ahhhh ok... look at this, they are upgrading it:

https://github.com/linuxserver/docker-organizr/issues/3

**Comment by JoeStratton** [comment]
Ahhh that makes sense. I will wait! Thanks!

**Comment by causefx** [comment]
:)

**Comment by JoeStratton** [comment]
Linuxserverio's latest container update fixed the issue, so I would consider this closed. If you are still having the issue, version 7 of the container works for the old php version.
