### ISSUE TITLE
Pings causes large delay in usable page load time

### ISSUE THREAD

**Issue by Undeadllama** [causefx/Organizr#821]
###### Operating System: Windows
<hr>

##### Problem Description:
Enabling the ping function on tabs causes a a significant delay to page load time.
The navigation frames to the top and left of the page load many seconds prior to a usable homepage appears.
This behaviour occurs even when all ping targets are online and in the LAN (so should be less than 10ms response time each).

I understand that it may not be possible to do much about reducing/optimising the ping times using the  ajax framework.
Instead is it possible to either:

- perform the ping tests after all other parts of the page have loaded so that we aren't waiting for the ping tests to complete
- or alternatively perform the ping tests independently to the page load functionality somehow

I'm not a web developer by profession so apologies if this is not possible but I thought it was worth asking!

<hr>

##### Reproduction Steps:
I use Chrome but imagine there's similar developer tools in other browsers.
1. Create some Organizr tabs and enable Ping on them all in the Organizr settings.
2. Open Chrome Developer Tools > Performance > Reload to being recording
3. Notice long delay caused by multiple ajax.php ping functions prior to homepage.php being called.

4. In a new browser tab disable ping on all Organizr tabs
5. Again open Chrome Developer Tools > Performance and start a new recording
6. Compare with previous recording
Usable homepage loads much quicker and no long wait for ajax.php pings to complete.

<hr>

#### Errors on screen?  If so paste here:

Notice on the far right that homepage.php is only called after all the ajax.php pings have completed, after more than 7 seconds, thus the delay in a usable/visible page on screen.

![ping_delay](https://user-images.githubusercontent.com/3908975/38526407-2bee551c-3c4e-11e8-9642-63334cf67641.PNG)

After disabling ping on all tabs homepage.php is requested in well under 1.5 seconds:

![ping_disabled](https://user-images.githubusercontent.com/3908975/38526761-71748e2a-3c4f-11e8-9b87-ea3d146c758d.PNG)

Hope that's enough info, let me know if I missed anything!

**Comment by causefx** [comment]
thanks for the write up, Since im still rewriting v2 - this is actually how i will be doing it.  Everything is ajax in v2.

**Comment by Undeadllama** [comment]
Good to know, thanks!
I'm looking forward to having a play with v2.

**Comment by causefx** [comment]
Closing this as this will be good by version 2.1 possibly.
