### ISSUE TITLE
iOS problems, Organizr not loading

### ISSUE THREAD

**Issue by kauanmocelin** [causefx/Organizr#823]
###### Operating System: Raspbian Stretch
<hr>

##### Problem Description:
I'm trying to acess organizr by my iPhone 6 using Safari/Firefox, i can navegate by app but nothing happing when tabs are clicked, i waited a large time but it doesn't loaded. Via desktop browser everything is ok.

<hr>

##### Reproduction Steps:

<hr>

#### Errors on screen?  If so paste here:

```
https://imgur.com/JMx9Kdk
https://imgur.com/flzjZmV
```

**Comment by kauanmocelin** [comment]
It's working now, i think was a network problem, please close this issue.

**Comment by causefx** [comment]
awesome
