### ISSUE TITLE
Functions.php - multiple errors

### ISSUE THREAD

**Issue by damusmf** [causefx/Organizr#824]
###### Operating System: Windows Server 2012r2
<hr>

##### Problem Description:
Multiple lines of errors in functions.php, seemed to happen out of nowhere as i changed nothing recently and it was working fine until 2 days ago.  

Screenshot: https://i.imgur.com/78tEztB.png?1

Console shows the following error
 ```
GET https://image.tmdb.org/t/p/w300/C 404 () 
```

Rebooting the server does not change it neither does clearing cache/cookies in the web browser.  I haven't made any changes to functions.php.  As far as i can tell everything still works, but the error takes up the whole top half of the screen.  This may be a problem with Caddy itself an not organizer?  But i don't run anything else through it to test.

<hr>

##### Reproduction Steps:
Login and load up home page and the top is filled with error code

<hr>

#### Errors on screen?  If so paste here:

```
Warning: Illegal string offset 'posterPath' in C:\Caddy\www\functions.php on line 5046 
Warning: Illegal string offset 'theMovieDbId' in C:\Caddy\www\functions.php on line 5048 
Warning: Illegal string offset 'title' in C:\Caddy\www\functions.php on line 5049 
Warning: Illegal string offset 'posterPath' in C:\Caddy\www\functions.php on line 5050 
Warning: Illegal string offset 'posterPath' in C:\Caddy\www\functions.php on line 5050 
Warning: Illegal string offset 'approved' in C:\Caddy\www\functions.php on line 5051
Warning: Illegal string offset 'available' in C:\Caddy\www\functions.php on line 5052 
Warning: Illegal string offset 'denied' in C:\Caddy\www\functions.php on line 5053 
Warning: Illegal string offset 'deniedReason' in C:\Caddy\www\functions.php on line 5054 
Warning: Illegal string offset 'requestedUser' in C:\Caddy\www\functions.php on line 5055 
Warning: Illegal string offset 'userName' in C:\Caddy\www\functions.php on line 5055 
Warning: Illegal string offset 'id' in C:\Caddy\www\functions.php on line 5056 
Warning: Illegal string offset 'requestedDate' in C:\Caddy\www\functions.php on line 5057 
Warning: Illegal string offset 'releaseDate' in C:\Caddy\www\functions.php on line 5058 
Warning: Illegal string offset 'childRequests' in C:\Caddy\www\functions.php on line 5067
```

**Comment by causefx** [comment]
Something happened with the ombi api. Can you please restart ombi?

**Comment by damusmf** [comment]
So far so good.  I just restarted ombi and the error seems to have gone away.
