### ISSUE TITLE
After updating plex account password cannot access anything.

### ISSUE THREAD

**Issue by dballard8** [causefx/Organizr#825]
###### Organizr Version: V 1.x
 Latest docker 
###### WebSever: Nginx/Apache
Nginx
###### Operating System: Windows/MacOS/Ubuntu
Ubuntu 16.04 and docker
<hr>

##### Problem Description:
After updating my plex account password, I cannot log into Organizr with the new password. I can login with my old plex account password but I only get the organizr homepage tab. No other tabs show up including the settings tab.

<hr>

##### Reproduction Steps:

<hr>

#### Errors on screen?  If so paste here:

```
Undefined index: user in /config/www/Dashboard/functions.php on line 312

```

**Comment by causefx** [comment]
edit config.php:

find plexPassword and change it there.

in v2 we use the Plex Token so this will no longer happen

**Comment by dballard8** [comment]
Perfect thanks!

**Comment by causefx** [comment]
you're welcome
