### ISSUE TITLE
 Warning: chmod(): Operation not permitted

### ISSUE THREAD

**Issue by danshaw** [causefx/Organizr#827]
###### Operating System: MacOS
<hr>

##### Problem Description:
I'm having a hard time figuring out the permissions, especially when it comes to logging in with a user account. I've set the owner and given read/write to the user "_www" for all recursive files. Each time I log in with a user, I get the attached error message. 

<hr>

##### Reproduction Steps:
Log into Organizr with any account.

<hr>

#### Errors on screen?  If so paste here:

```
Warning: chmod(): Operation not permitted in /Users/danshaw/Sites/organizr/user.php on line 752

Warning: Cannot modify header information - headers already sent by (output started at /Users/danshaw/Sites/organizr/user.php:752) in /Users/danshaw/Sites/organizr/functions.php on line 81

```
![screenshot 2018-04-17 13 21 56](https://user-images.githubusercontent.com/6180024/38897392-76605e2a-4251-11e8-97f7-114634775e9c.png)

![screenshot 2018-04-17 13 22 30](https://user-images.githubusercontent.com/6180024/38897389-764ffbc0-4251-11e8-931b-6fbdd5002e64.png)

**Comment by elmerfdz** [comment]
Broswe to check.php and see if everything is ok, if not try the following:

chmod -R 775 OrganizrFolder                     -- [including db & log files]
chown -R _www:staff OrganizrFolder          -- [including db & log files]

The above is based on what works on Nginx, so hopefully that does it for Apache as well.

**Comment by causefx** [comment]
correct, please set perms recursively
