### ISSUE TITLE
V2 - Plex on Homepage displaying user info regardless of min authorization

### ISSUE THREAD

**Issue by iamernie** [causefx/Organizr#829]
###### Operating System: Ubuntu 16.04
<hr>

##### Problem Description:
When Plex displays the now playing streams on the homepage, it displays the usernames watching the streams regardless of the minimum authorization

<hr>

##### Reproduction Steps:
1. Set minimum authorization to admin for user info
2. Login with a non-admin account and you will see the usernames of people currently streaming.

<hr>

#### Errors on screen?  If so paste here:
```
None
```

**Comment by causefx** [comment]
Can you back and double check stream authorization?

Seems okay on my text machine.
![image](https://user-images.githubusercontent.com/16184466/39080607-de0ebe6c-44e6-11e8-992f-52a457fa8810.png)
![image](https://user-images.githubusercontent.com/16184466/39080618-03c66dc6-44e7-11e8-8d37-34ee4f6dc511.png)

**Comment by iamernie** [comment]
I just did another pull to 7d566a4 and it's fine now.  Thanks!
