### ISSUE TITLE
Change color first background

### ISSUE THREAD

**Issue by fana13** [causefx/Organizr#83]
Hello,

In first time, I want to thank you for this great job.

Could you give us possibility to change color in first background, the background when Organizr is loading ?

Thanks :)

**Comment by SgtBatten** [comment]
Either the title text or the active tab BG ones change the loading colour.

Try either of those two.

**Comment by causefx** [comment]
Currently it is set up as:

```
.refresh-preloader {
                    
    background: <?=$topbartext;?>;
                
}
```
I'm looking into a DB updater so I can add columns on the fly.

**Comment by chrisvdgeld** [comment]
Would be great if those could be seperate indeed. Because it's the title text that changes the BG. However, if you're okay with having no title text and therefor setting it on "black" - the login and forgot password text also turns black.

**Comment by causefx** [comment]
I could move the title name to settings and use that field for loading...

**Comment by fana13** [comment]
@causefx if you could add a new column on the fly, it would be perfect !
Thanks so much :)

**Comment by causefx** [comment]
@fana13 i figured it out.  This will be included in the next release.

**Comment by fana13** [comment]
You're great !!!
