### ISSUE TITLE
Feature Request, use Plex OAuth

### ISSUE THREAD

**Issue by flying-sausages** [causefx/Organizr#832]
Would be nice to be able to use Plex OAuth as one of the login backends, would take out a lot of the confusion from "which credentials should I use".
I would suggest first showing a button above the login form with "log in with plex" or something of the like

**Comment by vertig0ne** [comment]
While not impossible to implement. Would undermine all security reasons you are thinking of in implementing this. In order for the user to login Organizr would need to store the authentication token for each user. Which would allow the server own to literally login as ANY USER on Plex and become them.

**Comment by fbartels** [comment]
>  In order for the user to login Organizr would need to store the authentication token for each user.

That does not sound right. Sure, organizr would need to be able to validate the token, but storing should not be required.

**Comment by flying-sausages** [comment]
>In order for the user to login Organizr would need to store the authentication token for each user. Which would allow the server own to literally login as ANY USER on Plex and become them.
Maybe I don't understand, but then how did [Ombi implement it in 3.0.3239](https://github.com/tidusjar/Ombi/releases/tag/v3.0.3239), and why can't organizrr cannot do the same?

**Comment by jonfinley** [comment]
Shoot, if you disable password need ability for ombi, anyone can type any username and request via that user.

**Comment by causefx** [comment]
Please request this on FeatHub and continue discussion there.  Cleaning up issues for v2.
