### ISSUE TITLE
Qbittorrent shows blank white page in Organizr, works fine outside of it

### ISSUE THREAD

**Issue by tastyratz** [causefx/Organizr#838]
###### Operating System: Windows Server 2016
<hr>

##### Problem Description:

Qbittorrent not loading in organizr, opens a blank white page. Other links (sonarr,radarr,nzbhydra,etc.) work fine. Localhost or local lan fine, not setup for reverse proxy.

Also impacts at least one other person
https://www.reddit.com/r/organizr/comments/7c5317/qbittorrent_tab_not_loading/
<hr>

##### Reproduction Steps:
Install qbittorrent, setup web administration page on default port 8080. view in browser

<hr>

#### Errors on screen?  If so paste here:

```
Opened F12 web developer view and all pages EXCEPT the qb 8080 source are listed. It's like the resource isn't even trying to open. No errors show

```

**Comment by htpc-helper** [comment]
I am also experiencing this problem with Nginx on Linux. I received the following error in the browser console:
```
Refused to display 'https://example.com/index.html' in a frame because it set 'X-Frame-Options' to 'sameorigin'
```
I updated my Nginx app config with the line below and now I am getting 401's:
```
proxy_hide_header X-Frame-Options;
```
Under both configurations I am able to access the subdomain qBittorrent is on when I load it directly after I have already authenticated with Organizr.

**Comment by causefx** [comment]
@rob1998

can you help with this

**Comment by rob1998** [comment]
Let's start with saying that I'm a total nginx noob myself, I just try stuff and see if it works. But this block works for me as a reverse proxy using a subdirectory (so http://website.com/qbt):
```
location /qbt/ {

            proxy_hide_header  Referer;
            proxy_hide_header  Origin;
            proxy_set_header   Referer           '';
            proxy_set_header   Origin            '';
            add_header X-Frame-Options "SAMEORIGIN";
            rewrite /qbt/(.*) /$1 break;
            proxy_pass http://192.168.178.201:8080;

        }
```

You need to change the ip and maybe the port
if you want to change the subdirectory, then don't forget to also change it in the rewrite rule

**Comment by rob1998** [comment]
@tastyratz & @htpc-helper Please let me know if this block works for you

**Comment by htpc-helper** [comment]
Thanks @rob1998 for your help. Adding these lines to my config has resolved this problem:
```
            proxy_hide_header  Referer;
            proxy_hide_header  Origin;
            proxy_set_header   Referer           '';
            proxy_set_header   Origin            '';
```

I use subdomains, so I replace:
```
            add_header X-Frame-Options "SAMEORIGIN";
            rewrite /qbt/(.*) /$1 break;
```
With:
```
            proxy_hide_header       x-frame-options;
```

**Comment by causefx** [comment]
awesome find on the fix!

**Comment by tastyratz** [comment]
Unfortunately, that workaround is only for nginx. IIS instructions would be different or might require something else. This is something that could end up falling on qbittorrent though where that security "feature" could somehow be disabled. Does not seem to be high up on the priority list though.

**Comment by causefx** [comment]
ahhh crap, i will open again to see if someone can chime in.

**Comment by causefx** [comment]
Will close for now, if someone who uses IIS knows the fix, please post.

**Comment by Adrian-at-CrimsonAuzre** [comment]
FYI, disabling Clickjacking Protection will get it working with no extra steps.
![image](https://user-images.githubusercontent.com/1719461/41174534-6ea52134-6b28-11e8-8346-5b64a01e1490.png)


Unrelated: Can we get a [built in icon](https://raw.githubusercontent.com/qbittorrent/qBittorrent/master/src/icons/skin/qbittorrent32.png) for qBittorrent?

**Comment by causefx** [comment]
thanks for that....

also there is an image for QB already:

https://github.com/causefx/Organizr/blob/v2-develop/plugins/images/tabs/qBittorrent.png

**Comment by tastyratz** [comment]
That must be a very old version of QB. I'm on 4.1.1 and neither of those checkboxes are there anymore. That's viewing options from the client OR the webui.

**Comment by Adrian-at-CrimsonAuzre** [comment]
@causefx Ah, sorry about that then. Didn't realize it was in development, currently still on the stable release.

@tastyratz 
Pulled and built today:
![image](https://user-images.githubusercontent.com/1719461/41180901-d1f0aa28-6b3d-11e8-9f69-7082156db08f.png)

**Comment by evlo** [comment]
Hmm, for me, even unchecking clickjacking protection did not help:
qBittorent: 415
organizr: 180

**Comment by bad1dea** [comment]
if you disable the 2nd option after clickjacking, it'll work.

**Comment by causefx** [comment]
thank you @bad1dea

**Comment by JimboJamez** [comment]
Hey Team

Looking for some assistance on this issue. I have Qbitorrent v4.21 installed with nginx for reverse proxy on my Windows 10 machine. All other apps are reachable from outside the network (sonarr, radarr, organizr etc), but Qbitorrent isn't. 

I have the following location block set in my config file:

```
location /qbt/ {
            proxy_hide_header  Referer;
            proxy_hide_header  Origin;
            proxy_set_header   Referer           '';
            proxy_set_header   Origin            '';
            add_header X-Frame-Options "SAMEORIGIN";
            rewrite /qbt/(.*) /$1 break;
            proxy_pass http://127.0.0.1:8090;
        }
```
But when I navigate to the **mydomain/qbt** url I get a **https://mydomain/login/** address but a white screen with a 

> No input file specified.

error.

Any suggestions on how to resolve this?

**Comment by IamCage** [comment]
> if you disable the 2nd option after clickjacking, it'll work.

working  flawless! thank you

**Comment by PilaScat** [comment]
Pls help me, I tried all methods but is not working

**Comment by Suekru** [comment]
> Pls help me, I tried all methods but is not working

Make sure to add it to Organizr with your computer's IP address instead of localhost

**Comment by faustXman** [comment]
> if you disable the 2nd option after clickjacking, it'll work.

works now. thanks
