### ISSUE TITLE
Display Version Info

### ISSUE THREAD

**Issue by rudyvarner** [causefx/Organizr#84]
How about adding the current version, commit/branch to the information page?

**Comment by causefx** [comment]
Current version is already there... you just want the branch added?

**Comment by rudyvarner** [comment]
I'm not seeing it.  I'm on the latest Master version too

![about](https://cloud.githubusercontent.com/assets/5005529/22478744/28946a54-e7b9-11e6-8876-98698874e7bc.png)

**Comment by causefx** [comment]
Wow. That's odd. Is there anything in the browser console?

**Comment by rudyvarner** [comment]
This is the only error in the browser console

Uncaught SyntaxError: Invalid hexadecimal escape sequence     VM2034 settings.php:4651

**Comment by causefx** [comment]
Let me look into that. What browser is this on?

**Comment by rudyvarner** [comment]
Chrome

**Comment by causefx** [comment]
can you load it up again and then view the source to see whats on that line? Line 4651

**Comment by causefx** [comment]
I bet it is this line:

`$(infoTabVersion).html("<strong><?php echo $language->translate("INSTALLED_VERSION");?>: </strong>" + currentVersion + " <strong><?php echo $language->translate("CURRENT_VERSION");?>: </strong>" + githubVersion + " <strong><?php echo $language->translate("DATABASE_PATH");?>:  </strong> <?php echo DATABASE_LOCATION;?>");`

can you tell me what the exact string is that is for you databaseLocation in the ini.php file?

**Comment by rudyvarner** [comment]
This is the content of my databaseLocation.ini.php file

`; <?php die("Access denied"); ?>
databaseLocation = "C:\xampp"
timezone = "America/Detroit"
titleLogo = ""
loadingIcon = ""
`

**Comment by causefx** [comment]
i just fixed it.  I will push a release today

**Comment by causefx** [comment]
@rudyvarner can you delete your databaseLocation.ini.php file and reload...

**Comment by rudyvarner** [comment]
Works! Thanks for fixing it so quickly!
