### ISSUE TITLE
Check for valid DB path, otherwise everything breaks

### ISSUE THREAD

**Issue by JesseHawkins** [causefx/Organizr#846]
###### Operating System: unRAID (Slackware Linux)
<hr>

##### Problem Description:
Defining a path for DB storage that doesn't exist will break things, however, there doesn't seem to be error checking for this.

<hr>

##### Reproduction Steps:
New install > as advised, choose a path other than /config/www > pick a path that doesn't yet exist on disk, like /config/db > complete setup with Finish button > app breaks.

<hr>

#### Errors on screen?  If so paste here:
Finish button doesn't move the screen forward, guest icon is missing if you reload the page, login fails, etc. Things are broken.
```

```

**Comment by causefx** [comment]
whoops, i will add that...
