### ISSUE TITLE
Homepage calendar doesn't respect alternative homepage titles option

### ISSUE THREAD

**Issue by Saltystew** [causefx/Organizr#848]
###### Operating System: Ubuntu
<hr>

##### Problem Description:
The blue title/text header for the calendar on the homepage from sonarr/radarr doesn't respect the alternative homepage titles option when enabled.

<hr>

##### Reproduction Steps:
Enable sonarr/radarr calender on homepage, as well as at least any one other homepage option, and then enable alternative homepage titles.

<hr>

**Comment by causefx** [comment]
I have to see how i want to code the css on this one.  was intentional for time being.
