### ISSUE TITLE
Get Plex Machine

### ISSUE THREAD

**Issue by justinglock40** [causefx/Organizr#850]
###### Operating System: Windows
<hr>

##### Problem Description:
Get Plex Machine ID button does not list the actual plex servers for selection. Nothing gets listed just says choose plex machine

<hr>

##### Reproduction Steps:
click get plex machine "retrieve" button

<hr>

#### Errors on screen?  If so paste here:

```

```

**Comment by justinglock40** [comment]
<img width="1311" alt="screenshot at may 05 08-36-57" src="https://user-images.githubusercontent.com/23133649/39663816-80fb21f2-503f-11e8-84a4-6e5f6b6b94ca.png">

**Comment by causefx** [comment]
Is the token valid above this?

**Comment by justinglock40** [comment]
Yea I entered my Plex credentials and it pulled the token itself

**Comment by causefx** [comment]
are there any errors in console?

also can you try this url?  replace token with yours:

https://plex.tv/pms/servers?X-Plex-Token=xxxxxxxxxx

**Comment by justinglock40** [comment]
I ended up just copying the machine ID block from ombi and all is well. I have problems getting the php mailer connected though. I’m trying to connect Gmail.

**Comment by causefx** [comment]
Let me check my gmail settings and will get back to u

**Comment by causefx** [comment]
Here ya go:

![image](https://user-images.githubusercontent.com/16184466/39678067-a19e1300-513a-11e8-921b-14933554989c.png)

Test button works with these settings and email center works too

**Comment by justinglock40** [comment]
I get this message after double checking everything? At the bottom right. Is there something else that needs to be enabled in PHP.ini?

<img width="1449" alt="screenshot at may 06 16-39-06" src="https://user-images.githubusercontent.com/23133649/39678118-3d1aa2d8-514c-11e8-940b-6eb4d9ff4090.png">

**Comment by justinglock40** [comment]
Also what is the domain link override for?

**Comment by causefx** [comment]
Have u enabled insecure apps in google settings? And the override link is for placing a certain domain for links in email.

**Comment by justinglock40** [comment]
Yea it says that it is on
    (https://mail.edison.tech/chat-invite.html?invitorName=Justin%20Washington&invitorEmail=justinglock40@gmail.com&message=Yea%20it%20says%20that%20it%20is%20on&mid=6248fe2fead2492093dc2a54d0a888dd&group=Author;author@noreply.github.com,causefx/Organizr;reply@reply.github.com,causefx/Organizr;organizr@noreply.github.com)
  
  

  
Sent With Edison Mail
  
  
    
  
  
  

  
  

  
  
>

**Comment by causefx** [comment]
What OS are you on?

**Comment by justinglock40** [comment]
Windows 10
    (https://mail.edison.tech/chat-invite.html?invitorName=Justin%20Washington&invitorEmail=justinglock40@gmail.com&message=Windows%2010&mid=2dd150c10d0346829417e8b734c40766&group=Author;author@noreply.github.com,causefx/Organizr;reply@reply.github.com,causefx/Organizr;organizr@noreply.github.com)
  
  

  
Sent With Edison Mail
  
  
    
  
  
  

  
  

  
  
>

**Comment by causefx** [comment]
Do you have valid cert file?

**Comment by causefx** [comment]
i.e.

```
[curl]
; A default value for the CURLOPT_CAINFO option. This is required to be an
; absolute path.
curl.cainfo = "C:\nginx\php\cacert.pem"
```

**Comment by justinglock40** [comment]
Cert file???
    (https://mail.edison.tech/chat-invite.html?invitorName=Justin%20Washington&invitorEmail=justinglock40@gmail.com&message=Cert%20file???&mid=d7fc8c5e56724a32bc31f602db2ba743&group=Author;author@noreply.github.com,causefx/Organizr;reply@reply.github.com,causefx/Organizr;organizr@noreply.github.com)
  
  

  
Sent With Edison Mail
  
  
    
  
  
  

  
  

  
  
>

**Comment by justinglock40** [comment]
Using caddy not NGINX
    (https://mail.edison.tech/chat-invite.html?invitorName=Justin%20Washington&invitorEmail=justinglock40@gmail.com&message=Using%20caddy%20not%20NGINX&mid=982ee8c1c3c74ae9aa47814027f72870&group=causefx/Organizr;organizr@noreply.github.com,Author;author@noreply.github.com,causefx/Organizr;reply@reply.github.com)
  
  

  
Sent With Edison Mail
  
  
    
  
  
  

  
  

  
  
>

**Comment by causefx** [comment]
Download from here:

https://curl.haxx.se/ca/cacert.pem

place in php folder...

find `curl.cainfo = ""` in php.ini file

replace with `curl.cainfo = "C:\nginx\php\cacert.pem"`

**Comment by justinglock40** [comment]
Even if I’m not using NGINX?
    (https://mail.edison.tech/chat-invite.html?invitorName=Justin%20Washington&invitorEmail=justinglock40@gmail.com&message=Even%20if%20I%E2%80%99m%20not%20using%20NGINX?&mid=5a1afb1c16c44d6faf5a6bb6b14c04e5&group=Author;author@noreply.github.com,causefx/Organizr;reply@reply.github.com,causefx/Organizr;organizr@noreply.github.com)
  
  

  
Sent With Edison Mail
  
  
    
  
  
  

  
  

  
  
>

**Comment by causefx** [comment]
this is php, it's regardless of webserver

**Comment by justinglock40** [comment]
Still no go

**Comment by causefx** [comment]
did yea restart php and caddy just in case

**Comment by justinglock40** [comment]
Yep still nothing. Just says can not connect to host.

**Comment by causefx** [comment]
is this line commented out in php.ini?


`extension=php_openssl.dll`

**Comment by justinglock40** [comment]
Yea it’s setup correctly. I switched from gmail to iCloud and it worked.

**Comment by justinglock40** [comment]
What is the domain link override meant for?

**Comment by justinglock40** [comment]
I have one more issue. the Open Invite Modal button doesn’t work for me in the media invites plugin

**Comment by causefx** [comment]
for links in the emails, such as invite codes and links back to your own Organizr.

Organizr will use whatever is in webserver servername, but you can override with what ever you want.

**Comment by justinglock40** [comment]
Alright cool thanks.

**Comment by kcwebby** [comment]
So I am having the same issue with the getting of machine ID.  Same results as the prior poster.   Can we verify this works?  (I'm not worried about the email, or the managing of invites now, my issue is related to being able to use Plex Logins to login).

**Comment by causefx** [comment]
does oAuth work for either you or one of your users?

**Comment by kcwebby** [comment]
I've just installed it -- Plex works throughout the app, but not for my oauth login.  I'll have to get with a user to see if they can try it, but right  now, its only accessible inside my network.

With recommendations during setup, I made my username match my plex username, and email match the email used for plex signup.   Like I stated, I get the oauth success message, then a few seconds later, I get a username/password combo wrong error.

![image](https://user-images.githubusercontent.com/10803458/50554138-c3153080-0c7a-11e9-89bc-3f5b80509240.png)


Also regarding the get machine ID...  I've noticed this also is not working for another software, so I wonder if there have been some Plex Side changes that would require adaptation to work.  Thanks!

**Comment by kcwebby** [comment]
Yes to both -- I had seen that somewhere, and made sure, as well -- during setup it suggested making it the same..  Right now, even my password syncs up with my Plex Password.

I'm a old Plex user, my username was just a name, then converted to an email, on plex website, both still work.   I have tried it both ways in the settings and neither works.

**Comment by causefx** [comment]
Can you check and see what the organizr logs say?

**Comment by kcwebby** [comment]
from my login just now:  the Transmission error, I know about, I have it
shut down currently.

The failure was the oauth, and then I login using the internal account.

[image: image.png]

**Comment by kcwebby** [comment]
I guess it doesn't auto-attach from emails -- Updated the post via the web.
![image](https://user-images.githubusercontent.com/10803458/50606525-abf95d00-0e8b-11e9-986e-3dcb947a84f9.png)

**Comment by causefx** [comment]
![image](https://user-images.githubusercontent.com/16184466/50606657-c16a8900-0e83-11e9-9147-4aeff7473090.png)

Were these two from the exact same login or was one oauth and the other normal?

**Comment by kcwebby** [comment]
the first was the Oauth plex login (with the oauth successful banner), and
second was the internal account

**Comment by causefx** [comment]
CAn you screenshot this section:
![image](https://user-images.githubusercontent.com/16184466/50607278-dfd18400-0e85-11e9-9fb6-8d262c73d700.png)

**Comment by kcwebby** [comment]
Sure -- looks exactly like yours :) 

on a side note, I did just re-try the get plex machine routine, and it worked this time, showing my server... but it had no effect on the ability to login with my plex account.

![image](https://user-images.githubusercontent.com/10803458/50609881-a5241780-0e96-11e9-87a3-c830a75152ab.png)

**Comment by causefx** [comment]
update organizr manually, and goto page above and turn off new toggle.

**Comment by causefx** [comment]
linux server doesn’t have a v2 docker image. how did u get v2?

**Comment by kcwebby** [comment]
oh my bad, that's right, theirs was v1.   I'm using
this organizrtools/organizr-v2

**Comment by causefx** [comment]
ok just restart the container

**Comment by kcwebby** [comment]
Updated -- saw the pull in the log.    Disabled the strict friends, no joy
on login.   enabled strict friends -- no joy on login.  Both attempts with
the Plex admin user.

-----------------------
| Updating Organizr |
-----------------------
HEAD is now at 2956037 Added official docker check
From https://github.com/causefx/Organizr
2956037..dc93048 v2-develop -> origin/v2-develop
Updating 2956037..dc93048
Fast-forward
api/config/default.php | 3 ++-
api/functions/auth-functions.php | 10 +++++++---
api/functions/organizr-functions.php | 8 ++++++++
3 files changed, 17 insertions(+), 4 deletions(-)
Current branch v2-develop is up to date.
[cont-init.d] 30-install: exited 0.
[cont-init.d] 30-keygen: executing...
using keys found in /config/keys
[cont-init.d] 30-keygen: exited 0.
[cont-init.d] 60-config: executing...
[cont-init.d] 60-config: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.

**Comment by causefx** [comment]
screenshot this section:
![image](https://user-images.githubusercontent.com/16184466/50705805-3622fc00-1019-11e9-8004-1a2f703655d9.png)

**Comment by kcwebby** [comment]
based on your screenshot, I noticed that I had my admin username as the
full email address that I login on plex.tv.   I changed to
bmeinershagen (I've been switching it back and forth during prior testing),
and I am now able to login.

Perhaps a recommendation to call out that its the username that is
displayed after you login, and not the user name that you use to login
(plex has asked people to start logging in with their full email for a
while now)

Thanks!

**Comment by causefx** [comment]
it should have worked with email in there as long as you logged in with email on org login page.

**Comment by kcwebby** [comment]
Yeah, the confusing part is when I login, the confirmation message is this:  which shows the full email.

![image](https://user-images.githubusercontent.com/10803458/50707259-daab3b00-1025-11e9-876a-5ee10ecac14e.png)


Anyways, glad its fixed, thanks for working through it with me.

Does this SSO allow the plex authentication token to pass through to tautilli or ombi (or will it in future releases) ?

**Comment by causefx** [comment]
yes, it passes them now if you use oauth.  if you dont, it passes the username and pass, i will clean it up in the future.

**Comment by SavageAUS** [comment]
I too am having an issue with organizr not showing my plex machine running in a freenas jail. All my settings look like the ones above. Using work around with manually adding token and machine id I have plex connected but if I click on get plex machine it does not show my server. Oh and I’m running version 2.0.0

**Comment by CollinChaffin** [comment]
Why on earth is this closed?!  This button simply does NOT work in v2.  If it does I would sure love to see a video shot of someone actually clicking the `Get Plex Machine` button and what magic combination is needed to make it return a server.

If I fill in my full plex email and pass for the `Get Plex Token` it works properly and retrieves the token.  Then, whether I use that same full Plex email address in the separate `Admin Username` box, or god forbid as someone above showed try to use just left of the `@` (which for me is a very common `htpc` since my full Plex ID is `htpc@MYDOMAIN.COM` - nothing works.

Can this be reopened until that is fixed or explained please?  Thanks!

**Comment by causefx** [comment]
The button works for 95% of Organizr users...  There is a setting in Plex that is causing this... As Organizr just parses the data it receives from Plex.  For now just copy the id from the URL when you visit your plex instance in browser.  I will play around with plex to find this setting.


https://vid.organizr.app/2019-05-16_08-15-29.mp4

**Comment by causefx** [comment]
@CollinChaffin ,

Actually I would like to try something if you have some time.

**Comment by antigravity83** [comment]
Yeah doesn't work for me either. Just get a blank list. 

Entered in the correct Plex Token, Admin ID etc

**Comment by tallevi1000** [comment]
This issue is not yet fixed.
Also, the token grabbed is the wrong one.
To find your plex token follow these simple steps:
https://www.plexopedia.com/plex-media-server/general/plex-token/

Once you grab the token, navigate to this URL:
http://PLEX_IP_HERE:32400/?X-Plex-Token=PLEX_TOKEN_HERE
Where "PLEX_IP_HERE" is the IP address of your plex server and "PLEX_TOKEN_HERE" is the token you grabbed in the previous step.
Once the URL loads, search for "machineIdentifier=" and copy the value there (copy just the string without the "")
Now head back the Organizr and use these values to configure Plex.
