### ISSUE TITLE
OrgV2 on Mobile - Missing Server Logo

### ISSUE THREAD

**Issue by zhdenny** [causefx/Organizr#853]
###### Operating System: Docker/Linux
<hr>

##### Problem Description:
When browsing on Mobile (Android 8.1), the server logo in the top left is missing. I do not know if this was intentional, but I wanted to mention

<hr>

##### Reproduction Steps:
Browse on Mobile. Look at top left for server logo. It is missing.

<hr>

**Comment by causefx** [comment]
that is intended, its more for a minimalist feel, the logo still shows up on the tab menu.   If you would like to add it back it can be done with custom css.

**Comment by zhdenny** [comment]
Ah gotcha. Understandable.

**Comment by causefx** [comment]
Thanks for understanding.
