### ISSUE TITLE
Extended support for home page's media server and requests modules

### ISSUE THREAD

**Issue by massoh** [causefx/Organizr#854]
Scenario 1: 

Good - A new episode or season has been added to Plex for a Television series and the media server module demonstrates this by adding the poster for the relevant season in the carousel. 

Bad - When mousing over the poster it doesn't signify the episode or season number and when clicking on the poster the pop-up only shows information about the whole series, not the season or episode.

Bad - When clicking on the link to open the item in Plex it only directs you to the shows main page, not the page for that season or episode.

Scenario 2: 

Good - A new album has been added to Plex and the homepage media module demonstrates this by displaying the poster for the album in the carousel. When mousing over the poster it displays the artist and the album name.

Bad - When clicking on the Album it brings up the page of the artist but does not mention the album or its information.

Bad - When clicking on the link to open the item in Plex it only directs you to the artists main page, not the page for the album.

Scenario 3:

Problem: You wish to request a specific season or episode of a television show in the requests module but you can only add the whole series.

Scenario 4:

Good: Your request has been generated for a television series' season or episode and a poster appears in the requests carousel.

Bad: The poster art is only for the series not for the season (or episode) requested.

Bad: When mousing over the request it does not denote the season(s) or episode(s) that were requested.

Bad: When clicking on the poster it brings you information only about the series and does not denote the season(s) or episodes(s).

Bad: There is no link to open the retrieved items in Plex. It should provide links to the fulfilled request item(s).

**Comment by causefx** [comment]
hi there,

1&2.  Season and album - 9/10 times plex has zero metadata info... that is the reason i choose to go with parent info.

3.  I will look into improving this.
4.  All of this information is gathered from the request api from Ombi. we are limited to what they give.

**Comment by hossame** [comment]
Appreciate it! I'll go bother the Plex and Ombi developers to expand on their APIs now.

**Comment by GroupMaster** [comment]
hossame, get'er done! I'm down with that!

**Comment by causefx** [comment]
Feel free to add some of these to Feathub.
