### ISSUE TITLE
General Question

### ISSUE THREAD

**Issue by justinglock40** [causefx/Organizr#857]
What functionality does this provide?

<img width="962" alt="screenshot at may 07 19-09-14" src="https://user-images.githubusercontent.com/23133649/39730946-281158a8-522a-11e8-8a4c-c64af8b00264.png">

**Comment by jonfinley** [comment]
You can set your own wallpaper instead of using the default.

**Comment by justinglock40** [comment]
Does it need to be saved somewhere specific?

**Comment by jonfinley** [comment]
Uploaded with your images.

**Comment by justinglock40** [comment]
Where do the images get uploaded too?

**Comment by causefx** [comment]
`/plugins/images/tabs`

you can also copy path from image manager
