### ISSUE TITLE
In the settings menu, when selecting a tab it doesn't auto select/show the first sub-tab. 

### ISSUE THREAD

**Issue by gilbN** [causefx/Organizr#866]
###### Operating System: Unraid Docker
<hr>

##### Problem Description:
In the settings menu, when selecting a tab it doesn't auto select the first sub-tab. 

For example when going to the `Customize tab` it should select and show the `Appearance` tab automatically.  Now you have to select `Appearance` even though it's the only sub-tab.

System settings, plugins and image manager already does this. 

<hr>

```

```

**Comment by causefx** [comment]
i have to think about this :)

**Comment by causefx** [comment]
this is complete!
