### ISSUE TITLE
Deluge homepage not hiding Seeding/Completed

### ISSUE THREAD

**Issue by Pinezerka** [causefx/Organizr#867]
Organizr Version: V 2.0.0-beta.100
Branch: v2-develop
WebSever: Nginx
Operating System: Unraid Docker
<hr>

##### Problem Description:
Hide Seeding
Hide Completed in deluge not seem to be working
<hr>

#### Errors on screen?  If so paste here:

```

```

**Comment by causefx** [comment]
When was the last time you pulled from github?

**Comment by christronyxyocum** [comment]
This functionality is working for me and I'm running latest version.

**Comment by Pinezerka** [comment]
Works but not hiding torrents at 100% with these settings

Pulled 3rd October 2018
Organizr: v2-develop
Deluge:1.3.15
WebAPI-0.3.1-py2.7.egg

![2018-10-03_16-17-24](https://user-images.githubusercontent.com/39213507/46394408-349b1c80-c728-11e8-9d80-b7bf497cd688.png)
![chrome_2018-10-03_16-15-12](https://user-images.githubusercontent.com/39213507/46394455-4e3c6400-c728-11e8-877b-8e4ad55d500f.png)

**Comment by causefx** [comment]
is this still happening? I dont use deluge anymore so i cant test.

**Comment by Pinezerka** [comment]
still happens

**Comment by causefx** [comment]
fixed, thanks @Pinezerka
