### ISSUE TITLE
TYPE:New Window leaves Organizr with a blank window

### ISSUE THREAD

**Issue by Pinezerka** [causefx/Organizr#868]
Organizr Version: V 2.0.0-beta.100
Branch: v2-develop
WebSever: Nginx
Operating System: Unraid Docker
<hr>

##### Problem Description:
opening a page in "TYPE:New Window" leaves Organizr with a blank window

<hr>

#### Errors on screen?  If so paste here:

```

```

**Comment by causefx** [comment]
completed.
