### ISSUE TITLE
Organiz V2 on Synolgy Diskstation

### ISSUE THREAD

**Issue by andyrav** [causefx/Organizr#869]
Hi 
Has anyone manage to get V2 working on Synology Diskstation?
Not Writable - Please fix permissions
Checked and are the same as V1

**Comment by causefx** [comment]
can you make sure the parent permissions are set too'?

**Comment by sydtrakked** [comment]
You need to make sure your 'http' User Group has read/write permissions on your organizr directory/sub-directories/files

**Comment by causefx** [comment]
setup should be exact same.

**Comment by spacecakes** [comment]
No. I get these errors no matter what PGID and PUID I put. `[pool www] please specify user and group other than root`
