### ISSUE TITLE
Multi-Device Login

### ISSUE THREAD

**Issue by rix1337** [causefx/Organizr#87]
I though this wasn't as high on my list, but I switch devices frequently.. any way to allow for multiple valid tokens to exist? 

So maybe a maximum of 3-5 current logins per user that are allowed..

**Comment by causefx** [comment]
I can do this but it will make it less secure.  It will only set one token for the device but will disable the token check, I can leave this as a toggle in settings.

**Comment by rix1337** [comment]
This. It should not be a default setting ..

More like an option for convenience...

**Comment by rix1337** [comment]
The new notifications are beautiful btw!

**Comment by causefx** [comment]
:) thanks!  I felt like i needed to change it to make it look more together.  As for the setting, yes it will not be default, it will have to be enabled.

**Comment by rix1337** [comment]
Cool stuft. Thanks you

**Comment by causefx** [comment]
I'll try to have ready for 1.0

**Comment by rix1337** [comment]
I requested it in time, it seems :D

**Comment by causefx** [comment]
this done, awaiting next commit.

**Comment by StevenChorkley** [comment]
What about discarding all authenticated tokens, similar to what facebook/google do?

Is this feature in the nightly @causefx?
