### ISSUE TITLE
Make it 2 different permissions on Ombi -  View requested content / Request content

### ISSUE THREAD

**Issue by Fma965** [causefx/Organizr#870]
###### Organizr Version: V2.0.0-beta.100
<hr>

##### Problem Description:
There is no way to have ombi show requested content but not allow requesting content, need for granular permission. 

I have 2 groups of users some RO and some can request. people who are RO should still be able to see the requested content but not be able to add their own requests.

Great work on V2 though, it's fast as hell and the granular permissions are almost perfect :) 

I'm on discord most of the time if this doesn't make sense.

**Comment by causefx** [comment]
completed

**Comment by Fma965** [comment]
mate... that was some quick :) perfect thanks
