### ISSUE TITLE
Small request with Sickrage homepage guide

### ISSUE THREAD

**Issue by GroupMaster** [causefx/Organizr#872]
###### Operating System: Debian
<hr>

##### Problem Description:

No problems, just loving it. I do however have feature requests...

I would like to know if it would be possible to include at minimum season & episode numbers for shows on the schedule grid displayed on the homepage. I have had many times where back issues were downloaded and mistaken for the most recent episode due to how generic the info is.

Also, would it be possible to allow for transparent logins to an included wordpress site. A "sign into one, sign into all" sort of thing. I have found that using wordpress inside organizr allows me to not only include all the web interfaces but to include a very capable info site as well. Some features within require a valid login to use and only having to sign in once would be nifty.

Thank you for your time.
C

<hr>

##### Reproduction Steps:

<hr>

#### Errors on screen?  If so paste here:

```

```

**Comment by causefx** [comment]
Lemme look into this

**Comment by causefx** [comment]
So i have checked back thru the docs for sickbeard/Rages API.  this is a limitation on their end as they dont really have a calendar-esq api endpoint... I have to use history....  with that being said, im not sure how we could tie in a minimum season number unless it was by show name which is not possible atm.

Here is a sample result of the api output from history:

```json
{
    "data": [
        {
            "date": "2011-08-19 12:58", 
            "episode": 4, 
            "provider": "-1", 
            "quality": "SD TV", 
            "resource": "project.runway.s09e04.all.about.nina.hdtv.xvid-crimson.avi", 
            "resource_path": "C:\\Users\\sickbeard\\Documents\\downloads\\complete\\TV\\Project.Runway.S09E04.All.About.Nina.HDTV.XviD-CRiMSON", 
            "season": 9, 
            "show_name": "Project Runway", 
            "status": "Downloaded", 
            "tvdbid": 74285
        }, 
        {
            "date": "2011-08-19 12:25", 
            "episode": 4, 
            "provider": "NZBs.org", 
            "quality": "SD TV", 
            "resource": "Project.Runway.S09E04.All.About.Nina.HDTV.XviD-CRiMSON", 
            "resource_path": "", 
            "season": 9, 
            "show_name": "Project Runway", 
            "status": "Snatched", 
            "tvdbid": 74285
        }
    ], 
    "message": "", 
    "result": "success"
}
```

**Comment by serfilian** [comment]
Not sure if this is still relevant but Sickrage does actually have a calendar located at http://server:port/web_root/calendar (trailing slash would cause an error as documented here: https://github.com/SickRage/SickRage/issues/3879). Would it be possible to add that to organizr calendar?

**Comment by causefx** [comment]
I believe I added sickrage to v2 already

**Comment by serfilian** [comment]
Ah, ok. I 'm running V1. Guess I better upgrade then.
