### ISSUE TITLE
[V2] about:blank tab when trying to view emby content from recent items

### ISSUE THREAD

**Issue by hbooo** [causefx/Organizr#874]
###### Operating System: Synology
<hr>

##### Problem Description:
When I try to open a recent item by clicking on the emby logo in the popin, a new tab is opened with about:blank

<hr>

##### Reproduction Steps:

Go to homepage with emby set, click on a tv show (or a movie)

<hr>

#### Errors on screen?  If so paste here:

```

```

**Comment by causefx** [comment]
@rob1998 do you have this issue too?

**Comment by causefx** [comment]
Also, did you fill in these boxes?

![image](https://user-images.githubusercontent.com/16184466/40147653-610eee94-591f-11e8-864b-77e8812bab32.png)

**Comment by hbooo** [comment]
Hi, 

I hadn't fill the boxes, I did it know, i'm correctly redirected to the tab, but I have a black tab not loading
![image](https://user-images.githubusercontent.com/242125/40168969-29f4dc38-59c5-11e8-9df0-13e8365128ff.png)

Emby tab works if I go to it directly

**Comment by causefx** [comment]
Fixed.
