### ISSUE TITLE
Hide 'Forgot pwd?' link option

### ISSUE THREAD

**Issue by massoh** [causefx/Organizr#877]
For those who are authenticating users to an external backend (Plex) can we add an option to remove the 'Forgot Pwd?' link on the sign-in block?

**Comment by causefx** [comment]
Rather then coding in toggles, i think it would be best to use CSS for this....

```
a#to-recover {
    display: none;
}
```

**Comment by massoh** [comment]
Excellent, works perfectly.

**Comment by causefx** [comment]
:)
