### ISSUE TITLE
Issues with static-globals.php 

### ISSUE THREAD

**Issue by arnie311** [causefx/Organizr#878]
###### Operating System: Windows
<hr>

##### Problem Description:
4 errors show up on the home page when it first loads. No settings have been made or changed.

<hr>

##### Reproduction Steps:
Pulled the repo at 3:45 pm CDT May 17th 2018

<hr>

#### Errors on screen?  If so paste here:

```
( ! ) Warning: dirname() expects exactly 1 parameter, 2 given in ...\orgv2\api\functions\static-globals.php on line 7

( ! ) Warning: dirname() expects exactly 1 parameter, 2 given in ...\orgv2\api\functions\static-globals.php on line 8
--

( ! ) Warning: dirname() expects exactly 1 parameter, 2 given in ...\orgv2\api\functions\static-globals.php on line 21
--

( ! ) Warning: dirname() expects exactly 1 parameter, 2 given in ...\orgv2\api\functions\static-globals.php on line 16
--
```
File in question:
![snag_31323cc1](https://user-images.githubusercontent.com/10731453/40258686-0483e540-5ab8-11e8-8861-b4a535b22d03.png)

**Comment by causefx** [comment]
What version of PHP?

**Comment by causefx** [comment]
What version of PHP?

**Comment by causefx** [comment]
What version of PHP?

**Comment by arnie311** [comment]
what came with WPN-XM

**Comment by arnie311** [comment]
Current PHP version: 5.6.12

**Comment by causefx** [comment]
odd that it let you install org, as org requires version 7.

**Comment by arnie311** [comment]
feel free to close this
