### ISSUE TITLE
Organizr v2 - Ombi SSO not working

### ISSUE THREAD

**Issue by jaydee99** [causefx/Organizr#880]
###### Operating System: Ubuntu
<hr>

##### Problem Description:

Hi,

Ombi SSO is not working anymore in V2. It was working with V1 and i'm using the same nginx conf file. Tautulli and Plex SSO are working perfect.

Any tips ?

Thanx !

<hr>

##### Reproduction Steps:

<hr>

#### Errors on screen?  If so paste here:

```

```

**Comment by jaydee99** [comment]
Ok solved it by using your nginx ombi guide ;)

https://github.com/causefx/Organizr/wiki/Ombi-SSO

**Comment by si0972** [comment]
Close the issue please.
