### ISSUE TITLE
v2 Various bugs

### ISSUE THREAD

**Issue by jaydee99** [causefx/Organizr#882]
###### Operating System: Ubuntu
<hr>

##### Problem Description:

Hi,

Some bugs i have seen so far with v2

- Users are not redirected to homepage after login, even if it is set as default page. It shows a blank screen
https://imgur.com/GA4TAz3

- Horizontal style layout has a problem as you can see
https://imgur.com/hTbs1Px

- Text layout in settings, when using french is not good
https://imgur.com/rwSZlCa

Thank you !

<hr>

##### Reproduction Steps:

<hr>

#### Errors on screen?  If so paste here:

```

```

**Comment by causefx** [comment]
on the last can i see the full size window?
