### ISSUE TITLE
[v2] Several closing buttons (X) are misplaced

### ISSUE THREAD

**Issue by christronyxyocum** [causefx/Organizr#883]
###### Operating System: Docker for Linux
<hr>

##### Problem Description:

The closing X for the media search box is way off to the right.
<hr>

##### Reproduction Steps:

Open the media search box.
<hr>

#### Errors on screen?  If so paste here:

```
functions.js?v=2.0.0-beta.200:3835 Uncaught TypeError: Cannot read property 'length' of undefined
    at buildMediaResults (functions.js?v=2.0.0-beta.200:3835)
    at Object.<anonymous> (custom.min.js?v=2.0.0-beta.200:1)
    at i (jquery-2.2.4.min.js:2)
    at Object.fireWith [as resolveWith] (jquery-2.2.4.min.js:2)
    at z (jquery-2.2.4.min.js:4)
    at XMLHttpRequest.<anonymous> (jquery-2.2.4.min.js:4)
```

![2018-05-20 14_21_34-tronflix - organizr v2](https://user-images.githubusercontent.com/22502007/40282193-9b318ac4-5c39-11e8-8cf0-6a6354b46a1d.png)

**Comment by christronyxyocum** [comment]
Looks like other boxes are affected.

![foo](https://user-images.githubusercontent.com/22502007/40282548-10bf035c-5c3f-11e8-8323-8f594881fc6f.png)

**Comment by si0972** [comment]
^^ Looks to affect all homepage-setting-boxes. Plugin-boxes does also have ther X's missaligned

**Comment by causefx** [comment]
im changing the framework away from magnific

**Comment by christronyxyocum** [comment]
FYI, that CSS just makes the X disappear completely.
