### ISSUE TITLE
v2 - Invite System Error

### ISSUE THREAD

**Issue by sydtrakked** [causefx/Organizr#884]
###### Operating System: Synology
<hr>

##### Problem Description:
I am attempting to test the Invite System but keep getting "Invite Error - Code Incorrect"

<hr>

##### Reproduction Steps:
1. Create invite in Admin profile successfully.
2. Log out of Admin profile.
3. Receive invite email at test account successfully. 
4. Click on the link to "Use Invite Code"
5. Browser opens to Organizr login page with invite code populated and I click Verify.
6. Prompt asks if user already has a Plex account, click yes and enter Plex credentials.
7. Receive "Invite Error - Code Incorrect" message

<hr>

#### Errors on screen?  If so paste here:

```
Invite Error - Code Incorrect
```

**Comment by causefx** [comment]
Let me test

**Comment by causefx** [comment]
can you check invite manager.... does it show the code being used?

**Comment by sydtrakked** [comment]
Yes it does.

**Comment by causefx** [comment]
cau you check logs in settings?

**Comment by sydtrakked** [comment]
![capture](https://user-images.githubusercontent.com/16075507/40334395-66e34af8-5d12-11e8-9977-42dc32f242aa.PNG)
This is what it shows pertaining to that invite

**Comment by causefx** [comment]
I added one line of code to write the response code of the request... You can update org to see and test again.

**Comment by sydtrakked** [comment]
`Plex Invite Function - An error occurred [404]`

That's the new error I get back in the logs.

**Comment by causefx** [comment]
odd, you should not get a 404....


go here please:

https://plex.tv/api/servers/ADDplexIDhere/shared_servers/?X-Plex-Token=ADDplexToken

**Comment by causefx** [comment]
Please double check the Plex Machine ID field in organizr then.


Having the incorrect ID would be the only way it gives 404 error.

**Comment by sydtrakked** [comment]
I copied Plex ID/Token directly from my Organizr settings

**Comment by causefx** [comment]
I cannot recreate this bug you are having on either of my instances.   I also had 2 other people try as well.

**Comment by sydtrakked** [comment]
Were any of the instances running on Synology? I'm wondering if there are differences in the PHP version on Synology vs. a normal Nginx installation.

**Comment by causefx** [comment]
can you screen shot the media settings plugin page?

**Comment by sydtrakked** [comment]
This one? 

![capture](https://user-images.githubusercontent.com/16075507/40559543-f4b4ccb6-600b-11e8-882a-fe7eb6a3fe7c.PNG)

**Comment by causefx** [comment]
Okay, i think i found the issue.  Can you try this new commit out please?

**Comment by sydtrakked** [comment]
![capture](https://user-images.githubusercontent.com/16075507/41636307-7b7198a6-7402-11e8-9a1e-0427da952eb3.PNG)

I'm still getting a 404 error

**Comment by causefx** [comment]
This was fixed, I dont recall which commit it was.  Please clear libraries in invite settings and reset them.

**Comment by sydtrakked** [comment]
Thanks for the update. I will check it out when I get a chance. It has been quite a while since I've had some time to update and mess around with my Organizr install

**Comment by causefx** [comment]
Thanks 🙏

**Comment by sydtrakked** [comment]
Appears to be working as intended! Thanks! That's just one more awesome piece to the puzzle

**Comment by causefx** [comment]
Awesome sauce 🤠
