### ISSUE TITLE
[V2] Error when adding Transmission to homepage

### ISSUE THREAD

**Issue by KoopaTroopas** [causefx/Organizr#885]
###### Operating System: Ubuntu
<hr>

##### Problem Description:

I am attempting to add Transmission to the homepage of Organizr V2, no matter which URL I seem to try it doesn't add and gives errors in the logs

<hr>

##### Reproduction Steps:

Go to Settings, Tab Editor, Homepage Items, Transmission.  I fill out the URL, username, and password.
I've tried multiple URLs:
http://ubuntu-downloader:9091
http://ubuntu-downloader:9091/transmission
http://ubuntu-downloader:9091/transmission/web
http://192.168.1.58:9091
http://192.168.1.58:9091/transmission
http://192.168.1.58:9091/transmission/web
https://mydomain.com/transmission
https://mydomain.com/transmission/web

I've also tried with a trailing /
<hr>

#### Errors on screen?  If so paste here:

I was getting this error fairly often, but I can't seem to reproduce now 
```
Transmission Connect Function - Error: Could not get session ID
```

The error that I am getting now is
```
Transmission Connect Function - Error: cURL error 6: Could not resolve host: myusername
```

**Comment by rix1337** [comment]
Same issue with latest .600 beta for me.

**Comment by KoopaTroopas** [comment]
I was never able to figure out what was causing this, I ended up reinstalling organizr, now when using http://192.168.0.108:9091/transmission as the URL it works fine

**Comment by rix1337** [comment]
You are right. Couple of restarts later with `/transmission` after the host:ip block it works.

**Comment by causefx** [comment]
seems to be non-issue now....

**Comment by neo-neo1** [comment]
Still an issue as of today (10/9/20). I installed a fresh install of organizr v2 for the first time and then was ripping my hair out for an hour on why it wasn't connected to transmission. If the problem can't be solved, I suggest an informational bubble/window be included warning you that a restart is need. And perhaps even have an automated prompt to restart after setting up transmission connection parameters. 

```
Version: 2.0.650
Branch: v2-master
Server OS: *nix
PHP: 7.3.22
Install Type: Official Docker
```

**Comment by causefx** [comment]
Restarting has nothing to do with it.  As long as you have the settings before testing it - it should be fine.

**Comment by neo-neo1** [comment]
> Restarting has nothing to do with it. As long as you have the settings before testing it - it should be fine.

Testing has nothing to do with it and restarting it is the only thing that made it work.

**Comment by causefx** [comment]
LOL... Ok.  ¯\_(ツ)_/¯

**Comment by Kenilik** [comment]
Bump. Fresh install of organizr/organizr and get the same connection error could not get session id when trying to add transmission to homepage.

**Comment by norsemangrey** [comment]
I have the same issue. Restarting did not help. Anyone found a solution to this?

**Comment by lukebarone** [comment]
Yea, add `/transmission` to the end of the URL, if it's not there already.
