### ISSUE TITLE
Export / Import config

### ISSUE THREAD

**Issue by madbuda** [causefx/Organizr#889]
###### Operating System: Ubuntu
<hr>

##### Problem Description:
Provide an export / import option to move to a new server
I suppose this could be part of the installer instead of the app

<hr>

##### Reproduction Steps:
Try to migrate to a new server

<hr>

#### Errors on screen?  If so paste here:

```
Option does not exist
```

**Comment by causefx** [comment]
would you want only the config and db zipped?  or do you want the entire project zipped?  I can do it like v1 too.

**Comment by madbuda** [comment]
I just zipped up the entire thing and moved it
Should include moving the nginx conf as well

**Comment by Roxedus** [comment]
https://docs.organizr.app/books/installation/page/backup-restore
