### ISSUE TITLE
V2 - Broken Email Center

### ISSUE THREAD

**Issue by saitoh183** [causefx/Organizr#891]
###### Operating System: Docker
<hr>

##### Problem Description:
Email Center text area seems to be broken.
* When you import a template and the try to add image, the image import will eliminate the all the text and only leave the image.
* When you insert a image, then import a template, the image is removed.
* When you highlight text because you want to overwrite it, it will act as if you did a select all and erase everything
* When you insert a image and then try to use the alignment options, they dont do anything.
* Template import doesnt import Subject

Thanks
<hr>

**Comment by causefx** [comment]
Fixed.  On the subject, please make sure the template body doesnt end in a `space`
