### ISSUE TITLE
V2 - Users able to request content which already exists in Plex & Ombi

### ISSUE THREAD

**Issue by EvilTactician** [causefx/Organizr#892]
###### Operating System: 7.0.30-0ubuntu0.16.04.1
<hr>

##### Problem Description:
Users are able to request content which already exists in Plex and show as already existing in Ombi too.

<hr>

##### Reproduction Steps:
Search for content which doesn't exist. "hello internet"
Get the "No Results for: hello internet" screen, click "Would you like to request it?"
Get the "Requests" search bar this way, search for anything and request it even if it already exists.
Content is added to Ombi as a Request even if it already exists.

This is just an example of how to get to the request bar, obviously there are other routes. The main point is that you can request things which exist from that version of the search bar. The "main" bar is fine and seems to check for this.
<hr>

#### Errors on screen?  If so paste here:

```
No errors, it works flawlessly. But it probably shouldn't :)
```

**Comment by causefx** [comment]
We can ask ombi to do a check with their api....

**Comment by EvilTactician** [comment]
That sounds like a sensible solution. Loving organizr btw, great work so far. I think it has potential to become the details facto norm for most Plex admins. My users love it as well, makes everything so convenient when ombi and tautulli are just there for them as well.

**Comment by causefx** [comment]
seems like it's gna stay the way it is....
