### ISSUE TITLE
V2

### ISSUE THREAD

**Issue by zhdenny** [causefx/Organizr#893]
###### Operating System: unRAID
<hr>

##### Problem Description:
Homepage NZBGet Configuration.......it does not like complex passwords.

<hr>

##### Reproduction Steps:
Results in Fail:
1. Inside NZBGet settings, Change NZBGet password to something complicated with symbols (for example # and * were in my test case)
2. Save and Reload NZBGet
3. Configure Organizr Homepage NZBGet with new password
4. Save and Test. It will FAIL test

Results in Success
1. Inside NZBGet settings, Change NZBGet password to something simpler.....no special symbols
2. Save and Reload NZBGet
3. Configure Organizr Homepage NZBGet with new password
4. Save and test. Success!

The same works if you simply remove username/password from NZBGet entirely.....it will work just fine. The issue is ONLY when the NZBGet password is a bit more complex. I discovered this while using my Password Manager to auto-generate my password for NZBGet.

<hr>

#### Errors on screen?  If so paste here:

```

```

**Comment by causefx** [comment]
how long was the password?

**Comment by causefx** [comment]
Just tested it some more:

![image](https://user-images.githubusercontent.com/16184466/41996166-eb5539c8-7a08-11e8-881b-2af8564297e5.png)


Can you let me know how long the password was?
