### ISSUE TITLE
Not creating users from Emby backend

### ISSUE THREAD

**Issue by schmittyd** [causefx/Organizr#894]
###### Operating System: ubuntu0.16.04.1
<hr>

##### Problem Description:
Does not create users from Emby Server backend.

<hr>

##### Reproduction Steps:
Set Organizr Settings => Authentication
Authentication Type => Organizr DB + Backend
Authentication Backend => Emby All
Emby URL => http://192.168.0.101:8096
Emby Token => *************

Org db: /srv/.config/organizr/domain.tld/test/users.db
              media:media -rwxrwxrwx
Emby db: /srv/.config/emby/data/users.db
                media:media -rwxrwxrwx
<hr>

#### Errors on screen?  If so paste here:

```
No errors
```

**Comment by schmittyd** [comment]
Just though I would mention... homepage items work, just not the connection with the Emby user database.

**Comment by causefx** [comment]
@rob1998

have you seen anything like this?

**Comment by rob1998** [comment]
Will check on it tomorrow, haven't had any problems yet

**Comment by schmittyd** [comment]
Is there any follow up on this issue? v1 and v2 still aren't creating users... Ombi does though (if this may help)

**Comment by rob1998** [comment]
@schmittyd so to get this clear:
Did you try to login with an emby account? Cause that's the moment that a user is created in Organizr. It doesn't import them all at once like Ombi.@causefx correct me if I'm wrong
Could that be what's wrong for you?

**Comment by schmittyd** [comment]
Emby won't even sign in using a connect account, unless it is from an emby.media portal (tv.emby.media or app.emby.media). It returns an `Invalid username or password. Please try again.` Organizr won't create the account, due to a `Login Error<br> Wrong username/email/password combo`

**Comment by rob1998** [comment]
@schmittyd @causefx 
So you can't login with an emby connect account (except when you use an emby portal) and it won't create the account in the user database.
But you can login with an offline emby account, and then the account is created successfully?
Also is the emby connect user you're trying to login with already added as a user to your emby server?

I just tested it on mine with an offline account and it worked fine, so if that's not working then I would say something's wrong on your end.
I know that all these questions must be annoying, but more information = more likely to find a solution 😃

**Comment by schmittyd** [comment]
Yes, I can only sign in to an Emby portal. I've tried creating local and connect accounts in Emby Server and using those credentials to sign in to Organizr, but does not create the accounts.

I have tested creating Connect accounts, but they are even unable to be accessed in Emby portals. The server can be logged into suing Connect, but actually logging into an account on the server results in `Invalid username or password. Please try again.` I have had to create local accounts then add the Connect user to the account.

Ombi creates accounts from Emby no problem. For some reason Organizr will not. I'm wondering if it isn't a bug, what could possible cause the issue.
