### ISSUE TITLE
[V2] No plex libraries retrieve in invites plugin

### ISSUE THREAD

**Issue by hbooo** [causefx/Organizr#895]
###### Operating System: Windows
<hr>

##### Problem Description:

Hi, 

I have no libraries retrieved when I try to configure invite plugin
![image](https://user-images.githubusercontent.com/242125/41547636-0bd9f2e0-7321-11e8-9b41-5aff5a914dc8.png)

<hr>

##### Reproduction Steps:

I have :
- Installed Organizr v2 through OrganizrInstaller
- Configured Single Sign-On for plex
- Activated invites plugin
- Tried to configurate plugin

<hr>

#### Errors on screen?  If so paste here:

```
2018/06/18 15:56:47 [error] 488#5536: *232 FastCGI sent in stderr: "PHP Warning:  Invalid argument supplied for foreach() in C:\nginx\www\organizr\html\api\functions\organizr-functions.php on line 1560
PHP Notice:  Undefined index: libraries in C:\nginx\www\organizr\html\api\plugins\invites.php on line 164
PHP Warning:  Invalid argument supplied for foreach() in C:\nginx\www\organizr\html\api\plugins\invites.php on line 165
PHP Notice:  Undefined variable: libraryList in C:\nginx\www\organizr\html\api\plugins\invites.php on line 224" while reading response header from upstream, client: xxx.xxx.xxx.xx, server: localhost, request: "POST /api/?v1/plugin HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "yy.yyy.yyy.yy", referrer: "http://yy.yyy.yyy.yy/"

```

**Comment by causefx** [comment]
Hmmmm.  This is odd....

Can you copy your Plex Machine ID and edit this URL?

https://plex.tv/api/servers/EDITHERE/shared_servers

then log into plex.tv and then goto this URL...

**Comment by hbooo** [comment]
It seems ok now, thanks for the quick correction!

**Comment by causefx** [comment]
awesome!  Thank you!
