### ISSUE TITLE
[v2] Not redirected back to $request_uri after login.

### ISSUE THREAD

**Issue by NemesisRE** [causefx/Organizr#896]
###### Operating System: Ubuntu - Docker
<hr>

##### Problem Description:
Not redirected back to $request_uri after login.

<hr>

##### Reproduction Steps:
* Open a subpage secured by oragnizr https://your-organizr.example/tautulli/libraries
* You will be redirected to the organizr 401 page
* Now login
* You will be redirected to your organizr default homepage.

**Comment by causefx** [comment]
will look into this one.

**Comment by causefx** [comment]
fixed in dev
