### ISSUE TITLE
[V2] Multiple instances of Organizr on sub domains conflict

### ISSUE THREAD

**Issue by fryfrog** [causefx/Organizr#900]
###### Operating System: Arch Linux
<hr>

##### Problem Description:
I run an instance of Organizr on two servers, both of which are sub-domains of a primary domain. If I log into each one on its own, everything is fine. But once I log into both at the same time, thing start behaving oddly.

For example, in Settings the first and second tier of options loads up fine, but the 3rd tier (like the tab list) do not. And a full refresh of the page results in being logged out.

On Discord, this seems to be a known problem... but I could not find an issue for it already.
<hr>

##### Reproduction Steps:
Log into instance one at one.domain.com
Log into instance two at two.domain.com
Weird stuff.
<hr>

**Comment by fryfrog** [comment]
My educated guess is something about cookie domains? :/

**Comment by causefx** [comment]
i may name the cookies for diff instances... :)

**Comment by fryfrog** [comment]
Could just include some randomness in cookie name... or maybe full domain name? I don't know much about cookies. :(

**Comment by causefx** [comment]
ok i got it now.
![image](https://user-images.githubusercontent.com/16184466/41875103-b8b6ab5e-787e-11e8-8ca5-5a4ad89000e7.png)


update soon

**Comment by causefx** [comment]
please update to test as this has been fixed.

**Comment by fryfrog** [comment]
Works fantastic now.
