### ISSUE TITLE
[V2] [Request] Settings tabs should have a default setting they open

### ISSUE THREAD

**Issue by douglasg14b** [causefx/Organizr#901]
###### Operating System: Ubuntu
<hr>

#### Request/Suggestion:

![image](https://user-images.githubusercontent.com/1400380/41892183-0abc8dcc-78cc-11e8-800a-8e63427bdd87.png)

When clicking on the settings tabs, they don't open their respective settings by default. This takes an extra click to open a setting area.

#### Why?

It's the common theme for settings in many UI's dating back for a few decades, it's an intuitive control at this point. Little consistencies with user assumptions go a long ways for a lovely ui.

**Comment by causefx** [comment]
The reason for this is because all the settings are pulled in real time thru AJAX.

**Comment by douglasg14b** [comment]
I meant this as a UX recommendation, not specifically as a technical problem. It's definitely doable, if a user can click on it, it can be done automatically.

If you want (And if it's extendable, and relatively easy to implement), I can just make a pull request that adds this functionality?

**Comment by douglasg14b** [comment]
Sweet!
