### ISSUE TITLE
[V2] No Status for Ping on Icons

### ISSUE THREAD

**Issue by x86txt** [causefx/Organizr#903]
###### Operating System: Windows
<hr>

##### Problem Description:
When ping is enabled for a tab, there is no status displayed on the icon, like the old red/green indicator. You have to expand the menu horizontally and see the response time in ms.

<hr>

##### Reproduction Steps:

<hr>

#### Errors on screen?  If so paste here:

```

```
I'm not sure if this is by design, planning to be added, or an error. Please feel free to close if working as designed.

**Comment by causefx** [comment]
It will only show if the server is down.

See below:
![image](https://user-images.githubusercontent.com/16184466/42139786-c38d8c8a-7d49-11e8-9fec-4c5d7edd7cca.png)

**Comment by x86txt** [comment]
Ohhh, that does look much better! Nice work! I'll close this.

**Comment by causefx** [comment]
No worries.  I’m glad ya like it :)
