### ISSUE TITLE
[V2] Custom Themes Limited by Base Stylesheet(s)

### ISSUE THREAD

**Issue by Burry** [causefx/Organizr#906]
###### Operating System: Docker
<hr>

##### Problem Description:

Custom stylesheets added to `/css/themes/` are limited in what styles can be set, as they are called in the markup prior to other stylesheets which set some `!important` rules. (e.g. the background color of `.bg-info` cannot be overridden). Stylesheets set through the "Custom CSS" pane in Organizr Settings do not experience this issue.

**Comment by causefx** [comment]
ahhh yeah, let me take a look at this.

**Comment by Burry** [comment]
I didn’t notice that this only occurs when setting custom values under Organizr’s Colors & Themes pane. Otherwise theme values aren’t overridden, so this isn’t really an issue except for the misunderstanding—my bad

**Comment by causefx** [comment]
no worries
