### ISSUE TITLE
[V2] [Request] Open Plex app on mobile

### ISSUE THREAD

**Issue by Burry** [causefx/Organizr#907]
It would be great to have a setting for Plex tabs and deep links so that when browsing Organizr on a mobile device, links would open in the Plex app. For example in iOS this can be accomplished with the URL scheme `plex://`. For users who occasionally want to change Plex Media Server settings from their mobile device, there could maybe be a fallback Plex tab available on mobile devices that would launch the web client as it normally would.

**Comment by si0972** [comment]
I have a feathub on this. and have been bugging cause about some js actions on tab-load. i have a temporary "[fix](https://github.com/si0972/RandomThings/blob/master/Server/Sites/Nginx/PlexIOSRedirect/rewrite.conf)" on this, doing a rewrite on the webserver. this will not work in safari though.

**Comment by Burry** [comment]
Now that there's a "Custom JavaScript" tab in V2, [here's a gist](https://gist.github.com/Burry/7f6c2caa9cf645ca511ffefd697b3126) to redirect all links to Plex on iOS/Android to the mobile app with functioning deep links.
