### ISSUE TITLE
v2 not getting login prompt on IOS 10.1.1 multiple browsers.

### ISSUE THREAD

**Issue by evilmanimani** [causefx/Organizr#908]
###### Operating System: Windows 10 x64
<hr>

##### Problem Description:

I've got Org v2 working well and it's accessible except on my iPhone running 10.1.1 (jailbroken). I see the grey background with the menu, stop, and reload buttons at the top left, but nothing else loads, tested on multiple browsers. Confirmed working on other IOS devices running 11.x.

I've also rebooted to temporarily disable the jailbreak and that had no effect as well.

Cheers.
<hr>

##### Reproduction Steps:

Load homepage in any browser on 10.1.1
<hr>

#### Errors on screen?  If so paste here:

```

```

**Comment by causefx** [comment]
i will try and debug this .

**Comment by causefx** [comment]
BrowserStack doesnt let  add to homescreen, I have no way of testing.

**Comment by evilmanimani** [comment]
I've just been loading Org as a bookmark in Safari, and tested by entering the address manually with the same result, I've got it added to my homescreen but it affects the other methods of accessing Org equally.

**Comment by damusmf** [comment]
I am having the exact same problem.  Let me know if there is anything i can do.

**Comment by causefx** [comment]
the only version that BrowserStack has for iOS 10 is 10.3

https://ss.organizr.app/chrome_2018-09-05_10-02-57.png

which works, i'm unable to test on 10.1

**Comment by causefx** [comment]
still unable to test on lower versions of iOS
