### ISSUE TITLE
Support for /app behind reverse proxy?

### ISSUE THREAD

**Issue by soakes** [causefx/Organizr#911]
Hi Guys,

Is there something I'm missing but I can't seem to run this behind a reverse proxy using subdirectory?

If I use subdomain it all works fine but ideally would like it on /organizr.

I have checked the default config but don't see like url_path in there so I assume there's no support for this yet.  Do anyone know when this could be added?

Kind Regards,

Simon

**Comment by causefx** [comment]
I havent tried, I will give this a go tomorrow.

**Comment by causefx** [comment]
try this:

```
	location ^~ /organizr/ {
		rewrite /organizr/(.*) /$1 break;
		proxy_pass http://ip:port;
		proxy_set_header Host $host;
		proxy_set_header X-Real-IP $remote_addr;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
	}
```

**Comment by soakes** [comment]
@causefx thanks very much for the nginx snippet, this resolved it.

**Comment by causefx** [comment]
Awesome. Glad it worked.

**Comment by rcdailey** [comment]
How can we do this in Traefik? I'm doing this right now:

```
labels:
  - traefik.enable=true
  - traefik.port=80
  - traefik.frontend.rule=PathPrefixStrip:/organizr
```

**Comment by causefx** [comment]
you may want to ask on discord... some people use traefik there
