### ISSUE TITLE
V2 Organizr homescreen shortcut iOS wont load

### ISSUE THREAD

**Issue by roflcoopter** [causefx/Organizr#912]
###### Operating System: Ubuntu
<hr>

##### Problem Description:
Organizr does not load when opened from the "Add to homescreen" shortcut from iOS 12.
I am able to input credentials but after that, infinite loading
It works fine when using plain Safari or Chrome.

<hr>

##### Reproduction Steps:
Go to Organizr, add to home screen, open shortcut, login > infinite loading icon

<hr>

#### Errors on screen?  If so paste here:

```

```

**Comment by causefx** [comment]
That's odd, i just tried and it worked fine.

iPhone X
iOS 12.0 (16A5318d)

**Comment by roflcoopter** [comment]
Interesting! Could it be my nginx config perhaps, I'll try to access the page directly without going through nginx when I get home and report back

**Comment by roflcoopter** [comment]
Seems to be working now, might have been some weird caching in cloudflare since im using that. Clearing the cache on cloudflare fixed it
