### ISSUE TITLE
[V2] Requesting functionality works intermittently

### ISSUE THREAD

**Issue by Burry** [causefx/Organizr#915]
###### Operating System: unRAID
<hr>

##### Problem Description:

The homepage request search button and the ability to launch into a new request from the navbar media search only shows up intermittently for me on Chrome, and not at all on desktop or mobile Safari (Mojave / iOS 12). Restarting Organizr and Ombi seem to have no effect on this. The homepage "Requested Content" row always appears, however.

<hr>

##### Reproduction Steps:

Attempt to make a new request from the Organizr homepage or navbar media search.

**Comment by causefx** [comment]
Those two buttons do different things.

The nav bar button searches current plex media. which the ombi saerch button on homepage does just that.

While using the plex search, if said search item doesnt show, it will ask if you want to request it, which then sends you to ombi search with the query already searched.

**Comment by Burry** [comment]
Yeah I’m saying that the Plex search is not offering to start a new request when an item is not found, and the Ombi search isn’t appearing at all. Though it did appear for me on iOS now, now so far Desktop Safari looks like the one experiencing this most.

**Comment by causefx** [comment]
Safari 11.1.1

Plex search:
<img width="943" alt="image" src="https://user-images.githubusercontent.com/16184466/42967912-97145d08-8b56-11e8-9b1c-b74476cc4101.png">

After clicking request:
<img width="919" alt="image" src="https://user-images.githubusercontent.com/16184466/42967926-a50f4b52-8b56-11e8-8064-680af6baf6b7.png"> 
A second try with no results:
<img width="913" alt="image" src="https://user-images.githubusercontent.com/16184466/42967964-bd38328e-8b56-11e8-8207-ae46b053e230.png">
<img width="920" alt="image" src="https://user-images.githubusercontent.com/16184466/42967971-c326ce62-8b56-11e8-8b5b-1eae8bcc37fd.png">


is there anything in browser console?

**Comment by Burry** [comment]
I'm using Safari 12.0, and what the hell, I tried on another computer running the same build, and it's working fine. There was nothing notable in the browser console on the other machine. Sorry probably shouldn't have filed this. Looks like it's an issue with the OS betas.

**Comment by causefx** [comment]
ahhh I will try the new betas too.
