### ISSUE TITLE
v2 auth taking a very long time, up to a minute

### ISSUE THREAD

**Issue by dejected1** [causefx/Organizr#917]
###### Operating System: Windows 10 x64
<hr>

##### Problem Description:
v2 auth taking a very long time, up to a minute

<hr>

##### Reproduction Steps:
I have a feeling im doing this wrong but with v2 my auth takes forever to work! I click on the tab and after about 1 minute the page loads finally. While im waiting the page is completely unresponsive then it just comes back.  Pages without auth load right away and v1 organizr tabs worked great with auth (without groups).

Here is what i got: 

location /auth-user {
			internal;
			proxy_pass https://localhost/api/?v1/auth&group=4;
			proxy_pass_request_body off;
			proxy_set_header Content-Length "";
			proxy_set_header X-Original-URI $request_uri;
			}

		#sonarr
		location /sonarr{
		auth_request /auth-user;
       	 	proxy_pass http://192.168.2.2:8989;
		    proxy_set_header Host $host;
		    proxy_set_header X-Real-IP $remote_addr;
		    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;	
    proxy_connect_timeout       300;
    proxy_send_timeout          300;
    proxy_read_timeout          300;
    send_timeout                300;		    
	}

I also tried admin and co-admin, same result. I tried clearing cookies and cache, different browsers and computers. 

<hr>

#### Errors on screen?  If so paste here:

```

```

**Comment by gilbN** [comment]
Have you tried the one from the wiki?
https://github.com/causefx/Organizr/wiki/Authentication-%7C-Server-Based#how-to-create-an-authorization-block-on-v2

**Comment by dejected1** [comment]
yeah i had tried it, I ended up trying the one above because it wasn't working. I ended up blowing out the whole website and starting from scratch, it worked then. I must of had some weird line of code or something. Not sure to tell you the truth. Either way its working now on a new install. Now if I could just get ombi SSO to work id be golden.....
