### ISSUE TITLE
[V2] iOS Full Screen Web App immediate logout

### ISSUE THREAD

**Issue by karaambaa** [causefx/Organizr#918]
###### Operating System: Ubuntu/Docker
<hr>

##### Problem Description:

As soon as the Web App is closed all cookies are deleted. I think it would be better to delete them after 30 mins or so. To allow short interruptions for texting or calling.
[https://stackoverflow.com/questions/7077518/ios-full-screen-web-app-drops-cookies](url)
<hr>

##### Reproduction Steps:

- Login to Organizr inside Web App
- Close Web App
- Reopen again

<hr>

**Comment by causefx** [comment]
This may be fixed in iOS 12 as this doesn’t happen to me on my phone.

**Comment by karaambaa** [comment]
Allright, thank you for your hard work!

**Comment by causefx** [comment]
:) thank you
