### ISSUE TITLE
Missing Homepage items

### ISSUE THREAD

**Issue by lwaldren** [causefx/Organizr#919]
###### Operating System: Ubuntu
<hr>

##### Problem Description:
Did a new install of organizr and now I am missing alot of the home page items I use to have such as sonarr/radarr. Any ideas on how to fix this?
![image](https://user-images.githubusercontent.com/38267031/43312036-798f7ae0-91cf-11e8-9da7-4c8e55723970.png)

<hr>

##### Reproduction Steps:

<hr>

#### Errors on screen?  If so paste here:

```

```

**Comment by causefx** [comment]
Sonarr and radarr are under calendar

**Comment by christronyxyocum** [comment]
Did this answer your question, @lwaldren? If so, please close.

**Comment by lwaldren** [comment]
@causefx Thanks, not sure why I had trouble working that at. Cheers.
