### ISSUE TITLE
The bars and fonts are so big and ugly

### ISSUE THREAD

**Issue by mikerun** [causefx/Organizr#92]
Excuse me if I'm being rude but fonts and sizes of side and top bars are really ugly and needs to slim down
I'm trying to fix it but it's not an easy task it looks like it needs a redesign
it shouldn't be any bigger than wordpress top and side menus
http://wpexplorer-themes.com/total/wp-content/uploads/sites/2/2014/12/header-overlay.png

**Comment by causefx** [comment]
thank you for your input, we may look into adding an option for slim styling.

**Comment by mikerun** [comment]
this screenshot was shared on reddit with a modification for the old iDashboard-PHP 
https://i.imgur.com/op6biXv.png
it looked really good

**Comment by causefx** [comment]
yea that is SwiftPanda's.  iDashboard comes with small borders by default.  I will make the slim styling soon.  a little after the release of 1.0

**Comment by mikerun** [comment]
Great! Thanks

**Comment by lgromb** [comment]
I second this, altough I think only the header is quite big.

If you sum up the height of my chrome window + fav tab + Organizr header + sidebar, it only leaves a few space for the iframe to show.

Think of the little resolutions 🗡 

Thanks !

**Comment by causefx** [comment]
thank you, i will still work on this.
