### ISSUE TITLE
[V2] Unable to login on a dns xxx.cloudapp.net

### ISSUE THREAD

**Issue by hbooo** [causefx/Organizr#920]
###### Operating System: Ubuntu
<hr>

##### Problem Description:

Hello, 

I'm unable to login on a fresh install of organizr using docker image on an azure VM. My dns is xxx.cloudapp.net

If I edit api/functions/normal-functions.php and add 'cloudapp.net' it works but it's remove when docker is updated. Can you add this dns to the list ?

Thanks
<hr>

##### Reproduction Steps:

Install docker image
Try to connect from DNS
<hr>

#### Errors on screen?  If so paste here:

```

```

**Comment by causefx** [comment]
this has been fixed.
