### ISSUE TITLE
"Manage Invites" and "Use Invite Code" persistent popups

### ISSUE THREAD

**Issue by Archmonger** [causefx/Organizr#922]
###### Browser: Chromium-based.
<hr>

##### Problem Description:
Popups such as "Manage Invites" and "Use Invite Code" sometimes persists even when the webpage is refreshed, user signs out, and cache is cleared. Only method to stop the popup from coming back on each page load is to clear cookies.

<hr>

##### Reproduction Steps:
Make a pop up such as "Manage Invites" and "Use Invite Code" appear. Sometimes they'll never leave. No clear method of reproduction known. Will update this ticket if I determine a direct cause.

<hr>

#### Errors on screen?  If so paste here:
N/A
```

```

**Comment by causefx** [comment]
Thanks, i will look into this :)

**Comment by si0972** [comment]
Usally fixed by clearing the cookie for the domain.

**Comment by causefx** [comment]
fixed in dev
