### ISSUE TITLE
Unable to copy / paste stuff in the custom css/html boxes on mobile.

### ISSUE THREAD

**Issue by gilbN** [causefx/Organizr#923]
###### Operating System: Docker
<hr>

##### Problem Description:
Unable to copy paste in custom css / homepage page html on mobile.

Would be nice when you're on the road and don't have access to a desktop ;)
<hr>

##### Reproduction Steps:
Try to paste code

<hr>

#### Errors on screen?  If so paste here:

```

```

**Comment by causefx** [comment]
it may be a bug in the framework im using :(
