### ISSUE TITLE
Not Writable - Please fix permissions

### ISSUE THREAD

**Issue by buttpain** [causefx/Organizr#924]
Organizr Version: V 2
Branch: Develop
WebSever: Apache
Operating System: Ubuntu
<hr>

##### Problem Description:
I just tried to update to the v2 beta and below was the screen I got (didn't include in the screenshot but all of the dependencies were ticked)
https://i.imgur.com/ZpHXS49.png
I then tried installing in another folder and I got the same screen

#### Errors on screen?  If so paste here:

```
Not Writable - Please fix permissions
```

**Comment by gilbN** [comment]
Try
```
sudo chown -R www-data:www-data /var/www
```

**Comment by buttpain** [comment]
Yeah you're right, not sure why I didn't try that

**Comment by gilbN** [comment]
Glad it worked.
