### ISSUE TITLE
Will there be a chat in v2

### ISSUE THREAD

**Issue by nickbe** [causefx/Organizr#927]
Is chat for v2 already under construction or still a long way from being finished?

**Comment by causefx** [comment]
I need to ask if people want it :)

**Comment by nickbe** [comment]
Well I for my part would very much like it :)

**Comment by Procuria** [comment]
I would like it very much too !

**Comment by causefx** [comment]
You guys can test on v2 beta now

**Comment by Procuria** [comment]
Thanks a lot! Awsome...just like the whole Organizr.

**Comment by tamburra** [comment]
The chat looks beautiful.
Is there any way to get the chat link to be a tab instead of being in the dropdown under the username?  I know it is currently an onclick event so there is no way to currently link to it.

**Comment by causefx** [comment]
i will maybe add toggle to place on tab list

**Comment by nickbe** [comment]
Does the chat really have to depend on a third party service?

**Comment by tamburra** [comment]
That would be amazing.  :)

**Comment by causefx** [comment]
it’s doesn’t “have” to but using websockets is by far the best route to go. you get instant messaging that way. otherwise if would just be polling ajax calls which isn’t really sufficient.
