### ISSUE TITLE
Would like something added or know how 

### ISSUE THREAD

**Issue by aztm22** [causefx/Organizr#933]
###### Operating System: Ubuntu
<hr>

##### Problem Description:

No problem just wanted to know is there a way to display 3x plex servers for recently added on the home page? And the same for who's streaming? 
Please let me know
<hr>

##### Reproduction Steps:

<hr>

#### Errors on screen?  If so paste here:

```

```

**Comment by christronyxyocum** [comment]
Not at this time, no.

**Comment by causefx** [comment]
I'm going have to think about this one.  it'll be real tricky.

**Comment by causefx** [comment]
Please make this a request on FeatHub.
