### ISSUE TITLE
Cannot Sort Categories

### ISSUE THREAD

**Issue by BzowK** [causefx/Organizr#935]
###### Operating System: Windows 10 x64 (1803)
<hr>

##### Problem Description:
Hey Guys - 

First of all, thanks to the devs for a fantastic tool and the hours you devote to it!

I've been using v2 for a few weeks now starting with beta 100 and this morning updated to beta 600.  Since the beginning, I've had a persistent issue which I reported in Discord, but wanted to add here as well.

I am unable to sort categories the way that I think it is supposed to work.  On the Settings screen where you add Categories, there is a default one for "Unsorted."  I assume that dragging new categories on top of the "Unsorted" one would put the categories above tabs which are not in one once the page is refreshed, but this does not occur.

I am able to reproduce this every time and in Discord found others could, too.  

Thank You!
<hr>

##### Reproduction Steps:
1. Add multiple tabs
2. Add a new category
3. Drag new category on top of "Unsorted" category
4. Refresh page - "Unsorted" tabs are still on top of custom categories
<hr>

###### More Environmental Information
- Organizr v2 
   - Installed / used at root of site
   - Currently have 24 tabs in "Unsorted" and 6 tabs in custom category (plan to add more categories once above issue is resolved) 
- Nginx
   - Configured for reverse proxy for many other locally hosted web apps
   - Configured to use HTTPS using 3rd party signed cert (GoDaddy)
   - Configured to forward all HTTP requests to HTTPS

Thanks again!

**Comment by causefx** [comment]
Unsorted isn't sorted the same way as categories.  Since itself isn't really a group.  There is an option to have the unsorted tabs above or below groups.  

![image](https://user-images.githubusercontent.com/16184466/45111005-aca9fe80-b0f8-11e8-8886-393330622a0d.png)


I hope that helps.

P.S.

Thanks for the kind words :)

**Comment by BzowK** [comment]
Good Morning - 

I see - I just found that setting and now understand.  To note, it would be nice in the future to be able to sort them using the method mentioned in my post as my ideal organization would be to have some tabs not in categories in between ones with categories.  Not a show stopper - just opinion.

Thank You!

**Comment by causefx** [comment]
I may revisit this in the future, I will keep it in mind, thanks!
