### ISSUE TITLE
Homepage Items Do Not Appear for Non-Admin Users

### ISSUE THREAD

**Issue by BzowK** [causefx/Organizr#936]
###### Operating System: Windows 10 x64 (1803)
<hr>

##### Problem Description:
Hey Guys - 

As always, thanks to the devs for a fantastic tool and the hours you devote to it!

Besides the recent issue I posted about sorting categories, I have found one more issue that I believe is not related to my configuration options.  I've created 5-6 homepage items which work great for my Admin / default user.  I recently created a new user for my sister where I set her level to "User" then went into ~3 of the homepage items (Plex, Sonarr, etc) and changed their Minimum Authorization to "User."    After saving, I refreshed then logged out then back in as her to test and the homepage was empty.  Logging back in as my admin account, I see the configurations I made are set correctly (as stated above) so know they saved.  I've tried refreshing, clearing browser cache, and restarting services to no avail.  Could be I am configuring incorrectly, but don't see any additional options and her user doesn't have access to go into Settings.

Thank You!
<hr>

##### Reproduction Steps:
1. Configure homepage items 
2. Within homepage items, ensure desired ones are set to the Minimum Authorization of "User" - Save
3. Refresh and verify homepage items work as admin / default user
4. Create a new user with level "User"
5. Log out then log back in as new user - the homepage is empty
<hr>

###### More Environmental Information
- Organizr v2 
   - Installed / used at root of site
   - Currently have 24 tabs in "Unsorted" and 6 tabs in custom category (plan to add more categories once above issue is resolved) 
- Nginx
   - Configured for reverse proxy for many other locally hosted web apps
   - Configured to use HTTPS using 3rd party signed cert (GoDaddy)
   - Configured to forward all HTTP requests to HTTPS

Thanks again!

**Comment by causefx** [comment]
On the enable portion of plex, did you set user group to `user` as well?

**Comment by BzowK** [comment]
Good Morning - 

Yes - I did.  The Plex Homepage Item is configured as follows:
- Enable
   - Enable: Yes
   - Minimum Authorization: User
- Connection
   - URL: https://mydomain.com/plex
   - Plex Machine: xxxxxxxx
   - Token: xxxxxxxxx
- Active Streams
   - Enable: Yes
   - User Information: Yes
   - Refresh: 60
   - Minimum Authorization: Co-Admin
   - Minimum Authorization: Co-Admin
- Recent Items
   - Enable: Yes
   - Minimum Authorization: User
   - Limit: 5
   - Refresh: 60
- Media Search
   - Enable: Yes
   - Minimum Authorization: User
   - Server: Plex
- Playlists
   - Enable: No
   - Minimum Authorization: Co-Admin
- Misc Options
   - Tab Name: Plex - Servername
   - Image Cache Size: 2x
   - Plex Tab WAN URL: https://mydomain.com/plex
- Test Connection
   - API Connection Successful

Thanks

**Comment by causefx** [comment]
sorry for the late delay, is the problem still happening?

**Comment by pr0xyfl00d3r** [comment]
for me it is

**Comment by bobloadmire** [comment]
Just wanted to add that I'm having this exact same issue, and yes i have the items set as user.
