### ISSUE TITLE
HOMEPAGE: Recently Added Plex

### ISSUE THREAD

**Issue by goldenpipes** [causefx/Organizr#937]
###### Operating System: Windows
<hr>

##### Problem Description:

HOMEPAGE: Recently Added Plex
TV show: a whole show gets added it shows every season instead of just the TV show being added
like I added the show 'House' and the recently added homepage items shows every season.  While Plex itself just shows the whole show was added.  Instead of taking 9 spots in the recently added it just took 1.

<hr>

##### Reproduction Steps:
Add a TV show to plex.

Recently added shows a new item for every season instead of just the TV show.

<hr>

#### Errors on screen?  If so paste here:

```

```

**Comment by causefx** [comment]
Please make this a request on FeatHub.

I want to see if everyone else wants to consolidate.
