### ISSUE TITLE
Homepage Calendar (iCal vs Sonarr)

### ISSUE THREAD

**Issue by BzowK** [causefx/Organizr#938]
###### Operating System: Windows 10 x64 (1803)
<hr>

##### Problem Description:
Hey Guys - 

As always, thanks to the devs for a fantastic tool and the hours you devote to it!

Sorry that this is my 3rd reported issue, but ran into it earlier today.  Seemingly, one may configure an iCal calendar as a homepage item, but cannot get it to appear on the homepage.  There is a "Calendar" option under "Homepage Order", but it is designated for the Sonarr calendar per my testing (as there is no Sonarr option yet a Sonarr item can be configured as a Homepage Item.

Overall, I do want to display my Sonarr calendar on my homepage as well as a few other things including my iCal calendar which currently I cannot seem to do assuming that was the intention.

Thank You!
<hr>

##### Reproduction Steps:
1. Within Homepage Items, I configure and enable "Calendar" with an iCal URL as well as Sonarr information
2. In "Homepage Order", there is no "Sonarr" option, but there is a "Calendar" which perhaps should be named "Sonarr Calendar" as that is what it appears as for me.
3. The iCal item does not appear on the homepage nor is there an option I am aware of for it within Homepage Order.
<hr>

###### More Environmental Information
- Organizr v2 
   - Installed / used at root of site
   - Currently have 24 tabs in "Unsorted" and 6 tabs in custom category (plan to add more categories once above issue is resolved) 
- Nginx
   - Configured for reverse proxy for many other locally hosted web apps
   - Configured to use HTTPS using 3rd party signed cert (GoDaddy)
   - Configured to forward all HTTP requests to HTTPS

Thanks again!

**Comment by apazzy** [comment]
I'm running in to this same issue, Organizr v2 behind nginx rev proxy for https. 

Below are the errors I'm getting in the web console.

Firefox x64 v62.0.2
`TypeError: response.data is undefined[Learn More] functions.js:4625:9
homepageCalendar/<    http://192.168.1.99:8043/js/functions.js:4625:9
i    http://192.168.1.99:8043/js/jquery-2.2.4.min.js:2:27146
fireWith    http://192.168.1.99:8043/js/jquery-2.2.4.min.js:2:27914
z    http://192.168.1.99:8043/js/jquery-2.2.4.min.js:4:12057
c/<    http://192.168.1.99:8043/js/jquery-2.2.4.min.js:4:15619`

Chrome Canary (currently v71.0.3562.0, but I've been having this issue for over a month now)
`Uncaught TypeError: Cannot read property 'events' of undefined
    at Object.<anonymous> (functions.js:4625)
    at i (jquery-2.2.4.min.js:2)
    at Object.fireWith [as resolveWith] (jquery-2.2.4.min.js:2)
    at z (jquery-2.2.4.min.js:4)
    at XMLHttpRequest.<anonymous> (jquery-2.2.4.min.js:4)`

**Comment by causefx** [comment]
is this issue still happening?

**Comment by apazzy** [comment]
Yep, updated the docker container and made sure I'm on  2.0.0-beta.600

Narrowed down the problem, though. If I disable Lidarr from the homepage options, everything works.

Same javascript errors come up, only when Lidarr is enabled.

**Comment by causefx** [comment]
does the test connection on lidarr work in settings?

**Comment by apazzy** [comment]
I'm an idiot... My API key got reset and I never updated it. Sorry. Hope that's the same issue OP was having.

**Comment by causefx** [comment]
haha no worries.  i will see if i can fix error message

**Comment by ohadbenita** [comment]
Happens to me as well with a Google Calendar iCal, what should I provide to further investigate this issue ?

**Comment by In0cenT** [comment]
I had the same error so I checked sonarr and radarr on their connections and they were fine. I then checked lidarr and that one failed allthough all details were correct. I just reentered all data and from then on everything works perfectly fine.

**Comment by causefx** [comment]
please update organizr and use the test buttons on lidarr,sonarr and radarr to see if there is an error.

**Comment by causefx** [comment]
closed for inactivity, reply and we will open back up
