### ISSUE TITLE
Attempting to update via the auto update tool

### ISSUE THREAD

**Issue by lastb0isct** [causefx/Organizr#94]
This is the error I get:

Warning: mkdir(): File exists in /var/www/html/dash/settings.php on line 192
can't make dir
Fatal error: Uncaught Error: Class 'ZipArchive' not found in /var/www/html/dash/settings.php:230 Stack trace: #0 /var/www/html/dash/settings.php(296): unzipFile('upgrade.zip') #1 {main} thrown in /var/www/html/dash/settings.php on line 230

**Comment by causefx** [comment]
You need to install zip. What OS?

**Comment by lastb0isct** [comment]
I installed zip and got the same error.  Running a LXC Ubuntu 16.04

**Comment by causefx** [comment]
Did you restart your web server and php?

**Comment by causefx** [comment]
PHP7? 

sudo apt-get install php7.0-zip

**Comment by lastb0isct** [comment]
Ahh, i just installed the normal zip package.  Had no idea it used its own php7.0-zip package.  Checking to see if that fixed it now.

**Comment by lastb0isct** [comment]
Yep, that was it.  Thanks for the help...

**Comment by causefx** [comment]
Awesome
