### ISSUE TITLE
[V2] Can't login after changing username/password/email with 2FA.

### ISSUE THREAD

**Issue by robertbaker** [causefx/Organizr#943]
##### Problem Description:
I had 2FA setup. I changed my username, password, and email at the same time. It seems to have only changed my username, as I get a 2FA error message when using old password. When I use the new password I get invalid pw error.

<hr>

##### Reproduction Steps:
2FA with google, organizer db, original admin account
Change email,, pw,username at the same time.

#### Errors on screen?  If so paste here:
2FA incorrect when using old password.

**https://imgur.com/a/YMhCva7**

I know why it's saying that, I changed my username which would invalidate my 2FA, however no warning or revoke occurred.
It also appears that you have to change the username separately first.

That was my only user, I just got it all setup with homepage, tabs, images, etc. 

How can I fix it without losing the config?

**Comment by causefx** [comment]
let me do some testing. for now you can edit the db file and just change the username back

**Comment by robertbaker** [comment]
Mind sharing the sqlite query I need?

**Comment by robertbaker** [comment]
I hosed the user it seems, please send me a query that makes a new  'admin' with a default pw

**Comment by causefx** [comment]
there isn’t a default query as the password is hashed. do you remember the registration password? if so, you can create a new user that way.

**Comment by robertbaker** [comment]
I disabled registration. I guess I'll just wipe it out and set it up again. Not a big deal, just some time.

**Comment by robertbaker** [comment]
@causefx I should be able to insert a record into user. Since you know how the password and token is hashed, couldn't I just insert a user with a password already encrypted?

**Comment by causefx** [comment]
you can re-enable through config/config.php

**Comment by causefx** [comment]
disabled username/email change wile 2fa active

**Comment by Lucavon** [comment]
Don't ask me why, it's completely borked for me. Whenever I pressed login, I didn't get queried for 2FA and it said "2FA incorrect". I reset my password, but the email wasn't sent, despite the mailserver working and the test mail having come through a few days ago. My registration password doesn't work anymore.
