### ISSUE TITLE
[Feature Request] Trakt.tv Integration

### ISSUE THREAD

**Issue by Generator** [causefx/Organizr#944]
## About:
Trakt.tv is used for many people to keep track Movies/TV Show they watch and also as a social platform.

## Suggestion:
Integration of Track.tv calendar as alternative to self-hosted apps (Sonarr, Radarr, Sickrage ...).

**Trakt.tv calendar can show:**
- User movies release date  
- Next TV show episodes 
- Watched/collected Movie/TV Show

**Track API:** https://trakt.docs.apiary.io

**Comment by causefx** [comment]
thanks for this. i will look into it.

**Comment by causefx** [comment]
Please make this a request on FeatHub.  Would love to get other users to vote what they want next.
