### ISSUE TITLE
PHP Mailer Logo Width Requires CSS max-width: 100%

### ISSUE THREAD

**Issue by Archmonger** [causefx/Organizr#945]
###### Branch: Develop
<hr>

##### Problem Description:

If the logo image inputted into "Test & Options" is of an unreasonably large width (ex. 2800px) then it will fail to properly display on many email clients that don't auto manage image sizes, such as the Windows 10 Mail app. Could be solved through adding CSS value ```max-width: 100%;``` to the logo element.
<hr>

##### Reproduction Steps:

Put in an image into 'PHP Mailer>Test & Options>WAN Logo URL' with an unreasonably large width.
Send a test email.
Doesn't display correctly in many mailing apps. Image will be cut off prematurely and a horizontal scrollbar will be added.
<hr>

**Comment by Archmonger** [comment]
Another option is to cap the max-width at a pre-defined px value, depending on what you deem is reasonable.

**Comment by causefx** [comment]
do all the themes do this?
