### ISSUE TITLE
[V2] Spotweb reverse proxy inline tab not working in V2 (works perfectly in v1)

### ISSUE THREAD

**Issue by l-t-k** [causefx/Organizr#947]
##### Problem Description:
With the old v1 version I could perfectly use my spotweb instance within an iframe. On v2 it return an error message: "Error while loading this page, you will be returned automaticly to the mainview". 
On both version I can reach out domain.com/spotweb/ without any troubles.

I run organizr and all my other apps in docker. Spotweb is configured as a reverse proxy in organizr. And organizr is proxied through my traefik docker.
https://github.com/spotweb/spotweb

##### NGINX config files
v1: https://pastebin.com/7A6EPzu5
v2: https://pastebin.com/w81rqziX

##### LOGS
v1: https://pastebin.com/RKX2YwX8
v2: https://pastebin.com/eDqKbgVm

##### SCREENSHOTS CONFIG
![tab-v1](https://user-images.githubusercontent.com/3150962/46905375-0caf7400-cef3-11e8-83b6-d79f0a34a180.png)
![tab-v2](https://user-images.githubusercontent.com/3150962/46905376-1042fb00-cef3-11e8-838f-314f5482d591.png)

##### SCREENSHOTS ORGANIZR / SPOTWEB
![spotweb-v1](https://user-images.githubusercontent.com/3150962/46905381-1d5fea00-cef3-11e8-83a8-e791ca814e94.jpg)
![spotweb-v2](https://user-images.githubusercontent.com/3150962/46905384-218c0780-cef3-11e8-9ea4-95df0ce47d2a.jpg)

**Comment by causefx** [comment]
Wow that is odd... maybe is should install spotweb to test....

one thing that was odd in v2 logs was:

```
172.19.0.2 - - [13/Oct/2018:14:04:05 +0200] "GET /Spotweb HTTP/1.1" 404 199 "https://front.****/spotweb/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36"
```

Capital `S` ....

**Comment by causefx** [comment]
is this issue still happening?

**Comment by CryptoKiwi** [comment]
I just switched to Organizr v2 and ran into the same issue.

The problem seems to be that Spotweb is reading the hash parameters from the parent window, which is set to the name of the active tab by Organizr.

This is caused by the sandbox "allow-same-origin" attribute on the iframe element.

Could there be an option to disable this attribute for specific tabs?

**Comment by stevenb9** [comment]
I'm having the same issue with the latest organizr2 and spotweb. out of 30 services this is the only one not working correctly.

**Comment by causefx** [comment]
Not sure what I could do about this one...  Someone can re-open if they find a solution
