### ISSUE TITLE
502 after install beta from script

### ISSUE THREAD

**Issue by KrunchMuffin** [causefx/Organizr#949]
###### Operating System: Windows
<hr>

##### Problem Description:
PHP doesn't start, but php-cgi.exe starts
going to url results in bad gateway

<hr>

##### Reproduction Steps:
install via install script

<hr>

#### Errors on screen?  If so paste here:

```
2018/10/14 18:43:20 [error] 25648#13304: *17 CreateFile() "c:/nginx/www/organizr/html/organizr" failed (2: The system cannot find the file specified), client: 127.0.0.1, server: localhost, request: "GET /organizr HTTP/1.1", host: "localhost:81"
2018/10/14 18:43:23 [error] 25648#13304: *17 upstream sent unsupported FastCGI protocol version: 72 while reading response header from upstream, client: 127.0.0.1, server: localhost, request: "GET /organizr HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "localhost:81"
2018/10/14 18:43:23 [error] 25648#13304: *17 CreateFile() "c:/nginx/www/organizr/html/favicon.ico" failed (2: The system cannot find the file specified), client: 127.0.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", host: "localhost:81", referrer: "http://localhost:81/organizr"
2018/10/14 18:43:23 [error] 25648#13304: *17 upstream sent unsupported FastCGI protocol version: 72 while reading response header from upstream, client: 127.0.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "localhost:81", referrer: "http://localhost:81/organizr"
2018/10/14 18:43:24 [error] 25648#13304: *17 CreateFile() "c:/nginx/www/organizr/html/service-worker.js" failed (2: The system cannot find the file specified), client: 127.0.0.1, server: localhost, request: "GET /service-worker.js HTTP/1.1", host: "localhost:81", referrer: "http://localhost:81/service-worker.js"
2018/10/14 18:43:24 [error] 25648#13304: *17 upstream sent unsupported FastCGI protocol version: 72 while reading response header from upstream, client: 127.0.0.1, server: localhost, request: "GET /service-worker.js HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "localhost:81", referrer: "http://localhost:81/service-worker.js"
```

**Comment by causefx** [comment]
which script did you use?  

On Oct 14, 2018, at 04:46 PM, Derek <notifications@github.com> wrote:

Organizr Version: beta
Branch: Develop
WebSever: Nginx
Operating System: Windows
Problem Description:
PHP doesn't start, but php-cgi.exe starts
going to url results in bad gateway

Reproduction Steps:
install via install script

Errors on screen? If so paste here:
2018/10/14 18:43:20 [error] 25648#13304: *17 CreateFile() "c:/nginx/www/organizr/html/organizr" failed (2: The system cannot find the file specified), client: 127.0.0.1, server: localhost, request: "GET /organizr HTTP/1.1", host: "localhost:81"
2018/10/14 18:43:23 [error] 25648#13304: *17 upstream sent unsupported FastCGI protocol version: 72 while reading response header from upstream, client: 127.0.0.1, server: localhost, request: "GET /organizr HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "localhost:81"
2018/10/14 18:43:23 [error] 25648#13304: *17 CreateFile() "c:/nginx/www/organizr/html/favicon.ico" failed (2: The system cannot find the file specified), client: 127.0.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", host: "localhost:81", referrer: "http://localhost:81/organizr"
2018/10/14 18:43:23 [error] 25648#13304: *17 upstream sent unsupported FastCGI protocol version: 72 while reading response header from upstream, client: 127.0.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "localhost:81", referrer: "http://localhost:81/organizr"
2018/10/14 18:43:24 [error] 25648#13304: *17 CreateFile() "c:/nginx/www/organizr/html/service-worker.js" failed (2: The system cannot find the file specified), client: 127.0.0.1, server: localhost, request: "GET /service-worker.js HTTP/1.1", host: "localhost:81", referrer: "http://localhost:81/service-worker.js"
2018/10/14 18:43:24 [error] 25648#13304: *17 upstream sent unsupported FastCGI protocol version: 72 while reading response header from upstream, client: 127.0.0.1, server: localhost, request: "GET /service-worker.js HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "localhost:81", referrer: "http://localhost:81/service-worker.js"

**Comment by KrunchMuffin** [comment]
\OrganizrInstaller\windows\o2wi\owi_installer.bat

**Comment by KrunchMuffin** [comment]
Sorry that was incorrect, should be **o2wi_installer.bat**

**Comment by causefx** [comment]
i will test this out today again

**Comment by KrunchMuffin** [comment]
I am trying manual install now.

**Comment by elmerfdz** [comment]
Hmm I'm unable to reproduce this error, did you get any errors during install?

**Comment by KrunchMuffin** [comment]
only that couldn't start nginx and php. i already have iis on port 80.

**Comment by elmerfdz** [comment]
Have you disabled iis? nginx uses port 80 and php port 9000

**Comment by KrunchMuffin** [comment]
no, i had changed it to use 81.

**Comment by elmerfdz** [comment]
probably you got php installed for IIS, that's the reason the new php instance installed by the script won't start.

**Comment by KrunchMuffin** [comment]
maybe. putting it on a different server and will install manually there.
thanks for checking.
