### ISSUE TITLE
[V2] Renaming Guest group breaks tabs

### ISSUE THREAD

**Issue by rix1337** [causefx/Organizr#950]
###### Operating System: Docker
<hr>

##### Problem Description:

Two of my tabs are to be publicly available. I've assigned them the guest group.

As soon as I rename the guest group, the tabs are no longer available to logged out users.
<hr>

##### Reproduction Steps:

Create Tab
Assign it to the Guest group
Log out: it is there

Now log back in and rename the guest group. 
Log back out: the tab is gone. 
<hr>

#### Errors on screen?  If so paste here:

```
-
```

Maybe allow to translate the default group names?

**Comment by causefx** [comment]
fixed :)

**Comment by rix1337** [comment]
Thank you!
