### ISSUE TITLE
[v2] Refreshing doesn't show recently added tab

### ISSUE THREAD

**Issue by powerdude** [causefx/Organizr#952]
###### Operating System: Windows/MacOS/Ubuntu
<hr>

##### Problem Description:

When a new tab is added and refresh is clicked, the new tab doesn't show.  Must sign out and sign back in in order to see tab.
<hr>

##### Reproduction Steps:

go to settings
Choose "Tab Editor" and then "tab"
Add a new tab
Move above the settings tab
Click the refresh icon in header next to "Organizr V2"
<hr>

#### Errors on screen?  If so paste here:

```

```

**Comment by causefx** [comment]
You just need to reload the current page not the current tab.  I will add a message for that.

**Comment by powerdude** [comment]
great, thanks!!
