### ISSUE TITLE
[v2] Deluge webapi github url is wrong

### ISSUE THREAD

**Issue by powerdude** [causefx/Organizr#953]
###### Operating System: docker
<hr>

##### Problem Description:

Github error for https://github.com/idlesign/deluge-webapi/raw/master/dist/WebAPI-0.2.1-py2.7.egg
<hr>

##### Reproduction Steps:

go to "Settings" -> "tab  editor" -> "Homepage items" -> "Deluge" and click on download plugin
<hr>

#### Errors on screen?  If so paste here:

```
Github 404 error
```

**Comment by causefx** [comment]
fixed on ad22fc8

how is organizr installed?  locally or docker?

**Comment by powerdude** [comment]
docker

**Comment by causefx** [comment]
which image?  can you delete image and pull again, this should be fixed.

**Comment by powerdude** [comment]
got it.  thanks
