### ISSUE TITLE
[v2] Enhancement: add tabs as homepage items are configured

### ISSUE THREAD

**Issue by powerdude** [causefx/Organizr#954]
###### Operating System: docker
<hr>

##### Problem Description:

duplicate data entry.  It would be nice that as you configure the homepage items if you could also be able to create tabs at the same time.
<hr>

##### Reproduction Steps:

<hr>

#### Errors on screen?  If so paste here:

```

```

**Comment by causefx** [comment]
the only problem with this is, on homepage item, the url would be local and tab would WAN.
