### ISSUE TITLE
[v2] whoami text is black on black

### ISSUE THREAD

**Issue by powerdude** [causefx/Organizr#955]
###### Operating System: docker
<hr>

##### Problem Description:

When showing whoami in a tab, the text is hard to read.
<hr>

##### Reproduction Steps:

use the emilevauge/whoami container and display it in a tab.  The display ends up being black on black since whoami is black on white.  
<hr>

#### Errors on screen?  If so paste here:

```

```

**Comment by gilbN** [comment]
Then I think whoami has a transparent background.

**Comment by causefx** [comment]
if that is true. we have an easy solution. i add tab names as class name to body. use custom css to fix.

**Comment by rix1337** [comment]
That's a great workaround. Same issue applies to homeassisstant.

**Comment by rix1337** [comment]
Confirmed working with tab name "Home-Assisstant" that has a transparent background:
Add this in "custom css"
`.frame-Home-Assisstant{background-color:white}`
