### ISSUE TITLE
[v2] Homepage custom plex url not working

### ISSUE THREAD

**Issue by rix1337** [causefx/Organizr#957]
###### Operating System: Docker
<hr>

##### Problem Description:

Whithout 'Plex Tab WAN URL' set for the homepage. All plex items are correctly linked and will open e.g. `https://app.plex.tv/desktop#!/server/randomcharacters/details?key=/library/metadata/itemnumber`.

When I set 'Plex Tab WAN URL' to my custom url (https://my.domain/web) I would expect this to work, but it doesn't.

Manual testing ensures that replacing `https://app.plex.tv/desktop` with `https://my.domain/web` works perfectly fine and calls the correct media item.

<hr>

**Comment by causefx** [comment]
![image](https://user-images.githubusercontent.com/16184466/47272363-5fafa980-d539-11e8-8450-4de0cbbafe71.png)

did you fill in Plex Tab Name?

**Comment by rix1337** [comment]
Yes. It's named after my server (`my.domain`

**Comment by rix1337** [comment]
Yes, i filled in `my.domain` as my Server is named.
