### ISSUE TITLE
Error on update 0.99991

### ISSUE THREAD

**Issue by elRadix** [causefx/Organizr#96]
Notice: Undefined index: hovertext in /var/www/organizr/index.php on line 247

Can you fix the above error, the tabs are now all misplaced

thank you.

see screenshot
http://imgur.com/a/F7SyD

**Comment by rix1337** [comment]
did you browse /#upgrade and then reload?

**Comment by elRadix** [comment]
yes, I did,  still same issue on chrome incognito as well as my Android Chrome 

Notice: Undefined index: hovertext in /var/www/organizr/index.php on line 246
Notice: Undefined index: hovertext in /var/www/organizr/index.php on line 247

**Comment by rix1337** [comment]
mh. move your database to a secure location (=delete it from its original spot) and set up Organizr again. Let us know, if that works for you.

**Comment by elRadix** [comment]
Issue resolved, something wrong with the db?
had recreate all of my 15 tabs, would be nice to have some xmlimport/export functionality?
or some backup functionality ?

**Comment by rix1337** [comment]
The upgrade "should" do exactly that. It worked fine for me. Since its pre 1.0 I guess this doesn't matter.

Glad you resolved it anyway. Feel free to close the issue..

**Comment by chrisvdgeld** [comment]
I would like to add something to this: I've had the same thing, the error dissapears when I try to select a default template but you then get:

`Fatal error: Uncaught PDOException: SQLSTATE[HY000]: General error: 1 table options has no column named loading in /var/www/html/exileserver/settings.php:562 Stack trace: #0 /var/www/html/exileserver/settings.php(562): PDO->prepare('INSERT INTO opt...') #1 {main} thrown in /var/www/html/exileserver/settings.php on line 562`

**Comment by causefx** [comment]
@chrisvdgeld did you navigate to index.php#upgrade

**Comment by causefx** [comment]
@elRadix when you went to #upgrade did an upgrade page load?

**Comment by elRadix** [comment]
@causefx I did not understand the new update/upgrade  method,  relooking I think it should have worked. 
 
It think should have been better to include the onetime url/button in the in the update page without having to type the correctly.

**Comment by causefx** [comment]
this is a one time thing, after this update, once you upgrade it will take you to that page automatically.  I just had to code it in which it is now on there now.

**Comment by SgtBatten** [comment]
I also have this issue, I went to #upgrade and it looked like it reloaded the website. It reset all my coulours to the red/pink theme and I get the Fatal Error when trying to change it now.

Before i went to the upgrade page i have the same problem as in the first post where the tabs were Huge on the left hand side. Full page length each.

**Comment by causefx** [comment]
#upgrade is supposed to load this:
![image](https://cloud.githubusercontent.com/assets/16184466/22910597/3ea6f866-f218-11e6-9288-0323d9dc0890.png)

a moot point at this point, you guys won't have any issue after this.  as it will auto load the upgrade screen after this update.
