### ISSUE TITLE
[V2] Wrong position for active emby streams

### ISSUE THREAD

**Issue by hbooo** [causefx/Organizr#960]
###### Operating System: MacOS
<hr>

##### Problem Description:

The current position of an active emby stream is incorrect
![image](https://user-images.githubusercontent.com/242125/47489843-d0abd580-d847-11e8-95a7-7fe69cd97fac.png)

When I check in emby I have the correct position
!(https://i.imgur.com/DdHZ9k0.png)
![image](https://user-images.githubusercontent.com/242125/47489868-dacdd400-d847-11e8-96ff-ce90f2ea671b.png)

<hr>

##### Reproduction Steps:

Watch an episode in emby, 
Check in organizr for current active streams
<hr>

#### Errors on screen?  If so paste here:

```

```

**Comment by causefx** [comment]
does this happen with only tv shows or movies/music too?

**Comment by hbooo** [comment]
It seems to happen also with movies, there is an offset between current position in emby
![image](https://user-images.githubusercontent.com/242125/47512220-036fc100-d87c-11e8-9832-c2ea531e4a63.png)
 and organizr
![image](https://user-images.githubusercontent.com/242125/47512234-0bc7fc00-d87c-11e8-8ca3-df1ecd7cfe54.png)

**Comment by causefx** [comment]
it seems the api may have changed, i will have to test out

**Comment by causefx** [comment]
@rob1998

can you check the API out?

**Comment by rob1998** [comment]
Hmmm, for me it's still working as usual. I'm running a docker install atm, I think I'm using the latest version of Emby Server atm, but I would have to check that. Will get back to you. @causefx

**Comment by causefx** [comment]
@hbooo what version of emby?

thanks @rob1998

**Comment by rob1998** [comment]
I just checked, I'm running Version 3.5.3.0 of Emby Server. Still haven't encountered the bug.

**Comment by hbooo** [comment]
Yep it also works for me now, I guess a new version of emby have fixed it

Le dim. 11 nov. 2018 à 22:33, Rob Gökemeijer <notifications@github.com> a
écrit :

**Comment by causefx** [comment]
awesome. i’m glad guys.
