### ISSUE TITLE
Origanizr broken after downloading upate twice on accident

### ISSUE THREAD

**Issue by azumukupoe** [causefx/Organizr#961]
###### Operating System: Windows
<hr>

##### Problem Description:
I carelessly downloaded the update and then I found out Organizr not working. I've already ran the
OrganizrInstaller and the uninstaller but doesn't help.
`502 Bad Gateway nginx/1.14.0` is shown when I access localhost now.
<hr>

##### Reproduction Steps:

Download the latest update on V2 beta twice
Organizr becomes unavailable
<hr>

#### Errors on screen?  If so paste here:

```
502 Bad Gateway nginx/1.14.0
```

**Comment by causefx** [comment]
the first update did nothing?

**Comment by azumukupoe** [comment]
I don't think so but can't be sure...

**Comment by causefx** [comment]
can you jump on Discord so i can remote connect and see, i would love to see what is happening...

**Comment by azumukupoe** [comment]
I'm getting the same issue again but I have no idea what caused it. Can you make a guide so I can fix it by myself?

**Comment by causefx** [comment]
All that i fixed was made your php run on port 9001 as you had something running on 9000.  i then edited nginx.conf to reflect the port change.
