### ISSUE TITLE
[v2] Homepage-Item: JDownloader

### ISSUE THREAD

**Issue by rix1337** [causefx/Organizr#962]
###### Operating System: Docker
<hr>

##### Request Description:
Please add  "JDownloader" as another item to the Organizr homepage that will work seperately and within the Combined Downloader. 

### Update: see https://github.com/causefx/Organizr/pull/1206

I have implemented an API that serves all relevant info about JDownloader's downloads.
https://pypi.org/project/myjd-api/

Proposed Icon:
https://upload.wikimedia.org/wikipedia/commons/f/f7/Jdownloader.png

I will very gladly help you understand the above json.

**Comment by causefx** [comment]
this is awesome. i will test this

**Comment by rix1337** [comment]
Thank you 😄 

To really test it you need a JDownloader and a running rsscrawler checked out from the dev branch.
The feature works already but isn't polished yet.

I am still fixing a few things around (for my frontend mostly) and might add a few details like package UUIDs that will allow starting/stopping individual packages.

If there is a more international community that uses JDownloader, I could potentially make a standalone helper for the MyJD-API. (further down the road)

**Comment by rix1337** [comment]
If need be, here is the flask portion, that actually serves the json:
https://github.com/rix1337/RSScrawler/blob/dev/rsscrawler/web.py#L405

**Comment by rix1337** [comment]
Updated the examples, because of the added UUIDS

**Comment by causefx** [comment]
do you have a test instance i can hit the API with?

**Comment by rix1337** [comment]
I'll build a standalone version.

**Comment by rix1337** [comment]
Can't give you an eta. This shouldn't take long. Thanks for staying interested 😜

**Comment by causefx** [comment]
haha no problem!

**Comment by rix1337** [comment]
There you go:
https://github.com/rix1337/MyJD-API

A simple `pip install myjd_api` should do.

**Comment by rix1337** [comment]
All you need is python 2.7/3 and a JDownloader connected to a MyJDownloader account

**Comment by rix1337** [comment]
Also there are tons of other, undocumented api-functions (don't have time for that.. 👎 )

**Comment by rix1337** [comment]
Hi @causefx 

I have looked at your very clean code again and managed to integrate support for my myjd_api package.
You need python and then `pip -I install myjd-api` (v.0.0.1 was broken -I will force a reinstall and upgrade to 0.0.2). Launch your JDownloader and connect it to the MyJDownloader services.

Running `myjd_api` from your terminal will then ask for your my.jdownloader.org credentials and output the URL at which it supplies all status info on the connected JDownloader.

**Comment by rix1337** [comment]
Once that is done, I will send a pull request. Hope you are interested 👍

**Comment by rix1337** [comment]
Feature complete:
![itworks](https://user-images.githubusercontent.com/9930448/60279416-48636000-9901-11e9-88ff-f7f61589dc35.PNG)

**Comment by rix1337** [comment]
Thanks for merging. Can't wait for the next update.
