### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by darkcloud784** [causefx/Organizr#965]
###### Operating System: Windows/MacOS/Ubuntu
<hr>

##### Request:
Add the ability to see mapped drives size. Example being a NAS storage size, how much is used, and how much is still free. This could be displayed on the top bar or as a stand alone row on the home page.
<hr>

**Comment by reliefs** [comment]
Go inside your organzir folder edit homepage.php
find the right line

insert
$ds = disk_total_space("/");
echo $ds;

**Comment by causefx** [comment]
Please make this a request on FeatHub.  Would love to get other users to vote what they want next.
