### ISSUE TITLE
How to get/read other plex api info?

### ISSUE THREAD

**Issue by reliefs** [causefx/Organizr#966]
###### Operating System: Windows/MacOS/Ubuntu
<hr>

##### Problem Description:
I want to read the "file" string attribute from the plex api. I have almost it done with my own php script. 
<hr>

##### Reproduction Steps:

I have tried to add but without any good results $('#calendarFile').text(result.file);
<hr>

#### Errors on screen?  If so paste here:

Can't call other plex attributes from their api.
```

```

**Comment by causefx** [comment]
which organizr version?

**Comment by reliefs** [comment]
> which organizr version?
> […](#)
> Sent from my iPhone
> On Oct 29, 2018, at 11:38 AM, reliefs ***@***.***> wrote: Organizr Version: V 1.x Branch: Master/Develop WebSever: Nginx/Apache Operating System: Windows/MacOS/Ubuntu Problem Description: I want to read the "file" string attribute from the plex api. I have almost it done with my own php script. Reproduction Steps: I have tried to add but without any good results $('#calendarFile').text(result.file); Errors on screen? If so paste here: Can't call other plex attributes from their api. — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

Version: 1.80

**Comment by causefx** [comment]
i'm no longer working on 1.8, i would try a fresh install of v2.

**Comment by reliefs** [comment]
I have now installed version 2.0, where can i change the plex api calling info so i can call other info from the api like file destination ?

**Comment by causefx** [comment]
using php you can call plex API using this function 

`plexConnect($action, $key = null)`

you can create a php file in root dir and start it with:


```
<?php
require_once './api/functions.php';
```
