### ISSUE TITLE
Error page redirects to "/" which breaks reverse proxy using base path

### ISSUE THREAD

**Issue by rcdailey** [causefx/Organizr#967]
I have a reverse proxy for Organizr which redirects `https://domain.com/organizr` to `http://organizr:80` in a docker container. When I do this:

    https://domain.com/organizr/?error=500

This successfully loads the error page, but redirects the browser to `https://domain.com`. I expect that the browser is instead sent to `https://domain.com/organizr/` instead.

Upon inspection of the code, I see this in `js/functions.js` (line 3231, at `function errorPage()`):

```js
if(local('get', 'error')){
    //show error page
    $('.error-page').html(buildErrorPage(local('get', 'error')));
    $('.error-page').fadeIn();
    local('remove', 'error');
    window.history.pushState({}, document.title, "/" );
}
```

The `pushState()` to `"/"` seems to be the issue. I'm not sure what the solution is, but iXNyNe (on Discord) confirmed with @causefx that this can be easily fixed.

Using latest version from the `organizrtools/organizr-v2` image.

**Comment by causefx** [comment]
this was fixed yesterday. :)

**Comment by rcdailey** [comment]
Oh I apologize, I saw 61219045bd18a486bafe78a09d179b3dd08f8e68 on `v2-develop` but the title was:

> OMBI SSO with Plex Token (Ombi 3.0.3950 needed - Thanks Jamie)

Didn't jump out at me as the fix for the issue we talked about. I'll go ahead test your fix then and close this out.

**Comment by rcdailey** [comment]
Just tested and it works!

Going to `https://domain.com/organizr/?error=500` takes me to `https://domain.com/organizr/`!

Thanks a bunch!

**Comment by causefx** [comment]
awesome. thanks.
