### ISSUE TITLE
[v2]Sign-up Error Occurred

### ISSUE THREAD

**Issue by fungus99** [causefx/Organizr#968]
###### Operating System: Freenas 11.1 U6
<hr>

##### Problem Description:
Fresh Nginx install and Organizr clone.  I work through the set up wizard including changing database location permissions.  Upon trying to finish the wizard, i get a pop-up: Sign-up Error Occurred. 

Also, where are the logs.  Nothing in /var/log.

<hr>

##### Reproduction Steps:

<hr>

#### Errors on screen?  If so paste here:

```
Sign-up Error Occurred
```

**Comment by causefx** [comment]
what version of php?

**Comment by fungus99** [comment]
PHP Version 7.2.11

**Comment by fungus99** [comment]
Browser console error messages:

![screen shot 2018-10-29 at 11 38 05 pm](https://user-images.githubusercontent.com/44594826/47698124-b705e780-dbd3-11e8-92d3-f33aee3a0989.png)

on mouse hover the jquery-2.2.4.min.js shows a location of 'jail-ip/js/jquery-2.2.4.min.js '

jquery-2.2.4.min.js is in that location with the nginx user as the file owner.  

I created a info.php page in the jail-ip/js/ folder and that is accessible

**Comment by causefx** [comment]
i need to research this one more...

**Comment by causefx** [comment]
did the test db location button work?

**Comment by fungus99** [comment]
Yes.  Originally it threw a permissions error, but once I chown the directory to the nginx user it created the database without issue.  

Is there a Organizr log somewhere that would be useful in your research? I have not been able to locate it so far.

**Comment by causefx** [comment]
the log is created after the db file. it’s placed inside the same folder as db

**Comment by fungus99** [comment]
the only thing in the database folder is the .db file created by the setup wizard.  No log.

**Comment by causefx** [comment]
is the db file zero bytes?

**Comment by fungus99** [comment]
yes

**Comment by causefx** [comment]
did you git clone or download files? if so, when?

**Comment by fungus99** [comment]
Git clone with the v2-develop branch.  Yesterday

**Comment by causefx** [comment]
i will try and set organizr up as a jail when i get home today. i too am on freenas 11

**Comment by fungus99** [comment]
Is there any more information I can provide to help you diagnose this?

**Comment by causefx** [comment]
Sorry, i got side tracked...  I will try and install on FN today.

**Comment by causefx** [comment]
I just installed it with zero problems on 11.1 U4

![image](https://user-images.githubusercontent.com/16184466/48288131-54f57f80-e428-11e8-9e3c-631372f9c23d.png)

**Comment by causefx** [comment]
I created a new jail:

ran:

```
pkg install nginx
pkg install php72
pkg install php72-extensions
pkg install php72-zip
pkg install php72-curl
pkg install php72-openssl
pkg install git
mkdir /usr/local/www/org
mkdir /usr/local/www/db
git clone https://github.com/causefx/Organizr.git -b vs-devleop /usr/local/www/org
```

i then edited nginx.conf to reflect correct paths to php and root folder.
then ran:
```
chown -R www:www /usr/local/www/org
chown -R www:www /usr/local/www/db
```

restarted both nginx and php and ran thru installer for org

**Comment by causefx** [comment]
Closing for now, reply back and we will open again.
