### ISSUE TITLE
[V2] Login with plex oauth broke organizr auto login to ombi and plex

### ISSUE THREAD

**Issue by polynar** [causefx/Organizr#969]
###### Operating System: Ubuntu
<hr>

##### Problem Description:
Hi! I want the user sign in with plex oAuth and Organizr login the user to ombi and plex. I set this up. but won't works only if the user login with username and password to organizr. When user login with oauth and manually login to ombi or plex then refresh the page ombi is logout only if the user logged in to organizr with oaut 

<hr>

##### Reproduction Steps:
set up ombi inside organizr
set up plex inside organizr
enable oath for plex and ombi
enable plex oauth for organizr login
login with plex oauth in organizr
open ombi and you see the login screen
if you log in and refresh the page you are logged out again

login with username and password to organizr without changing the settings
and open plex or ombi tab you alredi logged in.

<hr>

#### Errors on screen?  If so paste here:

```

```

**Comment by si0972** [comment]
Ombi Ouath SSO is only available on the develop brach of ombi atm.

**Comment by causefx** [comment]
ombi OAuth only work on 3.0.3950 and above

**Comment by justinpeterson13** [comment]
I'm on Ombi 3.0.3966 and I have the same issue. My SSO (ombi/plex/tautulli) is only broken when I log into Org via Plex oAuth. When I log in with Org credentials, SSO is fine (ombi/plex/tautulli). Not sure if its a config issue on my end or an issue others have as well.

**Comment by polynar** [comment]
@justinpeterson13 I have the same issue.

**Comment by causefx** [comment]
@polynar just change image to use `lsiodev/ombi-preview`

can you post output from User Menu > Debug Area > SSO

![image](https://user-images.githubusercontent.com/16184466/48212618-35cbf480-e339-11e8-8228-84aaa63bd709.png)

**Comment by justinpeterson13** [comment]
Now that I've called this to your attention, it just seems to work... The only thing I changed in the mean time was retrieve a new Plex Token, couldn't tell you if it was the Org Auth or SSO tab in settings. 
The Debug came back "True" for all three plex/ombi/tautulli. Sorry to waste your time!

**Comment by causefx** [comment]
great tip tho!  That may be something... lol who knows.   Thanks!

**Comment by regoras** [comment]
Sorry to necro this, but I'm actually experiencing the same issue. For some reason, it looks like the debug is saying Ombi isn't getting a login cookie like tautulli and Plex are. 

```
{
	"plex": {
		"enabled": true,
		"cookie": true,
		"machineID": "(my machine ID)",
		"token": true,
		"oAuth": true,
		"backend": true
	},
	"ombi": {
		"enabled": true,
		"cookie": false,
		"url": true,
		"api": true
	},
	"tautulli": {
		"enabled": true,
		"cookie": true,
		"url": true
	}
}
```

Above is the output the debug command is spitting out. I've struck my machine ID, not sure if that's necessary here.

**Comment by causefx** [comment]
is plex oauth enabled in ombi settings?

**Comment by regoras** [comment]
Yup, Oauth is enabled on Ombi. I've tried with the ombi url as https://myddns/ombi, http://127.0.0.1:5000/ombi, and http://127.0.0.1/ombi on the Ombi SSO settings in Org. So far none of the above have worked for Oauth. SSO does work if I just use my regular Org login credentials (which match my Plex creds).

Interestingly, if I use 127.0.0.1, then SSO doesn't work even with my regular Org login credentials.

**Comment by causefx** [comment]
haha. yeah i hear that. sometimes i don’t question the computer gods. lol
