### ISSUE TITLE
[V2] Plex oAuth succesful but login fails

### ISSUE THREAD

**Issue by mvanlijden** [causefx/Organizr#970]
###### Operating System: docker organizrtools/organizr-v2 on UnRaid 6.6.3
<hr>

##### Problem Description:
After enabling Plex oath in the settings trying to log in with my admin's Plex oAuth fails. However the oAuth itself seems to have been succesfully completed. The notifcation "oAuth Successful - Please wait..." appears. However also the error "Login error - Wrong username/email/password combo" also appears. Login is cancelled afterwards.

<hr>

##### Reproduction Steps:
Set up a new docker, set up admin account (tried one with my Plex admin data and also a fresh one with another user & email & password)
In Authentication enable Organizr DB + Backend and select Plex. Get Plex Token and Get Plex Machine works fine on this part. Switch Plex oAuth on
Log out and try to log back in with Plex oAuth

<hr>

#### Errors on screen?  If so paste here:
```
Login error - Wrong username/email/password combo
oAuth Successful - Please wait...
```

**Comment by mvanlijden** [comment]
Using another browser session i did manage to login with Plex user from my girlfriend.
No user was present before logging in. Was created fine....

My own Plex user can log into Plex site normally, get tokens for access and machines normally...
Don't know what is different, besides the fact that i have PlexPass and she does not.

**Comment by causefx** [comment]
On settings page, do you have plex admin username filled in?

**Comment by causefx** [comment]
do you have the plex admin username filled in on the settings page?

**Comment by causefx** [comment]
for Ombi SSO, you need to fill in ombi url and ombi api key.

once its setup, you can log out and back in... if username and password matches ombi, you can now:
be auto logged into ombi url (automatically works with /ombi) if ombi is on subdomain, you need to add /auth/cookie to the end of url.

for tautulli, same info needed... this can be either directory or subdomain.... this will auto log that user in, only if guest access is enabled for that user in tautulli settings.

**Comment by jaydee99** [comment]
Hi,

Ombi SSO is broken for me with last update...

Regards

**Comment by causefx** [comment]
can you goto debug area and click Ombi SSO. 

debug is under user menu

**Comment by jaydee99** [comment]
{
	"enabled": true,
	"cookie": false,
	"url": true,
	"api": true
}

**Comment by mvanlijden** [comment]
Ombi SSO also not working here,
Same debug output
{
	"enabled": true,
	"cookie": false,
	"url": true,
	"api": true
}

Created new API key also to test, but no go.

**Comment by causefx** [comment]
When everything is true except cookie, that means that ombi rejected the credentials org supplied to them.  if using oAuth make sure you are on 3.0.3950

**Comment by jaydee99** [comment]
It doesn't work using oAuth or not and i'm on latest ombi release... It was working perfectly with last version of Organizr and i didn't change anything...

**Comment by causefx** [comment]
i have to research this a bit more as nothing really has changed.

**Comment by mvanlijden** [comment]
Might be, but it is still not working here...
All dockers are updated to latest release, still same version numbers as above.
Attached are all relevant settings. API key from Ombi is entered in Organzr v2 of course but hidden for privacy.
![screenshot 4](https://user-images.githubusercontent.com/14346943/48062458-6e958d80-e1c2-11e8-8930-8b1edc781fd8.jpg)
![screenshot 1](https://user-images.githubusercontent.com/14346943/48062459-6e958d80-e1c2-11e8-9751-75e383d31108.jpg)
![screenshot 2](https://user-images.githubusercontent.com/14346943/48062460-6f2e2400-e1c2-11e8-8761-76da78ba0cea.jpg)
![screenshot 3](https://user-images.githubusercontent.com/14346943/48062461-6f2e2400-e1c2-11e8-9bb4-f50fa54ea0ed.jpg)

**Comment by causefx** [comment]
on the single sign on page for ombi, please put in http://localip:port of ombi instance

**Comment by jaydee99** [comment]
Still not working with http://localip:port

**Comment by mvanlijden** [comment]
Doesn't work either here....

**Comment by causefx** [comment]
can everyone try ombi 3.0.3950

**Comment by mvanlijden** [comment]
> can everyone try ombi 3.0.3950

Would love to if it is released into the latest linuxserver docker image, but it hasn't yet.

**Comment by causefx** [comment]
just chg img to:

lsiodev/ombi-preview

you can always change back - or make a backup

**Comment by causefx** [comment]
also everyone recheck your plex machine ID

**Comment by jaydee99** [comment]
Updated with lsiodev/ombi-preview and now working perfect ! Thanx !!

**Comment by dejected1** [comment]
my ombi sso wasnt working on latest master build: 3.0.3945 after the latest organizr update.  i just updated to latest ombi developer build: 3.0.3966. SSO still not working. i tried logging into organizr with Plex OAuth and without. I also tried with and without Plex OAuth in ombi as well. 

my sso debug shows 
{
	"misc": {
		"oAuthLogin": true,
		"rememberMe": true,
		"rememberMeDays": "7"
	},
	"plex": {
		"enabled": true,
		"cookie": true,
		"machineID": "OMITED",
		"token": true,
		"oAuthEnabled": true,
		"backend": true
	},
	"ombi": {
		"enabled": true,
		"cookie": false,
		"url": true,
		"api": true
	},
	"tautulli": {
		"enabled": true,
		"cookie": true,
		"url": true
	}
}

my logs also state: 
Ombi Token Function - Ombi did not return Token

Looks like the cookie isnt created for ombi? i tried clearing all cookies and cache as well. tatutulli sso is working ok.

**Comment by mvanlijden** [comment]
SSO on Ombi from Organzr still not working... Ombi stable is updated to 3.0.3988. Organizr still on 2.0.0-beta.800 but latest docker.
Logging in manually with Plex OAuth in Ombi also takes a while. Here are the debug settings..

{
	"misc": {
		"oAuthLogin": true,
		"rememberMe": true,
		"rememberMeDays": "7"
	},
	"plex": {
		"enabled": true,
		"cookie": true,
		"machineID": "<<nope>>",
		"token": true,
		"oAuthEnabled": true,
		"backend": true
	},
	"ombi": {
		"enabled": true,
		"cookie": false,
		"url": true,
		"api": true
	},
	"tautulli": {
		"enabled": true,
		"cookie": true,
		"url": true
	}
}

**Comment by causefx** [comment]
is ombi oAuth enabled?

**Comment by mvanlijden** [comment]
> is ombi oAuth enabled?

it was. I changed the SSO settings for ombi url from "/ombi" to "http://IP:3579/ombi" and now seems to be working. Debug confirms it. Maybe an idea to create a instruction / helptext for the field what format it should be. Other places in Organzr /ombi is enough, but for SSO the local IP:Port/Dir is needed.

{
	"misc": {
		"oAuthLogin": true,
		"rememberMe": true,
		"rememberMeDays": "7"
	},
	"plex": {
		"enabled": true,
		"cookie": true,
		"machineID": "cad5d5042c719690f8d5fcb8cef82aac1ec3084b",
		"token": true,
		"oAuthEnabled": true,
		"backend": true
	},
	"ombi": {
		"enabled": true,
		"cookie": true,
		"url": true,
		"api": true
	},
	"tautulli": {
		"enabled": true,
		"cookie": true,
		"url": true
	}
}

**Comment by dejected1** [comment]
i tried changing the organizr ombi sso settings to http://ip:port/ombi. still no go. I tried https:domain/omib, no go. I tried getting a new token from plex and ombi. no go. Debug says cookie: false for ombi sso. this was working prior to last organizr update. ive also updated ombi to 4007, no change.

**Comment by kimsbrian** [comment]
> 
> 
> Don't know why, i tried setting and resetting this before too. But now it works ok..... Still very glad! Can now disable the Organizr DB authentication on go Plex only :)
> 
> From the text in the SSO settings i have one other question. For me it not clear what the SSO on Ombi and Tautulli does... Because both use the same Plex login to work. Is it that because Plex is enabled as SSO, that it can be used to auto login with Ombi and Tautulli? It's not very clear from a user perspective. What do you have to fill with Token in the Ombi OSS? the Plex Token of the Ombi API key? Both seem not to work...

I'm having the same problem and can't seem to fix it. Do you remember what you reset?

**Comment by causefx** [comment]
can you post the debug part of SSO?

**Comment by kimsbrian** [comment]
{
	"misc": {
		"oAuthLogin": false,
		"rememberMe": true,
		"rememberMeDays": "7"
	},
	"plex": {
		"enabled": true,
		"cookie": true,
		"machineID": true,
		"token": true,
		"oAuthEnabled": true,
		"backend": true
	},
	"ombi": {
		"enabled": true,
		"cookie": true,
		"url": "http://localhost:5000",
		"api": true
	},
	"tautulli": {
		"enabled": true,
		"cookie": true,
		"url": "http://localhost:8181"
	}
}

**Comment by causefx** [comment]
what is the issue that is happening to you?

**Comment by kimsbrian** [comment]
Same as the original poster. When it's someone other than me who tries to login to Organizr using Plex, they receive "Login error - Wrong username/email/password combo" but it also shows "oAuth Successful - Please wait..."

**Comment by dejected1** [comment]
SSO for ombi still doesn't work. Was working before last organizr update. No changes made and it stopped working. 
i tried changing the organizr ombi sso settings to http://ip:port/ombi. still no go. I tried https:domain/omib, no go. I tried getting a new token from plex and ombi. no go. Debug says cookie: false for ombi sso. this was working prior to last organizr update. ive also updated ombi to 4007, no change.

{
	"misc": {
		"oAuthLogin": true,
		"rememberMe": true,
		"rememberMeDays": "7"
	},
	"plex": {
		"enabled": true,
		"cookie": true,
		"machineID": "OMITTED",
		"token": true,
		"oAuthEnabled": true,
		"backend": true
	},
	"ombi": {
		"enabled": true,
		"cookie": false,
		"url": true,
		"api": true
	},
	"tautulli": {
		"enabled": true,
		"cookie": true,
		"url": true
	}
}

**Comment by causefx** [comment]
can you test it for a non admin acct

**Comment by causefx** [comment]
something in ombi isn’t allowing the return of the token.  is admin listed in users as a Plex User?

**Comment by dejected1** [comment]
yes, in organizr and ombi and plex the user id for admin is listed , its the same across all platforms. oath works for organizr and works for ombi, separately. if i use plex auth for organzir it works. but i have to do it again from the ombi interface to log into ombi. it works there too thou.

**Comment by causefx** [comment]
nothing in org process has changed at all... i just pass the token from plex to ombi. ombi then checks the token and if it is good to go then it will return an ombi token. so now that we know the process from a normal users works, it confirms that ombi is the reason for not returning a token. everything in organizr is configured correctly.

**Comment by kimsbrian** [comment]
Does remote access have to be enabled and correctly configured? Someone in the Discord mentioned it but I don't really have a way to test that out. Is access from a custom access url not sufficient for logging on? I may be mistaken but I'd imagine Plex auth is with the account and not necessarily the server itself.

**Comment by Lockszmith** [comment]
Had the same issue, which got me to here.
Nothing here really helped me.
Eventually I reset the Plex token and machine token in the SSO configuration which seems to do the trick.

hope this helps someone who will get here.

**Comment by TristBella** [comment]
I can not login using Plex SSO. I get the same error as the OP description. I can however login when on the machine where Organizr exists. When using NGINX reverse proxy (which is the outside world) login fails with the following error in log: 
"Plex Token Check Function - Error: cURL error 28: Resolving timed out after 10000 milliseconds [Execution Time: 11.08s | 11080.5ms]"
I can connect directly to Plex from the outside NGINX domain (https://plex.domain.com) and from local ip domain (http://192.1.1.1:32400) on the hosting box.

Tried resetting the token, didn't work.
