### ISSUE TITLE
[V2] If "Database Name" contains .db during setup, do not append .db

### ISSUE THREAD

**Issue by Archmonger** [causefx/Organizr#971]
###### Operating System: Freenas
<hr>

##### Problem Description:
Double appending of file extensions will occur of this check is not in place. Honestly may be worth also putting in a check for any file extension and warning the user it's a bad name, or outright rejecting the name.
<hr>

##### Reproduction Steps:
During setup, put "database.db" in as the "Database Name" and watch as you are given `database.db.db`.
<hr>

#### Errors on screen?  If so paste here:
N/A

**Comment by causefx** [comment]
ahhhh.... let me research.

**Comment by causefx** [comment]
I am going to temp disable lock function for users logged in via oAuth

**Comment by causefx** [comment]
completed
