### ISSUE TITLE
[V2]Can't request movie/tv show from Plex search

### ISSUE THREAD

**Issue by ochbob** [causefx/Organizr#972]
###### Operating System: Debian
<hr>

##### Problem Description:
Can't request movie/tv show from Plex search on Homepage.

<hr>

##### Reproduction Steps:
I do not have "Request" option when i use plex search like this:

https://raw.githubusercontent.com/Burry/organizr-v2-plex-theme/master/screenshots/4.png

connexion to Ombi is good, I can see request from homepage.

<hr>

#### Errors on screen?  If so paste here:

```

```

**Comment by causefx** [comment]
ombi sso needs to be on, once that is on, you need to make sure that the user logging in matches an ombi user.

**Comment by ochbob** [comment]
Sorry for stupid question, but what's SSO ?

**Comment by causefx** [comment]
it’s not stupid. SSO is single sign on. 

go to settings in organizr and fill in the ombi portion under SSO

**Comment by ochbob** [comment]
Oh, I see :)

Thank you,

so I double check my configuration:

SSO Ombi  settings in Organizr V2 => http://LOCALIPOMBI:5000 + token + enable
Ombi homepage settings in Organizr V2  => enable for min user level + http://LOCALIPOMBI:5000 + token 

I'm admin on Plex/Ombi, I'm connected into Organizr with my id (same as plex/ombi), but i can't request movie when it does not exist, but i can mark as available or delete request (from homepage) made directly from ombi (so admin right is good)

I try with a user level account connected from plex oauth, I can't remove or mark as available from homepage (so right is good too)

Ombi SSO is the only one active and my authentification settings are:

Organizr DB + backend, backend is Plex, oauth is enable.

Any idea ?

Thx :)

**Comment by causefx** [comment]
did you log out and then back in after enabling ombi sso?

**Comment by ochbob** [comment]
I think it was the trick, but, i logout to test my other level account user and it does not work at this moment...

Maybe need some time to connect to different API ?

right now it's OK !

thank you !

**Comment by causefx** [comment]
just make sure the user exists in ombi. then do the logout login dance :)

**Comment by ochbob** [comment]
I try it again for a user who is a "user" level, but i can't request :/
(login with plex oauth and user exist in ombi)

It's ok for my admin account.

**Comment by ochbob** [comment]
ok, will try later, thx for advice :)

i'm running with stable 3.0.3923 right now.

**Comment by polynar** [comment]
> Found out something, when I login from admin account without plex oauth => it's OK
> with plex oauth prompt on login page it's not OK.

The situation is similar to me: #969
