### ISSUE TITLE
[V2] Lock Screen Password Fails If Using Plex oAuth

### ISSUE THREAD

**Issue by MattKavs** [causefx/Organizr#973]
###### Operating System: Ubuntu
<hr>

##### Problem Description:

When using the lock screen, unlocking will fail if the user originally logged in with the Plex backend rather than Organizr. The only workaround I've found is to clear cookies, re-login to Organizr using the Organizr database, at which point the user will again be presented with a lock screen where the password will now work. This could cause issues for users who use only the Plex backend for authentication.
<hr>

##### Reproduction Steps:

Log in using Plex oAuth, activate lock screen, attempt to unlock.
<hr>

#### Errors on screen?  If so paste here:

```
N/A
```

**Comment by causefx** [comment]
I am going to temp disable lock function for users logged in via oAuth

**Comment by causefx** [comment]
Closing this for now, I will also add an option in future for admin to unlock user accts.
