### ISSUE TITLE
Remote access 

### ISSUE THREAD

**Issue by luluhoc** [causefx/Organizr#975]
Will you guys ever consider adding remote access on top of the local?
I mean if there is a possibility to put two addresses in each tab for local and remote.

**Comment by causefx** [comment]
yes, i was playing around with that idea.  I already have the DB setup to accept local url in future.  I will keep everyone posted.

**Comment by luluhoc** [comment]
Thank you for your answer

**Comment by causefx** [comment]
Can you please make this request on FeatHub?

Thank you
