### ISSUE TITLE
No Settings / Blank Screen

### ISSUE THREAD

**Issue by adriangigliotti** [causefx/Organizr#976]
###### Operating System: Raspbian Jessie Lite
<hr>

##### Problem Description:
I cannot see settings, or anything on the homepage. Almost blank screen, see screenshot: https://imgur.com/a/gRWOpvn

<hr>

##### Reproduction Steps:
Rebooted Raspberry Pi, pressed the refresh icon in Organizr.

<hr>

**Comment by si0972** [comment]
Did you reach the Wizard?

**Comment by causefx** [comment]
make sure the homepage tab is setup for that user group

**Comment by causefx** [comment]
closed for inactivity.  reply and we will open this back up
