### ISSUE TITLE
Downloader not disappearing if insufficient perms.

### ISSUE THREAD

**Issue by si0972** [causefx/Organizr#977]
###### Operating System: Docker
<hr>

##### Problem Description:
Downloader stays on homepage, even when the user isnt allowed to view the cue.
https://img.roxedus.net/chrome-2018-11-09_15-25-32.png

Happening on both single and combined view.

<hr>

#### Errors on screen?  If so paste here:

From Dev console.

https://img.roxedus.net/2018-11-09_15-28-29.png

**Comment by causefx** [comment]
fixed.
