### ISSUE TITLE
Make left hand indicator bar grab-able for easier navigation

### ISSUE THREAD

**Issue by wallsy1703** [causefx/Organizr#979]
###### Operating System: Windows / Chome
<hr>

##### Problem Description:
Using a laptop / track pad, it's very difficult to scroll up and down the Navigation Bar.
Is it possible to please make the indicator bar on the far left (that appears when first hovering over the bar) grab-able,  with a single left click, so it can then be moved up and down easily with a normal single movement on the track pad

<hr>

##### Reproduction Steps:

<hr>

#### Errors on screen?  If so paste here:

```

```
![capture1](https://user-images.githubusercontent.com/29837777/48314078-37f1b580-e5bc-11e8-9771-eda183038700.png)

**Comment by causefx** [comment]
the bar is grab-able.  I will try on my laptop later today.

**Comment by causefx** [comment]
this has been fixed

**Comment by wallsy1703** [comment]
Thank You, really appreciated :)
