### ISSUE TITLE
Error when modify color since v.0.99991

### ISSUE THREAD

**Issue by fana13** [causefx/Organizr#98]
Hi,

Since the v.0.99991 an error was appear when change any color in any field.
It appear when we save options

Here the error : 
`Fatal error: Uncaught exception 'PDOException' with message 'SQLSTATE[HY000]: General error: 1 table options has no column named loading' in /var/www/Organizr/settings.php:562 Stack trace: #0 /var/www/Organizr/settings.php(562): PDO->prepare('INSERT INTO opt...') #1 {main} thrown in /var/www/Organizr/settings.php on line 562`

Thanks :)

**Comment by causefx** [comment]
navigate to index.php#upgrade or just updatedb.php

**Comment by fana13** [comment]
You're the best.
Many thanks
