### ISSUE TITLE
502 Bad Gateway, tired all solutions i could find to this error.

### ISSUE THREAD

**Issue by xAhlen** [causefx/Organizr#980]
###### Operating System: Ubuntu
<hr>

##### Problem Description:
Getting the error msg bellow in /var/log/nginx/error.log

Ran the installation script with 4 (full installation), tried it 2 times. On a brand new deployed Ubuntu VM, running Ubuntu 18.04.1.
I understand it's missing something but i don't understand what. Sorry if this is a noob error but im not very good at linux and i've tried finding a solution on my own but i'm at a loss.

**Extra info**

ahlen@organizr:~$ whereis php
php: /usr/lib/php /etc/php /usr/share/php7.2-sqlite3 /usr/share/php7.2-xml /usr/share/php7.2-curl /usr/share/php7.2-xmlrpc /usr/share/php7.2-common

<hr>

##### Reproduction Steps:
Rolled back the machine with a snabshot and ran the installation script again and got the same error.
Rolled it back an other time and installed the V1 and still the same error.
<hr>

#### Errors on screen?  If so paste here:

```
19:57:50 [crit] 27575#27575: *1 connect() to unix:/run/php/php7.2-fpm.sock failed (2: No such file or directory) while connecting to upstream, client: 192.168.XX.XX, server: www.organizr.local, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.2-fpm.sock:", host: "192.168.XX.XX"
```

**Comment by xAhlen** [comment]
The problem is that i can't find anything about php in /run/ , it doesn't exist. Am i missing some dependencies?

**Comment by causefx** [comment]
the path is in `nginx.conf` edit it in the php block.

**Comment by xAhlen** [comment]
I'm sorry i don't understand what you mean. Is there a path in the nginx.conf file that i need paste in a php block file? or do i need to specify the path to the ngnix.conf somewhere?

**Comment by causefx** [comment]
locate you www.conf inside the php folder....

possibly /etc/php and then some subfolder, maybe conf.d/

inside that www.conf you will see the socket location...

**Comment by xAhlen** [comment]
found the only www.conf on my server and it was
/opt/OrganizrInstaller/centos/oci/config/php/www.conf
in that i found the path "listen = /var/run/php-fpm/php-fpm.sock"
but that path doesn't exist either. Every guide i find the php.sock should be under etc/php/
But that folder doesn't contain anything useful. Just can figure out what im doing wrong. 

<img width="883" alt="screenshot 2018-11-13 at 19 25 01" src="https://user-images.githubusercontent.com/24399180/48434386-dc6d2680-e779-11e8-8acd-b893d27e2413.png">
<img width="602" alt="screenshot 2018-11-13 at 19 23 47" src="https://user-images.githubusercontent.com/24399180/48434389-dc6d2680-e779-11e8-898c-c6d3ce17d337.png">
<img width="912" alt="screenshot 2018-11-13 at 19 23 11" src="https://user-images.githubusercontent.com/24399180/48434390-dd05bd00-e779-11e8-82f2-6cd787e985ef.png">

Maybe i should give up here and try to learn linux instead. Is it easier deploying in CentOS? 
Watching a guide on youtube installing this and he doesn't have to adjust anything it just works straight out of the box with ubuntu, im not getting what im doing wrong. Sorry for taking up your time, i just really love the concept of Organizr.

**Comment by xAhlen** [comment]
I read through the readme instructions of the ubuntu installations script and saw that it was tested on 16.04 so deployed a 16.04 machine and it worked straight away. So maybe the script doesn't work in 18.04.1. 

Thanks for taking your time.

**Comment by agrudsky** [comment]
I also had this issue. The problem is that Ubuntu 18.04.1 ships with PHP 7.2, so the path to the socket has changed. In your Nginx site config file, you need to change the PHP socket location to the new 7.2 socket:

`fastcgi_pass unix:/var/run/php/php7.2-fpm.sock;`

When this is done, you will be able to access Organizr but it will get stuck in a refresh loop on the Dependency Check page. I have opened a new issue for this in #982.

**Comment by causefx** [comment]
awesome! glad it is sorted.
