### ISSUE TITLE
don't delete nginx default vhost

### ISSUE THREAD

**Issue by notstevek** [causefx/Organizr#981]
###### Organizr Version: V 1.x
v1
###### Branch: Master/Develop
master
###### WebSever: Nginx/Apache
nginx
###### Operating System: Windows/MacOS/Ubuntu
raspbian 8.0 jessie
<hr>

##### Problem Description:

using the first option "Organizr install + Nginx site install", you end up deleting the "default" vhost located in sites-available (and sym-linked to sites-enabled on fresh install). I assume this issue will happen with any script installation option that involves nginx, as it's clearly a written functionality in the script on lines 249 and 503 of the ou_installer.sh bash file. I guess for most people its not an issue, and you do back it up to /tmp/Organizr/bk/nginx_site_default but option 1 doesn't say it backed it up, nor deleted it in the first place, I just found that from reading through the script. However for users like me with multiple sites on nginx I use the default file a lot for reference, and have extra additions added for other stuff like proxy_pass etc, I think deleting the sym-linked default in sites-enabled would suffice (as the script does anyway as well) as that will disable it (hence the whole available/enabled nginx setup), while leaving the stock file. Again it's not a huge deal, I assume most using the script in the first place won't have this issue, as they'll never know that it existed let alone deleted, I only used the script to see how well it worked and what it offered. It's only a 4kb file and some tutorials online reference this file (cp default "newsite", edit "newsite"), so I don't think you'll get flack for leaving it by anyone, or at least delete it only for people who use this script to install nginx, and not option 1 which just installs the vhost. thanks.
<hr>

##### Reproduction Steps:

since it's *not a bug* technically no need to reproduce, but any fresh installation including nginx install will reproduce the issue.
<hr>

#### Errors on screen?  If so paste here:

```

```

**Comment by christronyxyocum** [comment]
It's assumed you're running this on a completely fresh install. If you already have Nginx installed and running multiple sites why are you using option 1 in the first place? Why not just Git clone the repo?

v1 isn't actively developed anymore. Install the v2 Beta (v2-develop branch of the repo) which is light-years ahead of v1 and very stable.

**Comment by notstevek** [comment]
if thats the case why have those extra options, and such for people who have php7/8 already installed? I wanted to see what the script did, how it performed, and i also didn't see the exact requirements that /check.php tells you if you have, and didn't see the nginx vhost, so led me to just try the script. like I said it's not a big deal but that's what the sym-link is for, to disable default vhost, it's less coding to not delete it as you're removing two lines of code at least and it'd still function as needed. as for v1 being inactive, wasn't aware of that. I will do that though later, thanks.

since v1 isn't developed anymore, Ill close this.
