### ISSUE TITLE
[V2] Where is declare the {domain} variable and how change default HTTP port

### ISSUE THREAD

**Issue by ptitsnake** [causefx/Organizr#983]
###### Operating System: Debian 9
<hr>

##### Problem Description:
1) When I send emails to my users the variable **{domain}** is valued at "http: //www.organizr.local/".
I would like to know where are these systems variables are configured?
2) Is it possible to modify the default HTTP port Iuse a Nginx server) ?

Thank you in advance,<hr>

##### Reproduction Steps:
2) Sent email to users : 
> Rendez-vous sur mon site Web et entrez le code pour rejoindre: http://www.organizr.local/
<hr>

**Comment by si0972** [comment]
Domain variable is gathered from the **first** server name in the nginx config. But you can use the `Domain Link Override` fienld under PHPMailer>Test and  Options.
To change the port, change the listen lines in the nginx config.

**Comment by causefx** [comment]
the above answer is correct.
