### ISSUE TITLE
[V2] 'Login with Plex' button function unclear to users

### ISSUE THREAD

**Issue by brickstool** [causefx/Organizr#985]
###### Operating System: Ubuntu
<hr>

##### Problem Description:
The 'Login with 'Plex' button is unclear to users who are not tech-savvy. I've had multiple users experience difficulties logging in as they did not know that they had to click the Plex icon underneath the username and password fields. Pictured is the button I am talking about:

![screenshot_20181123_154051](https://user-images.githubusercontent.com/4110173/48928760-3322ef00-ef36-11e8-8658-a8daf18ae79f.jpeg)

I think a solution to this would be to have an option to display either the Plex icon as it is currently, or to have the button replaced with different button which reads 'Login with Plex' in the style of the 'Login' button in the screenshot above.

<hr>

**Comment by causefx** [comment]
i’ve been playing around with this. i need to settle on a UI. it’ll be fixed soon

**Comment by brickstool** [comment]
Glad to hear it, thank you for your effort :)
