### ISSUE TITLE
[V2] Ombi request button on homepage showing for mobile but not desktop

### ISSUE THREAD

**Issue by ageisen2000** [causefx/Organizr#986]
###### Operating System: Docker (Ubuntu 18.04)
<hr>

##### Problem Description:

When on mobile I can see a search button for the ombi area on the homepage that allows me to request TV/Movies. When on the desktop page it doesn't display.
<hr>

##### Reproduction Steps:

In the newest docker container open the page on mobile with requests. It should display a search icon that you can click and request new shows. On desktop this button doesn't show up.
<hr>

#### Errors on screen?  If so paste here:

```

```

**Comment by ageisen2000** [comment]
![image](https://user-images.githubusercontent.com/8844888/48973606-94b38e00-f008-11e8-9633-cb0d06efb58b.png)
This is what I see on the desktop version and I see the below screenshot on mobile:
![image](https://user-images.githubusercontent.com/8844888/48973633-0e4b7c00-f009-11e8-870f-c48bbd4c903d.png)

**Comment by causefx** [comment]
logging into them the same? can you try without the plex theme

**Comment by ageisen2000** [comment]
I've tried with and without the plex theme. Same issue.

I also tried logging in with a non-admin account and still can't see it on desktop

**Comment by ageisen2000** [comment]
If it helps at all here is the HTML that was generated on desktop version, it seems that it didn't even render that button at all:

`<div class="panel-heading bg-info p-t-10 p-b-10">
			<span class="pull-left m-t-5"><img class="lazyload homepageImageTitle loaded" data-src="plugins/images/tabs/ombi.png" src="plugins/images/tabs/ombi.png" data-was-processed="true"> &nbsp; Requests</span>
			<div class="btn-group pull-right">
					
		<button type="button" class="btn btn-info waves-effect hidden-xs" onclick="owlChange('request-items','previous');"><i class="fa fa-chevron-left"></i></button>
		<button type="button" class="btn btn-info waves-effect hidden-xs" onclick="owlChange('request-items','next');"><i class="fa fa-chevron-right"></i></button>
		<button aria-expanded="false" data-toggle="dropdown" class="btn btn-info dropdown-toggle waves-effect waves-light" type="button">
			<i class="fa fa-filter m-r-5"></i><span class="caret"></span>
		</button>
		
		<div role="menu" class="dropdown-menu request-filter">
			<div class="checkbox checkbox-success m-l-20 checkbox-circle">
				<input id="request-filter-available" data-filter="request-available" class="filter-request-input" type="checkbox" checked="">
				<label for="request-filter-available"> <span lang="en">Available</span> </label>
			</div>
			<div class="checkbox checkbox-danger m-l-20 checkbox-circle">
				<input id="request-filter-unavailable" data-filter="request-unavailable" class="filter-request-input" type="checkbox" checked="">
				<label for="request-filter-unavailable"> <span lang="en">Unavailable</span> </label>
			</div>
			<div class="checkbox checkbox-info m-l-20 checkbox-circle">
				<input id="request-filter-approved" data-filter="request-approved" class="filter-request-input" type="checkbox" checked="">
				<label for="request-filter-approved"> <span lang="en">Approved</span> </label>
			</div>
			<div class="checkbox checkbox-warning m-l-20 checkbox-circle">
				<input id="request-filter-unapproved" data-filter="request-unapproved" class="filter-request-input" type="checkbox" checked="">
				<label for="request-filter-unapproved"> <span lang="en">Unapproved</span> </label>
			</div>
			<div class="checkbox checkbox-purple m-l-20 checkbox-circle">
				<input id="request-filter-denied" data-filter="request-denied" class="filter-request-input" type="checkbox" checked="">
				<label for="request-filter-denied"> <span lang="en">Denied</span> </label>
			</div>
			<div class="checkbox checkbox-inverse m-l-20 checkbox-circle">
				<input id="request-filter-movie" data-filter="request-movie" class="filter-request-input" type="checkbox" checked="">
				<label for="request-filter-movie"> <span lang="en">Movie</span> </label>
			</div>
			<div class="checkbox checkbox-inverse m-l-20 checkbox-circle">
				<input id="request-filter-tv" data-filter="request-tv" class="filter-request-input" type="checkbox" checked="">
				<label for="request-filter-tv"> <span lang="en">TV</span> </label>
			</div>
		</div>

		
			</div>
			<div class="clearfix"></div>
		</div>`

**Comment by ageisen2000** [comment]
Seems to have been an issue with Chrome Version 70.0.3538.102. 

Updating chrome fixed the issue

**Comment by Procuria** [comment]
Sorry to open this up again, but I ran into the same problem.
Tried Chrome, Firefox and even Opera but noch request button at all (standard and plex theme).

Are therre any other approaches ?

**Comment by causefx** [comment]
please post output of SSO from debug area in user menu.
