### ISSUE TITLE
[V2] [Request] Add tooltips next to headers in the tab editor screen

### ISSUE THREAD

**Issue by ageisen2000** [causefx/Organizr#987]
###### Operating System: Ubuntu Docker
<hr>

##### Problem Description:

I'm not sure what each of these options does, and I feel like it would be a better user experience if there was a tooltip or hover text to explain what they do:

Active,
Splash,
Ping,
Preload
<hr>

![image](https://user-images.githubusercontent.com/8844888/48973589-06d7a300-f008-11e8-87a9-8ddb07a13c37.png)

**Comment by causefx** [comment]
that makes sense. will add.

**Comment by ageisen2000** [comment]
Another one that might be nice to have would be some explanation of what "backend" authentication means.

**Comment by causefx** [comment]
this is done, in the coming days/weeks i will add more help info
