### ISSUE TITLE
Force Database upgrade

### ISSUE THREAD

**Issue by andyrav** [causefx/Organizr#99]
Hi just did a update and looks lihe the database didnt upgrade.
Is there a way to force it to upgrade?
Might be a nice feature to have the option to check database

cheers
Notice: Undefined variable: activetabBG in /var/www/html/Dashboard/settings.php on line 1727

Fatal error: Uncaught PDOException: SQLSTATE[HY000]: General error: 1 table options has no column named loading in /var/www/html/Dashboard/settings.php:562 Stack trace: #0 /var/www/html/Dashboard/settings.php(562): PDO->prepare('INSERT INTO opt...') #1 {main} thrown in /var/www/html/Dashboard/settings.php on line 562

**Comment by andyrav** [comment]
found the answer
run updatedb.php
cheers

**Comment by causefx** [comment]
yea after this update, it will auto update in the future.  the instructions were in the notes but they weren't very clear.
