### ISSUE TITLE
[V2] Splash screen not working since last update with docker plex tag

### ISSUE THREAD

**Issue by JoyDistelbrink** [causefx/Organizr#992]
###### Operating System: Ubuntu 18.04 Docker
<hr>

##### Problem Description:

Since last update of the docker image organizrtools/organizr-v2 with the "plex" tag  the splash screen doesn't work anymore
https://imgur.com/a/lvFl23r

Buttons are not working and need to push "escape" to close the splash screen
<hr>

Thanks

**Comment by causefx** [comment]
I changed the Splashscreen UI Slightly.  @burry wanna take a look at this?

**Comment by Burry** [comment]
Ah my bad, will work on updating for the new UI later today

**Comment by JoyDistelbrink** [comment]
Thanks guys !

**Comment by Burry** [comment]
[Fixed in 2.8.0](https://github.com/causefx/Organizr/pull/993)
