### ISSUE TITLE
[V2] Image uploader keeps spaces in filenames breaking links

### ISSUE THREAD

**Issue by firedomain** [causefx/Organizr#994]
###### Operating System: Docker/UNRAID
<hr>

##### Problem Description:
When uploading an image via the image manager, spaces in filenames seem to be kept, breaking links to the image when used.

<hr>

##### Reproduction Steps:
Name a wallpaper for example "color wallpaper.jpeg", then upload, copy the link & paste it in the customize login wallpaper field. When accessing the login page the default image appears instead of the custom. renaming the image without a space & repeating the steps resolves the problem.

<hr>

I assume the wanted behavior would be for the image manager to replace spaces (or invalid characters) with underscores to prevent this issue.

**Comment by causefx** [comment]
i will test this today
