### ISSUE TITLE
[V2] fails to update in endless loop

### ISSUE THREAD

**Issue by hagabla** [causefx/Organizr#995]
###### Operating System: Debian 9
<hr>

##### Problem Description:
updating via the UI does not update and wants to  udate again after restart
<hr>

##### Reproduction Steps:
Settings-> updates -> hit the update button to update to beta.800
after reaching 100% organizr restarts and wnats to update again.

<hr>

#### Errors on screen?  If so paste here:

```

```

**Comment by causefx** [comment]
I'm sorry for not seeing this earlier, is this still the case?

**Comment by hagabla** [comment]
I fixed it somehow, I don't remember how though.

**Comment by causefx** [comment]
Thank you for the response.  Again, i'm sorry I missed this.
