### ISSUE TITLE
[V2] Icon Packs in the Marketplace: Blackberry Themes Icons

### ISSUE THREAD

**Issue by Archmonger** [causefx/Organizr#999]
##### Description:
Within the Blackberry Themes repository, I have made custom like icons designed for use within Organizr.

Currently have 109 icons in 12 different themes. Would be great to see these integrated directly into Organizr through the marketplace.

As another thought, the icon selection menu could simply provide the user a copy button to the icon's GitHub pages link, which they can then put into their tab editor.

Sample github pages links
[https://archmonger.github.io/Blackberry-Themes/Themes/Blackberry-Royal/Icons/tautulli.png](https://archmonger.github.io/Blackberry-Themes/Themes/Blackberry-Royal/Icons/tautulli.png)
[https://archmonger.github.io/Blackberry-Themes/Themes/Blackberry-Flat/Icons/ombi.png](https://archmonger.github.io/Blackberry-Themes/Themes/Blackberry-Flat/Icons/ombi.png)

**Comment by Archmonger** [comment]
Updated this ticket to reflect the change from Blackberry Flat to Blackberry Themes

**Comment by Archmonger** [comment]
Bumping because there's a metric shit ton of icons within blackberry themes that Organizr users would love to have on hand.

**Comment by causefx** [comment]
Yeah - I'm thinking of ways to implement this.... just not sure how atm

**Comment by Archmonger** [comment]
I found this npm library that might help.

https://github.com/fregante/list-github-dir-content

I was thinking maybe use that library, then filter files that contain the string "/icons/" within their folder path?

**Comment by causefx** [comment]
yeah that wasn't the issue. i'm trying to figure out how to do the ui. i need to think of a clean way to give it to user

**Comment by causefx** [comment]
completed in master now.
